### ISSUE TITLE
az webapp list-runtimes --linux error

### ISSUE THREAD

**Issue by shaiamir** [Azure/azure-cli#15488] opened 2020-10-12 08:18 UTC
## Describe the bug

**Command Name**
`az webapp list-runtimes`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list-runtimes --linux`

## Environment Summary
```
Linux-5.4.0-48-generic-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment] 2020-10-12 12:06
hi @shaiamir  could you pls try uninstall 2.0.81 and install latest Azure CLI? this is a known issue in Focal azure CLI package, tracked in #14011

**Comment by fengzhou-msft** [comment] 2020-11-02 07:51
Duplicate of #14011

**Closed by fengzhou-msft** 2020-11-02 07:51 UTC
Labels: Packaging
