### ISSUE TITLE
az network watcher flow-log configure requires optional new parameter

### ISSUE THREAD

**Issue by codyrat** [Azure/azure-cli#8757] opened 2019-03-11 20:00 UTC
**Describe the bug**
az network watcher flow-log configure on azure-cli =>2.0.57 requires --traffic-analytics and --workspace id set

**To Reproduce**
az network watcher flow-log configure \
       --retention 5 \
       --enabled true \
       --format JSON \
       --log-version 2 \
       --resource-group ResourceGroup  \
       --storage-account storageAccountId \
       --nsg NSGName 

Parameter 'TrafficAnalyticsConfigurationProperties.workspace_region' can not be None.
Traceback (most recent call last):
  File "/home/midupuis/lib/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/midupuis/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
ValidationError: Parameter 'TrafficAnalyticsConfigurationProperties.workspace_region' can not be None.

**Expected behavior**
Above command works as expected in azure-cli 2.0.56.
--traffic-analytics or --workspace are optional parameters introduced in 2.0.57 are causing conflict with mandatory options

**Environment summary**
azure-cli 2.0.57 or greater

**Additional context**
Workaround pinning azure-cli version to 2.0.56 or lower.

**Comment by tjprescott** [comment] 2019-03-11 21:31
I am not able to repro your issue using the command you gave. Please provide the output of `az --version`.

**Comment by tjprescott** [comment] 2019-03-21 17:53
Closing as I am not able to reproduce this. If you have additional data you can provide, feel free to reopen.

**Closed by tjprescott** 2019-03-21 17:53 UTC
Labels: Network-cli
