### ISSUE TITLE
az storage container generate-sas error: self.account_key should not be None.

### ISSUE THREAD

**Issue by MaurGi** [Azure/azure-cli#13632] opened 2020-05-22 17:11 UTC
## Describe the bug

**Command Name**
`az storage container generate-sas`

**Errors:**
```
self.account_key should not be None.
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
storage/v2018_11_09/blob/baseblobservice.py, ln 421, in generate_container_shared_access_signature
    _validate_not_none('self.account_key', self.account_key)
storage/v2018_11_09/common/_error.py, ln 130, in _validate_not_none
    raise ValueError(_ERROR_VALUE_NONE.format(param_name))
ValueError: self.account_key should not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

I get an error with: 
- `az storage container generate-sas --subscription {} --account-name {} --name {} --permissions=r --start 2020-05-22T15:45Z --expiry 2020-05-22T17:45Z --auth-mode login -o tsv`

if I remove the '--auth-mode login' I don't get the error, but I get the reccomendation to use it!

```
> az storage container generate-sas --subscription {} --account-name {}--name {} --permissions=r --start 2020-05-22T15:45Z --expiry 2020-05-22T17:45Z -o tsv
No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account.
```

## Expected Behavior

Either support `--auth-mode login` or do not recommend to use it.
Also, manage this error and provide a clear information to the api consumer rather than a runtime error.

## Environment Summary
```
Linux-4.19.84-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.6.0

Extensions:
azure-devops 0.13.0

```

**Comment by yonzhan** [comment] 2020-05-22 22:31
add to S171

**Comment by Juliehzl** [comment] 2020-06-11 06:20
dupe of #13012

**Closed** 2020-06-20 00:14 UTC
Labels: OKR3.2 Candidate, Storage, feature-request
