### ISSUE TITLE
azure-cli crash when redirecting output

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#13413] opened 2020-05-09 03:03 UTC
**azure-cli** crash when redirecting output to some commands:
```
$ az --version | head -1
azure-cli                          2.5.1
The command failed with an unexpected error. Here is the traceback:

[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 207, in invoke
    self.show_version()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 108, in show_version
    print(ver_string)
  File "/opt/az/lib/python3.6/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/opt/az/lib/python3.6/site-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/opt/az/lib/python3.6/site-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/opt/az/lib/python3.6/site-packages/colorama/ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
BrokenPipeError: [Errno 32] Broken pipe

To open an issue, please run: 'az feedback'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

$ cat /etc/os-release | head  -1
NAME="Ubuntu"

$ az --version | tail -1
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

```
Same issue has already been reported previously in https://github.com/Azure/azure-cli/issues/58 and https://github.com/Azure/azure-cli/issues/770, those  are now closed but still seeing the issue.

## Environment
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1
```

**Comment by yonzhan** [comment] 2020-05-09 03:43
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment] 2020-05-09 09:36
The issue is caused by the colorama code for survey link. 
You can turn off the link with `export AZURE_OUTPUT_SHOW_SURVEY_LINK=False` or disable the color for all command output with `export AZURE_CORE_NO_COLOR=True`.

For the purpose of parsing Azure CLI version, we recommend `az version`, the output is a simple json.

**Comment by fengzhou-msft** [comment] 2020-05-12 06:37
@jiasli anything we can do in kanck or core to catch the BrokenPipeError?

**Comment by jiasli** [comment] 2020-05-13 12:56
We shouldn't enable color if `stdout` is not a TTY. Fixed it in Knack.

**Comment by johanburati** [comment] 2021-01-08 01:04
Still crashing to this day, any plan to fix this ?

```
johan@Azure:~$ az --version | head
azure-cli                         2.16.0 *

You have 2 updates available. They will be updated with the next build of Cloud Shell.
core                              2.16.0 *
telemetry                          1.0.6

Extensions:
webapp                            0.2.20
vm-repair                          0.1.2
azure-devops                      0.18.0
kusto                              0.2.0
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 207, in invoke
    self.show_version()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 115, in show_version
    print(UX_SURVEY_PROMPT_COLOR if self.enable_color else UX_SURVEY_PROMPT)
  File "/opt/az/lib/python3.6/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/opt/az/lib/python3.6/site-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/opt/az/lib/python3.6/site-packages/colorama/ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "/opt/az/lib/python3.6/site-packages/colorama/ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
BrokenPipeError: [Errno 32] Broken pipe
To open an issue, please run: 'az feedback'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by jiasli** [comment] 2021-01-08 03:58
This issue will be fixed in the next release. Please see my comment at https://github.com/Azure/azure-cli/issues/13979#issuecomment-754305006.

**Closed** 2021-01-20 03:04 UTC
Labels: OKR3.4 Candidate, Packaging

**Comment by johanburati** [comment] 2021-01-21 00:48
Thanks !

```
$ az --version | head -1
azure-cli                         2.18.0
$
```

**Comment by jiasli** [comment] 2021-03-11 13:26
I re-thought about this issue today and it is actually a colorama bug with `head` command (linked above 👆). 

Anyway, we no longer init colorama if `stdout` is not a TTY, so we are good.
