### ISSUE TITLE
Az afd rule create error

### ISSUE THREAD

**Issue by LotteVoorhorst** [Azure/azure-cli#21938] opened 2022-04-05 13:55 UTC
## Describe the bug

Error occurs when choosing 'OriginOverride' as the action-name. 

**Command Name**
`az afd rule create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'cli_ctx'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/cdn/custom/custom_afdx.py", line 556, in create_afd_rule
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/cdn/custom/custom.py", line 354, in create_action
AttributeError: 'NoneType' object has no attribute 'cli_ctx'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az afd rule create --action-name {} --order {} --profile-name {} --resource-group {} --rule-name {} --rule-set-name {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
front-door 1.0.16

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-04-05 14:05
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-04-06 05:05
@LotteVoorhorst Thank you for reaching out to us, we are looking into it.

**Comment by t-bzhan** [comment] 2022-04-07 03:24
Hi @RakeshMohanMSFT and @RakeshMohanMSFT , the action "OriginGroupOverride" is deprecated in the latest release and you should use "[RouteConfigurationOverride](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-rules-engine-actions?tabs=portal&pivots=front-door-standard-premium#properties)" instead. 

The command grammar is like:
`az afd rule create --action-name RouteConfigurationOverride --order 1 --profile-name p-bugbash101 --resource-group bogroup --rule-name rule2204071 --rule-set-name rs0407 `

However this is a defect in the latest CLI release (2.0.35) which prevents the above command from executing successfully, we will fix the issue in next release. 

As a workaround, you could use below commands to achieve the same effects with the latest CLI release (2.0.35):
```
az afd rule create --action-name ModifyResponseHeader --profile-name p-bugbash101 --resource-group bogroup --rule-name rule2204071 --rule-set-name rs0407 --header-action Delete --header-name dummy --order 1

az afd rule action add --action-name RouteConfigurationOverride --profile-name p-bugbash101 --resource-group bogroup --rule-name rule2204071 --rule-set-name rs0407 --origin-group og0407 --forwarding-protocol HttpOnly

az afd rule action remove --index 0 --profile-name p-bugbash101 --resource-group bogroup --rule-name rule2204071 --rule-set-name rs0407
```

That is what you will observe in the portal:
![image](https://user-images.githubusercontent.com/61817681/162113990-efb0be3b-e47e-4b97-8f67-3529894e862a.png)

**Comment by RakeshMohanMSFT** [comment] 2022-04-07 03:57
@LotteVoorhorst do check the work around provided by @t-bzhan until the issue is fixed in next Release

**Comment by LotteVoorhorst** [comment] 2022-04-07 07:06
@t-bzhan @RakeshMohanMSFT  Thanks for the explanation and the workaround! Greatly appreciated!

**Closed** 2022-04-11 02:10 UTC
Labels: Network, Network - CDN, customer-reported, Network - Front Door, needs-team-attention, CXP Attention, Auto-Assign
