### ISSUE TITLE
Unable to create acs in westeurope, --master-vm-size parameter not working

### ISSUE THREAD

**Issue by kbiernat** [Azure/azure-cli#4716] opened 2017-10-19 07:50 UTC
When trying to create an ACS in West Europe location, I get this message:
"The VM Size of Master is not allowed in your subscription in location 'westeurope'. Master VM Size 'Standard_D2' is available in locations: ...."

Adding --master-vm-size=Standard_A2 to az parameters does not help, it still tries to create with Standard_D2. I know that smaller VMs are not recommended, but this is for testing.

A workaround is creating this in northeurope, but it still creates a Standard_D2 master node.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
azure-cli installed with apt-get

$ az --version
azure-cli (2.0.19)

acr (2.0.13)
acs (2.0.17)
appservice (0.1.18)
backup (1.0.1)
batch (3.1.5)
batchai (0.1.1)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.18)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.15)
eventgrid (0.1.4)
extension (0.0.4)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.12)
lab (0.0.11)
monitor (0.0.10)
network (2.0.16)
nspkg (3.0.1)
profile (2.0.14)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.16)
role (2.0.13)
servicefabric (0.0.4)
sql (2.0.13)
storage (2.0.17)
vm (2.0.16)

Python location '/opt/az/bin/python3'
Extensions directory '/home/user/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Oct  9 2017, 22:55:40) 
[GCC 4.8.4]

OS: Ubuntu 14.04
Shell: Bash
```

**Comment by rjtsdl** [comment] 2017-10-24 18:25
--master-vm-size is feature in preview, it only works in preview regions. WestEurope is NOT!
Those are clearly stated in the `--master-vm-size` description.

@tjprescott Please close this, as it is by design.

**Comment by yugangw-msft** [comment] 2019-07-27 00:54
closing as `az acs` is deprecating

**Closed by yugangw-msft** 2019-07-27 00:54 UTC
Labels: ACS, Service Attention
