### ISSUE TITLE
az iot dps delete: The full name required for the Hub

### ISSUE THREAD

**Issue by djaus2** [Azure/azure-cli#12884] opened 2020-04-06 12:59 UTC
In most az cli commands, the IoT Hub name _(a single word)_  without a path is what required. For this command, the full 'path' for the name is required.    
**.azure-devices.net** needs to attached to the hub name.
This need to be made clear.

**_OR IS IT A BUG IN THE API?_**

---
#### Document Details

The given syntax for the command is
```
az iot dps delete [--ids]
                  [--name]
                  [--only-show-errors]
                  [--resource-group]
                  [--subscription]
```
The example given is:
```
az iot dps delete --name MyDps  --resource-group MyResourceGroup
```
The name needs to be **MyDPs.azure-devices.net**
```
az iot dps delete --name MyDPs.azure-devices.net  --resource-group MyResourceGroup
```

NB There might be other DPS commands with this issue??

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb078bf-8f6c-a3f6-d157-3ecf9d94f7e2
* Version Independent ID: a5e7ccb7-7593-4c0c-bc95-66c8216ed35f
* Content: [az iot dps](https://docs.microsoft.com/en-us/cli/azure/iot/dps?view=azure-cli-latest#az-iot-dps-delete)
* Content Source: [src/azure-cli/azure/cli/command_modules/iot/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/iot/_help.py)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-04-06 23:30
iot

**Comment by jlian** [comment] 2020-04-06 23:52
@digimaun and @iluican thoughts?

**Comment by vilit1** [comment] 2021-12-08 22:38
I cannot reproduce the error here - I can delete a dps instance by only giving it the name (without the azure-devices-provisioning.net). Can you update your azure-iot extension and let me know if the error still shows up?

**Comment by vilit1** [comment] 2024-05-13 16:58
Closing since there are no recent updates. Feel free to reopen if you have any other issues

**Closed by vilit1** 2024-05-13 16:58 UTC
Labels: Service Attention, customer-reported, IoTDPS
