### ISSUE TITLE
az group delete not working

### ISSUE THREAD

**Issue by sudlo** [Azure/azure-cli#12592] opened 2020-03-15 05:42 UTC
## Describe the bug

**Command Name**
`az group delete`

**Errors:**
```
az group delete: error: the following arguments are required: --name/-n/--resource-group/-g
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group delete {}`

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0

```

**Comment by yungezz** [comment] 2020-03-15 07:14
hi @Juliehzl could you pls look at it?thanks.

**Comment by yonzhan** [comment] 2020-03-15 09:40
add to S167

**Comment by zhoxing-ms** [comment] 2020-03-16 07:23
@sudlo Because the name of the resource group must be specified when deleting the resource group, so the parameter `--name/-n/--resource-group/-g` must be passed in. 
Do you have any questions about this?

**Comment by sudlo** [comment] 2020-03-17 13:48
@zhoxing-ms  thanks for your response.. 
for example i am using the following command 
az group delete --name linux

**Comment by zhoxing-ms** [comment] 2020-03-18 08:40
@sudlo I can't reproduce your question. Could you please add `--debug` to the original command? And then please show me the information returned, thanks~

**Comment by yonzhan** [comment] 2020-03-28 02:57
@sudlo any update?

**Comment by zhoxing-ms** [comment] 2020-04-07 02:05
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-04-07 02:05 UTC
Labels: ARM
