### ISSUE TITLE
Bastion Host Creation Failed Error "GatewayAllocationFailed" "Compute allocation failed. Please retry later"

### ISSUE THREAD

**Issue by byteknacker** [Azure/azure-cli#21678] opened 2022-03-17 08:09 UTC
**Description**
When creating a Bastion host in West Europe with allowed parameters for the Subnet with Terraform it fails with this error:

Error: waiting for creation/update of Bastion Host: (Name "bh-example" / Resource Group "example-rg"): Code="GatewayAllocationFailed" Message="Compute allocation failed. Please retry later.

When creating a Bastion host in West Europe with allowed parameters for the Subnet using the Portal and doing so manually it fails with this error: 

InternalServerError
Conflict

The Bastion host will be created but the provisioning state fails almost all the time. But sometimes, it succeeds. 

**To Reproduce**
Simply create a Bastion Host with allowed parameters in West Europe a couple of times. Maybe you can reproduce this error. For me it happened since 15.03.2022 and ever since then, I get this error. 

**Expected behavior**
I expect that Bastion host will be created and provisioned successfully using both the Portal and Terraform.

**Environment summary**
Either Terraform in Gitlab pipeline or Portal

**Additional context**
I researched a bit and found that most likely, this is due to internal Azure problems with resource allocation in the bare metal or VM clusters where the Bastion host should be set up. Since the provisioning is failing, I expect this to be more of a network throttle issue but cannot be sure. Can someone at Azure please check this internally.

**Comment by yonzhan** [comment] 2022-03-17 08:41
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2022-03-18 18:28
@byteknacker Are your trying to use the CLI commands as mentioned in the [documentation](https://docs.microsoft.com/en-us/azure/bastion/create-host-cli#createhost) ?
![image](https://user-images.githubusercontent.com/38112130/159062047-baf354d9-ac5f-4ed6-b25c-78495925664b.png)

**Comment by SaurabhSharma-MSFT** [comment] 2022-03-29 22:53
@byteknacker We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-03-29 22:53 UTC
Labels: Network, customer-reported, needs-author-feedback, no-recent-activity, Network - Bastion, CXP Attention, Auto-Assign

**Comment by paolosalvatori** [comment] 2022-05-10 13:02
Hi all

I'm experiecing the same issue deploying Azure Bastion to West Europe using Bicep. The Bastion Hots gets created in a failed state with the following error message:

The resource operation completed with terminal provisioning state 'Failed'. GatewayAllocationFailed. Compute allocation failed. Please retry later.

Here is my bicep code which looks correct to me:

```bicep
resource bastionPublicIpAddress 'Microsoft.Network/publicIPAddresses@2021-08-01' = {
  name: bastionPublicIpAddressName
  location: location
  tags: tags
  sku: {
    name: 'Standard'
  }
  properties: {
    publicIPAllocationMethod: 'Static'
  }
}

resource bastionHost 'Microsoft.Network/bastionHosts@2021-08-01' = {
  name: bastionHostName
  location: location
  tags: tags
  properties: {
    disableCopyPaste: bastionHostDisableCopyPaste
    enableFileCopy: bastionHostEnableFileCopy
    enableIpConnect: bastionHostEnableIpConnect
    enableShareableLink: bastionHostEnableShareableLink
    enableTunneling: bastionHostEnableTunneling
    ipConfigurations: [
      {
        name: 'IpConf'
        properties: {
          subnet: {
            id: '${vnet.id}/subnets/${bastionSubnetName}'
          }
          publicIPAddress: {
            id: bastionPublicIpAddress.id
          }
        }
      }
    ]
  }
}
```

Thoughts?

**Comment by torivara** [comment] 2022-05-11 08:55
I am seeing the same, but this is a closed issue. Maybe someone can create a new issue if this problem has resurfaced, @paolosalvatori ?

**Comment by asos-callumdaw** [comment] 2022-05-11 09:52
> @torivara I think the issue is due to some capacity issues within a specific region. I tried to deploy to another region and the same Bicep code worked without any issue.

Are you seeing this in west europe? Seem to be having lots of troubles at the moment, north europe worked ok for me

**Comment by paolosalvatori** [comment] 2022-05-11 09:55
> > @torivara I think the issue is due to some capacity issues within a specific region. I tried to deploy to another region and the same Bicep code worked without any issue.
> 
> Are you seeing this in West Europe? Seem to be having lots of troubles at the moment, north Europe worked ok for me

Yes, I had issues in West Europe, North Europe, and France Central. It worked for example in Switzerland North. I'm just testing a Bicep, so any region is fine now.

**Comment by torivara** [comment] 2022-05-11 10:06
> > @torivara I think the issue is due to some capacity issues within a specific region. I tried to deploy to another region and the same Bicep code worked without any issue.
> 
> Are you seeing this in west europe? Seem to be having lots of troubles at the moment, north europe worked ok for me

I experienced this in West Europe.

**Comment by jdevillard** [comment] 2022-05-11 10:07
same for me in West Europe using Portal.

**Comment by prateek-narula** [comment] 2022-05-11 14:12
We are planning to write one, but the issue is we do not have a definite pattern to identify what actually caused it. As Ii said it occurs and gets resolved after few hours and it is always like this. So I had been facing it from last 5 hours and now the issue no longer persist. Right now I'm collecting more information about the instances of when it occurs.

**Comment by lbergnehr** [comment] 2022-05-12 08:42
We're trying to create azure bastion in west europe in our CI system regularly, and about 1 in 10 works. Very often it's the issue reported here.

**Comment by TahaBenseddik** [comment] 2022-05-12 12:48
I have the same issue for western europe region: 
terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"GatewayAllocationFailed\",\"message\":\"Compute allocation failed. Please retry later.\",\"details\":[]}]}}",

**Comment by artouolevi** [comment] 2022-05-12 13:41
One additional comment about Azure Bastion deployment failure. Same fail code: _GatewayAllocationFailed_ when trying to create Azure bastion to West europe region. Tested several times with: bicep template, ARM template and portal deployment. All fails. Bastion deployments to North Europe and France Central regions works and Azure VMs are accessible via those.

Even this thread is closed, hopefully these comments will raise visibility to this issue.

**Comment by scottpendlebury** [comment] 2022-05-13 10:05
I also have this same issue for West Europe

![image](https://user-images.githubusercontent.com/2189228/168261640-ba1af1bb-a732-4a49-a581-dc4178f3096c.png)

**Comment by daniell0o** [comment] 2022-05-13 10:17
I have the exact same issue using terraform
<img width="958" alt="azurebastionerror" src="https://user-images.githubusercontent.com/102770757/168263700-88a2b544-88d2-4426-a15d-cfe0036c5d05.png">

**Comment by leom-restack** [comment] 2022-05-17 14:32
Hello, I think this issue needs to be reopened. Im getting similar issue using Powershell Module, Azure Cli and Terraform using the WestEurope region. See below samples.

*Terraform*: 
```
╷
│ Error: waiting for creation/update of Bastion Host: (Name "bastion-test-01" / Resource Group "rg-test-01"): Code="GatewayAllocationFailed" Message="Compute allocation failed. Please retry later." Details=[]
│ 
```

*Azure cli*:
```
PS C:\Users\devBox005> az network bastion create --name "Bastion-Test" --public-ip-address "Bastion-Test-pip" --resource-group "rg-test-01" --vnet-name "vnet-test-01" --location "westeurope"
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InternalServerError) An error occurred.
Code: InternalServerError
Message: An error occurred.
```

*Powershell module*:
```
PS C:\Users\devBox007> New-AzBastion -ResourceGroupName "rg-test-01" -Name "Bastion-Test-01" `
>>    -PublicIpAddressRgName "rg-test-01" -PublicIpAddressName "Bastion-Test-pip" `
>>    -VirtualNetworkRgName "rg-test-01" -VirtualNetworkName "vnet-test-01" `
>>    -Sku "Standard"
New-AzBastion: Long running operation failed with status 'Failed'. Additional Info:'An error occurred.'
StatusCode: 200
ReasonPhrase: OK
Status: Failed
ErrorCode: InternalServerError
ErrorMessage: An error occurred.
PS C:\Users\devBox007>
```

What I don't understand is why it keeps the resources even if its in a failed state. See below:

*Sample on the Azure portal*: 
![image](https://user-images.githubusercontent.com/93972728/168835955-d9108bca-4500-4e9c-9720-a7cca746446b.png)

**Comment by byteknacker** [comment] 2022-05-25 07:41
This issue needs to be reopened. I just did a clean terraform apply after deleting my previous infra. A related error occurred. I am using Terraform 1.1.6:

Error: waiting for creation/update of Bastion Host: (Name "bastion-host-name" / Resource Group "rg-name"): Code="InternalServerError" Message="An error occurred." Details=[]

When upgrading from Terraform azurerm 2.98 to 3.6.0 where there have some breaking changes in the Azure provider for Terraform, Bastion Host cannot be created upon terraform apply. Error in the console of Gitlab CI/CD pipeline: InternalServerError without details.

 Versions of my tools:
 
Job runs in Gitlab runner on a VM hosted on Azure with a custom Docker image with tools for azure cli and Terraform binary
Terraform binary: 1.1.6
Azurerm: 3.6.0
Azure CLI: 2.30.0

Error Output Screenshots:

![Screenshot 2022-05-25 at 09 11 17](https://user-images.githubusercontent.com/10653912/170207825-0dee28ba-e92e-48b2-9bcd-f97815aec572.png)
![Screenshot 2022-05-25 at 09 37 41](https://user-images.githubusercontent.com/10653912/170207834-ac6db481-6f5d-4fe9-9561-78b1e49fd838.png)
 
I suspect that this is a platform error on the side of Azure. This looks like a low capacity issue. Due to the long time to spin up a Bastion Host, I also suspect that the underlying infrastructure is very heavy. Would be great to make it containerised and much faster in creation and deletion. Can you please relay that to the Azure development or SRE team? This is a major bottleneck for me as it prevents ssh and kubectl access to my private AKS. The only way we can get in there as an admin is via Bastion Host.
 
Also, I suggest that the Azure dev team implements a scale to zero feature for Bastion Host. It is an expensive service to run continuously, especially when not needed. I am ok paying more per unit time of usage but having the ability to toggle Bastion Host on and off automatically based on usage. For example, only when I am using Bastion Host, is it running. If I log out, after 10 minutes it shuts down to nothing. If I log in again, it spins it up on the fly and takes a minute or so before it is ready for usage. The shorter it takes for the ephemeral spin up, the better. If you charge more per unit time of using your unit economics will increase massively since more people are going to use it and it is more profitable per time period.

I also raised a technical ticket, let us see what I get as an answer. I hope this gets prioritised as it is a very crucial security feature for many enterprise clients.

**Comment by pchettri3** [comment] 2022-06-14 21:32
same error in eastus

**Comment by WaitingForGuacamole** [comment] 2022-06-15 12:03
Exact same error in East US. I've torn it down and reapplied my Terraform three times now. This is a capacity issue, IMO.

**Comment by byteknacker** [comment] 2022-07-06 09:18
Yes, I agree it must be a platform issue. I just had to stop using it and instead use VPN Gateway/Tunnel and a ssh password or key.

**Comment by Rainier-MSFT** [comment] 2023-04-03 12:06
Same issue here, deploying into UK South. Can this be re-opened folks?
