### ISSUE TITLE
az login errors: ValueError: Unable to get authority configuration for https//login.microsoftonline.com/organizations.

### ISSUE THREAD

**Issue by cek012** [Azure/azure-cli#27020] opened 2023-07-27 09:24 UTC
### Describe the bug

I am Using pyapacheatlas to bulk upload the Excel. I use AzureCliCredential() to get arthority from Azure. Then I use "az login" and what to login. I got the ERROR message as below.

![キャプチャ0727](https://github.com/Azure/azure-cli/assets/24391302/8718d148-5d70-403f-8f87-dc5431869913)

### Related command

az login

### Errors

ValueError: Unable to get authority configuration for https//login.microsoftonline.com/organizations.

### Issue script & Debug output

![キャプチャ0727](https://github.com/Azure/azure-cli/assets/24391302/59cbf9b2-d57b-47a8-8f3b-389e061dbc45)

### Expected behavior

pass the console

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0

**Comment by yonzhan** [comment] 2023-07-27 09:25
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2023-07-31 08:20
Duplicate of #20507

**Closed by bebound** 2023-07-31 08:20 UTC
Labels: bug, Account, customer-reported, Auto-Assign, Azure CLI Team, Auto-Resolve
