### ISSUE TITLE
"az ad app permission admin-consent --id " is not running with python error out

### ISSUE THREAD

**Issue by jkl2554** [Azure/azure-cli#14065] opened 2020-06-23 04:24 UTC
## Describe the bug

**Command Name**
`az ad app permission admin-consent`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad app permission admin-consent --id {}`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

Extensions:
aks-preview 0.4.43

```
## Additional Context
it runs with administrator

**Comment by yungezz** [comment] 2020-06-23 05:25
hi @jkl2554 where did you meet the error? Is it from CloudShell? If yes, this is a known Cloudshell issue #11749.

**Comment by yungezz** [comment] 2020-08-03 14:52
known issue in #11749 in Cloudshell. hi @jkl2554 could you pls run `az login` to workaround? thanks

**Comment by maertendMSFT** [comment] 2020-09-30 23:14
Can we close this as a dupe of https://github.com/Azure/azure-cli/issues/11749 ?

**Closed** 2020-10-01 09:06 UTC
Labels: Cloud Shell, Service Attention, customer-reported
