### ISSUE TITLE
failure to enable addons

### ISSUE THREAD

**Issue by anshprat** [Azure/azure-cli#11897] opened 2020-01-18 21:00 UTC
## Describe the bug

**Command Name**
`az aks enable-addons`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.8/site-packages/six.py, ln 696, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cli/command_modules/acs/custom.py, ln 1844, in aks_enable_addons
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles['omsagent'])
cli/command_modules/acs/custom.py, ln 2487, in _ensure_container_insights_for_monitoring
    if 'loganalyticsworkspaceresourceid' in addon.config:
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons {} --resource-group {} --name {}`

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.79 *

```

**Comment by jluk** [comment] 2020-01-21 17:05
This is duplicate of #11456 - please route comments there to keep these consolidated.

**Comment by jluk** [comment] 2020-02-21 01:18
A fix has been made, please reference this issue for the latest tracking. I am going to close this to consolidate info to one thread.

https://github.com/Azure/azure-cli/issues/11456

**Closed by jluk** 2020-02-21 01:18 UTC
Labels: AKS, Service Attention
