### ISSUE TITLE
WebApp:`az webapp` defaulting to production slot without any kind of confirmation is unacceptably dangerous

### ISSUE THREAD

**Issue by saevarb** [Azure/azure-cli#20117] opened 2021-10-30 11:03 UTC
**Describe the bug**
Running any command under `az webapp` *defaults to the production slot*, and almost none of the commands ever ask for any kind of confirmation. Slipped up and forgot to type `-s dev`? You just stopped the production system. 

**Expected behavior**
The expected behavior is that your command line utility doesn't automatically default to running potentially destructive actions against the production system. How on earth did this get through QA and testing?????

**Comment by yonzhan** [comment] 2021-10-30 14:03
route to service team

**Comment by panchagnula** [comment] 2021-11-01 17:25
@saevarb is there is a specific command you are referring to her - where you slipped to add -s? This doesn't seem to be specific to CLI but an explicit 'possible destructive action' taken with a specific API? so we can ensure we add some warning / explicit action to confirm.
All the webapp commands have -s as optional parameter & this has been this way for a long time after going through PR & testing & this is the first time we are hearing this feedback. Please share the explicit command & we can take a further look. From App service end 'Production' is always the default & has the same behavior if an API is used or using ARM (not just CLI). Thanks!

**Comment by saevarb** [comment] 2021-11-01 18:06
@panchagnula Well, I realize now that there is no reason for me to use the default slot as the production slot.

But regardless, both the documentation and the azure web UI call the default slot the "production slot", so that is indeed what I ended up using it as.

This then in turn means that *any* command I run under `az webapp` must have its slot explicitly set or otherwise I am targeting the production system, which is obviously a problem, because I could stop or restart or deploy a dev build or misconfigure the production system.

I guess my issue is with the defaults suggested by azure, namely that you use the default slot as the production slot, combined with the fact that the azure CLI defaults to using this slot for all its actions. Some argument could be made that this could be prevented via permissions, and I agree, but that doesn't make these defaults any less bad.

**Comment by navba-MSFT** [comment] 2022-05-17 10:29
@saevarb Could you please check if the parameter `--target-slot` helps ? More Info [here](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/slot?view=azure-cli-latest#az-webapp-deployment-slot-list). Awaiting your reply

>--target-slot
Target slot to swap, default to 'production'.

**Comment by saevarb** [comment] 2022-05-17 10:43
@navba-MSFT 

I'm sort of confused why you would think that this flag would help, since I never talked about swapping slots specifically. Also, what you posted is actually a perfect description of the problem that I originally posted about, since it tells me that if I want to swap slots which aren't the production slots, I have to be careful to specify the target slot, otherwise it will mess up production. These defaults are nuts.

**Comment by navba-MSFT** [comment] 2022-05-17 10:45
@saevarb Thanks for clarifying and sharing the feedback. The Service Team is already added to this github thread to look into this ask.

**Comment by seligj95** [comment] 2023-07-05 15:25
Thank you for the feedback. This is by design for our commands. We will keep this on our radar but haven't received this feedback from other customers. If that changes, we will reconsider. Closing for now.

**Closed by seligj95** 2023-07-05 15:25 UTC
Labels: Web Apps, Service Attention, customer-reported, needs-team-attention, feature-request, app-service-webapp-up
