### ISSUE TITLE
az storage blob copy start-batch returns an error after waiting for some time

### ISSUE THREAD

**Issue by markdebruijne** [Azure/azure-cli#11419] opened 2019-11-27 20:42 UTC
## az storage blob copy start-batch returns an error after waiting for some time
I wanted to copy an amount of blobs across storage accounts. So to find the right commandarguments values, I added the `--dryrun` switch and a `--pattern` argument to validate it will work. 
Unfortunately after some time (>30s - 180s or something) I received the errors below. Maybe a timeout or something?

**Command Name**
`az storage blob copy start-batch`

**Errors:**
```
('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 297, in recv_into
pip-install-6e754znd\pyOpenSSL\OpenSSL\SSL.py, ln 1822, in recv_into
pip-install-6e754znd\pyOpenSSL\OpenSSL\SSL.py, ln 1622, in _raise_ssl_error
OpenSSL.SSL.WantReadError

...

storage\v2018_11_09\common\storageclient.py, ln 430, in _perform_request
storage\v2018_11_09\common\storageclient.py, ln 361, in _perform_request
azure.common.AzureException: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob copy start-batch --account-name {} --destination-container {} --source-account-name {} --source-account-key {} --source-container {} --dryrun --pattern {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.74 *

Extensions:
azure-devops 0.12.0

```
## Additional Context
Might be related to this issue as lack of performance with this command is being reported: https://github.com/Azure/azure-cli/issues/10924

**Comment by haroldrandom** [comment] 2019-11-28 01:45
@Juliehzl Please take a look here

**Comment by Juliehzl** [comment] 2019-11-28 08:20
dupe of #11043

**Comment by Juliehzl** [comment] 2019-11-28 08:20
Add @jsntcy

**Comment by Juliehzl** [comment] 2019-12-02 01:39
dupe of #11043,#9890
Hi @markdebruijne, it should be network issue. Could you please try again with good Network? 
I will close this issue now and if you still have problems, feel free to reopen it or create a new issue😊

**Closed by Juliehzl** 2019-12-02 01:39 UTC
Labels: Storage
