### ISSUE TITLE
az cdn endpoint purge: How to set multiple path?

### ISSUE THREAD

**Issue by rick-hayek** [Azure/azure-cli#23897] opened 2022-09-15 06:04 UTC
The following script was working fine on 2.39.*, while it fails on 2.40.0:

```
$paths = @("/*","/css/*","/js/*","/fonts/*","/images/*")
az cdn endpoint purge -g $group -n $endpoint --profile-name $profile --content-paths $paths
```

How can I define a variable which can represent multiple paths for the purge command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e2b3b2-3e26-a47f-ee80-5bd5c3b065c4
* Version Independent ID: 72ef6ca0-b8f6-4952-732d-34aefa414bb6
* Content: [az cdn endpoint](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-purge)
* Content Source: [latest/docs-ref-autogen/cdn/endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cdn/endpoint.yml)
* Service: **azure-cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2022-09-15 08:20
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-09-16 02:20
@rick-hayek Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment] 2022-09-19 03:27
Duplicate of https://github.com/Azure/azure-cli/issues/23797

**Closed by RakeshMohanMSFT** 2022-09-19 03:27 UTC
Labels: Network, Network - CDN, customer-reported, CXP Attention, Auto-Assign
