### ISSUE TITLE
Error  running aks browse

### ISSUE THREAD

**Issue by elesdoar** [Azure/azure-cli#9897] opened 2019-07-09 18:34 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04E13110>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión',))
Traceback (most recent call last):
pip-install-wuxrdt2n\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.64 *

```

**Comment by seanmck** [comment] 2019-07-14 07:08
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:08 UTC
Labels: AKS, Service Attention
