### ISSUE TITLE
Azure Synapse SQL Script import is succeeded but not reflected. 

### ISSUE THREAD

**Issue by Lakshmiputchagatla** [Azure/azure-cli#24708] opened 2022-11-22 08:20 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az synapse sql-script --name testscript --workspace-name testscriptworkspacename --file 'path/test.sql'

**Describe the bug**

**To Reproduce**

**Expected behavior**
az synapse sql-script import is succeeded but .sql is not reflected

**Environment summary**
Tried from Azure DevOps pipeline with Azure PowerShell task.

**Additional context**
Followed https://learn.microsoft.com/en-us/cli/azure/synapse/sql-script?view=azure-cli-latest#az-synapse-sql-script-import but Azure Synapse SQL Script not updated. Please help me to resolve this issue

**Comment by yonzhan** [comment] 2022-11-22 09:14
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2022-11-30 04:29
@Lakshmiputchagatla I am unable to reproduce this, and I could see the file getting imported successfully.  (Screenshot below)
![image](https://user-images.githubusercontent.com/38112130/204707198-5e2ee086-b154-4bbc-a5ab-364bfeb0d44c.png)
Can you please share the CLI synapse module version you are using.  Also, is your Synapse workspace configured with Git, then please check your Live branch. Thanks.

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-02 02:35
@Lakshmiputchagatla Please let me know if you still are having issues.

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-06 05:43
@Lakshmiputchagatla We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-12-06 05:43 UTC
Labels: bug, customer-reported, Synapse, needs-author-feedback, CXP Attention, Auto-Assign
