### ISSUE TITLE
Failure when trying to run MS Learn Lab for Build Serverless API with Functions API Management Exercise

### ISSUE THREAD

**Issue by mikegray831** [Azure/azure-cli#10990] opened 2019-10-26 01:58 UTC
https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/3-exercise-import-function-app-api-management

## Describe the bug
This error was encountered when running bash setup.sh in the instructions on this page in MS Learn:  https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/3-exercise-import-function-app-api-management

**Command Name**
`az functionapp create`

**Errors:**
```
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp create --resource-group {} --consumption-plan-location {} --name {} --storage-account {} --runtime {}`

## Expected Behavior
Probably a change in the CLI or default commands that needs to be updated in the github repo that is pulled down in this step.

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

```

**Comment by ahmedelnably** [comment] 2019-11-11 18:35
duplicate of https://github.com/Azure/azure-cli/issues/11098

This is not an Azure CLI issue, the script in the Learn module is written against westus region, please change it to another US region (ex. centralus)

You may also want to open the issue against the Learn repo https://github.com/MicrosoftDocs/mslearn-apim-and-functions

**Closed by ahmedelnably** 2019-11-11 18:35 UTC
Labels: Functions, Service Attention
