### ISSUE TITLE
az login issue

### ISSUE THREAD

**Issue by OmkarShidore** [Azure/azure-cli#23846] opened 2022-09-12 17:43 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'http_cache'
Traceback (most recent call last):
  File "/home/heller/.local/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 135, in login_with_auth_code
    "with `az login --use-device-code`.", self._msal_app.authority.authorization_endpoint)
  File "/home/heller/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 107, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/home/heller/.local/lib/python3.8/site-packages/msal/application.py", line 858, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'http_cache'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.14.0-1051-oem-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.10
Installer: PIP

azure-cli 2.40.0
```

**Comment by yonzhan** [comment] 2022-09-12 22:58
@jiasli for awareness

**Comment by bebound** [comment] 2022-09-13 02:27
Duplicate of #20723

**Closed by bebound** 2022-09-13 02:27 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
