### ISSUE TITLE
`az storage account list`  is not listing all storage accounts

### ISSUE THREAD

**Issue by shreyasHpandya** [Azure/azure-cli#22465] opened 2022-05-16 10:08 UTC
**Command Name**
`az storage account list`

this is not generating list of all the storage account, I can see the complete list in console (all 35). But in CLI output it only shows 9 results. All the storage accounts are in 35 different regions.

## Environment Summary
```
macOS-12.3.1-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.36.0
```

**Comment by yonzhan** [comment] 2022-05-16 12:26
storage

**Comment by evelyn-ys** [comment] 2022-05-16 12:31
Have you set default resource group before?
The command would try to read default resource group from environment variables and it turns out to be `az storage account list -g your_default_rg`:
![image](https://user-images.githubusercontent.com/10227683/168592978-1e18b630-6b25-43e1-a9e0-572876afd0f9.png)

**Comment by shreyasHpandya** [comment] 2022-05-16 13:21
All the Storage accounts are in the same resource group. and I am passing that RG in the argument explicitly. Following is the command I am running.

    az storage account list -g <myrg> --query "[*].[name,location]" -o tsv

**Comment by evelyn-ys** [comment] 2022-05-17 01:22
Can you use `az config get` to check if you have default resource group? If you do have, please use `az config unset` to unset.

**Comment by shreyasHpandya** [comment] 2022-05-17 03:47
output of `az cofig get`

    Command group 'config' is experimental and under development. Reference and support levels: 
    https://aka.ms/CLI_refstatus
    {
      "cloud": [
        {
          "name": "name",
          "source": "/Users/shreyas.pandya/.azure/config",
          "value": "AzureCloud"
        }
      ]
    }

I don't think any default rg is set

**Comment by evelyn-ys** [comment] 2022-05-17 05:26
@jonie001 Can you help take a look if we will fetch default resource group from other settings?

**Comment by shreyasHpandya** [comment] 2022-05-17 05:43
Even if resource group is set somewhere, it should list all the storage accounts, since I have 35 storage accounts in the same resource group. it is listing only 9 storage account out of 35 in that resource group

**Comment by evelyn-ys** [comment] 2022-05-17 05:52
Need server side to check

**Comment by navba-MSFT** [comment] 2022-05-17 07:18
@shreyasHpandya Thanks for reaching out to us and sharing this feedback. Could you please confirm if the same command works fine from the [Azure Cloud Shell](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-list) ?

If Yes, while running the same command could you please share the `--debug `output of the working and failing scenario so that we could compare it. Awaiting your reply.

**Comment by shreyasHpandya** [comment] 2022-05-17 08:14
From cloud shell also it does not list all the storage accounts

**Comment by navba-MSFT** [comment] 2022-05-17 08:16
@shreyasHpandya Thanks for getting back. Please run the same above command with` --debug `switch and share the output here.

**Comment by navba-MSFT** [comment] 2022-05-17 08:57
@shreyasHpandya Please email the debug output to navba@microsoft.com

**Comment by navba-MSFT** [comment] 2022-05-17 10:20
@shreyasHpandya Thanks for sharing the debug output. I tried to create (35) StorageAccounts under my subscription, under a single resourceGroup and I was able to list the Storage Accounts. See the below screenshot:

![image](https://user-images.githubusercontent.com/57353862/168788092-eb19ca72-00b5-40f3-a7de-ff2334a9d546.png)

I tried with the same AzCLI version as yours ( 2.36.0). The only difference here being my resource location is the same. 

Could you please run either of the below commands and check if that helps ?

**Command # 1:**
```
az rest --method GET --uri https://management.azure.com/subscriptions/MYSUBID/resourceGroups/MyRGName/providers/Microsoft.Storage/storageAccounts?api-version=2021-09-01 --query 'value[].{Account:name,Location:location}' --output table
```

**Command # 2** 
```
az resource list -g MyRGName --query "[*].[name,location]" -o tsv
```
Awaiting your reply.

**Comment by shreyasHpandya** [comment] 2022-05-17 10:51
Sent both output in email

**Comment by shreyasHpandya** [comment] 2022-05-17 12:02
The command 2 and 1 both are listing same storage accounts, other extra resources listed by command 2 are not storage accounts (they are VPCS)

also all the storage account names are 3-24 characters (even the once not listed by these commands). 

These storage accounts are created by terraform. Terraform internally uses this API.
 
I will open a support ticket for this

**Comment by navba-MSFT** [comment] 2022-05-17 12:12
@shreyasHpandya Thanks for getting back. Since the same command works fine at our end (for 35 storage accounts in same resource group). see [this](https://github.com/Azure/azure-cli/issues/22465#issuecomment-1128689564), Please go ahead and create a support ticket as it would require active troubleshooting over a live meeting session.

**Comment by shreyasHpandya** [comment] 2022-05-17 12:13
Where can I create support ticket for this, its not allowing me from my azure portal

**Comment by navba-MSFT** [comment] 2022-05-17 12:19
@shreyasHpandya You need to have a minimum of [Support Request Contributor ](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#support-request-contributor) permissions on your subscription to create support ticket. Once you have the right permissions on the subscription, you can go to the Portal and create Support ticket as shown below:

![image](https://user-images.githubusercontent.com/57353862/168809121-30aef4fc-542c-4511-a397-b0d771c2a2e1.png)

Else you can check with your Subscription Administrator for that. He should be able to help you to create a ticket.

**Comment by shreyasHpandya** [comment] 2022-05-18 07:00
Update:
I deleted all storage accounts and recreated. It started showing up now. Still don't know the root cause of original issue.

**Comment by navba-MSFT** [comment] 2022-05-18 07:05
@shreyasHpandya Thanks for the update. I am glad that the issue is now resolved. Were you able to create support ticket and work with our support professionals before you fixed the issue ?

**Comment by shreyasHpandya** [comment] 2022-05-18 07:50
I could not create support ticket, it requires paid support plan.

**Comment by navba-MSFT** [comment] 2022-05-18 07:56
@shreyasHpandya Thanks for getting back. As I mentioned before, I wasn't able to replicate this issue. I did check a few of our backend issue knowledge bases but couldn't find any such similar issues being faced. So determining the exact cause of this issue wouldn't be possible. Nonetheless, I am glad that the issue is now fixed. If you need any further assistance in future please feel free to report the issue and we would be happy to help.

**Closed by navba-MSFT** 2022-05-18 07:56 UTC
Labels: Storage, customer-reported, CXP Attention, Auto-Assign
