### ISSUE TITLE
AZ Find command error

### ISSUE THREAD

**Issue by Vivekbsn** [Azure/azure-cli#11714] opened 2019-12-30 13:59 UTC
## Describe the bug

**Command Name**
`az find`

**Errors:**
```
HTTPSConnectionPool(host='app.aladdin.microsoft.com', port=443): Max retries exceeded with url: /api/v1.0/examples?query=appservice&clientType=AzureCli&context=%7B%22sessionId%22%3A+%223c3281e6-da4b-4bd8-89a5-0ca1a1967d9f%22%2C+%22subscriptionId%22%3A+null%2C+%22clientRequestId%22%3A+%2258de4546-2b0c-11ea-adf4-d46d6dde4b5c%22%2C+%22installationId%22%3A+%223a4a5376-2b0a-11ea-81f7-d46d6dde4b5c%22%2C+%22versionNumber%22%3A+%222.0.78%22%7D (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 456, in wrap_socket
pip-install-2ombfg7z\pyOpenSSL\OpenSSL\SSL.py, ln 1934, in do_handshake
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az find {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.78

```

**Comment by bim-msft** [comment] 2019-12-31 02:54
Related to #10839

**Comment by jiasli** [comment] 2021-08-06 06:51
Duplicate of #13444, #1572

**Closed by jiasli** 2021-08-06 06:51 UTC
Labels: Service Attention, Find, customer-reported
