### ISSUE TITLE
How to specify currency in az consumption budget create command

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/azure-cli#10696] opened 2019-09-30 12:18 UTC
I don't see a way to specify `currency` in  `az consumption budget create`  command. By default it's taking $. But i want GBP and AUD at least.

## Describe the bug

**Command Name**
`az consumption budget create`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

[<class 'decimal.ConversionSyntax'>]Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 273, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\parser.py", line 256, in parse_args
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1824, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 2265, in _get_values
    value = self._get_value(action, arg_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 2294, in _get_value
    result = type_func(arg_string)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-consumption\azure\cli\command_modules\consumption\_validators.py", line 25, in decimal_type
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az consumption budget create --amount {} --budget-name {} --category {} --resource-group {} --time-grain {} --start-date {} --end-date {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62

Extensions:
azure-devops                      0.12.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Venkata.Dorisala\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

```

**Comment by ms-premp** [comment] 2020-06-28 08:43
This is by design. This is derived from your pricing currency.

**Comment by ramaganesan-rg** [comment] 2020-06-29 17:00
Closing as per Prem's comments.

**Closed by ramaganesan-rg** 2020-06-29 17:00 UTC
Labels: Consumption, Service Attention, question
