### ISSUE TITLE
Crash on mac for az aks browse after crl+c

### ISSUE THREAD

**Issue by jlpedrosa** [Azure/azure-cli#9425] opened 2019-05-17 10:19 UTC
## Describe the bug
az cli crashes after hitting ctrl+C to stop the command.

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e830780>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
python3.7/site-packages/urllib3/connection.py, ln 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
site-packages/urllib3/util/connection.py, ln 80, in create_connection
    raise err
...

python3.7/site-packages/requests/adapters.py, ln 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e830780>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse -g {} -n {}`

## Expected Behavior
Well... command stoping without a stack trace

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63 *

Extensions:
aks-preview 0.4.0

```

**Comment by adewaleo** [comment] 2019-05-17 18:43
@jlpedrosa, can you reproduce this issue? Seems like there was a request connection error likely because of the timing of the interrupt was sent. If this is a reproducible issue then maybe we might want to handle this exception. 

However, if this is indeed very unlikely to occur, then it won't be worth it to add custom logic that hides this exception. Especially, given that this exception might be indicative of a bug in other circumstances.

Moreover, I think it is reasonable to expect that something can occur when a process abruptly receives an interrupt signal

@tjprescott @marstr @limingu  What are your thoughts about this?

**Comment by limingu** [comment] 2019-05-17 19:55
Agree. If the user wants to stop the command, the command can stop and exit at any point. We may add a special handler to exit the command without showing the stack trace. But some customers may want to have the stack trace to know where the command is if the command is take too long.

**Comment by jlpedrosa** [comment] 2019-05-22 16:53
@adewaleo  @limingu 

IF you have a look at the particular command `aks browse` that opens a browser to poke around with your cluster. It's a command that will always get ctrl+c. in mac I have that behaviour 100% of the times.

**Comment by adewaleo** [comment] 2019-05-29 17:58
Hmm, looks like aks browse might indeed be flakey and / or have other issues.  We should find ways to try to handle these connection errors more cleanly. 

related issues: #9500, #9000, #9144 

@mboersma, would you be able to look into this issue and the other related `aks browse issues`

**Comment by mboersma** [comment] 2019-05-30 14:53
@zqingqing1 @julienstroheker @samkreter could someone on the AKS team please take a look?

**Comment by jlpedrosa** [comment] 2019-06-25 09:14
Any feedback? plan?
Thanks!

**Comment by pieterclaerhout** [comment] 2019-07-08 13:19
Same problem here. It's happening many times per day and makes being productive really hard…

**Comment by adewaleo** [comment] 2019-07-09 00:07
I will look into this and try to come up with a fix. Sorry for the inconvenience!! seeing the mentioned people haven't commented. 

so sorry again @jlpedrosa and @pieterclaerhout

**Comment by pieterclaerhout** [comment] 2019-07-09 07:29
If you need more info, let me know!

**Comment by seanmck** [comment] 2019-07-14 07:13
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:13 UTC
Labels: AKS, Needs Triage, Service Attention
