### ISSUE TITLE
"az storage file upload-batch" requires login even when storage keys used

### ISSUE THREAD

**Issue by maxburke** [Azure/azure-cli#9292] opened 2019-05-02 19:21 UTC
I am trying to upload files using a storage key, but when I use `az storage file upload-batch`, it is failing as I am not logged in.

If I use a different command, like `az storage file list`, it succeeds as expected.

**Command Name**
`az storage file upload-batch`

**Errors:**
Suppress exception There are no active accounts.
Suppress exception Please run 'az login' to setup account.
command ran in 3.576 seconds.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage file upload-batch --verbose -d {} --destination-path {} -s {} --account-name {} --account-key {} --content-type {} --pattern {}`

## Expected Behavior
Expecting the batch upload to complete as all necessary credentials should be present

## Environment Summary
```
Linux-4.18.0-1014-azure-x86_64-with-debian-9.9
Python 3.6.5
Shell: bash

azure-cli 2.0.63

```
## Additional Context

Thanks for your feedback!

**Comment by bmancini42** [comment] 2019-05-08 15:22
Encountering the same issue for `az storage blob copy start-batch`

**Comment by limingu** [comment] 2019-05-08 23:18
Looking into it.

**Comment by limingu** [comment] 2019-05-15 21:09
@maxburke, can you add the details of the errors? I can't repro the issue. If you can run the command with --debug, that will be great. Thanks!

Suppress exception There are no active accounts.
Suppress exception Please run 'az login' to setup account.
command ran in 3.576 seconds.

These are not errors. They are just messages.

**Comment by tjprescott** [comment] 2019-05-15 21:21
If you run with `--debug` please don't post the output. Send to limin.gu@microsoft.com

**Comment by Juliehzl** [comment] 2019-08-02 14:46
@maxburke @bmancini42 Can you try to run with ```--debug``` and send to zuh@microsoft.com?

**Comment by Juliehzl** [comment] 2019-08-13 14:08
@maxburke  Anyway I cannot reproduce this issue now. So I will close this issue now, if you still have problems, feel free to open a new one or send an E-mail.

**Closed by Juliehzl** 2019-08-13 14:08 UTC
Labels: Storage

**Comment by ktmaul** [comment] 2019-11-22 16:12
I'm experiencing this issue in Azure DevOps when running an inline script via an Azure Pipelines agent. When run via PowerShell, I get a returned exit code of 1, which fails the task. If I run the task via PowerShell Core, I receive the messages mentioned by @limingu and the task succeeds.

PowerShell:
![image](https://user-images.githubusercontent.com/7206570/69441331-83cf5280-0d18-11ea-8dec-2ffa267606cc.png)

PowerShell Core:
![image](https://user-images.githubusercontent.com/7206570/69441432-ba0cd200-0d18-11ea-90fd-ec9a08f00b44.png)

**Comment by ChrisGibson1982** [comment] 2019-12-19 14:10
I get exactly the same issue

**Comment by kylehwang** [comment] 2020-04-16 01:19
confirming I am facing the same issue

**Comment by Juliehzl** [comment] 2020-04-17 04:49
> confirming I am facing the same issue

could you please provide more information about the error? with `--debug` in your command to show more debug information.
I just tried and I cannot reproduce the scenario. It should work with account name and account key provided.
