### ISSUE TITLE
Fail to create role assignment az ad cp create-for-rbac with malformed scope

### ISSUE THREAD

**Issue by simongdavies** [Azure/azure-cli#8892] opened 2019-03-27 14:53 UTC
**Describe the bug**
Executing az ad sp create-for-rbac with --scope "/subscriptions/{subscriptionId}/resourceGroups/ argument fails with the following error 

Role assignment creation failed.

role assignment response headers: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'x-ms-failure-cause': 'gateway', 'x-ms-request-id': 'fe7ba205-1514-4476-aedb-f79dece974a6', 'x-ms-correlation-request-id': 'fe7ba205-1514-4476-aedb-f79dece974a6', 'x-ms-routing-request-id': 'NORTHEUROPE:20190327T143620Z:fe7ba205-1514-4476-aedb-f79dece974a6', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 27 Mar 2019 14:36:19 GMT', 'Content-Length': '440'}

The api-version '2018-01-01-preview' is invalid. The supported versions are '2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

**To Reproduce**
execute az ad sp create-for-rbac with malformed scope as above

**Expected behavior**
Error message that the scope is invalid 

**Environment summary**
using bash CloudShell

**Additional context**
azure-cli                         2.0.61

**Comment by yugangw-msft** [comment] 2019-04-18 03:00
okay, this is rather a bad error from the service end.

**Comment by jiasli** [comment] 2022-12-19 04:17
Duplicate of https://github.com/Azure/azure-cli/issues/8892

**Closed by jiasli** 2022-12-19 04:17 UTC
Labels: Service Attention, Authorization-cli
