### ISSUE TITLE
az find failed with an unexpected error

### ISSUE THREAD

**Issue by bestbear** [Azure/azure-cli#13444] opened 2020-05-12 00:31 UTC
## Describe the bug

**Command Name**
`az find`

**Errors:**
```
HTTPSConnectionPool(host='app.aladdin.microsoft.com', port=443): Max retries exceeded with url: /api/v1.0/examples?query=az+sql+db+show-connection-string&clientType=AzureCli&context=%7B%22sessionId%22%3A+%223da80348-0e2a-401e-a2d8-1cf36dd1167f%22%2C+%22subscriptionId%22%3A+%229624cf99-973c-43cc-b512-b216a5f3395f%22%2C+%22versionNumber%22%3A+%222.5.1%22%7D (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 456, in wrap_socket
pip-install-7cl6xofh\pyOpenSSL\OpenSSL\SSL.py, ln 1934, in do_handshake
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az find {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: 

azure-cli 2.5.1

Extensions:
interactive 0.4.4

```

**Comment by bestbear** [comment] 2020-05-12 00:34
Likely related to this previously reported bug with SSLErrors via the CLI:
https://github.com/Azure/azure-cli/issues/8632

**Comment by yonzhan** [comment] 2020-05-12 07:41
az find

**Comment by jiasli** [comment] 2020-05-12 08:00
@bestbear, looks like you are behind a proxy. Could you check https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy and see if it solves the issue?

**Comment by jiasli** [comment] 2021-08-06 06:47
Duplicate of #1572

**Closed by jiasli** 2021-08-06 06:47 UTC
Labels: Service Attention, question, Find, customer-reported
