### ISSUE TITLE
--resource Name or ID is a wrong

### ISSUE THREAD

**Issue by vbrinza** [Azure/azure-cli#13043] opened 2020-04-16 06:44 UTC
"--resource
Name or ID of the target resource."
is a wrong statement because it works only with the ID.

az monitor diagnostic-settings list --resource asdasd-fw-acc-westeurope
Command group 'monitor' is in preview. It may be changed/removed in a future release.
usage error: --resource ID | --resource NAME --resource-group NAME --resource-type TYPE [--resource-parent PARENT] [--resource-namespace NAMESPACE]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ae3afa-74ff-12e8-a32c-c01240bd37da
* Version Independent ID: 522b7e55-2510-8e51-021a-2fc134fabfbe
* Content: [az monitor diagnostic-settings](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-04-16 06:50
add to S169

**Comment by MyronFanQiu** [comment] 2020-04-17 02:42
@vbrinza Thanks. I will fix it later.

**Comment by yonzhan** [comment] 2020-05-03 01:14
add to S171

**Comment by MyronFanQiu** [comment] 2020-06-05 03:39
@vbrinza Hi. `--resource` could accept name when you input both `--resource-group NAME --resource-type TYPE [--resource-parent PARENT] [--resource-namespace NAMESPACE]`. Please check the error message.

**Comment by MyronFanQiu** [comment] 2020-06-16 08:55
close this issue since it's by design.

**Closed by MyronFanQiu** 2020-06-16 08:55 UTC
Labels: Monitor, OKR3.2 Candidate, feature-request
