### ISSUE TITLE
Unable to use cloud shell from portal

### ISSUE THREAD

**Issue by justathoughtnz** [Azure/azure-cli#23328] opened 2022-07-26 03:10 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/tony/.azure/commands/2022-07-26.03-09-55.login.509.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 518, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE,
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path, encoding=LOG_FILE_ENCODING)
  File "/opt/az/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
OSError: [Errno 30] Read-only file system: '/home/tony/.azure/commands/2022-07-26.03-09-55.login.509.log'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-07-26 03:46
@jiasli for awareness

**Comment by jiasli** [comment] 2022-07-26 06:04
Duplicate of https://github.com/Azure/azure-cli/issues/13855

**Closed** 2022-07-26 06:55 UTC
Labels: Account, customer-reported, Auto-Assign
