### ISSUE TITLE
az aks update --enable-managed-identity isn't supported while it is now GA

### ISSUE THREAD

**Issue by djsly** [Azure/azure-cli#15953] opened 2020-11-17 14:55 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-existing-service-principal-based-aks-cluster-to-managed-identities tells us to use : az aks update --enable-managed-identity

**To Reproduce**
❯ az aks update --update-managed-identity -g sky-aks-rg -n sly-k8s
UnrecognizedArgumentError: unrecognized arguments: --enable-managed-identity

**Expected behavior**
For the command to work

**Environment summary**
OSX

✖ az version
{
  "azure-cli": "2.15.0",
  "azure-cli-core": "2.15.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.65"
  }
}

**Additional context**

**Comment by miwithro** [comment] 2020-11-17 22:13
@norshtein

**Comment by yonzhan** [comment] 2020-11-18 01:23
aks

**Comment by norshtein** [comment] 2020-11-20 09:34
Could you remove your aks-preview extension and re-install it? The command should be included in the latest aks-preview extension.

By the way, updating from using service principal to use managed identity is still a Preview feature, you need to register feature flag "Microsoft.ContainerService/MigrateToMSIClusterPreview" to use the feature.

**Comment by TomGeske** [comment] 2020-11-20 10:14
@miwithro should we update our doc and call out the required feature flag? Right now it looks like SP to MI migrate is GA.

**Comment by djsly** [comment] 2020-11-20 12:05
Correct, the DOC says it is now GA as well as the AKS release note. There is no mentioned of AKS-preview nor that a feature flag is needed. 

@palma21 should the release note be updated to reflect the status of the feature?

**Comment by miwithro** [comment] 2020-11-20 12:21
Added the Preview note and the Feature Flag steps to the document.   Should be live tomorrow.

**Comment by TomGeske** [comment] 2020-11-20 12:24
Thanks @djsly for your feedback and pointing out. It is really appreciated.

Let's close this one. Feel free to keep commenting.

#please-close

**Comment by djsly** [comment] 2020-11-20 17:07
FYI, maybe we need to make this release note clearer as well: https://github.com/Azure/AKS/releases/tag/2020-11-09 

It doesn't say GA but it doesn't say preview either

> Migration from Service Principal-based clusters to Managed Identity Managed clusters is now supported. See how here.

**Closed** 2020-11-20 17:07 UTC
Labels: AKS, Service Attention

**Comment by feliperoveran** [comment] 2020-12-01 14:39
@norshtein I ran the upgrade yesterday and along with having to enable `Microsoft.ContainerService/MigrateToMSIClusterPreview`, it also required `Microsoft.ContainerService/AutoUpgradePreview`.

is that expected? I couldn't find any mentions of that feature anywhere in the docs

**Comment by norshtein** [comment] 2020-12-02 04:53
@feliperoveran no, that's not expected behavior. We are investigating what happened.

**Comment by feliperoveran** [comment] 2020-12-02 22:31
@norshtein thank you!

by the way, I was able to get it working without enabling `AutoUpgradePreview` with `aks-preview` version `0.4.67`

**Comment by norshtein** [comment] 2020-12-03 07:33
Yes, the auto-upgrade feature support is added in aks-preview 0.4.68, so 0.4.67 will not hit this error.
