### ISSUE TITLE
Can not create azure VM by CLI without  NSG

### ISSUE THREAD

**Issue by emp00001** [Azure/azure-cli#21586] opened 2022-03-10 17:22 UTC
running by CLI: az vm create --nsg "" or --nsg " "      so VM should be created without NSG, getting the error : argument --nsg: expected one argument.  is there any way to fix it ?

**Comment by yonzhan** [comment] 2022-03-10 22:55
Compute

**Comment by emp00001** [comment] 2022-03-11 00:55
what do you mean by  Compute   "

**Comment by zhoxing-ms** [comment] 2022-03-11 02:24
@emp00001 This is by designed. Because CLI does not support passing in '' as parameter's value, [knack](https://github.com/microsoft/knack) will think that the user has not passed in any value, such as:
```pwsh
(env) PS C:\Users\zhoxing.FAREAST\Desktop\project> az vm create -n zhoxing-test -g zhoxing-test --nsg-rule "" --debug
cli.knack.log: File logging enabled - writing logs to 'C:\Users\zhoxing.FAREAST\.azure\logs'.
cli.knack.cli: Command arguments: ['vm', 'create', '-n', 'zhoxing-test', '-g', 'zhoxing-test', '--nsg-rule', '--debug']
```
Please note that we have explained in the help description of `az vm create -h` that the input `--nsg NONE` indicates that the NSG will not be created
```pwsh
    --nsg-rule                                                    : NSG rule to create when creating
                                                                    a new NSG. Defaults to open
                                                                    ports for allowing RDP on
                                                                    Windows and allowing SSH on
                                                                    Linux. NONE represents no NSG
                                                                    rule.  Allowed values: NONE,
                                                                    RDP, SSH.
```

**Comment by emp00001** [comment] 2022-03-11 02:53
I ran it with --nsg NONE, but it still created the NSG named NONE

**Comment by emp00001** [comment] 2022-03-11 02:54
I ran it with --nsg NONE, but it still created the NSG named NONE

**Comment by emp00001** [comment] 2022-03-11 03:16
I even did : instead of --nsg     I added  --nsg-rule NONE   and it still created the NSG

**Comment by zhoxing-ms** [comment] 2022-03-11 03:21
@emp00001 Sorry, I misunderstood the parameter you mean just now, you run this command in Power Shell environment, right?

Please refer to the help description of parameter `--nsg`
```pwsh
    --nsg                                                         : The name to use when creating a
                                                                    new Network Security Group
                                                                    (default) or referencing an
                                                                    existing one. Can also reference
                                                                    an existing NSG by ID or specify
                                                                    "" for none ('""' in Azure CLI
                                                                    using PowerShell or --%
                                                                    operator).
```
Please use `--nsg '""'`, such as:
```pwsh
(env) PS C:\Users\zhoxing.FAREAST\Desktop\project> az vm create -n zhoxing-test -g zhoxing-test --nsg '""' --debug
cli.knack.log: File logging enabled - writing logs to 'C:\Users\zhoxing.FAREAST\.azure\logs'.
cli.knack.cli: Command arguments: ['vm', 'create', '-n', 'zhoxing-test', '-g', 'zhoxing-test', '--nsg', '', '--debug']
```
Or please use the `--%` 
```pwsh
(env) PS C:\Users\zhoxing.FAREAST\Desktop\project> az --% vm create -n zhoxing-test -g zhoxing-test --nsg "" --debug
cli.knack.log: File logging enabled - writing logs to 'C:\Users\zhoxing.FAREAST\.azure\logs'.
cli.knack.cli: Command arguments: ['vm', 'create', '-n', 'zhoxing-test', '-g', 'zhoxing-test', '--nsg', '', '--debug']
```

**Comment by emp00001** [comment] 2022-03-11 03:29
I am running it form Linux  Bash, but not from PowerShell


Thank you.
Michael.

**Comment by zhoxing-ms** [comment] 2022-03-11 03:40
I can't reproduce this issue in Linux Bash environment. Could you send me the debug log by email? My email address is Zhou.Xing@microsoft.com
![Screenshot 2022-03-11 113704](https://user-images.githubusercontent.com/16612065/157797591-ab751cd5-0896-4890-82a2-ef846792f673.png)

**Comment by emp00001** [comment] 2022-03-11 03:44
when I use:  --nsg ""     or --nsg ''

getting the error:   argument --nsg: expected one argument


Thank you.
Michael.

**Comment by emp00001** [comment] 2022-03-11 04:19
I see the problem

if I do:   az vm create --nsg '' -g 01_VM_RG -n 001 --image CentOS --debug
   - it works and created the VM without NSG


but in my case I use the variable:   NSG_RG=''          and in the command
line I do:     --nsg $NSG_RG


and getting error:     argument --nsg: expected one argument


Thank you.
Michael.

**Comment by zhoxing-ms** [comment] 2022-03-11 07:40
The problem is that the variable you reference should be `"$NSG_RG"` instead of `$NSG_RG`.

We can add `set -vx` to the script to help us analyze the parameters input to CLI
```pwsh    
# This command is purely for showing what is going on inside Bash.
# $ help set
# -v  Print shell input lines as they are read.
# -x  Print commands and their arguments as they are executed.
$ set -vx
```

When the input reference variable is `$NSG_RG`:
```shell
set -vx
NSG_RG=''
az vm create --nsg $NSG_RG --debug
```
The output of the script is as follows:
![Screenshot 2022-03-11 152528](https://user-images.githubusercontent.com/16612065/157823314-5fca30c9-d14c-44f2-a83c-69b61b614abe.png)
We can see that when the parameter has not been passed into the CLI, the parameter's value of `$NSG_RG` is discarded when Shell parses this instruction in advance.

When the input reference variable is `"$NSG_RG"`:
```shell
set -vx
NSG_RG=''
az vm create --nsg "$NSG_RG" --debug
```
It can normally the input parameter's value into the CLI
![Screenshot 2022-03-11 152559](https://user-images.githubusercontent.com/16612065/157823336-ca7e8366-e51a-461d-89bc-b3ea5250a2c8.png)

**Comment by zhoxing-ms** [comment] 2022-03-25 03:07
If there are no other questions, I will close the issue first. If there are any other questions later, we will reopen it

**Closed by zhoxing-ms** 2022-03-25 03:07 UTC
Labels: Compute, customer-reported, Auto-Assign

**Comment by emp00001** [comment] 2022-03-25 14:48
yes, it can be closed


Thank you.
Michael.
