### ISSUE TITLE
az keyvault list shows error message about openssl

### ISSUE THREAD

**Issue by jwendl** [Azure/azure-cli#4106] opened 2017-07-31 18:31 UTC
### Description
On a fresh Ubuntu for Windows install (lxrun /uninstall etc). Using the steps below to install azure cli. When running from /opt/az/bin/python3 it's
```bash
jwendl@PC:~$ /opt/az/bin/python3
Python 3.6.1 (default, Jul 28 2017, 00:18:58)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.bindings._openssl import ffi, lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
>>>
```

When running from /usr/bin/python3 it works fine:
```bash
jwendl@PC:~$ /usr/bin/python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.bindings._openssl import ffi, lib
>>>
```

When running az keyvault list I get the following error:
```bash
jwendl@PC:~$ az keyvault list
/opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 175, in execute
    self.configuration.load_params(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 50, in load_params
    commands.load_params(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 362, in load_params
    command_table[command].load_arguments()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 312, in load_arguments
    self.arguments.update(self.arguments_loader())
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 577, in arguments_loader
    return extract_args_from_signature(get_op_handler(operation), no_wait_param=no_wait_param)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 461, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/keyvault/custom.py", line 12, in <module>
    from OpenSSL import crypto
  File "/opt/az/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/az/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/opt/az/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
![image](https://user-images.githubusercontent.com/1068431/28791903-c5dd643e-75e2-11e7-96f4-edfff609394d.png)

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
jwendl@PC:~$ az --version
azure-cli (2.0.12)

acr (2.0.9)
acs (2.0.11)
appservice (0.1.11)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
container (0.1.7)
core (2.0.12)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.11)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.11)
nspkg (3.0.1)
profile (2.0.9)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.11)
role (2.0.9)
sf (1.0.5)
sql (2.0.8)
storage (2.0.11)
vm (2.0.11)

Python (Linux) 3.6.1 (default, Jul 28 2017, 00:18:58)
[GCC 4.8.4]

Python location '/opt/az/bin/python3'

**OS Version:** What OS and version are you using?  
Linux PC 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
(ie; bash on windows 10)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Bash on Windows

**Comment by derekbekoe** [comment] 2017-08-03 00:57
What's the output of `lsb_release -a`?

**Comment by jwendl** [comment] 2017-08-03 03:13
jwendl@PC:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

**Comment by tjprescott** [comment] 2017-08-07 17:31
From @schaabs via email:

"I’ve root caused the problem, and it seems to be an issue with the apt-get package and is specific to Ubuntu on Windows.  For some reason the CLI deb package installs 3.6.1 on the machine, but 3.6.1 doesn’t appear to be supported on ubuntu on Windows.  This must have been a recent update to the package you got when you did an upgrade.  I’ve reached out to the azure-cli team to discuss the issue and a fix for it.  I’ll let you know when it’s available.   In the meantime if you need to install the CLI on Ubuntu on Windows to get unblocked I can walk you through how to manually install the CLI using PIP.  Or you can use an actual linux VM and the install instructions will work properly.  Let me know."

**Comment by derekbekoe** [comment] 2017-08-07 22:15
Here is a work around to install the prev. version of the package:
```
sudo apt-get remove azure-cli
wget https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.0.10-1_all.deb
sudo dpkg -i azure-cli_2.0.10-1_all.deb
```

To remove later:
```
sudo dpkg -r azure-cli
```

**Comment by marrobi** [comment] 2017-08-17 12:00
Any news on this? Is blocking me as need the "az container" commands so need to be > 2.0.12

**Comment by derekbekoe** [comment] 2017-08-17 14:41
Closing so we can track the conversation all in https://github.com/Azure/azure-cli/issues/4154.
@marrobi please see that issue.

**Closed by derekbekoe** 2017-08-17 14:41 UTC
Labels: KeyVault, Packaging
