### ISSUE TITLE
Azure CLI Login issue

### ISSUE THREAD

**Issue by MuthukkumarNicheSoft** [Azure/azure-cli#9247] opened 2019-04-30 07:09 UTC
**Describe the bug**
Getting the error with Azure CLI command "az login -u -p". Error message "Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50126: Invalid username or password..."

**To Reproduce**
I am configure the azure pipeline, to build the image I have to login to Azure portal to get the Postgres connection. For that I have given azure CLI command like "az login -u -p", I am getting below error "Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50126: Invalid username or password..."
But if I give az login then its prompting one URL and given some code "WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code to authenticate." with this its working but I want to login without the manual process. Have tried with "az account clear" as well but no luck. Could someone help me with that. 

**Expected behavior**
I want to login to azure portal to connect to PostgreSQL db without the manual efforts. az login -u -p should take care of my azure postal login.

az --version : azure-cli                         2.0.61 *

**Comment by marstr** [comment] 2019-04-30 16:32
Your account may not be authorized for basic authentication like this.

If you're working out of Azure Pipelines, I'd recommend using the "Azure CLI" job which will take care of authenticating you based on an account you select using Manged Service Identity under the covers. If that's not an option, you should create a service principal to authenticate.

**Comment by MuthukkumarNicheSoft** [comment] 2019-04-30 17:01
We are using the Azure pipeline and I have tried with az login and az subscription but it didn't helped me. Let me try with the service principal for the authenticate.

**Comment by yugangw-msft** [comment] 2019-05-03 02:23
The key error is `ADSTS50126: Invalid username or password...`, can you cross check whether or not the user name or password is wrong, or contains special character that which gets escaped by the shell?
Also what is you OS and Shell you are using (BASH, Windows CMD, PS?)

**Comment by MuthukkumarNicheSoft** [comment] 2019-05-03 04:30
I have tried with Service Principal but its not helping out. Even I have tried with my local VM its asking me to login from browser. Below is the steps what I have done in VM.

1. First time I am login to azure from VM with the command of "az login", and its open the browser to give the username and password. (In Windows its open the browser , In Linux its giving the Login URL and one Code after that we have to enter the credential) 

2. After the first time login with the browser(closed everything) I can able to login with the command "az login -u muthukkumar@example.com -p mypassword", and its working fine. 

3. Then if I command "az account clear" then my account will be cleared.

4. After the account clear if I try to command "az login -u muthukkumar@example.com -p mypassword" I am getting the invalid Token error.

So First time to use Azure CLI we have to login from the browser then we can use "az login -u -p". But my requirement is I have to login without giving the username and password manually. Could you please suggest is there any possible ways to do it.

**Comment by MuthukkumarNicheSoft** [comment] 2019-05-03 05:24
> The key error is ADSTS50126: Invalid username or password..., can you cross check whether or not the user name or password is wrong, or contains special character that which gets escaped by the shell?
> Also what is you OS and Shell you are using (BASH, Windows CMD, PS?)
Actually its working fine with my Linux VM. And the one which I am trying is Azure DevOps Hosted Ubuntu 1604 and the script is Bash. You can check my command https://github.com/Azure/azure-cli/issues/9247#issuecomment-488927434 which I have tried to reproduce it.

**Comment by yugangw-msft** [comment] 2019-05-07 04:28
@MuthukkumarNicheSoft, i believe i understand the root cause, likely the password is either in-correct or it contains special characters that gets escaped by shell.
The step 2 seemingly working is because the token is already in the token cache. Please note, successful `az login` at step 1 will always cache the token in the local cache, so the subsequent step 2 of `"az login -u muthukkumar@example.com -p mypassword"` never hits the wire, rather gets the token from the local cache and calls a success.

I suggest you wrap both username and password with quotes and try again.

**Comment by MuthukkumarNicheSoft** [comment] 2019-05-07 06:12
@yugangw-msft I have tried with quotes see the below screenshot.
![image](https://user-images.githubusercontent.com/47320493/57275798-2695eb80-70bd-11e9-898b-29d5f1f4c815.png)

**Comment by yugangw-msft** [comment] 2019-05-07 16:35
@MuthukkumarNicheSoft, does your account have MFA enabled?

**Comment by MuthukkumarNicheSoft** [comment] 2019-05-14 07:12
> @MuthukkumarNicheSoft, does your account have MFA enabled?
It was there but I have disabled and tried it but no luck. For the first time I have to login from the browser.

**Comment by marstr** [comment] 2019-06-17 17:35
I still suspect this is about your password not getting escaped correctly in your terminal. Checkout our documentation on this [./doc/use_cli_effectively#quoting-issues](https://github.com/Azure/azure-cli/blob/a1f2f2b666a759eb2f593dd7796db6bbd0237614/doc/use_cli_effectively.md#quoting-issues). Also, given that you're using PowerShell, you might want to check this out: https://ss64.com/ps/syntax-esc.html

**Comment by marstr** [comment] 2019-06-17 17:36
Given that we're not hearing other reports about this, I'm going to close it out for now. If you feel strongly that there is a bug here, and that it's not related to special characters being escaped correctly in your command-line environment, I'll open it back up.

**Closed by marstr** 2019-06-17 17:36 UTC
Labels: Authentication, Needs Triage
