### ISSUE TITLE
Missing authorization header

### ISSUE THREAD

**Issue by espensb** [Azure/azure-cli#10908] opened 2019-10-18 08:06 UTC
## Describe the bug
Get an error message indicating that the az cli is not including the required headers in requests.

**Command Name**
`az cosmosdb collection list`

**Errors:**
```
Operation Failed: Status code: 401
{"code":"Unauthorized","message":"Required Header authorization is missing. Ensure a valid Authorization token is passed.\r\nActivityId: 156da7de-c571-467c-b06d-10842bec3bd3, Microsoft.Azure.Documents.Common/2.7.0"}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az cosmosdb collection list -n {} -d {} --subscription {}`

## Environment Summary
```
Linux-4.19.61-1-lts-x86_64-with-arch
Python 3.7.4
Shell: bash

azure-cli 2.0.75

```

**Comment by shurd** [comment] 2019-10-21 06:28
Hi @espensb thank you for opening this issue. In version 2.0.71 of the CLI, we introduced new API specific commands for managing databases and collections. Could you try running the command using the new command group? You can find some examples using the new commands here: https://docs.microsoft.com/en-us/azure/cosmos-db/manage-with-cli#create-a-container

Each API has different expectations and behaviors when dealing with databases and containers, so the generic "database" and "collection" commands do not cover every scenario.

For example, if you have a SQL account, you can try the command `az cosmosdb sql container list -a {account name} -d {database name} -g {resource group}`. Each API has a similar command that you can discover with the -h flag.

If you want to continue using that specific command, try specifying the account key (--key) or resource group name (-g). The help text for the "-n" parameter for that command states: "Cosmos DB account name. Must be used in conjunction with either name of the resource group or cosmosdb account key."

**Comment by shurd** [comment] 2019-11-09 00:24
We have been unable to reproduce this behavior, so I am going to close this issue. Please use the new API specific commands for managing databases and collections. Please specify both the key and account name if you want to continue using the older command group.

**Closed by shurd** 2019-11-09 00:24 UTC
Labels: Cosmos, Question, Service Attention
