### ISSUE TITLE
az iot dps certificate create fails with "too many 500 error responses"

### ISSUE THREAD

**Issue by jokarl** [Azure/azure-cli#11131] opened 2019-11-06 13:50 UTC
az version information:

```sh
azure-cli                         2.0.76

command-modules-nspkg              2.0.3
core                              2.0.76
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
find                               0.3.0
azure-cli-iot-ext                  0.7.1
```

Command:
```sh
az iot dps certificate create --dps-name xxx -g xxx -n xxx -p xxx
```

Fails with:

```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Devices/provisioningServices/xxx/certificates/xxx?api-version=2018-01-22 (Caused by ResponseError('too many 500 error responses',))
```

Verified that the same certificate works when uploading through the portal to the same DPS, with the same name for the uploaded certificate.

**Comment by jlian** [comment] 2019-12-11 00:28
@iluican can you take a look?

**Comment by iluican** [comment] 2019-12-11 03:19
@digimaun.

**Comment by digimaun** [comment] 2019-12-12 01:10
@hochas Can you please share some details about the failing request? For example regarding the cert, is it a .pem or .cer file? How is the contend encoded? base64, binary, etc?

**Comment by cocowalla** [comment] 2020-05-14 10:21
I'm having the exact same issue - the problem seems only to occur if you provide a PEM certificate that includes the full chain.

If I provide a PEM or DER encoded certificate that includes only the leaf certificate, then it works OK.

This is a bug, as it works just fine in the Azure Portal if you provide a PEM cert containing the full chain.

**Comment by azhar-iot** [comment] 2021-05-31 10:32
> I'm having the exact same issue - the problem seems only to occur if you provide a PEM certificate that includes the full chain.
> 
> If I provide a PEM or DER encoded certificate that includes only the leaf certificate, then it works OK.
> 
> This is a bug, as it works just fine in the Azure Portal if you provide a PEM cert containing the full chain.

We tried the same and the verification certificate is uploaded fine from the portal however it doesn't do it via cli command

az iot dps certificate verify --certificate-name xxxxx --dps-name xxxxxx --etag XXXXXXX --path D:/github/icore-iot-backend/static-files/certificates/A66324F5EC0E245BA141738366F57477B5BB0E55362F2A04_fullchain.cert.pem --resource-group xxxxx  --subscription xxxxxx


but it gives error


ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/8eb3fd4e-882d-4c04-88e4-5b13add00779/resourceGroups/rg-rtfs-eus2-sandbox-iot/providers/Microsoft.Devices/provisioningServices/dps-rtfs-eus2-sandbox-internal/certificates/cert-rtfs-eus2-sandbox-internal/verify?api-version=2018-01-22 (Caused by ResponseError('too many 500 error responses',))

**Comment by azhar-iot** [comment] 2021-05-31 10:35
I get exactly the same error while following the documentation https://docs.microsoft.com/en-us/cli/azure/iot/dps/certificate?view=azure-cli-latest

Please let us know if there is a workaround for this our or any solution

**Comment by c-ryan-k** [comment] 2021-12-09 18:19
Hey @azhar-iot - can you try this again with a more current version of the Azure CLI? I believe this should work as expected after [some fixes](https://github.com/Azure/azure-cli/pull/18966) that went in to a release earlier this year (2.27 I believe).

**Comment by vilit1** [comment] 2024-05-13 16:57
Closing since there have been no replies recently. Feel free to reopen if you have any other issues.

**Closed by vilit1** 2024-05-13 16:57 UTC
Labels: Service Attention, customer-reported, IoTDPS
