### ISSUE TITLE
Sandbox Excerise : attempted manual cleanup of VM and resource group in CLI

### ISSUE THREAD

**Issue by AdCognita** [Azure/azure-cli#17426] opened 2021-03-24 06:31 UTC
## Describe the bug

**Command Name**
`az group delete`

**Errors:**
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/clouddenizen/.azure/commands/2021-03-24.06-20-03.group_show.247.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 517, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 173, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 117, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/clouddenizen/.azure/commands/2021-03-24.06-20-03.group_show.247.log'
To open an issue, please run: 'az feedback'
clouddenizen@Azure:~$ az group exists --resource-group learn-ae384a34-577c-4f7a-b7df-cd294cc515ec
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/clouddenizen/.azure/commands/2021-03-24.06-20-49.group_exists.252.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 517, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 173, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 117, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/clouddenizen/.azure/commands/2021-03-24.06-20-49.group_exists.252.log'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Deleted the VM then tried removing the resource group._
- `az group delete --resource-group {}`

## Environment Summary
```
Linux-4.15.0-1110-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.21.0

Extensions:
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by yonzhan** [comment] 2021-03-24 11:03
ARM

**Comment by zhoxing-ms** [comment] 2021-07-27 06:40
Duplicate of #13855

**Closed by zhoxing-ms** 2021-07-27 06:40 UTC
Labels: ARM, OKR3.2 Candidate, feature-request
