### ISSUE TITLE
az cli version 2.0.74 commands write to stderr stream even when the command succeeds

### ISSUE THREAD

**Issue by tejasd1990** [Azure/azure-cli#10856] opened 2019-10-16 07:48 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

We own the "Azure CLI" Azure Pipelines task.
We have come across 3 customer issues so far where az cli version 2.0.74 commands write to stderr stream even when the command succeeds
Could be happening since some other older version, I don't know about that, but see this issue with at least this version.

**Describe the bug**
We have come across 3 customer issues so far where az cli version 2.0.74 commands write to stderr stream even when the command succeeds
At line:1 char:1
+ az extension add --name application-insights --output none 2>&1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Extens...eady installed.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**To Reproduce**
For example, 
az extension add --name application-insights --output none 2>&1

**Expected behavior**
successful commands should not write to stderr stream

**Environment summary**
Azure Pipelines Hosted Agent, Powershell on my local machine

**Additional context**

**Comment by dmitrykarnitski** [comment] 2019-10-16 09:58
Hi, We have experienced this issue as well. 

But according to the reply from this comment (https://github.com/Azure/azure-cli/issues/9891#issuecomment-539316006), this is the expected behavior. 

So, what is the right approach? 
IMO, the error stream should not contain any garbage that is not really related to errors happened during the execution.

**Comment by yonzhan** [comment] 2019-10-19 09:12
@jiasli please take a look.

**Comment by jiasli** [comment] 2019-11-19 11:56
It is by-design to write warnings to stderr. To remove the warning, use

```
az extension add --name application-insights --output none 2>nul
```

**Comment by tvanfosson** [comment] 2019-11-21 18:18
@jiasli using Azure DevOps pipelines to execute scripts it is common to turn on "Fail on Standard Error" because commands don't always exit with a non-zero value. Having Azure CLI commands output non-fatal errors to stderr makes it much more difficult to capture actual errors from CLI commands while still dealing with other script elements that don't behave nicely in other ways.

**Comment by yonzhan** [comment] 2019-12-15 11:46
Can we close this issue?

**Comment by jiasli** [comment] 2019-12-24 03:32
@tvanfosson if you see any az command that returns zero value when it fails, please let us know. We will consider adding `--no-warning` or `--quite` switch in the future.

**Comment by tvanfosson** [comment] 2019-12-30 17:48
@jiasli we don't limit ourselves to just Azure CLI commands in our scripts. It's hard to definitely say that we can rely on command exit values only.

**Comment by SanderHolvoet** [comment] 2020-01-09 15:36
> It is by-design to write warnings to stderr. To remove the warning, on Windows use
> 
> ```
> az extension add --name application-insights --output none 2>nul
> ```
> 
> On Linux use
> 
> ```
> az extension add --name application-insights --output none 2>/dev/null
> ```

This didn't work for me. Appending `2>null` to `--output none` results in the following output

```
out-file : FileStream was asked to open a device that was not a file. For support for devices like 'com1:' or 'lpt1:', 
call CreateFile, then use the FileStream constructors that take an OS handle as an IntPtr.
At D:\a\1\s\automation\CreateTeam.ps1:120 char:13
+             $updateDenyPermissions = az devops security permission up ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], NotSupportedException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

**Comment by jiasli** [comment] 2020-01-10 05:26
For PowerShell, please use [`$null`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-6#null) as the destination of the redirection:

```
az extension add --name application-insights --output none 2>$null
```

**Comment by SanderHolvoet** [comment] 2020-01-10 09:00
That fixed it, thanks.

**Closed** 2020-02-01 08:44 UTC
Labels: Core, Feature Request

**Comment by jiasli** [comment] 2020-03-24 13:19
We have added option `--only-show-errors` in #12604 to disable warnings that are written to `stderr`. It will be included in [S167](https://github.com/Azure/azure-cli/milestone/84) release.

**Comment by Rajuvimal** [comment] 2022-03-24 04:43
-bash: $null: ambiguous redirect 
getting this error, after using 2>$null

**Comment by Crytlig** [comment] 2022-03-30 11:24
@Rajuvimal $null is for PowerShell. On bash use 2>/dev/null
