### ISSUE TITLE
failed to install az-cli on debian based docker container 

### ISSUE THREAD

**Issue by guochengjun1993** [Azure/azure-cli#26769] opened 2023-06-28 08:36 UTC
### Describe the bug

I have this dockerfile which installs az cli & az bicep. It works last week but today when I building the container I found that the script which downloaded from https://aka.ms/InstallAzureCLIDeb is unable to install az cli anymore.
```
FROM python:3.10
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN	curl -sL https://aka.ms/InstallAzureCLIDeb | bash && az bicep install
```
I have looked into the python:3.10 and I found out that it is based on debian. So I tried to run the same dockerfile but based on ubuntu, and it works fine.

### Related command

curl -sL https://aka.ms/InstallAzureCLIDeb | bash

### Errors

Sending build context to Docker daemon  270.8MB
Step 1/7 : FROM python:3.10
 ---> 23e11cf6844c
Step 2/7 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> a5d9ce78e57a
Step 3/7 : RUN  curl -sL https://aka.ms/InstallAzureCLIDeb | bash && az bicep install
 ---> Running in 6ac54b33cdcc
Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8904 kB]
Get:5 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [31.6 kB]
Fetched 9183 kB in 1s (6413 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
gnupg is already the newest version (2.2.40-1.1).
curl is already the newest version (7.88.1-10).
The following NEW packages will be installed:
  apt-transport-https lsb-release
0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.
Need to get 31.7 kB of archives.
After this operation, 53.2 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 apt-transport-https all 2.6.1 [25.2 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 lsb-release all 12.0-1 [6416 B]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 31.7 kB in 0s (754 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 23974 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.6.1_all.deb ...
Unpacking apt-transport-https (2.6.1) ...
Selecting previously unselected package lsb-release.
Preparing to unpack .../lsb-release_12.0-1_all.deb ...
Unpacking lsb-release (12.0-1) ...
Setting up apt-transport-https (2.6.1) ...
Setting up lsb-release (12.0-1) ...
Get:1 https://packages.microsoft.com/repos/azure-cli bullseye InRelease [3587 B]
Get:2 https://packages.microsoft.com/repos/azure-cli bullseye/main all Packages [1852 B]
Hit:3 http://deb.debian.org/debian bookworm InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Hit:5 http://deb.debian.org/debian-security bookworm-security InRelease
Get:6 https://packages.microsoft.com/repos/azure-cli bullseye/main amd64 Packages [782 B]
Fetched 6221 B in 1s (11.5 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 azure-cli : Depends: libffi7 (>= 3.3~20180313) but it is not installable
             Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/bash -o pipefail -c curl -sL https://aka.ms/InstallAzureCLIDeb | bash && az bicep install' returned a non-zero code: 100

### Issue script & Debug output

N/A

### Expected behavior

Should be able to install az cli for my docker container which based on debian.

### Environment Summary

N/A

**Comment by yonzhan** [comment] 2023-06-28 08:37
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2023-06-29 06:26
Duplicate of #25750

`python:3.10`'s base image changes to bookworm, but CLI does not support it yet. You can use `3.10-bullseye` as a workaround for now.

**Closed by bebound** 2023-06-29 06:26 UTC
Labels: bug, ARM, customer-reported, Installation, CXP Attention, Auto-Assign
