### ISSUE TITLE
az eventgrid event-subscription list failing

### ISSUE THREAD

**Issue by vrvinodchandar** [Azure/azure-cli#24819] opened 2022-12-06 19:12 UTC
## Describe the bug

**Command Name**
`az eventgrid event-subscription list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventgrid/custom.py", line 918, in cli_event_subscription_list
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventgrid/custom.py", line 1776, in _list_event_subscriptions_by_resource_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventgrid/custom.py", line 1829, in _validate_subscription_id_matches_default_subscription_id
AttributeError: 'NoneType' object has no attribute 'lower'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az eventgrid event-subscription list --resource-group {} --source-resource-id {} --location {}`

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *
```

**Comment by yonzhan** [comment] 2022-12-06 23:22
route to CXP team

**Comment by giladshanan** [comment] 2022-12-08 23:07
I'm getting a similar looking error when running `az containerapp logs show -n {} -g {}`:

```
The command failed with an unexpected error. Here is the traceback:
'logStreamEndpoint'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/Users/gilad/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2140, in stream_containerapp_logs
    logstream_endpoint = token_response["properties"]["logStreamEndpoint"]
KeyError: 'logStreamEndpoint'
```

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-09 05:39
@vrvinodchandar I am not able to reproduce this issue and able to get the results.  
![image](https://user-images.githubusercontent.com/38112130/206632128-416fa999-6749-4512-b9ef-4ba53370a153.png)
Can you please try upgrading your CLI version.

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-13 04:58
@vrvinodchandar Please let me know if you still need help else, we will proceed with the issue closure. Thanks.

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-22 11:06
@vrvinodchandar We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-12-22 11:06 UTC
Labels: Event Grid, customer-reported, needs-author-feedback, no-recent-activity, CXP Attention, Auto-Assign
