### ISSUE TITLE
`az acs kubernetes get-credentials` should use ssh-agent if available

### ISSUE THREAD

**Issue by jseely** [Azure/azure-cli#2612] opened 2017-03-23 16:17 UTC
Currently `az acs kubernetes get-credentials` will by default look for an ssh-key in `~/.ssh/id_rsa` or use an ssh key file provided through the `--ssh-key-file`. It appears this key is just being used to ssh into the master node in the cluster, so it should be able to use keys stored in the ssh-agent on the local machine.

**Comment by brendandburns** [comment] 2017-04-22 04:40
Did it not work? According to the docs here:

http://docs.paramiko.org/en/2.1/api/client.html

It looks like parimiko should be trying to talk to an ssh-agent if one is running...

**Comment by rjtsdl** [comment] 2017-10-12 23:47
@jseely can you confirm the issue is resolved or not?

**Comment by yugangw-msft** [comment] 2019-07-27 00:41
closing as the `az acs` are deprecating

**Closed by yugangw-msft** 2019-07-27 00:41 UTC
Labels: ACS, Service Attention
