### ISSUE TITLE
AKS cli install - SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)

### ISSUE THREAD

**Issue by VipinAgarwal** [Azure/azure-cli#11555] opened 2019-12-11 19:55 UTC
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
Traceback (most recent call last):
CLI2\lib\urllib\request.py, ln 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
CLI2\lib\http\client.py, ln 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
CLI2\lib\http\client.py, ln 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
CLI2\lib\http\client.py, ln 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
...
Azure\CLI2\lib\ssl.py, ln 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)


CLI2\lib\urllib\request.py, ln 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.63 *

```

**Comment by jluk** [comment] 2019-12-12 20:08
@VipinAgarwal I'm unable to reproduce your issue on cli build 2.0.77 could you please do an upgrade of the cli tool and retry?

```
➜  ~ az aks install-cli
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/darwin/amd64/kubectl"
Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.

➜  ~ az --version
azure-cli                         2.0.77

command-modules-nspkg              2.0.3
core                              2.0.77
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.0.77/libexec/bin/python'
Extensions directory '/Users/justin/.azure/cliextensions'

Python (Darwin) 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by jluk** [comment] 2019-12-16 22:13
@VipinAgarwal I'm going to close this for now, but please revisit and comment if an upgrade does not fix this and I can re-open.

**Closed by jluk** 2019-12-16 22:13 UTC
Labels: AKS, Service Attention

**Comment by arinmupenn** [comment] 2020-02-12 22:29
I am using the following 

az version:

az --version
azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.0.81/libexec/bin/python'
Extensions directory '/Users/arindammukherjee/.azure/cliextensions'

Python (Darwin) 3.8.1 (default, Dec 27 2019, 18:05:50) 
[Clang 10.0.0 (clang-1000.11.45.5)]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

I am still getting the same error. Any help is appreciated.

Thanks,
Arindam
