### ISSUE TITLE
FunctionApp:Unable to show webapp configuration

### ISSUE THREAD

**Issue by BenD10** [Azure/azure-cli#20566] opened 2021-11-30 20:47 UTC
## Describe the bug

**Command Name**
`az webapp show`

**Errors:**
The command failed with an unexpected error. Here is the traceback:
```
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 605, in show_webapp
    return _show_app(cmd, resource_group_name, name, "webapp", slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 734, in _show_app
    "Unable to find {} '{}', in RG '{}'".format(cmd_app_type.value, name, resource_group_name),
AttributeError: 'str' object has no attribute 'value'

```

## To Reproduce:
Steps to reproduce the behavior.
Run the following command for any valid resource group and function app.
- `az webapp show -g $RESOURCE_GROUP -n $FUNCTION_APP_NAME`

## Environment Summary
```
Linux-5.11.0-40-generic-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
azure-iot 0.11.0

```

**Comment by yonzhan** [comment] 2021-11-30 23:10
route to service team

**Comment by Kotasudhakarreddy** [comment] 2021-12-01 12:00
Duplicate of #20437

**Closed by Kotasudhakarreddy** 2021-12-01 12:00 UTC
Labels: Web Apps, Service Attention, customer-reported
