### ISSUE TITLE
az vm extension delete: does not print completion

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#764] opened 2016-08-26 17:14 UTC
```
$ az vm extension delete -g ahmet-test --vm-name myvm -n CustomScript
Starting vm extension delete
$
```

**Comment by tjprescott** [comment] 2016-08-26 19:38
This is what the service call returns. Are you expecting the output to be the VM showing the extension no longer associated?

**Comment by ahmetalpbalkan** [comment] 2016-08-26 20:26
Are you sure "Starting" is returned by the service? I assumed it's a client generated message which is missing a "Completed" equivalent. 

Most commands don't print progress messages as far as observed in the CLI. But this one does. Seems inconsistent.

**Comment by tjprescott** [comment] 2016-08-26 20:35
All of the long running operations print "Starting <command name>" and none of them print a completion message. You indication that the operation completed is that you have your cursor back. :) The LRO commands will return whatever the server returns, but in the case of deletes that is often nothing.

**Comment by johanste** [comment] 2016-08-26 20:39
At one point, we had a starting command, followed by a “dots running across my screen every second” followed by a “done” command. It was suggested that this did very little in ways of helping the user understand what is happening, and that being chatty actually degrades the overall experience (especially for scripting) and we removed most of it. The begin message is likely a left-over from those earlier days and should (in my opinion) also be removed.

**Comment by tjprescott** [comment] 2016-08-26 20:41
Closing since this is by design.

**Comment by johanste** [comment] 2016-08-26 20:42
I would suggest that either we should print a matching start/done pair OR we should be quiet altogether. I prefer the latter.

**Comment by johanste** [comment] 2016-08-26 20:43
I would suggest that either we should print a matching start/done pair OR we should be quiet altogether. I prefer the latter.

**Comment by ahmetalpbalkan** [comment] 2016-08-26 20:59
> All of the long running operations print "Starting <command name>" and none of them print a completion message. Your indication that the operation completed is that you have your cursor back. :)

Please don't do this. I agree with @johanste here. Either you print progress a lot or you just don't do anything. You can't just say "Starting" and prompt me back to cursor.

To me this behavior totally feels like the program started to do something and just crashed without printing a completion message, so let me `echo ExitCode=$?` to see if it actually failed.

On many operating systems, if your process gets killed due to far too many reasons (such as segmentation faults or other low-level runtime jazz) it will just silently exit and it will exactly look like what you currently do.

**Comment by derekbekoe** [comment] 2016-08-26 21:02
I'd vote to remove that print statement as well.
The code that does this is [here](https://github.com/Azure/azure-cli/blob/master/src/azure/cli/commands/__init__.py#L96).

I'll create a PR to remove that line. If a user still wants the status, it's output to logger.info.

**Closed** 2016-08-26 22:08 UTC
