### ISSUE TITLE
`az functionapp plan show` doesn't return exit code 1 at non-existing resource

### ISSUE THREAD

**Issue by kipal** [Azure/azure-cli#14572] opened 2020-07-29 10:40 UTC
```az functionapp plan show``` returns exit code 0 when the resource doesn't exist.

**Command Name**
`az functionapp plan show`

**Errors:**

## To Reproduce:
- `az functionapp plan show -n {} -g {}`

## Expected Behavior
It should return with a non-zero exit code.

## Environment Summary
```
Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.9.1

Extensions:
application-insights 0.1.7

```
## Debug log
```
Command arguments: ['functionapp', 'plan', 'show', '-n', 'plan', '-g', 'resource-group', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f8eb5ab4ea0>, <function OutputProducer.on_global_arguments at 0x7f8eb5a90ea0>, <function CLIQuery.on_global_arguments at 0x7f8eb5a41158>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'functionapp': ['azure.cli.command_modules.appservice']
Loading command modules:
Name                  Load Time    Groups  Commands
appservice                0.128        58       204
Total (1)                 0.128        58       204
These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_ai_did_you_mean_this']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
Total (0)                 0.000         0         0  
Loaded 58 groups, 204 commands.
Found a match in the command table for 'functionapp plan show'
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f8eb55b9bf8>]
az_command_data_logger : command args: functionapp plan show -n {} -g {} --debug
metadata file logging enabled - writing logs to '/home/user/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f8eb558ec80>]
attempting to read file /opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json as utf-8-sig
attempting to read file /opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json as utf-8-sig
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f8eb558eae8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f8eb558ebf8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f8eb5a90f28>, <function CLIQuery.handle_query_parameter at 0x7f8eb5a411e0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f8eb558eb70>]
Getting management service client client_type=WebSiteManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
attempting to read file /home/user/.azure/accessTokens.json as utf-8-sig
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - Authority:Performing instance discovery: ...
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - Authority:Performing static instance discovery
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - Authority:Authority validated via static instance discovery
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Found 4 potential entries.
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Resource specific token found.
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'Y/l81TmNKaZsGcP/u2zaYT1WC9ZywRsL7L1VEg2gsgU=', RefreshTokenId: b'bKOjgTL7EjBcHw1OrsXnfERJrLzU246hpI1S2AcdPU8='
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Cached token is expired at 2020-07-29 12:01:02.561544.  Refreshing
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - TokenRequest:called to refresh a token from the cache
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - TokenRequest:Getting a new token from a refresh token
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /cfd26b50-fb8f-44cf-87b2-d5df3d15d884/oauth2/token HTTP/1.1" 200 3219
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - OAuth2Client:Get Token Server returned this correlation_id: f3695632-f2c6-4753-8ff8-647061fbd229
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Created new cache entry from refresh response.
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Removing entry.
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Adding entry AccessTokenId: b'mIfE1xJcZ1SSOIbKyO7LN7/cUf/uCzzbGdN6pPK11t8=', RefreshTokenId: b'L3901ig/zu/DhJ0CMnmkrDaA/gzpn177/2Up59iVGdw='
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Updating 3 cached refresh tokens
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Remove many: 3
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Add many: 3
adal-python : f3695632-f2c6-4753-8ff8-647061fbd229 - CacheDriver:Returning token refreshed after expiry.
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/0098c991-644b-4aed-8792-41d5e208c1c4/resourceGroups/resource-group/providers/Microsoft.Web/serverfarms/plan?api-version=2019-08-01'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'User-Agent': 'python/3.6.10 (Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid) msrest/0.6.9 msrest_azure/0.6.3 azure-mgmt-web/0.47.0 Azure-SDK-For-Python AZURECLI/2.9.1 (DEB)'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/0098c991-644b-4aed-8792-41d5e208c1c4/resourceGroups/resource-group/providers/Microsoft.Web/serverfarms/plan?api-version=2019-08-01 HTTP/1.1" 404 243
msrest.http_logger : Response status: 404
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-request-id': 'c0f756e2-5a45-42b5-82ea-4f92f3989bb2'
msrest.http_logger :     'x-ms-correlation-request-id': 'c0f756e2-5a45-42b5-82ea-4f92f3989bb2'
msrest.http_logger :     'x-ms-routing-request-id': 'GERMANYWESTCENTRAL:20200729T103549Z:c0f756e2-5a45-42b5-82ea-4f92f3989bb2'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Wed, 29 Jul 2020 10:35:49 GMT'
msrest.http_logger :     'Content-Length': '243'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/serverFarms/plan' under resource group 'resource-group' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f8eb5587840>, <function _x509_from_base64_to_hex_transform at 0x7f8eb55878c8>]
Event: CommandInvoker.OnFilterResult []
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f8eb55b9e18>]
az_command_data_logger : exit code: 0
telemetry.save : Save telemetry record of length 2536 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /home/user/.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
Command ran in 4.616 seconds (init: 0.024, invoke: 4.591)
```

**Comment by yonzhan** [comment] 2020-07-29 23:44
functionapp

**Comment by apawast** [comment] 2020-07-30 18:18
@yonzhan is there any guidance for a this type of scenario where a command succeeds, but it's executed against a non-existent resource?

**Comment by MyronFanQiu** [comment] 2020-07-31 02:17
@apawast Azure CLI would exit with code 3 if server return 404. The logic is correct in functionapp command module. The root cause for this issue is that python sdk won't treat 404 as an error. In the [swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/5699b02c38fc1d90220e7e62c399ea5a5df30b7e/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/AppServicePlans.json#L140-L141), we should not set 404. If we set it, all SDK would treat 404 as a success instead of a failure. Please fix the swagger, regenerate the SDK and bump the dependency of azure-cli.

**Comment by apawast** [comment] 2020-08-13 18:10
@gzuber to investigate

**Comment by navba-MSFT** [comment] 2022-03-22 10:27
@kipal Apologies for the late reply. The similar issue was discussed here. https://github.com/Azure/azure-cli/issues/17424
The PR was filed for this https://github.com/Azure/azure-cli/pull/18475 . The issue is now fixed. Please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of AzCLI and check if you are facing any issue. Awaiting you reply.

**Closed** 2022-04-13 08:01 UTC
Labels: Service Attention, Functions, customer-reported, needs-author-feedback, no-recent-activity
