### ISSUE TITLE
"az network nic create" command should display warning message or be blocked when updating existing NIC

### ISSUE THREAD

**Issue by tatazoe** [Azure/azure-cli#8753] opened 2019-03-11 06:53 UTC
**Is your feature request related to a problem? Please describe.**
"az network nic create" command change existing NIC setting without warnings.
This will impose very high risk of unexpected mis-configuration.

    [Version]
    azure-cli 2.0.59 *
    
    [How to reproduce]
    # Create resource group and vNet
    az group create --name Dev_test01 --location japaneast
    az network vnet create \
      --name vNet_dev01 \
      --resource-group Dev_test01 \
      --subnet-name subnet01 \
      --address-prefixes 10.100.1.0/24 \
      --subnet-prefixes 10.100.1.0/24 \
      --location "japaneast"
    
    #  Create new NIC
    az network nic create --vnet-name "vNet_dev01" --subnet "subnet01" --resource-group "Dev_test01" --name test_nic --location "japaneast"   --private-ip-address "10.100.1.4"
    az network nic show --resource-group "Dev_test01" --name test_nic --query ipConfigurations[0].privateIpAddress
    -->"10.100.1.4"
    
    # Update NIC information with "create" option
    az network nic create --vnet-name "vNet_dev01" --subnet "subnet01" --resource-group "Dev_test01" --name test_nic --location "japaneast" --private-ip-address "10.100.1.100"
    az network nic show --resource-group "Dev_test01" --name test_nic --query ipConfigurations[0].privateIpAddress
    --> "10.100.1.100" ** IP address is changed without warning

**Describe the solution you'd like**
1. Display warning message and pause the process.
2. Change specification to prohibit "az network nic create" for nic updating. Allow "az network nic update" or "az network nic  ip-config update" command for NIC updating.

**Comment by tjprescott** [comment] 2019-03-11 17:09
This is by design and is true for nearly all create commands in the CLI. There is an open issue already to offer an opt-in safety net for all create commands (#7613). Since this ask is covered by that, I will close this issue.

**Closed by tjprescott** 2019-03-11 17:09 UTC
