### ISSUE TITLE
az network route-table create is not idempotent

### ISSUE THREAD

**Issue by olandese** [Azure/azure-cli#10970] opened 2019-10-24 14:11 UTC
**Describe the bug**
If run az network route-table create on an existing route table with existing routes, all the routes are gone/deleted

**To Reproduce**

1. Create a route table: az network route-table create --name myroutetable --g myresourcegroup
2. Add user defined routes to it
3. Rerun:  az network route-table create --name myroutetable --g myresourcegroup
4. the routes added in step 2 are gone 

**Expected behavior**
The route table and the existings routes are still there

**Comment by MyronFanQiu** [comment] 2019-10-25 01:28
@olandese Hello. I will take a look soon. Due to low bandwidth now, it may take some time.

**Comment by qwordy** [comment] 2020-04-28 03:49
The status after 3 is same as status after 1. I thinks it's reasonable.
Your expectation also makes sense.

**Comment by MyronFanQiu** [comment] 2020-05-07 05:59
@olandese Right now, from Azure CLI perspective, we don't keep idempotent in `create` command right now. It's reasonable to have same status after the third command with the first command since they're same. I prefer keeping the current behavior.

**Comment by MyronFanQiu** [comment] 2020-05-12 08:30
Closed this issue since it's by design. If anyone want to change the design, please vote for this issue.

**Closed by MyronFanQiu** 2020-05-12 08:30 UTC
Labels: Network, OKR3.4 Candidate
