### ISSUE TITLE
az k8s-configuration flux create results in python error

### ISSUE THREAD

**Issue by DwCloudDabo** [Azure/azure-cli#27866] opened 2023-11-17 02:21 UTC
### Describe the bug

I run the command `az k8s-configuration flux create ... ` and get instantly an error instead of getting the configuration that I want.

### Related command

az k8s-configuration flux create

### Errors

```
The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.PublicKey._ec_ws': Not found '_ec_ws.cp311-win_amd64.pyd', Cannot load '_ec_ws.pyd': cannot load library 'C:\Users\xyz\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.pyd': error 0xc1
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 561, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 521, in load_arguments
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 318, in load_arguments
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xyz\.azure\cliextensions\k8s-configuration\azext_k8s_configuration\providers\FluxConfigurationProvider.py", line 38, in <module>
    from ..validators import (
  File "C:\Users\xyz\.azure\cliextensions\k8s-configuration\azext_k8s_configuration\validators.py", line 18, in <module>
    from Crypto.PublicKey import RSA, ECC, DSA
  File "C:\Users\xyz\.azure\cliextensions\k8s-configuration\Crypto\PublicKey\ECC.py", line 57, in <module>
    _ec_lib = load_pycryptodome_raw_lib("Crypto.PublicKey._ec_ws", """
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\.azure\cliextensions\k8s-configuration\Crypto\Util\_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.PublicKey._ec_ws': Not found '_ec_ws.cp311-win_amd64.pyd', Cannot load '_ec_ws.pyd': cannot load library 'C:\Users\xyz\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.pyd': error 0xc1
```

### Issue script & Debug output

Script is like
```
az k8s-configuration flux create --cluster-name $clusterFqdn `
    --cluster-type 'managedClusters' `
    --name $clusterFqdn `
    --namespace 'flux-system' `
    --resource-group $clusterFqdn `
    --url 'abc' `
    --branch 'cba' `
    --kustomization name='flux' path='./flux' prune=true `
    --scope 'cluster' `
    --https-key $key `
    --https-user $user
```

The debug output is the error.

### Expected behavior

I expected that a flux configuration would be created.

### Environment Summary

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.171
amg                                0.1.1
application-insights              0.1.16
azure-devops                      0.26.0
connectedk8s                      1.2.11
cosmosdb-preview                  0.14.0
k8s-configuration                  1.7.0
k8s-extension                      1.5.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xyz\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment] 2023-11-17 02:21
Thank you for opening this issue, we will look into it.

**Comment by DwCloudDabo** [comment] 2023-11-17 17:07
> Hi @DwCloudDabo Find similar issue #19562.
> 
> Issue title	az k8s-configuration show failure
> Create time	2021-09-14
> Comment number	7
> Possible solution: As mentioned in that issue, the root cause of the problem is that the 'pycryptodome' dependency was not installed when the 'k8s-configuration' extension was installed. The fix for this issue will be rolled out on 12/07. In the meantime, you can try installing pycryptodome by directly installing it using "pip install". If possible, you can also try removing the extension and reinstalling it to see if that resolves the issue. We apologize for any inconvenience this may have caused and thank you for trying out our CLI extension.
> 
> Please confirm if this resolves your issue.

Unfortunately this does not work.

**Comment by NarayanThiru** [comment] 2024-01-08 18:39
@bavneetsingh16 , can you pl. take a look at this?

**Comment by bavneetsingh16** [comment] 2024-02-04 19:10
The cause for the failure mentioned above. The new release should have fixed the issue.

**Comment by bavneetsingh16** [comment] 2024-07-02 19:45
@yonzhan, can you please close this issue as the issue is resolved.

**Closed** 2024-07-02 23:44 UTC
Labels: bug, Service Attention, customer-reported, Kubernetes Configuration, Auto-Assign, Auto-Resolve, Similar-Issue, Possible-Solution
