### ISSUE TITLE
ACR Issue with tags

### ISSUE THREAD

**Issue by LudwigTirazona** [Azure/azure-cli#7438] opened 2018-09-28 07:49 UTC
**Describe the bug**

I'm importing images twice into an ACR from another ACR. I'm importing them twice because I need two tags for the image: 
1.) the actual version, e.g. "1.0.1"
2.) a "latest" tag

Example:
```
az acr import -n marinastaging --source marinadevelopment.azurecr.io/myrepo:1.0.1 --force

az acr import -n marinastaging --source marinadevelopment.azurecr.io/myrepo:1.0.1 -t myrepo:latest --force
```

After doing that, the latest tags will not show up when looked up via the Azure Web interface.

They will also not show up when performing an "az acr repository show-tags --detail". 
Doing a "az acr repository show" on the repo will only show the old tag count.

But doing "az acr repository show-tags" shows all of the new tags created via "az acr import". 

**To Reproduce**

Import an image from another ACR twice into the current ACR using the ff:
```
az acr import -n marinastaging --source marinadevelopment.azurecr.io/myrepo:1.0.1 --force
az acr import -n marinastaging --source marinadevelopment.azurecr.io/myrepo:1.0.1 -t myrepo:latest --force
```
Check via the Azure Web Interface, "az acr repository show-tags -n marinastaging --repository myrepo --detail -o tsv", and "az acr repository show -n marinastaging --repository myrepo". Those tags will not be visible/reflected.

However, doing a "az acr repository show-tags -n marinastaging --repository myrepo" will show the new tags.

**Expected behavior**
Tags will be visible and queryable via the Azure Web Interface and the Azure CLI.

**Environment summary**
OS: Ubuntu 18.04
az version: 2.0.46
 az installed via apt with instructions from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

**Additional context**
See screenshot. Only the command in the middle shows the tags, but in the two other commands, certain tags are not present or accounted for.

![screenshot_20180928_154818](https://user-images.githubusercontent.com/800073/46195155-13a48700-c336-11e8-8bf7-f7bc2daebb46.png)

**Comment by ehotinger** [comment] 2018-09-29 01:32
@djyou + @NatalieGong 
/cc @sajayantony

**Comment by djyou** [comment] 2018-09-29 01:51
Hi @LudwigTirazona, there is a known issue with import image API that certain metadata is not populated. We are rolling out a fix and it will be available in all regions by next week.

As you said, the workaround right now is to use the `az acr repository show-tags` command without `--detail` option.

There is no data corruption, all your images can still be pulled. /cc @yuwaMSFT2

**Comment by LudwigTirazona** [comment] 2018-10-01 00:39
@djyou , thanks for the info.

Is there a workaround so I can see the SHA hashes of the imported images?

A use case of mine is I need to be able to know which tags actually point to the same image.

**Comment by djyou** [comment] 2018-10-02 20:45
@LudwigTirazona This issue has been fixed from server side. Could you please try the commands again?

**Comment by LudwigTirazona** [comment] 2018-10-03 00:35
@djyou, looks good.

Missing data are now showing properly, thanks!

**Comment by sajayantony** [comment] 2018-10-16 21:47
Including @yuwaMSFT2 to investigate this. Is this delayed and is there eventual consistency?

**Comment by yuwaMSFT2** [comment] 2018-10-16 22:47
The event generated by ImageImport didn't have correct timestamp. Working on a fix.

**Comment by LudwigTirazona** [comment] 2018-10-17 00:19
@sajayantony, just ran the "show-tags" command again with the "--detail" option, the 1.0.3-13 tag is still not showing.

**Comment by yuwaMSFT2** [comment] 2018-10-17 01:36
Thanks @LudwigTirazona for your patience. Will have you updated on the progress.

**Comment by LudwigTirazona** [comment] 2018-10-25 06:39
Hello @yuwaMSFT2, is there an estimate on when this will be fixed? I'm still seeing import-based issues where tags don't exist or aren't being updated, even when --force is used.

**Comment by yuwaMSFT2** [comment] 2018-10-26 18:08
@LudwigTirazona currently the fix is being deployed region by region. Most likely it will reach WUS on 10/31. Will let you know once it's in place.

**Comment by yuwaMSFT2** [comment] 2018-11-01 19:30
@LudwigTirazona can you please try it again and let me know if it works for you now? Thanks!

**Comment by LudwigTirazona** [comment] 2018-11-12 07:02
@yuwaMSFT2 , can confirm that everything is normal now, thanks! Tag metadata are being updated almost instantly.

**Comment by LudwigTirazona** [comment] 2018-11-13 05:50
Sorry about this, @yuwaMSFT2 , but I'm having the same issue again after I deleted a repo, and created it again.

```
ljtirazona@ludwig:~$ az acr import -n marinastaging --source reekohdevelopment.azurecr.io/reekoh/users-api:1.2.2-1 --force --verbose
ljtirazona@ludwig:~$ az acr import -n marinastaging --source reekohdevelopment.azurecr.io/reekoh/users-api:1.2.2-1 -t reekoh/users-api:latest --force --verbose
ljtirazona@ludwig:~$ az acr repository show-tags -n marinastaging --repository reekoh/users-api --detail

ljtirazona@ludwig:~$ az acr repository show-tags -n marinastaging --repository reekoh/users-api
Result
--------
1.2.2-1
latest

```

**Comment by yuwaMSFT2** [comment] 2018-11-13 07:11
Thanks @LudwigTirazona. We are investigating and will have you updated.

**Comment by yuwaMSFT2** [comment] 2018-11-13 07:43
@LudwigTirazona When you get chance can you try again? Thanks!

**Comment by dibraser** [comment] 2019-06-06 09:30
Hello everyone

Maybe I can give some additional information about this. IMHO this problem only occurs if a repository has >10 tags for the same digest. This behaviour can only be reproduces if the same digest has this many tags, maybe thats why it aint detected earlier in this thread.

**Explanation**
Azure az currently offers three interresting commands for our case:

1. az acr show-tags which correctly shows all tags for a given repository in a given registryy
2. az acr repository show which shows information about an image with a specific tag oder digest
3. az acr repository show-manifests which shows information about all images in a repository

To reproduce, we're trying to find an image in our repository with tag 201905291416 and digest sha256:217...495

The command "show-tags" correctly lists all tags of a repository, in our case:

` az acr repository show-tags -n [our-container-registry] --repository [our-repo]`
... output is:
`
[
  "20190320.2",
  "20190423.2",
  "201905151829",
  "201905151850",
  "201905151914",
  "201905151929",
  "201905201454",
  "201905201509",
  "201905201534",
  "201905201609",
  "201905201650",
  "201905211606",
  "201905211741",
  "201905291341",
  "201905291416",
  "latest",
  "stable"
]
`

As you can see, that tag is listed third from last, so far everything is fine.

BUT when trying to get repository-information by

`
 az acr repository show-manifests -n [our-container-registry] --repository [our-repo]
`
we get the following output: 
`
 {
    "digest": "sha256:217...495",
    "tags": [
      "201905151829",
      "201905151850",
      "201905151914",
      "201905151929",
      "201905201454",
      "201905201509",
      "201905201534",
      "201905201609",
      "201905201650",
      "201905211606"
    ],
    "timestamp": "2019-05-15T16:44:17.5285623Z"
  }
`

As you can see here, tag 201905291416 is missing in the tag-array. There are only 10 tags displayed, but actually this image has more tags associated.

Also trying to get information for exaclty that digest does not list all tags:
`
az acr repository show -n [our-container-registry] [our-registry]@sha256:217....495
`
... and get this output:
`
...
"tags": [
    "201905151829",
    "201905151850",
    "201905151914",
    "201905151929",
    "201905201454",
    "201905201509",
    "201905201534",
    "201905201609",
    "201905201650",
    "201905211606"
  ] ...
`

To prove that, we're listing information for that missing image, which seems to exist if we trust the Azure Portal and the first command listing all tags:
`
az acr repository show -n [our-container-registry] --image [our-registry]:201905291416
`
and boom we get the expected output:
` ...
"digest": "sha256:217fc18f15ba93759945d56c2af3fa2662138014360d5bc6575915dbc7c04495",
...
  "name": "201905291416",
...
`

After some research we even tried some options like --top [>10] trying to exceed that limit, but this doensn't make any changes. 

This behaviour is very dangerous due I cannot rely on the output of these commands! I need to double-check every digest and tag if there's anywhere something missing.

I hope you'll find a way to fix that issue soon.

**Comment by yuwaMSFT2** [comment] 2019-06-26 19:37
@dibraser This is by design for now.
The show manifest command is primarily used to show manifest attributes. Associated tags is just one of them. When there are too many tags, we do not know how to show them all effectively, as we cannot do paging for the associated tags. Showing all tags becomes dangerous and also impractical (how will Cli show all the associated tags in the manifest attribute?). As a result, we decided to only show a subset of 10 associated tag for the manifest, primarily to just let user know that there are many tags associated with the manifest. 

In order to show the complete tags, you need to call show tags, and the filter by the manifest.

We probably can consider to add filter parameter for show tags so it only shows tags associated with a manifest. You can open a separate issue as feature request.

**Comment by yugangw-msft** [comment] 2019-10-02 10:11
Closing, as the original issue was considered fixed. @LudwigTirazona, please let us know otherwise
@dibraser, please open a new issue per suggestion from @yuwaMSFT2.

**Closed by yugangw-msft** 2019-10-02 10:11 UTC
Labels: Bug, Container Registry, Service Attention
