### ISSUE TITLE
Unable to create private endpoints in CLI using bash terminal

### ISSUE THREAD

**Issue by lchave** [Azure/azure-cli#13687] opened 2020-05-26 14:05 UTC
## Describe the bug

**Command Name**
`az network private-endpoint create`

**Errors:**
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/b526aa26-e5c4-4583-90a3-6d0a4663242a/resourceGroups/rg-eu2-network/providers/Microsoft.Network/privateEndpoints/pe-eu2-iris-dev-006?api-version=2020-03-01 (Caused by ResponseError('too many 500 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network private-endpoint create --name {} --resource-group {} --vnet-name {} --subnet {} --location {} --private-connection-resource-id {} --group-id {} --connection-name {} --tags {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: 

azure-cli 2.6.0

Extensions:
interactive 0.4.4

```

**Comment by yungezz** [comment] 2020-05-26 14:14
hi @MyronFanQiu, could you pls have a look?

**Comment by yonzhan** [comment] 2020-05-26 14:24
add to S170

**Comment by MyronFanQiu** [comment] 2020-05-27 09:09
@lchave Hi, Are you targeting at Private Link Service? --group-id is not needed for private link service. Or do you have any name containing `'` or `"`? Could you run the command with `--debug`?

**Comment by lchave** [comment] 2020-05-27 14:52
@MyronFanQiu The group-id is just passing a variable defined in a previous step. When i run the `--debug` I see that the `--private-connection-resource-id` is sending the id with an `\r` at the end of it which is not added by us. The way we are getting the resource id is by running the `az resource show` and specifying the `--query` parameter to get the id. When I echo the variable defined to hold this ID it doesn't show the `\r` however, when calling the variable on the `az network private-endpoint create` it adds it. Any suggestions on this?

**Comment by MyronFanQiu** [comment] 2020-05-28 03:03
@lchave I see. Thanks for such useful information. @jiasli @zhoxing-ms Any idea?

**Comment by zhoxing-ms** [comment] 2020-05-28 03:17
Related issue: #13573

**Comment by zhoxing-ms** [comment] 2020-05-28 03:36
@lchave This problem seems to be related to Windows style newline characters, there is a similar problems here:
https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile

Bash expects that end-of-line in a script is always and only a newline `\n` character, Unix-style, not a carriage return-newline combination `\r\n` like you normally see on Windows. 
Bash thinks the `\r` character is just an ordinary character at the end of the string. 

Could you try to execute the command `dos2unix` for the scripts executed in Windows?

**Comment by jiasli** [comment] 2020-05-28 04:06
Hello @lchave,

1. May I know the shell you are using, Mintty, Cygwin, MinGW? We haven't heard of this issue before with PowerShell on Windows or Bash on Linux. I doubt the output is not parsed correctly by the shell. 
2. Could you share a full code snippet so that we can repro?

**Comment by lchave** [comment] 2020-05-28 21:51
@jiasli I've tried on WSL, Bash & Git Bash terminals from Visual Studio on Windows. As per the code, if you can share your MS email I can send the code to reproduce it.

@zhoxing-ms this looks accurate, however, this command runs on files and I'm just trying to pass this variable within my code to complete deployments.

**Comment by zhoxing-ms** [comment] 2020-05-29 04:54
@lchave Hi, please send them to jiasli@microsoft.com and Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment] 2020-06-28 03:43
I have reproduced this problem in the WSL environment and identified the root cause:
The newline character in WSL is `LF` and the newline character in windows is `CRLF`. Therefore, when a script written under Windows is used in WSL, only `\n` in the newline character `\r\n` of `CRLF` is recognized as the newline character of `LF`, while `\r` is recognized as plain text.

For example:
1. Write a bash script in Windows, which is in CRLF format:
The script content:
```bash
group_name=$(az group show -n zhoxing-test --query name)
echo $group_name
az group create -l westus --debug -n $group_name
```

2. Execute the script in the WSL environment
```bash
root@DESKTOP-S8GCCTE:/mnt/c/Users/zhoxing.FAREAST/Desktop# file test.sh
test.sh: ASCII text, with CRLF line terminators

root@DESKTOP-S8GCCTE:/mnt/c/Users/zhoxing.FAREAST/Desktop# bash test.sh
"zhoxing-test"
Command arguments: ['group', 'create', '-l', 'westus', '--debug', '-n', '"zhoxing-test"\r\r']
```
At this point, the value of `group_name` is added with `\r` due to incompatibility between WSL and windows newline character.

3. Convert the file format from `CRLF` to `LF` and then execute the script
```bash
root@DESKTOP-S8GCCTE:/mnt/c/Users/zhoxing.FAREAST/Desktop# dos2unix test.sh
dos2unix: converting file test.sh to Unix format...

root@DESKTOP-S8GCCTE:/mnt/c/Users/zhoxing.FAREAST/Desktop# file test.sh
test.sh: ASCII text

root@DESKTOP-S8GCCTE:/mnt/c/Users/zhoxing.FAREAST/Desktop# bash test.sh
"zhoxing-test"
Command arguments: ['group', 'create', '-l', 'westus', '--debug', '-n', '"zhoxing-test"']
```
Problem solving after the file format becomes `LF`.

@lchave The same is true even if the value of the variable is not written directly in the file but is returned from a query (as the example I provided). So when using `CRLF` files in Unix and Unix-like Systems (including WSL), you need to convert the file to `LF` (you can use the command `dos2unix`)

For more information, please refer to: https://en.wikipedia.org/wiki/Newline

**Comment by zhoxing-ms** [comment] 2020-07-08 03:27
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-07-08 03:27 UTC
Labels: Infrastructure, OKR3.2 Candidate, environment-compatibility, feature-request
