### ISSUE TITLE
"az functionapp create --app-insights" doesn't link Application Insights

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#15176] opened 2020-09-16 00:14 UTC
## Describe the bug

Attempting to create a new functionapp and link to an existing Application Insights instance. The key appears to be saved but `--app-insights` doesn't seem to do anything.

**Command Name**
`az functionapp create -g MyGroup -n MyFunctionApp --disable-app-insights false --app-insights em --app-insights-key $APP_INSIGHTS_KEY -s $STORAGE_ACCOUNT  --consumption-plan-location westus2 --assign-identity --functions-version 3`

**Errors:**
No errors from the CLI but after creation, Function App is not linked to Application Insights. 
![image](https://user-images.githubusercontent.com/1231630/93277241-be5a1e00-f776-11ea-846c-2ffa13b5fdb9.png)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az functionapp create -g MyGroup -n MyFunctionApp --disable-app-insights false --app-insights em --app-insights-key $APP_INSIGHTS_KEY -s $STORAGE_ACCOUNT  --consumption-plan-location westus2 --assign-identity --functions-version 3`
- View Application Insights tab in Azure Portal

## Expected Behavior
Creating a functionapp with provided Application Insights instance links the two

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.11.1

Extensions:
application-insights 0.1.11

```

**Comment by seanknox** [comment] 2020-09-16 00:17
I tried providing a fake app-insights name and the CLI didn't process it as an error. Maybe I'm misunderstanding what `--app-insights` does?

`az functionapp create -g MyGroup -n MyFunctionApp --disable-app-insights false --app-insights totally-fake-name-doesnt-exist ...`

**Comment by yonzhan** [comment] 2020-09-16 04:51
functionapp

**Comment by apawast** [comment] 2020-09-17 18:24
@seanknox --app-insights and --app-insights-key are mutually exclusive, you should only be using one or the other. If you use just --app-insights-key does it work? We can also do some work to enhance the experience and make it clear what should happen.

**Comment by ergihu** [comment] 2020-09-20 17:33
Second this: I cannot get Function App to be linked to Application Insights with Azure CLI.

If I create the Function App with the command

az functionapp create \
  --name "MyFunctionApp" \
  --resource-group "MyGroup" \
  --consumption-plan-location "westeurope" \
  --os-type Linux \
  --runtime node \
  --functions-version 3 \
  --assign-identity '[system]' \
  --storage-account "MyStorageAccount" \
  --app-insights "MyAlreadyCreatedAppIns"

the result is that APPINSIGHTS_INSTRUMENTATIONKEY is visible in the output of "az functionapp config appsettings list -g MyGroup -n MyFunctionApp" and in the Configuration in portal, but the Function App is not linked to the Application Insights, says the portal, just like in the screenshot in the original post.

If I then link the Function App to Application Insights via portal, the same command "az functionapp config appsettings list -g MyGroup -n MyFunctionApp" shows both APPINSIGHTS_INSTRUMENTATIONKEY and APPLICATIONINSIGHTS_CONNECTION_STRING. These can also be seen in the Configuration in portal.

If instead of linking via portal I add APPLICATIONINSIGHTS_CONNECTION_STRING with "az functionapp config appsettings set", it shows up in the Configuration, but still the portal tells me that the linking is not there.

"az functionapp show -g MyGroup -n MyFunctionApp" doesn't show anything related to Application Insights whether the Function App is linked to Application Insights or not.

In which resource property is the linking actually configured and visible programmatically?

---
Environment:
WSL2 on Windows 10 Enterprise, OS Build 18363.1082
azure-cli                         2.11.1
application-insights              0.1.11
Python (Linux) 3.6.10 (default, Aug 28 2020, 06:40:03)

**Comment by apawast** [comment] 2020-09-24 18:09
@ehamai is this a portal issue? What permission does portal look for to check if App Insights is configured?

**Comment by mgressman** [comment] 2020-10-19 18:46
I would say this is fundamentally an Azure issue. There are two other open issues from two other sources that point to the same problem.

Can't do it from [Terraform](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8909).

Can't do it from the Azure [portal](https://docs.microsoft.com/en-us/answers/questions/131172/application-insights-not-connected-to-azure-functi.html).

Since it can't be done from Terraform, and it can't even be done in the Azure portal, I am going to guess all methods will suffer the same issue until it is fundamentally fixed within the Azure ecosystem.

**Comment by ChaitanyaNaykodi-MSFT** [comment] 2020-10-23 19:22
Hello All, just to add on to the observation made by @ergihu, even I observed that the APPINSIGHTS_INSTRUMENTATIONKEY and APPLICATIONINSIGHTS_CONNECTION_STRING are configured in the app settings and the metrics are getting funneled to Application Insights instance. The issue is with the portal UX as it does not reflect this connection, the team will be rolling out a fix for this issue soon, the current timeline is November 1st week.

**Comment by jmeadowcroft** [comment] 2021-09-21 22:05
@ChaitanyaNaykodi-MSFT Looks like its been a year since the last update and still no fix. Do you have any insights on the current status? Thanks

**Comment by RakeshMohanMSFT** [comment] 2022-09-20 06:29
This is fixed.
![image](https://user-images.githubusercontent.com/49954584/191183451-d31d73b6-a069-441e-a19f-18ddb3aee528.png)

![image](https://user-images.githubusercontent.com/49954584/191183531-34fb987d-6cbe-404d-9969-9a39a3991188.png)

**Closed by RakeshMohanMSFT** 2022-09-20 06:29 UTC
Labels: Service Attention, Functions
