### ISSUE TITLE
Issue in az network vpn-connection show

### ISSUE THREAD

**Issue by AshsihGarg** [Azure/azure-cli#15836] opened 2020-11-09 06:46 UTC
## Describe the bug

**Command Name**
`az network vpn-connection show`

**Errors:**
```
'Response' object has no attribute 'status'
Traceback (most recent call last):
azure/cli/core/adal_authentication.py, ln 103, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
...

azure/cli/core/adal_authentication.py, ln 114, in set_token
    .format(err.response.status, err.response.reason))
AttributeError: 'Response' object has no attribute 'status'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vpn-connection show --resource-group {} --name {} --output {} --query {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yonzhan** [comment] 2020-11-09 10:17
network

**Comment by haroldrandom** [comment] 2020-11-10 06:43
Would you mind post the value of `--query {}` ?

**Comment by AshsihGarg** [comment] 2020-11-10 07:00
here you go ... query '{Name:name,ConnectionStatus:connectionStatus}

**Comment by haroldrandom** [comment] 2020-11-11 05:52
@AshsihGarg The issue is known and the fixture patch should be merged in this Sprint.

**Closed** 2020-11-11 08:42 UTC
Labels: Network
