### ISSUE TITLE
azure cli proxy connection issue from windows 

### ISSUE THREAD

**Issue by MNH1623** [Azure/azure-cli#21696] opened 2022-03-18 15:02 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.1
```

**Comment by yonzhan** [comment] 2022-03-18 15:05
@jiasli for awareness

**Comment by Sanjib-Chowdhury** [comment] 2022-03-26 17:48
Hi,

Try this & share the outcome -

1. convert the Sever certificate (if not using proxy)/ proxy certificate (if using proxy) using OpenSSL/ Portecle or similar tools
2. Download run the script from https://github.com/Sanjib-Chowdhury/407-proxy-authentication-required-CERTIFICATE_VERIFY_FAILED-from-AWS-Azure-Git-NPM-CLI

**Comment by jiasli** [comment] 2022-03-28 03:03
@Sanjib-Chowdhury, thanks for the script. 

### ⚠️ For anyone else, please be aware this script is not provided by Microsoft. Please use it with caution!

**Comment by jiasli** [comment] 2022-03-28 03:06
@MNH1623, please make sure you have followed the link https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy to configure the root CA properly.

**Comment by jiasli** [comment] 2022-08-25 09:08
Duplicate of #19571

**Closed by jiasli** 2022-08-25 09:08 UTC
Labels: Account, customer-reported, Proxy, Auto-Assign
