### ISSUE TITLE
Support Azure Functions .NET runtime 3.0

### ISSUE THREAD

**Issue by jvandertil** [Azure/azure-cli#11746] opened 2020-01-02 15:58 UTC
**Is your feature request related to a problem? Please describe.**
I am unable to create a Azure Functions App that uses the .NET Core 3.1 runtime (runtime version 3).
It should be available according to the [docs](https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-versions), but the CLI only supports version 2.

**Describe the solution you'd like**
Adding '3' as an allowed version in `--runtime-version` when using `--runtime dotnet`.

**Describe alternatives you've considered**
Currently I have to switch the runtime to 3.x in the Azure portal, but I want to create the app with the correct settings.

**Additional context**
I was deploying an application with dependency injection that targetted `netcoreapp3.1` using the .NET Core 3.1 dependency injection extensions, and I ran into this bug: https://github.com/Azure/azure-functions-dotnet-extensions/issues/29

When I wanted to adjust my provision script to set the runtime to the correct version, I was unable to.

**Comment by fabiocav** [comment] 2020-01-07 19:20
This is a duplicate of https://github.com/Azure/azure-cli/issues/11349
Please follow that issue for updates.

**Closed by fabiocav** 2020-01-07 19:20 UTC
Labels: Feature Request, Functions, Service Attention
