### ISSUE TITLE
az login PersistenceDecryptionError

### ISSUE THREAD

**Issue by emiledufour** [Azure/azure-cli#23497] opened 2022-08-10 14:29 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az login

**Describe the bug**
az login returns the following error after browser login:

> Decryption failed: [WinError 0] None. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

Deleting the .azure folder and retrying will work after several attempts, but any subsequent command involving Azure CLI will result in the same PersistenceDecryptionError, taking me back to square one.

**To Reproduce**
Run 'az login'

**Expected behavior**
az login should work everytime

**Environment summary**
Installed through azure-cli-2.39.0.msi
azure-cli                         2.39.0
core                              2.39.0
telemetry                          1.0.6 *
OS: Windows 10 Version 1909 (OS Build 18363.2274)
Shell Type: Bash on Windows, also tried cmd.exe with same result

**Additional context**

**Comment by yonzhan** [comment] 2022-08-10 14:30
@jiasli for awareness

**Comment by ramfattah** [comment] 2022-08-11 23:18
@emiledufour,

Looks like I was not able to repro from my end.

#### Environment

* azure-cli 2.39.0
* core 2.39.0
* OS: Windows 11
* Windows Terminal: Powershell


#

After running the command
`az login`

It appears I was successfully logged in without issue after the browser opened:
![image](https://user-images.githubusercontent.com/38049078/184257606-7844a42e-e75f-489d-a56a-e5d6fd8e6363.png)

**Comment by jiasli** [comment] 2022-08-23 15:35
Duplicate of https://github.com/Azure/azure-cli/issues/20278

**Closed by jiasli** 2022-08-23 15:35 UTC
Labels: bug, Account, customer-reported, Auto-Assign, Azure CLI Team
