### ISSUE TITLE
Template deployment fails with no details

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#6075] opened 2018-04-10 18:52 UTC
az cli on windows
azure-cli (2.0.27)

az group deployment create results in the error below with no details:
"The template deployment failed with multiple errors. Please see details for more information."

If I deploy the template in the portal, I can see that the deployment fails due to an Azure Policy.

**Comment by derekbekoe** [comment] 2018-04-10 19:07
Is more information available if you run the command with --debug?

**Comment by Teodelas** [comment] 2018-04-13 01:11
Yes, but it it’s a bit buried where it shows up:

msrest.http_logger : b'{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment failed with multiple errors. Please see details for more information.","details":[{"code":"RequestDisallowedByPolicy","target":"sqlserverdrmtcefs35ypg","message":"Resource \'sqlserverdrmtcefs35ypg\' was disallowed by policy. Policy identifiers: \'[{\\"policyDefinitionId\\":\\"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c\\",\\"policyAssignmentId\\":\\"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policyAssignments/076600eccae24751850c1942\\",\\"policySetDefinitionId\\":\\"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policySetDefinitions/ba09b1e1-59b9-4488-91d6-076ca9dd2098\\"}]\'.","innererror":{"policyInfo":[{"policyDefinitionDisplayName":"Allowed locations","policySetDefinitionDisplayName":"Allowed Locations","policyAssignmentDisplayName":"Allowed Locations","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c","policySetDefinitionId":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policySetDefinitions/ba09b1e1-59b9-4488-91d6-076ca9dd2098","policyDefinitionReferenceId":"11585898879207960213","policySetDefinitionName":"ba09b1e1-59b9-4488-91d6-076ca9dd2098","policyDefinitionName":"e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionEffect":"deny","policyAssignmentId":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policyAssignments/076600eccae24751850c1942","policyAssignmentName":"076600eccae24751850c1942","policyAssignmentScope":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589","policyAssignmentSku":{"name":"A1","tier":"Standard"},"policyAssignmentParameters":{"LISTOFALLOWEDLOCATIONS_1":{"value":["eastus","centralus","eastus2","westus","westus2"]}}}]}},{"code":"RequestDisallowedByPolicy","target":"sqlserverdrmtcefs35ypg/AuditLogDB","message":"Resource \'sqlserverdrmtcefs35ypg/AuditLogDB\' was disallowed by policy. Policy identifiers: \'[{\\"policyDefinitionId\\":\\"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c\\",\\"policyAssignmentId\\":\\"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policyAssignments/076600eccae24751850c1942\\",\\"policySetDefinitionId\\":\\"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policySetDefinitions/ba09b1e1-59b9-4488-91d6-076ca9dd2098\\"}]\'.","innererror":{"policyInfo":[{"policyDefinitionDisplayName":"Allowed locations","policySetDefinitionDisplayName":"Allowed Locations","policyAssignmentDisplayName":"Allowed Locations","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c","policySetDefinitionId":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policySetDefinitions/ba09b1e1-59b9-4488-91d6-076ca9dd2098","policyDefinitionReferenceId":"11585898879207960213","policySetDefinitionName":"ba09b1e1-59b9-4488-91d6-076ca9dd2098","policyDefinitionName":"e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionEffect":"deny","policyAssignmentId":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policyAssignments/076600eccae24751850c1942","policyAssignmentName":"076600eccae24751850c1942","policyAssignmentScope":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589","policyAssignmentSku":{"name":"A1","tier":"Standard"},"policyAssignmentParameters":{"LISTOFALLOWEDLOCATIONS_1":{"value":["eastus","centralus","eastus2","westus","westus2"]}}}]}},{"code":"RequestDisallowedByPolicy","target":"apiservicedrmtcefs35ypg","message":"Resource \'apiservicedrmtcefs35ypg\' was disallowed by policy. Policy identifiers: \'[{\\"policyDefinitionId\\":\\"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c\\",\\"policyAssignmentId\\":\\"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policyAssignments/076600eccae24751850c1942\\",\\"policySetDefinitionId\\":\\"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policySetDefinitions/ba09b1e1-59b9-4488-91d6-076ca9dd2098\\"}]\'.","innererror":{"policyInfo":[{"policyDefinitionDisplayName":"Allowed locations","policySetDefinitionDisplayName":"Allowed Locations","policyAssignmentDisplayName":"Allowed Locations","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c","policySetDefinitionId":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policySetDefinitions/ba09b1e1-59b9-4488-91d6-076ca9dd2098","policyDefinitionReferenceId":"11585898879207960213","policySetDefinitionName":"ba09b1e1-59b9-4488-91d6-076ca9dd2098","policyDefinitionName":"e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionEffect":"deny","policyAssignmentId":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/providers/Microsoft.Authorization/policyAssignments/076600eccae24751850c1942","policyAssignmentName":"076600eccae24751850c1942","policyAssignmentScope":"/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589","policyAssignmentSku":{"name":"A1","tier":"Standard"},"policyAssignmentParameters":{"LISTOFALLOWEDLOCATIONS_1":{"value":["eastus","centralus","eastus2","westus","westus2"]}}}]}}]}}'
msrest.exceptions : The template deployment failed with multiple errors. Please see details for more information.
The template deployment failed with multiple errors. Please see details for more information.

**Comment by tjprescott** [comment] 2019-04-26 21:03
This issue is incredibly out of date. Closing. If still a problem, please open a new issue.

**Closed by tjprescott** 2019-04-26 21:03 UTC
Labels: Resource Manager-cli

**Comment by RobertoPrevato** [comment] 2023-12-05 13:24
For what is worth, the issue is still relevant. Working with Azure Policies enabled still makes for an extremely poor user experience because error messages are useless.

This happens even enabling debug:

```ps1
New-AzSubscriptionDeployment @params -DeploymentDebugLogLevel ResponseContent -verbose -ErrorAction Stop

VERBOSE: Using Bicep v0.22.6
VERBOSE: Calling Bicep with arguments: build "main.bicep" --outdir "C:\Users\...\AppData\Local\Temp\550b1bd7-6ce2-43d3-9d90-ac419e83267c"

WARNING: The DeploymentDebug setting has been enabled. This can potentially log secrets like passwords used in resource property or listKeys operations when you retrieve the deployment operations through Get-AzResourceGroupDeploymentOperation
New-AzDeployment: 2:17:38 PM - Error: Code=InvalidTemplateDeployment; Message=The template deployment failed with multiple errors. Please see details for more information.
```

The only information I get is: `The template deployment failed with multiple errors. Please see details for more information.`.

Being part of IT in a company, and trying to enforce policies on colleagues who will get useless error messages and likely waste hours over these, make me wonder if using Azure Policies is truly good for the business.
