### ISSUE TITLE
Got CLIInternalError when logging in to Azure with command "az login"

### ISSUE THREAD

**Issue by vinh75002** [Azure/azure-cli#15972] opened 2020-11-18 22:49 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
local variable 'token_entry' referenced before assignment
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-s90ugolk\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 717, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 710, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-7f66x3i5\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-_1bqfhco\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\profile\custom.py, ln 158, in login
pip-unpacked-wheel-_1bqfhco\azure\cli\core\_profile.py, ln 195, in find_subscriptions_on_login
pip-unpacked-wheel-_1bqfhco\azure\cli\core\_profile.py, ln 875, in find_through_authorization_code_flow
UnboundLocalError: local variable 'token_entry' referenced before assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.15.0

```

**Comment by yonzhan** [comment] 2020-11-19 12:35
az login

**Comment by jiasli** [comment] 2020-11-19 12:36
Duplicate of #15961

**Comment by jiasli** [comment] 2020-11-19 12:38
This is a known issue and we are working on a fix. To get over it, please use a valid pair of username + password.

**Closed** 2020-12-31 02:32 UTC
Labels: Account, OKR3.2 Candidate, feature-request
