### ISSUE TITLE
Error creating an webapp

### ISSUE THREAD

**Issue by johnverwoerd** [Azure/azure-cli#12229] opened 2020-02-16 14:44 UTC
## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
update_site_config() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 657, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/custom.py, ln 135, in create_webapp
    match['setter'](cmd, match, site_config)
TypeError: update_site_config() takes 2 positional arguments but 3 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --resource-group {} --plan {} --name {} --runtime {} --deployment-local-git`

## Environment Summary
```
Linux-4.15.0-1067-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

```

**Comment by arrownj** [comment] 2020-02-17 01:36
@johnverwoerd , thanks for reporting, we are looking at it.

**Comment by panchagnula** [comment] 2020-02-17 02:32
This because of the --runtime parameter same as. https://github.com/Azure/azure-cli/issues/12159. Please use the Edge builds or run the command without the  --runtime parameter.

**Comment by johnverwoerd** [comment] 2020-02-17 07:36
Ok thanks @panchagnula

**Comment by hihorika** [comment] 2020-02-18 11:37
Hi @panchagnula 

I see same error when executing `az webapp create` specified runtime by `java|1.8|Tomcat|8.5` or other value which are listed by `az webapp list-runtimes` as following.

```
$ az webapp list-runtimes
[
    :
  "java|11|Tomcat|8.5",
    :
]
$ az webapp create --resource-group $RESOURCE_GROUP --name $SITE_NAME --plan $PLAN_NAME --runtime "java|1.8|Tomcat|9.0"
The command failed with an unexpected error. Here is the traceback:


update_site_config() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially           results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 135, in create_webapp     match['setter'](cmd, match, site_config)
TypeError: update_site_config() takes 2 positional arguments but 3 were given

```

I always have updated Azure CLI to 2.1.0 as following.

```
$ az --version
azure-cli                          2.1.0

command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/hihorika/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Feb 14 2020, 05:22:57)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.
```

Could you please check this behavior of the command?

**Comment by panchagnula** [comment] 2020-02-18 17:30
@hihorika yes the regression is mainly in code path that retrieves runtime version. and is fixed by this release https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md

**Comment by hihorika** [comment] 2020-02-18 19:29
Thanks @panchagnula 
But this error of `az webapp create --runtime` happens on Azure CLI 2.1.0.

Could you please check it again ?

**Closed** 2020-03-11 05:43 UTC
Labels: Service Attention, Web Apps
