### ISSUE TITLE
webapp:Azure deployment source config - changing branch doesn't seem to work

### ISSUE THREAD

**Issue by pjfsilva** [Azure/azure-cli#3650] opened 2017-06-09 21:36 UTC
### Description

I have a webapp where I already configure my git deployment integration. Now I want to quickly change the branch I'm using but it seems that the branch never changes.

I'm running 
```
az webapp deployment source config --repo-url MY_REPO_URL --branch staging --name MY_APP --resource-group MY_RESOURCE
```
The output seems ok: Finished and shows the right branch. Then I run the sync command but it seems the branch isn't really changed. Checking my site\deployments\settings.xml file using KUDU also shows old branch is still there. Basically branch didn't change.

Seems to me like a bug but please advise if I should be running something else. In CLI 1.0, in theory we had a command to only change branches so that's a good thing to have also in CLI 2.0

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.7)

**OS Version:** What OS and version are you using?  
Windows 7

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
cmd.exe

**Comment by yugangw-msft** [comment] 2017-06-12 23:49
I will fix this in CLI. The root cause is the another webapp service api weirdness, that no error was reported when it was not able to finish off the work.

**Comment by ahmedelnably** [comment] 2017-11-09 18:57
@panchagnula can you please check if the work around is working, if yes let's close this issue

**Comment by yugangw-msft** [comment] 2017-11-09 19:15
//CC:@mayurid
We probably should leave these issues along, which are tagged with "ServiceAttn", as someone from SDK team will reach to your team in future for possible fixes at the service end.

**Comment by panchagnula** [comment] 2019-06-28 01:19
Closing this since this is old & from the previous notes not something we will fix on the client side. Please open a new issue if this is still a problem. Thank you,

**Closed by panchagnula** 2019-06-28 01:19 UTC
Labels: App Services, Bug, Service Attention
