### ISSUE TITLE
Instructions do not work for default Visual Studio Code online Linux host

### ISSUE THREAD

**Issue by BharathNimmala-MSFT** [Azure/azure-cli#11339] opened 2019-11-21 08:13 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
This a escalation from CLI GitHub docs repo 
https://github.com/microsoftdocs/azure-docs-cli/issues/1649 

Appears to be Ubuntu 18.04.1 (output of uname -a is "Linux 4f95409cc772 5.0.0-1023-azure #24~18.04.1-Ubuntu SMP Wed Oct 2 20:23:29 UTC 2019 x86_64 GNU/Linux.") Fails on "lsb_release -cs."

Help needed to understand if there is any ongoing issues which team is aware of , which might affect on what customer is trying to evaluate with Visual studio code online Linux host. 

**To Reproduce**
Customer is following this documentation https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback , but getting the following error 

**Expected behavior**
The steps in the docs should work. 

**Environment summary**
Ubuntu 18.04.1 

**Additional context**
Please help evaluate any product related issues or its primarily doc needs to be updated

**Comment by fengzhou-msft** [comment] 2019-11-22 09:51
Thanks for reporting the issue. I will investigate.

**Comment by fengzhou-msft** [comment] 2019-11-29 09:55
I created a Ubuntu 18.04 vm and `uname -a` shows
`Linux feng-ubuntu-18 5.0.0-1025-azure #27~18.04.1-Ubuntu SMP Mon Nov 11 15:19:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

I cannot reproduce the issue. `lsb_release -cs` gives me `bionic` as expected.

**Comment by alexvy86** [comment] 2019-12-05 18:09
I have a similar issue,  `lsb_release -cs` gives me `stretch` (Debian?), even though `uname -a` says Ubuntu, and in fact when selecting the VM for my VSO environment, there were only Ubuntu options.

![image](https://user-images.githubusercontent.com/716334/70261395-f5b38d00-1757-11ea-9a57-06525ec7913f.png)

This environment is in EastUS, in case that's relevant.

**Comment by fengzhou-msft** [comment] 2019-12-09 07:16
@alexvy86 I set up a vsonline VM and can reproduce your result. azure-cli can be installed successfully. 

This is more likely an issue with the VM system implementation for `lsb_release` and `uname`. There's a discrepancy here.

**Comment by yonzhan** [comment] 2019-12-15 13:25
@alexvy86 any update? Can we close this issue?

**Comment by alexvy86** [comment] 2019-12-16 21:20
Well, I didn't report the issue... I haven't checked if the VMs created by VS Online now behave correctly (`lsb_release -cs` and `uname -a` not contradicting each other) but I'd say maybe you can close this issue, since it doesn't have to do with Azure cli directly?

**Closed** 2019-12-18 02:09 UTC
