### ISSUE TITLE
{VirtualWan} Support RoutingIntent resource

### ISSUE THREAD

**Issue by nagula-ritvika** [Azure/azure-cli#22817] opened 2022-06-09 17:51 UTC
1. Resource provider : Az.Network
2. Description of feature or work requested : https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1179 
3. Minimum API version required. What is the minimum API version of your service required to implement your feature? 2020-11-01
4. Swagger link: https://github.com/Azure/azure-rest-api-specs/pull/15998/files
5. Target date : July end(https://github.com/Azure/azure-cli/blob/dev/doc/onboarding_guide.md#extension-vs-module).
6. Status of the service. Is it in preview or GA? : public preview
7. Prerequisite to use this feature. Whitelisting subscription? Registering the feature for subscription? Is it available in public Azure?  : Available in public Azure

**Comment by yonzhan** [comment] 2022-06-09 22:48
network

**Comment by necusjz** [comment] 2022-06-17 02:13
@nagula-ritvika, may I ask, it this issue a duplicate of https://github.com/Azure/azure-cli/issues/22795?

**Closed** 2022-06-21 02:31 UTC
Labels: Network, feature-request
