### ISSUE TITLE
az interactive not working

### ISSUE THREAD

**Issue by jwrightazure** [Azure/azure-cli#9341] opened 2019-05-08 17:57 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
cannot import name 'DEFAULTS_SECTION'
Traceback (most recent call last):
Temp\pip-install-v1m4qsu_\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 611, in _run_job
Local\Temp\pip-install-v1m4qsu_\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 453, in default_command_handler
azure\cli\command_modules\interactive\custom.py, ln 31, in start_shell
.azure\cliextensions\interactive\azext_interactive\__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
cliextensions\interactive\azext_interactive\azclishell\app.py, ln 35, in <module>
    from azure.cli.core._config import DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64

Extensions:
interactive 0.4.1

```

**Comment by tjprescott** [comment] 2019-05-08 18:15
Dupe of pinned issue #9260.

**Closed by tjprescott** 2019-05-08 18:15 UTC
