### ISSUE TITLE
On-board API Management Service

### ISSUE THREAD

**Issue by sdementen** [Azure/azure-cli#3614] opened 2017-06-04 10:20 UTC
### Description

I would like to manage my API Management Service instances via the azure cli and I could not find the command for this. Is support for APIM yet to be added ?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

**OS Version:** What OS and version are you using?  
Answer here: win7

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by tjprescott** [comment] 2017-06-05 16:13
Hi @sdementen this service is currently not supported.

@mayurid, there is a Swagger spec for this service but no SDK support.

**Comment by mayurid** [comment] 2017-06-05 17:36
@sdementen : thanks for the request. I will follow up with the team and get back to you asap.

**Comment by sdementen** [comment] 2017-07-27 15:50
Any news regarding this issue ?

**Comment by angrox** [comment] 2017-09-18 10:07
Any news?

**Comment by boker** [comment] 2018-01-30 02:35
This is amazing.. so you close this by providing a reference to #5067 and then you close #5067 by saying that that is a duplicate of the current issue.

**Comment by tjprescott** [comment] 2018-01-30 16:45
@boker this issue isn't closed and hasn't been closed.

**Comment by angrox** [comment] 2018-02-03 15:40
Again the question: Any news? At least the product owner could state that it is not on the list for the next X month? (We worked around using Ansible and curl requests. But it *is* ugly)

**Comment by tjprescott** [comment] 2018-02-06 00:58
@KedarJoshi for comment.

**Comment by karel1980** [comment] 2018-06-02 05:04
@tjprescott it's June. Still on target?

**Comment by tjprescott** [comment] 2018-06-05 15:58
The service team is responsible for on-boarding their commands, not the CLI team.  @KendarJoshi @twitchax for comment.

**Comment by twitchax** [comment] 2018-06-05 21:56
@KedarJoshi, can you give an update here, please?

**Comment by KedarJoshi** [comment] 2018-06-07 16:41
Unfortunately, due to other priorities we had to postpone this work.  Please feel free to add Azure CLI request for APIM @ http://aka.ms/apimwish . This will tremendously help us prioritize this work accordingly.

There are obviously lot of other option for automation including ARM templates, PS cmdlets, REST API.  

Totally understand that if you have built all other automation using CLI then it is easier to use the same set of tooling and I apologize for inconvenience.

Thanks,
Kedar

**Comment by tjprescott** [comment] 2018-06-07 17:08
I have created the requested issue here:

https://feedback.azure.com/forums/248703-api-management/suggestions/34482196-on-board-commands-to-azure-cli-2-0

**Comment by kevinhillinger** [comment] 2019-07-26 15:32
This week, myself and @jonlester have created the initial set of service commands for APIM in #10074 PR. Our objective is to get APIM module in preview support, and continue to contribute to APIM by developing the most requested subcommand modules. Right now, having worked in the field with many customers, I think the list includes:

- api
- certificate
- product
- subscription

**Comment by yugangw-msft** [comment] 2019-08-22 11:57
done

**Closed by yugangw-msft** 2019-08-22 11:57 UTC
Labels: H2-2019, New Service
