### ISSUE TITLE
Wrong API is called by AZ cmd "az ad sp credential list" 

### ISSUE THREAD

**Issue by Xuzhou-Huang** [Azure/azure-cli#20764] opened 2021-12-17 06:12 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

By running **"az ad sp credential list"**, we find Rest API "https://graph.chinacloudapi.cn/<tenant id>/ **applications** /<app id>/passwordCredentials" is called, which make it returns credential of application rather than that of service principal.

DEBUG: msrest.http_logger: Request URL: 'https://graph.chinacloudapi.cn/954ddad8-xxxx152d9587/applications/4c142b1f-xxxxx1cc81f2f/passwordCredentials?api-version=1.6'
DEBUG: msrest.http_logger: Request method: 'GET'

Compared with the powershell command **"Get-AzADSpCredential"**, the API called is https://graph.chinacloudapi.cn/<tenant id>/**servicePrincipals**/<sp id>/passwordCredentials, which is the correct one.

**To Reproduce**

az login
az ad sp credential list --id xxxx

**Expected behavior**

"az ad sp credential list" should provide the credentials of the service principal with API "https://graph.chinacloudapi.cn/<tenant id>/**servicePrincipals**/<sp id>/passwordCredentials" called.

**Environment summary**

az --version
azure-cli                         2.31.0

core                              2.31.0
telemetry                          1.0.6

Extensions:
ssh                                1.0.0

**Additional context**

**Comment by jiasli** [comment] 2021-12-17 08:26
Duplicate of #11458

**Closed** 2021-12-22 07:41 UTC
Labels: question, Graph, customer-reported
