### ISSUE TITLE
Interactive CLI not showing parameters

### ISSUE THREAD

**Issue by hajekj** [Azure/azure-cli#5375] opened 2018-01-23 11:00 UTC
I have recently discovered, that the CLI 2.0 in interactive mode stopped displaying the parameter hints for commands. For example, I only get the "-o" and "-h" parameters for each of the commands, nothing else gets listed. The same is happening on both my Windows (MSI installation) and WSL (apt-get installation) environments. When I checked in the Azure Shell (https://shell.azure.com/bash) the parameter hinting doesn't seem to work either...

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
C:\Users\hajek>az --version
azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\hajek\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
```

**Comment by tjprescott** [comment] 2018-01-23 17:55
Duplicate of #5284.

**Closed by tjprescott** 2018-01-23 17:55 UTC
