### ISSUE TITLE
(Mac) az cli for Azure Bot Service is failing across the board (az bot ...)

### ISSUE THREAD

**Issue by lynn-orrell** [Azure/azure-cli#7463] opened 2018-10-02 02:45 UTC
**Describe the bug**
az bot create/delete/update/publish/... is failing with the following error:

_**ModuleNotFoundError: No module named 'azure.mgmt.botservice'**_

**To Reproduce**
Install az cli
Install bot extension
Attempt to run az bot create/delete/update/publish/...

**Expected behavior**
Commands should execute without throwing a ModuleNotFoundError

**Environment summary**
MacOS High Sierra 10.13.6

**Additional context**
See full information here: https://github.com/Microsoft/botbuilder-tools/issues/533

**Comment by tjprescott** [comment] 2018-10-02 15:36
Dupe of #7448. Will be fixed in the next release.

**Closed by tjprescott** 2018-10-02 15:36 UTC
