### ISSUE TITLE
The group deployment list --top does not work as expected.

### ISSUE THREAD

**Issue by manojvazirani** [Azure/azure-cli#9983] opened 2019-07-19 19:29 UTC
## Describe the bug

**Command Name**
`az group deployment list`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

1. Complete multiple deployments.
2. List deployments with --top 1.
3. Lists all deployments instead of the top 1 deployment.

- _Put any pre-requisite steps here..._
- `az group deployment list -g {} --top {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.66 *

Extensions:
interactive 0.4.1

```

**Comment by yugangw-msft** [comment] 2019-07-20 15:44
@Tiano2017 , this is a service end bug, can you cross check whether this `top` query string still works?
Please check out the full uri below, as you can tell Azure CLI does supply the `top` query string 
``` 
GET /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourcegroups/deploy/providers/Microsoft.Resources/deployments/?%24top=1&api-version=2018-05-01&%24skiptoken=... 
```

**Comment by snaheth** [comment] 2020-09-01 00:23
Duplicate of #8953

**Closed by snaheth** 2020-09-01 00:23 UTC
Labels: ARM, ARM - Templates, Resource Manager-cli, Service Attention, bug
