### ISSUE TITLE
Invalid validation rules for registry name in ACR

### ISSUE THREAD

**Issue by skudryk** [Azure/azure-cli#8984] opened 2019-04-04 07:02 UTC
Environment: Cloud shell at https://portal.azure.com

The rules used to validate resource group for AKS are invalid and misleading:

1)  i was able to create cluster using this command:

serhii@Azure:~$ az aks create --resource-group Helloguest_RG --name HelloguestCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys

notice that in returned output JSON  resource group listed under specified name:

{
  "aadProfile": null,
 ..
  "agentPoolProfiles": [
    {
      "count": 1,
      "maxPods": 110,
      "name": "nodepool1",
      "osDiskSizeGb": 100,
      "osType": "Linux",
      "storageProfile": "ManagedDisks",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": null
    }
  ],
  ....
  "location": "eastus",
  "name": "HelloguestCluster",
  ..
  "provisioningState": "Succeeded",
  "resourceGroup": "Helloguest_RG",
....
  "type": "Microsoft.ContainerService/ManagedClusters"
}

2)  then i tried to create Azure Container Registry in order to be able to login to it but get weird error about invalid resource name:

serhii@Azure:~$ az acr create  --resource-group=Helloguest_RG --name microsoft.aks-20190403081426 --sku Basic
The command failed with an unexpected error. Here is the traceback:

Parameter 'registry_name' must conform to the following pattern: '^[a-zA-Z0-9]*$'.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 402, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/custom.py", line 104, in acr_create
    return client.create(resource_group_name, registry_name, registry)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerregistry/v2018_09_01/operations/registries_operations.py", line 351, in create
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerregistry/v2018_09_01/operations/registries_operations.py", line 276, in _create_initial
    'registryName': self._serialize.url("registry_name", registry_name, 'str', max_length=50, min_length=5, pattern=r'^[a-zA-Z0-9]*$')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 592, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 672, in validate
    raise ValidationError(key, name, value)

msrest.exceptions.ValidationError: Parameter 'registry_name' must conform to the following pattern: '^[a-zA-Z0-9]*$'.

Expected result : first command should failed with validation error  or second command shouldn't produce any validation error.

**Comment by jluk** [comment] 2019-12-17 00:12
Assigning to ACR as this is not AKS validation being done.

**Comment by yonzhan** [comment] 2020-05-02 13:39
ACR

**Comment by jluk** [comment] 2020-05-02 18:57
Removing AKS tag as this is an ACR error

**Comment by toddysm** [comment] 2020-06-25 22:46
@skudryk The first command does validation for the AKS cluster while the second command does validation for the ACR you are trying to create. The error in the second command is that the name of the ACR cannot have the special symbols that you added (see the pattern). This is an expected behavior and it is by design.

**Closed by toddysm** 2020-06-25 22:46 UTC
Labels: ACR, Container Registry, Service Attention, customer-reported
