### ISSUE TITLE
az vm extenstion delete timed out and left the "provisioningState": "Deleting"

### ISSUE THREAD

**Issue by ajay15283** [Azure/azure-cli#14106] opened 2020-06-25 17:24 UTC
az vm extension delete timed out and left the extension in "deleting" state and re installation fails with below error

Operation 'PUT Extension' is not allowed on VM extension 'OmsAgentForLinux' since it is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete).

azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.4.10 (default, Dec 13 2019, 16:20:47) [GCC]

Legal docs and information: aka.ms/AzureCliLegal

[
  {
    "autoUpgradeMinorVersion": false,
    "forceUpdateTag": null,
    "id": "/subscriptions/XXXXX/resourceGroups/XXXXXXX/providers/Microsoft.Compute/virtualMachines/XXXXXXX/extensions/OmsAgentForLinux",
    "instanceView": null,
    "location": "northeurope",
    "name": "OmsAgentForLinux",
    "protectedSettings": null,
    "provisioningState": **"Deleting"**,
    "publisher": "Microsoft.EnterpriseCloud.Monitoring",
    "resourceGroup": "XXXXXXXXXX",
    "settings": {
      "workspaceId": "XXXXXXXXXXXXXXX"
    },
    "tags": null,
    "type": "Microsoft.Compute/virtualMachines/extensions",
    "typeHandlerVersion": "1.12",
    "virtualMachineExtensionType": "OmsAgentForLinux"
  }
]

**Comment by yungezz** [comment] 2020-06-28 01:44
hi @qwordy could you pls have a look?

**Comment by qwordy** [comment] 2020-06-29 07:00
Have you retried the delete operation or waited for an ongoing one to complete?

**Comment by ajay15283** [comment] 2020-06-29 15:46
I waited for a while it was in a "Deleting" state .approx after 3 to 4 hours it changed to "Failed" state but if i retry again it timed out leaving the extension in "Deleting" state . 

To Test I removed the extension rpm packages from the VM and cleaned up all relevant directories but still the az-cli extension list command  still shows the extension details so i am not sure how it checks the extension traces.

**Comment by qwordy** [comment] 2020-09-16 06:35
If "provisioningState" is "Deleting" forever, it seems a service problem.

**Comment by Drewm3** [comment] 2020-09-16 23:17
@amjads1, could you please look into this issue.

**Comment by amjads1** [comment] 2020-09-17 17:18
Looking into the issue.

**Comment by amjads1** [comment] 2020-09-22 02:38
Working with 'OmsAgentForLinux' extension team to identify the issue and get additional details. Sent a follow up today again and I will update as soon as I have more details.

**Comment by amjads1** [comment] 2020-10-01 04:58
Followed up with the extension owner multiple times, still waiting for the response. I will continue to track and update as soon as I have more information available.

**Comment by amjads1** [comment] 2020-10-05 21:40
@ajay15283 , @qwordy - Can you try these following steps that helps to understand on how to remove the OMS agent. These steps should help when portal/waagent think the extension is in the wrong state. 

Per OMSLinuxAgent team, only removing the RPM/DEB packages won't make waagent/ARM 'believe' that the extension is uninstalled. 

Please try these steps and update if this resolve the issue.

**Comment by amjads1** [comment] 2020-10-09 19:06
@ajay15283 , @qwordy - Following up to check if the issue is resolved. Let me know if you need any additional help.

**Comment by amjads1** [comment] 2020-11-02 05:19
@ajay15283 , @qwordy - I wanted to follow up and check if you need any further help on this issue. I will go ahead and close this issue tomorrow assuming that issue is resolved.

**Comment by amjads1** [comment] 2020-11-05 18:58
Closing this issue assuming that issue is resolved. Feel free to re-open if you need any further assistance. Thanks!

**Closed by amjads1** 2020-11-05 18:58 UTC
Labels: Compute - Extensions, Service Attention

**Comment by jarrettprosser** [comment] 2023-01-11 01:22
Not the OP, but I had this issue and following the steps that @amjads1 posted above, with some minor changes, resolved my issue. In step 5.2 I had to run `service walinuxagent stop`, and in step 6 I needed to check for packages with `dpkg -l`. Thanks!
