### ISSUE TITLE
az staticwebapp delete doesn't work

### ISSUE THREAD

**Issue by paulaustin-automutatio** [Azure/azure-cli#18653] opened 2021-06-26 01:20 UTC
[Enter feedback here]

There doesn't seem to be a way to delete a static web app. Either through Azure Portal or this command.

They all complete, but don't actually  delete the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e683c181-f005-a6c8-cb11-74ce557e51f8
* Version Independent ID: 860411b7-f2f1-af2b-b5e2-7d67e1b8e028
* Content: [az staticwebapp](https://docs.microsoft.com/en-us/cli/azure/staticwebapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/staticwebapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/staticwebapp.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2021-06-26 01:57
route to service team

**Comment by seligj95** [comment] 2021-07-08 14:34
closing. unable to reproduce. successfully deleted static web app from portal and cli.

az staticwebapp delete -n <app name>

and 

"delete" button in portal

**Closed by seligj95** 2021-07-08 14:34 UTC
Labels: Service Attention, Web Apps
