### ISSUE TITLE
WindowsTerminal: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

### ISSUE THREAD

**Issue by sabieler** [Azure/azure-cli#14108] opened 2020-06-25 21:47 UTC
## Describe the bug

**Command Name**
`az vm list`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm list`

## Expected Behavior
List available VMs, which does work from Azure Shell application. This time the command has been issued from WindowsTerminal-Azure Cloud Shell

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yonzhan** [comment] 2020-06-26 15:28
400 Client Error

**Comment by yungezz** [comment] 2020-06-28 01:41
this is duplicate issue with #11749. Pls try rerun `az login` to work around. Corresponding team is working on fixing it.

**Comment by maertendMSFT** [comment] 2020-09-30 23:15
Can we close this as a dupe of https://github.com/Azure/azure-cli/issues/11749 ?

**Closed** 2020-10-01 09:06 UTC
Labels: Cloud Shell, Service Attention
