### ISSUE TITLE
az login not working

### ISSUE THREAD

**Issue by austin-altaml** [Azure/azure-cli#20138] opened 2021-11-01 21:39 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 152, in login
    subscriptions = profile.find_subscriptions_on_login(
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 201, in find_subscriptions_on_login
    subscriptions = subscription_finder.find_through_authorization_code_flow(
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 929, in find_through_authorization_code_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 973, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
  File "/Users/austingoebel/opt/anaconda3/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 891, in create_arm_client_factory
    client = client_type(credentials, api_version=api_version,
TypeError: __init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
macOS-10.16-x86_64-i386-64bit, Darwin 21.1.0
Python 3.8.8
Installer: PIP

azure-cli 2.29.2
azure-cli-ml 1.33.0

Extensions:
azure-cli-ml 1.33.0

```

**Comment by yonzhan** [comment] 2021-11-01 22:54
@jiasli for awareness

**Comment by jiasli** [comment] 2021-11-12 07:12
Duplicate of #18626

**Closed by jiasli** 2021-11-12 07:12 UTC
Labels: Account, customer-reported

**Comment by cclark-work** [comment] 2023-04-20 13:22
Yes, executing `wsl --update --pre-release` to get the patch has worked for me
