### ISSUE TITLE
az aks browse ,the command failed with an unexpected error

### ISSUE THREAD

**Issue by e0m00l8** [Azure/azure-cli#9805] opened 2019-06-26 11:42 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110cfd470>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
python3.7/site-packages/urllib3/connection.py, ln 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
site-packages/urllib3/util/connection.py, ln 80, in create_connection
    raise err
...

python3.7/site-packages/requests/adapters.py, ln 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110cfd470>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Darwin-18.2.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1

```

**Comment by e0m00l8** [comment] 2019-06-26 11:42
m-c02t75ugg8wn:~ e0m00l8$ az aks browse --resource-group WEIoT_SmartBuildings_Dev_SC --name edge-aks
Merged "edge-aks" as current context in /var/folders/4f/l90yt4xd6wj42t21g32_4x80jtd43v/T/tmp3hua3dwi
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
The command failed with an unexpected error. Here is the traceback:

HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110cfd470>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x110cfd470>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110cfd470>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 566, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 624, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 617, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 594, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 303, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 470, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1447, in aks_browse
    requests.post('http://localhost:8888/closeport/8001')
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110cfd470>: Failed to establish a new connection: [Errno 61] Connection refused'))

To open an issue, please run: 'az feedback'

**Comment by matelang** [comment] 2019-06-28 10:03
I can confirm the same using Arch Linux
$ uname -a
Linux devmate 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux

$ python --version
Python 3.7.3

$ az -v
azure-cli                         2.0.67

acr                                2.2.9
acs                                2.4.4
advisor                            2.0.1
ams                                0.4.7
appservice                        0.2.21
backup                             1.2.5
batch                              4.0.3
batchai                           0.4.10
billing                            0.2.2
botservice                         0.2.2
cdn                                0.2.4
cloud                              2.1.1
cognitiveservices                  0.2.6
command-modules-nspkg               2.0.2
configure                         2.0.24
consumption                        0.4.4
container                         0.3.18
core                              2.0.67
cosmosdb                          0.2.11
deploymentmanager                  0.1.1
dla                                0.2.6
dls                               0.1.10
dms                                0.1.4
eventgrid                          0.2.4
eventhubs                          0.3.7
extension                          0.2.5
feedback                           2.2.1
find                               0.3.4
hdinsight                          0.3.5
interactive                        0.4.5
iot                               0.3.11
iotcentral                         0.1.7
keyvault                          2.2.16
kusto                              0.2.3
lab                                0.1.8
maps                               0.3.5
monitor                           0.2.15
natgateway                         0.1.1
network                            2.5.2
nspkg                              3.0.3
policyinsights                     0.1.4
privatedns                         1.0.2
profile                            2.1.5
rdbms                             0.3.12
redis                              0.4.4
relay                              0.1.5
reservations                       0.4.3
resource                          2.1.16
role                               2.6.4
search                             0.1.2
security                           0.1.2
servicebus                         0.3.6
servicefabric                     0.1.20
signalr                            1.0.1
sql                                2.2.5
sqlvm                              0.2.0
storage                            2.4.3
telemetry                          1.0.2
vm                                2.2.23

Python location '/usr/bin/python'
Extensions directory '/home/mate/.azure/cliextensions'

Python (Linux) 3.7.3 (default, Jun 24 2019, 04:54:02) 
[GCC 9.1.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by seanmck** [comment] 2019-07-14 07:09
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:09 UTC
Labels: AKS, Service Attention
