### ISSUE TITLE
az acr login failed

### ISSUE THREAD

**Issue by zhangjianye88** [Azure/azure-cli#16813] opened 2021-02-05 05:10 UTC
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
This command requires running the docker daemon, which is not supported in Azure Cloud Shell. You may want to use 'az acr login -n jackyharbor --expose-token' to get an access token, which does not require Docker to be installed.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {}`

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.18.0
azure-cli-ml 1.20.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.20.0

```

**Comment by yungezz** [comment] 2021-02-05 07:38
route to appropriate team

**Comment by yugangw-msft** [comment] 2021-02-05 17:53
This is by design. if you don't have docker installed, you can use `--expose-token` to get the credential for other clients to authenticate.
Closing

**Closed by yugangw-msft** 2021-02-05 17:53 UTC
Labels: Container Registry, Service Attention, question
