### ISSUE TITLE
az resource show traceback

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#8998] opened 2019-04-04 23:17 UTC
**Describe the bug**
The command failed with an unexpected error. Here is the traceback:

'namespace'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 402, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 732, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 742, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 730, in handler
    return getter(**args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 826, in show_resource
    include_response_body) for id_dict in parsed_ids])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 826, in <listcomp>
    include_response_body) for id_dict in parsed_ids])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 790, in _get_rsrc_util_from_parsed_id
    api_version)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 1793, in __init__
    api_version = _ResourceUtils._resolve_api_version_by_id(self.rcf, resource_id)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 1996, in _resolve_api_version_by_id
    namespace = parts.get('child_namespace_1', parts['namespace'])
KeyError: 'namespace'
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
show the contents of the resource id specified or produce an error that it cannot be shown in az cli (resource is an rg that contains classic resources)

**Environment summary**
cloud shell cli

**Additional context**

**Comment by tjprescott** [comment] 2019-04-04 23:19
We will add a warning. Azure CLI does not support classic (pre-ARM) resources.

**Comment by tjprescott** [comment] 2019-04-04 23:21
Could you post an example of the resource ID you tried to show?

**Comment by tjprescott** [comment] 2019-04-08 15:59
Currently I'm unable to repro. I've used `az resource show --ids {id}` on several classic resources and they work fine. While I can add logic to the area in the stack trace, when I have tried to trigger it, I find something else catches the problem first, so I would really need to know the structure of the ID you are using to be able to repro.

**Comment by zhoxing-ms** [comment] 2019-12-31 09:37
@christiankuhtz Hi, I can't reproduce this case now. Do you still have any problems with the operation now?
If you can reproduce the problem, please provide a specific example

**Comment by yonzhan** [comment] 2020-01-02 03:28
@christiankuhtz any update?

**Comment by zhoxing-ms** [comment] 2020-01-13 05:51
Because it hasn't been replied for a long time, I'll close the issue first. If you have any other questions, please feel free to reopen it or create a new one.

**Closed by zhoxing-ms** 2020-01-13 05:51 UTC
Labels: ARM, Output, Resource Manager-cli

**Comment by nyetwurk** [comment] 2020-02-14 02:52
`azure/cli/core/commands/arm.py`
```
--- arm.py-dist 2020-02-14 02:32:41.713651949 +0000
+++ arm.py      2020-02-14 02:12:13.609049163 +0000
@@ -100,7 +100,8 @@
 def handle_template_based_exception(ex):
     try:
-        raise CLIError(ex.inner_exception.error)
+        # raise CLIError(ex.inner_exception.error.message) # NTL
+        raise CLIError(ex.inner_exception.error) # NTL
     except AttributeError:
         raise CLIError(ex)
```
