### ISSUE TITLE
objectId is no longer returned when using "az ad sp show --id  xxxxx-xxxx-xxxx-xxxx-xxxxxx

### ISSUE THREAD

**Issue by tazd007** [Azure/azure-cli#27686] opened 2023-10-25 14:21 UTC
### Describe the bug

Documentation states you can retrieve the objectID this is not the case 

### Related command

 az ad sp show
 az ad sp list

### Errors

objectID  is not returned in the json 

### Issue script & Debug output

objectID  is not returned in the json 

### Expected behavior

objectId should be returned

### Environment Summary

 az --version
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment] 2023-10-25 14:21
Thank you for opening this issue, we will look into it.

**Comment by doherty100** [comment] 2023-10-25 18:24
I am hitting this as well with azure cli 2.53.1. Basically if you create any azure resource using Azure CLI (key vault, storage account, etc.) and you immediately try to view that resource it will fail. This is going to break a lot of stuff.

**Comment by doherty100** [comment] 2023-10-25 20:48
I'm seeing it take up to 90 seconds for an azure cli `show` command to work after an azure cli `create` completes against the same resource. I'm testing against key vaults and storage accounts.

**Comment by jiasli** [comment] 2023-10-26 01:20
@tazd007, your issue is a duplicate of https://github.com/Azure/azure-cli/issues/22328.

> Documentation states you can retrieve the objectID this is not the case

BTW, could you let us know which document states that?

**Closed by jiasli** 2023-10-26 01:20 UTC
Labels: question, Graph, customer-reported, Auto-Assign, Azure CLI Team

**Comment by jiasli** [comment] 2023-10-26 01:29
@doherty100, it looks like you are facing a different issue. It is not related to the missing property `objectId` in the service principal object, but ARM not being able to retrieving the resource immediately after creation. According to my experience, this is usually caused by some caching or syncing issue in ARM.

Azure CLI is a client calling ARM API. You can add `--debug` argument to see the network trace. I would recommend creating a support ticket at https://azure.microsoft.com/en-us/support/create-ticket to contact service team.

**Comment by tazd007** [comment] 2023-10-28 22:09
Your assumption is in correct these resources are already present in fact some even years. My code uses the objectId and has worked fine, however now the objectId is not returned where previously it was
