### ISSUE TITLE
az disk update does not update to Allow Private

### ISSUE THREAD

**Issue by mcarter106** [Azure/azure-cli#19455] opened 2021-09-05 14:45 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When running the command to update a disk to use a disk access object, the script is not running as intended.  

**To Reproduce**
diskAccessId=$(az disk-access show -n $diskAccessName -g $rg --query [id] -o tsv)
az disk update --name $diskname --resource-group $rgdisk --network-access-policy AllowPrivate --disk-access $diskAccessId >> /tmp/pe.log

**Expected behavior**
When running the above I am receiving this error which I should not be receiving as I am passing a valid diskAccessId.  I had a coworker confirm this as well.  
(ConflictingUserInput) AllowPrivate NetworkAccessPolicy can only supported with Disk Access.  Expected behavior is to attach the disk access to the disk and set the network settings to allow private.

**Environment summary**
CLI version = latest as this behavior occurs in the Cloud shell as well as on linux.

**Additional context**

**Comment by yonzhan** [comment] 2021-09-05 15:20
Compute

**Comment by zhoxing-ms** [comment] 2021-09-06 01:50
In fact, this is an error returned by service, so it should be a service issue.
＠mcarter106 Please send the specific debug logs by email, thanks

**Comment by zhoxing-ms** [comment] 2021-09-08 02:26
The response body returned by service :
```json
{
  "error": {
    "code": "ConflictingUserInput",
    "message": "AllowPrivate NetworkAccessPolicy can only supported with Disk Access"
   }
}
```
**'x-ms-correlation-request-id': '2ecdf504-39d9-47c1-a142-1ce487237704'**

**Comment by mcarter106** [comment] 2021-09-08 23:48
Yes.  I'm passing a valid disk access id into the command if you look at my initial submission.

**Comment by jaylabell** [comment] 2021-09-09 18:24
@Vaibhav-Agar Do you mind taking a look at this issue?

**Comment by oriwolman** [comment] 2021-09-30 01:32
@mcarter106 
I was able to reproduce the last item
This looks like a bug in the CLI code. As we are not receiving the diskAccessId in the incoming request. contacting the dev team and will update

**Comment by zhoxing-ms** [comment] 2021-09-30 03:02
@oriwolman Hi, this is the request from CLI to service:
REST: [disks/create-or-update](https://docs.microsoft.com/en-us/rest/api/compute/disks/create-or-update)
Request body:
```json
{
    "location": "eastus", 
    "tags": { }, 
    "sku": {
        "name": "Premium_LRS"
    }, 
    "properties": {
        "hyperVGeneration": "V1", 
        "creationData": {
            "createOption": "Empty"
        }, 
        "diskSizeGB": 10, 
        "networkAccessPolicy": "AllowAll", 
        "diskAccessId": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/zhoxing-test/providers/Microsoft.Compute/diskAccesses/zhoxing-test"
    }
}
```
We can see that CLI sends the `diskAccessId` to REST. However, the service returns the error:
```json
{
  "error": {
    "code": "ConflictingUserInput",
    "message": "Disk Access is only supported for disks with NetworkAccessPolicy AllowPrivate"
  }
}
```
Therefore, this should be a service problem, which needs to be investigated by the service team

**'x-ms-correlation-request-id': '683985d3-310f-4e51-88d9-8335ef334d34'**

**Comment by avirishuv** [comment] 2021-11-09 23:55
Assigning to @oriwolman and removing @Vaibhav-Agar

**Comment by TravisCragg-MSFT** [comment] 2022-01-20 19:12
I am driving this forward, please let me know if anyone else has this issue.

**Comment by TravisCragg-MSFT** [comment] 2022-01-20 19:20
This is now fixed, please post here if this issue is encountered again in an updated CLI version.

**Closed by TravisCragg-MSFT** 2022-01-20 19:20 UTC
Labels: Compute, Service Attention
