### ISSUE TITLE
Account create should show supported values.

### ISSUE THREAD

**Issue by jfellien** [Azure/azure-cli#5604] opened 2018-02-16 23:09 UTC
There are some switches here but I cant find all the possibilities. For example `--kind` it is described but which values are possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7172de-478b-5200-6370-747a8c40efb2
* Version Independent ID: baffbf17-2f5d-44a6-de77-7ecb320f35ed
* [Content](https://docs.microsoft.com/en-us/cli/azure/cognitiveservices/account?view=azure-cli-latest#az_cognitiveservices_account_create)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/_help.py)
* Service: cognitive-services

**Comment by derekbekoe** [comment] 2018-02-16 23:11
This is regarding `az cognitiveservices account create`

**Comment by jfellien** [comment] 2018-02-16 23:17
I know, I know. I'm asking for a list of for example `--kind`. I miss the list of possibilities. In the documentation I can see `Face` is one of the values and the rest?

**Comment by jfellien** [comment] 2018-02-16 23:22
A simple Link to Azure REST API for the win: https://docs.microsoft.com/en-us/rest/api/cognitiveservices/cognitiveservicesaccounts/create#kind

**Comment by derekbekoe** [comment] 2018-02-16 23:28
@jfellien I added the comment for others as it's not immediately obvious from the issue description what command it was referring to 👍

**Comment by tjprescott** [comment] 2018-02-20 18:07
Duplicate of #5246.

**Closed by tjprescott** 2018-02-20 18:07 UTC
Labels: CognitiveServices, Documentation
