### ISSUE TITLE
Azure CLI could not be installed because it requires Administrator privileges (Windows 10)

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-cli#21982] opened 2022-04-07 15:20 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I cannot install Azure CLI on my corporate workstation (Windows 10)

**To Reproduce**
- Navigate to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
- Download the MSI package for Windows
- Try installing and you will see the setup process asking you for username/password of an Administrative user
- Try ignoring it and the Setup fails with the following message
![image](https://user-images.githubusercontent.com/20245330/162233643-d4d30cb6-2bc3-4900-8b33-924e6564fb89.png)

**Expected behavior**
I do not see any reason why Microsoft would not allow me to install Azure CLI as a non-admin user under my current user Account. 

**Environment summary**

- Windows 10
- Non administrative user
- 
**Additional context**

**Comment by yonzhan** [comment] 2022-04-07 23:39
@jiasli for awareness

**Comment by sdg002** [comment] 2022-05-14 09:14
Hello Team,
Any progress on this?

**Comment by jiasli** [comment] 2022-05-16 02:29
Duplicate of #15381

**Closed** 2022-05-16 02:31 UTC
Labels: customer-reported, Installation, Auto-Assign
