### ISSUE TITLE
az storage account keys list not working with 'read-only' resource lock

### ISSUE THREAD

**Issue by jonnylangefeld** [Azure/azure-cli#8452] opened 2019-02-06 20:43 UTC
I don't know if this is the right place to file this bug. If not, please move.

the command `az storage account keys list --account-name <storage account name>` works fine if there is no resource lock on the storage account. It lists the keys for the storage account.
It still works with the lock `delete` that prevents the resource from deletion.

However it doesn't work with the `read-only` resource lock anymore. Even though I am just reading a property. So the expectation would be, that still the keys are listed. However the following error is returned:

    The scope '/subscriptions/<subscription id>/resourceGroups/<resource group>/providers/Microsoft.Storage/storageAccounts/<storage account name>' cannot perform write operation because following scope(s) are locked: '/subscriptions/<subscription id>/resourcegroups/<resource group>/providers/Microsoft.Storage/storageAccounts/<storage account name>'. Please remove the lock and try again.

---

### Environment summary

azure CLI in latest Docker image

**Comment by tjprescott** [comment] 2019-02-06 21:59
The CLI calls directly into the Python SDK for this call. 

@zezha-msft I can confirm that the SDK is making a POST call:
`https://management.azure.com:443 "POST /subscriptions/xxxx/resourceGroups/tjp-rg/providers/Microsoft.Storage/storageAccounts/tjpstorage2/listKeys`

From a technical perspective it makes sense why a POST call would fail, but from a customer perspective, this makes no sense and the call should succeed. @zezha-msft is there a GET alternative for requesting these keys?

**Comment by zezha-msft** [comment] 2019-02-06 22:48
Hi @tjprescott, @lmazuel can help you on this. I work on the data-plane SDK.

**Comment by tjprescott** [comment] 2019-02-06 23:22
@zezha-msft my mistake--I thought this was a data plane call but you are right. Thanks!

**Comment by tjprescott** [comment] 2019-02-06 23:25
Hi @jonnylangefeld thank you for the report. Unfortunately, there is nothing we can do on the CLI-side to work around this issue because the service is using a write operation (an HTTP POST) to retrieve the keys. At best we can bring this to the attention of the service team.

**Comment by zhusijia26** [comment] 2019-06-04 19:55
Close this issue based on last comment and the idle time.

**Closed by zhusijia26** 2019-06-04 19:55 UTC
Labels: Question, Service Attention, Storage
