### ISSUE TITLE
can open port 80

### ISSUE THREAD

**Issue by apivaras** [Azure/azure-cli#13421] opened 2020-05-09 16:54 UTC
## Describe the bug

**Command Name**
`az vm open-port`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm open-port -g {} -n {} --port {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment] 2020-05-09 23:41
@qwordy please take a look

**Comment by yungezz** [comment] 2020-05-11 01:37
hi @apivaras did you see the error on Cloudshell?

**Comment by jiasli** [comment] 2020-05-12 09:03
Looks like the same issue as https://github.com/Azure/azure-cli/issues/11749

**Comment by qwordy** [comment] 2020-05-12 09:21
According the error message, something is wrong when trying to get msi token. Are you using CloudShell?

**Comment by qwordy** [comment] 2020-07-17 05:38
@apivaras Does this issue still exist?

**Comment by maertendMSFT** [comment] 2020-09-30 23:10
Can we close this as a dupe of https://github.com/Azure/azure-cli/issues/11749 ?

**Closed** 2020-10-01 09:05 UTC
Labels: Cloud Shell, Service Attention, customer-reported
