### ISSUE TITLE
az interactive  progress_patch() got an unexpected keyword argument 'det'

### ISSUE THREAD

**Issue by pomberer** [Azure/azure-cli#18815] opened 2021-07-12 08:01 UTC
## Describe the bug

**Command Name**
`az interactive`
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
az>> Error loading command module 'iot': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'network': progress_patch() got an unexpected keyword argument 'det'
     Error loading command module 'resource': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'sql': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'vm': progress_patch() got an unexpected keyword argument 'det'

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
progress_patch() got an unexpected keyword argument 'det'
Traceback (most recent call last):
  File "/Users/gerhardpomberer/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 663, in cli_execute
    result = invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 702, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 878, in __init__
    self.progress_bar = progress_bar if progress_bar is not None else IndeterminateProgressBar(cli_ctx)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/progress.py", line 180, in __init__
    self.hook = self.cli_ctx.get_progress_controller(
TypeError: progress_patch() got an unexpected keyword argument 'det'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`
- aks upgrade --resource-group XXX --name XXX --kubernetes-version 1.20.7

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.0

Extensions:
interactive 0.4.4

```
## Additional Context
az --version
azure-cli                         2.26.0

core                              2.26.0
telemetry                          1.0.6

Extensions:
interactive                        0.4.4

Python location '/usr/local/Cellar/azure-cli/2.26.0/libexec/bin/python'
Extensions directory '/Users/xxx/.azure/cliextensions'

Python (Darwin) 3.8.11 (default, Jun 29 2021, 03:08:07)
[Clang 12.0.5 (clang-1205.0.22.9)]

**Comment by yonzhan** [comment] 2021-07-12 08:56
interactive

**Comment by jiasli** [comment] 2021-07-13 06:22
Duplicate of #17740

**Closed** 2021-07-13 06:22 UTC
Labels: Interactive, feature-request
