### ISSUE TITLE
az group deployment validate missing data in response

### ISSUE THREAD

**Issue by michaelw85** [Azure/azure-cli#10518] opened 2019-09-12 11:36 UTC
cli version: 2.0.73

**Describe the bug**
I'm using the following command to validate my arm templates and since I updated to the latest version the response is lacking allot of details on the resources.
```
  az group deployment validate \
            --resource-group ${resourceGroup} \
            --template-file ${tpl} \
            --parameters ${tplParams}
```

**To Reproduce**
Run validate with cli `2.0.72` 
It will produce validated resources something as detailed as this:
```
{
  "apiVersion": "2018-11-01",
  "dependsOn": [
	"/subscriptions/123/resourceGroups/arm-test/providers/Microsoft.Web/serverfarms/foo-doc-dev-we-spec-sp"
  ],
  "id": "/subscriptions/123/resourceGroups/arm-test/providers/Microsoft.Web/sites/foo-doc-dev-we-spec-app",
  "location": "westeurope",
  "name": "foo-doc-dev-we-spec-app",
  "properties": {
	"httpsOnly": true,
	"serverFarmId": "/subscriptions/123/resourceGroups/arm-test/providers/Microsoft.Web/serverfarms/foo-doc-dev-we-spec-sp",
	"siteConfig": {
	  "ftpsState": "Disabled",
	  "http20Enabled": true,
	  "managedPipelineMode": "Integrated",
	  "netFrameworkVersion": "v4.7",
	  "siteAuthSettings": {
		"clientId": "456",
		"defaultProvider": "AzureActiveDirectory",
		"enabled": true,
		"issuer": "https://sts.windows.net/***",
		"unauthenticatedClientAction": "RedirectToLoginPage",
		"validateIssuer": true
	  }
	}
  }
```
compared to latest version .73:

```
{
  "id": "/subscriptions/123/resourceGroups/arm-test/providers/Microsoft.Web/sites/foo-doc-dev-we-spec-app",
  "resourceGroup": "arm-test"
}
```

**Expected behavior**
Expect detailed response to be able to verify the ARM template with a unit test.

**Environment summary**
Windows 10 env with cli installed using the msi installer.

**Additional context**
CLI changelog shows an api change. This issue is probably more related to this than the cli but I don't know where to go to report it hence I placed it here since it's a result of a cli update. A potential solution might be to be able to set the api version when using the cli.
```
ARM
Updated to use API version 2019-05-10
```

**Comment by Juliehzl** [comment] 2019-09-14 00:43
@michaelw85 Thanks a lot for your feedback. Because it is related to service API, I think we can wait for service response for why detailed information is reduced.  I can reproduce this issue with storage account template. In "validatedResources" part, I can get the flooding information in API v2018-05-01:
```
"validatedResources": [
      {
        "apiVersion": "2019-04-01",
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/zuh/providers/Microsoft.Storage/storageAccounts/avavfacxs",
        "kind": "StorageV2",
        "location": "eastus",
        "name": "avavfacxs",
        "properties": {
          "accessTier": "Hot",
          "supportsHttpsTrafficOnly": true
        },
        "resourceGroup": "zuh",
        "sku": {
          "name": "Standard_RAGRS"
        },
        "type": "Microsoft.Storage/storageAccounts"
      }
    ]
```
With API v2019-05-10, I only get:
```
    "validatedResources": [
      {
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/zuh/providers/Microsoft.Storage/storageAccounts/avavfacxs",
        "resourceGroup": "zuh"
      }
    ]
```

**Comment by michaelw85** [comment] 2019-10-03 10:04
@Juliehzl Any update on this topic? This is blocking me from updating the cli, at some point this will become an issue

**Comment by yonzhan** [comment] 2019-10-06 11:23
@Juliehzl   is this a service issue ?

**Comment by Juliehzl** [comment] 2019-10-06 12:24
@hjhhh3000vitae Can you take a look at this issue? API v2019-05-10 returns response with less properties than v2018-05-01.

**Comment by rickardp** [comment] 2020-01-13 13:23
Any news on this? It blocks us from upgrading the CLI as well, as we use the data returned by validate in our scripts.

**Comment by yonzhan** [comment] 2020-01-13 23:14
@hjhhh3000vitae any update?

**Comment by snaheth** [comment] 2021-01-20 00:25
@rickardp -- Do you still run into this? Looks like @hjhhh3000vitae might've missed this so I can follow up with him, if so.

Feel free to open this if it still occurs. Closing it for the time being given it's an old api version.

**Closed by snaheth** 2021-01-20 00:25 UTC
Labels: ARM, Service Attention, customer-reported
