### ISSUE TITLE
az aks update --attach-acr erroring in 2.46.0

### ISSUE THREAD

**Issue by Misterjohnson87** [Azure/azure-cli#25963] opened 2023-03-28 13:33 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az aks update -g $RG -n $AKS --attach-acr $ACR`

**Describe the bug**

When running the above command with an account that has owner for the subscription, the command returns the following error:
`ERROR: Could not create a role assignment for ACR. Are you an Owner on this subscription?`

**To Reproduce**

Download Azure CLI 2.45.0 (https://azcliprod.blob.core.windows.net/msi/azure-cli-2.45.0.msi) and run the command `az aks update --attach-acr` and confirm you receive `AAD role propagation done[############################################]  100.0000%` to indicate success. 

Then download Azure CLI 2.46.0  (https://azcliprod.blob.core.windows.net/msi/azure-cli-2.46.0.msi) and run the same command and you will receive an error: `ERROR: Could not create a role assignment for ACR. Are you an Owner on this subscription?`

**Expected behavior**

Running the command  `az aks update --attach-acr` when you are an owner on the subscription should give you the following message:  `AAD role propagation done[############################################]  100.0000%`

**Environment summary**

Occurring on multiple enviornments, running Azure CLI 2.46.0 locally on Windows 10, using the AzureCLI@v2 task on a linux build agent

**Additional context**

Others have reported the issue here: https://github.com/Azure/AKS/issues/3530

**Comment by yonzhan** [comment] 2023-03-28 14:41
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2023-03-30 00:12
@Misterjohnson87 I am not able to reproduce this issue with CLI - 2.46.0 and attaching an acr worked fine.  
![image](https://user-images.githubusercontent.com/38112130/228695608-2f31c109-c8ea-431c-a658-aaca65acf048.png)
![image](https://user-images.githubusercontent.com/38112130/228695262-0e7f01bb-2fdc-463e-807c-8152bc628d2b.png)
Can you please share the debug logs using `--debug`?

**Comment by Misterjohnson87** [comment] 2023-03-30 08:13
@SaurabhSharma-MSFT - Are you running az aks update -g $RG -n $AKS --attach-acr $ACR as a standalone command after running the command the first time?

**Comment by BramReijnders** [comment] 2023-03-30 09:59
Hi,

We experience the same issue. azure-cli version 2.45.0 it works fine.
Starting 2.46.0 we get the same error message as described in the issue.

I notice that @SaurabhSharma-MSFT uses az aks create instead of az aks update. 
Possibly only happens with the az aks update command?

Workaround is to manually define to use azure-cli version 2.45.0 till this is fixed.

**Comment by SaurabhSharma-MSFT** [comment] 2023-03-30 18:19
@BramReijnders I have checked with `az aks update` and able to reproduce this issue.  I am working on it internally and get back to you.

**Comment by Misterjohnson87** [comment] 2023-04-04 09:47
@SaurabhSharma-MSFT - Just to confirm this issue is still present in 2.47.0

**Comment by jaliyaudagedara** [comment] 2023-04-09 01:49
@Misterjohnson87 @SaurabhSharma-MSFT,

Just checked the issue with Azure CLI **`2.47.0`**, for me it's fixed.
[#3530#issuecomment-1501016757](https://github.com/Azure/AKS/issues/3530#issuecomment-1501016757)

**Comment by SaurabhSharma-MSFT** [comment] 2023-04-11 15:01
@Misterjohnson87 Thanks for the confirmation. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2023-04-11 15:01 UTC
Labels: question, AKS, customer-reported, CXP Attention, Auto-Assign
