### ISSUE TITLE
az ad app list - 400 Client Error - Azure Cloud Shell via Windows Terminal 

### ISSUE THREAD

**Issue by dreamuth** [Azure/azure-cli#12671] opened 2020-03-19 16:39 UTC
## Describe the bug

**Command Name**
`az ad app list`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 657, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad app list`

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0

```

**Comment by yonzhan** [comment] 2020-03-19 22:43
add to S168

**Comment by jiasli** [comment] 2020-04-01 08:41
Duplicate of #11749

`400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token` is a known issue of Cloud Shell that it intermittently fails with this error. 

To solve it, please use Azure CLI on a local machine or run `az login` in Cloud Shell and retry the command.

**Comment by maertendMSFT** [comment] 2020-07-07 21:31
I cannot repro this issue, this looks to be working in Windows Terminal.  Please close

**Closed** 2020-07-08 09:58 UTC
Labels: Cloud Shell, Graph, Service Attention
