### ISSUE TITLE
AKS-Dashboard add-on Fails

### ISSUE THREAD

**Issue by balajivenkataraman** [Azure/azure-cli#11769] opened 2020-01-03 21:27 UTC
## Describe the bug

**Command Name**
`az aks enable-addons`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
Temp\pip-install-umfcm_n2\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-umfcm_n2\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\acs\custom.py, ln 1843, in aks_enable_addons
azure\cli\command_modules\acs\custom.py, ln 2482, in _ensure_container_insights_for_monitoring
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons {} --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76 *

```

**Comment by jluk** [comment] 2020-01-06 16:29
This is a duplicate of #11768

**Comment by jluk** [comment] 2020-01-06 17:33
Reopening to capture the error reported from a separate cmd / trigger

**Comment by jluk** [comment] 2020-01-06 17:34
Related to #11456

**Comment by jluk** [comment] 2020-02-21 15:12
We believe a fix has been made, please reference this issue for the latest tracking. I am going to close this to consolidate info to one thread. If you still hit issues after the S166 milestone release, feel free to recomment.

https://github.com/Azure/azure-cli/issues/11456

**Closed by jluk** 2020-02-21 15:12 UTC
Labels: AKS, Service Attention
