### ISSUE TITLE
ServiceBus topic update doesn't work for Standard serviceBus

### ISSUE THREAD

**Issue by wolszakp** [Azure/azure-cli#13560] opened 2020-05-19 05:28 UTC
**Describe the bug**
Update azure service bus for ServiceBus should be possible according with documentation. 
It is possible to it using azure portal.

**To Reproduce**
`az servicebus topic update --enable-batched-operations true --name $topic --namespace-name $ns -g $rg`

**Expected behavior**
Batch operation should be enabled

**Environment summary**
My service bus is in `Standard` tier
`azure-cli` in version `2.5.1 *`

**Additional context**
I've spotted that more than one operation to update topic is not working. 
I assume that it can be connected with validation.

**Comment by yonzhan** [comment] 2020-05-19 06:22
servicebus

**Comment by yungezz** [comment] 2020-05-19 12:41
hi @wolszakp could you pls share error you met for investigation?

**Comment by wolszakp** [comment] 2020-05-25 12:54
@yungezz 
Here is the error
![image](https://user-images.githubusercontent.com/19219192/82814259-16eb6f80-9e97-11ea-898b-469e0985d2b8.png)

And here is proof that it has Standard `sku`
![image](https://user-images.githubusercontent.com/19219192/82814479-8eb99a00-9e97-11ea-9b53-c1bfa06d29dd.png)

**Comment by nemakam** [comment] 2020-05-26 23:43
@v-Ajnava , this looks like an issue in CLI. Could you please take a look at it? If it isn't CLI issue, please assign it back to us.

**Comment by axisc** [comment] 2021-01-21 01:18
@wolszakp  can you confirm if this issue is still occurring?

**Comment by Saglodha** [comment] 2022-03-02 12:55
@wolszakp, I tried reproducing the issue with latest version of CLI latest but couldn't. Can you confirm if you are still facing the issue?

**Closed** 2022-04-13 08:01 UTC
Labels: Service Attention, question, Service Bus, customer-reported, needs-author-feedback, no-recent-activity
