### ISSUE TITLE
az vm availability-set list missing &$expand=virtualMachines

### ISSUE THREAD

**Issue by wind1126** [Azure/azure-cli#11821] opened 2020-01-10 23:57 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az vm availability-set list missing &$expand=virtualMachines, so each time, the response doesn't include VM list, instead it has null.

**To Reproduce**
az vm availability-set list

**Expected behavior**
we want to have the AS content, including vm list, but each time it returns:
PS Azure:\> az vm availability-set list
[
  {
    "id": "/subscriptions/0726b7c7-2155-4457-8579-ee1c25c96ba2/resourceGroups/AVAILSET/providers/Microsoft.Compute/availabilitySets/availset",
    "location": "westus2",
    "name": "availset",
    "platformFaultDomainCount": 2,
    "platformUpdateDomainCount": 5,
    "proximityPlacementGroup": null,
    "resourceGroup": "AVAILSET",
    "sku": {
      "capacity": null,
      "name": "Aligned",
      "tier": null
    },
    "statuses": null,
    "tags": {},
    "type": "Microsoft.Compute/availabilitySets",
    "virtualMachines": null //// this is the info we need the most.
  }
]

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
https://docs.microsoft.com/en-us/rest/api/compute/availabilitysets/listbysubscription
this online doc gives us the accurate info on how to add Virtual Machines info in API call. We need to have the same from CLI module.

**Comment by jsntcy** [comment] 2020-01-13 05:30
@qwordy , please help take a look, thanks.

**Comment by yungezz** [comment] 2020-01-20 07:41
hi @wind1126 thanks for reporting the issue. I cannot reproduce the issue. Could you pls provide below info to help trouble shooting? thanks.
- could you pls check at https://portal.azure.com , your availability set -> virtual machines, to see if there any virtual machines showed?
- could you pls share how the availability set created? or VM created?

**Comment by skingd** [comment] 2020-01-20 22:14
> hi @wind1126 thanks for reporting the issue. I cannot reproduce the issue. Could you pls provide below info to help trouble shooting? thanks.
> 
> * could you pls check at https://portal.azure.com , your availability set -> virtual machines, to see if there any virtual machines showed?
> * could you pls share how the availability set created? or VM created?
> * could you pls try latest version of AZ CLI to see if the issue exists?

The VMs and availability set are both present in Azure. We actually have a number of them and none of them show up using that command.

Availability set was created manually via the portal.

The latest version was used and reported null for VMs in all availability sets. Azure shell was also tested with the same result.

Owner account was used for testing and still showed null for VMs.

**Comment by yungezz** [comment] 2020-01-21 04:36
thanks for the info, looking at it.

**Comment by yungezz** [comment] 2020-01-21 12:56
when list availability set in subs level, the result from service doesn't contain detail of vms, that's why user see null vm from azure cli. When list availability set in resource group level, the result from service contains vm detail. 
hi @wind1126 could you pls use below way to get vm detail of availability sets in subs:
```bash
local availabilitysets=$(az vm availability-set list --query '[].resourceGroup')
for set in "${availabilitysets[@]}"; do
   az vm availability-set list -g "$set"
```

**Comment by skingd** [comment] 2020-01-21 16:29
> when list availability set in subs level, the result from service doesn't contain detail of vms, that's why user see null vm from azure cli. When list availability set in resource group level, the result from service contains vm detail.
> hi @wind1126 could you pls use below way to get vm detail of availability sets in subs:
> 
> ```shell
> local availabilitysets=$(az vm availability-set list --query '[].resourceGroup')
> for set in "${availabilitysets[@]}"; do
>    az vm availability-set list -g "$set"
> ```

@yungezz To clarify, I was the one who encountered this. @wind1126 is a Microsoft tech that created the issue. I'll run the command and let you know the result.

**Comment by skingd** [comment] 2020-01-21 17:50
@yungezz "Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url:" do you have a PS equiv that you would prefer? It would be easier for me to run than bash, which is almost non-existent in our environment.

**Comment by qwordy** [comment] 2020-04-20 05:34
I find a bug in the rest api doc.
https://github.com/Azure/azure-rest-api-specs/issues/9130

**Comment by qwordy** [comment] 2020-04-29 07:55
It is fixed in latest Azure CLI.

**Closed by qwordy** 2020-04-29 07:55 UTC
Labels: Compute, Compute - VM, feature-request
