### ISSUE TITLE
az error when creating managedapp with tags

### ISSUE THREAD

**Issue by jhua18** [Azure/azure-cli#13355] opened 2020-05-06 09:45 UTC
In my bash script, same tags work well to create app resource group at very beginning:
# Create app resource group 
az group create \
  --name $appGroupName \
  --location $location \
  --tags Owner="$tagOwner" Project="$tagProject"

in the final step, the following az command is to create the managed resource group, however keeps getting error complaining about the tags:
# Create the managed application
az managedapp create \
  --name ${appName} \
  --location $location \
  --kind "Servicecatalog" \
  --resource-group $appDefinitionGroup \
  --managedapp-definition-id $appid \
  --managed-rg-id $managedGroupId \
  --parameters @${createUIDefinitionParametersFile} \
  --tags Owner="$tagOwner" Project="$tagProject"  \
  --verbose
az: error: unrecognized arguments: Project=AIFL

The tags are required by company policy, so this becomes a blocking issue. Is there any alternative way to handle the tags?

Also FYI,
az --version
azure-cli                          2.5.1

command-modules-nspkg              2.0.3
core                               2.5.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.5.1/libexec/bin/python'
Extensions directory '/Users/${userName}/.azure/cliextensions'

Python (Darwin) 3.8.2 (default, Mar 11 2020, 00:29:50) 
[Clang 11.0.0 (clang-1100.0.33.17)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17acc857-c9ef-301e-d49d-51bd415682f4
* Version Independent ID: f2697c9f-cce6-6e5f-890e-047aef849b64
* Content: [az managedapp](https://docs.microsoft.com/en-us/cli/azure/managedapp?view=azure-cli-latest#az-managedapp-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-05-06 11:56
managedapp

**Comment by panchagnula** [comment] 2020-07-08 01:51
@yonzhan managed app is not app service - can you check with owner file & assign this to the correct team? Thanks!

**Comment by yonzhan** [comment] 2020-07-08 10:05
add to S173

**Comment by MSEvanhi** [comment] 2020-07-09 16:46
We're investigating why this would be happening. Will provide an update within 72 hours.

**Comment by yonzhan** [comment] 2020-08-01 03:31
@MSEvanhi  any update?

**Comment by JayDoubleu** [comment] 2020-08-14 14:33
Any update on this ?

**Comment by MSEvanhi** [comment] 2020-09-10 00:53
Hey sorry for the late reply, this was marked as read for me unfortunately.

I believe the problem is the way we're quoting the tags here. Please update to follow [this document's guidance](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources#azure-cli) on how to format your call for tags.

You will need to quote both the field, equals sign, and the value.

**Comment by zhoxing-ms** [comment] 2020-09-10 06:11
@jhua18 Hi, this is a legacy bug that has been fixed in PR: https://github.com/Azure/azure-cli/pull/14381
Please upgrade the CLI to the latest version (2.11.0) and try again~

**Closed** 2020-09-19 04:13 UTC
Labels: ARM - Managed Applications
