### ISSUE TITLE
none of my 'az aks' commands are working, even '--help' crashes with an ssl error

### ISSUE THREAD

**Issue by dayglo** [Azure/azure-cli#11465] opened 2019-12-03 17:39 UTC
## Describe the bug

**Command Name**
`az aks`

**Errors:**
```
dlopen(/usr/local/Cellar/azure-cli/2.0.69/libexec/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/azure-cli/2.0.69/libexec/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
  Reason: image not found
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
  Reason: image not found
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks --help`

## Environment Summary
```
Darwin-18.0.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.69 *

Extensions:
acrbuildext 0.0.4

```

**Comment by jluk** [comment] 2019-12-05 00:02
@dayglo could you please retry this after updating your az version to 2.0.77? I am not able to reproduce but would like to see if recent builds resolves this given your version is a bit old.

**Comment by jluk** [comment] 2019-12-17 00:00
Closing this as we're waiting response if an upgrade fixes it. Please give it a try and re-comment if it still reproduces.

**Closed by jluk** 2019-12-17 00:00 UTC
Labels: AKS, Service Attention
