### ISSUE TITLE
Unable to login use az login

### ISSUE THREAD

**Issue by MNO098** [Azure/azure-cli#28275] opened 2024-01-30 08:05 UTC
### Describe the bug

Hi Team,
I am unable to login using az login in windows powershell and I tried all possible solutions posted on similar issues and its still not resolved,
Note : I installed it by following the instructions from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli 

### Related command

az login

### Errors

PS C:\Users\0033ET744> az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Found multiple accounts with the same username 'martina.noble@maersk.com': [{'home_account_id': 'ecace3e3-afa5-408a-ba0a-b59f1b684442.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'martina.noble@maersk.com', 'authority_type': 'MSSTS', 'local_account_id': 'ecace3e3-afa5-408a-ba0a-b59f1b684442', 'realm': 'organizations'}, {'home_account_id': '5392b4dd-2e34-4178-bfbd-f9565c15ba1a.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'martina.noble@maersk.com', 'authority_type': 'MSSTS', 'local_account_id': '5392b4dd-2e34-4178-bfbd-f9565c15ba1a', 'realm': 'organizations'}]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

### Issue script & Debug output

PS C:\Users\0033ET744> az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Found multiple accounts with the same username 'martina.noble@maersk.com': [{'home_account_id': 'ecace3e3-afa5-408a-ba0a-b59f1b684442.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'martina.noble@maersk.com', 'authority_type': 'MSSTS', 'local_account_id': 'ecace3e3-afa5-408a-ba0a-b59f1b684442', 'realm': 'organizations'}, {'home_account_id': '5392b4dd-2e34-4178-bfbd-f9565c15ba1a.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'martina.noble@maersk.com', 'authority_type': 'MSSTS', 'local_account_id': '5392b4dd-2e34-4178-bfbd-f9565c15ba1a', 'realm': 'organizations'}]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

### Expected behavior

I need to be able to login to azure successfully in order to get connected to aks.

### Environment Summary

core                              2.39.0 *
telemetry                          1.0.6 *

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

**Comment by yonzhan** [comment] 2024-01-30 08:05
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-01-31 06:50
Duplicate of #20168

**Closed by jiasli** 2024-01-31 06:50 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
