### ISSUE TITLE
Command az feature register --namespace Microsoft.Compute --name SIGSoftDelete does not work, remains in pending state

### ISSUE THREAD

**Issue by helge12** [Azure/azure-cli#29263] opened 2024-06-27 12:25 UTC
### Describe the bug

When executing the command
az feature register --namespace Microsoft.Compute --name SIGSoftDelete
it stays in "pending" state forever. For the test I submitted I waited 20 minutes. But it does not change after 3 days.
When you change to unregister, it does work.
It can be repeated with same result.

I know 2 subscriptions where it does not work.
I use latest az cli (see output)
PowerShell gives no different result. Therefore, it might be a server side issue.

### Related command

az feature register

### Errors

No errors, it just hangs in "pending" state

### Issue script & Debug output

Debug is not relevant, no error

PS C:\Users\helge> az feature register --namespace Microsoft.Compute --name SIGSoftDelete
Once the feature 'SIGSoftDelete' is registered, invoking 'az provider register -n Microsoft.Compute' is required to get the change propagated
{
  "id": "/subscriptions/d4b0XXXXXXXXXXXXXXXXXXXXXXXXXe934f86/providers/Microsoft.Features/providers/Microsoft.Compute/features/SIGSoftDelete",
  "name": "Microsoft.Compute/SIGSoftDelete",
  "properties": {
    "state": "Pending"
  },
  "type": "Microsoft.Features/providers/features"
}
PS C:\Users\helge> get-date

Thursday, June 27, 2024 1:57:42 PM

PS C:\Users\helge> az feature show --namespace Microsoft.Compute --name SIGSoftDelete
{
  "id": "/subscriptions/d4b0XXXXXXXXXXXXXXXXXXXXXXXXXe934f86/providers/Microsoft.Features/providers/Microsoft.Compute/features/SIGSoftDelete",
  "name": "Microsoft.Compute/SIGSoftDelete",
  "properties": {
    "state": "Pending"
  },
  "type": "Microsoft.Features/providers/features"
}
PS C:\Users\helge> get-date

Thursday, June 27, 2024 2:21:33 PM

PS C:\Users\helge>

### Expected behavior

State should change to "registered" after a few minutes.

### Environment Summary

PS C:\Users\helge>
PS C:\Users\helge> az version
{
  "azure-cli": "2.61.0",
  "azure-cli-core": "2.61.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "vm-repair": "1.0.5"
  }
}

**Comment by yonzhan** [comment] 2024-06-27 12:25
Thank you for opening this issue, we will look into it.

**Comment by jennyhunter-msft** [comment] 2024-07-10 21:02
@helge12  - This behavior is as expected and not a bug. Some features are hidden and require approval by the service team. In this case, you would need to ensure that the Microsoft.Compute team has allowlisted the SIGSoftDelete feature for your pending subscriptions in order for the registration to complete.

**Comment by jennyhunter-msft** [comment] 2024-07-10 21:02
Closing as by design

**Closed by jennyhunter-msft** 2024-07-10 21:02 UTC
Labels: Service Attention, question, ARM, customer-reported, Auto-Assign

**Comment by baidarka** [comment] 2024-08-30 09:07
How can I know as a user that a feature requires approval by a product team?
My issue appears related (although occurs with feature 'SIGSharing').

### SCENARIO
Deploy an Azure Compute Gallery (`Microsoft.Compute/galleries@2023-07-03`)
Get error message:
`Subscription 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is not registered with the feature Microsoft.Compute/SIGSharing. Please register the subscription before retrying the call.`

Register feature SIGSharing as recommended:
```sh
az feature register --namespace Microsoft.Compute --name SIGSharing
az provider register --namespace Microsoft.Compute
```

### ISSUE
The state of the feature SIGSharing stays '**pending**', for ever and ever.
From a user perspective I have no clue or indication what is going on.
```json
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Features/providers/Microsoft.Compute/features/SIGSharing",
  "name": "Microsoft.Compute/SIGSharing",
  "properties": {
    "state": "Pending"
  },
  "type": "Microsoft.Features/providers/features"
}
```

### WORKAROUND
I will fallback to an older API version, that does not require SIGSharing.
(that should work since I do not really use this feature: `sharingProfile/permissions: 'Private'`)

### REQUEST
As a user, I'd appreciate a warning that 'an approval by others' is required, or time to completion make take a really long time ⚠️ 
Even just a warning log entry in an activity log would be really helpful! 🤓

**Comment by azurecorner** [comment] 2025-02-28 08:16
Hi, I have the same issue =>  

```
 az feature register --namespace Microsoft.Compute --name SIGSharing
Once the feature 'SIGSharing' is registered, invoking 'az provider register -n Microsoft.Compute' is required to get the change propagated
{
  "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Features/providers/Microsoft.Compute/features/SIGSharing",
  "name": "Microsoft.Compute/SIGSharing",
  "properties": {
    "state": "Pending"
  },
  "type": "Microsoft.Features/providers/features"
}
```
