### ISSUE TITLE
az login --identity gives errors: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by sambroy** [Azure/azure-cli#25397] opened 2023-02-08 23:13 UTC
```
$ az login --identity
bash: /anaconda/envs/jupyter_env/lib/libtinfo.so.6: no version information available (required by bash)
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 122, in login
    return profile.login_with_managed_identity(username, allow_no_subscriptions)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 234, in login_with_managed_identity
    msi_creds = MSIAuthenticationWrapper(resource=resource)
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/adal_authentication.py", line 75, in set_token
    super().set_token()
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 596, in set_token
    self.scheme, _, self.token = get_msi_token_webapp(self.resource, self.msi_conf)
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 548, in get_msi_token_webapp
    token_entry = result.json()
  File "/opt/az/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/az/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Linux-5.15.0-1031-azure-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.45.0

Extensions:
ml 2.14.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2023-02-08 23:33
@jiasli for awareness

**Comment by jiasli** [comment] 2023-02-09 02:47
Seems to be a duplicate of #24675.

**Comment by sambroy** [comment] 2023-02-09 05:50
@jiasli While the other ticket is a duplicate, there is no solution indicated on that ticket. Can this be prioritized and resolved since this is hitting multiple users?

**Comment by sambroy** [comment] 2023-02-09 05:50
+ @yonzhan

**Comment by luigiw** [comment] 2023-02-09 23:48
@sambroy thx for reporting this issue. Did you use a managed identity when setting up this compute instance? Can you share how the managed identity is setup?

**Comment by sambroy** [comment] 2023-02-09 23:54
This is what I see when I set up a new compute instance. How do I set up a managed identity (ME) here? (the advanced settings also did not show anything for a ME)
<img width="909" alt="chrome_ykIbbqH2yg" src="https://user-images.githubusercontent.com/65827957/217965013-044d64b1-40c6-4e66-b64c-2dee6de328b7.png">

**Comment by luigiw** [comment] 2023-02-14 18:45
Thank you for sharing the screenshot. Do you see this in "Advanced settings"?

You can also use CLI to show details of your CI by running `az ml compute show -n <ci_name>`

![image](https://user-images.githubusercontent.com/1483379/218828854-35c9240d-d334-4c6d-b854-ac3c6f309fff.png)

**Comment by jwgwalton** [comment] 2023-02-16 10:47
Are we mean to assign a managed identity to compute instances? the notes on starting a terminal instance in Azure ML Studio are


Welcome to the Azure Machine Learning terminal

Enter "git clone [url]" to clone a repo                         
Enter "git --help" to learn about Git CLI. To learn more about integrating Git with the Azure Machine Learning terminal, navigate here:
        https://learn.microsoft.com/en-us/azure/machine-learning/concept-train-model-git-integration#clone-git-repositories-into-your-workspace-file-system
Enter "az ml --help" to learn about Azure ML CLI v2                                                                                                                          

Note: Use "az login --identity" instead of "az login" to avoid device code authentication


However there is no mention of the need for a managed identity.

**Comment by jwgwalton** [comment] 2023-02-16 10:59
I have created an instance with a system assigned managed identity. but still get the same error.

**Comment by sumit-sp** [comment] 2023-03-21 06:17
Below solution worked for me:
1. After opening Azure Machine learning Studio, go to Notebooks.
2. Open any jupyter notebook or create a new jupyter notebook.
3. Once inside a Jupyter notebook file, at the top (Shown in image) Azure will ask to "Authenticate". Click on "Authenticate" button and that will log you in.
![image](https://user-images.githubusercontent.com/21123230/226531226-1b62ee8e-605e-43ac-b48c-ad41278d7e3e.png)

5. Then you can open Azure Terminal and perform "az login --identity".

**Comment by luigiw** [comment] 2023-03-22 00:50
Please refer to steps by @sumit-sp above as the solution. Thx all.

**Closed** 2023-03-29 04:01 UTC
Labels: Account, Service Attention, question, Auto-Assign, Azure CLI Team, issue-addressed
