### ISSUE TITLE
az group deployment fails when property contains "="

### ISSUE THREAD

**Issue by joshua-harrison-2011** [Azure/azure-cli#3738] opened 2017-06-15 17:46 UTC
### Description

When I run a deployment with an equals sign in a parameter, I get a failure.  This is particularly impactful when sending an sasToken or base64 encoded string in as a parameter value.

It appears the problem was introduced by https://github.com/Azure/azure-cli/commit/3753b503aa8f9d21a28ca8fbeccd5d1623eafdda.  The function `_try_parse_key_value_object` splits on '=' prior to parsing as json.  I suspect this order needs to be reversed.

The following reduction test can be used to duplicate the problem.

    $ cat /tmp/azure.json
    {
        "$schema":        "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
        "contentVersion": "1.0.0.0",
        "parameters": {
            "testParameter": {
                "type": "string"
            }
        },
        "resources": [
            {
                "comments":   "Public IP Address",
                "type":       "Microsoft.Network/publicIPAddresses",
                "name":       "Test",
                "apiVersion": "2016-03-30",
                "location":   "[resourceGroup().location]"
            }
        ]
    }

    $ cat /tmp/azure-params.json
    {
        "testParameter": "ac=d"
    }

    $ az group deployment validate --verbose --resource-group <RESOURCE GROUP> --template-file /tmp/azure.json --parameters @/tmp/azure-params.json
    Please provide a value for 'testParameter' (? for help): sdf
    {
      "error": {
        "code": "InvalidTemplate",
        "details": null,
        "message": "Deployment template validation failed: 'The template parameters '{\n\"testParameter\": \"ac' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'testParameter'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.",
        "target": null
      },
      "properties": null
     }

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
bash-4.3# az --version
azure-cli (2.0.8+dev)

acr (2.0.6+dev)
acs (2.0.8+dev)
appservice (0.1.8+dev)
batch (3.0.1+dev)
billing (0.1.1+dev)
cdn (0.0.4+dev)
cloud (2.0.4+dev)
cognitiveservices (0.1.4+dev)
command-modules-nspkg (2.0.0+dev)
component (2.0.5+dev)
configure (2.0.8+dev)
consumption (0.1.1+dev)
core (2.0.8+dev)
cosmosdb (0.1.8+dev)
dla (0.0.8+dev)
dls (0.0.8+dev)
feedback (2.0.4+dev)
find (0.2.4+dev)
interactive (0.3.4+dev)
iot (0.1.7+dev)
keyvault (2.0.6+dev)
lab (0.0.6+dev)
monitor (0.0.6+dev)
network (2.0.8+dev)
nspkg (3.0.0+dev)
profile (2.0.6+dev)
rdbms (0.0.3+dev)
redis (0.2.5+dev)
resource (2.0.8+dev)
role (2.0.6+dev)
sf (1.0.3+dev)
sql (2.0.5+dev)
storage (2.0.8+dev)
taskhelp (0.1.3+dev)
vm (2.0.8+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11)
[GCC 5.3.0]

Python location '/usr/local/bin/python'

**OS Version:** What OS and version are you using?  
macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash

**Comment by tjprescott** [comment] 2017-06-16 15:41
Dupe of #3729. Fixed by #3743.

**Closed by tjprescott** 2017-06-16 15:41 UTC

**Comment by joshua-harrison-2011** [comment] 2017-06-16 19:39
@tjprescott Awesome - Thanks!
