### ISSUE TITLE
az storage blob copy start: FAILURE

### ISSUE THREAD

**Issue by wk-n** [Azure/azure-cli#10656] opened 2019-09-26 16:34 UTC
I have "Owner" role on this Resource Group. Below autogenerated output.
## Describe the bug

**Command Name**
`az storage blob copy start`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\output.py", line 132, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\output.py", line 38, in format_json
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob copy start --destination-blob {} --destination-container {} --account-name {} --account-key {} --source-uri {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.74

```

**Comment by yonzhan** [comment] 2019-09-28 08:47
@Juliehzl  please take a look and comment

**Comment by Juliehzl** [comment] 2019-09-28 14:49
Hi @wk-n, can you show me more information with `--debug` in your command? You can also try the new `az storage copy` command to do what you want. Anyway, please show me your debug information and I will help you figure what happened and hide the account key info if it is in your debug information.

**Comment by wk-n** [comment] 2019-09-30 07:23
Hi @Juliehzl, I've made more tests and looks like it's some kind of network issue, unlike the error message. I've done the same steps on 4 environments (linux vm in Azure, linux server standalone and 2runs on same windows laptop, but inside and outside corporate network).

Problem exist only on windows laptop behind corporate network, but with error message:
```You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
```
As i said - same laptop outside corporate network works fine. Here is debug result:
[azstoragecopydebug.txt](https://github.com/Azure/azure-cli/files/3669294/azstoragecopydebug.txt)

On all environments variable values were copypasted, so it's not mispelling issue.

**Comment by Juliehzl** [comment] 2019-10-16 03:12
@wk-n Thanks for you information. We will improve the error message.

**Comment by Juliehzl** [comment] 2019-10-16 08:28
dupe of #9995

**Comment by Juliehzl** [comment] 2019-11-18 07:28
@wk-n Can you check networkRules for your storage account using  az storage account show -n {accountname} --query networkRuleSet?
Please make sure your ip address is allowed in ipRules or vnet is allowed in virtualNetworkRules or defaultAction is "Allow".

**Comment by Juliehzl** [comment] 2019-11-26 13:51
Please try with azure cli 2.0.77. It can throw correct error message for your operation and check your command according to error message. Hope it can help you and I will close it now. If you still have problems, feel free to create a new one.

**Closed by Juliehzl** 2019-11-26 13:51 UTC
Labels: Storage
