### ISSUE TITLE
Always getting the remote exception message after executing the az storage blob upload

### ISSUE THREAD

**Issue by MoueenShaik** [Azure/azure-cli#16503] opened 2021-01-12 17:26 UTC
Hello Team,

I am trying to upload the files to the Azure blob storage by using the following command.

 **az storage blob upload --only-show-errors   --auth-mode login --account-name "BlobName" -c "folder\testing" -f "D:\localfile.txt" -n "localfile.txt"**

file is uploading successfully, but I am getting the below exception in the PowerShell output window. 

Output after executing the commad: 
az : 
At line:2 char:2
+  az storage blob upload --only-show-errors  --auth-mode login --accou ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Alive[################################################################]  100.0000%
Finished[#############################################################]  100.0000%
{
  "etag": "\"0x8D8B71E5AA7EEB3\"",
  "lastModified": "2021-01-12T17:20:27+00:00"
}

Query : How to fix the remote exception error with any command params or how to get rid of the remote exception in output window

Thanks In Advance 
Moueen Shaik

**Comment by yonzhan** [comment] 2021-01-12 22:57
storage

**Comment by Juliehzl** [comment] 2021-01-15 09:05
dupe of #16504

**Closed** 2021-01-15 09:06 UTC
Labels: Storage
