### ISSUE TITLE
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.

### ISSUE THREAD

**Issue by githubdrk** [Azure/azure-cli#23380] opened 2022-07-29 06:16 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

AZ Login
**Describe the bug**

Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
**To Reproduce**

Need to login with a login 
**Expected behavior**

**Environment summary**

using az login  i am getting error
**Additional context**

ERROR Message:A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login 
in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231

**Comment by yonzhan** [comment] 2022-07-29 06:38
Duplicate of https://github.com/Azure/azure-cli/issues/20231

**Closed by yonzhan** 2022-07-29 06:38 UTC
Labels: Account, customer-reported, Installation, Auto-Assign
