### ISSUE TITLE
AZ Cli SSL verification failure with proxy root cert (Python works)

### ISSUE THREAD

**Issue by jeremy-morren** [Azure/azure-cli#29018] opened 2024-05-24 00:16 UTC
### Describe the bug

All cli commands fail with `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure`.

Running ` & "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration').status_code)"` succeeds.

### Related command

Any command

### Errors

`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1006)`

### Issue script & Debug output

Any command

### Expected behavior

No certificate error

### Environment Summary

azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\jerem\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

**Comment by yonzhan** [comment] 2024-05-24 00:16
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2024-05-24 02:15
Duplicate of https://github.com/Azure/azure-cli/issues/26064
It is possibly caused by proxy configuration.

**Closed by bebound** 2024-05-24 02:15 UTC
Labels: question, customer-reported, Azure CLI Team

**Comment by jeremy-morren** [comment] 2024-05-24 02:29
Yes, I know it is a proxy configuration. I have followed all the steps at https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully?tabs=bash%2Cbash2#work-behind-a-proxy and added the ca certs from the proxy I am behind to the cacerts.pem file. This was working previously, but seems to have suddenly broken.

**Comment by jeremy-morren** [comment] 2024-05-24 03:17
Sorry, I finally figured out the problem: One of the proxy certs I was asked to install did not have a `KeyUsageExtension`. Once I removed that certificate from the cacert.pem file, it started working.
