### ISSUE TITLE
"az network application-gateway frontend-ip create" command can't accept more than 4 args

### ISSUE THREAD

**Issue by nakamacchi** [Azure/azure-cli#12965] opened 2020-04-11 01:33 UTC
**Describe the bug**
"az network application-gateway frontend-ip create" command can't accept more than 4 args

**To Reproduce**
nobuyuki@Azure:\~$ az network application-gateway frontend-ip create --gateway-name $AKS_IWF_NAME --resource-group $RG_AKS --name $AKS_IWF_PRIVATE_FRONTEND_IP_NAME
Cannot parse the request.

nobuyuki@Azure:\~$ az network application-gateway frontend-ip create --gateway-name $AKS_IWF_NAME --resource-group $RG_AKS --name MyFrontendIp
Cannot parse the request.

nobuyuki@Azure:\~$ az network application-gateway frontend-ip create --gateway-name $AKS_IWF_NAME --resource-group $RG_AKS
az network application-gateway frontend-ip create: error: the following arguments are required: --name/-n
... (omitted)

nobuyuki@Azure:\~$ az network application-gateway frontend-ip create --name $AKS_IWF_PRIVATE_FRONTEND_IP_NAME
az network application-gateway frontend-ip create: error: the following arguments are required: --resource-group/-g, --gateway-name
... (omitted)

**Additional context**
CLI version 2.2.0, 2.3.1

**Comment by yonzhan** [comment] 2020-04-11 03:05
add to S169

**Comment by MyronFanQiu** [comment] 2020-04-13 01:30
@nakamacchi Can you run the first command with --debug? Is the error message `Cannot parse the request.`?

**Comment by yonzhan** [comment] 2020-05-03 00:24
add to S171

**Comment by yonzhan** [comment] 2020-05-03 00:24
@nakamacchi any update for this issue?

**Comment by MyronFanQiu** [comment] 2020-06-02 09:47
@nakamacchi Hi. Did you still meet this issue?

**Comment by MyronFanQiu** [comment] 2020-06-11 07:00
close this issue since cannot reproduce.

**Closed by MyronFanQiu** 2020-06-11 07:00 UTC
Labels: Network, OKR3.2 Candidate, feature-request
