### ISSUE TITLE
[RBAC] Role assignment create: required permissions

### ISSUE THREAD

**Issue by Henchway** [Azure/azure-cli#5738] opened 2018-03-06 18:10 UTC
Which Microsoft Graph permissions are required to set the owner of e.g. a Resource group on which the User setting it has Owner permissions?
I recon that the Azure CLI still uses graph.windows.net and not graph.microsoft.com, which I believe to be the new interface (?), with which i had permissions enough via REST, but not with CLI it seems.
az role assignment create --role Owner --resource-group JIRA --assignee {user}
When using the ID, i'm getting:  Forbidden for url: https://graph.windows.net/ 
When using the UPN, i'm getting "Insufficient privileges to complete the operation." and a Traceback list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dacfad8-cb2f-2534-3b29-89b0930a2252
* Version Independent ID: 17325cd4-44c5-4069-d9f6-940a55f0f7c9
* [Content](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest#az_role_assignment_create)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: azure-resource-manager

**Comment by yugangw-msft** [comment] 2018-06-19 18:18
The CLI/RBAC uses AAD-Graph instead of MS-Graph. You are right, the endpoint is `graph.windows.net` 
For `set the owner of e.g. a Resource group` you don't go through the graph permission, rather go through role assignment, e.g. `az role assignment create -g myResourceGroup --role owner`
The error of `Forbidden for url: https://graph.windows.net/` is caused by you logged in using a service principal, which hasn't been given the permission to AAD graph and you need to configure separately. So check out [this comment](https://github.com/Azure/azure-sdk-for-node/issues/2363#issuecomment-354897064). Note 'az ad app create' would also let you configure the permission, but you still need to go to portal and click the button of `Grant Permission` to settle all, so you are better off just doing all in the portal
It is definitely not a trivial process, but due to the limitation at the service level, CLI is not able to configure all for you.
I am closing this since this is not a CLI bug, but feel free to post any follow-up questions here. And sorry for the delay in response.

**Closed by yugangw-msft** 2018-06-19 18:18 UTC
Labels: Authorization-cli, Question
