### ISSUE TITLE
HomeBrew Brew update brakes az-cli Version 2.26.0

### ISSUE THREAD

**Issue by 0hlov3** [Azure/azure-cli#18772] opened 2021-07-08 10:56 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.26.0

**Describe the bug**

After Updating the azure-cli on the Mac (Version 11.4) with brew upgrade  I got the following error messages.

```
❯ az vm list
/usr/local/Cellar/azure-cli/2.26.0/libexec/bin/python: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed
```

```
or while finding module specification for 'azure.cli' (ModuleNotFoundError: No module named 'azure')
```

So I was playing with different Python Versions etc. But nothing helped.

So I was going to install the python modules myself:
```
pip install azure.cli
pip install azure
```
Error output

```
[...]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azure 4.0.0 requires azure-batch~=4.1, but you have azure-batch 10.0.0 which is incompatible.
azure 4.0.0 requires azure-graphrbac~=0.40.0, but you have azure-graphrbac 0.60.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-advisor~=1.0, but you have azure-mgmt-advisor 9.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-applicationinsights~=0.1.1, but you have azure-mgmt-applicationinsights 1.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-authorization~=0.50.0, but you have azure-mgmt-authorization 0.61.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-batch~=5.0, but you have azure-mgmt-batch 15.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-billing~=0.2.0, but you have azure-mgmt-billing 6.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-cdn~=3.0, but you have azure-mgmt-cdn 11.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-cognitiveservices~=3.0, but you have azure-mgmt-cognitiveservices 12.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-compute~=4.0, but you have azure-mgmt-compute 21.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-containerregistry~=2.1, but you have azure-mgmt-containerregistry 8.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-containerservice~=4.2, but you have azure-mgmt-containerservice 16.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-cosmosdb~=0.4.1, but you have azure-mgmt-cosmosdb 6.4.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-datalake-analytics~=0.6.0, but you have azure-mgmt-datalake-analytics 0.2.1 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-datamigration~=1.0, but you have azure-mgmt-datamigration 4.1.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-devtestlabs~=2.2, but you have azure-mgmt-devtestlabs 4.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-dns~=2.0, but you have azure-mgmt-dns 8.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-eventgrid~=1.0, but you have azure-mgmt-eventgrid 9.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-eventhub~=2.1, but you have azure-mgmt-eventhub 4.1.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-iotcentral~=0.1.0, but you have azure-mgmt-iotcentral 4.1.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-iothub~=0.5.0, but you have azure-mgmt-iothub 2.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-keyvault~=1.0, but you have azure-mgmt-keyvault 9.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-loganalytics~=0.2.0, but you have azure-mgmt-loganalytics 8.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-marketplaceordering~=0.1.0, but you have azure-mgmt-marketplaceordering 1.1.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-media~=1.0.0rc2, but you have azure-mgmt-media 3.1.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-monitor~=0.5.2, but you have azure-mgmt-monitor 2.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-network~=2.0, but you have azure-mgmt-network 19.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-policyinsights~=0.1.0, but you have azure-mgmt-policyinsights 0.5.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-rdbms~=1.2, but you have azure-mgmt-rdbms 8.1.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-recoveryservices~=0.3.0, but you have azure-mgmt-recoveryservices 1.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-recoveryservicesbackup~=0.3.0, but you have azure-mgmt-recoveryservicesbackup 0.12.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-redis~=5.0, but you have azure-mgmt-redis 7.0.0rc2 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-reservations~=0.2.1, but you have azure-mgmt-reservations 0.6.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-resource~=2.0, but you have azure-mgmt-resource 18.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-search~=2.0, but you have azure-mgmt-search 8.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-servicebus~=0.5.1, but you have azure-mgmt-servicebus 6.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-servicefabric~=0.2.0, but you have azure-mgmt-servicefabric 0.5.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-signalr~=0.1.0, but you have azure-mgmt-signalr 1.0.0b2 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-sql~=0.9.1, but you have azure-mgmt-sql 0.29.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-storage~=2.0, but you have azure-mgmt-storage 18.0.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-trafficmanager~=0.50.0, but you have azure-mgmt-trafficmanager 0.51.0 which is incompatible.
azure-mgmt 4.0.0 requires azure-mgmt-web~=0.35.0, but you have azure-mgmt-web 2.0.0 which is incompatible.
[...]
```

But now everything works as expected.

**To Reproduce**
```
brew update && \
brew upgrade azure-cli &&  \
brew install python3 && \
 brew upgrade python && \
brew link --overwrite python3 && \
brew link --overwrite  azure-cli 
```

**Expected behavior**
brew upgrade should not brake azure-cli

**Environment summary**
- MacOS 11.4
- Python: Python 3.9.6
- Azure-CLI: 2.26.0
- PIP: pip 21.1.3 (python 3.9)
- HomeBrew

**Additional context**
I don't know why the azure-cli broke, however I believe a custom python version was included (but am unsure), however now the python is set as symlink.

```
> ls -la /usr/local/Cellar/azure-cli/2.26.0/libexec/bin/python
[REDACTED] /usr/local/Cellar/azure-cli/2.26.0/libexec/bin/python -> ../../../../../opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3.9

```

**Comment by yonzhan** [comment] 2021-07-08 11:03
HomeBrew

**Comment by jiasli** [comment] 2021-08-19 07:35
Duplicate of #19027

**Closed** 2021-08-19 07:35 UTC
Labels: Packaging, Packaging/Homebrew
