### ISSUE TITLE
Issue trying to create backup policy from Azure CLI

### ISSUE THREAD

**Issue by wallace223** [Azure/azure-cli#16345] opened 2020-12-23 02:11 UTC
## Describe the bug

**Command Name**
`az backup policy create`

**Errors:**
wallace@Azure:~$ az backup policy create --policy {policy} --resource-group K8s --vault-name RSV1000 --name wchen-backup-test02 --backup-management-type AzureIaasVM --workload-type VM
Command group 'backup' is in preview. It may be changed/removed in a future release.
CLIInternalError: The command failed with an unexpected error. Here is the traceback:

            The variable passed should be in valid JSON format and be supplied by az backup CLI commands.
            Make sure that you use output of relevant 'az backup show' commands and the --out is 'json'
            (use -o json for explicit JSON output) while assigning value to this variable.
            Take care to edit only the values and not the keys within the JSON file or string.

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_base.py", line 44, in create_policy
    return custom.create_policy(client, resource_group_name, vault_name, name, policy)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 182, in create_policy
    policy_object = _get_policy_from_json(client, policy)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 974, in _get_policy_from_json
    return _get_object_from_json(client, policy, 'ProtectionPolicyResource')
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 1009, in _get_object_from_json
    json_obj = _get_or_read_json(json_or_file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 1003, in _get_or_read_json
    """)
ValueError:
            The variable passed should be in valid JSON format and be supplied by az backup CLI commands.
            Make sure that you use output of relevant 'az backup show' commands and the --out is 'json'
            (use -o json for explicit JSON output) while assigning value to this variable.
            Take care to edit only the values and not the keys within the JSON file or string.
```
The variable passed should be in valid JSON format and be supplied by az backup CLI commands.
            Make sure that you use output of relevant 'az backup show' commands and the --out is 'json'
            (use -o json for explicit JSON output) while assigning value to this variable.
            Take care to edit only the values and not the keys within the JSON file or string.
            
Traceback (most recent call last):
...
            Make sure that you use output of relevant 'az backup show' commands and the --out is 'json'
            (use -o json for explicit JSON output) while assigning value to this variable.
            Take care to edit only the values and not the keys within the JSON file or string.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup policy create --policy {} --resource-group {} --vault-name {} --name {} --backup-management-type {} --workload-type {}`

## Environment Summary
```
Linux-4.15.0-1102-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.16.0

Extensions:
ai-examples 0.2.5

```

**Comment by yonzhan** [comment] 2020-12-23 02:32
backup

**Comment by pvrk** [comment] 2020-12-23 07:59
@wallace223 : Without the actual policy details, it is hard to figure out the error root cause. Can you please provide the JSON file details to my email "pullabhk@microsoft.com"?

**Comment by mepand** [comment] 2021-01-11 12:06
@wallace223 Could you please share the policy details?

**Comment by pvrk** [comment] 2021-02-26 11:57
@wallace223: If the issue still exists, can you please provide the policy details?

**Comment by mepand** [comment] 2021-03-05 12:58
Since we don't have the policy, its difficult to troubleshoot . Closing the issue for the time being. Incase any further assistance if required from the PG team, please feel free to reopen it.

**Closed by mepand** 2021-03-05 12:58 UTC
Labels: Recovery Services Backup, Service Attention, customer-response-expected

**Comment by sknaresh2000** [comment] 2021-04-29 16:05
> Since we don't have the policy, its difficult to troubleshoot . Closing the issue for the time being. Incase any further assistance if required from the PG team, please feel free to reopen it.

I have the same issue while creating a policy via CLI. The same JSON policy works via REST API. Please see attached. 
[SQLBackupPolicy.txt](https://github.com/Azure/azure-cli/files/6400028/SQLBackupPolicy.txt)
