### ISSUE TITLE
[INTERACTIVE] AZ LOGIN SSL VERIFY ERROR 

### ISSUE THREAD

**Issue by jeff-block** [Azure/azure-cli#4197] opened 2017-08-10 23:35 UTC
### Description
**Outline the issue here:**

az>> login --debug
Loading all installed modules as module with name 'login' not found.
Installed command modules ['acr', 'acs', 'appservice', 'batch', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'component', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'resource', 'role', 'sf', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.000 seconds.
Loaded module 'acs' in 0.000 seconds.
Loaded module 'appservice' in 0.000 seconds.
Loaded module 'batch' in 0.000 seconds.
Loaded module 'billing' in 0.000 seconds.
Loaded module 'cdn' in 0.000 seconds.
Loaded module 'cloud' in 0.000 seconds.
Loaded module 'cognitiveservices' in 0.000 seconds.
Loaded module 'component' in 0.000 seconds.
Loaded module 'configure' in 0.000 seconds.
Loaded module 'consumption' in 0.000 seconds.
Loaded module 'container' in 0.000 seconds.
Loaded module 'cosmosdb' in 0.000 seconds.
Loaded module 'dla' in 0.000 seconds.
Loaded module 'dls' in 0.000 seconds.
Loaded module 'feedback' in 0.000 seconds.
Loaded module 'find' in 0.000 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.000 seconds.
Loaded module 'keyvault' in 0.000 seconds.
Loaded module 'lab' in 0.000 seconds.
Loaded module 'monitor' in 0.000 seconds.
Loaded module 'network' in 0.000 seconds.
Loaded module 'profile' in 0.000 seconds.
Loaded module 'rdbms' in 0.000 seconds.
Loaded module 'redis' in 0.000 seconds.
Loaded module 'resource' in 0.000 seconds.
Loaded module 'role' in 0.000 seconds.
Loaded module 'sf' in 0.000 seconds.
Loaded module 'sql' in 0.000 seconds.
Loaded module 'storage' in 0.000 seconds.
Loaded module 'vm' in 0.000 seconds.
Loaded all modules in 0.001 seconds. (note: there's always an overhead with the first module loaded)
Application event 'CommandTable.Loaded' with event data {'command_table': {'login': <azure.cli.core.commands.CliCommand object at 0x03EDD650>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'login': <azure.cli.core.commands.CliCommand object at 0x03EDD650>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['login']}
Application event 'CommandParser.Parsed' with event data {'command': 'login', 'args': Namespace(_command_package='login', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az login', usage=None, description='Log in to access Azure subscriptions', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[], allow_no_subscriptions=False, command='login', func=<azure.cli.core.commands.CliCommand object at 0x03EDD650>, [...]
attempting to read file C:\Users\xxxx\.azure\accessTokens.json as utf-8-sig
adal-python : 9ffe0e0b-4e6a-45c8-be46-1bc40aa5f165 - Authority:Performing instance discovery: https://login.microsoftonline.com/common
adal-python : 9ffe0e0b-4e6a-45c8-be46-1bc40aa5f165 - Authority:Performing static instance discovery
adal-python : 9ffe0e0b-4e6a-45c8-be46-1bc40aa5f165 - Authority:Authority validated via static instance discovery
adal-python : 9ffe0e0b-4e6a-45c8-be46-1bc40aa5f165 - CodeRequest:Getting user code info.
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/devicecode?api-version=1.0 HTTP/1.1" 200 441
adal-python : 9ffe0e0b-4e6a-45c8-be46-1bc40aa5f165 - OAuth2Client:Get Device Code Server returned this correlation_id: 9ffe0e0b-4e6a-45c8-be46-1bc40aa5f165
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code A4F7CHKKQ to authenticate.
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - Authority:Instance discovery/validation has either already been completed or is turned off: https://login.microsoftonline.com/common
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - TokenRequest:Getting a token via device code
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /common/oauth2/token HTTP/1.1" 200 3767
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - OAuth2Client:Get token with device code Server returned this correlation_id: 02f39063-de78-4209-831b-89a77d5f133e
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - TokenRequest:Storing retrieved token into cache
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - OAuth2Client:Adding entry AccessTokenId: b'/FiQ58tuVWOx00kgqN6w86LJBCcnEFBFVTjbXCL45vk=', RefreshTokenId: b'rqurmGd3cxjLV7BrIu7iWrUAMYDvrcfgJ8GvjiSJ8/w='
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - OAuth2Client:Added entry is MRRT
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - OAuth2Client:Updating 3 cached refresh tokens
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - OAuth2Client:Remove many:3
adal-python : 02f39063-de78-4209-831b-89a77d5f133e - OAuth2Client:Add many: 3
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
urllib3.util.retry : Incremented Retry for (url='/tenants?api-version=2016-06-01'): Retry(total=2, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=2, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)': /tenants?api-version=2016-06-01
urllib3.connectionpool : Starting new HTTPS connection (2): management.azure.com
urllib3.util.retry : Incremented Retry for (url='/tenants?api-version=2016-06-01'): Retry(total=1, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=1, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)': /tenants?api-version=2016-06-01
urllib3.connectionpool : Starting new HTTPS connection (3): management.azure.com
urllib3.util.retry : Incremented Retry for (url='/tenants?api-version=2016-06-01'): Retry(total=0, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=0, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)': /tenants?api-version=2016-06-01
urllib3.connectionpool : Starting new HTTPS connection (4): management.azure.com
msrest.exceptions : Error occurred in request., ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /tenants?api-version=2016-06-01 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.12)

acr (2.0.9)
acs (2.0.11)
appservice (0.1.11)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
container (0.1.7)
core (2.0.12)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.11)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.11)
nspkg (3.0.1)
profile (2.0.9)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.11)
role (2.0.9)
sf (1.0.5)
sql (2.0.8)
storage (2.0.11)
vm (2.0.11)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

**OS Version:** What OS and version are you using?  
Answer here:
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
cmd

**Comment by yugangw-msft** [comment] 2017-08-11 18:49
> HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /tenants?api-version=2016-06-01 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))

@jmblock, likely you hit a temporary service end issue during their deployment. Such error  did happen before. I am not able to reproduce it right now. Could you try again?

**Comment by tjprescott** [comment] 2018-02-14 22:17
Login is disabled in `az interactive`. Closing.

**Closed by tjprescott** 2018-02-14 22:17 UTC
Labels: Interactive
