### ISSUE TITLE
error by importing via az extension add

### ISSUE THREAD

**Issue by syntetic81** [Azure/azure-cli#24914] opened 2022-12-16 07:32 UTC
## Describe the bug

**Command Name**
`az extension add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unknown extension type. Only Python wheels are supported.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 341, in add_extension
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 102, in _add_whl_ext
ValueError: Unknown extension type. Only Python wheels are supported.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add --source {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0 *

Extensions:
ssh 1.1.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by syntetic81** [comment] 2022-12-16 07:52
also after updating to new az version same error

**Comment by bebound** [comment] 2022-12-16 08:21
I can't see your full command, but I guess it's duplicate of https://github.com/Azure/azure-cli/issues/12034

**Closed** 2023-01-06 17:01 UTC
Labels: question, Extensions, customer-reported, needs-author-feedback, no-recent-activity, CXP Attention
