### ISSUE TITLE
az storage logging update not producing any json output

### ISSUE THREAD

**Issue by lotaezhao** [Azure/azure-cli#12357] opened 2020-02-26 12:21 UTC
This command doesn't produce any json output when run as is the case with other az cli commands. 

Also when you run it without specifying a connection string, account key or sas token it displays the warning:
"No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account."
This warning is problematic for running the commands in scripts that are reading stdout, there needs to be a way of suppressing it and returning just the json object you'd expect when az cli is executed successfully. The command executes successfully despite the warning and It's obvious that if you don't provide those values that you want to query the account keys so why do we even need the warning? 

In my case I'm running this command via the 'external' provider in Terraform which requires a valid json return value which I am unable to get.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c237378a-a708-8e2f-3c8c-0bc8b623d21c
* Version Independent ID: c4e27b67-9605-60f5-899d-8ffd727079b2
* Content: [az storage logging](https://docs.microsoft.com/en-us/cli/azure/storage/logging?view=azure-cli-latest&source=docs#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-02-27 02:06
add to S167.

**Comment by qianwens** [comment] 2020-03-15 09:57
Same issue as #12193 , this will be fixed by new feature --only-show-errors to provide a way to avoid warning message.

**Comment by Juliehzl** [comment] 2020-04-20 02:41
Hi @lotaezhao, thanks for your feedback! Actually it is by design because we will add breaking change for such usage, which will make credential information required in command to avoid extra request in server side.
In addition, `--only-show-errors` is supported in latest CLI to filter warning message. But I will recommend you to add additional credentials to prevent the changes in the future.

I will close this issue and if there is still a problem, please feel free to create a new one or reopen it.

**Closed by Juliehzl** 2020-04-20 02:41 UTC
Labels: Feature Request, OKR3.2 Candidate, Storage
