### ISSUE TITLE
"az ad sp credential reset --id XXXX --append" creates app secret that is not available in the portal

### ISSUE THREAD

**Issue by oleksii-motonakha** [Azure/azure-cli#26724] opened 2023-06-21 15:42 UTC
### Describe the bug

After upgrading azure-cli from 2.32.0 to 2.49.0 there is issue related to 'az ad sp credential'. 
When using the portal and the command line, I get different results for managing secrets. E.g. Secrets created in portal are not available using 'az ad sp credential list --id XXXX' and vice versa secrets created using 'az ad sp credential reset --id XXXX --append' are not available in portal.

### Related command

`az ad sp credential list --id XXXX` shows secrets created only by the command line `az ad sp credential reset --id XXXX --append`

### Errors

N/A

### Issue script & Debug output

N/A

### Expected behavior

`az ad sp credential list --id XXXX` this command should display the secrets created in the portal and command line
`az ad sp credential reset --id XXXX --append` this command should create secrets that should be visible in the portal

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
databricks                         0.8.0
datafactory                        0.7.0
storage-preview                    0.8.3

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python (Darwin) 3.8.13 (default, Jun 20 2022, 10:21:31) 
[Clang 12.0.0 (clang-1200.0.32.29)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment] 2023-06-21 15:42
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2023-06-26 03:47
Duplicate of https://github.com/Azure/azure-cli/issues/23566

**Closed by jiasli** 2023-06-26 03:47 UTC
Labels: bug, Service Attention, Graph, customer-reported, Auto-Assign, Azure CLI Team
