### ISSUE TITLE
`aks get-credentials` failed

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-cli#10307] opened 2019-08-23 09:06 UTC
**This is autogenerated. Please review and update as needed.**

Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
'users'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 693, in reraise
    raise value
...
cli/command_modules/acs/custom.py, ln 2415, in _print_or_merge_credentials
    merge_kubernetes_configurations(path, temp_path, overwrite_existing)
cli/command_modules/acs/custom.py, ln 1064, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'users', replace)
cli/command_modules/acs/custom.py, ln 1006, in _handle_merge
    if existing[key] is None:
KeyError: 'users'
```

To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --debug`

Expected Behavior

Environment Summary
```
Linux-4.18.0-1023-azure-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.70 *

```
Additional Context

**Comment by FooBarWidget** [comment] 2019-10-11 08:33
I think this is a duplicate of https://github.com/Azure/azure-cli/issues/10812

**Comment by jluk** [comment] 2019-12-05 00:00
Closing in favor of the duplicate #10812 please visit that open issue for latest discussion

**Closed by jluk** 2019-12-05 00:00 UTC
Labels: AKS, Service Attention
