### ISSUE TITLE
`az webapp up` with --logs results in exception and no logs

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli#23058] opened 2022-06-29 00:11 UTC
### **This is autogenerated. Please review and update as needed.**

For a while now, nearly every time I run `az webapp up` with the --logs argument, I get the exception message below, and never see any logs. 

**Command Name**
`az webapp up`

**Errors:**
```
 >  az webapp up --runtime 'PYTHON:3.9' --sku B1 --logs --os-type linux
Parameter persistence is turned on. Its information is saved in working directory C:\git. You can run `az config param-persist off` to turn it off.
Command argument values from persistent parameters: --resource-group: charris-django-cms, --location: canadacentral
The webapp 'delightful-forest-843a3e127b744275a0ef056edf4510e8' doesn't exist
Creating AppServicePlan 'charris_asp_8518' ...
Creating webapp 'delightful-forest-843a3e127b744275a0ef056edf4510e8' ...
Configuring default logging for the app, if not already enabled
Creating zip with contents of dir C:\git\azure\msdocs-python-fastapi-webapp-quickstart ...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
You can launch the app at http://delightful-forest-843a3e127b744275a0ef056edf4510e8.azurewebsites.net
Configuring default logging for the app, if not already enabled
2022-06-29T00:03:52  Welcome, you are now connected to log-streaming service.
Exception in thread Thread-1 (_get_log):
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 697, in _update_chunk_length
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 438, in _error_catcher
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 764, in read_chunked
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 701, in _update_chunk_length
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2582, in _get_log
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 572, in stream
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 752, in read_chunked
  File "contextlib.py", line 153, in __exit__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 455, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
Terminate batch job (Y/N)? y

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ` az webapp up --runtime 'PYTHON:3.9' --sku B1 --logs --os-type linux`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
azure-dev 0.0.1b456
containerapp 0.3.7
rdbms-connect 1.0.2
webapp 0.4.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-06-29 00:57
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-06-29 02:43
@charris-msft Thank you for reaching out, we are looking into it.

**Comment by panchagnula** [comment] 2022-07-14 16:27
@StrawnSC looking at the stack this doesn't seem like a CLI issue rather may be a runtime problem. Given this SKU Basic , please check if log streaming is supported on Linux for this.

**Comment by btardif** [comment] 2023-06-28 15:38
We should connect the status API to this command @vivekjilla to review mocs

**Comment by tulikac** [comment] 2023-09-20 14:41
This is a duplicate of https://github.com/Azure/azure-cli/issues/25599. We will be tracking the original issue.

**Closed** 2023-10-04 14:51 UTC
Labels: bug, Web Apps, Service Attention, Auto-Assign, app-service-logging-monitoring
