### ISSUE TITLE
Operation failed. [Code: "ResourceNotFound"]

### ISSUE THREAD

**Issue by mariojacobo** [Azure/azure-cli#8570] opened 2019-02-19 16:34 UTC
While trying to create a diagnostic setting for a Key Vault, I get this error: 
Operation failed. [Code: "ResourceNotFound"]

Command:  $ az monitor diagnostic-settings create --resource /subscriptions/REDACTED/resourceGroups/My-RG/providers/Microsoft.KeyVault/vaults/test-kv11 -n test --workspace testsdevws01 --storage-account testarchivedev1 --logs '[
                             {
                               "category": "AuditEvent",
                               "enabled": true,
                               "retentionPolicy": {
                                 "enabled": true,
                                 "days": 365
                               }
                             }
                           ]'
                           --metrics '[
                             {
                               "category": "AllMetrics",
                               "enabled": true,
                               "retentionPolicy": {
                                 "enabled": false,
                                 "days": 365
                               }
                             }
                           ]'

The --resource exists: 

$ az keyvault list --query [].id -o tsv

/subscriptions/REDACTED/resourceGroups/My-RG/providers/Microsoft.KeyVault/vaults/test-kv11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ae3afa-74ff-12e8-a32c-c01240bd37da
* Version Independent ID: 522b7e55-2510-8e51-021a-2fc134fabfbe
* Content: [az monitor diagnostic-settings](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings?view=azure-cli-latest#az-monitor-diagnostic-settings-create)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment] 2019-02-19 16:37
Please provide the output of `az --version`. Additionally, please run the command with --debug and see if you get any more error information (do not just paste the whole debug output)

**Comment by mariojacobo** [comment] 2019-02-20 08:02
ob@Azure:~$ az --version
azure-cli                         2.0.58

I'm running all the commands in the Azure cloud shell, so the versioning is managed automatically by Azure afaik. 

Ran the same command using a different subscription and different RG and getting below errors: 

urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/REDACTED/resourceGroups/drupal-acr-poc/providers/Microsoft.KeyVault/vaults/test111222/providers/microsoft.insights/diagnosticSettings/test?api-version=2017-05-01-preview HTTP/1.1" 404 42
msrest.http_logger : {"code":"ResourceNotFound","message":null}
msrest.exceptions : Operation returned an invalid status code 'Not Found'
Operation failed. [Code: "ResourceNotFound"]

The Keyvault exists, so not sure what is happening here.

**Comment by tjprescott** [comment] 2019-02-21 23:33
@mariojacobo I was able to reproduce this and it was the OperationalInsights workspace that did not exist. Apparently the service throws a bad error when any of the related resources cannot be found. Since you provided names for both the workspace and storage account, if either of those are in a different subscription or resource group, they would not be found and might be the reason for your error. Try supplying those values by ID.

**Comment by mariojacobo** [comment] 2019-02-22 13:33
Looks to be working fine @tjprescott, thanks a lot.  Also, this (https://github.com/Azure/azure-cli/issues/5637) helped with getting both logs and metrics.

**Comment by tjprescott** [comment] 2019-02-22 16:27
Glad it is working for you @mariojacobo. I will leave this issue open because the service team needs to fix the bad error messages.

**Comment by MyronFanQiu** [comment] 2019-09-02 03:30
@Dalubash Could you please take a look at this issue?

**Comment by asheniam** [comment] 2019-09-03 16:18
Thanks for sharing this feedback.  We plan to rollout an improvement to the error message by early October.

**Comment by MyronFanQiu** [comment] 2019-12-31 06:07
@asheniam Hello. Is there any update about this issue?

**Comment by asheniam** [comment] 2020-04-04 17:03
The error message should be fixed already.

**Closed by asheniam** 2020-04-04 17:03 UTC
Labels: Monitor - Diagnostic Settings, Service Attention
