### ISSUE TITLE
az aks create fails with Internal Server Error

### ISSUE THREAD

**Issue by markheath** [Azure/azure-cli#10281] opened 2019-08-20 15:07 UTC
## Describe the bug
Trying to create an AKS cluster, but am getting "Bad Request" - "Internal server error"

**Command Name**
`az aks create`

**Errors:**
```
Operation failed with status: 'Bad Request'. Details: Internal server error
```

## To Reproduce:

- Create an empty resource group
- `az aks create -g aksrg -n myaks --node-count 3 --generate-ssh-keys`

## Expected Behavior
Creates an AKS Cluster

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.71

Extensions:
noelbundick 0.0.15

```
## Additional Context

If I run with `--verbose` I get the following output:

```
Use existing SSH public key file: G:\\.ssh\id_rsa.pub
Operation failed with status: 'Bad Request'. Details: Internal server error
command ran in 2.050 seconds.
```

**Comment by markheath** [comment] 2019-08-21 08:13
Fails with the same error in Cloud Shell as well, and also fails if I leave off the `--node-count` and `--generate-ssh-keys` arguments

**Comment by markheath** [comment] 2019-08-21 12:06
I tried creating an AKS cluster in the portal on this subscription, and that failed in a similar way too, but the error gives a good hint of what is going wrong:

```
{"code":"InvalidTemplateDeployment",
"message":"The template deployment 'microsoft.aks-20190821092627' is not valid according to the validation procedure. The tracking id is 'd4532f1a-036b-41f7-8c28-2ffe8c5fa6aa'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.",
"details":[{"code":"BadRequest",
"message":"Provisioning of resource(s) for container service MarkKedaTest in resource group KedaTest failed. 
Message: {
  "code": "BadRequest",
  "message":\"The credentials in ServicePrincipalProfile were invalid. Please see https://aka.ms/aks-sp-help for more details. (Details: adal: Refresh request failed. Status Code = '400'. 
Response body: {
"error":"unauthorized_client",
"error_description":"AADSTS700016: Application with identifier 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' was not found in the directory 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: a89e3424-4b56-422d-8dc6-8640fbff1700
Correlation ID: 6fb10d6e-0d93-4806-8f76-b5fa84f1f4f0
Timestamp: 2019-08-21 08:32:51Z",
"error_codes":[700016],
"timestamp":"2019-08-21 08:32:51Z",
"trace_id":
"a89e3424-4b56-422d-8dc6-8640fbff1700",
"correlation_id":"6fb10d6e-0d93-4806-8f76-b5fa84f1f4f0",
"error_uri":"https://login.microsoftonline.com/error?code=700016"})"
 }. Details: "}]}
```

So it seems that the service principal it wants to use is not available for some reason.

This means I can workaround the issue with `az aks create` by first creating a service principal manually with `az ad sp create-for-rbac --skip-assignment` and then using the `--service-principal` and `--client-secret` arguments for `az aks create`

**Comment by jluk** [comment] 2019-12-04 23:54
@markheath unfortunately this looks like the same issue reported in https://github.com/Azure/AKS/issues/1206 which is caused by AAD propagation delays. Given this has been a few months and it looks tied to the same problem, I am going to close this issue as a duplicate but please comment on the related issue or open a new one on the AKS github repo if needed given this is a service issue and not a CLI problem.

**Closed by jluk** 2019-12-04 23:54 UTC
Labels: AKS, Service Attention
