### ISSUE TITLE
[sig] image version exclude-from-latest parameter is not working

### ISSUE THREAD

**Issue by bsemperlotti** [Azure/azure-cli#8720] opened 2019-03-07 13:42 UTC
**Describe the bug**
Flag parameter `--exclude-from-latest` in command `az sig image-version create` is not working as expected and cannot be set.

**To Reproduce**

Using `--exclude-from-latest` as a flag or setting it to `true` raises an error

```bash
az sig image-version create \ 
   --subscription xxxxxxx \
   --location "WestEurope" \
   -g image_gallery \
   --gallery-name xxx \
   --gallery-image-definition xxxx \
   --gallery-image-version xx.xx.xx \
   --target-regions "WestEurope=1" \
   --replica-count 2 \
   --managed-image "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/xxxxxx" \
   --exclude-from-latest

The value 'True' of parameter 'galleryImageVersion.properties.publishingProfile.excludeFromLatest' is not allowed. Allowed values are 'false'.
```

```bash
az sig image-version create \ 
   --subscription xxxxxxx \
   --location "WestEurope" \
   -g image_gallery \
   --gallery-name xxx \
   --gallery-image-definition xxxx \
   --gallery-image-version xx.xx.xx \
   --target-regions "WestEurope=1" \
   --replica-count 2 \
   --managed-image "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/xxxxxx" \
   --exclude-from-latest true

The value 'True' of parameter 'galleryImageVersion.properties.publishingProfile.excludeFromLatest' is not allowed. Allowed values are 'false'.
```

Not using `--exclude-from-latest` or setting it to `false` works as expected

```bash
az sig image-version create \ 
   --subscription xxxxxxx \
   --location "WestEurope" \
   -g image_gallery \
   --gallery-name xxx \
   --gallery-image-definition xxxx \
   --gallery-image-version xx.xx.xx \
   --target-regions "WestEurope=1" \
   --replica-count 2 \
   --managed-image "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/xxxxxx" \
   --exclude-from-latest false

- Running ..
```

```bash
az sig image-version create \ 
   --subscription xxxxxxx \
   --location "WestEurope" \
   -g image_gallery \
   --gallery-name xxx \
   --gallery-image-definition xxxx \
   --gallery-image-version xx.xx.xx \
   --target-regions "WestEurope=1" \
   --replica-count 2 \
   --managed-image "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/xxxxxx"

- Running ..
```

**Expected behavior**

Expected behavior is no error when using parameter as a flag `--exclude-from-latest` or setting a it to `true` : `--exclude-from-latest true`

**Environment summary**

OS: MacOS 10.14.3 Mojave
Shell: ZSH
Install method: homebrew
cli version:

```bash
azure-cli                         2.0.59

acr                                2.2.1
acs                               2.3.18
advisor                            2.0.0
ams                                0.4.2
appservice                        0.2.14
backup                             1.2.1
batch                              4.0.0
batchai                            0.4.7
billing                            0.2.0
botservice                         0.1.7
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices                  0.2.4
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.14
core                              2.0.59
cosmosdb                           0.2.8
dla                                0.2.4
dls                                0.1.8
dms                                0.1.2
eventgrid                          0.2.1
eventhubs                          0.3.3
extension                          0.2.3
feedback                           2.1.4
find                              0.2.13
hdinsight                          0.3.1
interactive                        0.4.1
iot                                0.3.6
iotcentral                         0.1.6
keyvault                          2.2.12
kusto                              0.2.0
lab                                0.1.5
maps                               0.3.3
monitor                           0.2.10
network                            2.3.3
nspkg                              3.0.3
policyinsights                     0.1.1
profile                            2.1.3
rdbms                              0.3.7
redis                              0.4.1
relay                              0.1.3
reservations                       0.4.1
resource                          2.1.11
role                               2.4.1
search                             0.1.1
security                           0.1.0
servicebus                         0.3.3
servicefabric                     0.1.13
signalr                            1.0.0
sql                                2.1.9
sqlvm                              0.1.0
storage                            2.3.1
telemetry                          1.0.1
vm                                2.2.16

Extensions:
subscription                       0.1.1
image-copy-extension               0.0.9

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/bsemperlotti/.azure/cliextensions'

Python (Darwin) 3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by tjprescott** [comment] 2019-03-11 17:28
@adewaleo is this using three-state flag?

**Comment by adewaleo** [comment] 2019-03-11 21:20
@bsemperlotti @tjprescott, I've started looking into this. The command is indeed using three-state flag, however the problem is either with how the command uses the SDK / interacts with arm or with the service itself.

**Comment by adewaleo** [comment] 2019-04-04 23:41
@bsemperlotti so this issue is indeed a service end issue. A fix will be rolled out this month, after which the CLI command should be working correctly. They haven't gotten back to me on the release date yet.

I will close the issue when the update has been released by the compute team.

**Comment by adewaleo** [comment] 2019-04-30 20:32
Closing this issue as it has been resolved on the service end:

```
$ az sig image-version create -r tosinsig -i tosindef -g ova-test -e 0.0.2 --exclude-from-latest True --managed-image "/subscriptions/000000/resourceGroups/ova-test/providers/Microsoft.Compute/images/image1"
{
  "id": "/subscriptions/000000/resourceGroups/ova-test/providers/Microsoft.Compute/galleries/tosinsig/images/tosindef/versions/0.0.2",
  "location": "westus",
  "name": "0.0.2",
  "provisioningState": "Succeeded",
  "publishingProfile": {
    "endOfLifeDate": null,
    "excludeFromLatest": true,
    "publishedDate": "2019-04-30T18:48:56.665669+00:00",
    "replicaCount": 1,
    "source": {
      "managedImage": {
        "id": "/subscriptions/000000/resourceGroups/ova-test/providers/Microsoft.Compute/images/image1",
        "resourceGroup": "ova-test"
      }
    },
    "storageAccountType": "Standard_LRS",
    "targetRegions": [
      {
        "name": "West US",
        "regionalReplicaCount": 1,
        "storageAccountType": "Standard_LRS"
      }
    ]
  },
  "replicationStatus": null,
  "resourceGroup": "ova-test",
  "storageProfile": {
    "dataDiskImages": null,
    "osDiskImage": {
      "hostCaching": "None",
      "sizeInGb": 30
    }
  },
  "tags": {},
  "type": "Microsoft.Compute/galleries/images/versions"
}
```

**Closed by adewaleo** 2019-04-30 20:32 UTC
Labels: Compute, bug
