### ISSUE TITLE
`az login` fails on Azure Stack Hub using ADFS and service principal: MSIS9605: The client is not allowed to access the requested resource

### ISSUE THREAD

**Issue by dfencegit** [Azure/azure-cli#20177] opened 2021-11-03 16:19 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
MSIS9605: The client is not allowed to access the requested resource.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u {} -p {} --tenant {}`

## Expected Behavior
Successful login

## Environment Summary
```
Linux-3.10.0-1160.42.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core, CentOS Linux 7 (Core)
Python 3.6.8
Installer: RPM

azure-cli 2.30.0

```
## Additional Context
Target system is disconnected Azure Stack Hub 1.2102.30.105 using ADFS.
Not present in 2.29.0

**Comment by yonzhan** [comment] 2021-11-03 22:43
@jiasli for awareness

**Comment by jiasli** [comment] 2021-11-04 09:27
It seems this has been seen before:

- https://github.com/Azure/azure-sdk-for-python/issues/19261
- https://github.com/Azure/azure-sdk-for-python/issues/20802

I will do some investigation. +@rayluo

**Comment by rkh-hash** [comment] 2022-01-18 11:29
Dear,

any updates ? I'm facing this issue too 😕.

**Comment by bganapa** [comment] 2022-01-20 06:17
Apologies that login with service principal is broken in the latest version of CLI against AzureStack Hub ADFS.
We recommend using CLI version 2.29.2 or earlier.  Our doc page is updated with the Important Note saying that the version 2.29.2 or earlier should be used
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2?view=azs-2108&tabs=adfs-win

The issue is on the ADFS and a fix has been queued up. The fix will ship with the next Azure Stack Update release

**Comment by TheOnlyWei** [comment] 2023-04-29 02:07
The long-term fix is to upgrade ASH version to 2206. The hotfix for this issue on ASH version 2108 is:
https://learn.microsoft.com/en-us/azure-stack/operator/hotfix-1-2108-2-130?view=azs-2108

**Comment by domggarrity** [comment] 2023-11-29 18:34
Hi @bganapa, did this fix ship? If so, are we able to close this issue?

**Comment by domggarrity** [comment] 2023-12-06 20:33
Hi @dfencegit, just checking in. Were you able to implement the fix suggested by @TheOnlyWei? If so, how did it go?

**Comment by domggarrity** [comment] 2023-12-07 07:51
@dfencegit, great to hear! That would be helpful.

**Closed** 2023-12-07 07:54 UTC
Labels: Account, customer-reported
