### ISSUE TITLE
CLI install via homebrew not working on high sierra

### ISSUE THREAD

**Issue by theanandramakrishna** [Azure/azure-cli#5624] opened 2018-02-21 18:20 UTC
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```brew install azure-cli
```

This installs from https://homebrew.bintray.com/bottles/azure-cli-2.0.27.high_sierra.bottle.tar.gz

Subsequently running

``` az --help

results in a failure:

field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.27/libexec/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.27/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 200, in execute
    args = _pre_command_table_create(self.cli_ctx, args)
  File "/usr/local/Cellar/azure-cli/2.0.27/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 101, in _pre_command_table_create
    cli_ctx.refresh_request_id()
  File "/usr/local/Cellar/azure-cli/2.0.27/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 67, in refresh_request_id
    self.data['headers']['x-ms-client-request-id'] = str(uuid.uuid1())
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)

**Comment by tjprescott** [comment] 2018-02-21 18:59
Dupe of #5184.

**Closed by tjprescott** 2018-02-21 18:59 UTC
