### ISSUE TITLE
Az rest with --uri-parameters 

### ISSUE THREAD

**Issue by EwertonJordao** [Azure/azure-cli#12977] opened 2020-04-12 05:46 UTC
## Describe the bug

Hello, I trying to use az cli to automate tasks, in special with this command *az rest* when I pass --uri-parameters on az rest command I receive an error when I construct URI with parameters it works. This error occurs on cloud shell, windows terminal, PowerShell all I trying to use. 

**Command Name**
`az rest`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure\cli\core\util.py, ln 281, in shell_safe_json_parse
CLI2\lib\json\__init__.py, ln 354, in loads
    return _default_decoder.decode(s)
CLI2\lib\json\decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
CLI2\lib\json\decoder.py, ln 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

...

cli\command_modules\resource\custom.py, ln 2283, in rest_call
azure\cli\core\util.py, ln 599, in send_raw_request
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
Error occour 
- az rest --uri "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/webhooks/generateUri?api-version=2015-10-31"  --uri-parameters '{"subscriptionId":"","resourceGroupName":"","automationAccountName":""}'  -m POST

Ok when don't use --uri-parameters
az rest --uri "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/{automationAccountName}/azautoxp/webhooks/generateUri?api-version=2015-10-31" -m POST

## Expected Behavior
https://docs.microsoft.com/en-us/rest/api/automation/webhook/generateuri 

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

```

**Comment by yonzhan** [comment] 2020-04-12 08:35
add to S169

**Comment by yonzhan** [comment] 2020-05-03 00:26
add to S171

**Comment by zhoxing-ms** [comment] 2020-06-02 06:50
@EwertonJordao I can't reproduce this problem in both version 2.3.1 and the latest version (2.7.0) of CLI. Will this problem still occur in your side? (you can upgrade the CLI version and try again)
If so, please add `--debug` to the original command and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by EwertonJordao** [comment] 2020-06-02 18:55
Ok, I'll send the email.
Thanks.

**Comment by zhoxing-ms** [comment] 2020-06-03 03:46
@EwertonJordao Hi, could you show me the debug level logs? If only the log information of info level is not specific enough.
Since I have used the CLI of 2.3.1 in multiple environments but I can't reproduce this problem, I would like to ask you two more questions:
1. What is your specific execution environment? PowerShell or CMD or something else?
2. Could you change to another automationaccounts and execute this command to see if there are the same problems?

**Comment by EwertonJordao** [comment] 2020-06-03 05:31
I found with --debug.

The parameter --uri-parameter use to query parameters and not to change values of a uri https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}?api-version=2019-10-01 i the document about az rest --uri-parameters
Space-separated queries in KEY=VALUE format or JSON string. Use @{file} to load from a file. 

it's not clear what is uri-parameter use to query parameters. I think is more clear if uri-parameter rename query-parameter it's more clear what it's. 

I would like to suggest a new parameter for change dynamically parameters with this patter {parameter_name} of a uri.

Thank you for your attention.

**Comment by zhoxing-ms** [comment] 2020-06-03 06:12
@EwertonJordao Thank you very much for your nice suggestion. My thoughts on this are as follows:
1. The specification of the existing `--uri-parameters` is not clear, we will modify the document to explain its usage in more detail and add some new examples for it. But we don't rename this parameter because it will cause a breaking change to the customers.
2. As for adding new parameters to support placeholder replacement in uri, I personally think this may introduce the complex problem of confusing placeholders with input parameters that contain placeholder text, and it will make the entire command longer. If there is more customers feedback about this requirement, we will consider supporting it.

What do you think of that?

**Comment by EwertonJordao** [comment] 2020-06-03 13:32
@zhoxing-ms thanks for all. 

About documentation, I can help too make some samples with uri-parameter.

I think about it's work the same way of the other command --body or --uri when you define a @{json.json} read a file and change some values,, when we interact with azure resource manager API it's a good help because some times we make a logic for string builder of uri, with this feature won't require to make this.

**Comment by zhoxing-ms** [comment] 2020-06-04 01:51
@EwertonJordao OK, thank you very much for the helpful suggestions. Welcome to provide us with the examples of `uri-parameter`, which we will probably refer to it ~

**Comment by zhoxing-ms** [comment] 2020-06-08 01:35
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Comment by yonzhan** [comment] 2020-06-08 01:52
@EwertonJordao any feedback for the example?

**Comment by EwertonJordao** [comment] 2020-06-12 21:24
That's cool.
I'll make a post in a few days on my blog about how to consume other API that's not Azure Resource or test some Azure Functions http trigger. 

Thanks for attention

**Comment by zhoxing-ms** [comment] 2020-06-19 04:25
The PR for adding examples has been merged, so I close this issue first. If you have any supplementary examples, please feel free to let us know~

**Closed by zhoxing-ms** 2020-06-19 04:25 UTC
Labels: ARM, OKR3.2 Candidate, feature-request, rest-cli
