### ISSUE TITLE
az role definition update failing with KeyError roleName when using an input file

### ISSUE THREAD

**Issue by jlautman** [Azure/azure-cli#14411] opened 2020-07-17 22:37 UTC
## Describe the bug

I am attempting to update an existing role definition with an additional action.

**Command Name**
`az role definition update`

**Errors:**
```
'roleName'
Traceback (most recent call last):
Temp\pip-install-yh2ypeu1\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 711, in _run_job
Local\Temp\pip-install-yh2ypeu1\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
site-packages\azure\cli\core\__init__.py, ln 776, in default_command_handler
azure\cli\command_modules\role\custom.py, ln 56, in update_role_definition
azure\cli\command_modules\role\custom.py, ln 85, in _create_update_role_definition
KeyError: 'roleName'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition update --role-definition <file name here> --verbose`

## Expected Behavior
An existing role definition should be updated with the new configuration.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.9.1

```

**Comment by yonzhan** [comment] 2020-07-18 01:00
add to S174

**Comment by jiasli** [comment] 2020-07-20 06:18
Duplicate of #12027

Please note that for `create`, the provided JSON should have `Name`, while for `update`, the provided JSON should have `roleName`.

```
> az role definition create -h
...
Examples
    Create a role with read-only access to storage and network resources, and the ability to start
    or restart VMs.
        az role definition create --role-definition '{ \
>>          "Name": "Contoso On-call", \
```

```
> az role definition update -h
...
Examples
    Update a role using the output of "az role definition list"
        az role definition update --role-definition '{ \
>>          "roleName": "Contoso On-call", \
```

**Closed** 2020-07-26 12:40 UTC
Labels: RBAC
