### ISSUE TITLE
bad error message for comments in JSON template

### ISSUE THREAD

**Issue by scottleyg** [Azure/azure-cli#8925] opened 2019-03-29 19:51 UTC
when you have comments in your ARM Template (valid // or /* foo */ style comments), you get the following error:

> Expecting property name enclosed in double quotes: line 7 column 5 (char 178)

or similar... removing the // and /* foo */ comments from my template fixes the issue.  

parsing should be tolerant of comments in JSON.

**Comment by scottleyg** [comment] 2019-03-29 19:54
simple example:
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
  },
  "variables": {
   // foo
    "aadTenantId": "[subscription().tenantId]",
// bar
    "webAppName": "[resourceGroup().name]"
},
"resource":[], 
"outputs":{}
}

c:\notAPath> az group deployment create --resource-group %RESOURCE_GROUP_NAME% --template-file .\azuredeploy.json
Expecting property name enclosed in double quotes: line 7 column 4 (char 177)

**Comment by tjprescott** [comment] 2019-03-29 20:56
This is essentially a duplicate of https://github.com/Azure/azure-cli/issues/4802 which has already been declined by the team as comments are not part of the JSON design. The recommendation is to pipe your JSON file through a tool like JSMin to strip the comments before sending to CLI.

**Closed by tjprescott** 2019-03-29 20:56 UTC
Labels: Feature

**Comment by scottleyg** [comment] 2019-03-30 00:19
Any reason why you wouldn't bake that into the tool? If you specify a min format as being required (so as to strip comments) why don't you do this before returning a meaningless error message?  

If you know this is an issue, return a more meaningful error like, "hey, we have had success minifying JSON before feeding it through"
