### ISSUE TITLE
`az component update` crashes

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1113] opened 2016-10-21 21:56 UTC
I was able to `sudo` and get it working, but we should clean this crash up and replace it with a message explaining **why** we need admin rights.  I believe I installed without sudo too (but not sure) 

```
$ az component update
Exception:
Traceback (most recent call last):
  File "/usr/local/az/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/az/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/az/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/az/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/az/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/az/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/az/bin/activate-global-python-argcomplete'
```

**Comment by derekbekoe** [comment] 2016-10-21 21:57
Duplicate of https://github.com/Azure/azure-cli/issues/1050?

**Comment by derekbekoe** [comment] 2016-10-21 22:25
Closing at it's a duplicate.

**Closed by derekbekoe** 2016-10-21 22:25 UTC
Labels: bug
