### ISSUE TITLE
Command fail in Git Bash, insertion of local path in URL

### ISSUE THREAD

**Issue by sinux-l5d** [Azure/azure-cli#29243] opened 2024-06-25 09:46 UTC
### Describe the bug

I'm on Windows. I've run a command in 3 different environments :
- Powershell
- Git Bash
- Wsl (Ubuntu) Bash

On Git Bash, a path is inserted in a request url. With `--debug` I managed to find the relevant piece of log :

Powershell :
```log
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/$MY_SUB/resourceGroups/$MY_RG/providers/Microsoft.ContainerRegistry/registries/$MY_REGISTRY/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName%20eq%20%27AcrPull%27&api-version=2022-05-01-preview'
```

Git Bash :
```log
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/C:/Program Files/Git/subscriptions/$MY_SUB/resourceGroups/$MY_RG/providers/Microsoft.ContainerRegistry/registries/$MY_REGISTRY/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName%20eq%20%27AcrPull%27&api-version=2022-05-01-preview'
```

### Related command

az role assignment create --assignee $MY_SP_APP_ID --role AcrPull --scope /subscriptions/$MY_SUB/resourceGroups/$MY_RG/providers/Microsoft.ContainerRegistry/registries/$MY_REGISTRY --debug

### Errors

Error on Git bash : 

```
(MissingSubscription) The request did not have a subscription or a valid tenant level resource provider.
Code: MissingSubscription
Message: The request did not have a subscription or a valid tenant level resource provider.
```

Works as expected on Powershell/WSL.

### Issue script & Debug output

DEBUG: msal.telemetry: Generate or reuse correlation_id: d6caeafe-0a6a-4861-afe1-9e20516f7950
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/C:/Program Files/Git/subscriptions/$MY_SUB/resourceGroups/$MY_RG/providers/Microsoft.ContainerRegistry/registries/$MY_REGISTRY/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName%20eq%20%27AcrPull%27&api-version=2022-05-01-preview'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '1d170750-32d0-11ef-a4d8-cc474000a6a5'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'role assignment create'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--assignee --role --scope --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.61.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /C:/Program%20Files/Git/subscriptions/$MY_SUB/resourceGroups/$MY_RG/providers/Microsoft.ContainerRegistry/registries/$MY_REGISTRY/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName%20eq%20%27AcrPull%27&api-version=2022-05-01-preview HTTP/1.1" 404 135
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 404
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '135'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd4803525-7bbd-4981-af83-7f291a45dc58'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd4803525-7bbd-4981-af83-7f291a45dc58'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'FRANCECENTRAL:20240625T085129Z:d4803525-7bbd-4981-af83-7f291a45dc58'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 66663CA88E5D4F2CB9A3F3C6E4995918 Ref B: AMS231022012007 Ref C: 2024-06-25T08:51:29Z'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 25 Jun 2024 08:51:29 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}

### Expected behavior

It should not insert "C:/Program Files/Git" in the Request URL and run the command as expected

### Environment Summary

azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
interactive                        0.5.3
ssh                                2.0.3

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\simleona\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 21:52:07) [MSC v.1937 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment] 2024-06-25 09:46
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-06-26 08:33
Duplicate of #16317

**Closed by jiasli** 2024-06-26 08:33 UTC
Labels: question, RBAC, customer-reported, Auto-Assign, Azure CLI Team, Auto-Resolve, Similar-Issue

**Comment by sinux-l5d** [comment] 2024-06-26 15:34
Sorry for the incontinence, the linked issue indeed fix the problem <3
