### ISSUE TITLE
az login causes an infinite refresh loop in the browser

### ISSUE THREAD

**Issue by alexpolozov** [Azure/azure-cli#4338] opened 2017-08-29 19:55 UTC
### Description
Not sure if this is the right repo for this question since it involves the Web login experience.

Installed the azure CLI tools, trying to login interactively. After I take the code produced by `az login`, paste it in the `aka.ms/devicelogin` form, and press "Continue", I'm getting a "Choose your account" page. After I click my account (it's already connected to Windows), I'm redirected back to the first step: the form where I should paste my CLI code.

The network tools show a 204 No Content response. Tried in Chrome 60, Edge 41.16273.1000.0, and IE 11. This is pretty odd since I'm already logged into Azure Portal (in all the browsers).

---

### Environment summary

**Install Method:** MSI

**CLI Version:** 2.0.14

**OS Version:** Windows 10 Version 1703 Build 16273.1000 (RS3 Preview)

**Shell Type:** PowerShell

**Comment by tjprescott** [comment] 2017-08-29 20:34
I have definitely experienced this myself--however, I don't think the CLI is the cause. I'll let @yugangw-msft comment as he knows more about the underlying issue.

**Comment by jeffwilcox** [comment] 2017-08-30 17:48
+1 we've been hitting this for a while now, seems to be related to the newer AAD authentication flows... maybe the device auth experience has regressed?

**Comment by yugangw-msft** [comment] 2017-09-08 00:21
I have logged an ICM ticket to the ESTS team. Will post updates

**Comment by PakDLiu** [comment] 2017-12-11 23:52
+1 I am also getting something similar.

After I login using the browser, it will just infinitely redirect. I've tried different browsers as well as different machines, all the same.

**Comment by yugangw-msft** [comment] 2018-01-22 20:43
Closing as it appears the same issue like #4987. Please refer that issue to opt-out the insider ring.

**Closed by yugangw-msft** 2018-01-22 20:43 UTC
Labels: Auth, ServiceAttn
