### ISSUE TITLE
Az ml environment create not recognizing build-context

### ISSUE THREAD

**Issue by bpetit2019** [Azure/azure-cli#23078] opened 2022-06-30 07:47 UTC
**Related command**
I executed :
az ml environment create --resource-group <r-name> --workspace-name <w-name> --name <Name> --debug -b .

**Describe the bug**
I received this error:
cli.azure.cli.core.azclierror: Met error <class 'marshmallow.exceptions.ValidationError'>:Validation for EnvironmentSchema failed:

 {
  "build": {
    "local_path": [
      "Unknown field."
    ]
  }
}

For a more detailed breakdown of the Environment schema, please see: https://aka.ms/ml-cli-v2-environment-yaml-reference.
The easiest way to author a specification file is using IntelliSense and auto-completion Azure ML VS code extension provides: https://code.visualstudio.com/docs/datascience/azure-machine-learning
To set up: https://docs.microsoft.com/azure/machine-learning/how-to-setup-vs-code
Please check log in debug mode for more details.
az_command_data_logger: Met error <class 'marshmallow.exceptions.ValidationError'>:Validation for EnvironmentSchema failed:

 {
  "build": {
    "local_path": [
      "Unknown field."
    ]
  }
}

For a more detailed breakdown of the Environment schema, please see: https://aka.ms/ml-cli-v2-environment-yaml-reference.
The easiest way to author a specification file is using IntelliSense and auto-completion Azure ML VS code extension provides: https://code.visualstudio.com/docs/datascience/azure-machine-learning
To set up: https://docs.microsoft.com/azure/machine-learning/how-to-setup-vs-code
Please check log in debug mode for more details.

**To Reproduce**
I have a Dockerfile in the current directory I'm executing the command, that I succeed to build locally.
I also tested this command with the "-d" option, which default matches mine. And also with relative and absolute Path, in string or not in --build-context
I use : 
az ml - 2.5.0
azure-cli - 2.37.0
**Expected behavior**
It should create an environment in Azure.

**Comment by yonzhan** [comment] 2022-06-30 08:59
route to CXP team

**Comment by bpetit2019** [comment] 2022-06-30 09:56
And if you can answer this too, it is related to this issue.
When I pushed my docker image to azure and create an environment with this one, all the files in the container weren't in the environment.
I had:
WORKDIR /usr/src/app
RUN git clone <repo>
WORKDIR /usr/src/app/repo
None of the files of the repo were in the environment, but all the required packages were. Why?

**Comment by hugoaponte** [comment] 2022-07-15 00:45
Thanks for reporting this. We identified a bug, and we are working on a fix for the next release.

Hugo

**Comment by gergelyhunyady** [comment] 2022-11-21 00:13
Hi,
any update on this issue?

I also have issues when trying to register a new aml env with the python sdk using the DockerBuildContext.from_local_directory method.
The method flattens the build context, so only toplevel files are uploaded.. the directory hierarchy is lost. Also files with identical name, but in separate dir, end up overwriting each other in the flattened destination context..

Not sure though how to file a bug report for the python sdk, I couldn't find the right place for it.

Thanks!

**Comment by CoreyRByrne** [comment] 2022-11-23 21:57
Hey @gergelyhunyady,

We've fixed the bug for build context on CLI since @hugoaponte's comment. I believe what you're observing with flattening of the folder structure isn't occurring on the CLI, but I am noticing a visual bug on the UI for these environments, where it will remove the separating folder slashes, so that may explain what you're seeing, but I'm not convinced from your description.

I would create a new issue on the SDK if this is repro'ing on the latest SDK.

**Comment by gergelyhunyady** [comment] 2022-11-23 23:08
Hi @CoreyRByrne ,

**CLI**
I can confirm that the issue is not occurring with the CLI, however as you mentioned there is a visual bug on the studio, for me it does not show the files of the context at all. I checked in the storage account and the blobs are there in correct form indeed. Another visual issue is that the build is shown as failed with the newly registered env version (I added a new version of an existing env, not a new env) even though there was no build (there are no build logs either) for this version at all.

**python SDK**
I can confirm that the issue is reproducible with latest python SDK, it is not just a visual thing on the UI, the blobs in the related blob container do not preserve the folder structure, only the file name. I debugged into the sdk and I believe that the issue originates from the `azureml.core.environment.Environment._get_files_to_upload` method.
I think to fix it, this line of the method:
```python
results[_file] = fpath
```
should be changed to:
```python
results[os.path.relpath(fpath, path)] = fpath
```
but maybe there is more than this to be fixed, so this is just my initial pointer.

Thanks!

**Comment by CoreyRByrne** [comment] 2022-11-29 18:06
Hey @gergelyhunyady thanks for the report! 

We'll file a bug on our end for the SDK issue and make sure it gets filed to the right team. 

I can't repro your issue for the build context, can you share how you created the environment? The issue I observed was much more minor with the build context not displaying folders correctly.

**Closed** 2023-01-07 17:01 UTC
Labels: bug, Service Attention, Machine Learning, customer-reported, needs-author-feedback, no-recent-activity, Auto-Assign
