### ISSUE TITLE
2.46.0 install failing on Debian looking for libffi6 but only libffi7 in Debian Stable 11+

### ISSUE THREAD

**Issue by lulujrush** [Azure/azure-cli#25965] opened 2023-03-28 15:05 UTC
**Related command**
sudo apt-get install azure-cli

**Describe the bug**

The installer package for 2.46.0 is looking for libffi6 but starting with Debian 11 (current stable out August 14th, 2021) libffi7 is included. 

The following packages have unmet dependencies:
 azure-cli : Depends: libffi6 (>= 3.0.10~rc8) but it is not installable
E: Unable to correct problems, you have held broken packages.

**To Reproduce**
While running Debian 11+  try to install latest AZ CLI

**Expected behavior**
latest version of az cli to be installed 

**Environment summary**
debian apt repo via MSFT instructions

**Additional context**
https://packages.debian.org/source/stable/libffi to see what version is included with Debian Stable. If Debian stable has a newer version we know that Ubuntu and other are going to have even newer ones. 

This appeared to have happened on 2.46.0 as I can remove and install 2.45.0 all day long.

**Comment by yonzhan** [comment] 2023-03-28 22:06
@bebound for awareness

**Comment by bebound** [comment] 2023-03-29 02:02
Duplicate of https://github.com/Azure/azure-cli/issues/25750
Debian 12 is not released yet.

**Closed by bebound** 2023-03-29 02:02 UTC
Labels: question, customer-reported, Installation, Auto-Assign, Azure CLI Team
