### ISSUE TITLE
az interactive failed after powershell-core version upgrade 

### ISSUE THREAD

**Issue by jamesyoung007** [Azure/azure-cli#25310] opened 2023-01-31 21:14 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'argcomplete.compat'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
  File "C:\Users\jamesyang3\.azure\cliextensions\interactive\azext_interactive\__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "C:\Users\jamesyang3\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 38, in <module>
    from .az_completer import AzCompleter
  File "C:\Users\jamesyang3\.azure\cliextensions\interactive\azext_interactive\azclishell\az_completer.py", line 19, in <module>
    from .argfinder import ArgsFinder
  File "C:\Users\jamesyang3\.azure\cliextensions\interactive\azext_interactive\azclishell\argfinder.py", line 9, in <module>
    from argcomplete.compat import USING_PYTHON2, ensure_bytes
ModuleNotFoundError: No module named 'argcomplete.compat'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.44.1

Extensions:
amg 0.3.0
azure-devops 0.25.0
interactive 0.4.5
portal 0.1.3
powerbidedicated 0.2.1

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2023-02-01 00:54
Duplicate of https://github.com/Azure/azure-cli/issues/25128

**Closed by yonzhan** 2023-02-01 00:54 UTC
Labels: Interactive, customer-reported, Auto-Assign
