### ISSUE TITLE
az aks create - aks workshop 02 deploy

### ISSUE THREAD

**Issue by Benauld** [Azure/azure-cli#13272] opened 2020-04-30 10:00 UTC
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --vm-set-type {} --load-balancer-sku {} --location {} --kubernetes-version {} --network-plugin {} --vnet-subnet-id {} --service-cidr {} --dns-service-ip {} --docker-bridge-address {} --generate-ssh-keys`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment] 2020-04-30 10:40
aks

**Comment by Benauld** [comment] 2020-04-30 11:24
Tried it again and got a different error

ben@Azure:~$ az aks create \
> --resource-group $RESOURCE_GROUP \
> --name $AKS_CLUSTER_NAME \
> --vm-set-type VirtualMachineScaleSets \
> --load-balancer-sku standard \
> --location $REGION_NAME \
> --kubernetes-version $VERSION \
> --network-plugin azure \
> --vnet-subnet-id $SUBNET_ID \
> --service-cidr 10.2.0.0/24 \
> --dns-service-ip 10.2.0.10 \
> --docker-bridge-address 172.17.0.1/16 \
> --generate-ssh-keys
AAD role propagation done[############################################]  100.0000%Operation failed with status: 'Bad Request'. Details: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'uksouth'.  For more details, please visit https://aka.ms/cpu-quota

**Comment by yungezz** [comment] 2020-04-30 15:21
hi @Benauld for the first issue, are you met it inside Cloudshell? If yes, it's a known Cloudshell issue, similiar with https://github.com/Azure/azure-cli/issues/13226.  For the second issue, need AKS team have a look.

**Comment by jluk** [comment] 2020-04-30 16:02
@Benauld it looks like a quota issue, can you try a different region your sub may have quota for?

**Comment by maertendMSFT** [comment] 2020-09-30 23:09
From a Cloud Shell standpoint, this is a dupe of https://github.com/Azure/azure-cli/issues/11749
If the quota issue is resolved, can we close?

**Closed** 2020-10-01 09:04 UTC
Labels: AKS, Cloud Shell, Service Attention, customer-reported
