### ISSUE TITLE
list azure users gives me an error

### ISSUE THREAD

**Issue by DaCheeseMan** [Azure/azure-cli#13681] opened 2020-05-26 07:55 UTC
## Describe the bug
when typing the command the error message is shown after approx. 10-20 seconds

**Command Name**
`az ad user list`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 686, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad user list`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment] 2020-05-26 11:14
@arrownj please take a look

**Comment by yungezz** [comment] 2020-08-03 13:41
hi @DaCheeseMan did you meet the issue in Cloudshell? If yes, it's a known issue in #11749 . Pls run `az login` to workaround it. add service attention label.

**Comment by DaCheeseMan** [comment] 2020-08-04 19:44
I just tried again using Azure Cloud Shell via Terminal (the app), and I got the same error. But after running `az login` it worked so this is probably the same issue as #11749.

**Comment by maertendMSFT** [comment] 2020-09-30 23:11
Can we close this as a dupe of https://github.com/Azure/azure-cli/issues/11749 ?

**Comment by DaCheeseMan** [comment] 2020-10-01 17:09
Yes.

Den tors 1 okt. 2020 01:11Danny Maertens <notifications@github.com> skrev:

**Comment by maertendMSFT** [comment] 2020-11-20 22:52
@DaCheeseMan , unfortunately I dont have permissions in this repro to close this issue, do you mind closing it?

**Comment by DaCheeseMan** [comment] 2020-11-21 08:57
Duplicate

**Closed** 2020-11-21 08:57 UTC
Labels: Cloud Shell, Service Attention, customer-reported
