### ISSUE TITLE
az

### ISSUE THREAD

**Issue by Tank1719248** [Azure/azure-cli#10291] opened 2019-08-21 10:52 UTC
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


<urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
URLError: <urlopen error [Errno 104] Connection reset by peer>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.71

```

**Comment by MyronFanQiu** [comment] 2019-08-21 14:12
@Tank1719248 Hello. There is another open issue https://github.com/Azure/azure-cli/issues/10288 similar with this one. Could we close this issue?

**Comment by seanmck** [comment] 2019-08-31 00:40
Duplicate of #10288

**Closed by seanmck** 2019-08-31 00:40 UTC
Labels: AKS
