### ISSUE TITLE
I cannot login through the cli

### ISSUE THREAD

**Issue by bijinbjames** [Azure/azure-cli#22369] opened 2022-05-12 07:36 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1652335530.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1652340576,
  "nbf": 1652340576,
  "exp": 1652344476,
  "aio": "AYQAe/8TAAAASUSMLMOym8oJ+f9VvkKAPYclnaEe/1xG2bwpxW3TxDoCLTAYwQIqYWcaO+6Ss93BYbPdhgOvrFnx4EW0JQsFh7Ud2MhhqL7BYVtnNNKKhmxjQdyu8o5OG1ZyvwxNae0+ZYU+E6vHqFZK2qbUBl61FNN9hn4vBpQf1HOGIw8REQU=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "82bb72532903d80c5932f34e53b6ab23aa403afec72a71da3bc137b01260674e",
  "preferred_username": "bijinbjames@gmail.com",
  "prov_data": [
    {
      "at": true,
      "prov": "github.com",
      "altsecid": "53501933"
    }
  ],
  "rh": "0.AXEAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAD8.",
  "sub": "KLlDAdceUsr7ueuYSyJZTtzQV-wLkdc0VF0rKwfk7Uk",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "JVtYuBIY2EKjZ1E6-qG7AA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 141, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1565, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 281, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 137, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 116, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 598, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 77, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1652335530.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1652340576,
  "nbf": 1652340576,
  "exp": 1652344476,
  "aio": "AYQAe/8TAAAASUSMLMOym8oJ+f9VvkKAPYclnaEe/1xG2bwpxW3TxDoCLTAYwQIqYWcaO+6Ss93BYbPdhgOvrFnx4EW0JQsFh7Ud2MhhqL7BYVtnNNKKhmxjQdyu8o5OG1ZyvwxNae0+ZYU+E6vHqFZK2qbUBl61FNN9hn4vBpQf1HOGIw8REQU=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "82bb72532903d80c5932f34e53b6ab23aa403afec72a71da3bc137b01260674e",
  "preferred_username": "bijinbjames@gmail.com",
  "prov_data": [
    {
      "at": true,
      "prov": "github.com",
      "altsecid": "53501933"
    }
  ],
  "rh": "0.AXEAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAD8.",
  "sub": "KLlDAdceUsr7ueuYSyJZTtzQV-wLkdc0VF0rKwfk7Uk",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "JVtYuBIY2EKjZ1E6-qG7AA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0
```

**Comment by yonzhan** [comment] 2022-05-12 10:53
@Jiasli for awareness

**Comment by yonzhan** [comment] 2022-05-12 10:54
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2022-05-12 10:54 UTC
Labels: Account, customer-reported, Auto-Assign

**Comment by jiasli** [comment] 2022-05-12 11:05
The error message is pretty clear:

> The ID token is not yet valid. Make sure your computer's time and time zone are both correct.
