### ISSUE TITLE
az storage blob delete-batch ignores --query

### ISSUE THREAD

**Issue by luckerby** [Azure/azure-cli#15734] opened 2020-10-30 12:27 UTC
Assume you're after deleting all the blobs whose names match a specific pattern. If `az storage blob delete-batch` is used, there are 2 parameters of interest: `--pattern` and `--query`.

Having used recently `az storage blob list` with the `--query` parameter, I was expecting a similar functionality, however I was wrong. As such, using the command below would not result in the deletion of only the blobs whose names match the string particle supplied, but of all the blobs within the specified container:
```
az storage blob delete-batch --container-name <container> --account-name <account> --account-key <key> --query "[?contains(name, `particle`)].{name:name}"
```

I'm not sure if this is by design or just a bug.

**Environment summary**
az version: `2.12.0`

**Comment by yonzhan** [comment] 2020-10-30 15:00
storage

**Comment by Juliehzl** [comment] 2020-11-12 07:25
Hi @luckerby, the output for `az storage blob download-batch` is different from `az storage blob list`. `az storage blob list` is targeted to get blob properties from Azure. `az storage blob download-batch` is to download blobs from Azure, so we only show file names to customer as below:
 
![image](https://user-images.githubusercontent.com/49508232/98907575-fae99200-24f9-11eb-8556-ed673770f633.png)

I will close the issue because it is by design, and if you have further question, feel free to create a new one.

**Closed by Juliehzl** 2020-11-12 07:25 UTC
Labels: OKR3.2 Candidate, Storage, feature-request
