### ISSUE TITLE
account name and key combination doesn't work.

### ISSUE THREAD

**Issue by jackchenquest** [Azure/azure-cli#7396] opened 2018-09-22 16:15 UTC
I am using azure-cli (2.0.45), looks like the cli allow three set of options :

az  cosmosdb database list
No credentials specified to access Cosmos DB service. Please provide any of the following:
    (1) resource group name and account name
    (2) account name and key
    (3) url-connection and key

I found only 1 and 3 work, 2 will give me a error:
az  cosmosdb database list  --name testaccount --key 'long_key=='
unsupported operand type(s) for +: 'NoneType' and 'str'

both "az cosmosdb database show" and "az cosmosdb database list" have same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by shurd** [comment] 2019-06-05 23:38
Hi @jackchenquest thank you for identifying this issue. I have reverted the change that introduced the problem as a part of #7929. It should be working as of CLI version 2.0.53

**Comment by shurd** [comment] 2019-06-06 16:57
@tjprescott Can we close this issue? It was a duplicate of #6770

**Closed** 2019-06-06 16:59 UTC
Labels: Bug, Cosmos, Service Attention
