### ISSUE TITLE
Trying to download a snapshot version of a file share fails with ResourceNotFound

### ISSUE THREAD

**Issue by jimmythedog** [Azure/azure-cli#9959] opened 2019-07-17 09:00 UTC
## Describe the bug

**Command Name**
`az storage file download-batch ... --source [SHARE_NAME] --destination [DEST_DIR] --snapshot [SNAPSHOT]`

**Errors:**
```
The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:321ffe99-801a-0056-2d7d-3c7264000000
Time:2019-07-17T08:56:12.4562505Z</Message></Error>
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
azure.common.AzureMissingResourceHttpError: The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:321ffe99-801a-0056-2d7d-3c7264000000
Time:2019-07-17T08:56:12.4562505Z</Message></Error>
```

## To Reproduce:
- Create a snapshot of the share
- Create a new file in the share (so, the file does **not** exist in the snapshot)
- `az storage file download-batch --account-name {} --account-key {} --source {} --destination {} --no-progress --snapshot {}`

## Expected Behavior

The destination directory should contain a snapshot of the share at the time the snapshot was created

## Environment Summary
```
Linux-4.19.0-5-amd64-x86_64-with-debian-10.0
Python 3.6.5
Shell: bash

azure-cli 2.0.69

```

**Comment by Juliehzl** [comment] 2019-09-24 06:04
Hi @jimmythedog, sorry for the late response. CLI team is in transition process in the past few months. I can reproduce your scenario in my computer. You get "ResourceNotFound" error because your file share snapshot don't have any file inside. If your snapshot share contains valid files, no error occurs. Out of curiosity, why do you want to download a null share snapshot?

**Comment by Juliehzl** [comment] 2019-09-24 06:11
@zhusijia26 @zezha-msft Can you give a more detailed explanation for null snapshot scenario? I wonder that when users create a snapshot for file share without files,  in portal we can see the snapshot information, but why python storage SDK cannot find it.

**Comment by jimmythedog** [comment] 2019-09-24 06:33
Hi all,
Perhaps I wasn't too clear on what I think the problem is, so please let try to elaborate.

Consider a file share with a single file in it: foo.txt
Now take a snapshot of that file share - that snapshot will contain just the single file.

Now add another file to the file share: bar.txt

If I now try to download the snapshot version of that file share, I get the original error I posted.
What I think is happening is that:
- The list of files in the file share is obtained - this will be two files (foo.txt & bar.txt)
- Then, it tries to download both files from the snapshot, *but* bar.txt does not exist in that snapshot, so it fails

Please get in touch if you need any more info

**Comment by zezha-msft** [comment] 2019-09-24 19:24
@Juliehzl in your repro, is the share snapshot completely empty?

**Comment by zezha-msft** [comment] 2019-09-24 19:26
To clarify, the scenario is:
- create snapshot on an empty share
- invoke download batch from the CLI

When does the "resource not found" error happen in the CLI's download batch code? I.e. on which API call to the SDK?

**Comment by mkit** [comment] 2020-06-03 18:16
Is there a progress on this issue?

**Comment by xiafu-msft** [comment] 2020-12-10 07:48
Hi @Juliehzl 

This should be a problem in CLI (@zezha-msft mentioned this).
does CLI include a `sharesnapshot` query parameter doing [list files](https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files) for batch download file?

**Comment by Juliehzl** [comment] 2020-12-16 05:19
the PR is merged and  you could try now with edge build https://github.com/Azure/azure-cli#edge-builds.
official release will be available on 12/29

**Closed by Juliehzl** 2020-12-16 05:19 UTC
Labels: Storage, bug, customer-reported, needs-team-triage
