### ISSUE TITLE
creating a vm, then deleting, then creating with same name fails.

### ISSUE THREAD

**Issue by smoser** [Azure/azure-cli#3918] opened 2017-06-29 14:48 UTC
### Description
I created a resource group, created a VM inside that group, but forgot to add `--ssh-key-value` so i deleted the vm.  I tried to create another one with the same name and that failed.  I believe it was because some automagically created resource already existed.

Heres the basic recreate:

    $ az group create --location=eastus2 --name=mygroup
    $ az vm create --resource-group=mygroup --name=myvm --image=UbuntuLTS
    
    # realize i messed up, so delete it.
    $ az vm delete --resource-group=mygroup --name=myvm

    # now try the same cmd above but with --ssh-key-value
    $ az vm create --resource-group=mygroup --name=smx1 -image UbuntuLTS \
        --ssh-key-value="$key"
    Deployment failed. {
      "status": "Failed",
      "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
          {
            "code": "ConflictingUserInput",
            "message": "Disk osdisk_b7660b2ba9 already exists in resource group MYGROUP. Only CreateOption.Attach is supported."
          }
        ]
      }
    }

---

### Environment summary

**Install Method:** How did you install the CLI?  
Answer here:

    curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

    # az --version
    azure-cli (2.0.9)
    
    acr (2.0.7)
    ...

    acs (2.0.9)
    appservice (0.1.9)
    batch (3.0.2)
    billing (0.1.2)
    cdn (0.0.5)
    cloud (2.0.5)
    cognitiveservices (0.1.5)
    command-modules-nspkg (2.0.0)
    component (2.0.6)
    configure (2.0.9)
    consumption (0.1.2)
    core (2.0.10)
    cosmosdb (0.1.9)
    dla (0.0.9)
    dls (0.0.9)
    feedback (2.0.5)
    find (0.2.5)
    interactive (0.3.5)
    iot (0.1.8)
    keyvault (2.0.7)
    lab (0.0.7)
    monitor (0.0.7)
    network (2.0.9)
    nspkg (3.0.0)
    profile (2.0.7)
    rdbms (0.0.4)
    redis (0.2.6)
    resource (2.0.9)
    role (2.0.7)
    sf (1.0.4)
    sql (2.0.6)
    storage (2.0.9)
    vm (2.0.9)
    
    Python (Linux) 3.5.2 (default, Nov 17 2016, 17:05:23) 
    [GCC 5.4.0 20160609]
    
    Python location '/root/lib/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
Answer here: **Ubuntu 16.04**

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: **bash**

**Comment by tjprescott** [comment] 2017-06-29 15:31
Hi @smoser you are absolutely correct. The managed disk for your previous OS is not deleted when you delete the VM.  Some options:

1) Delete the resource group, which will delete all associated resources.
2) Run the VM create and specify --attach-os-disk (with that disk name) instead of --image, since your OS disk is already set up, this should speed things up.
3) Specify a different name with --os-disk-name. The automatically calculated one is deterministic (by design).

**Comment by smoser** [comment] 2017-06-29 16:25
On Thu, 29 Jun 2017, Travis Prescott wrote:

> Hi @smoser you are absolutely correct. The managed disk for your previous OS is not deleted when you delete the VM.  Some options:
>
> 1) Delete the resource group, which will delete all associated resources.

But clearly that is not really an option in all but the most basic of
cases.  Ie, it will only work for your first vm in a resource group.

> 2) Run the VM create and specify --attach-os-disk (with that disk name) instead of --image, since your OS disk is already set up, this should speed things up.
> 3) Specify a different name with --os-disk-name. The automatically calculated one is deterministic (by design).

I think really there needs to be *some* easy way to delete a vm and any
resources that were automatically created for it.  That is default
behavior on OpenStack, AWS, GCE...

I realize that is somewhat non-trivial, but some path to it seems
important.

**Comment by tjprescott** [comment] 2017-06-29 16:38
> I think really there needs to be *some* easy way to delete a vm and any
> resources that were automatically created for it.  That is default
> behavior on OpenStack, AWS, GCE...

@smoser I wholeheartedly agree.

**Comment by adewaleo** [comment] 2018-12-19 02:39
@smoser, I couldn't reproduce this issue.  I created a vm, deleted it and was able to successfully recreate it. It is very likely this issue has already been fixed in a previous PR, seeing this issue was opened for version 2.0.9 and the latest version of the CLI is 2.0.53

I will be closing this issue. Please let me know if you have any questions or if this is still an issue for you.

**Closed by adewaleo** 2018-12-19 02:39 UTC
Labels: Compute-cli

**Comment by sistoimenov** [comment] 2019-07-03 14:29
This issue is so easy to reproduce that I am surprised it is closed without a resolution...

To reproduce it create a resource group, create a machine in it, delete the machine but keep the resource group. Create a new machine in the same resource group and it fails...

**Comment by adewaleo** [comment] 2019-07-03 17:31
@sistoimenov, what version of the CLI are you on?

I just retried and couldn't reproduce this issue on the latest version of the cli (2.0.68 / dev branch)

```
(cli-venv) [10:21 AM] Work-Mac:azure-cli tosin$ az group create -n test-vm-issue -l westus
{
  "id": "/subscriptions/0000/resourceGroups/test-vm-issue",
  "location": "westus",
  "managedBy": null,
  "name": "test-vm-issue",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": null
}
(cli-venv) [10:22 AM] Work-Mac:azure-cli tosin$ az vm create -g test-vm-issue -n ubuntu-vm --image ubuntults
{
  "fqdns": "",
  "id": "/subscriptions/0000/resourceGroups/test-vm-issue/providers/Microsoft.Compute/virtualMachines/ubuntu-vm",
  "location": "westus",
  "macAddress": "00-0D-3A-36-73-4E",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.4",
  "publicIpAddress": "104.40.80.36",
  "resourceGroup": "test-vm-issue",
  "zones": ""
}
(cli-venv) [10:24 AM] Work-Mac:azure-cli tosin$ az vm delete -n ubuntu-vm -g test-vm-issue
Are you sure you want to perform this operation? (y/n): y
(cli-venv) [10:25 AM] Work-Mac:azure-cli tosin$ 
(cli-venv) [10:26 AM] Work-Mac:azure-cli tosin$ 
(cli-venv) [10:26 AM] Work-Mac:azure-cli tosin$ az vm create -g test-vm-issue -n ubuntu-vm --image ubuntults
{
  "fqdns": "",
  "id": "/subscriptions/0000/resourceGroups/test-vm-issue/providers/Microsoft.Compute/virtualMachines/ubuntu-vm",
  "location": "westus",
  "macAddress": "00-0D-3A-36-73-4E",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.4",
  "publicIpAddress": "104.40.54.31",
  "resourceGroup": "test-vm-issue",
  "zones": ""
}
(cli-venv) [10:28 AM] Work-Mac:azure-cli tosin$ az --version
azure-cli                         2.0.68

command-modules-nspkg               2.0.3
core                              2.0.68
nspkg                              3.0.4
telemetry                          1.0.3
testsdk                            0.2.4

Extensions:
alias                              0.5.2
aks-preview                        0.4.5
vm-repair                          0.1.0

Python location '/Users/tosin/Repos/my_venvs/cli-venv/bin/python'
Extensions directory '/Users/tosin/.azure/devcliextensions'

Python (Darwin) 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
(cli-venv) [10:28 AM] Work-Mac:azure-cli tosin$ 
```
