### ISSUE TITLE
appservice plan modified by az webapp up

### ISSUE THREAD

**Issue by dionisiovj** [Azure/azure-cli#11279] opened 2019-11-18 13:58 UTC
## Describe the bug
 `az webapp up` modifies the plan given via -p option. Tested for Linux apps plan.

## Expected Behavior
The appservice plan settings are respected by the command

## To Reproduce:
Create a plan and then a webapp (in my case a Python Flask app)

- `az appservice plan create -n my-plan -g my-group --sku B1 -l "West Europe" --is-linux`
- `az webapp up -n my-app -g my-group -p my-plan`

Now the plan is P1v2 instead of B1 as originally created.

## Environment Summary
```
Linux-4.15.0-65-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75 *

```

**Comment by panchagnula** [comment] 2019-11-27 23:42
Thanks for reporting this,  for a current work around please run the up command with --sku parameter  as az webapp up -n my-app -g my-group -p my-plan --sku B1

This is because the up command uses some defaults & SKU might be using the defaults, i will take a look but could you also try to upgrade to 2.077 [https://pypi.org/project/azure-cli/](url) if possible if you still see this?

**Comment by yonzhan** [comment] 2019-12-15 13:38
Can we close this issue?

**Comment by dionisiovj** [comment] 2019-12-15 19:41
I haven't been able to test. I will do so this week and comment on the results here.

**Comment by panchagnula** [comment] 2019-12-16 01:39
@ammanifold can you check if this repros for you locally. I am expecting this shouldn't be an issue since if the app exists we try to use the SKU from the ASP of the APP. https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3012

Please close this if this doesn't repro for you. thanks!

**Comment by ammanifold** [comment] 2019-12-17 17:52
Thanks @panchagnula 

I also cannot reproduce this issue, closing!

**Closed** 2019-12-18 23:39 UTC
Labels: Service Attention, Web Apps
