### ISSUE TITLE
az login error

### ISSUE THREAD

**Issue by sk9424** [Azure/azure-cli#24210] opened 2022-10-14 12:05 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0
```

**Comment by yonzhan** [comment] 2022-10-14 13:14
Please provide detailed error log

**Comment by sk9424** [comment] 2022-10-14 19:29
Hi Yong
Below is the detail logs


$ az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
The command failed with an unexpected error. Here is the traceback:
Unable to get authority configuration for https://login.microsoftonline.com/042afadc-7134-4617-9b93-ee67367522fe. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
Traceback (most recent call last):
  File "/home/shree/.local/lib/python3.8/site-packages/msal/authority.py", line 102, in __init__
    openid_config = tenant_discovery(
  File "/home/shree/.local/lib/python3.8/site-packages/msal/authority.py", line 171, in tenant_discovery
    raise ValueError(
ValueError: OIDC Discovery endpoint rejects our request. Error: {"error":"invalid_tenant","error_description":"AADSTS90002: Tenant '042afadc-7134-4617-9b93-ee67367522fe' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\r\nTrace ID: 531b8315-ed03-4fc0-9b13-d429e68f1400\r\nCorrelation ID: a7ca8821-f987-4eb7-b51e-08f0c266a07b\r\nTimestamp: 2022-10-14 14:14:34Z","error_codes":[90002],"timestamp":"2022-10-14 14:14:34Z","trace_id":"531b8315-ed03-4fc0-9b13-d429e68f1400","correlation_id":"a7ca8821-f987-4eb7-b51e-08f0c266a07b","error_uri":https://login.microsoftonline.com/error?code=90002}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shree/.local/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 176, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 756, in find_using_common_tenant
    specific_tenant_credential = identity.get_user_credential(username)
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 224, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/home/shree/.local/lib/python3.8/site-packages/azure/cli/core/auth/msal_authentication.py", line 39, in __init__
    super().__init__(client_id, **kwargs)
  File "/home/shree/.local/lib/python3.8/site-packages/msal/application.py", line 1629, in __init__
    super(PublicClientApplication, self).__init__(
  File "/home/shree/.local/lib/python3.8/site-packages/msal/application.py", line 489, in __init__
    self.authority = Authority(
  File "/home/shree/.local/lib/python3.8/site-packages/msal/authority.py", line 106, in __init__
    raise ValueError(
ValueError: Unable to get authority configuration for https://login.microsoftonline.com/042afadc-7134-4617-9b93-ee67367522fe. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
To open an issue, please run: 'az feedback'

**Comment by yonzhan** [comment] 2022-10-14 23:51
Duplicate of https://github.com/Azure/azure-cli/issues/20507. Please make sure your tenant GUID or name is correct.

**Closed by yonzhan** 2022-10-14 23:51 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
