### ISSUE TITLE
Please document required permissions

### ISSUE THREAD

**Issue by TWolverson** [Azure/azure-cli#26488] opened 2023-05-18 16:15 UTC
I have written a script which uses `az ad group member add`. This errors when the specified object id is already a member, so I added another step `az ad group member check` first before trying to add them again. I was expecting this to require the same permissions; why wouldn't it? But this fails with a permissions error that doesn't tell me **what** permission it expects, and the documentation is no help.

The CLI reference should list what permissions are required to run each command. To be honest, I'm surprised this wasn't considered a bare minimum essential requirement for the documentation. Otherwise, this conversation will happen every time I need to negotiate access to a resource to be able to do any configuration:
Them: "What permissions do you need?"
Me: "I don't know; everything?"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45dfe717-aca6-420c-8ba1-83a6cddbaf4a
* Version Independent ID: 1eadc56a-abbf-cc25-9a45-757fbee16f75
* Content: [Azure Active Directory](https://learn.microsoft.com/en-us/cli/azure/service-page/azure%20active%20directory?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/service-page/Azure Active Directory.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/service-page/Azure Active Directory.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2023-05-18 16:15
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2023-05-19 02:19
Duplicate of #22362

**Closed by jiasli** 2023-05-19 02:19 UTC
Labels: question, Graph, AAD, customer-reported, Auto-Assign, Azure CLI Team
