### ISSUE TITLE
Cannot create web apps in Azure

### ISSUE THREAD

**Issue by kobayashikazu** [Azure/azure-cli#23420] opened 2022-08-03 03:28 UTC
**Related command**
az webapp up --runtime PYTHON:3.9 --sku FREE --logs

**Describe the bug**
The error urllib3.exceptions.ProtocolError: is printed.

**To Reproduce**
(.venv) C:\Users\user_\msdocs-python-flask-webapp-quickstart>pip install -r requirements.txt

(.venv) C:\Users\user_\msdocs-python-flask-webapp-quickstart>az login
(.venv) C:\Users\user_\msdocs-python-flask-webapp-quickstart>az webapp up --runtime PYTHON:3.9 --sku FREE --logs

The webapp 'zealous-wave-*********' doesn't exist
Creating Resource group 'user_*********' ...
Resource group creation complete
Creating AppServicePlan 'user_*********' ...
Creating webapp 'zealous-wave-*********' ...
Configuring default logging for the app, if not already enabled
Creating zip with contents of dir C:\Users\user_\msdocs-python-flask-webapp-quickstart ...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
You can launch the app at Http://zealous-wave-*********.azurewebsites.net
Configuring default logging for the app, if not already enabled
2022-08-03T03:15:43  Welcome, you are now connected to log-streaming service.
Exception in thread Thread-1 (_get_log):
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 697, in _update_chunk_length
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 438, in _error_catcher
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 764, in read_chunked
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 701, in _update_chunk_length
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2613, in _get_log
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 572, in stream
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 752, in read_chunked
  File "contextlib.py", line 153, in __exit__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 455, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

ProtocolError:" error and does not proceed to the next process.

**Expected behavior**

I want to create a web app in Azure.

**Environment summary**

OS version:Windows 10

Python Virtual Environment:Python 3.9.13

azure cli version:

azure-cli                         2.39.0
core                              2.39.0
telemetry                          1.0.6 *

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\user_\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

※I am using a free Azure account.

**Comment by yonzhan** [comment] 2022-08-03 04:37
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2022-08-03 18:09
@kobayashikazu We are looking into it and get back to you for any additional information.

**Comment by kobayashikazu** [comment] 2022-08-03 23:22
@SaurabhSharma-MSFT Thank you.

**Comment by SatishBoddu-MSFT** [comment] 2022-08-09 23:02
Hello @kobayashikazu Thanks for reaching out on this issue!

Is this the below document that you have followed?
[Quickstart: Deploy a Python (Django or Flask) web app to Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=flask%2Cwindows%2Cazure-cli%2Cvscode-deploy%2Cdeploy-instructions-azportal%2Cterminal-bash%2Cdeploy-instructions-zip-azcli)

**Comment by kobayashikazu** [comment] 2022-08-10 03:33
[Quickstart: Deploy a Python (Django or Flask) web app to Azure App Service
](https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=flask%2Cwindows%2Cazure-cli%2Cvscode-deploy%2Cdeploy-instructions-azportal%2Cterminal-bash%2Cdeploy-instructions-zip-azcli)

Hello @SaurabhSharma-MSFT  Follow the documentation.

`py -3.9 -m venv .venv
`
`az webapp up --runtime PYTHON:3.9 --sku Free --logs
`
Where it differs somewhat is in the above commands.

```
Configuring default logging for the app, if not already enabled
2022-08-10T03:26:00  Welcome, you are now connected to log-streaming service.
Exception in thread Thread-1 (_get_log):
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 697, in _update_chunk_length
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 438, in _error_catcher
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 764, in read_chunked
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 701, in _update_chunk_length
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2613, in _get_log
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 572, in stream
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 752, in read_chunked
  File "contextlib.py", line 153, in __exit__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 455, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

※The process does not proceed with urllib3.exceptions.ProtocolError being displayed.

**Comment by jbrandesLS** [comment] 2022-08-16 16:58
I'm currently having the same issue in the Azure web UI. I've been trying for weeks now to upload my code via zip.  I'm getting this error. Any progress on a solution? 

![snippet 081622](https://user-images.githubusercontent.com/111380057/184936391-5e34bc12-7fc2-4529-8f1e-f287de08459c.png)

**Comment by Nazarius1** [comment] 2022-09-18 12:55
Hello Azure team, 

I am having the same problem. 
Is there already any explanation about the error?
Thank you.

**Comment by panchagnula** [comment] 2022-09-30 00:31
from the original issue reported & stack trace, the app was created successfully, the --logs is the one causing exception & I believe this might be because logstreaming is not supported on Free SKU. Please run the same command without --logs & see if that works.

**Comment by panchagnula** [comment] 2022-09-30 00:32
> I'm currently having the same issue in the Azure web UI. I've been trying for weeks now to upload my code via zip. I'm getting this error. Any progress on a solution?
> 
> ![snippet 081622](https://user-images.githubusercontent.com/111380057/184936391-5e34bc12-7fc2-4529-8f1e-f287de08459c.png)

Sorry this needs to be reported to the portal team - maybe create a support case.

**Comment by tulikac** [comment] 2023-09-20 14:40
Duplicate of https://github.com/Azure/azure-cli/issues/25599. We will be tracking the linked issue.

**Closed** 2023-10-04 14:51 UTC
Labels: Web Apps, Service Attention, customer-reported, Auto-Assign, app-service-logging-monitoring
