### ISSUE TITLE
Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by samhodgkinson** [Azure/azure-cli#28322] opened 2024-02-07 13:14 UTC
### Describe the bug

When using Azure CLI work with what seems to be JSON object from multiple commands I'm getting, the below errors today, this work fine the day before.

### Related command

Az datadog monitor create

az repos pr create

### Errors

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/json/__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 1869, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 2096, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 2073, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.11/argparse.py", line 1962, in take_action
    argument_values = self._get_values(action, argument_strings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/parser.py", line 272, in _get_values
    value = super(AzCliCommandParser, self)._get_values(action, arg_strings)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 2506, in _get_values
    self._check_value(action, value[0])
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/parser.py", line 300, in _check_value
    use_dynamic_install = try_install_extension(self, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/extension/dynamic_install.py", line 119, in try_install_extension

### Issue script & Debug output

We seem to be seeing UTF-8 BOM which seems to be affect actions performed on json

### Expected behavior

To deploy data dog ISV 
To create an AZO pull / approve ...etc

### Environment Summary

[Azure DevOps CLI extension for Azure CLI 1.0.0](https://github.com/Azure/azure-devops-cli-extension/releases/tag/20240206.1) [Latest](https://github.com/Azure/azure-devops-cli-extension/releases/latest)

**Comment by yonzhan** [comment] 2024-02-07 13:14
Thank you for opening this issue, we will look into it.

**Comment by samhodgkinson** [comment] 2024-02-07 13:15
> Hi @samhodgkinson Find similar issue #28321.
> 
> Issue title	Installation of extension(s) is not working due to parsing error of extensionCommandTree.json
> Create time	2024-02-07
> Comment number	0
> Please confirm if this resolves your issue.

This look similar but does not fix my issue

**Comment by mdrakiburrahman** [comment] 2024-02-07 13:22
All our automation pipelines are all blocked. This is a new regression caused last night in Azure CLI, things were working fine last night for the same pipeline:

![image](https://github.com/Azure/azure-cli/assets/46581776/4a9f9cfd-8ffe-4d7d-a61f-2d0346e79d41)

**Comment by DeV1L** [comment] 2024-02-07 13:27
The same issue with `az ssh vm --ip ...`

```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/json/__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 1869, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 2096, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 2073, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.11/argparse.py", line 1962, in take_action
    argument_values = self._get_values(action, argument_strings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/parser.py", line 272, in _get_values
    value = super(AzCliCommandParser, self)._get_values(action, arg_strings)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/argparse.py", line 2506, in _get_values
    self._check_value(action, value[0])
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/parser.py", line 300, in _check_value
    use_dynamic_install = try_install_extension(self, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/extension/dynamic_install.py", line 119, in try_install_extension
    _check_value_in_extensions(cli_ctx, parser, args, use_dynamic_install == 'yes_without_prompt')
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/extension/dynamic_install.py", line 150, in _check_value_in_extensions
    ext_name = _search_in_extension_commands(cli_ctx, command_str, allow_prefix_match=allow_prefix_match)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/extension/dynamic_install.py", line 87, in _search_in_extension_commands
    cmd_chain = _get_extension_command_tree(cli_ctx)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/extension/dynamic_install.py", line 38, in _get_extension_command_tree
    EXT_CMD_TREE.data = response.json()
                        ^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

**Comment by LandryDubus** [comment] 2024-02-07 13:28
We got the same issue starting today too

**Comment by ranat5** [comment] 2024-02-07 13:28
We are also having a similar issue in our automated pipelines -
<img width="932" alt="image" src="https://github.com/Azure/azure-cli/assets/97531570/b0295d15-fbcb-43ef-ac03-8306aa2aec80">

**Comment by SAday-WASR** [comment] 2024-02-07 13:30
Same issue here, using `az functionapp config appsettings set`

**Comment by kabasm** [comment] 2024-02-07 13:33
Same issue here, using `az monitor app-insights component create`

**Comment by grixxie** [comment] 2024-02-07 13:34
same issue here using ``` az monitor app-insights component show ```, started seeing this 1-2 hours ago today

**Comment by malsey** [comment] 2024-02-07 13:35
same issue using `az config set extension.use_dynamic_install=yes_without_prompt --only-show-errors`

**Comment by arasdk** [comment] 2024-02-07 13:44
Same issue here using `az datafactory pipeline-run query-by-factory --factory-name "name" --resource-group "rg" --output json | ConvertFrom-Json -Depth 100`

**Comment by virgilp** [comment] 2024-02-07 13:48
Same issues with `az account help` - pretty much everything

**Comment by jiasli** [comment] 2024-02-07 13:55
Duplicate of #28321

**Closed by jiasli** 2024-02-07 13:55 UTC
Labels: bug, Service Attention, customer-reported, DevOps, Auto-Assign, Auto-Resolve, Similar-Issue

**Comment by yonzhan** [comment] 2024-02-07 13:56
We are looking into this and will follow up in https://github.com/Azure/azure-cli/issues/28321
