### ISSUE TITLE
VM Create: differences between Xplat CLI and Azure CLI 2.0

### ISSUE THREAD

**Issue by dkarakas1** [Azure/azure-cli#3120] opened 2017-05-01 19:21 UTC
### Description
**Outline the issue here:**

Azure CLI tools no longer taking plan information and requires new storage flags.

This command was working on April 7, 2017 but does not today:

```
/usr/local/bin/azure vm create
--resource-group
--name
--location
--vm-size
--nic-names
--storage-account-name
--storage-account-container-name
--admin-username
--admin-password
--image-urn
--plan-name
--plan-publisher
--plan-product
--os-type
```
The --plan* flags are no longer accepted for Marketplace Images.
The --storage* flags no longer work without the --use-unmanaged-disk flag.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

`https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#linux`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

```
azure --version
azure-cli (2.0.2)

acr (2.0.0)
acs (2.0.2)
appservice (0.1.2)
batch (2.0.0)
cloud (2.0.0)
component (2.0.0)
configure (2.0.2)
container (0.1.2)
core (2.0.2)
documentdb (0.1.2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.2)
keyvault (2.0.0)
lab (0.0.1)
monitor (0.0.1)
network (2.0.2)
nspkg (2.0.0)
profile (2.0.2)
redis (0.1.1b3)
resource (2.0.2)
role (2.0.1)
sql (2.0.0)
storage (2.0.2)
vm (2.0.2)

Python (Linux) 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
```
pip3 freeze
adal==0.4.5
asn1crypto==0.22.0
awscli==1.11.75
azure==2.0.0rc5
azure-batch==0.30.0rc5
azure-common==1.1.5
azure-graphrbac==0.30.0rc5
azure-mgmt==0.30.0rc5
azure-mgmt-authorization==0.30.0rc5
azure-mgmt-batch==0.30.0rc5
azure-mgmt-cdn==0.30.0rc5
azure-mgmt-cognitiveservices==0.30.0rc5
azure-mgmt-commerce==0.30.0rc5
azure-mgmt-compute==0.30.0rc5
azure-mgmt-keyvault==0.30.0rc5
azure-mgmt-logic==0.30.0rc5
azure-mgmt-network==0.30.0rc5
azure-mgmt-notificationhubs==0.30.0rc5
azure-mgmt-nspkg==2.0.0
azure-mgmt-powerbiembedded==0.30.0rc5
azure-mgmt-redis==0.30.0rc5
azure-mgmt-resource==0.30.0rc5
azure-mgmt-scheduler==0.30.0rc5
azure-mgmt-storage==0.30.0rc5
azure-mgmt-web==0.30.0rc5
azure-nspkg==2.0.0
azure-servicebus==0.20.2
azure-servicemanagement-legacy==0.20.3
azure-storage==0.32.0
botocore==1.5.38
certifi==2017.1.23
cffi==1.10.0
click==6.7
colorama==0.3.8
cryptography==1.8.1
docutils==0.13.1
idna==2.5
isodate==0.5.4
jmespath==0.9.2
keepercommander==0.6.5
keyring==10.3.2
msrest==0.4.7
msrestazure==0.4.7
oauthlib==2.0.2
packaging==16.8
pip-autoremove==0.9.0
py==1.4.33
pyasn1==0.2.3
pycparser==2.17
pycrypto==2.6.1
pycryptodomex==3.4.5
PyJWT==1.4.2
pyparsing==2.2.0
pytest==3.0.7
python-dateutil==2.6.0
PyYAML==3.12
requests==2.13.0
requests-oauthlib==0.8.0
rsa==3.4.2
s3transfer==0.1.10
SecretStorage==2.3.1
six==1.10.0
tabulate==0.7.7
```

**OS Version:** What OS and version are you using?  
Answer here:

```
cat /etc/centos-release                                                                             
CentOS Linux release 7.3.1611 (Core)
```

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

BASH

**Comment by dkarakas1** [comment] 2017-05-01 19:33
More on the installation history:
```
history|grep -i -e az -e azure
   39  curl -L https://aka.ms/InstallAzureCli | bash
   46  pip install azure==2.0.0rc5
   48  pip install msrestazure
```

**Comment by tjprescott** [comment] 2017-05-01 19:47
A couple things here:

1) "azure" refers to Xplat CLI (https://github.com/Azure/azure-xplat-cli) or Azure CLI 1.0. Thus arguments you listed are from Xplat CLI. What you describe are difference between the two products.

2) Azure CLI 2.0 does support creation of images that require plan information.  The CLI simply handles this behind the scenes.  @yugangw-msft, correct me if I'm wrong.

3). It would be the correct behavior in both Xplat and Azure CLI 2.0 that the storage parameters only work when `--use-unmanaged-disks` is supplied since the default behavior is to use managed disks, which does not require the creation of a storage account.

**Comment by dkarakas1** [comment] 2017-05-01 20:03
Pretty sure Xplat is not installed on my dev platform.  Xplat requires nodejs, which is not installed on my dev platform.  I installed azure-cli via:

curl -L https://aka.ms/InstallAzureCli | bash

I then ran "pip install azure==2.0.0rc5" as per Ansible Azure getting started doc here:

**Comment by tjprescott** [comment] 2017-05-01 20:26
Commands in Azure 2.0 are run using `az`.  Commands in Xplat are run using `azure`.  The parameters you listed:

```
/usr/local/bin/azure vm create
--resource-group
--name
--location
--vm-size
--nic-names
--storage-account-name
--storage-account-container-name
--admin-username
--admin-password
--image-urn
--plan-name
--plan-publisher
--plan-product
--os-type
```

These are parameters used in Xplat, not Azure CLI 2.0.  You have installed it correctly, but the thing you are comparing it to isn't the older version of Azure CLI 2.0, but rather Xplat CLI.

**Comment by dkarakas1** [comment] 2017-05-01 20:34
Are you saying that running 

`pip install azure==2.0.0rc5`

resulted in Azure XPlat being installed?

Checking rpm database I don't have the npm or nodejs packages installed, which appear to be required to install XPlat.

**Comment by yugangw-msft** [comment] 2017-05-01 20:47
> Azure CLI 2.0 does support creation of images that require plan information. The CLI simply handles this behind the scenes. @yugangw-msft, correct me if I'm wrong.

@tjprescott it is correct. CLI 2.0 never ever exposes `--plan`

> `/usr/local/bin/azure vm create` 

This is definitely xplat. Please run `azure` and share the ouput

**Comment by tjprescott** [comment] 2017-05-01 20:47
Well `pip install azure==2.0.0rc5` would result in an older version of the Azure SDK being installed. We have never supported `--plan*` arguments within Azure CLI 2.0. Only Xplat has supported those. 

If you run `az -h` and `azure -h` you will get very different output.

**Comment by dkarakas1** [comment] 2017-05-01 22:48
@tjprescott On my system, az and azure are the same command.  I created a softlink from az to azure:

```
[karakas@cent7 ~]$ which az
/usr/local/bin/az
[karakas@cent7 ~]$ which azure
/usr/local/bin/azure
[karakas@cent7 ~]$ ll /usr/local/bin/az
-rwxr-xr-x. 1 root root 74 Apr 11 13:40 /usr/local/bin/az
[karakas@cent7 ~]$ ll /usr/local/bin/azure
lrwxrwxrwx. 1 root root 17 Apr 11 21:09 /usr/local/bin/azure -> /usr/local/bin/az
```

So the actual command on my box is /usr/local/bin/az

**Comment by tjprescott** [comment] 2017-05-01 23:20
The plan arguments were not removed as they have never existed in CLI 2.0 (however you can create Marketplace Images that require this information).

That storage account parameters do not work without specifying `--use-unmanaged-disks` is by design.

Closing this issue.

**Closed by tjprescott** 2017-05-01 23:20 UTC
Labels: Compute
