### ISSUE TITLE
Switching the environment in the cli will report an error

### ISSUE THREAD

**Issue by ulua1** [Azure/azure-cli#27279] opened 2023-08-29 09:15 UTC
### Describe the bug

Switching the login environment in the cli will report an error

### Related command

az cloud set --name Azurecloud
az login

### Errors

The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 168, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/application.py", line 2011, in acquire_token_by_device_flow
    response = _clean_up(self.client.obtain_token_by_device_flow(
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/oauth2cli/oauth2.py", line 383, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/oauth2cli/oauth2.py", line 345, in _obtain_token_by_device_flow
    result = self._obtain_token(
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/oauth2cli/oauth2.py", line 788, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/application.py", line 707, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/token_cache.py", line 317, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/token_cache.py", line 128, in add
    return self.__add(event, now=now)
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/token_cache.py", line 192, in __add
    self.modify(self.CredentialType.ACCESS_TOKEN, at, at)
  File "/usr/lib64/az/lib/python3.9/site-packages/msal_extensions/token_cache.py", line 64, in modify
    self._reload_if_necessary()
  File "/usr/lib64/az/lib/python3.9/site-packages/msal_extensions/token_cache.py", line 55, in _reload_if_necessary
    self.deserialize(self._persistence.load())
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/token_cache.py", line 329, in deserialize
    self._cache = json.loads(state) if state else {}
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Issue script & Debug output

no

### Expected behavior

You can switch subscriptions normally

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
azure-iot                         0.21.4
ml                                2.19.1
spring                            1.13.2
spring-cloud                       3.1.8
ssh                                2.0.1
webpubsub                          1.3.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/marian/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

no

**Comment by jiasli** [comment] 2023-08-29 11:09
Duplicate of #26312

**Closed by jiasli** 2023-08-29 11:09 UTC
Labels: Account, question, customer-reported, CXP Attention, Auto-Assign, Azure CLI Team
