### ISSUE TITLE
az network application-gateway using older API version

### ISSUE THREAD

**Issue by prateek2211** [Azure/azure-cli#28635] opened 2024-03-26 10:44 UTC
### Describe the bug

az network application-gateway command is using api version 2022-05-01 which is incorrect.
API version was last updated in this PR to 2023-02-01 - https://github.com/Azure/azure-cli/pull/26958/files
But, this doesn't seem to be reflected in all of the az network application-gateway commands

### Related command

az network application-gateway

### Errors

ApplicationGatewayCustomErrorStatusCodeIsInvalid

### Issue script & Debug output

az network application-gateway ssl-policy set -g agw-js --gateway-name agw-js -n AppGwSslPolicy20170401S --policy-type Predefined

### Expected behavior

Expected to use API version 2023-02-01

### Environment Summary

{   "azure-cli": "2.58.0",   "azure-cli-core": "2.58.0",   "azure-cli-telemetry": "1.1.0",   "extensions": {     "ai-examples": "0.2.5",     "ml": "2.23.0",     "ssh": "2.0.2"   } }

**Comment by yonzhan** [comment] 2024-03-26 10:44
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment] 2024-03-27 06:44
from the codebase, it should be 2022-05-01 https://github.com/necusjz/azure-cli/blob/8628b084e87eaa0d25775a5c9ba1a0b90e0e9267/src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/ssl_policy/_set.py#L30

**Comment by jaesoni** [comment] 2024-04-08 07:15
@necusjz can you please take a look at this and help us get this on priority. The GA release of this feature is kept on hold due to the missing API details. Thanks

**Comment by necusjz** [comment] 2024-04-08 08:23
> ApplicationGatewayCustomErrorStatusCodeIsInvalid

@prateek2211 we can do that, but could you please share some evidences about `ApplicationGatewayCustomErrorStatusCodeIsInvalid` is caused by api version (2022-05-01)? and 2023-02-01 can really solve it.

**Comment by jaesoni** [comment] 2024-04-08 09:01
Customer case# 2402220050000353 - It gives this error for another listener that has the custom error page configured and is targeted to be changed by the Azure CLI command.

`az network application-gateway rule update -g bdavid_AppGw_training --gateway-name myAppGateway -n WebApp --address-pool test_delete
(ApplicationGatewayCustomErrorStatusCodeIsInvalid) Custom error page has an invalid HTTP status code '500', for httpListeners /subscriptions/0fa91e27-da0e-45b9-82d3-45e0c0532c82/resourceGroups/bdavid_AppGw_training/providers/Microsoft.Network/applicationGateways/myAppGateway/httpListeners/bogdan2.anas.cloud. Valid status codes are: '[403, 502]'.
Code: ApplicationGatewayCustomErrorStatusCodeIsInvalid
Message: Custom error page has an invalid HTTP status code '500', for httpListeners /subscriptions/0fa91e27-da0e-45b9-82d3-45e0c0532c82/resourceGroups/bdavid_AppGw_training/providers/Microsoft.Network/applicationGateways/myAppGateway/httpListeners/bogdan2.anas.cloud. Valid status codes are: '[403, 502]'`

**Comment by necusjz** [comment] 2024-04-08 09:18
did you mean that, the valid status code in `2023-02-01` contains 500?

**Comment by jaesoni** [comment] 2024-04-08 09:23
yes, these are all the new status codes introduced in preview state.
![image](https://github.com/Azure/azure-cli/assets/80025770/8415ab6b-3b10-4b18-82f1-fe0725a624dc)

**Comment by jaesoni** [comment] 2024-04-24 15:22
@necusjz @yonzhan what will be its go-live ETA? Thanks

**Comment by necusjz** [comment] 2024-04-25 03:45
https://github.com/Azure/azure-cli/milestone/142

**Comment by necusjz** [comment] 2024-05-13 02:49
resolved by https://github.com/Azure/azure-cli/pull/28934

**Closed by necusjz** 2024-05-13 02:49 UTC
Labels: Network, question, Auto-Assign, Azure CLI Team
