### ISSUE TITLE
az postgres server vnet-rule create And Requested feature is not enabled

### ISSUE THREAD

**Issue by mnadeem** [Azure/azure-cli#25580] opened 2023-02-25 07:29 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

I have created postgres server with **Deny public network access** set to **yes**

<img width="771" alt="image" src="https://user-images.githubusercontent.com/476145/221344676-acb80b93-b3ed-4dcc-9fa9-20211fb199b5.png">

When I execute the following

```
az postgres server vnet-rule create --name $rule --resource-group $resourceGroup --server $server --vnet-name $vNet --subnet $subnet
```

I am getting the following error

<img width="864" alt="image" src="https://user-images.githubusercontent.com/476145/221344751-68159e41-3d2c-4bf0-a261-5c4a24903f49.png">

Note the subnet

<img width="574" alt="image" src="https://user-images.githubusercontent.com/476145/221344777-5d04e0ca-5800-4555-adc0-049ddecdccdb.png">

**To Reproduce**

Follow the above steps

**Expected behavior**

Vnet rule should execute fine 

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment] 2023-02-25 11:02
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2023-03-02 02:05
@mnadeem I am not able to reproduce this error and you may be getting this error if you subscription is not registered with `Microsoft.Sql` and `Microsoft.DBforPostgreSQL` resource providers. Can you please go to Azure Portal > Your subscription > Resource provider tab and check for the required resource providers?
![image](https://user-images.githubusercontent.com/38112130/222306251-bc28e2f4-9d50-45d5-9df0-c147936a6224.png)

**Comment by SaurabhSharma-MSFT** [comment] 2023-03-08 02:57
@mnadeem Please let us know if you need any help on this.

**Comment by SaurabhSharma-MSFT** [comment] 2023-03-10 17:12
@mnadeem We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2023-03-10 17:12 UTC
Labels: question, PostgreSQL, customer-reported, needs-author-feedback, CXP Attention, Auto-Assign
