### ISSUE TITLE
CLI is logging on each command when service-principal is used

### ISSUE THREAD

**Issue by bsuchorowski** [Azure/azure-cli#13275] opened 2020-04-30 10:14 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 
2.5.0 and older

**Describe the bug**
We are experiencing same issues with login taking too long as described here https://github.com/Azure/azure-cli/issues/7465. We use self-hosted Azure Devops agent and AzureCLI@2 task. From time to time it takes a few minutes to login. As we are doing a lot of quering from our container registry via az acr command, we notices that our script (that contains ~10 az commands) takes 10+ minutes to finish and it is only querying simple things such as repository tags and so on. I tried to reproduce it with --debug option and I noticed that every command tries to login and hangs there for a while. I am wondering why it does not find any cached accessTokens in accessToken.json (entry for service-principal does not have _clientId property over there).

> adal-python : bcd11473-ee6d-48f7-9123-ae680f2dce7c - TokenRequest:No user_id passed for cache query
adal-python : bcd11473-ee6d-48f7-9123-ae680f2dce7c - CacheDriver:finding with query keys: {'_clientId': '...'}
adal-python : bcd11473-ee6d-48f7-9123-ae680f2dce7c - CacheDriver:Looking for potential cache entries: {'_clientId': '...'}
adal-python : bcd11473-ee6d-48f7-9123-ae680f2dce7c - CacheDriver:Found 0 potential entries.
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com:443

It happens on every az command and it takes a lot of time.

**To Reproduce**
1. Login with az login --service-principal
2. Do any az command, for example az acr repository list with --debug to see whether it uses cached token or not.

**Expected behavior**
1. Running the command should not require to login every time.

**Comment by yonzhan** [comment] 2020-04-30 10:46
@jiasli  please take a look

**Comment by jiasli** [comment] 2020-04-30 10:48
Duplicate of #13276

**Closed by jiasli** 2020-04-30 10:48 UTC
Labels: customer-reported, feature-request, question
