### ISSUE TITLE
Pulling latest resource SDK update breaks most tab completions [Regression]

### ISSUE THREAD

**Issue by oakeyc** [Azure/azure-cli#3412] opened 2017-05-19 23:29 UTC
### Description
**Outline the issue here:**
completions for:
```bash
az vm show -n 
```
show the right completions
but when you do
```bash
az vm show -g {group} -n
```
the '-g' is supposed to narrow the completions to ones of just that resource group, but no completions appear all together
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev-setup

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.6+dev

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment] 2017-05-22 15:58
This has the same root cause as #3343.

**Comment by tjprescott** [comment] 2017-05-22 16:05
This was caused by PR #3256.

While it needs to be fixed, we also need to add unit tests to cover these completer methods and protect against future regression.

**Comment by tjprescott** [comment] 2017-05-24 16:39
TL/DR -- closing issue

This was fixed by PR #3416 as both the command and the generic completer used the same method. Thus, as long as we have a test for `resource list` (which we do) then this is protected. Issue #3336 covers testing for API profiles more generally, so when that is done, the testing aspect will be covered here as well.

**Closed by tjprescott** 2017-05-24 16:39 UTC
Labels: bug, Profile Versioning, Resource Manager
