### ISSUE TITLE
azure login through interactive mode: cant recognizer user identifier or password

### ISSUE THREAD

**Issue by BrodaUa** [Azure/azure-cli#3501] opened 2017-05-28 20:47 UTC
### Description
Basically, I already solved my problem, and as I did not find any information to such kind of issues, in case if somebody else will face that too, I decided to describe it here. 

So, I was having an issue during interactive login using Azure CLI 1.0 from my Linux VM. And the key of interactive login is that you need to follow the link and input the code from the command line. As I was connected to my VM only through Putty from Windows, I was not be able to go to that link and specify the code, thats whyI was using my browser on Windows. And the thing is when you trying to do that, it shows an error in the browser like this: 

> Can not recognizer user identifier or password

And it solves just installing the CLI tool on Windows and following all the steps for login. 
Hope somebody will find this helpful.

P.S.: please fix problems with urllib3 on CLI 2.0 login 
P.S.S.: put it to the appropriate place as FAQ, whatever. Or delete it if there are already such info provided.

**Comment by yugangw-msft** [comment] 2017-05-29 01:06
Using browser in Windows to login should definitely work. Once the login in the browser page goes through the "az login" command in the Putty shell should proceed to finish.
The error inside the browser of `Can not recognizer user identifier or password` is an AAD service bug. Could you please send me the error page, particularly the correlation id and associated fiddler trace. I will forward to ESTS team to investigate. My mail is yugangw at microsoft dot com
Since this is not a CLI issue or an expected behavior we should document, I will close it.

**Closed by yugangw-msft** 2017-05-29 01:06 UTC
