### ISSUE TITLE
december_2024

### ISSUE THREAD

**Issue by tchatua** [Azure/azure-cli#30556] opened 2024-12-20 06:33 UTC
### Describe the bug

Unable to run terraform plan on azure

### Related command

az plan

### Errors

[Warning] The login output has been updated. Please be aware that it no longer displays the full list of available subscriptions by default.

### Issue script & Debug output

az login

### Expected behavior

login on az

### Environment Summary

azure cli

**Comment by yonzhan** [comment] 2024-12-20 06:33
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-12-23 08:17
Duplicate of https://github.com/Azure/azure-cli/issues/30558

**Closed by jiasli** 2024-12-23 08:17 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
