### ISSUE TITLE
Not sure I understand the local context error

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#15335] opened 2020-09-28 21:30 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Interesting... not sure if local context worked or not...
![image](https://user-images.githubusercontent.com/30876406/94488104-df6b3780-0196-11eb-94d3-1733ef8aea41.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/30876406/94488145-f3169e00-0196-11eb-94bd-c163471965d1.png)

**Expected behavior**
1) Output from az config param-persist that either it's successfully turned on or not, without having user to run it the 2nd time to doublecheck
2) Being able to view what the validation error is about...

**Environment summary**

![image](https://user-images.githubusercontent.com/30876406/94488229-14778a00-0197-11eb-8e26-7a72b1095472.png)

**Additional context**

**Comment by yungezz** [comment] 2020-09-29 00:10
hi @arrownj could you pls have a look? thanks

**Comment by houk-ms** [comment] 2020-09-29 05:22
Currently, **CLIError** message will be prefixed with the 'ValidationError', but I have no idea why the message is blank.

As we discussed, the 'ValidationError' will not shown to users any more unless we know it's a **ValidationError**.

**Comment by arrownj** [comment] 2020-09-29 07:26
Hi @chenlomis , why there is no output of `az group create` ? I tried as your commands and the group was created successfully. Could you please try once more with `--debug` ?

**Comment by chenlomis** [comment] 2020-09-29 23:22
Thank you for all the follow ups
I'm not entirely sure what happened but when I reran the commands today it worked
![image](https://user-images.githubusercontent.com/30876406/94626363-d1d5b080-026f-11eb-8dd2-96945f7c08b0.png)

**Comment by chenlomis** [comment] 2020-09-29 23:24
I do think though.. if it's an output message indicating that the feature is already turned on.. perhaps we could make it a generic output instead of an error like what Houk suggested (?)

**Comment by arrownj** [comment] 2020-09-30 01:20
Hi @chenlomis , let's keep this issue open until the root cause is addressed. For the screenshot you give in the beginning, actually it is by design in 2.12.0. If `param-persist(local-context)` is turned on, CLI will raise an error and our error framework will automatically add a `ValidationError`. We will do 2 changes in the coming release:

1. From `param-persist(local-context)` side, we will only print a warning message instead of throwing an error when `pram-persist(local-context)` is already on/off
2. From error handling side, Houk will update the mechanism not to add "ValidationError" if it is CLIError. (@houk-ms please fix me if I'm not right)

What wired in your case is that there is an empty error when you run `az group create`. I'm not what's going wrong in your case. So if you come across it again, could please please run with `--debug` and paste the log to us. It will help us identify the root case a lot. Thanks very much. :)

**Comment by chenlomis** [comment] 2020-09-30 16:48
Thank you! Love the response. Will run --debug in my future screenshots/issues too

**Comment by arrownj** [comment] 2020-11-19 07:05
Close this first as not able to reproduce the empty error message problem.

**Closed by arrownj** 2020-11-19 07:05 UTC
Labels: Error Handling, Local Context
