### ISSUE TITLE
`az ad sp create-for-rbac` without password errors

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#5959] opened 2018-03-30 00:28 UTC
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
- homebrew
- MacOS High Sierra
- zsh

```
$ az -v
azure-cli (2.0.30)

acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.1.0)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.20)
core (2.0.30)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.20)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.20)
monitor (0.1.4)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.21)
rdbms (0.2.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.30)
vm (2.0.29)
```

STR:
- run `az ad sp create-for-rbac`

EXPECTED:
- SP credentials generated including autogenerated password

ACTUAL:
```
The password should contain least 1 upper/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 930, in create_service_principal_for_rbac
    end_date=app_end_date)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 584, in create_application
    result = client.create(app_patch_param)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/graphrbac/operations/applications_operations.py", line 86, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: The password should contain least 1 upper/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
```

**Comment by johanburati** [comment] 2018-03-30 00:38
I noticed the same issue, I tried with azure-cli (2.0.30) on Cloud Shell and with azure-cli (2.0.29) on my Ubuntu workstation.
<hr>

- Cloud Shell
```

johan@Azure:~$ az --version
azure-cli (2.0.30)

acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.1.0)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.20)
core (2.0.30)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.20)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.20)
monitor (0.1.4)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.21)
rdbms (0.2.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.30)
vm (2.0.29)

Python location '/opt/az/bin/python3'
Extensions directory '/home/johan/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Mar 23 2018, 16:30:24)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal
```

```
johan@Azure:~$ az ad sp create-for-rbac
The password should contain least 1 upper/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 930, in create_service_principal_for_rbac
    end_date=app_end_date)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 584, in create_application
    result = client.create(app_patch_param)
  File "/opt/az/lib/python3.6/site-packages/azure/graphrbac/operations/applications_operations.py", line 86, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: The password should contain least 1 upper/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
```
<hr>

- Ubuntu workstation
```
azure-cli (2.0.29)

acr (2.0.22)
acs (2.0.28)
advisor (0.5.0)
appservice (0.1.29)
backup (1.0.7)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.29)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.11)
eventhubs (0.1.0)
extension (0.0.10)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.17)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.17)
monitor (0.1.3)
network (2.0.25)
nspkg (3.0.2)
profile (2.0.20)
rdbms (0.1.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.25)
role (2.0.20)
servicebus (0.1.0)
servicefabric (0.0.11)
sql (2.0.23)
storage (2.0.27)
vm (2.0.28)

Python location '/opt/az/bin/python3'
Extensions directory '/home/dad/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Mar 10 2018, 17:48:57) 
[GCC 4.7.2]

Legal docs and information: aka.ms/AzureCliLegal

```

```
 ~  $  az ad sp create-for-rbac
The password should contain least 1 upper/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 418, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 814, in create_service_principal_for_rbac
    end_date=app_end_date)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 562, in create_application
    return client.create(app_create_param)
  File "/opt/az/lib/python3.6/site-packages/azure/graphrbac/operations/applications_operations.py", line 87, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: The password should contain least 1 upper/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
```

**Comment by yugangw-msft** [comment] 2018-03-30 03:47
Can you please run with --debug,  capture the output and send it to me at yugangw at microsoft dot com? If the generated uuid4 (to be used as password) does not contain characters, then it could fail. Anyway, I would like see what kind of password that could fail like this

**Comment by yugangw-msft** [comment] 2018-03-30 04:02
Thanks for the log. I will follow up the AAD graph team and post updates here

**Comment by seanknox** [comment] 2018-03-30 04:15
Thanks Yugang. Could you share the icm ticket #?

thanks,
Sean
________________________________

**Comment by yugangw-msft** [comment] 2018-03-30 05:34
ICM ticket: 
https://icm.ad.msft.net/imp/v3/incidents/details/64290805

**Comment by acmshanyi** [comment] 2018-03-30 05:36
Same issue here. Tried to create kube cluster using az aks create without --service-principles option, after turning on debug mode, it shows that az aks create will create a service principle however fails to do so with the exact same error as above.

**Comment by marcobattaglia** [comment] 2018-03-30 09:06
Same error creating new credential with cloudbreak.

**Comment by vyunev** [comment] 2018-03-30 12:08
Same here, azure-cli (2.0.29)

**Comment by mboersma** [comment] 2018-03-30 15:31
It's a server-side error, since the same version of the CLI began failing on the same commands sometime yesterday afternoon.

**Comment by yugangw-msft** [comment] 2018-03-30 17:12
Fix has been deployed. Please reactivate this issue if you still see it, and please also share the trace using the `--debug` flag

**Closed by yugangw-msft** 2018-03-30 17:12 UTC
Labels: Auth

**Comment by mboersma** [comment] 2018-03-30 17:17
Confirmed: looks like it's fixed now. :+1:

**Comment by A-Malone** [comment] 2018-11-15 17:51
I'm getting the same issue again, in azure-cli 2.0.50. I've included the output with the --debug option below.

<pre>Command arguments: ['ad', 'sp', 'create-for-rbac', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f3dbcb27b70>, <function OutputProducer.on_global_arguments at 0x7f3dbc649158>, <function CLIQuery.on_global_arguments at 0x7f3dbc66cbf8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'servicebus', 'servicefabric', 'signalr', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.014 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.005 seconds.
Loaded module 'appservice' in 0.006 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.010 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.003 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.001 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.003 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.005 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.004 seconds.
Loaded module 'network' in 0.024 seconds.
Loaded module 'policyinsights' in 0.001 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.005 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.006 seconds.
Loaded module 'role' in 0.003 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'servicebus' in 0.004 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.031 seconds.
Loaded module 'vm' in 0.013 seconds.
Loaded all modules in 0.205 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/aidan/.azure/cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f3dbc5f3840>, <function register_ids_argument.<locals>.add_ids_arguments at 0x7f3dbc5ad2f0>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f3db9c207b8>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f3dbc6491e0>, <function CLIQuery.handle_query_parameter at 0x7f3dbc66cc80>, <function register_ids_argument.<locals>.parse_ids_argumentsat 0x7f3dbc5ad378>, <function handler at 0x7f3db9b73ea0>]
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Getting management service client client_type=AuthorizationManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 1806
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://graph.windows.net/'}
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 1806
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://graph.windows.net/'}
msrest.http_logger : Request URL: 'https://graph.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/applications?api-version=1.6'
msrest.http_logger : Request method: 'POST'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '406'
msrest.http_logger :     'User-Agent': 'python/3.6.5 (Linux-4.15.0-1025-azure-x86_64-with-debian-stretch-sid) msrest/0.6.1 cloud-shell/1.0 msrest_azure/0.5.1 azure-graphrbac/0.52.0 Azure-SDK-For-Python AZURECLI/2.0.50 cloud-shell/1.0'
msrest.http_logger : Request body:
msrest.http_logger : {"availableToOtherTenants": false, "displayName": "azure-cli-2018-11-15-17-48-55", "homepage": "https://azure-cli-2018-11-15-17-48-55", "identifierUris": ["http://azure-cli-2018-11-15-17-48-55"], "passwordCredentials": [{"startDate": "2018-11-15T17:48:55.168569Z", "endDate": "2019-11-15T17:48:55.168569Z", "keyId": "f2793513-8360-40a9-b8c2-f0154c25f539", "value": "05cd606a-d4a6-4dda-b322-18f39650af0b"}]}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): graph.windows.net:443
urllib3.connectionpool : https://graph.windows.net:443 "POST /33e01921-4d64-4f8c-a055-5bdaffd5e33d/applications?api-version=1.6 HTTP/1.1" 400 452
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'private'
msrest.http_logger :     'Content-Type': 'application/json; odata=minimalmetadata; charset=utf-8'
msrest.http_logger :     'Server': 'Microsoft-IIS/10.0'
msrest.http_logger :     'ocp-aad-diagnostics-server-name': '/lC86iJ3cwwJGyTWjAKYWDPkB/lyglon9hmrn0nLUXM='
msrest.http_logger :     'request-id': 'fc4b1145-771c-4405-9931-820737ee504a'
msrest.http_logger :     'client-request-id': 'b875e36c-e8fe-11e8-926b-0a580af4a711'
msrest.http_logger :     'x-ms-dirapi-data-contract-version': '1.6'
msrest.http_logger :     'ocp-aad-session-key': 'EWmf8iDlvMtBW3YqEe1uUKQlfK0tI3C38WUVZDujBnZJaKlJjvsV6WIRb9MR4PQ--za2NqVCbQwt643ZDxS2PgQ8jMrsShwaEv5fJZ6aKc7LEMpTme-f2lcGzZJvLBz5.Z2zagICt4fNxVpjsi0jfbV0a1YXe5CZeoqVtHYMuc_8'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Access-Control-Allow-Origin': '*'
msrest.http_logger :     'X-AspNet-Version': '4.0.30319'
msrest.http_logger :     'X-Powered-By': 'ASP.NET'
msrest.http_logger :     'Duration': '905990'
msrest.http_logger :     'Date': 'Thu, 15 Nov 2018 17:48:55 GMT'
msrest.http_logger :     'Content-Length': '452'
msrest.http_logger : Response content:
msrest.http_logger : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"The password should contain least 1 upper\/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application"},"date":"2018-11-15T17:48:55","requestId":"fc4b1145-771c-4405-9931-820737ee504a","values":[{"item":"PropertyName","value":"passwordCredentials"},{"item":"PropertyErrorCode","value":"AppPasswordWeak"}]}}
msrest.exceptions : The password should contain least 1 upper/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
The password should contain least 1 upper/lower case character(s). paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
telemetry.save : Save telemetry record of length 2495 in cache
telemetry.check : Negative: The /home/aidan/.azure/telemetry.txt was modified at 2018-11-15 17:40:42.880553, which in less than 600.000000 s</pre>
