### ISSUE TITLE
Azure ARC Extension - No module named google.auth

### ISSUE THREAD

**Issue by jbinko** [Azure/azure-cli#11997] opened 2020-01-30 22:19 UTC
## Describe the bug

**Command Name**
`az connectedk8s connect`

**Errors:**
```
No module named google.auth
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
connectedk8s/kubernetes/config/__init__.py, ln 19, in <module>
    from .kube_config import (list_kube_config_contexts, load_kube_config,
connectedk8s/kubernetes/config/kube_config.py, ln 28, in <module>
    import google.auth
ImportError: No module named google.auth
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {}`

## Environment Summary
```
Linux-4.15.0-58-generic-x86_64-with-Ubuntu-16.04-xenial
Python 2.7.12
Shell: bash

azure-cli 2.0.80

Extensions:
connectedk8s 0.1.0
k8sconfiguration 0.1.1

```

**Comment by jluk** [comment] 2020-01-31 00:55
@yonzhan can we create an arc specific tag? What do you think @slack?

**Comment by seanmck** [comment] 2020-01-31 01:01
I'd suggest moving it over to the Arc preview repo since it's not actually part of the core CLI yet. I don't have admin rights on that repo, but maybe @slack has the necessary powers.

**Comment by slack** [comment] 2020-01-31 17:06
@jbinko please open this issue against the private preview repo.

@jluk and @yonzhan yes, we should create an Azure Arc for Kubernetes tag.

**Comment by jbinko** [comment] 2020-01-31 21:20
> @jbinko please open this issue against the private preview repo.
> 
> @jluk and @yonzhan yes, we should create an Azure Arc for Kubernetes tag.

@slack - somebody did already: https://github.com/Azure/azure-arc-kubernetes-preview/issues/29

**Comment by yonzhan** [comment] 2020-02-01 02:34
Share we close this one if the issue is already recorded in another repo?

**Comment by seanmck** [comment] 2020-02-12 06:45
Yes. The extension in question is not in this repo yet, so closing.

**Closed by seanmck** 2020-02-12 06:45 UTC
Labels: AKS, Service Attention
