### ISSUE TITLE
"az mysql server create --name olivermysqlserver" allocates a DNS entry olivermysqlserver.mysql.database.azure.com. and will lead to name collision with other Azure clients, therefore az create will fail for common names like sqlserver 

### ISSUE THREAD

**Issue by omichels** [Azure/azure-cli#7109] opened 2018-08-21 11:04 UTC
when creating a SaaS MySQL Server or SQL Server a public DNS entry for the domain mysql.database.azure.com will be allocated. That DNS entry must be unique, therefore common names like sqlserver will clash and the creation will fail.

reproduce:
az mysql server create --resource-group myResourceGroup --name olivermysqlserver  --location westeurope --admin-user myadmin  \
--admin-password nimda0123QWERTUIOP --sku-name GP_Gen4_2 --version 5.7

For each MySQL Server name a public DNS Entry will be created, e.g. olivermysqlserver.mysql.database.azure.com. The creation of the SaaS Service will fail, if the name is already occupied

**Comment by omichels** [comment] 2018-10-19 10:04
any news on this issue from microsoft?

**Comment by tjprescott** [comment] 2018-10-19 17:40
@Suna-MS for comment

**Comment by Suna-MS** [comment] 2018-10-26 08:35
Yes, once a mysql server created, a public DNS Entry will be created, and sql server cannot reuse this server name, which is by design. @QingqingYuan please help to follow, I don't understand the issue clearly.

**Comment by ajlam** [comment] 2019-06-03 22:42
@omichels - the server names must be unique as the underlying provisioning server is shared between the Azure SQL DB, MySQL, PostgreSQL, and MariaDB services. Is there a specific ask for this issue?

**Comment by ajlam** [comment] 2019-06-24 22:02
@omichels - closing this issue for now. Please feel free to re-open.

**Closed by ajlam** 2019-06-24 22:02 UTC
Labels: MySQL, Question, Service Attention

**Comment by bradhead** [comment] 2021-06-15 23:51
For Infrastructure as code, i.e. in a yaml file executing az commands, how do I ensure that the yaml file runs "create only if needed" for deploying a mysql database?  I am looking for similar behaviour as with 'az webapp create ' where no big deal if the web app name already exists.
