### ISSUE TITLE
tar: "no such command" on latest docker image

### ISSUE THREAD

**Issue by amnon-rv** [Azure/azure-cli#29927] opened 2024-09-18 13:07 UTC
### Describe the bug

Trying to execute "tar" on the latest image result in "no such command". tar was available on 2.63.0

### Related command

tar

### Errors

```
$ docker run -it mcr.microsoft.com/azure-cli:latest tar --version
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "tar": executable file not found in $PATH: unknown.
```

### Issue script & Debug output

docker run -it mcr.microsoft.com/azure-cli:latest tar --version

### Expected behavior

I expect tar to succeed. This is a very basic tool.On previous version:
```
$ docker run -it mcr.microsoft.com/azure-cli:2.63.0 tar --version
tar (busybox) 1.36.1
```

### Environment Summary

azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/usr/bin/python3.9'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.9.19 (main, Aug 23 2024, 00:07:48) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment] 2024-09-18 13:07
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2024-09-19 02:13
Duplicate of #29857

**Closed by bebound** 2024-09-19 02:13 UTC
Labels: question, customer-reported, Azure CLI Team
