### ISSUE TITLE
az backup protection backup-now 'ValueError: Item not found. Please provide a valid item_name'

### ISSUE THREAD

**Issue by tameek** [Azure/azure-cli#9135] opened 2019-04-17 19:57 UTC
Attempting to backup my VM, and got a Trackback error:

>> az backup protection backup-now --resource-group XXXXXX --vault-name vault701 --container-name XXXXXX --item-name XXXXXX --retain-until 17-05-2019

The command failed with an unexpected error. Here is the traceback:

Item not found. Please provide a valid item_name.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
ValueError: Item not found. Please provide a valid item_name.

**Comment by tjprescott** [comment] 2019-04-17 20:57
When opening a new issue, please either use `az feedback` or fill out the requested information in the issue template. Copied here for you convenience.

==================

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by pvrk** [comment] 2019-07-30 15:06
@tameek: Can you please provide more information as @tjprescott suggested?

**Comment by metrue** [comment] 2019-09-04 02:25
@pvrk 

Just open a related ticket with detail description. https://github.com/Azure/azure-cli/issues/10409

**Comment by pvrk** [comment] 2019-09-05 17:48
@metrue : I have updated the other incident. Also pasting the same comments here for clarity.
Thanks for the feedback. Now the issue is clear. If you run the az backup item list command with output as table, there will be a column called 'Name'. That should be passed as '--name' in 'backup now'. The value under that column 'Name' in az backup item list table output is actually 'FriendlyName' in the JSON output. Basically, you should pass the value 'FriendlyName' as 'Name'. We wanted users to pass the FriendlyName but as per CLI guidelines the parameter had to be '-Name'. Hope this is clear. This can be clarified with clear documentation and examples. I will start working as soon as I can.

**Comment by yonzhan** [comment] 2020-05-02 13:38
backup

**Comment by pvrk** [comment] 2020-09-24 10:02
Sincere apologies for the delay. We have updated help text and examples first and now we are working on updating documentation.

**Comment by pvrk** [comment] 2020-12-28 06:18
@metrue , @tameek : I have commented on the other [thread](https://github.com/Azure/azure-cli/issues/10409). The container name and item name are not exactly same. Use container list/show commands to get it's name and use backup item list/show command to get the name and pass them both.

**Comment by pvrk** [comment] 2020-12-28 06:19
Closing this thread since the fix is provided. Please feel free to re-open if this doesn't solve the issue.

**Closed by pvrk** 2020-12-28 06:19 UTC
Labels: Documentation, Recovery Services Backup, Service Attention, customer-reported
