### ISSUE TITLE
Why django samples can't deploy to azure if I update the django version?

### ISSUE THREAD

**Issue by zinlingzhi** [Azure/azure-cli#21271] opened 2022-02-13 05:29 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 394, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 239, in request
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1046, in _send_output
  File "http\client.py", line 968, in send
  File "ssl.py", line 1204, in sendall
  File "ssl.py", line 1173, in send
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 532, in increment
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/packages/six.py", line 769, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 394, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 239, in request
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1046, in _send_output
  File "http\client.py", line 968, in send
  File "ssl.py", line 1204, in sendall
  File "ssl.py", line 1173, in send
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 713, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 38, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4094, in webapp_up
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 540, in enable_zip_deploy
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 117, in post
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 61, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --resource-group {} --location {} --plan {} --sku {} --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.0

Extensions:
db-up 0.2.6

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by chrisriu** [comment] 2022-02-14 00:41
Thank you

**Comment by SatishBoddu-MSFT** [comment] 2022-02-15 01:01
Hello @chrisriu 
Is this issue consistent? or was just intermittent?
What was the Django base version which was updated?
Could you please share the `--debug ` log for further analysis?
Did you try any other commands?, like Az Webapp create, etc?

az webapp up --resource-group {} --location {} --plan {} --sku {} --name {} --debug

please sanitize the sensitive info while providing the debug logs!

![image](https://user-images.githubusercontent.com/62923178/153972636-e12d80d0-3070-4411-952a-2a9fcfb3a691.png)

**Comment by chrisriu** [comment] 2022-02-18 02:46
This is working now but when I added the django updated version. it is not working.
So I am using python3.7.9 version to match azure.

If anyone knows how to use 3.9 python in Azure, please let me know.

**Comment by panchagnula** [comment] 2022-02-25 00:51
@StrawnSC is this (Python 3.9 failing to deploy) with up due to the fact the runtime version was not updated on CLI (Stacks API)?

@chrisriu can you share the samples of the latest version you are trying to use here? Thanks!

**Comment by StrawnSC** [comment] 2022-02-25 00:57
> @StrawnSC is this (Python 3.9 failing to deploy) with up due to the fact the runtime version was not updated on CLI (Stacks API)?
> 
> @chrisriu can you share the samples of the latest version you are trying to use here? Thanks!

I don't believe this error is caused by the runtime stacks update, but I will look more into it

**Comment by panchagnula** [comment] 2022-02-25 00:59
@StrawnSC not caused by - but checking the fact the hardcoded support stacks didn't have Python 3.9 this was failing?

**Comment by StrawnSC** [comment] 2022-02-25 01:06
@panchagnula version `2.33.0` would have included this change: https://github.com/Azure/azure-cli/pull/20770, so it should have python 3.9 support. Also if the runtime passed in wasn't in one of the hardcoded files, it would return an error like so: 

`Linux runtime 'XXX' is not supported. Please invoke 'az webapp list-runtimes --linux' to cross check`

**Comment by panchagnula** [comment] 2022-02-25 04:37
> @panchagnula version `2.33.0` would have included this change: #20770, so it should have python 3.9 support. Also if the runtime passed in wasn't in one of the hardcoded files, it would return an error like so:
> 
> `Linux runtime 'XXX' is not supported. Please invoke 'az webapp list-runtimes --linux' to cross check`

I was checking incase up was surfacing the right error, since Python 3.9 is supported by platform & looks like user downgraded to a different version version to unblock themselves. If we get a repro we should share with linux team as runtime issue - if not then this is not a CLI specific issue & we can close this.

**Comment by navba-MSFT** [comment] 2022-04-19 07:21
Removing the CXP attention as the Service team is working on this.

**Comment by seligj95** [comment] 2023-03-13 19:28
Closing since it looks like this was resolved. Please re-open if this is still an issue.

**Closed by seligj95** 2023-03-13 19:28 UTC
Labels: Web Apps, Service Attention, customer-reported, needs-team-attention, app-service-webapp-up
