### ISSUE TITLE
Azure CLI -  webapp: Keyvault and Azure App Services certificate commands

### ISSUE THREAD

**Issue by chadcarlton** [Azure/azure-cli#10806] opened 2019-10-10 18:48 UTC
I'm trying to use Azure CLI to configure an Azure app service SSL certificates that are stored in an Azure KeyVault.  I'm not sure if I'm not understanding something, or if the Azure CLI commands are missing functionality/functionality isn't performing correctly to accomplish what 
I'm trying to do.

I chained these three commands together, but am not able to get it to work.

```
#download the cert
az keyvault secret download --file $fileName --vault-name $vaultName --name $certName;

#upload the cert and get the thumbprint
$thumbprint=az webapp config ssl upload --certificate-file $fileName --certificate-password $pfxPassword --name $site_name --resource-group $ResourceGroupName --query thumbprint --output tsv

#bind the uploaded cert to the app service.
az webapp config ssl bind --certificate-thumbprint $thumbprint --ssl-type SNI --name $site_name --resource-group $ResourceGroupName

```

I can confirm the first command is downloading the cert. Though it was a surprise that the cert password was removed.

Is there a way to get the cert file without stripping out the password?

It looks like the second command (upload and get the thumbprint) REQUIRES a password.

Is this a bug? Are these commands not meant to be used in conjunction with each other? I feel like I must be missing something

**Comment by haroldrandom** [comment] 2019-10-11 07:53
Hi, @chadcarlton , for your three questions. We will look into them.

Before that, please provide some extra information: 

1. The **secret** you downloaded, is it a plain text file or a certification file like *.crt / *.cer,  *.pem, * that can be operated by OpenSSL?
2. How do your create your cert file? By command line on your computer and then upload to Azure KeyVault, or auto generated through Azure KeyVault Portal? ( In my knowledge, seems that there is no way to create a password-guarded certificates... )

FYI, here is the [doc ](https://docs.microsoft.com/en-us/azure/key-vault/tutorial-net-create-vault-azure-web-app)about how to create a Azure Web App with KeyVault. And here is the [doc](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-ssl) about how to bind SSL certificate to your Azure Web App.

**Comment by chadcarlton** [comment] 2019-10-15 14:20
I was not involved in initially creating the certs, or the webapp. I've been asked to script a repeatable process on recreating them in a different resource group (a start to look into CI/CD).  

I believe the Certs were created using a non involved separate IIS CSR which was sent to entrust, then imported into a local PC and exported to a PFX (with password) which was then uploaded into the webapp via the portal.

The same PFX was given to me (along with the password), and I uploaded it to keyvault.

The issue that I am encountering is that I don't see a way to connect these commands together.

**Are these statements correct?**

1. With Azure CLI, I have to download the cert as a file from Keyvault, and then upload it?
2. With Azure CLI, It looks like Keyvault strips out the password on the PFX when it is downloaded
3. The Azure CLI command `az webapp config ssl upload` command requires a password, and null is not allowed

**Comment by panchagnula** [comment] 2019-10-16 06:29
Sorry we don't have a first class support for this using CLI & PowerShell, for now portal is the way to support this.

**Comment by chadcarlton** [comment] 2019-10-16 13:27
Can this be added to the backlog? I'd really like to use Azure CLI to create the app service, get the cert from keyvault, and bind it.  (It would even be better if the new reference capabilities could be used: https://azure.microsoft.com/en-us/updates/general-availability-of-key-vault-references-in-app-service-and-azure-functions/ )

**Comment by panchagnula** [comment] 2019-11-15 06:13
Duplicate of #5004

**Closed by panchagnula** 2019-11-15 06:13 UTC
Labels: KeyVault, Web Apps
