### ISSUE TITLE
Az boot diagnostics cli is broken: "TypeError: startswith first arg must be str, unicode, or tuple, not NoneType"

### ISSUE THREAD

**Issue by archmangler** [Azure/azure-cli#11447] opened 2019-12-02 05:01 UTC
When trying to get vm boot diagnostics with the following command:

```
 az vm boot-diagnostics get-boot-log --ids <vm resource id>

or

 az vm boot-diagnostics get-boot-log --name <vm-name> --resource-group <resource group>

```

, the cli breaks with the following error:

 "TypeError: startswith first arg must be str, unicode, or tuple, not NoneType"

```
azure-cli                         2.0.72

command-modules-nspkg               2.0.3
core                              2.0.72
nspkg                              3.0.4
telemetry                          1.0.3
```

**Describe the bug**

When trying to get vm boot diagnostics with "", the cli breaks with the following error:

```
++ az vm boot-diagnostics get-boot-log --ids /subscriptions/xxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: startswith first arg must be str, unicode, or tuple, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
TypeError: startswith first arg must be str, unicode, or tuple, not NoneType
WARNING: 
To open an issue, please run: 'az feedback'
```

**To Reproduce**

Run the following command:

```

 az vm boot-diagnostics get-boot-log --ids <vm resource id>

or

 az vm boot-diagnostics get-boot-log --name <vm-name> --resource-group <resource group>

```

**Expected behavior**

boot disagnostic logs should be returned

**Environment summary**

```
azure-cli                         2.0.72
command-modules-nspkg               2.0.3
core                              2.0.72
nspkg                              3.0.4
telemetry                          1.0.3
```

**Additional context**

**Comment by haroldrandom** [comment] 2019-12-03 02:04
@qwordy Please take a look

**Comment by archmangler** [comment] 2019-12-03 04:12
Additional information:

- Test az cli with python 3.6 as well, the behaviour is the same.

**Comment by yungezz** [comment] 2020-02-24 10:35
duplicate with #11404

**Comment by qwordy** [comment] 2020-02-27 08:39
When I run `az vm boot-diagnostics get-boot-log -g fytest2 -n vm1`
I get result of
```
2020-02-24T08:47:46.163986Z INFO ExtHandler Certificate with thumbprint 02DD85D3C8C274ACADFFD0B1499B3E5CEFD17A97 has no matching private key.
2020-02-24T08:47:46.285807Z INFO ExtHandler ProcessGoalState completed [incarnation 2; 204 ms]
2020/02/24 08:51:24.643966 INFO Agent WALinuxAgent-2.2.46 launched with command 'python -u bin/WALinuxAgent-2.2.46-py2.7.egg -run-exthandlers' is successfully running
2020/02/24 08:51:24.656786 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.46 launched with command 'python -u bin/WALinuxAgent-2.2.46-py2.7.egg -run-exthandlers' is successfully running, duration=0
```
I cannot reproduce the issue. highly suspect it's caused by environment difference. Python 2 is not supported by Azure CLI any more. Could you please try again? Close the issue for now, feel free to create new issue if you met the error again.

**Closed by qwordy** 2020-02-27 08:39 UTC
Labels: Compute - VM, OKR3.2 Candidate
