### ISSUE TITLE
Azure login repeatedly asks for login information after a "read" command in bash script on WSL

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-cli#6691] opened 2018-06-29 19:25 UTC
Using a bash script in WSL Ubuntu subsystem to automatically perform Azure login using service principal.

**To Reproduce**
Execute this sh script in Ubuntu WSL.

#!/bin/bash
az login --service-principal --username $servicePrincipalAppId --password $servicePrincipalPassword --tenant $servicePrincipalTenantId
read subscriptionId
az account set --subscription $subscriptionId 
read key
az group create -n myResourceGroup -l westus2

The az group command again asks for login information despite already logging in with service principal. The read commands in between seem to mess up the authentication details (suspect)

**Environment summary**
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

az cli version: **azure-cli (2.0.38)**

**Comment by yugangw-msft** [comment] 2018-06-29 20:20
Are you able to reproduce the same issue by running the 3 command manually?
```bash
   az login ...
   az account set ...
   az group create ...
```
Particularly, you can cross check after `az login` whether you see the `$subscriptionId` shows up in the output.

**Comment by priyaananthasankar** [comment] 2018-07-02 21:03
Manually it works, but when using it in a bash script we might want to read in the subscription id, and when using "read" command in ubuntu WSL, the azure creds are reset. Probably Azure should not be using environment variables that the read command can mess with. This issue is sneaky and requires either a documentation write up or a fix. This was quite hard to find.

**Comment by yugangw-msft** [comment] 2018-07-05 16:44
What you got from the stdout & stderr when run the bash script?

**Comment by priyaananthasankar** [comment] 2018-07-06 18:35
stdout and stderr did not say anything, this fails silently. Just try the following inside a bash script in ubuntu WSL and you can reproduce the bug:

az login --service-principal --username $servicePrincipalAppId --password $servicePrincipalPassword --tenant $servicePrincipalTenantId

read $subscriptionId

az account set --subscription $subscriptionId 

Once you perform "read" command, the azure login from previous step is lost, when doing az account set, it asks for relogin again, or any other az command.

"read" from bash script should not be able to mess around with az login variables.

**Comment by yugangw-msft** [comment] 2018-07-08 05:32
The `az` commands must have outputted something; otherwise it means they didn't execute. Please do provide the output from `az login` and `az account set` for us to help you out

**Comment by priyaananthasankar** [comment] 2018-07-09 20:53
I have provided the exact bash commands that have led to this issue. Can you please execute a bash script with my instructions? The az login and az account set seemed to behave normally. Please try the bash script on an ubuntu wsl.

**Comment by yugangw-msft** [comment] 2018-07-09 21:53
Works for me. A side note, you probably should improve the script to output a few traces, and add a prompt for `read` to help the self-diagnosis. Also you recent script has a bug at `read $subscriptionId`, that the `$` should not be there.
![image](https://user-images.githubusercontent.com/6014209/42477904-bdd08c18-8387-11e8-957a-522877395502.png)

**Comment by yugangw-msft** [comment] 2018-07-09 21:55
No repro'd on WSL. Unlikely caused by CLI. Closing.

**Closed by yugangw-msft** 2018-07-09 21:55 UTC
