### ISSUE TITLE
Cannot create new Kubernetes cluster via Cloud Shell.

### ISSUE THREAD

**Issue by kotx** [Azure/azure-cli#12872] opened 2020-04-03 19:15 UTC
## Describe the bug
Tried to create a new Kubernetes cluster via the Cloud Shell from this article: https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/create-cluster-cloud-shell
**Command Name**
`az aks create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -g {} -n {} --location {} --generate-ssh-keys`

## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```
## Additional Context
Using Azure Cloud Shell from Windows Terminal.

**Comment by yonzhan** [comment] 2020-04-03 23:33
aks

**Comment by jluk** [comment] 2020-04-06 15:42
@yonzhan can you please tag the cloud shell team for this issue? this looks like it's caused by the cloud shell managed identity endpoint.

**Comment by jiasli** [comment] 2020-04-07 01:58
Duplicate of #11749. This is a Cloud Shell issue. I can't repro on my Cloud Shell:

```
leo@Azure:~$ az aks create -g myrg -n myaks --location eastus --generate-ssh-keys
SSH key files '/home/leo/.ssh/id_rsa' and '/home/leo/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud Shell without an attached file share, back up your keys to a safe location
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
...
```

**Closed** 2020-06-22 03:37 UTC
Labels: AKS, Cloud Shell, Service Attention
