### ISSUE TITLE
Unsupported API version being used by az keyvault in AzureUSGovernment

### ISSUE THREAD

**Issue by sdubeymsft** [Azure/azure-cli#18483] opened 2021-06-14 19:34 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Unsupported API version being used by az keyvault in AzureUSGovernment

(NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2021-04-01-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01'. The supported locations are 'usgovvirginia, usgoviowa, usdodcentral, usdodeast, usgovtexas, usgovarizona'.

**To Reproduce**
az cloud set AzureUSGovernment
az login
az keyvault create

**Expected behavior**
Key Vault should be created successfully.

**Environment summary**
Azure CloudShell for Bash

**Additional context**
>

**Comment by yonzhan** [comment] 2021-06-14 22:19
keyvault

**Comment by evelyn-ys** [comment] 2021-06-16 02:38
Duplicate of #18006 
Thanks for reporting! You can move forward for newest updates under #18006

**Comment by evelyn-ys** [comment] 2021-06-16 02:39
Duplicate of #18006

**Closed** 2021-06-16 15:31 UTC
Labels: KeyVault, Service Attention
