### ISSUE TITLE
Homebrew and azure-cli 2.50.0

### ISSUE THREAD

**Issue by dinowang** [Azure/azure-cli#27209] opened 2023-08-21 08:27 UTC
### Describe the bug

Latest azureli 2.51.0 can not upgrade by homebrew.

I suppose because of homebrew formula path changed
https://github.com/Homebrew/homebrew-core/commit/c03bfb472ba1465eceeeb9b3f43cf5683b28c974

From
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/azure-cli.rb
to
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/a/azure-cli.rb

### Related command

brew upgrade

### Errors

No error message (upgrade not found)

### Issue script & Debug output

➜ brew upgrade azure-cli --debug
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.1.5\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --fail --progress-bar --remote-time --output /Users/dinowang/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/dinowang/Library/Caches/Homebrew/api/formula.jws.json --compressed --speed-limit 100 --speed-time 5 --progress-bar https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################################################################### 100.0%
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading azure-cli from API
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.1.5\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --fail --progress-bar --remote-time --output /Users/dinowang/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/dinowang/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 --progress-bar https://formulae.brew.sh/api/cask.jws.json
############################################################################################################################################################################################################### 100.0%
Warning: azure-cli 2.50.0_1 already installed

### Expected behavior

Upgrade azure-cli successful

### Environment Summary

azure-cli 2.50.0

**Comment by yonzhan** [comment] 2023-08-21 08:28
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2023-08-21 13:25
Duplicate of https://github.com/Azure/azure-cli/issues/27047

**Closed by bebound** 2023-08-21 13:25 UTC
Labels: question, Azure CLI Team, Auto-Resolve
