### ISSUE TITLE
az vm create --tags: docs confusing

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#578] opened 2016-08-01 18:55 UTC
`az vm create --help` says:

```
    --tags                        : Multiple semicolon separated tags in 'key[=value]' format. Omit
                                    value to clear tags.
```

What does it mean clearing tags? I don't have any tags yet as I don't have the VM? It sounds very confusing.

**Comment by yugangw-msft** [comment] 2016-08-01 20:32
Dupe of #536. The tag's help should be finer tuned

**Closed by yugangw-msft** 2016-08-01 20:32 UTC
