### ISSUE TITLE
Please Bundle pip-system-certs with the installer

### ISSUE THREAD

**Issue by EmperorArthur** [Azure/azure-cli#24628] opened 2022-11-11 16:31 UTC
**Related command**
`az extension add ...`

All commands dealing with `pip` on Windows.

**Is your feature request related to a problem? Please describe.**

**Yes**
On Windows, in a corporate environment I can not install extensions easily since the corporate firewall's SSL certificate is not recognized by `pip`.  The certificate is in the Windows Certificate Store, but that is not used by `pip`

**Describe the solution you'd like**

Please add the https://pypi.org/project/pip-system-certs/ project to the CLI installer for windows.

**Describe alternatives you've considered**

1: Patching pip directly as part of the installer build process
2: Adding significant documentation and warnings to the installer about additional steps regarding environment variables corporate users must do to install and use this software.

**Additional context**

This affects everyone who is behind a transparent corporate firewall.

**Comment by yonzhan** [comment] 2022-11-12 00:58
@jiasli for awareness

**Comment by jiasli** [comment] 2024-12-19 05:43
Duplicate of https://github.com/Azure/azure-cli/issues/19305

**Closed by jiasli** 2024-12-19 05:43 UTC
Labels: customer-reported, Installation, feature-request, Auto-Assign, Azure CLI Team
