### ISSUE TITLE
Extensions break without HOME environment variable

### ISSUE THREAD

**Issue by algattik** [Azure/azure-cli#11379] opened 2019-11-25 10:53 UTC
## Describe the bug

When running without a set HOME environment variable (e.g in an Azure DevOps agent), the behaviour of `az extension add -n azure-cli-ml` and `az ml` in inconsistent. `az extension add -n azure-cli-ml` still manages to install the extension in the home directory, but `az ml` can't find it.

This issue is not easy to debug for the user!

Strangely, AZURE_EXTENSION_DIR, when set, is honoured by "az extension add" but not by "az ml".

**Command Name**
`az ml`

**Errors:**
```
az: 'ml' is not in the 'az' command group. See 'az --help'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `unset HOME` (to simulate the environment of Azure DevOps agents)
- `az extension add -n azure-cli-ml` (succeeds)
- `az ml` (fails - UNEXPECTED)
```
az: 'ml' is not in the 'az' command group. See 'az --help'.
```
- `AZURE_EXTENSION_DIR=. az ml`  (fails - UNEXPECTED)
```
az: 'ml' is not in the 'az' command group. See 'az --help'.
```
- `HOME=. az ml` (succeeds - expected)
```
az ml: error: the following arguments are required: _subcommand
usage: az ml [-h]
             {computetarget,service,model,dataset,datastore,environment,experiment,folder,pipeline,run,workspace}
```

with `--debug`:
```
  File "/root/.azure/cliextensions/azure-cli-ml/azext_ml/__init__.py", line 29, in <module>
    load_common_help()
  File "/root/.azure/cliextensions/azure-cli-ml/azext_ml/__init__.py", line 24, in load_common_help
    from azureml._cli.aml_cli import load_azurecli_help
  File "/root/.azure/cliextensions/azure-cli-ml/azureml/_cli/aml_cli.py", line 11, in <module>
    from azureml._cli import abstract_subgroup
  File "/root/.azure/cliextensions/azure-cli-ml/azureml/_cli/abstract_subgroup.py", line 12, in <module>
    from azureml._cli.cli_command import CliCommand
  File "/root/.azure/cliextensions/azure-cli-ml/azureml/_cli/cli_command.py", line 8, in <module>
    from azureml._base_sdk_common.common import set_correlation_id
  File "/root/.azure/cliextensions/azure-cli-ml/azureml/_base_sdk_common/common.py", line 93, in <module>
    USER_PATH = os.path.join(os.getenv('HOME'), '.config')
  File "/opt/az/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Expected Behavior

`az ml` should work. If this is not possible, then at least the `az extension add` command should fail with a clear error message that HOME is not set.

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76
azure-cli-ml 1.0.74

Extensions:
azure-cli-ml 1.0.74

```

**Comment by haroldrandom** [comment] 2019-11-26 06:43
Why `unset HOME` ? 
azure-cli put extensions installed by `az extension add` on a certain dir which based on $HOME

**Comment by haroldrandom** [comment] 2019-11-26 07:44
Thanks for the feedback, we will look into it soon.

**Comment by algattik** [comment] 2019-11-27 07:39
It would be useful to have clear instructions on how to pre-provision extensions, for example when spinning Azure DevOps build agents.

**Comment by haroldrandom** [comment] 2020-01-03 14:56
Met the same problem in [build](https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/223676/logs/31) 

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.9/x64/bin/azdev", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/azdev/__main__.py", line 40, in main
    config_dir=get_azdev_config_dir())
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/azdev/utilities/config.py", line 24, in get_azdev_config_dir
    _, env_name = os.path.splitdrive(get_env_path())
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/posixpath.py", line 138, in splitdrive
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Intuitively, it's a bug that caused by azdev.

As a workaround, you could use a virtual Python environment to make it work like what CI does now.

I will fix it with the latest azdev release.

**Comment by haroldrandom** [comment] 2020-02-22 08:35
Sorry. It's not an extension of azdev. But share the common behavior when HOME is unset.

**Comment by haroldrandom** [comment] 2020-02-22 09:28
azure-cli put configuraiton files in ~/.azure by default. Which is set via:
https://github.com/Azure/azure-cli/blob/13eff82d94b9f59f8206f0424b5bbb0c18055522/src/azure-cli-core/azure/cli/core/_environment.py#L7-L9

The triky part is here, it use tilde `~` instead of `HOME` environment variable.

According to the doc from GNU [3.5.2 Tilde Expansion](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html#Tilde-Expansion)

>  1.  If a word begins with an unquoted tilde character (‘~’), all of the characters up to the first unquoted slash (or all characters, if there is no unquoted slash) are considered a tilde-prefix. 
> 2.  If none of the characters in the tilde-prefix are quoted, the characters in the tilde-prefix following the tilde are treated as a possible login name. 
> 3.  If this login name is the null string, the tilde is replaced with the value of the HOME shell variable. 
> 4.  If HOME is unset, the home directory of the user executing the shell is substituted instead. 
> 5.  Otherwise, the tilde-prefix is replaced with the home directory associated with the specified login name.

To conclude, `~` still have meaningful value even when `HOME` is unset. Which means `~/.azure/` is still a value path.

`azure-cli-ml` use the `HOME` environment variable so the behavior is inconsisnt with `az extension add -n azure-cli-ml`

**Comment by DavidParks8** [comment] 2020-04-07 18:02
I can confirm this behavior is an issue for much more than just ml. When HOME is not set, this is the output of the help text of az:

```
Group
    az

Subgroups:
    account                      : Manage Azure subscription information.
    ad                           : Manage Azure Active Directory Graph entities needed for Role
                                   Based Access Control.
    appconfig                    : Manage App Configurations.
    appservice                   : Manage App Service plans.
    cache              [Preview] : Commands to manage CLI objects cached using the
                                   `--defer` argument.
    cloud                        : Manage registered Azure clouds.
    deployment                   : Manage Azure Resource Manager template deployment at subscription
                                   scope.
    disk                         : Manage Azure Managed Disks.
    eventhubs                    : Manage Azure Event Hubs namespaces, eventhubs, consumergroups and
                                   geo recovery configurations - Alias.
    extension                    : Manage and update CLI extensions.
    functionapp                  : Manage function apps. To install the Azure Functions Core tools
                                   see https://github.com/Azure/azure-functions-core-tools.
    group                        : Manage resource groups and template deployments.
    hdinsight                    : Manage HDInsight resources.
    image                        : Manage custom virtual machine images.
    iot                          : Manage Internet of Things (IoT) assets.
    keyvault                     : Manage KeyVault keys, secrets, and certificates.
    local-context [Experimental] : Manage Local Context.
    lock                         : Manage Azure locks.
    managedapp                   : Manage template solutions provided and maintained by Independent
                                   Software Vendors (ISVs).
    network                      : Manage Azure Network resources.
    policy                       : Manage resource policies.
    provider                     : Manage resource providers.
    resource                     : Manage Azure resources.
    role                         : Manage user roles for access control with Azure Active Directory
                                   and service principals.
    security           [Preview] : Manage your security posture with Azure Security
                                   Center.
    snapshot                     : Manage point-in-time copies of managed disks, native blobs, or
                                   other snapshots.
    storage                      : Manage Azure Cloud Storage resources.
    tag                          : Manage resource tags.
    vm                           : Manage Linux or Windows virtual machines.
    vmss                         : Manage groupings of virtual machines in an Azure Virtual Machine
                                   Scale Set (VMSS).
    webapp                       : Manage web apps.

Commands:
    configure                    : Manage Azure CLI configuration. This command is interactive.
    feedback                     : Send feedback to the Azure CLI Team!
    find                         : I'm an AI robot, my advice is based on our Azure documentation as
                                   well as the usage patterns of Azure CLI and Azure ARM users.
                                   Using me improves Azure products and documentation.
    interactive        [Preview] : Start interactive mode. Installs the Interactive
                                   extension if not installed already.
    login                        : Log in to Azure.
    logout                       : Log out to remove access to Azure subscriptions.
    rest                         : Invoke a custom request.
    version            [Preview] : Show the versions of Azure CLI modules and extensions
                                   in JSON format by default or format configured by --output.
```

Notice how a bunch of the subgroups are missing.

**Comment by DavidParks8** [comment] 2020-04-07 18:44
The issue also occurs when running as root. In such a case, HOME is set to /root in ubuntu 16.04 LTS. Setting HOME=. seems to cause all the subgroups to be resolved again.

**Comment by DavidParks8** [comment] 2020-04-07 18:53
@haroldrandom considering the broad scope of this issue across many services, do you still think this should not be fixed centrally?

**Comment by haroldrandom** [comment] 2020-04-08 08:11
@DavidParks8 Thanks for the remind, I will think about how to deal with it in CLI.

**Comment by haroldrandom** [comment] 2020-05-07 07:35
@DavidParks8 Could you give a list of the missing command groups?

**Comment by lostmygithubaccount** [comment] 2020-11-05 22:25
@algattik are you still facing this issue?

**Comment by v-strudm-msft** [comment] 2021-04-15 19:50
Since there hasn't been a response to this issue in the last several months, we assume it was resolved and will close it. Should there still be a question, please open a new issue and we will respond on a timely basis. Thank you.

**Closed by v-strudm-msft** 2021-04-15 19:50 UTC
Labels: Extensions, Infrastructure, ML-MLOps, Machine Learning, Service Attention
