### ISSUE TITLE
az group deployment create fails to access template URI from AZ Storage via SAS Token

### ISSUE THREAD

**Issue by dtissen** [Azure/azure-cli#5676] opened 2018-02-27 10:26 UTC
Absolutly strange:

I try to deploy a template from a file stored in azure storage. 
The File Link includes the SAS Token to access the File. It works if i try it in my browser. 

When passing the uri to the az deployment command i got this output:

root@DavidTissen-PC:/mnt/c# az group deployment create -g test02 --template-uri https://test02std.file.core.cloudapi.de/backup/2018-02-26.15-02-51.Configuration.test02.Backup.abc980ec-1e7c-4d18-bc67-771edc3f13723319568286514842231.json?se=2018-02-28T10%3A52%3A37Z&sp=r&spr=https&sv=2017-07-29&sr=s&sig=[REMOVED] --debug
[1] 954
[2] 955
[3] 956
[4] 957
[5] 958
--debug: command not found
[2]   Done                    sp=r
[3]   Done                    spr=https
[4]   Done                    sv=2017-07-29
[5]+  Done                    sr=s
[2]   Done                    sp=r
[3]   Done                    spr=https
[4]   Done                    sv=2017-07-29
[5]+  Done                    sr=s
root@DavidTissen-PC:/mnt/c# HTTP Error 400: The value for one of the HTTP headers is not in the correct format.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 304, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 168, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 348, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 623, in deploy_arm_template
    deployment_name, parameters, mode, no_wait=no_wait)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 230, in _deploy_arm_template_core
    template_obj = shell_safe_json_parse(_urlretrieve(template_uri).decode('utf-8'), preserve_order=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 215, in _urlretrieve
    req = urlopen(url, context=_ssl_context())
  File "/opt/az/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/az/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/az/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/az/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/az/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/az/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: The value for one of the HTTP headers is not in the correct format.

[1]+  Exit 1                  az group deployment create -g test02 --template-uri https://test02std.file.core.cloudapi.de/backup/2018-02-26.15-02-51.Configuration.test02.Backup.abc980ec-1e7c-4d18-bc67-771edc3f13723319568286514842231.json?se=2018-02-28T10%3A52%3A37Z
---

### Environment summary
azure-cli (2.0.27)

acr (2.0.21)
acs (2.0.26)
advisor (0.1.2)
appservice (0.1.26)
backup (1.0.6)
batch (3.1.10)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.1)
container (0.1.18)
core (2.0.27)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.10)
extension (0.0.9)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.16)
iot (0.1.17)
keyvault (2.0.18)
lab (0.0.17)
monitor (0.1.2)
network (2.0.23)
nspkg (3.0.1)
profile (2.0.19)
rdbms (0.0.12)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.23)
role (2.0.19)
servicefabric (0.0.10)
sql (2.0.21)
storage (2.0.25)
vm (2.0.26)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Feb  9 2018, 03:55:42)
[GCC 4.7.2]

Legal docs and information: aka.ms/AzureCliLegal

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

what went wrong?

**Comment by yugangw-msft** [comment] 2019-03-07 23:24
The problem is the sas token contains shell special characters and you need to wrap them with quotes.
I was able to verify that after quoted the url, all are working. Hence I am closing this issue.

**Closed by yugangw-msft** 2019-03-07 23:24 UTC
Labels: Resource Manager-cli
