### ISSUE TITLE
az vm list-usage table format eliminates "Name" & "Unit" columns. 

### ISSUE THREAD

**Issue by mkiernan** [Azure/azure-cli#2047] opened 2017-02-12 21:47 UTC
cli 2.0 shows less useful output than cli 1.0 when defaulting to table format: 

$ az vm list-usage --location westeurope
  CurrentValue    Limit
--------------  -------
             1     2000
           100      264
            10    10000
             1     2000
            72      100
             1      100
             2      100
             1      100
                    164
            24       24
                    100
                    100
                    100
                    100
                    100
                    100
                    100
                     48
                    100
                    100

Whereas the old format showed more useful output with the Name & Unit fields: 

$ azure vm list-usage --location westeurope
info:    Executing command vm list-usage
data:    Name                          Unit   CurrentValue  Limit
data:    ----------------------------  -----  ------------  -----
data:    Availability Sets             Count  1             2000
data:    Total Regional Cores          Count  100           264
data:    Virtual Machines              Count  10            10000
data:    Virtual Machine Scale Sets    Count  1             2000
data:    Standard A8-A11 Family Cores  Count  72            100
data:    Standard DSv2 Family Cores    Count  1             100
data:    Standard A0-A7 Family Cores   Count  2             100
data:    Standard Dv2 Family Cores     Count  1             100
data:    Standard H Family Cores       Count  0             164
data:    Standard NV Family Cores      Count  24            24
data:    Basic A Family Cores          Count  0             100
data:    Standard D Family Cores       Count  0             100
data:    Standard G Family Cores       Count  0             100
data:    Standard DS Family Cores      Count  0             100
data:    Standard GS Family Cores      Count  0             100
data:    Standard F Family Cores       Count  0             100
data:    Standard FS Family Cores      Count  0             100
data:    Standard NC Family Cores      Count  0             48
data:    Standard Av2 Family Cores     Count  0             100
data:    Standard LS Family Cores      Count  0             100
info:    vm list-usage command OK

**Comment by derekbekoe** [comment] 2017-02-12 22:50
Hi @mkiernan this looks like a dupe of https://github.com/Azure/azure-cli/issues/2019

**Closed by derekbekoe** 2017-02-12 22:50 UTC
