### ISSUE TITLE
Getting Error AADSTS50005

### ISSUE THREAD

**Issue by harjitdotsingh** [Azure/azure-cli#25870] opened 2023-03-17 12:26 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

 I do az login --use-device-code  in the AZ CLI in to a sub I'm owner of. After I log in ,I try to run the command az ad sp create-rbac  in CLI and I get this error

AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
Trace ID: 738cdc39-a1f2-493b-9d07-b0ae3f215d00
Correlation ID: 23fefbb3-2cde-4e63-8598-90f13e0ab14e
Timestamp: 2023-03-17 12:23:27Z

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment] 2023-03-17 23:12
@jiasli for awareness

**Comment by jiasli** [comment] 2023-03-20 02:37
Duplicate of #16401

**Closed** 2023-03-20 02:37 UTC
Labels: Account, question, Graph, Auto-Assign, Azure CLI Team

**Comment by harjitdotsingh** [comment] 2023-03-20 16:23
This was done from a Mac using CLI.
