### ISSUE TITLE
Azure CLI v2.37.0 breaks pipeline CLI task with "az role assignment create" command

### ISSUE THREAD

**Issue by dndao** [Azure/azure-cli#22750] opened 2022-06-07 00:23 UTC
The below task produces three:
`WARNING: This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
`

```
- task: AzureCLI@1
  displayName: 'Set RBAC Permissions for Web App to Resources'
  inputs:
    azureSubscription: ${{ parameters.subscription }}
    scriptLocation: inlineScript
    failOnStandardError: true
    inlineScript: |

      # Keyvault
      kvName=$(az resource show --ids ${{ parameters.keyVaultResourceId }} --query name --output tsv)
      az keyvault set-policy --name $kvName --object-id $(webapp_principalId) --secret-permissions get

      # Edge Storage Account
      az role assignment create \
        --role "Storage Blob Data Contributor" \
        --assignee-object-id $(webapp_principalId) \
        --assignee-principal-type ServicePrincipal \
        --scope ${{ parameters.storageEdgeResourceId }}

      # Bunker Storage Account
      az role assignment create \
        --role "Storage Blob Data Contributor" \
        --assignee-object-id $(webapp_principalId) \
        --assignee-principal-type ServicePrincipal \
        --scope ${{ parameters.storageBnkrResourceId }}

      # App Configuration
      az role assignment create \
        --role "App Configuration Data Reader" \
        --assignee-object-id $(webapp_principalId) \
        --assignee-principal-type ServicePrincipal \
        --scope ${{ parameters.appConfigurationResourceId }}
```

If the "failOnStandardError" is set to "true" then this step will fail with this error:
`##[error]Script failed with error: Error: The process '/usr/bin/bash' failed because one or more lines were written to the STDERR stream
`

**Comment by jiasli** [comment] 2022-06-07 01:06
Duplicate of #21683

**Closed** 2022-06-07 01:09 UTC
Labels: KeyVault, Graph, RBAC, ARM, customer-reported, Auto-Assign
