### ISSUE TITLE
az account list-locations Should Return Availability Zones

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/azure-cli#21579] opened 2022-03-10 09:49 UTC
The `az account list-locations` command should also return a list of availability zones supported by the location.

**Comment by yonzhan** [comment] 2022-03-10 12:06
@jiasli for awareness

**Comment by jiasli** [comment] 2022-03-11 01:49
Duplicate of https://github.com/Azure/azure-cli/issues/10421

**Closed by jiasli** 2022-03-11 01:49 UTC
Labels: Account, customer-reported, Auto-Assign
