### ISSUE TITLE
UnexpectedError: The command failed with an unexpected error. Here is the traceback: list index out of range

### ISSUE THREAD

**Issue by ajforu74** [Azure/azure-cli#15603] opened 2020-10-21 20:46 UTC
## Describe the bug

**Command Name**
`az acr run`

**Errors:**
```
list index out of range
Traceback (most recent call last):
Temp\pip-unpacked-wheel-tuw8_17y\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 579, in execute
Temp\pip-unpacked-wheel-tuw8_17y\knack\parser.py, ln 262, in parse_args
argparse.py, ln 1734, in parse_args
azure\cli\core\parser.py, ln 304, in parse_known_args
argparse.py, ln 1766, in parse_known_args
argparse.py, ln 1954, in _parse_known_args
argparse.py, ln 1931, in consume_positionals
argparse.py, ln 1840, in take_action
argparse.py, ln 1137, in __call__
azure\cli\core\parser.py, ln 304, in parse_known_args
...
argparse.py, ln 1137, in __call__
azure\cli\core\parser.py, ln 304, in parse_known_args
argparse.py, ln 1766, in parse_known_args
argparse.py, ln 2001, in _parse_known_args
azure\cli\core\parser.py, ln 167, in error
azure\cli\core\command_recommender.py, ln 61, in __init__
azure\cli\core\command_recommender.py, ln 244, in _normalize_parameters
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr run --anandregistry`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.12.1

Extensions:
logic 0.1.0

```

**Comment by yonzhan** [comment] 2020-10-22 00:06
acr

**Comment by yugangw-msft** [comment] 2020-10-22 01:01
dupe of #15465

**Closed by yugangw-msft** 2020-10-22 01:01 UTC
