### ISSUE TITLE
az servicebus namespace list throws an exception

### ISSUE THREAD

**Issue by mkistler** [Azure/azure-cli#20499] opened 2021-11-24 15:32 UTC
## Describe the bug

**Command Name**
`az servicebus namespace list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 704, in _run_job
    result = list(result)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/mgmt/servicebus/operations/_namespaces_operations.py", line 371, in extract_data
    return deserialized.next_link or None, iter(list_of_elem)
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az servicebus namespace list`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.30.0

```
## Additional Context

I issued this command when logged in to a subscription that does not have service bus configured.

**Comment by yonzhan** [comment] 2021-11-24 23:37
route to service team

**Comment by Saglodha** [comment] 2022-03-02 11:11
Hi @mkistler , can you please confirm if you are having any namespaces in subscription where you are running the list command? 

If there are none, then this looks to be a duplicate of #18866

**Comment by mkistler** [comment] 2022-03-02 18:53
I believe I saw this error when I had no service bus namespaces defined, so I agree that this is a dup.

**Closed** 2022-03-02 18:53 UTC
Labels: Service Attention, Service Bus
