### ISSUE TITLE
az storage container generate-sas  crashes when --auth-mode login is specified

### ISSUE THREAD

**Issue by vllama** [Azure/azure-cli#13657] opened 2020-05-24 15:35 UTC
**Running the following command causes the command to crash:**

```
az storage container generate-sas --auth-mode login --account-name $storageAccountName --name "middleware-logs" --permissions "rwdl" --expiry "$logTokenExpiry" --https-only 
```
When running it without --auth-mode login  the following warning is produced:

> No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account.

**Command Name**
`az storage container generate-sas`

**Errors:**
```
self.account_key should not be None.
Traceback (most recent call last):
pip-install-1o1fsnhi\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 608, in execute
cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
cli\core\commands\__init__.py, ln 657, in _run_job
cli\command_modules\storage\__init__.py, ln 257, in new_handler
cli\core\commands\__init__.py, ln 636, in _run_job
cli\core\commands\__init__.py, ln 306, in __call__
azure\cli\core\__init__.py, ln 493, in default_command_handler
command_modules\storage\operations\blob.py, ln 460, in generate_container_shared_access_signature
storage\v2018_11_09\blob\baseblobservice.py, ln 421, in generate_container_shared_access_signature
storage\v2018_11_09\common\_error.py, ln 130, in _validate_not_none
ValueError: self.account_key should not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- I am already logged in using az login.
- `az storage container generate-sas --auth-mode login --account-name $storageAccountName --name "middleware-logs" --permissions "rwdl" --expiry "$logTokenExpiry" --https-only `

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.81 *

Extensions:
application-insights 0.1.3

```

**Comment by yonzhan** [comment] 2020-05-24 23:05
add to S171

**Comment by yonzhan** [comment] 2020-06-03 13:35
add to S172

**Comment by Juliehzl** [comment] 2020-06-11 06:21
dupe of #13012 , #13632

**Closed** 2020-06-22 03:23 UTC
Labels: OKR3.2 Candidate, Storage, feature-request
