### ISSUE TITLE
Console color doesn't reset after error when output is redirected

### ISSUE THREAD

**Issue by scabana** [Azure/azure-cli#13979] opened 2020-06-16 12:08 UTC
## Describe the bug

After some errors, console color doesn't reset. This is similar to https://github.com/Azure/azure-cli/issues/6080.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

For example, but not limited to this example: 

1. az login
1. wait for token expire
1. az keyvault secret list --vault-name somekeyvault
1. az prints: ```Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrato...```
1. echo Hey
1. "Hey" is now red

## Expected Behavior

Console color resets to original color.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0 *

Extensions:
aks-preview 0.4.50
azure-devops 0.18.0
```
## Additional Context

```
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by yonzhan** [comment] 2020-06-16 12:36
add to S172

**Comment by jiasli** [comment] 2020-06-17 01:58
Hi @scabana, are you redirecting the result of `az keyvault secret list --vault-name somekeyvault` to somewhere else? If so, the only fix is to **manually disable color** (introduced in https://github.com/Azure/azure-cli/pull/12601) following [CLI configuration values and environment variables](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables) with the `no_color` config.

This is a bug with colorama (https://github.com/tartley/colorama/issues/200) out of our control.

**Comment by scabana** [comment] 2020-06-17 11:35
Hi, 

It's exactly that. I'll rename the issue. Should this issue be kept opened until a proper fix can be provided?

**Comment by jiasli** [comment] 2020-06-18 04:05
Yes. The fix https://github.com/microsoft/knack/pull/209 is on its way!

**Comment by czmirek** [comment] 2021-01-04 17:51
Got similar issue with `az pipelines variable-group list`

![image](https://user-images.githubusercontent.com/18615545/103563883-d688b100-4ebd-11eb-9141-16b8964151f1.png)

**Comment by jiasli** [comment] 2021-01-05 00:19
@czmirek, this is definitely caused by the colorama bug which is triggered by redirecting the `stdout` to `ConvertTo-Json`. https://github.com/microsoft/knack/pull/209 has been merged and the next version of CLI `2.18.0` released by [S181](https://github.com/Azure/azure-cli/milestone/99) at 2020-01-19 will get rid of this issue.

**Comment by jiasli** [comment] 2021-01-20 03:01
Duplicate of #6080.

**Comment by jiasli** [comment] 2021-01-20 03:01
Duplicate of #6080

**Closed** 2021-01-20 03:02 UTC
Labels: Core, Service Attention, customer-reported

**Comment by jiasli** [comment] 2021-01-20 03:07
This issue has been fixed. Please see https://github.com/Azure/azure-cli/issues/6080#issuecomment-763294594 for the solution.
