### ISSUE TITLE
Tried to az login, didn't work

### ISSUE THREAD

**Issue by swpepin** [Azure/azure-cli#24459] opened 2022-10-27 17:46 UTC
Tried to az login, got this error message:

The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1666887313.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1666891933,
  "nbf": 1666891933,
  "exp": 1666895833,
  "aio": "AXQAi/8TAAAA6ghF+kMD7siekAXoFqHTs4tBZiUUipOnzjeybfEHD7rCtNSrV6NjYADX89q6OnBGPdPR4dN3myGRH48x4zlad+0S8FBBHYn9Os8l6Pjp0b/F5TnSYBFt0mAoLkM7d+KdbJ3bBrBuj6LCIp9TJxiMQQ==",
  "name": "",
  "nonce": "31582fb1cac185f260066c6ae9331549eb8a676b2939d870fa676a0c9efeb6d5",
  "oid": "9fc501f6-2ba1-4ae3-880f-cbe243cc34e5",
  "preferred_username": "",
  "puid": "100320021E03D279",
  "rh": "I",
  "sub": "Cnl7X0z1yEd1Bug6RiSRGp6UjJVZwLkwnvErNJ6Izfw",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "rMHVqSGnWkyEC8DeBccAAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1779, in acquire_token_interactive
    response = _clean_up(self.client.obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 281, in obtain_token_by_browser
    return super(Client, self).obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 639, in obtain_token_by_browser
    return self._obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 677, in _obtain_token_by_browser
    return self.obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 142, in obtain_token_by_auth_code_flow
    return super(_ClientWithCcsRoutingInfo, self).obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
    result = super(Client, self).obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 547, in obtain_token_by_auth_code_flow
    return self._obtain_token_by_authorization_code(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 731, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 788, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 643, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 314, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 117, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 158, in __add
    decode_id_token(id_token, client_id=event["client_id"]) if id_token else {})
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    raise RuntimeError("%s Current epoch = %s.  The id_token was: %s" % (
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1666887313.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1666891933,
  "nbf": 1666891933,
  "exp": 1666895833,
  "aio": "AXQAi/8TAAAA6ghF+kMD7siekAXoFqHTs4tBZiUUipOnzjeybfEHD7rCtNSrV6NjYADX89q6OnBGPdPR4dN3myGRH48x4zlad+0S8FBBHYn9Os8l6Pjp0b/F5TnSYBFt0mAoLkM7d+KdbJ3bBrBuj6LCIp9TJxiMQQ==",
  "name": "",
  "nonce": "31582fb1cac185f260066c6ae9331549eb8a676b2939d870fa676a0c9efeb6d5",
  "oid": "9fc501f6-2ba1-4ae3-880f-cbe243cc34e5",
  "preferred_username": "",
  "puid": "100320021E03D279",
  "rh": "I",
  "sub": "Cnl7X0z1yEd1Bug6RiSRGp6UjJVZwLkwnvErNJ6Izfw",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "rMHVqSGnWkyEC8DeBccAAA",
  "ver": "2.0"
}
To open an issue, please run: 'az feedback'

**Comment by yonzhan** [comment] 2022-10-27 23:41
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2022-10-27 23:41 UTC
Labels: Account, customer-reported, Auto-Assign
