### ISSUE TITLE
[Mooncake]Cannot create Premium CDN profile with Premium_ChinaCdn SKU with CLI 2.0

### ISSUE THREAD

**Issue by forester123** [Azure/azure-cli#4475] opened 2017-09-19 01:48 UTC
### Description
**Outline the issue here:**
I can create premium CDN profile in Ibiza portal, when I run `az cdn profile list` , I can see the SKU name is **Premium_ChinaCdn ** as below:
```
C:\Users\v-johch>az cdn profile list
[
  {
    "id": "/subscriptions/cc124843-d4b8-4a3a-8edf-1314908bda90/resourcegroups/premiumcdn/providers/Microsoft.Cdn/profiles/testcdn",
    "location": "ChinaEast",
    "name": "testcdn",
    "provisioningState": "Succeeded",
    "resourceGroup": "premiumcdn",
    "resourceState": "Active",
    "sku": {
      "name": "Premium_ChinaCdn"
    },
    "tags": {},
    "type": "Microsoft.Cdn/profiles"
  }
]
```

However, when I try to create another new premium CDN profile with the same SKU via CLI, it says invalid the SKU is invalid:
```
C:\Users\v-johch>az cdn profile create -g premiumcdn -n testpremium --sku Premium_ChinaCdn
az cdn profile create: error: argument --sku: invalid choice: Premium_ChinaCdn
usage: az cdn profile create [-h] [--output {json,tsv,table,jsonc}]
                             [--verbose] [--debug] [--query JMESPATH]
                             --resource-group RESOURCE_GROUP_NAME --name NAME
                             [--sku {Standard_Verizon,Premium_Verizon,Custom_Verizon,Standard_Akamai,Standard_ChinaCdn}]
                             [--location LOCATION] [--tags [TAGS [TAGS ...]]]
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.17)

**OS Version:** What OS and version are you using?  
Answer here:  Win 10 version 1703 (OS Build 15063.608)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by forester123** [comment] 2017-10-11 08:13
Any updates?

**Comment by devigned** [comment] 2019-03-22 17:44
As specified in #8855, this will likely require a new spec covering API Version 2018-04-02 for CDN in the rest api specs repo. I've alerted the team and am awaiting a response. I'll follow up when I hear back from CDN team.

**Comment by devigned** [comment] 2019-03-22 21:33
This issue should stay open until the new API version is available in the specs repo and generated.

**Comment by t-bzhan** [comment] 2022-02-09 06:46
Mooncake CDN RP's supported API version is too old, working on to align the version with global CDN to mitigate the issue.

**Comment by t-bzhan** [comment] 2022-04-22 02:13
The issue is fixed now

**Closed** 2022-04-22 02:13 UTC
Labels: bug, Service Attention, Network - CDN
