### ISSUE TITLE
az aks get-credentials doesn't use KUBECONFIG

### ISSUE THREAD

**Issue by daniel-anova** [Azure/azure-cli#26444] opened 2023-05-16 09:14 UTC
## Describe the bug

When using `az aks get-credentials` to retrieve aks login it does not use the config in `KUBECONFIG` and instead [uses the default kubectl config file location](https://github.com/Azure/azure-cli/blob/98f536486379f73818a227f05b18d9f56b8f4948/src/azure-cli/azure/cli/command_modules/acs/custom.py#L1123).

**Command Name**
`az aks get-credentials`

**Errors:**

N/A

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Define `KUBECONFIG` variable
- execute `az aks get-credentials`

## Expected Behavior

Credentials are merged with config file set in `KUBECONFIG`.

## Environment Summary
```
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.48.1

Extensions:
aks-preview 0.5.93
azure-devops 0.26.0
front-door 1.0.16
storage-preview 0.8.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment] 2023-05-16 09:14
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment] 2023-05-16 11:59
@daniel-anova Thanks for reaching out to us and reporting this issue. Could you please use the `--file `parameter and run the 
[az aks get-credentials](https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) command and test ?

> **--file -f** Kubernetes configuration file to update. Use "-" to print YAML to stdout instead.
> default value: ~\.kube\config

**Comment by daniel-anova** [comment] 2023-05-17 08:41
@navba-MSFT are you saying the behavior is by design and i need to use `--file $KUBECONFIG` to update the active kubeconfig?


If I run the normal command the output is what's bellow:

```bash
❯ env | grep KUBECONFIG && az aks get-credentials --resource-group rg-<redacted> --name aks-<redacted> --context test
KUBECONFIG=/home/df/.environments/staging/kube/config
The behavior of this command has been altered by the following extension: aks-preview
Merged "test" as current context in /home/df/.kube/config

❯
```

If i use `--file $KUBECONFIG` it updates the correct file, if i use `--file -` it just outputs the config into stdout as expected.

**Comment by navba-MSFT** [comment] 2023-05-18 04:41
@daniel-anova The default location of the Kubeconfig file is **$HOME/.kube/config**. The CLI and kubectl uses this config from this location. If you have changed the default location of the config you need to specify the location in your command by using `--file $KUBECONFIG` parameter.

You can also leverage the `KUBECONFIG `environment variable with the kubeconfig file path to connect to the cluster.

**Comment by daniel-anova** [comment] 2023-05-18 08:18
Except that `kubectl` automatically uses the `$KUBECONFIG` variable automatically, as does every other tool I'm using without passing any additional parameters.

Per `kubectl` documentation on config files:

> The loading order follows these rules:
>
>  1.  If the --kubeconfig flag is set, then only that file is loaded. The flag may only be set once and no merging takes place.
>  2.  **If `$KUBECONFIG` environment variable is set, then it is used as a list of paths (normal path delimiting rules for your system).** These paths are merged. When a value is modified, it is modified in the file that defines the stanza. When a value is created, it is created in the first file that exists. If no files in the chain exist, then it creates the last file in the list.
> 3.  Otherwise, `${HOME}/.kube/config` is used and no merging takes place. 

_Emphasis mine_

So it makes no sense `az get-credentials` will merge the login details in `${HOME}/.kube/config` when it wont be used by `kubectl` if `$KUBECONFIG` is defined.

**Comment by navba-MSFT** [comment] 2023-05-18 10:13
@FumingZhang is this by design ?

**Comment by FumingZhang** [comment] 2023-05-18 11:01
Hey @daniel-anova , @navba-MSFT, this should be caused by you've got aks-preview installed, which doesn't handle the default path and env KUBECONFIG properly.

![image](https://github.com/Azure/azure-cli/assets/81607949/9c1e1ede-867c-4700-9168-8b88ec07c111)

Will update the command in aks-preview later. Temp workaround is to remove aks-preview (via `az extension remve -n aks-preview`).

**Comment by navba-MSFT** [comment] 2023-05-18 12:19
@daniel-anova Could you please follow the above suggestion to remove the `aks-preview `extension and test the command again ?

**Comment by daniel-anova** [comment] 2023-05-18 12:41
@navba-MSFT Can confirm without aks-preview it works as expected

**Comment by navba-MSFT** [comment] 2023-05-19 05:39
@daniel-anova Thanks for the update.

@FumingZhang Could you please confirm if there are any plans to fix this in the upcoming `aks-preview` version ?

**Comment by navba-MSFT** [comment] 2023-05-26 06:12
@daniel-anova The above PR is now merged. Fix will be released soon. Refer the milestone: https://github.com/Azure/azure-cli-extensions/milestone/80

**Closed by navba-MSFT** 2023-05-26 06:12 UTC
Labels: question, AKS, customer-reported, needs-team-attention, CXP Attention, Auto-Assign
