### ISSUE TITLE
az aks install-cli 

### ISSUE THREAD

**Issue by mohanperera** [Azure/azure-cli#17303] opened 2021-03-14 22:10 UTC
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
az/lib/python3.6/shutil.py, ln 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpmvgmi707/bin/linux_amd64/kubelogin' -> '/usr/local/bin/kubelogin'

...

az/lib/python3.6/shutil.py, ln 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli --install-location={}`

## Environment Summary
```
Linux-4.15.0-1108-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

Extensions:
ai-examples 0.2.5

```

**Comment by yungezz** [comment] 2021-03-15 01:55
route to appropriate team

**Comment by RakeshMohanMSFT** [comment] 2022-08-09 08:57
Duplicate of https://github.com/Azure/azure-cli/issues/15860

**Closed by RakeshMohanMSFT** 2022-08-09 08:57 UTC
Labels: Service Attention, question, AKS
