### ISSUE TITLE
az vm create: --ssh-key-value docs quite confusing

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-cli#579] opened 2016-08-01 19:01 UTC
`az vm create`  says:

```
    --ssh-key-value               : SSH public key or public key file path.
```

OK I think an argument should either accept a file OR a file contents. Not both. It's unintuitive and opens a clear path to bugs and more discoverability issues. Many CLIs have solved this problem by doing things like
- If the input string starts with @, then it's a path
- If the input string is `-`, read from STDIN
- ...

Please make this either `--ssh-key [path]` or `--ssh-key-value [value]`.

**Comment by mayurid** [comment] 2016-08-24 18:45
@johanste : Looks like something that we can adjust based on your PR https://github.com/Azure/azure-cli/pull/738

**Comment by mayurid** [comment] 2016-09-15 21:58
@johanste : Confirm and close?

**Comment by johanste** [comment] 2016-09-15 22:43
@ahmetalpbalkan's concern is still valid. The issue is that when given an explicit path, there is processing done on the input. So there is (currently) a difference between using the @ notation and just specifying a path to the file. 

We can either have two parameters, one which accepts a path and one that accepts a value, or we can munge the existing parameter lookup to, instead of looking for the presence of a file, add the ability to parse/strip out the relevant public key parts from the file.

**Comment by yugangw-msft** [comment] 2017-01-18 20:42
This is not compute specific issue.

**Comment by twitchax** [comment] 2017-02-14 20:55
@devigned is working on VM docs.

**Comment by devigned** [comment] 2017-02-16 23:14
@twitchax if we want to get this right with @ symbols for file paths rather than strings, this needs to be corrected in code. We also need to ensure that this is the rule for how we handle strings or files. If we don't nail this down, it will be a breaking change after 1.0.

I can think of a couple other places where this is happening off the top of my head.

**Comment by devigned** [comment] 2017-02-16 23:27
If not '@', then we could think about using file://foo/bar/baz. I believe most would used to this notation. It would also disambuguate file from text.

**Comment by twitchax** [comment] 2017-02-17 06:42
Sorry, I did not read the rest of the thread: only the title.

Just to be contrarian here...why do we need to designate to the user?  Are unable to tell the difference between a path and an SSH key value?

If anything, I think it should be `--ssh-key [path or value]`.  `--ssh-key-value` is definitely wrong if it accepts both.

**Comment by devigned** [comment] 2017-02-17 18:02
@twitchax what if the value of the string you want to pass just happens to be the name of a local file?

**Comment by yugangw-msft** [comment] 2017-02-17 18:29
This is not a vm command issue, rather about a general pattern CI 2.0 has been with from the very start.  `ssh public key` and json files for deployment and parameter are the 2 main scenarios using it. 
File content and name conflict would be very rare to be impossible, but I agree we can make it clear if we can. I suggest we finalize the design and update them all, rather only focus on one command. 
Till now, I have not received any customer confusion caused by `--ssh-key-value`, but i have received a few caused by commands enforcing the `@` pattern.
//CC: @johanste

**Comment by tjprescott** [comment] 2018-10-04 23:00
We have introduced the @ syntax to load text from files. As we have not had other user complaints regarding this, and to alter the behavior would be a breaking change, I will close this issue.

**Closed by tjprescott** 2018-10-04 23:00 UTC
Labels: Documentation, Feature
