### ISSUE TITLE
WebApp:az webapp create-remote-connection AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by glettl** [Azure/azure-cli#15503] opened 2020-10-13 07:47 UTC
## Describe the bug

**Command Name**
`az webapp create-remote-connection`

**Errors:**
```
'Thread' object has no attribute 'isAlive'
Traceback (most recent call last):
python3.9/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/custom.py, ln 3759, in create_tunnel
    while t.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create-remote-connection --resource-group {} -n {}`

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.9.0
Installer: HOMEBREW

azure-cli 2.12.1 (2.12.1_1)

Extensions:
azure-firewall 0.6.1

```

**Comment by yonzhan** [comment] 2020-10-13 11:49
webapp

**Comment by tirkarthi** [comment] 2020-12-26 14:08
Seems to have been fixed in https://github.com/Azure/azure-cli/pull/15446 and is a duplicate of https://github.com/Azure/azure-cli/issues/15441

**Closed** 2021-02-26 15:48 UTC
Labels: Error Handling, Service Attention, Web Apps
