### ISSUE TITLE
az login returns with error

### ISSUE THREAD

**Issue by kabsingh1** [Azure/azure-cli#23711] opened 2022-08-30 05:45 UTC
cli version : azure-cli-2.39.0
C:\Users\055861744>az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231

**Related command**
az login

**Describe the bug**
az login command is not successful. It does get authenticated from the browser, post hitting this command, and directs to this page, https://docs.microsoft.com/en-us/cli/azure/.
But, the above error pops out in the cli.

**To Reproduce**
open azure cli and type 'az login' and hit enter.

**Expected behavior**
I should be able to successfully logged in to azure cli.

**Environment summary**
Installed azure-cli-2.39.0 in my windows 10, 64-bit machine.

**Additional context**

**Comment by yonzhan** [comment] 2022-08-30 06:26
Duplicate of https://github.com/Azure/azure-cli/issues/20231

**Closed by yonzhan** 2022-08-30 06:26 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
