### ISSUE TITLE
AZ CLI issue - OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by lahmhub** [Azure/azure-cli#15211] opened 2020-09-19 05:39 UTC
## Describe the bug

az group list
``

The command failed with an unexpected error. Here is the traceback:

[Errno 30] Read-only file system: '/home/cloud/.azure/versionCheck.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 782, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/feedback/custom.py", line 764, in handle_feedback
    show_updates_available(new_line_before=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 344, in show_updates_available
    VERSIONS[_VERSION_CHECK_TIME] = str(datetime.datetime.now())
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 86, in __setitem__
    self.save_with_retry()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 76, in save_with_retry
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 30] Read-only file system: '/home/cloud/.azure/versionCheck.json'

To open an issue, please run: 'az feedback'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

create a storage account for az cli
create a vm using az cli
delete all the resources in the resource group from the console
create a new storage account for az cli
run any az cli command on the shell

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1095-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

Extensions:
ai-examples 0.2.3

```

**Comment by yungezz** [comment] 2020-09-19 06:11
hi @fengzhou-msft could you pls help to look is this related to az upgrade? thanks.

**Comment by fengzhou-msft** [comment] 2020-09-19 15:25
This is a known issue of Cloud Shell file system,  same cause as #13855

**Comment by lahmhub** [comment] 2020-09-20 04:29
@fengzhou-msft  Can you advise on the solution?

**Comment by fengzhou-msft** [comment] 2020-09-23 09:48
@lahmhub  there is a workaround provided by CloudShellTeam: https://github.com/Azure/azure-cli/issues/13855#issuecomment-652793995

**Comment by ITChristos** [comment] 2020-10-04 21:18
I had the same problem because I created a different storage resource, I hit the power icon to restart the cloud shell, rebooted and everything worked fine.

**Comment by fengzhou-msft** [comment] 2020-11-27 02:06
Duplicate of #13855

**Closed by fengzhou-msft** 2020-11-27 02:06 UTC
Labels: Packaging
