### ISSUE TITLE
Webapp:az webapp config ssl failing

### ISSUE THREAD

**Issue by anuradhaarao** [Azure/azure-cli#14729] opened 2020-08-10 16:36 UTC
## Trying to add certificate to webapp using powershell but constantly failing at this error:

**Command Name**
`az webapp config ssl upload`

**Errors:**
```
[('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
Traceback (most recent call last):
Temp\pip-unpacked-wheel-2q13h4sp\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 654, in execute
cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
cli\core\commands\__init__.py, ln 711, in _run_job
Local\Temp\pip-unpacked-wheel-39yzrobz\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 688, in _run_job
...
Temp\pip-unpacked-wheel-15a0onnd\OpenSSL\crypto.py, ln 3067, in load_pkcs12
Temp\pip-unpacked-wheel-15a0onnd\OpenSSL\_util.py, ln 54, in exception_from_error_queue
OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config ssl upload --certificate-file {} --certificate-password {} --name {} --resource-group {} --debug`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.0 *

```

**Comment by yonzhan** [comment] 2020-08-10 22:22
webapp

**Comment by anuradhaarao** [comment] 2020-08-11 00:58
az --version : 
![image](https://user-images.githubusercontent.com/40577033/89845340-2c923c00-db4c-11ea-97ed-884f4da9b60a.png)

**Comment by ThejaChoudary** [comment] 2020-08-11 09:16
Assigning it to myself to repro

**Comment by panchagnula** [comment] 2020-08-12 19:53
@yonzhan as per the stack trace this is failing even before it reaches the webapp command execution
 [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]

is there some debugging we can do to check If this was a package install failure?

**Comment by yonzhan** [comment] 2020-08-12 22:28
@fengzhou-msft please help with package install check.

**Comment by anuradhaarao** [comment] 2020-08-14 15:23
To add to this, I tried it in a separate env(VM) and did a fresh installation of python, pip and azure-cli. 

az --version output:
![azversion](https://user-images.githubusercontent.com/40577033/90265357-774bd680-de20-11ea-8166-e13bd73bb973.png)

But i still get the same error, so I am assuming it is a package installation error. It shows the package is installed.

**Comment by fengzhou-msft** [comment] 2020-08-24 01:50
The error is caused by certificate verification. @jiasli can you take a look?

**Comment by fengzhou-msft** [comment] 2020-08-24 04:29
@anuradhaarao how do you get the certificate? @panchagnula any requirements or documentation about using the certificate?

**Comment by AnuRadhaRao** [comment] 2020-08-24 12:29
@fengzhou-msft  - The idea is to get it from keyVault eventually, but for now, I am trying to upload certificate from desktop.

**Comment by panchagnula** [comment] 2020-08-24 16:19
> @anuradhaarao how do you get the certificate? @panchagnula any requirements or documentation about using the certificate in webapp?

@fengzhou-msft no special requirements this command simply lets you upload a local pfx to you an Azure app service app/

**Comment by panchagnula** [comment] 2020-08-24 16:23
> @fengzhou-msft - The idea is to get it from keyVault eventually, but for now, I am trying to upload certificate from desktop.

@AnuRadhaRao from the screenshot above  I see you are using PS as your client to run CLI commands - could yo try to use a normal window or may use cloudshell shell.azure.com & use BASH to verify if this still fails for you? Thank you. please refer to this link on cloudshell as well https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart?view=azure-cli-latest

**Comment by AnuRadhaRao** [comment] 2020-08-24 18:39
@panchagnula  - Used BASH on Azure. Same issue :

`cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 776, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2207, in upload_ssl_cert
    thumb_print = _get_cert(certificate_password, certificate_file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2221, in _get_cert
    p12 = OpenSSL.crypto.load_pkcs12(open(certificate_file, 'rb').read(), certificate_password)
  File "/opt/az/lib/python3.6/site-packages/OpenSSL/crypto.py", line 3067, in load_pkcs12
    _raise_current_error()
  File "/opt/az/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
[('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 776, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2207, in upload_ssl_cert
    thumb_print = _get_cert(certificate_password, certificate_file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2221, in _get_cert
    p12 = OpenSSL.crypto.load_pkcs12(open(certificate_file, 'rb').read(), certificate_password)
  File "/opt/az/lib/python3.6/site-packages/OpenSSL/crypto.py", line 3067, in load_pkcs12
    _raise_current_error()
  File "/opt/az/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]`

**Comment by kwelch2015** [comment] 2020-09-18 18:22
I am also seeing this issue. My password contains special characters. Uploading the same file with the same password works via the UX.

**Comment by kwelch2015** [comment] 2020-09-21 10:40
Looks like this was the error we got when the password was incorrect. Fixing the password allowed the command to work. Would've been nice if the library gave some reasonable error instead of the stack trace. FYI - we saw this behavior on PS, command prompt and bash.

**Comment by panchagnula** [comment] 2020-09-25 03:27
> Looks like this was the error we got when the password was incorrect. Fixing the password allowed the command to work. Would've been nice if the library gave some reasonable error instead of the stack trace. FYI - we saw this behavior on PS, command prompt and bash.

@singlessis can you see if can repro this with a bad password & check if we can fix the error message in CLI? Thanks!

**Closed** 2023-03-02 03:37 UTC
Labels: Web Apps, Service Attention, customer-reported, app-service-certs-domains
