### ISSUE TITLE
az containerapp create fails with "argument of type NoneType is not iterable"

### ISSUE THREAD

**Issue by glennsc** [Azure/azure-cli#25012] opened 2022-12-30 22:35 UTC
## Describe the bug

`az containerapp create` fails with name, resource group, subscription params.

**Command Name**
`az containerapp create
Extension Name: containerapp. Version: 0.3.16.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/Users/gs/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/gs/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 573, in create_containerapp
    handle_raw_exception(e)
  File "/Users/gs/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "/Users/gs/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 563, in create_containerapp
    if "configuration" in r["properties"] and "ingress" in r["properties"]["configuration"] and "fqdn" in r["properties"]["configuration"]["ingress"]:
TypeError: argument of type 'NoneType' is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az containerapp create -n myName -g myGroup --subscription mySub --environment myEnv`

## Expected Behavior

A containerapp is created

## Environment Summary
```
macOS-13.2-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.9

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-31 02:20
@glennsc We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment] 2022-12-31 03:53
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2023-01-04 08:08
@glennsc I am not able to reproduce this issue.
![image](https://user-images.githubusercontent.com/38112130/210510653-97bb27cb-a582-4755-881b-b8a43daa411c.png)
What kind of image you are trying to use ?

**Comment by SaurabhSharma-MSFT** [comment] 2023-01-09 12:48
@glennsc Please let me know if you are still having problems.

**Comment by SaurabhSharma-MSFT** [comment] 2023-01-18 06:38
@glennsc We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2023-01-18 06:38 UTC
Labels: Container Instances, question, customer-reported, CXP Attention, Auto-Assign, ContainerApp, issue-addressed

**Comment by hernandoz** [comment] 2024-02-01 12:53
how do fix this problem ? I am having the same issued 

`PS C:\DEV\test\POC\POCMicroservice-ProjectReporting\SRM.Microservice.Configuration\ContainerAppConfig> az containerapp create -n project-reportingdev -g srmdev-container-services --environment srmdev-container-services-managed-internal --yaml config.yaml
The behavior of this command has been altered by the following extension: containerapp
Additional flags were passed along with --yaml. These flags will be ignored, and the configuration defined in the yaml will be used instead
The command failed with an unexpected error. Here is the traceback:
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\hernando\.azure\cliextensions\containerapp\azext_containerapp\_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\hernando\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 429, in create_containerapp
    containerapp_create_decorator.construct_payload()
  File "C:\Users\hernando\.azure\cliextensions\containerapp\azext_containerapp\containerapp_decorator.py", line 613, in construct_payload
    self.set_up_service_type()
  File "C:\Users\hernando\.azure\cliextensions\containerapp\azext_containerapp\containerapp_decorator.py", line 784, in set_up_service_type
    safe_set(self.containerapp_def, "properties", "configuration", "service", value=service_def)
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/_utils.py", line 1198, in safe_set
TypeError: argument of type 'NoneType' is not iterable
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues`
