### ISSUE TITLE
Azure backup protection enable for vm fails

### ISSUE THREAD

**Issue by Arulanand** [Azure/azure-cli#21018] opened 2022-01-17 16:18 UTC
## Describe the bug

**Command Name**
`az backup protection enable-for-vm`

**Errors:**
```

            The specified Azure Virtual Machine Not Found. Possible causes are
               1. VM does not exist
               2. The VM name or the Service name needs to be case sensitive
               3. VM is already Protected with same or other Vault.
                  Please Unprotect VM first and then try to protect it again.

            Please contact Microsoft for further assistance.
            

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protection enable-for-vm --resource-group {} --vault-name {} --vm {} --policy-name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0 *

Extensions:
azure-devops 0.22.0

```

**Comment by yonzhan** [comment] 2022-01-17 23:21
route to service team

**Comment by pvrk** [comment] 2022-01-18 19:34
@Arulanand : Please check whether backup is already enabled on this VM using the [```az backup protection check-vm```](https://docs.microsoft.com/cli/azure/backup/protection?view=azure-cli-latest#az-backup-protection-check-vm) command

**Comment by adityabalaji-msft** [comment] 2022-01-30 07:21
@Arulanand - just checking back whether you have validated that backup is enabled on this VM already or not. If backup is already enabled, then the above is expected behaviour

**Comment by Arulanand** [comment] 2022-02-01 05:31
> @Arulanand - just checking back whether you have validated that backup is enabled on this VM already or not. If backup is already enabled, then the above is expected behaviour

Backup was not enabled on that VM. I was trying to configure backup for server on location "France Central" and i got the above error. I am sure that recovery vault is also on the same location. But i was able to configure backup without any issues on US East. I did try to configure backup using Portal, one thing i observed is VM was not getting listed for servers to enable for backup.

**Comment by adityabalaji-msft** [comment] 2022-02-02 07:15
Thanks @Arulanand and @neviegas for the details. I tried out the same for a France Central VM but I was not able to reproduce the issue. 

Would you be able to share the debug logs for the same (by using --debug flag in the command)? Apologies for the inconvenience.

Also adding @akshayneema

**Comment by adityabalaji-msft** [comment] 2022-03-16 03:53
Hi @Arulanand - wanted to check back if you could share the debug output for the command (in case it is still failing).
We had identified a related bug which is being fixed right now, but we would need the debug output to confirm whether your issue is due to the same underlying cause.

**Comment by adityabalaji-msft** [comment] 2022-07-06 07:23
awaiting user response

**Comment by zubairabid** [comment] 2024-01-09 05:37
@yonzhan as the Cx hasn't responded in a while can we close this issue.

**Closed** 2024-01-09 07:37 UTC
Labels: Service Attention, Recovery Services Backup, customer-response-expected, customer-reported
