### ISSUE TITLE
"--unmodified-since" is not working with "az storage blob delete"

### ISSUE THREAD

**Issue by JavedEqbal** [Azure/azure-cli#9106] opened 2019-04-15 09:50 UTC
**Describe the bug**
Trying to delete all the snapshots which are older than 3 days using "az storage blob delete" using --unmodified-since switch and throwing the below error.

```
javed@Azure:~$ az storage blob delete --name "unmanagedvm-datadisk.vhd" --account-name eastussa --account-key '' -c vhds --if-unmodified-since $date --delete-snapshots only
The command failed with an unexpected error. Here is the traceback:

The condition specified using HTTP conditional header(s) is not met. ErrorCode: ConditionNotMet
<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.
RequestId:60e08b37-801e-0084-046d-f3b2cc000000
Time:2019-04-15T09:26:02.3121974Z</Message></Error>
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 375, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 240, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 183, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/baseblobservice.py", line 3254, in delete_blob
    self._perform_request(request)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 381, in _perform_request
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 306, in _perform_request
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 292, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: The condition specified using HTTP conditional header(s) is not met. ErrorCode: ConditionNotMet
<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.
RequestId:60e08b37-801e-0084-046d-f3b2cc000000
Time:2019-04-15T09:26:02.3121974Z</Message></Error>

To open an issue, please run: 'az feedback'
```

**To Reproduce**
Run the below az cli command 

`javed@Azure:~$ az storage blob delete --name "unmanagedvm-datadisk.vhd" --account-name eastussa --account-key '' -c vhds --if-unmodified-since $date --delete-snapshots only`

**Expected behavior**
The snapshots where modified date is older than 3 days should have been deleted.

**Environment summary**
Running from Azure Cloud Shell (bash)

**Comment by limingu** [comment] 2019-04-22 20:44
Looking it. @JavedEqbal, can you provider the CLI version that you are using? Thanks.

**Comment by JavedEqbal** [comment] 2019-04-23 17:55
@limingu : I'm running from Azure Cloud shell, I believe that should be the latest one. I can still confirm this.

```
javed@Azure:~$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by limingu** [comment] 2019-04-26 23:55
@JavedEqbal I mean the CLI command version. You can use 'az --version' to show the CLI version. It is some like azure-cli 2.0.63

**Comment by Juliehzl** [comment] 2019-08-14 03:41
@JavedEqbal  It looks you are using Azure Cloud Shell to run cli command, right? I cannot reproduce your error now. Does the error still exist now?

**Comment by Juliehzl** [comment] 2019-08-26 04:50
@JavedEqbal Do you still have problems? If not, I will close this issue.

**Closed** 2019-12-17 08:42 UTC
Labels: Bug, Storage-cli
