### ISSUE TITLE
NotImplementedError: APIVersion is not available for az storage commands

### ISSUE THREAD

**Issue by maguir** [Azure/azure-cli#18447] opened 2021-06-10 23:18 UTC
## Describe the bug

**Command Name**
`az storage account list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
APIVersion 2021-04-01 is not available
Traceback (most recent call last):
  File "/home/maguir/.local/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/maguir/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/maguir/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/maguir/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/maguir/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/maguir/.local/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/home/maguir/.local/lib/python3.7/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 143, in cf_sa
    return storage_client_factory(cli_ctx).storage_accounts
  File "/home/maguir/.local/lib/python3.7/site-packages/azure/mgmt/storage/_storage_management_client.py", line 413, in storage_accounts
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2021-04-01 is not available

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- This happens using wsl, works fine on windows powershell
- `az storage account list`

## Expected Behavior
should work
## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-Ubuntu-18.04-bionic
Python 3.7.5
Installer: PIP

azure-cli 2.24.2

```
## Additional Context
I upgraded azcli and still got the same error (before it was giving me a different apiversion
this happens for any az storage command I try to run

**Comment by yonzhan** [comment] 2021-06-11 00:34
storage

**Comment by Juliehzl** [comment] 2021-07-12 05:46
dupe of https://github.com/Azure/azure-cli/issues/18769

**Comment by Juliehzl** [comment] 2021-07-12 05:47
please make sure you azure-mgmt-storage >= 18.0.0

**Closed** 2021-07-31 05:21 UTC
Labels: OKR3.2 Candidate, Storage, feature-request
