### ISSUE TITLE
{ams asset} HTML tag isn't allowed in example syntax

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#27055] opened 2023-08-01 14:29 UTC
### Describe the bug

The source code for ams asset is using HTML tags for examples

Instance 1: https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ams/asset.yml#L267
`Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.'`

Instance 2: https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ams/asset.yml#L274
`Example: --set property1.property2=<value>.'`

Modify these instances to use some other character like a backtick or escape character.

**Contributor's Guide guideance:**
https://review.learn.microsoft.com/en-us/help/platform/validation-ref/disallowed-html-tag?branch=main

**Instance 1 YML syntax looks like this:**
summary: 'Remove a property or an element from a list.  Example: --remove property.list \<indexToRemove> OR --remove propertyToRemove.'

**Instance 1 published content renders like this:**
![image](https://github.com/Azure/azure-cli/assets/58762114/f6102212-d1ab-4c7c-949d-40620f37a917)

**This impacts \latest only**
- https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ams/asset.yml

### Related command

az ams asset update --remove
az ams asset update --set

### Errors

**GitHub build warning:**
![image](https://github.com/Azure/azure-cli/assets/58762114/4e193b2d-d488-4030-b784-61e17625e69d)

### Issue script & Debug output

See "Describe the bug" section above.

### Expected behavior

See "Describe the bug" section above.

### Environment Summary

See "Describe the bug" section above.

**Comment by yonzhan** [comment] 2023-08-01 14:29
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment] 2023-08-02 03:26
Since this is non-customer reported, Adding Service team to look into this.

**Comment by dbradish-microsoft** [comment] 2023-09-22 01:57
@yonzhan, do you know if this issue made it to anyone's backlog to get fixed?

**Comment by jiasli** [comment] 2023-11-03 08:40
Duplicate of #27054

**Closed by jiasli** 2023-11-03 08:40 UTC
Labels: bug, Service Attention, Media Services, Auto-Assign, Auto-Resolve, Similar-Issue, Possible-Solution
