### ISSUE TITLE
az extension update failed with access denied for azure-cli-ml

### ISSUE THREAD

**Issue by brianholley** [Azure/azure-cli#10509] opened 2019-09-11 18:15 UTC
## Describe the bug

CLI extension update from azure-cli-ml 1.0.41 to latest (1.0.60) failed with an access denied error. After failing, the extension was uninstalled (rather than left unchanged).

**Command Name**
`az extension update`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

[WinError 5] Access is denied: 'C:\\Users\\bholley\\.azure\\cliextensions\\azure-cli-ml\\_ruamel_yaml.cp36-win32.pyd'Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\extension\operations.py", line 276, in update_extension
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\bholley\\.azure\\cliextensions\\azure-cli-ml\\_ruamel_yaml.cp36-win32.pyd'
```

## To Reproduce:

- Install azure-cli-ml extension v 1.0.41
- `Run: az extension update -n azure-cli-ml`

## Expected Behavior

CLI extension update succeeded
If CLI extension update fails, extension is left installed in the previous state

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli                         2.0.62 *

```

**Comment by yonzhan** [comment] 2019-10-02 23:44
@zikalino please take a look and comment.

**Comment by gogowings** [comment] 2019-12-05 21:24
To add more info as we have investigated this issue on azure-cli-ml side. 

* This only repro in windows, not linux. In windows, it consistently repros. 
* We hit the consistent repro on python 3.7.3. Not sure about other version of python.
* the access denied always happens to _ruamel_yaml.cp36-win32.pyd
* azure-cli-ml takes dependency on ruamel.yaml
* We ran procmon during 'az extension update -n azure-cli-ml', it showed python process tried to access the .azure\cliextensions\azure-cli-ml\_ruamel_yaml.cp36-win32.pyd multiple times. So the error comes from os.unlink call. In ProcMon log file, right before that, there's CreateFile call with ShareMode: Read/Write/Delete and that handle wasn't closed. That should be the direct cause for the access denied. 
* not sure what triggered the file access though but it's a pyd file so probably somehow "az extension update" recompile that file?

**Comment by gogowings** [comment] 2019-12-05 21:25
Happy to share the procmon log file if that helps.

**Comment by yonzhan** [comment] 2020-06-14 12:18
add to S173

**Comment by haroldrandom** [comment] 2020-07-15 06:39
dup https://github.com/Azure/azure-cli/issues/11078

**Comment by lostmygithubaccount** [comment] 2020-11-05 22:27
@v-strudm-msft please close, duplicate of #11078

**Closed** 2020-11-05 22:33 UTC
Labels: Extensions, ML-MLOps, Machine Learning, Service Attention
