### ISSUE TITLE
cross-subscription private-endpoint creation not possible

### ISSUE THREAD

**Issue by kosticd** [Azure/azure-cli#13614] opened 2020-05-21 20:10 UTC
There is no way to specify --subscription of private-endpoint and --subscription where privateLinkService resides, if they are different:
az network private-endpoint create - is failing with

InvalidResourceReference - Resource /subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/... referenced by resource /subscriptions/.../resourceGroups/.../providers/Microsoft.Network/privateEndpoints/... was not found. Please make sure that the referenced resource exists, and that both resources are in the same region. &lt;-- Private link service and private link endpoint are in different subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8911e94f-9496-a68d-50c0-b5d536a375a4
* Version Independent ID: cc37b77b-0fa2-991b-e16b-fcdbbf183853
* Content: [az network private-endpoint](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest&source=docs#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-05-21 23:01
add to S170

**Comment by MyronFanQiu** [comment] 2020-05-22 01:44
Are you using subnet id instead of the name to specify the subnet? Please use resource id of subnet instead of `--subnet and --vnet-name`

**Comment by yonzhan** [comment] 2020-05-31 12:56
@kosticd any update for above?

**Comment by MyronFanQiu** [comment] 2020-06-19 03:43
closed this one since it's usage question and should be solved. feel free to reopen it if you still have any question.

**Closed by MyronFanQiu** 2020-06-19 03:43 UTC
Labels: Network, OKR3.2 Candidate, feature-request

**Comment by richeney** [comment] 2021-05-03 19:21
This error also comes up if the location for the `az network private-endpoint create` is not specified to the same region as both the local vnet/subnet and the private link service (if applicable).

**Comment by msyyc** [comment] 2021-05-06 07:59
If name of vnet/subnet is provided, cli will use '--resource-group' as a part to assemble id. If you want to use resources in different resource groups, please use id instead of name.

**Comment by yogspatel** [comment] 2022-07-14 17:32
I am having this same error message trying to create a cross subscription private endpoint for Azure Cache for Redis. 

`az network private-endpoint create -g myRG -n myEndpointName --subnet "/subscriptions/1xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx1/resourceGroups/myNetworkRg/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/subnet-10.0.1.0" --private-connection-resource-id "/subscriptions/2xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx2/resourceGroups/myRedisCacheRg/providers/Microsoft.Cache/redis/myRedisCache" --connection-name myConnection --group-id redisCache -l northeurope`

Above command works fine if `--subnet` and `--private-connection-resource-id` are both in pointing to resources in the same subscription.

Any Ideas??? 

Thank you!

**Comment by elshat128** [comment] 2022-11-18 18:13
same issue/error happened for a web app and PE creation via CLI
Command using:
az network private-endpoint create \\
    --name examplePE \\
    --connection-name MyconnectionName \\
    --private-connection-resource-id /subscriptions/2xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx2/resourceGroups/webAppRG/providers/Microsoft.Web/sites/MySites \\
    --resource-group webAppRG \\
    --subnet /subscriptions/1xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx1/resourceGroups/networking/providers/Microsoft.Network/virtualNetworks/PEvnet/subnets/PEsubnet \\
    --group-id sites \\
    --location eastus2 \\
    --manual-request false \\-subscription 2xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx2

**ERROR:** (InvalidResourceReference) Resource /subscriptions/1xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx1/resourceGroups/networking/providers/Microsoft.Network/virtualNetworks/PEvnet referenced by resource /subscriptions/2xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx2/resourceGroups/webAppRG/providers/Microsoft.Network/privateEndpoints/examplePE was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
Code: InvalidResourceReference

**Comment by CaishenNefri** [comment] 2023-04-03 08:27
It seems that it is not possible to create private endpoint in the own subscription but pointing to vnet resides in different subscription.

**Comment by yashvit** [comment] 2023-06-06 18:56
Is there a solution to this?

**Comment by fuyong2022** [comment] 2023-08-01 01:28
Confirmed az cli cant do it and the doc seems to be wrong about this.
