### ISSUE TITLE
Obtain an Azure SQL connection string template via az cli

### ISSUE THREAD

**Issue by alexvicegrab** [Azure/azure-cli#4606] opened 2017-10-04 11:29 UTC
### Description
I need to create a connection string to my az cli Azure SQL database programmatically (just as I can do in other services like CosmosDB, etc.), and can get templates on the Azure Portal with tokens for substituting "username" and "password", but can't seem to be able to find anything like this in the az cli.

This makes it more difficult to do this programatically and means I will need to manually update it every time the connection string format is updated.

Did I miss some option and can this be implemented?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Python (Darwin) 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here: Mac OSX 10.12.6 (16G29)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: zsh (antigen/oh-my-zsh)

**Comment by tjprescott** [comment] 2017-10-06 16:12
This is a duplicate of #2789. PR #4609 has been opened by SQL team, which will add the functionality you desire.  Please watch for that in next release or so.

**Closed by tjprescott** 2017-10-06 16:12 UTC
Labels: Question, SQL
