### ISSUE TITLE
az interactive command fails

### ISSUE THREAD

**Issue by dollarpo7** [Azure/azure-cli#12835] opened 2020-04-01 21:15 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
cannot import name 'ENV_ADDITIONAL_USER_AGENT'
Traceback (most recent call last):
Temp\pip-install-_1mlo87m\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 625, in execute
azure\cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 682, in _run_job
Local\Temp\pip-install-_1mlo87m\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 659, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 531, in default_command_handler
azure\cli\command_modules\interactive\custom.py, ln 41, in start_shell
.azure\cliextensions\interactive\azext_interactive\__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
cliextensions\interactive\azext_interactive\azclishell\app.py, ln 31, in <module>
    from azure.cli.core.commands.client_factory import ENV_ADDITIONAL_USER_AGENT
ImportError: cannot import name 'ENV_ADDITIONAL_USER_AGENT'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment] 2020-04-01 23:16
interactive

**Comment by jiasli** [comment] 2020-04-02 04:00
Duplicate of #12837

**Closed by jiasli** 2020-04-02 04:00 UTC
Labels: Feature Request, Interactive, Service Attention

**Comment by jiasli** [comment] 2020-04-02 04:08
Duplicate of https://github.com/Azure/azure-cli-extensions/issues/1480
