### ISSUE TITLE
In Az Network vnet-gateway update command the purpose of the add/remove/set parameters is unlcear

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#2052] opened 2017-02-13 06:59 UTC
Most of the Gateway settings that need to be configured seem to be available. Either these params should be removed or their purpose should be specified clearly.

**Comment by tjprescott** [comment] 2017-02-13 16:32
"add/remove/set" are not unique to this command. They are generic across nearly all of the CLI's update commands. 

This is effectively a dupe of #1582.

**Closed by tjprescott** 2017-02-13 16:32 UTC

**Comment by aanandr** [comment] 2017-02-13 18:32
Hi Travis – I agree. But do we really need it in this case? Most of the capabilities are already covered through other params. If we do need it then we have to at least specify which settings need it.

**Comment by tjprescott** [comment] 2017-02-13 19:28
By design, we have made a point to expose the generic parameters and the convenience flags for all of our update commands.

**Comment by aanandr** [comment] 2017-02-13 20:07
Ok. But can you document what those can be used for (to configure which settings)? This may be a P2 or a P3 bug.
