### ISSUE TITLE
keyvault wrong argument --vault-name in VSS instead of --name

### ISSUE THREAD

**Issue by chrmarti** [Azure/azure-cli#8180] opened 2019-01-07 09:33 UTC
_From @sameershaikgithub on January 5, 2019 21:35_

in VSS auto complete shows --vault-name which doesn't exists in cli instead uses --name. Please update this. Screenshot attached.

bash-3.2$ az keyvault purge  --vault-name shaiksvault 
az keyvault purge: error: argument --name/-n is required

usage: az keyvault purge [-h] [--verbose] [--debug]
                         [--output {tsv,table,json,jsonc,yaml}]
                         [--query JMESPATH] [--subscription _SUBSCRIPTION]
                         --name NAME --location LOCATION

<img width="621" alt="screen shot 2019-01-05 at 2 40 16 pm" src="https://user-images.githubusercontent.com/20804460/50729457-d7887b80-1107-11e9-9a22-7982ef77e370.png">

_Copied from original issue: Microsoft/vscode-azurecli#41_

**Comment by chrmarti** [comment] 2019-01-07 09:33
We are reading these from the CLI itself. `az interactive` shows the same (wrong) argument names for `keyvault purge --help`.

**Comment by tjprescott** [comment] 2019-01-07 17:03
This is a duplicate of #8179

**Closed by tjprescott** 2019-01-07 17:03 UTC
