### ISSUE TITLE
az extension add has an Unicode display issue

### ISSUE THREAD

**Issue by limingu** [Azure/azure-cli#9122] opened 2019-04-16 21:03 UTC
**Describe the bug**
az extension add has an Unicode display issue

**To Reproduce**
Steps to reproduce the behavior.
az extension add --name azure-devops

**Expected behavior**

**Additional context**
has an Unicode display issue

**Comment by limingu** [comment] 2019-04-16 21:04
![unicode](https://user-images.githubusercontent.com/48228819/56243910-87974a00-6050-11e9-9047-dce1835a3e35.png)

**Comment by adewaleo** [comment] 2019-04-16 21:07
I will add this command was an issue on the command prompt

**Comment by tjprescott** [comment] 2019-04-16 21:45
What is the python version?

**Comment by atbagga** [comment] 2019-05-02 12:58
This is duplicate of #9140 

I haven't been able to get to it. I will try to debug and raise a fix soon. 
FYI.. The issue is on Windows only.

**Comment by yonzhan** [comment] 2019-12-08 11:38
add to S164.

**Comment by jiasli** [comment] 2020-03-03 07:14
Fixed by #9660

**Closed by jiasli** 2020-03-03 07:14 UTC
Labels: Core, Output
