### ISSUE TITLE
az repos requiredArgumentMissing error

### ISSUE THREAD

**Issue by Evilk1llah** [Azure/azure-cli#17267] opened 2021-03-10 14:51 UTC
## Describe the bug

**Command Name**
`az repos`

**Errors:**
```
RequiredArgumentMissingError: the following arguments are required: _subcommand
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az repos`

## Environment Summary
```
Linux-5.10.0-3parrot1-amd64-x86_64-with-glibc2.31
Python 3.9.1+
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yungezz** [comment] 2021-03-11 02:38
route to appropriate team

**Comment by stewartadam** [comment] 2021-06-22 20:38
Duplicate of #15375?

**Comment by jiasli** [comment] 2022-07-20 04:58
Tracked by #19592

**Closed by jiasli** 2022-07-20 04:58 UTC
Labels: Service Attention, question, DevOps
