### ISSUE TITLE
MaxBurst for az functionapp plan incorrectly limited to 20, when Azure Portal allows 100 for MaxBurst

### ISSUE THREAD

**Issue by vhhughes** [Azure/azure-cli#20841] opened 2021-12-27 18:48 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15cb3fd0-5d13-ab34-223b-f7972aae16a2
* Version Independent ID: 65cc59ca-c366-dbe0-b95d-7dcfa3a4438d
* Content: [az functionapp plan](https://docs.microsoft.com/en-us/cli/azure/functionapp/plan?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/plan.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/plan.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2021-12-28 00:38
route to service team

**Comment by navba-MSFT** [comment] 2022-03-22 10:08
@vhhughes Closing as duplicate of https://github.com/Azure/azure-cli/issues/21225

**Closed by navba-MSFT** 2022-03-22 10:08 UTC
Labels: Service Attention, Functions, customer-reported
