### ISSUE TITLE
msal and msal extensions pinned to old versions

### ISSUE THREAD

**Issue by ianhelle** [Azure/azure-cli#15212] opened 2020-09-19 18:00 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
azure-cli-core has dependencies on msal (~= 1.0.0) and msal-extensions (0.1.3) that are incompatible with with recent versions of azure-identity (anything after 1.3.1).

azure-identity recently released support for use AzureCliCredential - pretty much the only way to obtain an AzureCredential from an existing Azure CLI logon. An AzureCredential is needed for recent versions of increasing parts of Azure SDK like Keyvault client, azure monitor and anything else migrating to msal-style creds. However, you cannot install a version of azure-identity that supports AzureCliCredential without a conflict with azure-cli-core.

New versions of pip are reporting this as an error and it breaks things like readthedocs builds.

**To Reproduce**
pip install azure-cli-core (or azure-cli)
pip install azure-identity

**Expected behavior**
azure-cli-core has more relaxed versioning requirements for msal and msal-extensions allowing it to be used alongside Azure SDK components that require later versions.

**Environment summary**
This is repro-able in any environment

**Additional context**

**Comment by yonzhan** [comment] 2020-09-20 00:40
add to S176

**Comment by jiasli** [comment] 2020-09-21 05:16
Yes, `azure-cli-core` has dependency on https://github.com/Azure/azure-cli/blob/573e66b75c1a6b102d32ef50e6740950e8c4fd4d/src/azure-cli-core/setup.py#L53-L54

However, [installing Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) with `pip` is not supported. If you must install with `pip`, we don't recommend installing Azure CLI and other Python SDKs in the same virtual environment.

`AzureCliCredential` only [uses subprocess to call `az account get-access-token`](https://github.com/Azure/azure-sdk-for-python/blob/86f41246602d1bfd32c8d2e93c152899ef2e2ace/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L28), so it is fine to install Azure CLI and `azure-identity` under different virtual environments. 

Moreover, installing Azure CLI and other Python SDKs in the same virtual environment will break other commands of Azure CLI as well, because Azure CLI still uses Track 1 SDKs and replacing them with Track 2 SDKs will break the underlying dependencies.

**Comment by ianhelle** [comment] 2020-09-25 21:58
@jiasli - I understand the not supporting pip install for the whole of azure-cli and using separate environments, etc. but why is azure-cli-core even available on PyPI if you don't support installing with pip?
There's still the question that azure-identity now has AzureCliCredential support but in the current state of things you cannot use it in a supported way because it's impossible to have azure-cli-core and azure-identity in the same environment without this version conflict.

**Comment by jiasli** [comment] 2020-09-26 14:47
> I understand the not supporting pip install for the whole of azure-cli and using separate environments, etc. but why is azure-cli-core even available on PyPI if you don't support installing with pip?

I will leave this question to @fengzhou-msft who is working on CLI release pipeline. 

The dependency of MSAL is for VM SSH. @arrownj will bump the MSAL version accordingly and test with the latest MSAL. Hope this will unblock you. 

> ... one of our dependencies does

May I know how the dependency is using Azure CLI? Ideally it should also use sub-process like `AzureCliCredential` does. 

> I'd assumed that a pip-installed azure-cli wouldn't even be visible to a different environment.

`az` is supposed to be visible on the `PATH`. This will require you to edit your `PATH` environment variable to include `az`. For example, on Windows, if you install outside a virtual environment, it is at `C:\Users\username\AppData\Local\Programs\Python\Python38\Scripts\az.bat`. Inside a virtual environment, it is at `<env>\Scripts\az.bat`. But again, we recommend installing in [officially supported ways](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest), instead of using `pip`.

**Comment by ivanst0** [comment] 2020-12-16 10:59
I believe this could be easily fixed by changing

    'msal~=1.0.0',
    'msal-extensions~=0.1.3',

into

    'msal~=1.0',
    'msal-extensions~=0.2',

@arrownj, would this work?

**Comment by jiasli** [comment] 2020-12-17 06:45
@qwordy, could you help verify if `msal-extensions~=0.2` works for VM SSH?

**Comment by tunayokumus** [comment] 2021-01-25 10:26
hi @jiasli . 
AzureML SDK has a dependency on  both azure-identity and on azure-cli-core (latter not stated in setup.py i believe but necessary for some modules). There we have the requirement to install both azureml-core and azure-cli-core in the same environment in order to use the azureml.core.authentication.AzureCliAuthentication module/class. Only installing azure-cli with the msi installer is not enough in that case.

However we are getting the dependency conflict because of the aforementioned issue.

It would be great from a user-experience point if the msal dependency conflict is solved.

**Comment by jiasli** [comment] 2021-01-25 10:32
@tunayokumus, I fully understand your problem. 

We will test SSH based on the latest MSAL and bump its version accordingly. Thank you for your patience and understanding.

**Closed** 2021-02-23 07:09 UTC
Labels: Azure Identity Integration, OKR3.2 Candidate, feature-request

**Comment by tunayokumus** [comment] 2021-02-23 12:05
Hi @jiasli and @fengzhou-msft, thanks a lot for following up on this. Unfortunately I am still experiencing the same issue, this time with the updated azure-cli-core==2.19.1. Although the dependencies are changed in the setup.py within the dev branch in git.

Is this fix published as a new version and already available through pypi? If yes, how can we pip install it? Or do you have any other idea what might be the cause of this?

> azure-cli-core 2.19.1 requires msal~=1.0.0, but you have msal 1.9.0 which is incompatible.
> azure-cli-core 2.19.1 requires msal-extensions~=0.1.3, but you have msal-extensions 0.2.2 which is incompatible.

**Comment by AlexandreBouffard** [comment] 2021-02-23 15:59
This issue is tagged with milestone S183 having official release on March 2nd so I guess they will publish a release to pypi over the next week or so.

**Comment by jiasli** [comment] 2021-02-24 11:11
> This issue is tagged with milestone S183 having official release on March 2nd so I guess they will publish a release to pypi over the next week or so.

Exactly, the change hasn't been released to PyPI yet. You may check our release schedule at https://github.com/Azure/azure-cli/milestones
