### ISSUE TITLE
Dashboard Browse ends with exceptions

### ISSUE THREAD

**Issue by brobichaud** [Azure/azure-cli#9466] opened 2019-05-23 16:49 UTC
## Describe the bug
On a new ASK cluster with Windows nodes I am able to connect and use the dashboard just fine. Bit when I'm done, pressing Ctrl-C results in a stream of exceptions as seen below.

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04DFA4B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
pip-install-wuxrdt2n\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
urllib3\urllib3\util\connection.py, ln 70, in create_connection
...
pip-install-v1m4qsu_\requests\requests\adapters.py, ln 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04DFA4B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} -n {}`

## Expected Behavior
The command should exit cleanly when pressing Ctrl-C

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64 *

Extensions:
aks-preview 0.4.1

```

**Comment by yugangw-msft** [comment] 2019-05-23 17:01
Dupe of #9465

**Closed by yugangw-msft** 2019-05-23 17:01 UTC
