### ISSUE TITLE
az role definition delete failed with OAuth2 Bad Request for URL

### ISSUE THREAD

**Issue by ea1het** [Azure/azure-cli#10294] opened 2019-08-21 15:06 UTC
## Describe the bug

**Command Name**
`az role definition delete`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition delete --name {}`

## Expected Behavior
A custom role definition should be deleted with a confirmation. 

## Environment Summary
```
Linux-4.15.0-1055-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.71

```

**Comment by jiasli** [comment] 2019-09-25 01:56
This is likely an old Cloud Shell issue. Does it work now?

**Comment by yonzhan** [comment] 2020-06-01 02:53
@ea1het any update for above?

**Comment by jiasli** [comment] 2020-06-30 03:41
Duplicate of #11749. For a workaround, please check https://github.com/Azure/azure-cli/issues/11749#issuecomment-570975762

**Closed by jiasli** 2020-06-30 03:41 UTC
Labels: Authorization, OKR3.4 Candidate
