### ISSUE TITLE
az upgrade --yes prompts to close Python before continuing

### ISSUE THREAD

**Issue by v-chilso** [Azure/azure-cli#26777] opened 2023-06-28 22:01 UTC
### Describe the bug

az upgrade prompts to close Python, then displays a Files in use dialog reporting Python has files in use that need to be updated by Setup. This ends with a prompt for system restart to complete Setup.

### Related command

az upgrade

### Errors

az upgrade prompted to close Python however I believe "az upgrade" started Python itself.

### Issue script & Debug output

This is not possible because the az upgrade already ran and updated to the latest.

### Expected behavior

az upgrade --silent to silently install the upgrade, if available, without user intervention. Sets an exit code to non-zero upon failure.

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mcauto\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

If this is fixed in the latest release, it is not possible to test the behavior until there is a new version released.

**Comment by yonzhan** [comment] 2023-06-28 22:02
Thank you for opening this issue, we will look into it.

**Comment by v-chilso** [comment] 2023-06-28 22:08
You're welcome @yonzhan I also want to add that I ran
`$ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; Remove-Item .\AzureCLI.msi`

Which had no prompts and the version successfully upgraded.

**Comment by bebound** [comment] 2023-06-29 02:13
Duplicate of #22741

**Closed by bebound** 2023-06-29 02:13 UTC
Labels: bug, customer-reported, Installation, Upgrade, Auto-Assign, Azure CLI Team
