### ISSUE TITLE
No module named 'decorator'

### ISSUE THREAD

**Issue by ayoubkoreteszx** [Azure/azure-cli#15584] opened 2020-10-20 09:32 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} --name {}`

## Environment Summary
```
Linux-5.4.0-51-generic-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81 *

```

**Comment by yonzhan** [comment] 2020-10-20 11:03
webapp

**Comment by yungezz** [comment] 2020-10-21 03:14
hi @ayoubkoreteszx could  you pls uninstall 2.0.81 and install latest Azure CLI? this is a known issue in 2.0.81 tracked in #14011

**Comment by fengzhou-msft** [comment] 2020-10-26 10:02
Duplicate of #14011

**Closed by fengzhou-msft** 2020-10-26 10:02 UTC
Labels: Packaging
