### ISSUE TITLE
Unable to retreive API keys for eventhub namespace using CLI

### ISSUE THREAD

**Issue by mkyukov** [Azure/azure-cli#11696] opened 2019-12-27 12:59 UTC
## Describe the bug
Unable to retreive API keys for eventhubs namespace using CLI.
**Command Name**
`az eventhubs namespace authorization-rule keys list`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create namespace using CLI
- `az eventhubs namespace authorization-rule keys list --name {} --namespace-name {}`

## Environment Summary
```
Linux-4.15.0-1064-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78

```
## Additional Context
Error occured when using the cloud shell provided in the following exercise - https://docs.microsoft.com/en-us/learn/modules/enable-reliable-messaging-for-big-data-apps-using-event-hubs/3-exercise-create-an-event-hub-using-azure-cli

Browser is Brave Browser version 1.1.23 (Latest).

**Comment by v-Ajnava** [comment] 2020-01-10 01:16
@mkyukov, we were not able to reproduce at our end. we are getting the keys . Can you please send the command you are using (without the parameter values)

**Comment by jfggdl** [comment] 2020-01-27 21:17
@mkyukov, we are closing this issue, but feel free to request it to be opened again if needed.

**Closed by jfggdl** 2020-01-27 21:17 UTC
Labels: Bug, Event Hubs, Service Attention, customer-response-expected
