### ISSUE TITLE
aks update

### ISSUE THREAD

**Issue by timlawless-la** [Azure/azure-cli#11856] opened 2020-01-14 21:02 UTC
### **This is autogenerated. Please review and update as needed.**
aks update not working
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
No module named 'azure.mgmt.containerservice.v2019_08_01'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 291, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 76, in <module>
    from ._helpers import _populate_api_server_access_profile, _set_load_balancer_sku, _set_vm_set_type
cliextensions/aks-preview/azext_aks_preview/_helpers.py, ln 8, in <module>
    from azure.mgmt.containerservice.v2019_08_01.models import ManagedClusterAPIServerAccessProfile
ModuleNotFoundError: No module named 'azure.mgmt.containerservice.v2019_08_01'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --update-cluster-autoscaler --min-count {} --max-count {}`

## Environment Summary
```
Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.72 *

Extensions:
aks-preview 0.4.27

```

**Comment by jluk** [comment] 2020-01-15 16:49
@timlawless-la I'm unable to reproduce this on 2.0.78, could you upgrade your az cli version and retry?

**Comment by timlawless-la** [comment] 2020-01-15 17:10
Hi Justin,

I’m on 2.0.72_1. I uninstalled the extension, I’ll try it later.

Thanks,

Tim

 <https://linuxacademy.com/>
 	#1 Learn-by-Doing Multicloud Training Platform
 	 	 	Tim Lawless
Training Architect

125 Bear Creek Parkway. Keller. Texas 76248
LinuxAcademy.com <https://linuxacademy.com/> <https://linuxacademy.sigstr.net/uc/5dd800d5057c8500aedc6509>



© Linux Academy, 2019. All Rights Reserved.
Pinehead® and the Linux Academy Logo® are registered trademarks of Linux Academy in the U.S. and other countries. Linux® is a registered trademark of Linus Torvalds in the U.S. and other countries.

**Comment by timlawless-la** [comment] 2020-01-15 20:03
Ok, updated and re-installed.

Now I get a different error message:
Cluster autoscaler is not enabled for this managed cluster.
Run "az aks update --enable-cluster-autoscaler" to enable cluster with min-count and max-count.

Autoscaling was enabled on that cluster with:
kubectl autoscale deployment azure-vote-front --cpu-percent=50 --min=3 --max=10

Thanks,

Tim

 <https://linuxacademy.com/>
 	#1 Learn-by-Doing Multicloud Training Platform
 	 	 	Tim Lawless
Training Architect

125 Bear Creek Parkway. Keller. Texas 76248
LinuxAcademy.com <https://linuxacademy.com/> <https://linuxacademy.sigstr.net/uc/5dd800d5057c8500aedc6509>



© Linux Academy, 2019. All Rights Reserved.
Pinehead® and the Linux Academy Logo® are registered trademarks of Linux Academy in the U.S. and other countries. Linux® is a registered trademark of Linus Torvalds in the U.S. and other countries.

**Comment by jluk** [comment] 2020-01-15 22:22
It looks like upgrade resolved the previous issue, so closing for that.

For the new error returned the following is an explanation.

The kubectl autoscale cmd handles the horizontal pod autoscaler, a concept to scale pods within k8s. Enabling HPA does not satisfy the requirements for setting a min max node target for AKS since HPA only scales pods.

To run an update of the max and min count for AKS, it requires the cluster autoscaler, which handles scaling of nodes backing the cluster. You need to run the --enable-cluster-autoscaler flag mentioned by the error via az to turn on the add-on on the AKS cluster.

This documentation explains both.
https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler

**Closed by jluk** 2020-01-15 22:22 UTC
Labels: AKS, Service Attention

**Comment by timlawless-la** [comment] 2020-01-16 14:54
Hi Justin,

Interesting. I’d been over that documentation before, but not looked closely enough to understand the differentiation. I’ll try and re-test later. That does leave me with more questions than when I started, which regards to the problem I was originally trying to fix, but thank you.

Thanks,

Tim

 <https://linuxacademy.com/>
 	#1 Learn-by-Doing Multicloud Training Platform
 	 	 	Tim Lawless
Training Architect

125 Bear Creek Parkway. Keller. Texas 76248
LinuxAcademy.com <https://linuxacademy.com/> <https://linuxacademy.sigstr.net/uc/5dd800d5057c8500aedc6509>



© Linux Academy, 2019. All Rights Reserved.
Pinehead® and the Linux Academy Logo® are registered trademarks of Linux Academy in the U.S. and other countries. Linux® is a registered trademark of Linus Torvalds in the U.S. and other countries.
