### ISSUE TITLE
az aks nodepool add with --vnet-subnet-id does not use vnet for nodepool

### ISSUE THREAD

**Issue by zeroX-tj** [Azure/azure-cli#10984] opened 2019-10-25 15:37 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am trying to add a nodepool to an existing AKS cluster with a different vnet-id as the main pool 
In the documentation there is an option to specify the subnet id https://docs.microsoft.com/bs-latn-ba/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest#ext-aks-preview-az-aks-nodepool-add

**To Reproduce**

> az aks nodepool add --subscription "Faktion AXA ADP" --resource-group "axa-prod" --cluster-name "adpaxaaksprod" --name "mempool" --node-count 1 --node-vm-size "Standard_DS14_v2" --enable-cluster-autoscaler --min-count 1 --max-count 6 --node-taints "type=worker:NoSchedule" --priority "Low" --vnet-subnet-id "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/RGNAME/providers/Microsoft.Network/virtualNetworks/customer-network-prod/subnets/newpool-subnet" --kubernetes-version 1.13.10

**Expected behavior**
I would expect the nodepool to be using addresses from the specified subnet. Currently it is taking addresses from the subnet where AKS is deployed

**Environment summary**
The existing cluster is using the Azure CNI for networking
```
Linux-5.0.0-32-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

Extensions:
interactive 0.4.3
aks-preview 0.4.17

```

**Comment by jluk** [comment] 2019-12-16 22:38
@zeroX-tj today all the subnets in each nodepool must align, hence the behavior you are seeing is by design. we have this functionality on the roadmap to enable a distinct subnet per pool which can be tracked here. https://github.com/Azure/AKS/issues/1338

closing as by design, with a redirection to the requested feature.

**Closed by jluk** 2019-12-16 22:38 UTC
Labels: AKS, Service Attention
