### ISSUE TITLE
az vmss update --capacity-reservation-group  exception (preview)

### ISSUE THREAD

**Issue by TiTi** [Azure/azure-cli#27522] opened 2023-10-04 14:24 UTC
### Describe the bug

I'm trying to associate a capacity reservation group to a VMSS but i got an exception.

This command is in preview but I wanted to report the behavior as I can't do that.

### Related command

az vmss update --capacity-reservation-group

### Errors

```
PS /home/adm> az vmss update --name p00002-pt-az3 --resource-group pr-asr-pgs-prd --capacity-reservation-group /subscriptions/<silenced>/resourceGroups/PR-ASR-PGS-PRD/providers/Microsoft.Compute/capacityReservationGroups/crg-az3
Argument '--capacity-reservation-group' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'capacity_reservation'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 452, in cached_put
    return _put_operation()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 446, in _put_operation
    result = operation(**kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 4002, in update_vmss
    vmss.virtual_machine_profile.capacity_reservation = capacity_reservation
AttributeError: 'NoneType' object has no attribute 'capacity_reservation'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
PS /home/adm>
```

### Issue script & Debug output

```
PS /home/adm> az vmss update --name p00002-pt-az3 --resource-group pr-asr-pgs-prd --capacity-reservation-group /subscriptions/<silenced>/resourceGroups/PR-ASR-PGS-PRD/providers/Microsoft.Compute/capacityReservationGroups/crg-az3 --debug
cli.knack.cli: Command arguments: ['vmss', 'update', '--name', 'p00002-pt-az3', '--resource-group', 'pr-asr-pgs-prd', '--capacity-reservation-group', '/subscriptions/<silenced>/resourceGroups/PR-ASR-PGS-PRD/providers/Microsoft.Compute/capacityReservationGroups/crg-az3', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fbd1c0a01f0>, <function OutputProducer.on_global_arguments at 0x7fbd1bfbad30>, <function CLIQuery.on_global_arguments at 0x7fbd1bf52310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'vmss': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.176        59       237
cli.azure.cli.core: Total (1)                 0.176        59       237
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.075         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.075         1         1  
cli.azure.cli.core: Loaded 60 groups, 238 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : vmss update
cli.azure.cli.core: Command table: vmss update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fbd1b3f6430>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/adm/.azure/commands/2023-10-04.14-20-21.vmss_update.389.log'.
az_command_data_logger: command args: vmss update --name {} --resource-group {} --capacity-reservation-group {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fbd1b3a0040>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fbd1b3d60d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fbd1b35fee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fbd1bfbadc0>, <function CLIQuery.handle_query_parameter at 0x7fbd1bf523a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fbd1b35fe50>]
Argument '--capacity-reservation-group' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 4106
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 4106
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1696512356' -> 1696512356
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<silenced>/resourceGroups/pr-asr-pgs-prd/providers/Microsoft.Compute/virtualMachineScaleSets/p00002-pt-az3?api-version=2023-03-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '2692bc94-62c1-11ee-8cb2-b2126e3c0c8f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vmss update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --capacity-reservation-group --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (RPM) azsdk-python-azure-mgmt-compute/30.0.0 Python/3.9.14 (Linux-5.4.0-1109-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<silenced>/resourceGroups/pr-asr-pgs-prd/providers/Microsoft.Compute/virtualMachineScaleSets/p00002-pt-az3?api-version=2023-03-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/GetVMScaleSet3Min;854,Microsoft.Compute/GetVMScaleSet30Min;5509'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '63d447fc-df5c-4c67-b3dd-0bf4aafc813a'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '4f528462-f0da-4833-9eae-d0b1f0e07f2c'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20231004T142021Z:4f528462-f0da-4833-9eae-d0b1f0e07f2c'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 04 Oct 2023 14:20:21 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "name": "p00002-pt-az3",
  "id": "/subscriptions/<silenced>/resourceGroups/pr-asr-pgs-prd/providers/Microsoft.Compute/virtualMachineScaleSets/p00002-pt-az3",
  "type": "Microsoft.Compute/virtualMachineScaleSets",
  "location": "francecentral",
  "tags": {
    "app-name": "pgs",
    "atemi": "4848",
    "autoshutdownschedule": "noautoshutdown",
    "build-tool": "iac",
    "build_info_demande": "",
    "build_info_eul": "",
    "builder": "sco",
    "criticality": "standard",
    "data-classification": "c3",
    "datadog-monitored": "no",
    "disablestartandstop": "none",
    "environment": "prd",
    "expo": "prv",
    "owner": "dea",
    "routing-hypervision": "none"
  },
  "properties": {
    "singlePlacementGroup": false,
    "orchestrationMode": "Flexible",
    "provisioningState": "Succeeded",
    "uniqueId": "a6f7551a-0923-453a-9489-a789eb9eb012",
    "platformFaultDomainCount": 1,
    "constrainedMaximumCapacity": false
  },
  "zones": [
    "3"
  ]
}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 4106
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 452, in cached_put
    return _put_operation()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 446, in _put_operation
    result = operation(**kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 4002, in update_vmss
    vmss.virtual_machine_profile.capacity_reservation = capacity_reservation
AttributeError: 'NoneType' object has no attribute 'capacity_reservation'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'NoneType' object has no attribute 'capacity_reservation'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 452, in cached_put
    return _put_operation()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 446, in _put_operation
    result = operation(**kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 4002, in update_vmss
    vmss.virtual_machine_profile.capacity_reservation = capacity_reservation
AttributeError: 'NoneType' object has no attribute 'capacity_reservation'
az_command_data_logger: 'NoneType' object has no attribute 'capacity_reservation'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 452, in cached_put
    return _put_operation()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 446, in _put_operation
    result = operation(**kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 4002, in update_vmss
    vmss.virtual_machine_profile.capacity_reservation = capacity_reservation
AttributeError: 'NoneType' object has no attribute 'capacity_reservation'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fbd1b3f6670>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.831 seconds (init: 0.128, invoke: 0.703)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7252 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/adm/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
PS /home/adm>
```

### Expected behavior

No exception
VMSS associated to capacity reservation group

### Environment Summary

Azure cloud shell
```
PS /home/adm> az version                                                                                                                                                         
{
  "azure-cli": "2.53.0",
  "azure-cli-core": "2.53.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ai-examples": "0.2.5",
    "ml": "2.20.0",
    "ssh": "2.0.1"
  }
}
```

**Comment by yonzhan** [comment] 2023-10-04 14:24
Thank you for opening this issue, we will look into it.

**Comment by ReaNAiveD** [comment] 2023-10-10 02:37
@TiTi Hi, thank you for reporting this issue. I tried to replicate the error you described, but I was not able to. I noticed that the information of the vmss fetched looks strange.

> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {
>   "name": "p00002-pt-az3",
>   "id": "/subscriptions/<silenced>/resourceGroups/pr-asr-pgs-prd/providers/Microsoft.Compute/virtualMachineScaleSets/p00002-pt-az3",
>   "type": "Microsoft.Compute/virtualMachineScaleSets",
>   "location": "francecentral",
>   "tags": {
>     "app-name": "pgs",
>     "atemi": "4848",
>     "autoshutdownschedule": "noautoshutdown",
>     "build-tool": "iac",
>     "build_info_demande": "",
>     "build_info_eul": "",
>     "builder": "sco",
>     "criticality": "standard",
>     "data-classification": "c3",
>     "datadog-monitored": "no",
>     "disablestartandstop": "none",
>     "environment": "prd",
>     "expo": "prv",
>     "owner": "dea",
>     "routing-hypervision": "none"
>   },
>   "properties": {
>     "singlePlacementGroup": false,
>     "orchestrationMode": "Flexible",
>     "provisioningState": "Succeeded",
>     "uniqueId": "a6f7551a-0923-453a-9489-a789eb9eb012",
>     "platformFaultDomainCount": 1,
>     "constrainedMaximumCapacity": false
>   },
>   "zones": [
>     "3"
>   ]
> }

Could you please share with me how you created the vmss? This might help us identify the root cause of the problem. I appreciate your cooperation.

**Comment by TiTi** [comment] 2023-10-10 08:02
Hello @ReaNAiveD 
What's strange?

The VMSS was created with 0 instance count. And then we added some machines inside by creating them.
We did not use manual (or automatic) scaling.  
In fact it was existing machines (that were not in a scaleset) we had to recreate with the existing disks/nic so that they end up in the scaleset.  
We do that for max spreading and ability to do capacity reservation in Azure Site Recovery.

The vmss is created through terraform 1.4.6 with azurerm provider 3.75.0  
Basically here is the output of the `terraform plan`:

```
17:30:45    # module.vmss_new["pt-az3"].azurerm_orchestrated_virtual_machine_scale_set.orchestrated_vmss[0] will be created
17:30:45    + resource "azurerm_orchestrated_virtual_machine_scale_set" "orchestrated_vmss" {
17:30:45        + extension_operations_enabled  = (known after apply)
17:30:45        + extensions_time_budget        = "PT1H30M"
17:30:45        + id                            = (known after apply)
17:30:45        + instances                     = 0
17:30:45        + location                      = "francecentral"
17:30:45        + max_bid_price                 = -1
17:30:45        + name                          = (known after apply)
17:30:45        + platform_fault_domain_count   = 1
17:30:45        + priority                      = "Regular"
17:30:45        + resource_group_name           = "pr-asr-pgs-prd"
17:30:45        + single_placement_group        = false
17:30:45        + tags                          = {
17:30:45            + "app-name"             = "pgs"
17:30:45            + "atemi"                = "4848"
17:30:45            + "autoshutdownschedule" = "noautoshutdown"
17:30:45            + "build-tool"           = "iac"
17:30:45            + "build_info_demande"   = ""
17:30:45            + "build_info_eul"       = ""
17:30:45            + "builder"              = "sco"
17:30:45            + "criticality"          = "standard"
17:30:45            + "data-classification"  = "c3"
17:30:45            + "datadog-monitored"    = "no"
17:30:45            + "disablestartandstop"  = "none"
17:30:45            + "environment"          = "prd"
17:30:45            + "expo"                 = "prv"
17:30:45            + "owner"                = "dea"
17:30:45            + "routing-hypervision"  = "none"
17:30:45          }
17:30:45        + unique_id                     = (known after apply)
17:30:45        + zone_balance                  = false
17:30:45        + zones                         = [
17:30:45            + "3",
17:30:45          ]
17:30:45  
17:30:45        + source_image_reference {
17:30:45            + offer     = "WindowsServer"
17:30:45            + publisher = "MicrosoftWindowsServer"
17:30:45            + sku       = "2019-Datacenter"
17:30:45            + version   = "latest"
17:30:45          }
17:30:45      }
17:30:45 
```

**Comment by TiTi** [comment] 2023-10-10 08:07
Note that since then we found this documentation: https://learn.microsoft.com/en-us/azure/virtual-machines/capacity-reservation-associate-virtual-machine-scale-set-flex#associate-a-new-virtual-machine-scale-set-to-a-capacity-reservation-group

Basically saying the association should be made at vmss creation.
We added that to our vmss creation since.  
(but we still end up with unability to associate VM declared in ASR with the reservation)

**Comment by ReaNAiveD** [comment] 2023-10-11 02:04
@grizzlytheodore Hi, please take a look at this issue. I found that there is no `virtualMachineProfile` in the `property` of the vmss fetched by `GET` request. Is this by design or a bug?

**Comment by Sharmistha-Rai** [comment] 2023-10-12 04:45
Hi team - It seems like you are using Azure Site Recovery, please correct me if I'm wrong. Capacity reservation in ASR for VMSS is not yet supported.

**Comment by sandeepraichura** [comment] 2023-10-12 18:33
@TiTi - I will close this one as the scenario is by design and not supported yet.  Please reopen if the issue isn't addressed.

**Closed by sandeepraichura** 2023-10-12 18:33 UTC
Labels: Compute, Service Attention, question, customer-reported, Auto-Assign, Azure CLI Team
