### ISSUE TITLE
Application Gateway dynamic internal ip shows as null

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2174] opened 2017-02-20 07:24 UTC
Create a new frontend-ip config element of type internal. Please note that we support two types of internal ip configuration - dynamic or static. In dynamic an internal ip is system generated while in static, its user chosen. Command below creates a dynamic internal ip but that ip is either not created properly or not shown in the output.

azureuser@amitubuntu15:~$ appgw frontend-ip create -n appgwinternal --subnet default --vnet-name azurewebsitetest  --gateway-name azurewebsitetest -g azurewebsitetest

  {
    "etag": "W/\"7af17ef0-87d1-447c-9a18-25dd82048698\"",
    "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendIPConfigurations/appgwinternal",
    "name": "appgwinternal",
    "privateIpAddress": null,
    "privateIpAllocationMethod": "Dynamic",
    "provisioningState": "Succeeded",
    "publicIpAddress": null,
    "resourceGroup": "azurewebsitetest",
    "subnet": {
      "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/virtualNetworks/azurewebsitetest/subnets/default",
      "resourceGroup": "azurewebsitetest"
    }
  }

**Comment by tjprescott** [comment] 2017-02-20 18:55
I agree that this does not seem to work.  I had an issue open for this very issue (Issue #526) but never received any guidance from the service team.  As far as I can tell, having a public and private IP configuration doesn't seem to be supported.

In any case, the CLI logic is correct.

- If you send a public-ip-address, a public configuration is created
- If you send a subnet reference without a private IP address, a dynamic internal configuration is created
- If you send a subnet reference with a private IP address, a static internal configuration is created

**Comment by tjprescott** [comment] 2017-03-07 16:25
This is a service issue as far as I can tell, so I am moving this to the backlog.

**Comment by yonzhan** [comment] 2019-12-23 09:30
add to S165.

**Comment by haroldrandom** [comment] 2020-02-14 19:34
seems like the bug described in issue body has been fixed on serivice side. I can't reproduce.

The problem Travis menetioned also resolved. Nowadays, the restriction of frontend ip is listed in [Application Gateway Frontend IP](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-components#frontend-ip-addresses). By default in CLI, it's allow to create both public ip and private ip.

Feel free to reopen it I miss something.

**Comment by rudolfdobias** [comment] 2020-03-23 18:56
Unfortunately I ran into it right now:

`    "frontendIpConfigurations": [
      {
        "etag": "W/\"5093649c-5263-40be-b579-c2f85dde5717\"",
        "id": "/subscriptions/XXXX/resourceGroups/rg_agw_stagedev/providers/Microsoft.Network/applicationGateways/agw_stage/frontendIPConfigurations/fc-default",
        "name": "fc-default",
        "privateIpAddress": null,
        "privateIpAllocationMethod": "Dynamic",
        "provisioningState": "Updating",
        "publicIpAddress": {
          "id": "/subscriptions/XXXX/resourceGroups/rg_agw_stagedev/providers/Microsoft.Network/publicIPAddresses/ip-stagedev-gatway",
          "resourceGroup": "rg_agw_stagedev"
        },
        "resourceGroup": "rg_agw_stagedev",
        "subnet": null,
        "type": "Microsoft.Network/applicationGateways/frontendIPConfigurations"
      },
      {
        "etag": "W/\"5093649c-5263-40be-b579-c2f85dde5717\"",
        "id": "/subscriptions/XXXX/resourceGroups/rg_agw_stagedev/providers/Microsoft.Network/applicationGateways/agw_stage/frontendIPConfigurations/test",
        "name": "test",
        "privateIpAddress": null,
        "privateIpAllocationMethod": "Dynamic",
        "provisioningState": "Updating",
        "publicIpAddress": null,
        "resourceGroup": "rg_agw_stagedev",
        "subnet": {
          "id": "/subscriptions/XXXX/resourceGroups/rg_network/providers/Microsoft.Network/virtualNetworks/vnet_cluster/subnets/staging_gate",
          "resourceGroup": "rg_network"
        },
        "type": "Microsoft.Network/applicationGateways/frontendIPConfigurations"
      }
    ]
`

It's hard to provide replication log, but at least this way: 
1) created the AGW only with public IP
2) Added some rules, tested functionality 
3) Configured new private IP -> this state

**Comment by KarenHammons** [comment] 2020-03-24 16:46
@amitsriva FYI looks like this is occurring again.

**Comment by surajmb** [comment] 2020-03-30 05:10
@rudolfdobias , can you let me know the provisioning state of the AppGw resource (not the sub-resources like frontend IP)? And since your private IP allocation method is Dynamic, an IP address will be assigned once you attach a listener to it, have you tried that?

**Comment by RakeshMohanMSFT** [comment] 2022-09-21 06:00
Please reopen this if the solution provided by @surajmb does not work.

**Closed by RakeshMohanMSFT** 2022-09-21 06:00 UTC
Labels: Service Attention, Network - Application Gateway
