### ISSUE TITLE
Azure CLI interactive bug

### ISSUE THREAD

**Issue by austinloveless** [Azure/azure-cli#10152] opened 2019-08-05 16:54 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.70

Extensions:
interactive 0.4.3

```

**Comment by code4clouds** [comment] 2019-08-05 17:02
It can be easily reproduced in the Azure Portal / Cloud Shell:

``` bash
VERBOSE: Authenticating to Azure ...
VERBOSE: Building your Azure drive ...
Azure:/
PS Azure:\> az interactive
This command is in preview. It may be changed/removed in a future release.
The command failed with an unexpected error. Here is the traceback:

No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/home/julio/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/home/julio/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'

To open an issue, please run: 'az feedback'
Azure:/

```

**Comment by yugangw-msft** [comment] 2019-08-05 22:13
dupe of #10088

**Closed by yugangw-msft** 2019-08-05 22:13 UTC

**Comment by code4clouds** [comment] 2019-08-06 21:26
@austinloveless   fyi... @yugangw-msft posted a workaround in #10088.
