### ISSUE TITLE
az interactive After prompt this command Microsoft  Azure sandbox shows below message

### ISSUE THREAD

**Issue by Julietuba** [Azure/azure-cli#24339] opened 2022-10-21 18:23 UTC
## Describe the bug

**Command Name**
`az version`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az version`

## Environment Summary
```
Linux-5.4.0-1094-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.41.0

Extensions:
interactive 0.4.5
ai-examples 0.2.5
ml 2.10.0
ssh 1.1.2

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-10-21 23:20
Duplicate of https://github.com/Azure/azure-cli/issues/24213

**Closed by yonzhan** 2022-10-21 23:20 UTC
Labels: Interactive, customer-reported, Auto-Assign
