### ISSUE TITLE
Unable to create "CorrelationFilter" rule in ServiceBus subscription from AZ CLI - 'az servicebus topic subscription rule create'

### ISSUE THREAD

**Issue by gopi158** [Azure/azure-cli#14581] opened 2020-07-29 20:44 UTC
Hello,

I am able to create ServiceBus subscription rules/filters through the Azure portal, but I am not able to create the same subscription rule/filter through AZ CLI.

while creating through az-cli, I am getting below error.
az servicebus topic subscription rule create --resource-group myresourcegroup --namespace-name mynamespace --topic-name mytopic --subscription-name mysubscription --name myrule --label myvalue --debug

> msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
> msrest.http_logger :     'Date': 'Wed, 29 Jul 2020 20:12:52 GMT'
> msrest.http_logger : Response content:
> msrest.http_logger : {"error":{"message":"Value cannot be null.\r\nParameter name: sqlExpression CorrelationId: 449c0b40-baf6-4830-9c4b-2a19c0d01ad3","code":"BadRequest"}}
> msrest.exceptions : Operation returned an invalid status code 'Bad Request'
> cli.azure.cli.core.util : BadRequest - Value cannot be null.
> Parameter name: sqlExpression CorrelationId: 449c0b40-baf6-4830-9c4b-2a19c0d01ad3
> BadRequest - Value cannot be null.
> Parameter name: sqlExpression CorrelationId: 449c0b40-baf6-4830-9c4b-2a19c0d01ad3
> az_command_data_logger : exit code: 1

I don't see any option to pass the _filterType=**CorrelationFilter**_ parameter in the below command.
[az servicebus topic subscription rule create ](https://docs.microsoft.com/en-us/cli/azure/servicebus/topic/subscription/rule?view=azure-cli-latest#az-servicebus-topic-subscription-rule-create)

I see the **filterType** parameter is available in [ServiceBus Template](https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/2017-04-01/namespaces/topics/subscriptions/rules#template-format) template too.

Please let me if I am using any wrong command for this or do we have any other az-cli command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fd5960a-ea47-7542-6837-3e4e49e95d0a
* Version Independent ID: c8a9f5b6-2a2f-4820-3be4-c87e3896a6b7
* Content: [az servicebus topic subscription rule](https://docs.microsoft.com/en-us/cli/azure/servicebus/topic/subscription/rule?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/servicebus/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/servicebus/_help.py)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment] 2020-07-30 01:20
Hi @gopi158 , thanks for reporting, we will look at it.

**Comment by LayZeeDK** [comment] 2020-08-28 09:24
Duplicate of https://github.com/Azure/azure-cli/issues/11389.

**Comment by Saglodha** [comment] 2022-02-21 14:38
Hi Team,

Apologies for the delay here. We have been looking into it and would get back with an update soon.

**Comment by Saglodha** [comment] 2022-04-06 07:32
Our latest release fixes this issue: https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#service-bus. 

Please retry the operation and let us know in case of any discrepancy. Thanks

**Closed** 2022-04-28 08:01 UTC
Labels: Service Attention, Service Bus, customer-reported, needs-team-attention, needs-author-feedback, no-recent-activity
