### ISSUE TITLE
az extension add -n azure-devops fails when Azure CLI was installed via pip under Python 3.11.0

### ISSUE THREAD

**Issue by brianrob** [Azure/azure-cli#24458] opened 2022-10-27 15:21 UTC
**Related command**
az extension add -n azure-devops

**Describe the bug**
Adding the azure-devops extension fails when the Azure CLI was installed via pip under Python 3.11.0:

```
az extension add -n azure-devops
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: argument _subcommand: conflicting subparser: add
Traceback (most recent call last):
  File "D:\a\_work\_tool\Python\3.11.0\x64\Lib\site-packages\knack\cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\_work\_tool\Python\3.11.0\x64\Lib\site-packages\azure\cli\core\commands\__init__.py", line 565, in execute
    self.parser.load_command_table(self.commands_loader)
  File "D:\a\_work\_tool\Python\3.11.0\x64\Lib\site-packages\azure\cli\core\parser.py", line 100, in load_command_table
    command_parser = subparser.add_parser(command_verb,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\_work\_tool\Python\3.11.0\x64\Lib\argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument _subcommand: conflicting subparser: add
To open an issue, please run: 'az feedback'
```

**To Reproduce**
```
1. Install Python 3.11.0.
2. python -m pip install --upgrade pip
3. pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
4. az extension add -n azure-devops
```

**Expected behavior**
The extension is successfully installed.

**Environment summary**
Observed this failure in AzureDevOps running Windows 10.  Note, this does not fail if installing using Python 3.10.x.

**Comment by yonzhan** [comment] 2022-10-27 23:42
route to CXP team

**Comment by navba-MSFT** [comment] 2022-10-28 02:46
Removing CXP attention label for Devops issue.

**Comment by bebound** [comment] 2022-10-31 07:18
Duplicate of https://github.com/Azure/azure-cli/issues/23015

Workaround: https://github.com/Azure/azure-cli/pull/24497

-------

3.11 is not supported now.
You can find the progress here: https://github.com/Azure/azure-cli/issues/24494

**Comment by Arvindgade** [comment] 2022-12-21 06:55
@brianrob could you please check the below links provided some work around.
https://github.com/Azure/azure-cli/issues/24494
https://github.com/Azure/azure-cli/pull/24497
Hope this will work.

**Comment by brianrob** [comment] 2023-01-03 19:53
> @brianrob could you please check the below links provided some work around. #24494 #24497 Hope this will work.

Thanks @Arvindgade.  I have downgraded to Python 3.10 to resolve this.

**Comment by v-soujanya** [comment] 2023-03-02 09:10
@brianrob Hi, we are closing the issue as its working for now, please feel free to reopen if any issues.

**Closed** 2023-03-02 09:11 UTC
Labels: Service Attention, customer-reported, Installation, DevOps, Auto-Assign
