### ISSUE TITLE
az aks get-versions doesn't return tsv output format correctly

### ISSUE THREAD

**Issue by softveda** [Azure/azure-cli#13399] opened 2020-05-08 10:00 UTC
The coomand
az aks get-versions -l &lt;location&gt; -o tsv
doesn't work as expected. 
Expected: to just return the versions in tsv format
Actual: /subscriptions/&lt;subscription id&gt;/providers/Microsoft.ContainerService/locations/australiaeast/orchestrators  default 6      Microsoft.ContainerService/locations/orchestrators

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-versions)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-05-08 12:43
aks

**Comment by jluk** [comment] 2020-05-08 20:47
Acknowledge, reproducing this as well and logging a backlog item.

**Comment by seanmck** [comment] 2020-06-20 22:56
Unfortunately, this is just how tsv output works in the Azure CLI - it only outputs the top level properties. Since the version information is embedded in a collection, it doesn't get displayed. We would need the suggestion in #8344 to provide a better experience. Closing since this is not currently actionable for AKS.

**Closed by seanmck** 2020-06-20 22:56 UTC
Labels: AKS, Service Attention, customer-reported, question
