### ISSUE TITLE
az storage entity query function error on fedora 36

### ISSUE THREAD

**Issue by zale1983** [Azure/azure-cli#22428] opened 2022-05-13 07:45 UTC
## Describe the bug

**Command Name**
`az storage entity query`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 683, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 837, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage entity query --help`

## Environment Summary
```
Linux-5.17.5-300.fc36.x86_64-x86_64-with-glibc2.35, Fedora Linux 36 (Workstation Edition)
Python 3.10.4
Installer: RPM

azure-cli 2.36.0

Extensions:
aks-preview 0.5.68

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-05-13 09:51
storage

**Comment by bebound** [comment] 2022-05-15 09:37
Duplicate of https://github.com/Azure/azure-cli/issues/22235

Installing `python3.6` should fix the issue. We have plan to build RPM for Fedora: https://github.com/Azure/azure-cli/issues/22278

**Closed** 2022-05-15 14:55 UTC
Labels: Storage, customer-reported, Auto-Assign
