### ISSUE TITLE
Release of MSI version 2021-09-30-preview

### ISSUE THREAD

**Issue by arndt-s** [Azure/azure-cli#22112] opened 2022-04-19 13:15 UTC
**Resource Provider**
MSI / Managed Identity

**Description of Feature or Work Requested**
We would like to release a new preview version that reflects new MSI api "listAssociatedResources" introduced in swagger (link below)

**Minimum API Version Required**
2021-09-30-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/msi/resource-manager/Microsoft.ManagedIdentity/preview/2021-09-30-preview/ManagedIdentity.json

**Target Date**
May 2022

**Comment by yonzhan** [comment] 2022-04-19 14:41
Managed Identity

**Comment by zhoxing-ms** [comment] 2022-04-20 02:00
@arndt-s Could you please provide the PR of Swagger change? 
And may I ask are there any requirements for new CLI commands and parameters? Or do we just need to upgrade the api-version to 2021-09-30-preview?

**Comment by PARADISSEEKR** [comment] 2022-04-21 08:32
The new SDK has not been released to pypi yet https://pypi.org/project/azure-mgmt-msi/#history

**Comment by arndt-s** [comment] 2022-04-25 13:29
@PARADISSEEKR it has been released: https://pypi.org/project/azure-mgmt-msi/6.0.0b2/
The PR for the python SDK is https://github.com/Azure/sdk-release-request/issues/2570

**Comment by PARADISSEEKR** [comment] 2022-04-28 03:34
> @PARADISSEEKR it has been released: https://pypi.org/project/azure-mgmt-msi/6.0.0b2/ The PR for the python SDK is [Azure/sdk-release-request#2570](https://github.com/Azure/sdk-release-request/issues/2570)

Hi @arndt-s CLI cannot use it due to inconsistency of api version and file name, please release the correct version.
![image](https://user-images.githubusercontent.com/37168047/165670786-d9eb64d6-f387-4e19-bb6b-77afa48ff3b2.png)
![image](https://user-images.githubusercontent.com/37168047/165670849-377ba65d-eaa3-46cc-9ef1-a49b4f6d47c6.png)

**Comment by zhoxing-ms** [comment] 2022-04-28 03:47
I guess the inconsistency between the api-version and the folder name is caused by a mistake from this PR https://github.com/Azure/azure-rest-api-specs/pull/18123#discussion_r860452876

**Comment by arndt-s** [comment] 2022-04-28 15:27
Fix is on the way: https://github.com/Azure/azure-rest-api-specs/pull/18850

**Comment by msyyc** [comment] 2022-04-29 02:52
Hi, we have fixed in https://github.com/Azure/azure-rest-api-specs/pull/18859 and we will release a new SDK version soon: https://github.com/Azure/sdk-release-request/issues/2750

**Comment by msyyc** [comment] 2022-04-29 03:12
Hi, it will be fixed in https://github.com/Azure/azure-rest-api-specs/pull/18860 and we will release a new version soon: https://github.com/Azure/sdk-release-request/issues/2750

**Comment by arndt-s** [comment] 2022-05-18 10:43
@PARADISSEEKR does your change add "listAssociatedResources" method to the MSI commands? I can only see that the api version got bumped up.

**Comment by arndt-s** [comment] 2022-05-18 10:48
@PARADISSEEKR another thing I wanted to clarify: Will calls going to MSI control plane still be using `2018-11-30` by default and only `2021-09-30-preview` when specified?

**Comment by zhoxing-ms** [comment] 2022-05-18 11:32
> does your change add "listAssociatedResources" method to the MSI commands? I can only see that the api version got bumped up.

@PARADISSEEKR  Please  remember to add new commands for method `listAssociatedResources` to `identity` module

> another thing I wanted to clarify: Will calls going to MSI control plane still be using 2018-11-30 by default and only 2021-09-30-preview when specified?

@arndt-s At present, the api-version in the official CLI can only set a fixed version in the RP level, it does not support allowing users to specify the api-version for each command. Therefore, the version currently used is `2021-09-30-preview`

**Comment by arndt-s** [comment] 2022-05-18 11:36
@zhoxing-ms this API version is in public preview and for example not available in sovereign clouds yet.

**Closed** 2022-05-19 09:54 UTC
Labels: Managed Identity, feature-request

**Comment by arndt-s** [comment] 2022-05-19 09:57
> @zhoxing-ms this API version is in public preview and for example not available in sovereign clouds yet. Will the release of azure-cli be a preview release or an official one?

@zhoxing-ms if release of azure-cli will be official we cannot have the preview version on it as all calls regarding MSI will fail in regions where preview apiVersion is not available.

**Comment by zhoxing-ms** [comment] 2022-05-19 09:58
@arndt-s We only upgraded the api-version in the profile used by public cloud, which will not affect the api-version used by Azure Stack or other sovereign clouds

**Comment by arndt-s** [comment] 2022-05-19 09:58
Thank you for clarification.

**Comment by zhoxing-ms** [comment] 2022-05-19 10:01
@arndt-s We release the official CLI for public cloud, I‘d like to confirm whether there are regions that are not available in the public cloud?

**Comment by arndt-s** [comment] 2022-05-19 11:05
@zhoxing-ms I can confirm that all regions in public can serve traffic for `2021-09-30-preview`
