### ISSUE TITLE
Not found 'antlr4' module when run command of `az vm availability-set ` in azure cli 

### ISSUE THREAD

**Issue by Hidden-22** [Azure/azure-cli#15326] opened 2020-09-28 06:00 UTC
## Describe the bug

**Command Name**
`az vm availability-set list`

**Errors:**
```
No module named 'antlr4'
Traceback (most recent call last):
lib/python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
dist-packages/azure/cli/core/__init__.py, ln 300, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/vm/__init__.py, ln 31, in load_arguments
    from azure.cli.command_modules.vm._params import load_arguments
azure/cli/command_modules/vm/_params.py, ln 31, in <module>
    from azure.cli.command_modules.monitor.actions import get_period_type
azure/cli/command_modules/monitor/actions.py, ln 7, in <module>
    import antlr4
ModuleNotFoundError: No module named 'antlr4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm availability-set list`

## Environment Summary
```
Linux-5.4.0-48-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment] 2020-09-28 13:42
hi @Hidden-22  could you pls try uninstall firstly, then install latest Azure CLI? This is an known issue in #14011

**Comment by fengzhou-msft** [comment] 2020-10-20 02:22
Duplicate of #14011

**Closed by fengzhou-msft** 2020-10-20 02:22 UTC
Labels: Packaging
