### ISSUE TITLE
FileNotFoundError on broken symbolic link

### ISSUE THREAD

**Issue by brollb** [Azure/azure-cli#10362] opened 2019-08-28 18:58 UTC
`upload-batch` fails when it encounters a broken symbolic link

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
[Errno 2] No such file or directory: '/home/brbroll/current-target/inspection/lf-vs-human/labels'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
storage/v2018_11_09/blob/blockblobservice.py, ln 453, in create_blob_from_path
    count = path.getsize(file_path)
usr/lib/python3.7/genericpath.py, ln 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/brbroll/current-target/inspection/lf-vs-human/labels'
```

## Environment Summary
```
Linux-5.2.9-arch1-1-ARCH-x86_64-with-arch
Python 3.7.4
Shell: bash

azure-cli 2.0.71 *

```

**Comment by achandmsft** [comment] 2019-08-28 23:57
@brollb Thanks for your issue, @Juliehzl could you please take a look?

**Comment by yonzhan** [comment] 2020-05-16 07:59
add to S171

**Comment by zhoxing-ms** [comment] 2020-06-02 08:35
@brollb Could you please show me the specific parameters you used? And have you confirmed the existence of the path `/home/brbroll/current-target/inspection/lf-vs-human/labels`?

**Comment by zhoxing-ms** [comment] 2020-06-16 01:42
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-06-16 01:42 UTC
Labels: OKR3.4 Candidate, Storage
