### ISSUE TITLE
az webapp up failed to create python app

### ISSUE THREAD

**Issue by RyanHill-MSFT** [Azure/azure-cli#13883] opened 2020-06-08 16:28 UTC
## Describe the bug
I've created a python app using visual studio. The IDE doesn't give me the option to deploy to a Linux hosting plan, therefore I tried to use to az webapp up for quick deployment.

**Command Name**
`az webapp up`

**Errors:**
```
'int' object has no attribute 'upper'
Traceback (most recent call last):
Temp\pip-install-umfcm_n2\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 652, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 2993, in webapp_up
azure\cli\command_modules\appservice\custom.py, ln 1390, in create_app_service_plan
azure\cli\command_modules\appservice\utils.py, ln 20, in _normalize_sku
AttributeError: 'int' object has no attribute 'upper'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {} -g {} --sku {} --logs`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76 *

Extensions:
interactive 0.4.1

```

**Comment by yungezz** [comment] 2020-06-09 01:45
@arrownj for awareness

**Comment by panchagnula** [comment] 2020-06-16 20:36
@RyanHill-MSFT thanks for reporting looks like you are using an older version of CLI - can you please update to use the latest version and check if this is resolved.  2.0.76 -> version had some regressions, but these should be fixed the latest version. Thanks

**Comment by RyanHill-MSFT** [comment] 2020-06-16 20:40
@panchagnula cool thanks. does the cli offer a command to update in place, I couldn't find one.

**Comment by panchagnula** [comment] 2020-06-16 21:16
@RyanHill-MSFT depends on how you originally installed CLI
if you use MSI then you need to do a full install if you used pip you can use this https://pypi.org/project/azure-cli/

otherwise you can reference this for installation https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by RyanHill-MSFT** [comment] 2020-06-18 20:14
Will do, @panchagnula.

**Comment by panchagnula** [comment] 2020-07-22 03:45
closing this please open new issue if this is still a problem with the latest version of CLI

**Closed by panchagnula** 2020-07-22 03:45 UTC
Labels: Service Attention, Web Apps
