### ISSUE TITLE
az network list-service-tags --location parameter not working

### ISSUE THREAD

**Issue by oliviercastonguay** [Azure/azure-cli#14394] opened 2020-07-16 12:52 UTC
**Describe the bug**
The "--location" parameter does not return the locations requested.  Instead, it returns all the locations no matter if we specify it or not.

**To Reproduce**
az login
#Both queries below returns the same values
az network list-service-tags --location canadaeast
az network list-service-tags 

**Expected behavior**
az network list-service-tags --location canadaeast should return only the service tags in the --location parameter if the parameter is set.  Otherwise, return all the locations.

**Environment summary**
"azure-cli": "2.5.1",
"azure-cli-command-modules-nspkg": "2.0.3",
"azure-cli-core": "2.5.1",
"azure-cli-nspkg": "3.0.4",
"azure-cli-telemetry": "1.0.4",
"extensions": {}
Powershell version : 5.1.17763.771 
Running on Windows 10 - 1809

**Additional context**
- Will try running the same script on another computer and post the result later
-> Result : Same problem on another computer
- Will try updating Azure CLI to the latest version and post the result later.
-> Same problem after updating CLI to latest build 2.9.1

**Comment by yonzhan** [comment] 2020-07-16 13:01
add to S174

**Comment by MyronFanQiu** [comment] 2020-07-17 01:44
@oliviercastonguay Hi. It's a known issue on server side. https://github.com/Azure/azure-cli/issues/12546. @allegradomel any updates?

**Comment by MyronFanQiu** [comment] 2020-07-17 01:46
@oliviercastonguay To quickly unblock you, there is a `--query` argument for you to filter the response.

**Comment by oliviercastonguay** [comment] 2020-07-17 02:11
> @oliviercastonguay To quickly unblock you, there is a `--query` argument for you to filter the response.

I actually just used a | Where-Object which did the trick for me.  It just appeared a few days ago so thought it would be great to advise.
Thanks !

**Comment by allegradomel** [comment] 2020-08-27 04:06
@oliviercastonguay  thanks for the feedback! From the PowerShell documentation for the same command:

"Please note that the Azure region information you specify will be used as a reference for version (not as a filter based on location). For example, even if you specify -Location eastus2 you will get the list of service tags with prefix details across all regions but limited to the cloud that your subscription belongs to (i.e. Public, US government, China or Germany)"

I have submitted a PR to add this explanation to the CLI doc as well: https://github.com/Azure/azure-cli/pull/14935

**Comment by MyronFanQiu** [comment] 2020-08-27 05:27
@allegradomel In other word, I can say this is by design. Is that correct?

**Comment by allegradomel** [comment] 2020-08-27 15:58
@MyronFanQiu yes

**Comment by MyronFanQiu** [comment] 2020-08-28 02:18
@oliviercastonguay I would close this issue since it's by design confirmed by service team. We had add more explanation into our cmdlet. Feel free to raise any more question.

**Closed by MyronFanQiu** 2020-08-28 02:18 UTC
Labels: Network - Virtual Network, Service Attention
