### ISSUE TITLE
webapp:TimeoutError: [WinError 10060] Deploying a flask application through windows powershell 

### ISSUE THREAD

**Issue by Trelaquix** [Azure/azure-cli#19526] opened 2021-09-10 10:39 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='pythonwordtopdf.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x064CD580>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 169, in _new_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 96, in create_connection
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 353, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 181, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x064CD580>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pythonwordtopdf.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x064CD580>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 3873, in webapp_up
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 441, in enable_zip_deploy
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 3230, in _check_zip_deployment_status
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 76, in get
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 61, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pythonwordtopdf.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x064CD580>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- git clone https://github.com/Trelaquix/python_word_to_pdf_editor.git
- cd into directory
- py -3 -m venv .venv
- .venv\scripts\activate
- pip install -r requirements.txt
- az webapp up --sku B1 --name pythonwordtopdf

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by yonzhan** [comment] 2021-09-10 14:37
route to service team

**Comment by Trelaquix** [comment] 2021-09-15 08:33
Hi, just an update, I managed to fix the deployment issue, however now I'm encountering another issue.

Below are my observations

**Http server errors**

<html>
<body>


HttpStatus | HttpSubStatus | Errors | Description
-- | -- | -- | --
503 | 0 | 20 | Server Unavailable


</body>
</html>


**Application Logs** - Platform logs
```
Warning 2021-09-15T06:58:39.576
INFO  - docker run -d -p 5568:8000 --name pythonwordpdf_0_34b614a5 -e WEBSITE_SITE_NAME=pythonwordpdf -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=pythonwordpdf.azurewebsites.net -e WEBSITE_INSTANCE_ID=5656892a738600b748cd8937def16f99a980ac87bf2ea3ad41fb6ecd9e578037 -e HTTP_LOGGING_ENABLED=1 appsvc/python:3.7_20210709.2  

Ok 2021-09-15T06:58:42.813
INFO  - Initiating warmup request to container pythonwordpdf_0_34b614a5 for site pythonwordpdf
 
Ok 2021-09-15T06:58:58.471
INFO  - Waiting for response to warmup request for container pythonwordpdf_0_34b614a5. Elapsed time = 15.6582049 sec

Error 2021-09-15T06:59:08.758
ERROR - Container pythonwordpdf_0_34b614a5 for site pythonwordpdf has exited, failing site start

Error 2021-09-15T06:59:08.766
ERROR - Container pythonwordpdf_0_34b614a5 didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.

Ok 2021-09-15T06:59:08.818
INFO  - Stopping site pythonwordpdf because it failed during startup.
```

**Container Crash Logs** Python 3.9

```
Container pythonwordpdf_0_813adbfd couldn't be started: Logs = 2021-09-14T16:09:27.033876462Z 
2021-09-14T16:09:27.033918162Z   _____                               
2021-09-14T16:09:27.033925562Z   /  _  \ __________ _________   ____  
2021-09-14T16:09:27.033929662Z  /  /_\  \___   /  |  \_  __ \_/ __ \ 
2021-09-14T16:09:27.033933762Z /    |    \/    /|  |  /|  | \/\  ___/ 
2021-09-14T16:09:27.033937762Z \____|__  /_____ \____/ |__|    \___  >
2021-09-14T16:09:27.033941862Z         \/      \/                  \/ 
2021-09-14T16:09:27.033946062Z 
2021-09-14T16:09:27.033949462Z A P P   S E R V I C E   O N   L I N U X
2021-09-14T16:09:27.033953162Z 
2021-09-14T16:09:27.033956462Z Documentation: http://aka.ms/webapp-linux
2021-09-14T16:09:27.033960062Z Python 3.9.0
2021-09-14T16:09:27.033963562Z Note: Any data outside '/home' is not persisted
2021-09-14T16:09:27.330905957Z Starting OpenBSD Secure Shell server: sshd.
2021-09-14T16:09:27.417827231Z App Command Line not configured, will attempt auto-detect
2021-09-14T16:09:27.418772533Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite
2021-09-14T16:09:27.439611175Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2021-09-14T16:09:27.442253580Z Build Operation ID: |FEKfGMVdC2s=.75526d0c_
2021-09-14T16:09:27.449813095Z Oryx Version: 0.2.20210708.1, Commit: 6ceb6608673b94827bac111ef5ea01c216f92abb, ReleaseTagName: 20210708.1
2021-09-14T16:09:27.450054096Z Output is compressed. Extracting it...
2021-09-14T16:09:27.451408599Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8d97780cf62f570'...
2021-09-14T16:09:52.855897197Z App path is set to '/tmp/8d97780cf62f570'
2021-09-14T16:09:53.013449311Z Detected an app based on Flask
2021-09-14T16:09:53.013475312Z Generating `gunicorn` command for 'app:app'
2021-09-14T16:09:53.590670664Z Writing output script to '/opt/startup/startup.sh'
2021-09-14T16:09:54.151104384Z Using packages from virtual environment antenv located at /tmp/8d97780cf62f570/antenv.
2021-09-14T16:09:54.153499989Z Updated PYTHONPATH to ':/tmp/8d97780cf62f570/antenv/lib/python3.9/site-packages'
2021-09-14T16:09:56.127481030Z [2021-09-14 16:09:56 +0000] [36] [INFO] Starting gunicorn 20.1.0
2021-09-14T16:09:56.128307532Z [2021-09-14 16:09:56 +0000] [36] [INFO] Listening at: http://0.0.0.0:8000 (36)
2021-09-14T16:09:56.134008643Z [2021-09-14 16:09:56 +0000] [36] [INFO] Using worker: sync
2021-09-14T16:09:56.143026961Z [2021-09-14 16:09:56 +0000] [37] [INFO] Booting worker with pid: 37
2021-09-14T16:09:59.037479540Z [2021-09-14 16:09:59 +0000] [37] [ERROR] Exception in worker process
2021-09-14T16:09:59.037510640Z Traceback (most recent call last):
2021-09-14T16:09:59.037516640Z   File "/opt/python/3.9.0/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2021-09-14T16:09:59.037533240Z     worker.init_process()
2021-09-14T16:09:59.037537440Z   File "/opt/python/3.9.0/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2021-09-14T16:09:59.037541240Z     self.load_wsgi()
2021-09-14T16:09:59.037553340Z   File "/opt/python/3.9.0/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2021-09-14T16:09:59.037557440Z     self.wsgi = self.app.wsgi()
2021-09-14T16:09:59.037561040Z   File "/opt/python/3.9.0/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2021-09-14T16:09:59.037564640Z     self.callable = self.load()
2021-09-14T16:09:59.037568640Z   File "/opt/python/3.9.0/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2021-09-14T16:09:59.037572440Z     return self.load_wsgiapp()
2021-09-14T16:09:59.037575840Z   File "/opt/python/3.9.0/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2021-09-14T16:09:59.037579540Z     return util.import_app(self.app_uri)
2021-09-14T16:09:59.037582940Z   File "/opt/python/3.9.0/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2021-09-14T16:09:59.037586740Z     mod = importlib.import_module(module)
2021-09-14T16:09:59.037590140Z   File "/opt/python/3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-09-14T16:09:59.037593940Z     return _bootstrap._gcd_import(name[level:], package, level)
2021-09-14T16:09:59.037597440Z   File "", line 1030, in _gcd_import
2021-09-14T16:09:59.037601540Z   File "", line 1007, in _find_and_load
2021-09-14T16:09:59.037605240Z   File "", line 986, in _find_and_load_unlocked
2021-09-14T16:09:59.037608940Z   File "", line 680, in _load_unlocked
2021-09-14T16:09:59.037612640Z   File "", line 790, in exec_module
2021-09-14T16:09:59.037616340Z   File "", line 228, in _call_with_frames_removed
2021-09-14T16:09:59.037620040Z   File "/tmp/8d97780cf62f570/app.py", line 4, in 
2021-09-14T16:09:59.037623840Z     from docx2pdf import convert
2021-09-14T16:09:59.037627440Z   File "/tmp/8d97780cf62f570/antenv/lib/python3.9/site-packages/docx2pdf/__init__.py", line 13, in 
2021-09-14T16:09:59.037631440Z     __version__ = version(__package__)
2021-09-14T16:09:59.037634940Z   File "/opt/python/3.9.0/lib/python3.9/importlib/metadata.py", line 551, in version
2021-09-14T16:09:59.037638640Z     return distribution(distribution_name).version
2021-09-14T16:09:59.037642940Z   File "/opt/python/3.9.0/lib/python3.9/importlib/metadata.py", line 257, in version
2021-09-14T16:09:59.037646640Z     return self.metadata['Version']
2021-09-14T16:09:59.037654140Z   File "/opt/python/3.9.0/lib/python3.9/importlib/metadata.py", line 245, in metadata
2021-09-14T16:09:59.037658240Z     self.read_text('METADATA')
2021-09-14T16:09:59.037661640Z   File "/opt/python/3.9.0/lib/python3.9/importlib/metadata.py", line 511, in read_text
2021-09-14T16:09:59.037665240Z     return self._path.joinpath(filename).read_text(encoding='utf-8')
2021-09-14T16:09:59.037668840Z AttributeError: 'PosixPath' object has no attribute 'read_text'
2021-09-14T16:09:59.041394548Z [2021-09-14 16:09:59 +0000] [37] [INFO] Worker exiting (pid: 37)
2021-09-14T16:09:59.204186173Z [2021-09-14 16:09:59 +0000] [36] [INFO] Shutting down: Master
2021-09-14T16:09:59.205011874Z [2021-09-14 16:09:59 +0000] [36] [INFO] Reason: Worker failed to boot.
```

**Container Crash Logs** Python 3.7

```
2021-09-15T03:58:23.350757730Z Traceback (most recent call last):
2021-09-15T03:58:23.350764130Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2021-09-15T03:58:23.350783030Z     worker.init_process()
2021-09-15T03:58:23.350787430Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
2021-09-15T03:58:23.350799530Z     self.load_wsgi()
2021-09-15T03:58:23.350803730Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2021-09-15T03:58:23.350807630Z     self.wsgi = self.app.wsgi()
2021-09-15T03:58:23.350811230Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2021-09-15T03:58:23.350815131Z     self.callable = self.load()
2021-09-15T03:58:23.350818831Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2021-09-15T03:58:23.350822631Z     return self.load_wsgiapp()
2021-09-15T03:58:23.350826231Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2021-09-15T03:58:23.350830131Z     return util.import_app(self.app_uri)
2021-09-15T03:58:23.350833731Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
2021-09-15T03:58:23.350837631Z     mod = importlib.import_module(module)
2021-09-15T03:58:23.350841331Z   File "/opt/python/3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module
2021-09-15T03:58:23.350845031Z     return _bootstrap._gcd_import(name[level:], package, level)
2021-09-15T03:58:23.350848631Z   File "", line 1006, in _gcd_import
2021-09-15T03:58:23.350852931Z   File "", line 983, in _find_and_load
2021-09-15T03:58:23.350856831Z   File "", line 967, in _find_and_load_unlocked
2021-09-15T03:58:23.350860631Z   File "", line 677, in _load_unlocked
2021-09-15T03:58:23.350864531Z   File "", line 728, in exec_module
2021-09-15T03:58:23.350868331Z   File "", line 219, in _call_with_frames_removed
2021-09-15T03:58:23.350872231Z   File "/tmp/8d977fb012810d7/app.py", line 4, in 
2021-09-15T03:58:23.350876231Z     from docx2pdf import convert
2021-09-15T03:58:23.350879831Z   File "/tmp/8d977fb012810d7/antenv/lib/python3.7/site-packages/docx2pdf/__init__.py", line 13, in 
2021-09-15T03:58:23.350883931Z     __version__ = version(__package__)
2021-09-15T03:58:23.350887531Z   File "/tmp/8d977fb012810d7/antenv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 994, in version
2021-09-15T03:58:23.350891431Z     return distribution(distribution_name).version
2021-09-15T03:58:23.350896131Z   File "/tmp/8d977fb012810d7/antenv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 640, in version
2021-09-15T03:58:23.350904131Z     return self.metadata['Version']
2021-09-15T03:58:23.350907931Z   File "/tmp/8d977fb012810d7/antenv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 618, in metadata
2021-09-15T03:58:23.350912231Z     self.read_text('METADATA')
2021-09-15T03:58:23.350915831Z   File "/tmp/8d977fb012810d7/antenv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 937, in read_text
2021-09-15T03:58:23.350919631Z     return self._path.joinpath(filename).read_text(encoding='utf-8')
2021-09-15T03:58:23.350923431Z AttributeError: 'PosixPath' object has no attribute 'read_text'
2021-09-15T03:58:23.359289583Z [2021-09-15 03:58:23 +0000] [40] [INFO] Worker exiting (pid: 40)
2021-09-15T03:58:23.512439135Z [2021-09-15 03:58:23 +0000] [37] [INFO] Shutting down: Master
2021-09-15T03:58:23.512519935Z [2021-09-15 03:58:23 +0000] [37] [INFO] Reason: Worker failed to boot.
```

I'm not sure why azure web app services is asking me to use importlib/metadata (py 3.9) and importlib_metadata (py 3.7) for my flash application even though I did not import it in my app.py file

Here are the dependencies I use
```
from re import X
from flask import Flask, request, render_template, redirect, url_for
from mailmerge import MailMerge
from docx2pdf import convert
import os
import fitz
import smtplib
from email import encoders
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import sys
import pypyodbc as odbc
import datetime
```

**Comment by Trelaquix** [comment] 2021-09-15 10:59
**Update**

I realised I was getting the errors for importlib_metadata because I had some codes that were trying to get the current working directory and joining it together with a file.

Initially I tried this:
```
edited_word_directory = os.path.join(current_dir, "edited_draft" + "." + "docx")
edited_pdf_directory = os.path.join(current_dir, "edited_draft" + "." + "pdf")
```

After commenting out the code above, my webpage was able to run however it was unable to perform its main role. I figured it was because of the 'os.path.join' so I tried another method
```
edited_word_directory =  pathlib.Path().resolve() / "edited_draft.docx"
edited_pdf_directory = pathlib.Path().resolve() / "edited_draft.pdf"
```

The new method did not work too. It produced the following errors:

**Application logs**
```
Ok 2021-09-15T10:42:53.0298681
File "/tmp/8d978326cb395af/antenv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 545, in read_text

Ok 2021-09-15T10:53:12.8666233
from importlib.metadata import version

Error 2021-09-15T10:53:12.8666275
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Platform logs**
```
Container pythonwordpdf05_0_4d0b0cd6 didn't respond to HTTP pings on port: 8000, failing site start
Container pythonwordpdf05_0_4d0b0cd6 for site pythonwordpdf05 has exited, failing site start
```

**Container Crashed Log**
```
2021-09-15T10:34:56.936992871Z   File "/tmp/8d978326cb395af/antenv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 273, in metadata
2021-09-15T10:34:56.936996771Z     self.read_text('METADATA')
2021-09-15T10:34:56.937000471Z   File "/tmp/8d978326cb395af/antenv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 545, in read_text
2021-09-15T10:34:56.937004371Z     return self._path.joinpath(filename).read_text(encoding='utf-8')
2021-09-15T10:34:56.937008171Z AttributeError: 'PosixPath' object has no attribute 'read_text'
2021-09-15T10:34:57.001025691Z [2021-09-15 10:34:56 +0000] [40] [INFO] Worker exiting (pid: 40)
2021-09-15T10:34:57.108034188Z [2021-09-15 10:34:57 +0000] [37] [INFO] Shutting down: Master
2021-09-15T10:34:57.114900968Z [2021-09-15 10:34:57 +0000] [37] [INFO] Reason: Worker failed to boot.
```

**Comment by panchagnula** [comment] 2021-09-30 17:14
@Trelaquix thanks for the updates on this & investigations , the issue is unrelated to CLI. If this still occurs, please open a support case so the feature team, can help assist here. Thanks!

**Comment by panchagnula** [comment] 2021-09-30 17:17
Need to close this since this is not actionable on the CLI team

**Closed by panchagnula** 2021-09-30 17:17 UTC
Labels: Web Apps, Service Attention, customer-reported
