### ISSUE TITLE
Az dls fs Upload fails with special characters in directory names

### ISSUE THREAD

**Issue by scherfj1** [Azure/azure-cli#10311] opened 2019-08-23 21:59 UTC
## Describe the bug

**Command Name**
`az dls fs upload`

**Errors:**
```
Data-lake REST exception: LISTSTATUS, cerebrodata-test/timestamp-partition/time_val=2019-06-11 00:00:00
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/datalake/store/lib.py, ln 449, in call
    self.log_response_and_raise(response, err, level=exception_log_level)
azure/datalake/store/lib.py, ln 344, in log_response_and_raise
    raise exception
azure.datalake.store.exceptions.DatalakeRESTException: Data-lake REST exception: LISTSTATUS, cerebrodata-test/timestamp-partition/time_val=2019-06-11 00:00:00
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
- Create source directory tree like following:
.
├── time_val=2019-06-11\ 00:00:00
│   └── data_0.csv
└── time_val=2019-06-12\ 00:00:00
    └── data_0.csv
```

- `az dls fs upload --account {} --source-path {} --destination-path {}`

## Environment Summary
```
Darwin-18.2.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64 *

```

**Comment by akharit** [comment] 2019-10-21 23:56
Colon is not allowed in the path name.

**Comment by sumantmehtams** [comment] 2019-10-22 00:23
Closing issue as this is by design.

**Closed by sumantmehtams** 2019-10-22 00:23 UTC
Labels: Data Lake Store, Service Attention
