### ISSUE TITLE
Function App Identity Failed to Create/Assign

### ISSUE THREAD

**Issue by bhummerstone** [Azure/azure-cli#11435] opened 2019-11-29 16:12 UTC
## Describe the bug

**Command Name**
`az functionapp identity assign`

**Errors:**
```
'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/appservice/custom.py, ln 641, in assign_identity
    webapp = _assign_identity(cmd.cli_ctx, getter, setter, role, scope)
cli/core/commands/arm.py, ln 1048, in assign_identity
    resource = setter(resource)
cli/command_modules/appservice/custom.py, ln 636, in setter
    webapp.identity = ManagedServiceIdentity(type='SystemAssigned')
AttributeError: 'NoneType' object has no attribute 'identity'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp identity assign --name {} --resource-group {} --role {} --scope {}`

## Environment Summary
```
Linux-4.19.79-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by bhummerstone** [comment] 2019-11-29 16:12
Also reproducible in Azure Cloud Shell

**Comment by RakeshMohanMSFT** [comment] 2022-07-19 11:44
@bhummerstone Duplicate of this https://github.com/Azure/azure-cli/issues/11435

**Closed by RakeshMohanMSFT** 2022-07-19 11:44 UTC
Labels: Service Attention, Functions

**Comment by RakeshMohanMSFT** [comment] 2022-07-20 03:57
@bhummerstone Please upgrade to the latest version of az cli [3.28.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

**Comment by bhummerstone** [comment] 2022-07-28 09:35
Thanks for finally getting around to this :)
