### ISSUE TITLE
Azure CLI Enrollment Group Update unlinks all IoT Hubs

### ISSUE THREAD

**Issue by cboschert1** [Azure/azure-cli#29002] opened 2024-05-21 19:57 UTC
### Describe the bug

When I update the allocation policy using the update enrollment-group command, it unlinks all IoT Hubs from the enrollment group.

### Related command

az iot dps enrollment-group update -n <name> -g <resource_group> --enrollment-id <id> --allocation-policy custom --webhook-url <functionUrl> --api-version 2021-10-01

### Errors

Command succeeds and updates the allocation policy.

### Issue script & Debug output

Please message if needed, don't want to have to go through the output and block sensitive info. 

### Expected behavior

I expect all other settings to stay the same on the enrollment group, and all of the selected linked hubs to remain unchanged. 
Before the command:
![image](https://github.com/Azure/azure-cli/assets/22844502/23f6d02f-33b3-4f8d-ba10-56ad7caac956)
After the command:
![image](https://github.com/Azure/azure-cli/assets/22844502/3dcbbb95-3784-494a-bf98-920b72bec548)

### Environment Summary

{
  "azure-cli": "2.52.0",
  "azure-cli-core": "2.52.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-devops": "0.26.0",
    "azure-iot": "0.23.1"
  }
}

### Additional context

Am I misunderstanding the update command. I expect an update command to only update the parameters I pass in, leaving everything else unchanged.

**Comment by yonzhan** [comment] 2024-05-21 19:57
Thank you for opening this issue, we will look into it.

**Comment by cboschert1** [comment] 2024-05-21 20:01
> Hi @cboschert1,
> 
> 2.52.0 is not the latest Azure CLI(2.61.0).
> 
> If you haven't already attempted to do so, please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

Verified this happens with the latest azure CLI (2.61.0) as well.

**Comment by vilit1** [comment] 2024-05-21 22:20
Hi,

I managed to reproduce your issue and have looked into the code and documentation as to why this occurs. The initial goal was to have the customer re-enter the IoT Hubs they want to connect if they change the allocation policy. This is extremely important for allocation policies such as static, in which exactly one IoT Hub is allowed.

However, I can see this being a pain point, especially if there are multiple IoT Hubs present and the allocation policy is minimally changed (such as updating the webhook url). Thus, I will modify the enrollment update code so that the current IoT Hub list is kept unless a new one is specified via the command.

**Comment by cboschert1** [comment] 2024-05-21 23:59
Thank you for the quick response, I appreciate it and will follow this issue for updates.

In the meantime I did this as a workaround if someone else happens across this. There's probably a better way, but this works for now:

``` 
enrollmentGroupInfo=$(az iot dps enrollment-group show -g $RESOURCE_GROUP --dps-name $DPS_NAME --enrollment-id $group)
linkedHubs=$(echo $enrollmentGroupInfo | jq -r '.iotHubs[]' | xargs)
...
az iot dps enrollment-group update -g $RESOURCE_GROUP --dps-name $DPS_NAME --enrollment-id $group --iot-hubs "$linkedHubs" --allocation-policy custom --webhook-url $FUNCTION_URL --api-version 2021-10-01
```

**Comment by vilit1** [comment] 2024-07-31 18:12
Closing issue since the code has been merged in and released

**Closed by vilit1** 2024-07-31 18:12 UTC
Labels: bug, Service Attention, customer-reported, IoT, IoT/CLI, Auto-Assign, Auto-Resolve
