### ISSUE TITLE
"az monitor activity-log alert list" raises "JSONDecodeError"

### ISSUE THREAD

**Issue by nuno-andre** [Azure/azure-cli#8228] opened 2019-01-11 20:07 UTC
**Describe the bug**
Custom command [`list_activity_logs_alert`](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/activity_log_alerts.py#L46) returns 
[`list_by_resource_group`](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-monitor/azure/mgmt/monitor/operations/activity_log_alerts_operations.py#L362) and [the exception handler tries to parse an empty string as JSON](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_exception_handler.py#L13) making `requests` to raise a `JSONDecodeError`.

**To Reproduce**
Run `az monitor activity-log alert list -g <RESOURCE_GROUP>` without alerts.

**Expected behavior**
Returning an empty list.

**Environment summary**
```
azure-cli (2.0.54)
monitor (0.2.7)
Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

**Additional context**
Maybe related with https://github.com/Azure/azure-sdk-for-python/issues/1556 ?

**Comment by tjprescott** [comment] 2019-01-11 23:11
There is logic in place to work around Azure/azure-sdk-for-python#1556. However, the format of the error returned in this instance doesn't conform to that. This is a service bug. I will submit a PR that avoids the stack trace, but the error in this case is still pretty vague:
`Operation returned an invalid status code 'Not Found'`

**Comment by msvijayn** [comment] 2019-06-28 13:10
Fix merged by [8240](https://github.com/Azure/azure-cli/pull/8240) on Azure CLI repository.
Hence closing the issue. Kindly re-open if the issue is still seen.

**Comment by msvijayn** [comment] 2019-06-28 13:11
closes: #8228

**Comment by msvijayn** [comment] 2019-06-28 13:12
closes #8228

**Comment by msvijayn** [comment] 2019-06-28 13:12
#please-close

**Comment by msvijayn** [comment] 2019-06-28 13:13
#close

**Closed** 2019-06-28 15:23 UTC
Labels: Bug, Monitor, Service Attention
