### ISSUE TITLE
Failure to start dashboard for a Kubernetes cluster in a web browser.

### ISSUE THREAD

**Issue by Teketel** [Azure/azure-cli#9543] opened 2019-06-03 15:03 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10322a850>: Failed to establish a new connection: [Errno 61] Connection refused',))
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Library/Python/2.7/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10322a850>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 2.7.10
Shell: bash

azure-cli 2.0.65

```

**Comment by adewaleo** [comment] 2019-06-03 19:52
@zqingqing1 @GaneshaThirumurthi @samkreter, is this related to

#9425,  #9500, #9000, #9144

**Comment by seanmck** [comment] 2019-07-14 07:11
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:11 UTC
Labels: AKS, Bug, Service Attention
