### ISSUE TITLE
webapp: Apply access restriction to resources in different resource groups

### ISSUE THREAD

**Issue by wonderplayer** [Azure/azure-cli#11698] opened 2019-12-27 17:35 UTC
I'd like to add VNET access restriction to Azure Function App. Azure Function App is located in RG1 and VNET is located in RG2.
I can't get it to work even with IDs.
Command:
`
az webapp config access-restriction add 
  --priority 100 
  --action Allow 
  --name $newParameters.FunctionAppName 
  --rule-name "APIm" 
  --subnet $newParameters.APImSubnetName 
  --vnet-name $newParameters.VnetName
`
Error message:
The Resource 'Microsoft.Network/virtualNetworks/dev-deploy-vnet' under resource group 'dev-deploy-rg-dev' was not found.

Command:
`az webapp config access-restriction add 
  --priority 100 
  --action Allow 
  --rule-name "APIm" 
  --ids $b, $c
`
Message:
/subscriptions/xxx/resourceGroups/dev-deploy-rg-dev/providers/Microsoft.Web/sites/dev-deploy-fadev,: "(ResourceNotFound) The Resource 'Microsoft.Web/sites/dev-deploy-vnet' under resource group 'dev-deploy-rg' was not found."
/subscriptions/xxx/resourceGroups/dev-deploy-rg/providers/Microsoft.Network/virtualNetworks/dev-deploy-vnet: "(ResourceNotFound) The Resource 'Microsoft.Web/sites/dev-deploy-fadev,' under resource group 'dev-deploy-rg-dev' was not found.

It's possible through Azure Portal.
Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c788e908-cee3-ae46-fac4-956d0606ad76
* Version Independent ID: 2ed69bfd-bb05-3d09-072e-00e505856fba
* Content: [az webapp config access-restriction](https://docs.microsoft.com/en-us/cli/azure/webapp/config/access-restriction?view=azure-cli-latest#az-webapp-config-access-restriction-set)
* Content Source: [latest/docs-ref-autogen/webapp/config/access-restriction.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/access-restriction.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment] 2019-12-30 05:48
if your app is a function app can you try using the function app equivalent? https://docs.microsoft.com/en-us/cli/azure/functionapp/config/access-restriction?view=azure-cli-latest

Does this work incases where the FunctionApp & the VNET are in the same RG?
Also the access-restriction command takes a RG as an input what happens if you pass the RG of the VNET as the value for this?

**Comment by wonderplayer** [comment] 2019-12-30 08:13
`az functionapp config access-restriction add --priority 100 --action Allow --name "dev-deploy-fadev" --rule-name "APIm" --subnet "APIm" --vnet-name "dev-deploy-vnet" --resource-group "dev-deploy-rg"`

This command group is in preview. It may be changed/removed in a future release.

ResourceNotFound - The Resource 'Microsoft.Web/sites/dev-deploy-fadev' under resource group 'dev-deploy-rg' was not found.


`az functionapp config access-restriction add --priority 100 --action Allow --name "dev-deploy-fadev" --rule-name "APIm" --subnet "APIm" --vnet-name "dev-deploy-vnet" --resource-group "dev-deploy-rg-dev"`

This command group is in preview. It may be changed/removed in a future release.

The Resource 'Microsoft.Network/virtualNetworks/dev-deploy-vnet' under resource group 'dev-deploy-rg-dev' was not found.

**Comment by wonderplayer** [comment] 2019-12-30 08:14
I've created the same issue with Az PowerShell [here](https://github.com/Azure/azure-powershell/issues/10794). Don't know if that might help.

**Comment by fabiocav** [comment] 2020-01-07 19:32
Removing the `Service Attention` label as @panchagnula is responding to this issue.

**Comment by yonzhan** [comment] 2020-01-08 07:57
@fabiocav normally if the commands are not owned by Azure CLI team, we will mark the Service Attention label.

**Comment by jnancel** [comment] 2020-01-12 18:53
Hello,
For the record, I get the exact same issue when using `--scm-site true`

**Comment by panchagnula** [comment] 2020-02-13 17:23
The issue is originating from the _validate_subnet call https://github.com/Azure/azure-cli/blob/46a142f2a6987ced98d5682721eec71626a9ea2b/src/azure-cli/azure/cli/command_modules/appservice/access_restrictions.py#L128
will look at getting a fix for this.

**Comment by yonzhan** [comment] 2020-03-07 03:52
move to S167

**Comment by panchagnula** [comment] 2020-03-09 16:47
@kotashudhakarreddy can you take a look at this - since you already fixed this in PowerShell

**Comment by Kotasudhakarreddy** [comment] 2020-03-28 11:54
Looking in to it.

**Comment by yonzhan** [comment] 2020-04-18 12:53
move to S169

**Comment by ktharsis-sw** [comment] 2020-08-07 17:54
Might be a little late, but try:
For the subnet param - instead of just putting the name, put the full resource ID of the subnet (including the subscription, vnet, etc parts of the path). 
`/subscriptions/[subsguid]/resourceGroups/[rgwithvnetinit]/providers/Microsoft.Network/virtualNetworks/[vnetname]/subnets/[subnetname]`

**Comment by madsd** [comment] 2020-11-03 15:38
The command was designed with the --subnet parameter accepting both a name combined with a vnet-name or a full resource-id for the subnet in the same --subnet parameter. However, we have had a few issues created on this not being clear, so we will improve help text and examples as well as adding a --vnet-resource-group to explicitly be able to specify this.

**Closed** 2020-11-05 05:47 UTC
Labels: Functions, Service Attention, Web Apps, customer-reported
