### ISSUE TITLE
Inability to successfully login my az in terminal

### ISSUE THREAD

**Issue by aristokratos** [Azure/azure-cli#25162] opened 2023-01-18 14:52 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
9. The ID token already expires. Make sure your computer's time and time zone are both correct. Current epoch = 1674085227.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/1e95fb9b-0494-4a20-9228-dbac29b8c33d/v2.0",
  "iat": 1674052528,
  "nbf": 1674052528,
  "exp": 1674056428,
  "aio": "AWQAm/8TAAAAXEr9wft3/uWZek2GJ1ShrV7k4Rut/8ISa576HhYiarBlmHhKWnJalQAxMhD7hUVwgjaTJ5gF38UX3sgEsi2sWG71QAYXRpxWkKNPwEu14ytIrGsXus2/+ls5uJHTS1gf",
  "name": "Oluwatobiloba Onawale",
  "nonce": "ab727881a4cb3a96ff382e653b583e3fa465389fa97dab033e5c928ab2bdd88f",
  "oid": "81b2f351-0fb0-437f-940a-1e18c9af08a1",
  "preferred_username": "oluwatobiloba.onawale@decagon.dev",
  "puid": "10032002294ED13A",
  "rh": "0.ATkAm_uVHpQEIEqSKNusKbjDPZV3sATbjRpGu-4C-eG_e0Y5AIM.",
  "sub": "uaRmxhm0q5lSIs4Gu3SeKJ649P6Q-7bwSCkihSj-dMA",
  "tid": "1e95fb9b-0494-4a20-9228-dbac29b8c33d",
  "uti": "Mrd4Hn0FZUCAkB3b8ShWAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 154, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1828, in acquire_token_interactive
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 281, in obtain_token_by_browser
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 639, in obtain_token_by_browser
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 677, in _obtain_token_by_browser
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 142, in obtain_token_by_auth_code_flow
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 547, in obtain_token_by_auth_code_flow
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 731, in _obtain_token_by_authorization_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 116, in _obtain_token
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 788, in _obtain_token
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 700, in <lambda>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 314, in add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 117, in add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 158, in __add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 77, in decode_id_token
RuntimeError: 9. The ID token already expires. Make sure your computer's time and time zone are both correct. Current epoch = 1674085227.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/1e95fb9b-0494-4a20-9228-dbac29b8c33d/v2.0",
  "iat": 1674052528,
  "nbf": 1674052528,
  "exp": 1674056428,
  "aio": "AWQAm/8TAAAAXEr9wft3/uWZek2GJ1ShrV7k4Rut/8ISa576HhYiarBlmHhKWnJalQAxMhD7hUVwgjaTJ5gF38UX3sgEsi2sWG71QAYXRpxWkKNPwEu14ytIrGsXus2/+ls5uJHTS1gf",
  "name": "Oluwatobiloba Onawale",
  "nonce": "ab727881a4cb3a96ff382e653b583e3fa465389fa97dab033e5c928ab2bdd88f",
  "oid": "81b2f351-0fb0-437f-940a-1e18c9af08a1",
  "preferred_username": "oluwatobiloba.onawale@decagon.dev",
  "puid": "10032002294ED13A",
  "rh": "0.ATkAm_uVHpQEIEqSKNusKbjDPZV3sATbjRpGu-4C-eG_e0Y5AIM.",
  "sub": "uaRmxhm0q5lSIs4Gu3SeKJ649P6Q-7bwSCkihSj-dMA",
  "tid": "1e95fb9b-0494-4a20-9228-dbac29b8c33d",
  "uti": "Mrd4Hn0FZUCAkB3b8ShWAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.44.1
```

**Comment by yonzhan** [comment] 2023-01-18 22:55
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2023-01-18 22:55 UTC
Labels: Account, customer-reported, Auto-Assign
