### ISSUE TITLE
az policy assignment show complains about assignment name length

### ISSUE THREAD

**Issue by itaylaufer** [Azure/azure-cli#10176] opened 2019-08-07 11:58 UTC
## Describe the bug

Policy that was assigned in the portal and was assigned correctly failed to show in cli. 

**Command Name**
`az policy assignment show`

**Errors:**
```
InvalidPolicyAssignmentName - The policy assignment name 'Audit virtual machines without disaster recovery configured' is invalid. The policy assignment name length must not exceed '24' characters.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

1. I've assigned an existing Azure policy in the portal to a management-group.
2. I chose the 'Audit virtual machines without disaster recovery configured' policy and called the assignment name 'Audit virtual machines without disaster recovery configured'
3. ran 'az policy assignment show --name "Audit virtual machines without disaster recovery configured"' and got the error 'InvalidPolicyAssignmentName - The policy assignment name 'Audit virtual machines without disaster recovery configured' is invalid. The policy assignment name length must not exceed '24' characters.'
 
- _Put any pre-requisite steps here..._
- `az policy assignment show --name {}`

## Environment Summary
```
Darwin-18.0.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.70

```

**Comment by whoeipingo** [comment] 2019-09-11 09:00
Check https://github.com/Azure/azure-powershell/issues/8992. This is based on the same issue. No limit in PS or CLI but in the backend.

**Comment by yonzhan** [comment] 2019-12-04 07:36
add to S163.

**Comment by zhoxing-ms** [comment] 2019-12-26 06:24
@itaylaufer I try to retry this problem in '2.0.70' version and the latest version of azure-cli, but find that the problem could not be reproduced.
Please try again, if you have any more questions, please let us know.

**Comment by yonzhan** [comment] 2020-01-02 03:27
@itaylaufer any update?

**Comment by zhoxing-ms** [comment] 2020-01-13 05:49
Because it hasn't been replied for a long time, I'll close the issue first. If you have any other questions, please feel free to reopen it or create a new one.

**Closed by zhoxing-ms** 2020-01-13 05:49 UTC
Labels: Policy
