### ISSUE TITLE
centos7 az cli issue: The ID token is not yet valid

### ISSUE THREAD

**Issue by vidhya199** [Azure/azure-cli#21089] opened 2022-01-24 11:15 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1643022189.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/3617ef9b-98b4-40d9-ba43-e1ed6709cf0d/v2.0",
  "iat": 1643022581,
  "nbf": 1643022581,
  "exp": 1643026481,
  "aio": "ATQAy/8TAAAAuwTRr3GJaeuYpFCucVUIFQQvdayb2zb/AnFS20SW9K//OVUtQM9Zst4hxJZW58Bt",
  "name": "Cloud Student",
  "oid": "951fe4e0-65d7-480e-af42-b678c914067b",
  "preferred_username": "cloud_user_p_a78d9eba@azurelabs.linuxacademy.com",
  "puid": "10032001D2C4EEE8",
  "rh": "0.ASkAm-8XNrSY2UC6Q-HtZwnPDZV3sATbjRpGu-4C-eG_e0YpABs.",
  "sub": "pojiuz-bX9HzZccGBUbBhEmc-cjh7vbQktbgzapb5LQ",
  "tid": "3617ef9b-98b4-40d9-ba43-e1ed6709cf0d",
  "uti": "yphSjTqOD0CutTBydOqgAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 158, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 158, in login
    user_identity = identity.login_with_username_password(username, password, scopes=scopes, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 186, in login_with_username_password
    result = self._msal_app.acquire_token_by_username_password(username, password, scopes, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 1411, in acquire_token_by_username_password
    **kwargs))
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 142, in obtain_token_by_username_password
    username, password, headers=headers, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 739, in obtain_token_by_username_password
    return self._obtain_token("password", data=data, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 115, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 795, in _obtain_token
    "response": _resp, "params": params, "data": _data,
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 582, in <lambda>
    event, environment=authority.instance)),
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/token_cache.py", line 307, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(even

**Comment by yonzhan** [comment] 2022-01-24 11:43
@jiasli for awareness

**Comment by jiasli** [comment] 2022-01-25 03:39
Duplicate of #20388

**Closed by jiasli** 2022-01-25 03:39 UTC
Labels: Account, customer-reported
