### ISSUE TITLE
issue in importing SSL certificate in azure web app using cli

### ISSUE THREAD

**Issue by nilesh-rawal** [Azure/azure-cli#22764] opened 2022-06-07 12:13 UTC
## Describe the bug

**Command Name**
`az webapp config ssl import`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'GraphClient' object has no attribute 'service_principals'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/commands.py", line 39, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2700, in import_ssl_cert
    if not _check_service_principal_permissions(cmd, kv_resource_group_name, kv_name, kv_subscription):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2779, in _check_service_principal_permissions
    graph_sp_client = _graph_client_factory(cmd.cli_ctx).service_principals
AttributeError: 'GraphClient' object has no attribute 'service_principals'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config ssl import --resource-group {} --name {} --key-vault {} --key-vault-certificate-name {}`

## Environment Summary
```
Linux-5.4.0-1080-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-06-07 13:31
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-06-07 16:03
@nilesh-rawal Duplicate of https://github.com/Azure/azure-cli/issues/22761. We are tracking this issue on the other one therefore closing this.

**Closed by RakeshMohanMSFT** 2022-06-07 16:03 UTC
Labels: Web Apps, customer-reported, CXP Attention, Auto-Assign
