### ISSUE TITLE
Impossible to create "multivalue" traffic manager profile with azure-cli

### ISSUE THREAD

**Issue by letienne** [Azure/azure-cli#16195] opened 2020-12-08 11:49 UTC
Hello,

It seems to be impossible to manage multivalue profiles with azure cli. When creating a profile, the cli throws:

```
BadRequestError: Operation failed with status: 'Bad Request'. Details: MaxReturn property must
 be defined for MultiValue profiles.
```

However, MaxReturn cannot be set via this CLI.

Thanks and kind regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8f3db91-d932-fd75-a98e-e125bc297ca8
* Version Independent ID: 985b32d5-634c-9883-6e27-223cb83f21cf
* Content: [az network traffic-manager profile](https://docs.microsoft.com/en-us/cli/azure/network/traffic-manager/profile?view=azure-cli-latest#az_network_traffic_manager_profile_create)
* Content Source: [latest/docs-ref-autogen/network/traffic-manager/profile.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/traffic-manager/profile.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-12-08 12:23
network

**Comment by msyyc** [comment] 2020-12-14 06:42
@letienne I couldn't reproduce the error, please post your failed cmd.

**Comment by letienne** [comment] 2020-12-15 08:28
```
PS C:\WINDOWS\system32> az network traffic-manager profile create --name 'issue-with-multivalue-tm' `
>> --resource-group '<<rgname>>' `
>> --routing-method 'Multivalue' `
>> --unique-dns-name 'issue-with-multivalue-dns-name' `
>> --protocol 'HTTPS' `
>> --port 443 `
>> --path "/"
```

throws

`BadRequestError: Operation failed with status: 'Bad Request'. Details: MaxReturn property must be defined for MultiValue profiles.`

Then:

```
PS C:\WINDOWS\system32> az network traffic-manager profile create --name 'issue-with-multivalue-tm' `
>> --resource-group 'LAB-TRAFFICMANAGER-DNS-ISPREDUNDANCY-RG' `
>> --routing-method 'Multivalue' `
>> --unique-dns-name 'issue-with-multivalue-dns-name' `
>> --protocol 'HTTPS' `
>> --port 443 `
>> --path "/" `
>> --MaxReturn 2
```

throws

```
UnrecognizedArgumentError: unrecognized arguments: --MaxReturn 2
Try this: 'az network traffic-manager profile create --name MyTmProfile --resource-group MyResourceGroup --routing-method Performance --unique-dns-name mywebapp'
Still stuck? Run 'az --help' to view all commands or go to 'https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest' to learn more
```

Version:

```
PS C:\WINDOWS\system32> az --version
azure-cli                         2.15.1

core                              2.15.1
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\EtienneL\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Unable to check if your CLI is up-to-date. Check your internet connection.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Comment by msyyc** [comment] 2020-12-16 01:58
got it. we are debugging it now

**Comment by msyyc** [comment] 2020-12-17 03:31
we have found the problem and it will be fixed at next CLI version(about 2020/12/31)

**Comment by letienne** [comment] 2020-12-17 09:13
Thank you

**Closed** 2021-03-22 06:59 UTC
Labels: Network, OKR3.2 Candidate, feature-request
