### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED during az container exec

### ISSUE THREAD

**Issue by laiddlai** [Azure/azure-cli#11166] opened 2019-11-09 01:37 UTC
## Describe the bug

**Command Name**
`az container exec`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container exec --resource-group {} --name {} --exec-command {}`

## Environment Summary
```
Linux-3.10.0-862.3.3.el7.x86_64-x86_64-with-centos-7.2.1511-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.72 *

```

**Comment by fengzhou-msft** [comment] 2019-11-09 01:49
Are you using a network proxy? If so, please refer the doc here: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy

**Comment by laiddlai** [comment] 2019-11-09 02:07
I tried this but still getting the same error:

az container exec --resource-group myResourceGroup --name ihubmain --exec-command "/bin/bash"
Connection verification disabled by environment variable AZURE_CLI_DISABLE_CONNECTION_VERIFICATION
Connection verification disabled by environment variable AZURE_CLI_DISABLE_CONNECTION_VERIFICATION
Connection verification disabled by environment variable AZURE_CLI_DISABLE_CONNECTION_VERIFICATION
/usr/lib64/az/lib/python2.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib64/az/lib/python2.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
The command failed with an unexpected error. Here is the traceback:

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)

**Comment by jiasli** [comment] 2019-11-13 02:41
`AZURE_CLI_DISABLE_CONNECTION_VERIFICATION` doesn't work with some data-plane operations. Please try the `REQUESTS_CA_BUNDLE` approach.

**Comment by sirlatrom** [comment] 2020-07-17 13:00
I've tried both approaches, and neither work. It is most likely due to the `az container exec` command using a websocket connection, whereas many other commands use a regular HTTP connection.

**Comment by jiasli** [comment] 2020-07-20 06:30
Routing to container team. @samkreter

**Comment by magnus-longva-bouvet** [comment] 2021-02-25 18:34
I would also like this issue solved.

**Comment by jiasli** [comment] 2021-08-06 06:42
Duplicate of #15121

**Closed by jiasli** 2021-08-06 06:42 UTC
Labels: Service Attention, Container Instances, customer-reported
