### ISSUE TITLE
az upgrade error

### ISSUE THREAD

**Issue by b1ackhawk-uh60** [Azure/azure-cli#16874] opened 2021-02-09 17:00 UTC
## Describe the bug

**Command Name**
`az upgrade`

**Errors:**
```
cannot import name 'status_tag_messages'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    out_file = sys.stdout
cli/core/commands/__init__.py, ln 659, in execute
    results, exceptions = self._run_jobs_concurrently(jobs, ids)
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    def _run_jobs_serially(self, jobs, ids):
cli/core/commands/__init__.py, ln 715, in _run_job
    cmd_copy.cli_ctx.raise_event(EVENT_INVOKER_TRANSFORM_RESULT, event_data=event_data)
...
<frozen importlib._bootstrap>, ln 618, in _exec
<frozen importlib._bootstrap_external>, ln 678, in exec_module
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
azure/cli/core/__init__.py, ln 60, in <module>
    _configure_knack()
azure/cli/core/__init__.py, ln 48, in _configure_knack
    from knack.util import status_tag_messages
ImportError: cannot import name 'status_tag_messages'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade`

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.0

```

**Comment by yungezz** [comment] 2021-02-10 00:45
hi @fengzhou-msft could you have a look? thanks

**Comment by fengzhou-msft** [comment] 2021-03-16 04:46
Duplicate of #16952

**Closed** 2021-03-16 16:20 UTC
Labels: Upgrade, question
