### ISSUE TITLE
No module named 'prompt_toolkit.interface' during Microsoft Learn course

### ISSUE THREAD

**Issue by ShinyCoconut** [Azure/azure-cli#24256] opened 2022-10-18 19:08 UTC
While in the Microsoft Learn course - [ Azure Fundamentals: Describe Azure architecture and services ](https://learn.microsoft.com/en-us/training/paths/azure-fundamentals-describe-azure-architecture-services/) | Describe the core architectural components of Azure -, an Azure Sandbox was generated.
Typing az interactive, as requested by the course, generates the following error.

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/home/gabriel/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/home/gabriel/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 33, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'

```

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.41.0

Extensions:
interactive 0.4.5
ai-examples 0.2.5
ml 2.10.0
ssh 1.1.2

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-10-18 23:04
Duplicate of https://github.com/Azure/azure-cli/issues/24213

**Closed by yonzhan** 2022-10-18 23:04 UTC
Labels: Interactive, customer-reported, Auto-Assign
