### ISSUE TITLE
InvalidResourceName when creating storage container with CAPS in name

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#11052] opened 2019-10-31 23:30 UTC
## Describe the bug

**Command Name**
`az storage container create` fails with `InvalidResourceName` if the name has capital letters, e.g. `my-container-NAME`

**Errors:**
```
The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:3330a233-801e-0059-7b42-90f8dc000000
Time:2019-10-31T23:24:31.0444608Z</Message></Error>
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
...
azure.common.AzureHttpError: The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:3330a233-801e-0059-7b42-90f8dc000000
Time:2019-10-31T23:24:31.0444608Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account create -n <account name> -g <rg name> -l westus2 --kind StorageV2 --https-only true`
- `az storage container create -n <container name with CAPS, e.g. my-container-NAME> --account-name <account name>`

## Expected Behavior

a container is created in the storage account specified in `--account-name`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.70 *

Extensions:
azure-devops 0.13.0

```

**Comment by seanknox** [comment] 2019-10-31 23:30
Can provide output from `--debug` if helpful. Wasn't sure if there's anything sensitive in there.

**Comment by Juliehzl** [comment] 2019-11-01 02:32
Hi @seanknox, I think you are right because it is caused by Capital letters. A valid container name should follow the following rules:

- blob container name must be between 3 and 63 characters in length; 
-  start with a letter or number; 
- and contain only letters, numbers, and the hyphen.
- All letters used in blob container names must be lowercase.

Fore more information, please refer to https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names.

**Comment by Juliehzl** [comment] 2019-11-01 02:34
Close it because it is service requirements for naming rules. If you still have problems, feel free to reopen it or open a new one. Thanks a lot for your feedback and hope it doesn't block you.

**Closed by Juliehzl** 2019-11-01 02:34 UTC
Labels: Storage
