### ISSUE TITLE
az synapse workspace-package upload-batch command results in TypeError: LibraryOperations.append() missing 1 required positional argument: 'content'

### ISSUE THREAD

**Issue by EnnekQ** [Azure/azure-cli#24700] opened 2022-11-21 13:54 UTC
## Describe the bug
az synape workspace upload command does not produce the same result as when ran on azure-cli **2.40.0**. It no longer uploads the provided packages to the sparkPool in the Azure Synapse Workspace. Instead it fails with the below traceback. Pipelines used to work, now they don't because of this bug introduced in either **2.41.0 or 2.42.0**.  Locally the same error arises. The first package it tries to upload, will fail and result in a 'Provisioning Status' equal to 'Incomplete' in Synapse.

**Command Name**
`az synapse workspace-package upload-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
LibraryOperations.append() missing 1 required positional argument: 'content'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 425, in workspace_package_upload_batch
    results.append(upload_workspace_package(cmd, workspace_name, source_file, progress_callback))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 397, in upload_workspace_package
    client.append(package_name, data)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
TypeError: LibraryOperations.append() missing 1 required positional argument: 'content'

```

## To Reproduce:
Azure Synapse environment with a sparkPool set-up is required. To reproduce in a local environment. Make sure to be permitted to connect to Synapse from local. Have the packages in a local dir and provide the path alongside the workspace name to az synapse command.

- `az synapse workspace-package upload-batch --source {} --workspace-name {} --subscription {}`

## Expected Behavior
To succesfully upload the workspace packages to the Synapse workspace.

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.42.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
Colleague confirmed that the bug does **not** occur when using azure-cli **2.40.0**. If any additional information is required, please feel free to contact me.

**Comment by yonzhan** [comment] 2022-11-22 00:53
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-11-28 06:36
Closing as Duplicate of https://github.com/Azure/azure-cli/issues/24718

**Closed by RakeshMohanMSFT** 2022-11-28 06:36 UTC
Labels: customer-reported, Synapse, CXP Attention, Auto-Assign

**Comment by EnnekQ** [comment] 2022-11-28 09:55
> Closing as Duplicate of #24718

How is this a duplicate when this issue was raised a day before https://github.com/Azure/azure-cli/issues/24718?
