### ISSUE TITLE
azure cli issue

### ISSUE THREAD

**Issue by chainfir3** [Azure/azure-cli#11400] opened 2019-11-26 17:33 UTC
## Describe the bug

**Command Name**
`az backup recoverypoint list`

**Errors:**
```
Item not found. Please provide a valid item_name.
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/backup/custom_help.py, ln 104, in validate_item
    validate_object(item, "Item not found. Please provide a valid item_name.")
cli/command_modules/backup/custom_help.py, ln 113, in validate_object
    raise ValueError(error_message)
ValueError: Item not found. Please provide a valid item_name.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup recoverypoint list --resource-group {} --vault-name {} --container-name {} --item-name {} --query {} --output {} --backup-management-type {}`

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by pvrk** [comment] 2020-02-25 06:54
@chainfir3 : We can't reproduce the error in our internal testing. Are you able to get the item name from az backup item list?

**Comment by pvrk** [comment] 2020-03-06 05:59
@chainfir3 : Please let us know if you are able to reproduce the issue.

**Comment by pvrk** [comment] 2020-06-08 05:44
Closing the issue since we didn't get the relevant data to reproduce and test.

**Closed by pvrk** 2020-06-08 05:44 UTC
Labels: Recovery Services Backup, Service Attention, customer-response-expected
