### ISSUE TITLE
az webapp create with invalid app service plan name throws: 'NoneType' object has no attribute 'location'

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#12613] opened 2020-03-17 00:41 UTC
## Describe the bug

I tried to create a webapp with an invalid app service plan and got this error:

```
az webapp create -n mvpsdkdemoapp -g groupname --plan azsdkdemoplan

az webapp create: error: 'NoneType' object has no attribute 'location'
```

**Command Name**
`az webapp create`

**Errors:**
az webapp create: error: 'NoneType' object has no attribute 'location'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create -n {} --plan {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.2.0

```
## Additional Context

azsdke2e

**Comment by yungezz** [comment] 2020-03-17 01:26
thanks for reporting, route to appropriate team

**Comment by panchagnula** [comment] 2020-03-27 20:21
Can you run the command with --debug with the same scenario & check the error message is more informative. Unfortunately this is a by design issue where the API returns a default error message and to see the internal error message you need use the --debug flag.

**Comment by jongio** [comment] 2020-03-31 17:15
```
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/serverFarms/azsdkdemoplan123' under resource group 'mvpsdkdemorg' was not found."}}
usage: az webapp create [-h] [--verbose] [--debug]
                        [--output {json,jsonc,table,tsv,yaml,yamlc,none}]
                        [--query JMESPATH] [--subscription _SUBSCRIPTION]
                        --resource-group RESOURCE_GROUP_NAME --name NAME
                        --plan PLAN [--runtime RUNTIME]
                        [--startup-file STARTUP_FILE]
                        [--deployment-container-image-name DEPLOYMENT_CONTAINER_IMAGE_NAME]
                        [--deployment-source-url DEPLOYMENT_SOURCE_URL]
                        [--deployment-source-branch DEPLOYMENT_SOURCE_BRANCH]
                        [--deployment-local-git]
                        [--docker-registry-server-password DOCKER_REGISTRY_SERVER_PASSWORD]
                        [--docker-registry-server-user DOCKER_REGISTRY_SERVER_USER]
                        [--multicontainer-config-type {COMPOSE,KUBE}]
                        [--multicontainer-config-file MULTICONTAINER_CONFIG_FILE]
                        [--tags [TAGS [TAGS ...]]]
az webapp create: error: 'NoneType' object has no attribute 'location'
```

**Comment by panchagnula** [comment] 2020-03-31 17:21
Thank you for the response. 
this error message "The Resource 'Microsoft.Web/serverFarms/azsdkdemoplan123' under resource group 'mvpsdkdemorg' was not found."}}" is the detailed message.

**Comment by jongio** [comment] 2020-03-31 18:07
Yeah, can we expose that error message to the user without having to add --debug?

**Comment by panchagnula** [comment] 2020-03-31 18:15
We have requested our API folks to make the changes on their end - in general polish/improve the default error message. For CLI the way to show the inner error message is to run using the debug flag

**Comment by jongio** [comment] 2020-03-31 18:17
1. 'NoneType' object has no attribute 'location' is not a good default error message.
2. The CLI could own parsing the inner message and displaying it. 

I don't see how API changes are needed for this.

**Comment by panchagnula** [comment] 2020-03-31 18:21
CLI doesn't create a error messages but displays whatever the API returns. CLI does parse inner error message but only when run by --debug flag.

**Comment by jongio** [comment] 2020-03-31 18:24
"'NoneType' object has no attribute 'location'" comes from the API? - 

Seems like we should update the CLI to parse the inner message and display without --debug.  Maybe one level deep?  Else, we'll keep seeing this type of stuff pop up.

**Comment by yonzhan** [comment] 2020-04-18 12:51
move to S169

**Comment by panchagnula** [comment] 2020-05-28 06:49
We are planning on adding better validation & will test the during those fixes.

**Comment by panchagnula** [comment] 2020-08-18 17:28
@calvinsID can you check if this is fixed by any of the validations you added. Moving to next milestone.

**Comment by calvinsID** [comment] 2020-08-18 18:17
Fixed with newer versions of CLI

**Closed by calvinsID** 2020-08-18 18:17 UTC
Labels: Service Attention, Web Apps
