### ISSUE TITLE
az interactive stop working after last upgrade

### ISSUE THREAD

**Issue by ZEROF** [Azure/azure-cli#17835] opened 2021-04-23 07:23 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
Error loading command module 'iot': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'network': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'resource': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'sql': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'vm': progress_patch() got an unexpected keyword argument 'det'
'public-ip' is misspelled or not recognized by the system.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-5.4.0-72-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.22.1

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment] 2021-04-23 08:35
@jiasli for awareness

**Comment by jiasli** [comment] 2021-06-07 02:03
Duplicate of #17740

**Closed by jiasli** 2021-06-07 02:03 UTC
Labels: Interactive, feature-request
