### ISSUE TITLE
AzureCLI ClientID doesn't give access to Azure Communication Service (while trying to send email)

### ISSUE THREAD

**Issue by erikrenaud** [Azure/azure-cli#26271] opened 2023-04-26 22:06 UTC
When developing using DotNetCore and the Azure DotNet SDK, it was found that it is impossible to send emails using Azure Communication Service from a developer workstation because a specific scope is not preapprouved for the AzureCLI ClientID.

Original thread which leads to creating this issue:
https://github.com/Azure/azure-sdk-for-net/issues/35816

Here is the error that AzureCLI gives:
```
AuthenticationFailedException: Azure CLI authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/azclicredential/troubleshoot ERROR: AADSTS65002: Consent between first party application '04b07795-8ddb-461a-bbee-02f9e1bf7b46' and first party resource '632ec9eb-fad7-4cbd-993a-e72973ba2acc' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.

Trace ID: 04bbb4fb-50c8-4444-aac8-1c0068440500

Correlation ID: b9689670-8f28-4b3e-a96a-28781a3b6d03

Timestamp: 2023-04-25 19:59:32Z
To re-authenticate, please run:
az login --scope https://communication.azure.com//.default
```

Adding the scope to the Azure CLI ClientID would allow us (devs) to use AzureCLI credentials to send email using Azure Communication Service instead of resolving to using connectionstrings (with the embedded keys) or creating a separate Service Principal.

**Comment by yonzhan** [comment] 2023-04-26 22:06
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2023-08-14 07:53
Duplicate of #23485

**Closed by jiasli** 2023-08-14 07:53 UTC
Labels: Account, customer-reported, feature-request, Auto-Assign, Azure CLI Team
