### ISSUE TITLE
aks commands not working on windows

### ISSUE THREAD

**Issue by lkjangir** [Azure/azure-cli#16338] opened 2020-12-22 10:40 UTC
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
No module named '_cffi_backend'
Traceback (most recent call last):
lib\site-packages\knack\cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli\core\commands\__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
azure\cli\core\__init__.py, ln 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli\core\commands\__init__.py, ln 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
lib\site-packages\knack\commands.py, ln 106, in load_arguments
    cmd_args = self.arguments_loader()
...
lib\site-packages\paramiko\dsskey.py, ln 37, in <module>
    from paramiko.pkey import PKey
lib\site-packages\paramiko\pkey.py, ln 31, in <module>
    import bcrypt
lib\site-packages\bcrypt\__init__.py, ln 25, in <module>
    from . import _bcrypt  # type: ignore
ModuleNotFoundError: No module named '_cffi_backend'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.6
Installer: PIP

azure-cli 2.14.0 *

```

**Comment by yonzhan** [comment] 2020-12-22 11:38
aks

**Comment by RakeshMohanMSFT** [comment] 2022-08-09 08:55
Duplicate of https://github.com/Azure/azure-cli/issues/15860

**Closed by RakeshMohanMSFT** 2022-08-09 08:55 UTC
Labels: Service Attention, question, AKS
