### ISSUE TITLE
Browse connection failed

### ISSUE THREAD

**Issue by alexandresilvadev** [Azure/azure-cli#9754] opened 2019-06-21 01:32 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05358770>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente',))
Traceback (most recent call last):
pip-install-izsysaz4\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
urllib3\urllib3\util\connection.py, ln 70, in create_connection
...
pip-install-dsvrkf2x\requests\requests\adapters.py, ln 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05358770>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse -g {} -n {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.65 *

```

**Comment by seanmck** [comment] 2019-07-14 07:10
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:10 UTC
Labels: AKS
