### ISSUE TITLE
python3.7 errors in both my laptop and AZ bash shell

### ISSUE THREAD

**Issue by jimsander** [Azure/azure-cli#8513] opened 2019-02-13 03:47 UTC
have about 20 subscriptions, and only works for a small subset, most fail with python errors 

```
$ az role assignment list-changelogs --subscription "f4241813-4cfa-4a52-9b8d-9cab0865c2d4" --start-time '2019-02-01T00:00:00Z' -o json
'properties'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.55/libexec/lib/python3.7/sit
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dacfad8-cb2f-2534-3b29-89b0930a2252
* Version Independent ID: 17325cd4-44c5-4069-d9f6-940a55f0f7c9
* Content: [az role assignment](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest#az-role-assignment-list-changelogs)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment] 2019-02-14 02:47
how did you install the azure-cli? please run the command with --debug and share with me the full stack trace

**Comment by patros** [comment] 2019-05-02 03:07
I'm having the same issue @yugangw-msft 

I've been trying out custom roles. And judging by the stack trace it is related.

I was testing them out. Created one, assigned it, unassigned it and deleted it. And did stuff like that a few times.

[stacktrace.txt](https://github.com/Azure/azure-cli/files/3136606/stacktrace.txt)

**Comment by patros** [comment] 2019-05-02 03:13
Just did a bit more testing @yugangw-msft. Looks like the creating and deleting a custom role is irrelevant.

Interestingly when I revoke a custom role assignment it works fine. But when I make a new custom role assignment it fails.

**Comment by yugangw-msft** [comment] 2019-05-02 03:40
@patros, I can't reproduce this, but I have submitted a PR to avoid this crash and continue to retrieving more logs.

**Comment by patros** [comment] 2019-05-03 00:00
@yugangw-msft thanks!

**Closed** 2019-05-03 01:50 UTC
Labels: Authorization-cli, Question
