### ISSUE TITLE
setup: invalid azure-mgmt-resource dependency  

### ISSUE THREAD

**Issue by dbilleci-lightstream** [Azure/azure-cli#10526] opened 2019-09-13 16:58 UTC
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
APIVersion 2019-05-10 is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/parameters.py, ln 137, in get_resources_in_subscription
    return list(rcf.resources.list(filter=filter_str))
mgmt/resource/resources/resource_management_client.py, ln 257, in resources
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-05-10 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {}`

## Environment Summary
```
Linux-5.0.0-1018-azure-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.8
Shell: bash

azure-cli 2.0.73

```

**Comment by ankurkhemani** [comment] 2019-09-24 22:46
@dbilleci-lightstream I was unable to repro this. Can you please update to the latest az [Version 2.0.74](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#september-24-2019) and try again?

**Comment by yugangw-msft** [comment] 2019-09-30 01:02
This is not an ACR issue; rather a generic setup problem that the SDK azure-mgmt-resource(3.1.0) is missing. Moving to the setup area. 
@fengzhou-msft, please follow up with the @dbilleci-lightstream, particularly what setup option was used to install the CLI.

**Comment by yonzhan** [comment] 2019-09-30 04:58
@fengzhou-msft please take a look and comment.

**Comment by fengzhou-msft** [comment] 2019-09-30 14:49
@dbilleci-lightstream please describe how you installed azure-cli. Based on the error message, the dependency package azure-mgmt-resource is missing.

**Comment by dbilleci-lightstream** [comment] 2019-09-30 16:03
with ansible:

````
  - name: Install Azure Python SDK in venv
    pip:
      name:
        - azure
        - azure-cli
      virtualenv: /opt/ansible/env
      virtualenv_command: python3.6 -m venv
````

**Comment by fengzhou-msft** [comment] 2019-10-11 09:35
@dbilleci-lightstream I'm not able to reproduce the issue using ansible and pip for install on ubuntu 18.04. azure-cli 2.0.73 and the latest 2.0.74 both work for me.  Can you uninstall and then reinstall azure-cli?

**Comment by fengzhou-msft** [comment] 2019-10-22 09:09
Close due to inactivity. Please reopen or issue a new ticket if you still have issues.

**Closed by fengzhou-msft** 2019-10-22 09:09 UTC
Labels: Packaging

**Comment by carbolymer** [comment] 2019-10-28 08:33
I'm having the same issue:

```
az acr login --name name
The command failed with an unexpected error. Here is the traceback:

APIVersion 2019-05-10 is not available
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/acr/custom.py", line 126, in acr_login
    password=password)
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 297, in get_login_credentials
    only_refresh_token=True)
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 198, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name)
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/acr/_utils.py", line 90, in get_registry_by_name
    cli_ctx, registry_name, resource_group_name)
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/acr/_utils.py", line 78, in get_resource_group_name_by_registry_name
    cli_ctx, registry_name, REGISTRY_RESOURCE_TYPE)
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/acr/_utils.py", line 32, in _arm_get_resource_by_name
    result = get_resources_in_subscription(cli_ctx, resource_type)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/parameters.py", line 137, in get_resources_in_subscription
    return list(rcf.resources.list(filter=filter_str))
  File "/usr/lib/python3.7/site-packages/azure/mgmt/resource/resources/_resource_management_client.py", line 255, in resources
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-05-10 is not available

To open an issue, please run: 'az feedback'
```

```
azure-cli                         2.0.75

command-modules-nspkg              2.0.3
core                              2.0.75
nspkg                              3.0.4

Extensions:
aks-preview                        0.4.5
storage-preview                    0.2.8
azure-devops                      0.11.0

Python location '/usr/bin/python'
Extensions directory '/home/carbolymer/.azure/cliextensions'

Python (Linux) 3.7.4 (default, Oct  4 2019, 06:57:26) 
[GCC 9.2.0]

Legal docs and information: aka.ms/AzureCliLegal


Unable to check if your CLI is up-to-date. Check your internet connection.
```

any info on that?

**Comment by fengzhou-msft** [comment] 2019-11-26 12:30
@carbolymer can you run `pip show azure-mgmt-resource` and paste the result?
