### ISSUE TITLE
Stack Trace for `az storage account create`

### ISSUE THREAD

**Issue by psenger** [Azure/azure-cli#30127] opened 2024-10-18 11:37 UTC
### Describe the bug

 Unable to create a simple Blob Storage in my Subscription when Im the owner / tenant 
azure-cli  2.65.0

 ![Image](https://github.com/user-attachments/assets/33304cd7-5375-4175-ba98-9745cbfa13fb)

### Related command

az storage account create --resource-group terraform-state-rg --name tfstate-MindMap-8192c793 --sku Standard_LRS --encryption-services blob

### Errors

The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 564, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/core/__init__.py", line 527, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/__init__.py", line 42, in load_arguments
    load_arguments(self, command)
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/_params.py", line 758, in load_arguments
    get_permission_help_string(t_account_permissions)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/_validators.py", line 871, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
                                                           ^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

### Issue script & Debug output

(azure-cli-env) psenger@Philips-MacBook-Pro ~ % az storage account create --resource-group terraform-state-rg --name tfstate-MindMap-8192c793 --sku Standard_LRS --encryption-services blob
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 564, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/core/__init__.py", line 527, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/__init__.py", line 42, in load_arguments
    load_arguments(self, command)
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/_params.py", line 758, in load_arguments
    get_permission_help_string(t_account_permissions)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/_validators.py", line 871, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
                                                           ^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
(azure-cli-env) psenger@Philips-MacBook-Pro ~ %

### Expected behavior

a blob created

### Environment Summary

azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/bin/python'
Extensions directory '/Users/psenger/.azure/cliextensions'

Python (Darwin) 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

Im on a mac...

**Comment by yonzhan** [comment] 2024-10-18 11:37
Thank you for opening this issue, we will look into it.

**Comment by psenger** [comment] 2024-10-18 11:40
this looks the same as https://github.com/Azure/azure-cli/issues/23990

**Comment by psenger** [comment] 2024-10-18 11:51
By the way Im in the Azure Shell in Azure, and I keep getting this error:

(SubscriptionNotFound) Subscription xxxxxxxxxxxxxxxx was not found.
Code: SubscriptionNotFound
Message: Subscription xxxxxxxxxxxxxxxx was not found.

same thing.. very strange.

**Comment by Oli1071** [comment] 2024-10-19 09:46
I encounter the same error when running:
`az storage entity query --table-name your_table_name --account-name your_storage_account --auth-mode login --query "items"
`
Installed:
azure-cli                         2.65.0                

core                              2.65.0
telemetry                          1.1.0

Extensions:
account                            0.2.5

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

However, on my MacBook, where I am still using azure-cli 2.62.0, I do not encounter any errors when running the same command.

**Comment by x97-epe** [comment] 2024-10-20 18:29
I have updated azure-cli to 2.65.0 on my MacBook running Sequoia and a script I have used for while started failing with same error reported here. Many command related to "storage account" seems to fail, no even the "help" can be used. Example: 

% az storage account create --help
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 564, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/__init__.py", line 527, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/__init__.py", line 42, in load_arguments
    load_arguments(self, command)
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/_params.py", line 758, in load_arguments
    get_permission_help_string(t_account_permissions)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/command_modules/storage/_validators.py", line 871, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
                                                           ^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

About Azure-cli:

% az --version 
azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/bin/python'
Extensions directory '/Users/XXXXXX/.azure/cliextensions'

Python (Darwin) 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Thanks!

**Comment by calvinhzy** [comment] 2024-10-21 02:48
Can you run `pip show azure-multiapi-storage` and see if the package is properly installed? Might need to reinstall using `brew update && brew install azure-cli`
![Image](https://github.com/user-attachments/assets/ec514fc6-3822-4502-9af8-b79bf47d142f)

**Comment by psenger** [comment] 2024-10-21 04:22
@calvinhzy Ive actually uninstalled Azure CI, verified it was uninstalled, and reinstalled it, I cant execute pip show azure-multiapi-storage 

By the way, I got the same error with the In-Browser Azure Command. If it doesn't work there, I doubt it works anywhere.

**Comment by calvinhzy** [comment] 2024-10-21 06:07
Can you try the suggestion in https://github.com/Azure/azure-cli/issues/29904#issuecomment-2357344816 to install setuptools

**Comment by rjollos** [comment] 2024-10-21 07:13
Installing setuptools fixes the problem for me on macOS:

```
$ /opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/bin/pip install setuptools
Collecting setuptools
  Downloading setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
Downloading setuptools-75.2.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 18.9 MB/s eta 0:00:00
Installing collected packages: setuptools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azure-cli 2.65.0 requires pycomposefile>=0.0.29, but you have pycomposefile 0.0.1a1 which is incompatible.
````

**Comment by calvinhzy** [comment] 2024-10-21 07:21
https://github.com/Azure/azure-cli/issues/30138#issuecomment-2425824403 
seems like for some reason even if setuptools is put as required in CLI dependencies, homebrew 3.12 does not install it

**Comment by x97-epe** [comment] 2024-10-21 10:53
@rjollos Thanks, you suggestion worked for me. 

I have other homebrew:
% brew -v
Homebrew 4.4.2

And it took me some extra effort (and brew doctor feedback) to get "setuptools" installed, but once done (still with errors) "azure-cli storage account" works.

**Comment by jaromirmikulik** [comment] 2024-10-21 11:25
From my perspective, it could be caused by: https://github.com/Azure/azure-cli/issues/30148

**Comment by ferben** [comment] 2024-10-21 11:55
> Installing setuptools fixes the problem for me on macOS with Azure CLI installed by Homebrew.
> 
> ```
> $ /opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/bin/pip install setuptools
> Collecting setuptools
>   Downloading setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
> Downloading setuptools-75.2.0-py3-none-any.whl (1.2 MB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 18.9 MB/s eta 0:00:00
> Installing collected packages: setuptools
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> azure-cli 2.65.0 requires pycomposefile>=0.0.29, but you have pycomposefile 0.0.1a1 which is incompatible.
> ```

This help, regardless of it install setuptools with error.

**Comment by allullk** [comment] 2024-10-21 17:55
@psenger Just used:

```az provider register --namespace Microsoft.Storage```

Worked for me 😊

Credits: @kenorb
#29215

**Comment by rogerkeizer** [comment] 2024-10-22 10:02
I ran in this problem as well and had the luxury of a Macbook with hardly any data on it. So I could try out a few suggestions mentioned here. 

This is what I did to finally solve my issue:
- Clean install Sonoma 14.4 (System Settings / General / Transfer or Reset)
- No installation of Xcode developer tools (you need them if you want to do `python3 --version`)
- Upgrade to Python 3.12.7 ([Python 3.12.7](https://www.python.org/downloads/macos/)) using the [macOS 64-bit universal2 installer](https://www.python.org/ftp/python/3.12.7/python-3.12.7-macos11.pkg)
- Install Certificates.command
- `python3 --version` -> 3.12.7
- Install Homebrew [Homebrew.pkg 4.4.2](https://github.com/Homebrew/brew/releases/tag/4.4.2)
    - pre-requisite Command Line Tools (CLT): `xcode-select --install` -> follow instructions on screen
    - `eval "$(/opt/homebrew/bin/brew shellenv)"`
- `brew update && brew install azure-cli`
- `az login`
- `az storage account list` returns my storage accounts and not the __'NoneType' object is not iterable__ error anymore

**Comment by Oli1071** [comment] 2024-10-22 10:35
It seems an update fixed it. I run brew update and brew upgrade, what updates azure-cli. Now my storage account comments work again.

**Comment by bebound** [comment] 2024-11-29 05:32
Caused by https://github.com/Homebrew/homebrew-core/pull/192912.
In 3.12, setuptools is not installed by default.

Already fixed in homebrew.

Related PR:
https://github.com/Homebrew/homebrew-core/pull/194884
https://github.com/Homebrew/homebrew-core/pull/195087

**Closed by bebound** 2024-11-29 05:32 UTC
Labels: Storage, question, customer-reported, Auto-Assign, Azure CLI Team, Similar-Issue
