### ISSUE TITLE
Cosmos DB does not return connection string

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-cli#6093] opened 2018-04-12 03:33 UTC
```
az cosmosdb list-connection-strings -g inventory-hub -n mycosmosdb03302018
 
{
  "additionalProperties": {},
  "connectionStrings": null
}
```

Empty connections string

**Comment by mindlessroman** [comment] 2018-12-10 18:35
See also #4419 as another report.

**Comment by tjprescott** [comment] 2018-12-10 19:41
Thank you @mindlessroman. Closing this issue as it is a duplicate of #4419.

**Closed by tjprescott** 2018-12-10 19:41 UTC
Labels: CosmosDB, Service Attention
