### ISSUE TITLE
Cannot call az quota commands if resource name contains spaces

### ISSUE THREAD

**Issue by gabrimonfa** [Azure/azure-cli#27118] opened 2023-08-08 14:08 UTC
### Describe the bug

I'm trying to show quota for a particular compute resource.
Its name unfortunately contains spaces, "Standard NCASv3_T4 Family".
This is the official name

```
{
  "id": "/subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral/providers/Microsoft.Quota/quotas/Standard NCASv3_T4 Family",
  "name": "Standard NCASv3_T4 Family",
  "properties": {
    ...
    "name": {
      "localizedValue": "Standard NCASv3_T4 Family vCPUs",
      "value": "Standard NCASv3_T4 Family"
    },
    snip...
}
```

Apparently I've found no way of passing it to the cli, even with proper quotation, because spaces are url-escaped when the api is called from python

```
az quota show --resource-name="Standard NCASv3 T4Family" --scope subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral --debug
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral/providers/Microsoft.Quota/quotas/Standard%20NCASv3%20T4Family?api-version=2021-03-15-preview HTTP/1.1" 400 114
...
cli.azure.cli.core.azclierror: (InvalidResourceName) Name Standard%20NCASv3%20T4Family is not valid resource name.
```

If I list compute resources, many of them has no spaces, some one space, between Standard and the rest, some two spaces.
Only resource names with spaces are problematic.

`az quota list --scope subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral | jq .[].name`

Is there any possible workaround to be able to call for instance az quota create passing a resource name with spaces?

### Related command

az quota show --resource-name="Standard NCASv3 T4Family" --scope subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral

### Errors

cli.azure.cli.core.azclierror: (InvalidResourceName) Name Standard%20NCASv3%20T4Family is not valid resource name.

### Issue script & Debug output

Already in main description

### Expected behavior

I would expect the az quota commands to work even where resource names have spaces.

### Environment Summary

```
"azure-cli": "2.51.0",
"azure-cli-core": "2.51.0",
"azure-cli-telemetry": "1.1.0",
"extensions": {
  "account": "0.2.5",
  "aks-preview": "0.5.128",
  "quota": "0.1.0"
}
```

**Comment by yonzhan** [comment] 2023-08-08 14:09
Thank you for opening this issue, we will look into it.

**Comment by gabrimonfa** [comment] 2023-08-30 11:10
Any news on this?
@yonzhan Being unable to use a certain resource because its name differs from the others does not qualify as a bug and it's a feature request? Sounds a little surprising to me.

**Comment by jsntcy** [comment] 2023-09-20 07:44
@gabrimonfa, please refer to https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#use-quotation-marks-in-parameters to see if it can help you on your issue.

**Comment by gabrimonfa** [comment] 2023-09-22 09:01
@jsntcy it cannot help. bash quoting is already ok.
The name "Standard NCASv3 T4Family" becomes Standard%20NCASv3%20T4Family in url escaping in urllib3 python library used to perform the call inside az cli.
Spaces are replaced with %20.


`az quota show --resource-name="Standard NCASv3 T4Family" --scope subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral --debug`  <-- **resource-name is correctly quoted**

`urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral/providers/Microsoft.Quota/quotas/Standard%20NCASv3%20T4Family?api-version=2021-03-15-preview`    <-- **it becomes part of the url so it's url escaped**

`cli.azure.cli.core.azclierror: (InvalidResourceName) Name Standard%20NCASv3%20T4Family is not valid resource name.`  <-- **the url-escaped name is unexpected**

So this resource (and the others with spaces in the name, just two or three of them) cannot be used afaik with az cli quota command.
IMHO this is a bug, unless there is an alternative way to show the quota of that resource that works

**Comment by jsntcy** [comment] 2023-09-25 05:40
@jiasli, could you please help on this issue?

**Comment by jsntcy** [comment] 2023-09-26 05:58
> @jsntcy Yu Chen FTE it cannot help. bash quoting is already ok. The name "Standard NCASv3 T4Family" becomes Standard%20NCASv3%20T4Family in url escaping in urllib3 python library used to perform the call inside az cli. Spaces are replaced with %20.
> 
> `az quota show --resource-name="Standard NCASv3 T4Family" --scope subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral --debug` <-- **resource-name is correctly quoted**
> 
> `urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral/providers/Microsoft.Quota/quotas/Standard%20NCASv3%20T4Family?api-version=2021-03-15-preview` <-- **it becomes part of the url so it's url escaped**
> 
> `cli.azure.cli.core.azclierror: (InvalidResourceName) Name Standard%20NCASv3%20T4Family is not valid resource name.` <-- **the url-escaped name is unexpected**
> 
> So this resource (and the others with spaces in the name, just two or three of them) cannot be used afaik with az cli quota command. IMHO this is a bug, unless there is an alternative way to show the quota of that resource that works

Could you please provide the full debug log with `--debug`?

**Comment by jsntcy** [comment] 2023-09-27 07:44
@rahuls-microsoft, could you please help take a look at this issue as it seems it's due to service limitation?

**Comment by gabrimonfa** [comment] 2023-10-04 15:41
@jsntcy, here is the full debug log

[27118_debug.log](https://github.com/Azure/azure-cli/files/12805342/27118_debug.log)

**Comment by jsntcy** [comment] 2023-10-08 03:22
From the debug log, seems it's a service limitation as the error is returned from service. @rahuls-microsoft, could you please help look at the issue?

`DEBUG: msal.telemetry: Generate or reuse correlation_id: 691cac95-abfc-4487-8591-ef2e73143f40
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Compute/locations/swedencentral/providers/Microsoft.Quota/quotas/Standard%20NCASv3_T4%20Family?api-version=2021-03-15-preview'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '0b6056c0-62cb-11ee-9838-00155db2cde5'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'quota show'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-name --scope --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (DEB) azsdk-python-azurequotaextensionapi/unknown Python/3.10.10 (Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Compute/locations/swedencentral/providers/Microsoft.Quota/quotas/Standard%20NCASv3_T4%20Family?api-version=2021-03-15-preview HTTP/1.1" 400 115
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 400
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '115'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '4266dc6c-ed77-42cb-bcd8-a48ebc21cd30'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '4266dc6c-ed77-42cb-bcd8-a48ebc21cd30'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'ITALYNORTH:20231004T153111Z:4266dc6c-ed77-42cb-bcd8-a48ebc21cd30'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 04 Oct 2023 15:31:10 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"InvalidResourceName","message":"Name Standard%20NCASv3_T4%20Family is not valid resource name."}}`

**Comment by gabrimonfa** [comment] 2023-10-10 07:21
Hi all, is there any update or eta on this issue?
Thank you

**Comment by gabrimonfa** [comment] 2023-10-23 16:00
@jsntcy, @rahuls-microsoft sorry for bothering but I need an update on this issue, if possible.

**Comment by gabrimonfa** [comment] 2023-11-15 09:28
There are multiple elements which has a space in the name, probably these names should be fixed removing the space, as it was done with other families.
Please fix them, otherwise they cannot be used with the cli.

```
az quota list --scope subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral | jq .[].name

"availabilitySets"
"cores"
"virtualMachines"
"virtualMachineScaleSets"
"dedicatedVCpus"
"cloudServices"
"lowPriorityCores"
"standardDDSv5Family"
"basicAFamily"
"standardA0_A7Family"
"standardA8_A11Family"
"standardDFamily"
"standardDv2Family"
"standardDSFamily"
"standardDSv2Family"
"standardGFamily"
"standardGSFamily"
"standardFFamily"
"standardFSFamily"
"standardNVFamily"
"standardNCFamily"
"standardHFamily"
"standardAv2Family"
"standardLSFamily"
"standardDv2PromoFamily"
"standardDSv2PromoFamily"
"standardMSFamily"
"standardDv3Family"
"standardDSv3Family"
"standardEv3Family"
"standardESv3Family"
"standardDv4Family"
"standardDDv4Family"
"standardDSv4Family"
"standardDDSv4Family"
"standardEv4Family"
"standardEDv4Family"
"standardESv4Family"
"standardEDSv4Family"
"standardBSFamily"
"standardFSv2Family"
"standardNDSFamily"
"standardNCSv2Family"
"standardNCSv3Family"
"standardLSv2Family"
"standardPBSFamily"
"standardEIv3Family"
"standardEISv3Family"
"standardDCSFamily"
"standardNVSv2Family"
"standardMSv2Family"
"standardHBSFamily"
"standardHCSFamily"
"standardNVSv3Family"
"standardNVPromoFamily"
"standardNCPromoFamily"
"standardHPromoFamily"
"standardDAv4Family"
"standardDASv4Family"
"standardEAv4Family"
"standardEASv4Family"
"standardNDSv3Family"
"standardDCSv2Family"
"standardNVSv4Family"
"standardNDSv2Family"
"standardNPSFamily"
"standardHBrsv2Family"
"Standard NCASv3_T4 Family" <-- THIS HAS SPACES INSIDE THE NAME
"Standard NDASv4_A100 Family" <-- THIS HAS SPACES INSIDE THE NAME
"standardXEIDSv4Family"
"standardXEISv4Family"
"standardEIASv4Family"
"standardHBv3Family"
"standardMDSMediumMemoryv2Family"
"standardMIDSMediumMemoryv2Family"
"standardMSMediumMemoryv2Family"
"standardMISMediumMemoryv2Family"
"standardDASv5Family"
"standardEASv5Family"
"standardEv5Family"
"standardEIv5Family"
"standardEDv5Family"
"standardEIDv5Family"
"standardESv5Family"
"standardEISv5Family"
"standardEDSv5Family"
"standardEIDSv5Family"
"standardDv5Family"
"standardDDv5Family"
"standardDSv5Family"
"standardDLSv5Family"
"standardDLDSv5Family"
"standardLSv3Family"
"standardLASv3Family"
"standardDCSv3Family"
"standardDDCSv3Family"
"standardDADSv5Family"
"standardEADSv5Family"
"standardFXMDVSFamily"
"standardDPLDSv5Family"
"standardDPLSv5Family"
"standardDPDSv5Family"
"standardDPSv5Family"
"standardEPDSv5Family"
"standardEPSv5Family"
"standard NDAMSv4_A100Family" <-- THIS HAS SPACES INSIDE THE NAME
"standardDCASv5Family"
"standardECASv5Family"
"standardECIASv5Family"
"standardDCADSv5Family"
"standardECADSv5Family"
"standardECIADSv5Family"
"StandardNVADSA10v5Family"
"StandardNCADSA100v4Family"
"standardEBDSv5Family"
"standardEBSv5Family"
"standardEIASv5Family"
"standardEIADSv5Family"
"StandardNCADSA10v4Family"
"standardDCACCV5Family"
"standardDCADCCV5Family"
"standardECACCV5Family"
"standardECADCCV5Family"
"standardEIBDSv5Family"
"standardEIBSv5Family"
"standardDCEV5Family"
"standardDCEDV5Family"
"standardECEV5Family"
"standardECEDV5Family"
"standardHBv4Family"
"standardHXFamily"
"standardBpsv2Family"
"standardBsv2Family"
"standardBasv2Family"
"standardNDSH100v5Family"
"StandardNGADSV620v1Family"
"standardECIEV5Family"
"standardECIEDV5Family"
"StandardDiskCount"
"PremiumDiskCount"
"StandardSSDDiskCount"
"StandardSSDZRSDiskCount"
"PremiumZRSDiskCount"
"UltraSSDDiskCount"
"PremiumV2DiskCount"
"StandardSnapshotCount"
"StandardSSDSnapshotCount"
"PremiumSnapshotCount"
"ZRSSnapshotCount"
"UltraSSDDiskSizeInGB"
"PremiumV2DiskSizeInGB"
"DiskEncryptionSetCount"
"DiskAccessCount"
"Gallery"
"GalleryImage"
"GalleryImageVersion"
"GalleryApplicationVersion"
```

**Comment by zhengdawu-db** [comment] 2023-11-28 18:49
+1 on this issue, could we prioritize fixing it? @yonzhan

**Comment by gabrimonfa** [comment] 2023-12-22 08:58
@rahuls-microsoft, @jsntcy I have some activities which are blocked by this bug, and I cannot leave them pending forever.
It will ever be fixed or should I give up?
This is not about priority obviously, but lack of communication.
This bug is very reproducible, with a clear root cause, and troubleshooting and triage have already been done AFAIK.
I would like to have an eta, one month, one release, one year, don't-hold-your-breath-this-will-never-be-fixed.
Some feedback will be warmly appreciated and needed at this point.

**Comment by jsntcy** [comment] 2023-12-25 06:25
This issue is probably a service issue (not a CLI issue, our team is only responsible for CLI side) and most of the members of service team are in vacation, this issue will probably be revisited in early next month (will check with service team at that time).

**Comment by Jing-song** [comment] 2023-12-26 08:08
Hi @gabrimonfa 
In `az quota list --scope subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral`, 
each resource has its ID, so does its ID also contain spaces? can you use the resource name in the id to use the show command


az quota usage show  --scope /subscriptions/subid/providers/Microsoft.Network/locations/eastus --resource-name '**RoutefilterrulesperRouteFilter**'
{
  "id": "/subscriptions/subid/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/**RoutefilterrulesperRouteFilter**",
  "name": "RouteFilterRulesPerRouteFilter",
  "properties": {
    "isQuotaApplicable": false,
    "name": {
      "localizedValue": "Route filter rules per Route Filter",
      "value": "RouteFilterRulesPerRouteFilter"
    },
    "properties": {},
    "unit": "Count",
    "usages": {
      "usagesType": "Individual",
      "value": 0
    }
  },
  "type": "Microsoft.Quota/Usages"
}

**Comment by Jing-song** [comment] 2023-12-28 01:52
Hi @gabrimonfa , I have confirmed the cause of the error with the service team and the bug will be fixed.

> For the resource name containing spaces, I found that it's an issue with the service and we aren't removing the escaping the spaces when ingesting the resource name. I have completed the fix but cannot deploy the fix until the deployment lockdown is lifted on January 8th. I will plan to deploy the fix that week. Thanks

**Comment by Jing-song** [comment] 2024-01-09 01:49
Hi @gabrimonfa ,service team has fixed it, please try again.

**Comment by gabrimonfa** [comment] 2024-01-10 10:06
> Hi @gabrimonfa ,service team has fixed it, please try again.

Hi, @Jing-song, I've tried and I cannot see any difference. Is there a mistake on my part?

`az quota list --scope subscriptions/$UUID/providers/Microsoft.Compute/locations/swedencentral | jq .[].name | grep NCAS`
```
"Standard NCASv3_T4 Family"
```

and

`az quota show --resource-name="Standard NCASv3_T4 Family" --scope subscriptions/$UUID/providers/Microsoft.Compute/locations/swedencentral`
```
(InvalidResourceName) Name Standard%20NCASv3_T4%20Family is not valid resource name.
Code: InvalidResourceName
Message: Name Standard%20NCASv3_T4%20Family is not valid resource name
```

I've upgraded quota extension just to be sure but nothing changed

`az version`
```json
{
  "azure-cli": "2.55.0",
  "azure-cli-core": "2.55.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "0.5.174",
    "quota": "1.0.0"
  }
}
```

**Comment by Jing-song** [comment] 2024-01-10 11:00
Hi @ahnj12, has this change been deployed?

**Comment by Jing-song** [comment] 2024-01-12 01:39
Hi @gabrimonfa, it's in the process of being deployed
![image](https://github.com/Azure/azure-cli/assets/37168047/9604a020-25e3-47a9-99bb-53b2af7914b2)

**Comment by gabrimonfa** [comment] 2024-01-15 08:52
Hi @Jing-song, it seems solved now.
Thank you

```
az quota show --resource-name="Standard NCASv3_T4 Family" --scope subscriptions/$UUID/providers/Microsoft.Compute/locations/swedencentral

{
  "id": "/subscriptions/<UUID>/providers/Microsoft.Compute/locations/swedencentral/providers/Microsoft.Quota/quotas/Standard NCASv3_T4 Family",
  "name": "Standard NCASv3_T4 Family",
  "properties": {
    "isQuotaApplicable": true,
    "limit": {
      "limitObjectType": "LimitValue",
      "limitType": "Independent",
      ...
  "type": "Microsoft.Quota/Quotas"
}
```

**Closed** 2024-01-16 03:41 UTC
Labels: Service Attention, customer-reported, feature-request, quota, Azure CLI Team
