### ISSUE TITLE
Role assignment creation failed through `az ad sp create-for-rbac` command

### ISSUE THREAD

**Issue by francisrod01** [Azure/azure-cli#22837] opened 2022-06-11 00:36 UTC
## Describe the bug

I'm following the Azure container Apps doc to [Create a service principal and store credential](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task#create-a-service-principal-and-store-credentials).

**Command Name**
`az ad sp create-for-rbac`

```bash
az ad sp create-for-rbac \
                --name $ACR_NAME-pull \
                --scopes $(az acr show --name $ACR_NAME --query id --output tsv) \
                --role acrpull \
                --query password \
                --output tsv
```

**Errors:**
```
This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
Found an existing application instance: (id) 7a2e34bf-443. We will patch it.
Creating 'acrpull' role assignment under scope '/subscriptions/71c1f426-e8cf/resourceGroups/dev-containerapps/providers/Microsoft.ContainerRegistry/registries/acadevfrancisrod01'
  Role assignment creation failed.


The command failed with an unexpected error. Here is the traceback:
'RoleAssignmentsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/commands.py", line 54, in graph_err_handler
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 1193, in create_service_principal_for_rbac
    _create_role_assignment(cmd.cli_ctx, role, sp_oid, None, scope, resolve_assignee=False,
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 196, in _create_role_assignment
    assignments_client.config.subscription_id)
AttributeError: 'RoleAssignmentsOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --name {} --scopes {} --role {} --query {} --output {}`

## Environment Summary
```
Linux-5.17.0-1-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
containerapp 0.3.6
deploy-to-azure 0.2.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment] 2022-06-11 00:43
@jiasli for awareness

**Comment by francisrod01** [comment] 2022-06-11 23:07
More to add:

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac)
* Content Source: [latest/docs-ref-autogen/ad/sp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/sp.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by francisrod01** [comment] 2022-06-12 04:33
I think you guys are working on it, 
'cause I keep seeing the deprecated message, but I could run it successfully. 🚀 🎉

**Comment by jiasli** [comment] 2022-06-13 03:22
Duplicate of #19640

**Closed by jiasli** 2022-06-13 03:22 UTC
Labels: Graph, customer-reported, Auto-Assign

**Comment by spanchal1980** [comment] 2023-09-18 15:49
Any update on this. I am getting same issue.
