### ISSUE TITLE
az find returns error 400 (BodyMalformed)

### ISSUE THREAD

**Issue by mbirgi** [Azure/azure-cli#14094] opened 2020-06-24 15:35 UTC
## Describe the bug

**Command Name**
`az find`

**Errors:**
`[?] Unexpected Error: [HTTP 400]: Content: b'{"error":{"code":"BadRequest","message":"The request message could not be processed. Please check it for errors.","target":null,"details":[{"code":"BodyMalformed","message":"The request body is missing required properties","target":null,"details":[{"code":"BodyMalformed","message":"The request was missing: context","target":null,"details":null,"innererror":null}],"innererror":null}],"innererror":null}}'`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az find blob`

## Expected Behavior
some output according to docs

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.8.0

```

**Comment by yonzhan** [comment] 2020-06-24 23:36
az find

**Comment by yungezz** [comment] 2020-06-25 00:12
add @christopher-o-toole @mirdaki to help have a look

**Comment by mirdaki** [comment] 2020-06-25 04:15
My guess it that the user was not logged into a subscription. I'll look at our telemetry to see if I can find this call to verify. 

We will work on a fix for the next release.

**Comment by mbirgi** [comment] 2020-06-28 14:46
Update: after a while, as I was trying to show the problem to a colleague, it worked without error. I didn't change or do anything in the shell, just retried after a few hours. I have no idea what it might have been, and I can't reproduce it anymore. I'll let you know if it happens again.

**Comment by mirdaki** [comment] 2020-06-29 21:36
Thank you for the update! That is weird. Fortunately I did find an improvement for `az find`, which I will work on, but it wouldn't explain why it started working later.

**Comment by mbirgi** [comment] 2020-07-01 08:13
also, in case it helps your debugging: I think that I *was* logged in, since other stuff was working, I only had trouble with the "az find" command. hth ;-)

**Comment by mirdaki** [comment] 2020-07-06 22:41
@mbirgi Did you happen to have telemetry disabled? That would of also caused an issue.

**Comment by mbirgi** [comment] 2020-07-07 07:31
@mirdaki: I don't know, do you know if I can still check it?

**Comment by mirdaki** [comment] 2020-07-07 16:53
You can check if telemetry is enabled or disabled by opening up the config file (`C:\Users\NAME\.azure\config` on Windows) and checking in the core section. Mine looks like this:
```
[core]
output = json
collect_telemetry = yes
cache_ttl = 10
```

I haven't merged my changes yet, so if that's the problem, you would (hopefully 😅) be able to reproduce it.

**Closed** 2020-07-09 15:44 UTC
Labels: Find, Service Attention
