### ISSUE TITLE
AZ CLI version >2.39  - response parsing is broken for most of network commands

### ISSUE THREAD

**Issue by ankirich** [Azure/azure-cli#26613] opened 2023-06-06 06:35 UTC
### Describe the bug

Hi,
AZ CLI commands run with the docker container beyond the version 2.39.0 seem to be broken from the perspective of respons parsing. I.e. the command, once it sent, trigger the execution process on the Azure backend, but the return response  has a error parsing   - "option values must be strings"

At the same time, the same command run with the use of AZ CLI 2.30.0. works as expected.

Here is the example.  There are two aliases:
- az30 - that one calls the az command from the docker 2.30.0
- az49 - the same command but using docker 2.49.0

az30 network route-table create -n test-au0etk3-rt-test30 -l australiaeast -g test-au0etk3-vnet-rg

DisableBgpRoutePropagation    Location       Name                  ProvisioningState    ResourceGroup         ResourceGuid
----------------------------  -------------  --------------------  -------------------  --------------------  ------------------------------------
False                         australiaeast  test-au0etk3-rt-test30  Succeeded            test-au0etk3-vnet-rg  xxxx-xxxxx-xxxxx

az49 network route-table create -n test-au0etk3-rt-test49 -l australiaeast -g test-au0etk3-vnet-rg
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: option values must be strings
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 680, in execute
    self.cli_ctx.save_local_context(parsed_args, self.commands_loader.command_table[command].arguments,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 154, in save_local_context
    self.local_context.set(lca.scopes, lca.name, value)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/local_context.py", line 116, in set
    self._local_context_file.set_value(scope.lower(), argument, value)
  File "/usr/local/lib/python3.10/site-packages/knack/config.py", line 239, in set_value
    config.set(section, option, value)
  File "/usr/local/lib/python3.10/configparser.py", line 1205, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/local/lib/python3.10/configparser.py", line 1190, in _validate_value_types
    raise TypeError("option values must be strings")

thx
Anton

### Related command

az network route-table create

### Errors

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: option values must be strings
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 680, in execute
    self.cli_ctx.save_local_context(parsed_args, self.commands_loader.command_table[command].arguments,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 154, in save_local_context
    self.local_context.set(lca.scopes, lca.name, value)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/local_context.py", line 116, in set
    self._local_context_file.set_value(scope.lower(), argument, value)
  File "/usr/local/lib/python3.10/site-packages/knack/config.py", line 239, in set_value
    config.set(section, option, value)
  File "/usr/local/lib/python3.10/configparser.py", line 1205, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/local/lib/python3.10/configparser.py", line 1190, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Issue script & Debug output

az49 network route-table create -n test-au0etk3-rt-test48 -l australiaeast -g test-au0etk3-vnet-rg --debug
DEBUG: cli.knack.cli: Command arguments: ['network', 'route-table', 'create', '-n', 'test-au0etk3-rt-test48', '-l', 'australiaeast', '-g', 'test-au0etk3-vnet-rg', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f3748dc5360>, <function OutputProducer.on_global_arguments at 0x7f3748c9c040>, <function CLIQuery.on_global_arguments at 0x7f3748cc52d0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: network                   0.448       113       346
DEBUG: cli.azure.cli.core: privatedns                0.003        14        66
DEBUG: cli.azure.cli.core: Total (2)                 0.451       127       412
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0
DEBUG: cli.azure.cli.core: Loaded 126 groups, 412 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : network route-table create
DEBUG: cli.azure.cli.core: Command table: network route-table create
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f37473ca170>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/root/.azure/commands/2023-06-06.06-29-12.network_route-table_create.1.log'.
INFO: az_command_data_logger: command args: network route-table create -n {} -l {} -g {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f37470acb80>]
INFO: cli.knack.commands: Configured default 'test-au0etk3-vnet-rg' for arg resource_group
INFO: cli.knack.commands: Configured default 'australiaeast' for arg location
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f37470acaf0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f3746bc7250>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f3748c9c0d0>, <function CLIQuery.handle_query_parameter at 0x7f3748cc5360>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f37473ceb00>]
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='/root/.azure/msal_token_cache.json', encrypt=False
DEBUG: cli.azure.cli.core.auth.binary_cache: load: /root/.azure/msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/cdf226d7-79fd-4290-a3a7-996968201a26/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/cdf226d7-79fd-4290-a3a7-996968201a26/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/cdf226d7-79fd-4290-a3a7-996968201a26/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/cdf226d7-79fd-4290-a3a7-996968201a26/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/cdf226d7-79fd-4290-a3a7-996968201a26/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/cdf226d7-79fd-4290-a3a7-996968201a26/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/cdf226d7-79fd-4290-a3a7-996968201a26/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: cf7d1fc9-2286-4edb-8ea3-0599cf4fcf41
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/skip_subs_id/resourceGroups/test-au0etk3-vnet-rg/providers/Microsoft.Network/routeTables/test-au0etk3-rt-test48?api-version=2021-08-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'PUT'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '29'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '73185fca-0433-11ee-9d0e-0242ac11000b'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'network route-table create'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -l -g --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (DOCKER) (AAZ) azsdk-python-core/1.26.0 Python/3.10.11 (Linux-3.10.0-1160.83.1.0.1.el7.x86_64-x86_64-with)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: {"location": "australiaeast"}
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/skip_subs_id/resourceGroups/test-au0etk3-vnet-rg/providers/Microsoft.Network/routeTables/test-au0etk3-rt-test48?api-version=2021-08-01 HTTP/1.1" 200 None
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '7768c11b-a37d-4eb4-95de-a7a5f9d0aa5c'
DEBUG: cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'https://management.azure.com/subscriptions/skip_subs_id/providers/Microsoft.Network/locations/australiaeast/operations/7768c11b-a37d-4eb4-95de-a7a5f9d0aa5c?api-version=2021-08-01'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '0c9448f2-116d-4ef1-8c14-2865911118db'
DEBUG: cli.azure.cli.core.sdk.policies:     'Azure-AsyncNotification': 'Enabled'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': '4105ccf5-f62f-4a6b-adaf-6a7ab47b0e87'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHCENTRALUS:20230606T062913Z:0c9448f2-116d-4ef1-8c14-2865911118db'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 06 Jun 2023 06:29:12 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {
  "name": "test-au0etk3-rt-test48",
  "id": "/subscriptions/skip_subs_id/resourceGroups/test-au0etk3-vnet-rg/providers/Microsoft.Network/routeTables/test-au0etk3-rt-test48",
  "etag": "W/\"8a866e83-9327-4069-80cd-7ccddf5dc2d6\"",
  "type": "Microsoft.Network/routeTables",
  "location": "australiaeast",
  "tags": {
    "AppName": "test",
    "Environment": "non-prod",
    "Owner": "bla@bla",
    "UAID": "blBLA"
  },
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "8e3aa219-d20e-4de4-a036-4356f5919c84",
    "disableBgpRoutePropagation": false,
    "routes": []
  }
}
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/skip_subs_id/providers/Microsoft.Network/locations/australiaeast/operations/7768c11b-a37d-4eb4-95de-a7a5f9d0aa5c?api-version=2021-08-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '73185fca-0433-11ee-9d0e-0242ac11000b'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'network route-table create'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -l -g --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (DOCKER) (AAZ) azsdk-python-core/1.26.0 Python/3.10.11 (Linux-3.10.0-1160.83.1.0.1.el7.x86_64-x86_64-with)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/skip_subs_id/providers/Microsoft.Network/locations/australiaeast/operations/7768c11b-a37d-4eb4-95de-a7a5f9d0aa5c?api-version=2021-08-01 HTTP/1.1" 200 None
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f963b656-6604-48be-b9d0-3301d2aece84'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '409eac10-5f9d-447b-bb7a-8e7df3ff1e0d'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': '137bd354-ac24-4f2c-9e81-38715cac74d6'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHCENTRALUS:20230606T062913Z:409eac10-5f9d-447b-bb7a-8e7df3ff1e0d'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 06 Jun 2023 06:29:12 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {
  "status": "Succeeded"
}
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/skip_subs_id/resourceGroups/test-au0etk3-vnet-rg/providers/Microsoft.Network/routeTables/test-au0etk3-rt-test48?api-version=2021-08-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '73185fca-0433-11ee-9d0e-0242ac11000b'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'network route-table create'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -l -g --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (DOCKER) (AAZ) azsdk-python-core/1.26.0 Python/3.10.11 (Linux-3.10.0-1160.83.1.0.1.el7.x86_64-x86_64-with)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/skip_subs_id/resourceGroups/test-au0etk3-vnet-rg/providers/Microsoft.Network/routeTables/test-au0etk3-rt-test48?api-version=2021-08-01 HTTP/1.1" 200 None
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'ETag': 'W/"8a866e83-9327-4069-80cd-7ccddf5dc2d6"'
DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'b5ef94ca-d185-4214-996d-e842ebc2f453'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '0bb86915-2444-4a46-92b2-1cbdf15de5c7'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': '2b3ff004-9203-4eb9-acb0-daaae14c5595'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHCENTRALUS:20230606T062913Z:0bb86915-2444-4a46-92b2-1cbdf15de5c7'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 06 Jun 2023 06:29:13 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {
  "name": "test-au0etk3-rt-test48",
  "id": "/subscriptions/skip_subs_id/resourceGroups/test-au0etk3-vnet-rg/providers/Microsoft.Network/routeTables/test-au0etk3-rt-test48",
  "etag": "W/\"8a866e83-9327-4069-80cd-7ccddf5dc2d6\"",
  "type": "Microsoft.Network/routeTables",
  "location": "australiaeast",
  "tags": {
    "AppName": "test",
    "Environment": "non-prod",
    "Owner": "bla@bla",
    "UAID": "blBLA"
  },
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "8e3aa219-d20e-4de4-a036-4356f5919c84",
    "disableBgpRoutePropagation": false,
    "routes": []
  }
}
DEBUG: cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f3746ff5f30>, <function _x509_from_base64_to_hex_transform at 0x7f3746ff5fc0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnFilterResult []
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 680, in execute
    self.cli_ctx.save_local_context(parsed_args, self.commands_loader.command_table[command].arguments,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 154, in save_local_context
    self.local_context.set(lca.scopes, lca.name, value)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/local_context.py", line 116, in set
    self._local_context_file.set_value(scope.lower(), argument, value)
  File "/usr/local/lib/python3.10/site-packages/knack/config.py", line 239, in set_value
    config.set(section, option, value)
  File "/usr/local/lib/python3.10/configparser.py", line 1205, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/local/lib/python3.10/configparser.py", line 1190, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
ERROR: cli.azure.cli.core.azclierror: option values must be strings
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 680, in execute
    self.cli_ctx.save_local_context(parsed_args, self.commands_loader.command_table[command].arguments,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 154, in save_local_context
    self.local_context.set(lca.scopes, lca.name, value)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/local_context.py", line 116, in set
    self._local_context_file.set_value(scope.lower(), argument, value)
  File "/usr/local/lib/python3.10/site-packages/knack/config.py", line 239, in set_value
    config.set(section, option, value)
  File "/usr/local/lib/python3.10/configparser.py", line 1205, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/local/lib/python3.10/configparser.py", line 1190, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
ERROR: az_command_data_logger: option values must be strings
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 680, in execute
    self.cli_ctx.save_local_context(parsed_args, self.commands_loader.command_table[command].arguments,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 154, in save_local_context
    self.local_context.set(lca.scopes, lca.name, value)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/local_context.py", line 116, in set
    self._local_context_file.set_value(scope.lower(), argument, value)
  File "/usr/local/lib/python3.10/site-packages/knack/config.py", line 239, in set_value
    config.set(section, option, value)
  File "/usr/local/lib/python3.10/configparser.py", line 1205, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/local/lib/python3.10/configparser.py", line 1190, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f37473ca3b0>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 3.546 seconds (init: 0.942, invoke: 2.604)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 7023 in cache
INFO: telemetry.check: Returns Positive.
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "/usr/local/bin/python /usr/local/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /root/.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Route table create and human readable response return:
DisableBgpRoutePropagation    Location       Name                  ProvisioningState    ResourceGroup         ResourceGuid
----------------------------  -------------  --------------------  -------------------  --------------------  ------------------------------------
False                         australiaeast  test-au0etk3-rt-test30  Succeeded            test-au0etk3-vnet-rg  xxxx-xxxxx-xxxxx

### Environment Summary

Working:
Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.39.0       2.39.0            1.0.6

Not working:
Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.49.0       2.49.0            1.0.8

**Comment by yonzhan** [comment] 2023-06-06 06:35
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment] 2023-06-07 04:04
It's related to a feature that is about to be deprecated https://github.com/Azure/azure-cli/issues/24726, please take `az config param-persist off` as a workaround

**Comment by necusjz** [comment] 2023-06-07 04:49
Duplicate of https://github.com/Azure/azure-cli/issues/26432.

**Closed by necusjz** 2023-06-07 04:49 UTC
Labels: bug, Network, customer-reported, Auto-Assign, Azure CLI Team, Auto-Resolve, Similar-Issue
