### ISSUE TITLE
Webapp:az webapp up error ("...returns malformed data. Retrying...") when deploying a Python application

### ISSUE THREAD

**Issue by asw101** [Azure/azure-cli#14264] opened 2020-07-08 05:23 UTC
as webapp up returns the following when deploying a Python application:

"Deployment status endpoint https://<...>/api/deployments/latest returns malformed data. Retrying"

Output of `az version` is as follows:
```
{
  "azure-cli": "2.8.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.8.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```

End user is running Linux:

```
$ uname -srm
Linux 5.7.7-arch1-1 x86_64
```

Opening a new issue per https://github.com/Azure/azure-cli/issues/11596 (cc: @panchagnula)

**Comment by yungezz** [comment] 2020-07-08 06:18
routing to appropriate team

**Comment by luciferankon** [comment] 2020-07-11 10:23
I'm also getting the same error. It works when I deploy it from vscode. But the command `az webapp up` does not seem to work

**Comment by panchagnula** [comment] 2020-07-13 17:12
@calvinsID can you investigate this, especially to check if we have a regression. Thanks!

**Comment by calvinsID** [comment] 2020-07-13 22:48
@asw101 Thanks for logging this. I was unable to repro, do you mind sharing what your deployment logs looks like from https://{your webapp}.scm.azurewebsites.net/api/deployments/latest, as well as the logs from running `az webapp up`?

**Comment by panchagnula** [comment] 2020-07-22 03:27
@asw101  / @luciferankon any updates on the ask from Calvin here? Thanks!

**Comment by elbuenizzy** [comment] 2020-07-28 06:01
Hey guys! This worked for me:

I first did a zip of my app, afterwards I used this command instead for the deployment:

az webapp deployment source config-zip --resource-group --name --src clouddrive/.zip

Hope it works for you!

https://docs.microsoft.com/en-us/azure/app-service/deploy-zip

**Comment by panchagnula** [comment] 2020-07-28 17:11
@elbuenizzy glad you found a work around. if zip deploy worked for you for the same content then that means that the BUILD on our end is failing since the only difference is UP does a zip deploy + build and doesn't zip the python env files, & triggers a build on our end to complete the deployment + build.

**Comment by btardif** [comment] 2020-07-29 21:39
@calvinsID can we close this?

**Comment by panchagnula** [comment] 2020-08-03 22:13
@asw101 - do you have updates on this to share details Calvin asked for?

**Comment by calvinsID** [comment] 2020-08-04 18:46
I was suddenly able to repro again, not sure what changed.. Will investigate

**Comment by panchagnula** [comment] 2020-08-18 17:32
@calvinsID are we planning to fix this during this sprint - tomorrow is last day of sprint,

**Comment by panchagnula** [comment] 2020-09-25 03:33
@calvinsID can we close this if this doesn't repro anymore? Thanks!

**Closed** 2020-09-25 23:22 UTC
Labels: Service Attention, Web Apps

**Comment by ankurkapil2020** [comment] 2020-11-14 16:54
hi.. i have the same problem.. could you please help https://ak-app.scm.azurewebsites.net/api/deployments/latest? thanks!

**Comment by anoopk-kr** [comment] 2021-08-30 19:20
Can we have an update on this? It seems to be happening still and none of the answers above says a fix for this?

**Comment by bittebak** [comment] 2022-01-23 16:22
You would expect that this always functions:
```az web up``` 

I have several issues
1. Timeouts
```Deployment endpoint responded with status code 202```
After a while a timeout

2. Invalid response
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
Deployment status endpoint https://<myapp>.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying...

3. Downgrade to Python|3.7
az webapp up will downgrade to 3.7 (from 3.9)

4. Powershell does not support --runtime
If --runtime is use in Powershell, an error will be returned 
```
(env) > az webapp up --sku B1 --name icarus-int  --resource-group <mygroup> --location westeurope --plan <myplan>  --runtime "PYTHON|3.9"
'3.9' is not recognized as an internal or external command,
```
