### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by abhi-markan** [Azure/azure-cli#21723] opened 2022-03-21 16:37 UTC
## Describe the bug

**Command Name**
`az webapp log tail`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2401, in get_streaming_log
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2068, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log tail --name {} --resource-group {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
front-door 1.0.16

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-03-21 22:39
route to CXP team

**Comment by navba-MSFT** [comment] 2022-03-22 08:55
@abhi-markan Thanks for reaching out to us and reporting this issue. This is a duplicate of https://github.com/Azure/azure-cli/issues/20489 . PR https://github.com/Azure/azure-cli/pull/21398 has been filed to address this issue and its merged now. Please use the [most recent version of the AzCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and let us know if you are still facing the same issue. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-03-29 06:27
@abhi-markan I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-03-31 04:23
@abhi-markan I hope you had a chance to follow the action plan suggested in the above comment. We will now proceed with the closure of this issue. If you need any further assistance on this issue, feel free to reopen this thread. We would be happy to help.

**Closed by navba-MSFT** 2022-03-31 04:23 UTC
Labels: Web Apps, App Services, customer-reported, needs-author-feedback, CXP Attention, Auto-Assign
