### ISSUE TITLE
Cannot use az container exec

### ISSUE THREAD

**Issue by czobrisky** [Azure/azure-cli#19735] opened 2021-09-29 19:49 UTC
## Describe the bug
az container exec fails on latest az version. I updated from 2.26 which was also erroring out.
```
{
  "azure-cli": "2.28.0",
  "azure-cli-core": "2.28.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-firewall": "0.12.0",
    "interactive": "0.4.5"
  }
}
```
**Command Name**
`az container exec`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerInstanceManagementClient' object has no attribute 'container'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 609, in container_exec
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/_client_factory.py", line 18, in cf_container
AttributeError: 'ContainerInstanceManagementClient' object has no attribute 'container'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container exec -n {} -g {} --exec-command {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

Extensions:
azure-firewall 0.12.0
interactive 0.4.5

```

**Comment by yonzhan** [comment] 2021-09-29 22:48
route to service team

**Comment by berndverst** [comment] 2021-10-06 19:48
Downgrade to 2.27.2 will fix the issue for now until this is fixed in the latest CLI:
https://github.com/Azure/azure-cli/issues/19789#issuecomment-936997354

**Comment by PramodValavala-MSFT** [comment] 2022-02-08 10:32
@czobrisky Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end with the latest version, I believe this could be closed.

**Closed** 2022-03-02 08:01 UTC
Labels: Service Attention, Container Instances, customer-reported, needs-author-feedback, no-recent-activity
