### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by nicolaibaralmueller** [Azure/azure-cli#7887] opened 2018-11-20 09:23 UTC
Following official installation guide produces errors during installation.

`
lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
`

`
sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu cosmic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu cosmic-updates InRelease                                        
Hit:3 http://archive.ubuntu.com/ubuntu cosmic-backports InRelease                                      
Hit:4 http://archive.ubuntu.com/ubuntu cosmic-security InRelease                                       
Ign:5 https://packages.microsoft.com/repos/azure-cli cosmic InRelease                                  
Err:6 https://packages.microsoft.com/repos/azure-cli cosmic Release
  404  Not Found [IP: 13.80.10.205 443]
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/repos/azure-cli cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

Manual installation via bash script works. However, I cannot update the system anymore because of this error.

**Comment by tjprescott** [comment] 2018-11-20 15:34
We are releasing the Ubuntu package that supports Cosmic later today.

**Comment by tjprescott** [comment] 2018-11-20 15:38
Dupe of #7776. Closing.

**Closed by tjprescott** 2018-11-20 15:38 UTC
Labels: Packaging/Debian

**Comment by nicolaibaralmueller** [comment] 2018-11-21 07:16
> We are releasing the Ubuntu package that supports Cosmic later today.

@tjprescott Just tried an update again and the same error is produced.

**Comment by tjprescott** [comment] 2018-11-21 15:02
Did you run `apt-get update` first to refresh your repositories?

**Comment by nicolaibaralmueller** [comment] 2018-11-23 07:01
@tjprescott 

This is output from today:

Last login: Wed Nov 21 14:13:29 2018 from 192.168.0.158
worker@worker:~$ sudo apt-get update
[sudo] password for worker: 
Hit:1 http://archive.ubuntu.com/ubuntu cosmic InRelease
Get:2 http://archive.ubuntu.com/ubuntu cosmic-updates InRelease [83.2 kB]                
Ign:3 https://packages.microsoft.com/repos/azure-cli cosmic InRelease                                              
Err:4 https://packages.microsoft.com/repos/azure-cli cosmic Release                                                
  404  Not Found [IP: 13.80.10.205 443]
Hit:5 http://archive.ubuntu.com/ubuntu cosmic-backports InRelease
Get:6 http://archive.ubuntu.com/ubuntu cosmic-security InRelease [83.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu cosmic-updates/main amd64 Packages [82.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu cosmic-updates/universe amd64 Packages [40.6 kB]
Reading package lists... Done                             
E: The repository 'https://packages.microsoft.com/repos/azure-cli cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by tjprescott** [comment] 2018-11-26 16:31
Hi @nicolaibaralmueller yes, we have to open a new repo for these builds. Please keep an eye on #7776 which is tracking this issue.

**Comment by nicolaibaralmueller** [comment] 2018-11-27 11:06
I can confirm that update is working again.
