### ISSUE TITLE
Error deploying 'helloworld' webapp tutorial with 'az webapp up'

### ISSUE THREAD

**Issue by frncesc** [Azure/azure-cli#11177] opened 2019-11-10 20:23 UTC
## Describe the bug

Following the steps described in:
https://docs.microsoft.com/ca-es/learn/modules/host-a-web-app-with-azure-app-service/6-exercise-deploy-your-code-to-app-service

... the deployment via "az webapp up" fails due to an internal python script error.

The environment variable values at the moment of launching the command where:

```
$APPLOCATION: "West Europe"
$APPSKU: "F1"
$APPPLAN: "ASP-learncd715f9d529f4604b3808f6b1c-8764"
$APPRG: "learn-cd715f9d-529f-4604-b380-8f6b1c75daea"
$APPNAME: "prova-met"
``` 

**Command Name**
`az webapp up`

**Errors:**
```
'int' object has no attribute 'upper'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/custom.py, ln 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
cli/command_modules/appservice/custom.py, ln 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
cli/command_modules/appservice/utils.py, ln 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'int' object has no attribute 'upper'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name prova-met --resource-group learn-cd715f9d-529f-4604-b380-8f6b1c75daea --plan ASP-learncd715f9d529f4604b3808f6b1c-8764 --sku F1 --location "West Europe"`

## Expected Behavior

Web app should be deployed

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment] 2019-11-11 02:18
Duplicate of #11100

**Comment by panchagnula** [comment] 2019-11-14 16:47
Fixed by https://github.com/Azure/azure-cli/pull/11019

**Closed by panchagnula** 2019-11-14 16:47 UTC
Labels: Service Attention, Web Apps
