### ISSUE TITLE
BUG az container attach

### ISSUE THREAD

**Issue by vfabio** [Azure/azure-cli#10689] opened 2019-09-29 21:08 UTC
## Describe the bug

**Command Name**
`az container attach`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container attach --resource-group {} --name {}`

## Environment Summary
```
Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.74

```

**Comment by jiasli** [comment] 2019-09-30 03:10
Please share the error message received. Thanks.

**Comment by vfabio** [comment] 2019-09-30 10:58
Hi,

        Follow the error:
[root@unknown ~]# az container exec \
>   --resource-group learn-deploy-aci-rg \
>   --name mycontainer \
>   --exec-command /bin/sh
The command failed with an unexpected error. Here is the traceback:

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206,
in invoke
    cmd_result = self.invocation.execute(args)
  File
"/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py",
line 603, in execute
    raise ex
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:618)

To open an issue, please run: 'az feedback'

Em seg, 30 de set de 2019 às 00:11, Jiashuo Li <notifications@github.com>
escreveu:

**Comment by jiasli** [comment] 2021-08-06 06:41
Duplicate of #15121

**Closed** 2021-08-06 06:42 UTC
Labels: Service Attention, Container Instances, customer-reported
