### ISSUE TITLE
AppGateway HTTP settings create/update needs root cert

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#9507] opened 2019-05-29 20:18 UTC
CLI missing support for trusted root certificate. This is at the same level as authentication certificate and is applicable only for V2 SKU.

**Comment by adewaleo** [comment] 2019-05-29 23:40
Please can you give more information? This helps us help you. Maybe something like:

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by amitsriva** [comment] 2019-05-29 23:58
This isnt a bug. Its a feature request. Most of the sections on environment, bug, steps to repro are not relevant.

Trusted root cert is missing in backend http settings. 
"az network application-gateway http-settings create" does not have any way of associating a trusted root cert. There is a --auth-certs param for V1 authentication certificates and similarly it should have a --trusted-root-certs param as well. 
There is a section to create a new root cert with 'az network application-gateway root-cert' but missing the association to http-settings.

**Comment by adewaleo** [comment] 2019-05-30 00:02
I used that as a template of what information is generally helpful. From your original description, I didn't know what command you were referring to or whether you were reporting a bug or requesting a feature.

Thanks for the follow up and adding more detail.

P.S. [Feature request issue template.](https://github.com/Azure/azure-cli/issues/new?template=Feature_request.md)

**Comment by tjprescott** [comment] 2019-05-30 13:31
This is already implemented.

`az network application-gateway root-cert`

**Comment by MyronFanQiu** [comment] 2019-07-31 02:47
@amitsriva Hello. Is this feature request same with the #9604? This PR https://github.com/Azure/azure-cli/pull/9978 has implemented `--root-cert` for `http-settings`.

**Comment by yonzhan** [comment] 2019-08-26 06:26
Since this issue was already covered, we will close it right now. Please reactive it if you have more requirements.

**Closed by yonzhan** 2019-08-26 06:26 UTC
Labels: Feature Request, Network
