### ISSUE TITLE
"az network" without any subcommands tells to run -h instead of just run "-h" directly

### ISSUE THREAD

**Issue by zobelhelas** [Azure/azure-cli#1244] opened 2016-11-04 20:50 UTC
```
$ ./az network
usage: az network [-h]
                  {express-route,application-gateway,dns,lb,route-table,traffic-manager,nic,nsg,vpn-gateway,vnet,local-gateway,vpn-connection,public-ip,list-usages}
                  ...
az network: error: too few arguments
```

Why not show the help directly instead of telling me that I shall run -h instead.

Probably also valid for other sub-commands. (eg `az vm`)

**Comment by mayurid** [comment] 2016-11-05 20:13
@zobelhelas : This is the design of the new CLI as you have observed. Running the command with the right set of parameters simply gives a list of next parameters that the command accepts.
Thanks for feedback here. We will discuss it with the team

@johanste as FYI

**Comment by tjprescott** [comment] 2017-06-02 20:56
This is a duplicate of #981. Closing.

**Closed by tjprescott** 2017-06-02 20:56 UTC
Labels: Discussion
