### ISSUE TITLE
Template Progress

### ISSUE THREAD

**Issue by oakeyc** [Azure/azure-cli#3560] opened 2017-05-31 18:08 UTC
### Description
**Outline the issue here:**
For commands that use template deployments, the CLI can get more information about creation and success for progress.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by tjprescott** [comment] 2017-06-02 21:21
What is the purpose of this issue?  It seems like a duplicate of #3510.

**Comment by tjprescott** [comment] 2017-06-02 21:24
Duplicate of #987.

**Closed by tjprescott** 2017-06-02 21:24 UTC
Labels: Infrastructure
