### ISSUE TITLE
"AZ REST" on AD B2C Identity Provider [Microsoft] via Graph-API seems not to work - Internal Error

### ISSUE THREAD

**Issue by fabienso** [Azure/azure-cli#17741] opened 2021-04-16 18:39 UTC
Hi everyone,

I am currently implementing a fully automated Azure AD B2C creation for multi-tenant solutions. The content of this automation is also the creation of the respective and individual identity providers. 

The creation of the Google-IDP via "azure rest" with a valid (jwt) token to the Graph-API permission "IdentityProvider.ReadWrite.All" works.

```
# json for goole idp
idp_template = json.loads('{ "type": "Google", "name": "Google", "clientId": "***************.apps.googleusercontent.com", "clientSecret": "*************" }')

# get identity-providers
execute(f'az login -t {tenant}.onmicrosoft.com --allow-no-subscriptions')
bearer = "<TOKEN>"
headers= "{'Authorization': 'Bearer "+bearer+"', 'Content-Type': 'application/json'}"
lala = execute(f'az rest --method POST --uri "https://graph.microsoft.com/v1.0/identityProviders" --headers "{headers}" --body "{idp_template}" --debug')
```

Challenge:
However, creating the Microsoft IDP via Azure Rest and the associated JSON does not work. Call-Code below:

```
# json for msa idp
idp_template_ms = json.loads('{ "type": "Microsoft", "name": "MSAAuth", "clientId": "APPLICATION ID FOR MSA", "clientSecret": "GENERATED SECRET STEP BEFORE" }')

# get identity-providers
execute(f'az login -t {tenant}.onmicrosoft.com --allow-no-subscriptions')
bearer = "<TOKEN>"
headers= "{'Authorization': 'Bearer "+bearer+"', 'Content-Type': 'application/json'}"
lala = execute(f'az rest --method POST --uri "https://graph.microsoft.com/v1.0/identityProviders" --headers "{headers}" --body "{idp_template_ms}" --debug')
```

The Azure CLI throws the following internal error in debug mode "--debug":

```
INFO: cli.azure.cli.core.util: Response content:
INFO: cli.azure.cli.core.util: {
  "error": {
    "code": "AADB2C90063",
    "message": "There is a problem with the service.",
    "innerError": {
      "correlationId": "bb04cc48-867a-4885-a514-5d724d996c0b",
      "date": "2021-04-16T18:14:39",
      "request-id": "18ead643-4ee7-4738-9320-de98477f9729",
      "client-request-id": "18ead643-4ee7-4738-9320-de98477f****"
    }
  }
}
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 720, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\util\custom.py", line 17, in rest_call
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\util.py", line 930, in send_raw_request
knack.util.CLIError: Internal Server Error({
  "error": {
    "code": "AADB2C90063",
    "message": "There is a problem with the service.",
    "innerError": {
      "correlationId": "bb04cc48-867a-4885-a514-5d724d996c0b",
      "date": "2021-04-16T18:14:39",
      "request-id": "18ead643-4ee7-4738-9320-de98477f9729",
      "client-request-id": "18ead643-4ee7-4738-9320-de98477f****"
    }
  }
})

ERROR: cli.azure.cli.core.azclierror: Internal Server Error({
  "error": {
    "code": "AADB2C90063",
    "message": "There is a problem with the service.",
    "innerError": {
      "correlationId": "bb04cc48-867a-4885-a514-5d724d996c0b",
      "date": "2021-04-16T18:14:39",
      "request-id": "18ead643-4ee7-4738-9320-de98477f9729",
      "client-request-id": "18ead643-4ee7-4738-9320-de98477f****"
    }
  }
})
ERROR: cli.azure.cli.core.azclierror: Internal Server Error({
  "error": {
    "code": "AADB2C90063",
    "message": "There is a problem with the service.",
    "innerError": {
      "correlationId": "bb04cc48-867a-4885-a514-5d724d996c0b",
      "date": "2021-04-16T18:14:39",
      "request-id": "18ead643-4ee7-4738-9320-de98477f9729",
      "client-request-id": "18ead643-4ee7-4738-9320-de98477f****"
    }
  }
})
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04EB04B0>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 1.614 seconds (init: 0.234, invoke: 1.381)
INFO: telemetry.save: Save telemetry record of length 3368 in cache
WARNING: telemetry.check: Negative: The C:\Users\USER\.azure\telemetry.txt was modified at 2021-04-16 20:07:15.144538, which in less than 600.000000 s
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    lala = execute(f'az rest --method POST --uri "https://graph.microsoft.com/v1.0/identityProviders" --headers "{headers}" --body "{idp_template_ms}" --debug')
  File "C:\dev\customer\b2c-setup\misc\helper.py", line 13, in execute
    result = subprocess.check_output(command, shell=True)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
```

Can any of you interpret the error?
Best Regards

**Comment by yonzhan** [comment] 2021-04-17 01:00
@jiasli for awareness

**Comment by jiasli** [comment] 2021-04-17 02:53
This `Internal Server Error` is caused by AAD service, instead of Azure CLI:

```
Internal Server Error({
  "error": {
    "code": "AADB2C90063",
    "message": "There is a problem with the service.",
    "innerError": {
      "correlationId": "bb04cc48-867a-4885-a514-5d724d996c0b",
      "date": "2021-04-16T18:14:39",
      "request-id": "18ead643-4ee7-4738-9320-de98477f9729",
      "client-request-id": "18ead643-4ee7-4738-9320-de98477f****"
    }
  }
})
```

You may [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) to AAD service team and our support engineers will help you with them.

As this issue falls out of the scope of Azure CLI, I will close it. Please feel free to raise a new issue if you have any concern with Azure CLI itself.

**Closed by jiasli** 2021-04-17 02:53 UTC
Labels: Graph
