### ISSUE TITLE
az login invalid_grant

### ISSUE THREAD

**Issue by wvxvw** [Azure/azure-cli#8239] opened 2019-01-14 09:16 UTC
**Describe the bug**
`az login` stopped working yesterday.  I believe it is a bug in `azure-cli` package.

**To Reproduce**
```
pip install -U azure-cli
az --version
azure-cli (2.0.46)

acr (2.1.5)
acs (2.3.4)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.4)
backup (1.2.1)
batch (3.4.0)
batchai (0.4.3)
billing (0.2.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.4)
core (2.0.46)
cosmosdb (0.2.1)
dla (0.2.3)
dls (0.1.3)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.2.4)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.30)
iot (0.3.2)
keyvault (2.2.3)
lab (0.1.1)
monitor (0.2.3)
network (2.2.5)
nspkg (3.0.3)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
reservations (0.4.0)
resource (2.1.4)
role (2.1.5)
search (0.1.1)
servicebus (0.2.3)
servicefabric (0.1.3)
sql (2.1.4)
storage (2.2.2)
telemetry (1.0.0)
vm (2.2.3)

Python location '<redacted>/python'
Extensions directory '<redacted>/cliextensions'

Python (Linux) 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831]

Legal docs and information: aka.ms/AzureCliLegal
```

Then:

```
az login -u <redacted> -p <redacted>
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password\r\nTrace ID: <redacted>\r\nCorrelation ID: <redacted>\r\nTimestamp: 2019-01-14 09:12:16Z","error_codes":[70002,50126],"timestamp":"2019-01-14 09:12:16Z","trace_id":"<redacted>","correlation_id":"<redacted>"}
```

I can log in with this user to Azure portal (web) w/o problems, I can create VMs and other appliances w/o problems.  More so, another person working on MS Windows reported that they have a slightly newer version of `azure-cli` not available to Linux, and that version can log in using the same credentials.

**Expected behavior**
`az login` works as advertised.

**Environment summary**
I you are going to preach installing your garbage through Docker images or system packages: remove it from pypi.org first.

**Comment by yugangw-msft** [comment] 2019-01-15 20:34
when you did login through browser, did you experience multi-factor authentications? If yes, then that is the reason using "az login -u <redacted> -p <redacted>" doesn't as your organization enforced the policy of MFA

**Comment by marstr** [comment] 2019-02-19 22:14
Howdy @wvxvw, have you confirmed whether or not this issue is the result of your company's policy?

**Comment by marstr** [comment] 2019-02-21 23:45
For folks stumbling on this issue because of the "invalid_grant", you may try `az account clear` as a work around. Work around originally mentioned here: https://github.com/Azure/azure-cli/issues/5724#issuecomment-466163284

**Comment by marstr** [comment] 2019-03-04 17:41
Closing, assuming the problem is about policy changes. If it continues to repro, we can open this bug back up or create a new one.

**Closed by marstr** 2019-03-04 17:41 UTC
Labels: Authentication, Question
