### ISSUE TITLE
az storage blob upload-batch: error: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by priya0917** [Azure/azure-cli#10489] opened 2019-09-10 08:30 UTC
On executing below script in azure Devops(VSTS),

resources:
- repo: self
trigger:
- next
queue:
  name: Hosted Ubuntu 1604

steps:
- task: NodeTool@0
  displayName: 'Install NodeJS'
  inputs:
    versionSpec: 10.14.2

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  displayName: 'Install yarn'
  inputs:
    versionSpec: 1.12.3

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn install'
  inputs:
    Arguments: install

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn build'
  inputs:
    Arguments: workspace @dxp/storybook build-storybook

- task: AzureCLI@1
  displayName: UploadToBlob
  inputs:
    azureSubscription: 'dmp-arm'
    scriptLocation: inlineScript
    inlineScript: 'az storage blob upload-batch --account-key $(DevBlobKey) --destination $(DevBlobUrl) --source packages/storybook/public'

I am getting the error stating "az storage blob upload-batch: error: too many values to unpack (expected 2)"

please help

**Comment by Juliehzl** [comment] 2019-09-10 14:12
dupe of  https://github.com/Azure/azure-cli/issues/9422. @priya0917 Is the same problem you encounted? Here for your inlineScript in Azure CLI task, it looks you don't specify your storage account name. Have you already set it in environment variable or somewhere else?

**Comment by Juliehzl** [comment] 2019-09-10 14:21
If it still don't work, can you show me the debug information with `--debug` appended in your inline script? Please note don't show your account key information.

**Comment by priya0917** [comment] 2019-09-11 07:48
On Debugging its giving :

The command failed with an unexpected error. Here is the traceback:

The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:ed20e415-201e-0006-5d75-686cba000000
Time:2019-09-11T07:46:25.7991174Z</Message></Error>
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 566, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 624, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 615, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 240, in new_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 183, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 594, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 303, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\__init__.py", line 470, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 263, in storage_blob_upload_batch
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\util.py", line 218, in wrapper
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 239, in _upload_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 352, in upload_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 345, in upload_block_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 463, in create_blob_from_path
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 582, in create_blob_from_stream
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 971, in _put_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 381, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 306, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 292, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\_error.py", line 115, in _http_error_handler
azure.common.AzureHttpError: The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:ed20e415-201e-0006-5d75-686cba000000

**Comment by Juliehzl** [comment] 2019-09-12 03:09
@priya0917 I try to reproduce your issue in Azure DevOps using the following task:
steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'Java Tooling Tests with TTL = 7 Days'
    scriptLocation: inlineScript
    inlineScript: 'az storage blob upload-batch -d test -s VSCodeJava/bin --account-name zuhtest

But it works for me. The CLI version I used in Azue Dev Ops is 2.0.71, what is your azure cli version used in Azure CLI task?

**Comment by Juliehzl** [comment] 2019-09-12 03:13
> On Debugging its giving :
> 
> The command failed with an unexpected error. Here is the traceback:
> 
> The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
> 
> `InvalidResourceName`The specifed resource name contains invalid characters.
> RequestId:ed20e415-201e-0006-5d75-686cba000000
> Time:2019-09-11T07:46:25.7991174Z
> Traceback (most recent call last):
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\knack\knack\cli.py", line 206, in invoke File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands__init__.py", line 566, in execute
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands__init__.py", line 624, in _run_jobs_serially File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands__init__.py", line 615, in _run_job File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage__init__.py", line 240, in new_handler
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage__init__.py", line 183, in handler File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands__init__.py", line 594, in _run_job File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands__init__.py", line 303, in **call**
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core__init__.py", line 470, in default_command_handler File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 263, in storage_blob_upload_batch
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\util.py", line 218, in wrapper File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 239, in _upload_blob
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 352, in upload_blob File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 345, in upload_block_blob
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 463, in create_blob_from_path File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 582, in create_blob_from_stream
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 971, in _put_blob File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 381, in _perform_request
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 306, in _perform_request File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 292, in _perform_request
> File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common_error.py", line 115, in _http_error_handler
> azure.common.AzureHttpError: The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
> 
> `InvalidResourceName`The specifed resource name contains invalid characters.
> RequestId:ed20e415-201e-0006-5d75-686cba000000

From the given trace information, it looks you use Azure CLI in your local machine. For this scenario, you are using storage SDK with v2018_03_28, which is not defined in azure cli profile. Can you also show me your local azure cli information and how do you install your azure cli?

**Comment by yonzhan** [comment] 2020-06-14 12:21
add to S173

**Comment by xiafu-msft** [comment] 2020-12-10 07:52
Hi @priya0917

Were you able to figure out this problem by chance?

**Comment by yonzhan** [comment] 2021-01-02 08:49
@priya0917 any update?

**Closed** 2021-03-05 15:41 UTC
Labels: OKR3.4 Candidate, Storage, Track2, customer-reported, feature-request, needs-author-feedback, no-recent-activity
