### ISSUE TITLE
REST version of list-skus returns different response than CLI version

### ISSUE THREAD

**Issue by vi-dot-cpp** [Azure/azure-cli#17239] opened 2021-03-09 05:26 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
- REST call: GET https://brazilus.management.azure.com/subscriptions/dad45786-32e5-4ef3-b90e-8e0838fbadb6/providers/Microsoft.Compute/skus?api-version=2019-04-01&$filter=location eq 'eastus2'
- REST response include resource named "Mdmsv2MedMem-Type1".
- CLI call:  msrest.http_logger : Request URL: 'https://brazilus.management.azure.com/subscriptions/dad45786-32e5-4ef3-b90e-8e0838fbadb6/providers/Microsoft.Compute/skus?api-version=2019-04-01'msrest.http_logger : Request method: 'GET'
- CLI response does not include resource named "Mdmsv2MedMem-Type1".

**To Reproduce**
- See above.

**Expected behavior**
Response from REST should match response from CLI.

**Environment summary**
'User-Agent': 'python/3.6.6 (Windows-10-10.0.19041-SP0) msrest/0.6.9 msrest_azure/0.6.3 azure-mgmt-compute/13.0.0 Azure-SDK-For-Python AZURECLI/2.9.1 (MSI)'

**Additional context**

**Comment by qwordy** [comment] 2021-03-09 05:29
@vi-dot-cpp, thanks for the feedback. I am investigating it.

**Comment by qwordy** [comment] 2021-03-09 05:33
Have talked with Vi in teams about details.

**Comment by yonzhan** [comment] 2021-06-17 14:36
Add @zhoxing-ms to take a look

**Comment by zhoxing-ms** [comment] 2021-06-18 03:06
@vi-dot-cpp Hi, may I ask is there still a problem? 
If so and it can be reproduced, please add parameter `--debug` after the original command and then execute it, then please send the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment] 2021-07-06 02:36
Since I haven't received reply for a long time, so I'll close this issue first. If you still have this problem, please email me the specific information and I will reopen this issue

**Closed by zhoxing-ms** 2021-07-06 02:36 UTC
Labels: Compute
