### ISSUE TITLE
Deployment of zip fails if run after creating functionapp.

### ISSUE THREAD

**Issue by mdsystems** [Azure/azure-cli#24644] opened 2022-11-14 13:38 UTC
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
HTTPSConnectionPool(host='dev-XXXXXXXXX.scm.azurewebsites.net', port=443): Read timed out. (read timeout=3)
Traceback (most recent call last):
python3.6/site-packages/urllib3/connectionpool.py, ln 426, in _make_request
    six.raise_from(e, None)
<string>, ln 3, in raise_from
python3.6/site-packages/urllib3/connectionpool.py, ln 421, in _make_request
    httplib_response = conn.getresponse()
lib/python3.6/http/client.py, ln 1354, in getresponse
    response.begin()
...
socket.timeout: The read operation timed out


python3.6/site-packages/requests/adapters.py, ln 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='dev-XXXXXXXXX.scm.azurewebsites.net', port=443): Read timed out. (read timeout=3)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip --src {} -g {} -n {}`

## Expected Behavior
The zip deploys successfully.

## Environment Summary
```
Linux-5.15.0-1022-azure-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.0 *

```
## Additional Context
If the same code is used to deploy to an existing function app, after a sufficient delay, it is successful. I think that this is timing related, so if it is possible for me to determine that a functionapp is ready to deploy to after creation, I would be happy to add code that manages this. However, I feel it would be better for the deployment code itself to wait a sufficient amount of time, rather than timing out.

**Comment by yonzhan** [comment] 2022-11-14 13:41
route to CXP team

**Comment by navba-MSFT** [comment] 2022-11-15 02:57
@mdsystems Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-11-15 08:49
@mdsystems Could you please update your Azure CLI version to the [most recent version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) and check if you still encounter the same issue ?

If you face the same issue again after upgrading the AzCLI try to run the same command with `--timeout` parameter and check if that helps.

> --timeout -t: Configurable timeout in seconds for checking the status of deployment.

**Comment by mdsystems** [comment] 2022-11-15 08:51
The same issue occurs with client 2.42.0. What timeout would you suggest?

**Comment by mdsystems** [comment] 2022-11-15 09:09
I am trying both locally and on an Azure VM and they behave identically. I'll try the longer timeout and report back.

**Comment by mdsystems** [comment] 2022-11-15 09:18
The longer timeout makes no difference. The error report (as per above) does mention timout=3. It appears as though the timeout parameter is being ignored in this instance, because the delay between the deployment starting and the failure is the same, irrespective of the timeout value specified.

**Comment by navba-MSFT** [comment] 2022-11-15 09:20
@mdsystems Are there any firewall / proxy within your network ?

**Comment by mdsystems** [comment] 2022-11-15 09:37
Locally, there is a firewall. The Azure VM has unrestricted access outbound. Both exhibit the same behaviour. Did you pick up on my comment that it is only the first deployment after creation of the functionapp that fails? Second and subsequent deployments do not fail.

Just to confirm what I am doing (values manually typed in place of shell script parameters for the purposes of illustration):

1. Check that the functionapp plan exists. If not create it. (In this case, the plan always exists and I am not creating it). I am using SKU B1 for this functionapp plan.
2. Check if the functionapp exists. If it doesn't create it using `az functionapp create -g XXXX -n MyFunctionApp -p XXXXFaPlan -s XXXXFncStore01 --os-type Linux --disable-app-insights --runtime Python --functions-version 4 --runtime-version 3.9`. Once created, I then set the configuration using `az functionapp config appsettings set -g XXXX -n MyFunctionApp --settings WEBSITE_RUN_FROM_PACKAGE=1`.
3. If the functionapp exists, or was successfully created and configured in step 2, deploy using `az functionapp deployment source config-zip --src MyFunctionApp.zip -g XXXX -n MyFunctionApp --timeout 360`

It is step 3 that fails. If I immediately try again on failure, it works. One thing I have noticed is that the Azure Web UI shows the following message (which I would not expect because WEBSITE_RUN_FROM_PACKAGE has already been set to 1 and is confirmed to be 1 in the web UI): 
![image](https://user-images.githubusercontent.com/4036468/201883883-79832481-12aa-4ee3-bfe9-77e85c2a4af1.png)

The function itself runs. The message above is possibly unrelated and I don't expect it to be resolved as part of this ticket. I am just mentioning it in case it is relevant.

**Comment by navba-MSFT** [comment] 2022-11-17 02:35
@mdsystems Thanks for getting back. We are looking into this in detail. In the meantime, Could you please run the same above command with `--timeout 360` and `--debug `parameter and share the detailed debug output over email navba [@] microsoft (dot) com ?

**Comment by navba-MSFT** [comment] 2022-11-28 04:55
@mdsystems Please let me know if you had any updates on this.

**Comment by kulkarnisonia16** [comment] 2022-11-28 06:12
@mdsystems - Thanks for creating this issue and your patience working with us. I am the PM who owns Azure Functions deployments and would like to know what is the time delay between the steps 2 and 3 that you mentioned? How are you determining that step 2 was successful. One of my guesses is that WEBSITE_RUN_FROM_PACKAGE=1 might not be propagated fully when you trigger the deployment.

cc - @patelchandni

**Comment by navba-MSFT** [comment] 2022-11-30 03:56
Thanks @kulkarnisonia16 .

@mdsystems I wanted to do quick follow-up to check if you had any updates on sharing the debug output. Also could you please answer the above query? Awaiting your reply.

**Comment by karthikeayan** [comment] 2022-12-02 07:04
I am seeing something similar when doing "azure webapp deploy". Posting here anyways as the issue seems similar,

```
az webapp deploy --resource-group myapp-rg --name webjobs-myapp --src-path myAppSampleTest.zip --type zip --clean false --restart true --timeout 30000 --debug
```

```
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): webjobs-myapp.scm.azurewebsites.net:443
DEBUG: urllib3.connectionpool: https://webjobs-myapp.scm.azurewebsites.net:443 "POST /api/publish?type=zip&restart=true&clean=false HTTP/1.1" 504 20
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 4655, in perform_onedeploy
    return _perform_onedeploy_internal(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 4821, in _perform_onedeploy_internal
    response = _make_onedeploy_request(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 4809, in _make_onedeploy_request
    raise CLIError("An error occured during deployment. Status Code: {}, Details: {}"
knack.util.CLIError: An error occured during deployment. Status Code: 504, Details: 504.0 GatewayTimeout

ERROR: cli.azure.cli.core.azclierror: An error occured during deployment. Status Code: 504, Details: 504.0 GatewayTimeout
ERROR: az_command_data_logger: An error occured during deployment. Status Code: 504, Details: 504.0 GatewayTimeout
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f8bb71d0040>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 288.099 seconds (init: 0.236, invoke: 287.864)
```

Tried with different timeout values and it doesn't make any difference.

Also, getting this issue only when the zip file contents changes.

**Comment by navba-MSFT** [comment] 2022-12-02 07:18
@kulkarnisonia16 We have another instance of the same issue. Do you have any pointers for this ?

**Comment by karthikeayan** [comment] 2022-12-02 07:33
@navba-MSFT There are no firewall/proxy. Yes, I can confirm it is on reliable network. I guess we can rule out the network because when there is no change in the zip content, the deployment always succeeds.

**Comment by mdsystems** [comment] 2022-12-02 08:41
@navba-MSFT. Sorry. I have been somewhat tied up on other things. I will take some time today to gather debug info and send it over to you.

@kulkarnisonia16 Thanks for your comment. I did force a wait after creation and of around 2 minutes before setting the configuration (and then waiting again) and deploying. Adding extra wait times did not resolve the issue. It always seems to be the first deployment after creation that fails, then it seems fine.

**Comment by mdsystems** [comment] 2022-12-02 11:46
A log has been sent to @navba-MSFT just now via email.

**Comment by mdsystems** [comment] 2022-12-02 13:30
> I would like to know what is the time delay between the steps 2 and 3 that you mentioned?

Not measured precisely, but somewhere around 30 seconds. I can time it exactly if you wish.

> How are you determining that step 2 was successful.

The result code from the az command. If it returns an exit code of 0, I treat it as successful. Non-zero is treated as a failure.

**Comment by navba-MSFT** [comment] 2022-12-06 04:49
@mdsystems Thanks for sharing the debug logs. I see this line in your issue description:

>If the same code is used to deploy to an existing function app, after a sufficient delay, it is successful. 

1. what do you mean by "sufficient delay" in the above statement.

2. Can you please tell me how quickly do you deploy after the creation?

I am guessing the issue is probably happening because request goes to SCM site before the SCM site is completely ready. For the reason, client times out because SCM site is taking long time to respond.

**Comment by navba-MSFT** [comment] 2022-12-07 05:37
Adding Service team to look into this.

 @Stefanus Hinardi, @Francisco-Gamino Could you please look into this once you get a chance ? Thanks in advance.

**Comment by navba-MSFT** [comment] 2022-12-20 05:25
@khkh-ms I have the debug logs of @mdsystems . I will share it with you offline over email.

**Comment by khkh-ms** [comment] 2022-12-20 16:41
We have identified the issue and we are in process of prioritizing the fix.

**Comment by mr-davidc** [comment] 2022-12-22 09:06
I seem to be running in to this issue as well. It only happens intermittently (not every pipeline) and if I immediately re-trigger the deployment job, it completes successfully.

I have a deployment pipeline which:
1. Run a Bicep template to create the function app (subsequent pipelines 
2. Run `az functionapp deployment source config-zip` to deploy the code

It doesnt seem to matter if Step 1 creates the function app OR Step 1 has already run previously in a previous pipeline and the function app already exists in Azure, the deployment job can still fail with this error:

```
$ az functionapp deployment source config-zip \ # collapsed multi-line command
WARNING: Getting scm site credentials for zip deployment
WARNING: Starting zip deployment. This operation can take a while to complete ...
WARNING: Deployment endpoint responded with status code 503
ERROR: An error occured during deployment. Status Code: 503, Details: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>
```

Glad to hear a fix may be on its way.

**Comment by khkh-ms** [comment] 2022-12-22 16:14
Thanks @mr-davidc for reporting it. We have identified the issue and will have the fix out in one of the first releases next year.

**Comment by mr-davidc** [comment] 2023-01-05 06:19
@khkh-ms

Just wanted to ask if there has been any progress on this issue?

I am still getting these sporadic 503 Service Unavailable errors most days.

**Comment by khkh-ms** [comment] 2023-01-05 19:14
We will fix it this week. It will be released in the next release. Thanks!

**Closed** 2024-01-09 17:52 UTC
Labels: Service Attention, question, Functions, customer-reported, needs-team-attention, Auto-Assign

**Comment by nathanblair** [comment] 2024-02-07 04:04
Is there a version number of the azure cli that this being completed has been tied to?

We're still seeing this when running `az webapp deploy` commands in Azure DevOps Microsoft Hosted Runners.

**Comment by david-may-shift** [comment] 2024-04-25 10:17
We are also running into this issue
deploying function app using `az functionapp deployment source config-zip ...` fails the first time but passes when run a second time

the failure message is

```
╷
│ Error: local-exec provisioner error
│ 
│   with null_resource.function_app_publish,
│   on main.tf line 165, in resource "null_resource" "function_app_publish":
│  165:   provisioner "local-exec" {
│ 
│ Error running command 'az functionapp deployment source config-zip
│ --resource-group sh-frc1-sdbx-dus-rg-ci-001 --name
│ sh-frc1-sdbx-dus-func-ci-001 --src ./azure-function.zip': exit status 1.
│ Output: WARNING: Setting SCM_DO_BUILD_DURING_DEPLOYMENT to false
│ WARNING: App settings have been redacted. Use `az
│ webapp/logicapp/functionapp config appsettings list` to view.
│ WARNING: Waiting SCM site to be updated with the latest app settings
│ WARNING: Getting scm site credentials for zip deployment
│ WARNING: Starting zip deployment. This operation can take a while to
│ complete ...
│ WARNING: Deployment endpoint responded with status code 202
│ WARNING: Configuring default logging for the app, if not already enabled
│ ERROR: Zip deployment failed. {'id': 'temp-2913e6c8', 'status': 3,
│ 'status_text': 'Deployment has been stopped due to SCM container restart.
│ The restart can happen due to a management operation on site. Do not
│ perform a management operation and a deployment operation in quick
│ succession. Adding a small delay can help avoid any conflicts.',
│ 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'az_cli_functions',
│ 'message': 'Deploying from pushed zip file', 'progress': '',
│ 'received_time': '2024-04-25T09:36:34.610801Z', 'start_time':
│ '2024-04-25T09:36:34.610801Z', 'end_time': '2024-04-25T09:36:[42](https://github.com/shift-technology/app-document-service/actions/runs/8830237703/job/24243026954?pr=717#step:7:43).5802923Z',
│ 'last_success_end_time': None, 'complete': True, 'active': False,
│ 'is_temp': True, 'is_readonly': False, 'url':
│ 'https://sh-frc1-sdbx-dus-func-ci-001.scm.azurewebsites.net/api/deployments/temp-2913e6c8',
│ 'log_url':
│ 'https://sh-frc1-sdbx-dus-func-ci-001.scm.azurewebsites.net/api/deployments/temp-2913e6c8/log',
│ 'site_name': 'sh-frc1-sdbx-dus-func-ci-001'}. Please run the command az
│ webapp log deployment show -n sh-frc1-sdbx-dus-func-ci-001 -g
│ sh-frc1-sdbx-dus-rg-ci-001
│ 
╵
```

**Comment by Saulopv** [comment] 2024-09-05 08:14
Still seeing this issue @khkh-ms

**Comment by jwphx** [comment] 2025-01-22 12:05
I've just experienced a similar issue - figured out it was down to the sku of my app service plan in my case. 4x func apps on a B1/B2 (for dev/test) didn't play nice with SCM build=true. CPU utilisation was @ 100% on the asp. 

Upped the sku to P0V3 - deployment worked as expected.
