### ISSUE TITLE
az upgrade failure

### ISSUE THREAD

**Issue by traynsford** [Azure/azure-cli#25911] opened 2023-03-22 14:51 UTC
## Describe the bug
az upgrade successfully downloads the MSI.  Request to elevate is accepted. Process then fails as per the Python stacktrace below.
Running the MSI directly is successful.

**Command Name**
`az upgrade`

**Errors:**
```
PS C:\Users\t.raynsford> az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.43.0. Latest version available is 2.46.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): Y
Updating Azure CLI with MSI from https://aka.ms/installazurecliwindows
Downloading MSI to C:\Users\<userFolder>\AppData\Local\Temp\tmplazybtzy\azure-cli-2.46.0.msi
Installing MSI
The command failed with an unexpected error. Here is the traceback:
[WinError 6] The handle is invalid
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 140, in upgrade_version
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 193, in _upgrade_on_windows
  File "subprocess.py", line 345, in call
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1463, in _execute_child
OSError: [WinError 6] The handle is invalid
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
Exception ignored in: <function Popen.__del__ at 0x03A282F8>
Traceback (most recent call last):
  File "subprocess.py", line 1075, in __del__
  File "subprocess.py", line 1477, in _internal_poll
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Handle.Close at 0x03A12BF8>
Traceback (most recent call last):
  File "subprocess.py", line 199, in Close
OSError: [WinError 6] The handle is invalid
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az upgrade`

## Expected Behavior
Upgrade should succeed.

## Environment Summary
```
azure-cli                         2.43.0 *

core                              2.43.0 *
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<userFolder>\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]
```

**Comment by yonzhan** [comment] 2023-03-22 23:18
@bebound for awareness

**Comment by bebound** [comment] 2023-03-23 01:41
Duplicate of https://github.com/Azure/azure-cli/issues/25412
This error is not caused by CLI.

**Closed** 2023-03-23 02:03 UTC
Labels: question, customer-reported, Upgrade, Auto-Assign, Azure CLI Team
