### ISSUE TITLE
Documentation not generated for az functionapp devops-pipeline

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#9343] opened 2019-05-08 21:06 UTC
**Describe the bug**
Documentation not generated for az functionapp devops-pipeline

**To Reproduce**
check docs page

**Comment by tjprescott** [comment] 2019-05-08 21:17
@yugangw-msft @dendeli-msft

**Comment by ahmedelnably** [comment] 2019-05-08 21:18
This is causing
https://github.com/MicrosoftDocs/azure-docs/issues/30865

**Comment by yugangw-msft** [comment] 2019-05-08 22:41
dupe of #9336

**Closed by yugangw-msft** 2019-05-08 22:41 UTC
Labels: Functions-cli
