### ISSUE TITLE
Azure CLI version 2.65.0 has deprecated modules

### ISSUE THREAD

**Issue by h44mkk** [Azure/azure-cli#30147] opened 2024-10-21 10:31 UTC
### Describe the bug

Hi! After upgrading homebrew packages on my macOS, the Azure-CLI version got updated as well. The new version shows always following errors:
`/usr/local/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,`

My work colleagues have the same issue  as well.
Can somebody fix that please?

### Related command

All commands are affected! Here is an example: `az staticwebapp hostname delete --name my-static-web-app --hostname example.com --resource-group MY-RESOURCE-GROUP`

### Errors

/usr/local/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,

### Issue script & Debug output

/usr/local/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,

### Expected behavior

Should work without logging erros!

### Environment Summary

azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/usr/local/Cellar/azure-cli/2.65.0_1/libexec/bin/python'
Extensions directory '/Users/h44mkk/.azure/cliextensions'

Python (Darwin) 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

Nothing to add.

**Comment by yonzhan** [comment] 2024-10-21 10:32
Thank you for opening this issue, we will look into it.

**Comment by h44mkk** [comment] 2024-10-21 10:37
Thank you for the suggestion. However, the proposed solution involves downgrading to version 2.64.0, which isn't ideal for our needs. We're looking for a proper fix rather than reverting to an older CLI version.

**Comment by jaromirmikulik** [comment] 2024-10-21 10:58
From my perspective, it could be caused by: https://github.com/Azure/azure-cli/issues/30148

**Comment by h44mkk** [comment] 2024-10-21 13:18
I tried the suggested solution to install the setup tools, but I still have the same issue:

![Image](https://github.com/user-attachments/assets/4dbe77ae-f634-479d-89af-ef3b08925d35)
Still getting here the same warnings:
![Image](https://github.com/user-attachments/assets/e87e72b2-f9ec-4e20-a508-b3a6063074be)
```
/usr/local/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
```

**Comment by jaromirmikulik** [comment] 2024-10-22 18:44
try to update azure-cli via homebrew:
brew update && brew upgrade

it should fix also this kind of issue.

**Comment by dvasdekis** [comment] 2024-10-23 01:07
> try to update azure-cli via homebrew: brew update && brew upgrade
> 
> it should fix also this kind of issue.

I still get this issue even though I have the latest Azure CLI version:
```
➜  az version
{
  "azure-cli": "2.65.0",
  "azure-cli-core": "2.65.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "resource-graph": "2.1.0"
  }
}
➜   az functionapp show --subscription "..." --resource-group "..." --name "my-funcapp-name"
/opt/az/lib/python3.11/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/opt/az/lib/python3.11/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Subscription '...' not recognized.
Not Found({"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}})
```

You can replace the ... with your real IDs for a real example but the above still illustrates the issue

**Comment by BenjaminEllisSo** [comment] 2024-11-04 12:38
Seeing the same here as well.

**Comment by bebound** [comment] 2024-11-08 03:19
Duplicate of https://github.com/Azure/azure-cli/issues/30048

**Closed by bebound** 2024-11-08 03:19 UTC
Labels: bug, Service Attention, customer-reported, staticwebapp, Auto-Assign, Similar-Issue
