### ISSUE TITLE
{postgres} HTML tag isn't allowed in example syntax 

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#27058] opened 2023-08-01 15:34 UTC
### Describe the bug

The source code for postgres server is using HTML tags for examples.

**There are eight instances:**
https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/postgres/flexible-server.yml
1. Line 986: HTML tag 'indexToRemove' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.
1. Line 993: HTML tag 'value' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/postgres/server.yml
1. Line 79:  HTML tag 'SingleIP' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.
1. Line 79:  HTML tag 'StartIP-DestinationIP' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.
1. Line 417: HTML tag 'SingleIP' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.
1. Line 417: HTML tag 'StartIP-DestinationIP' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.
1. Line 421: HTML tag 'indexToRemove' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.
1. Line 428: HTML tag 'value' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.

All eight instances render as `blank` in our autogenerated reference content. Modify these instances to use some other character like a backtick or escape character.

**Contributor's Guide guideance:**
https://review.learn.microsoft.com/en-us/help/platform/validation-ref/disallowed-html-tag?branch=main

### Related command

az postgres flexible-server update --remove
az postgres flexible-server update --set

az postgres server create --public --public-network-access

az postgres server update --public --public-network-access
az postgres server update --public --remove
az postgres server update --public --set

### Errors

MicrosoftDocs/azure-docs-cli warning:

![image](https://github.com/Azure/azure-cli/assets/58762114/6dc4ec3a-6e51-4c10-9066-2d8ba38648fe)

### Issue script & Debug output

See "Describe the bug" section above.

### Expected behavior

See "Describe the bug" section above.

### Environment Summary

See "Describe the bug" section above.

**Comment by yonzhan** [comment] 2023-08-01 15:34
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment] 2023-08-02 03:27
Since this is non-customer reported, Adding Service team to look into this.

**Comment by dbradish-microsoft** [comment] 2023-09-22 01:57
@yonzhan, do you know if this issue made it to anyone's backlog to get fixed?

**Comment by jiasli** [comment] 2023-11-03 08:43
For 

- az postgres flexible-server update --remove
- az postgres flexible-server update --set
- az postgres server update --public --remove
- az postgres server update --public --set

This issue is a duplicate of https://github.com/Azure/azure-cli/issues/27054

**Comment by dbradish-microsoft** [comment] 2023-11-08 16:33
@jiasli, There are [six GitHub issues for HTML tags](https://github.com/Azure/azure-cli/issues?q=is%3Aissue+is%3Aopen+html+tag+in%3Atitle+) -- one for each reference group.

**Comment by jiasli** [comment] 2023-11-09 05:43
@dbradish-microsoft, thanks for the kind reminder. I am using https://github.com/Azure/azure-cli/issues/27054 as the main tracking issue.

**Comment by nachoalonsoportillo** [comment] 2024-06-10 15:07
@yonzhan it seems this one was addressed with #27752. Please, proceed with closing it. Thanks!

**Comment by nachoalonsoportillo** [comment] 2024-07-04 22:27
@yonzhan Please, close this one. Thanks!

**Closed** 2024-07-04 23:44 UTC
Labels: bug, Service Attention, PostgreSQL, Auto-Assign
