### ISSUE TITLE
ErrorCode: InvalidUri <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.

### ISSUE THREAD

**Issue by sidhag** [Azure/azure-cli#9265] opened 2019-05-01 06:20 UTC
Following the article https://docs.microsoft.com/en-us/azure/functions/tutorial-static-website-serverless-api-with-database?tutorial-step=1

Getting error : 
C:\Users\sidhag\functions-first-serverless-web-application\www\dist>az storage blob upload-batch -s C:\Users\sidhag\functions-first-serverless-web-application\www\dist -d \$web --account-name 1stserverless
The command failed with an unexpected error. Here is the traceback:

The requested URI does not represent any resource on the server. ErrorCode: InvalidUri
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.
RequestId:86648354-b01e-0096-4fe2-ffda55000000
Time:2019-05-01T05:56:43.3624572Z</Message><UriPath>https://1stserverless.blob.core.windows.net//$web/.nojekyll</UriPath></Error>
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 351, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 409, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 400, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 237, in new_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 180, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 263, in storage_blob_upload_batch
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-storage\azure\cli\command_modules\storage\util.py", line 218, in wrapper
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 239, in _upload_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 352, in upload_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 345, in upload_block_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 463, in create_blob_from_path
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 582, in create_blob_from_stream
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 971, in _put_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 381, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 306, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 292, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\_error.py", line 115, in _http_error_handler
azure.common.AzureHttpError: The requested URI does not represent any resource on the server. ErrorCode: InvalidUri
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.
RequestId:86648354-b01e-0096-4fe2-ffda55000000
Time:2019-05-01T05:56:43.3624572Z</Message><UriPath>https://1stserverless.blob.core.windows.net//$web/.nojekyll</UriPath></Error>

To open an issue, please visit: https://aka.ms/azcli/issues

PLease help..

**Comment by adewaleo** [comment] 2019-05-01 17:57
Please provide more information. What command exactly failed? It looks like **az storage blob upload-batch **, but it isn't too clear. 

Try to follow this format:

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by adewaleo** [comment] 2019-05-01 18:00
Two conclusions:

1. The error / stack trace shows that a uri passed is invalid. Are you passing the correct value to `-d` $web should refer to a blob container I believe. Also this is bash syntax not cmd syntax.
2. We shouldn't be throwing a stack trace. This should be fixed @limingu.

**Comment by limingu** [comment] 2019-05-17 17:14
@sidhag the issue is because of $web. '$web' should be replaced with the Storage container name. For example, you can create a container name as 'web' with cmd like:  az storage container create -n web. Then you can upload as command: az storage blob upload-batch -s C:\Users\sidhag\functions-first-serverless-web-application\www\dist -d web --account-name 1stserverless

**Closed by limingu** 2019-05-17 17:14 UTC
Labels: Question, Storage-cli, bug
