### ISSUE TITLE
az interactive stop working after last upgrade

### ISSUE THREAD

**Issue by urlichLivonian** [Azure/azure-cli#18202] opened 2021-05-24 21:17 UTC
##  The bug description

**Command Name**
`az interactive`

**Errors:**
```
Error loading command module 'iot': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'network': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'resource': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'sql': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'vm': progress_patch() got an unexpected keyword argument 'det'
'vm' is misspelled or not recognized by the system.
```

## To Reproduce:
Steps to reproduce the behavior.

- `az interactive`

## Expected Behavior
- just works

## Environment Summary
```
macOS-11.3-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment] 2021-05-25 01:03
interactive

**Comment by urlichLivonian** [comment] 2021-05-25 08:04
By the way, I've noticed that the same bug occurs in shell.azure.com (bash)

##  Environment Summary
Linux-5.4.0-1047-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

Python location '/opt/az/bin/python3'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

azure-cli 2.23.0
core 2.23.0
telemetry 1.0.6

Extensions:
interactive 0.4.4
ai-examples 0.2.5
ssh 0.1.5

## Errors
```
Error loading command module 'iot': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'network': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'resource': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'sql': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'vm': progress_patch() got an unexpected keyword argument 'det
```

**Comment by ozbillwang** [comment] 2021-06-05 13:31
yes, after upgrade to latest

```
az>> az version
{
  "azure-cli": "2.24.2",
  "azure-cli-core": "2.24.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.18.0",
    "blueprint": "0.3.0",
    "interactive": "0.4.4"
  }
}
```

**Comment by jiasli** [comment] 2021-06-07 02:03
Duplicate of #17740

**Closed by jiasli** 2021-06-07 02:03 UTC
Labels: Interactive, feature-request
