### ISSUE TITLE
az login fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by TorbenRahbekKoch** [Azure/azure-cli#12957] opened 2020-04-10 14:36 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\_profile.py", line 1200, in _get_authorization_code_worker
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socketserver.py", line 453, in __init__
    self.server_bind()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 10: invalid start byte

Login failed
```
My computer has in no way an exotic or esoteric name. It has the humble name "thebeast" ;)

## To Reproduce:

- Ïnstall latest (2.3.1) Azure CLI using MSI (or PowerShell, this fails, too)
- Execute the command: `az login`

## Expected Behavior
A brower opens for enabling me to login.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI
azure-cli 2.3.1

```
## Additional Context
Please note that both
````
az login -u _username_
az login -u _username_ -p _password_
````
successfully logs in.

**Comment by yonzhan** [comment] 2020-04-10 23:48
add to S169

**Comment by jiasli** [comment] 2020-04-11 15:04
Similar to https://github.com/Azure/azure-cli/issues/7989. 

To be honest, I can't reproduce it. I added a line `print(name)` at `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py:673` and run `az login`, it shows `127.0.0.1`, which is returned by `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socketserver.py:468` 

```py
self.server_address = self.socket.getsockname()
```

Perhaps you are under some VPN? Could you please run this line in cmd and share the result?

```
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import socket; print(socket.getfqdn()); print(socket.gethostbyaddr(socket.gethostname()))"
```

**Comment by TorbenRahbekKoch** [comment] 2020-04-11 15:36
No VPN or anything else strange about my internet connection. 

The result of running that command shows the computer name with an ipv6 address:

````
E:\projects> & 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -c "import socket; print(socket.getfqdn()); print(socket.gethostbyaddr(socket.gethostname()))"
thebeast
('thebeast', [], ['fe80::7426:3af5:f6b1:1b9e'])
````

I would probably have expected it to return the ipv4 address instead. I am behind a NAT'ed router. The internet connection does not support ipv6.

**Comment by TorbenRahbekKoch** [comment] 2020-04-11 15:47
If it is the host name of the local computer it complains I find it very curious that it complains about 0xf8 in position 10. 'thebeast' is, after all, only 8 characters long.

**Comment by jiasli** [comment] 2020-04-11 15:48
This is weird. This time `gethostbyaddr` is successful. IPv6 is not the problem. I also get similar result:

```pwsh
> & 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -c "import socket; print(socket.getfqdn()); print(socket.gethostbyaddr(socket.gethostname()))"
my-surface.DHCP HOST
('my-surface.DHCP HOST', [], ['fe80::206c:9c47:346:e55f'])
```

Could you open `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py` with admin permission and add `print(name)` to L673:

```py
672:    try:
673:        print(name)
673:        hostname, aliases, ipaddrs = gethostbyaddr(name)
```

Then run `az login` again. If the terminal can't display the character, run `az login > out.txt` to redirect the `stdout` and open with a text editor like VS Code.

**Comment by TorbenRahbekKoch** [comment] 2020-04-11 15:54
That results in ``127.0.0.1`` just as it did for you.

But, if I run

````
'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -c "import socket; print(socket.getfqdn('127.0.0.1'))"
````

I get:

````
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 674, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 10: invalid start byte
````
It is really not happy about that localhost.

**Comment by TorbenRahbekKoch** [comment] 2020-04-11 15:59
And then again, if I run:

``'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -c "import socket; print(socket.gethostname())"``

it returns ``thebeast`` - not ``127.0.0.1``:

**Comment by jiasli** [comment] 2020-04-11 16:00
I have docker installed, so this command gives me `kubernetes.docker.internal`:

```
> & 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -c "import socket; print(socket.getfqdn('127.0.0.1'))"
127.0.0.1
kubernetes.docker.internal
```

Maybe you can check the contents of `C:\Windows\System32\drivers\etc\hosts`? Mine looks like

```
192.168.1.101 host.docker.internal
192.168.1.101 gateway.docker.internal
# Added by Docker Desktop
192.168.1.102 host.docker.internal
192.168.1.102 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by TorbenRahbekKoch** [comment] 2020-04-11 16:05
Oh my! You are a genius.

I did have some 127.0.01 domain names in there. One of them with an international character... Doh!

After removing that, az login works flawlessly!

**Comment by TorbenRahbekKoch** [comment] 2020-04-11 16:11
And a followup. If I make sure that the ``hosts`` file is saved as UTF8 _without_ BOM_, I can leave in the domain name with an international character and it still works.

So: It seems it was a mistake on my side. I really appreciate the help. Thanks!

**Comment by jiasli** [comment] 2020-04-11 16:21
Glad to know it works! Yes, saving the `hosts` file as **UTF-8 without BOM** does solve it! I also verified it. 

In my test, I added `127.0.0.1 测试` to my `hosts`. The error only happens if I have system locale other than English:

![image](https://user-images.githubusercontent.com/4003950/79048919-edfa7c80-7c52-11ea-8523-2e0a5a1887df.png)

```
> & 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -c "import socket; print(socket.getfqdn('127.0.0.1'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte
```

Checking the "Beta: Use Unicode UTF-8 for worldwide language support" also solves this issue:

```
> & 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -c "import socket; print(socket.getfqdn('127.0.0.1'))"
测试
```

There is definitely some problem with Python and Windows: https://bugs.python.org/issue26227

**Comment by TorbenRahbekKoch** [comment] 2020-04-11 16:32
Ouch! Even in newer versions it has problems. Bummer!

At least: Having this ticket now may help some other poor UTF8-dependent souls like me, when googling it ;)

Suggestion, though: Would it be possible to catch this exception and maybe print a helpful error message instead. E.g. something that suggests checking the hosts file :D

**Comment by jiasli** [comment] 2020-04-11 16:37
The reason I can think of is Windows relies on BOM to decide if the file is UTF-8. 

- If `hosts` has no BOM, Windows thinks the file is ANSI (but actually not), so `测试` is not converted and Python can decode it with UTF-8
- If `hosts` has BOM, Windows converts `测试` to ANSI first, which can't be decoded by Python's UTC-8 codec

Sure! Give me some time to draft a PR. We can definitely improve the error!

**Comment by TorbenRahbekKoch** [comment] 2020-04-11 16:40
Ah - that makes perfectly sense, actually.

So saving it without BOM makes Windows puke and with BOM Python pukes. Better not put anything needing UTF8 inside it, it seems ;)

Seriously! Thanks for the help!

**Comment by jiasli** [comment] 2020-04-11 17:10
You are very welcome. The Python issue was intended to be fixed in https://github.com/python/cpython/commit/7240030c52b5b738830c538bf849da8241c569d0, but was broken again by changing `PyUnicode_DecodeFSDefault` to use UTF-8 by [PEP 529](https://www.python.org/dev/peps/pep-0529/). 

- If `hosts` doesn't contain `127.0.0.1` items, Python

**Comment by jiasli** [comment] 2020-04-11 17:41
You are very welcome. 

For those looking for a quick solution, there are three:

1. Make sure there is no international character in **computer name** or `C:\Windows\System32\drivers\etc\hosts` file
2. Enable UTF-8 support on Windows 
    ![](https://user-images.githubusercontent.com/4003950/75752152-13968b00-5d63-11ea-82a9-5b8ac4a474eb.png)
3. (This one is [a hack](https://github.com/Azure/azure-cli/issues/12957#issuecomment-612460282)) If international characters appear in `hosts`, save the file as **UTF-8 without BOM**


### The Explanation (TL;DR)

If `hosts` doesn't contain `127.0.0.1` items, `gethostbyaddr` returns the computer name:
 
```pwsh
> python -c "import socket; print(socket.gethostbyaddr('127.0.0.1'))"
('my-surface-book', [], ['127.0.0.1'])
```

If `hosts` contains `127.0.0.1` items, like

```
127.0.0.1 web1.com
127.0.0.1 web2.net
```

`gethostbyaddr` returns those items:

```pwsh
> python -c "import socket; print(socket.gethostbyaddr('127.0.0.1'))"
('web1.com', ['web2.net'], ['127.0.0.1'])
```

In either case, international characters cause a decoding problem in Python. This issue was intended to be fixed by https://github.com/python/cpython/commit/7240030c52b5b738830c538bf849da8241c569d0 for [#26227](https://bugs.python.org/issue26227), but was broken again by changing `PyUnicode_DecodeFSDefault` to use UTF-8 by default in [PEP 529](https://www.python.org/dev/peps/pep-0529/).

Without a fix from Python, we need to workaround it.

**Closed** 2020-04-20 05:26 UTC
Labels: Authentication
