### ISSUE TITLE
az vm extension show: misdocumented

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#750] opened 2016-08-25 18:29 UTC
Apparently `--vm-name` and `-g` are required too, but ze docs didn't tell me. :(

```
➜  ~ az vm extension show -h

Command
    az vm extension show

Arguments
    --name -n [Required]: The name of the virtual machine extension.
    --api-version       : Client Api Version.  Default: 2016-03-30.
    --expand            : The expand expression to apply on the operation.
    --ids               : ID of resource.
    --resource-group -g : Name of resource group.
    --vm-name           : The name of the virtual machine.

Global Arguments
    --debug             : Increase logging verbosity to show all debug logs.
    --help -h           : Show this help message and exit.
    --output -o         : Output format.  Allowed values: json, tsv, list, table, jsonc.  Default:
                          json.
    --query             : JMESPath query string. See http://jmespath.org/ for more information and
                          examples.
    --verbose           : Increase logging verbosity. Use --debug for full debug logs.

➜  ~ az vm extension show -n CustomScript
usage: az vm extension show [-h] [--output {json,tsv,list,table,jsonc}]
                            [--verbose] [--debug] [--query JMESPATH]
                            [--api-version API_VERSION]
                            [--ids RESOURCE_ID [RESOURCE_ID ...]]
                            [--resource-group RESOURCE_GROUP_NAME]
                            [--vm-name NAME] --name NAME [--expand EXPAND]
az vm extension show: error: (--resource-group --vm-name | --ids) are required
```

**Comment by yugangw-msft** [comment] 2016-08-26 01:58
dupe of #656

**Closed by yugangw-msft** 2016-08-26 01:58 UTC
