### ISSUE TITLE
Updating azure role definition gives error

### ISSUE THREAD

**Issue by oxbo-andre** [Azure/azure-cli#24499] opened 2022-10-31 06:35 UTC
## Describe the bug

**Command Name**
`az role definition update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'roleName'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 71, in update_role_definition
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 101, in _create_update_role_definition
KeyError: 'roleName'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition update --role-definition {}`

## Environment Summary
```
Windows-10-10.0.25231-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
account 0.2.3
managementpartner 0.1.3

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by aavdberg** [comment] 2022-10-31 06:36
Item here

**Comment by RakeshMohanMSFT** [comment] 2022-11-01 05:00
@oxbo-andre We are unable to reproduce this in similar environment.

![image](https://user-images.githubusercontent.com/49954584/199161967-377580b2-1157-4373-9bb5-92a1d3d4fe3b.png)

**Comment by aavdberg** [comment] 2022-11-01 07:25
I think that it had to do with token that was expired because when i did az logout and then az login it did not happen anymore.

**Comment by RakeshMohanMSFT** [comment] 2022-11-01 07:29
@aavdberg Thank you. @oxbo-andre can you try it please?

**Comment by aavdberg** [comment] 2022-11-01 07:30
@oxbo-andre is my account at the customer

**Comment by RakeshMohanMSFT** [comment] 2022-11-01 07:32
@oxbo-andre @aavdberg Thank you. I will close the issue.

**Closed by RakeshMohanMSFT** 2022-11-01 07:32 UTC
Labels: question, RBAC, customer-reported, needs-author-feedback, Auto-Assign, Azure CLI Team

**Comment by jiasli** [comment] 2024-10-10 02:41
Duplicate of https://github.com/Azure/azure-cli/issues/12027
