### ISSUE TITLE
Az cli 2.24.0 break 'what-if' command

### ISSUE THREAD

**Issue by Jian-Huang-Dev** [Azure/azure-cli#18248] opened 2021-05-26 18:03 UTC
Once az cli is updated to 2.24.0, then running 'az deployment sub what-if ..' command will get an error
'str' object has no attribute 'value'

Bug:

Image version
All microsoft hosted agents with az cli 2.24.0 installed

Expected behavior
If you choose a earlier version of az cli, for example 2.23.0, then the 'what-if' command runs successfully and gives you the expected results.

Actual behavior
Got an error when running 'what-if' command - ERROR:'str' object has no attribute 'value'

note: running the command with 'create' is working fine, no issue. Such as 'az deployment sub create -f .. -p .. -l ..'

Repro steps
Run az cli command such as 'az deployment sub what-if -f .. -p .. -l ..' with version 2.24.0 (latest as of writing)
Then you will get an error: 'str' object has no attribute 'value'

**Comment by yonzhan** [comment] 2021-05-27 01:50
route to service team

**Comment by dallmair** [comment] 2021-05-28 11:18
This seems to be a duplicate of #18235.

**Comment by mariuszdotnet** [comment] 2021-05-28 15:45
This is causing PROD issues for customers who are doing what-if as part of their CI/CD with ADO hosted agents..

**Comment by dallmair** [comment] 2021-06-01 08:31
This is fixed in release 2.24.1, which was published a few hours ago:

https://github.com/Azure/azure-cli/pull/18307

**Closed** 2021-06-01 14:27 UTC
Labels: ARM, Service Attention
