### ISSUE TITLE
Failed to run `az aks browse` command

### ISSUE THREAD

**Issue by tkak** [Azure/azure-cli#6893] opened 2018-07-26 02:54 UTC
**Describe the bug**
`az aks browse` command was failed with the following error messages,

```
$ az aks browse --resource-group loadTestPOC --name loadTestPOC
Merged "loadTestPOC" as current context in /var/folders/j0/t3gr2t0n2vn9x6y9ygsk6yww438dz0/T/tmpaq66zxl2
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 93, in wait_then_open
    urlopen(url, context=_ssl_context())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 278, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <?xml version="1.0" encoding="utf-8" ?>


Forwarding from [::1]:8001 -> 9090
```

**To Reproduce**

1. Create azure kubernetes cluster (version 1.10.5)
2. Run `az aks browse` command

**Expected behavior**
The command will be finished successfully.

**Environment summary**
I've installed azure-cli with homebrew. And, I use zsh.

```
$ az --version
azure-cli (2.0.42)

acr (2.1.0)
acs (2.2.0)
advisor (0.6.0)
ams (0.2.0)
appservice (0.2.0)
backup (1.2.0)
batch (3.3.0)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.0)
core (2.0.42)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.0)
extension (0.2.0)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.26)
iot (0.2.0)
keyvault (2.2.0)
lab (0.1.0)
maps (0.3.0)
monitor (0.2.0)
network (2.2.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.0)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.0)
resource (2.1.0)
role (2.1.0)
servicebus (0.2.0)
servicefabric (0.1.0)
sql (2.1.0)
storage (2.1.0)
vm (2.1.0)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/takaaki.furukawa/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Jul 23 2018, 20:24:19)
[Clang 9.0.0 (clang-900.0.39.2)]

Legal docs and information: aka.ms/AzureCliLegal

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1314
```

**Comment by yugangw-msft** [comment] 2018-07-26 16:18
Dupe of #6811

**Closed by yugangw-msft** 2018-07-26 16:18 UTC

**Comment by yugangw-msft** [comment] 2018-07-26 16:19
//CC: @mboersma, another one on `az aks browse`
