### ISSUE TITLE
az monitor autoscale rule list fails when optional param --profile is not specified

### ISSUE THREAD

**Issue by leparduk** [Azure/azure-cli#14611] opened 2020-07-31 13:35 UTC
## Describe the bug

**Command Name**
`az monitor autoscale rule list`

**Errors:**
```
Traceback (most recent call last):
Temp\pip-install-_1mlo87m\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 625, in execute
azure\cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 680, in _run_job
azure\cli\command_modules\monitor\_exception_handler.py, ln 42, in monitor_exception_handler
Local\Temp\pip-install-_1mlo87m\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 659, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 531, in default_command_handler
cli\command_modules\monitor\operations\autoscale_settings.py, ln 341, in autoscale_rule_list
StopIteration
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor autoscale rule list --resource-group {} --autoscale-name {}`

## Expected Behavior

A list of items?

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1 *

Extensions:
application-insights 0.1.8
azure-devops 0.17.0

```

**Comment by leparduk** [comment] 2020-07-31 13:37
There is one profile. If I specify the profile the command succeeds. If I do not the is an error. I would expect the one item to be returned.

**Comment by yonzhan** [comment] 2020-07-31 15:19
add to S174

**Comment by MyronFanQiu** [comment] 2020-08-03 02:02
@leparduk `--profile-name` is optional since most of them named `default`. If your profile's name is not `default`, you have to specify this value.

**Comment by MyronFanQiu** [comment] 2020-08-11 02:30
Close this issue since it's by design.

**Closed by MyronFanQiu** 2020-08-11 02:30 UTC
Labels: Customer Usage, Feature Request, Monitor, OKR3.2 Candidate
