### ISSUE TITLE
Unable to update Capacity units on the Application Gateway when using WAF Policy

### ISSUE THREAD

**Issue by timvanderweijde** [Azure/azure-cli#15520] opened 2020-10-14 13:15 UTC
## Describe the bug
After creating a WAF Policy and creating an Application Gateway, it's not possible to update the Capacity units anymore. Trying to update the Capacity in Azure Portal gives an error.

**Command Name**
`az network application-gateway create`

**Errors:**
Failed to save configuration changes to application gateway 'application-gateway-some-name'. Error: WebApplicationFirewallConfiguration cannot be changed when there is a WAF Policy <resource here>'>application-gateway-waf-policy associated with it.

## To Reproduce:
- `az network application-gateway waf-policy create `
- `az network application-gateway waf-policy policy-setting update `
- `az network application-gateway create -g {} -l {} -n {} --vnet-name {} --subnet {} --public-ip-address {} --frontend-port {} --sku {} --min-capacity {} --max-capacity {} --http2 {} --zones {} {} {} --waf-policy {}`
- Now, try to change the capacity in Azure Portal.

## Expected Behavior
The capacity updated as normal without a WAF policy.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1 *

```

**Comment by yonzhan** [comment] 2020-10-14 14:43
add to S178

**Comment by haroldrandom** [comment] 2020-10-27 03:34
@timvanderweijde Is the 3rd step you describe to reproduce returning the expected response? Is so, I might redirect this issue to service team

**Comment by timvanderweijde** [comment] 2020-10-29 19:12
The first az command are succesfull. 

When I try to change the capacity from within the Azure Portal (web UI), I got the error.

**Comment by haroldrandom** [comment] 2020-10-30 03:13
> The first az command are succesfull.
> 
> When I try to change the capacity from within the Azure Portal (web UI), I got the error.

what properties are you going to update?

**Comment by jeffwmiles** [comment] 2020-12-09 02:55
Has there been any update to this? We are stuck in a position of requiring to update capacity but cannot, as the WAF policy cannot be removed.

**Comment by appgwsuppgithub** [comment] 2020-12-09 06:05
@Drew Taylor<mailto:ant@microsoft.com>, can you take a look at this?

Thanks,
Suraj

**Comment by winthrop28** [comment] 2021-04-15 00:19
@yonzhan has there been any progress on this?

**Comment by yonzhan** [comment] 2021-04-15 00:34
network service team should look into this issue

**Comment by msyyc** [comment] 2021-04-15 03:08
@timvanderweijde @winthrop28 We could not reproduce the error without specific parameters. We need more detailed parameters instead of ‘{}’.
![image](https://user-images.githubusercontent.com/70930885/114808433-cd6f8000-9dda-11eb-993f-6331117fe3ac.png)

**Comment by winthrop28** [comment] 2021-04-20 21:09
I don't have any more specific params, we need to rely on the customer for that

**Comment by yonzhan** [comment] 2021-04-20 22:38
@winthrop28 could you help engage the customer to get detailed params for us to troubleshoot this issue?

**Comment by jkpl** [comment] 2021-06-07 11:04
I managed to reproduce this from the Azure portal. Attempting to update the fixed capacity produces this `ApplicationGatewayWafConfigurationCannotBeChangedWithWafPolicy` error:

> WebApplicationFirewallConfiguration cannot be changed when there is a WAF Policy /subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/[REDACTED] associated with it.

**Comment by aholler2** [comment] 2022-06-28 21:53
We are getting this in North Central US

**Comment by ygnr** [comment] 2022-07-05 07:00
We are also seeing this when we try to update backend pool ip address

**Comment by SatishNaidi** [comment] 2022-07-05 10:26
We too started facing the similar issue while AGIC is trying to update the backend pools on Application Gateway and this was working earlier.

**Comment by ygnr** [comment] 2022-07-06 01:02
We found a fix, our issue was we had both WAF config and WAF policy configured on the app gateway. We had WAF Config before and we moved to policy long back but somehow WAF config was still there even though it won't show on UI. I guess there was a recent change on the app gateway to add more validation if there are both configured it won't allow changes.

We were able to remove the config with the following commands and after that, it started working.

`$SubscriptionId = "<sub ID>"
$ResourceGroupName = "<ResourceGroup>"
$GatewayName = "<AppGWName>"
Connect-AzAccount -Subscription $SubscriptionId
$AppGw = Get-AzApplicationGateway -ResourceGroupName $ResourceGroupName -Name $GatewayName
$AppGw.webApplicationFirewallConfiguration = $null
Set-AzApplicationGateway -ApplicationGateway $AppGw`

**Comment by SatishNaidi** [comment] 2022-07-06 01:59
> We found a fix, our issue was we had both WAF config and WAF policy configured on the app gateway. We had WAF Config before and we moved to policy long back but somehow WAF config was still there even though it won't show on UI. I guess there was a recent change on the app gateway to add more validation if there are both configured it won't allow changes.
> 
> We were able to remove the config with the following commands and after that, it started working.
> 
> > $SubscriptionId = sub ID
> > $ResourceGroupName = ResourceGroup
> > $GatewayName = AppGWName
> > Connect-AzAccount -Subscription $SubscriptionId
> > $AppGw = Get-AzApplicationGateway -ResourceGroupName $ResourceGroupName -Name $GatewayName
> > $AppGw.webApplicationFirewallConfiguration = $null
> > Set-AzApplicationGateway -ApplicationGateway $AppGw

Thank you @ygnr , we are able to resolve the issue following similar step with the help of Azure support.

**Comment by ygnr** [comment] 2022-07-06 06:23
> > We found a fix, our issue was we had both WAF config and WAF policy configured on the app gateway. We had WAF Config before and we moved to policy long back but somehow WAF config was still there even though it won't show on UI. I guess there was a recent change on the app gateway to add more validation if there are both configured it won't allow changes.
> > We were able to remove the config with the following commands and after that, it started working.
> > > $SubscriptionId = sub ID
> > > $ResourceGroupName = ResourceGroup
> > > $GatewayName = AppGWName
> > > Connect-AzAccount -Subscription $SubscriptionId
> > > $AppGw = Get-AzApplicationGateway -ResourceGroupName $ResourceGroupName -Name $GatewayName
> > > $AppGw.webApplicationFirewallConfiguration = $null
> > > Set-AzApplicationGateway -ApplicationGateway $AppGw
> 
> Thank you @ygnr , we are able to resolve the issue following similar step with the help of Azure support. We faced this issue in EASTUS2 region, is it same case for you guys?

No it was in Australia East

**Comment by marlowp** [comment] 2022-07-18 12:25
We suddenly started experiencing this issue today with an AGW instance that has been in place for ~2 years in the UK West region. As mentioned previously it appears to be because the default WAF config is still enabled on the AGW even though a separate WAF policy is being used.

For those using the Azure CLI this can be fixed by running:

`az network application-gateway waf-config set --resource-group <resource-group> --gateway-name <gateway-name> --enabled false`

**Comment by Piet-van-Bruggen** [comment] 2022-07-19 09:31
Same as @marlowp here and used his CLI command to fix it; however got an error on the rule-set version not allowed to be Null, so had to supply the parameters: --enabled false --rule-set-type OWASP --rule-set-version 3.2 

But worked like a charm; so that took away a bit of the irritation that this suddenly popped up and no way to fix it from the portal itself..

Our AppGw is running in West-Europe btw..

**Comment by roviracarlos** [comment] 2022-07-21 20:43
Same as @marlowp and @Piet-van-Bruggen, and the workaround fix the issue, thanks guys!. I try to reproduce the error in others older GW but is not the same because add others properties when link the Policys, like forceFirewallPolicyAssociation and the error not appears. I think is some specific check introduced in the latest days that creates a conflict if both options are already enabled.

**Comment by gunjanj** [comment] 2022-07-25 19:53
Thanks for raising this issue. We are aware of the API issue that was recently introduced. We are working on rolling out the fix. The issue can occur when you use API to update the config to policy.  If you're using [migration script](https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/migrate-policy) or Firewall Manager integration, you will also encounter this issue. 

Meanwhile, the workaround is to nullify the WAF config object post upgrade.  Thanks for your patience.

$SubscriptionId = '<sub id>'
$ResourceGroupName = '<sub id>'
$GatewayName = '<sub id>'
Connect-AzAccount -Subscription $SubscriptionId
$AppGw = Get-AzApplicationGateway -ResourceGroupName $ResourceGroupName -Name $GatewayName
$AppGw.webApplicationFirewallConfiguration = $null
Set-AzApplicationGateway -ApplicationGateway $AppGw


The s

**Comment by NikStayCMNH** [comment] 2022-08-03 19:19
I received this same error when trying to make changes to rules (Setting Priority or deleting) on our Application Gateway that we migrated to using an Application Gateway WAF policy.
[On another site](https://docs.microsoft.com/en-us/answers/questions/911237/cannot-renew-certificate-to-application-gateway-wi.html), they removed the WAF policy and converted the AG to a standard v2 SKU and then made the updates. 
That worked, and I was able to remove the rules I needed to.
Then I manually changed it back to WAF v2 and re-assigned the policy. So far, everything seems to be working ok. When I went to submit a support ticket they provided this issue so I wanted to submit my experience since it seems like it is related.

**Comment by BasBerk** [comment] 2022-08-04 06:39
seem that we get the same error when we try to replace an certificate.

**Comment by mateuszdrab** [comment] 2022-08-04 11:46
> Thanks for raising this issue. We are aware of the API issue that was recently introduced. We are working on rolling out the fix. The issue can occur when you use API to update the config to policy. If you're using [migration script](https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/migrate-policy) or Firewall Manager integration, you will also encounter this issue.
> 
> Meanwhile, the workaround is to nullify the WAF config object post upgrade. Thanks for your patience.
> 
> $SubscriptionId = '' $ResourceGroupName = '' $GatewayName = '' Connect-AzAccount -Subscription $SubscriptionId $AppGw = Get-AzApplicationGateway -ResourceGroupName $ResourceGroupName -Name $GatewayName $AppGw.webApplicationFirewallConfiguration = $null Set-AzApplicationGateway -ApplicationGateway $AppGw

Thank you for sharing @gunjanj 
This workaround helped me solve the issue for a customer facing the same error with AGIC in their AKS deployment.

**Comment by JackStromberg** [comment] 2022-09-08 04:47
We are pleased to announce this issue is now resolved and should no longer be observed.  Appreciate you all for raising the issue and your patience while we have rolled out a fix.

#please-close

**Closed** 2022-09-08 04:50 UTC
Labels: Service Attention, Network - Application Gateway
