### ISSUE TITLE
az storage share create - crashes when invalid name specified

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli#10034] opened 2019-07-24 15:20 UTC
It worked correctly when i tried:

`az storage share create --account-name mystoragexxxyyyy --name myshare`

but then i tried:

`az storage share create --account-name mystoragexxxyyyy --name MyShare`

and i got this crash:

```
root@d96027f3bc74:/workspaces/az/azure-cli-extensions# az storage share create --account-name mystoragexxxyyyy --name MyShare
The command failed with an unexpected error. Here is the traceback:

The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:6ff1c3b8-301a-012b-0432-42038e000000
Time:2019-07-24T15:17:54.6695224Z</Message></Error>
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/workspaces/az/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/workspaces/az/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/workspaces/az/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/env/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/workspaces/az/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/workspaces/az/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/workspaces/az/azure-cli/src/azure-cli-core/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/env/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/file/fileservice.py", line 667, in create_share
    _dont_fail_on_exist(ex)
  File "/env/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/_error.py", line 88, in _dont_fail_on_exist
    raise error
  File "/env/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/file/fileservice.py", line 664, in create_share
    self._perform_request(request, expected_errors=[_SHARE_ALREADY_EXISTS_ERROR_CODE])
  File "/env/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/storageclient.py", line 430, in _perform_request
    raise ex
  File "/env/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/storageclient.py", line 358, in _perform_request
    raise ex
  File "/env/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/env/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:6ff1c3b8-301a-012b-0432-42038e000000
Time:2019-07-24T15:17:54.6695224Z</Message></Error>
```

**Comment by Juliehzl** [comment] 2019-07-29 02:20
For Azure file share name, it should be lowercase. The second share name you want to create is invalid.

**Comment by zikalino** [comment] 2019-07-29 03:37
@Juliehzl I know it's invalid, and I think Azure CLI should detect that and display appropriate message instead of crashing.

**Comment by Guilhermeslucas** [comment] 2020-04-24 19:06
I'll take a quick look at it!

**Comment by Guilhermeslucas** [comment] 2020-04-24 19:47
I took a look at it, and the problem is that, even if you add a validator on the share_name variable, the command first checks remotely if this is a valid name. Any clues on ways of fixing it besides using a validator?

**Comment by yonzhan** [comment] 2020-04-25 00:50
add to S170

**Comment by yonzhan** [comment] 2020-06-19 04:26
add to S172

**Comment by RakeshMohanMSFT** [comment] 2022-08-03 10:42
@zikalino This issue is fixed with proper error message/warning
`az storage share create --account-name issue10034storage --name MyShare`

There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
The specifed resource name contains invalid characters.
RequestId:<resource_id>
Time:2022-08-03T10:41:50.3381022Z
ErrorCode:InvalidResourceName

**Closed by RakeshMohanMSFT** 2022-08-03 10:42 UTC
Labels: Storage, Track2, feature-request
