### ISSUE TITLE
[ACS] Scale command doesn't seem to work for Kubernetes clusters

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1303] opened 2016-11-12 01:50 UTC
The `az acs scale` command has worked great for DC/OS clusters, however, I just tried using it against a Kubernetes-configured cluster, and I get the following error: `Parameter 'secret' can not be None.`.

Is this command specific to DC/OS, or is it intended to support all ACS-supported orchestrators? Its help text seems to indicate that it's generic, but if that isn't the case, maybe it should be moved underneath the `az acs dcos` command group?

**Comment by chaliy** [comment] 2016-12-15 14:35
The same issue, 

```
az acs scale -n chaliy-play-azure-kubernetes \
		-g play-azure-kubernetes \
		--new-agent-count 5 \
		--debug
```

produces log:

```
Installed command modules ['acr', 'acs', 'appservice', 'cloud', 'component', 'configure', 'container', 'context', 'feedback', 'network', 'profile', 'resource', 'role', 'storage', 'vm']

Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x000001ABCA50B730>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x000001ABCA50B730>
Loaded module 'acr' in 0.540 seconds.
Loaded module 'acs' in 0.418 seconds.
Loaded module 'appservice' in 0.178 seconds.
Loaded module 'cloud' in 0.005 seconds.
Loaded module 'component' in 0.007 seconds.
Loaded module 'configure' in 0.017 seconds.
Loaded module 'container' in 0.005 seconds.
Loaded module 'context' in 0.009 seconds.
Loaded module 'feedback' in 0.005 seconds.
Loaded module 'network' in 0.921 seconds.
Loaded module 'profile' in 0.007 seconds.
Loaded module 'resource' in 0.014 seconds.
Loaded module 'role' in 0.112 seconds.
Loaded module 'storage' in 0.152 seconds.
Registered application event handler 'CommandParser.Parsed' at <function _handle_auth_types at 0x000001ABCC1128C8>
Registered application event handler 'CommandParser.Parsed' at <function _handle_container_ssh_file at 0x000001ABCC112C80>
Loaded module 'vm' in 0.110 seconds.
Loaded all modules in 2.498 seconds. (note: there's always an overhead with the first module loaded)
.....Truncated....
Getting management service client client_type=ComputeManagementClient
msrest.pipeline : Adding 'log_request' callback before event: 'request'
msrest.pipeline : Callback to overwrite original call: False
msrest.pipeline : Adding 'log_response' callback after event: 'response'
msrest.pipeline : Callback to overwrite original call: False
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - Authority:Performing instance discovery: https://login.microsoftonline.com/f37.............ad3
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - Authority:Performing static instance discovery
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - Authority:Authority validated via static instance discovery
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - OAuth2Client:finding with query: {"_clientId": "04b...............46", "userId": "mike@chaliy.name"}
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - OAuth2Client:Looking for potential cache entries:
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - OAuth2Client:{"_clientId": "04b0.........46", "userId": "mike@chaliy.name"}
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - OAuth2Client:Found 4 potential entries.
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - OAuth2Client:Resource specific token found.
adal-python : 339cc072-c65d-4b0e-b154-aff0a311db0e - OAuth2Client:Returning token from cache lookup, AccessTokenId: b'cV........h4=', RefreshTokenId: b'vA...............8='
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/e08.....827/resourceGroups/play-azure-kubernetes/providers/Microsoft.ContainerService/containerServices/chaliy-play-azure-kubernetes?api-version=2016-09-30'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.5.2 (Windows-10-10.0.10586-SP0) requests/2.12.4 msrest/0.4.4 msrest_azure/0.4.6 computemanagementclient/0.32.1 Azure-SDK-For-Python AZURECLI/0.1.0b11'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Authorization': 'Bearer eyJ0eX......hA7MoFdiQ8yg'
msrest.http_logger :     'x-ms-client-request-id': 'a38a5c30-c2d2-11e6-af2a-448500c58cc0'
msrest.http_logger :     'CommandName': 'acs scale'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
requests.packages.urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/e08.........827/resourceGroups/play-azure-kubernetes/providers/Microsoft.ContainerService/containerServices/chaliy-play-azure-kubernetes?api-version=2016-09-30 HTTP/1.1" 200 None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Transfer-Encoding': 'chunked'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'x-ms-served-by': '22fcc43b-688e-4402-a02d-bb333ded2418_131236373258010686'
msrest.http_logger :     'x-ms-request-id': '4a922193-2541-466b-a162-0031d265f974'
msrest.http_logger :     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '14882'
msrest.http_logger :     'x-ms-correlation-request-id': 'ad466a58-e059-420c-aa9e-6073d31c2856'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTEUROPE:20161215T142748Z:ad466a58-e059-420c-aa9e-6073d31c2856'
msrest.http_logger :     'Date': 'Thu, 15 Dec 2016 14:27:48 GMT'
msrest.http_logger : Response content:
msrest.http_logger : Body contains chunked data.
msrest.exceptions : Parameter 'secret' can not be None.
Parameter 'secret' can not be None.
```

If this is not correct way to scale it, please let us know what is correct way.

**Comment by kaubry** [comment] 2016-12-16 07:45
Same here, impossible to scale a Kubernetes cluster on Azure. 
Trying with `az acs scale` command as well as in the portal. 
`az acs scale` throw me P`arameter 'secret' can not be None`
portal tells me that scale up/down is not supported by this orchestratorType.

Please fix this. I think this is a basic functionality for a container service cluster.

**Comment by chaliy** [comment] 2016-12-16 07:50
Root cause of the issue is lack of scaling support in acs-engine - https://github.com/Azure/acs-engine/issues/109 , so probably acs-engine is better place to track the progress.

**Comment by brendandburns** [comment] 2017-02-28 00:38
This was fixed by: https://github.com/Azure/azure-cli/pull/2287

Please re-open if it re-occurs.

**Closed by brendandburns** 2017-02-28 00:38 UTC
Labels: ACS

**Comment by dbalaouras** [comment] 2017-03-11 10:38
Hi @brendandburns , is this fix live yet? I just had the same issue:

```
dimi (dev *) config $ date && az acs scale --name=clst-west-eu-dev --new-agent-count=9 --resource-group=acs-west-eu-dev
Sat Mar 11 12:37:37 EET 2017
Parameter 'ContainerServiceServicePrincipalProfile.secret' can not be None.
```

ta.

**Comment by krish7919** [comment] 2017-03-13 01:16
@brendandburns: I just hit the same issue again even after running a 'az component update...'.

**Comment by derekbekoe** [comment] 2017-03-13 19:17
This change is part of this release happening later today.
https://github.com/Azure/azure-cli/pull/2480

**Comment by tdnguyen070** [comment] 2017-10-24 01:01
I am running into the same issue with az acs scaling.

Version:
Client: 1.7.5
Server: 1.7.5

Error:An error has occurred in subscription 3f8d5e21-f22d-4986-abab-4bd8862cadaa, resourceGroup: testRG request: Provisioning of resource(s) for container service testKube in resource group testRG failed. Message: {
  "code": "OperationNotAllowed",
  "message": "Updating Kubernetes version and agent node scaling are mutually exclusive operations"
 }. Details: .
