### ISSUE TITLE
az keyvault secret list gets stacktrace in WSL2 ubuntu

### ISSUE THREAD

**Issue by mdesimone1** [Azure/azure-cli#15957] opened 2020-11-17 21:10 UTC
## Describe the bug

**Command Name**
`az keyvault secret list`

this was in ubuntu WSL2 in windows 10.  the summary command 'az keyvault secret' worked:
 az keyvault secret
az keyvault secret: error: the following arguments are required: _subcommand
usage: az keyvault secret [-h]
                          {list,list-versions,list-deleted,set,set-attributes,show,show-deleted,delete,purge,recover,download,backup,restore}

also this worked: "az keyvault show --name mdesimone-vault"

i'd installed via 'apt install azure-cli'

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret list`

## Expected Behavior
list the secrets in the test vault

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment] 2020-11-18 01:57
hi @bim-msft could you pls help to have a look?

**Comment by yungezz** [comment] 2021-02-18 09:33
hi @mdesimone1 the issue is fixed in latest Azure CLI, could you pls try install latest CLI to validate? will close the issue for now, pls create new one if see any errors, thanks.

**Closed by yungezz** 2021-02-18 09:33 UTC
Labels: KeyVault

**Comment by jiasli** [comment] 2022-06-07 05:05
Duplicate of #13101. To fix it, please see https://github.com/Azure/azure-cli/issues/19640#issuecomment-924578571.
