### ISSUE TITLE
Is az deployment related to auto-created deployment?

### ISSUE THREAD

**Issue by ericmoses** [Azure/azure-cli#10524] opened 2019-09-13 16:39 UTC
Under a resource group =&gt; deployments, I see hundreds of deployments. These seem to be auto-generated(?) as I have no code that creates or generates them. Since I'm a heavy user, this sometimes leads to the error below:

Creating the deployment 'Microsoft.VirtualNetwork-20190226034727' would exceed the quota of '800'. The current deployment count is '800', please delete some deployments before creating a new one. Please see https://aka.ms/arm-deploy for usage details. (Code: DeploymentQuotaExceeded)

The Deployments in question can be deleted, but from the GUI/Console, it must be done one-by one, there is no select all.

To resolve this, I was under the impression that 'az deployment delete..' 'az deployment list...' 'az deployment show..' etc could be used to manage this list, but apparently not -- because, none of these calls return or do anything at all. So I'm requesting clarification, do these API calls apply to this auto-generated deployments?

Thanks!
Eric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 823a25e4-e55f-28b1-fc60-bf2dbe423864
* Version Independent ID: a51a0f39-009e-ad07-b471-54c8762ddf0b
* Content: [az deployment](https://docs.microsoft.com/en-us/cli/azure/deployment?view=azure-cli-latest#az-deployment-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment] 2019-09-15 16:01
@ericmoses Thanks for your feedback. I am the new owner for `az deployment` command. From my current knowledge for `az deployment`, I think it cannot achieve what you want. But let's involve @yugangw-msft   for more information for this.

**Comment by jits2019** [comment] 2019-10-29 13:45
I am not able to run : az deployment delete command. It gives this error: 

[**Upcoming breaking change**]: a new parameter "scope-type" will be introduced to commands in this group and will be mandatory. Scope type will be an enum with four values: ResourceGroup, Subscription, ManagementGroup, Tenant. Adding this parameter allows us to use one command for all Azure Resource Manager template deployments but still determine the intended level of scope. 

Can the doc be updated for any changes with the syntax please?

**Comment by yonzhan** [comment] 2020-05-03 03:51
add to S170

**Comment by zhoxing-ms** [comment] 2020-05-20 08:15
@ericmoses Hi, the commands related to `az deployment` will deploy all resources in the ARM template. You can click the *Related events* in the list page of deployments on portal to see the corresponding Activity log for the deployments, so as to find out the causes of the deployment.
@jits2019 As for the commands related to `az deployment` (include `az deployment delete`), there is a big upgrade in the new version of CLI. For details, please refer to the documentation: [link](https://docs.microsoft.com/en-us/cli/azure/deployment?view=azure-cli-latest)

Do you have any other questions?

**Comment by yonzhan** [comment] 2020-05-31 02:30
@ericmoses  @jits2019  any other questions?

**Comment by zhoxing-ms** [comment] 2020-06-10 07:51
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-06-10 07:51 UTC
Labels: ARM, OKR3.4 Candidate
