### ISSUE TITLE
"az monitor autoscale list" should not write TimeZone in "start" and "end" property

### ISSUE THREAD

**Issue by kamiyn** [Azure/azure-cli#10116] opened 2019-08-01 06:13 UTC
fixedDate property produced by "az monitor autoscale list" have inconsistent timezones.

"stard" and "end" have "+00:00" (UTC)
but
individual property "timeZone" have my local timezone
like this:

```json
[
    {
        "name": "sample-autoscale",
        "profiles": [
            {
                "fixedDate": {
                    "end": "2018-12-31T16:00:00+00:00",
                    "start": "2018-12-27T12:00:00+00:00",
                    "timeZone": "Tokyo Standard Time"
                }
            }
        ]
    }
]```

In my opinion, "start" and "end" should not have +00:00 timezone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ad7b0e-134f-f900-9541-755fba68ec82
* Version Independent ID: b5c272d3-4df7-59c3-6f2d-23fb97122258
* Content: [az monitor autoscale profile](https://docs.microsoft.com/en-us/cli/azure/monitor/autoscale/profile?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment] 2019-10-17 02:03
Sorry for the delay. I will take a look at it later.

**Comment by yonzhan** [comment] 2020-05-02 13:29
add to S170

**Comment by shilpasharmaAM** [comment] 2020-05-28 23:11
Hi @kamiyn the start and end time always contain +00:00" (UTC). I would like to understand more on how it impacts the scaling condition you are setting? Can you provide me examples of issues caused by this?

**Comment by shilpasharmaAM** [comment] 2020-06-04 20:16
Closing this issue for now. Feel free to reactivate if you have data to share with us.

**Closed by shilpasharmaAM** 2020-06-04 20:16 UTC
Labels: Monitor, Monitor - Autoscale, Service Attention
