### ISSUE TITLE
CLI Login Fails: ValueError: Unable to find wstrust endpoint from MEX.

### ISSUE THREAD

**Issue by bullsear** [Azure/azure-cli#26315] opened 2023-05-02 20:35 UTC
## Describe the bug

Login works via the portal, but when I provide username and password at the cli, I get the stack trace below.

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
- _Put any pre-requisite steps here..._
- `az login -u {} -p {}`
The command failed with an unexpected error. Here is the traceback:
Unable to find wstrust endpoint from MEX. This typically happens when attempting MSA accounts. More details available here. https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 157, in login
    user_identity = identity.login_with_username_password(username, password, scopes=scopes, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 172, in login_with_username_password
    result = self._msal_app.acquire_token_by_username_password(username, password, scopes, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/msal/application.py", line 1619, in acquire_token_by_username_password
    response = _clean_up(self._acquire_token_by_username_password_federated(
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/msal/application.py", line 1641, in _acquire_token_by_username_password_federated
    raise ValueError("Unable to find wstrust endpoint from MEX. "
ValueError: Unable to find wstrust endpoint from MEX. This typically happens when attempting MSA accounts. More details available here. https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication
```

## Expected Behavior
Login successfully

## Environment Summary
```
macOS-13.3.1-arm64-arm-64bit, Darwin 22.4.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.48.1
```

**Comment by yonzhan** [comment] 2023-05-02 20:35
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2023-05-05 07:25
Duplicate of https://github.com/Azure/azure-cli/issues/20221

**Closed** 2023-05-29 00:18 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
