### ISSUE TITLE
Extensions should be able to register cloud-specific information 

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4786] opened 2017-10-30 21:54 UTC
Extensions need a way to register any custom endpoints for different clouds. Core CLI modules manually add their entries to the core profile code, but this isn't available to extensions, so there must be some way (perhaps through the extension metadata) that this information can be applied.

**Comment by derekbekoe** [comment] 2018-04-25 22:07
I've taken a look at this and after the Knack conversion, this is already possible:

e.g.:
```
class MyCommandsLoader(AzCommandsLoader):
    def __init__(self, cli_ctx=None):
        cli_ctx.cloud.endpoint.custom_endpoint = 'mytest.a.b.c'
```

Then, this endpoint is available where needed.
This is possible after Knack conversion because the cli_ctx contains the current cloud object.

Sound good to close this issue? @troydai @tjprescott @williexu @yugangw-msft

**Comment by JasonRShaver** [comment] 2018-08-08 22:01
working as intended

**Closed by JasonRShaver** 2018-08-08 22:01 UTC
Labels: Extensions, Feature
