### ISSUE TITLE
Blob Storage error in large file upload

### ISSUE THREAD

**Issue by yiufung** [Azure/azure-cli#7108] opened 2018-08-21 09:59 UTC
**Describe the bug**
When using `az storage blob upload` to upload a large file (~>1G), return status is normal, but blob is not correctly created (`exists` and `download` failes)

**To Reproduce**
Create a 1MB file and upload, both return success on `exists` and `download`. 
Create a 1GB file and upload, upload process return 0, but `exists` and `download` both fail. 
Uploading both files using AzCopy instead is fine. 

**Expected behavior**
Success upload regardless of size. 

**Environment summary**
Kubuntu 18.04 Terminal
azure-cli (2.0.44)

**Additional context**
As we use the blob storage in HDFS as well, after uploading the file using Azure CLI, it will shows up in `hdfs dfs -ls` command. However, `-mv` or `-rm` the file in HDFS will fail as well, giving non-exist errors. 

[Understanding Block/Page/Append Blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs) provides some hints. However, the API seems not available in Azure CLI.

**Comment by williexu** [comment] 2018-08-23 00:14
@yiufung what types of blobs are you uploading? (block/page/append)

Also, can you clarify what you mean by "the API seems not available in Azure CLI"?

**Comment by yiufung** [comment] 2018-08-23 02:48
@williexu Oh, I thought the method of specifying `--type` is not available in the docs. 

I did not specify `--type` before, so the default should be `block`. Tried it with the same command today, and now it works as expected, whether to add `--type "block"` or not. This is strange, coz the file I uploaded before are still listed by `hdfs dfs -ls`, but not accessible.

**Comment by williexu** [comment] 2018-08-23 17:18
@yiufung  By default, blobs are uploaded as block blobs unless they are .vhd files. That's probably why it didn't matter whether you specified `--type block` or not. 
It sounds like you are able to upload successfully the second time.

For the blobs you uploaded the first round; you mentioned that an existence check does not pass. That probably means you also can't do a `blob show` on the blob correct? Are you able to reproduce this?

**Comment by yiufung** [comment] 2018-08-24 01:53
@williexu Yes, for the default upload method, it's as expected. 

For the first round, what I mean is that when I do a `blob exists`, it returns `false`, and `blob show` returns `ErrorCode:BlobNotFound`. It's still the case for the blobs I uploaded previously. They are shown when I do a `hdfs dfs -ls` using `wasbs` protocol, but cannot be `-rm` or `-mv`.

**Comment by williexu** [comment] 2018-08-30 22:39
@seguler @zezha-msft  in what situation would hadoop see a blob despite it a 404 being returned from the service?

**Comment by zezha-msft** [comment] 2018-08-30 22:59
Hi @williexu, that sounds extremely strange and shouldn't happen at all. 

Hi @yiufung, to clarify, are you saying that:

1. You tried uploading a 1GB file to Storage as block blob, and it looks like it succeeded. 
3. However, the exist call fails; but from the WASB side, it does exist.

Could you please confirm whether the blob exists or not using [Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/)?

**Comment by yiufung** [comment] 2018-08-31 02:44
@zezha-msft Yes. Additionally,

3. When I do a `hdfs dfs -ls wasbs://path/to/folder` in WASB side, the file is shown in list results. 
4. When I do a `hdfs dfs -ls wasbs://path/to/folder/the_error_file` in WASB side, `No such file or directory` error is shown.

**Comment by seguler** [comment] 2018-08-31 18:47
Can you share the exact CLI command you ran to upload the file ? We had an issue before where an extra slash would be placed in front of the blob name.. Hence some tools like WASB may have trouble listing or stating the file like you face above.

**Comment by yiufung** [comment] 2018-09-03 01:54
```sh
az storage blob upload --account-name "***" --container-name "***" --sas-token "***" --file "~/path/to/transac.sqlite" --name "Price_Model_transac.sqlite"
```
If you are talking about the `--name` parameter, there is no extra slash placed in front of it in my bash_history.

**Comment by zhusijia26** [comment] 2019-06-06 18:14
Close the issue due to the idle time. Please reopen if there is still questions.

**Closed by zhusijia26** 2019-06-06 18:14 UTC
Labels: Question, Service Attention, Storage
