### ISSUE TITLE
Error running az group list

### ISSUE THREAD

**Issue by ausafonly** [Azure/azure-cli#13886] opened 2020-06-08 18:06 UTC
## Describe the bug

**Command Name**
`az group list`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group list`

## Environment Summary
```
Linux-4.15.0-1083-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yungezz** [comment] 2020-06-09 01:47
hi @ausafonly where did you see this error? same error as in https://github.com/Azure/azure-cli/issues/13884.

**Comment by ausafonly** [comment] 2020-06-09 16:53
When i am running it om windows terminal using azure cloud shell

**Comment by yonzhan** [comment] 2020-06-09 21:10
@ausafonly Could you pls workaround with az login ?

**Comment by yonzhan** [comment] 2020-07-04 14:41
@ausafonly any update?

**Comment by arrownj** [comment] 2020-08-18 06:39
Hi @ausafonly , this is a know issue of cloud shell. The problem is tracked in #11749 . For a workaround solution, you can run `az login` and retry the command. Close this one first.

**Closed by arrownj** 2020-08-18 06:39 UTC
Labels: Account, Cloud Shell, Service Attention
