### ISSUE TITLE
"az extension add --name rdbms-connect" not working

### ISSUE THREAD

**Issue by kosher-svk** [Azure/azure-cli#21985] opened 2022-04-07 23:49 UTC
## Describe the bug

**Command Name**
`az extension add --name rdbms-connect`

**Errors:**
```
An error occurred. Pip failed with status code 1. Use --debug for more information.

```

**To Reproduce**
```
1. i used this tutorial https://docs.microsoft.com/en-us/azure/mysql/flexible-server/connect-azure-cli
2. i want to instal it because i did MySQL flexible server tutorial
3. after creating MySQL server i ran Azure CLI
4.  az mysql flexible-server connect -n <servername> -u <username> -p <password> -d <databasename>
5. after it showed :
The command requires the extension rdbms-connect. It will be installed first.
 cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /home/<MY USERNAME>/.azure/cliextensions/rdbms-connect
6. I tried "az extension add --name rdbms-connect" but nothing works
```
**Expected behavior**

**Environment summary**

```
Linux-5.4.0-1074-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
ai-examples 0.2.5
ssh 1.0.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Additional context**

**Comment by yonzhan** [comment] 2022-04-08 00:11
route to CXP team

**Comment by kosher-svk** [comment] 2022-04-08 00:34
Hello,
Does i need send it to another place?

Dňa pi 8. 4. 2022, 2:11 Yong Zhang ***@***.***> napísal(a):

**Comment by RakeshMohanMSFT** [comment] 2022-04-08 04:09
@kosher-svk Thank you for reaching out to us. We are looking into it.

**Comment by RakeshMohanMSFT** [comment] 2022-04-11 10:52
This is a duplicate of https://github.com/Azure/azure-cli/issues/21953, we will continue to work on the issue to provide a solution under https://github.com/Azure/azure-cli/issues/21953

**Closed by RakeshMohanMSFT** 2022-04-11 10:52 UTC
Labels: MySQL, customer-reported, CXP Attention, Auto-Assign
