### ISSUE TITLE
[DNS] Zone import crashes

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1882] opened 2017-01-26 13:43 UTC
Please try to import the attached zone file. Currently, this causes the CLI to crash.

This zone file covers many (but not all) of the zone import cases we've learned from in CLI1.0
[mytestzone.com.dns.txt](https://github.com/Azure/azure-cli/files/732392/mytestzone.com.dns.txt)

**Comment by tjprescott** [comment] 2017-01-26 17:43
Duplicate of #1126.

**Closed by tjprescott** 2017-01-26 17:43 UTC
