### ISSUE TITLE
´aks browse´ disconnects constantly

### ISSUE THREAD

**Issue by jesulink2514** [Azure/azure-cli#9582] opened 2019-06-06 16:34 UTC
## Describe the bug
Using Azure cli, I connect to AKS cluster and use the dashboard without problems, but after a couple of minutes the connection just drops out. This happens time after time. You can see error details below.

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05B6E9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
pip-install-oxpg5sa3\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
urllib3\urllib3\util\connection.py, ln 70, in create_connection
...
pip-install-ygnynjtx\requests\requests\adapters.py, ln 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05B6E9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
```

## To Reproduce:
Steps to reproduce the behaviour. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse -g {} -n {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66

Extensions:
dev-spaces 1.0.1
dev-spaces-preview 0.1.6

```

**Comment by seanmck** [comment] 2019-07-14 07:11
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:11 UTC
Labels: AKS, Needs Triage, Service Attention
