### ISSUE TITLE
az image copy failed create snapshot

### ISSUE THREAD

**Issue by architectone** [Azure/azure-cli#14560] opened 2020-07-29 02:04 UTC
## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**
```
The client has permission to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' on scope '/subscriptions/X/resourceGroups/image-copy-rg/providers/Microsoft.Compute/snapshots/snapshot', however the linked subscription 'sub_x' was not found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az snapshot create --resource-group {} --name {} --location {} --source {} --source-storage-account-id {} --output {} --subscription {} --tags {}`

## Environment Summary
```
Linux-4.15.0-1091-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.0 *

Extensions:
azure-devops 0.18.0
image-copy-extension 0.2.6

```

**Comment by yonzhan** [comment] 2020-07-29 02:59
@qwordy please take a look

**Comment by arrownj** [comment] 2020-09-02 09:23
To give a background introduction, the root cause is that `az snapshot create` do not accept `location` value which differ from the source disk's location. 

Not sure it's an issue from the very beginning or introduced by service side from some point.  HI @qwordy , could you please help involve service team member into this ?

**Comment by qwordy** [comment] 2020-09-03 08:24
Service team confirms that snapshot must locate in same location as source disk.

**Comment by yungezz** [comment] 2020-09-14 04:57
hi @qwordy so this is by design? can we close the issue then?

**Comment by qwordy** [comment] 2020-09-14 07:09
We have fixed this issue. We will always create snapshot in same location with disk.

**Closed by qwordy** 2020-09-14 07:09 UTC
Labels: Compute, OKR3.2 Candidate
