### ISSUE TITLE
Example condition is incorrect

### ISSUE THREAD

**Issue by ikantspel9** [Azure/azure-cli#12925] opened 2020-04-08 16:51 UTC
Current example lists --condition "avg Percentage CPU &gt; 90" as a parameter. This is no longer valid, --condition "avg cpu_percent &gt; 90" must be used. This is also incorrect in az monitor metrics alert create --help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-04-08 23:16
add to S169

**Comment by yonzhan** [comment] 2020-05-02 23:59
add to S171

**Comment by MyronFanQiu** [comment] 2020-06-02 08:53
@ikantspel9 I have a test and `Percentage CPU` still works. Could you share more context about this issue?

**Comment by MyronFanQiu** [comment] 2020-06-11 07:00
close this issue since cannot reproduce. Feel free to open new issue if you still meet such issue.

**Closed by MyronFanQiu** 2020-06-11 07:00 UTC
Labels: Monitor, OKR3.2 Candidate, feature-request
