### ISSUE TITLE
az aks upgrade tty error in Azure DevOps agent

### ISSUE THREAD

**Issue by torosent** [Azure/azure-cli#11099] opened 2019-11-04 22:29 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.77

**Describe the bug**
az aks upgrade command results in failure on tty exception
```
2019-11-04T22:21:12.3465035Z ERROR: The command failed with an unexpected error. Here is the traceback:
2019-11-04T22:21:12.3465893Z
2019-11-04T22:21:12.4362846Z ERROR:
2019-11-04T22:21:12.4363326Z Traceback (most recent call last):
2019-11-04T22:21:12.4364522Z File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
2019-11-04T22:21:12.4364661Z cmd_result = self.invocation.execute(args)
2019-11-04T22:21:12.4365063Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
2019-11-04T22:21:12.4365196Z raise ex
2019-11-04T22:21:12.4365577Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
2019-11-04T22:21:12.4365669Z results.append(self._run_job(expanded_arg, cmd_copy))
2019-11-04T22:21:12.4366020Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
2019-11-04T22:21:12.4366295Z six.reraise(*sys.exc_info())
2019-11-04T22:21:12.4366608Z File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
2019-11-04T22:21:12.4366954Z raise value
2019-11-04T22:21:12.4367328Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
2019-11-04T22:21:12.4367407Z result = cmd_copy(params)
2019-11-04T22:21:12.4367730Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
2019-11-04T22:21:12.4367811Z return self.handler(*args, **kwargs)
2019-11-04T22:21:12.4368596Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
2019-11-04T22:21:12.4368696Z return op(**command_args)
2019-11-04T22:21:12.4369086Z File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2048, in aks_upgrade
2019-11-04T22:21:12.4369179Z if not prompt_y_n(msg, default="n"):
2019-11-04T22:21:12.4369522Z File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 73, in prompt_y_n
2019-11-04T22:21:12.4369839Z return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
2019-11-04T22:21:12.4370194Z File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 81, in _prompt_bool
2019-11-04T22:21:12.4370277Z verify_is_a_tty()
2019-11-04T22:21:12.4370617Z File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 30, in verify_is_a_tty
2019-11-04T22:21:12.4370700Z raise NoTTYException()
2019-11-04T22:21:12.4370798Z knack.prompting.NoTTYException
```

**To Reproduce**
`az aks upgrade --resource-group  grp --name aks --kubernetes-version 1.14.8 --yes`

**Expected behavior**
Start upgrade operation 

**Environment summary**
Azure DevOps Ubuntu 16.04 agent

**Comment by torosent** [comment] 2019-12-04 17:41
@Azure/aks-pm  Any update on this?

**Comment by jluk** [comment] 2019-12-04 21:32
@torosent this is a bit outdated of an azure cli version, could you please try to upgrade to 2.0.77 as I was not able to reproduce this bug on that version?

**Comment by torosent** [comment] 2019-12-09 18:49
@jluk ,I was able to reproduce it with 2.0.77 in Azure DevOps Ubuntu 16.04 agent.
```
2019-12-09T18:46:41.7905699Z azure-cli 2.0.77
2019-12-09T18:46:41.7906453Z
2019-12-09T18:46:41.7907306Z command-modules-nspkg 2.0.3
2019-12-09T18:46:41.7907722Z core 2.0.77
2019-12-09T18:46:41.7907798Z nspkg 3.0.4
2019-12-09T18:46:41.7907960Z telemetry 1.0.4
2019-12-09T18:46:41.7908001Z
2019-12-09T18:46:41.7909288Z Python location '/opt/az/bin/python3'
2019-12-09T18:46:41.7909573Z Extensions directory '/home/vsts/.azure/cliextensions'
2019-12-09T18:46:41.7909819Z
2019-12-09T18:46:41.7909891Z Python (Linux) 3.6.5 (default, Nov 22 2019, 05:32:22)
2019-12-09T18:46:41.7909958Z [GCC 5.4.0 20160609]
2019-12-09T18:46:41.7910273Z
2019-12-09T18:46:41.7910332Z Legal docs and information: aka.ms/AzureCliLegal
2019-12-09T18:46:41.7910377Z
2019-12-09T18:46:41.7910452Z
2019-12-09T18:46:41.7910485Z
2019-12-09T18:46:41.7910781Z Your CLI is up-to-date.
2019-12-09T18:46:47.0909532Z ERROR: The command failed with an unexpected error. Here is the traceback:
2019-12-09T18:46:47.0910704Z
2019-12-09T18:46:47.1932086Z ERROR:
2019-12-09T18:46:47.1932237Z Traceback (most recent call last):
2019-12-09T18:46:47.1933434Z File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
2019-12-09T18:46:47.1933527Z cmd_result = self.invocation.execute(args)
2019-12-09T18:46:47.1933934Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
2019-12-09T18:46:47.1934017Z raise ex
2019-12-09T18:46:47.1934388Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
2019-12-09T18:46:47.1934504Z results.append(self._run_job(expanded_arg, cmd_copy))
2019-12-09T18:46:47.1935027Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
2019-12-09T18:46:47.1935323Z six.reraise(*sys.exc_info())
2019-12-09T18:46:47.1935682Z File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
2019-12-09T18:46:47.1935756Z raise value
2019-12-09T18:46:47.1936103Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
2019-12-09T18:46:47.1936179Z result = cmd_copy(params)
2019-12-09T18:46:47.1936497Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
2019-12-09T18:46:47.1936574Z return self.handler(*args, **kwargs)
2019-12-09T18:46:47.1936923Z File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 487, in default_command_handler
2019-12-09T18:46:47.1937016Z return op(**command_args)
2019-12-09T18:46:47.1937377Z File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2100, in aks_upgrade
2019-12-09T18:46:47.1937461Z if not prompt_y_n(msg, default="n"):
2019-12-09T18:46:47.1937791Z File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 73, in prompt_y_n
2019-12-09T18:46:47.1938084Z return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
2019-12-09T18:46:47.1938588Z File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 81, in _prompt_bool
2019-12-09T18:46:47.1938666Z verify_is_a_tty()
2019-12-09T18:46:47.1939004Z File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 30, in verify_is_a_tty
2019-12-09T18:46:47.1939084Z raise NoTTYException()
2019-12-09T18:46:47.1939187Z knack.prompting.NoTTYException
```

**Comment by palma21** [comment] 2019-12-16 22:31
@MyronFanQiu This looks Azure DevOps agent specific. Could we bring/ask the ADO team?

**Comment by MyronFanQiu** [comment] 2019-12-18 02:17
@torosent @palma21  We need to do the investigation about this issue.

**Comment by MyronFanQiu** [comment] 2019-12-18 02:18
+ @jiasli who is the current owner of Knack.

**Comment by torosent** [comment] 2020-02-05 16:24
@jiasli Any update on this issue?

**Comment by jiasli** [comment] 2020-02-07 11:16
Sorry for the delay as we are very heavily loaded recently. 

From the error message:

```
File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", 
  line 2100, in aks_upgrade
if not prompt_y_n(msg, default="n"):
```

We can see it reaches this line:

https://github.com/Azure/azure-cli/blob/c0e345c7719cf20898ad4257171557b8e7e4d955/src/azure-cli/azure/cli/command_modules/acs/custom.py#L2101

Apparently the program when into a step where user input is needed. As commands running in DevOps doesn't have a tty, this failure is expected. 

Fix can be either of:
- @torosent, adjust the command so that it doesn't reach this line. 
- @jluk, add param to skip/override human input

**Comment by torosent** [comment] 2020-02-10 00:06
@jluk  since `--yes` is already added to the command, this line shouldn't be reached.

**Comment by tdihp** [comment] 2020-02-21 05:12
For a workaround:

    az resource update --ids <aks_resource_id> --set 'properties.kubernetesVersion=<k8s_version>'--set 'properties.agentPoolProfiles[0].orchestratorVersion=<k8s_version>'

**Comment by sathishkumar3009** [comment] 2023-02-24 15:48
I'm facing this issue, what is the final update on this issue.

**Comment by mhassan1** [comment] 2023-04-07 14:19
It seems like this has been resolved by https://github.com/Azure/azure-cli/pull/13741, when passing `--yes`. This issue can probably be closed.

**Closed** 2023-04-08 00:46 UTC
Labels: Service Attention, Knack, VSTS
