### ISSUE TITLE
CosmosDB: Cannot disable key based metadata write

### ISSUE THREAD

**Issue by alsastre** [Azure/azure-cli#13808] opened 2020-06-03 16:13 UTC
## Describe the bug
Following the documentation at: https://docs.microsoft.com/en-us/azure/cosmos-db/role-based-access-control#preventing-changes-from-cosmos-sdk
I tried to lockdown the cosmosdb but the cli failed with the following trace:
**Command Name**
`az cosmosdb update`

**Errors:**
```
'NoneType' object has no attribute 'consistency_policy'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 545, in default_command_handler
    return op(**command_args)
cli/command_modules/cosmosdb/custom.py, ln 163, in cli_cosmosdb_update
    max_staleness_prefix = existing.consistency_policy.max_staleness_prefix
AttributeError: 'NoneType' object has no attribute 'consistency_policy'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
Create a cosmosDb and try to update it.
- `az cosmosdb update --name {} --resource-group {} --disable-key-based-metadata-write-access {}`

## Expected Behavior
key-based-metadata-write-access is disabled

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0

Extensions:
azure-firewall 0.3.1
azure-devops 0.17.0

```

**Comment by yonzhan** [comment] 2020-06-03 23:34
cosmosdb

**Comment by shurd** [comment] 2020-06-04 19:57
Hi @alsastre thank you for opening this issue. I was able to reproduce this error by targeting a non-existent account. Can you please ensure that the resource group and account name are correct? We are working on fixing the error message in this case, and I will update once we have a timeline for the fix.

**Comment by shurd** [comment] 2020-07-14 19:21
We have updated the swagger so that the SDK will provide an error message when the account does not exist. This change will be in the next SDK release and then can be applied to the CLI. Target is middle of August release.

**Comment by shurd** [comment] 2020-09-08 19:20
To update this issue, the management SDK has been updated to properly throw the not found exception. The CLI will be updated to use the newer version with the next cosmosdb command module update. This was originally targeted for the middle of August, but has been delayed.

**Comment by MehaKaushik** [comment] 2020-09-23 08:44
As a part of S175(https://github.com/Azure/azure-powershell/milestone/109), a CosmosDB was updated. @alsastre please verify if the issue is resolved.

**Comment by MehaKaushik** [comment] 2020-09-23 08:46
As a part of S175(https://github.com/Azure/azure-powershell/milestone/109), a CosmosDB was updated. @alsastre please verify if your issue is resolved now.

**Comment by shurd** [comment] 2020-09-28 20:33
Closing this issue as the error messaging was improved in CLI release 2.12.0 as Meha mentioned. Please re-open or open a new issue if the problem persists.

**Closed by shurd** 2020-09-28 20:33 UTC
Labels: Cosmos, Service Attention, customer-reported, customer-response-expected
