### ISSUE TITLE
az storage container generate-sas generates an invalid SAS if I don't pass the expiry date

### ISSUE THREAD

**Issue by shehabafawzy** [Azure/azure-cli#10935] opened 2019-10-22 00:49 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If you try to create a container SAS using the following command __az storage container generate-sas__, without passing the __expiry date__, it will generate a SAS that will give you the following error if you try to use it:
```
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:6019e900-201e-003c-216e-887033000000 Time:2019-10-22T00:17:04.6790192Z
</Message>
<AuthenticationErrorDetail>se is mandatory. Cannot be empty</AuthenticationErrorDetail>
</Error>
```
If i try the same command with passing the __--expiry__ parameter it works.

**To Reproduce**
Run the following command __az storage container generate-sas --account-name "contosoads" -n dsc --permissions rw__ on a storage account that you own
trying using the generated SAS and it will give you the above error.

**Expected behavior**
It shouldn't have generated a SAS that doesn't work, it should have asked for the expiry date as a missing parameter.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by Juliehzl** [comment] 2019-10-22 01:27
Hi @shehabafawzy, thanks a lot for your feedback! It's really valuable to us! There are two problems which should pay attention to for CLI team:
1. For the sas-token generated without --expiry, Azcopy copy command will throw error:
```
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:2c37a983-101e-0013-4276-886998000000
Time:2019-10-22T01:14:36.1502672Z, Details:
   AuthenticationErrorDetail: se is mandatory. Cannot be empty
   Code: AuthenticationFailed
...
```
2.  For the sas-token generated without --expiry, az storage blob upload will give wrong error message as follows:
```
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
```
which is dupe of #10861.

**Comment by yonzhan** [comment] 2020-05-16 07:50
add to S171

**Closed** 2020-06-19 00:34 UTC
Labels: OKR3.4 Candidate, Storage
