### ISSUE TITLE
Missing parenthesis - Python Error

### ISSUE THREAD

**Issue by Udayabharathi-Thiagarajan** [Azure/azure-cli#8617] opened 2019-02-22 12:57 UTC
**Missing Parenthesis**
When i tried to use azure-cli for the first time after installation, I got the following error, which is obviously a python error. I'm using python3, but **az** command is using python2 it seems

**The error that I got**
Missing parentheses in call to 'print'. Did you mean print("Content-type:text/html\r\n\r\n")? (html.py, line 3)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 263, in execute
    self.help.show_welcome(subparser)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/help.py", line 656, in show_welcome
    help_file = self.group_help_cls(self, '', parser)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/help.py", line 219, in __init__
    child.load(options)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/help.py", line 163, in load
    description = getattr(options, 'description', None)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/parser.py", line 216, in __getattribute__
    if callable(self._description) else self._description
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 457, in default_description_loader
    op = handler or self.get_op_handler(operation)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 496, in get_op_handler
    op = import_module(mod_to_import)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/command_modules/find/custom.py", line 16, in <module>
    from azure.cli.core.api import get_config_dir
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/api.py", line 11, in <module>
    from ._profile import load_subscriptions
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/_profile.py", line 16, in <module>
    from six.moves import BaseHTTPServer
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 93, in <module>
    import html
  File "/Users/udayabharathi_thiaga/Documents/sslcheckexpire/html.py", line 3
    print "Content-type:text/html\r\n\r\n"
                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Content-type:text/html\r\n\r\n")?

**Environment summary**
I'm using macOS High Sierra, I used brew to install azure-cli.

**Comment by tjprescott** [comment] 2019-02-22 17:13
Duplicate of #7367. Please reference that issue for the workaround.

**Comment by tjprescott** [comment] 2019-02-22 17:14
Please see referenced issue for workaround.

**Closed by tjprescott** 2019-02-22 17:13 UTC
