### ISSUE TITLE
Budget is not iterable

### ISSUE THREAD

**Issue by brucedkyle** [Azure/azure-cli#8927] opened 2019-03-29 21:17 UTC
When I tried the following command:

az consumption budget create --amount 2200 --budget-name $mybudgetname --category usage --end-date  2019-06-30 --start-date 2019-03-26 --time-grain monthly --resource-group $resourcegroup_name --subscription $env:SUBSCR
IPTION_ID

I received the following error:

'Budget' object is not iterable
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 366, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-consumption\azure\cli\command_modules\consumption\_exception_handler.py", line 17, in consumption_exception_handler
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-consumption\azure\cli\command_modules\consumption\custom.py", line 111, in cli_consumption_create_budget
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-mgmt-consumption\azure\mgmt\consumption\operations\budgets_operations.py", line 265, in create_or_update
TypeError: 'Budget' object is not iterable

Am I missing a step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d0e4fd3-7458-6d8e-b4ae-aefcdde52409
* Version Independent ID: 9a13720a-356a-6631-f4a0-f9aecd80f92e
* Content: [az consumption budget](https://docs.microsoft.com/en-us/cli/azure/consumption/budget?view=azure-cli-latest#az-consumption-budget-create)
* Content Source: [src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/_help.py)
* Service: **consumption**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment] 2019-03-29 22:47
This is a duplicate of #7775

**Closed by tjprescott** 2019-03-29 22:47 UTC
Labels: Consumption, bug
