### ISSUE TITLE
postgres flexible-server create doesn't use an existing vnet if it's in a different resource group

### ISSUE THREAD

**Issue by larslind** [Azure/azure-cli#17883] opened 2021-04-26 17:41 UTC
When running 
`az postgres flexible-server create`
and supplying --vnet and --subnet parameters for a vnet that is deployed in a different resource group, the command tries to create a new vnet and subnet in the same resource group as the server.

In many enterprise environments, the management of network resources are handled by a different team from the one that deploys application resources. This bug was discovered because the CI/CD pipeline service principal that is used to create the PostgreSQL server didn't have permissions to create a vnet. I've reproduced the issue below in my own subscription, where I do have the necessary permissions, so the vnet gets created in the server resource group rather than using the existing one.

Adding a new parameter, --vnet-resource-group, and using this for the vnet would solve this problem.

**Errors:**
Doesn't use existing vnet.

## To Reproduce:
az group create -l westeurope -n postgres-test-server-rg
az group create -l westeurope -n postgres-test-vnet-rg
az network vnet create --resource-group postgres-test-vnet-rg --name postgres-vnet --address-prefix 10.0.0.0/16 --subnet-name postgres-subnet --subnet-prefix 10.0.0.0/24
az postgres flexible-server create -l westeurope -n larslindpostgrestestserver -g postgres-test-server-rg --subnet postgres-subnet --vnet postgres-vnet
OUTPUT:
Command group 'postgres flexible-server' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Checking the existence of the resource group 'postgres-test-server-rg'...
Resource group 'postgres-test-server-rg' exists ? : True
You have supplied a Vnet and Subnet name. Verifying its existence...
Creating new Vnet "postgres-vnet" in resource group "postgres-test-server-rg"
Creating new Subnet "postgres-subnet" in resource group "postgres-test-server-rg"
Creating PostgreSQL Server 'larslindpostgrestestserver' in group 'postgres-test-server-rg'...

## Expected Behavior
Existing vnet and subnet would be used even if the vnet is in a different resource group.

## Environment Summary
```
Linux-4.15.0-1113-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.22.0 *

Extensions:
resource-graph 0.1.8
azure-iot 0.9.2
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by yonzhan** [comment] 2021-04-27 00:03
route to service team

**Comment by larslind** [comment] 2021-04-27 08:17
A better solution to this would be to just use Resource ID for the --vnet parameter rather than name.

**Comment by larslind** [comment] 2021-04-27 12:18
I tried creating with the --vnet = <Resource ID>, but it actually tells me to use names:

```
az postgres flexible-server create -l westeurope -n larslindpostgrestestserver -g postgres-test-server-rg --subnet postgres-subnet --vnet /subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet-rg/providers/Microsoft.Network/virtualNetworks/postgres-vnet
Command group 'postgres flexible-server' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Checking the existence of the resource group 'postgres-test-server-rg'...
Resource group 'postgres-test-server-rg' exists ? : True
If you pass both --vnet and --subnet, consider passing names instead of IDs.
```

**Comment by larslind** [comment] 2021-04-27 15:48
I know this hasn't been triaged yet, but wanted to flag it to @DaeunYim given your recent commit to [this code](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py).
Currently this is a blocking issue for our project, so would appreciate if someone could take a look at it. Please contact me directly if you want more details.

**Comment by DaeunYim** [comment] 2021-04-27 15:59
Hi @larslind,
You are correct. When using vnet/subnet from different resource group or subscription, you need to provide vnet or subnet id. In your case, since you want to use existing subnet, could you try with --subnet subnetid parameter? Sorry for your inconvenience, and let me work on improve this user experience. Thanks a lot for reaching out to us and let me know the result.

**Comment by larslind** [comment] 2021-04-27 16:28
Hi @DaeunYim  - yes, I did try that and it also didn't work:

```
az postgres flexible-server create -l westeurope -n larslindpostgrestestserver -g postgres-test-server-rg --subnet /subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet-rg/providers/Microsoft.Network/virtualNetworks/postgres-vnet/subnets/postgres-subnet --vnet /subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet-rg/providers/Microsoft.Network/virtualNetworks/postgres-vnet
Command group 'postgres flexible-server' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Checking the existence of the resource group 'postgres-test-server-rg'...
Resource group 'postgres-test-server-rg' exists ? : True
If you pass both --vnet and --subnet, consider passing names instead of IDs.
```

**Comment by DaeunYim** [comment] 2021-04-27 16:32
Oh I mean only subnet not vnet.

**Comment by larslind** [comment] 2021-04-27 16:34
That works, thanks! I think it would be a good idea to clarify this in the --help and docs...

**Comment by DaeunYim** [comment] 2021-04-27 16:37
Yeah, I totally agree. Let me work on updating the help doc. Thanks for reporting the issue and let me know if you need anything else!

**Comment by larslind** [comment] 2021-04-28 08:58
Hi @DaeunYim. We've been doing some further testing and came across additional issues with this scenario that my original test environment didn't capture. The situation is that the user/service principal creating the PostgreSQL Flexible Server only has read access to the resource group containing the VNet. Also, the actual VNet address prefix obviously isn't 10.0.0.0/16. To reproduce the issue I've re-created the VNet:

`az network vnet create --resource-group postgres-test-vnet-rg --name postgres-vnet --address-prefix 172.20.0.0/16 --subnet-name postgres-subnet --subnet-prefix 172.20.0.0/24`

I've then added a user "postgresadmin" with the following role assignments:

```
Role		Resource Name		Resource Type	Assigned To
Reader		postgres-test-vnet-rg	Resource Group	postgresadmin
Contributor	postgres-test-server-rg	Resource Group	postgresadmin
```

When logged in as postgresadmin you  then get the following error:

```
az postgres flexible-server create -l westeurope -n larslindpostgrestestserver -g postgres-test-server-rg --subnet /subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet-rg/providers/Microsoft.Network/virtualNetworks/postgres-vnet/subnets/postgres-subnet
Command group 'postgres flexible-server' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Checking the existence of the resource group 'postgres-test-server-rg'...
Resource group 'postgres-test-server-rg' exists ? : True
You have supplied a Subnet ID. Verifying its existence...
Using existing Vnet "postgres-vnet" in resource group "postgres-test-vnet-rg"
Adding address prefix 10.0.0.0/16 to Vnet postgres-vnet
(AuthorizationFailed) The client 'postgresadmin@<AAD domain>.onmicrosoft.com' with object id '<User GUID>' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/write' over scope '/subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet-rg/providers/Microsoft.Network/virtualNetworks/postgres-vnet' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

There are two issues here:
1. It shouldn't be trying to add 10.0.0.0/16 to the VNet
2. It shouldn't require the user to have write access to the VNet

**Comment by larslind** [comment] 2021-04-28 12:28
Hi @DaeunYim. I've just tried it through the portal as well, and get a different error message. Unfortunately it's not possible to copy the message, so below is an OCR of a screenshot with identifying information redacted. This suggests that using an existing VNet requires write access to the network resources, which would be an issue in our scenario.

```
Additional details from the underlying API that might be 
helpful: Deployment failed with multiple errors: 
'Authorization failed far template resource 
'privateDnszone_805053ad-c4co-4751-g3c2- 
ffe4e753e045' of type 'Microsoft.Resources/deployments•. 
The client 
'postgresadmin@<AAD tenant domain>.onmicrosoft.com' 
with object id '<User GUID>' 
does not have permission to perform action 
'Microsoft.Resources/deployments/write' at scope 
'/subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet- 
rg/providers/Microsoft.Resources/deployments/privateD... 
c4cO-4751-g3c2-ffe4e753e045'.:Authorization failed for 
template resource •virtualNetwork_805053ad-c4cO-4751- 
g3c2-ffe4e753e043' of type 
'Microsoft.Resources/deployments•. The client 
postgresadmin@<AAD tenant domain>.onmicrosoft.com' 
with object id '<User GUID>' 
does not have permission to perform action 
'Microsoft.Resources/deployments/write' at scope 
'/subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet- 
rg/providers/Microsoft.Resources/deployments/virtualN... 
c4cO-4751-g3c2-ffe4e753e043'.:Authorization failed for 
template resource •virtualNetworkLlnk_805053ad-c4cO- 
4751-93c2-ffe4e753e044' of type 
'Microsoft.Resources/deployments•. The client 
'postgresadmin@<AAD tenant domain>.onmicrosoft.com' 
with object id '<User GUID>' 
does not have permission to perform action 
'Microsoft.Resources/deployments/write' at scope 
'/subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet- 
rg/providers/Microsoft.Resources/deployments/virtualN... 
c4cO-4751-g3c2-ffe4e753e044'.:Authorization failed for 
template resource 
'larslindpostgrestest.private.postgres.database.azure.com' 
of type 'Microsoft.Network/privateDnsZones'. The client 
'postgresadmin@<AAD tenant domain>.onmicrosoft.com' 
with object id '<User GUID>' 
does not have permission to perform action 
'Microsoft.Network/privateDnsZones/write' at scope 
'/subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet- 
rg/providers/Microsoft.Network/privateDnsZo nes/la rslin 
failed for template resource 'postgres-vnet/postgres- 
subnet' of type 
'Microsoft.Network/virtualNetworks/subnets'. The client 
'postgresadmin@<AAD tenant domain>.onmicrosoft.com' 
with object id '<User GUID>' 
does not have permission to perform action 
'Microsoft.Network/virtualNetworks/subnets/write• at 
scope '/subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet- 
rg/providers/Microsoft.Network/vi rtualNetwo rks/postgr.. 
failed for 
template resource 
```

**Comment by DaeunYim** [comment] 2021-04-28 18:27
@larslind 
> 1. It shouldn't be trying to add 10.0.0.0/16 to the VNet
I was able to reproduce error and the fix will be checked it today and released in a week.
Thanks a lot for reporting. 

> It shouldn't require the user to have write access to the VNet
I think causes are,, 
1) 'reader' role didn't allow you to add address to vnet but the CLI was trying to do this. I think once the fix is in, the error won't happen. (This won't be problem in portal) 
2) Additionally, we create private DNS zone for any vnet servers. Let me bring this up with the relevant team and get back to you

**Comment by larslind** [comment] 2021-04-29 10:31
Hi @DaeunYim. I tried giving the user the "Private DNS Zone Contributor" role, but the PostgreSQL Flexible Server creation still fails. The subnet has already been delegated to Microsoft.DBforPostgreSQL/flexibleServers, but I'm wondering if that's what it's also trying to do?

This is the error message:

```
{
    "status": "Failed",
    "error": {
        "code": "LinkedAuthorizationFailed",
        "message": "The client 'postgresadmin@<AAD domain name>.onmicrosoft.com' with object id <User GUI>' has permission to perform action 'Microsoft.DBforPostgreSQL/flexibleServers/write' on scope '/subscriptions/<Subscription GUID>/resourcegroups/postgres-test-server-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/larslindtestpgsql'; however, it does not have permission to perform action 'write' on the linked scope(s) '/subscriptions/<Subscription GUID>/resourceGroups/postgres-test-vnet-rg/providers/Microsoft.Network/virtualNetworks/postgres-vnet/subnets/postgres-subnet' or the linked scope(s) are invalid."
    }
}
```

**Comment by DaeunYim** [comment] 2021-04-29 23:20
@larslind

I checked with the portal team that we add storage endpoint to the subnet for restoring purpose. This operation will be removed after 5/3 in the portal and June train for CLI.

**Comment by larslind** [comment] 2021-05-05 14:46
@DaeunYim I've been testing this over the past couple of days in the portal and with both ARM template and Terraform and they all fail with the same error message:
```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "LinkedAuthorizationFailed",
      "message": "The client 'postgresadmin@<AAD domain name>.onmicrosoft.com' with object id '<User GUI>' has permission to perform action 'Microsoft.DBforPostgreSQL/flexibleServers/write' on scope '/subscriptions/<Subscription GUI>/resourcegroups/postgres-test-server-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/<Server Name>'; however, it does not have permission to perform action 'write' on the linked scope(s) '/subscriptions/<Subscription GUI>/resourceGroups/postgres-test-vnet-rg/providers/Microsoft.Network/virtualNetworks/postgres-vnet/subnets/postgres-subnet' or the linked scope(s) are invalid."
    }
  ]
}
```

**Closed** 2021-05-07 15:55 UTC
Labels: PostgreSQL, Service Attention
