### ISSUE TITLE
az interactive fails with No module named 'prompt_toolkit.interface' ERROR

### ISSUE THREAD

**Issue by hepais-microsoft** [Azure/azure-cli#10133] opened 2019-08-02 17:27 UTC
Hello,
I'm running 'az interactive' to install the Interactive shell and it is failing with the 
"No module named 'prompt_toolkit.interface" I couldn't find a solution to this...
I also tried installing the AZ CLI on my Windows 10 machine and got the same error.

Thanks

**Comment by tjprescott** [comment] 2019-08-02 17:29
Duplicate of #10088

**Closed by tjprescott** 2019-08-02 17:29 UTC

**Comment by hepais-microsoft** [comment] 2019-08-02 17:47
I’m sorry but the fix doesn’t work:

On the local Windows 10 PowerShell – there is no PIP command, hence I can’t “pip uninstall”…

On the Azure BASH Shell, the pip uninstall generates a warning:
WARNING: Skipping prompt-toolkit as it is not installed.


Therefore the proposed fix does not work. IT IS NOT FIXED.
﻿ --
Hermann Fernandes Pais
Category Director, Data Management
Azure Commercial Marketplace
Cloud Commercial Communities
Office: +1 (425) 7065111
Mobile: +1 (425) 628-9965
Hermann.Pais@microsoft.com<mailto:Hermann.Pais@microsoft.com>
9 AM - 6 PM
[Microsoft]
Helpful links:
Marketplace Publisher Guide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fmarketplace%2Fmarketplace-publishers-guide&data=02%7C01%7CHermann.Pais%40microsoft.com%7C79d5f8b93dd140c239c808d71094411d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636996101240186328&sdata=%2Fv0phmaR5sae%2FiuafeetWUY2tL3JAqsH9k236cvD6pM%3D&reserved=0>
Comparing AppSource and Azure Marketplace<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fmarketplace%2Fcomparing-appsource-azure-marketplace&data=02%7C01%7CHermann.Pais%40microsoft.com%7C79d5f8b93dd140c239c808d71094411d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636996101240196325&sdata=eKUjKLr86l5YMiSBCgwm9AF%2FvFXrZ8ft5pGiBevp9eE%3D&reserved=0>
Become a Marketplace Publisher<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fmarketplace%2Fbecome-publisher&data=02%7C01%7CHermann.Pais%40microsoft.com%7C79d5f8b93dd140c239c808d71094411d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636996101240196325&sdata=O8HQK0twjYivtuHjuZlVSFEiSICrqe5NWT5g8AZwuU0%3D&reserved=0>
Microsoft Marketplace Partner Community Forum<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoftpartnercommunity.com%2Ft5%2FMarketplace%2Fbd-p%2F2222&data=02%7C01%7CHermann.Pais%40microsoft.com%7C79d5f8b93dd140c239c808d71094411d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636996101240206318&sdata=j%2FfWz4wCv4oNcFm3u6pJsDAc5oQM6NcMQPZHoFG7DpY%3D&reserved=0>

﻿
One Microsoft Way, Redmond, WA 98052 USA | Privacy Statement<http://go.microsoft.com/fwlink/?LinkId=248681>
