### ISSUE TITLE
"az webapp config snapshot restore" CLI command not working when restoring the snapshot to deployment slot

### ISSUE THREAD

**Issue by SAIKUMAR-MANDEPUDI** [Azure/azure-cli#23705] opened 2022-08-29 13:49 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
 
az webapp config snapshot restore --time <snapshot timestamp> --name <name of the web app> --resource-group <name of the resource group> --restore-content-only --slot <name of the slot> --source-name <name of the webapp to retrieve snapshot from> --source-resource-group <source resource group name>

**Describe the bug**

I am trying to restore the snapshot of an App service to the deployment slot of the same App service using the CLI command, and it fails. Below is the CLI command used
az webapp config snapshot restore --time <snapshot timestamp> --name <name of the web app> --resource-group <name of the resource group> --restore-content-only --slot <name of the slot> --source-name <name of the webapp to retrieve snapshot from> --source-resource-group <source resource group name>

**Full error message:**
The command failed with an unexpected error. Here is the traceback:
('Unable to build a model: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'")), DeserializationError: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'")))
Traceback (most recent call last):
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1436, in _deserialize
 found_value = key_extractor(attr, attr_desc, data)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1201, in rest_key_case_insensitive_extractor
 return attribute_key_case_insensitive_extractor(key, None, working_data)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1230, in attribute_key_case_insensitive_extractor
 return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 622, in body
 data = deserializer._deserialize(data_type, data)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1454, in _deserialize
 raise_with_traceback(DeserializationError, msg, err)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
 raise error.with_traceback(exc_traceback)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1436, in _deserialize
 found_value = key_extractor(attr, attr_desc, data)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1201, in rest_key_case_insensitive_extractor
 return attribute_key_case_insensitive_extractor(key, None, working_data)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1230, in attribute_key_case_insensitive_extractor
 return data.get(found_key)
azure.core.exceptions.DeserializationError: ("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
 cmd_result = self.invocation.execute(args)
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
 raise ex
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
 results.append(self._run_job(expanded_arg, cmd_copy))
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
 result = cmd_copy(params)
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
 return self.handler(*args, **kwargs)
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
 return op(**command_args)
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 2164, in restore_snapshot
 return client.web_apps.begin_restore_snapshot_slot(resource_group_name, name, request, slot)
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
 return func(*args, **kwargs)
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/web/v2022_03_01/operations/_web_apps_operations.py", line 44098, in begin_restore_snapshot_slot
 raw_result = self._restore_snapshot_slot_initial( # type: ignore
 File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/web/v2022_03_01/operations/_web_apps_operations.py", line 44017, in _restore_snapshot_slot_initial
 _json = self._serialize.body(restore_request, 'SnapshotRestoreRequest')
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 624, in body
 raise_with_traceback(
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
 raise error.with_traceback(exc_traceback)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 622, in body
 data = deserializer._deserialize(data_type, data)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1454, in _deserialize
 raise_with_traceback(DeserializationError, msg, err)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
 raise error.with_traceback(exc_traceback)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1436, in _deserialize
 found_value = key_extractor(attr, attr_desc, data)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1201, in rest_key_case_insensitive_extractor
 return attribute_key_case_insensitive_extractor(key, None, working_data)
 File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1230, in attribute_key_case_insensitive_extractor
 return data.get(found_key)
azure.core.exceptions.SerializationError: ('Unable to build a model: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'")), DeserializationError: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'")))

**To Reproduce**

Reproduce the scenario by restoring the snapshot of the App service to the deployment slot of same App service. Use the below command.
az webapp config snapshot restore --time <snapshot timestamp> --name <name of the web app> --resource-group <name of the resource group> --restore-content-only --slot <name of the slot> --source-name <name of the webapp to retrieve snapshot from> --source-resource-group <source resource group name>

I have tried multiple times but end up getting the same error message.

The same command works perfectly when no slot is used. But my requirement is to restore the snapshot to the deployment slot by using CLI command.

**Expected behavior**

I expected that the snapshot restore happens to the slot. This works when using the portal but fails only when using CLI command

**Environment summary**

az --version
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
ai-examples                        0.2.5
azure-cli-ml                      1.41.0
ssh                                1.1.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/bin/python3.9'
Extensions directory '/home/saikumar/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.13 (main, Jul 13 2022, 05:35:38) 
[GCC 11.2.0]

I am using cloud shell in Azure portal to execute the CLI command.

**Additional context**

**Comment by yonzhan** [comment] 2022-08-29 14:12
route to CXP team

**Comment by SAIKUMAR-MANDEPUDI** [comment] 2022-08-31 13:01
Hello Team. Please let me know if we have any update on this.

**Comment by SaurabhSharma-MSFT** [comment] 2022-08-31 23:28
@SAIKUMAR-MANDEPUDI I am able to reproduce this and currently investigating this issue.

**Comment by SaurabhSharma-MSFT** [comment] 2022-09-28 16:27
@panchagnula Can you please help here.

**Comment by SAIKUMAR-MANDEPUDI** [comment] 2022-10-08 12:40
Hello Team. Can you please provide an update on this issue?

**Comment by SAIKUMAR-MANDEPUDI** [comment] 2022-10-25 12:38
Hello @panchagnula . Hope you are doing well. Could you please provide an update on this? Please provide me an ETA to know when this can be fixed. I am looking forward to hearing from you on this. Thanks in advance.

**Comment by seligj95** [comment] 2022-12-09 16:22
This is not a CLI issue. This is a known bug in the API that is being addressed. Backup restores to deployment slots will fail. Will update the thread when an ETA is available.

**Comment by seligj95** [comment] 2022-12-21 17:43
@SAIKUMAR-MANDEPUDI - can you please update to the latest CLI (version 2.43.0 is currently the latest) and try again? I've tested and the fix seems to be implemented

**Comment by SAIKUMAR-MANDEPUDI** [comment] 2022-12-22 02:47
Hello @seligj95 I have tested it again in the CLI with version 2.43.0 and the snapshot restore was successful. I have checked couple of times and it seems to be fixed now. Thanks for the update.

**Comment by seligj95** [comment] 2022-12-22 21:10
Thanks for the confirmation. Closing this issue.

**Closed by seligj95** 2022-12-22 21:10 UTC
Labels: bug, Web Apps, Service Attention, customer-reported, Auto-Assign, app-service-backup-restore
