### ISSUE TITLE
az acs kubernetes get-credentials throws inconsistent error

### ISSUE THREAD

**Issue by wesyao** [Azure/azure-cli#5883] opened 2018-03-22 00:27 UTC
The issue is inconsistent and does not occur every time. The cluster deploys successfully.

Once I run get credentials again, I am able to access my cluster with kubectl.

### Repro Steps

Deploy Cluster
```
az acs create --orchestrator-type=kubernetes --generate-ssh-keys --resource-group wesyao-kube-wesley --name=wesyao-kube-wesley --dns-prefix=wesyao-kube-wesley --service-principal htt
```

Get Credentials
```
az acs kubernetes get-credentials --resource-group wesyao-kube-wesley --name wesyao-kube-wesley
```

Error message:
```
No existing session
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 418, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 920, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 941, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/acs_client.py", line 72, in secure_copy
    ssh.connect(host, username=user, pkey=pkey, sock=proxy)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/paramiko/client.py", line 691, in _auth
    self._transport.auth_publickey(username, key))
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/paramiko/transport.py", line 1440, in auth_publickey
    raise SSHException('No existing session')
paramiko.ssh_exception.SSHException: No existing session
```

---

#### Operating System
``` OSX```

#### az CLI version
```
az --version
azure-cli (2.0.29)

acr (2.0.22)
acs (2.0.28)
advisor (0.5.0)
appservice (0.1.29)
backup (1.0.7)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.29)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.11)
eventhubs (0.1.0)
extension (0.0.10)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.17)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.17)
monitor (0.1.3)
network (2.0.25)
nspkg (3.0.2)
profile (2.0.20)
rdbms (0.1.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.25)
role (2.0.20)
servicebus (0.1.0)
servicefabric (0.0.11)
sql (2.0.23)
storage (2.0.27)
vm (2.0.28)

Python location '/Users/wesyao/anaconda3/bin/python3.6'
Extensions directory '/Users/wesyao/.azure/cliextensions'

Python (Darwin) 3.6.2 |Anaconda custom (x86_64)| (default, Sep 21 2017, 18:29:43)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by mboersma** [comment] 2018-05-10 20:57
I can't reproduce this with `az acs`. The symptoms are really curious.

Is it possible your ~/.kube/config file is being edited or replaced between your `get-credentials` commands? That would explain why running that command seems to fix things.

@wesyao please let me know if you've found any more specific about how to reproduce this.

**Comment by wesyao** [comment] 2018-05-17 16:45
@mboersma I double checked again. My config file was not opened.

**Comment by yugangw-msft** [comment] 2019-07-27 00:52
closing as `az acs` is deprecating

**Closed by yugangw-msft** 2019-07-27 00:52 UTC
Labels: ACS, Service Attention
