### ISSUE TITLE
The ID token already expires. Make sure your computer's time and time zone are both correct

### ISSUE THREAD

**Issue by AnimogM** [Azure/azure-cli#23300] opened 2022-07-22 02:09 UTC
I am trying to login using 'az login' and am getting the followin error:

The command failed with an unexpected error. Here is the traceback:
9. The ID token already expires. Make sure your computer's time and time zone are both correct. Current epoch = 1658484126.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1658455016,
  "nbf": 1658455016,
  "exp": 1658458916,
  "aio": "AYQAe/8TAAAA9evFf+svWipZPwo8jFVKroxcMyD8/lDo/vMEJygkC3mtw4IwGDlE3OL6euZwBTgkFmSAjnMxHept4P7y0QdIf7RRTXLFqSRQykYuVmORXp6AWvG/Kjpo7R2cq1o2SK2tq2C5WLnkKa3SYCVjXYej4GJkCq9KAQMexaotM5iPf6w=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "138c428e6fec4226eb9f8d3ca860af9151da0899930be0d980dbc218738697f2",
  "preferred_username": "gominamaryam@gmail.com",
  "rh": "0.AXkAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAIc.",
  "sub": "ZUTSX3yss_FHs0du-_0bOG6Os_C-Iea96puZrwwk2EI",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "xN3avRWFQEmRlvwtRL4wAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 141, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1608, in acquire_token_interactive
    response = _clean_up(self.client.obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 281, in obtain_token_by_browser
    return super(Client, self).obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
    return self._obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
    return self.obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 138, in obtain_token_by_auth_code_flow
    return super(_ClientWithCcsRoutingInfo, self).obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
    result = super(Client, self).obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
    return self._obtain_token_by_authorization_code(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 789, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 599, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 310, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 153, in __add
    decode_id_token(id_token, client_id=event["client_id"])
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    raise RuntimeError("%s Current epoch = %s.  The id_token was: %s" % (
RuntimeError: 9. The ID token already expires. Make sure your computer's time and time zone are both correct. Current epoch = 1658484126.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1658455016,
  "nbf": 1658455016,
  "exp": 1658458916,
  "aio": "AYQAe/8TAAAA9evFf+svWipZPwo8jFVKroxcMyD8/lDo/vMEJygkC3mtw4IwGDlE3OL6euZwBTgkFmSAjnMxHept4P7y0QdIf7RRTXLFqSRQykYuVmORXp6AWvG/Kjpo7R2cq1o2SK2tq2C5WLnkKa3SYCVjXYej4GJkCq9KAQMexaotM5iPf6w=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "138c428e6fec4226eb9f8d3ca860af9151da0899930be0d980dbc218738697f2",
  "preferred_username": "gominamaryam@gmail.com",
  "rh": "0.AXkAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAIc.",
  "sub": "ZUTSX3yss_FHs0du-_0bOG6Os_C-Iea96puZrwwk2EI",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "xN3avRWFQEmRlvwtRL4wAA",
  "ver": "2.0"
}

**Comment by bebound** [comment] 2022-07-22 02:51
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by bebound** 2022-07-22 02:51 UTC
Labels: Account, customer-reported, Auto-Assign
