### ISSUE TITLE
Azure CLI Interactive on a Azure VM 

### ISSUE THREAD

**Issue by mountainbrother** [Azure/azure-cli#9102] opened 2019-04-14 08:54 UTC
Get an exepction an an Azure VM
az 2.062 works but if i try to install an extenstion like the interactive i run in this error i never ever seen bevor:
Try to run the cmd also as an admin, repair the az installation all with no sucess.
Exception in thread Thread-1:
Traceback (most recent call last):
File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in bootstrap_inner
self.run()
File "C:\Users\aatv.azure\cliextensions\interactive\azext_interactive\azclishell\threads.py", line 21, in run
FreshTable(self.shell).dump_command_table(self.shell)
File "C:\Users\aat.azure\cliextensions\interactive\azext_interactive\azclishell_dump_commands.py", line 88, in dump_command_table
main_loader.load_arguments(None)-----------------------------------------------------------------------------------
File "C:\Users\aat.azure\cliextensions\interactive\azext_interactive\azclishell_dump_commands.py", line 49, in load_arguments--------------------------------------------------------------------------------------------------------
command.load_arguments()
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands_init.py", line 130, in load_arguments : use commands outside the application
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\commands.py", line 89, in load_arguments
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core_init_.py", line 454, in default_arguments_loader : do a step by step tutorial of example
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core_init_.py", line 494, in get_op_handler : set a scope, and scopes can be chained with spaces
File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import Hit [enter] to refresh
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "", line 678, in exec_module
File "", line 219, in _call_with_frames_removed
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-servicefabric\azure\cli\command_modules\servicefabric\custom.py", line 43, in 
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\models.py", line 10, in 
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30_init_.py", line 12, in 
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\compute_management_client.py", line 16, in 
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations_init_.py", line 12, in 
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\disks_operations.py", line 18, in 
File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\compute\v2018_09_30\models_init_.py", line 56, in 
from ._compute_management_client_enums import StorageAccountTypes
ImportError: cannot import name 'StorageAccountTypes'

**Comment by mountainbrother** [comment] 2019-04-14 11:00
get the same error on my a new physical machine / also with the edge msi 
there is something wrong !

**Comment by adewaleo** [comment] 2019-04-16 17:10
Please can you try to give us more context. What scenario and what commands are actually failing? @mountainbrother 

Please provide the information requested in the bug report template:


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by mountainbrother** [comment] 2019-04-17 15:05
Describe the bug
I download the version 2.062 on several machines Physical or VM´s on azure.
I can install the cli and it works. 
If i start the az interactive it runs always the same error. 

A clear and concise description of what the bug is.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\guent\.azure\cliextensions\interactive\azext_interactive\azclishell\threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "C:\Users\guent\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 88, in dump_command_table
    main_loader.load_arguments(None)
  File "C:\Users\guent\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 49, in load_arguments
    command.load_arguments()
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-cli-core\azure\cli\core\commands\__init__.py", line 130, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\knack\knack\commands.py", line 89, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-cli-core\azure\cli\core\__init__.py", line 454, in default_arguments_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-cli-core\azure\cli\core\__init__.py", line 494, in get_op_handler
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module---------------------------------------------------------------------------------
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-cli-servicefabric\azure\cli\command_modules\servicefabric\custom.py", line 43, in <module>                                                                      *
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-mgmt-compute\azure\mgmt\compute\models.py", line 10, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\__init__.py", line 12, in <module>----
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\compute_management_client.py", line 16, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\__init__.py", line 12, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qor58sf1\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\disks_operations.py", line 18, in <module>              : use commands outside the application
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\compute\v2018_09_30\models\__init__.py", line 56, in <module>
    from ._compute_management_client_enums import StorageAccountTypes
ImportError: cannot import name 'StorageAccountTypes'ial of example
$                           : get the exit code of the previous command
%%[cmd]                     : set a scope, and scopes can be chained with spaces
%% ..                       : go back a scope
To Reproduce
Steps to reproduce the behavior.
az interactive with version 2.062

Expected behavior
that it works like the versions bevor

Environment summary
MSI installer from azure cli
Windows 10 Pro

**Comment by adewaleo** [comment] 2019-04-17 21:07
@mountainbrother I was able to reproduce it. 

I will be closing this as a duplicate of #9133

**Closed by adewaleo** 2019-04-17 21:07 UTC
Labels: Compute-cli, Needs Triage, bug
