### ISSUE TITLE
item-name not found

### ISSUE THREAD

**Issue by hmi12** [Azure/azure-cli#14983] opened 2020-08-31 04:01 UTC
## Describe the bug

**Command Name**
`az backup protection backup-now`

**Errors:**
```
Item not found. Please provide a valid item_name.
Traceback (most recent call last):
Temp\pip-install-1o1fsnhi\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-1o1fsnhi\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\backup\custom_base.py, ln 96, in backup_now
azure\cli\command_modules\backup\custom_help.py, ln 104, in validate_item
azure\cli\command_modules\backup\custom_help.py, ln 113, in validate_object
ValueError: Item not found. Please provide a valid item_name.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protection backup-now --resource-group test_recovery_vault --vault-name testvault --container-name master01 --item-name master01 --retain-until 18-10-2020 --backup-management-type AzureWorkload`

## Environment Summary
```
Windows-8.1-6.3.9600-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.81 *

```
## Additional Context

The recovery vault and item-names are in different resource groups.

**Comment by yonzhan** [comment] 2020-08-31 05:17
backup

**Comment by hmi12** [comment] 2020-08-31 07:05
@pvrk could you please advise somthing?

**Comment by pvrk** [comment] 2020-09-03 12:01
@hmi12 : Examples are provided [here](https://docs.microsoft.com/azure/backup/tutorial-sap-hana-backup-cli#trigger-an-on-demand-backup) for SAP HANA. You can also use `az backup item list' to get items and `az backup item show` commands to view a particular database. The same parameters used for these commands will work for any item-name or container-name params in other commands.

**Comment by hmi12** [comment] 2020-09-04 14:53
Thank you.  
How to specify the resource group of the backup item(VMs)?  because the recovery vault and VMs are in different resource group.

**Comment by pvrk** [comment] 2020-09-07 13:06
@hmi12 : Resource group of the VM is only required during enabling protection or first-time-backup. Once the VM is backed up, the backup item name is part of vault and hence doesn't require the resource group to be mentioned again.

In short, you don't require RG of the VM to list or show backup items.

Hope this helps.

**Comment by mepand** [comment] 2020-09-22 06:22
@hmi12 Just wanted to check if the issue is fixed for you.

**Comment by mepand** [comment] 2020-10-14 07:47
As there is no further action pending from the PG side, closing this issue, @hmi12 : Please feel free to reopen the issue incase its not yet fixed for you.

**Closed by mepand** 2020-10-14 07:47 UTC
Labels: Recovery Services Backup, Service Attention, customer-reported
