### ISSUE TITLE
Fail of cli when we execute some commands in parallel

### ISSUE THREAD

**Issue by fbejarano** [Azure/azure-cli#3452] opened 2017-05-25 13:34 UTC
### Description
**Outline the issue here:**

Hi

I am executing some commands of cli in parallel. In some cases the commands fails and the cli does not correctly run anymore.

I have been investigating and sometimes the execution of cli commands change de file `${home}/.azure/cloud.configs` changing the order of blocks ¿¿?? so I have deleted de .azure directory and execute login and all is ok. Then I have repeat de execution in parallel of many commands, previously, I have copied the original file and then I have done a diff between both and this is the result

```
/.azure$ diff clouds.config clouds.config_ok 
1,26d0
< [AzureGermanCloud]
< endpoint_management = https://management.core.cloudapi.de/
< endpoint_resource_manager = https://management.microsoftazure.de
< endpoint_sql_management = https://management.core.cloudapi.de:8443/
< endpoint_batch_resource_id = https://batch.cloudapi.de/
< endpoint_gallery = https://gallery.cloudapi.de/
< endpoint_active_directory = https://login.microsoftonline.de
< endpoint_active_directory_resource_id = https://management.core.cloudapi.de/
< endpoint_active_directory_graph_resource_id = https://graph.cloudapi.de/
< suffix_storage_endpoint = core.cloudapi.de
< suffix_keyvault_dns = .vault.microsoftazure.de
< suffix_sql_server_hostname = .database.cloudapi.de
< 
< [AzureUSGovernment]
< endpoint_management = https://management.core.usgovcloudapi.net/
< endpoint_resource_manager = https://management.usgovcloudapi.net/
< endpoint_sql_management = https://management.core.usgovcloudapi.net:8443/
< endpoint_batch_resource_id = https://batch.core.usgovcloudapi.net/
< endpoint_gallery = https://gallery.usgovcloudapi.net/
< endpoint_active_directory = https://login.microsoftonline.com
< endpoint_active_directory_resource_id = https://management.core.usgovcloudapi.net/
< endpoint_active_directory_graph_resource_id = https://graph.windows.net/
< suffix_storage_endpoint = core.usgovcloudapi.net
< suffix_keyvault_dns = .vault.usgovcloudapi.net
< suffix_sql_server_hostname = .database.usgovcloudapi.net
< 
53a28,53
> 
> [AzureUSGovernment]
> endpoint_management = https://management.core.usgovcloudapi.net/
> endpoint_resource_manager = https://management.usgovcloudapi.net/
> endpoint_sql_management = https://management.core.usgovcloudapi.net:8443/
> endpoint_batch_resource_id = https://batch.core.usgovcloudapi.net/
> endpoint_gallery = https://gallery.usgovcloudapi.net/
> endpoint_active_directory = https://login.microsoftonline.com
> endpoint_active_directory_resource_id = https://management.core.usgovcloudapi.net/
> endpoint_active_directory_graph_resource_id = https://graph.windows.net/
> suffix_storage_endpoint = core.usgovcloudapi.net
> suffix_keyvault_dns = .vault.usgovcloudapi.net
> suffix_sql_server_hostname = .database.usgovcloudapi.net
> 
> [AzureGermanCloud]
> endpoint_management = https://management.core.cloudapi.de/
> endpoint_resource_manager = https://management.microsoftazure.de
> endpoint_sql_management = https://management.core.cloudapi.de:8443/
> endpoint_batch_resource_id = https://batch.cloudapi.de/
> endpoint_gallery = https://gallery.cloudapi.de/
> endpoint_active_directory = https://login.microsoftonline.de
> endpoint_active_directory_resource_id = https://management.core.cloudapi.de/
> endpoint_active_directory_graph_resource_id = https://graph.cloudapi.de/
> suffix_storage_endpoint = core.cloudapi.de
> suffix_keyvault_dns = .vault.microsoftazure.de
> suffix_sql_server_hostname = .database.cloudapi.de
```

So, I can not execute commands in parallel to reduce the time of create resources because the cli fails in a random way. I think these changes cause that when another command tries to access the file it is being changed by another and fails. But I don't know why this file need change the order of data or the file.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Linux) 3.6.1 (default, May 18 2017, 14:59:59) 
[GCC 4.8.4]

Python location '/opt/az/bin/python3'

**OS Version:** What OS and version are you using?  
Answer here:

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

bash --version
GNU bash, versión 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by derekbekoe** [comment] 2017-05-25 14:18
Closing as this looks like a dupe of https://github.com/Azure/azure-cli/issues/3255

**Closed by derekbekoe** 2017-05-25 14:18 UTC
