### ISSUE TITLE
Az login from ubuntu

### ISSUE THREAD

**Issue by sonalika-roy** [Azure/azure-cli#21638] opened 2022-03-14 20:15 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1647285258.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1647288565,
  "nbf": 1647288565,
  "exp": 1647292465,
  "aio": "AXQAi/8TAAAAjVe8AYAPRVNECGKwMOOdWph2gcXdHIRNfznK7hPo/ka1P9VC4vad/NzCTswjoTAxSsRipjjbNmQfl0fGNe3rbTZGhre7TWLLhG+zjKcpBr6BR/nN5DUhIP5jYlww1qk/ZQS/MTN6ppxoyExZEQvAEw==",
  "name": "Sonalika Roy",
  "nonce": "dae74b9cdb227a6cd470e0d25a111fecd96b72a3cc86f95c9c4c95ddcd5d6b97",
  "oid": "24474993-8e99-48a7-88d4-d3c79f776f6a",
  "preferred_username": "sonalikaroy@microsoft.com",
  "puid": "100320013719367D",
  "rh": "0.ARoAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAAk.",
  "sub": "EQFAzubOgER9c0fKu0a-QqiuPTRi6eP0Fc5HG5ER2vE",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "zKaRP2nHq0Wc2nySvJ4LAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 171, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1647285258.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1647288565,
  "nbf": 1647288565,
  "exp": 1647292465,
  "aio": "AXQAi/8TAAAAjVe8AYAPRVNECGKwMOOdWph2gcXdHIRNfznK7hPo/ka1P9VC4vad/NzCTswjoTAxSsRipjjbNmQfl0fGNe3rbTZGhre7TWLLhG+zjKcpBr6BR/nN5DUhIP5jYlww1qk/ZQS/MTN6ppxoyExZEQvAEw==",
  "name": "Sonalika Roy",
  "nonce": "dae74b9cdb227a6cd470e0d25a111fecd96b72a3cc86f95c9c4c95ddcd5d6b97",
  "oid": "24474993-8e99-48a7-88d4-d3c79f776f6a",
  "preferred_username": "sonalikaroy@microsoft.com",
  "puid": "100320013719367D",
  "rh": "0.ARoAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAAk.",
  "sub": "EQFAzubOgER9c0fKu0a-QqiuPTRi6eP0Fc5HG5ER2vE",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "zKaRP2nHq0Wc2nySvJ4LAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: 

azure-cli 2.33.0 *

Extensions:
containerapp 0.2.2

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-03-14 22:34
@jiasli for awareness

**Comment by jiasli** [comment] 2022-03-15 02:30
Duplicate of #20388

**Closed by jiasli** 2022-03-15 02:30 UTC
Labels: Account, Auto-Assign
