### ISSUE TITLE
az commands not able to find the resource unless --location is specified

### ISSUE THREAD

**Issue by niwsa** [Azure/azure-cli#6882] opened 2018-07-24 20:56 UTC
**Describe the bug**
1.```$ az image create --resource-group RT14 --name test --source Lego-Official
Source Virtual Machine 'Lego-Official specified in the request does not exist in this Azure location.```
Above works if I give the --location argument  where the source vm exists
2. [az image copy extension fails while creating snapshot](https://github.com/Azure/azure-cli-extensions/issues/248)
**To Reproduce**
Steps to reproduce the behavior.
Execute the above commands without --location argument
**Expected behavior**
The --resource-group and other arguments  should be sufficient to identify the resource,should be able to work without --location argument.
**Environment summary**
Ubuntu 16.04 az-cli 2.0.42-1~xenial

**Comment by yugangw-msft** [comment] 2018-07-25 17:44
#1 is by design, as CLI would default to resource group's location if `--location` is missing. So if the 2 locations are different, the create will not work as cross region is not supported yet. This issue will be resolved sometime this fall through [share image gallery](https://azure.microsoft.com/en-us/blog/shared-image-gallery-now-in-limited-public-preview/) where you can deploy your image to more than one regions.

**Comment by yugangw-msft** [comment] 2018-07-25 17:46
Closing as it is not a CLI issue

**Closed by yugangw-msft** 2018-07-25 17:46 UTC

**Comment by niwsa** [comment] 2018-07-25 19:08
I got the error for az image create with the resource group and vm being in the same location, also image copy extension used to work fine until yesterday,now its breaking with az snapshot create failing (internally image-copy calls az snapshot create without --location)

**Comment by yugangw-msft** [comment] 2018-07-25 19:17
> I got the error for az image create with the resource group and vm being in the same location

Can you please share the error?

**Comment by niwsa** [comment] 2018-07-25 19:34
I am wrong here. Sorry for the carelessness.
The resource group happens to be in a different location.
