### ISSUE TITLE
Error with Azure CLI 2.46.0 and Bicep if no bicep configuration exists

### ISSUE THREAD

**Issue by qetza** [Azure/azure-cli#25710] opened 2023-03-07 18:03 UTC
## Describe the bug

**Command Name**
`az bicep install`

**Errors:**
```
Installing Bicep CLI v0.14.85...
The command failed with an unexpected error. Here is the traceback:
No section: 'bicep'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3648, in install_bicep_cli
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 141, in ensure_bicep_installation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 99, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 94, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 208, in get
  File "configparser.py", line 783, in get
  File "configparser.py", line 1154, in _unify_values
configparser.NoSectionError: No section: 'bicep'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- install Azure CLI 2.46.0
- `az bicep install --version {}`

## Expected Behavior
No error if configuration is not set.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0
```
## Additional Context
This error also happens when running an `az deployment` command passing a bicep file. It seems that the code is not resilient if no configuration for bicep is specified in the config file.

**Comment by yonzhan** [comment] 2023-03-07 23:03
route to CXP team

**Comment by kurt-mueller-osumc** [comment] 2023-03-08 00:54
I can confirm that I receive this same error when running inside an `aarch64` devcontainer. I've been installing azure cli via python since `apt` apparently only supports the `x86` architecture.

Here are my specs:

```
Version: 1.77.0-insider
Commit: bbc87d8ec2453f12c0066e1c30b41cd5bd2aa021
Date: 2023-03-07T05:36:47.728Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by dawidholka** [comment] 2023-03-08 07:23
I have the same problem, the installation works when I set:
`az config set bicep.use_binary_from_path=False`.
The problem occurs since version 2.46.0.

**Comment by PramodValavala-MSFT** [comment] 2023-03-08 21:35
@qetza @kurt-mueller-osumc @dawidholka Thanks for the feedback! We have worked up a PR to address this.

Please do note that despite this error, the `bicep` CLI is installed and can be used as usual.

**Comment by krizskp** [comment] 2023-03-08 23:13
> @qetza @kurt-mueller-osumc @dawidholka Thanks for the feedback! We have worked up a PR to address this.
> 
> Please do note that despite this error, the `bicep` CLI is installed and can be used as usual.

The error breaks automated deployment pipelines though. 
I use BitBucket Pipelines for deployment and face this same error message. The pipeline fails at this error message from `az deployment ...` command in the pipeline.

**Comment by dawidholka** [comment] 2023-03-08 23:18
> > @qetza @kurt-mueller-osumc @dawidholka Thanks for the feedback! We have worked up a PR to address this.
> > Please do note that despite this error, the `bicep` CLI is installed and can be used as usual.
> 
> The error breaks automated deployment pipelines though. I use BitBucket Pipelines for deployment and face this same error message. The pipeline fails at this error message from `az deployment ...` command in the pipeline.

I also have this problem when running the pipeline and `az deployment ...` command. I solved this problem by adding at the beginning:
```
az config set bicep.use_binary_from_path=False
az bicep install
```

I haven't tested yet how this would work with:
az config set bicep.use_binary_from_path=if_found_in_ci

**Comment by michaelelleby** [comment] 2023-03-09 19:33
> @krizskp
> 
> > > @qetza @kurt-mueller-osumc @dawidholka Thanks for the feedback! We have worked up a PR to address this.
> > > Please do note that despite this error, the `bicep` CLI is installed and can be used as usual.
> > 
> > 
> > The error breaks automated deployment pipelines though. I use BitBucket Pipelines for deployment and face this same error message. The pipeline fails at this error message from `az deployment ...` command in the pipeline.
> 
> I also have this problem when running the pipeline and `az deployment ...` command. I solved this problem by adding at the beginning:
> 
> ```
> az config set bicep.use_binary_from_path=False
> az bicep install
> ```
> 
> I haven't tested yet how this would work with: az config set bicep.use_binary_from_path=if_found_in_ci

Another workaround is to run the same az command twice, as the first time it will fail and the second time it succeeds.

**Comment by KarenTazayan** [comment] 2023-03-10 09:09
The same error breaks my Azure Pipelines when build agents upgraded to Azure CLI 2.46.0.

**Comment by Sumtin** [comment] 2023-03-10 15:37
Breaking Azure Pipeline builds for me too.  Tried workaround but still breaking.  Currently can't deploy any of my infra from Pipelines.  What's the timeframe for the fix?

**Comment by Sdelausnay** [comment] 2023-03-10 15:57
We have the same issue on our agents. Workaround also don't seem to do the trick for use. Any news on the topic?

**Comment by sb1975** [comment] 2023-03-10 23:55
Same error, resolved by using inline script in additional Task before running the main Task.
    inlineScript: |
      az config set bicep.use_binary_from_path=False
      az bicep install

**Comment by AshuBanctec** [comment] 2023-03-13 04:18
I am facing same issue bicep install fails. even after setting **az config set bicep.use_binary_from_path=False** , it produces warning on the console and build fails.

**Comment by vishnuss10308** [comment] 2023-03-13 06:06
I am also facing the same issue in GitLab Pipelines
az deployment group validate command is failing with error 
ERROR: No section: 'bicep'
Retry worked for az deployment group validate command for the same parameters.

**Comment by TenaciousG** [comment] 2023-03-13 07:27
This is also breaking my Azure Pipelines. Cannot deploy production changes!

**Comment by ricardoschroeder** [comment] 2023-03-13 09:53
Any news yet? All our deployments are failing now

**Comment by patricksengalrayan** [comment] 2023-03-13 10:49
All deployments failing here as well, on an Agent in a deployment agent pool.

/usr/bin/bash /home/azuredevops/azdoAgent/_work/_temp/azureclitaskscript1678703942369.sh
ERROR: No section: 'bicep'
##[error]Script failed with exit code: 1

Temporary solution:
Until fixed, downgrading version to az cli 2.45 seems to solve the issue. On agent VM run:
`sudo apt-get install azure-cli=2.45.0-1~focal`

Mind: when fixed, upgrade az cli again!

**Comment by KarenTazayan** [comment] 2023-03-13 11:18
As a temporary solution, I also downgraded all agents to the previous version.

**Comment by az-core** [comment] 2023-03-13 11:25
This issue seems related to a recent change 
[CLI 2.45.0 breaks Github Actions that tried to install a specific version of Bicep](#25541)
[Fix #25510: az bicep: Set bicep.use_binary_from_path to false when installed using Azure CLI](#25510) 

It also breaks pipelines using the latest image **mcr.microsoft.com/azure-functions/dotnet:4-dotnet6-core-tools** as Azure Cli 2.46.0 is internally referenced and installed. 

As mentioned in the thread above, the `az deploment` command also fails. 

For now, last week, we managed to fix this by including command
`az config set bicep.use_binary_from_path=false`

before `az bicep install` and` az deployment` commands. This work around is mentioned in this thread as above and also on https://github.com/Azure/azure-cli/issues/25510

**Comment by Grant-Rc** [comment] 2023-03-14 00:16
Can also confirm we are getting this error in Gitlad Pipeline deployments using the MS image
image: [mcr.microsoft.com/azure-cli](http://mcr.microsoft.com/azure-cli)

can confirmed `az config set bicep.use_binary_from_path=false` got me around this also

**Comment by TenaciousG** [comment] 2023-03-15 07:26
Is this the same issue that I'm facing when using the AzureResourceManagerTemplateDeployment@3 Azure Pipeline task?
My error message for the past week is:
```
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Error: Command failed: az bicep build --file /agent/_work/1/s/ARMTemplates/goweb/prod/prod-goweb.bicep
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: No section: 'bicep'

```
This is crippling for my ARM deployments! And the workaround by first running this script doesn't do anything for me>
```
az config set bicep.use_binary_from_path=false
az bicep install
```

**Comment by kek-Sec** [comment] 2023-03-15 10:05
breaking all pipelines on ubuntu , windows agents appear to be working for now

**Comment by sandert98** [comment] 2023-03-15 14:37
Still broken since last week. Workarounds aren't working for us.
If possible, a hotfix would be highly appreciated. Our workload is depending on bicep, which are all failing now.

**Comment by dawidholka** [comment] 2023-03-15 16:54
> Is this the same issue that I'm facing when using the AzureResourceManagerTemplateDeployment@3 Azure Pipeline task? My error message for the past week is:
> 
> ```
> ##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
> ##[error]Error: Command failed: az bicep build --file /agent/_work/1/s/ARMTemplates/goweb/prod/prod-goweb.bicep
> ERROR: The command failed with an unexpected error. Here is the traceback:
> ERROR: No section: 'bicep'
> ```
> 
> This is crippling for my ARM deployments! And the workaround by first running this script doesn't do anything for me:
> 
> ```
> az config set bicep.use_binary_from_path=false
> az bicep install
> ```

This workaround works for me with AzureCLI@2 task and setting input: `useGlobalConfig: true`.

**Comment by TenaciousG** [comment] 2023-03-16 09:49
@dawidholka Thanks, didn't get a chance to test it out since my pipelines seem to be working today. Hopefully the issue has been fixed globally.

**Comment by danielmackay** [comment] 2023-03-16 10:08
I've tried the `az config` work around, and have now got our bit bucket pipelines working.

Thanks @dawidholka! 😄

**Comment by johnnyreilly** [comment] 2023-03-17 13:44
Seeing this also on GitHub Actions deployments for my Azure Static Web App blog. Failing build: https://github.com/johnnyreilly/blog.johnnyreilly.com/actions/runs/4433656682/jobs/7810249789?pr=459

PR that triggered this: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/459

**Comment by PNeergaard** [comment] 2023-03-17 14:23
We found that this issue may be related to the fact that Bicep is already installed on the agent running the build i.e. if running windows-latest. If we remove our "az bicep install" step, deployments run without any issues.

**Comment by ugreg** [comment] 2023-03-17 18:20
Anyone facing this issue when trying to set to false, it causes any Azure Pipelines to fail.

```sh
az config set bicep.use_binary_from_path=false
az bicep install
```

![image](https://user-images.githubusercontent.com/8151045/225986684-75451971-c3da-4c0b-800d-4e7099a5772c.png)

**Comment by ugreg** [comment] 2023-03-17 20:00
Thanks adding those two lines in their own PowerShell task worked.

Example

```yml
- task: PowerShell@2
  displayName: "Install Bicep"
  inputs:
    targetType: 'inline'
    script: |         
          az config set bicep.use_binary_from_path=false
          az bicep install
    failOnStderr: false
    showWarnings: true
    pwsh: true
```

**Comment by m-soltani** [comment] 2023-03-20 23:28
This is an extra burden for us when writing CI/CD pipelines, which is now broken due to this functionality. I have to add the flag `use_binary_from_path=False` and install Bicep CLI manually, which is really nasty.

**Closed** 2023-03-29 11:25 UTC
Labels: bug, ARM, customer-reported, Client, CXP Attention, Auto-Assign
