### ISSUE TITLE
Azure VM Extension Set error

### ISSUE THREAD

**Issue by Newlearns** [Azure/azure-cli#14318] opened 2020-07-10 09:09 UTC
## Describe the bug

**Command Name**
`az vm extension set`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm extension set --resource-group {} --vm-name {} --name {} --publisher {} --version {} --settings {} --protected-settings {}`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yungezz** [comment] 2020-07-13 03:29
hi @Newlearns did you meet the error in Cloudshell? If yes, could you pls try 'az login` to workaround? This is a known issue in Cloudshell #11749 . They're working on fixing.

**Comment by maertendMSFT** [comment] 2020-09-30 23:16
Can we close this as a dupe of https://github.com/Azure/azure-cli/issues/11749 ?

**Closed** 2020-10-01 09:07 UTC
Labels: Cloud Shell, Service Attention, customer-reported
