### ISSUE TITLE
Cannot get Netapp Files mount targets with azcli (version 2.3.1)

### ISSUE THREAD

**Issue by garvct** [Azure/azure-cli#13011] opened 2020-04-14 18:36 UTC
**Describe the bug**

After deploying ANF/CIFS, I cannot get the mount targets with the following az cli (version 2.3.1) commamd

az netappfiles list-mount-targets --resource-group <REsource group> --account-name <account_name> --pool-name <pool_name> --volume-name <vol_name>

Command group 'netappfiles' is in preview. It may be changed/removed in a future release.
Azure Error: InvalidResourceType
Message: The resource type 'netAppAccounts/capacityPools/volumes/mountTargets' could not be found in the namespace 'Microsoft.NetApp' for api version '2019-10-01'. The supported api-versions are '2017-08-15,2019-05-01,2019-06-01,2019-07-01,2019-08-01'.

**To Reproduce**

Deploy ANF/CIFS and use az cli to get the mount targets.

**Expected behavior**
If I use az cli version 2.2.0 from cloud shell, I get the expected result.

cormac@Azure:~$ az netappfiles list-mount-targets --resource-group cg_ad_demo-scus --account-name hpcnetappad --pool-name anfpool --volume-name anfvolume1
Command group 'netappfiles' is in preview. It may be changed/removed in a future release.
[
  {
    "endIp": "10.2.3.4",
    "fileSystemId": "9156b26e-4688-95cc-c110-a568a9338313",
    "gateway": "",
    "id": "/subscriptions/f5a67d06-2d09-4090-91cc-e3298907a021/resourceGroups/cg_ad_demo-scus/providers/Microsoft.NetApp/netAppAccounts/hpcnetappad/capacityPools/anfpool/volumes/anfvolume1/mountTargets/9156b26e-4688-95cc-c110-a568a9338313",
    "ipAddress": "10.2.3.4",
    "location": "southcentralus",
    "mountTargetId": "9156b26e-4688-95cc-c110-a568a9338313",
    "name": "hpcnetappad/anfpool/anfvolume1/9156b26e-4688-95cc-c110-a568a9338313",
    "netmask": "",
    "provisioningState": "Succeeded",
    "resourceGroup": "cg_ad_demo-scus",
    "smbServerFqdn": null,
    "startIp": "10.2.3.4",
    "subnet": "",
    "tags": null,
    "type": "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/mountTargets"
  }
]
cormac@Azure:~$

**Environment summary**
az cli installed on Windows 10 WSL, Ubuntu 16.04.5 LTS

az --version
azure-cli                          2.3.1

command-modules-nspkg              2.0.3
core                               2.3.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/linuxuser/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Apr  1 2020, 07:19:36)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment] 2020-04-14 22:27
netappfiles

**Comment by xpillons** [comment] 2020-05-06 09:23
When this will be fixed ?

**Comment by edwardsp** [comment] 2020-05-11 14:20
I am presuming the issue is the from api_version used in [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python)?  I can see it is set [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_accounts_operations.py#L40).  The modification history for that is [here](https://github.com/Azure/azure-sdk-for-python/commits/master/sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_accounts_operations.py).

**Comment by audunn** [comment] 2020-07-09 16:36
Quick test using Azure CLI docker images shows this working the same in latest (2.8.0), 2.3.1 and 2.2.0.

However note that list-mount-targets is due for deprecation/removal in upcoming version of the CLI, as mount target information can be retrieved using volume show.

az netappfiles volume show -g TestRG -a test-account -p test-pool -v tests-vol-1

. . "mountTargets": [ { "endIp": "", "fileSystemId": "3fcf5730-6f36-0900-7228-5effdea724bd", "gateway": "", "ipAddress": "10.14.0.5", "mountTargetId": "3fcf5730-6f36-0900-7228-5effdea724bd", "netmask": "", "provisioningState": "", "startIp": "", "subnet": "" } ], . .

**Comment by ranieuwe** [comment] 2020-08-11 22:31
As of latest azure-cli v 2.10.1 this is working as expected: 

```
azure-cli                         2.10.1

command-modules-nspkg              2.0.3
core                              2.10.1
nspkg                              3.0.4
telemetry                          1.0.4
```

```
az netappfiles volume show -a anf-sizing -p sizing -g general -n sizingvol
```

```
  "mountTargets": [
    {
      "endIp": "",
      "fileSystemId": "6146bcab-df85-9f90-1711-dc62d5b485b7",
      "gateway": "",
      "ipAddress": "10.1.1.4",
      "mountTargetId": "6146bcab-df85-9f90-1711-dc62d5b485b7",
      "netmask": "",
      "provisioningState": "",
      "smbServerFqdn": null,
      "startIp": "",
      "subnet": ""
    }
```

I believe this issue can be closed.

**Closed** 2020-08-12 00:03 UTC
Labels: NetAppFiles, Service Attention
