### ISSUE TITLE
getting syntax error while executing az group list commnd

### ISSUE THREAD

**Issue by jibin18** [Azure/azure-cli#14610] opened 2020-07-31 12:39 UTC
## Describe the bug

**Command Name**
`az group list`

**Errors:**
```
invalid syntax (custom.py, line 696)
Traceback (most recent call last):
python3.5/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 470, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap_external>, ln 661, in exec_module
<frozen importlib._bootstrap_external>, ln 767, in get_code
<frozen importlib._bootstrap_external>, ln 727, in source_to_code
<frozen importlib._bootstrap>, ln 222, in _call_with_frames_removed
cli/command_modules/resource/custom.py, ln 696
    err_messages = [f'{preflight_error.code} - {preflight_error.message}']
                                                                        ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group list`

## Environment Summary
```
Linux-4.8.0-54-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2
Installer: 

azure-cli 2.9.1

```

**Comment by yonzhan** [comment] 2020-07-31 15:16
add to S174

**Comment by zhoxing-ms** [comment] 2020-08-07 03:19
@jibin18 Sorry, I can't reproduce your question. Please add `--debug` to the original command and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment] 2020-08-10 09:39
@jibin18 Hi, thanks for your email~ From my analysis of the error information in the log, it is likely to be an environment related problem. May I ask what is the specific environment you used and how did you install CLI?

**Comment by zhoxing-ms** [comment] 2020-08-21 02:02
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-08-21 02:02 UTC
Labels: ARM, Feature Request, OKR3.2 Candidate
