### ISSUE TITLE
The `az acr login` command is a bit unfriendly

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-cli#5619] opened 2018-02-20 22:35 UTC
With the Azure Container Registry we need to use `az acr login`.

However, it is a bit unfiendly because:

1. Users need to know in which subscription the registry is.
2. Users need to issue `az account set` command first. This itself is a dangerous one.

It would be lovely to remove the need to know the sub for ACR altogeher.

If that is not possible at all, it would make things easier if we could have `--subscription` arg in `az acr login`. 

See also https://github.com/Azure/azure-cli/issues/5618, which would help if implemented.

PS. It would be even nicer if we could use `docker login` with user credentials directly without the need to have `azure CLI`, because TBH it's a bit heavy-handed option (but I realise it's not azure cli issue per se).  It's especially so that this command does not work with dockerized version of azure CLI.

**Comment by djyou** [comment] 2018-02-21 22:09
Could you please elaborate why running `az account set` is dangerous? My understanding is that even if we provide a `--subscription` parameter we will just set the subscription internally using the same flow of `az account set` since the Azure resource is under a subscription by design. For scripting purpose it's a matter of running either 2 commands or 1 command. As you also mentioned this is indeed a framework pattern that subscription is always required from users.

`az acr login` internally calls `docker login` but it requires the correct subscription to find the resource and obtain login credentials. Once you have the credentials, users could call `docker login` directly too (e.g., using admin user credentials, service principals, or AAD tokens).

/cc @sajayantony @SteveLas

**Comment by sajayantony** [comment] 2018-02-26 17:14
I've faced this issue myself and feel it does make sense to have a subscription parameter. #807 is a CLI level change and not just ACR change. @tjprescott is there any priority on that issue?

**Comment by tjprescott** [comment] 2018-02-26 17:56
I can't say that there's much traction on it as far as our backlog is concerned, though feel free to reach out to @johanste and @yugangw-msft via email.

The standard way of handling cross-RG and cross-subscription things in the CLI is to allow ARM IDs for anything that could accept names.  This pattern is applied almost universally across the CLI and thus has largely diminished the perceived urgency for a `--subscription` parameter.

There may be specific parameters that only accept names when they could logically accept names or IDs. I would suggest writing the script to utilize IDs as much as possible and raising issues for specific pain points that seem hard-coded to the current user's subscription.

**Comment by djyou** [comment] 2018-02-26 18:19
@tjprescott The `--id` parameter doesn't help here. It basically parses a resource ID into a resource group name and a resource name, and then tries to find the resource group and resource under the current subscription set by `az account set` while ignoring the subscription ID in the specified resource ID. If you are not in the correct subscription the resource couldn't be found either.

**Comment by tjprescott** [comment] 2018-02-26 18:22
Thanks @djyou.  This should help us prioritize the work.

**Comment by djyou** [comment] 2018-06-13 18:55
This appears to be supported by https://github.com/Azure/azure-cli/pull/6516

Thank you @tjprescott for adding the support, could you please also close this issue?

**Closed** 2018-06-25 16:21 UTC
Labels: Container Registry
