### ISSUE TITLE
Resource list does not filter correctly on tags.

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-cli#7674] opened 2018-10-25 17:12 UTC
Resource list does not filter correctly on tags.

A command like (XXX is an existing resource group)
```
19:08 $  az resource list --resource-group XXX --resource-type "Microsoft.KeyVault/vaults" --tag Team=Y
```

returns
```
Operation failed with status: 'Bad Request'. Details: "{\"error\":{\"code\":\"InvalidFilterInQueryString\",\"message\":\"Invalid $filter 'resourceGroup eq 'XXX' and resourceType eq 'Microsoft.KeyVault/vaults' and tagname eq 'Team' and tagvalue eq 'Y'' specified in the query string.\"}}"
```

I am running on Mac OSX with cli  version 2.0.45

The error persist removing the resource-type filter. Adding quotes does not help. However, the following works:

```
22:04 $  az resource list --resource-group XXX --resource-type "Microsoft.KeyVault/vaults" 
```

Interestingly, only filtering like

```
 az resource list   --tag "Team=X"
```

returns resources with tags equal to null.

**Comment by andreacassioli** [comment] 2018-11-02 19:10
Is this issue confirmed as bug?

**Comment by andreacassioli** [comment] 2018-12-13 21:15
Any progress on this?

**Comment by adewaleo** [comment] 2018-12-18 22:35
Hello @andreacassioli, it looks like this issue fell through the cracks. 
I can confirm both issues you raised as bugs:
- Using `--tags` alongside `--resource-group` and/or `--resource-type` returns a service error.
- The resources returned by using only `--tags` return have tags set to null.

I can look into a fix for this bug, but it would likely be at the end of this sprint or in our next sprint.

cc: @tjprescott, how can we prevent issues like this from falling through the cracks?

**Comment by adewaleo** [comment] 2019-01-24 22:04
So it turns out these issues are Service issues. 

See [here](https://github.com/Azure/azure-rest-api-specs/issues/3819), [here](https://github.com/Azure/azure-sdk-for-net/issues/2819) and [here](https://github.com/Azure/azure-sdk-for-net/issues/2757)

A work around is to use query expressions:
```
az resource list  --tag "Team=Y" \
 --query "[?type=='Microsoft.KeyVault/vaults'] | [?resourceGroup=='XXX']"
```

The query is a [JMESPATH](http://jmespath.org/) expression that filters out all the resulting resources with type keyvault and then pipes the output to another expression that filters based on resource group.

Here is a tutorial on our docs on how to use [`--query`](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest)

**Comment by ehrnst** [comment] 2019-05-28 11:35
Any updates on this. I see the same issue running REST requests directly.

**Comment by andreacassioli** [comment] 2019-08-21 21:13
Any news? The work around are pretty cumbersome and to me confusing as long as the other parameters are available. Nothing worst than a CLI with unpredictable behavior...

**Comment by MisinformedDNA** [comment] 2020-10-23 14:39
The AZ PowerShell module works fine.

```pwsh
Get-AzResource -ResourceGroupName my-rg3 -TagName Environment -TagValue Dev
```

**Comment by rthorn17** [comment] 2024-11-11 18:34
The az resource list function in cli doesn't allow the '-tag parameter' and  '--resource-group' or '--resource-type' parameter to be used together.  It seems to have been done this way by design when introduced for performance reasons.  The ARM Resource Tags team have added this to our backlog but I have no timeline for when it can be worked on.  I am closing this ticket and will update it when changes for this have done.

**Closed by rthorn17** 2024-11-11 18:34 UTC
Labels: bug, Service Attention, ARM, ARM - Tags
