### ISSUE TITLE
Issue with az vm list-skus

### ISSUE THREAD

**Issue by smoop-msft** [Azure/azure-cli#15265] opened 2020-09-23 17:16 UTC
I have a customer who is having issues with az vm list-skus CLI command not listing a particular VM SKU(D15_v2) in a region(CentralUS) as being available.

![image](https://user-images.githubusercontent.com/71783322/94046047-02f04580-fd85-11ea-8467-0af364ff790e.png)
But the SKU is shown as being available in PS AzureRM command Get-AzureRmVMSize and also shows up as available in the Azure Portal.
Interestingly the VM with that SKU can be deployed using portal as well as using CLI. It just the CLI command az vm list-skus does not show the SKU as being available.
Would appreciate if we can find the reason on why the SKU does not show as being available even though deploying the same VM SKU works just fine.
Thanks in advance!

**Comment by yungezz** [comment] 2020-09-24 03:44
hi @qwordy could you pls check why the sku not sured? this is pure rest call. Maybe caused by API version difference?

**Comment by smoop-msft** [comment] 2020-09-24 16:33
Please note the issue persistent in cloud shell session too.

**Comment by qwordy** [comment] 2020-09-25 02:20
My result.
```
yfy@DESKTOP-ARGPJS4:~$ az vm list-skus --location centralus | grep D15
    "name": "Standard_D15_v2",
    "size": "D15_v2",
```
Can you add `--debug` to your command to check the request and response?

**Comment by qwordy** [comment] 2020-09-29 06:50
Your log:
```
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/1fd1d0ad-a457-4f28-a2e7-810438683bc1/providers/Microsoft.Compute/skus?api-version=2019-04-01'
msrest.http_logger : Request method: 'GET'
```
My log:
```
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Compute/skus?api-version=2019-04-01'
msrest.http_logger : Request method: 'GET'
```
The only difference is subscription.
Can you try `GET https://management.azure.com/subscriptions/1fd1d0ad-a457-4f28-a2e7-810438683bc1/providers/Microsoft.Compute/skus?api-version=2020-06-01`

**Comment by smoop-msft** [comment] 2020-09-29 18:26
Are you saying to run this?
az rest -m get --header "Accept=application/json" -u ‘https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute/skus?api-version=2020-06-01'

**Comment by qwordy** [comment] 2020-09-30 01:30
I usually send HTTP request using Postman. Command line tool is also a good choice, like `az rest`, `curl`, `wget`.

**Comment by qwordy** [comment] 2020-10-10 06:59
I check the result you send to me and find that Standard_D15_v2 appears. We will upgrade the API version of "list skus".

**Comment by qwordy** [comment] 2020-10-10 08:53
@avirishuv 
Do you think we should use 
```
https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Compute/skus?api-version=2020-06-01
```
instead of `2019-04-01`?
However, I can't find `skus.json` in
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01

**Comment by amjads1** [comment] 2020-10-12 06:18
Looking into the issue

**Comment by amjads1** [comment] 2020-10-12 16:59
Assigned to Avi.

**Comment by qwordy** [comment] 2020-10-16 08:21
@avirishuv Kindly ping.

**Comment by smoop-msft** [comment] 2020-10-19 16:23
@avirishuv - Request any update on this please.

**Comment by avirishuv** [comment] 2020-11-05 21:47
@qwordy @smoop-msft as discussed, the issue was related to zone level availability for the specific deployment. The API and CLI responses were as per the expected behavior. Closing the issue, thanks.

**Closed by avirishuv** 2020-11-05 21:47 UTC
Labels: Compute, Service Attention
