### ISSUE TITLE
az postgres up: Extension install doesn't work on Mac OS Catalina

### ISSUE THREAD

**Issue by nnja** [Azure/azure-cli#13630] opened 2020-05-22 16:39 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**

On macOS Catalina 10.15.4

Install az cli with brew:

```
$ brew install az
```

Attempt to install the preview extension to use `az postgres up` following the instructions in the [quickstart](https://docs.microsoft.com/en-us/azure/postgresql/quickstart-create-server-up-azure-cli).

```
$ az extension add --name db-up
```

**Expected behavior**

The extension should be installed successfully. 

Instead, an error message is printed.

```
$ az extension add --name db-up
An error occurred. Pip failed with status code 1. Use --debug for more information.
```

**Environment summary**

System Python: 3.7.7
Az Python: 3.8.2 (Installed as a dependency via brew)

macOS-10.15.4-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.6.0

**Additional context**

Stack trace seen when running with debug flags below.

I'm not 100% sure, but one issue may have to do with the [az cli extension relying on Python 3.8](https://formulae.brew.sh/formula/azure-cli), while the az db extension relies on [Python 3.6](https://github.com/Azure/azure-cli-extensions/blob/ddefab4a9c1e74737db1161030d614dd16465870/src/db-up/setup.py#L23). There might also be an issue with an older [version of the psycopg2-binary library](https://github.com/Azure/azure-cli-extensions/blob/ddefab4a9c1e74737db1161030d614dd16465870/src/db-up/setup.py#L30) that the extension depends on.

```
g2-binary
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.8
    creating build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/_json.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/extras.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/errorcodes.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/tz.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/_range.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/_ipaddress.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/psycopg1.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/extensions.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/sql.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    copying lib/pool.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2
    creating build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_transaction.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/dbapi20.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_extras_dictcursor.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_with.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_types_basic.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_bug_gc.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_module.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_psycopg2_dbapi20.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_async.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_dates.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_async_keyword.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/testutils.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_connection.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_copy.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_bugX000.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_cursor.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_types_extras.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_sql.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_fast_executemany.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_green.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_ipaddress.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_cancel.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_quote.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/testconfig.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_errcodes.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_replication.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_lobject.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/test_notify.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    copying tests/dbapi20_tpc.py -> build/lib.macosx-10.15-x86_64-3.8/psycopg2/tests
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.macosx-10.15-x86_64-3.8
    creating build/temp.macosx-10.15-x86_64-3.8/psycopg
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION=2.7.7 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=120003 -DHAVE_LO64=1 -I/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8 -I. -I/usr/local/include -I/usr/local/include/postgresql/server -c psycopg/psycopgmodule.c -o build/temp.macosx-10.15-x86_64-3.8/psycopg/psycopgmodule.o
    psycopg/psycopgmodule.c:689:18: error: incomplete definition of type 'struct _is'
        while (interp->next)
               ~~~~~~^
    /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/pystate.h:20:8: note: forward declaration of 'struct _is'
    struct _is;
           ^
    psycopg/psycopgmodule.c:690:24: error: incomplete definition of type 'struct _is'
            interp = interp->next;
                     ~~~~~~^
    /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/pystate.h:20:8: note: forward declaration of 'struct _is'
    struct _is;
           ^
    2 errors generated.

    It appears you are missing some prerequisite to build the package from source.

    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    error: command 'clang' failed with exit status 1
    Running setup.py install for psycopg2-binary: finished with status 'error'
ERROR: Command errored out with exit status 1: /usr/local/Cellar/azure-cli/2.6.0/libexec/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-install-8iewgpi_/psycopg2-binary/setup.py'"'"'; __file__='"'"'/private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-install-8iewgpi_/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-record-fn1judrv/install-record.txt --single-version-externally-managed --home /private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-target-890sc0zw --compile --install-headers /usr/local/Cellar/azure-cli/2.6.0/libexec/bin/../include/site/python3.8/psycopg2-binary Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 827, in install
    success = install_legacy(
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 398, in run
    installed = install_given_reqs(
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 67, in install_given_reqs
    requirement.install(
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 845, in install
    six.reraise(*exc.parent)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 270, in runner
    call_subprocess(
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/Cellar/azure-cli/2.6.0/libexec/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-install-8iewgpi_/psycopg2-binary/setup.py'"'"'; __file__='"'"'/private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-install-8iewgpi_/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-record-fn1judrv/install-record.txt --single-version-externally-managed --home /private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-target-890sc0zw --compile --install-headers /usr/local/Cellar/azure-cli/2.6.0/libexec/bin/../include/site/python3.8/psycopg2-binary Check the logs for full command output.
Removed build tracker: '/private/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/pip-req-tracker-us649el3'

Command '['/usr/local/Cellar/azure-cli/2.6.0/libexec/bin/python', '-m', 'pip', 'install', '--target', '/Users/nina/.azure/cliextensions/db-up', '/var/folders/sp/2xl8pg3d4l501xtxl_ncn4n40000gn/T/tmp1cl12mfa/db_up-0.1.13-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
Homebrew patch: Deleting the temporarily created /Users/nina/.pydistutils.cfg
Pip failed so deleting anything we might have installed at /Users/nina/.azure/cliextensions/db-up
cli.azure.cli.core.util : An error occurred. Pip failed with status code 1. Use --debug for more information.
An error occurred. Pip failed with status code 1. Use --debug for more information.
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10ce634c0>]
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2579 in cache
telemetry.check : Negative: The /Users/nina/.azure/telemetry.txt was modified at 2020-05-22 09:29:07.662102, which in less than 600.000000 s
command ran in 57.619 seconds.
```

**Comment by yonzhan** [comment] 2020-05-22 22:26
add to S171

**Comment by Juliehzl** [comment] 2020-05-27 01:45
dupe of #12340

**Comment by Juliehzl** [comment] 2020-05-27 08:02
It is fixed in latest db-up. Please upgrade your version with `az extension update -n db-up`.

**Comment by bkjones** [comment] 2020-06-05 14:03
@Juliehzl could you provide some info or link to what the fix was? I have this issue with the same exact error but am not using az.

**Comment by jackchau102** [comment] 2020-06-06 00:04
Same problem here. I tried to install psycog2 in a python3 venv and it keeps throwing out this error.

**Comment by Juliehzl** [comment] 2020-06-08 02:19
> Same problem here. I tried to install psycog2 in a python3 venv and it keeps throwing out this error. I'm not using az either.

May I know which is the installed version for psycog2?

**Comment by Juliehzl** [comment] 2020-06-08 02:21
> @Juliehzl Zunli Hu FTE could you provide some info or link to what the fix was? I have this issue with the same exact error but am not using az.

The fix is to update `psycopg2-binary` yo 2.8.5.

**Closed** 2020-06-08 02:21 UTC
Labels: PostgreSQL, db-up, feature-request, question

**Comment by jackchau102** [comment] 2020-06-08 03:10
One important thing to notice is that you might also need to install openssl and add that to your library path.

**Comment by ninadicara** [comment] 2020-12-04 09:44
In case relevant to anyone else who ends up here - 
I had a very similar error after upgrading to Big Sur. Just in case anyone else does too, mine actually ended up being an issue with Big Sur changing clang to an unsupported version. I ran the [fix suggested here](https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target) and the extension now installs fine.
