### ISSUE TITLE
update AZ CLI for compatibility with Python 3.8

### ISSUE THREAD

**Issue by PaulCharlton** [Azure/azure-cli#14083] opened 2020-06-24 01:52 UTC
re: https://github.com/Azure/azure-cli/issues/12390

see: https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior

This issue is still wide open with many AZ CLI modules

```
az version
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.51",
    "azure-devops": "0.18.0",
    "mesh": "0.10.6",
    "resource-graph": "1.1.0"
  }
}
```

see, for example:
```
az storage account list
/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/_upload_chunking.py:403: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if n is 0 or self._buffer.closed:
/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:1063: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:2719: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/common/_connection.py:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/multiapi/cosmosdb/v2017_04_17/common/_connection.py:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
```

**Comment by yungezz** [comment] 2020-06-24 02:07
hi @fengzhou-msft could you pls have a look?

**Comment by fengzhou-msft** [comment] 2020-06-29 03:23
@Juliehzl can you take a look at the error message with azure-multiapi-storage SDK?

**Comment by Juliehzl** [comment] 2020-06-29 03:38
Hi @PaulCharlton, could you provide more information with `--debug` in your command?

**Comment by PaulCharlton** [comment] 2020-06-29 04:23
@Juliehzl This occurs on MacOS with BREW install of az-cli.

For specific example, just look at the source code file `azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/_upload_chunking.py` at line 403.

That line says `if n is 0 or self._buffer.closed:`

This is incorrect syntax on Python3.8 and should read `if n == 0 or self._buffer.closed:`

**Comment by Juliehzl** [comment] 2020-06-29 06:57
could you share the cli command you are using? For `az storage account list`, we cannot reproduce the issue.

**Comment by PaulCharlton** [comment] 2020-07-06 06:07
Hi @Juliehzl -- I am not sure what to say ... I have MacOS + home-brew + AZ CLI installed via home-brew.

I still get, as of moments ago:
```
STDERR: if lease_duration is not -1 and \
STDERR: /usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:2719: SyntaxWarning: "is not" with a literal. Did you mean "!="?
```

When I look at the path in the error above, it shows Az Cli 2.7.0 and also python3.8 as part of that path.

**Comment by GeeWee** [comment] 2020-07-15 12:39
Definitely still not solved. When running something like `az storage account create --name foobarteststorageaccount --kind StorageV2` under Python 3.8 on Fedora 32 I get a barrage of warnings like below.

```
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/_upload_chunking.py:403: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if n is 0 or self._buffer.closed:
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:1063: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:2719: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/_connection.py:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/cosmosdb/v2017_04_17/common/_connection.py:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
```
Seems like it's subtly different from the problem above, where mine is actually trying to run libraries from python 3.6's `site-packages`

Perhaps it's a packaging issue on the yum repo on the fedora side? My version stats are as follows:
```
azure-cli                          2.9.0

command-modules-nspkg              2.0.3
core                               2.9.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
application-insights               0.1.4

Python location '/usr/bin/python3'
Extensions directory '/home/geewee/.azure/cliextensions'

Python (Linux) 3.8.3 (default, May 29 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

Full output of `az storage account create --name foobarteststorageaccount --kind StorageV2 --debug`
```
Command arguments: ['storage', 'account', 'create', '--name', 'foobarteststorageaccount', '--kind', 'StorageV2', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f73faa95790>, <function OutputProducer.on_global_arguments at 0x7f73fabdadc0>, <function CLIQuery.on_global_arguments at 0x7f73fac09430>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'storage': ['azure.cli.command_modules.storage']
Loading command modules:
Name                  Load Time    Groups  Commands
Event: CommandLoader.OnLoadCommandTable []
storage                   0.037        49       216
Total (1)                 0.037        49       216
These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_ai_did_you_mean_this']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
Total (0)                 0.000         0         0  
Loaded 49 groups, 216 commands.
Found a match in the command table for 'storage account create'
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f73fadaf0d0>]
az_command_data_logger : command args: storage account create --name {} --kind {} --debug
metadata file logging enabled - writing logs to '/home/geewee/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f73fadcb820>]
Event: CommandLoader.OnLoadArguments []
Configured default 'rg-aip-test-001' for arg resource_group_name
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/_upload_chunking.py:403: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if n is 0 or self._buffer.closed:
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:1063: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:2719: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/_connection.py:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/cosmosdb/v2017_04_17/common/_connection.py:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
Configured default 'rg-aip-test-001' for arg resource_group_name
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f73fa1e2040>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f73fa1e2160>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f73fabdae50>, <function CLIQuery.handle_query_parameter at 0x7f73fac094c0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f73fa1e20d0>]
Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
attempting to read file /home/geewee/.azure/accessTokens.json as utf-8-sig
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - Authority:Performing instance discovery: ...
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - Authority:Performing static instance discovery
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - Authority:Authority validated via static instance discovery
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - CacheDriver:Found 4 potential entries.
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - CacheDriver:Resource specific token found.
adal-python : 2b5c2dfb-1888-4425-a42b-bd57b1f9d2f4 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'IHzdOne05SClgEiTpzb2pNWAwXNBlvi8yHdJCPWnBoA=', RefreshTokenId: b'b6U1vz2qD3EG7OhAymA0uv474EYraCkJAgpP2yxyP7o='
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/247ec29e-9ce1-4f42-992e-8f31b28f471a/resourcegroups/rg-aip-test-001?api-version=2019-07-01'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'User-Agent': 'python/3.8.3 (Linux-5.7.8-200.fc32.x86_64-x86_64-with-glibc2.2.5) msrest/0.6.9 msrest_azure/0.6.3 azure-mgmt-resource/10.0.0 Azure-SDK-For-Python AZURECLI/2.9.0 (RPM)'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/247ec29e-9ce1-4f42-992e-8f31b28f471a/resourcegroups/rg-aip-test-001?api-version=2019-07-01 HTTP/1.1" 200 288
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '11986'
msrest.http_logger :     'x-ms-request-id': '21f8b832-7a28-4c58-a12f-12c2f4b58e7a'
msrest.http_logger :     'x-ms-correlation-request-id': '21f8b832-7a28-4c58-a12f-12c2f4b58e7a'
msrest.http_logger :     'x-ms-routing-request-id': 'GERMANYNORTH:20200715T123636Z:21f8b832-7a28-4c58-a12f-12c2f4b58e7a'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Wed, 15 Jul 2020 12:36:36 GMT'
msrest.http_logger :     'Content-Length': '288'
msrest.http_logger : Response content:
msrest.http_logger : {"id":"/subscriptions/247ec29e-9ce1-4f42-992e-8f31b28f471a/resourceGroups/rg-aip-test-001","name":"rg-aip-test-001","type":"Microsoft.Resources/resourceGroups","location":"northeurope","properties":{"provisioningState":"Succeeded"}}
using location 'northeurope' from resource group 'rg-aip-test-001'
Getting management service client client_type=StorageManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Getting management service client client_type=StorageManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - Authority:Performing instance discovery: ...
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - Authority:Performing static instance discovery
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - Authority:Authority validated via static instance discovery
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - CacheDriver:Found 4 potential entries.
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - CacheDriver:Resource specific token found.
adal-python : a3a799ca-741b-4942-8700-c878a9fd1fdb - CacheDriver:Returning token from cache lookup, AccessTokenId: b'IHzdOne05SClgEiTpzb2pNWAwXNBlvi8yHdJCPWnBoA=', RefreshTokenId: b'b6U1vz2qD3EG7OhAymA0uv474EYraCkJAgpP2yxyP7o='
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/247ec29e-9ce1-4f42-992e-8f31b28f471a/resourceGroups/rg-aip-test-001/providers/Microsoft.Storage/storageAccounts/foobarteststorageaccount?api-version=2019-06-01'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '175'
msrest.http_logger :     'User-Agent': 'python/3.8.3 (Linux-5.7.8-200.fc32.x86_64-x86_64-with-glibc2.2.5) msrest/0.6.9 msrest_azure/0.6.3 azure-mgmt-storage/11.1.0 Azure-SDK-For-Python AZURECLI/2.9.0 (RPM)'
msrest.http_logger : Request body:
msrest.http_logger : {"sku": {"name": "Standard_RAGRS"}, "kind": "StorageV2", "location": "northeurope", "properties": {"encryption": {"services": {"blob": {}}, "keySource": "Microsoft.Storage"}}}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/247ec29e-9ce1-4f42-992e-8f31b28f471a/resourceGroups/rg-aip-test-001/providers/Microsoft.Storage/storageAccounts/foobarteststorageaccount?api-version=2019-06-01 HTTP/1.1" 200 None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Transfer-Encoding': 'chunked'
msrest.http_logger :     'Content-Type': 'application/json'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-request-id': 'd89ef4fe-4360-40b4-ac1d-25808e079079'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1193'
msrest.http_logger :     'x-ms-correlation-request-id': 'b102a755-4c04-471e-b8c4-9f5101ddd7ea'
msrest.http_logger :     'x-ms-routing-request-id': 'GERMANYNORTH:20200715T123637Z:b102a755-4c04-471e-b8c4-9f5101ddd7ea'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Wed, 15 Jul 2020 12:36:37 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {"sku":{"name":"Standard_RAGRS","tier":"Standard"},"kind":"StorageV2","id":"/subscriptions/247ec29e-9ce1-4f42-992e-8f31b28f471a/resourceGroups/rg-aip-test-001/providers/Microsoft.Storage/storageAccounts/foobarteststorageaccount","name":"foobarteststorageaccount","type":"Microsoft.Storage/storageAccounts","location":"northeurope","tags":{},"properties":{"privateEndpointConnections":[],"networkAcls":{"bypass":"AzureServices","virtualNetworkRules":[],"ipRules":[],"defaultAction":"Allow"},"supportsHttpsTrafficOnly":true,"encryption":{"services":{"file":{"keyType":"Account","enabled":true,"lastEnabledTime":"2020-07-15T12:35:02.6564343Z"},"blob":{"keyType":"Account","enabled":true,"lastEnabledTime":"2020-07-15T12:35:02.6564343Z"}},"keySource":"Microsoft.Storage"},"accessTier":"Hot","provisioningState":"Succeeded","creationTime":"2020-07-15T12:35:02.5782872Z","primaryEndpoints":{"dfs":"https://foobarteststorageaccount.dfs.core.windows.net/","web":"https://foobarteststorageaccount.z16.web.core.windows.net/","blob":"https://foobarteststorageaccount.blob.core.windows.net/","queue":"https://foobarteststorageaccount.queue.core.windows.net/","table":"https://foobarteststorageaccount.table.core.windows.net/","file":"https://foobarteststorageaccount.file.core.windows.net/"},"primaryLocation":"northeurope","statusOfPrimary":"available","secondaryLocation":"westeurope","statusOfSecondary":"available","secondaryEndpoints":{"dfs":"https://foobarteststorageaccount-secondary.dfs.core.windows.net/","web":"https://foobarteststorageaccount-secondary.z16.web.core.windows.net/","blob":"https://foobarteststorageaccount-secondary.blob.core.windows.net/","queue":"https://foobarteststorageaccount-secondary.queue.core.windows.net/","table":"https://foobarteststorageaccount-secondary.table.core.windows.net/"}}}
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f73fa7bfe50>, <function _x509_from_base64_to_hex_transform at 0x7f73fa7bfee0>]
Event: CommandInvoker.OnFilterResult []
{
  "accessTier": "Hot",
  "allowBlobPublicAccess": null,
  "azureFilesIdentityBasedAuthentication": null,
  "blobRestoreStatus": null,
  "creationTime": "2020-07-15T12:35:02.578287+00:00",
  "customDomain": null,
  "enableHttpsTrafficOnly": true,
  "encryption": {
    "keySource": "Microsoft.Storage",
    "keyVaultProperties": null,
    "requireInfrastructureEncryption": null,
    "services": {
      "blob": {
        "enabled": true,
        "keyType": "Account",
        "lastEnabledTime": "2020-07-15T12:35:02.656434+00:00"
      },
      "file": {
        "enabled": true,
        "keyType": "Account",
        "lastEnabledTime": "2020-07-15T12:35:02.656434+00:00"
      },
      "queue": null,
      "table": null
    }
  },
  "failoverInProgress": null,
  "geoReplicationStats": null,
  "id": "/subscriptions/247ec29e-9ce1-4f42-992e-8f31b28f471a/resourceGroups/rg-aip-test-001/providers/Microsoft.Storage/storageAccounts/foobarteststorageaccount",
  "identity": null,
  "isHnsEnabled": null,
  "kind": "StorageV2",
  "largeFileSharesState": null,
  "lastGeoFailoverTime": null,
  "location": "northeurope",
  "minimumTlsVersion": null,
  "name": "foobarteststorageaccount",
  "networkRuleSet": {
    "bypass": "AzureServices",
    "defaultAction": "Allow",
    "ipRules": [],
    "virtualNetworkRules": []
  },
  "primaryEndpoints": {
    "blob": "https://foobarteststorageaccount.blob.core.windows.net/",
    "dfs": "https://foobarteststorageaccount.dfs.core.windows.net/",
    "file": "https://foobarteststorageaccount.file.core.windows.net/",
    "internetEndpoints": null,
    "microsoftEndpoints": null,
    "queue": "https://foobarteststorageaccount.queue.core.windows.net/",
    "table": "https://foobarteststorageaccount.table.core.windows.net/",
    "web": "https://foobarteststorageaccount.z16.web.core.windows.net/"
  },
  "primaryLocation": "northeurope",
  "privateEndpointConnections": [],
  "provisioningState": "Succeeded",
  "resourceGroup": "rg-aip-test-001",
  "routingPreference": null,
  "secondaryEndpoints": {
    "blob": "https://foobarteststorageaccount-secondary.blob.core.windows.net/",
    "dfs": "https://foobarteststorageaccount-secondary.dfs.core.windows.net/",
    "file": null,
    "internetEndpoints": null,
    "microsoftEndpoints": null,
    "queue": "https://foobarteststorageaccount-secondary.queue.core.windows.net/",
    "table": "https://foobarteststorageaccount-secondary.table.core.windows.net/",
    "web": "https://foobarteststorageaccount-secondary.z16.web.core.windows.net/"
  },
  "secondaryLocation": "westeurope",
  "sku": {
    "name": "Standard_RAGRS",
    "tier": "Standard"
  },
  "statusOfPrimary": "available",
  "statusOfSecondary": "available",
  "tags": {},
  "type": "Microsoft.Storage/storageAccounts"
}
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f73fadaf310>]
az_command_data_logger : exit code: 0
telemetry.save : Save telemetry record of length 2539 in cache
telemetry.check : Negative: The /home/geewee/.azure/telemetry.txt was modified at 2020-07-15 14:34:46.422100, which in less than 600.000000 s
Command ran in 2.533 seconds (init: 0.062, invoke: 2.471)
```

**Comment by fengzhou-msft** [comment] 2020-08-12 02:44
The warning is caused by a dependency package `azure-multiapi-storage` and will be resolved by https://github.com/Azure/azure-multiapi-storage-python/pull/31

**Closed** 2020-08-20 02:02 UTC
Labels: Packaging
