### ISSUE TITLE
Cannot use my own SSL certificate with Enable-Https command

### ISSUE THREAD

**Issue by alexpilon666** [Azure/azure-cli#7644] opened 2018-10-23 03:01 UTC
Since the Preview and GA launch of the Standard_Microsoft CDN tier, we've been able, through the portal, and via the use of the Key Vault, to store and use our own SSL certificates.
Azure CLI hasn't been yet updated to support this feature (nor is it supporting the new Standard_Microsoft CDN Tier profile creation, but I've already submitted this elsewhere), so we cannot fully automate endpoint setup w/ custom https domain using Azure CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8c61db-b294-77fb-0e92-eae01d07b776
* Version Independent ID: 958b6e8d-609b-2a58-dbe1-240d3fd894bb
* Content: [az cdn custom-domain](https://docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest#az-cdn-custom-domain-enable-https)
* Content Source: [src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by alexpilon666** [comment] 2018-11-09 00:51
Haven't heard anything back in over two weeks.
Any idea when this will be implemented ?
Thanks.

**Comment by ChristianGottinger** [comment] 2019-01-16 06:37
Is there any suggested automated workaround?

**Comment by tjprescott** [comment] 2019-01-17 17:35
We'll reach out to the relevant team and provide an update this sprint.

**Comment by adewaleo** [comment] 2019-03-08 19:15
Moved this to backlog @devigned

**Comment by devigned** [comment] 2019-03-22 17:42
I'm not going to get to this until next week. #8855 will provide access to these operations via the updated management library. From there, the custom-https-enable and disable will need to be created allowing for either a provided certificate or a Key Vault source.

**Comment by nachakra** [comment] 2019-10-14 20:51
We are currently working on adding this support. It should be available by the end of next week.

**Comment by dmitrykarnitski** [comment] 2019-10-30 11:46
Hi,
could you please advise when the feature will be available for production purposes?

**Comment by lsmith130** [comment] 2020-02-13 17:01
Closing as a duplicate of #9894. A fix for this is in progress.

**Closed by lsmith130** 2020-02-13 17:01 UTC
Labels: CDN, Service Attention
