### ISSUE TITLE
Applying az resource tag fails

### ISSUE THREAD

**Issue by michaelnemtsev** [Azure/azure-cli#11074] opened 2019-11-02 11:14 UTC
## Describe the bug

**Command Name**
`az resource tag`

**Errors:**
```
'namespace'
Traceback (most recent call last):
pip-install-76yvurxi\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 575, in execute
cli\core\commands\__init__.py, ln 633, in _run_jobs_serially
cli\core\commands\__init__.py, ln 626, in _run_job
Temp\pip-install-76yvurxi\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 603, in _run_job
cli\core\commands\__init__.py, ln 305, in __call__
azure\cli\core\__init__.py, ln 470, in default_command_handler
cli\command_modules\resource\custom.py, ln 928, in tag_resource
cli\command_modules\resource\custom.py, ln 928, in <listcomp>
cli\command_modules\resource\custom.py, ln 802, in _get_rsrc_util_from_parsed_id
cli\command_modules\resource\custom.py, ln 1802, in __init__
cli\command_modules\resource\custom.py, ln 2005, in _resolve_api_version_by_id
KeyError: 'namespace'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az resource tag --tags {} --ids {}`

## Environment Summary
```
Windows-10-10.0.19013-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.68 *
azure-cli-ml 1.0.48

Extensions:
azure-cli-ml 1.0.48

```

**Comment by Juliehzl** [comment] 2019-11-03 09:28
Thanks for your feedback. We will look into it.

**Comment by Juliehzl** [comment] 2019-12-12 14:35
dupe of #11075

**Closed by Juliehzl** 2019-12-12 14:35 UTC
Labels: ARM
