### ISSUE TITLE
Modules require old msrestazure

### ISSUE THREAD

**Issue by ryancrawcour** [Azure/azure-cli#7721] opened 2018-10-30 23:23 UTC
When doing a pip install azure-cli you get the following errors showing up - 

zure-mgmt-datalake-analytics 0.2.0 has requirement msrestazure~=0.4.7, but you'll have msrestazure 0.5.0 which is incomatible.
zure-mgmt-recoveryservices 0.1.0 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.5.0 which is incomptible.
zure-mgmt-recoveryservicesbackup 0.1.1 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.5.0 which is incompatible.

It looks like Datalake Analytics, Recovery Service and Recovery Services Backup modules need to be updated to take requirements on the current version of msrestazure, 0.5.0.

**Comment by tjprescott** [comment] 2018-10-31 17:16
Closing as this is a duplicate of #6973. We are actively working with the relevant service teams to move their modules to the newer version of msrestazure.

**Closed by tjprescott** 2018-10-31 17:16 UTC
