### ISSUE TITLE
az aks get-credentials not returning access-profile

### ISSUE THREAD

**Issue by xinyiou** [Azure/azure-cli#5218] opened 2018-01-06 01:36 UTC
I am using Azure-CLI version 2.0.24, however `az aks get-credentials` is not working.

I am getting the following error:

> 'ManagedCluster' object has no attribute 'properties'
Traceback (most recent call last):
  File "/home/xiou/lib/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/xiou/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/home/xiou/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/home/xiou/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/home/xiou/lib/azure-cli/local/lib/python2.7/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/home/xiou/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "/home/xiou/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1329, in aks_get_credentials
    access_profiles = mc.properties.access_profiles
AttributeError: 'ManagedCluster' object has no attribute 'properties'

**Comment by vpopescu** [comment] 2018-01-06 05:39
I am just seeing this as well, where it was previously working.

**Comment by markphillips100** [comment] 2018-01-06 05:49
@vpopescu I was seeing that message for v2.0.21 hence I upgraded to v2.0.24 and now see same as @xinyiou.

I'm wondering if it's anything to do with patching upgrades due to the global cpu issue in the news.  Just saying cos everything was working fine yesterday and now both my laptop and desktop have these issues with no cluster changes from me over the last 24 hours.

**Comment by marratj** [comment] 2018-01-06 17:42
I see exactly the same issue with v2.0.24. 

Provisioning new clusters works just fine, however `az aks get-credentials` gives me the same error as @xinyiou

**Comment by jakobehn** [comment] 2018-01-07 10:57
+1, also started happening for me yesterday. Seeing "No Kubernetes access profiles found. Cluster provisioning state is "Succeeded" with v2.0.21 of the CLI

**Comment by sprab** [comment] 2018-01-07 11:18
This looks like an issue with the Azure CLI.
I downloaded v2.0.23 from https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.0.23.msi and was able to login to the aks cluster.

**Comment by jakobehn** [comment] 2018-01-07 12:02
@sprab Thanks, upgrading to 2.0.23 did the trick for me.

**Comment by mdoulaty** [comment] 2018-01-07 13:25
I was having the same error with v2.0.24 (AttributeError: 'ManagedCluster' object has no attribute 'properties') and No Kubernetes access profiles found. Cluster provisioning state is "Succeeded" with v2.0.21 of the CLI.
Seems like v2.0.23 is the one which works as expected for the aks operations.

**Comment by amityo** [comment] 2018-01-07 15:10
I have the same issue with 2.0.24

**Comment by rajesh-chawla** [comment] 2018-01-07 15:57
Also have the same issue using the versions below. Any suggestions / workarounds appreciated.
az --version
azure-cli (2.0.24)

acr (2.0.18)
acs (2.0.23)

**Comment by sprab** [comment] 2018-01-07 15:58
@rajesh-chawla 
This looks like an issue with the Azure CLI.
I downloaded v2.0.23 from https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.0.23.msi and was able to login to the aks cluster.

Alternatively you can also try logging in from the Azure CloudShell Bash

**Comment by ziXet** [comment] 2018-01-07 16:37
+1

**Comment by rajesh-chawla** [comment] 2018-01-07 20:58
I was able to create, download credentials and execute 'kubectl get nodes' using the version 2.0.23.
Appreciate the work around.

Details:
>az --version
azure-cli (2.0.23)

acr (2.0.17)
acs (2.0.22)

**Comment by sabbour** [comment] 2018-01-08 07:00
Workarounds for macOS? I started getting the error on azure-cli (2.0.20) and still got the error on (2.0.24).

Fortunately the Homebrew version is still at 2.0.23.

**Comment by bramvdklinkenberg** [comment] 2018-01-08 08:57
Same issue here with an AKS cluster.

azure-cli (2.0.22)
aks (1.7.7)

**Comment by sethtregenna** [comment] 2018-01-08 09:29
+1 on this  having just upgraded  to 2.0.24 on Ubuntu.

$ az --version
azure-cli (2.0.24)

$ az aks get-credentials -n dnatrial -g rg-dnatrial
'ManagedCluster' object has no attribute 'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1329, in aks_get_credentials
    access_profiles = mc.properties.access_profiles
AttributeError: 'ManagedCluster' object has no attribute 'properties'

**Comment by MariuszJozala-Avaleo** [comment] 2018-01-08 09:44
Same problem here with Ubuntu and azure-cli 2.0.24-1:

> 'ManagedCluster' object has no attribute 'properties'
> Traceback (most recent call last):
>   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
>     six.reraise(*sys.exc_info())
>   File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
>     result = cmd(params)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
>     return super(AzCliCommand, self).__call__(*args, **kwargs)
>   File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
>     return self.handler(*args, **kwargs)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
>     result = op(**command_args)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1329, in aks_get_credentials
>     access_profiles = mc.properties.access_profiles
> AttributeError: 'ManagedCluster' object has no attribute 'properties'

After downgrading to azure-cli 2.0.23-1 with command `sudo apt-get install azure-cli=2.0.23-1` it works fine.

**Comment by sethtregenna** [comment] 2018-01-08 10:28
I can confirm that downgrading to 2.0.23-1 as @MariuszJozala-Avaleo suggests works.

**Comment by frank-montyne** [comment] 2018-01-08 11:37
Got the error when coming back from vacation. I was using 2.2.0. I just upgraded to 2.0.24 on OSX and get the same errors as mentioned in other posts.

BTW: How can I manually install 2.2.23 on OSX? Brew doesn't work, seems to have problems with python3 and I don't want to mess up my OSX install also...

**Comment by frank-montyne** [comment] 2018-01-08 11:38
I meant 2.0.23 of course and was using 2.0.2...

**Comment by luayalem** [comment] 2018-01-08 13:46
'brew upgrade azure-cli' should do it for you since 2.0.23 is the brew stable version.
brew info azure-cli
azure-cli: stable 2.0.23 (bottled), HEAD

**Comment by luayalem** [comment] 2018-01-08 14:11
do not make the mistake I made and upgraded to 2.0.23 on MAC you will run to this issue #5184 which will break azure-cli.

**Comment by frank-montyne** [comment] 2018-01-08 17:01
Unfortunately I get this error now:

>az login

field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.23/libexec/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.23/libexec/lib/python3.6/site-packages/azure/cli/core/application.py", line 141, in execute
    self.refresh_request_id()
  File "/usr/local/Cellar/azure-cli/2.0.23/libexec/lib/python3.6/site-packages/azure/cli/core/application.py", line 269, in refresh_request_id
    self.session['headers']['x-ms-client-request-id'] = str(uuid.uuid1())
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)

**Comment by frank-montyne** [comment] 2018-01-08 17:02
Brew related info:

brew info azure-cli
azure-cli: stable 2.0.23 (bottled), HEAD
Microsoft Azure CLI 2.0
https://docs.microsoft.com/cli/azure/overview
/usr/local/Cellar/azure-cli/2.0.23 (8,748 files, 49.3MB) *
  Poured from bottle on 2018-01-08 at 17:43:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/azure-cli.rb
==> Dependencies
Required: openssl ✔
==> Requirements
Required: python3 ✔
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

**Comment by frank-montyne** [comment] 2018-01-08 17:06
Hello Microsoft!
This is prevents a lot of people of using managed AKS Kubernetes!
Any workaround is appreciated!

**Comment by derekbekoe** [comment] 2018-01-08 17:10
cc: @mboersma

**Comment by mboersma** [comment] 2018-01-08 18:49
It appears that some CLI changes in #5086 were lost in this release? We're working on a fix, but for the time being I think the only workaround is to use the previous 2.0.23 release.

**Comment by malachma** [comment] 2018-01-08 19:43
The issue with "az aks get-credentials" gets also reproduced with azure-cli (2.0.20)
In a cloud-shell environemnt with 2.0.23 I'm able to get the credentials

**Comment by mboersma** [comment] 2018-01-08 19:53
Note that if you installed the azure-cli with `pip` (which isn't an officially supported method), you may have to [install all requirements explicitly](https://github.com/Azure/azure-cli/issues/5223#issuecomment-356063391) to get to a working 2.0.23 version.

**Comment by branstraub** [comment] 2018-01-11 16:43
Is there any fix on MacOS?
Thxs!

**Comment by frank-montyne** [comment] 2018-01-11 16:54
I removed the current installation that used the install script and then
installed cli 2.0.23 using HomeBrew. That did the trick for now.

Best regards,
Frank

**Comment by benc-uk** [comment] 2018-01-12 11:30
I'm giving a demo of AKS at an event next week, this does not look good. 
This is the 2nd time the CLI has broken support for AKS, please can we have an ETA on a fix?

**Comment by bramvdklinkenberg** [comment] 2018-01-12 11:47
@benc-uk just make sure you use 2.0.23 and everything will work :)

**Comment by benc-uk** [comment] 2018-01-12 11:51
@bramvdklinkenberg Thanks, I've rolled back using apt and installed .23 and it's working again. Phew!

**Comment by ComeMaes** [comment] 2018-01-12 11:53
@frank-montyne Are there any steps to install 2.0.23 via HomeBrew if you don't have this version locally? The current formula is 2.0.24_1, which does not fix 2.0.24. I can't seem to be able to switch to a older version of azure-cli - I don't have 2.0.23 locally.
@benc-uk According to [this comment](https://github.com/Azure/AKS/issues/113#issuecomment-356377129), 2.0.25 is scheduled for january 17th.

**Comment by ormico** [comment] 2018-01-12 14:30
just came in today and found this error.
I'm on v2.0.21
How can I get a copy of 2.0.23?

**Comment by ormico** [comment] 2018-01-12 15:02
looking for the Windows msi for 2.0.23

**Comment by derekbekoe** [comment] 2018-01-12 15:07
https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.0.23.msi for the previous msi

**Comment by davidwholland** [comment] 2018-01-12 18:56
@derekbekoe How did you find that link? Are previous versions listed somewhere?

**Comment by derekbekoe** [comment] 2018-01-12 19:37
@davidwholland The main install link, https://aka.ms/InstallAzureCliWindows, has a redirect that points to the latest versions. You can go back to older versions by modifying the URL.

```
$ curl https://aka.ms/installazurecliwindows
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.0.24.msi">here</a>.</h2>
</body></html>
```

**Comment by davidwholland** [comment] 2018-01-12 20:40
@derekbekoe nice, thanks!

**Comment by gmagniez** [comment] 2018-01-16 11:09
For macos:
`brew unlink azure-cli //if already installed
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d8a64440c3944f1dfde4f1bb228d7218868c636f/Formula/azure-cli.rb` // Commit of 2.023 formula

**Comment by ovhemert** [comment] 2018-01-16 16:17
@gmagniez nice... works great!

**Comment by derekbekoe** [comment] 2018-01-17 18:54
2.0.25 has been released which should include this fix.

**Comment by benc-uk** [comment] 2018-01-17 22:42
Can confirm 2.0.25 fixes the issue

**Comment by rajshakerp** [comment] 2018-01-24 06:43
I am seeing the same issue on 2.0.25 too, I tried on **Windows 10 as well as Windows Server 2016** However 2.0.23 is working for me.

**Comment by tjprescott** [comment] 2018-01-24 17:08
@mboersma

**Comment by mboersma** [comment] 2018-01-24 17:53
@rajshakerp I tried with v2.0.25 in an Azure Windows PowerShell and it's working there:
```console
PS Azure:\> az --version
azure-cli (2.0.25)
PS Azure:\> az aks get-credentials -g clitestvf7i5xnlcs -n cliakstesttiknj6
Merged "cliakstesttiknj6" as current context in C:\Users\ContainerAdministrator\.kube\config
```

Could you post the stack trace or error you're seeing?

**Comment by ryankmcintyre** [comment] 2018-01-24 22:48
Using 2.0.25 in bash on WSL and it's working. Previously got an error on 2.0.22.

**Comment by markmcdermid** [comment] 2018-01-25 13:11
Confirmed working with 2.0.25 on Mac OS X too.

**Comment by salmicrosoft** [comment] 2018-01-26 23:52
2.0.25 working on Mac OSX via manual install and via homebrew

**Comment by jochenvanwylick** [comment] 2018-02-01 14:04
2.0.26 solved it for me on Win10

**Comment by tjprescott** [comment] 2018-02-01 17:18
In that case, I will close this.  @rajshakerp if you are still encountering a problem, please open a new issue.

**Closed by tjprescott** 2018-02-01 17:18 UTC
Labels: ACS
