### ISSUE TITLE
[--query] parameter does not acknowledge Boolean values

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#18511] opened 2021-06-16 15:01 UTC
The following syntax does not return a value:
![image](https://user-images.githubusercontent.com/58762114/122242368-42ba0880-ce91-11eb-90f0-fc2dc8e3f129.png)

I’ve also tried 
* az account list –query “[?isDefault==true]”          --this returns the entire list including ‘false’ values
 
According to <https://jmespath.org/proposals/improved-filters.html> page, the customer should be able to ask
* az account list –query “[?isDefault == ‘true’]”      /or/
* az account list –query “[?isDefault]”                        --Boolean values are assumed “is true”
![image](https://user-images.githubusercontent.com/58762114/122242513-62513100-ce91-11eb-8f01-edb3302bcf1d.png)

**This issue is not about finding the current subscription** -- az account list is only being used for an example.  This issue was encountered when trying to build out [Query Azure CLI command output](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli) that has a mention of Boolean values [here](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli#change-output).  This issue originated in email thread with subject "About Az (resource) list has filtering option".

**Comment by yonzhan** [comment] 2021-06-16 15:05
@jsntcy for awareness

**Comment by booyaa** [comment] 2021-06-17 10:36
@dbradish-microsoft the quote around the `true` value is a backtick, not a regular single quote. The following should return data

```sh
az account list --query "[?isDefault == \`true\`]"
```

note: we need to escape the backtick because it's used for command substitution in any bash-like shell (zsh included)

Also, the proposed specification you cited has been implemented because we can do something nicer looking

```sh
az account list --query "[?isDefault]"
```

**Comment by dbradish-microsoft** [comment] 2021-06-17 15:27
@booyaa, Thank you!  I'll add your working example to a couple of articles that need clarification.  I don't close issues in this repo, but as far as I'm concerned, this issue is resolved.

**Comment by jsntcy** [comment] 2021-06-18 02:11
@dbradish-microsoft, could you please verify if the issue is resolved? Once it's resolved, we'll close this issue.

**Comment by dbradish-microsoft** [comment] 2021-06-19 01:41
@jsntcy, I don't close issues in this repo, but as far as I'm concerned, this issue is resolved.

**Closed** 2021-06-19 14:49 UTC
Labels: Customer Usage, Output Query, Usability
