### ISSUE TITLE
`az webapp up` does not target existing web apps as expected

### ISSUE THREAD

**Issue by nickwalkmsft** [Azure/azure-cli#9955] opened 2019-07-16 20:06 UTC
**Describe the bug**
`az webapp up` does not behave as expected when attempting to target an existing web app for deployment.

**To Reproduce**
Target an existing web app with `--name` and `--resource-group`, which are enough to disambiguate/fully specify in most `az` commands. The command will find the resource group, but will then create a new App Service plan without checking to see if the app already exists. Then, it will try to create the app and fail with the confusing error message "Cannot update the site <sitename> because it uses AlwaysOn feature which is not allowed in the target compute mode."

The same behavior occurs if specifying an existing web app by its resource id with `--id`.

**Expected behavior**
The existing app should be detected and targeted.

**Environment summary**
Cloud shell:
Linux-4.15.0-1050-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash
azure-cli 2.0.68 *

**Additional context**
The only way I've gotten this to work is by explicitly specifying all of `--name`, `--resource-group`, `--plan` and `--sku`.

**Comment by panchagnula** [comment] 2019-07-16 23:35
@nickwalkmsft - the problem is that we need the ASP name to target the app - try to use the command with --plan parameter as well for now. Have an item on my plate to make this experience better.

**Comment by panchagnula** [comment] 2019-08-07 20:44
Moving this to next sprint release

**Closed** 2019-09-18 17:31 UTC
Labels: Bug, Service Attention, Web Apps
