### ISSUE TITLE
No info on logging output double spacing

### ISSUE THREAD

**Issue by jgaardsted** [Azure/azure-cli#26545] opened 2023-05-26 10:35 UTC
I have been using the log command since 2017 daily at work.
I see no info about why its output appears doubly spaced (line breaks),
and how to control this behaviour (which is very annoying, it wastes half the screen space.)
I have experimented with leaving out line breaks to avoid it,
but this causes the opposite problem of log lines sometimes not being line-separated.
Its behaviour is also inconsistent - the 'no new trace' msg is not doubly spaced.

2023-05-26T10:27:56.073807403Z       Done Import06.

2023-05-26T10:27:56.073811003Z warn: int[0]

2023-05-26T10:27:56.073814603Z       Done implImportIfcFile_05.

2023-05-26T10:27:56.073818303Z warn: int[0]

2023-05-26T10:27:56.073821903Z        Import Completed.

2023-05-26T10:27:56.150789597Z warn: int[0]

2023-05-26T10:27:56.150821697Z       cleaning up IFC-file..
2023-05-26T10:27:59  Stream terminated due to timeout 120 min(s).
2023-05-26T10:28:00    Error occurred, type: error, text: LogStreamManager: Inside TerminateClient

2023-05-26T10:28:00    Error occurred, type: error, text: LogStreamManager: Inside Reset
2023-05-26T10:29:24  No new trace in the past 1 min(s).
2023-05-26T10:30:24  No new trace in the past 2 min(s).
2023-05-26T10:31:24  No new trace in the past 3 min(s).
2023-05-26T10:32:24  No new trace in the past 4 min(s).
2023-05-26T10:33:24  No new trace in the past 5 min(s).
2023-05-26T10:34:24  No new trace in the past 6 min(s).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bee2e287-5fb7-a849-9d3b-87013b783f16
* Version Independent ID: 97f9e1c4-1573-b776-0fce-53c65839d713
* Content: [az webapp log](https://learn.microsoft.com/en-US/cli/azure/webapp/log?view=azure-cli-latest#az_webapp_log_show)
* Content Source: [latest/docs-ref-autogen/webapp/log.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/log.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2023-05-26 10:35
Thank you for opening this issue, we will look into it.

**Comment by pylgrym** [comment] 2023-06-22 06:46
Command-line in powershell of course has the effect.

Log Stream _in the azure UI_ (which is kudu, I assume?) shows it too.

If I instead click 'https://aoc-linux-api-test.scm.azurewebsites.net/api/logstream'
under the 'advanced tools' (which I also assume is kudu?),
that page never loads (in firefox), instead it shows up as perpetually downloading?

The effect persists across all my web services, both dotnet core and old dotnet.
If I try to tail that download, I only get

/home/LogFiles/kudu/trace/ebed1b382ce1-3caf6b5d-8e10-4531-a565-9324796772c0.txt  (https://aoc-linux-api-test.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/ebed1b382ce1-3caf6b5d-8e10-4531-a565-9324796772c0.txt)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(H

I wonder, are there other mechanisms that can be used to connect to the log source..

**Comment by jgaardsted** [comment] 2023-06-29 09:32
This is really strange.. Today, I helped a colleague set up another azure app service,
and configure logging for it. Lo and behold, the weird formatting problem was gone??

Then I went back to my previous/most recent webservice (the one I used to report this thread),
and the bug/behaviour was fixed on that one too??

This is strange to me, as I have been used to seeing this weird behaviour since around 2017..

So, I wonder if something has been fixed on the azure side.

On the short term, I am quite happy, as I now have 'working-as-inspected' useful practical log acess to azure/our azure app services.
So that, this issue should probably be closed(?).

On the longer/forward perspective, I think dotnetcore application developers would probably like some interface/control through which to format the azure logging channel(*).
The only logging providers that allow formatting, to my knowledge, are.. the Console log source, I think?
(which is problematic to use on azure if even possible.)

(*) I am not sure to which extent formatting makes sense. If log is 'string linebased', it does.
But if logging is semantic, ie includes scopes and/or {0} {1} debug objects, an interface for formatting may be "a broken design".
Anyway, the use case is, that some shops would prefer to see the context class in the log, and other shops, like mine, prefer to avoid the context class listed in the log.
(so instead of formatting options, maybe it's really just a choice of two kinds of fixed log?).

Whatever, I'm happy for now, if this is indeed a fix :-).

**Comment by jgaardsted** [comment] 2023-06-29 09:33
To wit, this is how the log suddenly looks, "correct":
2023-06-29T09:21:09  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2023-06-29 09:21:39.262 +00:00 [Warning] int: home 6/29/2023 9:21:39 AM #0:
2023-06-29 09:21:39.294 +00:00 [Error] int: home 6/29/2023 9:21:39 AM #0:
2023-06-29 09:21:39.298 +00:00 [Critical] int: home 6/29/2023 9:21:39 AM #0:

**Comment by btardif** [comment] 2023-07-05 15:07
@jgaardsted you are not seeing the extra line breaks because the new app you are looking at is hosted on windows.

We have a repro on Linux and have identified a fix.

**Comment by tulikac** [comment] 2023-07-12 15:15
This is a confirmed issue on Kudu and we are working on a fix.

**Comment by tulikac** [comment] 2023-09-20 14:37
Fix is rolling out. Should be done in the next couple of weeks.

**Comment by btardif** [comment] 2023-09-21 21:42
@tulikac if change is checked in, can we link to the PR and close this issue?

**Comment by btardif** [comment] 2023-10-04 14:56
This should now be fixed with the latest CLI update.

**Closed** 2023-10-04 14:56 UTC
Labels: Web Apps, Service Attention, customer-reported, Auto-Assign, app-service-logging-monitoring
