### ISSUE TITLE
az vmss extension set fails with "Max price change is not allowed."

### ISSUE THREAD

**Issue by belgiajong** [Azure/azure-cli#13974] opened 2020-06-16 00:07 UTC
I deployed a VMSS with 4 spot instances and custom script extension. ~~Upon trying to update the custom script extension (running az vmss extension set again),~~ I got the above error. Full error message: "Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages"

The max price is currently set to -1. Azure CLI is on version 2.7.0.

Edit: this fails during initial deployment, not during update.

**Comment by yungezz** [comment] 2020-06-16 01:36
hi @belgiajong could you pls share reproduce steps?

**Comment by qwordy** [comment] 2020-06-16 04:58
And could you append --debug to the end of the command and post the result?

**Comment by belgiajong** [comment] 2020-06-16 17:16
Command with debug output: [customScriptOutput.txt](https://github.com/Azure/azure-cli/files/4788096/customScriptOutput.txt)

Steps:
1. Create resource group
2. Create VMSS
3. Assign "virtual machine contributor" identity to VMSS 
4. Disable Windows update
5. Create storage account
6. Deploy custom script extension
Script finishes running successfully.
7. Redeploy custom script extension - hit error above

**Comment by belgiajong** [comment] 2020-06-22 17:13
@qwordy and @yungezz any updates?

**Comment by yungezz** [comment] 2020-08-03 14:39
hi @qwordy @Yao725 could you pls look at the issue?

**Comment by qwordy** [comment] 2020-09-08 11:19
According to logs, the original value is -1, the value in PUT operation is also -1. Service issue. Add a service attention label for confirmation.

**Comment by amjads1** [comment] 2020-09-08 19:32
Assigned to @avirishuv to look into this issue.

**Comment by Drewm3** [comment] 2020-09-24 21:11
This is a bug, and we are working with the dev team to understand the fix timeline.

**Comment by Drewm3** [comment] 2020-12-03 22:21
Just to provide an update on this. The issue is still on our backlog to be fixed in a future milestone, but we do not yet have a timeframe to share as to when we expect the fix to be available.

**Comment by avirishuv** [comment] 2021-03-03 20:01
apologies for the delay here, this is yet to be picked up development. We don't have final timelines yet, but it should be picked up sometime next month. Will keep you posted on the updates.

**Comment by avirishuv** [comment] 2021-03-17 19:42
hi @qwordy are you still facing this issue? the dev team is unable to repro. If any more details can be shared that may help.

**Comment by qwordy** [comment] 2021-03-18 02:36
@avirishuv This is the logs. The old value of the VMSS is -1, new value in request is still -1. Full logs are available in previous comment.
@belgiajong Does this error still occur?
```
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/3b3496e1-b95d-44f7-9506-cab111737643/resourceGroups/CSpotjoh/providers/Microsoft.Compute/virtualMachineScaleSets/CSpotjoh?api-version=2019-12-01'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '3491'
msrest.http_logger :     'User-Agent': 'python/3.6.6 (Windows-10-10.0.19041-SP0) msrest/0.6.9 msrest_azure/0.6.3 azure-mgmt-compute/12.0.0 Azure-SDK-For-Python AZURECLI/2.7.0 (MSI)'
msrest.http_logger : Request body:
msrest.http_logger : {"location": "eastus", "tags": {}, "sku": {"name": "Standard_A1_v2", "tier": "Standard", "capacity": 4}, "properties": {"upgradePolicy": {"mode": "Automatic"}, "virtualMachineProfile": {"osProfile": {"computerNamePrefix": "cspotf520", "adminUsername": "AzureAdmin", "windowsConfiguration": {"provisionVMAgent": true, "enableAutomaticUpdates": true}, "secrets": []}, "storageProfile": {"imageReference": {"publisher": "MicrosoftWindowsServer", "offer": "WindowsServer", "sku": "2016-Datacenter", "version": "latest"}, "osDisk": {"caching": "ReadWrite", "createOption": "FromImage", "diskSizeGB": 127, "managedDisk": {"storageAccountType": "Standard_LRS"}}}, "networkProfile": {"networkInterfaceConfigurations": [{"name": "cspotf520Nic", "properties": {"primary": true, "enableAcceleratedNetworking": false, "networkSecurityGroup": {"id": "/subscriptions/3b3496e1-b95d-44f7-9506-cab111737643/resourceGroups/CSpotjoh/providers/Microsoft.Network/networkSecurityGroups/CSpotjohNSG"}, "dnsSettings": {"dnsServers": []}, "ipConfigurations": [{"name": "cspotf520IPConfig", "properties": {"subnet": {"id": "/subscriptions/3b3496e1-b95d-44f7-9506-cab111737643/resourceGroups/CSpotjoh/providers/Microsoft.Network/virtualNetworks/CSpotjohVNET/subnets/CSpotjohSubnet"}, "privateIPAddressVersion": "IPv4", "loadBalancerBackendAddressPools": [{"id": "/subscriptions/3b3496e1-b95d-44f7-9506-cab111737643/resourceGroups/CSpotjoh/providers/Microsoft.Network/loadBalancers/CSpotjohLB/backendAddressPools/CSpotjohLBBEPool"}], "loadBalancerInboundNatPools": [{"id": "/subscriptions/3b3496e1-b95d-44f7-9506-cab111737643/resourceGroups/CSpotjoh/providers/Microsoft.Network/loadBalancers/CSpotjohLB/inboundNatPools/CSpotjohLBNatPool"}]}}], "enableIPForwarding": false}}]}, "extensionProfile": {"extensions": [{"name": "Microsoft.Azure.Geneva.GenevaMonitoring", "properties": {"publisher": "Microsoft.Azure.Geneva", "type": "GenevaMonitoring", "typeHandlerVersion": "2.0", "autoUpgradeMinorVersion": true, "settings": {}}}, {"name": "CustomScriptExtension", "properties": {"forceUpdateTag": "87f85dcc-aef1-4388-ba96-5a6d3879a3d3", "publisher": "Microsoft.Compute", "type": "CustomScriptExtension", "typeHandlerVersion": "1.10", "autoUpgradeMinorVersion": true, "settings": {"fileUris": ["https://johstorageaccount.blob.core.windows.net/azpecanary/AzPECanary.zip", "https://johstorageaccount.blob.core.windows.net/azpecanary/AzPECanaryLifeCycleMonitor.zip", "https://johstorageaccount.blob.core.windows.net/azpecanary/startCanary.ps1", "https://johstorageaccount.blob.core.windows.net/azpecanary/runGenevaAgent.cmd", "https://johstorageaccount.blob.core.windows.net/azpecanary/cert.pfx", "https://johstorageaccount.blob.core.windows.net/azpecanary/TLSSettings.ps1"], "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File startCanary.ps1 -LogConnectionString DefaultEndpointsProtocol=https;AccountName=canjoh;AccountKey=qoIyDxwELHpeIlrLv7uQ39k9wnwxnNyLjGutXnEgSkfh0+lEKs+Qvx85lSAAMiCdLRA8TLXbD3e/TUYR7o9M9g==;EndpointSuffix=core.windows.net -NumOfVMs 4"}, "protectedSettings": {"storageAccountName": "johstorageaccount", "storageAccountKey": "guNSCLl5+2qwx9LMENXyUnCoYJc3GTI7OLCItS7mjueVp6eDaG30jYB8ZEH7q8TxzZF0OEii/3UynWOklUn62w=="}}}]}, "priority": "Spot", "evictionPolicy": "Deallocate", "billingProfile": {"maxPrice": -1.0}}, "overprovision": true, "doNotRunExtensionsOnOverprovisionedVMs": false, "singlePlacementGroup": false, "platformFaultDomainCount": 1}, "identity": {"type": "SystemAssigned"}}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/3b3496e1-b95d-44f7-9506-cab111737643/resourceGroups/CSpotjoh/providers/Microsoft.Compute/virtualMachineScaleSets/CSpotjoh?api-version=2019-12-01 HTTP/1.1" 409 1367
msrest.http_logger : Response status: 409
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Length': '1367'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/CreateVMScaleSet3Min;59,Microsoft.Compute/CreateVMScaleSet30Min;291'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'x-ms-request-id': '37136116-5b62-44ae-8a46-8e19631d06d0'
msrest.http_logger :     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-correlation-request-id': '824e88a1-fdda-4620-bb17-8b2b57d4e58e'
msrest.http_logger :     'x-ms-routing-request-id': 'NORTHCENTRALUS:20200616T064844Z:824e88a1-fdda-4620-bb17-8b2b57d4e58e'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Tue, 16 Jun 2020 06:48:44 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {
  "error": {
    "details": [
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM 'CSpotjoh_0' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "CSpotjoh_0"
      },
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM 'CSpotjoh_1' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "CSpotjoh_1"
      },
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM 'CSpotjoh_2' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "CSpotjoh_2"
      },
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM 'CSpotjoh_3' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "CSpotjoh_3"
      }
    ],
    "code": "OperationNotAllowed",
    "message": "Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages"
  }
}
msrest.exceptions : Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages
cli.azure.cli.core.util : Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages
Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages
```

**Comment by hitesh-raichandani** [comment] 2021-05-24 15:15
Hi, I am seeing the same issue. Repro steps:
1. launch a vmss with load balancer
2. create a nat pool using cli
```
$az network lb inbound-nat-pool create \
    --resource-group dev-hitesh-cluster0162-cs-interactive0  \
    --lb-name dev-hitesh-cluster0162-cs-interactive0 -LoadBalancer \
    --name MyRule \
    --protocol Tcp \
    --backend-port 1093 \
    --frontend-port-range-end 1393 \
    --frontend-port-range-start 1093

$az vmss update \
      -g dev-hitesh-cluster0162-cs-interactive0  \
      -n 1621550401-VMSS \
      --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].loadBalancerInboundNatPools "{'id':'/id/of/MyRule'}"

$ az vmss update-instances \
          --instance-ids "*" \
          --resource-group dev-hitesh-cluster0162-cs-interactive0  \
          --name 1621550401-VMSS
```

Getting error on last step.
debug logs for `az vmss update-instances`:
```
cli.knack.cli: Command arguments: ['vmss', 'update-instances', '--instance-ids', '*', '--resource-group', 'dev-hitesh-cluster0162-cs-interactive0', '--name', '1621550401-VMSS', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x101029310>, <function OutputProducer.on_global_arguments at 0x1010a6160>, <function CLIQuery.on_global_arguments at 0x1010c2940>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'vmss': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.095        44       225
cli.azure.cli.core: Total (1)                 0.095        44       225
cli.azure.cli.core: Loaded 44 groups, 225 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : vmss update-instances
cli.azure.cli.core: Command table: vmss update
cli.azure.cli.core: remaining    :             instances
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10215fd30>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/tesh/.azure/commands/2021-05-20.17-00-22.vmss_update-instances.59415.log'.
az_command_data_logger: command args: vmss update-instances --instance-ids {} --resource-group {} --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x102180f70>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x1021db550>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1021db5e0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1021db700>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x1010a61f0>, <function CLIQuery.handle_query_parameter at 0x1010c29d0>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x1021db4c0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1021db670>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file /Users/tesh/.azure/accessTokens.json as utf-8-sig
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - Authority:Performing instance discovery: ...
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - Authority:Performing static instance discovery
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - Authority:Authority validated via static instance discovery
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - CacheDriver:Found 2 potential entries.
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - CacheDriver:Resource specific token found.
adal-python: 7323fc9a-f9b8-477d-9ac7-d38b11316f6d - CacheDriver:Returning token from cache lookup, AccessTokenId: b'rOeeDLj7j819v2c4jGOYEdRP5vrMlXZ+Lv6CiwFQ80Y=', RefreshTokenId: b'nt5a+CFDdp2HnA44MNs7ML+iX1OOfJasmmQRnEEeUmE='
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<sub_id>/resourceGroups/dev-hitesh-cluster0162-cs-interactive0/providers/Microsoft.Compute/virtualMachineScaleSets/1621550401-VMSS/manualupgrade?api-version=2020-12-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '22'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '89e1a86e-b9c7-11eb-883d-1e2940089855'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vmss update-instances'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--instance-ids --resource-group --name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.23.0 (HOMEBREW) azsdk-python-azure-mgmt-compute/20.0.0 Python/3.8.10 (macOS-11.3.1-arm64-i386-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"instanceIds": ["*"]}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/<sub_id>/resourceGroups/dev-hitesh-cluster0162-cs-interactive0/providers/Microsoft.Compute/virtualMachineScaleSets/1621550401-VMSS/manualupgrade?api-version=2020-12-01 HTTP/1.1" 409 2035
cli.azure.cli.core.sdk.policies: Response status: 409
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '2035'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/VMScaleSetActions3Min;238,Microsoft.Compute/VMScaleSetActions30Min;1198'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'a8af1457-46e5-4513-93e6-f7751829d21a'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '40c83900-441a-46ec-8ee4-871afc8eed3d'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS:20210521T000023Z:40c83900-441a-46ec-8ee4-871afc8eed3d'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 21 May 2021 00:00:22 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "details": [
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM '1621550401-VMSS_0' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "1621550401-VMSS_0"
      },
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM '1621550401-VMSS_1' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "1621550401-VMSS_1"
      },
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM '1621550401-VMSS_2' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "1621550401-VMSS_2"
      },
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM '1621550401-VMSS_4' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "1621550401-VMSS_4"
      },
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM '1621550401-VMSS_5' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "1621550401-VMSS_5"
      },
      {
        "code": "OperationNotAllowed",
        "message": "Max price change is not allowed when the VM '1621550401-VMSS_6' is currently allocated. Please deallocate and try again. For more information, see http://aka.ms/AzureSpot/errormessages",
        "target": "1621550401-VMSS_6"
      }
    ],
    "code": "OperationNotAllowed",
    "message": "Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages"
  }
}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 2962, in update_vmss_instances
    return sdk_no_wait(no_wait, client.virtual_machine_scale_sets.begin_update_instances,
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/util.py", line 648, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/mgmt/compute/v2020_12_01/operations/_virtual_machine_scale_sets_operations.py", line 1853, in begin_update_instances
    raw_result = self._update_instances_initial(
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/mgmt/compute/v2020_12_01/operations/_virtual_machine_scale_sets_operations.py", line 1811, in _update_instances_initial
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/opt/homebrew/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/core/exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: (OperationNotAllowed) Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages

cli.azure.cli.core.azclierror: (OperationNotAllowed) Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages
az_command_data_logger: (OperationNotAllowed) Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10215ff70>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.492 seconds (init: 0.055, invoke: 0.437)
telemetry.save: Save telemetry record of length 3267 in cache
telemetry.check: Negative: The /Users/tesh/.azure/telemetry.txt was modified at 2021-05-20 17:00:18.510651, which in less than 600.000000 s
```

**Comment by avirishuv** [comment] 2021-06-17 18:29
quick update: a fix is currently in progress, and will update here once it is rolled out.

**Comment by avirishuv** [comment] 2021-09-09 19:28
The fix roll out has completed for this issue.
Can you please confirm that this is not happening any more? And if so, are we good to close the issue?

**Comment by avirishuv** [comment] 2021-09-16 23:19
Given the fix has rolled out as per previous comment, closing this issue. Please feel free to reopen if any additional questions on this topic.

**Closed by avirishuv** 2021-09-16 23:19 UTC
Labels: bug, Compute, Service Attention, customer-reported, OKR3.2 Candidate
