### ISSUE TITLE
Output format is not respected on macOS

### ISSUE THREAD

**Issue by mattias-kindborg-at-work** [Azure/azure-cli#20336] opened 2021-11-15 15:44 UTC
## Describe the bug

On macOS, after upgrading from Azure CLI v2.29.0 to v2.30.0, output formatting options aren't respected. Formatting options have been verified to work on v2.30.0 running Windows or Ubuntu, but not macOS.

**Command Name**

All commands where output is formatted, e.g. `az group create --name foo --location eastus --output none` and `az iot hub list --query "[?name=='foo'] | length(@)"`.

**Errors:**

Response is always formatted as JSON indifferent of `--output` argument, and `--query` with a filter doesn't work at all but instead displays the result as if the query wasn't even applied.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Example 1 where output format isn't respected.

```
$ az group create --name foo --location eastus --output none
> {
>   "id": "/subscriptions/<id>/resourceGroups/foo",
>   "location": "eastus",
>   "managedBy": null,
>   "name": "foo",
>   "properties": {
>     "provisioningState": "Succeeded"
>   },
>   "tags": null,
>   "type": "Microsoft.Resources/resourceGroups"
> }
```

Example 2 where query isn't respected, and the response should be the length of the result, not the result itself.

```
$ az iot hub list --query "[?name=='foo'] | length(@)"
> [
>   { ... },
>   { ... },
>   { ... }
> ]
```

## Expected Behavior

Example 1

```
$ az group create --name foo --location eastus --output none
```

Example 2

```
$ az iot hub list --query "[?name=='foo'] | length(@)"
> 0
```
## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.8
Installer: HOMEBREW

azure-cli 2.30.0

Extensions:
azure-iot 0.11.0

```

**Comment by yonzhan** [comment] 2021-11-15 23:10
@jiasli for awareness

**Comment by jiasli** [comment] 2021-11-16 03:09
Duplicate of https://github.com/Azure/azure-cli/issues/20269

**Closed by jiasli** 2021-11-16 03:09 UTC
Labels: Core, customer-reported
