### ISSUE TITLE
cmdlet 'az ad group member list' doesn't return service principals

### ISSUE THREAD

**Issue by Olosinsk-commits** [Azure/azure-cli#23835] opened 2022-09-09 17:29 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az ad group member list previously was returning SP on 2.36.0:
![image](https://user-images.githubusercontent.com/11326592/189408915-c55190a7-75e2-4e7f-948a-02d4eaba9445.png)

and stopped returning starting from 2.37.0
![image](https://user-images.githubusercontent.com/11326592/189409207-5940c8eb-5354-429a-8a81-7ca0d88c5ae2.png)

From one side, it seems expecting based on the cmdlets description, from another, seems kind odd for me what we return this object by using the PowerShell script Get-AzureADGroupMember with the same description or SP was returning before. 
![image](https://user-images.githubusercontent.com/11326592/189409276-abd2cf7c-0092-4697-a0e0-f74caa48cedd.png)

Additionally when we use the "az ad group member check" command with the group id and one of the member id's , the response is "True".

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**
 
End users needs a solution as the workaround of checking if every SPI is part of every group(using "az ad group member check") is not efficient but is the only solution they have at the moment.

**Comment by yonzhan** [comment] 2022-09-10 01:03
@jiasli for awareness

**Comment by jiasli** [comment] 2022-09-19 06:20
Duplicate of #22664

**Closed** 2022-09-19 06:20 UTC
Labels: question, Graph, Installation, Auto-Assign, Azure CLI Team
