### ISSUE TITLE
We are unable to create a new repair vm with az vm repair create -n -g

### ISSUE THREAD

**Issue by sarbaker** [Azure/azure-cli#20736] opened 2021-12-14 21:41 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When we try to us the azure cli extension to run the az vm repair create -n avd1host-0 -g AVD command. We get an error
sara@Azure:~$ az vm repair create -n avd1host-0 -g AVD
Repair VM admin username: sara
Repair VM admin password:
Confirm Repair VM admin password:
Does repair vm requires public ip? (y/n): y
WARNING: It is recommended to use parameter "--public-ip-sku Standard" to create new VM with Standard public IP. Please note that the default public IP used for VM creation will be changed from Basic to Standard in the future.
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"Resource name 'avd1host-0-DiskCopy-20211214213502' does not match resource name in ID 'avd1host-0-DiskCopy-20211214213502.038133'.\",\r\n    \"target\": \"/subscriptions/00c12a0c-88fd-4b01-b9bb-666a634006de/resourceGroups/repair-avd1host-0-20211214213502.038133/providers/Microsoft.Compute/disks/avd1host-0-DiskCopy-20211214213502\"\r\n  }\r\n}"}]}}

Repair create failed. Cleaning up created resources.
{
  "error_message": "WARNING: It is recommended to use parameter \"--public-ip-sku Standard\" to create new VM with Standard public IP. Please note that the default public IP used for VM creation will be changed from Basic to Standard in the future.\nERROR: {\"status\":\"Failed\",\"error\":{\"code\":\"DeploymentFailed\",\"message\":\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\"details\":[{\"code\":\"BadRequest\",\"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"InvalidParameter\\\",\\r\\n    \\\"message\\\": \\\"Resource name 'avd1host-0-DiskCopy-20211214213502' does not match resource name in ID 'avd1host-0-DiskCopy-20211214213502.038133'.\\\",\\r\\n    \\\"target\\\": \\\"/subscriptions/00c12a0c-88fd-4b01-b9bb-666a634006de/resourceGroups/repair-avd1host-0-20211214213502.038133/providers/Microsoft.Compute/disks/avd1host-0-DiskCopy-20211214213502\\\"\\r\\n  }\\r\\n}\"}]}}\n",
  "message": "Repair create failed. Cleaning up created resources.",
  "status": "ERROR"
}
sara@Azure:~$

Steps to Reproduce:
=================
run az vm repair create -n avd1host-0 -g AVD. 

**Expected behavior**
To create a repair vm for the broken vm.a

**Environment summary**

I'm using Azure cloudShell and the version is below. 
sara@Azure:~$ az version
{
  "azure-cli": "2.31.0",
  "azure-cli-core": "2.31.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "ssh": "1.0.0",
    "vm-repair": "0.3.9"
  }
}
sara@Azure:~$

**Additional context**

**Comment by jpramirez54** [comment] 2021-12-14 21:57
Same issue here.
Different subscriptions and it doesn’t matter if  I try on new or existing VM’s, the issue is the same.
When prompted if it requires a public IP or not, it doesn’t matter the answer, the issue persists.
Attempted adding and removing some parameters but, still the same.
![image](https://user-images.githubusercontent.com/96149578/146085912-d88d3747-9c65-4a46-a677-398df8c8f120.png)

**Comment by jiasli** [comment] 2021-12-15 06:31
Adding @zhoxing-ms to help.

**Comment by zhoxing-ms** [comment] 2021-12-15 09:20
> Resource name 'avd1host-0-DiskCopy-20211214213502' does not match resource name in ID 'avd1host-0-DiskCopy-20211214213502.038133

This error message is returned by the service, so we need service team to help troubleshoot it

**Comment by bashar-alali** [comment] 2021-12-15 16:38
Got this issue today as well. This however seems to be specific to az cli 2.31.0.
az vm repair works fine on 2.27.2 and 2.30.0 per our tests.

**Comment by zhoxing-ms** [comment] 2021-12-16 07:31
@haagha Could you please help take a look at this issue?

**Comment by prafulbusa** [comment] 2021-12-16 19:01
I didn't thought of changing the version of the Az Repair Script, nice findings. I have observed this issue multiple times with some MS cx. Glad to know.

**Comment by cdandrea** [comment] 2021-12-22 04:54
Just a quick comment to note. I had the same issue running 2.31.0 via Azure Cloud Shell. However I had 2.29.2 installed locally and it ran successfully creating the repair VM.

http://sharing.caseydandrea.com/6z4Ytea

**Comment by marinnedea** [comment] 2022-01-04 08:29
Quick workaround:

`az vm repair create -g AffectedVMRG -n AfectedVM --copy-disk-name copyOfDiskToFix`

### IMPORTANT! Make sure the name of the copy of the affected disk doesn't include any dot.

Example wrong name:
`copy.OfDiskToFix`

Example correct Name:
`CopyOfDIskToFix`

Once issue is fixed, to restore the VM just use the usual command:

`az vm repair restore -g AffectedVMRG -n AfectedVM`

**Comment by amjads1** [comment] 2022-02-03 19:27
@sarbaker Following up to check if the issue is fixed with the above workaround.

**Comment by navba-MSFT** [comment] 2022-02-17 05:16
@sarbaker Apologies for the late reply. Could you please let us know if the above workaround has helped ? Also please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the AzCLI and test the behavior ? Awaiting your reply.

**Closed as completed** 2022-03-11 08:00 UTC
Labels: Compute, Service Attention, question, customer-reported, needs-author-feedback, no-recent-activity
