### ISSUE TITLE
az login error

### ISSUE THREAD

**Issue by hengv** [Azure/azure-cli#24134] opened 2022-10-09 05:59 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1665292336.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1665294788,
  "nbf": 1665294788,
  "exp": 1665298688,
  "aio": "AWQAm/8TAAAA7n3gq8iRMf3Y3j+JbwUKHIg1Je6XpDykGsJ8t8rSMci/HdRHbjIn0f5cZf1Ie59L8/KlMQgMkbfMmN4FdZudpotJ6V5bLjWG415JEucJTVLt5RJuFGRTRDiobeRUv2pH",
  "name": "Heng Wei",
  "oid": "a057aa73-c230-47ef-8ff0-b6bc53208494",
  "preferred_username": "weiheng@microsoft.com",
  "puid": "100320018A1749DF",
  "rh": "0.ARoAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAGQ.",
  "sub": "_bFsM9Naf7qswhGx8O-kfdLZBw6FUf85MbJArOgTnes",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "5rLPmoXHE0aXk1l9s2McAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 154, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1670, in acquire_token_by_device_flow
    response = _clean_up(self.client.obtain_token_by_device_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 384, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 346, in _obtain_token_by_device_flow
    result = self._obtain_token(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 789, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 599, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 310, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 153, in __add
    decode_id_token(id_token, client_id=event["client_id"])
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    raise RuntimeError("%s Current epoch = %s.  The id_token was: %s" % (
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1665292336.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1665294788,
  "nbf": 1665294788,
  "exp": 1665298688,
  "aio": "AWQAm/8TAAAA7n3gq8iRMf3Y3j+JbwUKHIg1Je6XpDykGsJ8t8rSMci/HdRHbjIn0f5cZf1Ie59L8/KlMQgMkbfMmN4FdZudpotJ6V5bLjWG415JEucJTVLt5RJuFGRTRDiobeRUv2pH",
  "name": "Heng Wei",
  "oid": "a057aa73-c230-47ef-8ff0-b6bc53208494",
  "preferred_username": "weiheng@microsoft.com",
  "puid": "100320018A1749DF",
  "rh": "0.ARoAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAGQ.",
  "sub": "_bFsM9Naf7qswhGx8O-kfdLZBw6FUf85MbJArOgTnes",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "5rLPmoXHE0aXk1l9s2McAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-5.15.57.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.3 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0

Extensions:
costmanagement 0.2.1
quota 0.1.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-10-09 06:03
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2022-10-09 06:03 UTC
Labels: Account, customer-reported, Auto-Assign
