### ISSUE TITLE
`az webapp up` failure leaves orphaned resource groups

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli#22713] opened 2022-06-02 15:38 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az webapp up

**Describe the bug**
When running `az webapp up` without specifying --resource-group it will create a new resource group with a random name.
If the `webapp up` command fails after the resource group is created, the resource group is left.
If the `webapp up` command is run a subsequent time, a new resource group is created and the one from the previous failure is orphaned.

**To Reproduce**
![image](https://user-images.githubusercontent.com/74415662/171666437-4bc6803b-19c0-45f6-8b64-1c5e69623dff.png)

**Expected behavior**
When the `webapp up` command fails, it should delete/roll-back the creation of all resources

**Environment summary**

Install Method: winget
Shell: PowerShell on Windows 11
Version:
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Extensions:
azure-dev                      0.0.1b456
containerapp                       0.1.3
rdbms-connect                      1.0.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\charris\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

**Additional context**

**Comment by navba-MSFT** [comment] 2022-06-07 04:12
Adding Service Team to take a look into this.

**Comment by panchagnula** [comment] 2022-07-15 16:33
Thanks for reporting, we will add support for clean up of resources.

**Comment by seligj95** [comment] 2023-07-05 15:20
Closing as this is by design

**Closed by seligj95** 2023-07-05 15:20 UTC
Labels: Web Apps, Service Attention, Auto-Assign, app-service-webapp-up
