### ISSUE TITLE
Azure CLI tagging VM failing due to unrequired permission

### ISSUE THREAD

**Issue by ecsousa** [Azure/azure-cli#13732] opened 2020-05-28 19:06 UTC
**Describe the bug**

Setting a tag on a VM resource fails if client doesn't have read permission on linked resource.

**To Reproduce**
`az vm update -n VirutalMachineName -g ResourceGroupName --set tags.TagName=TagValue  --subscription SubscriptionName`

On my case, I'm receiving a message like this (I've masked all personal data):

```
The client '******@****.com' with object id '********-****-****-****-****************' has permission to perform action 'Microsoft.Compute/virtualMachines/write' on scope '/subscriptions/********-****-****-****-****************/resourceGroups/Buy-Planning-Dev/providers/Microsoft.Compute/virtualMachines/VirtualMachineName'; however, it does not have permission to perform action 'read' on the linked scope(s) '/subscriptions/********-****-****-****-****************/resourceGroups/ResourceGroupName/providers/Microsoft.Compute/images/**********.vhd' or the linked scope(s) are invalid.
```

**Expected behavior**
Tag named `TagName` on VM `VirtualMachineName` should be set with value `TagValue`

**Environment summary**
Az cli on windows installed using chocolatey, package version 2.6.0.

`az --version` output:

```
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\esousa\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Additional context**

I'm able to create and update tags, using the same user, with both Azure Portal, and PowerShell Az module, This indicates that it's a az cli issue rather than a real permission issue.

**Comment by yungezz** [comment] 2020-05-29 01:30
hi @qwordy could  you pls have a look?

**Comment by qwordy** [comment] 2020-07-31 06:50
@ecsousa Could you run `az vm update -n VirutalMachineName -g ResourceGroupName --set tags.TagName=TagValue --subscription SubscriptionName --debug` and paste output here?

**Comment by qwordy** [comment] 2020-08-05 03:05
@ecsousa Could you run the above command?

**Comment by ecsousa** [comment] 2020-08-05 21:12
@qwordy Here's the requested log: [tags-update.log](https://github.com/Azure/azure-cli/files/5031164/tags-update.log)

**Comment by qwordy** [comment] 2020-08-17 05:40
You can try `az resource tag` command.
https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-tag
Update operation should pass the whole model of the resource. So it contains image reference.
```
{"location": "westus", "tags": {"ProjectorDesiredState": "on", "Gap_ID": "{\"AppID\":\"TBD\",\"Name\":\"TBD\",\"ProjectID\":\"131122\"}", "Gap_Finance": "{\"CostCenter\":\"131122\",\"Environment\":\"Development\",\"Lifecycle\":\"In-Service\"}", "ProjectId": "137170", "DesiredState": "off"}, "properties": {"hardwareProfile": {"vmSize": "Standard_F8s"}, "storageProfile": {"imageReference": {"id": "/subscriptions/231ce626-a41d-4bb2-9bec-51ab394e76a6/resourceGroups/RG-CES-Shared/providers/Microsoft.Compute/images/win2016-Apr18.vhd"}, "osDisk": {"osType": "Windows", "name": "DAZWUSADASRD001_disk1_24cbb6004dc348649eb37124fa057fe6", "caching": "None", "createOption": "FromImage", "diskSizeGB": 60, "managedDisk": {"id": "/subscriptions/231ce626-a41d-4bb2-9bec-51ab394e76a6/resourceGroups/BUY-PLANNING-DEV/providers/Microsoft.Compute/disks/DAZWUSADASRD001_disk1_24cbb6004dc348649eb37124fa057fe6", "storageAccountType": "Premium_LRS"}}, "dataDisks": [{"lun": 0, "name": "DAZWUSADASRD001-datadisk1", "caching": "ReadOnly", "createOption": "Empty", "diskSizeGB": 1, "managedDisk": {"id": "/subscriptions/231ce626-a41d-4bb2-9bec-51ab394e76a6/resourceGroups/BUY-PLANNING-DEV/providers/Microsoft.Compute/disks/DAZWUSADASRD001-datadisk1", "storageAccountType": "Premium_LRS"}, "toBeDetached": false}, {"lun": 1, "name": "DAZWUSADASRD001-datadisk2", "caching": "ReadOnly", "createOption": "Empty", "diskSizeGB": 40, "managedDisk": {"id": "/subscriptions/231ce626-a41d-4bb2-9bec-51ab394e76a6/resourceGroups/BUY-PLANNING-DEV/providers/Microsoft.Compute/disks/DAZWUSADASRD001-datadisk2", "storageAccountType": "Premium_LRS"}, "toBeDetached": false}]}, "osProfile": {"computerName": "DAZWUSADASRD001", "adminUsername": "cestestuser", "windowsConfiguration": {"provisionVMAgent": true, "enableAutomaticUpdates": true, "patchSettings": {"patchMode": "AutomaticByOS"}}, "secrets": []}, "networkProfile": {"networkInterfaces": [{"id": "/subscriptions/231ce626-a41d-4bb2-9bec-51ab394e76a6/resourceGroups/Buy-Planning-Dev/providers/Microsoft.Network/networkInterfaces/DAZWUSADASRD001-nic"}]}, "diagnosticsProfile": {"bootDiagnostics": {"enabled": true, "storageUri": "http://buyplanstorageac.blob.core.windows.net"}}, "availabilitySet": {"id": "/subscriptions/231ce626-a41d-4bb2-9bec-51ab394e76a6/resourceGroups/Buy-Planning-Dev/providers/Microsoft.Compute/availabilitySets/BUYPLAN-PROJECTOR-DEV-BLUE-AVSET"}}}
```
Could you share the PowerShell command that you use?

**Comment by yungezz** [comment] 2020-08-27 03:42
hi @ecsousa could you pls try the command above? are you still on this issue?

**Comment by qwordy** [comment] 2020-08-28 07:59
I found the root cause. Recently, a similar issue https://github.com/Azure/azure-cli/issues/14924 was reported. He said we can pass a partial model of a VM/VMSS via PUT API to update it. I am fixing it. Close it for now. Will update in #14924

**Closed by qwordy** 2020-08-28 07:59 UTC
Labels: Compute, OKR3.2 Candidate, customer-response-expected
