### ISSUE TITLE
'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by Arextion** [Azure/azure-cli#20131] opened 2021-11-01 09:31 UTC
## Describe the bug
Got this error during a course:
https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/3-exercise-import-function-app-api-management

when running the bash setup.sh command and i'm unable to continue the course.

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 403, in enable_zip_deploy_functionapp
    remove_remote_build_app_settings(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 538, in remove_remote_build_app_settings
    should_contain=app_settings_should_contain)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1019, in validate_app_settings_in_scm
    scm_settings = _get_app_settings_from_scm(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 81, in call
    raise exception
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 77, in call
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1038, in _get_app_settings_from_scm
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1948, in _get_scm_url
    webapp = show_webapp(cmd, resource_group_name, name, slot=slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
    return _show_app(cmd, resource_group_name, name, "webapp", slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
    "Unable to find {} '{}', in RG '{}'".format(cmd_app_type.value, name, resource_group_name),
AttributeError: 'str' object has no attribute 'value'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment] 2021-11-01 11:37
route to service team

**Comment by akakaule** [comment] 2021-11-03 00:13
After having updated to azure cli 2.29 used by latest hosted Azure DevOps agents I'm recieving same error with 

az functionapp deployment source config-zip --resource-group $resourceGroupName --name $functionAppName --src $faZipDeploymentPath

2021-11-02T23:35:52.2621951Z WARNING: Setting SCM_DO_BUILD_DURING_DEPLOYMENT to false
2021-11-02T23:36:14.2689471Z WARNING: Waiting SCM site to be updated with the latest app settings
2021-11-02T23:36:25.6636659Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-11-02T23:36:25.6640515Z ERROR: 'str' object has no attribute 'value'
2021-11-02T23:36:25.6642530Z Traceback (most recent call last):
2021-11-02T23:36:25.6644248Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
2021-11-02T23:36:25.6645563Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
2021-11-02T23:36:25.6646804Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-11-02T23:36:25.6647739Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-11-02T23:36:25.6648613Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
2021-11-02T23:36:25.6649876Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2021-11-02T23:36:25.6650633Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 403, in enable_zip_deploy_functionapp
2021-11-02T23:36:25.6651530Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 536, in remove_remote_build_app_settings
2021-11-02T23:36:25.6653085Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1019, in validate_app_settings_in_scm
2021-11-02T23:36:25.6654462Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/utils.py", line 81, in call
2021-11-02T23:36:25.6655424Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/utils.py", line 77, in call
2021-11-02T23:36:25.6656395Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1038, in _get_app_settings_from_scm
2021-11-02T23:36:25.6657413Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1948, in _get_scm_url
2021-11-02T23:36:25.6658337Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
2021-11-02T23:36:25.6659806Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
2021-11-02T23:36:25.6660596Z AttributeError: 'str' object has no attribute 'value'

**Comment by Mjay2k** [comment] 2021-11-03 05:03
I am also receiving this exact same error on this very course!

**Comment by ruijterkamp** [comment] 2021-11-03 07:16
We're now also unable to deploy our Azure Functions due this exact same error.

**Comment by AlexBrunnerLearning** [comment] 2021-11-03 08:26
I am receiving the same error on this course as well...

**Comment by sowmyagomatam** [comment] 2021-11-03 10:40
Hi, is there any solution to this? It still doesn't seem to be rectified.

**Comment by davidcconrad** [comment] 2021-11-03 21:08
Duplicate of #19939

**Comment by ruijterkamp** [comment] 2021-11-04 12:24
In Azure DevOps version 2.30.0 of Azure CLI is available and the deployment is working again without any error.

**Closed** 2021-11-04 14:27 UTC
Labels: Service Attention, Functions, customer-reported
