### ISSUE TITLE
'az postgres server create' does have idempotent behaviour.

### ISSUE THREAD

**Issue by felixengstrom** [Azure/azure-cli#15980] opened 2020-11-19 07:17 UTC
**Describe the bug**
'az postgres server create' returns error code when trying to create server that already exists.

**To Reproduce**
Run 'az postgres server create' for a postgres server that already exists.

**Expected behavior**
Should according to [Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types) be idempotent.

**Comment by yonzhan** [comment] 2020-11-19 12:46
postgres

**Comment by Strepto** [comment] 2020-11-25 13:49
+1

This is a regression from behaviour in v2.13.0, where this was idempotent (or at least did not fail).

**Comment by yonzhan** [comment] 2020-11-25 14:12
postgres service team should look into this issue.

**Comment by lfittl-msft** [comment] 2020-11-25 19:43
@felixengstrom Thanks for the report - we're looking into this.

Please note that responses might be delayed due to the Thanksgiving holiday in the US.

**Comment by rekhakm** [comment] 2022-01-21 18:06
I am also facing this issue.

Not able to increase the storage size  from ARM template
Is there any update from the team?

**Comment by nachoalonsoportillo** [comment] 2024-06-24 22:04
@felixengstrom Thanks for having taken the time to create this issue! Apologize for not having responded much earlier. Unfortunately it is too late already to have this fixed in Single Server. However, we have an identical request for Flexible Server which we're triaging at the moment.

**Comment by nachoalonsoportillo** [comment] 2024-06-24 22:05
@yonzhan Please, close this one as resolved. Thanks!

**Closed** 2024-06-24 23:24 UTC
Labels: Service Attention, PostgreSQL
