### ISSUE TITLE
HPC Cache - az hpc-cache blob-storage-target-update

### ISSUE THREAD

**Issue by rebecca-makar** [Azure/azure-cli#13004] opened 2020-04-14 13:07 UTC
```
az hpc-cache blob-storage-target add --resource-group "remakar" --cache-name "climakar" --name "testupdate" --storage-account "/subscriptions/<SUB_ID>/resourceGroups/remakar/providers/Microsoft.Storage/storageAccounts/makarst" --container-name "test2" --virtual-namespace-path "/test1"


az hpc-cache blob-storage-target update --resource-group "remakar" --cache-name "climakar" --name "testupdate" --storage-account "/subscriptions/<SUB_ID> /resourceGroups/remakar/providers/Microsoft.Storage/storageAccounts/makarst" --container-name "test2" --virtual-namespace-path "/test2"
```

1. Create new ST
2. Update that ST junctions = Operation failed with status: 202. Details: Resource state Updating
NUMBER 2 is bug since it is actually updating the storage target but returns to user that it is an error. Looks like mapping may be wrong somewhere.

**Comment by yonzhan** [comment] 2020-04-14 13:12
add to S169

**Comment by zhoxing-ms** [comment] 2020-07-31 07:56
@rebecca-makar Hi, the command `az hpc-cache blob-storage-target update` does not support updating the parameter `--junction`.
Is the issue #13005 what you want to say?

**Comment by rebecca-makar** [comment] 2020-07-31 13:41
@zhoxing-ms  so if you run the command it does what it is suppose to be doing...
but it shows the user an error in red even though the response is 202. 
It should not say it is a failure.

It says
```Operation failed with status: 202. Details: Resource state Updating```

**Comment by rebecca-makar** [comment] 2020-07-31 13:42
That comment also applies to #13005

**Comment by zhoxing-ms** [comment] 2020-08-03 01:41
@rebecca-makar Thanks for your reply~ Yes, I understand that. So could we close this issue and only keep #13005 to track this issue?

**Comment by rebecca-makar** [comment] 2020-08-03 18:15
@zhoxing-ms since they are two separate commands should we keep it separated? One Buy for nfs and one bug for blob. 

Also I am on PTO this week if I am a little slower to respond.

**Comment by zhoxing-ms** [comment] 2020-08-04 07:49
@rebecca-makar Sorry, I can't see the parameter `--junctions` after executing command `az hpc-cache blob-storage-target update -h`, and I can't reproduce this problem.
```pwsh
This command is from the following extension: hpc-cache

Command
    az hpc-cache blob-storage-target update : Create or update a blob Storage Target. This operation
    is allowed at any time, but if the Cache is down or unhealthy, the actual creation/modification
    of the Storage Target may be delayed until the Cache is healthy again.
        Command group 'hpc-cache' is experimental and not covered by customer support. Please
        use with discretion.
Arguments
    --cache-name        [Required] : Name of Cache.
    --name              [Required] : Name of the Storage Target.
    --resource-group -g [Required] : Name of resource group. You can configure the default group
                                     using `az configure --defaults group=<name>`.
    --container-name               : Name of target storage container.
    --storage-account              : Resource ID of target storage account.
    --virtual-namespace-path -v    : Path to create for this storage target in the client-facing
                                     virtual filesystem.
```

Could you please add the parameter `--debug` to the command which is in the issue, and then execute it to show me the printed information?
You can send it to me by email, my email address Zhou.Xing@microsoft.com

**Comment by zhoxing-ms** [comment] 2020-08-20 03:13
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-08-20 03:13 UTC
Labels: Breadth, Feature Request, HPC Cache, OKR3.2 Candidate
