### ISSUE TITLE
Azure AAD App Credential Reset via AzCLI

### ISSUE THREAD

**Issue by davidfranz001** [Azure/azure-cli#23374] opened 2022-07-28 23:25 UTC
**Related command**
az ad sp credential reset
https://docs.microsoft.com/en-us/cli/azure/ad/sp/credential?view=azure-cli-latest

**Describe the bug**
After resetting the credential, the output shows that the credential is reset when using `az ad sp credential list --id $AksApplicationID`, but when viewing the changes the the Azure portal, they have not been reset.
This causes the SP account credential to be invalid.

**To Reproduce**
`$AksApplicationSP = "myserviceprincipal"`
`$AksApplicationID = $(az ad sp create-for-rbac --skip-assignment --name $AksApplicationSP --query appId -o tsv)`
`az ad sp credential reset --id $AksApplicationID --end-date "2250-12-31" --display-name "MyNewDisplayName"`

`az ad sp credential list --id $AksApplicationID`

**Expected behavior**
Both AzCLI and the Azure portal should have matching passwords display names, but this does not happen

**Environment summary**
Executed via Az CLI in PowerShell window

**Additional context**
Fix is to change from `az ad sp credential reset` to `az ad app credential reset`
https://docs.microsoft.com/en-us/cli/azure/ad/app/credential?view=azure-cli-latest

MS need to update their doco or fix this issue

**Comment by yonzhan** [comment] 2022-07-28 23:30
@jiasli for awareness

**Comment by jiasli** [comment] 2022-08-24 03:46
Duplicate of #23566

**Closed by jiasli** 2022-08-24 03:46 UTC
Labels: bug, Graph, AAD, customer-reported, Auto-Assign, Azure CLI Team
