### ISSUE TITLE
The operation 'azure.cli.command_modules.acs.custom#aks_scale' is invalid.

### ISSUE THREAD

**Issue by swingbit** [Azure/azure-cli#9775] opened 2019-06-24 10:10 UTC
## Describe the bug
Any az aks command fails.
The error suggests something is wrong with module aks_scale

**Command Name**
`az aks -h`

**Errors:**
```
The operation 'azure.cli.command_modules.acs.custom#aks_scale' is invalid.
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 513, in execute
    parsed_args = self.parser.parse_args(args)
python2.7/site-packages/knack/parser.py, ln 259, in parse_args
    return super(CLICommandParser, self).parse_args(args)
usr/lib64/python2.7/argparse.py, ln 1705, in parse_args
    args, argv = self.parse_known_args(args, namespace)
...
azure/cli/core/__init__.py, ln 479, in default_description_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
azure/cli/core/__init__.py, ln 520, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.cli.command_modules.acs.custom#aks_scale' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks -h`

## Environment Summary
```
Linux-5.1.11-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
Python 2.7.16
Shell: bash

azure-cli 2.0.67

```

**Comment by manrajag** [comment] 2019-06-26 15:02
I am also facing this problem. 

Fedora25 

azure-cli                         2.0.67

acr                                2.2.9
acs                                2.4.4
advisor                            2.0.1
ams                                0.4.7
appservice                        0.2.21
backup                             1.2.5
batch                              4.0.3
batchai                           0.4.10
billing                            0.2.2
botservice                         0.2.2
cdn                                0.2.4
cloud                              2.1.1
cognitiveservices                  0.2.6
command-modules-nspkg               2.0.2
configure                         2.0.24
consumption                        0.4.4
container                         0.3.18
core                              2.0.67
cosmosdb                          0.2.11
deploymentmanager                  0.1.1
dla                                0.2.6
dls                               0.1.10
dms                                0.1.4
eventgrid                          0.2.4
eventhubs                          0.3.7
extension                          0.2.5
feedback                           2.2.1
find                               0.3.4
hdinsight                          0.3.5
interactive                        0.4.5
iot                               0.3.11
iotcentral                         0.1.7
keyvault                          2.2.16
kusto                              0.2.3
lab                                0.1.8
maps                               0.3.5
monitor                           0.2.15
natgateway                         0.1.1
network                            2.5.2
nspkg                              3.0.3
policyinsights                     0.1.4
privatedns                         1.0.2
profile                            2.1.5
rdbms                             0.3.12
redis                              0.4.4
relay                              0.1.5
reservations                       0.4.3
resource                          2.1.16
role                               2.6.4
search                             0.1.2
security                           0.1.2
servicebus                         0.3.6
servicefabric                     0.1.20
signalr                            1.0.1
sql                                2.2.5
sqlvm                              0.2.0
storage                            2.4.3
telemetry                          1.0.2
vm                                2.2.23

Extensions:
interactive                        0.4.3

Python location '/usr/bin/python2'
Extensions directory '/home/manrajag/.azure/cliextensions'

Python (Linux) 2.7.13 (default, Dec  1 2017, 09:21:53) 
[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

### **This is autogenerated. Please review and update as needed.**

## Describe the bug

**Command Name**
`az aks`

**Errors:**
```
The operation 'azure.cli.command_modules.acs.custom#aks_scale' is invalid.
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 513, in execute
    parsed_args = self.parser.parse_args(args)
python2.7/site-packages/knack/parser.py, ln 259, in parse_args
    return super(CLICommandParser, self).parse_args(args)
...
azure/cli/core/__init__.py, ln 520, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.cli.command_modules.acs.custom#aks_scale' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks -h`

## Expected Behavior

## Environment Summary
```
Linux-4.13.16-100.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
Python 2.7.13
Shell: bash

azure-cli 2.0.67

Extensions:
interactive 0.4.3

```
## Additional Context

**Comment by brendandburns** [comment] 2019-07-31 20:43
Duplicate of #9651

**Comment by brendandburns** [comment] 2019-08-03 03:56
@tjprescott we can close this as a duplicate.

**Closed** 2019-08-05 14:56 UTC
Labels: AKS, Service Attention
