### ISSUE TITLE
az dls fs download should return message from service side instead of CLI core

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#12239] opened 2020-02-18 02:52 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
when user run `az dls fs download` command, the command failed because file/dir not exists. While the exception/stacktrace is confusing, because it's from CLI core. pls see below. The error is not from service side although it supposed to when file/dir not exists. Missing clear info from service side error message makes trouble shooting less informative, and causes user confusion. Need to refine it.
```
az dls fs download -n bkwndtl --overwrite --destination-path /mnt/glm/ --source-path '/clusters/ETAP-Cluster/simulation2/*/*.glm'
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 547, in get_default_cli
    from azure.cli.core.azlogging import AzCliLogging
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 30, in <module>
    from azure.cli.core.commands.events import EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 28, in <module>
    from azure.cli.core.extension import get_extension
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/__init__.py", line 16, in <module>
    az_config = CLIConfig(config_dir=GLOBAL_CONFIG_DIR, config_env_var_prefix=ENV_VAR_PREFIX)
  File "/opt/az/lib/python3.6/site-packages/knack/config.py", line 50, in __init__
    current_dir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yungezz** [comment] 2020-02-18 02:52
HI @Juliehzl I'm not sure the right owner. Could you pls help to reassign if you're not right contact point? Thanks.

**Comment by yonzhan** [comment] 2020-02-18 02:58
The same issue mentioned in Sev 3: ID 175946000: [bkw.ch][sev B][120021222002848 - Since 2020 the "az dls fs"command don't seem to work properly, right?

**Comment by yungezz** [comment] 2020-02-18 03:02
more info from service team about the exception from service side when downloading failure:
https://github.com/Azure/azure-data-lake-store-python/blob/d7293c7690870bf730f3001ac64933a4183d9e8d/azure/datalake/store/exceptions.py#L32

**Comment by yonzhan** [comment] 2020-02-18 03:49
We will take a look and follow up, thx.

**Comment by Juliehzl** [comment] 2020-02-18 05:41
@akharit Can you take a look for this issue?

**Comment by akharit** [comment] 2020-02-18 19:05
I am not sure if this is an adls issue as there doesn't seem to be dls module in the stack trace. 

The stack trace shows 
```
    current_dir = os.getcwd()
    FileNotFoundError: [Errno 2] No such file or directory
```

This means the current dir in the according to python was somehow deleted. 

It is possible that adls destination path was specified in such a way to delete the current dir, but I would classify that as a user error. It could have been deleted by any other user process as well. 

If a fix is needed, we possibly need to open a bug on knack module.

**Comment by MyronFanQiu** [comment] 2020-02-27 11:38
@jiasli I had a try and it's indeed a quite weird corner case for knack. I don't know whether we can fix it or not. You can take a look.
![Untitled](https://user-images.githubusercontent.com/49134743/75441420-9c46ad00-5998-11ea-9073-1cc70a4c3198.png)

**Comment by jiasli** [comment] 2020-02-27 11:51
This is indeed a corner case of Knack, but I don't think it is a bug. Linux doesn't put a lock on the folder when some process's working directory is still that folder. On the other hand, Windows does put a lock, so deleting the folder will result in a failure. I will mute the error on Knack.

**Comment by jiasli** [comment] 2020-02-28 05:23
This is indeed a corner case of Knack, but I don't think it is a bug that is ought to be fixed in Knack. 

I tested on an Azure VM running Linux (centos 7.7.1908) and reproduced this error:

```
$ mkdir t1
$ cd t1
$ rmdir ~/t1
$ az
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python3.6/pkgutil.py", line 412, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
 File "/usr/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in _build_master
    ws = cls()
  File "/usr/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 554, in __init__
    self.add_entry(entry)
  File "/usr/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 610, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1862, in find_distributions
    importer = get_importer(path_item)
  File "/usr/lib64/python3.6/pkgutil.py", line 416, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1324, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 102, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory
```

Interestingly enough, it fails way earlier than entering Knack or Azure CLI.

There are some discussions on Stackoverflow: 
https://stackoverflow.com/questions/12758125/sh-0-getcwd-failed-no-such-file-or-directory-on-cited-drive
https://stackoverflow.com/questions/12338233/shell-init-issue-when-click-tab-whats-wrong-with-getcwd
https://stackoverflow.com/questions/3210902/python-why-does-os-getcwd-sometimes-crash-with-oserror

This article explains Linux file system very well: http://www.iakovlev.org/index.html?p=4660

In short, Python does no more than calling the system’s [`getcwd`](https://linux.die.net/man/2/getcwd ) which works on the i-node, not the path string of the directory.

```c
char *getcwd(char *buf, size_t size);
```

When the folder doesn’t exist anymore, `getcwd` returns

> ENOENT
> The current working directory has been unlinked.

Even after recreating the folder and its i-node is reused, the `i_version` or `i_generation` changes, causing `getcwd` to fail. 

This is simply a design of Linux system. (Windows doesn’t have this issue because Windows puts a lock if some process is still in that directory.) Even if we mute this error in Knack, there may be other places where `FileNotFoundError` can occur, like writing to a file in that folder, or like the exception I gave earlier from finding packages. It is impossible to cover all scenarios (especially Python’s or Linux kernel’s internal usages) when `getcwd` is used. 

My suggestion is to remove the unnecessary directory change and always work in a directory that is never deleted, or use `cd .` or `cd $PWD` to re-enter the directory to make sure `az` is executed in a directory that is still valid.

**Closed** 2020-03-17 09:42 UTC
Labels: Knack
