### ISSUE TITLE
Table output unavailable

### ISSUE THREAD

**Issue by pwalleni** [Azure/azure-cli#20399] opened 2021-11-17 20:36 UTC
**Describe the bug**
I get the following error when running az command to list accounts

```
cli.knack.output: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 237, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 146, in out
    output = formatter(obj)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 79, in format_table
    raise CLIError("Table output unavailable. "
knack.util.CLIError: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

cli.azure.cli.core.azclierror: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
az_command_data_logger: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```

**To Reproduce**
I ran the following command:

`az account list -o table --debug`

**Expected behavior**
I expected a table formated list of my subscriptions.

**Environment summary**
```
-> % brew info azure-cli
azure-cli: stable 2.30.0 (bottled), HEAD
Microsoft Azure CLI 2.0
https://docs.microsoft.com/cli/azure/overview
/usr/local/Cellar/azure-cli/2.30.0_1 (21,516 files, 459.6MB) *
  Poured from bottle on 2021-11-17 at 20:54:11
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/azure-cli.rb
License: MIT
==> Dependencies
Required: openssl@1.1 ✔, python@3.10 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 60,283 (30 days), 149,986 (90 days), 471,927 (365 days)
install-on-request: 60,113 (30 days), 149,542 (90 days), 469,898 (365 days)
build-error: 125 (30 days)
```
```
-> % uname -a
Darwin C02F82EXML7H 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```

`zsh 5.8 (x86_64-apple-darwin20.0)`

**Comment by yonzhan** [comment] 2021-11-17 23:03
@jiasli for awareness

**Comment by jiasli** [comment] 2021-11-18 02:34
Duplicate of #20348

**Closed by jiasli** 2021-11-18 02:34 UTC
Labels: Core, customer-reported
