### ISSUE TITLE
$x = $(az appconfig kv list .... ) hangs and never returns.

### ISSUE THREAD

**Issue by billpieper** [Azure/azure-cli#11965] opened 2020-01-28 15:01 UTC
## Describe the bug
Unable to run az appconfig commands and have output assigned to PowerShell variable.  Same command running standalone in the same shell works just fine.  This repos on multiple versions of PowerShell on multiple machines as well as different versions of az cli (tried it on 2.0.74 and 2.0.80)  Other az cli commands are able to successfully have results assigned to a PowerShell variable.

**Command Name**
This works:
```
az appconfig kv list --name $AzureAppConfigServiceName --subscription $AzureAppConfigServiceSubscriptionId
```
This just hangs and never returns:
```
$x = $(az appconfig kv list --name $AzureAppConfigServiceName --subscription $AzureAppConfigServiceSubscriptionId)
```

**Errors:**
behaving is that it hangs when trying to assign to a variable.  does not show an error.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
```
az login
$AzureAppConfigServiceName = "<app-config-service-name-here>"
$AzureAppConfigServiceSubscriptionId = "<subscription-id-here>"
az appconfig kv list --name $AzureAppConfigServiceName --subscription $AzureAppConfigServiceSubscriptionId
## list of data from app config service displayed in console
$x = $(az appconfig kv list --name $AzureAppConfigServiceName --subscription $AzureAppConfigServiceSubscriptionId)
## prior command just hangs and does not return...
```
- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
output would be assigned to the variable and it would not hang

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe (PowerShell Core 6.2.4 64-bit)

azure-cli 2.0.80

Extensions:
aks-preview 0.4.27
application-insights 0.1.1
azure-devops 0.16.0
azure-firewall 0.1.8
dev-spaces 1.0.4
find 0.3.0
front-door 1.0.2
interactive 0.4.3
log-analytics 0.1.4
resource-graph 1.0.0
storage-preview 0.2.10
subscription 0.1.3
webapp 0.2.24

```

**Comment by shenmuxiaosen** [comment] 2020-02-06 01:41
Hi @billpieper , I can somehow repo the similar scenario but I am not sure if this is the same problem that you have. When I use powershell to execute ```$x = $(az appconfig kv list --name $AzureAppConfigServiceName --subscription $AzureAppConfigServiceSubscriptionId)``` It first returned a line "Command group 'appconfig' is in preview. It may be changed/removed in a future release." as expected, then followed by a big black chunk. You can verify by running the same script in Windows PowerShell ISE. For me, running in there returned key values.

**Comment by billpieper** [comment] 2020-02-06 12:59
Sounds like same behavior.  I am not running this from PowerShell ISE -- but rather trying to use in a stand-alone PowerShell script.  If you follow the same pattern of `$x = $(az .... pick your command here)` for any other az command $x will be populated with the results and it does not hang like it is doing when using az appconfig kv list.

**Comment by shenmuxiaosen** [comment] 2020-02-06 18:42
Yeah, I was suggesting that if running in PowerShell ISE works fine in your case, then we are hitting the same issue. Regarding to the root cause, I believe it is not due to ```appconfig``` command but the preview help message. It somehow change the background color or font color so we are not able to see it in terminal. But I tried to copy the block and paste in notepad, it actually returned something. As of now, we are not GA yet so all commands are marked as preview. When I removed the preview message in local, the issue resolved. You can also verify by running other CLI commands in preview not under ```appconfig```. The preview message is not controlled by service but by CLI framework, I will  create an issue against it.

**Comment by jiasli** [comment] 2020-02-07 03:56
Thanks for reporting this issue. Let's move to #12084.

**Comment by lilyjma** [comment] 2021-01-13 22:12
Close since the other issue talks about this problem.

**Closed by lilyjma** 2021-01-13 22:12 UTC
Labels: App Configuration, Service Attention, customer-reported
