### ISSUE TITLE
WebApp:Exception trying to tail webapp logs

### ISSUE THREAD

**Issue by garrettheaver** [Azure/azure-cli#20555] opened 2021-11-30 10:22 UTC
## Describe the bug

**Command Name**
`az webapp log tail`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2280, in get_streaming_log
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log tail --name {} --resource-group {}`

## Environment Summary
```
Linux-5.14.18-200.fc34.x86_64-x86_64-with-fedora-34-Thirty_Four, Fedora 34 (Workstation Edition)
Python 3.6.15
Installer: RPM

azure-cli 2.30.0

```

**Comment by yonzhan** [comment] 2021-11-30 11:51
route to service team

**Comment by Kotasudhakarreddy** [comment] 2021-12-01 05:33
Duplicate of #20484.

**Closed by Kotasudhakarreddy** 2021-12-01 05:33 UTC
Labels: Web Apps, Service Attention, customer-reported
