### ISSUE TITLE
No IoT Hub found with name  in current subscription.

### ISSUE THREAD

**Issue by binishababu** [Azure/azure-cli#7799] opened 2018-11-09 14:23 UTC
**Describe the bug**
'No IoT Hub found with name Hydro-QA-Hub in current subscription.' error when executing
az iot hub device-identity create --device-id "testabe" --hub-name "hubName" --edge-enabled

**To Reproduce**
1.  az login -u <username> -p <password>
2. az account set --subscription "<subscription name>"
3. az iot hub show -n "<hubName>" --resource-group "<resource group name>"
4. az iot hub device-identity create --device-id "test" --hub-name "<hubName>" --edge-enabled

**Expected behavior**
The edge device 'test' in the hubName should be created.

**Environment summary**
1. Installed Azure CLI version 2 in windows machine.

Actual Result:
'No IoT Hub found with name Hydro-QA-Hub in current subscription.' error

**Comment by jongio** [comment] 2018-11-09 18:19
@c-ryan-k

**Comment by binishababu** [comment] 2018-11-13 04:56
> az account show -o table
EnvironmentName    IsDefault    Name         State    TenantId
-----------------  -----------  -----------  -------  ------------------------------------
AzureCloud         True        mysubscription  Enabled  3d2d2b6f-061a-48b6-b4b3-9312d687e3a1

and the below command gives
>az iot hub show -n "Hydro-QA-Hub" -o table
Operation returned an invalid status code 'Not Found'
------------------------------------------------------------------------------
Also 

'az iot hub show -n "Hydro-QA-Hub" -o table 'gives an error as below

ResourceGroupNotFound - Resource group 'test-UAT-RG' could not be found.

The test-UAT-RG is in another subscription.

**Comment by tjprescott** [comment] 2018-11-13 16:56
If the hub is in a resource group in another subscription you have two options:

1: specify --name NAME --resource-group GROUP and --subscription SUB_ID
2: specify --ids ID

Both of those approaches should work--if they don't it is a bug.

**Comment by binishababu** [comment] 2018-11-16 10:15
@tjprescott  why this ticket is closed?
1. I tried switching to the subscription
2. Tried sprcifying the resource group and subscription name.

Nothing works.

**Comment by binishababu** [comment] 2018-11-16 10:16
Please reopen the ticket

**Comment by binishababu** [comment] 2018-12-05 05:40
any workaround for this issue?

**Comment by tjprescott** [comment] 2018-12-06 17:14
@c-ryan-k for comment.

**Comment by c-ryan-k** [comment] 2018-12-06 18:34
@binishababu - So just to make sure I can reproduce this issue, let's verify where your hub lives:

1. Can you navigate to your hub in the portal? If so, can you verify which Resource Group the IoT Hub belongs to, and which Subscription that Resource Group belongs to?
2. Can you verify that you have access to that subscription? Does it appear when you run:
 `az account list -o table` ?
3. Can you make sure you're logged into that subscription by running:
 `az account set --subscription [sub]`
4. Then, when you run `az iot hub list -o table` - do you see your hub?

If your hub lives inside a different subscription, then like @tjprescott mentioned, you can try to locate it within the RG and Subscription it belongs to:
`az iot hub list --resource-group [RG] --subscription [sub]`

**Comment by c-ryan-k** [comment] 2018-12-10 23:50
@binishababu - Are you still encountering this issue? If so, please share your experience after following the steps above.

**Comment by jlian** [comment] 2019-07-19 21:03
@binishababu can you let us know if you're still hitting this issue?

**Comment by ilyas-it83** [comment] 2019-08-23 14:56
This still exists

**Comment by jasonnewyork** [comment] 2019-10-26 21:00
Try only including the IoT Hub name - not the full name. Ie if the hub hostname is yourname.azure-devices.net - trying using yourname only.

**Comment by jlian** [comment] 2019-12-12 18:38
@binishababu we need a bit more detail to continue as per comment from @c-ryan-k above. In the meantime I will close the issue. Please comment back and we can reopen

**Closed by jlian** 2019-12-12 18:38 UTC
Labels: IotHub, Question, Service Attention

**Comment by KyKenCo** [comment] 2019-12-14 21:51
I'm experiencing the same issue and _cannot_ resolve it with the steps outlined by @tjprescott

**Comment by mightylastingcode** [comment] 2023-08-25 23:05
I am having the same problem but with the cloud shell.

Sometimes the IoT Hub cannot be found and I can't monitor the data sent by my IoT device.   I don't know the reason.   How should I debug it and fix the problem?  I did some investigation with what is suggested here.  But, I am still stuck.

Thank you.  Below is the interaction with the cloud shell using the browser.


Case A: When it is working, I get the data.

$ az iot hub monitor-events --hub-name MikeProjectHub --device-id MyIoTDevice
Starting event monitor, filtering on device: MyIoTDevice, use ctrl-c to stop...
{
    "event": {
        "origin": "MyIoTDevice",
        "payload": "{\"deviceId\":\"ESP32Device\", \"messageId\":1, \"Temperature\":26.400000, \"Humidity\":65.000000}"
    }
}

$az iot hub list -o table
Location    Name            Resourcegroup    Subscriptionid
westus      MikeProjectHub  MyResourceGroup  b35ecede-e49d-4e92-99ce-e0cb7746c0ac   (Good)

$ az account list -o table
Name                  CloudName    SubscriptionId                        TenantId                              State    IsDefault
Azure subscription 1  AzureCloud   b35ecede-e49d-4e92-99ce-e0cb7746c0ac  8db65f71-b9f8-4259-a0eb-ff7792280fb9  Enabled  True (Good)



Case B: When it is not working, I get the error message saying that the hub is not found.

michael [ ~ ]$ az iot hub monitor-events --hub-name MikeProjectHub --device-id MyIoTDevice
Unable to find IoT Hub: MikeProjectHub in current subscription b35ecede-e49d-4e92-99ce-e0cb7746c0ac.
michael [ ~ ]$ az iot hub list -o table
                                                                                (bad - empty list)
michael [ ~ ]$ az iot hub show -n "MikeProjectHub"
No IoT Hub found with name MikeProjectHub in current subscription.    (bad)
michael [ ~ ]$ az account show --output table
EnvironmentName    HomeTenantId                          IsDefault    Name                  State    TenantId
AzureCloud         8db65f71-b9f8-4259-a0eb-ff7792280fb9  True         Azure subscription 1  Enabled  8db65f71-b9f8-4259-a0eb-ff7792280fb9      (The subscription ID is not shown)
michael [ ~ ]$ az account list --query "[?isDefault]"
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "8db65f71-b9f8-4259-a0eb-ff7792280fb9",
    "id": "b35ecede-e49d-4e92-99ce-e0cb7746c0ac",  /* This is my subscription id */
    "isDefault": true,
    "managedByTenants": [],
    "name": "Azure subscription 1",
    "state": "Enabled",
    "tenantId": "8db65f71-b9f8-4259-a0eb-ff7792280fb9",
    "user": {
      "cloudShellID": true,
      "name": "------------",
      "type": "user"
    }
  }
]

Even when the hub is not found,  my device can still send messages to the hub. 

{"deviceId":"ESP32Device", "messageId":8, "Temperature":27.200001, "Humidity":64.000000}
Info: >>>IoTHubClient_LL_SendEventAsync accepted message for transmission to IoT Hub.
Info: >>>Confirmation[7] received for message tracking id = 7 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Send Confirmation Callback finished.

**Comment by mightylastingcode** [comment] 2023-08-25 23:31
Hi all,

Additional testing reveals to me that I must keep trying until the hub is available.  So, the hub is not always available for me to monitor for data.  Is this same problem for all other users?   Is there a better way to monitor for data?

michael [ ~ ]$ az iot hub list -o table

michael [ ~ ]$ az iot hub list -o table

michael [ ~ ]$ az iot hub list -o table

michael [ ~ ]$ az iot hub list -o table
Location    Name            Resourcegroup    Subscriptionid
----------  --------------  ---------------  ------------------------------------
westus      MikeProjectHub  MyResourceGroup  b35ecede-e49d-4e92-99ce-e0cb7746c0ac
michael [ ~ ]$ az iot hub list -o table
Location    Name            Resourcegroup    Subscriptionid
----------  --------------  ---------------  ------------------------------------
westus      MikeProjectHub  MyResourceGroup  b35ecede-e49d-4e92-99ce-e0cb7746c0ac
michael [ ~ ]$ az iot hub list -o table
Location    Name            Resourcegroup    Subscriptionid
----------  --------------  ---------------  ------------------------------------
westus      MikeProjectHub  MyResourceGroup  b35ecede-e49d-4e92-99ce-e0cb7746c0ac
michael [ ~ ]$ az iot hub list -o table

michael [ ~ ]$ az iot hub list -o table

michael [ ~ ]$
