### ISSUE TITLE
Automated Script didn't work

### ISSUE THREAD

**Issue by sanjogram** [Azure/azure-cli#11330] opened 2019-11-20 16:24 UTC
## Describe the bug

**Command Name**
`az functionapp create`

**Errors:**
```
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp create --resource-group {} --consumption-plan-location {} --name {} --storage-account {} --runtime {}`

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by sanjogram** [comment] 2019-11-20 16:24
azureuser@Azure:~$ git clone https://github.com/MicrosoftDocs/mslearn-apim-and-functions.git OnlineStoreFuncs
Cloning into 'OnlineStoreFuncs'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 23 (delta 6), reused 5 (delta 2), pack-reused 0
Unpacking objects: 100% (23/23), done.
Checking connectivity... done.
azureuser@Azure:~$ cd OnlineStoreFuncs
azureuser@Azure:~/OnlineStoreFuncs$ bash setup.sh
The resource group is called learn-3552d3b6-6bde-4e9a-8ead-0ac8eeb9081c
Creating a storage account for the functions...
The default kind for created storage account will change to 'StorageV2' from 'Storage' in the future
{
  "accessTier": null,
  "azureFilesIdentityBasedAuthentication": null,
  "creationTime": "2019-11-20T16:04:14.237169+00:00",
  "customDomain": null,
  "enableHttpsTrafficOnly": true,
  "encryption": {
    "keySource": "Microsoft.Storage",
    "keyVaultProperties": null,
    "services": {
      "blob": {
        "enabled": true,
        "lastEnabledTime": "2019-11-20T16:04:14.299685+00:00"
      },
      "file": {
        "enabled": true,
        "lastEnabledTime": "2019-11-20T16:04:14.299685+00:00"
      },
      "queue": null,
      "table": null
    }
  },
  "failoverInProgress": null,
  "geoReplicationStats": null,
  "id": "/subscriptions/9af485fa-1be7-4be5-87dd-ef8c97b32d38/resourceGroups/learn-3552d3b6-6bde-4e9a-8ead-0ac8eeb9081c/providers/Microsoft.Storage/storageAccounts/storestorage64bb230e7b",
  "identity": null,
  "isHnsEnabled": null,
  "kind": "Storage",
  "largeFileSharesState": null,
  "lastGeoFailoverTime": null,
  "location": "westus",
  "name": "storestorage64bb230e7b",
  "networkRuleSet": {
    "bypass": "AzureServices",
    "defaultAction": "Allow",
    "ipRules": [],
    "virtualNetworkRules": []
  },
  "primaryEndpoints": {
    "blob": "https://storestorage64bb230e7b.blob.core.windows.net/",
    "dfs": null,
    "file": "https://storestorage64bb230e7b.file.core.windows.net/",
    "queue": "https://storestorage64bb230e7b.queue.core.windows.net/",
    "table": "https://storestorage64bb230e7b.table.core.windows.net/",
    "web": null
  },
  "primaryLocation": "westus",
  "provisioningState": "Succeeded",
  "resourceGroup": "learn-3552d3b6-6bde-4e9a-8ead-0ac8eeb9081c",
  "secondaryEndpoints": null,
  "secondaryLocation": null,
  "sku": {
    "capabilities": null,
    "kind": null,
    "locations": null,
    "name": "Standard_LRS",
    "resourceType": null,
    "restrictions": null,
    "tier": "Standard"
  },
  "statusOfPrimary": "available",
  "statusOfSecondary": null,
  "tags": {},
  "type": "Microsoft.Storage/storageAccounts"
}
Storage account created.
Creating function apps in Azure...
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.
Function apps created.
Publishing function source code...
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'server_farm_id'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 316, in enable_zip_deploy_functionapp
    parse_plan_id = parse_resource_id(app.server_farm_id)
AttributeError: 'NoneType' object has no attribute 'server_farm_id'

To open an issue, please run: 'az feedback'
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'server_farm_id'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 316, in enable_zip_deploy_functionapp
    parse_plan_id = parse_resource_id(app.server_farm_id)
AttributeError: 'NoneType' object has no attribute 'server_farm_id'

To open an issue, please run: 'az feedback'
Code published. Functions are ready to use.

**Comment by sanjogram** [comment] 2019-11-20 16:24
From: https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/3-exercise-import-function-app-api-management

**Comment by ahmedelnably** [comment] 2019-11-26 19:17
duplicate of #11098

This is not an Azure CLI issue, the script in the Learn module is written against westus region, please change it to another US region (ex. centralus)

You may also want to open the issue against the Learn repo https://github.com/MicrosoftDocs/mslearn-apim-and-functions

**Closed by ahmedelnably** 2019-11-26 19:17 UTC
Labels: Functions, Service Attention
