### ISSUE TITLE
az login errors: ValueError: Unable to get authority configuration

### ISSUE THREAD

**Issue by rjsalicco** [Azure/azure-cli#23021] opened 2022-06-25 01:59 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to get authority configuration for https://login.microsoftonline.com/616941b4-32ab-470d-88a4-3dacc505429b. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/msal/authority.py", line 100, in __init__
    openid_config = tenant_discovery(
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/msal/authority.py", line 169, in tenant_discovery
    raise ValueError(
ValueError: OIDC Discovery endpoint rejects our request. Error: {"error":"invalid_tenant","error_description":"AADSTS90002: Tenant '616941b4-32ab-470d-88a4-3dacc505429b' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\r\nTrace ID: 13655cd9-53b2-4345-8408-a6bb96090f00\r\nCorrelation ID: 154f0209-f4d0-4e3f-bdb2-fd0e8c73371b\r\nTimestamp: 2022-06-25 01:56:46Z","error_codes":[90002],"timestamp":"2022-06-25 01:56:46Z","trace_id":"13655cd9-53b2-4345-8408-a6bb96090f00","correlation_id":"154f0209-f4d0-4e3f-bdb2-fd0e8c73371b","error_uri":"https://login.microsoftonline.com/error?code=90002"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 176, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 745, in find_using_common_tenant
    specific_tenant_credential = identity.get_user_credential(username)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 203, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 39, in __init__
    super().__init__(client_id, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/msal/application.py", line 1525, in __init__
    super(PublicClientApplication, self).__init__(
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/msal/application.py", line 456, in __init__
    self.authority = Authority(
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/msal/authority.py", line 104, in __init__
    raise ValueError(
ValueError: Unable to get authority configuration for https://login.microsoftonline.com/616941b4-32ab-470d-88a4-3dacc505429b. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`
- browser opens
- account is selected
- success message in browser
- error in terminal

## Environment Summary
```
macOS-12.3.1-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.37.0
```

**Comment by yonzhan** [comment] 2022-06-25 02:17
@jiasli for awareness

**Comment by jiasli** [comment] 2022-06-27 09:22
Duplicate of #20507. Please make sure your tenant GUID or name is correct.

**Closed** 2022-06-27 09:41 UTC
Labels: Account, customer-reported, Auto-Assign

**Comment by jiasli** [comment] 2022-07-07 03:27
Wait. @rayluo, shouldn't MSAL fails before "browser opens" phase?
