### ISSUE TITLE
login failure

### ISSUE THREAD

**Issue by alexmlopez** [Azure/azure-cli#21770] opened 2022-03-23 17:40 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
9. The current time MUST be before the time represented by the exp Claim. Current epoch = 1648082367.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/ad5cb5db-ff3d-4135-90cf-0bef39f9cac5/v2.0",
  "iat": 1648056867,
  "nbf": 1648056867,
  "exp": 1648060767,
  "aio": "AVQAq/8TAAAA/FZhBboGci2AZLRTXFefL6D6PugKw2aSdnOaMfypAyvsHQJ8wC3t5jzhSG76vnGC3ipqqod/pt1ZXwEi4J8w0x+rDLCopIGgulq92KJn6Zg=",
  "name": "Alex Lopez",
  "nonce": "b68ff96660b1189dc08e193e56a03977ea43c449b34dae13db7015b506d57ac9",
  "oid": "33b25c6e-0a6a-499c-a6eb-7ea31f49fa85",
  "preferred_username": "AlexLopez@CubescaleTech.onmicrosoft.com",
  "puid": "10032001CEEE3E0E",
  "rh": "0.AUYA27VcrT3_NUGQzwvvOfnKxZV3sATbjRpGu-4C-eG_e0aAAK8.",
  "sub": "1y7Yyj4E3vkm4VpIpyFmwDzun6YCutWKLYOxurULPwo",
  "tid": "ad5cb5db-ff3d-4135-90cf-0bef39f9cac5",
  "uti": "i3acKB50U0aCDn9M-ktkAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 171, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 9. The current time MUST be before the time represented by the exp Claim. Current epoch = 1648082367.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/ad5cb5db-ff3d-4135-90cf-0bef39f9cac5/v2.0",
  "iat": 1648056867,
  "nbf": 1648056867,
  "exp": 1648060767,
  "aio": "AVQAq/8TAAAA/FZhBboGci2AZLRTXFefL6D6PugKw2aSdnOaMfypAyvsHQJ8wC3t5jzhSG76vnGC3ipqqod/pt1ZXwEi4J8w0x+rDLCopIGgulq92KJn6Zg=",
  "name": "Alex Lopez",
  "nonce": "b68ff96660b1189dc08e193e56a03977ea43c449b34dae13db7015b506d57ac9",
  "oid": "33b25c6e-0a6a-499c-a6eb-7ea31f49fa85",
  "preferred_username": "AlexLopez@CubescaleTech.onmicrosoft.com",
  "puid": "10032001CEEE3E0E",
  "rh": "0.AUYA27VcrT3_NUGQzwvvOfnKxZV3sATbjRpGu-4C-eG_e0aAAK8.",
  "sub": "1y7Yyj4E3vkm4VpIpyFmwDzun6YCutWKLYOxurULPwo",
  "tid": "ad5cb5db-ff3d-4135-90cf-0bef39f9cac5",
  "uti": "i3acKB50U0aCDn9M-ktkAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1
```

**Comment by yonzhan** [comment] 2022-03-23 21:56
@jiasli for awareness

**Comment by jiasli** [comment] 2022-03-24 07:02
Duplicate of https://github.com/Azure/azure-cli/issues/20158

**Closed by jiasli** 2022-03-24 07:02 UTC
Labels: Account, customer-reported, CXP Attention, Auto-Assign
