### ISSUE TITLE
az interactive is broken

### ISSUE THREAD

**Issue by vinex22** [Azure/azure-cli#24501] opened 2022-10-31 06:55 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
macOS-13.0-arm64-arm-64bit, Darwin 22.1.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.41.0

Extensions:
ad 0.1.0
interactive 0.4.5
account 0.2.3

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by bebound** [comment] 2022-10-31 07:29
Duplicate of #24213

**Closed by bebound** 2022-10-31 07:29 UTC
Labels: Interactive, customer-reported, Auto-Assign
