### ISSUE TITLE
some weird issue in Az acr build

### ISSUE THREAD

**Issue by RAJMITTAL** [Azure/azure-cli#15588] opened 2020-10-20 19:04 UTC
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
list index out of range
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 579, in execute
    parsed_args = self.parser.parse_args(args)
python3.6/site-packages/knack/parser.py, ln 262, in parse_args
    return super(CLICommandParser, self).parse_args(args)
az/lib/python3.6/argparse.py, ln 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
...
azure/cli/core/command_recommender.py, ln 61, in __init__
    self.parameters = self._normalize_parameters(parameters)
azure/cli/core/command_recommender.py, ln 257, in _normalize_parameters
    standard_form = sorted_options[0]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build --registry {} --image {}`

## Environment Summary
```
Linux-4.15.0-1096-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.13.0

Extensions:
ai-examples 0.2.4

```

**Comment by yonzhan** [comment] 2020-10-21 00:00
acr

**Comment by yugangw-msft** [comment] 2020-10-21 01:35
dupe of #15465

**Closed by yugangw-msft** 2020-10-21 01:35 UTC
Labels: Container Registry, Service Attention
