### ISSUE TITLE
az resource delete --ids get bad request when the resources are different types

### ISSUE THREAD

**Issue by Joseluismantilla** [Azure/azure-cli#12798] opened 2020-03-31 00:14 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

I am trying to delete a vm with all its resources but the command shows a bad request for an internal azure  url.

**Describe the bug**

the az resource delete --ids cannot remove resources by ids with different types.
Messages:

400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/c97666f2-4562-400d-821a-51692e1d20c3/resourceGroups/PRUEBA/providers/Microsoft.Compute/disks/test1_disk1_88781d0436254276a4e2c3b81a78bb2f%09test1_disk1_88781d0436254276a4e2c3b81a78bb2f?api-version=2019-11-01
400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/c97666f2-4562-400d-821a-51692e1d20c3/resourceGroups/prueba/providers/Microsoft.Compute/virtualMachines/test1%09test1?api-version=2019-12-01
400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/c97666f2-4562-400d-821a-51692e1d20c3/resourceGroups/prueba/providers/Microsoft.Network/networkInterfaces/test1VMNic%09test1VMNic?api-version=2020-03-01
400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/c97666f2-4562-400d-821a-51692e1d20c3/resourceGroups/prueba/providers/Microsoft.Network/networkSecurityGroups/test1NSG%09test1NSG?api-version=2020-03-01
400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/c97666f2-4562-400d-821a-51692e1d20c3/resourceGroups/prueba/providers/Microsoft.Network/publicIPAddresses/test1PublicIP%09test1PublicIP?api-version=2020-03-01
400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/c97666f2-4562-400d-821a-51692e1d20c3/resourceGroups/prueba/providers/Microsoft.Network/virtualNetworks/test1VNET%09test1VNET?api-version=2020-03-01

**To Reproduce**

1) Create a vm called test1 inside prueba resource group.
2) Delete it by id with all its resources with the command:
az resource delete --ids $(az resource list -g prueba  --query "[?contains(name,'test1')].{id:id, Name:name}" -o tsv) --verbose

**Expected behavior**

All the resources listed by id deleted
**Environment summary**

**Additional context**

**Comment by yonzhan** [comment] 2020-03-31 01:46
add to S169

**Comment by zhoxing-ms** [comment] 2020-04-17 08:28
Hi @Joseluismantilla, I can't reproduce your question. Could you please provide the following information?
1. You can view the Activity log of the Resource Group(prueba) on the portal after the delete operation fails. After clicking the failed operation name, there is a JSON information corresponding to the failure reason, then please tell me what is the error message?
2. If there is no obvious clue in step 1, could you please add `--debug` to the original command and execute it? Then please show me the information returned by debug.

**Comment by zhoxing-ms** [comment] 2020-04-28 08:36
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-04-28 08:36 UTC
Labels: ARM, OKR3.2 Candidate, feature-request
