### ISSUE TITLE
`vmss disk attach` makes `latestModelApplied` become false

### ISSUE THREAD

**Issue by whites11** [Azure/azure-cli#18259] opened 2021-05-27 13:50 UTC
## Describe the bug

**Command Name**
`az vmss disk attach --disk $diskid --lun $LUN --ids $INSTANCEID`

I have a VMSS with `health probes` and `Rolling` `Upgrade Policy`.
I attach a managed disk to one instance using `az vmss disk attach`.
The command succeeds and the disk gets attached as expected to the VMSS instance BUT:
- the instance's latest model applied flag becomes false
- the health state does not report `Healthy` nor `Unhealthy` any more
- It's impossible to recover because the `Update` function is blocked (it requires setting the `Upgrade Mode` to `Manual`).

![az](https://user-images.githubusercontent.com/868430/119837400-d5a2fb00-bf02-11eb-8fbe-696f8ea82057.png)

If I attach the disk using the azure portal it works as expected.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a VMSS with health probe and `Upgrade Mode` = `Rolling`
- run `az vmss disk attach` to attach a managed disk to one of the instances

## Expected Behavior

Latest model should still be applied and Health state should still be `Healthy`.

## Environment Summary
```
Linux-5.12.5-arch1-1-x86_64-with-glibc2.33
Python 3.9.5
Installer: 

azure-cli 2.22.1 *

```

**Comment by yonzhan** [comment] 2021-05-27 15:14
Compute

**Comment by avirishuv** [comment] 2021-07-14 20:27
@whites11 thanks for the question. Let me try to repro the issue and will get back with an update here soon.

**Comment by avirishuv** [comment] 2021-08-19 19:07
hi @whites11 sorry for the delay. Are you still observing this issue?

When I repro'd it does not occur. I created a VMSS with upgrade mode as Rolling and Health monitoring enabled. I added a disk to one instance using CLI cmd, but all the instances in the portal still show as Latest Model = Yes.

**Comment by whites11** [comment] 2021-08-23 11:05
I confirm this does not seem to happen any more

**Comment by avirishuv** [comment] 2021-09-09 18:57
Thanks @whites11 for confirming that the issue is not happening any more. Closing the issue.

**Closed by avirishuv** 2021-09-09 18:57 UTC
Labels: Compute, Service Attention, question
