### ISSUE TITLE
Installing extension progress shows escape code '?[K'

### ISSUE THREAD

**Issue by Eilon** [Azure/azure-cli#9627] opened 2019-06-10 23:32 UTC
## Describe the bug

Running `az interactive` for the first time causes it to install the interactive extension. The progress bar for download/installation renders incorrectly:

![image](https://user-images.githubusercontent.com/202643/59233392-0e722a00-8b9d-11e9-935a-22a622ab771e.png)

Note the escape sequence (ANSI escape?) at the bottom left.

## To Reproduce:
1. Fresh install of Azure CLI on Windows 10
2. Open CMD window
3. Run `az interactive`
4. Watch progress bar

## Expected Behavior
Escape codes should not be visible in the command window.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.66

Extensions:
interactive 0.4.3

```

**Comment by tjprescott** [comment] 2019-06-11 13:02
Duplicate of #9122.

**Closed by tjprescott** 2019-06-11 13:02 UTC
Labels: Bug, Output
