### ISSUE TITLE
[DNS] zone import TXT api bad request

### ISSUE THREAD

**Issue by ddfs** [Azure/azure-cli#6122] opened 2018-04-15 22:48 UTC
zone import fails to add TXT record for "v=spf1 redirect=_spf.yandex.net" 
all other TXT records processed properly.  DKIM etc.

record that import fail:

domain.fi.                       IN TXT	"v=spf1 redirect=_spf.yandex.net"

error detail:

400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/sub-id-here/resourceGroups/myresource-name/providers/Microsoft.Network/dnsZones/domain.fi/TXT/@?api-version=2018-03-01-preview

---

### Environment summary
$ az --version
azure-cli (2.0.30)

acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.1.0)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.20)
core (2.0.30)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.20)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.20)
monitor (0.1.4)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.21)
rdbms (0.2.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.30)
vm (2.0.29)

Python location '/opt/az/bin/python3'
Extensions directory '/home/thuser/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Mar 23 2018, 16:30:39) 
[GCC 6.3.0 20170516]

Legal docs and information: aka.ms/AzureCliLegal

OS: Linux thuser 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux

```
```

**Comment by tjprescott** [comment] 2019-03-21 18:49
I cannot even create this record manually. It says:
```
Operation failed with status: 'Bad Request'. Details: The resource records' relative name 'domain.fi.' must not end with a dot.
```

When I try to import this I get:
```
Record names '['domain.fi.']' are not part of the domain.
```

So I believe this is by design and will be closing this issue.

**Closed by tjprescott** 2019-03-21 18:49 UTC
Labels: Network - DNS
