### ISSUE TITLE
az ml environment delete feature is broken 

### ISSUE THREAD

**Issue by AnijaJacob** [Azure/azure-cli#21957] opened 2022-04-06 15:02 UTC
**Describe the bug**

Latest version of az ml extension (2.21) doesn't seem to support 'delete' method for environment class. Same was working fine in earlier release.
**To Reproduce**

az ml environment delete --name <name>  --resource-group <group> --workspace-name <name > -v <versionname> 

**Expected behavior**

Environment deleted successfully
**Environment summary**

az --version
azure-cli                         2.35.0

core                              2.35.0
telemetry                          1.0.6

Extensions:
ml                                 2.2.1

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

**Additional context**

**Comment by yonzhan** [comment] 2022-04-06 22:39
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-04-07 04:01
@AnijaJacob Thank you for reaching out to us. We are looking into it.

**Comment by RakeshMohanMSFT** [comment] 2022-04-07 16:54
@azureml-github FYI

**Comment by bandsina** [comment] 2022-04-07 17:26
Hi @AnijaJacob , thank you for the report and for using the new CLIv2. Appreciate it! 

With the CLIv2 version released on 3/14, delete functionality has been moved to archive verb. Could you please see if that satisfies your requirements? 

Link to release notes and relevant section copied below: 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli 

- Removed the delete commands for assets (model, component, data, environment). The existing delete functionality is only a soft delete, so the delete commands will be reintroduced in a later release once hard delete is supported
- Added support for archiving and restoring assets (model, component, data, environment) and jobs, e.g. az ml model archive and az ml model restore. You can now archive assets and jobs, which will hide the archived entity from list queries (e.g. az ml model list).

**Comment by AnijaJacob** [comment] 2022-04-08 07:00
@bandsina thanks for the update.
Yes I did tried using 'archive' functionality , but the environment is still getting listed over studio UI.
The main issue for us is that the conda file for the AML environment holds sensitive information .
![image](https://user-images.githubusercontent.com/38662956/162381603-4516a403-b7cc-4f02-bdf2-02d735074e82.png)

These are the credentials to our private artifactory from which we are installing few private python packages needed for the train file. These credentials are fetched from Azure Keyvvault using get_secret() method and is used in the pip command as below:
```
keyvault = aml_workspace.get_default_keyvault()
jfrog_token = keyvault.get_secret(name="token")
jfrog_user = keyvault.get_secret(name="user)
```
`conda.set_pip_option(f"--index-url https://{jfrog_user}:{jfrog_token}@xxxx.jfrog.io/artifactory/api/pypi/yyyy") `).

Can you provide suggestions on how to handle sensitive information with AML environment conda file?

**Comment by RakeshMohanMSFT** [comment] 2022-04-18 10:34
@AnijaJacob Can you please file a support ticket to help you with this issue further? This issue would require a some further investigation to identity the root cause. 

If you **do not have** a support contract, could you please share the below details over an email with the subject line “Attn: ramarath” to AzCommunity[at]Microsoft[dot]com referencing this github thread?

**Details required**
Your Resource and Resource group name
Your subscription id

Awaiting your reply.

**Comment by AnijaJacob** [comment] 2022-04-25 07:36
#2204200030000708  created for same

**Comment by RakeshMohanMSFT** [comment] 2022-04-25 08:40
Thank you @AnijaJacob. I will go ahead and close this Issue, the rest of the troubleshooting will happen through the support ticket. If you need any further assistance please go ahead and open this issue.

**Closed by RakeshMohanMSFT** 2022-04-25 08:40 UTC
Labels: Machine Learning, customer-reported, needs-team-attention, CXP Attention, Auto-Assign

**Comment by thomasv1995** [comment] 2022-09-06 14:28
Could someone please explain to me the rationale behind not allowing users to properly delete (not archive) environments? We can delete jobs, experiments, models, but for some reason we can't do it for environments.

**Comment by gre-jkpoynter** [comment] 2025-01-29 17:32
Whilst I appreciate there's a really important principle around archiving vs deleting to ensure that production workloads are maintainable, as  others have mentioned there are legitimate reasons for wanting to delete data associated with an environment - perhaps it's a more privileged operation but it should not be blocked... especially in an environment where data scientists are doing experimentation.
