### ISSUE TITLE
It takes too long to list all images

### ISSUE THREAD

**Issue by root0day** [Azure/azure-cli#20832] opened 2021-12-26 16:04 UTC
I am trying to export all image information (name) via cli tool in Azure Cloud Shell
But there has been no output for five minutes
I think the waiting time is too long

![image](https://user-images.githubusercontent.com/26130494/147413706-b3117cfc-96ec-4d00-a038-3730a8080791.png)

**Comment by yonzhan** [comment] 2021-12-27 00:31
The long time is caused by service

**Comment by jiasli** [comment] 2021-12-27 03:28
I am also concerned with this command `az vm image list --all`. It takes too long to finish. At least some progress should be given.

**Comment by Drewm3** [comment] 2022-04-07 20:05
This method does allow for filtering by region, publisher, offer, SKU and edge zone already. If you only need a subset of the images, then using one of these methods is highly recommended.   If you truly need the full list, then it will take some time to download the list.

In order for the client side tool like the CLI to provide a progress bar it would need to know the total count of images, and then display a progress using this Infomation. Currently we do not generally offer interfaces to just get the count in order to provide the data for a progress bar because most applications do not need to download the full list of images. So, I am closing this request for now because we are not planning to change the API in the near-term.

**Closed by Drewm3** 2022-04-07 20:05 UTC
Labels: Compute, Service Attention, customer-reported, feature-request

**Comment by jvmap** [comment] 2026-04-10 08:44
It's still absurdly slow in 2026. But I found this website which is much faster https://az-vm-image.info/
