### ISSUE TITLE
az aks create unrecognized argument --nodepool-name

### ISSUE THREAD

**Issue by odhekar** [Azure/azure-cli#8572] opened 2019-02-19 18:28 UTC
**Describe the bug**
when creating a k8s cluster, i cannot specify node pool name in latest available update.

**To Reproduce**
1. create a service principal and secret for use with aks cluster
1. export SP_NAME=
1. export SP_SECRET=
1. export SUBSCR=
1. az aks create -n aks-gitlab -g rg-mygroup --location eastus --subscription $SUBSCR --node-count 1 --node-vm-size Standard_B4ms --node-osdisk-size 30 --dns-name-prefix gitlabrunner --admin-username centos --service-principal $SP_NAME --client-secret $SP_SECRET  --kubernetes-version 1.12.5  --enable-cluster-autoscaler --enable-vmss --min-count 1 --max-count 5 --nodepool-name gitlab

This results in error,
```
az: error: unrecognized arguments: --nodepool-name gitlab
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {aks} ...
```

**Expected behavior**
cluster is created with the provided nodepool name

**Environment summary**
```
user@mysystem:/repos/gitlab-k8s-runner/auto$ az --version
azure-cli                         2.0.58

acr                                2.2.0
acs                               2.3.17
advisor                            2.0.0
ams                                0.4.1
appservice                        0.2.13
backup                             1.2.1
batch                              3.4.1
batchai                            0.4.7
billing                            0.2.0
botservice                         0.1.6
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices                  0.2.4
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.13
core                              2.0.58
cosmosdb                           0.2.7
dla                                0.2.4
dls                                0.1.8
dms                                0.1.2
eventgrid                          0.2.1
eventhubs                          0.3.3
extension                          0.2.3
feedback                           2.1.4
find                              0.2.13
hdinsight                          0.3.0
interactive                        0.4.1
iot                                0.3.6
iotcentral                         0.1.6
keyvault                          2.2.11
kusto                              0.1.0
lab                                0.1.5
maps                               0.3.3
monitor                           0.2.10
network                            2.3.2
nspkg                              3.0.3
policyinsights                     0.1.1
profile                            2.1.3
rdbms                              0.3.7
redis                              0.4.0
relay                              0.1.3
reservations                       0.4.1
resource                          2.1.10
role                               2.4.0
search                             0.1.1
security                           0.1.0
servicebus                         0.3.3
servicefabric                     0.1.12
signalr                            1.0.0
sql                                2.1.9
sqlvm                              0.1.0
storage                            2.3.1
telemetry                          1.0.1
vm                                2.2.15

Extensions:
aks-preview                        0.2.2

Python location '/opt/az/bin/python3'
Extensions directory '/home/user/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Feb 12 2019, 02:10:26)
[GCC 7.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**

**Comment by mboersma** [comment] 2019-02-19 19:18
@odhekar it looks like you have the [AKS preview extensions](https://github.com/Azure/azure-cli-extensions/tree/master/src/aks-preview) installed. If I run an `az aks create` command without the extension, it works fine (as expected):

```
$ az aks create -n aks-gitlab -g rg-mygroup --location eastus \
    --subscription $SUBSCR --node-count 1 --node-vm-size Standard_B4ms \
    --node-osdisk-size 30 --dns-name-prefix gitlabrunner --admin-username centos \
    --service-principal $SP_NAME --client-secret $SP_SECRET  --kubernetes-version 1.12.5 \
    --nodepool-name gitlab
```

Let me try a few more tests to see where the problem is specifically.

**Comment by mboersma** [comment] 2019-02-19 19:30
Once I installed the preview module with `az extension add --name aks-preview`, the above command no longer works. I the `error: unrecognized arguments: --nodepool-name` as described in this bug.

I created Azure/azure-cli-extensions#530 to track this in the extensions repo. cc: @zqingqing1

**Comment by odhekar** [comment] 2019-02-19 19:32
thanks @mboersma

**Comment by zqingqing1** [comment] 2019-02-19 21:02
@mboersma , thanks, I created bug at VSTS. And will work on the fix at az cli extension.

**Comment by tjprescott** [comment] 2019-02-19 21:09
Since this is an issue with the CLI extension, I will close this issue.

**Closed by tjprescott** 2019-02-19 21:09 UTC
Labels: AKS
