### ISSUE TITLE
Deployment issue with azure function:Trying to deploy zip file through azure cli

### ISSUE THREAD

**Issue by sunil110** [Azure/azure-cli#13127] opened 2020-04-23 02:10 UTC
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

Example: azfunctionapp deployment source config-zip -g azureGeoGroup -n \azureGeo --src https://drive.google.com/drive/u/0/folders/1OiWIOVTDAQE87U3z5yOizLyUjKFWoZ6J/hlsAPIGeocoder.zip
**Errors:**
```
[Errno 22] Invalid argument: 'C:\\Users\\Sanjay\\https:\\drive.google.com\\drive\\u\\0\\folders\\1OiWIOVTDAQE87U3z5yOizLyUjKFWoZ6J\\hlsAPIGeocoder.zip'
Traceback (most recent call last):
pip-install-_1mlo87m\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 625, in execute
cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
cli\core\commands\__init__.py, ln 682, in _run_job
Temp\pip-install-_1mlo87m\six\six.py, ln 703, in reraise
...
cli\command_modules\appservice\custom.py, ln 367, in enable_zip_deploy
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Sanjay\\https:\\drive.google.com\\drive\\u\\0\\folders\\1OiWIOVTDAQE87U3z5yOizLyUjKFWoZ6J\\hlsAPIGeocoder.zip'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1 *

```

**Comment by yonzhan** [comment] 2020-04-23 02:37
functionapp

**Comment by yungezz** [comment] 2020-04-24 12:32
from the error, the command expecting a local file path instead remote url

**Comment by fabiocav** [comment] 2020-04-28 18:09
That is correct. Currently, only local files are supported. 

Closing as "by design", please let us know if you have any additional questions.

**Closed by fabiocav** 2020-04-28 18:09 UTC
Labels: Functions, Service Attention, customer-reported
