### ISSUE TITLE
[Errno 104] Connection reset by peer when downloading PostgreSQL server logs

### ISSUE THREAD

**Issue by YiYingWu1302** [Azure/azure-cli#18969] opened 2021-07-23 04:45 UTC
## Describe the bug
This command failed with the following errors when downloading postgres server logs (which is around 27Mb).
Download time: 2021/07/23 04:4x UTC
Download file: `postgresql-2021-07-23_040000.log`

**Command Name**
`az postgres server-logs download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/rdbms/custom.py", line 574, in _download_log_files
    urlretrieve(f.url, f.name)
  File "/opt/az/lib/python3.6/urllib/request.py", line 277, in urlretrieve
    block = fp.read(bs)
  File "/opt/az/lib/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/opt/az/lib/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/opt/az/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/az/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/az/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/opt/az/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres server-logs download -g {} -s {} --subscription {} -n {}`

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.24.0 *

Extensions:
application-insights 0.1.13

```

**Comment by yonzhan** [comment] 2021-07-23 05:05
route to service team

**Comment by nachoalonsoportillo** [comment] 2024-07-04 21:47
@YiYingWu1302 Thanks for reporting this issue. I'm not able to reproduce the error with even bigger log files. Notice that this error can also be caused if the connection is severed by any networking artifact (physical or virtual) through which the communication is routed. I've also tested it on the equivalent functionality in Flexible Server and I'm not able to reproduce it there either.

**Comment by nachoalonsoportillo** [comment] 2024-07-04 21:47
@yonzhan Please, proceed to close this one. Thanks!

**Closed** 2024-07-04 23:43 UTC
Labels: Service Attention, PostgreSQL
