### ISSUE TITLE
Webapp:Can't run azure cli commands because of error

### ISSUE THREAD

**Issue by kaalkop** [Azure/azure-cli#15204] opened 2020-09-18 04:14 UTC
## Describe the bug

**Command Name**
`az webapp show`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp show`

## Environment Summary
```
Linux-5.4.0-47-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81 *

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment] 2020-09-18 06:35
hi @kaalkop this is a known issue in version 2.0.81 https://github.com/Azure/azure-cli/issues/14011. Could you pls try install latest Azure CLI to resolve the issue? Thanks.

**Comment by fengzhou-msft** [comment] 2020-09-23 09:49
Duplicate of #14011

**Closed by fengzhou-msft** 2020-09-23 09:49 UTC
Labels: Packaging, Web Apps
