### ISSUE TITLE
AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access.

### ISSUE THREAD

**Issue by xkszltl** [Azure/azure-cli#17714] opened 2021-04-15 13:05 UTC
**Describe the bug**

We hit **AADSTS70043** for months, with at least 2 failures every day.
As you can see, there's some kind of 12h conditional access policy, and after timeout `az acr` cannot handle it properly.
It doesn't prompt for re-login or have machine-readable way to let us do so automatically.

**To Reproduce**

```
% az acr credential show --name <****************>                                  
AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-04-14T21:31:07.1749157Z and the maximum allowed lifetime for this request is 43200.
Trace ID: 150de44a-fe53-4165-8f75-59d63f6d1e00
Correlation ID: 6d45f5c4-8f32-48ad-9945-2476bbb60fa0
Timestamp: 2021-04-15 12:43:15Z
To re-authenticate, please run `az login`. If the problem persists, please contact your tenant administrator.
```

**Expected behavior**

1. Prompt for re-login, probably with a flag for backward compatibility.
2. Provide subcommand to detect this.
    - We have some parallelism on top, meaning an auto-prompt may not be handled by user properly. So we'd like to detect this in advance in serial section.

**Environment summary**

- Homebrew for macOS
- apt-get for Ubuntu 18.04

**Version on macOS:**

```
{
  "azure-cli": "2.21.0",
  "azure-cli-core": "2.21.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Comment by xkszltl** [comment] 2021-04-15 13:14
Note that we don't want to blindly call `az login` everytime because:
- It's slow.
- Browser interaction cannot be automated.
- It's interruptive, and may trigger additional 2FA causing even more burden.

**Comment by yungezz** [comment] 2021-04-16 01:32
route to appropriate team

**Comment by yugangw-msft** [comment] 2021-04-16 02:22
The refresh token has expired hence you have to run `az login`. If you would like automation support, consider service principal or managed identity
I am closing this ticket because this is not an ACR issue and it is by design unfortunately.

**Closed by yugangw-msft** 2021-04-16 02:22 UTC
Labels: Container Registry, Service Attention, question

**Comment by xkszltl** [comment] 2021-04-16 17:59
@yugangw-msft 
I think you probably misunderstood the issue.
We are aware of the 12h limit and it's not done by ACR.
The main issue is: we need a machine-readable way to capture this error, so that our code can tell what's the next step.
Currently we only have a text msg on screen with exit code 1.
`grep` it may be a temporary option but we're looking for a more decent way.

**Comment by yugangw-msft** [comment] 2021-04-16 19:12
@xkszltl, the text should go to stderr. Unless you write program calling the same authentication API like CLI does which give you a native way to capture the exception, `exit code` + `grep` is the only way to work with a command.

**Comment by xkszltl** [comment] 2021-04-18 17:06
> `exit code` + `grep` is the only way to work with a command.

What exactly does exit code 1 mean?
Can any non-auth-related error exit with 1?
We'd like a well-defined error, e.g. a special exit code that only applies to one class of error, rather than grep text that we don't know if it will change in the future or not.

**Comment by jodyford** [comment] 2021-06-18 17:54
@yugangw-msft are you going to answer?

**Comment by yonzhan** [comment] 2021-06-19 00:45
acr service team should take a look

**Comment by jiasli** [comment] 2023-06-14 01:15
Duplicate of https://github.com/Azure/azure-cli/issues/16209
