### ISSUE TITLE
Cannot check table exists using SAS token

### ISSUE THREAD

**Issue by jjcollinge** [Azure/azure-cli#3784] opened 2017-06-20 17:10 UTC
### Description
I've been having issues with the following call on Linux

```
az storage table exists --name <my-table-name> --account-name <my-acc-name> --sas-token "<my-sas-token>"
```
The response is simply;

` Forbidden`

I've created the sas-token via az-cli with -o tsv and the Portal. Hence it is not the previously raised issue with the '?' prefixed on the token.

All other calls I've tested using `az storage table ...` with the same sas-token have worked fine. I can use the sas-token in the browser as well. I've reproduced this on Bash on Windows and on a Linux VM in Azure. The exact same call works when running az in Windows PowerShell.

Note: If I remove the enclosing quotes (") around the SAS token, then I will get a response but it is incorrect and actually loads each of the key value pairs from the SAS token (.i.e. st=2017-06-19T16) into the SHELL as environment variables as it expands the command.

Adding `--debug` gives me the following output:

```
Command arguments ['storage', 'table', 'exists', '--name', '<my-table-name>', '--account-name', '<my-acc-name>', '--sas-token', '<my-sas-token>']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/'},
 'is_active': True,
 'name': 'AzureCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x7ff86be9de18>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x7ff86be9de18>
Successfully loaded command table from module 'storage'.
Application event 'CommandTable.Loaded' with event data {'command_table': {'storage table exists': <azure.cli.core.commands.CliCommand object at 0x7ff86be320b8>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'storage table exists': <azure.cli.core.commands.CliCommand object at 0x7ff86be320b8>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['storage', 'table', 'exists', '--name', 'networkbootnodes', '--account-name', 'dotjsonquorum', '--sas-token', 'st=2017-06-19T16%3A28%3A00Z&se=2017-06-24T16%3A28%3A00Z&sp=r&sv=2015-12-11&tn=networkbootnodes&sig=hoWsNqLvbkYJhETMlmlDcwEz0GIb0229Vja0mAmF7CU%3D']}
Application event 'CommandParser.Parsed' with event data {'command': 'storage table exists', 'args': Namespace(_command_package='storage', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az storage table exists', usage=None, description='Returns a boolean indicating whether the table exists.', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[<function validate_client_parameters at 0x7ff86bebd2f0>], accou [...]
Getting data service client service_type=TableService
requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): dotjsonquorum.table.core.windows.net
requests.packages.urllib3.connectionpool : https://dotjsonquorum.table.core.windows.net:443 "GET /Tables('networkbootnodes')?st=2017-06-19T16%3A28%3A00Z&se=2017-06-24T16%3A28%3A00Z&sp=r&sv=2015-12-11&tn=networkbootnodes&sig=hoWsNqLvbkYJhETMlmlDcwEz0GIb0229Vja0mAmF7CU%3D HTTP/1.1" 403 None
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Installed on Bash on Windows via apt-get, installed on Linux VM via curl install script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:  azure-cli (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here: Bash on Windows (Creators update), Ubuntu 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows and bash on Ubuntu

**Comment by troydai** [comment] 2017-06-20 17:43
@jjcollinge thank you for reporting this issue. The reason why your sas token doesn't work is that you created a __table__ sas token, which manages the permission of access objects in the scope of given table. To generate a sas token to validate the existence of a table, you need a sas token at the account level.

Here's an example:
``` BASH
10:35 $ az storage account generate-sas --expiry '2017-12-31T00:00Z' --permissions ldpruwac --resource-types sco --services bfqt
"se=2017-12-31T00%3A00Z&sp=rwdlacup&sv=2016-05-31&ss=bqtf&srt=sco&sig=TzTpRlOK/kTIf13A5T5byool2S3/8LOMtJ%2BSPH5qJqQ%3D"

10:35 $ az storage table exists -n table01 --account-name trdaitest01 --sas-token 'se=2017-12-31T00%3A00Z&sp=rwdlacup&sv=2016-05-31&ss=bqtf&srt=sco&sig=TzTpRlOK/kTIf13A5T5byool2S3/8LOMtJ%2BSPH5qJqQ%3D'
{
  "exists": true
}
```
_In above command, I grand all permissions on all types of resources. You can tailor the scope based on your need._

**Comment by troydai** [comment] 2017-06-20 17:44
I'll close this issue since it is not a bug. Please feel free to share your concern or suggestions.

**Closed by troydai** 2017-06-20 17:44 UTC
Labels: Storage
