### ISSUE TITLE
Data Lake Store - can't list files under root directory

### ISSUE THREAD

**Issue by matt1883** [Azure/azure-cli#3400] opened 2017-05-19 01:12 UTC
### Description
Using Data Lake Store's command to list files, I get an exception when passing in "" or "/" as the path to indicate that I want to list files/folders under the account's root directory.

When running `az dls fs show --account myaccount --path "/"`, below is the error output. Other folder paths work just fine.

```
.
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 473, in _execute_command
    reraise(*sys.exc_info())
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 450, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\command_modules\dls\custom.py", line 111, in get_adls_item
    return cf_dls_filesystem(account_name).info(path)
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\datalake\store\core.py", line 145, in info
    raise FileNotFoundError(path)
FileNotFoundError: .
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
container (0.1.4)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
documentdb (0.1.5)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
shell (0.2.2)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Windows) 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]

Python location 'C:\Users\***\AppData\Local\Programs\Python\Python35\python.exe'

**OS Version:** What OS and version are you using?  
Answer here:
Microsoft Windows [Version 10.0.15063]

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
cmd.exe

**Comment by akharit** [comment] 2018-11-26 22:09
I am not able to reproduce this issue. My best guess is that it was fixed a while ago, since the version mentioned in the description is quite old. Please close this.

**Closed** 2018-11-27 01:04 UTC
Labels: Data Lake Store
