### ISSUE TITLE
AZ login is failing with CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by vyshnavi-gadiparthi** [Azure/azure-cli#23886] opened 2022-09-14 10:27 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/oauth2/v2.0/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.40.0
```

**Comment by yonzhan** [comment] 2022-09-14 10:57
Duplicate of https://github.com/Azure/azure-cli/issues/19571

**Closed by yonzhan** 2022-09-14 10:57 UTC
Labels: Account, customer-reported, Auto-Assign
