### ISSUE TITLE
az aks pod-identity add fails to add role assignment

### ISSUE THREAD

**Issue by jackmtrayport** [Azure/azure-cli#26121] opened 2023-04-12 10:20 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az aks pod-identity add --resource-group "xxx" --cluster-name "xxx" --namespace "xxx" --name "xxxy" --identity-resource-id "/subscriptions/xxx"

**Describe the bug**
With az cli 2.47.0 and the aks-preview extension 0.5.118+, the above command will fail to add the Managed Identity Operator role assignment for the AKS cluster over the managed identity. It will not report any errors, but instead will just print `Waiting for AAD role to propagate` until the percentage reaches 100% and it gives up and prints `Could not grant Managed Identity Operator permission for cluster`. Running with --debug shows that GET requests are made for the AKS cluster, the managed ID and the managed ID's role assignments and then nothing else. Doing the same with az cli 2.42.0 showed a GET for the Managed Identity Operator role definition (to fetch it's ID) and then a PUT to actually assign that role over the managed ID (followed by the rest of the requests to create the pod-identity).

**To Reproduce**
Run the above command with valid rg/cluster name etc.

**Expected behavior**
The pod-identity should be created.

**Environment summary**
> az --version
azure-cli                         2.47.0

core                              2.47.0
telemetry                          1.0.8

Extensions:
aks-preview                      0.5.118

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

**Additional context**

**Comment by yonzhan** [comment] 2023-04-12 10:21
Thank you for opening this issue, we will look into it.

**Comment by tiagofu-ms** [comment] 2023-04-14 09:53
Hi yesterday I had a discussion regarding this same issue and seems to affect every user, as it seems to be a regression to an issue previously reported here https://github.com/Azure/azure-cli-extensions/issues/3679

![image](https://user-images.githubusercontent.com/85108752/232011785-8f0bb4ef-3562-4965-9294-d4f5dae23246.png)


For now the mitigation was to downgrade az cli to version 2.45.0.

![image](https://user-images.githubusercontent.com/85108752/232011896-56a9b2f1-673a-499f-8c21-ad25a2750031.png)

**Comment by sorin-united** [comment] 2023-04-14 10:26
Hello, we have been facing the exact same issue and the mitigation to downgrade az cli to version 2.45.0 works fine - but hoping this issue is solved in the latest version of the cli since we might need to use it at one point.

Looking forward to updates from development team on this issue.

**Comment by SaurabhSharma-MSFT** [comment] 2023-04-24 18:33
@jackmtrayport I am not able to reproduce this.  I have tried multiple times but cmdlet worked fine with CLI version **2.47** - 
![image](https://user-images.githubusercontent.com/38112130/233713851-66ece2d2-fb53-43ec-b409-a6c88393971d.png)
![image](https://user-images.githubusercontent.com/38112130/233714036-60fffa80-866f-4b57-a893-4356af5c3223.png)
Can you please upgrade your `aks-preview` version and test again.

**Comment by SaurabhSharma-MSFT** [comment] 2023-04-26 19:39
@jackmtrayport Please let us know if you are still having problems.

**Comment by jackmtrayport** [comment] 2023-04-27 10:06
I've not had to add any more pod identities since I downgraded my azcli, so if I have more issues in future I'll let you know.

**Comment by SaurabhSharma-MSFT** [comment] 2023-04-27 14:50
@jackmtrayport Thanks for the confirmation. We will now proceed to close this thread. Thanks again.

**Closed by SaurabhSharma-MSFT** 2023-04-27 14:50 UTC
Labels: bug, AKS, customer-reported, needs-team-attention, CXP Attention, Auto-Assign

**Comment by jackmtrayport** [comment] 2023-05-15 11:12
@SaurabhSharma-MSFT I just tried to add another one and it failed in the same way.

$ az --version
azure-cli                         2.48.1

core                              2.48.1
telemetry                          1.0.8

Extensions:
aks-preview                      0.5.116

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/vsts/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.10/site-packages/azure-cli-extensions'

Python (Linux) 3.10.10 (main, Apr 25 2023, 04:23:10) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by Kruti-Joshi** [comment] 2023-08-08 21:29
@SaurabhSharma-MSFT , I still see this issue with Az CLI 2.51.0 -

![image](https://github.com/Azure/azure-cli/assets/10906811/ce402918-734a-469f-a62a-1e6da8bf55d0)

**Comment by FumingZhang** [comment] 2023-09-08 05:25
Hey @jackmtrayport, @Kruti-Joshi, please upgrade your aks-preview to 0.5.137+.

The bug was caused by a breaking change of the auth SDK in core azure-cli and the fix on aks-preview side is applied in [0.5.137](https://github.com/Azure/azure-cli-extensions/pull/6203).

**Comment by RichardPenswick** [comment] 2023-09-13 11:25
Has anyone had success with this - Ive changed cli and aks-preview versions but still getting errors. 

![image](https://github.com/Azure/azure-cli/assets/113374549/d7fd6609-cacb-4074-8c9e-24250512b1d9)

**Comment by RichardPenswick** [comment] 2023-09-13 13:22
@FumingZhang doh!!! I was using my login rather than the elevated SP. 

thanks so much, silly error thanks
