### ISSUE TITLE
az monitor app-insights api-key show does not return the api-key value

### ISSUE THREAD

**Issue by ehuggz** [Azure/azure-cli#10132] opened 2019-08-02 17:00 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az monitor app-insights api-key show --app <AppInsightsName> -g <ResourceGroup> does not return application insights key and instead returns a blank line.

**To Reproduce**

1. Connect to Subscription with az login
2. Set Subscription with az account set --s <SubscriptionName>
3. Verify Subscription properly set with az account show
4. Run command az monitor app-insights api-key show --app <AppInsightsName> -g <ResourceGroup>

**Expected behavior**
The Application Insights key with the Application Insights  Name specified by the --app directive should be returned

**Environment summary**
Installed in WSL Bash and Windows
Tested via Bash and Windows Powershell.
Both environments display the same behavior.

**Additional context**

**Comment by yonzhan** [comment] 2019-10-14 05:44
@MyronFanQiu  please take a look.

**Comment by MyronFanQiu** [comment] 2019-11-12 08:25
@ehuggz Sorry for the delay. I just tried to reproduce the error. But it show the api-key successfully. Did you create a api-key before?

**Comment by MyronFanQiu** [comment] 2019-11-19 04:25
@ehuggz Hello. I cannot reproduce this error. Maybe you can try to create a api-key before showing it. I will close this issue first. Do not hesitate to re-open it if you have any more question.

**Closed by MyronFanQiu** 2019-11-19 04:25 UTC
Labels: Monitor, Monitor - ApplicationInsights
