### ISSUE TITLE
WebApp:`az webapp up` by default resets the Python version to 3.7

### ISSUE THREAD

**Issue by larsschellhas** [Azure/azure-cli#16777] opened 2021-02-02 18:18 UTC
## Describe the bug
When running `az webapp up` without the "runtime" flag, the Python version of my webapp is always reset to 3.7, although my Python app is running in Python 3.8. 
While `az webapp up` does store other default values from the first deployment in the config file, it does not do so with the runtime version.

**Command Name**
`az webapp up`

## To Reproduce:
- _Put any pre-requisite steps here..._
- `az webapp up --runtime "PYTHON|3.8 --other-args"`
- `az webapp up`

## Expected Behavior
Running `az webapp up` with a new flag should always store that setting as a standard in the config file. This should include the runtime, Python version etc. 

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.18.0

Extensions:
db-up 0.2.0

```

**Comment by yonzhan** [comment] 2021-02-02 23:24
webapp

**Comment by Kotasudhakarreddy** [comment] 2021-02-04 16:00
Looking in to it.

**Comment by Kotasudhakarreddy** [comment] 2021-02-11 05:14
@larsschellhas - `az webapp up` will just create a webapp with default or specified configuration. here `default` means the default azure configuration. please find more details [here](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_up). 

To clarify your questions
1.  `az webapp up` will create  a new app all the times. It cannot be used for `deployment` in to the existing apps. So it does create a new webapp all the times.
2. if we don't specify the `--runtime`  argument then the `az webapp up` command will take the default runtime versions from `az webapp list-runtimes`

Hope it clarifies your question.

**Comment by larsschellhas** [comment] 2021-02-12 13:10
Hey @Kotasudhakarreddy , 
thank you very much for your answer! This does explain why the command acts as it does. However, wenn `az webapp up` is used to redeploy, it does seem to update the existing app. After all:
1. During the deployment it does say `Updating runtime from Python 3.8 to Python 3.7`
2. Previously set environment variables on the webapp are kept and not deleted.
3. In this [tutorial in the MS Docs](https://docs.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=bash%2Cclone#53-redeploy-the-code-to-azure) it literally says this:
    > This command uses the parameters cached in the .azure/config file. Because App Service detects that the app already exists, it just redeploys the code.

**Comment by Kotasudhakarreddy** [comment] 2021-02-15 14:24
> Hey @Kotasudhakarreddy ,
> thank you very much for your answer! This does explain why the command acts as it does. However, wenn `az webapp up` is used to redeploy, it does seem to update the existing app. After all:
> 
> 1. During the deployment it does say `Updating runtime from Python 3.8 to Python 3.7`
> 2. Previously set environment variables on the webapp are kept and not deleted.
> 3. In this [tutorial in the MS Docs](https://docs.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=bash%2Cclone#53-redeploy-the-code-to-azure) it literally says this:
>    > This command uses the parameters cached in the .azure/config file. Because App Service detects that the app already exists, it just redeploys the code.

Hi @larsschellhas - agreed on your points. Thanks for correcting me. Parameters cached under .azure/config will just store the info related to the azure configuration of your app like RG, SKU etc. Regarding `-runtime` as per the implementation if we don't specify the `-runtime` by default it  consider and set as `python|3.7`. 
 we will look in to the feasibility of considering the `runtime` version from previous deployment and set as default if we don't specify in the latest deployment.

**Comment by panchagnula** [comment] 2021-02-16 23:22
@calvinsID for an existing app we shouldn't override the run-time version if the language is the same right? Is this a regression with --runtime support?

**Comment by seligj95** [comment] 2023-03-13 19:30
Closing as it looks like the associated work has been done. Please re-open if this is still an issue.

**Closed by seligj95** 2023-03-13 19:30 UTC
Labels: Web Apps, Service Attention, app-service-webapp-up
