### ISSUE TITLE
login with tenant failed  

### ISSUE THREAD

**Issue by UteHaus** [Azure/azure-cli#22145] opened 2022-04-21 16:28 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to get authority configuration for https://login.microsoftonline.de/2b0623dd-90fa-4c5c-bee8-8dc18bd4d948. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 100, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 169, in tenant_discovery
ValueError: OIDC Discovery endpoint rejects our request. Error: {"error":"invalid_tenant","error_description":"AADSTS90002: Tenant '2b0623dd-90fa-4c5c-bee8-8dc18bd4d948' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\r\nTrace ID: c1806f4a-bcae-4ac1-b7ff-4eea2dcd1200\r\nCorrelation ID: 9d8aaacf-a655-4b1f-b113-3d0691054798\r\nTimestamp: 2022-04-21 16:26:49Z","error_codes":[90002],"timestamp":"2022-04-21 16:26:49Z","trace_id":"c1806f4a-bcae-4ac1-b7ff-4eea2dcd1200","correlation_id":"9d8aaacf-a655-4b1f-b113-3d0691054798","error_uri":"https://login.microsoftonline.de/error?code=90002"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 160, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 159, in login_with_service_principal
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line 123, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 455, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 104, in __init__
ValueError: Unable to get authority configuration for https://login.microsoftonline.de/2b0623dd-90fa-4c5c-bee8-8dc18bd4d948. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u {} -p {} --tenant {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.3
Installer: 

azure-cli 2.35.0
```

**Comment by jiasli** [comment] 2022-04-21 16:49
Duplicate of #20507

**Closed by jiasli** 2022-04-21 16:49 UTC
Labels: Account, customer-reported, Auto-Assign
