### ISSUE TITLE
Issue running installation script on Linux

### ISSUE THREAD

**Issue by KevinDMack** [Azure/azure-cli#19239] opened 2021-08-16 14:48 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When trying to install the CLI, I'm getting the following:
Get:1 file:/var/nccl-repo-2.2.13-ga-cuda9.2  InRelease
Ign:1 file:/var/nccl-repo-2.2.13-ga-cuda9.2  InRelease
Get:2 file:/var/nccl-repo-2.2.13-ga-cuda9.2  Release [574 B]                                                                                                                                            
Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                                           
Hit:4 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                                                   
Get:2 file:/var/nccl-repo-2.2.13-ga-cuda9.2  Release [574 B]                                                                                                                                                
Hit:5 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                                                                     
Hit:6 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                                             
Hit:7 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                                                                           
Get:8 https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64  InRelease [1484 B]                                                                                                             
Get:9 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64  InRelease [1481 B]                                                                                                      
Hit:10 https://packages.microsoft.com/repos/azure-cli bionic InRelease                                                                                                        
Hit:11 https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic InRelease                                                      
Hit:12 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease                                                                     
Hit:13 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease                                                                       
Ign:14 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease   
Hit:15 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease                                                                                        
Ign:16 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease                                                                                
Hit:17 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release                                                                                              
Hit:18 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release                                                            
Hit:19 http://ppa.launchpad.net/webupd8team/atom/ubuntu bionic InRelease                                                                                         
Hit:20 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease                                                                                                 
Hit:22 http://ppa.launchpad.net/x2go/stable/ubuntu bionic InRelease                                                                                                          
Err:23 https://dl.bintray.com/sbt/debian  InRelease                                                                         
  403  Forbidden [IP: 52.39.193.126 443]
Reading package lists... Done                      
E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 52.39.193.126 443]
E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**To Reproduce**
Running : curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

**Expected behavior**
Successful completion of the execution

**Environment summary**
Ubuntu 18.04

**Additional context**
Just started happening today, must be a new release

**Comment by yonzhan** [comment] 2021-08-16 15:29
@jiasli for awareness

**Comment by jiasli** [comment] 2021-08-17 02:55
Duplicate of #17666

Please see https://github.com/Azure/azure-cli/issues/17666#issuecomment-899953711 for the solution.

**Closed by jiasli** 2021-08-17 02:55 UTC
Labels: customer-reported, Installation
