### ISSUE TITLE
Are these documentation sections not redundant "Azure Devops" and "Azure DevOps"?

### ISSUE THREAD

**Issue by gro1m** [Azure/azure-cli#20218] opened 2021-11-05 08:38 UTC
Are these documentation sections not redundant "Azure Devops" and "Azure DevOps"?

The sections seem to be redundant apart from the fact that the Summary link does not seem to work for the "Azure Devops" section, whereas it does for the "Azure DevOps" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db571e2-29f1-aa5b-9879-82564633e5b7
* Version Independent ID: c6331f40-2660-1830-9a7c-0ed62463a994
* Content: [az devops](https://docs.microsoft.com/en-us/cli/azure/devops?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/devops.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/devops.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2021-11-05 13:44
route to service team

**Comment by RakeshMohanMSFT** [comment] 2022-03-29 13:55
Duplicate of https://github.com/Azure/azure-cli/issues/20292

**Closed by RakeshMohanMSFT** 2022-03-29 13:55 UTC
Labels: Service Attention, customer-reported, DevOps
