### ISSUE TITLE
Error decoding secrets

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli#9451] opened 2019-05-22 12:52 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When using the **az vm create** command I'm receiving "error decoding secrets" when using **--secrets** that points to the secret identifer that i've received from using **az keyvault secret list-versions --vault-name vaultname -n cert1 --query "[?attributes.enabled].id** command. When using the command it asks for the admin password twice and then says they don't match and then gives the "error decoding secrets".

**To Reproduce**
Using the **az vm create** with the **--secrets** parameter pointing to a secret identifier in a key vault.

**Expected behavior**
I would expect az cli to use the secret that I placed in the key vault as the administrator password for the virtual machine.

**Environment summary**
Windows 10 1709
AZ CLI (2.0.52) in VS CODE.

**Comment by yugangw-msft** [comment] 2019-05-22 17:59
@ChristianSmith2204, are you providing secrets in json format to the `--password` field?

**Comment by ChristianSmith2204** [comment] 2019-05-23 07:13
> @ChristianSmith2204, are you providing secrets in json format to the `--password` field?

No currently I'm only using the `--secrets` parameter instead of the `--admin-password` parameter since it was to my understanding that I could use the `--secrets` as a way to retrieve the password from the keyvault when pointing to the secret identifier but I might be using it the wrong way?

I'm not aware of a `--password` when using the `az vm create` only `--admin-password`.

**Comment by yonzhan** [comment] 2020-05-02 13:32
add to S170

**Comment by yungezz** [comment] 2020-08-03 14:27
hi @ghost I don't think `az vm create --secret` supports directly secret id from keyvault, but content, as example list below, doc https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create
```
Create a Debian VM using Key Vault secrets.

Azure CLI

Copy

Try It
az keyvault certificate create --vault-name vaultname -n cert1 \
  -p "$(az keyvault certificate get-default-policy)"

secrets=$(az keyvault secret list-versions --vault-name vaultname \
  -n cert1 --query "[?attributes.enabled].id" -o tsv)

vm_secrets=$(az vm secret format -s "$secrets")

az vm create -g group-name -n vm-name --admin-username deploy  \
  --image debian --secrets "$vm_secrets"
```

**Comment by yungezz** [comment] 2020-08-03 14:27
close the issue as not a bug, but by design.

**Closed by yungezz** 2020-08-03 14:27 UTC
Labels: Compute, Compute-cli, customer-reported
