### ISSUE TITLE
Admin Consent is not working in Cloud Shell

### ISSUE THREAD

**Issue by logachev** [Azure/azure-cli#14230] opened 2020-07-06 07:43 UTC
## Describe the bug

**Command Name**
`az ad app permission admin-consent`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Use Cloud Shell to run az cli
- `az ad app permission admin-consent --id {}`

## Expected Behavior

It works as locally

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by logachev** [comment] 2020-07-06 07:49
Looks like MSI doesn't like this GUID: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/custom.py#L907

**Comment by yonzhan** [comment] 2020-07-06 08:22
Cloud Shell

**Comment by jiasli** [comment] 2020-07-06 09:41
It is a known issue that `resource='74658136-14ec-4630-ad9b-26e160ff0fc6'` or `https://main.iam.ad.ext.azure.com/` is not accepted by Cloud Shell's managed identity. You will need to manually run `az login` before using this command. 

For more information, you could check https://github.com/Azure/azure-cli/issues/9942#issuecomment-650669473.

**Comment by maertendMSFT** [comment] 2020-07-07 22:22
This should be fixed now.  I cannot repro, please close.

**Comment by jiasli** [comment] 2020-08-17 01:57
Hi $ az ad app permission admin-consent --id b9df9246-f8c2-4505-8556-814b7ecc95a9
The command failed with an unexpected error. Here is the traceback:

400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 776, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 907, in admin_consent
    send_raw_request(cmd.cli_ctx, 'post', url, resource='74658136-14ec-4630-ad9b-26e160ff0fc6')
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 775, in send_raw_request
    token_info, _, _ = profile.get_raw_token(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 643, in get_raw_token
    creds = self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 391, in _get_token_from_cloud_shell
    auth = MSIAuthenticationWrapper(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

**Comment by maertendMSFT** [comment] 2020-09-30 23:15
Can we close this as a dupe of https://github.com/Azure/azure-cli/issues/11749 ?

**Closed** 2020-10-01 09:07 UTC
Labels: Cloud Shell, Service Attention

**Comment by jiasli** [comment] 2024-07-19 06:41
Duplicate of #8912
