### ISSUE TITLE
Budgets: az resource create - deployment error message and cannot see budgets

### ISSUE THREAD

**Issue by awoSYS** [Azure/azure-cli#10028] opened 2019-07-24 09:05 UTC
**Describe the bug**
I'm trying to create budgets with `az resource create` and encounter two problems:
* command execution results in error message: `Deployment failed. Correlation ID: <id>. Request is missing a certificate`. According to the `--debug` output, the following things happen internally:
** GET request to Microsoft.Consumption provider --> succeeds (status 200)
** GET request to the resource group --> succeeds (status 200)
** PUT request to create budget --> succeeds (status 201, containing the budget data in the body)
** GET request to the new budget --> fails (status 401 and `Request is missing a certificate` error)
* In Azure Portal and via `az consumption budget list`, I do not see the new budget. But if I try to create the same budget again, I get a `There are changes made to Budget <name>...` error message. And I receive correct email notifications from such a budget, if I add an e-mail notification. Seems like I am creating zombies...

**To Reproduce**
`az resource create -g testgroup -n "testbudget2" --resource-type "Microsoft.Consumption/Budgets" --properties "{\"amount\" : 1000, \"category\" : \"Cost\", \"timeGrain\" : \"Monthly\", \"name\" : \"testbudget2\", \"timePeriod\" : {\"startDate\" : \"2019-07-01T00:00:00Z\", \"endDate\" : \"2019-12-31T00:00:00Z\"}}"`

**Expected behavior**
* budget creation succeeds without error message
* budget is visible in Azure portal and via `az consumption budget list`

**Environment summary**
```
azure-cli                         2.0.69

command-modules-nspkg               2.0.3
core                              2.0.69
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-cli-iot-ext                  0.7.1

Python (Linux) 3.6.5 (default, Jul 11 2019, 08:41:35) 
[GCC 7.4.0]

Ubuntu 18.04
```
**Additional context**
I think, there is something happening in the background. On Monday this week, the behavior of the `az resource create` command changed. Until then, things were like this:
* I saw the missing certificate error
* I saw the Budgets after creating them
* No e-mail notifications were thrown, when budget limits were exceeded

Another weird thing is that if I first create a budget this way, then delete the whole resource group with this budget inside, then create a new resource group with the same name as the old one and create the same budget inside again, I also get the `There are changes made to Budget <name>...` error. So obviously, the zombies don't get killed properly when destroying their resource group.

If it helps, I can also provide some debug output. Thanks for your help!

**Comment by zikalino** [comment] 2019-07-24 09:52
@awoSYS I will check this issue

**Comment by zikalino** [comment] 2019-07-24 13:44
I managed to reproduce this issue myself, and I have some more observations.

PUT /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/rg1/providers/Microsoft.Consumption/Budgets/testbudget2?api-version=2019-05-01

Returns with code 201.

Response headers contain following header:

'Location': 'https://consumption.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/rg1/providers/Microsoft.Consumption/Budgets/testbudget2?api-version=2019-05-01'

But also body is returned:

Response content:
msrest.http_logger : {"id":"subscriptions/172a3774-5a9d-4160-8dab-a4fe8d35c676/resourceGroups/rg1/providers/Microsoft.Consumption/budgets/testbudget2","name":"testbudget2","type":"Microsoft.Consumption/budgets","eTag":"\"1d54223db133924\"","properties":{"timePeriod":{"startDate":"2019-07-01T00:00:00Z","endDate":"2019-12-31T00:00:00Z"},"timeGrain":"Monthly","amount":1000.0,"currentSpend":null,"category":"Cost","notifications":{},"filter":{}}}

> The response may contain URI in Location header field in HTTP headers list, which can have reference to the newly created resource. Also, response payload also may include an entity containing a list of resource characteristics and location(s) from which the user or user agent can choose the one most appropriate. The entity format is specified by the media type given in the Content-Type header field.

This means we could just use response body, or submit another GET to retrieve content from specified location. In this case former happens.

Pls note, that new location has different host value **consumption.azure.com**.

**Comment by zikalino** [comment] 2019-07-24 13:47
I have tried:

`az resource show -g rg1 -n "testbudget2" --resource-type "Microsoft.Consumption/Budgets"`

and it works correctly.

**Comment by zikalino** [comment] 2019-07-24 14:04
@awoSYS i have one question. what is the reason that you don't use **az consumption budget create**? I guess it's because it doesn't provide some parameters that are available via REST API?

I think there are 2 problems here to be fixed:
(1) **az resource** shouldn't attempt to use Location header if body is available.
(2) We should upgrade **az consumption** to use latest API.

+
(3) check why budget created via rest api is not visible on the portal

**Comment by awoSYS** [comment] 2019-07-24 14:08
@zikalino Thanks for testing! Exact same behavior for me. 

concerning `az consumption budget create`: You're right, there is no possibility to define contact mails and contact groups (see [this issue](https://github.com/Azure/azure-cli/issues/8488)), which I need.

**Comment by zikalino** [comment] 2019-07-24 14:13
there's something weird going on, I have tried older api version;

```
# az resource create -g rg1 -n "testbudget2" --resource-type "Microsoft.Consumption/Budgets" --properties "{\"amount\" : 1000, \"category\" : \"Cost\", \"timeGrain\" : \"Monthly\", \"name\" : \"testbudget2\", \"timePeriod\" : {\"startDate\" : \"2019-07-01T00:00:00Z\", \"endDate\" : \"2019-12-31T00:00:00Z\"}}" --debug --api-version 2018-01-31
```

And I got following error:

**Subscription 172a3774-5a9d-4160-8dab-a4fe8d35c676 is not associated with EA offer type**

**Comment by awoSYS** [comment] 2019-07-24 14:15
This is also already a known bug: https://github.com/Azure/azure-cli/issues/9867

**Comment by zikalino** [comment] 2019-07-24 14:24
@awoSYS thanks for linking this. Seems like @axelwogawa created budget sing the same command and could at least see it in the portal. Perhaps that have changed as well.

**Comment by awoSYS** [comment] 2019-07-24 14:30
@zikalino Actually, @axelwogawa is another account of mine (sorry for confusing). What I described there was last week's observation. Because now the budgets became invisible, I decided to file a new issue for this.

**Comment by zikalino** [comment] 2019-07-24 14:34
@awoSYS now I see similarity in acc names :-)
anyway, are you able to create budget via portal? I can't really find it anywhere...

**Comment by awoSYS** [comment] 2019-07-24 14:40
> anyway, are you able to create budget via portal? I can't really find it anywhere...

Yes, I am (Resource group -> Cost management -> Budgets -> Add): Works fine!

**Comment by awoSYS** [comment] 2019-07-24 15:03
@zikalino Your suggestion from #9867 

> Btw, you could also try az rest command, i think it doesn't have the same problem.

I did 
```
az rest --method put --uri "https://management.azure.com/subscriptions/<ID>/resourcegroups/<group>/providers/Microsoft.Consumption/Budgets/testbudget4?api-version=2019-05-01" --body '{"location": "westeurope", "properties": {"category": "Cost", "timeGrain": "Monthly", "amount": 10, "timePeriod": {"startDate": "2019-07-01T00:00:00Z", "endDate": "2020-12-31T00:00:00Z"}, "notifications": {"testNotification100": {"operator": "GreaterThanOrEqualTo", "threshold": 100, "contactEmails": ["<mail>"], "enabled": true, "contactGroups": ["<action group path>"]}}}}'
``` 
and got the same result as by using `az resource create`: 
- invisible in portal
- `az consumption budget list` and `az consumption budget show` don't find it
- `az resource show` finds it

(Of course, there is no 401 error now, because I don't do any explicit GET)

**Comment by zikalino** [comment] 2019-07-25 04:31
@awoSYS I have to discuss this with service team.

In the Azure CLI:
(1) we can fix **az resource** ( @yugangw-msft  do you agree?)
(2) upgrade **az consumption** to use latest API

and we will have some consistency here at least.

But... it almost seems like we are dealing with two separate services here, and it also seems portal was not updated....

**Comment by IbraheemAlSaady** [comment] 2020-01-12 13:57
Any updates on this issue?

**Comment by zhoxing-ms** [comment] 2020-04-16 08:51
The information in this issue is relatively large. After sorting it out, there are mainly the following problems:

1. Solved problems
The budget created by `az resource create budgets` can be seen in `az consumption budget list/show`, `az resource show` and portal (need to refresh).

2. Know issue
`Subscription <subscription id> is not associated with EA offer type (Request ID: <request id>)` problem with command `az consumption budget create`. #9867
It can be resolved by upgrading the api version called by the `az consumption budget create` command

**Comment by zhoxing-ms** [comment] 2020-04-16 09:00
The issues need to be solved by Service team:
1. The error `Request is missing a certificate` on first budget creation:

The first time to create a budget with PUT request: 
> PUT /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourcegroups/zhoxing-test/providers/Microsoft.Consumption/Budgets/zhoxing-test?api-version=2019-10-01

Service returns the redirect URL 
> https://consumption.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourcegroups/zhoxing-test/providers/Microsoft.Consumption/Budgets/zhoxing-test?api-version=2019-10-01'

Request the URL of the asynchronous result
> GET https://consumption.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourcegroups/zhoxing-test/providers/Microsoft.Consumption/Budgets/zhoxing-test?api-version=2019-10-01

The Service return `{"error":{"code":"401","message":"Request is missing a certificate"}}`

When the PUT request is called for the second time, the status of 200 and the data of corresponding budget are returned without error.

2. If adding the budget for a resource group, deleting the resource group will not cascade to delete the budget. If the resource group with the same name is recreated later, the budget bound to the deleted old resource group will still be bound to the new resource group.
Is this in line with expectations?

3. After adding the budget through CLI, if creating a budget with the same name on the potal without first refreshing the budget list on the list page. The duplicate check will ignore the budget just created by CLI and create a new budget with the same name to overwrite the one created by cli. (I found it by accident)

**Comment by ramaganesan-rg** [comment] 2020-06-29 17:10
Team is investigating.

**Comment by theelderwand** [comment] 2020-12-10 00:08
Hi @zhoxing-ms , please find the responses to your questions
1) The issue where the Location Header was returning you a 401 has been fixed. We will be rolling this out in the coming weeks after holidays.
2) Budgets are sticky to the resource groups, so recreating the resource group will bring back the budget. Also, budgets do not get deleted automatically on resource group deletion. This is expected.
3) The behavior in the portal is expected because last write wins.

**Comment by zhoxing-ms** [comment] 2020-12-10 03:24
@theelderwand Thank you for your reply. Please let we know when you rolling this fix out and we will test it again~

**Comment by JaikishanRupani** [comment] 2021-01-15 01:37
@zhoxing-ms Fix for the location header issue has been deployed now. You can test it again.

**Comment by zhoxing-ms** [comment] 2021-01-15 03:46
@JaikishanRupani Thank you for your notice. I have verified it and this issue has been solved

**Closed by zhoxing-ms** 2021-01-15 03:46 UTC
Labels: Consumption, Service Attention, customer-reported, feature-request, rest
