### ISSUE TITLE
az disk update doesn't increase os disk filesystem size

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#3380] opened 2017-05-17 08:34 UTC
### Description
**Outline the issue here:**
According to https://docs.microsoft.com/pdfstore/en-us/Azure.azure-documents/live/virtual-machines/linux.pdf it's possible to expand os disk.
Documentation also shows expanding data disk automatically increase filesystem size.
However it doesn't clarify if it's possible to automatically increase filesystem size for os disk after its expansion.
I expanded os disk using 
az vm deallocate ...
az disk update ...
az vm start ...
but filesystem size for os disk was not increased automatically after os disk expansion
My questions:
- is it by design? if not it has to be fixed. if so it has to be clearly documented.
in the latter case what is the way to increase os disk filesystem size after os disk expansion either automatically or manually?
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
According to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
2.0.6
**OS Version:** What OS and version are you using?  
Answer here:
Windows 10 Pro 64-bit
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
cmd.exe and Bash on Windows

**Comment by tjprescott** [comment] 2017-05-17 21:26
I would expect this would increase the size of the "physical" hard disk, but not the size of the disk partition within the OS.  For that, you would likely need to interact directly with the OS.  I'll confirm though.

**Comment by alexeyshishkin01** [comment] 2017-05-17 21:36
let's see what documentation says:
'If you've resized the operating system disk, the partition is automatically be expanded. If you have resized a data disk, any current partitions need to be expanded in the VMs operating system'
'To verify the OS disk has been resized, use df -h'.
It doesn't work unfortunately for operating system disk.
Disk size is increased, but neither partition nor filesystem size is not.

**Comment by tjprescott** [comment] 2017-05-17 21:50
@yugangw-msft can you confirm the expected behavior with the managed disk folks?  It looks like the documentation is wrong here.

**Comment by alexeyshishkin01** [comment] 2017-05-17 22:48
is it possible to automate OS disk file system size increase based on
https://blogs.msdn.microsoft.com/cloud_solution_architect/2016/05/24/step-by-step-how-to-resize-a-linux-vm-os-disk-in-azure-arm/
in order not to fix documentation?
described solution works fine for me, but it has to be done manually

**Comment by tjprescott** [comment] 2017-05-17 23:41
Right, but the fact that you have to manually go in an adjust the partition size seems to imply that the documentation is wrong about it being automatic.

The technical requirements are such that we can't make the CLI command automate these tasks:
1) the CLI doesn't have a way to connect to the VM
2) the process would be different for each OS image

**Comment by yugangw-msft** [comment] 2017-05-17 23:47
@tjprescott, agreed. Let us close this issue

**Comment by tjprescott** [comment] 2017-05-17 23:51
Yes, but we should report this somewhere so the docs can be fixed.

**Comment by alexeyshishkin01** [comment] 2017-05-18 06:53
ok, pls. fix documentation then. cheers

**Comment by mayurid** [comment] 2017-05-18 22:22
@alexeyshishkin01 : can you point to the exact link to the docs you would like to change? I can work with the right folks.

**Comment by alexeyshishkin01** [comment] 2017-05-19 07:09
sure, for example the link
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-manage-disks#resize-vm-disk
says:
'If you’ve resized the operating system disk, the partition is automatically be expanded. If you have resized a data disk, any current partitions need to be expanded in the VMs operating system.'

another link
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/expand-disks#expand-disk
says:
'SSH to your VM with the appropriate credentials. To verify the OS disk has been resized, use df -h. The following example output shows the data drive (/dev/sdc1) is now 200 GB' - which means both partition and filesystem are expanded automatically

could you pls also look at the corresponding items in pdf-file
https://docs.microsoft.com/pdfstore/en-us/Azure.azure-documents/live/virtual-machines/linux.pdf

thanks!

**Comment by yugangw-msft** [comment] 2018-11-07 21:40
This is a tutorial doc that is not actionable for CLI @sptramer

**Closed by yugangw-msft** 2018-11-07 21:40 UTC
Labels: Compute-cli, Question

**Comment by yugangw-msft** [comment] 2018-11-07 21:42
@alexeyshishkin01, please open an issue at https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/linux/tutorial-manage-disks.md

**Comment by alexeyshishkin01** [comment] 2018-11-08 07:00
ok, I've opened an issue https://github.com/MicrosoftDocs/azure-docs/issues/18436
