### ISSUE TITLE
azure-cli still depends on old API for managedapps from azure-mgmt-resource

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-cli#25828] opened 2023-03-15 13:33 UTC
The `azure-cli` package is incompatible with the current stable version of `azure-mgmt-resource` [1].

> [1] https://pypi.org/project/azure-mgmt-resource/

When `azure-mgmt-resource` 22.0.0 is installed, running `az managedapp --help` results in the following backtrace:

```
glaubitz@suse-laptop:~> az managedapp --help
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.resource.managedapplications.operations'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/lib/python3.10/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/usr/lib64/python3.10/argparse.py", line 1826, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.10/argparse.py", line 2054, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.10/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.10/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.10/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.10/argparse.py", line 1099, in __call__
    parser.print_help()
  File "/usr/lib64/python3.10/argparse.py", line 2560, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/parser.py", line 192, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/usr/lib/python3.10/site-packages/knack/parser.py", line 248, in format_help
    self.cli_help.show_help(self.prog.split()[0],
  File "/usr/lib/python3.10/site-packages/azure/cli/core/_help.py", line 165, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/usr/lib/python3.10/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/_help.py", line 296, in load
    loader.versioned_load(self, options)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/usr/lib/python3.10/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/usr/lib/python3.10/site-packages/knack/parser.py", line 241, in __getattribute__
    self.description = self._description() \
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.resource.managedapplications.operations'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
glaubitz@suse-laptop:~>
```

**Comment by yonzhan** [comment] 2023-03-15 14:46
route to CXP team

**Comment by zhoxing-ms** [comment] 2023-03-16 01:58
Yes, this is a known issue, this is the root cause https://github.com/Azure/azure-cli/pull/24211#issuecomment-1407598840 of this issue

**Comment by zhoxing-ms** [comment] 2023-03-16 02:05
At present, we have a PR that is solving this issue: https://github.com/Azure/azure-cli/pull/25434

**Comment by navba-MSFT** [comment] 2023-03-16 02:59
@glaubitz Thanks for reaching out to us and reporting this issue. As mentioned in the above comment, Azure/azure-cli#25434 PR has been filed and it is currently under review.

**Comment by navba-MSFT** [comment] 2023-03-21 04:29
@glaubitz The above PR is now merged. The fix should be available as a part of this milestone https://github.com/Azure/azure-cli/milestone/128

**Closed by navba-MSFT** 2023-03-21 04:29 UTC
Labels: bug, ARM - Managed Applications, customer-reported, CXP Attention
