### ISSUE TITLE
Support Azure Arc managed identity with az login --identity

### ISSUE THREAD

**Issue by rpsqrd** [Azure/azure-cli#21394] opened 2022-02-22 21:09 UTC
**Is your feature request related to a problem? Please describe.**
No, this is not related to a problem.

**Describe the solution you'd like**
Azure Arc provides the ability for on-premises and multicloud servers to get an AAD system assigned managed identity. It would be great if the `az login --identity` command were updated to also try to obtain a token from the [Azure Arc IMDS](https://docs.microsoft.com/azure/azure-arc/servers/managed-identity-authentication). The Az.Accounts PowerShell module already supports this functionality, so it will help bridge parity between the two.

The recommended flow for agents to deal with the two different managed identity implementations is to first try the Azure IMDS endpoint (169.254.169.254:80), and if there's no response, then try the Arc managed identity endpoint (127.0.0.1:40342).

**Describe alternatives you've considered**
N/A - there is no other way to use the Arc managed identity with Az CLI because CLI doesn't take an AAD token as an authentication mechanism.

**Additional context**
N/A

**Comment by yonzhan** [comment] 2022-02-22 23:16
@jiasli for awareness

**Comment by parameshbabu** [comment] 2022-05-16 18:03
Piling on this request as we need this also for our scenarios

**Comment by jiasli** [comment] 2022-05-17 03:19
Duplicate of #16573

**Closed by jiasli** 2022-05-17 03:19 UTC
Labels: Account, feature-request, Auto-Assign
