### ISSUE TITLE
az login --identity stopped working: Failed to connect to MSI

### ISSUE THREAD

**Issue by sakitA** [Azure/azure-cli#28604] opened 2024-03-21 15:06 UTC
### Describe the bug

I follow this page to create azure cloud instance and test system managed identity. https://learn.microsoft.com/en-us/azure/container-instances/container-instances-managed-identity#example-2-use-a-system-assigned-identity-to-access-azure-key-vault

My container created successfully. I connect the container instance and try to execute following command inside the container

```
az login --identity
```

And got following error

```
PS C:\work> az login --identity
Failed to connect to MSI. Please make sure MSI is configured correctly and check the network connection.
Error detail: HTTPConnectionPool(host='XXX.XXX.XXX.XXX', port=80): Max retries exceeded with url: /metadata/identity/oau
th2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<u
rllib3.connection.HTTPConnection object at 0x0000024C2C46D2E0>: Failed to establish a new connection: [WinError 10060] A
 connection attempt failed because the connected party did not properly respond after a period of time, or established c
onnection failed because connected host has failed to respond'))
```

### Related command

az login --identity

### Errors

Failed to connect to MSI. Please make sure MSI is configured correctly and check the network connection.
Error detail: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oau
th2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01&client_id=348f0b58-24de-4880-97a4
-c9ebacc39cd9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A26CBFB2B0>: Failed to
 establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly r
espond after a period of time, or established connection failed because connected host has failed to respond'))

### Issue script & Debug output

PS C:\work> az login --identity
Failed to connect to MSI. Please make sure MSI is configured correctly and check the network connection.
Error detail: HTTPConnectionPool(host='XXX.XXX.XXX.XXX', port=80): Max retries exceeded with url: /metadata/identity/oau
th2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<u
rllib3.connection.HTTPConnection object at 0x0000024C2C46D2E0>: Failed to establish a new connection: [WinError 10060] A
 connection attempt failed because the connected party did not properly respond after a period of time, or established c
onnection failed because connected host has failed to respond'))

### Expected behavior

it should authenticate in azure container instance

### Environment Summary

PS C:\work> az --version
azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\tools\python3\python.exe'
Extensions directory 'C:\Users\ContainerAdministrator\.azure\cliextensions'

Python (Windows) 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment] 2024-03-21 15:06
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-03-22 09:57
The error indicates Azure CLI is not able to connect to managed identity endpoint on the Azure Container Instances. 

You may create a support ticket for Azure Container Instances to investigate it further.

Duplicate of #14961

**Closed by jiasli** 2024-03-22 09:57 UTC
Labels: Account, question, Auto-Assign, Azure CLI Team
