### ISSUE TITLE
Add management/activation of Privileged Identity Management controlled roles

### ISSUE THREAD

**Issue by mjclarke94** [Azure/azure-cli#20013] opened 2021-10-24 12:06 UTC
**Is your feature request related to a problem? Please describe.**
Having to go via the portal to activate role assignments via PIM is inconvenient. Adding in PIM functionality to the CLI interface would be very useful.

**Describe the solution you'd like**
An expansion of the `az ad` command to include PIM management, as is available via the [Powershell interface](https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/powershell-for-azure-ad-roles).

**Describe alternatives you've considered**
I've tried doing this via powershell, but working on an M1 Mac this is shaky at best, and also not an interface I am familiar with. Ideally I wouldn't need to jump between terminal based interfaces depending on what set of features I need.

**Comment by jiasli** [comment] 2022-06-22 01:55
Duplicate of #13064

As stated in https://github.com/Azure/azure-cli/issues/22580#issuecomment-1150686865,

> Azure CLI's `az ad` command group is only designed to facilitate interacting with Azure resources. It is NOT designed to be a fully-fledged client for managing Microsoft Graph. Therefore, only a limited subset of [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/overview) is supported natively by Azure CLI.

**The equivalent of Azure CLI is `Az` PowerShell module from [Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure).** `AzureAD` and `AzureADPreview` modules are from [Azure Active Directory PowerShell](https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2) maintained by AAD team.

Also, as stated in https://github.com/Azure/azure-cli/issues/12946#issuecomment-737196942,

AAD team is currently developing their own CLI tool [Microsoft Graph CLI](https://github.com/microsoftgraph/msgraph-cli) which is designed to be an equivalent of `AzureAD` and `AzureADPreview` modules. You may try it instead.

**Closed by jiasli** 2022-06-22 01:55 UTC
Labels: Graph, customer-reported, feature-request, Feature Candidate
