### ISSUE TITLE
az login --identity

### ISSUE THREAD

**Issue by netz007** [Azure/azure-cli#27069] opened 2023-08-02 14:13 UTC
### Describe the bug

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jwt/algorithms.py", line 257, in prepare_key
    key = load_pem_private_key(key, password=None)
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 18, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1248, in load_pem_private_key
    password,
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1475, in _load_key
    self._handle_key_loading_error()
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1518, in _handle_key_loading_error
    "Could not deserialize key data. The data may be in an "
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 140, in login
    return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 367, in find_subscriptions_in_vm_with_msi
    decode = jwt.decode(token, verify=False, algorithms=['RS256'])
  File "/usr/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/lib/python3.6/site-packages/jwt/api_jws.py", line 182, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/usr/lib/python3.6/site-packages/jwt/api_jws.py", line 266, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/usr/lib/python3.6/site-packages/jwt/algorithms.py", line 259, in prepare_key
    key = load_pem_public_key(key)
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 23, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1274, in load_pem_public_key
    self._handle_key_loading_error()
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1518, in _handle_key_loading_error
    "Could not deserialize key data. The data may be in an "
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

### Related command

az login --identity

### Errors

az login --identity

### Issue script & Debug output

[0] create a generic issue.
   [1] az storage blob list: FAILURE. Ran: 1 hrs 34 mins ago.
   [2] az storage blob list: FAILURE. Ran: 1 hrs 33 mins ago.
   [3] az storage blob list: FAILURE. Ran: 1 hrs 33 mins ago.
   [4] az storage blob list: FAILURE. Ran: 1 hrs 32 mins ago.
   [5] az storage blob list: FAILURE. Ran: 1 hrs 32 mins ago.
   [6] az login            : FAILURE. Ran: 1 hrs 32 mins ago.
   [7] az login            : FAILURE. Ran: 1 hrs 32 mins ago.
   [8] az login            : FAILURE. Ran: 22 mins ago.      
   [9] az login            : FAILURE. Ran: 14 secs ago.  

### Expected behavior

az login --identity

### Environment Summary

azure-cli                         2.17.1 *

core                              2.17.1 *
telemetry                          1.0.6

Python location '/usr/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment] 2023-08-02 14:13
Thank you for opening this issue, we will look into it.

**Comment by netz007** [comment] 2023-08-06 18:37
Given no hashes to check 0 links for project 'azure-mgmt-keyvault': discarding no candidates
ERROR: Could not find a version that satisfies the requirement azure-mgmt-keyvault==10.1.0 (from azure-cli) (from versions: 0.30.0rc5, 0.30.0rc6, 0.30.0, 0.30.1, 0.31.0, 0.40.0, 1.0.0b1, 1.0.0, 1.1.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 7.0.0b1, 7.0.0b2, 7.0.0b3, 7.0.0, 8.0.0, 9.0.0, 9.1.0, 9.2.0, 9.3.0, 10.0.0)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-hpk430pv'
ERROR: No matching distribution found for azure-mgmt-keyvault==10.1.0 (from azure-cli)

**Comment by jiasli** [comment] 2023-08-07 02:52
Could be a duplicate of https://github.com/Azure/azure-cli/issues/19999

`/usr/lib/python3.6/site-packages` is not the installation location of official Azure CLI packages.

- Where are you running Azure CLI?
- How is Azure CLI installed?
- Does installing the latest version solve this issue? https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf

**Comment by jiasli** [comment] 2023-08-07 02:54
> Given no hashes to check 0 links for project 'azure-mgmt-keyvault': discarding no candidates ERROR: Could not find a version that satisfies the requirement azure-mgmt-keyvault==10.1.0 (from azure-cli) (from versions: 0.30.0rc5, 0.30.0rc6, 0.30.0, 0.30.1, 0.31.0, 0.40.0, 1.0.0b1, 1.0.0, 1.1.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 7.0.0b1, 7.0.0b2, 7.0.0b3, 7.0.0, 8.0.0, 9.0.0, 9.1.0, 9.2.0, 9.3.0, 10.0.0) Cleaning up... Removed build tracker: '/tmp/pip-req-tracker-hpk430pv' ERROR: No matching distribution found for azure-mgmt-keyvault==10.1.0 (from azure-cli)

`azure-mgmt-keyvault==10.1.0` does exist on PyPI: https://pypi.org/project/azure-mgmt-keyvault/10.1.0/

Are you using your own `pip` index which doesn't have `azure-mgmt-keyvault==10.1.0`?

**Comment by Mojzauke** [comment] 2023-08-08 07:07
Hi, 
We fixed it yesterday. I updated pip and reinstall the azure-cli package in different location (/usr/lib/python3.6 instead of /usr/lib64/python3.6) and now everything works fine. Thank You all for help!

**Closed** 2023-08-08 08:24 UTC
Labels: Account, Storage, question, customer-reported, Auto-Assign, Azure CLI Team, Auto-Resolve
