### ISSUE TITLE
unable to connect to serverless postgres db

### ISSUE THREAD

**Issue by ryancolekt** [Azure/azure-cli#21953] opened 2022-04-06 09:18 UTC
## Describe the bug
Unable to connect to postgres flexible-server from local installation of cli.  

**Command Name**
`az postgres flexible-server connect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'psycopg2._psycopg'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.8/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ryco/.azure/cliextensions/rdbms-connect/azext_rdbms_connect/custom.py", line 10, in <module>
    import psycopg2
  File "/home/ryco/.azure/cliextensions/rdbms-connect/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres flexible-server connect -n {} -u {} --interactive`

## Expected Behavior
Should (and used to) provide an interactive shell from the postgres db

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
rdbms-connect 1.0.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-04-06 09:47
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-04-07 04:02
@ryancolekt Thank you for reaching out to us. We are looking into it.

**Comment by RakeshMohanMSFT** [comment] 2022-04-22 06:04
@ryancolekt this is a bug and will are looking into this. The fix will be released tentatively by end of next month. In the meantime, if you have any questions, please feel free to ask. I would be happy to answer it.

**Comment by RakeshMohanMSFT** [comment] 2022-05-04 11:00
@ryancolekt can you please try with the latest CLI and extension version (1.0.2)?
And make sure the rdbms-connect folder is removed in the ~/.azure/cliextensions/ and re-installing it.

**Comment by RakeshMohanMSFT** [comment] 2022-05-06 12:25
@ryancolekt Hope you got a chance to try the action plan provided above.

**Closed** 2022-05-28 08:00 UTC
Labels: PostgreSQL, customer-reported, needs-author-feedback, no-recent-activity, CXP Attention, Auto-Assign

**Comment by mannyovena** [comment] 2024-09-11 16:06
I ran into a similar issue on Alpine. I confirmed that `psycopg` was not installing because I was missing `gcc`. I ran the following command to resolve the issue:

`apk add gcc musl-dev`
