### ISSUE TITLE
Azure DevOps Build Agent not able to access Azure Storage Account during deployment

### ISSUE THREAD

**Issue by micheleissa** [Azure/azure-cli#11017] opened 2019-10-29 18:42 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I have a static website that I wish to have CD pipeline for it, the pipeline has one task which is Azure CLI to copy files to storage account, I'm using a service connection that has a service principal that has access to the resource. I keep getting the following error 
You do not have the required permissions needed to perform this operation.
 Depending on your operation, you may need to be assigned one of the following roles:
"Storage Blob Data Contributor"
"Storage Blob Data Reader"
"Storage Queue Data Contributor"
"Storage Queue Data Reader"
In the script I'm adding the IP of the build agent to the list of allowed IP on the firewall for the storage account so it would have access then I can issue azure cli commands to list or upload content.  This behavior used to work up to yesterday and out of sudden it stopped working, I tried to reproduce on Azure Shell itself and it is working fine and also I tried locally on my work machine and the same steps work fine.
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A successful upload to Azure Storage account container.

**Environment summary**
Azure CLI Version: 2.0.74
Azure CLI Task version: 1.0

**Additional context**

**Comment by micheleissa** [comment] 2019-10-29 18:42
[4_Azure CLI  copy files to storage account.log](https://github.com/Azure/azure-cli/files/3785232/4_Azure.CLI.copy.files.to.storage.account.log)

**Comment by Juliehzl** [comment] 2019-10-30 01:13
Thanks for your feedback. I will have a look at it and try to fix it in next sprint. So you only have problems in Azure DevOps and it's fine for local machine and Azure Cloud Shell, right?

**Comment by micheleissa** [comment] 2019-10-30 01:17
@Juliehzl that is correct, it works fine on both local machine and Azure Cloud Shell.

**Comment by micheleissa** [comment] 2019-11-04 14:34
@Juliehzl any news on this?
I've also added the service principal as a Contributor on the subscription but still the same error happens.

**Comment by Juliehzl** [comment] 2019-11-18 05:48
Hi @micheleissa , through your log information, I found that you have set network rules for your storage account as follows:
13.107.6.0/24
```
2019-10-29T18:36:44.3801455Z   "networkRuleSet": {
2019-10-29T18:36:44.3801570Z     "bypass": "AzureServices",
2019-10-29T18:36:44.3801639Z     "defaultAction": "Deny",
2019-10-29T18:36:44.3801753Z     "ipRules": [
2019-10-29T18:36:44.3801860Z       {
2019-10-29T18:36:44.3801926Z         "action": "Allow",
2019-10-29T18:36:44.3802044Z         "ipAddressOrRange": "47.187.19.110"
2019-10-29T18:36:44.3802145Z       },
2019-10-29T18:36:44.3802254Z       {
2019-10-29T18:36:44.3802317Z         "action": "Allow",
2019-10-29T18:36:44.3802616Z         "ipAddressOrRange": "76.228.200.171"
2019-10-29T18:36:44.3802734Z       },
2019-10-29T18:36:44.3802798Z       {
2019-10-29T18:36:44.3802890Z         "action": "Allow",
2019-10-29T18:36:44.3803071Z         "ipAddressOrRange": "139.180.25.115"
2019-10-29T18:36:44.3803159Z       },
2019-10-29T18:36:44.3803218Z       {
2019-10-29T18:36:44.3803444Z         "action": "Allow",
2019-10-29T18:36:44.3803514Z         "ipAddressOrRange": "104.41.132.253"
2019-10-29T18:36:44.3803622Z       },
2019-10-29T18:36:44.3803679Z       {
2019-10-29T18:36:44.3803896Z         "action": "Allow",
2019-10-29T18:36:44.3803966Z         "ipAddressOrRange": "63.96.91.120"
2019-10-29T18:36:44.3804082Z       },
2019-10-29T18:36:44.3804141Z       {
2019-10-29T18:36:44.3804883Z         "action": "Allow",
2019-10-29T18:36:44.3804972Z         "ipAddressOrRange": "13.66.0.100"
2019-10-29T18:36:44.3805091Z       },
2019-10-29T18:36:44.3805199Z       {
2019-10-29T18:36:44.3805260Z         "action": "Allow",
2019-10-29T18:36:44.3805391Z         "ipAddressOrRange": "40.71.169.68"
2019-10-29T18:36:44.3805470Z       }
```
When you access blob in ADO, your ip may be not in the rule set. Can you confirm if you have allowed ADO ip is allowed for your storage account?

**Comment by micheleissa** [comment] 2019-11-19 01:55
As I stated above, I manually add the IP of the build agent on the fly during the deployment and list all the allowed IPs and the agent is one of them.

**Comment by Juliehzl** [comment] 2019-11-19 02:34
According to your error code, it should be caused by  Firewall. You can check it by setting default action of your storage account to Allow, and it should works well. But why not set default action to  Allow? Do you have any concern?
If you want to config network rules, what you need to do is to config IP address correctly. Could you please confirm ip address is right and satisfy the [rules](https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security#grant-access-from-an-internet-ip-range)? By the way, how do you find build agent ip in ADO?

**Comment by micheleissa** [comment] 2019-11-19 02:53
The IP address is the public IP given to the build agent machine and I obtain it from an api call to [this](https://ipinfo.io/ip)
so it is right and satisfy the rules. The weird part is before the problem started to happen, the original approach of adding IP rule to firewall was working fine. I managed to get it to work by using default action allow then deny again after uploading the static content of the website. 
To find the ip in ADO is like that:
```
# obtain build agent IP to be used later
Build_Agent_IP=$(curl -k https://ipinfo.io/ip)
echo 'Build Agent IP is: ' $Build_Agent_IP
```

**Comment by Juliehzl** [comment] 2019-11-26 14:26
@micheleissa Thanks for you information. At least we know it is caused by network rules, not CLI issue. In ADO, typically build agent is assigned randomly. But I think what you need to do is to find the correct IP address for you build agent and add it to allow for you storage account. You can find ADO guys for help. 
I will close it now because it is not a CLI issue and if you still have problems when using CLI, feel free to create a new one.😊

**Closed by Juliehzl** 2019-11-26 14:26 UTC
Labels: Storage

**Comment by micheleissa** [comment] 2019-11-29 22:28
How is that not a ADO CLI issue?? And I did find the correct IP Address

**Comment by nidhyn** [comment] 2020-05-20 15:19
@micheleissa were you able to solve the issue ? I am facing the same issue.

**Comment by c-mccutcheon** [comment] 2020-05-26 20:35
@nidhyn also experiencing the same issue - the only thing that allows it to work is setting 'allow public networks' which is the same as setting default rule of allow all - not something we wish to allow.

**Comment by cjmcewan** [comment] 2020-06-01 09:53
I am also having the same issue, it's intermittent and seems to be an issue with adding the agent ip. @c-mccutcheon @nidhyn by any chance did either of you manage to get round this issue?

**Comment by nidhyn** [comment] 2020-06-04 15:40
@c-mccutcheon  @cjmcewan no luck so far.

**Comment by nidhyn** [comment] 2020-07-13 10:54
@c-mccutcheon @cjmcewan  If you are still like to hear what the issue is, What I got from Microsoft is that the system is whitelisting the private IP of the Azure Vm instead of the public IP. And it is not always that case, 2/10 attempts gets successful. But that's a shame. We resolved the issue with a custom agent in the same vnet.

**Comment by SebastianBalle** [comment] 2020-11-25 20:12
> The IP address is the public IP given to the build agent machine and I obtain it from an api call to [this](https://ipinfo.io/ip)
> so it is right and satisfy the rules. The weird part is before the problem started to happen, the original approach of adding IP rule to firewall was working fine. I managed to get it to work by using default action allow then deny again after uploading the static content of the website.
> To find the ip in ADO is like that:
> 
> ```
> # obtain build agent IP to be used later
> Build_Agent_IP=$(curl -k https://ipinfo.io/ip)
> echo 'Build Agent IP is: ' $Build_Agent_IP
> ```

I am doing similar commands in my Azure Pipeline, however there seem to be a delay from whitelisting the IP of the Microsoft hosted agent to it being allowed to write/read from the Storage account. I have, for a temporary solution, added a sleep command in there for 4-5 minutes but is seems to be random if the network rules has been applied. Does anyone know if it is possible to return an exit code 2 instead of the standard 'the request may be blocked by network rules of storage account', which is only a warning meaning it will not fail in the Azure Pipeline. 

For now I have tried the following:
`
az storage account show -n [storage-account-name] --query networkRuleSet --resource-group [resource-group-name] > network_rules.json 
IP_MATCH=$(cat network_rules.json | jq --arg CURRENT_IP "$CURRENT_IP" '.ipRules[] | select(.ipAddressOrRange | contains($CURRENT_IP))')
if [ -z "$IP_MATCH" ]
then 
  echo "IP $CURRENT_IP was not whitelisted. Try again."
  exit 2
else
  # Upload file or something
```

**Comment by ClaraGaya** [comment] 2021-11-02 09:51
Facing the same issue, added the agent's ip on the fly, added a sleep time (even increased it to 300!) but still having the same AuthorizationFailure error

**Comment by ClaraGaya** [comment] 2021-11-02 09:55
Facing the same issue, added the agent's IP on the fly, added a sleep time (even increased it to 300!) but still having the same AuthorizationFailure error intermittently. Anyone found another solution?

# Get local IP for firewall rule
agentIp=$(curl ifconfig.me)

```
# Create firewall rule for Storage with Network rule (https://github.com/terraform-providers/terraform-provider-azurerm/issues/2977)
az storage account network-rule add --resource-group $(resourceGroupName) --account-name $(ingestStorageAccountName) --ip-address $agentIp

# Give chance for Azure to apply firewall rule
sleep 300
```

**Comment by ClaraGaya** [comment] 2021-11-02 11:46
Found out the following: 
**IP network rules have no effect on requests originating from the same Azure region as the storage account**

When the hosted agent spins up it gets assigned an IP randomly. If this is in the same region as your storage account, work around does not work. This explains why the issue is intermittent.

A workaround would be enabling public access and then remove it.

**Comment by Matthew0x** [comment] 2023-03-03 16:18
I am doing something similar and it's still broken.
Half of the time it works, half of the time it doesn't (even with the sleep() function).

In my case the script literally obtains the IP of the agent, the IP gets added through the CLI.
Set to public - no problems, set with firewall exception? Nope

Also
"According to your error code, it should be caused by Firewall. You can check it by setting default action of your storage account to Allow, and it should works well. But why not set default action to Allow? Do you have any concern?"

Sorry, but is this advice for real?
Do you ask somebody what is wrong with public access to their Storage Account? Why would they even try allowing an IP if they wished for their default rule to be on "allow"?

The default rule is deny, every explicitly stated IP is allowed only. That's the idea, to allow only selected ranges, be it subnets or public IPs.

PS: Is this really not possible to include DevOps agents as Microsoft Service bypass in the Resource settings? It's been 4 years, it's only quite rational to categorize Microsoft Agents as Microsoft Services, is it not?

**Comment by Matthew0x** [comment] 2023-03-03 17:03
I am doing something similar and it's still quite problematic, especially with Terraform, that works a bit differently than the CLI. There are API delays and e.g. the firewall rules can take up to 2 minutes to even appear in the target resource...

Set to public - no problems, set with firewall exceptions? Some magical stuff happens from time to time.

Also, "According to your error code, it should be caused by Firewall. You can check it by setting default action of your storage account to Allow, and it should works well. But why not set default action to Allow? Do you have any concern?"

Why would they even try allowing an IP if they wished for their default rule to be on "allow"?

Is this really not possible to include DevOps agents as Microsoft Service bypass in the Resource settings?  Tt's only quite rational to categorize Microsoft Agents as Microsoft Services, is it not?  The workaround is not very complicated, but I can see some use-cases, where this potentially becomes an obstacle.

PS: Your documentation on assigning the agent's IP states that the public IPs belong under the (the ServiceTags file), AzureCloud, which can contain even 300 different IPs.

I can't see why exactly it's not supported to even retrieve the IP of the agent through some kind of a pre-defined variable? There seems to be no other way than to write custom scripts for this purpose, and they are a workaround using the API, which brings additional delay to the pipeline and even makes them waste time needlessly.

**Comment by Ognengineer** [comment] 2023-10-31 16:10
> I am doing something similar and it's still quite problematic, especially with Terraform, that works a bit differently than the CLI. There are API delays and e.g. the firewall rules can take up to 2 minutes to even appear in the target resource...
> 
> Set to public - no problems, set with firewall exceptions? Some magical stuff happens from time to time. It's unreliable. The same routine can work 4 times in a row, to throw API error on the next attempt.
> 
> Also, "According to your error code, it should be caused by Firewall. You can check it by setting default action of your storage account to Allow, and it should works well. But why not set default action to Allow? Do you have any concern?"
> 
> Why would they even try allowing an IP if they wished for their default rule to be on "allow"?
> 
> Is this really not possible to include DevOps agents as Microsoft Service bypass in the Resource settings? It's only quite rational to categorize Microsoft Agents as Microsoft Services, is it not? The workaround is not very complicated, but I can see some use-cases, where this potentially becomes an obstacle.
> 
> PS: Your documentation on assigning the agent's IP states that the public IPs belong under the (the ServiceTags file), AzureCloud, which can contain even 300 different IPs. Assigning those IPs manually is not a solution at all.
> 
> I can't see why exactly it's not supported to even retrieve the IP of the agent through some kind of a pre-defined variable? There seems to be no other way than to write custom scripts for this purpose, and they are a workaround using the API, which brings additional delay to the pipeline and even makes them waste time needlessly.
> 
> PS2: In case anybody is wondering why exactly a Storage Account with explicitly allowed public IP might WORK FINE 4 times in a row, then throw an API error, here is a random answer from a random place
> 
> ```
> - Services deployed in the same region as the storage account use private Azure IP addresses for communication.
> - IP network rules have no effect on requests originating from the same Azure region as the storage account
> ```
> 
> I would be happy to find this in the documentation instead of wasting 4-5 hours manually testing why exactly it's broken. Please, tell me, what is the point of putting that information in: https://learn.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-portal
> 
> When at the same time it isn't present in: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
> 
> So basically there is a guide on how to find the IPs of managed agents (which is by the way, pretty much of no use, given the restrictions of the firewall settings), but it doesn't mention that in fact - even if bypassed, it will not work. Great.

I share the same frustration when it comes to the build agent and whitelist rules, specifically in the context of QA and end-to-end automation.
