### ISSUE TITLE
Error when creating vwan hub

### ISSUE THREAD

**Issue by ChristianDeckelmann** [Azure/azure-cli#18313] opened 2021-06-01 10:29 UTC
## Describe the bug

I get an error when trying to create a vwan hub.

**Command Name**
``
network vhub create ....

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
progress_patch() got an unexpected keyword argument 'det'
Traceback (most recent call last):
  File "C:\Users\deckel\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 663, in cli_execute
    result = invocation.execute(args)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 702, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 878, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/progress.py", line 179, in __init__
TypeError: progress_patch() got an unexpected keyword argument 'det'
To open an issue, please run: 'az feedback'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior

vwan hub creation.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.0 *

Extensions:
azure-firewall 0.10.0
import-export 0.1.1
interactive 0.4.4
ssh 0.1.5
virtual-wan 0.2.6

```

**Comment by yonzhan** [comment] 2021-06-01 14:37
network

**Comment by kairu-ms** [comment] 2021-06-02 05:19
Can you use `az network vhub create` in terminal directly instead of in `az interactive`. There maybe some bug in interactive.

You can use `az network vhub create -h` to get help messages.

**Comment by jiasli** [comment] 2021-06-07 02:03
Duplicate of #17740

**Closed by jiasli** 2021-06-07 02:03 UTC
Labels: Network, OKR3.2 Candidate, feature-request
