### ISSUE TITLE
webapp:az webapp up not working in tutorial

### ISSUE THREAD

**Issue by KeneObi** [Azure/azure-cli#15940] opened 2020-11-16 17:17 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
Expecting property name enclosed in double quotes: line 7 column 3 (char 116)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 3 (char 116)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Follow the steps in this tutorial
https://docs.microsoft.com/en-gb/learn/modules/host-a-web-app-with-azure-app-service/6-exercise-deploy-your-code-to-app-service?pivots=node
- `az webapp up --name {} --resource-group {} --plan {} --sku {} --location {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yonzhan** [comment] 2020-11-16 23:17
webapp

**Comment by KeneObi** [comment] 2020-11-19 18:31
Hi, please are there any updates on this?

**Comment by calvinsID** [comment] 2020-11-19 19:51
Hi @KeneObi, I was unable to reproduce following the tutorial linked above. From the tutorial where you set the variables, can you print out each one to verify the variables are set correctly? 
![image](https://user-images.githubusercontent.com/14339314/99716953-93819400-2a5d-11eb-9c2b-32c2a69d4a57.png)

**Comment by calvinsID** [comment] 2020-12-04 00:22
Closing since unable to repro, seems like invalid use of command. If error persists please tag me and reply here, and I'll re-investigate

**Closed by calvinsID** 2020-12-04 00:22 UTC
Labels: Service Attention, Web Apps
