### ISSUE TITLE
AZ Storage Blob copy show fails on azurestack

### ISSUE THREAD

**Issue by bottkars** [Azure/azure-cli#10160] opened 2019-08-06 04:47 UTC
## Describe the bug

**Command Name**
`az storage blob show`

**Errors:**
```
There is currently a pending copy operation.ErrorCode: PendingCopyOperation
<?xml version="1.0" encoding="utf-8"?><Error><Code>PendingCopyOperation</Code><Message>There is currently a pending copy operation.
RequestId:b7bc4247-4367-0190-64d5-81944a675031
Time:2019-08-06T04:44:05.8281636Z</Message></Error>
Traceback (most recent call last):
cli/command_modules/storage/__init__.py, ln 240, in new_handler
    handler(ex)
cli/command_modules/storage/__init__.py, ln 180, in handler
    if isinstance(ex, t_error) and ex.status_code == 409 and ex.error_code == 'NoPendingCopyOperation':
AttributeError: 'AzureConflictHttpError' object has no attribute 'error_code'

...

<?xml version="1.0" encoding="utf-8"?><Error><Code>PendingCopyOperation</Code><Message>There is currently a pending copy operation.
RequestId:b7bc4247-4367-0190-64d5-81944a675031
Time:2019-08-06T04:44:05.8281636Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._

* Start a storage blob copy from azure to AzureStack

- `az storage blob show --account-name {} --container-name {} --name {} --output {}`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67 *

```

**Comment by Juliehzl** [comment] 2019-08-06 05:34
Hi @bottkars, I think your issue is that after you run ```az storage blob copy```, you want to check if all the things have been copied and run```az storage blob show``` , but it fails with above error message, right?
It looks preceding copy operation hasn't been completed.

**Comment by bottkars** [comment] 2019-08-06 08:30
Problem here is that  I want to query the ongoing status.
connected to Azure, the result would be:
Expected Behaviour, verified on Azure
```
az storage blob show --account-name opsmanagerimage --container-name images --name ops-manager-2.6.6-build-test.179.vhd --query '[properties.copy.status]'
[
  "pending"
]
```
Atual Behaviour  on AzureStack:
```
az storage blob show --account-name opsmanagerimage --container-name images --name ops-manager-2.6.6-build-test.179.vhd --query '[properties.copy.status]'
The command failed with an unexpected error. Here is the traceback:

There is currently a pending copy operation.ErrorCode: PendingCopyOperation
<?xml version="1.0" encoding="utf-8"?><Error><Code>PendingCopyOperation</Code><Message>There is currently a pending copy operation.
RequestId:badf56da-0a7c-0712-4c03-1f600259469f
Time:2019-08-06T08:26:45.6761485Z</Message></Error>
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/command_modules/storage/__init__.py", line 248, in new_handler
    handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/command_modules/storage/__init__.py", line 188, in handler
    if isinstance(ex, t_error) and ex.status_code == 409 and ex.error_code == 'NoPendingCopyOperation':
AttributeError: 'AzureConflictHttpError' object has no attribute 'error_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/command_modules/storage/__init__.py", line 252, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/core/commands/arm.py", line 750, in show_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 375, in show_blob
    if_unmodified_since=if_unmodified_since, if_match=if_match, if_none_match=if_none_match, timeout=timeout)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/multiapi/storage/v2017_11_09/blob/pageblobservice.py", line 558, in get_page_ranges
    return self._perform_request(request, _convert_xml_to_page_ranges)
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/multiapi/storage/v2017_11_09/common/storageclient.py", line 370, in _perform_request
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/multiapi/storage/v2017_11_09/common/storageclient.py", line 305, in _perform_request
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/multiapi/storage/v2017_11_09/common/storageclient.py", line 291, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/site-packages/azure/multiapi/storage/v2017_11_09/common/_error.py", line 111, in _http_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureConflictHttpError: There is currently a pending copy operation.ErrorCode: PendingCopyOperation
<?xml version="1.0" encoding="utf-8"?><Error><Code>PendingCopyOperation</Code><Message>There is currently a pending copy operation.
RequestId:badf56da-0a7c-0712-4c03-1f600259469f
Time:2019-08-06T08:26:45.6761485Z</Message></Error>

To open an issue, please run: 'az feedback'
```

this brings a whole burden on scrtipting, as i need o query for until "success", wich may never come back when status is like "connection reset by peer" or "failed"

**Comment by Juliehzl** [comment] 2019-08-09 02:37
From my understanding, 1. what you really want is that you do not need to query if it succeed using ```blob show```. 2. In AzureStack, when you run ```blob show```, it should show something like Azure side:
```
az storage blob show --account-name opsmanagerimage --container-name images --name ops-manager-2.6.6-build-test.179.vhd --query '[properties.copy.status]'
[
  "pending"
]
```
rather than a burden of PendingCopyOperation message. Right?

**Comment by bottkars** [comment] 2019-08-21 09:45
yes.

**Comment by bottkars** [comment] 2019-08-21 09:48
i need to query the actual status of the operation to eval next steps in pipeline. 
i  can essentially work around the above to query in an until loop, buit this might to cause an endless loop for staes like "connection reset by peer" or thers

**Comment by jgallucci32** [comment] 2020-09-04 17:22
Has there been any progress on this issue? This is still an issue with Azure Stack Hub 2005 release. I was expecting the new storage APIs in the 2005 release to fix this but apparently it did not. Same error appears.

**Comment by calvinhzy** [comment] 2023-12-01 08:39
Hi @domggarrity, since this issue was for a very old version of the CLI, I have not been able to reproduce this issue. Do you have version information if you have encountered it recently? 
![image](https://github.com/Azure/azure-cli/assets/17182306/1fe53969-fb9d-42c5-a3b0-b09309ce8961)

**Comment by domggarrity** [comment] 2023-12-04 20:37
@calvinhzy, right now, we recommend that Azure Stack customers use Azure CLI 2.40.0 or higher. Which version(s) are you using?

**Comment by calvinhzy** [comment] 2023-12-05 01:30
@domggarrity currently using 2.54.0
![image](https://github.com/Azure/azure-cli/assets/17182306/2e2424b9-4e92-40db-b5e2-3bace16c5f75)

**Comment by domggarrity** [comment] 2024-01-17 17:57
@calvinhzy, following up on this.

**Comment by calvinhzy** [comment] 2024-01-18 07:33
Hi @domggarrity, can you share screenshots on your side? Have not been able to reproduce with old api version on Azure. Not sure how to test this on Azure Stack Hub.

**Comment by TheOnlyWei** [comment] 2024-01-19 01:53
Hi @domggarrity @calvinhzy I just tried the command using the latest Azure CLI version and cannot reproduce the error. Since the original customer hasn't replied, I think we can close this.

**Closed** 2024-01-19 01:54 UTC
Labels: Storage, customer-reported, feature-request

**Comment by coding-totoro** [comment] 2024-03-22 01:41
Not fixed, latest version using Azure CLI (from azure portal), I am getting something like the below:

There is currently a pending copy operation.
RequestId:733e7141-b01e-002b-76f9-7b3689000000
Time:2024-03-22T01:36:43.8769772Z
ErrorCode:PendingCopyOperation

This is a cross region copy just for reference. This error is intermittent, sometimes it returns the status and info, sometimes it doesn't and throws the above.

I have multiple copies running so checking status is vital.

**Comment by almalinux4all** [comment] 2024-03-26 14:04
We have the exactly same issue:

$ az version
{
  "azure-cli": "2.38.1",
  "azure-cli-core": "2.38.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Comment by zucchinidev** [comment] 2024-03-27 11:28
Same here. Example using Azure Cloud Shell:

```bash
andrea [ ~ ]$ az storage blob show  --account-name <ACCOUNT_NAME> --name <NAME> --container-name <CONTAINER_NAME> --query properties.copy_status

There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

You also can add `--auth-mode login` in your command to use Azure Active Directory (Azure AD) for authorization if your login account is assigned required RBAC roles.
For more information about RBAC roles in storage, visit https://docs.microsoft.com/azure/storage/common/storage-auth-aad-rbac-cli.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
There is currently a pending copy operation.
RequestId:d36ce1f0-201e-000c-0439-8073de000000
Time:2024-03-27T11:22:10.4148004Z
ErrorCode:PendingCopyOperation
andrea [ ~ ]$ az version
{
  "azure-cli": "2.58.0",
  "azure-cli-core": "2.58.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ai-examples": "0.2.5",
    "ml": "2.23.0",
    "ssh": "2.0.2"
  }
}
```
