### ISSUE TITLE
SSL failure with variable AZURE_CLI_DISABLE_CONNECTION_VERIFICATION set on az contianer exec

### ISSUE THREAD

**Issue by mztriz** [Azure/azure-cli#12466] opened 2020-03-05 20:51 UTC
## Describe the bug
SSL failure with variable AZURE_CLI_DISABLE_CONNECTION_VERIFICATION set on az contianer exec
AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1

**Command Name**
`az container exec`

**Errors:**
```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
3.7/lib/python3.7/ssl.py, ln 870, in _create
    self.do_handshake()
3.7/lib/python3.7/ssl.py, ln 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az container exec --resource-group {} --name {} --exec-command {}`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.77

```

**Comment by jiasli** [comment] 2021-08-06 06:42
Duplicate of #15121

**Closed** 2021-08-06 06:43 UTC
Labels: Service Attention, Container Instances, customer-reported, needs-team-attention
