### ISSUE TITLE
"az deployment mg what-if" fails for non-existent management groups

### ISSUE THREAD

**Issue by jomora** [Azure/azure-cli#22154] opened 2022-04-22 09:39 UTC
### **This is autogenerated. Please review and update as needed.**

I automated the creation of a management group sub-hierarchy below an existing management group using **Bicep**.
I created a pipeline in Azure DevOps which runs the `what-if` command, but it kept failing both in the pipeline and locally.
I used the same service principal in the pipeline as well as locally.
Digging into the issue I observed the steps listed in the "Steps to Reproduce" section.

## Describe the bug

**Command Name**
`az deployment mg what-if`

**Errors:**
```
MultipleErrorsOccurred - Multiple error occurred: DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError. Please see details.
DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/providers/Microsoft.Management/managementGroups/mg-root' has failed due to a resource error. See details for more information.
AuthorizationFailed - The client '...' with object id '...' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/mg-connectivity' or the scope is invalid. If access was recently granted, please refresh your credentials.
... and similar for other management groups
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- I use a service principal which has the owner role on the extising management group, but has no rights on tenant level.

1. Start: I have a single top-level management group with no child management groups
2. Running what-if fails with the error below
    - `az deployment mg what-if --location {} --name {} --template-file {} --management-group-id {} --parameters {}`
3. I successfully run the `az deployment mg create` command to deploy the management group hierarchy below the existing management group.
    - `az deployment mg create --location {} --name {} --template-file {} --management-group-id {} --parameters {}`
4. Running what-if fails again with the error below
5. I run `az login` again with the respective service principal
6. I run `az account set -s <subscription>` 
7. Running what-if works now

## Expected Behavior

Instead of failing, the what-if command should show that the non-existing management groups will be created.

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1 *

Extensions:
ssh 1.0.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context

Please let me know if you need more information.

**Comment by yonzhan** [comment] 2022-04-22 10:25
route to CXP team

**Comment by jennyhunter-msft** [comment] 2022-04-26 00:44
Also CC @alex-frankel

**Comment by alex-frankel** [comment] 2022-04-26 13:44
Duplicate of https://github.com/Azure/arm-template-whatif/issues/162

cc @rthorn17 / @shenglol / @majastrz. 

We have discussed this issue in the past. MG PUT returns a 403 for a non-existent MG instead of a 404. We believe this API should return a 404 in this case to match other RP behavior, but I remember there were extra challenges to making this change that Rich can clarify. The only other option is to special case this in what-if, which we would prefer not to do.

**Closed** 2022-06-30 08:02 UTC
Labels: Service Attention, ARM, customer-reported, needs-author-feedback, no-recent-activity, Auto-Assign
