### ISSUE TITLE
az interactive error

### ISSUE THREAD

**Issue by mikhailgithub** [Azure/azure-cli#10146] opened 2019-08-04 17:59 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-4.15.0-1052-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.70

Extensions:
interactive 0.4.3
image-copy-extension 0.2.1

```

**Comment by Juliehzl** [comment] 2019-08-05 01:20
Please run ```az interactive -h``` for more information. Through help message, you can find that you have to install interactive extension when using interactive mode.

**Comment by Juliehzl** [comment] 2019-08-05 01:24
@jiasli I think you have encounter a similar problem. Can you help figure out the error?

**Comment by Juliehzl** [comment] 2019-08-05 04:58
This is an error caused by duplicated prompt-toolkit 2.0.9 in core cli. You can delete the prompt-toolkit package in python3.6/site-packages/ and it will works. We will fix this in next release.

**Comment by yugangw-msft** [comment] 2019-08-05 16:09
dupe of #10088

**Closed by yugangw-msft** 2019-08-05 16:09 UTC
Labels: Interactive
