### ISSUE TITLE
unable to create mysql database using aws-cli on ubuntu 20.04

### ISSUE THREAD

**Issue by mahfooziiitian** [Azure/azure-cli#20573] opened 2021-12-01 08:57 UTC
## Describe the bug

**Command Name**
`az mysql flexible-server db create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py", line 699, in database_create_func
    parameters)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/rdbms/mysql_flexibleservers/operations/_databases_operations.py", line 154, in begin_create_or_update
    **kwargs
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/rdbms/mysql_flexibleservers/operations/_databases_operations.py", line 72, in _create_or_update_initial
    'resourceGroupName': self._serialize.url("resource_group_name", resource_group_name, 'str', max_length=90, min_length=1),
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 650, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az mysql flexible-server db create -d {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
rdbms-connect 0.1.4

```

**Comment by yonzhan** [comment] 2021-12-01 10:27
route to service team

**Comment by RakeshMohanMSFT** [comment] 2022-07-13 06:14
@mahfooziiitian Apologies for the delay, can you upgrade to the latest version of CLI [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and see if that fixes the issue for you?

**Comment by Bashar-MSFT** [comment] 2022-07-20 18:26
please assign this to sumuth@microsoft.com, this is not a bug but the user needs to use the latest cli version. @mksuni

**Comment by mksuni** [comment] 2022-07-20 18:54
@mahfooziiitian  I am not able to reproduce the issue for db create. The error No value for given attribute is very generic typically refers to missing parameter in the arguments being passed.  If you have a subscription  set by default on client machine and the server exists in that subscription , when you run the command as shown below it should work

az mysql flexible-server db create --database-name <DBNAME> --server-name <SERVERNAME> --resource-group <RESOURCEGROUPNAME>

You can find samples here https://docs.microsoft.com/en-us/cli/azure/mysql/flexible-server/db?view=azure-cli-latest to try it out . If you still run into the issue , I would recommend to share the arguments used without the actual values so it can help me reproduce the issue.

**Comment by Bashar-MSFT** [comment] 2022-07-27 20:21
@mahfooziiitian can you please check the answer and resolve this ?

**Comment by markingmyname** [comment] 2022-08-12 03:43
@mahfooziiitian

Is this GitHub Issue still a concern for you? If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

Due to the age of this issue, we will continue to close this issue.

Please visit https://docs.microsoft.com/en-us/answers/support/ for more information on asking questions about the product or service.

Thank you.

#please-close

**Comment by markingmyname** [comment] 2022-08-12 03:43
#please-close

**Closed** 2022-08-12 03:58 UTC
Labels: Service Attention, MySQL, customer-reported, needs-author-feedback
