### ISSUE TITLE
Issue with command 'az role definition list'

### ISSUE THREAD

**Issue by hemski635** [Azure/azure-cli#22546] opened 2022-05-20 13:20 UTC
## Describe the bug

**Command Name**
`az role definition list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'RoleDefinitionsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 49, in list_role_definitions
    definitions_client.config.subscription_id)
AttributeError: 'RoleDefinitionsOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition list`
- `az role definition list --subscription {}`

## Expected Behavior
List role definitions

## Environment Summary
```
Linux-5.17.0-1-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.10.4
Installer: DEB

azure-cli 2.36.0

Extensions:
ad 0.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment] 2022-05-20 14:58
@jiasli for awareness

**Comment by hemski635** [comment] 2022-05-20 15:00
Unrelated, but I love the auto generated issues from az cli <3

**Comment by jiasli** [comment] 2022-05-22 11:18
Duplicate of https://github.com/Azure/azure-cli/issues/19640

**Closed by jiasli** 2022-05-22 11:18 UTC
Labels: RBAC, customer-reported, Auto-Assign

**Comment by bartekmi** [comment] 2022-12-19 16:14
I don't believe this issue should have been closed.

I have done the following:

1. Uninstalled old/unofficial version of az as per instructions here: https://github.com/Azure/azure-cli/issues/19640#issuecomment-924578571
2. Installed the official `az` as per instructions here: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

Behavior is identical to the original error reported - exact same command, exact same error output. For reference, I paste the output below (stack trace is identical to original post except for changed line numbers).

Version Info:
```
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "ad": "0.1.0",
    "azure-devops": "0.24.0"
  }
}
```

```
Error loading command module 'aro': cannot import name 'AzureRedHatOpenShiftClient' from 'azure.mgmt.redhatopenshift' (/usr/lib/python3/dist-packages/azure/mgmt/redhatopenshift/__init__.py)
The command failed with an unexpected error. Here is the traceback:
'RoleDefinitionsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 224, in list_role_assignments
    definitions_client.config.subscription_id)
AttributeError: 'RoleDefinitionsOperations' object has no attribute 'config'
```
