### ISSUE TITLE
Cannot log into Azure Subscription

### ISSUE THREAD

**Issue by hoyabaptiste92** [Azure/azure-cli#21707] opened 2022-03-21 01:21 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to get authority configuration for https://login.microsoftonline.com/d5884a56-f725-4e55-bb68-9f4525198f88. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant_name
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 83, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 151, in tenant_discovery
ValueError: OIDC Discovery endpoint rejects our request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 177, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 746, in find_using_common_tenant
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 233, in get_user_credential
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line 39, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1466, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 438, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 87, in __init__
ValueError: Unable to get authority configuration for https://login.microsoftonline.com/d5884a56-f725-4e55-bb68-9f4525198f88. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant_name

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
account 0.2.2

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-03-21 01:46
@jiasli for awareness

**Comment by jiasli** [comment] 2022-03-21 01:59
Duplicate of https://github.com/Azure/azure-cli/issues/20507

Your tenant ID `d5884a56-f725-4e55-bb68-9f4525198f88` is incorrect:

```
GET https://login.microsoftonline.com/d5884a56-f725-4e55-bb68-9f4525198f88/v2.0/.well-known/openid-configuration
{"error":"invalid_tenant","error_description":"AADSTS90002: Tenant 'd5884a56-f725-4e55-bb68-9f4525198f88' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\r\nTrace ID: 9d9cdf4e-c3cf-4a44-87f3-756015a54500\r\nCorrelation ID: ce1b3092-c487-40bb-8820-ea01fdc19481\r\nTimestamp: 2022-03-21 01:54:54Z","error_codes":[90002],"timestamp":"2022-03-21 01:54:54Z","trace_id":"9d9cdf4e-c3cf-4a44-87f3-756015a54500","correlation_id":"ce1b3092-c487-40bb-8820-ea01fdc19481","error_uri":"https://login.microsoftonline.com/error?code=90002"}
```

We will refine the error message in next release of Azure CLI which takes https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/443.

**Closed by jiasli** 2022-03-21 01:59 UTC
Labels: Account, customer-reported, Auto-Assign

**Comment by jiasli** [comment] 2022-03-22 05:00
`d5884a56-f725-4e55-bb68-9f4525198f88` is not correct as AAD doesn't have information about this tenant: https://login.microsoftonline.com/d5884a56-f725-4e55-bb68-9f4525198f88/v2.0/.well-known/openid-configuration

Please double check if the GUID is right. BTW, can you access this subscription in Azure Portal?

**Comment by hoyabaptiste92** [comment] 2022-03-22 09:33
d5884a56-f725-4e55-bb68-9f4525198f88

It is a deleted (orphaned) AD that is still tied to my subscription. The subscription is my original when I signed up  for a personal Azure account. I am the subscription owner and I still see 8t in my billing. In fact I will have a bill for March due to activity.

**Comment by jiasli** [comment] 2022-03-23 05:27
For billing, subscription and directory/tenant management, you may create an Azure support ticket and a support engineer will assist you with it: https://azure.microsoft.com/en-us/support/create-ticket/
