### ISSUE TITLE
EventHubs Namespace List Fails when there are no EventHub Namespaces.

### ISSUE THREAD

**Issue by scsibug** [Azure/azure-cli#21833] opened 2022-03-28 21:07 UTC
## EventHubs Namespace List Fails with no EventHubs

**Command:**
``
az eventhubs namespace list --subscription=<subscription-id>
``

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 705, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.8/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.8/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/opt/az/lib/python3.8/site-packages/azure/mgmt/eventhub/v2021_06_01_preview/operations/_namespaces_operations.py", line 98, in extract_data
    return deserialized.next_link or None, iter(list_of_elem)
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:
Run `az eventhubs namespace list --subscription=<id>` in a subscription that contains no EventHub namespaces.

## Expected Behavior
No namespaces are returned, no errors.

## Environment Summary
```
Linux-5.13.0-37-generic-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
account 0.2.1
azure-iot 0.9.6

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-03-29 00:37
route to CXP team

**Comment by PramodValavala-MSFT** [comment] 2022-03-29 02:32
@scsibug I was unable to reproduce this error with a subscription having no event hub namespaces. Could you confirm if you are able to list them on the Azure Portal using the same account?

**Comment by scsibug** [comment] 2022-03-29 13:49
It only fails when the subscription ID is used, the subscription name works fine.

I can confirm it fails when run in Azure Portal Cloudshell as well (I'm testing in AzureUSGovernment cloud).

**Comment by scsibug** [comment] 2022-03-29 13:59
On another cloud (AzureCloud), I can get it to fail with either the subscription name or ID, in a different tenant.

I can duplicate across Cloudshell or locally installed AzureCLI, across multiple tenants, and multiple clouds.

**Comment by scsibug** [comment] 2022-10-16 18:06
How is this a feature request?  The feature is clearly documented in the help page (`az eventhubs namespace list`), where it lists  the option `--subscription      : Name or ID of subscription`.  Simply using that argument in a brand new cloudshell today continues to give the stacktrace from the original report.

Documented features giving stacktraces seems like a bug, no?

**Comment by Saglodha** [comment] 2022-10-17 11:57
Thanks for reporting this @scsibug. I could reproduce the issue at my side and would be investigating this ahead with the team. I would share updates soon.

**Comment by Saglodha** [comment] 2023-05-30 08:12
Hi @scsibug , this has been fixed in our latest release. Please retry the operation and let us know in case there are any other concerns.

**Closed** 2023-06-21 17:01 UTC
Labels: Service Attention, Event Hubs, customer-reported, needs-author-feedback, no-recent-activity, feature-request, Auto-Assign
