### ISSUE TITLE
Need to have DNS servers exposed at the time of NIC create

### ISSUE THREAD

**Issue by anavinahar** [Azure/azure-cli#3577] opened 2017-06-01 17:43 UTC
### Description
az network nic create should expose the option of being able to set a custom DNS server. The PowerShell equivalent of this is: 

New-AzureRmNetworkInterface -Name "NetworkInterface1" -ResourceGroupName "ResourceGroup1" -Location "centralus" -SubnetId "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/ResourceGroup1/providers/Microsoft.Network/virtualNetworks/VirtualNetwork1/subnets/Subnet1" -IpConfigurationName "IPConfiguration1" -DnsServer "8.8.8.8", "8.8.4.4"

Also can be found at this link: https://docs.microsoft.com/en-us/powershell/module/azurerm.network/New-AzureRmNetworkInterface?view=azurermps-4.0.0

CLI does show this when I do az network nic show as below: 

az network nic show --name nic1 -g pseudovipskip
{
  "dnsSettings": {
    "appliedDnsServers": [],
    "dnsServers": [
      "10.0.0.12"
    ],
    "internalDnsNameLabel": null,
    "internalDomainNameSuffix": "io4hp2nl3juexm2h50u44p1uub.xx.internal.cloudapp.net",
    "internalFqdn": null
  },
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2,0,0

**OS Version:** What OS and version are you using?  
Answer here: Windows

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by tjprescott** [comment] 2017-06-01 17:50
This is a duplicate of #3558.

**Closed by tjprescott** 2017-06-01 17:50 UTC

**Comment by tjprescott** [comment] 2017-06-01 17:54
You can set these currently with: 
`az network nic update -g {rg} -n {nic} --set dnsSettings.dnsServers=['10.0.0.12', '10.0.0.13']`

You may need to adjust the syntax somewhat and do any necessary escaping based on your shell of choice.
