### ISSUE TITLE
Prompts to upgrade from 2.50.0 to 2.51.0, then fails to upgrade (MacOS)

### ISSUE THREAD

**Issue by mkheck** [Azure/azure-cli#27173] opened 2023-08-15 14:10 UTC
### Describe the bug

Running `az upgrade` on a 2.50.0 install of azure-cli on MacOS results in following:

>> az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

**Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.**

Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): 

Updated 1 tap (homebrew/cask-fonts).

**Warning: azure-cli 2.50.0_1 already installed
CLI upgrade failed or aborted.**

In an effort to resolve this, I've completely uninstalled the azure-cli, deleted the ~/.azure directory, and reinstalled az using homebrew as prescribed here: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos

Same results.

NOTE: This is a significant problem because because it affects scripting. As an example: I have creation/configuration scripts I use, and I have several upcoming sessions at a partner conference showcasing Azure Spring Apps etc. Those scripts fail at key points due to the prompt inserting itself into the results (e.g. --query queries assigning values to env vars). This would seem to indicate that customer's production scripts could also be affected, at least in certain circumstances.

### Related command

az upgrade

### Errors

Warning: azure-cli 2.50.0_1 already installed
CLI upgrade failed or aborted.

### Issue script & Debug output

az upgrade

### Expected behavior

It should upgrade to the current version as indicated in the prompt it provides when running `az` commands:

Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.

### Environment Summary

>> az --version                                                             2 ↵

azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/Cellar/azure-cli/2.50.0_1/libexec/bin/python'
Extensions directory '/Users/markheckler/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jun 20 2023, 17:00:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal

**You have 3 update(s) available. Consider updating your CLI installation with 'az upgrade'**

**Comment by yonzhan** [comment] 2023-08-15 14:10
Thank you for opening this issue, we will look into it.

**Comment by mkheck** [comment] 2023-08-15 14:25
Thank you @yonzhan, please let me know how I can help, happy to do so.

**Comment by matthewlatcham** [comment] 2023-08-15 20:59
@mkheck - having the same issue on my Mac.

**Comment by bebound** [comment] 2023-08-16 01:55
2.51 is not available on homebrew, see https://github.com/Azure/azure-cli/issues/27047
Please disable autoupgrade `az config set auto-upgrade.enable=no`
Duplicate of https://github.com/Azure/azure-cli/issues/27091

**Comment by mkheck** [comment] 2023-08-16 18:30
Hi @bebound, that stops the "forced" upgrade but this message still applies with *every* command executed:

`You have 3 update(s) available. Consider updating your CLI installation with 'az upgrade'`

Still, progress. 👍

**Comment by NullChecked** [comment] 2023-08-16 20:04
I disabled all updates for now. `az config set auto-upgrade.all=no`

**Comment by hitec-lbmc** [comment] 2023-08-31 15:20
I was able to successfully upgrade it on my Mac using pip – 

`pip3 install azure-cli==2.51.0`

```
% az --version
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/opt/python@3.11/bin/python3.11'
Extensions directory '/Users/hiteshashar/.azure/cliextensions'

Python (Darwin) 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by bebound** [comment] 2023-09-06 01:55
Close as 2.52.0 is available in Homebrew.

**Closed by bebound** 2023-09-06 01:55 UTC
Labels: question, Installation, Upgrade, Auto-Assign, Azure CLI Team, Auto-Resolve
