### ISSUE TITLE
az webapp up failed

### ISSUE THREAD

**Issue by dnj55** [Azure/azure-cli#11247] opened 2019-11-15 03:18 UTC
<Note: This issue is a complement to the issue that I filed at 20:15 PST on Nov. 14, 2019; a browser window did not open and I wanted to file an issue this way as well to cover my bases.>

Issue: az webapp up failed

Steps already taken to attempt to remediate: uninstalled and reinstalled azure cli and updated pip.

Screenshot attached.

Thank you.

<img width="674" alt="2019-11-14" src="https://user-images.githubusercontent.com/26126597/68914470-e2467080-071b-11ea-8989-865d56439c10.png">

**Comment by dionisiovj** [comment] 2019-11-15 10:03
Same problem under Ubuntu 18.04. Commando still worked in v2.0.75

**Comment by panchagnula** [comment] 2019-11-16 02:23
Sorry this is a known issue & we are working on rolling out the new version with the fix soon. In the meanwhile please downgrade to 2.0.75

pip install azure-cli==2.0.75

The issue is fixed by the following change https://github.com/Azure/azure-cli/pull/11019

**Comment by panchagnula** [comment] 2019-11-27 23:46
Please update to the latest version of CLI https://pypi.org/project/azure-cli/ version 2.0.77 and re-try. there was a known regression with version 2.0.76

**Closed by panchagnula** 2019-11-27 23:46 UTC
Labels: Web Apps
