### ISSUE TITLE
failed to install on Ubuntu 21.10: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

### ISSUE THREAD

**Issue by hholst80** [Azure/azure-cli#21590] opened 2022-03-10 22:11 UTC
```
Step 6/8 : RUN     curl -sL https://aka.ms/InstallAzureCLIDeb | bash
 ---> Running in 8a66b2baea18
Hit:1 http://archive.ubuntu.com/ubuntu impish InRelease
Hit:2 http://archive.ubuntu.com/ubuntu impish-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu impish-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu impish-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.74.0-1.3ubuntu2).
The following additional packages will be installed:
  dirmngr distro-info-data gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client
  gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libnpth0 pinentry-curses
Suggested packages:
  dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage
  scdaemon pinentry-doc
The following NEW packages will be installed:
  apt-transport-https dirmngr distro-info-data gnupg gnupg-l10n gnupg-utils
  gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libassuan0
  libksba8 libnpth0 lsb-release pinentry-curses
0 upgraded, 17 newly installed, 0 to remove and 0 not upgraded.
Need to get 2165 kB of archives.
After this operation, 6127 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu impish-updates/main amd64 distro-info-data all 0.51ubuntu1.1 [5112 B]
Get:2 http://archive.ubuntu.com/ubuntu impish/main amd64 lsb-release all 11.1.0ubuntu3 [10.8 kB]
Get:3 http://archive.ubuntu.com/ubuntu impish/universe amd64 apt-transport-https all 2.3.9 [1510 B]
Get:4 http://archive.ubuntu.com/ubuntu impish/main amd64 libassuan0 amd64 2.5.5-1 [38.4 kB]
Get:5 http://archive.ubuntu.com/ubuntu impish/main amd64 gpgconf amd64 2.2.20-1ubuntu4 [91.1 kB]
Get:6 http://archive.ubuntu.com/ubuntu impish/main amd64 libksba8 amd64 1.5.1-1 [109 kB]
Get:7 http://archive.ubuntu.com/ubuntu impish/main amd64 libnpth0 amd64 1.6-3 [8220 B]
Get:8 http://archive.ubuntu.com/ubuntu impish/main amd64 dirmngr amd64 2.2.20-1ubuntu4 [281 kB]
Get:9 http://archive.ubuntu.com/ubuntu impish/main amd64 gnupg-l10n all 2.2.20-1ubuntu4 [51.4 kB]
Get:10 http://archive.ubuntu.com/ubuntu impish/main amd64 gnupg-utils amd64 2.2.20-1ubuntu4 [302 kB]
Get:11 http://archive.ubuntu.com/ubuntu impish/main amd64 gpg amd64 2.2.20-1ubuntu4 [479 kB]
Get:12 http://archive.ubuntu.com/ubuntu impish/main amd64 pinentry-curses amd64 1.1.1-1 [32.0 kB]
Get:13 http://archive.ubuntu.com/ubuntu impish/main amd64 gpg-agent amd64 2.2.20-1ubuntu4 [191 kB]
Get:14 http://archive.ubuntu.com/ubuntu impish/main amd64 gpg-wks-client amd64 2.2.20-1ubuntu4 [62.3 kB]
Get:15 http://archive.ubuntu.com/ubuntu impish/main amd64 gpg-wks-server amd64 2.2.20-1ubuntu4 [56.9 kB]
Get:16 http://archive.ubuntu.com/ubuntu impish/main amd64 gpgsm amd64 2.2.20-1ubuntu4 [186 kB]
Get:17 http://archive.ubuntu.com/ubuntu impish/main amd64 gnupg all 2.2.20-1ubuntu4 [260 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2165 kB in 0s (18.6 MB/s)
Selecting previously unselected package distro-info-data.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 13704 files and directories currently installed.)
Preparing to unpack .../00-distro-info-data_0.51ubuntu1.1_all.deb ...
Unpacking distro-info-data (0.51ubuntu1.1) ...
Selecting previously unselected package lsb-release.
Preparing to unpack .../01-lsb-release_11.1.0ubuntu3_all.deb ...
Unpacking lsb-release (11.1.0ubuntu3) ...
Selecting previously unselected package apt-transport-https.
Preparing to unpack .../02-apt-transport-https_2.3.9_all.deb ...
Unpacking apt-transport-https (2.3.9) ...
Selecting previously unselected package libassuan0:amd64.
Preparing to unpack .../03-libassuan0_2.5.5-1_amd64.deb ...
Unpacking libassuan0:amd64 (2.5.5-1) ...
Selecting previously unselected package gpgconf.
Preparing to unpack .../04-gpgconf_2.2.20-1ubuntu4_amd64.deb ...
Unpacking gpgconf (2.2.20-1ubuntu4) ...
Selecting previously unselected package libksba8:amd64.
Preparing to unpack .../05-libksba8_1.5.1-1_amd64.deb ...
Unpacking libksba8:amd64 (1.5.1-1) ...
Selecting previously unselected package libnpth0:amd64.
Preparing to unpack .../06-libnpth0_1.6-3_amd64.deb ...
Unpacking libnpth0:amd64 (1.6-3) ...
Selecting previously unselected package dirmngr.
Preparing to unpack .../07-dirmngr_2.2.20-1ubuntu4_amd64.deb ...
Unpacking dirmngr (2.2.20-1ubuntu4) ...
Selecting previously unselected package gnupg-l10n.
Preparing to unpack .../08-gnupg-l10n_2.2.20-1ubuntu4_all.deb ...
Unpacking gnupg-l10n (2.2.20-1ubuntu4) ...
Selecting previously unselected package gnupg-utils.
Preparing to unpack .../09-gnupg-utils_2.2.20-1ubuntu4_amd64.deb ...
Unpacking gnupg-utils (2.2.20-1ubuntu4) ...
Selecting previously unselected package gpg.
Preparing to unpack .../10-gpg_2.2.20-1ubuntu4_amd64.deb ...
Unpacking gpg (2.2.20-1ubuntu4) ...
Selecting previously unselected package pinentry-curses.
Preparing to unpack .../11-pinentry-curses_1.1.1-1_amd64.deb ...
Unpacking pinentry-curses (1.1.1-1) ...
Selecting previously unselected package gpg-agent.
Preparing to unpack .../12-gpg-agent_2.2.20-1ubuntu4_amd64.deb ...
Unpacking gpg-agent (2.2.20-1ubuntu4) ...
Selecting previously unselected package gpg-wks-client.
Preparing to unpack .../13-gpg-wks-client_2.2.20-1ubuntu4_amd64.deb ...
Unpacking gpg-wks-client (2.2.20-1ubuntu4) ...
Selecting previously unselected package gpg-wks-server.
Preparing to unpack .../14-gpg-wks-server_2.2.20-1ubuntu4_amd64.deb ...
Unpacking gpg-wks-server (2.2.20-1ubuntu4) ...
Selecting previously unselected package gpgsm.
Preparing to unpack .../15-gpgsm_2.2.20-1ubuntu4_amd64.deb ...
Unpacking gpgsm (2.2.20-1ubuntu4) ...
Selecting previously unselected package gnupg.
Preparing to unpack .../16-gnupg_2.2.20-1ubuntu4_all.deb ...
Unpacking gnupg (2.2.20-1ubuntu4) ...
Setting up libksba8:amd64 (1.5.1-1) ...
Setting up apt-transport-https (2.3.9) ...
Setting up distro-info-data (0.51ubuntu1.1) ...
Setting up libnpth0:amd64 (1.6-3) ...
Setting up libassuan0:amd64 (2.5.5-1) ...
Setting up gnupg-l10n (2.2.20-1ubuntu4) ...
Setting up gpgconf (2.2.20-1ubuntu4) ...
Setting up lsb-release (11.1.0ubuntu3) ...
Setting up gpg (2.2.20-1ubuntu4) ...
Setting up gnupg-utils (2.2.20-1ubuntu4) ...
Setting up pinentry-curses (1.1.1-1) ...
Setting up gpg-agent (2.2.20-1ubuntu4) ...
Setting up gpgsm (2.2.20-1ubuntu4) ...
Setting up dirmngr (2.2.20-1ubuntu4) ...
Setting up gpg-wks-server (2.2.20-1ubuntu4) ...
Setting up gpg-wks-client (2.2.20-1ubuntu4) ...
Setting up gnupg (2.2.20-1ubuntu4) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.34-0ubuntu3.2) ...
Get:1 https://packages.microsoft.com/repos/azure-cli impish InRelease [[581](https://github.com/omnimodular/centsoft/runs/5502930047?check_suite_focus=true#step:4:581)6 B]
Hit:2 http://archive.ubuntu.com/ubuntu impish InRelease
Hit:3 http://archive.ubuntu.com/ubuntu impish-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu impish-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu impish-security InRelease
Fetched 5816 B in 1s (11.2 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package azure-cli
The command '/bin/sh -c curl -sL https://aka.ms/InstallAzureCLIDeb | bash' returned a non-zero code: 100
Service 'integration-tests' failed to build : Build failed

Error: Process completed with exit code 1.
```

**Comment by yonzhan** [comment] 2022-03-10 23:03
@jiasli for awareness

**Comment by jiasli** [comment] 2022-03-11 02:15
Duplicate of https://github.com/Azure/azure-cli/issues/21532

**Closed by jiasli** 2022-03-11 02:15 UTC
Labels: customer-reported, Installation, Auto-Assign
