### ISSUE TITLE
Unclaim functionality needed 

### ISSUE THREAD

**Issue by theharleyquin** [Azure/azure-cli#8194] opened 2019-01-08 18:29 UTC
Having the ability to claim a VM is very nice but there is no way to unclaim the VM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5457fd-c38a-6fb8-1df4-24a15e6ba787
* Version Independent ID: ef65acdc-464a-08c7-b013-d9e3f1560977
* Content: [az lab vm](https://docs.microsoft.com/en-us/cli/azure/lab/vm?view=azure-cli-latest#az-lab-vm-claim)
* Content Source: [src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_help.py)
* Service: **devtest-lab**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment] 2019-01-08 21:50
Duplicate of #6022.

**Closed by tjprescott** 2019-01-08 21:51 UTC
Labels: Devtestlab, Feature
