### ISSUE TITLE
cannot execute az connectedk8s connect

### ISSUE THREAD

**Issue by dainomat** [Azure/azure-cli#25235] opened 2023-01-25 22:52 UTC
## Describe the bug

**Command Name**
`az connectedk8s connect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cpython-310-x86_64-linux-gnu.so': cannot load library '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.cpython-310-x86_64-linux-gnu.so': /root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.cpython-310-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.cpython-310-x86_64-linux-gnu.so', Trying '_MD5.abi3.so': cannot load library '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.abi3.so': /root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.abi3.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.abi3.so', Trying '_MD5.so': cannot load library '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.so': /root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.so'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 507, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.10/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 33, in <module>
    from Crypto.IO import PEM
  File "/root/.azure/cliextensions/connectedk8s/Crypto/IO/PEM.py", line 39, in <module>
    from Crypto.Hash import MD5
  File "/root/.azure/cliextensions/connectedk8s/Crypto/Hash/MD5.py", line 29, in <module>
    _raw_md5_lib = load_pycryptodome_raw_lib("Crypto.Hash._MD5",
  File "/root/.azure/cliextensions/connectedk8s/Crypto/Util/_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cpython-310-x86_64-linux-gnu.so': cannot load library '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.cpython-310-x86_64-linux-gnu.so': /root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.cpython-310-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.cpython-310-x86_64-linux-gnu.so', Trying '_MD5.abi3.so': cannot load library '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.abi3.so': /root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.abi3.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.abi3.so', Trying '_MD5.so': cannot load library '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.so': /root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/root/.azure/cliextensions/connectedk8s/Crypto/Util/../Hash/_MD5.so'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {}`

## Environment Summary
```
Linux-5.4.0-1100-azure-x86_64-with-glibc2.27, Ubuntu 18.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.44.1

Extensions:
k8s-extension 1.0.0
connectedk8s 1.2.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2023-01-26 06:22
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2023-02-10 01:48
@dainomat  I am not able to reproduce this issue.  Can you please try to upgrade `connectedk8s` extension version.

**Comment by SaurabhSharma-MSFT** [comment] 2023-02-15 18:26
@dainomat Please let me know if you still have any questions.

**Comment by dainomat** [comment] 2023-02-15 21:43
Thank you for your help. You can close this case. Thank you.

**Comment by SaurabhSharma-MSFT** [comment] 2023-02-15 22:02
@dainomat Thanks for the confirmation.  We will now proceed to close this thread.

**Closed by SaurabhSharma-MSFT** 2023-02-15 22:02 UTC
Labels: customer-reported, needs-team-attention, Connected Kubernetes, CXP Attention
