### ISSUE TITLE
az monitor autoscale rule list fails

### ISSUE THREAD

**Issue by uveta** [Azure/azure-cli#11888] opened 2020-01-17 09:50 UTC
## Describe the bug

**Command Name**
`az monitor autoscale rule list`

**Errors:**
```
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 657, in _run_job
    cmd_copy.exception_handler(ex)
cli/command_modules/monitor/_exception_handler.py, ln 42, in monitor_exception_handler
    reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 490, in default_command_handler
    return op(**command_args)
command_modules/monitor/operations/autoscale_settings.py, ln 341, in autoscale_rule_list
    profile = next(x for x in autoscale_settings.profiles if x.name == profile_name)
StopIteration
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create autoscale rule for AppService from Azure portal
- `az monitor autoscale rule list --autoscale-name {} --resource-group {}`

## Environment Summary
```
Linux-4.15.0-1064-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78 *

```

**Comment by jsntcy** [comment] 2020-01-19 02:20
@MyronFanQiu, @jsntcy, please help take a look, thanks.

**Comment by yonzhan** [comment] 2020-03-08 02:11
add to S168

**Comment by jsntcy** [comment] 2020-04-16 10:50
@uveta,

- If you run the command `az monitor autoscale rule list -h`, you can see there is an optional argument `--profile-name` with default value `default`, as you created autoscale rule for AppService from Azure portal and the profile name for the autoscale is not `default`, so you need run command `az monitor autoscale rule list` with your `--profile-name`. 
- You can find `--profile-name` on Portal as below, the default profile name is `Auto created scale condition` if you don't rename it.
![image](https://user-images.githubusercontent.com/16348853/79447583-a5581000-8012-11ea-86e8-4f4a74566a6c.png)
- If you use CLI command `az monitor autoscale create` without `--profile-name` to create a autoscale rule, the profile name will be "default" as default.

**Comment by jsntcy** [comment] 2020-04-17 03:00
Close this issue as this issue was caused by missing necessary `--profile-name` argument when running `az monitor autoscale rule list`.

**Closed by jsntcy** 2020-04-17 03:00 UTC
Labels: Feature Request, Monitor, Monitor - Autoscale, OKR3.2 Candidate

**Comment by uveta** [comment] 2020-04-17 10:47
Thank you @jsntcy 

It was not clear what was the issue from the error message I received. But thanks once again for clarification.
