### ISSUE TITLE
No module named azure.cli.__main__

### ISSUE THREAD

**Issue by travisnielsen** [Azure/azure-cli#8716] opened 2019-03-07 03:56 UTC
**Describe the bug**
Unable to run ```az``` after installing azure-cli via homebrew.
```
/usr/local/opt/python/bin/python3.7: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed
```

**To Reproduce**
Re-installed python and azure-cli via homebrew.

**Expected behavior**
Able to run command

**Environment summary**
MacOS 10.24.3

```
which az
/usr/local/bin/az

cat $(which az)
#!/usr/bin/env bash
export PYTHONPATH="/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages"
if command -v python3.7 >/dev/null 2>&1; then
  python3.7 -m azure.cli "$@"
else
  python3 -m azure.cli "$@"
fi
```

**Additional context**
I'm not super deep with managing Python environments. Really hoping someone can assist here!

**Comment by yugangw-msft** [comment] 2019-03-07 21:17
@marstr, can you please check out whether this is a known issue and can be address'd by the venv solution?

**Comment by marstr** [comment] 2019-03-08 05:30
This is effectively a dupe of https://github.com/Azure/azure-cli/issues/8689. This problem occurs when Python3.7 is installed outside of the Hombrew environment before the Azure CLI is installed. We're fixing this by installing into a virtual environment and having the execution script shown above be replaced by a call directly to the python launcher in the virtual environment that was created for us.

**Closed by marstr** 2019-03-08 05:30 UTC
Labels: Packaging/Homebrew
