### ISSUE TITLE
az login failed when running inside LSW ubuntu image on windows desktop.

### ISSUE THREAD

**Issue by BrianMouncer** [Azure/azure-cli#12392] opened 2020-02-29 00:56 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
[Errno 13] Permission denied: '/home/brian/.azure/accessTokens.json'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 693, in reraise
    raise value
...
azure/cli/core/util.py, ln 237, in get_file_json
    content = read_file_content(file_path)
azure/cli/core/util.py, ln 251, in read_file_content
    with codecs_open(file_path, encoding=encoding) as f:
az/lib/python3.6/codecs.py, ln 897, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/home/brian/.azure/accessTokens.json'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81 *

```

**Comment by yungezz** [comment] 2020-02-29 02:02
HI @arrownj could you pls have a look? thanks.

**Comment by arrownj** [comment] 2020-04-13 05:55
Hi @BrianMouncer , it seems that you don't have permission to read/write files under `.azure` of your home directory. Could you please help check the folder permission? Maybe you can do some manual test to check whether you can read/write files or just use `ll` to check the folder/file mod.

**Comment by arrownj** [comment] 2020-05-26 07:17
Hi @BrianMouncer , per talked offline, will close this issue first as can't reproduce it. You can reopen it or submit a new one if you encounter it again. And please help check it permission if it happens again. Thanks

**Closed by arrownj** 2020-05-26 07:17 UTC
Labels: Authentication
