### ISSUE TITLE
az group create: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by sanghoonkim0918** [Azure/azure-cli#12696] opened 2020-03-21 17:57 UTC
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
'NoneType' object is not callable
Traceback (most recent call last):
lib/python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 608, in execute
    raise ex
azure/cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
azure/cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
3.7/lib/python3.7/site-packages/six.py, ln 696, in reraise
    raise value
azure/cli/core/commands/__init__.py, ln 636, in _run_job
    result = cmd_copy(params)
azure/cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
site-packages/azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
azure/cli/command_modules/resource/custom.py, ln 991, in create_resource_group
    tags=tags
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group create --location eastus2 --name TestGroup`

## Environment Summary
```
Darwin-19.3.0-x86_64-i386-64bit
Python 3.7.4

azure-cli 2.2.0

```

**Comment by yonzhan** [comment] 2020-03-22 01:07
add to S168

**Comment by zhoxing-ms** [comment] 2020-04-07 03:00
@sanghoonkim0918 Hi, I can't reproduce your question. Could you please provide more specific parameter information? Placeholders can be used instead of sensitive privacy information.

**Comment by zhoxing-ms** [comment] 2020-04-07 03:02
It seems to be the same problem #12540

**Comment by yonzhan** [comment] 2020-04-11 10:30
@sanghoonkim0918 any update/feedback?

**Comment by zhoxing-ms** [comment] 2020-04-28 08:36
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-04-28 08:36 UTC
Labels: ARM, OKR3.2 Candidate, feature-request

**Comment by lodos2005** [comment] 2021-02-03 21:30
### **This is autogenerated. Please review and update as needed.**

## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
'NoneType' object is not callable
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 330, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 786, in default_command_handler
    return op(**command_args)
cli/command_modules/resource/custom.py, ln 1211, in create_resource_group
    parameters = ResourceGroup(
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group create --location {} --name {} --debug`

## Expected Behavior

## Environment Summary
```
Linux-5.8.0-kali1-amd64-x86_64-with-glibc2.31
Python 3.9.1+
Installer: DEB

azure-cli 2.18.0

Extensions:
azure-devops 0.19.0

```
## Additional Context
