### ISSUE TITLE
licenseType query doesn't work as expected

### ISSUE THREAD

**Issue by Xumukk** [Azure/azure-cli#7118] opened 2018-08-22 14:18 UTC
**Describe the bug**
According to [documentation ](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/hybrid-use-benefit-licensing#cli-3) you can query licenseType with JMESPath queries.
This command `az vm list --query '[?licenseType==Windows_Server]' -o table` should return table with VMs with licenseType value equal to Windows_Server, but it will return list of VMs with licenseType value null.
If you run `az vm list --query '[?licenseType!=Windows_Server]' -o table` it will show all VMs with Windows_Server and Windows_Client values.
If you run `az vm list --query '[].{vmname:name,licenseType:licenseType}' -o table` it will list all VMs with correct information regarding licenseType value.

**To Reproduce**
Run commands from description.

**Expected behavior**
Command `az vm list --query '[?licenseType==Windows_Server]' -o table` should return table with VMs with licenseType value equal to Windows_Server.

**Environment summary**
azure-cli (2.0.34) on Windows,  azure-cli (2.0.44) on Azure CloudShell. 

**Additional context**

**Comment by tjprescott** [comment] 2018-08-22 15:55
@adewaleo since you are looking at JMESPath queries anyways, can you take a look?  I suspect the issue is just that the format is wrong in the example.

**Comment by adewaleo** [comment] 2018-08-23 18:02
**You can correctly make the above query by doing the following:**

`az vm list --query "[?licenseType == 'Windows_Server']" -o table`

**For an explanation of why this is the correct way of writing the filter expression query, please see below.**

There are two different ways to specify [string literals in JMESPath](http://jmespath.org/specification.html#raw-string-literals):

-     `"Windows_Server"`
Back ticks are used in literal expressions. So the above is a string literal expression.
-     'Windows_Server'
Using single quotes is a shorthand for writing a string literal expression.

The following is an alternative way of making the query you want.

    az vm list --query "[?licenseType==\`\"Windows_Server\"\`]" -o table

Notice that the back-ticks and double quotes are escaped. `echo  my_query` can be helpful for seeing what is actually passed as the query to the command.

I hope this helps. I will be closing this issue, but please let us know if you have any other questions.
The query from the documentation you linked to is incorrect, so I will make sure to raise the issue with them.

**Closed by adewaleo** 2018-08-23 18:02 UTC
Labels: Compute-cli, Documentation
