### ISSUE TITLE
"Table output unavailable" for command "az network public-ip list -o table" on Mac OS.

### ISSUE THREAD

**Issue by ptsapralis** [Azure/azure-cli#20440] opened 2021-11-19 11:21 UTC
## Describe the bug

**Command Name**
Command `az network public-ip list -o table` returns an error message as indicated below (tested on both Mac OS Big Sur or Monterey). Command works as expected on Linux systems (same Azure CLI version, 2.30.0, tested on different Linux versions).

**Errors:**
```
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network public-ip list -o table`

## Expected Behavior

Display a table-formatted list of public IP addresses available in the subscription.

## Environment Summary
```
macOS-11.6.1-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.30.0

```

**Comment by yonzhan** [comment] 2021-11-19 13:38
Table output unavailable

**Comment by juarezr** [comment] 2021-11-19 15:35
It looks like any command with table output fails. 

E.g: `az account list -o table`.

See also the diagnostics [here](https://github.com/Azure/azure-cli/issues/17744#issuecomment-974163422) on #17744 17744

**Comment by ptsapralis** [comment] 2021-11-19 15:39
Indeed, I have just confirmed that “-o table” isn’t accepted as a command-line option for any command on Mac OS.

Panos Tsapralis
Head of Networks
(M) 07507477883
(direct) 442082755505
4 Imperial Place, Maxwell Road, Borehamwood, Hertfordshire, WD6 1JN
***@***.******@***.***>

[signature_1980114370]   [signature_218181445]     ***@***.***

From: Juarez Rudsatz ***@***.***>
Reply to: Azure/azure-cli ***@***.***>
Date: Friday, 19 November 2021 at 15:36
To: Azure/azure-cli ***@***.***>
Cc: Panos Tsapralis ***@***.***>, Author ***@***.***>
Subject: Re: [Azure/azure-cli] "Table output unavailable" for command "az network public-ip list -o table" on Mac OS. (Issue #20440)


It looks like any command with table output fails.

E.g: az account list -o table.

See also the diagnostics here<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F17744%23issuecomment-974163422&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7C6e2dc6e6227c405779e908d9ab724862%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637729329628752120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=umDoUDYZyxDBP6Ujxkt0NqBwNl%2FgvdcGW0vGj8iuWM4%3D&reserved=0> on #17744<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F17744&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7C6e2dc6e6227c405779e908d9ab724862%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637729329628762114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5bL20nWR69zJSph5ck4E4CalZtAXYCVz3dYBajkyx30%3D&reserved=0> 17744

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F20440%23issuecomment-974174857&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7C6e2dc6e6227c405779e908d9ab724862%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637729329628762114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8CssDWhUEYUKqvUsnUg4K4QQu6k%2BLt7MsBL5ReWP2FI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADLRXZOC3ZBT3YNQJLQQR7DUMZVFZANCNFSM5IL45DKA&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7C6e2dc6e6227c405779e908d9ab724862%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637729329628772105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Fq7CT8B6uJoCgpNl9HP6Ehriz5CCjDacrYFrZIrsBN8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7C6e2dc6e6227c405779e908d9ab724862%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637729329628782110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oTeU4Dwf%2BQwFMrV%2By7mGg5vlIiGv97c8Bk4GMZs8hFE%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7C6e2dc6e6227c405779e908d9ab724862%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637729329628782110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l4iIQOHoUAT3y5VrN4Az6UFuu3%2FiXrAa5u1maGuApS4%3D&reserved=0>.

**Comment by ralfkrause** [comment] 2021-11-20 08:33
The issue seems to be related to python 3.10

A workaround until the problem is fixed was for me installing the Azure CLI with pip:

`pip install az-cli`

After that the azure cli was using Python 3.9 again. And table as output format worked again.

```
az network vnet  list -o table
Name     ResourceGroup    Location    NumSubnets    Prefixes     DnsServers    DDOSProtection
-------  ---------------  ----------  ------------  -----------  ------------  ----------------
vnetde1  AZ-104           westeurope  1             10.2.0.0/16                False
vnetus1  AZ-104           centralus   1             10.1.0.0/16                False
```

**Comment by jiasli** [comment] 2021-11-22 01:50
Duplicate of #20348

**Comment by jiasli** [comment] 2021-11-22 01:51
@ralfkrause, the pip command should be 

```
pip install azure-cli
```

(not `az-cli`)

**Closed by jiasli** 2021-11-22 01:50 UTC
Labels: Network, Core, customer-reported

**Comment by ralfkrause** [comment] 2021-11-22 03:12
@jiasli That didn't work for me at the first try. But installing it with  `pip install az-cli` which installs [https://github.com/MarkWarneke/Az.Cli](https://github.com/MarkWarneke/Az.Cli) worked immediately.
When I tried `pip install azure-cli` the first time, it was still using python 3.10 which resulted in the problem.
Maybe there was still some information kept which pointed to Python 3.10.
I removed uninstalled now the azure cli from homebrew with `brew uninstall azure-cli` and uninstalled also az which I installed previously `pip uninstall az`.

I installed it now with `pip install azure-cli`. This time it was using Python 3.9

**Comment by jiasli** [comment] 2021-11-22 03:33
- `az.cli` (https://pypi.org/project/az.cli/) is not `azure-cli` at all. It is a Python interface to call Azure CLI. It depends on `azure-cli` directly, without any version specification: https://github.com/MarkWarneke/Az.Cli/blob/dev/requirements.txt. So I don't think it will solve the problem. Something should be missing.
- `az` (https://pypi.org/project/az/): I don't know what this is.



> I installed it now with `pip install azure-cli`. This time it was using Python 3.9

Yes. This should be the correct solution for now.

**Comment by ralfkrause** [comment] 2021-11-22 06:55
@jiasli I know that az.cli isn't azure cli and just a python library for Azure CLI. 
I also don't understand why installing az.cli corrected which Python version Azure CLI is using. That is completely out of my understanding.

**Comment by jiasli** [comment] 2021-11-22 09:45
@ralfkrause, I don't understand either. Anyway, you may use `azure-cli` with Python 3.9 for now.

**Comment by jiasli** [comment] 2021-11-22 09:58
Wait, looks like homebrew hasn't take Python 3.9.9 yet (https://github.com/Azure/azure-cli/issues/20348#issuecomment-973803211). We can only wait for Homebrew to take Python 3.9.9 and install with `pip`.

**Comment by ptsapralis** [comment] 2021-11-22 11:09
Hi.

Thanks for the hint on un-installing / re-installing "az-cli" component. Not that simple in my case, though, as I had to remove “sfctl” 9Service Fabric Control command-line utility) because of versions’ conflicts. Anyway, I now have Azure CLI working properly on the command line on the Mac - hopefully, there will soon be a fix to re-align versions / dependencies etc.

Regards,
--
Panos Tsapralis
Head of Networks
(M) 07507477883
(direct) 442082755505
4 Imperial Place, Maxwell Road, Borehamwood, Hertfordshire, WD6 1JN
***@***.******@***.***>

***@***.***   ***@***.*** ***@***.***

On 22 Nov 2021, at 09:58, Jiashuo Li ***@***.******@***.***>> wrote:



Wait, looks like homebrew hasn't take Python 3.9.9 yet (#20348 (comment)<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F20348%23issuecomment-973803211&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cf45d1173200641e5805a08d9ad9e9b75%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637731718997601240%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Bdw%2FLjOnuTHtzQmxmmHfsto4PZrzOGobQUqIl366GzA%3D&reserved=0>). We can only wait for Homebrew to take Python 3.9.9 and install with pip.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F20440%23issuecomment-975349084&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cf45d1173200641e5805a08d9ad9e9b75%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637731718997611233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dUiBxCOht7lFKFp4ULLBRzagxQRsDH46j8OTnZApDpk%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADLRXZKKTU3IUGNNX2YWMELUNIH3RANCNFSM5IL45DKA&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cf45d1173200641e5805a08d9ad9e9b75%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637731718997621228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rwvW8%2FtrIEFC9bCFzIKBHo%2B326HfVgraqCc26LN6GIk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cf45d1173200641e5805a08d9ad9e9b75%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637731718997621228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FA9L4pSkQC%2FGa8of6y3npl2ZCT1HcqEzcgFmhslGNqY%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cf45d1173200641e5805a08d9ad9e9b75%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637731718997631218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tV1z9EIf5OeaQrr067rOJvpuOYHvqt4B1R4PepY4bMM%3D&reserved=0>.
