### ISSUE TITLE
K8s Max retries exceeded with url

### ISSUE THREAD

**Issue by pimjansen** [Azure/azure-cli#9144] opened 2019-04-18 13:24 UTC
## Describe the bug
Error while creating K8s tunnel which is open for some time.
```
$ az aks browse --resource-group k8s-test-resource-group -
Merged "k8s-test" as current context in /tmp/tmpRZo4wL
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
```
```
The command failed with an unexpected error. Here is the traceback:

HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f26901290>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/home/pim/lib/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/pim/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f26901290>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Command Name**
`az aks browse`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Run: az aks browse --resource-group {} --name {}`

## Expected Behavior

Expect the tunnel to stay open

## Environment Summary
```
Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-18.04-bionic
Python 2.7.15rc1
Shell: bash

azure-cli                         2.0.62

```

**Comment by tjprescott** [comment] 2019-04-18 22:12
This looks like it might be a transient error

**Comment by seanmck** [comment] 2019-07-14 07:13
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:13 UTC
Labels: AKS, Needs Triage, Service Attention
