### ISSUE TITLE
az login with managed identity times out.

### ISSUE THREAD

**Issue by wordrak** [Azure/azure-cli#9054] opened 2019-04-10 16:32 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01&msi_res_id=%2Fsubscriptions%2F55ac4ce5-f395-4dca-90bd-f92edcdd82b7%2Fresourcegroups%2Ftest-project-setup%2Fproviders%2FMicrosoft.ManagedIdentity%2FuserAssignedIdentities%2FHRC-API-Deployer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11047ce48>: Failed to establish a new connection: [Errno 60] Operation timed out'))Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11047ce48>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01&msi_res_id=%2Fsubscriptions%2F55ac4ce5-f395-4dca-90bd-f92edcdd82b7%2Fresourcegroups%2Ftest-project-setup%2Fproviders%2FMicrosoft.ManagedIdentity%2FuserAssignedIdentities%2FHRC-API-Deployer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11047ce48>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/command_modules/profile/custom.py", line 111, in login
    return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/_profile.py", line 288, in find_subscriptions_in_vm_with_msi
    msi_creds = MSIAuthentication(resource=resource, msi_res_id=identity_id)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 689, in __init__
    self.set_token()
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 697, in set_token
    token_entry = self._vm_msi.get_token()
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 746, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry()
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 766, in _retrieve_token_from_imds_with_retry
    result = requests.get(request_uri, params=payload, headers={'Metadata': 'true', 'User-Agent':self._user_agent})
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01&msi_res_id=%2Fsubscriptions%2F55ac4ce5-f395-4dca-90bd-f92edcdd82b7%2Fresourcegroups%2Ftest-project-setup%2Fproviders%2FMicrosoft.ManagedIdentity%2FuserAssignedIdentities%2FHRC-API-Deployer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11047ce48>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az login --identity -u {}`

## Environment Summary
```
Darwin-18.2.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli                         2.0.62

```

**Comment by achandmsft** [comment] 2019-04-11 23:56
Hi @wordrak,
Thanks a lot for your bug report (and for using our new and improved az feedback mechanism!). Can you tell us a little bit more about what you are trying to accomplish here?  

Thanks,
Arun Chandrasekhar
Principal Program Manager
Azure Management Experience

**Comment by achandmsft** [comment] 2019-04-12 00:39
@wordrak How did you install the Azure CLI? Want to see if this is related to #9030.

**Comment by marstr** [comment] 2019-04-18 22:51
> @achandmsft says:
> @wordrak How did you install the Azure CLI? Want to see if this is related to #9030.

Stack trace indicates that the CLI is installed in the Homebrew Cellar.

However, the failure looks pretty different to me. This stack trace makes no mention of SSL failure, which leads me to believe it's not as likely to be about newtwork configuration.

**Comment by keremispirli** [comment] 2019-06-13 13:42
I have the same problem with a Windows VM on Azure. I'm pasting the "Feedback" here, instead of opening a new issue.

## Describe the bug

**Command Name**
`az login --identity`

**Errors:**
```
MSI: Failed to acquire tokens after 12 times
Traceback (most recent call last):
pip-install-dsvrkf2x\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 560, in execute
cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
cli\core\commands\__init__.py, ln 611, in _run_job
Temp\pip-install-dsvrkf2x\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 588, in _run_job
cli\core\commands\__init__.py, ln 297, in __call__
...
pip-install-dsvrkf2x\msrestazure\msrestazure\azure_active_directory.py, ln 584, in set_token
pip-install-dsvrkf2x\msrestazure\msrestazure\azure_active_directory.py, ln 632, in get_token
pip-install-dsvrkf2x\msrestazure\msrestazure\azure_active_directory.py, ln 674, in _retrieve_token_from_imds_with_retry
TimeoutError: MSI: Failed to acquire tokens after 12 times
```

## To Reproduce:
Run following command in an Azure VM with identity.
- `az login --identity`

## Expected Behavior
This command has been working in this VM since yesterday. Today it doesn't.

## Environment Summary
```
Windows-10-10.0.177
```

## Additional Info
When run with `--debug` flag, output looks like this:
```
urllib3.connectionpool : Starting new HTTP connection (1): 169.254.169.254:80
urllib3.connectionpool : http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 HTTP/1.1" 500 21
msrestazure.azure_active_directory : MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01'}
msrestazure.azure_active_directory : MSI: wait: 0.1s and retry: 1
urllib3.connectionpool : Starting new HTTP connection (1): 169.254.169.254:80
urllib3.connectionpool : http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 HTTP/1.1" 500 21
msrestazure.azure_active_directory : MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01'}
msrestazure.azure_active_directory : MSI: wait: 0.1s and retry: 2
...
```
Same command has following debug output when successful, in another VM with virtually identical configuration:
```
urllib3.connectionpool : Starting new HTTP connection (1): 169.254.169.254:80
urllib3.connectionpool : http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 HTTP/1.1" 200 1604
msrestazure.azure_active_directory : MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01'}
msrestazure.azure_active_directory : MSI: Token retrieved
MSI: token was retrieved. Now trying to initialize local accounts...
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.async_paging : Paging async iterator protocol is not available for SubscriptionPaged
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions?api-version=2016-06-01 HTTP/1.1" 200 347
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x033B1588>, <function _x509_from_base64_to_hex_transform at 0x033B15D0>]
Event: CommandInvoker.OnFilterResult []
[
  {
      //my account data
  }
]
...
```

**Comment by keremispirli** [comment] 2019-06-13 13:58
After costing a day of time, stopping and then starting the VM again solved the issue. Mind you that a reboot has not worked; had to Stop and then Start from the Azure web interface (deallocation and reallocation of the VM).

**Comment by marstr** [comment] 2019-06-13 19:59
Given that this is solved by a hard stop/start of the VM, I suspect this is an MSI issue, not a CLI issue. I'm going to close this out for now. @achandmsft, mind forwarding this issue on to the appropriate service team?

**Closed by marstr** 2019-06-13 19:59 UTC
Labels: Authentication

**Comment by alexeyzimarev** [comment] 2019-08-13 17:55
@marstr it cannot be an MSI issue, because the issue was originally reported on Mac, then on a Windows VM in Azure and I am now having the same issue on Ubuntu VM.
