### ISSUE TITLE
Could not create AKS ckuster from CLI

### ISSUE THREAD

**Issue by pinboro** [Azure/azure-cli#6862] opened 2018-07-21 04:04 UTC
**Describe the bug**
When creating a AKS cluster from the command line following the official guide, an error is returned and the cluster is not created.

https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough

**To Reproduce**

```
> az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all subscriptions you have access to...
[
  {
    "cloudName": "AzureCloud",
    "id": "sdfsdfsdfsd-sdfsdf-sdfs-sdfsdf-sdfsdfsdfsdfsdf",
    "isDefault": true,
    "name": "Microsoft Azure \u30a8\u30f3\u30bf\u30fc\u30d7\u30e9\u30a4\u30ba",
    "state": "Enabled",
    "tenantId": "sdfsdfsdf-1f30-sdfsdf-sdfsdf-sdfsdfsdfsd",
    "user": {
      "name": "sdfs@sdfsdf.com",
      "type": "user"
    }
  }
]

> az group create --name my-chart-group --location eastus
{
  "id": "/subscriptions/cc07cdf5-sdff-4abe-9718-2sdfb78ab03a/resourceGroups/my-chart-group",
  "location": "eastus",
  "managedBy": null,
  "name": "my-chart-group",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null
}

> az aks create --resource-group my-chart-group --name my-chart --node-count 3 --generate-ssh-keys
Deployment failed. Correlation ID: 43c1c6e2-sdfg-4f4f-907c-05cdad59c25e. VM has reported a failure when processing extension 'cse-agent-1'. Error message: "Enable failed: failed to execute command: command terminated with exit status=31
[stdout]

[stderr]
".
```

**Expected behavior**

Cluster is created successfully.

**Environment summary**

```
> az --version
azure-cli (2.0.42)

acr (2.1.0)
acs (2.2.0)
advisor (0.6.0)
ams (0.2.0)
appservice (0.2.0)
backup (1.2.0)
batch (3.3.0)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.0)
core (2.0.42)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.0)
extension (0.2.0)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.26)
iot (0.2.0)
keyvault (2.2.0)
lab (0.1.0)
maps (0.3.0)
monitor (0.2.0)
network (2.2.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.0)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.0)
resource (2.1.0)
role (2.1.0)
servicebus (0.2.0)
servicefabric (0.1.0)
sql (2.1.0)
storage (2.1.0)
vm (2.1.0)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/jb/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Jul 21 2018, 10:38:00) 
[Clang 9.1.0 (clang-902.0.39.1)]

Legal docs and information: aka.ms/AzureCliLegal
```
Installed with brew on Mac OS.

**Additional context**

n/a

**Comment by jluk** [comment] 2019-06-07 18:17
@pinboro this looks like it was a service issue at the time and not CLI specific - that hopefully is not reproducing anymore. If it is please feel free to reopen. @yugangw-msft can you please close this out?

**Closed** 2019-06-10 16:17 UTC
Labels: AKS, Question, Service Attention
