### ISSUE TITLE
`az login` hangs when connecting to login.microsoftonline.de

### ISSUE THREAD

**Issue by SetTrend** [Azure/azure-cli#24631] opened 2022-11-11 22:16 UTC
## Describe the bug

`az login` hangs.

I used different client machines at different locations (and network connections). They all show the same effect.

During my examinations I noticed that `az login` uses a German TLD when connecting to `login.microsoftonline.de` … That domain doesn't answer and that's the issue within `az login`.

## To Reproduce:

- use the following Azure CLI config file:
  [zipped config file (click here to download)](https://github.com/Azure/azure-cli/files/9993413/config.zip)
- hit `az login`
- wait …

## Expected Behavior

`az login` should display a login screen.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0
```

### `az login` – Fiddler log
![2 - az login – Fiddler log](https://user-images.githubusercontent.com/9283914/201438272-4aaaf87c-2fcb-4fd7-bd4a-c407be979d4f.png)

### Arbitrary other Microsoft websites are working/responding smoothly
![1 - az login – other sites are working](https://user-images.githubusercontent.com/9283914/201438265-2f1ef1ad-01c0-452c-9d21-d0f7305f995f.gif)

### `login.microsoftonline.de` – `tracert`
![3 - az login – tracert](https://user-images.githubusercontent.com/9283914/201438277-4cb3db6e-4ff8-4aab-9d61-ee43edd93d09.png)

**Comment by yonzhan** [comment] 2022-11-12 00:57
@jiasli for awareness

**Comment by jiasli** [comment] 2023-06-26 06:41
Duplicate of #23775

Nice GIF by the way. 😆

**Closed** 2023-06-26 06:42 UTC
Labels: Account, customer-reported, feature-request, Auto-Assign, Azure CLI Team
