### ISSUE TITLE
Run Az login command at WSL2

### ISSUE THREAD

**Issue by SNAKE169** [Azure/azure-cli#24151] opened 2022-10-11 08:02 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
'NoneType' object is not callable
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 811, in find_through_authorization_code_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
azure/cli/core/_profile.py, ln 853, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
azure/cli/core/_profile.py, ln 772, in create_arm_client_factory
    client = client_type(credentials, api_version=api_version,
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment] 2022-10-11 10:16
@jiasli for awareness

**Comment by bebound** [comment] 2022-10-12 09:04
Duplicate of https://github.com/Azure/azure-cli/issues/19640

**Closed by bebound** 2022-10-12 09:04 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
