### ISSUE TITLE
[SSH] - Unable to connect to App Service SSH through "az webapp ssh" command

### ISSUE THREAD

**Issue by garimpeirodouniverso** [Azure/azure-cli#12308] opened 2020-02-21 13:47 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Cannot connect to App Service SSH using "az webapp ssh" command. It states "Connection is not ready yet, please wait", and waits until times out.

**To Reproduce**
- log into our tenant in Azure Portal
- open cloud shell
- type the command "az webapp ssh --name [our-app-service-name] -g [our-resource-group-name]-rg -t 30"

**Expected behavior**
Connection on our App Service through SSH.

**Environment summary**
We are using Azure portal own CLI (azure-cli 2.1.0) and also DevOps task "AzureCLI@2", both failing to reach our App Services.

**Additional context**
We have several App Services into the same App Service Plan, none of which can be connected through the "az webapp ssh" command. We are able to connect the SSH via Azure Portal > App Service > SSH normally.
Until last week we could (although not consistently) connect using this command. Now we just cannot.

**Comment by yonzhan** [comment] 2020-02-22 03:56
webapp

**Comment by garimpeirodouniverso** [comment] 2020-03-06 23:37
Hi, any news? All connections set using "az webapp ssh" command are highly unstable, we just cannot rely on this command to connect to our App Service.

**Comment by panchagnula** [comment] 2020-03-10 06:46
@btardif can you please check with the Linux folks on this command please. Thanks.

**Comment by amasover** [comment] 2020-03-12 19:14
I see the same behavior as @garimpeirodouniverso, both running the CLI locally on my machine, and from Cloud Shell. I hadn't tried `az webapp ssh` before today, so I've never seen successful behavior. I also get a timeout error with `az webapp create-remote-connection`.

**Comment by dasumner** [comment] 2020-03-30 15:11
Has anybody had any insight regarding this topic?

**Comment by PandaonMars** [comment] 2020-04-18 01:19
I met the same issue. I was using CLI on VM machine. I could not access ssh from the terminal or from the website.

**Comment by siljemda** [comment] 2020-04-23 07:42
Currently seeing this in Web App for Containers.

**Comment by Acadomia** [comment] 2020-05-28 14:56
having the same issue when I use "--slot slotname" , I'm using osx.

**Comment by santhoshraj2960** [comment] 2021-03-10 03:45
any update yet?

**Comment by seligj95** [comment] 2021-07-07 14:10
Unable to reproduce bug. I was able to SSH via portal and CLI - insufficient details for further reproduction. closing this issue. FYI, this command is planned to be deprecated and replaced, timeline TBD.

**Closed by seligj95** 2021-07-07 14:10 UTC
Labels: Service Attention, Web Apps, customer-reported

**Comment by gagarine** [comment] 2021-07-28 12:08
@seligj95 I cannot connect from the portal neither from the CLI. It's a real bug. You can ask form extra information, but closing it like that is absurd.

What information do you need?

**Comment by seligj95** [comment] 2021-08-02 19:14
@gagarine Thank you for the feedback. We are aware of this instability associated with these commands and are prioritizing updates. As this was an old GH issue with few details that was unable to be reproduced, it was closed. 

However, if you're still experiencing issues, I am happy to help. Can you confirm if you are able to connect using the menu item in the screen shot below? That can be found by navigating to your App Service via the portal and looking under "Development Tools" in the menu on the left hand side.

![image](https://user-images.githubusercontent.com/11475594/127911442-f7b7c62d-30a4-4518-b89e-394d22537a42.png)

**Comment by gagarine** [comment] 2021-08-03 11:34
I wanted to say "Yes when the server is stable and running, yes (but still, unstable)" but I just tried it again, and it fails. Apparently now i had to disconnect from other Microsoft account otherwise it fail miserably:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/164074/128007526-29a80f43-b96e-4fe2-afab-ef899b862459.png">

Disconnecting from all other account was not enough, i had to "forget" them. Not great.

But when a project fail to deploy, then SSH become a nightmare. Certainly because the machine shutdown when not responding to ping. But if I try to ssh in, Azure should wake up the machine and stop trying to shut it down every 230 seconds... 

And certainly it is linked with Microsoft multiple account, but regularly I have problem with authorization and get red cryptic message at the bottom of the web SSH windows...

And once you are finally connected, you end up with one of the worst "web ssh" I ever experienced. Even line return is broken : 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/164074/128008593-54be9b7c-62c0-401d-bb26-c0fa12afca08.png">
