### ISSUE TITLE
Unable to load extension 'webapp'. sku = sku.upper() AttributeError: 'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by KarthikaSeenivasa** [Azure/azure-cli#11183] opened 2019-11-11 15:26 UTC
Unable to load extension 'webapp'. Use --debug for more information.
webapp aimauditing doesn't exist
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'

## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/custom.py, ln 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
cli/command_modules/appservice/custom.py, ln 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
cli/command_modules/appservice/utils.py, ln 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --location {} --name {}`

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

Extensions:
webapp 0.2.16

```

**Comment by KarthikaSeenivasa** [comment] 2019-11-11 15:33
I referred that issue https://github.com/Azure/azure-cli/pull/11104 still open. Can you please let me know the alternative way of hosting?

**Comment by Juliehzl** [comment] 2019-11-12 02:34
dupe of #11100

**Comment by Juliehzl** [comment] 2019-11-12 02:37
This issue has been fixed but will deployed only with the next release please use 2.0.75 for now pip install azure-cli==2.0.75

**Comment by KarthikaSeenivasa** [comment] 2019-11-12 04:39
Thanks for the quick support.

**Comment by KarthikaSeenivasa** [comment] 2019-11-13 13:47
I am getting below error when executing 'pip install azure-cli==2.0.75'

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/azure_mgmt_signalr-0.3.0.dist-info'
Consider using the `--user` option or check the permissions.

**Comment by panchagnula** [comment] 2019-11-14 16:47
Fixed by https://github.com/Azure/azure-cli/pull/11019

**Closed by panchagnula** 2019-11-14 16:47 UTC
Labels: Service Attention, Web Apps

**Comment by viswanath27** [comment] 2019-11-16 01:01
In cloud shell we are not able to install, as it would be needing root permissions. I tried installing in my local machine (azure-cli=2.0.75). It had installed successfully but getting below error. when I enter `az login`

`: /usr/bin/python: No module named azure`
