### ISSUE TITLE
_az login_ failure: The ID token is not yet valid.

### ISSUE THREAD

**Issue by msnyder1-insight** [Azure/azure-cli#21258] opened 2022-02-11 16:18 UTC
# Notes Prologue:

- Using Linux 2.32.0 CLI package upon encountering this failure.  Rebuilt environment to get updates (found 2.33.0 available), but issue persists.
- Zero changes in 24 hour span where it worked at the beginning of the interval, and failed at the end of the interval.
  - using version 2.32.0 at both ends of the cited span.
  - was in the same shell session for the entire timespan as well.

# Environment Detail:
```
# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1644589899.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/6c637512-c417-4e78-9d62-b61258e4b619/v2.0",
  "iat": 1644595286,
  "nbf": 1644595286,
  "exp": 1644599186,
  "aio": "AVQAq/8TAAAA7eC4JK/ZbkVSMG29HsLq78Zqua7RhwsrxVkHy/yO/e44wc2t0xbTKCTXPGgBw0VCD56Ch7BBiONLfakU/weEm87aN+ekWfuNm56vkqOQGes=",
  "name": "[redacted]",
  "oid": "b762c883-52ed-4004-92f9-b989c17e7c10",
  "preferred_username": "[redacted]",
  "puid": "10032000D51A063B",
  "rh": "0.AScAEnVjbBfEeE6dYrYSWOS2GZV3sATbjRpGu-4C-eG_e0YnAB4.",
  "sub": "wvft6qK9Ikig0QfR2qEXmdOJHQTMs9oEMCZYLvhfREE",
  "tid": "6c637512-c417-4e78-9d62-b61258e4b619",
  "uti": "yU9sE65ghUabUf5ZKFEfAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 153, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 182, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/opt/azure-cli/lib/python3.9/site-packages/msal/application.py", line 1608, in acquire_token_by_device_flow
    response = _clean_up(self.client.obtain_token_by_device_flow(
  File "/opt/azure-cli/lib/python3.9/site-packages/msal/oauth2cli/oauth2.py", line 384, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/opt/azure-cli/lib/python3.9/site-packages/msal/oauth2cli/oauth2.py", line 346, in _obtain_token_by_device_flow
    result = self._obtain_token(
  File "/opt/azure-cli/lib/python3.9/site-packages/msal/oauth2cli/oidc.py", line 11

**Comment by msnyder1-insight** [comment] 2022-02-11 18:16
Working through this, I've regained functionality through rebooting my environment.  I now suspect that this may have been caused by a stale web credential/authentication.  In the work I'm doing, I'm using the "az login" interaction with a web browser that produces the following message:
```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
```
My web credential was authenticated much more than 24 hours prior to experiencing this error.  The error seems to have now cleared with the full environment reboot, and making fresh authentications in Azure via the browser.

If triage/review makes further pursuit desirable, I'm very happy to execute test cases against my use case.

**Comment by yonzhan** [comment] 2022-02-12 01:03
@jiasli for awareness

**Comment by jiasli** [comment] 2022-02-14 03:41
Duplicate of #20388

**Closed by jiasli** 2022-02-14 03:41 UTC
Labels: Account, customer-reported
