### ISSUE TITLE
az aks get-credentials fails when env:KUBECONFIG is set with windows paths

### ISSUE THREAD

**Issue by crowne** [Azure/azure-cli#22321] opened 2022-05-09 17:11 UTC
## Describe the bug
`az aks get-credentials` fails when env:KUBECONFIG is set with windows paths

**Command Name**
`az aks get-credentials`

**Errors:**
```
Merged "ss-locn-dev-tst-aks001" as current context in C
```

## To Reproduce:
When the environment variable KUBECONFIG is set to
- %USERPROFILE%\.kube\config;%USERPROFILE%\.kube\k8stest.config
or
- %USERPROFILE%\.kube\config
`az aks get-credentials` fails but produces truncated output as follows -
`Merged "ss-locn-dev-tst-aks001" as current context in C`

If I change environment variable KUBECONFIG to
- ~/.kube/config

Then the command finishes successfully and the config file is produced successfully output is as follows:
`Merged "ss-locn-dev-tst-aks001" as current context in ~/.kube/config`  

However `kubectl config get-contexts` only lists the Azure hosted cluster and not my local or vmware hosted cluster.

if I then change environment variable KUBECONFIG back to 
- %USERPROFILE%\.kube\config;%USERPROFILE%\.kube\k8stest.config
Then `kubectl config get-contexts` lists all of the contexts correctly

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Expected Behavior
Ideally I would like to be able to use `az aks get-credentials` to produce a standalone config file without merging,
and then be able to append the new config file path to the KUBECONFIG environment variable.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"8211ae4d6757c3fedc53cd740d163ef65287276a", GitTreeState:"clean", BuildDate:"2022-03-31T20:28:03Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yonzhan** [comment] 2022-05-09 22:40
route to CXP team

**Comment by navba-MSFT** [comment] 2022-05-13 04:22
@crowne You shouldn't embed unresolved environment variables in your $KUBECONFIG, which is what it looks like you've done. %foo% is effectively proprietary to cmd.exe, it isn't a special notation for most apps (even PowerShell handles environment variables with $env:<whatever>, e.g.) -- you'll need to pre-expand your $USERPROFILE and set $KUBECONFIG to a resolved path, and I suspect that will work fine. Could you please try this plan and let me know if that works fine ?

Alternatively, You can add --file or -f to output to a separate file:

>az aks get-credentials --resource-group rgAksClusters --name MyAKScluster --file mynewconfig
Merged "MyAKScluster" as current context in mynewconfig

Hope this helps.

**Comment by crowne** [comment] 2022-05-16 09:01
Thanks the --file option works great, even with the env vars set as above.

The environment variables aren't unresolved, Windows resolves them before the Powershell is created.  
```
→ C:\Users\user.name› dir env:KUB*

Name                           Value
----                           -----
KUBECONFIG                     C:\Users\user.name\.kube\config;C:\Users\user.name\.kube\azdevtst.config;C:\Users\user.name\.kube\k8stest.config
```

I can confirm that if I run the command  
`az aks get-credentials --resource-group ss-locn-dev-tst-rg --name ss-locn-dev-tst-aks001`
without the --file option and with the KUBECONFIG env var set to 
- C:\Users\user.name\.kube\config;C:\Users\user.name\.kube\azdevtst.config;C:\Users\user.name\.kube\k8stest.config
or
- C:\Users\user.name\.kube\config

Then the config file in ~/.kube is not created.
The output of the command is 
```
Merged "ss-locn-dev-tst-aks001" as current context in C
```

I also just noticed that a the context info was actually written to a file called `C` in my home dir.
-  `C:\Users\user.name\C`

So it looks like the `az` command isn't interpreting the windows path in the environment variable correctly,
and is treating the colon in C: as a delimiter.

**Comment by navba-MSFT** [comment] 2022-05-17 04:19
@crowne I wasn't able to reproduce this issue as it worked fine for me. Sharing the below details if that helps:

![image](https://user-images.githubusercontent.com/57353862/168727856-60486e0d-c65b-45e2-b3fc-239ab9f9efe6.png)


![image](https://user-images.githubusercontent.com/57353862/168727701-c533ea69-f92b-48ee-ab3c-7a97bf10e0b6.png)

Sharing my Azure CLI version too if you would like to test with older version (2.35.0) and check if that helps. Awaiting your reply.

PS C:\windows\system32> az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.69"
  }
}

**Comment by navba-MSFT** [comment] 2022-05-20 04:01
@crowne I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by crowne** [comment] 2022-05-20 10:21
Hi, thanks for your help.
The --file option which you mentioned has helped me work around the issue,
So I'm happy with the way things are for now.

**Comment by navba-MSFT** [comment] 2022-05-20 10:24
@crowne Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Closed by navba-MSFT** 2022-05-20 10:24 UTC
Labels: AKS, customer-reported, CXP Attention, Auto-Assign
