### ISSUE TITLE
The "az keyvault create" and "az keyvault delete" links do not work

### ISSUE THREAD

**Issue by eugen-nw** [Azure/azure-cli#18782] opened 2021-07-08 20:06 UTC
I'd expect them to take me to the content below, but they did not do anything.  I tried both on Chrome and Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/keyvault.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/keyvault.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2021-07-09 00:00
keyvault

**Comment by evelyn-ys** [comment] 2021-07-09 08:07
@eugen-nw Which link do you mean?

**Comment by jiasli** [comment] 2021-07-09 09:48
Duplicate of https://github.com/Azure/azure-cli/issues/18764

**Closed by jiasli** 2021-07-09 09:48 UTC
Labels: Documentation, KeyVault
