### ISSUE TITLE
AZ Login Suddenly stopped working

### ISSUE THREAD

**Issue by HossamAmer12** [Azure/azure-cli#25903] opened 2023-03-21 16:00 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```
![image](https://user-images.githubusercontent.com/13424646/226667345-1a641b15-6797-49b6-a37f-11eba3396639.png)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.46.0

Extensions:
resource-graph 2.1.0
azure-devops 0.26.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2023-03-21 23:04
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2023-03-21 23:04 UTC
Labels: Account, Graph, customer-reported, Auto-Assign
