### ISSUE TITLE
Failed to establish a new connection: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by makokui** [Azure/azure-cli#9515] opened 2019-05-30 12:53 UTC
It regularly execute Azure CLI commands from Azure Virtual Machine (REL 7).. It had been stable for a while, but recently errors sometimes occur. Please tell me how to avoid this error.

- Batch command
/bin/az monitor metrics list --resource /subscriptions/xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.Cache/Redis/xxxxx --start-time yyyy-mm-ddTnn:nn:nnZ --end-time yyyy-mm-ddTnn:nn:nnZ --metrics cachehits,cachemisses,cacheRead,cacheWrite,connectedclients,percentProcessorTime,evictedkeys,expiredkeys,getcommands,operationsPerSecond,serverLoad,setcommands,totalkeys,totalcommandsprocessed,usedmemory,usedmemoryRss -o table

- Error detail
ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /xxxxxxxxxxxxxxxxxxx/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x43ac350>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by tjprescott** [comment] 2019-05-30 14:57
@makokui  are you on the Redis Cache service team? This issue template is for service teams to request the CLI team to add features.

**Comment by adewaleo** [comment] 2019-05-30 21:29
@makokui is your issue with a `redis`command or with `az monitor metrics list`

@makokui for bugs please use the template [here](https://github.com/Azure/azure-cli/issues/new?template=Bug_report.md):

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by makokui** [comment] 2019-05-31 14:04
@adewaleo my issue with a az monitor metrics list, and this issue is occurring in user's environment. I am waiting for information from the user. I will file a bug report as soon as I can confirm the execution environment.

**Comment by tjprescott** [comment] 2019-05-31 14:50
If you are getting flaky behavior with the `monitor metrics list` command, that would be a service issue. You would likely want to escalate your scenario by opening a ticket on the portal.

However, looking at your command, you should not be providing comma-separated metrics.  

```
--metrics             : Space-separated list of metric names to retrieve.  Values from: az
                            monitor metrics list-definitions.
```

So this:
```
 --metrics cachehits,cachemisses,cacheRead,cacheWrite,connectedclients,percentProcessorTime,evictedkeys,expiredkeys,getcommands,operationsPerSecond,serverLoad,setcommands,totalkeys,totalcommandsprocessed,usedmemory,usedmemoryRss
```
should be:
```
 --metrics cachehits cachemisses cacheRead cacheWrite connectedclients percentProcessorTime evictedkeys expiredkeys getcommands operationsPerSecond serverLoad setcommands totalkeys totalcommandsprocessed usedmemory usedmemoryRss
```

**Comment by MyronFanQiu** [comment] 2019-09-02 03:27
@makokui Hello. Is this issue solved?

**Comment by MyronFanQiu** [comment] 2019-12-31 06:06
@makokui Hello. Since this issue is out of date. I will close this issue. Don't hesitate and feel free to open a new one if you still meet any problem.

**Closed by MyronFanQiu** 2019-12-31 06:06 UTC
Labels: Monitor-cli, Service Attention
