### ISSUE TITLE
Azure CLI issue : raise error, v # invalid expression while creating nic interface or getting pulic-ip list using azure-cli

### ISSUE THREAD

**Issue by darshit95** [Azure/azure-cli#10701] opened 2019-09-30 18:49 UTC
## Describe the bug

**Command Name**
`az network public-ip list`

**Errors:**
```
nothing to repeat
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 291, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 290, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
bin/lib64/python2.7/re.py, ln 190, in compile
    return _compile(pattern, flags)
bin/lib64/python2.7/re.py, ln 242, in _compile
    raise error, v # invalid expression
error: nothing to repeat
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network public-ip list`

## Environment Summary
```
Linux-2.6.32-696.30.1.el6.x86_64-x86_64-with-centos-6.10-Final
Python 2.7.5
Shell: bash

azure-cli 2.0.74

Extensions:
virtual-wan 0.1.0

```

**Comment by MyronFanQiu** [comment] 2019-10-01 05:09
@darshit95 Thanks. I will take a look at this issue.

**Comment by MyronFanQiu** [comment] 2019-11-19 04:22
@darshit95 Hello. Sorry for the delay due to low bandwidth. I cannot reproduce the error. Do you still meet this error now?

**Comment by MyronFanQiu** [comment] 2019-11-25 02:43
Close this issue since I cannot reproduce it. Do not hesitate and feel free to re-open it if you meet any problem again.

**Closed by MyronFanQiu** 2019-11-25 02:43 UTC
Labels: Network
