### ISSUE TITLE
[Extensions] "Blessed" Extensions should not trigger warnings when overriding existing commands

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4712] opened 2017-10-18 22:24 UTC
As discussed via email, official or "blessed" extensions should suppress the warning about overriding the default implementation.

**Comment by digimaun** [comment] 2017-10-18 22:31
Thanks for creating the issue we discussed @tjprescott. The IoT extension can be a guinea pig for blessing criteria.

**Comment by troydai** [comment] 2017-10-19 21:23
The difficulty of assigning an extension the 'blessed' status is that there is no way to verify the identity of an extension. We don't sign the extension.

**Comment by derekbekoe** [comment] 2017-10-19 21:32
With an extension index, we could have control over such blessed extensions.

**Comment by JasonRShaver** [comment] 2018-08-08 22:01
Currently this is by design, especially given the relative scope of extensions.  As the CLI grows, we'll revisit this to setup some healthy and secure patterns here.  If you have any user data or complains, please share with us to help us prioritize.

**Comment by jongio** [comment] 2018-10-30 18:33
@johanste - The message is pretty intimidating and for the IoT extension, we'd like to have something more friendly or nothing at all.  Can we revisit this?

**Comment by yonzhan** [comment] 2019-12-23 03:03
add to S165.

**Comment by jiasli** [comment] 2020-03-26 10:08
We have added option `--only-show-errors` in #12604 to disable warnings that are written to `stderr`. It will be included in [S167](https://github.com/Azure/azure-cli/milestone/84) release.

**Closed by jiasli** 2020-03-26 10:08 UTC
Labels: Discussion, Extensions, Feature Request
