### ISSUE TITLE
Public IPv6 address retruned as null

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#3000] opened 2017-04-26 12:22 UTC
az --version is 2.0.3

az network public-ip list retrieves Public IP addresses but those enabled for IPv6 show up as null.  Below is the output.

{
    "dnsSettings": null,
    "etag": "W/\"0dbc0843-57f0-4bce-8e60-3e46813378d6\"",
    "id": "/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/resourceGroups/IPv6v2/providers/Microsoft.Network/publicIPAddresses/LBIPv6PubAddressvw4konls2vfbw0",
    "idleTimeoutInMinutes": 4,
    "ipAddress": null,
    "ipConfiguration": {
      "etag": null,
      "id": "/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/resourceGroups/IPv6v2/providers/Microsoft.Network/loadBalancers/IPv6v4LBvw4konls2vfbw0/frontendIPC
onfigurations/XRELoadBalancerFrontEndIPv6",
      "name": null,
      "privateIpAddress": null,
      "privateIpAllocationMethod": null,
      "provisioningState": null,
      "publicIpAddress": null,
      "resourceGroup": "IPv6v2",
      "subnet": null
    },
    "location": "centralus",
    "name": "LBIPv6PubAddressvw4konls2vfbw0",
    "provisioningState": "Succeeded",
    "publicIpAddressVersion": "IPv6",
    "publicIpAllocationMethod": "Dynamic",
    "resourceGroup": "IPv6v2",
    "resourceGuid": "a4b819aa-4963-4775-94c5-9d2222a5e389",
    "tags": null,
    "type": "Microsoft.Network/publicIPAddresses"
  }

**Comment by jbrozena22** [comment] 2017-05-24 12:03
same issue here. Seems to happen randomly because worked when I tried creating a new one.

**Comment by tjprescott** [comment] 2017-05-24 15:48
The service does not return a value for the IP address, and that is why it is deserialized to `null`. @markjbrown, is this is expected behavior?

**Comment by jbrozena22** [comment] 2017-05-24 15:52
After more digging on my end I realized I was wrong in my prior report, or at least it was not the cause of the problem. I was getting a resource not found error for a NIC I had made, which led me to look into the components of the NIC, public IP included. It seemed odd that the IP was null, leading me to believe it was the culprit. However, now I believe you are right, it doesn't get assigned an IP until later when actually attached to a VM perhaps?

Either way, I resolved my problem because the error had more to do with using the wrong region (server template specified eastus, but NIC was located in southcentralus leading to the resource not found error).

Thanks.

**Comment by markjbrown** [comment] 2017-05-24 17:09
Yes, that's correct. The IP Address doesn't get assigned until its either associated to the VM for the NIC it's attached to or to a Load Balancer.

**Comment by markjbrown** [comment] 2017-05-24 17:20
Is this resolved? Can it be closed?

**Comment by tjprescott** [comment] 2017-05-24 17:44
When I create an IPv6 public IP and then create a VM using that IP, the value that displays for that public IP is an IPv4 address:

```
 {
    "ipAddress": "13.64.184.227",
    "ipConfiguration": {
      "etag": null,
      "id": "/subscriptions/xxxxx/resourceGroups/tjp-ip/providers/Microsoft.Network/networkInterfaces/vm1VMNic/ipConfigurations/ipconfigvm1",
      "privateIpAddress": null,
      "privateIpAllocationMethod": null,
      "provisioningState": null,
      "publicIpAddress": null,
      "resourceGroup": "tjp-ip",
      "subnet": null
    },
    "location": "westus",
    "name": "ip1",
    "provisioningState": "Succeeded",
    "publicIpAddressVersion": "IPv6",
    "publicIpAllocationMethod": "Dynamic",
    "resourceGroup": "tjp-ip",
    "resourceGuid": "3f3e3ef6-17fa-4ecd-907f-e93f631b92be",
    "tags": null,
    "type": "Microsoft.Network/publicIPAddresses"
  }
```

**Comment by Teodelas** [comment] 2017-05-24 19:31
As far as I know IPv6 addresses can / should only be assigned to load balancers.  VM's don't yet support native IPv6 addresses.  But I'm no longer seeing the issue:
{
    "dnsSettings": null,
    "etag": "W/\"dcc7a9ac-75b3-4fbc-8729-597be38dae5c\"",
    "id": "/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/resourceGroups/IPv6/providers/Microsoft.Network/publicIPAddresses/XREMemcacheLBIPv6PubAddress45ekwzeohxvjm1",
    "idleTimeoutInMinutes": 4,
    "ipAddress": "2603:1030:7::547",
    "ipConfiguration": {
      "etag": null,
      "id": "/subscriptions/fed7f475-6055-4e3c-8529-c1345df70589/resourceGroups/IPv6/providers/Microsoft.Network/loadBalancers/IPv6v4LBMemcache45ekwzeohxvjm1/frontendIPConfigurations/XREMemcacheLoadBalancerFrontEndIPv6",
      "name": null,
      "privateIpAddress": null,
      "privateIpAllocationMethod": null,
      "provisioningState": null,
      "publicIpAddress": null,
      "resourceGroup": "IPv6",
      "subnet": null
    },

**Comment by markjbrown** [comment] 2017-05-24 19:42
Our announcement last September was for native IPv6 for VM's so we do support it.

@tjprescott I'm researching this now. I've recreated this and also cannot find how to query for the v6 address. Will revert back once I get an answer.

**Comment by Teodelas** [comment] 2017-05-24 20:03
Right.  But you can't assign a public IPv6 address directly to a VM (or you shouldn't be able to).  The 'right' way for the VM to get an IPv6 address (today) is through DHCP.  The IPv6 communication / connectivity to other IPv6 addresses is through the LB.

**Comment by markjbrown** [comment] 2017-05-24 20:36
So I talked to some folks and you do indeed can only do this as a Public IP for a Load Balancer.

See the article here. In particular the "details" section and limitations. Including the DHCP assigned IPv6 address for the VMs.
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ipv6-overview

sorry for the confusion. I was also under the impression that we enabled this directly on the VM's, meaning you could assign it directly as we announced it as providing "native" IPv6 support for VM's. The support is correct but the how to get there was a bit more nuanced.

thanks.

**Comment by tjprescott** [comment] 2017-05-24 21:16
In light of this, I'm closing this issue.

**Closed by tjprescott** 2017-05-24 21:16 UTC
Labels: Network, ServiceAttn

**Comment by rccueva** [comment] 2018-05-08 18:13
Please, I have not ip address
![ipv6](https://user-images.githubusercontent.com/26943106/39774791-8b09ede8-52c1-11e8-922d-622a7c1c1919.png)

Whats wrong..?

**Comment by ameetkonnur** [comment] 2018-07-08 06:32
same issue as @rccueva dont see the private ipv6 address for the VM. Any fixes ?

**Comment by tjprescott** [comment] 2018-07-09 14:21
According to the Networking team, there is nothing to fix. IPv6 address is not for the VM itself but for the load balancer.  
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ipv6-overview
