### ISSUE TITLE
Create MySQL database does not honor location from resource group

### ISSUE THREAD

**Issue by ingnil** [Azure/azure-cli#7896] opened 2018-11-21 10:00 UTC
Why does "az mysql server create" not use the location from the resource group? I had to set the default location manually, despite specifying resource group (which has a location) on the command line.

Many other Azure CLI commands infer the location from the resource group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667a3da9-f15a-680b-b749-eacba058a80d
* Version Independent ID: 702910fa-69c9-df0d-1cc0-9f5664702ed3
* Content: [az mysql server](https://docs.microsoft.com/en-us/cli/azure/mysql/server?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/mysql/server.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/mysql/server.yml)
* Service: **mysql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment] 2018-11-21 14:53
Duplicate of #7035.

**Closed by tjprescott** 2018-11-21 14:53 UTC
