### ISSUE TITLE
[Test] Tests written with older test base will no longer record

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3896] opened 2017-06-27 16:10 UTC
After my changes to the resource module, I decided to wipe the recordings and simply re-record all tests. However, upon doing so, I found that, after recent changes, tests written using the old test base (VCRTestBase) will no longer record when played back using:

`nosetests azure.cli.command_modules.resource.tests.test_resource.ResourceGroupNoWaitScenarioTest -c nose.cfg`

As a result, the test passed (it ran live but didn't record) and then failed on CI.  This leaves me with two options:

1. Convert all of the tests to the new test base (did for a few)
2. Restore the old recording (finally resorted to this)

Considering the plan is for the live tests suite to update the recordings, this is a major bug since only tests that have the new base will work.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:  azure-cli (2.0.9+dev)

acr (2.0.7+dev)
acs (2.0.9+dev)
appservice (0.1.9+dev)
batch (3.0.2+dev)
billing (0.1.2+dev)
cdn (0.0.5+dev)
cloud (2.0.5+dev)
cognitiveservices (0.1.5+dev)
component (2.0.6+dev)
configure (2.0.9+dev)
consumption (0.1.2+dev)
core (2.0.10+dev)
cosmosdb (0.1.9+dev)
dla (0.0.9+dev)
dls (0.0.9+dev)
feedback (2.0.5+dev)
find (0.2.5+dev)
interactive (0.3.5+dev)
iot (0.1.8+dev)
keyvault (2.0.7+dev)
lab (0.0.7+dev)
monitor (0.0.7+dev)
network (2.0.9+dev)
nspkg (3.0.0+dev)
profile (2.0.7+dev)
rdbms (0.0.4+dev)
redis (0.2.6+dev)
resource (2.0.9+dev)
role (2.0.7+dev)
sf (1.0.4+dev)
sql (2.0.6+dev)
storage (2.0.9+dev)
taskhelp (0.1.4+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.9+dev)

Python (Windows) 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here: Win10CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by troydai** [comment] 2017-06-27 17:56
top priority.

**Comment by tjprescott** [comment] 2017-07-19 22:08
@troydai ping.  Just ran into this again today--but now I can't just restore the old recording.

**Comment by troydai** [comment] 2017-07-20 16:14
I'll take a look at this today.

**Comment by troydai** [comment] 2017-07-21 15:57
Close as the issue is addressed in https://github.com/Azure/azure-cli/pull/4058. If you notice any other malfunction, please feel free to open a new issue or reopen this one.

**Closed by troydai** 2017-07-21 15:57 UTC
Labels: bug, Infrastructure, Test
