### ISSUE TITLE
webapp: Way to get 'Custom Domain Verification ID' for web app

### ISSUE THREAD

**Issue by jonsamwell** [Azure/azure-cli#14142] opened 2020-06-30 04:29 UTC
I need a way to get the `Custom Domain Verification ID` of a web app so that I can automate binding a custom host name.

![image](https://user-images.githubusercontent.com/3694497/86083529-dad2ac80-badd-11ea-9652-cf7d3db9d7a7.png)

I've looked through all the documentation and methods exposed on `az webapp` but I am unable to find a way to get the verification id which I can use to add a TXT record to an Azure DNS zone then bind the custom host name without performing the verification step manually.

This is a big hole in our environment creation process we would like to automate.

Sorry if I missed anything!  

Thanks!

**Comment by yungezz** [comment] 2020-06-30 05:09
routing to appropriate team to help look if it's a feature reqeust or doc issue

**Comment by peter-dolkens** [comment] 2020-07-06 03:35
@jonsamwell there's some older methods which still work - I was hoping to move to this new TXT based record too, but unfortunately we're stuck using CNAMEs for now.

Instead, you can create an extra `awverify` record as follows:

```
CNAME awverify.yourdns.com => awverify.web-app-name.azurewebsites.net
CNAME yourdns.com => web-app-name.azurewebsites.net
```

Note: this additional `awverify` record is only needed if you're unable to point `yourdns.com` directly at your website immediately. The `awverify` record allows you to add the binding ahead of time, or alternatively, if you have a proxy (e.g. Cloudflare) in front, the `awverify` record removes the requirement for a direct CNAME binding all together.

**Comment by panchagnula** [comment] 2020-07-22 03:35
@peter-dolkens we need the Python SDK updated with this new property for CLI to expose this. We are working on it.  this got added to the rest-api-sepc as a part of this https://github.com/Azure/azure-rest-api-specs/pull/10117 we will get the SDK updated & released soon. Adding  tentative ETA to the milestone tag to track this.

**Comment by ericsampson** [comment] 2020-08-13 14:25
@panchagnula does someone have a ticket to add it to the go SDK?

**Comment by panchagnula** [comment] 2020-08-13 16:41
@ericsampson don't have a firm ETA but next week (if all goes as planned) we should be able to release a new Python SDK that should have this property after which we can work on incorporating this to azure-cli

**Comment by ericsampson** [comment] 2020-08-13 17:22
@panchagnula I was asking not about azure-clie but about the GO SDK because that's what's used by Terraform - looks like the go SDK work is inflight here so I'm good: https://github.com/Azure/azure-sdk-for-go/issues/12160
Thanks!

**Comment by panchagnula** [comment] 2020-08-13 17:51
Got it @ericsampson I am not the right person to talk about GO SDK - since I mainly work on CLI - but I can make sure GO SDK gets released once the python SDK is released as well.

**Comment by SupriyaGangineni** [comment] 2020-08-19 16:46
Hi,

You can use the Azure Resource Graph to achieve this. https://docs.microsoft.com/en-us/azure/governance/resource-graph/overview

If you are using CLI, you can get the Custom Verification ID of Azure App Service with following commands.

az extension add --name resource-graph
az graph query -q "Resources | project name,  properties.customDomainVerificationId, type | where type == 'microsoft.web/sites'"

Thanks,
Supriya.

**Comment by Bunzab** [comment] 2020-09-16 15:44
Is there an ETA for this being released in the CLI?

**Comment by panchagnula** [comment] 2020-09-25 03:34
still waiting for Python SDK to be published.

**Comment by brandonwittwer** [comment] 2020-10-01 14:37
Notably, the domain verification id is the same for all app services on the same subscription.  the following query gives you a list of all subscriptions you have access to.

`
az graph query -q "Resources | join kind=leftouter (ResourceContainers | where type=='microsoft.resources/subscriptions' | project SubName=name, subscriptionId) on subscriptionId | where type == 'microsoft.web/sites'| project vid = tostring(properties.customDomainVerificationId), SubName | distinct *"
`

**Comment by panchagnula** [comment] 2020-10-14 19:50
Moving this to next sprint since we need the new SDK with latest API Version to support this property

**Comment by aarsan** [comment] 2020-12-03 21:44
Is this ID set dynamically when the first App Service is created or is it possible to know what this ID is prior to deploying the first App Service? @brandonwittwer

**Comment by PabloJomer** [comment] 2021-06-18 06:33
@aarsan I want to know the same thing. Is it possible to get the id without a website?

Kindly,
Pablo

**Comment by panchagnula** [comment] 2021-06-18 08:09
> @aarsan I want to know the same thing. Is it possible to get the id without a website?
> 
> Kindly,
> Pablo

Nope this value can be used for app service only so which means you need a webapp/function app.

Also, this value is already added as part of new SDK update change released a while back.

**Closed by panchagnula** 2021-06-18 08:09 UTC
Labels: Service Attention, Web Apps, customer-reported, question

**Comment by PabloJomer** [comment] 2021-06-18 08:48
> > @aarsan I want to know the same thing. Is it possible to get the id without a website?
> > Kindly,
> > Pablo
> 
> Nope this value can be used for app service only so which means you need a webapp/function app.
> 
> Also, this value is already added as part of new SDK update change released a while back.

@panchagnula From what I can see the custom domain name verification id is unique for a subscription so two webapps within the same subscription would use the same id. In our use case it would be valuable to be able to get the id from the subscription without having to create a webapp/functionapp first. That way we could setup the infrastructure in one step and keep all our settings as code, without manual steps.

I understand we could create a fake webapp to retrive the id but it seems suboptimal and is exactly the kind of thing you want to avoid with infrastructure as code.

Could we open a new ticket to allow this to be retrieved some way directly from the subscription? 

Kindly,
Pablo

**Comment by panchagnula** [comment] 2021-06-18 08:52
> > > @aarsan I want to know the same thing. Is it possible to get the id without a website?
> > > Kindly,
> > > Pablo
> > 
> > 
> > Nope this value can be used for app service only so which means you need a webapp/function app.
> > Also, this value is already added as part of new SDK update change released a while back.
> 
> @panchagnula From what I can see the custom domain name verification id is unique for a subscription so two webapps within the same subscription would use the same id. In our use case it would be valuable to be able to get the id from the subscription without having to create a webapp/functionapp first. That way we could setup the infrastructure in one step and keep all our settings as code, without manual steps.
> 
> I understand we could create a fake webapp to retrive the id but it seems suboptimal and is exactly the kind of thing you want to avoid with infrastructure as code.
> 
> Could we open a new ticket to allow this to be retrieved some way directly from the subscription?
> 
> Kindly,
> Pablo

I don't understand the ask - the customDomainVerficationId can be used for AppService only so if you have a sub but no webapp resources, what is the purpose of using this DomainVerficationId - since this an AppServicePlan concept, will need a webapp resource. Sorry by design & at this point won't be associated with Subscription alone. i.e you need atleast one webapp associated with a resource to use this.

**Comment by PabloJomer** [comment] 2021-06-18 09:01
> > > > @aarsan I want to know the same thing. Is it possible to get the id without a website?
> > > > Kindly,
> > > > Pablo
> > > 
> > > 
> > > Nope this value can be used for app service only so which means you need a webapp/function app.
> > > Also, this value is already added as part of new SDK update change released a while back.
> > 
> > 
> > @panchagnula From what I can see the custom domain name verification id is unique for a subscription so two webapps within the same subscription would use the same id. In our use case it would be valuable to be able to get the id from the subscription without having to create a webapp/functionapp first. That way we could setup the infrastructure in one step and keep all our settings as code, without manual steps.
> > I understand we could create a fake webapp to retrive the id but it seems suboptimal and is exactly the kind of thing you want to avoid with infrastructure as code.
> > Could we open a new ticket to allow this to be retrieved some way directly from the subscription?
> > Kindly,
> > Pablo
> 
> I don't understand the ask - the customDomainVerficationId can be used for AppService only so if you have a sub but no webapp resources, what is the purpose of using this DomainVerficationId - since this an AppServicePlan concept, will need a webapp resource. Sorry by design & at this point won't be associated with Subscription alone. i.e you need atleast one webapp associated with a resource to use this.

We setup our infrastructure (functionapp & other resources) via a bicep/ARM template. In the bicep template we bind the custom hostname to the functionapp but this requires that we have already added the records with our DNS provider. Thus we a way to retrieve the record values and set these with our DNS provider before setting up our infrastructure. 

Kindly,
Pablo

**Comment by JohnDelisle** [comment] 2022-01-10 22:42
> We setup our infrastructure (functionapp & other resources) via a bicep/ARM template. In the bicep template we bind the custom hostname to the functionapp but this requires that we have already added the records with our DNS provider. Thus we a way to retrieve the record values and set these with our DNS provider before setting up our infrastructure. Since it's not possible to get the value from the subscription alone this means we would have to create a webapp use the cli to get the id and then destroy the webapp. If we want to automate the task. Since the value is unique for the subscription alone it feels like it would be better for everyone if it could be retrieved directly from there. Or if it was possible for MS to share how the value is calculated.

We have the same drivers (automation) and requirement for the ID.  We're looking for a way to obtain the ID prior to provisioning an App Service.  Is this possible?  Did you happen to find a way?

**Comment by panchagnula** [comment] 2022-01-10 23:03
> > We setup our infrastructure (functionapp & other resources) via a bicep/ARM template. In the bicep template we bind the custom hostname to the functionapp but this requires that we have already added the records with our DNS provider. Thus we a way to retrieve the record values and set these with our DNS provider before setting up our infrastructure. Since it's not possible to get the value from the subscription alone this means we would have to create a webapp use the cli to get the id and then destroy the webapp. If we want to automate the task. Since the value is unique for the subscription alone it feels like it would be better for everyone if it could be retrieved directly from there. Or if it was possible for MS to share how the value is calculated.
> 
> We have the same drivers (automation) and requirement for the ID. We're looking for a way to obtain the ID prior to provisioning an App Service. Is this possible? Did you happen to find a way?

Due to security reasons there is no way to obtain this prior to creating app Service at this point.

**Comment by JeffreyCA** [comment] 2025-08-05 22:34
You can refer to the algorithm shared in https://github.com/dotnet/aspire/issues/6271#issue-2583658245
It's basically a hash of your subscription ID + a constant.
