### ISSUE TITLE
az upgrade ends with error

### ISSUE THREAD

**Issue by elonp** [Azure/azure-cli#17248] opened 2021-03-09 10:09 UTC
## Describe the bug

**Command Name**
`az upgrade`

**Errors:**
```
cannot import name 'status_tag_messages'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    out_file = sys.stdout
cli/core/commands/__init__.py, ln 659, in execute
    ex, id_arg = exceptions[0]
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    try:
cli/core/commands/__init__.py, ln 715, in _run_job
    return cmd_copy.exception_handler(ex)
...
<frozen importlib._bootstrap>, ln 618, in _exec
<frozen importlib._bootstrap_external>, ln 678, in exec_module
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
azure/cli/core/__init__.py, ln 57, in <module>
    _configure_knack()
azure/cli/core/__init__.py, ln 45, in _configure_knack
    from knack.util import status_tag_messages
ImportError: cannot import name 'status_tag_messages'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade`

## Environment Summary
```
Linux-5.4.0-1036-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

```

**Comment by yungezz** [comment] 2021-03-10 00:35
@fengzhou-msft could you pls have a look?

**Comment by fengzhou-msft** [comment] 2021-03-16 04:46
Duplicate of #16952

**Closed** 2021-03-16 16:20 UTC
Labels: Upgrade, question
