### ISSUE TITLE
App Configuration: Key/values without labels are not returned when using the label parameter

### ISSUE THREAD

**Issue by jmshal** [Azure/azure-cli#15440] opened 2020-10-08 02:10 UTC
## Describe the bug

The use of `--label \0` has broken in one of the more recent versions of the Azure CLI, causing our CI/CD to fail.

We use the `--label` flag to filter out any key/values that should not be accessible to the application. We use `az appconfig kv list` at deploy-time (in Azure DevOps) to build up a list of environment variables & secrets that should be deployed along with our micro-services (to aks).

Our build script has been failing since of today (last successful deploy was at `2020-10-06T01:58:48.375Z`), complaining that particular environment variables could not be found within Azure App Configuration. I ran the deploy script locally, and it worked just fine, so I updated to the latest version of the Azure CLI (via Homebrew), re-ran the deploy script, and it failed.

I debugged the deploy script, and I can see that the call to `az appconfig kv list` is only returning key/values that have labels. For example, we have one App Configuration resource per environment, and key/values that we'd like all micro-services to have access to have no label, and key/values we only want particular micro-services to have access to have a label like this: `app=custom-tools-service` or `app=text-extraction-service`. We have generic key/values (like `NODE_ENV`) which are shared across all micro-services, thus do not have a label attached, and those are the ones that are not returning.

I have tried a number of things to try and get the correct results returning from the CLI, however nothing I have tried has worked. I have tried re-ordering the labels in the cli. I have tried URL encoding the `\0` label manually. And a number of random other things.

**Command Name**
`az appconfig kv list`

**Errors:**
The command doesn't error, however it does not return any key/values. The App Configuration resource has many key/values without labels.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az appconfig kv list --subscription [REDACTED] --name [REDACTED] --label \0`

OR

- `az appconfig kv list --subscription [REDACTED] --name [REDACTED] --label \0,app=custom-tools-service`

## Expected Behavior

All key/values without labels should be returned.

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.9.0
Installer: HOMEBREW

azure-cli 2.12.1

Extensions:
front-door 1.0.4

```

**Comment by jmshal** [comment] 2020-10-08 02:12
I've just checked the last Azure DevOps build that was successful, and it used version `2.11.1` of the Azure CLI.

So this has regressed somewhere between `2.11.1` and `2.12.1`.

**Comment by jmshal** [comment] 2020-10-08 02:18
I can see that there was only one change relating to App Configuration between the two versions I've determined the regression must've happened. I see that the azure-mgmt-appconfiguration package was updated from `0.5.0` to `0.6.0` - I wonder whether the regression has happened there, and not within the Azure CLI itself.

**Comment by yonzhan** [comment] 2020-10-08 02:30
appconfig

**Comment by avanigupta** [comment] 2020-10-08 07:05
Hi @jmshal, thanks for providing all the details of the issue you are facing. 
I was able to reproduce the issue in Azure Cloud Shell using bash. The problem occurs because the backslash character needs to be escaped in bash. If you run the command with `--debug` argument, you'll see that the \ character is lost from input:

You can resolve the issue by providing `--label '\0'` or `--label "\0"` or `--label \\0`.

![image](https://user-images.githubusercontent.com/5563494/95418609-c415d000-08ec-11eb-847e-c64cc99fc88f.png)

Hope that helps!

**Comment by jmshal** [comment] 2020-10-08 08:43
Hi @avanigupta,

Our build script is already quoting the arguments (using double quotes), it has been since the build script was put together. We've not changed the build script at all within the past few days, and as far as I can tell - the only different is the version of the Azure CLI that us being used by Azure DevOps.

I think it perhaps may have been all the random things I have tried - but it appears the actual issue is when we use `\0` along with another label (multiple label filters). The `\0` filter works just file, as you correctly pointed out - it must however be quoted. This is a little confusing as the `--help` flag shows an example without it quoted - it should probably be updated I imagine, as it made me believe there was also something wrong with the `\0` filter alone.

Here's an example of the command our build script executes, and it's output:

```
$ az appconfig kv list --subscription [REDACTED] --name [REDACTED] --label "\0,app=custom-tools-service"
[]
```

It should be returning results, however it is not.

**Comment by avanigupta** [comment] 2020-10-08 19:28
Hi @jmshal, thanks for pointing this out! We did introduce a regression with querying multiple labels in the last CLI update. This will be fixed in the next CLI release. Sorry for the inconvenience.

**Comment by jmshal** [comment] 2020-10-08 19:42
> This will be fixed in the next CLI release

Thanks, @avanigupta. Do you know what kind of timeline are we looking at here? From as far as I can tell, I cannot target an older version of the Azure CLI within Azure DevOps - so without making some large changes to our pipelines, we're stuck without the ability to deploy.

I also don't know how often the Azure DevOps team updates the version of Azure CLI they use - so that's another concern.

Any information, just so we're not in the dark, will be helpful. Thanks!

**Comment by avanigupta** [comment] 2020-10-08 21:16
@jmshal, Azure CLI has a new release approximately every 3 weeks, and this fix would most likely be included in the release scheduled for end of this month. Until then, the workaround would be to tweak the command for listing key values in either of these two ways:

1. You can split the list command into two commands - one which lists only null labels, and the second which lists any other labels: 
```
settingsWithNullLabel=$(az appconfig kv list --name test-appconfig-00 --label '\0')
settingsWithOtherLabels=$(az appconfig kv list --name test-appconfig-00 --label MyLabel,MyLabel2)
```

2. You can fetch key-values with all labels and then use `--query` argument to filter the required labels:
```
az appconfig kv list --name test-appconfig-00 --query """[?label=='MyLabel'||label==null]"""
```

**Comment by jmshal** [comment] 2020-10-08 23:07
Thanks @avanigupta - I can confirm the workarounds you've provided are enough to get us back on track with deploys for the time being. Much appreciated!

**Closed** 2020-10-19 04:26 UTC
Labels: App Configuration, Service Attention
