### ISSUE TITLE
Automation: persist command surfaces and detect changes between commits.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1466] opened 2016-11-29 23:57 UTC
And compare the dump between build to detect the command surface changes.

**Comment by tjprescott** [comment] 2016-11-30 00:03
Related to, but not a dupe of, #733

**Comment by JasonRShaver** [comment] 2017-11-03 02:53
Cleaning u old issues, reopen if this is still active.

**Comment by tjprescott** [comment] 2018-10-04 23:05
We have numerous other ways of detecting changes to commands. Closing this.

**Closed by tjprescott** 2018-10-04 23:05 UTC
Labels: Infrastructure, Test
