### ISSUE TITLE
Functionapp:az functionapp create fails to create and configure Application Insights for function app in new regions

### ISSUE THREAD

**Issue by pgombar** [Azure/azure-cli#21072] opened 2022-01-20 21:47 UTC
**Describe the bug**
When trying to create a Linux Consumption Function App in Jio India West and US West 3 regions (these are new regions), we get the following error:

```
PS C:\Users\pagombar> az functionapp create --name pagombar-usw3-cli --resource-group pagombar --storage-account pagombarusw3 --os-type Linux --runtime dotnet --consumption-plan-location westus3
No functions version specified so defaulting to 3. In the future, specifying a version will be required. To create a 3.x function you would pass in the flag `--functions-version 3`
 
--runtime-version is not supported for --runtime dotnet. Dotnet version is determined by --functions-version. Dotnet version will be 3.1 for this function app.
 
Your Linux function app 'pagombar-usw3-cli', that uses a consumption plan has been successfully created but is not active until content is published using Azure Portal or the Functions Core Tools.
 
Error while trying to create and configure an Application Insights for the Function App. Please use the Azure Portal to create and configure the Application Insights, if needed.
```

The function app gets created, but not Application Insights. Here is the output when the same command is ran with `--debug` flag:
```
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<subscriptionid-removed>/resourceGroups/nzthiwestus33/providers/Microsoft.Insights/components/nzthiwestus333-cli?api-version=2015-05-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '81'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e59320a7-794c-11ec-8831-c8348e1c4d50'
cli.azure.cli.core.sdk.policies:     'CommandName': 'functionapp create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --storage-account --os-type --functions-version --runtime --consumption-plan-location --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.32.0 (MSI) azsdk-python-azure-mgmt-applicationinsights/1.0.0
Python/3.8.9 (Windows-10-10.0.22000-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "westus3", "kind": "web", "properties": {"Application_Type": "web"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<subscriptionid-removed>/resourceGroups/nzthiwestus33/providers/Microsoft.Insights/components/nzthiwestus333-cli?api-version=2015-05-01 HTTP/1.1" 400 261
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '261'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Request-Context': 'appId=cid-v1:920e14b1-13f3-461a-a4bb-b4fe6f1a4525'
cli.azure.cli.core.sdk.policies:     'Access-Control-Expose-Headers': 'Request-Context'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '74b50abd-f7cd-471e-98bb-859322fbb86d'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '74b50abd-f7cd-471e-98bb-859322fbb86d'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS2:20220119T172635Z:74b50abd-f7cd-471e-98bb-859322fbb8
6d'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 19 Jan 2022 17:26:34 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"code":"BadRequest","message":"Region doesn’t support Classic resource mode for Application Insights resources. Please use Workspace-based mode.","innererror":{"diagnosticcontext":"e59320a7-794c-11ec-8831-c8348e1c4
d50","time":"2022-01-19T17:26:34.8195205Z"}}
cli.azure.cli.command_modules.appservice.custom: Error while trying to create and configure an Application Insights for the
Function App. Please use the Azure Portal to create and configure the Application Insights, if needed.
```

**To Reproduce**
Create a function app using azure cli in Jio India West or US West 3.

**Expected behavior**
Function app and Application Insights gets created in all supported regions, including the ones above: Jio India West and US West 3.

**Environment summary**
az-cli v2.30.0 and v2.32.0 on Windows.

**Additional context**
When creating the same app from Azure Portal, the Portal uses apiVersion `2020-02-02-preview`, which is newer than the version az CLI uses: `2015-05-01`.

**Comment by yonzhan** [comment] 2022-01-20 23:49
route to service team

**Comment by pragnagopa** [comment] 2022-01-21 15:33
cc @nzthiago

**Comment by panchagnula** [comment] 2022-04-01 00:07
@pragnagopa / @nzthiago can this issue be closed - or should we not allow users to not create function App in regions whee ApplicationInsights is unavailable - if the function app created is not manageable or useful? If so is there a way/ API of CLI to pre-validate this & show a useful message?

**Comment by panchagnula** [comment] 2022-04-01 17:31
> > should we not allow users to not create function App in regions whee ApplicationInsights is unavailable - if the function app created is not manageable or useful?
> 
> We should improve create flows to consider regions where ApplicationInsights is not avaialable - as creating a function app without ApplicationInsights will result in lack of visibility into logs. CLI create flow should explicitly prompt user giving a choice if they would be Ok creating ApplicationInsights in another region . or Pick a different region altogether

Thanks Pragna. In CLI we avoid blocking a command waiting on a prompt - by I agree with the better create experience. Is there an API we can use here to check if application Insights is supported & return a list of supported regions.

**Comment by nzthiago** [comment] 2022-05-02 20:38
@panchagnula @pragnagopa the issue isn't that App Insights is not available in the region; it is available, but App Insights in that region doesn't support the older Classic resource mode for Application Insights resources, and only supports the newer [Workspace-based Application Insights resources](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource). 

So this issue is more for the CLI to use the newer apiVersion for App Insights just like when creating the Function with App Insights via the Azure Portal. As per the note in the issue description at the time of creating this issue the Portal uses apiVersion 2020-02-02-preview for the App Insights portion, which is newer than the version the az CLI uses (2015-05-01) as per this part of the CLI debug logs:
```
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "westus3", "kind": "web", "properties": {"Application_Type": "web"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<subscriptionid-removed>/resourceGroups/nzthiwestus33/providers/Microsoft.Insights/components/nzthiwestus333-cli?api-version=2015-05-01 HTTP/1.1" 400 261
cli.azure.cli.core.sdk.policies: Response status: 400
```

Hope that clarifies it.

**Comment by pragnagopa** [comment] 2022-05-02 23:55
Thanks for the clarification @nzthiago  - @pgombar  - if you can - please edit the title of the issue to reflect - CLI needs to be updated to use latest version of API to create App insights

**Comment by panchagnula** [comment] 2022-05-03 01:28
@nzthiago thanks for the update will create a bug for us to update CLI. In the future - could you please keep CLI team updated as well along with portal for such changes so we don't discover these by customer reports. Thank you :)

**Comment by pragnagopa** [comment] 2022-05-03 13:20
Tagging @shimedh - in case she can loop in @panchagnula when Ux moves to newer ARM APIs as part of Functions Create Flow

**Comment by mshelll** [comment] 2022-06-15 12:05
> @panchagnula @pragnagopa the issue isn't that App Insights is not available in the region; it is available, but App Insights in that region doesn't support the older Classic resource mode for Application Insights resources, and only supports the newer [Workspace-based Application Insights resources](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource).
> 
> So this issue is more for the CLI to use the newer apiVersion for App Insights just like when creating the Function with App Insights via the Azure Portal. As per the note in the issue description at the time of creating this issue the Portal uses apiVersion 2020-02-02-preview for the App Insights portion, which is newer than the version the az CLI uses (2015-05-01) as per this part of the CLI debug logs:
> 
> ```
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: {"location": "westus3", "kind": "web", "properties": {"Application_Type": "web"}}
> urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
> urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<subscriptionid-removed>/resourceGroups/nzthiwestus33/providers/Microsoft.Insights/components/nzthiwestus333-cli?api-version=2015-05-01 HTTP/1.1" 400 261
> cli.azure.cli.core.sdk.policies: Response status: 400
> ```
> 
> Hope that clarifies it.

Is there any documentation for the appinsights newer api version

**Comment by nzthiago** [comment] 2022-06-15 15:38
@mshelll It seems the [docs still show the older API version](https://docs.microsoft.com/en-us/rest/api/application-insights/components/create-or-update). But I found the [template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2020-02-02-preview/components?tabs=bicep#applicationinsightscomponentproperties-object) and [API Specs](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2020-02-02-preview).

**Comment by abhijaiswal123** [comment] 2023-09-13 11:05
Any update on when this issue can be fixed, we wish to deploy functionapps in newer region but this has us blocked.

**Comment by kamperiadis** [comment] 2024-01-09 20:22
Hi @pgombar @abhijaiswal123 By default, we now create workspace-based application insights components in the `az functionapp create` command. Therefore, you should no longer be running into this issue. As such, I will close this but feel free to open a new GitHub issue if you are still facing this problem.

**Closed by kamperiadis** 2024-01-09 20:22 UTC
Labels: Service Attention, Monitor, Functions, Monitor - ApplicationInsights
