### ISSUE TITLE
az mysql server firewall-rule delete fails with 200 response if the rule doesn't exist

### ISSUE THREAD

**Issue by yaronyg** [Azure/azure-cli#4209] opened 2017-08-11 22:35 UTC
### Description
```
az mysql server firewall-rule delete --resource-group mySQLSCUp --server-name mysqlscupmysql --name "20aaea739282e3ea251977cc" --yes --debug
The output of the command is a failure with:
Deployment failed. Operation failed with status: 200. Details: Resource state Failed
```
First off, 200 is success, not failure. So right away this error doesn't make any obvious sense.

I used --debug and for response content it just says "Body contains chunked data." for the GET request used to find out the result of the DELETE but no actual content is lised. The next like is the Operation failed with status: 200.

Note that this error occurs when trying to delete a rule that doesn't exist. Which, if you think about it, isn't an error. We said "nuke it" and it's "nuked". All good, right?
 
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.10

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Powershell

**Comment by SaloniSonpal** [comment] 2017-11-03 18:19
@yaronyg - This is by design. Since the rule does not exist, deletion of it declares success.

**Comment by yaronyg** [comment] 2017-11-05 17:07
@SaloniSonpal - I agree that this should be successful, but as I document above, it isn't. The operation fails. In other words if the command to delete a rule that didn't exist succeeded I would be happy. But as I document above that isn't what's going on, instead the command says "200" but then exits with a failure code causing my script to fail.

**Comment by ajlam** [comment] 2019-06-03 22:49
Will also track this internally in VSO. 

@bsiegel - please help close this issue.

**Closed** 2019-06-04 15:12 UTC
Labels: MySQL, Service Attention
