### ISSUE TITLE
`az webapp vnet-integration add` fails when the App Service Plan was moved

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-cli#12629] opened 2020-03-18 03:54 UTC
**Describe the bug**
Move an app service and its app service plan to a new resource group and you can no longer use the `az webapp vnet-integration` commands. This seems to be a common and frustrating recurring theme with app services in general - they don't work well if you move them out of their original resource group which their webspace is tied to. I only have the one app service plan and it is already connected to the vnet through other app services, there are no other app services plans connected to the vnet. Using the Azure Portal also does not work.

**Command**
az webapp vnet-integration add --resource-group GroupNEW --name AppService1 --vnet Vnet1 --subnet Subnet1

**Error**
Operation returned an invalid status code 'Conflict'

**Debug details**
Subnet Subnet1 in VNET Vnet1 is already occupied by service /subscriptions/123/resourceGroups/GroupOLD/providers/Microsoft.Web/serverfarms/AppServicePlan1.

**To Reproduce**
1. Move an app service and its app service plan to a new resource group.
1. Try to use the `az webapp vnet-integration add` command on it.
1. Error: Operation returned an invalid status code 'Conflict'

**Expected behavior**
Success

**Workaround**
1. Move the App Service Plan back to a resource group named the same as the original it was created in.
1. Connect the vnet.
1. You can then move it back to the new group if required.

**Comment by yungezz** [comment] 2020-03-18 08:47
thanks for reporting, we'll look at it

**Comment by panchagnula** [comment] 2020-04-17 15:07
Thanks for reporting same root cause as this one https://github.com/Azure/azure-cli/issues/12834
Closing this as Duplicate.

**Closed by panchagnula** 2020-04-17 15:07 UTC
Labels: Service Attention, Web Apps

**Comment by krispenner** [comment] 2020-07-22 21:52
@panchagnula I'm not 100% convinced is the same root cause. That issue is about ASE (App Service Environment) and VNet being in different resource groups.

My issue is about an App Service Plan not being located in the original resource group is was created in.

Very different and I really doubt the underlying root cause is the same. 

There are many known problems with moving App Service Plans out of their original resource group and I think this relates more to that as the underlying issue.

I'd prefer this stay open so someone can investigate it further or provide reasons why it is a duplicate.
