### ISSUE TITLE
Updating IoT Hub File Upload Settings Not working

### ISSUE THREAD

**Issue by mohamedsaif** [Azure/azure-cli#11438] opened 2019-11-29 19:45 UTC
## Describe the bug

**Command Name**
`az iot hub update`

**Errors:**
```
Couldn't find '$default' in 'properties.storageEndpoints.$default.connectionString=DefaultEndpointsProtocol=https;AccountName=ie22919framesstg;AccountKey=jkmzlC50utT2xbuYV2YcE3IodwPfSitmzD47zng7jhJ3nwJwONXQ16Gyx81fpOtWiTEjCpsXJS+BorXxTiHIDw==;EndpointSuffix=core.windows'. Available options: []
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub update --name {} --add properties.storageEndpoints.'$default'.connectionString="$FRAMES_STORAGE_CONN"`

## Expected Behavior
File Upload connection string to storage updated

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by jlian** [comment] 2019-12-02 17:21
Seems related to https://github.com/Azure/azure-cli/issues/11437

@iluican

**Comment by jlian** [comment] 2019-12-12 18:48
Closing since this is a dupe of #11437

**Closed by jlian** 2019-12-12 18:48 UTC
Labels: IotHub, Service Attention
