### ISSUE TITLE
az functionapp deployment source config-zip doesn't work

### ISSUE THREAD

**Issue by akopitsa** [Azure/azure-cli#22127] opened 2022-04-20 11:06 UTC
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='ps-chronos-dev.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0619A940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 174, in _new_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 73, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 358, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0619A940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ps-chronos-dev.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0619A940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 524, in enable_zip_deploy_functionapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 557, in enable_zip_deploy
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 117, in post
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 61, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ps-chronos-dev.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0619A940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0
```

**Comment by yonzhan** [comment] 2022-04-20 12:31
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2022-04-20 18:58
@akopitsa We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment] 2022-04-22 22:55
Hello @akopitsa thanks for the query!

Could you please share more details on the Azure function App plan? region? version? So that we get a better understanding of the issue to reproduce it? Is this an intermittent issue? Is your host machine able to reach the Azure subscription during this CLI command execution?

`az functionapp create --name $functionName --storage-account $storageAccountName --consumption-plan-location westeurope --resource-group $resourceGroupName --functions-version 2`

Did you try from [PowerShell zip deployment](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#with-powershell)?

**Comment by akopitsa** [comment] 2022-04-23 07:28
> Hello @akopitsa thanks for the query!
> 
> Could you please share more details on the Azure function App plan? region? version? So that we get a better understanding of the issue to reproduce it? Is this an intermittent issue? Is your host machine able to reach the Azure subscription during this CLI command execution?
> 
> `az functionapp create --name $functionName --storage-account $storageAccountName --consumption-plan-location westeurope --resource-group $resourceGroupName --functions-version 2`
> 
> Did you try from [PowerShell zip deployment](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#with-powershell)?

Hello Satish,

We used `az functionapp create ...` command to deploy our code once we deploy the Azure Function infrastructure with ARM template but without that parameter **--functions-version 2**
region East US
the sku we used 
```
            "sku": {
                "name": "Y1",
                "tier": "Dynamic",
                "size": "Y1",
                "family": "Y",
                "capacity": 0
            }
```
It seems it's an intermittent issue and always reproducible after several attempts azure function (infrastructure part) deployment when we deploy the function code once the infrastructure part is deployed  

Powershell deployment with **Publish-AzWebApp** doesn't work at all in this case.

**Comment by SatishBoddu-MSFT** [comment] 2022-04-25 21:15
Hello @akopitsa Thanks for the detailed information on this intermittent issue!

The better option would be to go with a support ticket immediately after the issue occurred!! so that we have logs in the backend and can troubleshoot this issue very quickly. We will archive this issue, for now, please do let us know if you want to close this issue ?

Please open a new issue on Azure Powershell Github for the related error and we are more than happy to assist you on that!

**Comment by SatishBoddu-MSFT** [comment] 2022-04-28 22:49
Hello @akopitsa Just checking back! Please let us know if you need further help.

**Comment by SatishBoddu-MSFT** [comment] 2022-05-02 20:34
Since we didn't receive any response, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.

**Closed by SatishBoddu-MSFT** 2022-05-02 20:34 UTC
Labels: Functions, App Services, customer-reported, needs-team-attention, needs-author-feedback, CXP Attention, Auto-Assign
