### ISSUE TITLE
az account set error in Cloudshell

### ISSUE THREAD

**Issue by VKorobejnik** [Azure/azure-cli#13924] opened 2020-06-10 12:02 UTC
## Describe the bug

Getting this error when trying to run any Azure command in the cloud powershell

**Command Name**
`az account set`

**Errors:**

```
The command failed with an unexpected error. Here is the traceback:

[Errno 30] Read-only file system: '/home/vladimir/.azure/versionCheck.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 48, in load
    with codecs_open(self.filename, 'r', encoding=self._encoding) as f:
  File "/opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vladimir/.azure/versionCheck.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/feedback/custom.py", line 763, in handle_feedback
    show_updates_available(new_line_before=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 287, in show_updates_available
    VERSIONS.load(os.path.join(get_config_dir(), 'versionCheck.json'))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 61, in load
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 30] Read-only file system: '/home/vladimir/.azure/versionCheck.json'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Running any command, the last one was az feedback
## Expected Behavior
Executing command and showing output
## Environment Summary
```
Linux-4.15.0-1083-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

``
<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by jiasli** [comment] 2020-07-23 07:53
Duplicate of #13855

**Comment by maertendMSFT** [comment] 2020-09-30 23:14
Can we close this as a dupe of #13855 ?

**Closed** 2020-10-01 09:06 UTC
Labels: Account, Cloud Shell, OKR3.2 Candidate, Service Attention, customer-reported
