### ISSUE TITLE
az containerapp no longer supporting environment variables with certain characters

### ISSUE THREAD

**Issue by evklein** [Azure/azure-cli#23199] opened 2022-07-14 01:55 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az containerapp update`

**Describe the bug**
When an Azure Container app has an environment variable with characters that are not: 'a-z, A-Z, 0-9 and _', `az containerapp` will not work and will deliver the following error message:

`ERROR: Env variable name 'your-env-variable' contains invalid character, allowed characters are 'a-z, A-Z, 0-9 and _'`

Originally reported here: https://github.com/microsoft/azure-container-apps/issues/308 This was working as of several days ago, so I think its okay to call this a regression.

**To Reproduce**
Add an environment variable to your Container in your Container app that contains a non 'a-z, A-Z, 0-9 or _' character.

**Expected behavior**
Environment variables with characters outside the 'a-z, A-Z, 0-9 or _' range should be allowed and should not cause `az containerapp` update to fail.

**Environment summary**
Blazor server application running in a Dockerfile. Deployed by Github actions using the standard script provided by Microsoft and the azure/CLI@v1 action.

**Additional context**
This was working as of about 72 hours ago, when I did the last deployment.

**Comment by yonzhan** [comment] 2022-07-14 02:13
route to CXP team

**Comment by navba-MSFT** [comment] 2022-07-14 03:37
@evklein Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-07-14 07:34
@evklein Could you please share the `--debug` output here ? I feel that this issue isn't related to the Container App but the underlying image OS type.

The bash manual mentions this clearly ([here](http://www.gnu.org/software/bash/manual/bashref.html#Definitions))

>name
A word consisting solely of letters, numbers, and underscores, and beginning with a letter or underscore. Names are used as shell variable and function names. Also referred to as an identifier.

Also the error message is again self-explanatory and it is as per the IEEE standard for environment variables.

>Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore)

Refer [this](https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html).

**Comment by evklein** [comment] 2022-07-14 10:53
@navba-MSFT Sure, here: 

![image](https://user-images.githubusercontent.com/5017975/178966448-ae2e00df-a07f-476e-9572-c774d2c47a4b.png)

> Also the error message is again self-explanatory and it is as per the IEEE standard for environment variables.

This is understandable, however I do want to emphasize that just a few days ago this was working, and I have made no changes to the OS I am using for deployment, both in the Github action and in the Dockefile.

**Comment by navba-MSFT** [comment] 2022-07-14 10:56
@evklein Could you please run the az --version command and share the output here ?

**Comment by evklein** [comment] 2022-07-14 11:03
@navba-MSFT 
![image](https://user-images.githubusercontent.com/5017975/178968321-3777cf47-402e-40aa-a826-bbbfd462d536.png)

Looks like I'm up to date using 2.38.0

**Comment by evklein** [comment] 2022-07-14 11:47
For anyone stumbling across this issue in a similar spot - I ended up removing my Azure Container App service and starting over from scratch with an Azure app service on the free tier. Azure app services have an option for database connection strings that don't follow these env-specific rules so deployment was pretty quick.

Happy to help continuing to work through this, although it sounds like the IEEE standard may have caught up with `az containerapps`, makes sense since this package is in preview.

**Comment by navba-MSFT** [comment] 2022-07-15 05:17
@evklein This isn’t a CLI issue. This occurs in the portal as well. This bug is a duplicate of this issue on the container apps github repo: https://github.com/microsoft/azure-container-apps/issues/308 . So we will close this as a duplicate and you can track this issue in the container apps repo.

**Closed by navba-MSFT** 2022-07-15 05:17 UTC
Labels: Container Instances, question, customer-reported, needs-team-attention, CXP Attention, Auto-Assign, ContainerApp
