### ISSUE TITLE
'az quantum offerings' not recognized

### ISSUE THREAD

**Issue by vivienlonde** [Azure/azure-cli#21307] opened 2022-02-15 17:09 UTC
az quantum offerings
returns: 
'offerings' is misspelled or not recognized by the system.
whereas it is used in the [documentation.](https://docs.microsoft.com/en-us/azure/quantum/how-to-manage-quantum-workspaces-with-the-azure-cli)

I am using the last version:
azure-cli 2.33.1

with the up-to-date extension:
quantum 0.15.2101.2800

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69eb01f8-5765-aac0-15e3-010b95d3a062
* Version Independent ID: 4f8d3944-c971-783e-5ca7-da5d06ceb01b
* Content: [az quantum offerings](https://docs.microsoft.com/en-us/cli/azure/quantum/offerings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/quantum/offerings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/quantum/offerings.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2022-02-16 00:19
route to service team

**Comment by jsntcy** [comment] 2022-02-16 07:13
@vxfield, @ricardo-espinoza, could you please help look at this issue?

**Comment by vxfield** [comment] 2022-02-16 22:12
During early investigations we noticed that this happen to any Az CLI extension, not just `quantum`.

@jsntcy, @yonzhan: is this expected in the CLI?
``` bash
> az storage       
the following arguments are required: _subcommand

Examples from AI knowledge base:
az storage account list
List all storage accounts in a subscription.
```

If I remember correctly, when a parameter was missing the Az CLI would complain but automatically print the help with the available options. That is not present anymore, perhaps due to a bug in CLI.

@warren-jones is continuing the investigation to see how we can improve the user experience.

**Comment by jsntcy** [comment] 2022-02-17 02:23
@vivienlonde @vxfield, it's by design currently as `az quantum offerings` and `az storage` are command group, only command will show recommendation, for example `az quantum offerings list`.

@vivienlonde, you need run command with arguments instead of command group, such as `az quantum offerings list`,

![image](https://user-images.githubusercontent.com/16348853/154392280-45d259f4-6084-426d-8f98-c24493b22065.png)

**Comment by vxfield** [comment] 2022-02-17 03:19
Thanks. Are there any plans (or concerns why not) to print the help message (as if using —help argument) when a command or parameter is missing?
________________________________

**Comment by jsntcy** [comment] 2022-02-17 04:19
@vxfield, sorry, I didn't quite understand what you mean, do you mean CLI should tell users that a command is missing when they only run command group?
CLI does print help message when users run command missing some parameters as the example above `az quantum offerings list`, it will tell users "location" is needed.

**Comment by vxfield** [comment] 2022-02-17 06:34
@yonzhan , yes, I guess I'm asking for a feature to improve user experience.
I created a separate issue for that.
Let's close this one and please consider #21337.

@vivienlonde, since this behavior is by design, I'm closing this issue.
Please reopen it if you disagree.

**Closed by vxfield** 2022-02-17 06:34 UTC
Labels: Core, customer-reported, feature-request

**Comment by vivienlonde** [comment] 2022-02-17 09:58
Thank you for the answers. But the error I have is different:
![Capture](https://user-images.githubusercontent.com/45631143/154451291-b3e7d7f9-06f7-4bf0-a308-43eb43c2e5f0.PNG)

Here are the versions I use:
azure-cli 2.33.1
quantum 0.15.2101.2800

**Comment by jsntcy** [comment] 2022-02-17 12:53
The latest version is 0.12.0, I'm curious why your version is 0.15.xxxx, could you upgrade to latest version to try again?
![image](https://user-images.githubusercontent.com/16348853/154484776-05ed5ca8-089a-4417-82bc-25fc553e22f3.png)

**Comment by vivienlonde** [comment] 2022-02-17 13:05
Indeed ! I don't know either.. I was not able to upgrade it (response: "no update available"). But removing the quantum extension and then adding it again installed version 0.12.0. And it fixed the error I had.
Thank you for the help !
