### ISSUE TITLE
Add quiet mode

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-cli#6341] opened 2018-05-13 15:26 UTC
For use in scripts, it would be nice to have a "quiet mode" (i.e that only outputs to stderr on error rather than the more verbose present style)

**Comment by tjprescott** [comment] 2018-05-14 15:40
The CLI is already designed to be quiet.  What verbose style are you referring to?  A specific command?

**Comment by udf2457** [comment] 2018-05-14 15:53
I'm more referring to the typical Linux definition of quiet (i.e. only make noise if there's something wrong).

For example, you would expect `az storage blob upload --no-progress` to be pretty quiet, but it still blurts out content on success but all I'm really interested in is whether or not the upload was successful, which means at the moment I'm forced to `> /dev/null 2>&1`

Or the same with a clean-up command such as:
`az storage blob delete-batch -s "${azureContainer}" --delete-snapshots include --if-unmodified-since "${timeDelta}"`

I don't really care for output if the clean-up was succesful, I only want to hear about failures.

**Comment by mattpetrick** [comment] 2018-09-14 03:49
duplicate of #5667

**Comment by yonzhan** [comment] 2019-12-22 10:30
add to S165.

**Comment by jiasli** [comment] 2020-03-24 13:48
We have added option `--only-show-errors` in #12604 to disable warnings that are written to `stderr`. It will be included in [S167](https://github.com/Azure/azure-cli/milestone/84) release.

**Closed by jiasli** 2020-03-24 13:48 UTC
Labels: Core, Discussion, Feature Request, Output
