### ISSUE TITLE
Azure error publish: found multiple accounts with the same username

### ISSUE THREAD

**Issue by OleksandrHrybovoda** [Azure/azure-cli#20783] opened 2021-12-20 15:23 UTC
![image](https://user-images.githubusercontent.com/16946202/146790890-b548946c-8fda-423e-a943-430b4d1d3a93.png)
What I should do if it is written: found multiple accounts with the same username.

**Comment by jiasli** [comment] 2021-12-21 07:48
Duplicate of #20168

**Closed by jiasli** 2021-12-21 07:48 UTC
Labels: question, customer-reported, needs-triage
