### ISSUE TITLE
`az webapp config ssl bind` clears Web App tags

### ISSUE THREAD

**Issue by Costo** [Azure/azure-cli#6929] opened 2018-07-31 20:23 UTC
**Describe the bug**

After running the command `az webapp config ssl bind -g <resource-group> --name <app-service-name> --certificate-thumbprint <thumbprint> --ssl-type SNI`, the Web App tags collection is empty

Same behavior with `unbind`.

**To Reproduce**

* Add tags to a Web App
* Add a custom domain (Required)
* Upload an SSL certificate
* Bind the certificate to the Web App using this command: `az webapp config ssl bind -g <resource-group> --name <app-service-name> --certificate-thumbprint <thumbprint> --ssl-type SNI`

After the command succeeds, check the Tags collection. It's empty.

**Expected behavior**
Tags collection should not be modified by the operation

**Environment summary**
Azure Cloud Shell (Bash)
CLI version 2.0.42

**Additional context**

**Comment by yugangw-msft** [comment] 2018-07-31 23:57
@panchagnula , i will take this one unless you are interested

**Comment by panchagnula** [comment] 2018-08-01 00:16
Sure thank you.

**Comment by Costo** [comment] 2018-08-07 18:36
Was this fixed? My Azure Cloud Shell CLI version is now 2.0.43 and this problem went away apparently.

**Comment by yugangw-msft** [comment] 2018-08-07 19:05
@Costo, I have not submitted any change for this, but since you are at it, can you double check the repro? This command indeed recreates the site payload w/o propagating the original data, which I thought would be the root cause; however if it works, then I would not touch it.

**Comment by Costo** [comment] 2018-08-07 19:42
So I created a new Web App from scratch and I could not reproduce this problem. However, I did the same repro on an existing Web App (the same I used when I reported this issue) and the problem is still definitely there.

**Comment by yugangw-msft** [comment] 2018-08-10 17:01
@Costo, I have tried 5 times but no lucks to reproduce. If you find a repro, please share. At the same time in  PR #7023, I have updated our test suites to cover this scenario in a hope to see a repro. 
For now, I don't plan to update CLI's command code till we understand the root cause.

**Comment by yugangw-msft** [comment] 2019-03-03 22:18
Closing since we can't find a repro

**Closed by yugangw-msft** 2019-03-03 22:18 UTC
Labels: Web Apps-cli
