### ISSUE TITLE
`browse` proxy seems fragile

### ISSUE THREAD

**Issue by Huge** [Azure/azure-cli#9500] opened 2019-05-29 06:30 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2354673910>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 523, in execute
    raise ex
ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2354673910>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Linux-5.0.9-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
Python 2.7.15
Shell: bash

azure-cli 2.0.63 *

```

**Comment by seanmck** [comment] 2019-07-14 07:12
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:12 UTC
Labels: AKS, Needs Triage, Service Attention

**Comment by martinvelos** [comment] 2019-07-29 13:16
This still remains as of
```Linux-5.0.9-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
Python 2.7.15
Shell: bash

azure-cli 2.0.66 * ```
