### ISSUE TITLE
pycopg2 seems to be missing in the included python when I install azure cli with brew

### ISSUE THREAD

**Issue by AronT-TLV** [Azure/azure-cli#14620] opened 2020-08-02 13:19 UTC
## Describe the bug

**Command Name**
`az postgres`

**Errors:**
```
No module named 'psycopg2._psycopg'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 470, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap_external>, ln 783, in exec_module
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
cliextensions/db-up/azext_db_up/custom.py, ln 15, in <module>
    import psycopg2
cliextensions/db-up/psycopg2/__init__.py, ln 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres --help`
or
- `az postgres up --help`
or
- `az postgres down --help`

## Expected Behavior
Should get help

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.9.1

Extensions:
aks-preview 0.4.55
storage-preview 0.2.10
db-up 0.1.13

```
## Additional Context
I manually installed pyscopg2 in the brew python and tested it was there by doing an import
`az postgres db --help` or - `az postgres server --help` works as expected

**Comment by yonzhan** [comment] 2020-08-02 14:30
add to S174

**Comment by Juliehzl** [comment] 2020-08-03 02:39
dupe of #13630

**Comment by Juliehzl** [comment] 2020-08-03 02:41
please upgrade db-up to latest version with the fix.

**Closed by Juliehzl** 2020-08-03 02:41 UTC
Labels: PostgreSQL
