### ISSUE TITLE
az appservice plan list

### ISSUE THREAD

**Issue by amafonso** [Azure/azure-cli#15510] opened 2020-10-13 19:53 UTC
## Describe the bug

**Command Name**
`az appservice plan list`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan list`

## Environment Summary
```
Linux-5.4.0-48-generic-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81 *

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment] 2020-10-13 22:43
appservice

**Comment by yungezz** [comment] 2020-10-14 02:38
hi @amafonso could you pls uninstall 2.0.81, and install lateste azure  cli via guideline  https://aka.ms/doc/InstallAzureCli. This is a known issue in #14011,  the CLI pacakge in Focal is out-of-data and has problem.

**Comment by fengzhou-msft** [comment] 2020-10-20 02:22
Duplicate of #14011

**Closed by fengzhou-msft** 2020-10-20 02:22 UTC
Labels: Packaging
