### ISSUE TITLE
az keyvault set-policy breaks in USGovermentCloud

### ISSUE THREAD

**Issue by ryanhofdotgov** [Azure/azure-cli#18498] opened 2021-06-15 20:05 UTC
## Describe the bug

**Command Name**
`az keyvault set-policy`

**Errors:**
```
(NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2021-04-01-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01'. The supported locations are 'usgovvirginia, usgoviowa, usdodcentral, usdodeast, usgovtexas, usgovarizona'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-  `az cloud set --name AzureUSGovernment`
- `az keyvault set-policy --name INSERT-VAULT-NAME --object-id INSERT-OBJECT-ID --secret-permissions get list`

## Expected Behavior

No error. Expectation is that if command is being run within AzureUSGovernment, it uses the version of the key vault API available in that cloud.

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.25.0

Extensions:
front-door 1.0.14
db-up 0.2.3

```
## Additional Context

The command works as expected in 2.1.6 in both public cloud and USGovernmentCloud. It also fails in azure-cli 2.24.2 which is in Cloud Shell in USGovernmentCloud.

**Comment by ryanhofdotgov** [comment] 2021-06-15 20:39
After poking around, I believe that USGovernmentCloud compatibility was broken by https://github.com/Azure/azure-cli/pull/17679

I've confirmed that 2.22.1 is the latest version that doesn't break in USGovernmentCloud, which is consistent with the release tags on the associated commits from PR above.

**Comment by yonzhan** [comment] 2021-06-16 00:40
keyvault

**Comment by evelyn-ys** [comment] 2021-06-16 02:40
Thanks for reporting! You can move forward for newest updates under #18006

**Comment by evelyn-ys** [comment] 2021-06-16 02:40
Duplicate of #18006

**Closed** 2021-06-16 15:32 UTC
Labels: KeyVault, Service Attention
