### ISSUE TITLE
idk what ahppened

### ISSUE THREAD

**Issue by braintrooper** [Azure/azure-cli#16760] opened 2021-02-02 07:18 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
invalid syntax (parser.py, line 158)
Traceback (most recent call last):
lib\site-packages\knack\cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli\core\commands\__init__.py, ln 659, in execute
    raise ex
cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli\core\commands\__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
Python38-32\lib\site-packages\six.py, ln 703, in reraise
    raise value
...
lib\site-packages\adal\token_request.py, ln 38, in <module>
    from .cache_driver import CacheDriver
lib\site-packages\adal\cache_driver.py, ln 32, in <module>
    from dateutil import parser
lib\site-packages\dateutil\parser.py, ln 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.3
Installer: PIP

azure-cli 2.18.0

```

**Comment by yonzhan** [comment] 2021-02-02 11:58
account

**Comment by jiasli** [comment] 2021-02-02 14:55
This is a duplicate of https://github.com/Azure/azure-cli/issues/16517. Please see the comment at https://github.com/Azure/azure-cli/issues/16517#issuecomment-759414821.

**Closed** 2021-02-02 23:17 UTC
Labels: Account
