### ISSUE TITLE
az aks browse - failure to browse AKS cluster

### ISSUE THREAD

**Issue by yashghia** [Azure/azure-cli#9907] opened 2019-07-10 17:10 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x073EDF70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
pip-install-68v0_w99\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.63 *

Extensions:
aks-preview 0.3.2
webapp 0.2.16

```

**Comment by seanmck** [comment] 2019-07-13 22:13
Duplicate of #9897

**Closed by seanmck** 2019-07-13 22:13 UTC
Labels: AKS, Needs Triage, Service Attention
