### ISSUE TITLE
Azure Tutorial Bug

### ISSUE THREAD

**Issue by chinhang97** [Azure/azure-cli#11205] opened 2019-11-13 06:15 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'int' object has no attribute 'upper'
Traceback (most recent call last):
  File "/home/smartfarm/lib/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/smartfarm/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'int' object has no attribute 'upper'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name {} --resource-group {} --plan {} --sku {} --location {}`

## Environment Summary
```
Linux-5.0.0-32-generic-x86_64-with-Ubuntu-18.04-bionic
Python 2.7.15+
Shell: bash

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment] 2019-11-13 10:38
Duplicate of #11100

**Comment by panchagnula** [comment] 2019-12-27 00:33
Please upgrade to 2.0.77

**Closed by panchagnula** 2019-12-27 00:33 UTC
Labels: Service Attention, Web Apps
