### ISSUE TITLE
az webapp config connection-string list does not give values for non-JSON output

### ISSUE THREAD

**Issue by Cam-Borrowell** [Azure/azure-cli#10495] opened 2019-09-10 17:36 UTC
**Command Name**
`az webapp config connection-string list`

**Errors:**
Values are missing with non-JSON output (such as `table` and `tsv`)

## To Reproduce:
- `az webapp config connection-string list --name {} --resource-group {} --output tsv`

## Expected Behavior
The output should be similar to `az webapp config connection-string list --name {} --resource-group {} --output json`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.71 *
azure-cli-ml 1.0.6

Extensions:
azure-cli-ml 1.0.6
```

**Comment by panchagnula** [comment] 2019-09-25 19:55
RG is marked as optional because ingeneral on CLI you can set a default value for RG using az configure --defaults group=<name>. if you don't do this you need to give us a RG or ID value

**Comment by Cam-Borrowell** [comment] 2019-09-26 12:50
@panchagnula I'm so confused why this issue was closed, it's still a bug (even if I'm missing some information). I don't have any resources that are public, so does it matter if I supply a resource group?

In general, I'm able to reproduce this with any web app that has a connection string. The problem is when you run the same command, with a different `--output`, you get a different set of information. This isn't specific to a resource group/web app.

**Comment by panchagnula** [comment] 2019-09-26 15:53
sorry ignore my comments above the comments for a different issue - reactivating this.

**Comment by panchagnula** [comment] 2019-10-05 03:27
@qwordy need your advice on this issue - is this expected behavior, is there something specific the command needs to do here to support the non JSON output?

**Comment by qwordy** [comment] 2019-10-11 03:35
`table` prints summary, which only contains the most important fields.
Take a look at
https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#custom-table-formats

**Comment by panchagnula** [comment] 2019-11-01 01:36
thanks for info will take a look at this further.

**Comment by yonzhan** [comment] 2020-02-15 04:48
move to S166.

**Comment by yonzhan** [comment] 2020-03-28 04:07
move to S168

**Comment by panchagnula** [comment] 2020-03-30 22:55
@Kotasudhakarreddy can you take a look at this please?

**Comment by Kotasudhakarreddy** [comment] 2020-03-31 05:26
Sure @Panchagnula, will look into it.

**Comment by Kotasudhakarreddy** [comment] 2020-04-01 11:22
@qwordy- we have analyzed and identified that Custom table format displays the plain `Key:Value` fields from the parent object. Where as if there is any child object presnt inside a parent object it is unable to convert in table format. Below is sample FYR. Can you please advise 

![image](https://user-images.githubusercontent.com/60102891/78131323-85ccbf00-7438-11ea-98f0-5be84aa189ca.png)

**Comment by panchagnula** [comment] 2020-04-09 16:12
@qwordy can you comment on the above details - this is not specific to AppService - and might be by Design as per the core implementation fo how --table works. Thanks!

**Comment by qwordy** [comment] 2020-04-10 06:39
Change
```
    with self.command_group('webapp config connection-string') as g:
        g.custom_command('list', 'get_connection_strings', exception_handler=empty_on_404)
```
to
```
    with self.command_group('webapp config connection-string') as g:
        g.custom_command('list', 'get_connection_strings', exception_handler=empty_on_404, table_transformer='{Name:name, SlotSetting:slotSetting, Type:value.type, Value:value.value}')
```
I have not tested it. Search "table_transformer=" in the project, you can find many examples. You can customize the schema of table.

**Comment by Kotasudhakarreddy** [comment] 2020-04-13 06:54
> Change
>     with self.command_group('webapp config connection-string') as g:
>         g.custom_command('list', 'get_connection_strings', exception_handler=empty_on_404)
> 
> to
>     with self.command_group('webapp config connection-string') as g:
>         g.custom_command('list', 'get_connection_strings', exception_handler=empty_on_404, table_transformer='{Name:name, SlotSetting:slotSetting, Type:value.type, Value:value.value}')
> 
> I have not tested it. Search "table_transformer=" in the project, you can find many examples. You can customize the schema of table.

Thanks! will check.

**Comment by panchagnula** [comment] 2020-04-15 15:28
Fixed by change[12685]( https://github.com/Azure/azure-cli/pull/12865)

**Closed by panchagnula** 2020-04-15 15:28 UTC
Labels: Core, Web Apps
