### ISSUE TITLE
"az vm deallocate" and  "az vmss stop" no longer returns anything.

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli#18249] opened 2021-05-26 18:54 UTC
**Describe the bug**

We noticed the following commands no longer return anything for the Azure Stack 2020-09-01-hybrid profile:
 
az vm deallocate -g $WlkVMRG -n $vmName
az vmss stop -n $vmssName -g $vmssRgName --instance-ids 1
 
This is a breaking change and we are wondering if this is an intended change and that we should be updating our tests to reflect such a breaking change. We are currently using the Azure CLI nightly build MSI installation which has the same version (2.24.0) as the current Azure CLI build.

Debug output for az vm deallocate:

```
[DBG]: PS C:\test\Workloads\DeveloperExperience\CLI>> az vm deallocate -g $WlkVMRG -n $vmName --debug
az : DEBUG: cli.knack.log: File logging enabled - writing logs to 'C:\CloudDeployment\BVTs\Output\AZSDKTOOLSCTQ\CLITestLogs\VmDeploymentLogs'.
At line:1 char:1
+ az vm deallocate -g $WlkVMRG -n $vmName --debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (DEBUG: cli.knac...eploymentLogs'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEBUG: cli.knack.cli: Command arguments: ['vm', 'deallocate', '-g', 'clicanvrg', '-n', 'testvmcli', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x033F61D8>, <function OutputProducer.on_global_arguments at 0x03471070>, <function CLIQuery.on_global_arguments 
at 0x0358AC40>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'vm': ['azure.cli.command_modules.vm']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: vm                        0.306        44       221
DEBUG: cli.azure.cli.core: Total (1)                 0.306        44       221
DEBUG: cli.azure.cli.core: Loaded 44 groups, 221 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : vm deallocate
DEBUG: cli.azure.cli.core: Command table: vm deallocate
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03A72100>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\Administrator\.azure\commands\2021-07-01.09-58-11.vm_deallocate.10516.log'.
INFO: az_command_data_logger: command args: vm deallocate -g {} -n {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03AC4A00>, <function 
register_global_query_examples_argument.<locals>.register_query_examples at 0x03AC4AD8>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03AC4B20>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03AC4BB0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x034710B8>, <function CLIQuery.handle_query_parameter at 0x0358AC88>, <function 
register_global_query_examples_argument.<locals>.handle_example_parameter at 0x03AC4A90>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03AC4B68>]
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
DEBUG: cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.azurestackci14.onmicrosoft.com/d5fe0416-5be1-4147-b068-69453149fce4/.default',)
DEBUG: cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.azurestackci14.onmicrosoft.com/d5fe0416-5be1-4147-b068-69453149fce4'
DEBUG: cli.azure.cli.core.util: attempting to read file C:\Users\Administrator\.azure\accessTokens.json as utf-8-sig
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - Authority:Performing instance discovery: ...
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - Authority:Performing static instance discovery
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - Authority:Authority validated via static instance discovery
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - TokenRequest:Getting token from cache with refresh if necessary.
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - CacheDriver:Found 3 potential entries.
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - CacheDriver:Resource specific token found.
DEBUG: adal-python: 817e4cd6-298c-4f08-a701-3615eeac19a8 - CacheDriver:Returning token from cache lookup, AccessTokenId: <REDACTED>, RefreshTokenId: <REDACTED>
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 
'https://management.local.azurestack.external/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/resourceGroups/clicanvrg/providers/Microsoft.Compute/virtualMachines/testvmcli/deallocate?api-version=2020-06-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'POST'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '848cd4fb-da8d-11eb-a43f-0c42a122c4fa'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'vm deallocate'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.25.0 (MSI) azsdk-python-azure-mgmt-compute/21.0.0 Python/3.8.9 (Windows-10-10.0.17763-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.local.azurestack.external:443
DEBUG: urllib3.connectionpool: https://management.local.azurestack.external:443 "POST 
/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/resourceGroups/clicanvrg/providers/Microsoft.Compute/virtualMachines/testvmcli/deallocate?api-version=2020-06-01 HTTP/1.1" 202 0
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 202
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Location': 
'https://management.local.azurestack.external/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/providers/Microsoft.Compute/locations/local/operations/fa57c643-1e71-4150-9268-770ae6cfad20?monitor=true&api-version=2020-06-01'
DEBUG: cli.azure.cli.core.sdk.policies:     'Retry-After': '10'
DEBUG: cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 
'https://management.local.azurestack.external/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/providers/Microsoft.Compute/locations/local/operations/fa57c643-1e71-4150-9268-770ae6cfad20?api-version=2020-06-01'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-served-by': '00000000-0000-0000-0000-000000000000_0'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '498bb371-a73f-4358-b348-c5d2d8602ee9'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'WWW-Authenticate': 'oYG3MIG0oAMKAQChCwYJKoZIgvcSAQICooGfBIGcYIGZBgkqhkiG9xIBAgICAG+BiTCBhqADAgEFoQMCAQ+iejB4oAMCARKicQRv57bQTWeVZLW4L5xG2If9HUtFM4kk3v/mf5UUsa8EeaAwFk6kS6BXRJGXRKcCcq
Rv9V370cLxRTv9p9kdr2kL/J7Jk/mk+nmmgow2Nj7gSpPb2maPAedzgnHvrzepcCbdmn9tTA/y5eVoihEaecEz'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1193'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '498bb371-a73f-4358-b348-c5d2d8602ee9'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'LOCAL:20210701T165812Z:498bb371-a73f-4358-b348-c5d2d8602ee9'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 01 Jul 2021 16:58:12 GMT'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '0'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: 
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 
'https://management.local.azurestack.external/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/providers/Microsoft.Compute/locations/local/operations/fa57c643-1e71-4150-9268-770ae6cfad20?api-version=2020-06-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '848cd4fb-da8d-11eb-a43f-0c42a122c4fa'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'vm deallocate'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.25.0 (MSI) azsdk-python-azure-mgmt-compute/21.0.0 Python/3.8.9 (Windows-10-10.0.17763-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: https://management.local.azurestack.external:443 "GET 
/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/providers/Microsoft.Compute/locations/local/operations/fa57c643-1e71-4150-9268-770ae6cfad20?api-version=2020-06-01 HTTP/1.1" 200 134
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '134'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Retry-After': '60'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-served-by': '00000000-0000-0000-0000-000000000000_0'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'b4f867b2-ec24-4fa8-bae1-1c856e35b29f'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'WWW-Authenticate': 'oYG3MIG0oAMKAQChCwYJKoZIgvcSAQICooGfBIGcYIGZBgkqhkiG9xIBAgICAG+BiTCBhqADAgEFoQMCAQ+iejB4oAMCARKicQRv6dtxzLNoV16/rgD19fhJL4eRmnzB8UYLQwuOSGzBSEZ8rwfEQX/9G3Jwc0DmTG
bzSrR9gmXUz2/SC2DS3QsfhBP7AgW/1dN6X6/GYe8ssKfUDJDuIjUBqUP9HE/P9Hl/Guk8Dd0P2oXFzcCTpqre'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '14964'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'b4f867b2-ec24-4fa8-bae1-1c856e35b29f'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'LOCAL:20210701T165822Z:b4f867b2-ec24-4fa8-bae1-1c856e35b29f'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 01 Jul 2021 16:58:22 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {

  "startTime": "2021-07-01T16:58:12.4024994+00:00",

  "status": "InProgress",

  "name": "fa57c643-1e71-4150-9268-770ae6cfad20"

}
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 
'https://management.local.azurestack.external/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/providers/Microsoft.Compute/locations/local/operations/fa57c643-1e71-4150-9268-770ae6cfad20?api-version=2020-06-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '848cd4fb-da8d-11eb-a43f-0c42a122c4fa'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'vm deallocate'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.25.0 (MSI) azsdk-python-azure-mgmt-compute/21.0.0 Python/3.8.9 (Windows-10-10.0.17763-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: https://management.local.azurestack.external:443 "GET 
/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/providers/Microsoft.Compute/locations/local/operations/fa57c643-1e71-4150-9268-770ae6cfad20?api-version=2020-06-01 HTTP/1.1" 200 184
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '184'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-served-by': '00000000-0000-0000-0000-000000000000_0'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e669f8bb-44b0-4b60-a002-021b9cd7f93b'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'WWW-Authenticate': 'oYG3MIG0oAMKAQChCwYJKoZIgvcSAQICooGfBIGcYIGZBgkqhkiG9xIBAgICAG+BiTCBhqADAgEFoQMCAQ+iejB4oAMCARKicQRv3xLkR+5k4aI34SiGhOqDi7lvTbsa85sQUgbR3YX2ADRq4PLfbHuBW8j1fN9yZp
XZxeY8QXICDSqLqMQIFq9hcjJGOSTZjIqzF++W4U8rgxeWNuKqWzRlTPVSrDyjVM/ByQNRhXAEHh2MC4lalymc'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '14963'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'e669f8bb-44b0-4b60-a002-021b9cd7f93b'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'LOCAL:20210701T165922Z:e669f8bb-44b0-4b60-a002-021b9cd7f93b'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 01 Jul 2021 16:59:22 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {

  "startTime": "2021-07-01T16:58:12.4024994+00:00",

  "endTime": "2021-07-01T16:59:04.8114829+00:00",

  "status": "Succeeded",

  "name": "fa57c643-1e71-4150-9268-770ae6cfad20"

}
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 
'https://management.local.azurestack.external/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/providers/Microsoft.Compute/locations/local/operations/fa57c643-1e71-4150-9268-770ae6cfad20?monitor=true&api-version=2020-06-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '848cd4fb-da8d-11eb-a43f-0c42a122c4fa'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'vm deallocate'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.25.0 (MSI) azsdk-python-azure-mgmt-compute/21.0.0 Python/3.8.9 (Windows-10-10.0.17763-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: https://management.local.azurestack.external:443 "GET 
/subscriptions/79dc96c4-01b4-498e-910e-cb21b5c44860/providers/Microsoft.Compute/locations/local/operations/fa57c643-1e71-4150-9268-770ae6cfad20?monitor=true&api-version=2020-06-01 HTTP/1.1" 200 0
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-served-by': '00000000-0000-0000-0000-000000000000_0'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '20490cd1-0028-488d-9dda-c78346f1383b'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'WWW-Authenticate': 'oYG3MIG0oAMKAQChCwYJKoZIgvcSAQICooGfBIGcYIGZBgkqhkiG9xIBAgICAG+BiTCBhqADAgEFoQMCAQ+iejB4oAMCARKicQRv5VSKntB8fX6DvF1xi6/eEfD8sP2VPhTZdMscogss1zAGHI6OKPhn1W43/0ezAD
LyWNgNF3P+cqtg+Ts8i8BdU0loEnvMXxDa7nPCg6drlEz7l/D/euRUzL+QBXj9zKP0aQjs/3/j5q6+NZDWQGd1'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '14962'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '20490cd1-0028-488d-9dda-c78346f1383b'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'LOCAL:20210701T165922Z:20490cd1-0028-488d-9dda-c78346f1383b'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 01 Jul 2021 16:59:22 GMT'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '0'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: 
DEBUG: cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x03AA7BF8>, <function _x509_from_base64_to_hex_transform at 0x03AA7C40>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnFilterResult []
DEBUG: cli.knack.cli: Event: Cli.SuccessfulExecute []
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03A72220>]
INFO: az_command_data_logger: exit code: 0
INFO: cli.__main__: Command ran in 72.116 seconds (init: 0.303, invoke: 71.813)
INFO: telemetry.save: Save telemetry record of length 2964 in cache
WARNING: telemetry.check: Negative: The C:\Users\Administrator\.azure\telemetry.txt was modified at 2021-07-01 09:52:48.717762, which in less than 600.000000 s
```

**To Reproduce**

1. Install Azure CLI.
2. Register for 2020-09-01-hybrid profile?
            az cloud register --name $TntAdminEnvironmentName `
                 --endpoint-resource-manager $asEndpoints.ResourceManagerEndpoint `
                 --suffix-storage-endpoint $asEndpoints.StorageEndpointSuffix `
                 --suffix-keyvault-dns ("." + $asEndpoints.AzureKeyVaultDnsSuffix) `
                 --endpoint-vm-image-alias-doc https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json `
                 --profile 2020-09-01-hybrid

4. Create a VM and VMSS.
5. Run the following commands:
az vm deallocate
az vmss stop

**Expected behavior**
The commands `az vm deallocate` and `az vmss stop` should return something.

**Environment summary**

Using windows powershell. Installed Azure CLI from here:
https://aka.ms/InstallAzureCliWindowsEdge

**Comment by yonzhan** [comment] 2021-05-27 01:59
Compute

**Comment by zhoxing-ms** [comment] 2021-05-28 07:33
This problem is caused by the change of Python SDK in the new api-version.

1. When building `ARMPolling`, there is no declaration of `lro_options={'final-state-via': 'azure-async-operation'}` in the SDK of new api-version, so `LocationPolling` will be executed once at the last time to send out an additional polling request containing `monitor=true` parameter.

The code of new api-version: [code link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2020_06_01/operations/_virtual_machine_scale_sets_operations.py#L1182)
The code of old api-version: [code link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/operations/_virtual_machine_scale_sets_operations.py#L1213)

When the request contains parameter `monitor=true`, the returned data will not be obtained.
![Screenshot 2021-05-28 104404](https://user-images.githubusercontent.com/16612065/119947030-dc487580-bfc9-11eb-887a-2802e2835d3c.png)
And the last request will overwrite the data that has been obtained in the previous polling request from `AzureAsyncOperationPolling` and become no data
![Screenshot 2021-05-28 152808](https://user-images.githubusercontent.com/16612065/119947052-e2d6ed00-bfc9-11eb-9f25-c1df6a8bbd39.png)

2. Deserialized data not returned in method `get_long_running_output()`
The code of new api-version: [code link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2020_06_01/operations/_virtual_machine_scale_sets_operations.py#L1172)
The code of old api-version: [code link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/operations/_virtual_machine_scale_sets_operations.py#L1200)

The change of SDK should be caused by the modification of swagger from service team, which needs the service team to confirm whether these changes meet the expectation.
If it does not meet the expectation, the service team needs to modify the swagger and then conduct the generation of new Python SDK.

**Comment by Vaibhav-Agar** [comment] 2021-06-03 15:00
@avirishuv can you please take a look?

**Comment by avirishuv** [comment] 2021-06-15 17:17
Following up to identify the specific change needed on the swagger side.

**Comment by Sandido** [comment] 2021-06-23 14:13
As per @zhoxing-ms 's  investigation.
The swagger line for ‘[final-state-via](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json#L2056)’ seen in 2017-12 was removed in the next release in [2018-04](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-04-01/compute.json#L2289). I am confident that Python SDKs have released since then. If the customer is only now updating from the 2017-12 version of the Python SDK then this would be the cause of the problem. 
If not, then the issue is likely caused by something else. 

The only other changes in the Swagger for the VIrtualMachines_PowerOff operation between 2017-12 and 2018-04 is the removal of 
1)	["schema": {
              "$ref": "#/definitions/OperationStatusResponse"](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json#L2047)
This would reduce what is present in the outputted response. It removed [this content](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json#L8107). 
Is this the content expected in the response that is missing? @TheOnlyWei , @zhoxing-ms .

2)	@avirishuv , the CRP VM team should know more as to what these Swagger changes accomplish and what API changes / standard were made to need these swagger changes. See our email thread.

**Comment by zhoxing-ms** [comment] 2021-06-24 02:33
> Is this the content expected in the response that is missing?

@Sandido Yes, exactly. 

By the way, may I ask why did Swagger make these changes?

**Comment by Sandido** [comment] 2021-06-24 19:42
All of these OperationStatusResponse values were removed from Post operations when the 2018-04 version was released. 
Looks like this was done to fix an issue with the responses, though I don't have the details. 

But for this Github issue, it looks like it can be resolved as By Design.

**Comment by TheOnlyWei** [comment] 2021-07-01 16:07
@Sandido We are still discussing this in the email. Seems like Azure CLI is returning the wrong HTTP response. Hyonho Lee from the email said the OperationStatusResponse was returned in HTTP response call, but the wrong response was returned, resulting in empty response.

**Comment by zhoxing-ms** [comment] 2021-07-02 06:58
@TheOnlyWei Hi, we already know this issue, which I mentioned in the first point of this comment
https://github.com/Azure/azure-cli/issues/18249#issuecomment-850214659

This is also due to swagger's modification:
> When building ARMPolling, there is no declaration of lro_options={'final-state-via': 'azure-async-operation'} in the SDK of new api-version, so LocationPolling will be executed once at the last time to send out an additional polling request containing monitor=true parameter.

**Comment by avirishuv** [comment] 2021-07-14 20:24
@TheOnlyWei Based on the comments above and internal discussion, the changes were made in 2018-04 release and are by design. Closing this thread as discussed. 

If there are additional questions on this topic, feel free to reopen.

**Closed by avirishuv** 2021-07-14 20:24 UTC
Labels: Compute, Service Attention
