### ISSUE TITLE
Error when creating resource group

### ISSUE THREAD

**Issue by wangdian** [Azure/azure-cli#12540] opened 2020-03-11 09:03 UTC
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group create --name {} --location {} --subscription {}`

## Environment Summary
```
Linux-4.4.0-174-generic-x86_64-with-Ubuntu-16.04-xenial
Python 2.7.12
Shell: bash

azure-cli 2.0.76 *

```

**Comment by yonzhan** [comment] 2020-03-11 10:03
add to S168

**Comment by zhoxing-ms** [comment] 2020-04-07 03:01
@wangdian Hi, I can't reproduce your question. Could you please provide more specific parameter information? Placeholders can be used instead of sensitive privacy information.

**Comment by yonzhan** [comment] 2020-04-11 08:08
@wangdian any update or feedback?

**Comment by zhoxing-ms** [comment] 2020-04-28 08:36
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-04-28 08:36 UTC
Labels: ARM, OKR3.2 Candidate, feature-request
