### ISSUE TITLE
Multiple NICs applied to Windows server inconsistently

### ISSUE THREAD

**Issue by GuyMacguffin** [Azure/azure-cli#3005] opened 2017-04-26 20:03 UTC
### Description
Azure CLI 2.0 applies NICs inconsistently

Steps to reproduce:

Create two NICs: NIC1. NIC2
Create a windows server 2012 R2 VM with the two NICs
Wait for Windows VM to launch and then log in to the machine and check the interfaces
Results:
Sometimes NIC1 = ethernet1 and NIC2=ethernet2 on the OS and sometimes NIC1 = ethernet2 and NIC2=ethernet1. This did not reproduce when using CLI v1, the first NIC applied was always ethernet1. Is there any way to get this consistent?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.1

**OS Version:** What OS and version are you using?  
Answer here: Win7 64

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd

**Comment by GuyMacguffin** [comment] 2017-05-04 22:55
Is this issue going to be addressed? Are there any possible workarounds?

**Comment by tjprescott** [comment] 2017-05-08 19:02
@GuyMacguffin to clarify, do the NIC assignments change potentially with each restart of the VM?  Or do you observe the behavior only after running VM create?

**Comment by GuyMacguffin** [comment] 2017-05-08 19:50
I observed the behavior after running VM create.

**Comment by tjprescott** [comment] 2017-05-08 21:49
I have not been able to reproduce this issue. I added a unit test to verify that CLI creates the same NIC array in a stable order for the same input. I got consistent results when I created multi-NIC VMs in terms of which Windows Server said was Ethernet and Ethernet 2.

To TS further, please try the following:
1) Update to the latest release (vm module will be 2.0.5).
2) When you deploy your multi-nic VM, first run it with --validate --verbose and save the data between the "==== BEGIN TEMPLATE ====" and "==== END TEMPLATE ====" tags. This represents the ARM template that is generated to actually create your VM. If the CLI is the source of this issue, there will be a difference in the "networkProfile" section of these two templates. If both configurations result from the same ARM template, then the issue likely exists in the service or the OS.

To better understand your scenario, I have a few questions:
1.  How often do you create your multi-NIC VMs?
2.  How often do you observe this switching behavior? I.e. is it 50-50 or does it usually favor one configuration?
3. How does this behavior inhibit your workflow?

**Comment by GuyMacguffin** [comment] 2017-05-11 19:15
I updated to the latest version (vm module is on 2.0.6). I'm still seeing the issue reproduce. I tried redeploying the VM 5 times and only 1 of those tries did the first NIC in the list become the first NIC on the OS. 

I tried running with the --validate --verbose options 10 times and each time had the same networkProfiles output. I can see my first NIC is marked primary. It sounds like this is a service or OS issue, should I engage the Azure support team? They sent me here in the first place.

1. The product I'm installing on the VM requires multiple NICs. All VMs will have this setup.
2. As mentioned earlier the switching behavior is happening more often than not (4 out 5 tests)
3. We are creating a deploy-able image with settings reliant on the NICs, if they are inconsistently applied this would break

**Comment by tjprescott** [comment] 2017-05-11 20:06
@GuyMacguffin thanks for the response.

We've ruled out that it has to do with the order the CLI sends the NICs in. 

`az vm show -g {rg} -n {name} --query networkProfile`
If you run this in each case, do you notice anything different between the two?

Xplat calls the Compute APIs directly while AzureCLI 2.0 builds an ARM template deployment which orchestrates the creation of (potentially) many different resources. If you notice that the resulting NetworkProfile is different in these two situations, that would suggest to me that ARM is the culprit.

If you observe the problematic behavior and the NetworkProfile is the same, then I'd suggest the issue has to be within the Compute service itself or the OS.

**Comment by GuyMacguffin** [comment] 2017-05-16 18:04
The NetworkProfile from the command you gave me is the same if it's in the correct or incorrect order. By your conclusions this indicates an issue with the Compute service itself or the OS.

**Comment by tjprescott** [comment] 2017-05-16 18:35
It does look that way.

**Comment by GuyMacguffin** [comment] 2017-05-17 16:40
Thanks @tjprescott. What are the next steps I need to perform to continue working on this issue? Do I need to engage another team?

**Comment by tjprescott** [comment] 2017-05-17 17:18
Open a new support ticket or re-engage an existing support ticket if you have one. Reference this thread so they can see what troubleshooting we have done to rule out the CLI/SDK as the cause. They should then engage the service team, as they are best positioned to identify the cause of your issue.

**Comment by tjprescott** [comment] 2017-06-02 16:02
Closing this issue as it doesn't seem we have any control over this via the CLI.

**Closed by tjprescott** 2017-06-02 16:02 UTC
Labels: Compute, Network, Question, ServiceAttn
