### ISSUE TITLE
Create group deployment cannot handle the letter Ä.

### ISSUE THREAD

**Issue by DLHForsberg** [Azure/azure-cli#11963] opened 2020-01-28 12:43 UTC
**Describe the bug**
When running `az group deployment create` on a resource group that contains the letter Ä an unexpected error happens.

**To Reproduce**
Create a resource group named something with the letter Ä, for instance `RegionVästerbotten` and run a  `az group deployment create` template from either WSL, PowerShell or Azure template deployment.

**Expected behavior**
Expect the deployment to proceed and deploy the resources specified.

**Environment summary**
Az Version 2.0.80
Bash on Windows
PowerShell

**Additional context**
Below is the error from the terminal.
It says the template deployment is not valid but running `az group deployment validate` will indicate everything is fine and the problem was solved by creating a new resourcegroup without the letter Ä.

```
--- Logging error ---
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 941, in deploy_arm_template
    no_wait=no_wait, aux_subscriptions=aux_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 289, in _deploy_arm_template_core
    return sdk_no_wait(no_wait, smc.deployments.create_or_update, resource_group_name, deployment_name, properties)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 383, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/opt/az/lib/python3.6/logging/__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 379: ordinal not in range(128)
Call stack:
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 47, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'infrastructure-as-code' is not valid according to the validation procedure. The tracking id is 'e8fe15e6-0d41-42ac-90cb-044789bc5040'. See inner errors for details.",)
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 941, in deploy_arm_template
    no_wait=no_wait, aux_subscriptions=aux_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 289, in _deploy_arm_template_core
    return sdk_no_wait(no_wait, smc.deployments.create_or_update, resource_group_name, deployment_name, properties)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 383, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/opt/az/lib/python3.6/site-packages/knack/log.py", line 78, in format
    msg = logging.StreamHandler.format(self, record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/opt/az/lib/python3.6/logging/__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 379: ordinal not in range(128)
Call stack:
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 47, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'infrastructure-as-code' is not valid according to the validation procedure. The tracking id is 'e8fe15e6-0d41-42ac-90cb-044789bc5040'. See inner errors for details.",)
Arguments: ()
```

**Comment by yonzhan** [comment] 2020-01-29 02:04
add to S165.

**Comment by yonzhan** [comment] 2020-03-08 02:56
add to S168

**Comment by zhoxing-ms** [comment] 2020-03-11 07:35
@DLHForsberg Hi, I did some tests according to my understanding of the problem, but I can't reproduce the problem. Could you please give me some specific information?
Please send me the template of deployment and command parameters you used by email (replace the confidential information with other string). My email address is Zhou.Xing@microsoft.com, Thank you~

**Comment by zhoxing-ms** [comment] 2020-03-12 08:38
@DLHForsberg Thank you for the templates and parameters provided in your email. I simplified the templates and parameters, and found that the command can be executed successfully, and the problem should not be related to Ä or ä.
Because I don't have the resources in your environment (such as keyvault), it's not easy for me to reproduce your problem. 
According to the error log you provided on github, the actual reason for the problem should be:
> Message: CloudError("The template deployment 'infrastructure-as-code' is not valid according to the validation procedure. The tracking id is 'e8fe15e6-0d41-42ac-90cb-044789bc5040'. See inner errors for details.",)

So I also need some of your log information:
1. You can view the Activity log of the Resource Group(like: RegionVästerbotten) on the portal after the deployment operation fails. After clicking the failed operation name, there is a JSON information corresponding to the failure reason, then tell me what is the error message of the failure?
2. If there is no obvious clue in step 1, Could you add --debug to the original command? And then please show me the information returned by debug.

Could you please provide the above information?

**Comment by zhoxing-ms** [comment] 2020-03-13 05:39
By the way, there is another unreasonable phenomenon: when the error message contains special characters, it will print a lot of less related error logs more than when there are no special characters in the error message.
The reason for this phenomenon is related to the bug of msrestazure-for-python: Azure/msrestazure-for-python#143. When calling the logging library to print the log, we encountered an exception raised by the __str__ method of msrestazure, which triggered the logic of printing all call stacks. This problem needs to wait for the msrestazure-for-python to be fixed.

**Comment by zhoxing-ms** [comment] 2020-03-16 07:15
@DLHForsberg Any update?

**Comment by zhoxing-ms** [comment] 2020-03-24 08:35
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-03-24 08:35 UTC
Labels: ARM, Feature Request, OKR3.2 Candidate, customer-response-expected
