### ISSUE TITLE
Incorrect prompt format while running `az --version` on old version cli client

### ISSUE THREAD

**Issue by bim-msft** [Azure/azure-cli#11673] opened 2019-12-26 08:54 UTC
**Describe the bug**
![微信截图_20191226164702](https://user-images.githubusercontent.com/3250203/71468018-99480880-27ff-11ea-8903-9598fa9c1025.png)

**To Reproduce**
Run `az --version` on old version cli

**Environment summary**
azure-cli dev branch 93a50bb
knack 0.6.3
```
azure-cli                         2.0.76 *

command-modules-nspkg              2.0.3
core                              2.0.76 *
nspkg                              3.0.4
telemetry                          1.0.4
testsdk                            0.2.4

Extensions:
interactive                        0.4.3
azure-firewall                     0.1.3 (dev) D:\repos\azure-cli-extensions\src\azure-firewall
```

**Comment by bim-msft** [comment] 2019-12-26 08:55
@jiasli Please take a look.

**Comment by jiasli** [comment] 2019-12-26 09:21
The issue is fixed in https://github.com/Azure/azure-cli/pull/11609. Please reinstall the latest version.

**Closed by jiasli** 2019-12-26 09:21 UTC
Labels: Core
