### ISSUE TITLE
I got an error while trying to install the kubectl tool on cloudshell. Is there an alternative way to achieving that?

### ISSUE THREAD

**Issue by haybeewhy** [Azure/azure-cli#22535] opened 2022-05-19 21:57 UTC
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpiqroks6p/bin/linux_amd64/kubelogin' -> '/usr/local/bin/kubelogin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 369, in k8s_install_cli
    k8s_install_kubelogin(cmd, kubelogin_version,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 496, in k8s_install_kubelogin
    shutil.move(download_path, install_location)
  File "/opt/az/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/opt/az/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/az/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli --install-location={}`

## Environment Summary
```
Linux-5.4.0-1078-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
ai-examples 0.2.5
ssh 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-05-20 00:03
route to CXP team

**Comment by navba-MSFT** [comment] 2022-05-20 04:37
Duplicate of https://github.com/Azure/azure-cli/issues/22536

**Closed by navba-MSFT** 2022-05-20 04:37 UTC
Labels: AKS, customer-reported, CXP Attention, Auto-Assign
