### ISSUE TITLE
SUSE images in azure cli do not have a "default" image.

### ISSUE THREAD

**Issue by susegrant** [Azure/azure-cli#19069] opened 2021-07-31 01:46 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

According to the azcli's "az vm create --help" output, each
distribution (publisher) should have some kind of "default" image.

##### BEGIN EXAMPLE #####
user@hostname:/> az vm create --help |grep Ubuntu
    Create a default Ubuntu VM with automatic SSH authentication.
        az vm create -n MyVm -g MyResourceGroup --image UbuntuLTS
[...]
##### END EXAMPLE #####

In checking the "Canonical" images, and more specifically, where this
"UbuntuLTS" comes from, the label in the cli help example is the "urnAlias".
Based on the --help output, one should be able to use this "urnAlias" by
itself to spin up a new "default" image.

##### BEGIN EXAMPLE #####
user@hostname:/> az vm image list -p Canonical
You are viewing an offline list of images, use --all to retrieve an up-to-date list
[
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "18.04-LTS",
    "urn": "Canonical:UbuntuServer:18.04-LTS:latest",
    "urnAlias": "UbuntuLTS",
    "version": "latest"
  }
]
##### END EXAMPLE #####

One can specify the full default image "urn" as well as short "urnAlias" for
the "--image" flag when setting up a system with 'az vm create'.

##### BEGIN EXAMPLE #####
user@hostname:/> az vm create --image UbuntuLTS --name ubuntu-test --ssh-key-value ~/.ssh/id_rsa.pub
{
  "fqdns": "",
  "id": "/subscriptions/01234567-89ab-cdef-0123-456789abcdef/resourceGroups/test-resource-group/providers/Microsoft.Compute/virtualMachines/ubuntu-test",
  "location": "westus2",
  "macAddress": "01-23-45-67-89-AB",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.4",
  "publicIpAddress": "x.x.x.x",
  "resourceGroup": "test-resource-group",
  "zones": ""
}
##### END EXAMPLE #####

This same syntax works perfectly fine for RedHat as well.

##### BEGIN EXAMPLE ######
user@hostname:/> az vm image list -p RedHat
You are viewing an offline list of images, use --all to retrieve an up-to-date list
[
  {
    "offer": "RHEL",
    "publisher": "RedHat",
    "sku": "7-LVM",
    "urn": "RedHat:RHEL:7-LVM:latest",
    "urnAlias": "RHEL",
    "version": "latest"
  }
]
user@hostname:/> az vm create --image RHEL --name rhel-test --ssh-key-value ~/.ssh/id_rsa.pub
{
  "fqdns": "",
  "id": "/subscriptions/01234567-89ab-cdef-0123-456789abcdef/resourceGroups/test-resource-group/providers/Microsoft.Compute/virtualMachines/rhel-test",
  "location": "westus2",
  "macAddress": "01-23-45-67-89-AB",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.5",
  "publicIpAddress": "x.x.x.x",
  "resourceGroup": "test-resource-group",
  "zones": ""
}
##### END EXAMPLE #####

**To Reproduce**

This same syntax does not work for SUSE or openSUSE images when using either the urnAlias or urn in the "default" offering.

###### BEGIN EXAMPLE ######
user@hostname:/> az vm image list -p SUSE
You are viewing an offline list of images, use --all to retrieve an up-to-date list
[
  {
    "offer": "openSUSE-Leap",
    "publisher": "SUSE",
    "sku": "42.3",
    "urn": "SUSE:openSUSE-Leap:42.3:latest",
    "urnAlias": "openSUSE-Leap",
    "version": "latest"
  },
  {
    "offer": "SLES",
    "publisher": "SUSE",
    "sku": "15",
    "urn": "SUSE:SLES:15:latest",
    "urnAlias": "SLES",
    "version": "latest"
  }
]
user@hostname:/> az vm create --image SLES --name sles-test --ssh-key-value ~/.ssh/id_rsa.pub
(InvalidTemplateDeployment) The template deployment 'vm_deploy_FU6AQDNtc5eDrQeWpXdtJ4Y7apQBLTr5' is not valid according to the validation procedure. The tracking id is '9bd1f1c8-a2dc-4519-8fce-70c9db48b25d'. See inner errors for details.
user@hostname:/> az vm create --image openSUSE-Leap --name leap-test --ssh-key-value ~/.ssh/id_rsa.pub
(InvalidTemplateDeployment) The template deployment 'vm_deploy_RykhV8NAfwiZE4s8VjL3JzW1KWP4RP2D' is not valid according to the validation procedure. The tracking id is '8a7f6d12-5c1d-404b-8818-658a4de5e6c2'. See inner errors for details.
###### END EXAMPLE ######

**Expected behavior**
This syntax, by convention, should spin up a new Azure image of a default version of SLES and openSUSE.

**Environment summary**
azure-cli package must be installed and it must be configured with a valid Azure subscription.

**Additional context**
Ideally, the default image should point to a generic SLES (Non-SAP) PAYG image for "SLES" and the latest PAYG Leap image for "openSUSE-Leap"  here.  If a user needs a more specific product/image version, they can search for it with az vm image list -p SUSE --all.

**Comment by yonzhan** [comment] 2021-07-31 01:58
@zhoxing-ms to help with

**Comment by zhoxing-ms** [comment] 2021-08-03 08:03
Actually, This issue is a service issue. The specific error messages returned by service are as follows:
```json
{
    "error": {
        "code": "InvalidTemplateDeployment", 
        "message": "The template deployment 'vm_deploy_VCmU39nDHDjoukH7x8tRz1DbkC15aZ7M' is not valid according to the validation procedure. The tracking id is '78c203f6-59ad-44a7-b881-d2ec47a2d1be'. See inner errors for details.", 
        "details": [
            {
                "code": "InvalidParameter", 
                "target": "imageReference", 
                "message": "The following list of images referenced from the deployment template are not found: Publisher: SUSE, Offer: SLES, Sku: 15, Version: latest. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images."
            }
        ]
    }
}
```
This seems to be caused by the image not being found. It is uncertain whether the data of some images in the offline file ([file url](https://github.com/Azure/azure-rest-api-specs/blob/main/arm-compute/quickstart-templates/aliases.json)) used by CLI has expired. This requires the service team to investigate the specific reasons.

**x-ms-correlation-request-id: 78c203f6-59ad-44a7-b881-d2ec47a2d1be**

**Comment by axayjo** [comment] 2021-08-03 22:30
@amjads1 can you take a look at this issue?

**Comment by susegrant** [comment] 2021-09-01 19:48
It's been about a month since the last comment.  

Any update on this issue?

**Comment by yonzhan** [comment] 2021-09-01 22:33
@amjads1 any update for this?

**Comment by amjads1** [comment] 2021-09-09 07:17
@susegrant Apologies for the delay response here. Based on the information provided on this issue by @zhoxing-ms, issue seems to be related to images being outdated but needs further investigation to confirm the same and fix it accordingly. I should have more details to share by end of this week.

**Comment by amjads1** [comment] 2021-09-23 07:00
@susegrant I have reached out to the engineering team to get further clarification on the issue and hoping to have an update within 1-2 days. Thanks for your patience!

**Comment by amjads1** [comment] 2021-10-08 05:52
@susegrant As we are looking into the issue, it seems that there's no default image and you may need to go with the latest version. While we continue to look for other possible use cases, can you try with the latest version and confirm?

**Comment by amjads1** [comment] 2021-11-04 19:29
@susegrant Thanks for the confirmation! I'm currently working with the CLI and other service teams internally to understand why the above syntax you have shared is not working for SLES images. 

I will update back as soon as I have more information on the root cause and next steps to fix this issue. Thanks for your patience!

**Comment by zhoxing-ms** [comment] 2021-12-09 08:17
Fixed by this PR https://github.com/Azure/azure-rest-api-specs/pull/16707

**Closed by zhoxing-ms** 2021-12-09 08:17 UTC
Labels: Compute, Service Attention
