### ISSUE TITLE
is:issue is:open az login fails on fresh OpenSUSE Leap 15.1

### ISSUE THREAD

**Issue by slowik21861** [Azure/azure-cli#9485] opened 2019-05-27 18:10 UTC
marek@opensuse151:~/Pobrane> az login
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 530, in get_default_cli
    help_cls=AzCliHelp)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 60, in __init__
    register_ids_argument(self)  # global subscription must be registered first!
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 181, in register_ids_argument
    from msrestazure.tools import parse_resource_id, is_valid_resource_id
  File "/usr/lib64/az/lib/python2.7/site-packages/msrestazure/__init__.py", line 28, in <module>
    from .azure_configuration import AzureConfiguration
  File "/usr/lib64/az/lib/python2.7/site-packages/msrestazure/azure_configuration.py", line 34, in <module>
    from msrest import Configuration
  File "/usr/lib64/az/lib/python2.7/site-packages/msrest/__init__.py", line 28, in <module>
    from .configuration import Configuration
  File "/usr/lib64/az/lib/python2.7/site-packages/msrest/configuration.py", line 37, in <module>
    from .pipeline import Pipeline
  File "/usr/lib64/az/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 41, in <module>
    import xml.etree.ElementTree as ET
ImportError: No module named xml.etree.ElementTree

**Comment by adewaleo** [comment] 2019-05-28 17:49
Please try to include more information!. It helps us help you:

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by slowik21861** [comment] 2019-05-28 20:09
Bug description:
Trying to login win Azure CLI (az login) produced error instead of asking for login name.
To reproduce:
Fresh install of OpenSUSE 15.1 in virtual machine. All recommended updates installed.
Expected behavior:
Command prompt asking for login name and password to Azure.
Environment summary:
OpenSUSE 15.1 x64 default install with GNOME in Vmware Fusion 11.1.0.
Install method: zyppier. Azure CLI version: 2.0.66. Shell type: Bash.

**Comment by marstr** [comment] 2019-05-28 21:30
Howdy @slowik21861, did you install using the EL7 RPM, or using pip?

**Comment by marstr** [comment] 2019-05-28 21:31
Regardless, try using zypper to install `python-base` and `python-xml`.

**Comment by Arnavion** [comment] 2019-06-01 04:24
Yeah, this is problem 2 in https://github.com/Azure/azure-cli/issues/7523 ; installing `python-xml` will resolve it. (`python-base` must already be there to be able to get as far as this error.)

**Comment by marstr** [comment] 2019-06-17 20:43
Closing this as a dupe of #7523

**Closed by marstr** 2019-06-17 20:43 UTC
Labels: Packaging
