### ISSUE TITLE
Can't login to az

### ISSUE THREAD

**Issue by wi5nia** [Azure/azure-cli#4375] opened 2017-09-05 09:58 UTC
### Description
**Outline the issue here:** 
When doing the command: az login I get the URL and code. I coy&paste the URL into a browser and than c&p the code. 
The page asks me to choose a login, I do so and then it refreshes to the code page again. I can enter the code again and the process starts again. I've tried Edge, Chrome, Opera - everywhere the same.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.15)

acr (2.0.11)
acs (2.0.14)
appservice (0.1.14)
batch (3.1.2)
billing (0.1.4)
cdn (0.0.7)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.9)
core (2.0.14)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.8)
iot (0.1.11)
keyvault (2.0.8)
lab (0.0.10)
monitor (0.0.9)
network (2.0.13)
nspkg (3.0.1)
profile (2.0.11)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.13)
role (2.0.11)
servicefabric (0.0.2)
sf (1.0.7)
sql (2.0.10)
storage (2.0.13)
vm (2.0.13)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise Version 1703 (OS Build 15063.540)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by tjprescott** [comment] 2017-09-05 15:34
This is a duplicate of #4338 and is being investigated. Are you able to login using `-u {username}`?

**Closed by tjprescott** 2017-09-05 15:34 UTC

**Comment by wi5nia** [comment] 2017-09-06 07:00
Then I get this:

tomaszwi@SP4TW C:\Users\tomaszwi
$ az login -u tomaszwi@microsoft.com
Password:
Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50079: The user is required to use multi-factor authentication.\r\nTrace ID: c3a51f74-adaa-40eb-86a0-447ceb880300\r\nCorrelation ID: 47554fc5-a5c0-4a99-854c-600036c81cfa\r\nTimestamp: 2017-09-06 06:59:35Z","error_codes":[50079],"timestamp":"2017-09-06 06:59:35Z","trace_id":"c3a51f74-adaa-40eb-86a0-447ceb880300","correlation_id":"47554fc5-a5c0-4a99-854c-600036c81cfa"}

Regards,
Tomasz

Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Travis Prescott<mailto:notifications@github.com>
Wysłano: Tuesday, September 5, 2017 17:36
Do: Azure/azure-cli<mailto:azure-cli@noreply.github.com>
DW: Tomasz Wisniewski<mailto:tomasz.wisniewski@windowslive.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [Azure/azure-cli] Can't login to az (#4375)


This is a duplicate of #4338<https://github.com/Azure/azure-cli/issues/4338> and is being investigated. Are you able to login using -u {username}?

**Comment by tjprescott** [comment] 2017-09-06 17:20
This is an annoying problem and I've experienced it myself.  Here are some things you might try while the fix is pending:

1. Try different browsers
2. When you navigate to the browser you may see a window that says "You are using the old/new sign-in experience".  Try clicking the link to try with the newer/older method.  I have had that work.

**Comment by wi5nia** [comment] 2017-09-06 18:14
I've tried all browsers. Tried the both methods. All the same.

Regards,
Tomasz

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tjprescott** [comment] 2017-09-06 18:26
In that case, I would recommend you log in to the Portal and open a support ticket. They will likely contact us and we can steer them from there.
