### ISSUE TITLE
Improve `--pattern` documentation with additional examples

### ISSUE THREAD

**Issue by tomfaltesek** [Azure/azure-cli#10382] opened 2019-08-30 14:51 UTC
**Resource Provider**
Azure Storage Blobs

**Description of Work Requested**
I'd like to suggest expanding the documentation around the `--pattern` parameter. Specifically, there is a lack of examples for common globbing scenarios. The tools for powerful patterns seem to be available, but the exact syntax required to achieve certain outcomes is not obvious.

I opened [this SO question](https://stackoverflow.com/questions/57713726/azure-cli-storage-blob-delete-batch-to-delete-all-blobs-excluding-two-directori) about making an exclusion pattern for the `az storage blob delete-batch` command. You can find [other folks](https://stackoverflow.com/questions/52070362/azure-cli-storage-delete-batch-with-exclude-pattern) having trouble with [different scenarios](https://stackoverflow.com/questions/56046447/azure-storage-copy-list-of-blobs).

I'm sure you can think of many example patterns that one might want to use, but here's a quick brain dump:

- Delete everything except for one specific directory
- Delete everything except for multiple specific directories
- Delete everything in a specific nested directory
- Delete all but one particular blob in a specific nested directory
- Delete everything from a specific directory that matches an extension (\*.txt)
- Delete everything from a specific directory that matches multiple extensions (\*.txt or \*.html)
- Delete everything from a specific directory that does NOT match an extension (\*.txt)
- Delete everything from a specific directory that does NOT match multiple extensions (\*.txt or \*.html)

Providing such examples in the documentation will help others to form the correct patterns for their needs.

**Comment by Juliehzl** [comment] 2019-08-31 01:28
@tomfaltesek  Thanks for your suggestion.  I think you can try our new `az storage remove`  command with `--exclude` flag, which is in preview now. Wait for you feedback😊

**Comment by tomfaltesek** [comment] 2019-09-03 14:52
Thanks for the reply, @Juliehzl. The `az storage remove` command with the `--exclude` flag looks like it should work fine. Although, that command was added in version 2.0.70 of the Azure CLI and my Azure DevOps build agent currently has version 2.0.68.

Fortunately, I can use [the answer to this SO question](https://stackoverflow.com/questions/57713726/azure-cli-storage-blob-delete-batch-to-delete-all-blobs-excluding-two-directori) to exclude directories with the existing Azure CLI commands.

Regardless of the new `az storage remove` command, consumers may want more detailed documentation on the `--pattern` parameter. Not only is it available for the `az storage blob delete-batch`, but it can also be used in the `az storage blob download-batch` and `az storage blob upload-batch`.

**Comment by bacongobbler** [comment] 2019-12-03 21:29
Adding a few more use cases to the list for after using `az storage blob upload-batch --pattern`:

- upload everything with a particular file extension (*.txt)
- upload everything with a particular file extension somewhere in the name (*.tar.gz, *.tar.gz.sha256)
- upload everything that matches multiple file extensions (*.txt, *.md)

1) and 2) are quite simple to implement (`*.txt` and `*.txt*`), but I haven't found any concrete examples demonstrating 3).

In particular, I'd love to read more on the expected behaviour and limitations of the `[seq]` pattern matcher. There's very little information available on how it should be used. I've looked everywhere (including by looking through several test cases in azure-cli itself), but didn't find any concrete examples other than what was provided in the SO answer shared above.

**Comment by bacongobbler** [comment] 2019-12-03 22:00
update: looks like [the pattern matcher](https://github.com/Azure/azure-cli/blob/8adf97355a605d147afc26f6c1b6f6afb6651c2f/src/azure-cli/azure/cli/command_modules/storage/util.py#L170-L172) comes from [fnmatch](https://docs.python.org/2/library/fnmatch.html), a python library that provides UNIX-style file pattern match sequences. The documentation doesn't appear to demonstrate much information on how the pattern matcher works, however you can drop into a python shell to play around with some patterns to see what the it provides as a regular expression.

```
><> python
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fnmatch
>>> fnmatch.translate("*")
'.*\\Z(?ms)'
```

**Comment by Juliehzl** [comment] 2020-01-06 05:41
dupe of #3982

**Comment by Juliehzl** [comment] 2020-01-06 07:30
Just as what @bacongobbler said, the --pattern in azure cli is based on [fnmatch](https://docs.python.org/3.7/library/fnmatch.html) library. What --pattern can match is limited, but I will add more information and examples for the usage.

**Closed** 2020-01-19 08:32 UTC
Labels: Feature Request, Storage
