### ISSUE TITLE
webapp: Uploading Python app to Azure

### ISSUE THREAD

**Issue by jrdat** [Azure/azure-cli#11201] opened 2019-11-12 23:54 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'resource_group'
Traceback (most recent call last):
Temp\pip-install-umfcm_n2\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 652, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 2929, in webapp_up
AttributeError: 'NoneType' object has no attribute 'resource_group'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} -n {} -l {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment] 2019-11-13 02:16
Duplicate of #11100

**Comment by panchagnula** [comment] 2019-11-16 02:40
Please downgrade to version pip install azure-cli==2.0.75

**Comment by panchagnula** [comment] 2019-11-27 23:51
Please update to the latest version of CLI https://pypi.org/project/azure-cli/ version 2.0.77 and re-try. there was a known regression with version 2.0.76

**Closed by panchagnula** 2019-11-27 23:51 UTC
Labels: Service Attention, Web Apps
