### ISSUE TITLE
az storage account create failed

### ISSUE THREAD

**Issue by Andriy-dev** [Azure/azure-cli#12873] opened 2020-04-04 22:41 UTC
## Describe the bug

**Command Name**
`az storage account create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account create -n {} -g {} -l {} --sku {}`

## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

Extensions:
aks-preview 0.4.42

```

**Comment by yonzhan** [comment] 2020-04-04 23:22
add to S169

**Comment by yonzhan** [comment] 2020-05-02 14:26
add to S171

**Comment by Juliehzl** [comment] 2020-06-15 03:26
dupe of #13517

**Closed** 2020-06-15 03:26 UTC
Labels: OKR3.2 Candidate, Storage, feature-request
