### ISSUE TITLE
Unable to use 'az interactive' in logged-in and otherwise working Azure Cloud Shell (bash)

### ISSUE THREAD

**Issue by rfreytag** [Azure/azure-cli#17081] opened 2021-02-24 16:56 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
cannot import name 'ENV_ADDITIONAL_USER_AGENT'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 664, in execute
    raise ex
cli/core/commands/__init__.py, ln 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 720, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 31, in <module>
    from azure.cli.core.commands.client_factory import ENV_ADDITIONAL_USER_AGENT
ImportError: cannot import name 'ENV_ADDITIONAL_USER_AGENT'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.19.0 *

Extensions:
interactive 0.4.3
ai-examples 0.2.5

```

**Comment by yonzhan** [comment] 2021-02-24 23:17
interactive

**Comment by jiasli** [comment] 2021-12-03 02:01
Duplicate of #12837

**Closed by jiasli** 2021-12-03 02:01 UTC
Labels: Interactive, feature-request
