### ISSUE TITLE
azure-cli mktemp: Invalid argument

### ISSUE THREAD

**Issue by mmbatha** [Azure/azure-cli#8353] opened 2019-01-28 14:14 UTC
---

### Environment summary

Install Method (interactive script) / CLI version (`az --version` N/A) / Shell Type (bash)  

```
```
Installation via `curl -L https://aka.ms/InstallAzureCli | bash` gives the error in the title. Solution: `mktemp -t azure_cli_install_tmp_XXXX` should be `mktemp -t azure_cli_install_tmp_XXXXXX`

**Comment by marstr** [comment] 2019-01-30 22:49
Howdy @mmbatha,

What environment are you running this in? I can't reproduce it on my Mac (10.14.2) or my Linux machine (Fedora 29). Here is the result of running `mktemp -t azure_cli_install_tmp_XXXX` on each of my machines:
- Mac: `/var/folders/9b/qp8qcdrd74q69ppzl1tzjl700000gn/T/azure_cli_install_tmp_XXXX.lDWTnSyO`
- Linux: `/tmp/azure_cli_install_tmp_S4RJ`

Admittedly, there's a little ugliness in the path that running this with MacOS results in, but it does fundamentally work for me.

**Comment by marstr** [comment] 2019-01-30 23:10
Additionally, I was just able to successfully install the Azure CLI on an Ubuntu container by running the following:
``` bash
docker run -it ubuntu /bin/bash
apt-get update
apt-get install python
curl -L https://aka.ms/InstallAzureCLI | bash # pressing enter for all default locations
ln -s /root/bin/az /usr/local/bin/az
az --version
az self-test
```

**Comment by marstr** [comment] 2019-01-30 23:50
Seeing as I can't repro this, I'm going to close it for now. Please feel free to get back to me, and if it's still a problem for you I'll open it back up.

**Comment by marstr** [comment] 2019-01-31 16:45
Thanks for getting back to me, @mmbatha. This seems like a great thing to submit as an Open Source contribution. Mind submitting a PR?

**Comment by mmbatha** [comment] 2019-01-31 20:25
Okay, I will

**Comment by mmbatha** [comment] 2019-02-02 12:32
Pull request #8418 has the requested changes

**Closed** 2019-02-04 19:48 UTC
Labels: Installation, Packaging, good first issue, help wanted

**Comment by marstr** [comment] 2019-02-14 21:52
These changes haves been deployed now.

**Comment by techiechap** [comment] 2019-05-01 16:37
vsts cli installation  failed "mktemp: Invalid argument" on the azure-cli docker image, can someone help here

**Comment by marstr** [comment] 2019-05-01 17:29
Howdy, I'm afraid the VSTS CLI is a different product. Please checkout https://github.com/Azure/azure-devops-cli-extension for more help.
