### ISSUE TITLE
az upgrade --yes command failed with code -1073741510

### ISSUE THREAD

**Issue by aiboli** [Azure/azure-cli#24522] opened 2022-11-01 16:38 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az upgrade --yes

**Describe the bug**

after running `az upgrade --yes` in the azure cli task, it was stuck at this line: `WARNING: cli.azure.cli.command_modules.util.custom: Installing MSI` for couple of minutes and then ends with error: `##[error]Exit code -1073741510 returned from process: file name 'D:\a\_work\1\b\2\externals\node10\bin\node.exe', arguments '"D:\a\_work\1\b\2\_work\_tasks\AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815\2.208.0\azureclitask.js"'`
**To Reproduce**

add Azure Cli Task with 2.* version in the Azure devops pipeline within power shell core

**Expected behavior**

the upgrade should succeed

**Environment summary**

Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.208.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
C:\WINDOWS\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"

WARNING: You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'

azure-cli                         2.40.0 *

core                              2.40.0 *
telemetry                          1.0.8

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\svccbld\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

**Additional context**

the agent has the 2.40.0 by default, so for version 2.41.0, after running az upgrade it will update to 2.41.0 which works totally fine.

**Comment by yonzhan** [comment] 2022-11-02 00:43
@bebound for awareness

**Comment by bebound** [comment] 2022-11-02 02:20
Duplicate of https://github.com/Azure/azure-cli/issues/22651

`az upgrade` currently doesn't work in Azure DevOps agent.

**Closed by bebound** 2022-11-02 02:20 UTC
Labels: question, customer-reported, Installation, Upgrade, Auto-Assign, Azure CLI Team
