### ISSUE TITLE
Cannot add secrets to virtual machine

### ISSUE THREAD

**Issue by ctolkien** [Azure/azure-cli#11785] opened 2020-01-07 06:28 UTC
## Describe the bug

**Command Name**
`az vm secret list`

**Errors:**
```
'NoneType' object has no attribute 'secrets'
Traceback (most recent call last):
cliextensions\interactive\azext_interactive\azclishell\app.py, ln 662, in cli_execute
    result = invocation.execute(args)
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-umfcm_n2\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\vm\custom.py, ln 1730, in list_vm_secrets
AttributeError: 'NoneType' object has no attribute 'secrets'
```

- _Put any pre-requisite steps here..._
- `az vm secret list --name {} -g {}`

## Expected Behavior
Should work?

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76 *

Extensions:
azure-devops 0.12.0
interactive 0.4.3

```

**Comment by bim-msft** [comment] 2020-01-07 08:34
@qwordy Please take a look.

**Comment by qwordy** [comment] 2020-01-22 02:21
@ctolkien, How do you create the vm?
We have written a patch #11914 . The problem is vm's os_profile is None.

**Comment by ctolkien** [comment] 2020-01-22 08:03
This was made via the portal, I Bieber from an existing HDD?

**Comment by qwordy** [comment] 2020-03-17 08:43
The patch has released in latest Azure CLI. Hope it can solve your issue. If any problem, you can open a new issue.

**Closed by qwordy** 2020-03-17 08:43 UTC
Labels: Compute, Compute - VM, OKR3.2 Candidate
