### ISSUE TITLE
Unable to update app gateway address pool

### ISSUE THREAD

**Issue by andymoe** [Azure/azure-cli#1622] opened 2016-12-28 22:50 UTC
I'm trying to update the servers in an app gateway's backend pool via the CLI using the --set (or --add) command.

The goal is to add additional VMs to the pool...

Here is the error I get for --set:

```
+ az network application-gateway update --resource-group [a-resource-group] --name [app-gateway-name] --set 'backendAddressPools[0].backendAddresses=[{"fqdn":null,"ipAddress":"172.17.1.4"}]'
u'ipAddress'
Traceback (most recent call last):
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 34, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 139, in execute
    result = expanded_arg.func(params)
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 293, in handler
    opres = setter(client, **getterargs) if client else setter(**getterargs)
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/azure/mgmt/network/operations/application_gateways_operations.py", line 223, in create_or_update
    body_content = self._serialize.body(parameters, 'ApplicationGateway')
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/msrest/serialization.py", line 303, in body
    data = _convert_to_datatype(data, data_type, self.dependencies)
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/msrest/serialization.py", line 171, in _convert_to_datatype
    getattr(data, attr), map['type'], localtypes))
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/msrest/serialization.py", line 150, in _convert_to_datatype
    param, data_type[1:-1], localtypes) for param in data
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/msrest/serialization.py", line 171, in _convert_to_datatype
    getattr(data, attr), map['type'], localtypes))
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/msrest/serialization.py", line 150, in _convert_to_datatype
    param, data_type[1:-1], localtypes) for param in data
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/msrest/serialization.py", line 164, in _convert_to_datatype
    localtypes) for key in data
  File "/home/jumpboxadmin/lib/azure-cli/local/lib/python2.7/site-packages/msrest/serialization.py", line 164, in <dictcomp>
    localtypes) for key in data
KeyError: u'ipAddress'
```

We've tried using --add, with a slightly different command, and gotten no further - similar/same error.

**Comment by tjprescott** [comment] 2017-01-04 01:10
--add would be the correct parameter to use. I would try
`az network application-gateway update {...} --add backendAddressPools[0].backendAddresses "{\"fqdn\":null,\"ip_address\":\"172.17.1.4\"}"`

**Comment by tjprescott** [comment] 2017-01-04 18:26
I have verified that this works. Also, when the app gateway PR is merged, you could also do this:

`az network application-gateway address-pool update -g {rg} --gateway-name {gateway} -n {backend-pool-name} --add backendAddresses "{\"fqdn\":{fqdn},\"ip_address\":\"{address}\"}"`

**Comment by tjprescott** [comment] 2017-01-04 18:29
So when you are using --set or --add to set an object:

1. ugly escape character are required
2. use the Python syntax for the properties (ip_address instead of ipAddress)

**Comment by andymoe** [comment] 2017-01-04 19:48
Thanks @tjprescott, I think it was probably 2 that was tripping us up. Trying this now.

**Comment by tjprescott** [comment] 2017-01-04 22:05
If you still have issues, please re-open :)

**Comment by andymoe** [comment] 2017-01-04 22:07
I got both set and add to work! Thanks!

**Comment by andymoe** [comment] 2017-01-05 23:55
Hey @tjprescott I was able to get this working for both --set and --add it was indeed the snake case issue. :/

**Comment by Aendapally** [comment] 2017-04-23 12:49
I am trying to use this below command to update the backend address pool of an Exisiting Application gateway.
**Command**
az network application-gateway address-pool update --resource-group outlookserviceclean --gateway-name Nimble-ApplicationGateway --name appGatewayBackendPool --add backendAddresses "{\"fqdn\":null, \"ip_address\":\"{10.0.0.13}\"}"
**Error**
Couldn't find '{"ip_address":"{10' in '{"ip_address":"{10.0'. Available options: ['backendAddresses', 'backendIpConfigurations', 'etag', 'id', 'name', 'provisioningState']

**Comment by tjprescott** [comment] 2017-04-24 15:03
Hi @Aendapally what version of the CLI and modules are you running (`az --version`)?

**Comment by Aendapally** [comment] 2017-04-24 17:07
Hello @tjprescott I am using CLI 2.0. It was giving me above mentioned error on my windows machine but I was able to execute the same successfully on linux machine.

**Comment by Aendapally** [comment] 2017-04-24 17:09
This is from my windows machine 
C:\Users\akhileshwar>az --version
azure-cli (2.0.2)

acr (2.0.0)
acs (2.0.2)
appservice (0.1.2)
batch (2.0.0)
cloud (2.0.0)
component (2.0.0)
configure (2.0.2)
container (0.1.2)
core (2.0.2)
documentdb (0.1.2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.2)
keyvault (2.0.0)
lab (0.0.1)
monitor (0.0.1)
network (2.0.2)
nspkg (2.0.0)
profile (2.0.2)
redis (0.1.1b3)
resource (2.0.2)
role (2.0.1)
sql (2.0.0)
storage (2.0.2)
vm (2.0.2)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]

**Comment by derekbekoe** [comment] 2017-04-24 17:35
@tjprescott The latest version is 2.0.3. Has it been fixed there? https://pypi.python.org/pypi/azure-cli

**Comment by tjprescott** [comment] 2017-05-31 18:26
Hi @Aendapally, try this on Windows:
`az network application-gateway address-pool update --resource-group outlookserviceclean --gateway-name Nimble-ApplicationGateway --name appGatewayBackendPool --add backendAddresses "{\"ip_address\":\"{10.0.0.13}\"}"`

You don't need to include the FQDN part since it will be null by default.

**Closed** 2017-05-31 18:27 UTC
Labels: Network

**Comment by galiacheng** [comment] 2020-07-14 06:48
Hi @tjprescott I am trying to use `--remove` to remove one of the backendAddresses  and failed, not sure if I passed the parameter in right way.
```
# delete index 1
az network application-gateway address-pool update -g oraclevm-cluster-07134 --gateway-name myAppGateway --name myGatewayBackendPool --remove backendAddresses[1]
# ERROR: index 1 doesn't exist on backendAddresses

# delete with [key=value]
az network application-gateway address-pool update -g oraclevm-cluster-07134 --gateway-name myAppGateway --name myGatewayBackendPool --remove backendAddresses["fqdn"="mspVM"]
# ERROR: item with value 'mspVM' doesn't exist for key 'fqdn' on backendAddresses
```

Could you please help!

**Comment by galiacheng** [comment] 2020-07-14 07:03
I updated az cli with 2.8.0, and it worked with the following command:
`az network application-gateway address-pool update -g oraclevm-cluster-07134 --gateway-name myAppGateway --name myGatewayBackendPool --remove backendAddresses 1'
Still not worked with key=value.

**Comment by Al-Nevado** [comment] 2020-08-11 11:54
I can confirm the same issue as galiacheng.

I can add IPs to a pool just fine:
`az network application-gateway address-pool update -g x --gateway-name x -n x --add backendAddresses "{\"fqdn\":null,\"ip_address\":\"172.17.0.20\"}"
{
  "backendAddresses": [
    {
      "fqdn": null,
      "ipAddress": "172.17.0.18"
    },
    {
      "fqdn": null,
      "ipAddress": "172.17.0.19"
    },
    {
      "fqdn": null,
      "ipAddress": "172.17.0.20"
    }
  ],
etag": "W/\"x"",
  "id": "/subscriptions/x/resourceGroups/x/providers/Microsoft.Network/applicationGateways/xbackendAddressPools/x",
  "name": "x",
  "provisioningState": "Succeeded",
  "resourceGroup": "x",
  "type": "Microsoft.Network/applicationGateways/backendAddressPools"
}
`

But if I then try and remove it it'll fail.
`az network application-gateway address-pool update -g x --gateway-name x -n x --remove backendAddresses "{\"fqdn\":null,\"ip_address\":\"172.17.0.20\"}"
invalid syntax: --remove property.list <indexToRemove> OR --remove propertyToRemove
`
Removal by index works fine, its just not so easy for scripting.

Using azure-cli 2.10.1 (current latest)

**Comment by azzab80** [comment] 2020-11-16 05:20
Same issue for me. Can we get this re-opened ?
