### ISSUE TITLE
az aks get-credentials 2.0.24 not working

### ISSUE THREAD

**Issue by doug-fish** [Azure/azure-cli#5296] opened 2018-01-12 22:15 UTC
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

I installed on OSX 10.11.6 via brew. I am running in bash.
My az version:
 az --version
azure-cli (2.0.24)
```
```
I am unable to obtain credentials to my cluster:

$ az aks get-credentials --resource-group=REDACTED --name=REDACTED

'ManagedCluster' object has no attribute 'properties'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1329, in aks_get_credentials
    access_profiles = mc.properties.access_profiles
AttributeError: 'ManagedCluster' object has no attribute 'properties'

This issue has been noted by others and recorded in a similar, previously closed issue, which includes a workaround:   https://github.com/Azure/azure-cli/issues/5218

**Comment by derekbekoe** [comment] 2018-01-12 22:19
Closing as duplicate of https://github.com/Azure/azure-cli/issues/5218.
There are some workarounds listed there including reverting to 2.0.23.
We will be releasing 2.0.25 next week.

**Closed by derekbekoe** 2018-01-12 22:19 UTC
