### ISSUE TITLE
add Docker 'tag' command for 'az acr'

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#22887] opened 2022-06-15 13:59 UTC
**Related command**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment] 2022-06-15 14:25
route to CXP team

**Comment by navba-MSFT** [comment] 2022-06-17 10:33
@alexeyshishkin01 Apologies for the late reply. Thanks for reaching out to us. From the issue title, I see that your ask is to have a tagging functionality for the images in ACR. 
>There is no Azure CLI command to create a tag for the images directly. If you want to add a tag for the image, you just can use the docker command docker tag to add the tag and then push the image to Azure Container Registry. When you create the image through the build task, it also will lead to the tag adding. Take a look at [this](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-build-task). Refer [this](https://stackoverflow.com/a/53311429) thread. 

Alternatively you can use [acr import ](https://aka.ms/acr/import ) and simply add the tags.

This ask is a duplicate of the existing open thread https://github.com/Azure/acr/issues/289 which is open for tracking purpose. So archiving this thread.

**Closed by navba-MSFT** 2022-06-17 10:33 UTC
Labels: Container Registry, customer-reported, CXP Attention, Auto-Assign

**Comment by alexeyshishkin01** [comment] 2022-06-17 21:36
ok, thanks 'acr import' does the job.

what if to point out it in the documentation ?

**Comment by navba-MSFT** [comment] 2022-06-21 11:06
This has been documented here: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-import-images?tabs=azure-cli

**Comment by alexeyshishkin01** [comment] 2022-06-21 14:55
many thanks, really appreciate it !

**Comment by riley-dinara** [comment] 2023-01-28 03:11
The use-case described here is _not_ covered in the documentation. This issue is not closed from my perspective. Let me explain what we actually want here. Below is metadata from an acr repository, returned by this command:
`az acr manifest list-metadata -r REGISTRY -n REPOSITORY_NAME`

the interesting bit is here:
`    "tags": [
      "123abcf33ab98ce977cf000050669c0ab0cba321",
      "merge-20220913.1"
    ]`

I simply want an Azure CLI command that will **_append a tag value to this array_**. The bulk import back into the same repository, as was vaguely suggested above, is not the ask, and I'm not entirely sure it's even possible. I keep getting errors that the tag already exists.

For reference, the data structure returned by the above command is an array of metadata objects that look like this:

`[{
    "architecture": "amd64",
    "changeableAttributes": {
      "deleteEnabled": true,
      "listEnabled": true,
      "readEnabled": true,
      "writeEnabled": true
    },
    "configMediaType": "application/vnd.docker.container.image.v1+json",
    "createdTime": "2022-09-13T15:19:57.0242796Z",
    "digest": "sha256:SOME_DIGEST_HERE",
    "imageSize": 291885753,
    "lastUpdateTime": "2022-09-13T15:19:57.0242796Z",
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "os": "linux",
    "tags": [
      "123abcf33ab98ce977cf000050669c0ab0cba321",
      "merge-2022-09-13.001"
    ]
  }]`
