### ISSUE TITLE
Aks and acr aren't available under Azure CLI

### ISSUE THREAD

**Issue by mclagett** [Azure/azure-cli#13455] opened 2020-05-12 09:51 UTC
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```
az: 'aks' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse` (or any other az aks or az acr command)

## Expected Behavior
I would expect the command to execute as advertised in the documentation, but instead I get an eror message: az: 'aks' (or 'acr') is not in the 'az' command group

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

Extensions:
aks-preview 0.4.44

```

**Comment by yonzhan** [comment] 2020-05-12 11:24
Aks

**Comment by yungezz** [comment] 2020-05-12 13:46
hi @mclagett you need install aks-preview extension by
```
az extension add --name aks-preview
```
before using aks-preview extension. Could you pls share the doc link so we can check if the doc steps correct?

**Comment by mclagett** [comment] 2020-05-21 20:36
Hi --  

I realize I may have never answered back to this.  I am not trying to use the aks-preview extension.  I have just installed and logged in to the azure cli.  It was my understanding (perhaps incorrect) that I wouldn't need to install anything separate to be able to issue az aks and acr commands.  Is this not the case?

**Comment by jluk** [comment] 2020-05-21 21:22
You should be able to do that.

Could you please post the exact command you ran and the full output with --debug?

**Comment by mclagett** [comment] 2020-05-21 22:34
Thank you very much for responding.  I ran az aks create, without any parameters, expecting that like all the other az commands, it would comeback with information about what parameters were needed and available.  Instead, it always comes back with the error message that can be seen in the debug output below (i.e the output from running az aks create –debug).  You can see the error in the output below about 15 lines from the bottom.  A similar message is displayed if I try az acr create:

az aks create --debuga
File logging enabled - writing logs to 'C:\Users\mclag\.azure\logs'.
Command arguments: ['aks', 'create', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x036E49C0>, <function OutputProducer.on_global_arguments at 0x03553300>, <function CLIQuery.on_global_arguments at 0x0356F540>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.002 seconds.
Loaded module 'acs' in 0.001 seconds.
Loaded module 'advisor' in 0.001 seconds.
Loaded module 'ams' in 0.001 seconds.
Loaded module 'apim' in 0.002 seconds.
Loaded module 'appconfig' in 0.005 seconds.
Loaded module 'appservice' in 0.010 seconds.
Loaded module 'aro' in 0.010 seconds.
Loaded module 'backup' in 0.001 seconds.
Loaded module 'batch' in 0.031 seconds.
Loaded module 'batchai' in 0.001 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.003 seconds.
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.003 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.001 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.003 seconds.
Loaded module 'deploymentmanager' in 0.001 seconds.
Loaded module 'dla' in 0.001 seconds.
Loaded module 'dls' in 0.001 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.006 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.005 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.006 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.008 seconds.
Loaded module 'kusto' in 0.001 seconds.
Loaded module 'lab' in 0.001 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.002 seconds.
Loaded module 'natgateway' in 0.004 seconds.
Loaded module 'netappfiles' in 0.002 seconds.
Loaded module 'network' in 0.029 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.006 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.003 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.001 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.011 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.002 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.001 seconds.
Loaded module 'sqlvm' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.039 seconds.
Loaded module 'vm' in 0.021 seconds.
Loaded all modules in 0.276 seconds. (note: there's always an overhead with the first module loaded)
Found 2 extensions: ['aks-preview', 'interactive']
Extension compatibility result: is_compatible=True cli_core_version=2.6.0 min_required=2.0.49 max_required=None
Extensions directory: 'C:\Users\mclag\.azure\cliextensions\aks-preview'
Loaded extension 'aks-preview' in 0.004 seconds.
Extension compatibility result: is_compatible=True cli_core_version=2.6.0 min_required=2.0.62 max_required=None
Extensions directory: 'C:\Users\mclag\.azure\cliextensions\interactive'
Loaded extension 'interactive' in 0.001 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04021780>]
az_command_data_logger : command args: aks create --debug
metadata file logging enabled - writing logs to 'C:\Users\mclag\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0421B150>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0421B978>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0421BA50>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04592198>]
cli.azure.cli.core.parser : az: 'aks' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
az: 'aks' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
recommendation_provider: version: 2.6.0, command: , parameters: ['--debug'], extension: None
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x040218A0>]
az_command_data_logger : exit code: 2
telemetry.save : Save telemetry record of length 2784 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\mclag\.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
command ran in 0.422 seconds.x`

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mclagett** [comment] 2020-05-21 22:37
Incidentally, this is what I get if I just run az by itself.  Does this look correct, or is it perhaps missing stuff that should be there?  I have uninstalled and reinstalled Azure CLI several times, but I always get this same result.

az

     /\
    /  \    _____   _ _  ___ _
   / /\ \  |_  / | | | \'__/ _\
  / ____ \  / /| |_| | | |  __/
/_/    \_\/___|\__,_|_|  \___|


Welcome to the cool new Azure CLI!

Use `az --version` to display the current version.
Here are the base commands:

    account            : Manage Azure subscription information.
    ad                 : Manage Azure Active Directory Graph entities needed for Role Based Access
                        Control.
    appconfig          : Manage App Configurations.
    appservice         : Manage App Service plans.
    cache              : Commands to manage CLI objects cached using the `--defer` argument.
    cloud              : Manage registered Azure clouds.
    configure          : Manage Azure CLI configuration. This command is interactive.
    deployment         : Manage Azure Resource Manager template deployment at subscription scope.
    deployment-scripts : Manage deployment scripts at subscription or resource group scope.
    disk               : Manage Azure Managed Disks.
    eventhubs          : Manage Azure Event Hubs namespaces, eventhubs, consumergroups and geo
                        recovery configurations - Alias.
    extension          : Manage and update CLI extensions.
    feedback           : Send feedback to the Azure CLI Team!
    find               : I'm an AI robot, my advice is based on our Azure documentation as well as
                        the usage patterns of Azure CLI and Azure ARM users. Using me improves Azure
                        products and documentation.
    functionapp        : Manage function apps. To install the Azure Functions Core tools see
                        https://github.com/Azure/azure-functions-core-tools.
    group              : Manage resource groups and template deployments.
    hdinsight          : Manage HDInsight resources.
    image              : Manage custom virtual machine images.
    interactive        : Start interactive mode. Installs the Interactive extension if not installed
                        already.
    iot                : Manage Internet of Things (IoT) assets.
    keyvault           : Manage KeyVault keys, secrets, and certificates.
    local-context      : Manage Local Context.
    lock               : Manage Azure locks.
    login              : Log in to Azure.
   logout             : Log out to remove access to Azure subscriptions.
    managedapp         : Manage template solutions provided and maintained by Independent Software
                        Vendors (ISVs).
    network            : Manage Azure Network resources.
    policy             : Manage resource policies.
    provider           : Manage resource providers.
    resource           : Manage Azure resources.
    rest               : Invoke a custom request.
    role               : Manage user roles for access control with Azure Active Directory and
                        service principals.
    security           : Manage your security posture with Azure Security Center.
    snapshot           : Manage point-in-time copies of managed disks, native blobs, or other
                        snapshots.
    storage            : Manage Azure Cloud Storage resources.
    tag                : Manage resource tags.
    version            : Show the versions of Azure CLI modules and extensions in JSON format by
                        default or format configured by --output.
    vm                 : Manage Linux or Windows virtual machines.
    vmss               : Manage groupings of virtual machines in an Azure Virtual Machine Scale Set
                        (VMSS).
    webapp             : Manage web apps.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Michael Clagett<mailto:mclagett@hotmail.com>
Sent: Thursday, May 21, 2020 6:33 PM
To: Azure/azure-cli<mailto:reply@reply.github.com>; Azure/azure-cli<mailto:azure-cli@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [Azure/azure-cli] Aks and acr aren't available under Azure CLI (#13455)

Thank you very much for responding.  I ran az aks create, without any parameters, expecting that like all the other az commands, it would comeback with information about what parameters were needed and available.  Instead, it always comes back with the error message that can be seen in the debug output below (i.e the output from running az aks create –debug).  You can see the error in the output below about 15 lines from the bottom.  A similar message is displayed if I try az acr create:

az aks create --debuga
File logging enabled - writing logs to 'C:\Users\mclag\.azure\logs'.
Command arguments: ['aks', 'create', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x036E49C0>, <function OutputProducer.on_global_arguments at 0x03553300>, <function CLIQuery.on_global_arguments at 0x0356F540>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.002 seconds.
Loaded module 'acs' in 0.001 seconds.
Loaded module 'advisor' in 0.001 seconds.
Loaded module 'ams' in 0.001 seconds.
Loaded module 'apim' in 0.002 seconds.
Loaded module 'appconfig' in 0.005 seconds.
Loaded module 'appservice' in 0.010 seconds.
Loaded module 'aro' in 0.010 seconds.
Loaded module 'backup' in 0.001 seconds.
Loaded module 'batch' in 0.031 seconds.
Loaded module 'batchai' in 0.001 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.003 seconds.
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.003 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.001 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.003 seconds.
Loaded module 'deploymentmanager' in 0.001 seconds.
Loaded module 'dla' in 0.001 seconds.
Loaded module 'dls' in 0.001 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.006 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.005 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.006 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.008 seconds.
Loaded module 'kusto' in 0.001 seconds.
Loaded module 'lab' in 0.001 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.002 seconds.
Loaded module 'natgateway' in 0.004 seconds.
Loaded module 'netappfiles' in 0.002 seconds.
Loaded module 'network' in 0.029 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.006 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.003 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.001 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.011 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.002 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.001 seconds.
Loaded module 'sqlvm' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.039 seconds.
Loaded module 'vm' in 0.021 seconds.
Loaded all modules in 0.276 seconds. (note: there's always an overhead with the first module loaded)
Found 2 extensions: ['aks-preview', 'interactive']
Extension compatibility result: is_compatible=True cli_core_version=2.6.0 min_required=2.0.49 max_required=None
Extensions directory: 'C:\Users\mclag\.azure\cliextensions\aks-preview'
Loaded extension 'aks-preview' in 0.004 seconds.
Extension compatibility result: is_compatible=True cli_core_version=2.6.0 min_required=2.0.62 max_required=None
Extensions directory: 'C:\Users\mclag\.azure\cliextensions\interactive'
Loaded extension 'interactive' in 0.001 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04021780>]
az_command_data_logger : command args: aks create --debug
metadata file logging enabled - writing logs to 'C:\Users\mclag\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0421B150>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0421B978>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0421BA50>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04592198>]
cli.azure.cli.core.parser : az: 'aks' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
az: 'aks' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
recommendation_provider: version: 2.6.0, command: , parameters: ['--debug'], extension: None
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x040218A0>]
az_command_data_logger : exit code: 2
telemetry.save : Save telemetry record of length 2784 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\mclag\.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
command ran in 0.422 seconds.x`

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jluk** [comment] 2020-05-21 22:52
It seems your build just doesn't have those modules built in, which is odd. Do you have other installs of azure cli on your machine? @fengzhou-msft can you take a look?

**Comment by mclagett** [comment] 2020-05-22 12:13
Hi –

Okay.  I think I figured out what’s going on.  I moved to another machine and downloaded azure cli and was excited to see that aks was among the commands that appeared when I did a command listing (az by itself).  I can’t tell you how psyched I was, because I’ve been trying to work through this for a couple weeks now.  As I set up this machine to remote administer the azure stack instance (making sure dns was configured correctly, making sure I could launch adminportal via the browser, etc)., I would periodically check the az command set just to make sure something I had done hadn’t ruined it.  Aks was always in the list…until I actually logged in properly from Powershell to my AzureStack cloud and set it to active.  The next time I listed the commands, aks was missing (actually I tried using it first and got the same message as in my previous emails).

So it would appear that aks is not enabled for an Azure CLI logged in to an Azure Stack SDK installation.  Bummer.  I already set up a kubernetes cluster via aks-engine and have been using kubectl (via ssh) to administer it.  But I was hoping that I could also set up clusters via aks, as this is what is used in most of the sample code I want to try out.

Is it possible that managed clusters are supposed to work on the Azure Stack SDK installation and that I just need to do something else?

Thanks.

Mike



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jluk** [comment] 2020-05-22 15:14
That may explain it then, AKS does not have a direct offering in AzStack so the modules likely get filtered out based on that environment. At the moment Stack offers AKS-Engine and kubectl management as you mention.

I believe this is the ultimate root cause, feel free to reach out to the Stack team about any further questions but I'm going to close this issue. Just lmk if there's anything else we can do for you.

**Closed by jluk** 2020-05-22 15:14 UTC
Labels: AKS, Packaging
