### ISSUE TITLE
Error building AzureRM Client

### ISSUE THREAD

**Issue by pavankumarda2136** [Azure/azure-cli#14778] opened 2020-08-13 18:21 UTC
I am getting the bellow error when running terraform plan. Did anyone face the same issue ? I am able to login using az login as well.

```
Error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

  on main.tf line 1, in provider "azurerm":
   1: provider "azurerm" {``
```

**I am using WSL****, and I have installed azure cli from MS docs. Bellow is my az -version for reference.

az --version
azure-cli                          2.6.0 *

command-modules-nspkg              2.0.3
core                               2.6.0 *
nspkg                              3.0.4
telemetry                          1.0.4

**Comment by yonzhan** [comment] 2020-08-13 22:28
add to S175

**Comment by jiasli** [comment] 2020-08-14 02:10
Are Terraform and Azure CLI in the same system? (Both under WSL?) In order to use Azure CLI authentication, Terraform should be able to sub-process `az account get-access-token`.

**Comment by pavankumarda2136** [comment] 2020-08-14 02:18
Hi @jiasli , yes Terraform and azure cli is on the same system. why do I need access-token?  Any how I am using az login to get all the subscriptions from azure. 
I followed the one for ubuntu.

**Comment by jiasli** [comment] 2020-08-14 02:40
Terraform internally calls `az account get-access-token` to use Azure CLI as the authentication provider. Could you follow the troubleshooting steps provided in https://github.com/terraform-providers/terraform-provider-azurerm/issues/3686#issuecomment-523983734?

\+ @mybayern1974 from Azure Terraform team to help take a look.

**Comment by mybayern1974** [comment] 2020-08-14 04:22
Hi @pavankumarda2136 , thank you for posting this question.

With assuming using AzCLI is one of the major auth ways in Terraform, the scenario should work with well tested. Per the description provided here, I may not be able to quickly troubleshoot given the provided contexts look correct.

May I suggest you could possibly go through docs first and map to your procedures to see whether there are any steps missed on your local (if you did not yet):
-   [A terraform tutorial instructing config AzCLI for TF](https://www.terraform.io/docs/providers/azurerm/guides/azure_cli.html)
- [A Microsoft e2e tutorial of using AzCLI in Terraform and eventually provision Azure resources in Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell). Though this tutorial is based on Azure Cloud Shell that is not the same with your local system/env, assume the key steps would be the same

**Comment by pavankumarda2136** [comment] 2020-08-14 16:10
Hi @mybayern1974 , I have followed the same steps before I posted my issue here. However, there might be an issue with azure-cli 2.6.0 * when working on terraform. so, downgrading my azure cli to different version solved my issue. Thank you everyone !

**Comment by jiasli** [comment] 2020-08-17 02:45
@pavankumarda2136, glad to know the issue is solved for you. However, I don't think this is related to Azure CLI's version. We recommend always using the [latest version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest). Could you try the latest version and see if the issue persists?

**Comment by magodo** [comment] 2020-08-17 06:15
One similar [issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/5694#issuecomment-585949039) under WSL, fixed by following workaround:

> Within the user profile directory (on windows) there was a folder .Azure. Deleted this folder, authenticated with az login followed the same steps above. terraform plan completed successfully.

**Comment by nocticdr** [comment] 2020-10-09 09:33
Had the same issue, however it was happening at terraform init stage and deleting the .azure folder didn't help. What was happening on my end was that although I was able to do az login in WSL, the .azure folder was being saved under the Windows user path instead. I ended up copying the .azure folder to my WSL user directory and terraform init worked again. Thanks @magodo for the pointer

**Comment by jiasli** [comment] 2021-07-08 10:09
> What was happening on my end was that although I was able to do az login in WSL, the .azure folder was being saved under the Windows user path instead.

This is because you are calling `az` installed on Windows, instead of the one installed on WSL. You may follow [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) to install on Ubuntu.

**Closed by jiasli** 2021-07-08 10:09 UTC
Labels: Account, OKR3.2 Candidate, customer-reported, feature-request

**Comment by amagura** [comment] 2022-12-06 19:11
I'm having the exact same issue; I'm not using WSL.

```
azure-cli                         2.40.0 *
Terraform v1.3.6
```

Both Terraform and Azure CLI are in the path.
