### ISSUE TITLE
[DocumentDB] The list and show commands throw an unhandled exception

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2009] opened 2017-02-08 18:15 UTC
I'm able to successfully create a DocumentDB instance via `az documentdb create`, however, if I subsequently try to run the `list`, `list-all` or `show` commands, I get the following exception:

```
unbound method get() must be called with DatabaseAccountsOperations instance as first argument (got DocumentDB instance instead)
Traceback (most recent call last):
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 333, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
TypeError: unbound method get() must be called with DatabaseAccountsOperations instance as first argument (got DocumentDB instance instead)
```

Is there maybe something wrong with my installation?

**Comment by lostintangent** [comment] 2017-02-22 16:45
I just updated to the latest bits, and the `list` command seems to work great now. However, I still get the above exception when running the `show` command.

**Comment by dmakwana** [comment] 2017-02-22 17:41
Tried to reproduce by executing the following 2 commands in order:
```
az documentdb create -g <resource-group-name> -n <database-account-name>
az documentdb show -g <resource-group-name> -n <database-account-name>
```
@lostintangent 
Was unable to reproduce, can you send me your input?

**Comment by lostintangent** [comment] 2017-02-22 17:49
The only different between your example, and what I'm running, is that I'm adding `--kind MongoDB` when creating the DocDB instance.

That said, I just tried running the exact same command as your example, and I still get the error, so it doesn't seem limited to MongoDB instances.

```
[~@09:42:36] az documentdb create -g test -n thisisatest
DatabaseAccountOfferType    DocumentEndpoint                              Kind              Location    Name         ProvisioningState    ResourceGroup
--------------------------  --------------------------------------------  ----------------  ----------  -----------  -------------------  ---------------
Standard                    https://thisisatest.documents.azure.com:443/  GlobalDocumentDB  West US     thisisatest  Succeeded            test


[~@09:45:42] az documentdb list
DatabaseAccountOfferType    DocumentEndpoint                                        Kind              Location    Name                   ProvisioningState    ResourceGroup
--------------------------  ------------------------------------------------------  ----------------  ----------  ---------------------  -------------------  ---------------
Standard                    https://thisisatest.documents.azure.com:443/            GlobalDocumentDB  West US     thisisatest            Succeeded            test


[~@09:46:18] az documentdb show -n thisisatest -g test
unbound method get() must be called with DatabaseAccountsOperations instance as first argument (got DocumentDB instance instead)
Traceback (most recent call last):
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 343, in _execute_command
    raise ex
TypeError: unbound method get() must be called with DatabaseAccountsOperations instance as first argument (got DocumentDB instance instead)
```

In case it helps, I'm using `documentdb (0.1.1b1+1.dev20170221)` of the DocDB plugin for the CLI.

**Comment by okelet** [comment] 2017-03-07 15:25
Also happens for `check-name-exists`:

```
$ az documentdb check-name-exists -n hola
unbound method check_name_exists() must be called with DatabaseAccountsOperations instance as first argument (got DocumentDB instance instead)
Traceback (most recent call last):
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in _execute_command
    raise ex
TypeError: unbound method check_name_exists() must be called with DatabaseAccountsOperations instance as first argument (got DocumentDB instance instead)
```

**Comment by iyerusad** [comment] 2017-03-16 22:46
I see the same issue, seems to be related to when using `--kind MongoDB`

**Comment by dmakwana** [comment] 2017-03-20 17:03
I tested this off the master branch and cannot reproduce any of the above noted issues. I also did a pip install to the latest azure-cli and this issue is not showing up in that installation either. I'd suggest updating installations.  @lostintangent can you close this issue if you can confirm? Thanks!

@okelet @iyerusad

**Comment by lostintangent** [comment] 2017-03-20 18:35
@dmakwana I just re-installed the CLI and am still getting this error unfortunately :(

**Comment by dmakwana** [comment] 2017-03-20 20:05
@lostintangent use Python 3.5. I can reproduce this issue with Python 2.7. Azure CLI 2.0 is recommended to be used with Python 3.5

**Comment by lostintangent** [comment] 2017-03-20 20:07
As a macOS user, I'm using the version that comes pre-installed since that's easy. Also, I've exercised most of the CLI and this is the sole command where the Python 3.5 requirement is apparently necessary. It seems like a stretch to ask users to change their Python installation purely to run `az documentdb show`.

**Comment by okelet** [comment] 2017-03-20 20:08
@dmakwana using azure-cli from ubuntu repository:

```
juan@pcjuan:~$ which az
/usr/bin/az
juan@pcjuan:~$ ls -l /usr/bin/az
-rwxr-xr-x 1 root root 57 mar 14 00:57 /usr/bin/az
juan@pcjuan:~$ head /usr/bin/az
#!/usr/bin/env bash
/opt/az/bin/python -m azure.cli "$@"
juan@pcjuan:~$ /opt/az/bin/python --version
Python 2.7.12
juan@pcjuan:~$ az documentdb check-name-exists -n hola
unbound method check_name_exists() must be called with DatabaseAccountsOperations instance as first argument (got DocumentDB instance instead)
Traceback (most recent call last):
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 361, in _execute_command
    raise ex
TypeError: unbound method check_name_exists() must be called with DatabaseAccountsOperations instance as first argument (got DocumentDB instance instead)
juan@pcjuan:~$ 
```

Please update to Python 3.5 in the repository, if this is required...

**Comment by dmakwana** [comment] 2017-03-20 20:22
@lostintangent fair enough, I was unaware that most of the CLI was compatible with python2.7. I'll fix this

**Comment by derekbekoe** [comment] 2017-03-20 20:24
@dmakwana I took a look and created a PR. I don't have DocDB to test it on but that PR may help.

**Comment by dmakwana** [comment] 2017-03-21 00:39
Thanks @derekbekoe 

I've tested the fix. Waiting for it to get merged and then we can close this issue

**Closed** 2017-03-22 04:06 UTC
Labels: bug, DocumentDB

**Comment by johnpapa** [comment] 2017-05-03 02:22
I ran into this today on python 2.7. Are we saying the CLI must use python 3.5?

Or should it work with 2.7, too?

**Comment by troydai** [comment] 2017-06-12 23:40
@johnpapa CLI works for both 2.7 and 3.5. Can you share the version of the CLI with me? (use `az --version` command)
