### ISSUE TITLE
az redis list-keys command fails with "Operation returned an invalid status 'Bad Request' "

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#25648] opened 2023-03-02 11:25 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az redis list-keys

**Describe the bug**

az redis list-keys command fails

```sh
redis_name=$(az deployment group show --name redis  -g ${{ env.RG_APP }} --query properties.outputs.redisName.value -o tsv)
 echo "redis_name" $redis_name

 az redis list-keys -n $redis_name -g rg-aca-XXX
```

```console
Operation returned an invalid status 'Bad Request'
```

**To Reproduce**

```sh
 redis_name=$(az deployment group show --name redis  -g ${{ env.RG_APP }} --query properties.outputs.redisName.value -o tsv)
echo "redis_name" $redis_name

redis_id=$(az deployment group show --name redis  -g ${{ env.RG_APP }} --query properties.outputs.redisResourceId.value -o tsv)
echo "redis_id" $redis_id

REDIS_KEY1=$(az redis list-keys --ids $redis_id --query "primaryKey" | tr -d '"')
REDIS_KEY2=$(az redis list-keys --ids $redis_id --query "secondaryKey" | tr -d '"')

echo $REDIS_KEY1 # this returns correctly the Key
echo $REDIS_KEY2 # this returns correctly the Key

 az redis list-keys -n $redis_name -g RG_APP # this fails
 
```

**Expected behavior**

az redis list-keys --name command should run sucessfully 

**Environment summary**

SCode/Terminal/WSL2/Ubunti2204
```console
 az version
{
  "azure-cli": "2.45.0",
  "azure-cli-core": "2.45.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "spring": "1.6.8"
  }
}
```

**Additional context**

**Comment by yonzhan** [comment] 2023-03-02 11:44
route to CXP team

**Comment by PramodValavala-MSFT** [comment] 2023-03-02 16:46
@ezYakaEagle442 I was unable to reproduce this error. Could you run the command with the `--debug` flag and share the output?

**Comment by ezYakaEagle442** [comment] 2023-03-03 09:09
see 
- [https://github.com/Azure/azure-cli/issues/25633](https://github.com/Azure/azure-cli/issues/25633)
- [https://github.com/Azure/azure-cli/issues/25647](https://github.com/Azure/azure-cli/issues/25647)

**Comment by ezYakaEagle442** [comment] 2023-03-03 09:42
> @ezYakaEagle442 I was unable to reproduce this error. Could you run the command with the `--debug` flag and share the output?

Can you please try not on Windows, on a GitHub Workflow and VSCode/Terminal/WSL2/Ubuntu2204 ? (as there is no file path 
D:\a_work\1\s\build_scripts\windows\xxxxx .....)

**Comment by ezYakaEagle442** [comment] 2023-03-05 12:35
@PramodValavala-MSFT  I share with you the Bicep template so that yo ucan test : 

```sh
@description('A UNIQUE name')
@maxLength(33)
param appName string = 'reddog${uniqueString(resourceGroup().id, subscription().id)}'

param location string = resourceGroup().location

param redisName string = 'redis-${appName}-poc' // redis-<project, app or service>-<environment>

// https://learn.microsoft.com/en-us/azure/templates/microsoft.cache/redis?pivots=deployment-language-bicep#sku
@allowed([
  'Basic'
  'Standard'
  'Premium'
]
)
param redisSkuName string = 'Premium'

@allowed([
  'C'
  'P'
]
)
param redisSkuFamily string = 'P'

resource redis 'Microsoft.Cache/redis@2022-06-01' = {
  name: redisName
  location: location
  properties: {
    sku: {
      name: redisSkuName
      family: redisSkuFamily
      capacity: 2
    }
    minimumTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
    enableNonSslPort: false
  }
}

output redisResourceId string = redis.id
output redisName string = redis.name
output redisHost string = redis.properties.hostName
output redisPort int = redis.properties.port
output redisVersion string = redis.properties.redisVersion
//output redisPassword string = listKeys(redis.id, redis.apiVersion).primaryKey

```

**Comment by ezYakaEagle442** [comment] 2023-03-06 08:21
In the debuf trace, I see  Request URL: 'https://management.azure.com/subscriptions/212121212121/resourceGroups/rg-aca-reddog-quarkus/providers/Microso
ft.Cache/redis/redis-reddog7wwufb7rkg2oe-poc%**0D**/listKeys?api-version=2022-06-01'

The 0D suggest a CR in Hexa, same straneg thing at [https://github.com/Azure/azure-cli/issues/25686](https://github.com/Azure/azure-cli/issues/25686)

**Comment by ezYakaEagle442** [comment] 2023-03-07 08:40
trim '\r' is a workaround : 
redis_name=$(az deployment group show --name redis  -g rg-aca-reddog-quarkus --query properties.outputs.redisName.value -o tsv | tr -d '\r')

**Comment by PramodValavala-MSFT** [comment] 2023-03-07 16:23
@ezYakaEagle442 Since the problem seems to be in the output of the `az deployment group show` command, I am closing this issue as a duplicate of #25647

**Closed by PramodValavala-MSFT** 2023-03-07 16:23 UTC
Labels: Redis Cache, question, Client, needs-team-attention, CXP Attention, Auto-Assign
