### ISSUE TITLE
Keyvault creation fails in Azure Government with "no registered resource provider" error

### ISSUE THREAD

**Issue by mark-strasser-nnl** [Azure/azure-cli#18320] opened 2021-06-01 18:02 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Creating a key vault and listing deleted key vaults no longer works in Azure Government.  The following error is returned:

```bash
(NoRegisteredProviderFound) No registered resource provider found for location 'USGovVirginia' and API version '2021-04-01-preview' for type 'vaults'.
```

**To Reproduce**

```bash
az group create --location usgovvirginia --name rg-test-kv
az keyvault create --location usgovvirginia --resource-group rg-test-kv --name NotAKeyVault
```

**Expected behavior**

Key vault should be created.

**Environment summary**

Using Azure Cloud Shell in Azure Government (portal.azure.us):

 * Install method:  none  (using cloud shell)
 * Shell type:  bash
 * OS version:  cloud shell  (Common Base Linux Delridge (quinault) - 10.0)
 * `az --version` returns the following:

```bash
azure-cli                         2.24.0 *

core                              2.24.0 *
telemetry                          1.0.6

Extensions:
ai-examples                        0.2.5
ssh                                0.1.5

Python location '/opt/az/bin/python3'
```

**Additional context**

Works fine in Azure Commercial.  Another developer tried the same commands and got the same result.  Other commands related to key vault also failed with the same error message - e.g. `az keyvault list-deleted`.

**Comment by yonzhan** [comment] 2021-06-01 22:07
keyvault

**Comment by RussTech** [comment] 2021-06-07 13:36
I am seeing this  issue as well.  

OS RHEL 7.9
last working az cli version: 
azure-cli.x86_64              2.22.1-1.el7 

started to fail with version:
2.23.0-1.el7

while connected to Azure Gov, running the command with --debug, the new az cli packages call API version  2021-04-01-preview 

The last working version of az cli calls the API 2019-09-01 (which is the latest API available in Azure Gov). 

I can also confirm this is impacting az Cli on MacOS

**Comment by evelyn-ys** [comment] 2021-06-08 02:02
This is a known issue from service side that for Gov Cloud, the preview API 2021-04-01-preview is not available.

To work around, CX can switch to an old profile temporarily:
`az cloud set --name AzureUSGovernment--profile 2020-09-01-hybrid`

**Comment by evelyn-ys** [comment] 2021-06-16 02:35
Duplicate of #18006

**Comment by sebansal** [comment] 2021-09-10 21:28
Closed as duplicate

**Closed by sebansal** 2021-09-10 21:28 UTC
Labels: KeyVault, Service Attention

**Comment by Stateofminf** [comment] 2021-09-11 02:45
Coco
