### ISSUE TITLE
Issue in Browse command

### ISSUE THREAD

**Issue by GauravRahi** [Azure/azure-cli#11855] opened 2020-01-14 20:38 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
The kube-dashboard addon was disabled for this managed cluster.
To use "az aks browse" first enable the add-on
by running "az aks enable-addons --addons kube-dashboard".
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Linux-4.15.0-1066-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78 *

```

**Comment by jluk** [comment] 2020-01-15 16:50
As the error states, you need to enable the addon before browse will do anything. Have you ran the command shown?

`az aks enable-addons --addons kube-dashboard`

**Comment by mfarley281** [comment] 2020-01-17 03:26
I'm having the same problem:

`[Jan 17 11:20 AM][matt@ubuntu:/tmp/tmp]$ az aks enable-addons --addons kube-dashboard --resource-group aks --name aks-IAfrAhu9 --verbose
The command failed with an unexpected error. Here is the traceback:

argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1844, in aks_enable_addons
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles['omsagent'])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2487, in _ensure_container_insights_for_monitoring
    if 'loganalyticsworkspaceresourceid' in addon.config:
TypeError: argument of type 'NoneType' is not iterable

To open an issue, please run: 'az feedback'
command ran in 2.180 seconds.
[Jan 17 11:21 AM][matt@ubuntu:/tmp/tmp]$ kubectl get pods -l k8s-app=kubernetes-dashboard
No resources found in default namespace.
[Jan 17 11:22 AM][matt@ubuntu:/tmp/tmp]$ az aks browse --resource-group aks --name aks-IAfrAhu9
The kube-dashboard addon was disabled for this managed cluster.
To use "az aks browse" first enable the add-on
by running "az aks enable-addons --addons kube-dashboard".
[Jan 17 11:25 AM][matt@ubuntu:/tmp/tmp]$ 
`

**Comment by mfarley281** [comment] 2020-01-17 03:29
Looks like this issue is a duplicate of: https://github.com/Azure/azure-cli/issues/11456

**Comment by jluk** [comment] 2020-01-17 16:09
Thanks for cross-ref let's try to move conversations to that single issue

**Comment by jluk** [comment] 2020-02-21 15:12
We believe a fix has been made, please reference this issue for the latest tracking. I am going to close this to consolidate info to one thread. If you still hit issues after the S166 milestone release, feel free to recomment.

https://github.com/Azure/azure-cli/issues/11456

**Closed by jluk** 2020-02-21 15:12 UTC
Labels: AKS, Service Attention
