### ISSUE TITLE
Could not create Python app from CLI with `az webapp up`

### ISSUE THREAD

**Issue by luispinedaneo** [Azure/azure-cli#11596] opened 2019-12-17 13:20 UTC
Could not complete "Quickstart: Create a Python app in Azure App Service on Linux". I obtained the following error when deploying the app.

Deployment endpoint responses with status code 503
Deployment status endpoint https://mypytest.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying...

**Command Name**
`az webapp up`

**Errors:**
```
HTTPSConnectionPool(host='luisazuretest.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x068173F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
pip-install-t7say61i\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 57, in create_connection
Azure\CLI2\lib\socket.py, ln 745, in getaddrinfo
...
pip-install-mjd5h3hf\requests\requests\sessions.py, ln 646, in send
pip-install-mjd5h3hf\requests\requests\adapters.py, ln 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='luisazuretest.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x068173F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku F1 -n mypytest -l francecentral`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.77

```

**Comment by panchagnula** [comment] 2019-12-17 21:14
can you please re-try & let us know if this still persists?

**Comment by MyronFanQiu** [comment] 2019-12-18 01:45
@panchagnula Thanks. 😄

**Comment by panchagnula** [comment] 2019-12-27 00:05
Closing this since there has been no update on this for more than 3 days. Please re-activate if this is still not resolved. Thanks!

**Closed by panchagnula** 2019-12-27 00:05 UTC
Labels: Service Attention, Web Apps

**Comment by tkosin** [comment] 2020-01-23 10:11
I got the same error by using Azure CLI on CMD. And try to run many times it could not be resolved. Please suggest me to solve this problem.

Thank you.

![image](https://user-images.githubusercontent.com/32434679/72975193-f5a04700-3e02-11ea-8683-49f5cf200235.png)

**Comment by danlee0528** [comment] 2020-01-28 04:48
I'm having the same error on Ubuntu 18.04
"Deplyment status endpoint https://pythonazureapp.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying..."

**Comment by danlee0528** [comment] 2020-01-28 05:12
> I got the same error by using Azure CLI on CMD. And try to run many times it could not be resolved. Please suggest me to solve this problem.
> 
> Thank you.
> 
> ![image](https://user-images.githubusercontent.com/32434679/72975193-f5a04700-3e02-11ea-8683-49f5cf200235.png)
> 
> ![image](https://user-images.githubusercontent.com/32434679/72975669-c63e0a00-3e03-11ea-97b6-b9c7f4cb916a.png)

I had the same error when running "az webapp up ..." and the issue was the location of an endpoint. Try "az account list-locations" and select the location that's the closest as possible to your location. I hope this helps !

**Comment by danlee0528** [comment] 2020-01-28 05:14
> I got the same error by using Azure CLI on CMD. And try to run many times it could not be resolved. Please suggest me to solve this problem.
> 
> Thank you.
> 
> ![image](https://user-images.githubusercontent.com/32434679/72975193-f5a04700-3e02-11ea-8683-49f5cf200235.png)
> 
> ![image](https://user-images.githubusercontent.com/32434679/72975669-c63e0a00-3e03-11ea-97b6-b9c7f4cb916a.png)

 I had the same error when running "az webapp up ..." and the issue was the location of an endpoint. Try "az account list-locations" and select the location that's the closest as possible to your location. I hope this helps !

**Comment by skelter** [comment] 2020-02-20 18:21
Should reopen.  Still a problem.

**Comment by outforpublic** [comment] 2020-05-19 17:16
Getting the same problem here

**Comment by panchagnula** [comment] 2020-05-20 02:21
@outforpublic if you are still seeing a problem here could you please file a new issue - the existing bug was fixed a while back so the root cause might be different if you are seeing this.

**Comment by elbuenizzy** [comment] 2020-07-28 05:57
Hey guys! This worked for me:

I first did a zip of my app, afterwards I used this command instead for the deployment:

az webapp deployment source config-zip --resource-group <group-name> --name <app-name> --src clouddrive/<filename>.zip

Hope it works for you!

https://docs.microsoft.com/en-us/azure/app-service/deploy-zip

**Comment by d0dulk0** [comment] 2020-12-02 20:57
> > I got the same error by using Azure CLI on CMD. And try to run many times it could not be resolved. Please suggest me to solve this problem.
> > Thank you.
> > ![image](https://user-images.githubusercontent.com/32434679/72975193-f5a04700-3e02-11ea-8683-49f5cf200235.png)
> > ![image](https://user-images.githubusercontent.com/32434679/72975669-c63e0a00-3e03-11ea-97b6-b9c7f4cb916a.png)
> 
> I had the same error when running "az webapp up ..." and the issue was the location of an endpoint. Try "az account list-locations" and select the location that's the closest as possible to your location. I hope this helps !

This worked for me, I'm located in central europe and by default the az webapp up command creates the resource group in US so you have to explicitly state the location for example 
`--location westeurope `

After rerunning with the --location option it worked

**Comment by exinmusic** [comment] 2021-04-28 19:23
I just have an observation regarding this issue, as we've started to experience this in a CI pipeline where it makes for a little deployment roulette.
If the initial zip deploy endpoint returns a 202, even if the following polling returns malformed for a minute, it will eventually return successful. 
If the initial deployment endpoint returns any sort of 500 though, the following async calls seem to endlessly return malformed data and never succeeds.
This is the CLI command we run in the pipeline.
`az webapp deployment source config-zip --resource-group <rg> --name <name> --src <src> `
