### ISSUE TITLE
'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by SergiiGalai** [Azure/azure-cli#11211] opened 2019-11-13 21:37 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'resource_group'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 485, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/custom.py, ln 2929, in webapp_up
    current_rg = app_details.resource_group
AttributeError: 'NoneType' object has no attribute 'resource_group'
```

## To Reproduce:
- go to https://docs.microsoft.com/en-us/learn/modules/azure-diagnose-application-startup-errors-with-kudu-console/4-exercise-implement-a-web-application?source=learn
- dotnet new mvc --name HotelApp
- cd HotelApp
- dotnet run
- Ctrl-C
- code Program.cs
- Add .UseContentRoot("invalid path") after UseStartup<Startup>(). Save the file after editing and close the editor.
- `az webapp up --name myuniquenameHotelApp --resource-group learn-c83b027a-8073-400c-ad39-a98960c8cf4f --sku F1` (tried different names: myuniquenameHotelApp, myuniquename1060HotelApp, "myuniquename-1060HotelApp", "myuniquenameHotelApp", [myuniquenameHotelApp] )

## Expected Behavior
App is deployed

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment] 2019-11-14 02:28
Duplicate of #11100

**Comment by panchagnula** [comment] 2019-12-27 00:32
Please upgrade to 2.0.77

**Closed by panchagnula** 2019-12-27 00:32 UTC
Labels: Service Attention, Web Apps
