### ISSUE TITLE
vm create: cannot decode secrets

### ISSUE THREAD

**Issue by WiseMack** [Azure/azure-cli#8456] opened 2019-02-07 00:19 UTC
### Describe the bug
Execute code
```
keyvaultName="airheadsbcKeys"
az keyvault update --name $keyvaultName --enabled-for-deployment true
admin="j007am"
resourceGroup="airheadsbc"
VMName="VMInstance"
bootDiagStorage="airheadsbcdiag"
customData=cloud-init-web-server.txt
subs=Pay-As-You-Go
nics="instancevm231"
image="Bitnami:simplemachinesforum:2-0:2.0.1811302007"
cert="airheadsbcCert"
secret=$(az keyvault secret list-versions --vault-name $keyvaultName --name $cert --query "[?attributes.enabled].id" --output tsv)
vm_secret=$(az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs)
az vm create --name $VMName --resource-group $resourceGroup --admin-username $admin --authentication-type ssh --boot-diagnostics-storage $bootDiagStorage --custom-data $customData --image $image --location "Canada Central" --nics $nics --ssh-key-value @"~/.ssh/id_rsa.pub" --subscription $subs --secrets $vm_secret
```
### Error
`Error decoding secrets: Expecting value: line 1 column 2 (char 1)`

### Note
Whether I use
```
vm_secret=$(az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs)
--secret $vm_secret
```
or
```
--secret $(az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs)
```
It throws the same error
`Error decoding secrets: Expecting value: line 1 column 2 (char 1)`

**Comment by tjprescott** [comment] 2019-02-07 01:26
What steps have you taken to troubleshoot the problem?

**Comment by tjprescott** [comment] 2019-02-07 01:40
@adewaleo I can reproduce this on CloudShell, though that doesn't rule out the possibility that it might fail on other Linux environments.

@WiseMack as a workaround, I have tested the following syntax in Cloud Shell:

```
secret=$(az keyvault secret list-versions --vault-name $keyvaultName --name $cert --query "[?attributes.enabled].id" --output tsv)
az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs > secrets.json
az vm create --name $VMName --resource-group $resourceGroup --image $image --secrets @secrets.json

```

**Comment by tjprescott** [comment] 2019-02-07 01:41
@adewaleo when I echo the value of `vm_secrets` in Cloud Shell, it looks like this:
`[ { "sourceVault": { "id": "/subscriptions/xxxx/resourceGroups/tjp-rg/providers/Microsoft.KeyVault/vaults/tjpkv12" }, "vaultCertificates": [ { "certificateUrl": "https://tjpkv12.vault.azure.net/secrets/cert1/xxxx" } ] } ]`

If I were to guess, I would say that the spaces between characters might be the cause of the issue.

**Comment by WiseMack** [comment] 2019-02-07 01:51
I tried to remove the spaces between characters manually, same error

**Comment by WiseMack** [comment] 2019-02-07 02:22
When running the same commands in PowerShell
At line:1 char:255
+ ...  --location "Canada Central" --nics $nics --ssh-key-value @"~/.ssh/id ...
No characters are allowed after a here-string header but before the end of the line.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : UnexpectedCharactersAfterHereStringHeader

The --ssh-key-value @"~/.ssh/id .. opens the string but doesn't close it.

When placing --location, --ssh-key-value in variables like this
```
$keyFile =cat "~/.ssh/id_rsa.pub"
$location = "Canada Central"
az vm create --name $VMName --resource-group $resourceGroup --admin-username $admin --authentication-type ssh --boot-diagnostics-storage $bootDiagStorage --custom-data $customData --image $image --location $location --nics $nics --ssh-key-value $keyFile --subscription $subs --secrets $vm_secret
```
It throws the same error as Bash
``Error decoding secrets: Expecting value: line 1 column 2 (char 1)``

> @adewaleo I can reproduce this on CloudShell, though that doesn't rule out the possibility that it might fail on other Linux environments.
> 
> @WiseMack as a workaround, I have tested the following syntax in Cloud Shell:
> 
> ```
> secret=$(az keyvault secret list-versions --vault-name $keyvaultName --name $cert --query "[?attributes.enabled].id" --output tsv)
> az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs > secrets.json
> az vm create --name $VMName --resource-group $resourceGroup --image $image --secrets @secrets.json
> ```

Do you mean PowerShell?
CloudShell is the **Environment** Powershell the Bash/PowerShell selection

**Comment by WiseMack** [comment] 2019-02-07 02:27
> @WiseMack as a workaround, I have tested the following syntax in Cloud Shell:

How exactly did you test 
`secret=$(az keyvault secret list-versions --vault-name $keyvaultName --name $cert --query "[?attributes.enabled].id" --output tsv)`
in CloudShell?
Do you mean you tested it on Bash?

**Comment by WiseMack** [comment] 2019-02-07 02:59
The code
> ```
> secret=$(az keyvault secret list-versions --vault-name $keyvaultName --name $cert --query "[?attributes.enabled].id" --output tsv)
> az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs > secrets.json
> az vm create --name $VMName --resource-group $resourceGroup --image $image --secrets @secrets.json
> ```

After adding the missing parameters has allowed me to finally create the VM !Insert Fireworks Here!

**Comment by WiseMack** [comment] 2019-02-07 02:59
There are still several problems with this that have been uncovered in this process
The @secrets.json workaround works, but is exactly that a **WORKAROUND** to be used when the proper method doesn't work.
The proper method doesn't work because of the following reasons

the --location parameter does not accept variables with more than 1 word
This works
`--location "Canada Central"`
This doesn't work
```
locat="Canada Central"
--location $locat
```
Error Message:
az: error: unrecognized arguments: Central

The --ssh-key-value parameter does not accept variables
This works
--ssh-key-value @"~/.ssh/id_rsa.pub"
This doesn't work
```
keyFile=$(cat ~/.ssh/id_rsa.pub)
--ssh-key-value $keyFile
```
Error Message:
az: error: unrecognized arguments: AAAAB3...

The --secrets parameter does not accept variables or commands
This works
```
secret=$(az keyvault secret list-versions --vault-name $keyvaultName --name $cert --query "[?attributes.enabled].id" --output tsv)
az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs > secrets.json
--secrets @secrets.json
```
This doesn't work
```
secret=$(az keyvault secret list-versions --vault-name $keyvaultName --name $cert --query "[?attributes.enabled].id" --output tsv)
vm_secret=$(az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs)

Either
--secrets $vm_secret
Or
--secrets (az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs)
```
For the same reason
`Error decoding secrets: Expecting value: line 1 column 2 (char 1)`

**Comment by adewaleo** [comment] 2019-02-07 19:34
@WiseMack, I can look into this issue more in depth later, however, this appears to me at first glance to be a shell quoting issue.  I will suggest you debugging with --debug (e.g. `az vm .... --debug`). It shows you what arguments the shell passes on to the CLI.

**Comment by adewaleo** [comment] 2019-03-05 02:44
I am closing this issue as these are bash syntax issues and not CLI issues.

For example concerning the location "issue":
```
(cli-venv) [06:30 PM] Work-Mac:azure-cli tosin$ locat="Canada Central"
(cli-venv) [06:31 PM] Work-Mac:azure-cli tosin$ az group create -n foo-test -l $locat
az: error: unrecognized arguments: Central
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {group} ...
(cli-venv) [06:31 PM] Work-Mac:azure-cli tosin$ az group create -n foo-test -l $locat --debug
File logging enabled - writing logs to '/Users/tosin/.azure/logs'.
Command arguments: ['group', 'create', '-n', 'foo-test', '-l', 'Canada', 'Central', '--debug']
Event: Cli.PreExecute []
```

We see that only canada is pased to the command when we expand `$locat`, the shell does not quote "Canada Central" (single token / string) when expanding the variable but instead passes two individual tokens which the CLI interprets differently. 

The solution is to quote the expanded variable like so:
```
(cli-venv) [06:34 PM] Work-Mac:azure-cli tosin$ az group create -n foo-test -l "$locat" --debug
File logging enabled - writing logs to '/Users/tosin/.azure/logs'.
Command arguments: ['group', 'create', '-n', 'foo-test', '-l', 'Canada Central', '--debug']
Event: Cli.PreExecute [] 
```

As you can see the CLI receives a single location token "Canada Central" instead of two separate tokens.

For your other issues:

run:

`--secrets "$vm_secret"`

instead of:

`--secrets $vm_secret`

To pass the result of a shell command into another command do the following

`az some command --param $(az another command )`

Solutions / conclusions:

- I suggest you read / learn more about bash syntax and quoting strings. 
- You would probably find the [pro tips doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md), particularly the section on [quoting issues](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues) helpful.
- The pro tips docs has helpful examples showing how to pass the result of a command to another
- The CLI's `--debug` parameter is very helpful with figuring out what arguments the shell actually passes to the CLI. 
- If any of [our](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest) examples are incorrect, **please** inform us.

Thanks,

Tosin

**Closed by adewaleo** 2019-03-05 02:44 UTC
Labels: Compute-cli, bug
