### ISSUE TITLE
Encrypt file using sops using a key store in Azure Vault

### ISSUE THREAD

**Issue by Shaun-Harrison** [Azure/azure-cli#16729] opened 2021-01-29 08:40 UTC
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://vault.azure.net was not found in the tenant named [TENTANT_ID]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az cloud set -n AzureChinaCloud` - this doesn't seem to make a difference but is suppose to change the CLI to know its using China Cloud
- Have a key vault created and a key inside with encrypt and decrypt permission 
- `sops --encrypt --azure-kv https://[VAULT_NAME].vault.azure.cn/keys/[KEY_NAME] secrets.yaml`

## Expected Behavior

Instead of authorization using `https://vault.azure.net` it uses `*.azure.cn` so that it can find the correct tenant
## Environment Summary
```
Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Python 3.6.8
Installer: RPM

azure-cli 2.18.0

```

**Comment by yonzhan** [comment] 2021-01-29 10:42
Account

**Comment by Ethan-LF** [comment] 2021-02-02 08:54
@Shaun-Harrison  The reason why failed to invoke China Azure Key Vault is caused by the limitation of sops tool as when SOPS invokes Azure key vault the internal SOPS will invoke the ip address of Global azure key vault by default and at the meantime the HELP inside sops tool does not have the functions which is similar to switching the environment of Azure Cloud( switch the account between domestic and global)..

**Comment by Shaun-Harrison** [comment] 2021-02-02 09:01
Hi @Ethan-LF - so there is nothing you can do at this time for this issue?

I have opened an issue with SOPS about this, but not had a reply yet https://github.com/mozilla/sops/issues/809

Is there another way of being able to encrypt & decrypt secrets in a similar way that you can suggest?

**Comment by Ethan-LF** [comment] 2021-02-02 12:57
Hi Shaun, I regret to inform you that we will not be able to invoke China azure key vault by using the sops tool , I do not found a better tool that similar to SOPS. Can you try it in the SDK way？Please see the details:
https://stackoverflow.com/questions/61966417/using-key-by-azure-key-vault-to-encrypt-and-decrypt-text

**Comment by jiasli** [comment] 2021-02-03 02:54
@Ethan-LF, 

> ... when SOPS invokes Azure key vault the internal SOPS will invoke the ip address of Global azure key vault by default ...

This issue actually doesn't have anything to do with IP addresses. Key Vaults in `AzureChinaCloud` and `AzureCloud` have different IPs resolved by DNS servers.

Key Vault is not a pre-defined `--resource-type`

```
> az account get-access-token --help
...
Arguments
    --resource         : Azure resource endpoints. Default to Azure Resource Manager.
    --resource-type    : Type of well-known resource.  Allowed values: aad-graph, arm, batch, data-
                         lake, media, ms-graph, oss-rdbms.
```

It should be provided as a URL directly via `--resource`, like `https://vault.azure.net`, so it won't change according to the selected cloud (via `az cloud set`).

As described in [Key Vault Authentication](https://docs.microsoft.com/en-us/azure/key-vault/general/authentication-requests-and-responses#authentication),

> Key Vault SDK clients for secrets, certificates, and keys in the first call to Key Vault do not provide an access token to retrieve tenant information. It’s expected to receive an HTTP 401 using Key Vault SDK client where the Key Vault shows to the application the WWW-Authenticate header containing the resource and the tenant where it needs to go and ask for the token. If everything is configured correctly, the second call from the application to Key Vault will contain a valid token and will succeed.

the client ([SOPS](https://github.com/mozilla/sops)) should get the `resource` for authentication from `WWW-Authenticate` header of the `401` response

```
401 Not Authorized  
WWW-Authenticate: Bearer authorization="…", resource="…"  
                                            ^^^^^^^^^^^^
```

instead of calling `az account get-access-token` directly with `--resource https://vault.azure.net`, as `https://vault.azure.net` is the `resource` for Key Vault in `AzureCloud` and will certainly fail in `AzureChinaCloud`.

**Comment by romeomorcia-wipro** [comment] 2021-03-17 15:11
@yonzhan @houk-ms any news regarding the fix?
I'm trying to find a workaround but couldn't find any.

**Comment by jiasli** [comment] 2021-03-18 03:20
@romeomorcia-wipro, Thank you for the SOPS solution. 

> @yonzhan @houk-ms @jiasli any news regarding the fix?

This is never an Azure CLI issue as I explained in https://github.com/Azure/azure-cli/issues/16729#issuecomment-772179264.

You may reach out to SOPS and instruct them to follow the standard Key Vault's `WWW-Authenticate` challenge protocol instead.

**Closed by jiasli** 2021-03-18 03:20 UTC
Labels: Account, Service Attention
