### ISSUE TITLE
'groupMembershipClaims' not found on root. Send it as an additional property 

### ISSUE THREAD

**Issue by way2arun** [Azure/azure-cli#8729] opened 2019-03-07 22:16 UTC
az ad app update --id XXXXXXXXXXXX--set groupMembershipClaims=All
Property 'groupMembershipClaims' not found on root. Send it as an additional property .
working on az cli version 2.0.59
if you list out the help 
az ad app update --id xxxxxxx  -h  (shows the  update an application's group membership claims to "All")  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment] 2019-03-07 23:35
The command actually works. 
The warning you quoted was emitted out by the generic updater with the root cause that the rest spec being incomplete, which my https://github.com/Azure/azure-rest-api-specs/pull/5181 will fix

Since everything is by-design, i am closing this issue

**Closed by yugangw-msft** 2019-03-07 23:35 UTC
Labels: Graph-cli, Needs Triage
