### ISSUE TITLE
azure-cli and alpine:3.9 - requests dependencies

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/azure-cli#9167] opened 2019-04-22 20:05 UTC
I have no luck with this Dockerfile on alpine:3.9.
Can anyone check dependecies?
Thanks
```
FROM alpine:3.9

ENV AZ 2.0.62

RUN apk add -U python3 bash && \
    apk add --virtual=build gcc python3-dev musl-dev libffi-dev openssl-dev make  && \
    pip3 install azure-cli==${AZ} && \
    ln -s /usr/bin/python3 /usr/bin/python
```
# log output:
```
...
requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25 which is incompatible
azure-cli-appservice 0.2.17 has requirement cryptography<2.5, but you'll have cryptography 2.6.1 which is incompatible.
...
```

# az login output:
```
/usr/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <CODE> to authenticate
```

Reference: https://github.com/Azure/azure-cli/issues/8863 

# Workaround
```
RUN apk add -U python3 bash && \
    apk add --virtual=build gcc python3-dev musl-dev libffi-dev openssl-dev make  && \
    pip3 install --upgrade requests && \
    pip3 install azure-cli==${AZ} && \
    ln -s /usr/bin/python3 /usr/bin/python
```

**Comment by rcarun** [comment] 2019-05-28 22:45
@marstr any update on this issue?

**Comment by marstr** [comment] 2019-05-28 23:07
Sorry, should have closed the loop. This is a dupe of https://github.com/Azure/azure-cli/issues/9257

Basically though, the answer is that the workaround presented is a totally viable one without any drawbacks. (Other than having to had applied a workaround, which stinks in and of itself.) Since this issue was filed, we've locked down the particular version of urllib3 in all of our release channels to squash this error. Also, in https://github.com/Azure/azure-cli/issues/9257 there's a discussion about our long term plan to create reproducible builds.

**Closed** 2019-05-28 23:21 UTC
Labels: Packaging/Docker, Question
