### ISSUE TITLE
Show computername of the remote machine in MSTSC when using az bastion

### ISSUE THREAD

**Issue by kayasax** [Azure/azure-cli#21327] opened 2022-02-16 09:47 UTC
**The VM name we are connected to should appear cleary in the  mstsc window's title bar**
when using az bastion the mstsc title is something like `localhost:<port>`
this is not optimal when we connect to several VMs, a better title would be to include the computername of the target VM

![2022-02-16_10_43_54](https://user-images.githubusercontent.com/1241767/154238520-ac443193-dd2e-4d4e-a18e-3cb71e674d21.png)

**Comment by yonzhan** [comment] 2022-02-16 10:12
route to CXP team

**Comment by SatishBoddu-MSFT** [comment] 2022-02-16 21:09
Hello @kayasax Thanks for the great Feedback!

Are you using the Azure Portal to connect via Bastion? or using RDP?

Some related old thread on this topic may help : [Link ](https://social.technet.microsoft.com/Forums/ie/en-US/8e641777-2d3e-4c14-9954-6dde8d3af0e6/how-to-change-title-bar-text-of-a-remote-desktop-connection?forum=winRDc#:~:text=The%20solution%20that%20worked%20for%20me%20was)

_The solution that worked for me was modifying my hosts file **C:\Windows\System32\drivers\etc\hosts**
In the hosts file you can create multiple aliases to the same IP address, and then you can use the alias to connect to remote desktop and the title bar text will show the alias name.
In your example above you could have a line like:
`127.0.0.1 MyAwesomePC`
In your hosts file, and then when connecting to remote desktop use MyAwesomePC:6000, and that will be what shows up in remote desktop._

**Comment by kayasax** [comment] 2022-02-17 07:06
Hello @SatishBoddu-MSFT I'm using the bastion rdp feature ( az network bastion rdp ) as seen  [here](https://argonsys.com/microsoft-cloud/library/how-to-transfer-files-to-your-azure-vm-with-no-public-open-rdp-port/ )

**Comment by SatishBoddu-MSFT** [comment] 2022-02-22 00:55
Hello @kayasax Thanks for the info!
Yes, I too see this behavior, let me check further on this!

**Comment by SatishBoddu-MSFT** [comment] 2022-02-25 21:43
Hello @kayasax thanks for the time on this issue!

We have a confirmation from the Product team and this is expected behavior as of now!

As it turns out at this time the product feature you are looking for is not supported. May I request you to please log the same on the[ official IDEAS portal?](https://feedback.azure.com/d365community/search/?q=bastion)

The product group does monitor the request and they can plan for the implementation in the future. Once you log the feature request you will also be notified of the status of the request. We expect you to keep using this forum and motivate others to do the same. You can always help other community members by answering their queries.

![image](https://user-images.githubusercontent.com/62923178/155806976-d81c35d4-6f83-410c-8dbc-c2d7ef54ddcc.png)


We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.


Thanks

**Closed by SatishBoddu-MSFT** 2022-02-25 21:43 UTC
Labels: Network, Feedback, customer-reported, Network - Bastion, feature-request, CXP Attention
