### ISSUE TITLE
Bash variable expansion swallows quotes

### ISSUE THREAD

**Issue by andythsu** [Azure/azure-cli#7658] opened 2018-10-24 15:20 UTC
key_1 = "foo"
key_2 = "boo"
val_1="foo 1"
val_2="boo 2"
tags=$key_1=$val_1 $key_2=$val_2
--tags $tags <- this command will give me error as it will parse the space in val_1 and val_2
please help. Thanks

_Originally posted by @andythsu in https://github.com/Azure/azure-cli/issue_comments#issuecomment-432701964_

**Comment by tjprescott** [comment] 2018-10-24 17:22
@andythsu the short answer to your question is, there is no solution due to limitations of the bash shell.

```bash
export key1="key"
export val1="val 1"
export tags="$key1=$val1"
echo $tags
> key=val 1
```
The CLI will not accept the above.

```bash
export key1="key"
export val1="val 1"
export tags="$key1=\"$val1\""
echo $tags
> key="val 1"
```
This looks like is *should* work, but when you run:
`az foo create --tags $tags`
You end up with:
```
"tags": {
  "1\"": "",
  "foo": "\"foo"
}
```

**Comment by andythsu** [comment] 2018-10-24 17:35
is there a wordaround to this? such as can I create with no tags first, and then update? or it's simply not possible

**Comment by tjprescott** [comment] 2018-10-24 17:41
You'd get the same result with update. The issue is that the bash shell either swallows the quotes entirely (1st case) or forces their preservation with (second).

**Comment by andythsu** [comment] 2018-10-24 17:43
yes... so I can only do --tags key="value", can't dynamically add keys right?

**Comment by tjprescott** [comment] 2018-10-24 17:45
Well, you can do `--tags key="value 1"` as well, but not through $ expansion (at least not on bash).  We will discuss whether we can implement a feasible workaround.

**Comment by andythsu** [comment] 2018-10-24 17:52
The workaround we've found out is to create tags with no spaces, then update each tag with spaces value in it.
running az group update --name $name --set tags."$key=$value" somehow works

**Comment by williexu** [comment] 2018-10-24 20:54
@andythsu you can do:
```
key=key
val="val 1"
az foo --tags "$key"="$val"
```
```
tag1="key=val 1"
tag2="key2=val 2"
az foo --tags "$tag1" "$tag2"
```
Please let me know if you have other scenarios

**Comment by tjprescott** [comment] 2018-10-24 21:28
This works for the single tag case, but not for his original question:
```bash
export key1=key1
export val1="val 1"
export key2=key2
export val2="val 2"
export tags=$key1=$val1 $key2=$val2

az foo --tags "$tags"

"tags": {
  "key1": "val 1 key2=val 2"
}

**Comment by williexu** [comment] 2018-10-24 21:39
Use arrays in that case:
```
tags=( "$key=$val1" "$tag1" )
az foo --tags --tags "${tags[@]}"
```
@andythsu if you would rather not use arrays, please use the examples I mentioned before, which should already let you bypass the restrictions of having to subsequently update and avoid spaces.

**Comment by tjprescott** [comment] 2018-10-24 22:22
Thanks @williexu. I'm closing this issue.

**Closed by tjprescott** 2018-10-24 22:22 UTC
Labels: Discussion, Question

**Comment by andythsu** [comment] 2018-10-25 13:36
@williexu Thank you for the suggestions!

**Comment by andythsu** [comment] 2018-10-25 13:36
@tjprescott Thanks for the comments too!
