### ISSUE TITLE
Dynamic example doesn't work for az monitor metrics alert create command.

### ISSUE THREAD

**Issue by pvanroos** [Azure/azure-cli#16216] opened 2020-12-10 00:38 UTC
Dynamic example doesn't work for az monitor metrics alert create command.

Running the following command on Azure Shell (v2.16):

az monitor metrics alert create -n "RuleName" -g "ResourceGroupName" \
        --description "Dynamically created alert rule" \
        --region "westus2" \
        --action "" \
        --evaluation-frequency 5m \
        --window-size 5m \
        --scopes "{redacted}" \
        --severity 2 \
        --condition "avg HttpResponseTime > dynamic medium 2 of 4 since 2020-10-01T10:23:00.000Z"

This is a new feature in 2.16 but it doesn't work.  I get the following error output after running it:

Error parsing request payload Activity ID: e6ca114f-426e-42e1-8b37-26a5da7c813f.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#az_monitor_metrics_alert_create)
* Content Source: [latest/docs-ref-autogen/monitor/metrics/alert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/monitor/metrics/alert.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-12-10 01:03
monitor

**Comment by rem-aj** [comment] 2020-12-10 04:26
I am able to reproduce the same issue, here is my command

az monitor metrics alert create -n "name" -g RG --scopes "XXXXXXXX" --condition "total FailedRequests > dynamic low 2 of 4 since 2020-11-01T10:23:00.000Z" --description "The Total # of Failed Requests is Greater than Standard Patterns normally seen. Please Investigate" --window-size 15m --evaluation-frequency 5m --severity 4 --debug

**Comment by kairu-ms** [comment] 2020-12-10 07:56
Acknowledged. It is a bug when you use a single scope. I'm fixing it.

**Comment by kairu-ms** [comment] 2020-12-10 09:31
Thanks for your help. This issue will be fixed in next release. You can download and use these [Artifacts](https://dev.azure.com/azure-sdk/public/_build/results?buildId=649106&view=artifacts&pathAsName=false&type=publishedArtifacts) as first.

**Comment by pvanroos** [comment] 2020-12-10 17:27
In the Release Notes for v2.16, it says that the feature was included:  https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#monitor

Are you guys saying it actually wasn't?

**Comment by rem-aj** [comment] 2020-12-10 18:14
@kairu-ms I'm not sure what you mean by download and use those artifacts. I went to that link and I'm unable to access anything when I click on any of the artifact links.
When can expect the fix?
Thanks!

**Comment by kairu-ms** [comment] 2020-12-11 03:31
@pvanroos @rem-aj Sorry for the bug. 
The patch PR has been created and it's going through reviewing and releasing process. It will take some days (at most 21 days). So I built the patched artifacts for your urgent use. 
You can download them by the following links and install locally.
* [Docker](https://artprodcus3.artifacts.visualstudio.com/A0fb41ef4-5012-48a9-bf39-4ee3de03ee35/29ec6040-b234-4e31-b139-33dc4287b756/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6dXJlLXNkay9wcm9qZWN0SWQvMjllYzYwNDAtYjIzNC00ZTMxLWIxMzktMzNkYzQyODdiNzU2L2J1aWxkSWQvNjQ5MTA2L2FydGlmYWN0TmFtZS9kb2NrZXI1/content?format=zip)
* [metadata](https://artprodcus3.artifacts.visualstudio.com/A0fb41ef4-5012-48a9-bf39-4ee3de03ee35/29ec6040-b234-4e31-b139-33dc4287b756/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6dXJlLXNkay9wcm9qZWN0SWQvMjllYzYwNDAtYjIzNC00ZTMxLWIxMzktMzNkYzQyODdiNzU2L2J1aWxkSWQvNjQ5MTA2L2FydGlmYWN0TmFtZS9tZXRhZGF0YQ2/content?format=zip)
* [msi](https://artprodcus3.artifacts.visualstudio.com/A0fb41ef4-5012-48a9-bf39-4ee3de03ee35/29ec6040-b234-4e31-b139-33dc4287b756/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6dXJlLXNkay9wcm9qZWN0SWQvMjllYzYwNDAtYjIzNC00ZTMxLWIxMzktMzNkYzQyODdiNzU2L2J1aWxkSWQvNjQ5MTA2L2FydGlmYWN0TmFtZS9tc2k1/content?format=zip)
* [pypi](https://artprodcus3.artifacts.visualstudio.com/A0fb41ef4-5012-48a9-bf39-4ee3de03ee35/29ec6040-b234-4e31-b139-33dc4287b756/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6dXJlLXNkay9wcm9qZWN0SWQvMjllYzYwNDAtYjIzNC00ZTMxLWIxMzktMzNkYzQyODdiNzU2L2J1aWxkSWQvNjQ5MTA2L2FydGlmYWN0TmFtZS9weXBp0/content?format=zip)

Thanks.

**Closed** 2020-12-21 06:36 UTC
Labels: Monitor, OKR3.2 Candidate, feature-request
