### ISSUE TITLE
Az Bicep Format throws error

### ISSUE THREAD

**Issue by m-soltani** [Azure/azure-cli#25892] opened 2023-03-20 23:43 UTC
## Describe the bug

**Command Name**
`az bicep format`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
ensure_bicep_installation() missing 1 required positional argument: 'cli_ctx'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3678, in format_bicep_file
TypeError: ensure_bicep_installation() missing 1 required positional argument: 'cli_ctx'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep format -f {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0

Extensions:
aks-preview 0.5.117
azure-devops 0.25.0
change-analysis 0.1.0
containerapp 0.3.16
maintenance 1.3.0
stream-analytics 0.1.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2023-03-21 00:39
route to CXP team

**Comment by navba-MSFT** [comment] 2023-03-21 03:24
@m-soltani Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2023-03-27 03:22
@m-soltani This PR https://github.com/Azure/azure-cli/pull/25707 has the fix for this issue. It is currently under review.

**Comment by navba-MSFT** [comment] 2023-03-28 03:54
@m-soltani This issue is a duplicate of  https://github.com/Azure/azure-cli/issues/25706 . Please refer this thread for the fix.

**Closed by navba-MSFT** 2023-03-28 03:54 UTC
Labels: ARM, customer-reported, CXP Attention
