### ISSUE TITLE
az cli on debian crashes

### ISSUE THREAD

**Issue by eswues** [Azure/azure-cli#24308] opened 2022-10-20 14:07 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/lib/python3/dist-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/usr/lib/python3/dist-packages/azure/cli/core/auth/identity.py", line 112, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/usr/lib/python3/dist-packages/msal/application.py", line 1525, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.19.0-2-amd64-x86_64-with-glibc2.35, Debian GNU/Linux bookworm/sid
Python 3.10.7
Installer: DEB

azure-cli 2.41.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by eswues** [comment] 2022-10-20 14:09
I was trying to use az cli on debian. no luck. I was reinstaling tool together with all python dependencies, I was trying to install it throuth pip. no success. I am on debian testing
I work as azure admin and this situation makes my work much harder and inconvinient.

**Comment by yonzhan** [comment] 2022-10-20 22:57
@jiasli for awareness

**Comment by bebound** [comment] 2022-10-21 06:50
Duplicate of https://github.com/Azure/azure-cli/issues/19640

You need to pin priority in Debian sid.

**Closed by bebound** 2022-10-21 06:50 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
