### ISSUE TITLE
az bot msteams create returns an error

### ISSUE THREAD

**Issue by mpustelnik** [Azure/azure-cli#9645] opened 2019-06-12 07:18 UTC
## Describe the bug

**Command Name**
`az bot msteams create`

**Errors:**
```
Error occurred in sending request. Please file an issue on https://github.com/Microsoft/botbuilder-tools/issues
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az bot msteams create --name {} --resource-group {}`

## Expected Behavior
MS Teams channel created without an error message.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66

Extensions:
application-insights 0.1.1
interactive 0.4.3

```
## Additional Context

Despite error message MSTeams channel is successfully configured on bot.

**Comment by jkolonko** [comment] 2019-06-12 07:29
Also reproducible in Cloud Shell.

**Comment by tjprescott** [comment] 2019-06-12 12:18
Did you also file an issue here:
`Please file an issue on https://github.com/Microsoft/botbuilder-tools/issues`

**Comment by mpustelnik** [comment] 2019-06-12 14:27
No, I didn't because I thought that it is related only to azure cli. Should I create another issue on botbuilder tools repository?

**Comment by tjprescott** [comment] 2019-06-13 16:30
@stevengum for comment.

**Comment by stevengum** [comment] 2019-06-14 16:54
@mpustelnik thanks for filing this issue, since someone filed an issue in botbuilder tools and added the debug logs we can close this issue and track the issue there. as there's more information in that issue.

microsoft/botbuilder-tools#1176

If the issue is filed in the tools repo we are usually able to respond quicker by virtue of seeing it sooner, but ultimately there isn't a real difference in filing an issue in the azure-cli repo or in the botbuilder-tools repo.

**Closed** 2019-06-17 14:57 UTC
Labels: BotService, Bug, Service Attention
