### ISSUE TITLE
Encryption options during storage account creation

### ISSUE THREAD

**Issue by alexvicegrab** [Azure/azure-cli#4248] opened 2017-08-17 12:58 UTC
### Description

While running

az storage account create -g mygroup -n mystorageaccount --sku Standard_LRS --encryption blob file table queue
I see the follwoing error: init() got an unexpected keyword argument 'table'

az storage account create -g mygroup -n mystorageaccount --sku Standard_LRS --encryption blob file
Appears to work fine, but table and queue encryption during creation seems to fail due to some problem with the python parsing.

Thanks!

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here: Mac OS X 10.12.6 (16G29)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: zsh

**Comment by tjprescott** [comment] 2017-08-17 17:05
This is essentially a duplicate of #4220.

**Closed by tjprescott** 2017-08-17 17:05 UTC
