### ISSUE TITLE
az login fails on WSL2 ubuntu

### ISSUE THREAD

**Issue by michael-fortin** [Azure/azure-cli#21226] opened 2022-02-08 20:51 UTC
## Describe the bug
unable to login on MSL2 ubuntu
**Command Name**
`az login` & `az login --use-device-code`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1644324580.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/6c4b3346-5ad4-4991-b51e-bb35a33065b0/v2.0",
  "iat": 1644352888,
  "nbf": 1644352888,
  "exp": 1644356788,
  "aio": "AWQAm/8TAAAAyU7dp5Pzxp0CNUuUsRFSWpiesCuefFuB1gZ8KHi69e+rRQnVh1OWytE1q2CW+A/XSkI8OxSaoJDSroUD8DAtVpKoMJqfOGfp0bhSGz1CyJD6xAn4joLciwYi77elCsfU",
  "name": "Michael Fortin",
  "nonce": "2f6b4a167c4461c48577ae0cf9ad5c01f6bdae056dba9bbe785c6c8ee5680c35",
  "oid": "7a69d856-298c-43ef-be61-441263fe09a0",
  "preferred_username": "michael.fortin@fadv.com",
  "puid": "10032000526BDFC5",
  "rh": "0.ARwARjNLbNRakUm1Hrs1ozBlsJV3sATbjRpGu-4C-eG_e0YcADQ.",
  "sub": "Q74lNKVGIkeNkIdS-z37SpIAuBSADz_XwqjYpO6-YDE",
  "tid": "6c4b3346-5ad4-4991-b51e-bb35a33065b0",
  "uti": "twsFIkuWEEOwb94LdOknAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 158, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 173, in login_with_auth_code
    success_template=success_template, error_template=error_template, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 1563, in acquire_token_interactive
    **kwargs))
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 282, in obtain_token_by_browser
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 641, in obtain_token_by_browser
    receiver, redirect_uri=uri, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 679, in _obtain_token_by_browser
    flow, auth_response, scope=scope, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 136, in obtain_token_by_auth_code_flow
    auth_code_flow, auth_response, headers=headers, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
    auth_code_flow, auth_response, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 561, in obtain_token_by_auth_code_flow
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 115, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 795, in _obtain_token
    "response": _resp, "params": params, "data": _data,
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 582, in <lambda>
    event, environment=authority.instance)),
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 307, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 153, in __add
    if id_token else {})
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    err, _now, json.dumps(decoded, indent=2)))
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1644324580.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/6c4b3346-5ad4-4991-b51e-bb35a33065b0/v2.0",
  "iat": 1644352888,
  "nbf": 1644352888,
  "exp": 1644356788,
  "aio": "AWQAm/8TAAAAyU7dp5Pzxp0CNUuUsRFSWpiesCuefFuB1gZ8KHi69e+rRQnVh1OWytE1q2CW+A/XSkI8OxSaoJDSroUD8DAtVpKoMJqfOGfp0bhSGz1CyJD6xAn4joLciwYi77elCsfU",
  "name": "Michael Fortin",
  "nonce": "2f6b4a167c4461c48577ae0cf9ad5c01f6bdae056dba9bbe785c6c8ee5680c35",
  "oid": "7a69d856-298c-43ef-be61-441263fe09a0",
  "preferred_username": "michael.fortin@fadv.com",
  "puid": "10032000526BDFC5",
  "rh": "0.ARwARjNLbNRakUm1Hrs1ozBlsJV3sATbjRpGu-4C-eG_e0YcADQ.",
  "sub": "Q74lNKVGIkeNkIdS-z37SpIAuBSADz_XwqjYpO6-YDE",
  "tid": "6c4b3346-5ad4-4991-b51e-bb35a33065b0",
  "uti": "twsFIkuWEEOwb94LdOknAA",
  "ver": "2.0"
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- start wsl shell interminal
- `az login`

## Expected Behavior
to verify identity and login

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.33.0
```

**Comment by yonzhan** [comment] 2022-02-08 23:44
@jiasli for awareness

**Comment by jiasli** [comment] 2022-02-09 02:11
Duplicate of #20388

**Closed by jiasli** 2022-02-09 02:11 UTC
Labels: Account, customer-reported
