### ISSUE TITLE
az login failed

### ISSUE THREAD

**Issue by Jas0n0ss** [Azure/azure-cli#24798] opened 2022-12-02 15:09 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1669977683.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1669993320,
  "nbf": 1669993320,
  "exp": 1669997220,
  "aio": "AYQAe/8TAAAA0tzYQ2k/93FlZLUg2TQZ7uEh5qQu4EJU9ELIaujE+TJclrJ4y3TPkrr+0AcEmPKfz8fiF6bOOjIBLYTN0ClOWjdbD6oJeM5k1yjC51W+MS5BanoHmhv80N2aW7mwhwTSvoYkocwoD8l5gPoMyMe4k2VIUyACpegaBzEVRg1h5zI=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "preferred_username": "Iibmer@outlook.com",
  "rh": "0.ASYAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAAQ.",
  "sub": "7WhX7FgTOhEQb6KQ1D4AZ7EpgAqiJJKDTJ6TmoNmgoA",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "FJssbeyc0UyZ0dg6ZSFPAg",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/root/lib/azure-cli/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 148, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 152, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/application.py", line 1681, in acquire_token_by_device_flow
    **kwargs))
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 384, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 347, in _obtain_token_by_device_flow
    self.DEVICE_FLOW["GRANT_TYPE"], data=data, **kwargs)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 795, in _obtain_token
    "response": _resp, "params": params, "data": _data,
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/application.py", line 600, in <lambda>
    event, environment=authority.instance)),
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/token_cache.py", line 310, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/token_cache.py", line 154, in __add
    if id_token
  File "/root/lib/azure-cli/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 78, in decode_id_token
    err, _now, json.dumps(decoded, indent=2)))
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1669977683.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1669993320,
  "nbf": 1669993320,
  "exp": 1669997220,
  "aio": "AYQAe/8TAAAA0tzYQ2k/93FlZLUg2TQZ7uEh5qQu4EJU9ELIaujE+TJclrJ4y3TPkrr+0AcEmPKfz8fiF6bOOjIBLYTN0ClOWjdbD6oJeM5k1yjC51W+MS5BanoHmhv80N2aW7mwhwTSvoYkocwoD8l5gPoMyMe4k2VIUyACpegaBzEVRg1h5zI=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "preferred_username": "Iibmer@outlook.com",
  "rh": "0.ASYAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAAQ.",
  "sub": "7WhX7FgTOhEQb6KQ1D4AZ7EpgAqiJJKDTJ6TmoNmgoA",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "FJssbeyc0UyZ0dg6ZSFPAg",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.9.2009-Core, CentOS Linux 7 (Core)
Python 3.6.8
Installer: 

azure-cli 2.39.0 *
```

**Comment by yonzhan** [comment] 2022-12-03 02:01
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2022-12-03 02:01 UTC
Labels: Account, customer-reported, Auto-Assign
