### ISSUE TITLE
az login succeeds, but later fails with "connection actively refused"

### ISSUE THREAD

**Issue by mikebutak** [Azure/azure-cli#14910] opened 2020-08-25 15:41 UTC
From command prompt, `az login` launches browser, prompting me to select my user account.  Clicking on my name, the next screen in the browser says "You have logged into Microsoft Azure!" However, about 30 seconds or so later my command line spits out:

`Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x045270B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))`

**Describe the bug**
Browser says login succeeded, but cmd gives error.  

**To Reproduce**
See above

**Expected behavior**
CLI logs in successfully and I'm able to issue commands.

**Environment summary**
Installed via MSI download
OS Windows 10
CLI version 2.11.0

**Comment by yonzhan** [comment] 2020-08-25 23:01
add to S175

**Comment by jiasli** [comment] 2022-10-19 08:13
Duplicate of #11829

**Closed by jiasli** 2022-10-19 08:13 UTC
Labels: Account, customer-reported, feature-request
