### ISSUE TITLE
unable to export ACI configuration to yaml via az container export

### ISSUE THREAD

**Issue by alexadams-ms** [Azure/azure-cli#23955] opened 2022-09-20 20:43 UTC
the command executed was `az container export --resource-group tnt19-mgmt-p01-eastus2 --name tnt19-mgmt-p01-eastus2-resourceserviceworkers --file aci_state.yaml` in subscription id `35c3cfee-42db-4215-8ce5-841ad245db7e`

## Describe the bug

**Command Name**
`az container export`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('cannot represent an object', <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.Identity object at 0x05310DC0>)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 610, in container_export
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 269, in safe_dump
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 241, in dump_all
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/representer.py", line 27, in represent
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/representer.py", line 48, in represent_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/representer.py", line 207, in represent_dict
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/representer.py", line 118, in represent_mapping
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/representer.py", line 58, in represent_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/representer.py", line 231, in represent_undefined
yaml.representer.RepresenterError: ('cannot represent an object', <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.Identity object at 0x05310DC0>)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container export --resource-group {} --name {} --file {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *
```

**Comment by alexadams-ms** [comment] 2022-09-20 21:39
I updated to version azure-cli 2.40.0 and I am still facing the issue.

**Comment by yonzhan** [comment] 2022-09-20 23:07
route to CXP team

**Comment by navba-MSFT** [comment] 2022-12-29 04:43
@alexadams-ms Apologies for the late reply. Thanks for reaching out to us and reporting this issue. While I ran the command it worked fine. While doing some research on this issue, it seems like the issue is specific to those ACI resources which are created from ACR using managed identity. 

Tagging a similar issue here: https://github.com/Azure/azure-cli/issues/24380

I am following up with the product owners and I will update this thread.

**Comment by navba-MSFT** [comment] 2023-01-10 09:10
@alexadams-ms The above PR has been merged now. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Closed by navba-MSFT** 2023-01-10 09:10 UTC
Labels: bug, Container Instances, CXP Attention, Auto-Assign
