### ISSUE TITLE
Issue with installing Azure CLI

### ISSUE THREAD

**Issue by ibashir** [Azure/azure-cli#29930] opened 2024-09-18 20:37 UTC
### Describe the bug

I was installing Azure CLI during the IEEE Quantum Week workshop 2024. az extension add --upgrade -n quantum --debug
...and I get the error message below.
![azure_CLI](https://github.com/user-attachments/assets/0d6724a1-25aa-4bb5-ad35-1dc99df36e9d)

![azure_CLI](https://github.com/user-attachments/assets/6d702946-32e7-4ded-9b0d-55582135384f)

### Related command

az extension add --upgrade -n quantum --debug

### Errors

![azure_CLI](https://github.com/user-attachments/assets/ff151c81-aa43-47b3-9332-330c6711a929)

### Issue script & Debug output

![azure_CLI](https://github.com/user-attachments/assets/2e98050a-50aa-4779-b075-e1b1af3953ee)

### Expected behavior

It should install the package.

### Environment Summary

![azure_CLI2](https://github.com/user-attachments/assets/14b005fc-98e6-4ef5-9c55-f9eda908027d)

**Comment by yonzhan** [comment] 2024-09-18 20:37
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2024-09-19 02:26
Duplicate of https://github.com/Azure/azure-cli/issues/29630

**Closed by bebound** 2024-09-19 02:26 UTC
Labels: Service Attention, question, customer-reported
