### ISSUE TITLE
AKS Template deployment fails when providing a keyvault reference to the "servicePrincipalProfile" attribute.

### ISSUE THREAD

**Issue by Diastro** [Azure/azure-cli#12101] opened 2020-02-07 22:33 UTC
## Describe the bug
When deploying an arm template for AKS, the "servicePrincipalProfile" cannot retrieve secrets from keyvault based on dynamic values (as described here : [Keyvault dynamic ids](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/key-vault-parameter?tabs=azure-cli)).

When providing the following 
```
"servicePrincipalProfile": {
                    "clientId": "[parameters('serviceSpnId')]",
                    "Secret": {
                        "reference": {
                            "keyVault": {
                                "id": "[resourceId(parameters('subscriptionId'), parameters('resourceGroup'), 'Microsoft.KeyVault/vaults', parameters('keyVaultName'))]"
                            },
                            "secretName": "[parameters('serviceSpnId')]"
                        }
                    }
}
```

to the resource/properties/servicePrincipalProfile of element of the template, the deployment failed with :

```
Deployment failed. Correlation ID: 9beefc6e-7fb3-4004-b77a-671e133c51cb. {
  "code": "UnmarshalError",
  "message": "UnmarshalEntity encountered error: json: cannot unmarshal object into Go struct field ServicePrincipalProfile.secret of type string."
}
```

**Command Name**
`az group deployment create`

**Errors:**
```
Deployment failed. Correlation ID: 9beefc6e-7fb3-4004-b77a-671e133c51cb. {

  "code": "UnmarshalError",

  "message": "UnmarshalEntity encountered error: json: cannot unmarshal object into Go struct field ServicePrincipalProfile.secret of type string."

}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a template to deploy aks and set the servicePrincipalProfile to a keyvault reference in the teamplate.json
- `az group deployment create --resource-group {} --template-file {} --parameter {} --debug`

## Expected Behavior
I would expect the deployment to retrieve the secret based on the dynamic id.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.79 *

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment] 2020-02-08 03:07
HI @qwordy  could you pls help to have a look at this issue to see if it's feature related firstly? if no, but arm related, could you pls help to route the issue to @Juliehzl ? thanks a lot.

**Comment by Juliehzl** [comment] 2020-02-13 06:07
@Diastro I have tried with the template you provide and there is no problem to me. Please make sure the parameter values you provided correct, especially service principal information.
What I provided here is my service principal application id for servicePrincipalClientId and password for servicePrincipalClientSecret. I also provide sshPublicKeys and others.

Can you check your parameter again? And if there is still problem, feel free to contact with me.

**Comment by Diastro** [comment] 2020-02-13 17:16
@Juliehzl If you look at the example I put above, this is supposed to be a reference to a keyvault (not providing the secret and appid directly in the template. Providing these directly also works for me but what I'm trying to achieve it providing a reference to a secret which is in keyvault.

**Comment by Diastro** [comment] 2020-02-19 16:41
@Juliehzl Any update on this?

**Comment by dhiraj-raj** [comment] 2020-04-18 17:13
hello, can anyone attach the aks-deploy.json and aks-parameter.json file where they have used key-vault for client id and client secret

**Comment by yungezz** [comment] 2020-08-03 13:54
hi @Juliehzl @qwordy any update on this issue?

**Comment by Juliehzl** [comment] 2020-08-04 06:26
I can reproduced with keyvault reference. From the error message, it is service error from AKS server.

**Comment by TomGeske** [comment] 2020-08-04 06:41
You should try to store your secret in a parameter and reference that parameter in servicePrincipalProfile.

```
"servicePrincipalProfile": {
  "clientId": "[parameters('serviceSpnId')]",
  "secretName": "[parameters('serviceSpnSecret')]"
}

```
Similar to this [guide](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/key-vault-parameter?tabs=azure-cli#reference-secrets-with-dynamic-id)

**Comment by Juliehzl** [comment] 2020-08-04 11:05
Hi @TomGeske, we are using with the following template format. is there anything wrong?

```
                "servicePrincipalProfile": {
                    "clientId": "[parameters('serviceSpnId')]",
                    "Secret": {
                        "reference": {
                            "keyVault": {
                                "id": "[resourceId(parameters('subscriptionId'), parameters('resourceGroup'), 'Microsoft.KeyVault/vaults', parameters('keyVaultName'))]"
                            },
                            "secretName": "[parameters('serviceSpnId')]"
                        }
                    }
                }
```

**Comment by TomGeske** [comment] 2020-08-04 11:45
I think you need to move your keyvault reference outside of your template into the parameters section:

```
"template": {
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "serviceSpnId": {
    "type": "string"
    },
    "serviceSpnSecret": {
      "type": "securestring"
    }
  },
  "resources": [
    {
      "type": "Microsoft.ContainerService/managedClusters",
      "apiVersion": "2020-03-01",
      "servicePrincipalProfile": {
        "clientId": "[parameters('serviceSpnId')]",
        "secretName": "[parameters('serviceSpnSecret')]"
      },
      ...
    }
  ]
},
"parameters": {
  "serviceSpnId": {
    "value": "<id>"
  },
  "serviceSpnSecret": {
    "reference": {
      "keyVault": {
        "id": "[resourceId(parameters('vaultSubscription'), parameters('vaultResourceGroupName'), 'Microsoft.KeyVault/vaults', parameters('vaultName'))]"
      },
      "secretName": "[parameters('secretName')]"
    }
  }
}
```

**Comment by apclouds** [comment] 2021-01-20 22:00
Hello @Diastro, did the suggestion from @TomGeske resolve your issue? Closing this for now given its been several months since response. Feel free to reopen the issue if you still have any outstanding questions here.

**Closed by apclouds** 2021-01-20 22:00 UTC
Labels: AKS, ARM - Templates, Service Attention
