### ISSUE TITLE
Problem with az login use serviceprincipal

### ISSUE THREAD

**Issue by morgulnet** [Azure/azure-cli#26059] opened 2023-04-06 11:23 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u{} {} -p{} {} --tenant {}`

## Environment Summary
```
Linux-5.15.49-linuxkit-x86_64-with, Alpine Linux v3.17
Python 3.9.16
Installer: PIP

azure-cli 2.47.0
```
## Additional Context

az login --service-principal --username --password --tenant

The command failed with an unexpected error. Here is the traceback:
allow_broker=True is only supported in PublicClientApplication
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 159, in login
    identity.login_with_service_principal(username, password, scopes=scopes)
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 182, in login_with_service_principal
    cred = ServicePrincipalCredential(sp_auth, **self._msal_app_kwargs)
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/azure/cli/core/auth/msal_authentication.py", line 132, in __init__
    super().__init__(service_principal_auth.client_id, client_credential=client_credential, **kwargs)
  File "/root/.local/share/virtualenvs/meta-97asrRFr/lib/python3.9/site-packages/msal/application.py", line 555, in __init__
    raise ValueError("allow_broker=True is only supported in PublicClientApplication")
ValueError: allow_broker=True is only supported in PublicClientApplication
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
zsh: exit 1     az login --service-principal --username

**Comment by yonzhan** [comment] 2023-04-06 11:23
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2023-04-07 03:04
Duplicate of #26052

**Closed by jiasli** 2023-04-07 03:04 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
