### ISSUE TITLE
Unable to log into AZ free account subscription

### ISSUE THREAD

**Issue by karthikeyaonda** [Azure/azure-cli#22844] opened 2022-06-12 15:40 UTC
PS C:\azure-tf> az login --tenant 5780a8af-4c6b-44a6-XXXXXXXX
The command failed with an unexpected error. Here is the traceback:
Unable to get authority configuration for https://login.microsoftonline.com/5780a8af-4c6b-44a6-bd5e-a8e812d684b1. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
Traceback (most recent call last):
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 100, in init
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 169, in tenant_discovery
ValueError: OIDC Discovery endpoint rejects our request. Error: {"error":"invalid_tenant","error_description":"AADSTS90002: Tenant '5780a8af-4c6b-44a6-bd5e-axxxxxb1' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\r\nTrace ID: 76dcd1fa-3960-4d2d-b9d8-1d6044156d00\r\nCorrelation ID: eb7c38c8-7dab-43b1-b597-9127696ee28b\r\nTimestamp: 2022-06-12 05:03:25Z","error_codes":[90002],"timestamp":"2022-06-12 05:03:25Z","trace_id":"76dcd1fa-3960-4d2d-b9d8-1d6044156d00","correlation_id":"eb7c38c8-7dab-43b1-b597-9127696ee28b","error_uri":"[https://login.microsoftonline.com/error?code=90002"}](https://login.microsoftonline.com/error?code=90002%22%7D)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 663, in execute
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 726, in _run_jobs_serially
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 697, in _run_job
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 333, in call
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 154, in login
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 134, in login_with_auth_code
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 106, in _msal_app
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1525, in init
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 456, in init
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 104, in init
ValueError: Unable to get authority configuration for https://login.microsoftonline.com/5780a8af-4c6b-44a6-bxxxxx. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
To open an issue, please run: 'az feedback'
PS C:\azure-tf> az feedback

**Comment by yonzhan** [comment] 2022-06-13 00:23
@jiasli for awareness

**Comment by jiasli** [comment] 2022-06-13 02:36
Duplicate of #22841

**Closed by jiasli** 2022-06-13 02:36 UTC
Labels: Account, customer-reported, Auto-Assign
