### ISSUE TITLE
az mysql db create - no support for special characters

### ISSUE THREAD

**Issue by 6heads** [Azure/azure-cli#10218] opened 2019-08-12 08:11 UTC
It doesn't seem to be possible to create a database with the name `my-db`.
In mysql console it is possible to run `create database my-db` escaping the name with ` (Unfortunately I can't show it here, because it gets interpreted as if I want to insert code).

When I try to do the same (az mysql db create -g my-group -s my-server -n `my-db`) in azure cli I always get the error `The provided database name is invalid.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46122767-3366-e20f-2dc8-b19954608386
* Version Independent ID: 5fd2e877-fe6e-8e0d-e29c-bd286ed5f15c
* Content: [az mysql db](https://docs.microsoft.com/en-us/cli/azure/mysql/db?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/mysql/db.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/mysql/db.yml)
* Service: **mysql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ajlam** [comment] 2019-08-12 17:52
@6heads, thanks for reaching out! Can you please enable ANSI_QUOTES mode and try again? This will allow you to use the backticks to escape. You can do this by setting the server parameter `sql_mode` in the Azure portal or Azure CLI. The Azure CLI command would be: 

`az mysql server configuration set -g yourresourcegroup -s yourservername -n sql_mode --value ANSI_QUOTES`

Once that's complete, you'll be able to run the following command:

`az mysql db create -g yourresourcegroup -s yourservername -n new`-`db
`

Give that a try and let me know if it works :)

**Comment by 6heads** [comment] 2019-08-13 06:44
@ajlam 

I tried it but still get the same error. Here is the result of `az mysql server configuration`:

> 2019-08-13T06:35:31.4545257Z {
> 2019-08-13T06:35:31.4545968Z   "allowedValues": ",ALLOW_INVALID_DATES,ANSI_QUOTES,ERROR_FOR_DIVISION_BY_ZERO,HIGH_NOT_PRECEDENCE,IGNORE_SPACE,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_BACKSLASH_ESCAPES,NO_DIR_IN_CREATE,NO_ENGINE_SUBSTITUTION,NO_FIELD_OPTIONS,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_UNSIGNED_SUBTRACTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,PAD_CHAR_TO_FULL_LENGTH,PIPES_AS_CONCAT,REAL_AS_FLOAT,STRICT_ALL_TABLES,STRICT_TRANS_TABLES",
> 2019-08-13T06:35:31.4546222Z   "dataType": "Set",
> 2019-08-13T06:35:31.4546344Z   "defaultValue": "",
> 2019-08-13T06:35:31.4546486Z   "description": "The current server SQL mode.",
> 2019-08-13T06:35:31.4546801Z   "id": "/subscriptions/********-****-****-****-************/resourceGroups/my-group/providers/Microsoft.DBforMySQL/servers/mysql-server/configurations/sql_mode",
> 2019-08-13T06:35:31.4546967Z   "name": "sql_mode",
> 2019-08-13T06:35:31.4547093Z   "resourceGroup": "my-group",
> 2019-08-13T06:35:31.4547226Z   "source": "user-override",
> 2019-08-13T06:35:31.4547346Z   "type": "Microsoft.DBforMySQL/servers/configurations",
> 2019-08-13T06:35:31.4547481Z   "value": "ANSI_QUOTES"
> 2019-08-13T06:35:31.4547588Z }

**Comment by ajlam** [comment] 2019-08-13 20:27
@6heads - thanks for the response. Looks like I can reproduce this as well. When I pass in the DB name as my'-'db (replacing ' with ` ), the DB is actually being created as "mydb" instead of "my-db". Let me follow up with my team to see if we can fix this issue.

**Comment by 6heads** [comment] 2019-08-14 06:05
> @6heads - thanks for the response. Looks like I can reproduce this as well. When I pass in the DB name as my'-'db (replacing ' with ` ), the DB is actually being created as "mydb" instead of "my-db". Let me follow up with my team to see if we can fix this issue.

If I provide `my'-'db` (replacing...) it isn't created as `mydb`. I tried it using powershell 6.2.0 and 5.1.18362.145 to no avail. My azure cli version is 2.0.71 and I use windows 10. I wonder what version you use.

**Comment by ajlam** [comment] 2019-09-04 22:15
@6heads  - I was using the Azure CLI Cloud Shell available in the Azure portal. I believe I was using 2.0.71 as well. 

Sorry for the delay. Myself and my teammate have just returned from vacation, so I am following up with the team now.

**Comment by shin-akuma** [comment] 2019-10-03 07:14
Same issue with ARM template. I've assigned value 'laravel-main' to parameters('databaseName') and the resource below returns error 'InvalidDatabaseName  The provided database name is invalid'
                 {
                    "type": "Microsoft.DBforMySQL/servers/databases",
                    "apiversion": "2017-12-01",
                    "name": "[concat(parameters('serverName'), '/', parameters('databaseName'))]",
                    "dependsOn": [
                        "[resourceId('Microsoft.DBforMySQL/servers', parameters('serverName'))]"
                    ],
                    "properties": {
                      "charset": "utf8",
                      "collation": "utf8_general_ci"
                    }
                  }

**Comment by ajlam** [comment] 2019-10-21 16:46
@6heads, @shin-akuma - we have a fix that will be rolling out in the Nov/Dec timeframe. Our rollout has been delayed due to no-fly zones for deployments during the upcoming US  holidays.

**Comment by shin-akuma** [comment] 2019-10-22 00:47
> @6heads, @shin-akuma - we have a fix that will be rolling out in the Nov/Dec timeframe. Our rollout has been delayed due to no-fly zones for deployments during the upcoming US holidays.

Great! Thanks

**Comment by rg54** [comment] 2019-10-25 14:34
Hello. There is the same issue on Azure MariaDB when deploying with ARM template :

`                        {
                            "type": "Microsoft.DBforMariaDB/servers/databases",
                            "apiVersion": "2018-06-01",
                            "name": "xx-useraccount-db",
                            "properties": {
                                "charset": "utf8",
                                "collation": "utf8_general_ci"
                            }
                        }`

Error message "The provided database name is invalid. (Code : InvalidDatabaseName)"

@ajlam Will this fix apply to MariaDB too ?
Thanks.

**Comment by ajlam** [comment] 2019-10-25 22:27
@rg54 - yes, these changes will also apply to Azure DB for MariaDB 😄

**Comment by ajlam** [comment] 2019-12-11 18:18
@6heads, @shin-akuma, @rg54  - this has been fixed in our most recent deployment.

Please confirm that it works for you as well 😄 

![image](https://user-images.githubusercontent.com/11048726/70648225-77dffd80-1bff-11ea-96df-7d9f5c9ed755.png)

**Comment by shin-akuma** [comment] 2019-12-11 21:03
Awesome! Thank you Andrea! Have a great Xmas

**Closed** 2019-12-13 01:31 UTC
Labels: MySQL, Service Attention
