### ISSUE TITLE
az login --identity tries to connect to host 169.254.169.254 port 80 and fails because there is no host there.

### ISSUE THREAD

**Issue by v-sijeff** [Azure/azure-cli#14577] opened 2020-07-29 18:26 UTC
### **This is autogenerated. Please review and update as needed.**
I am trying to login to ` https://msazure.visualstudio.com/LSG-linux/` with a PAT.

## Describe the bug

v-sijeff@ovlvm102:~$  az login --identity
The command failed with an unexpected error. Here is the traceback:

HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConn             ectionError('<urllib3.connection.HTTPConnection object at 0x7f001af856d8>: Failed to establish a new connection: [Errno 113] No route to host',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/az/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/az/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f001af856d8>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-ver             sion=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f001af856d8>: Failed to establish a new connection: [Errno 113] No route to host',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 776, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 137, in login
    return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 345, in find_subscriptions_in_vm_with_msi
    msi_creds = MSIAuthenticationWrapper(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 600, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 685, in _retrieve_token_from_imds_with_retry
    result = requests.get(request_uri, params=payload, headers={'Metadata': 'true', 'User-Agent':self._user_agent})
  File "/opt/az/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-             version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f001af856d8>: Failed to establish a new connection: [Errno 113] No route to host',))

To open an issue, please run: 'az feedback'
v-sijeff@ovlvm102:~$

**Command Name**
`az login`

**Errors:**
Here is the traceback:
```
HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f001af856d8>: Failed to establish a new connection: [Errno 113] No route to host',))
Traceback (most recent call last):
python3.6/site-packages/urllib3/connection.py, ln 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
...
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f001af856d8>: Failed to establish a new connection: [Errno 113] No route to host',))
```
The problem, of course, is that for some reason, the az login command thinks there is a server at 169.254.169.254 and there isn't.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Linux-5.3.0-51-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.9.1

Extensions:
azure-devops 0.18.0

```
## Additional Context
I tried 2 different PATs, one for msazure.visualstudio.com and one for AzureCSI-SE and az login fails the same way for both of them.

I would love to know how to override the value of envar AZURE_DEVOPS_EXT_PAT from the command line.

**Comment by arrownj** [comment] 2020-07-30 01:16
Hi @v-sijeff , thanks for reporting, we will look at it.

**Comment by arrownj** [comment] 2020-10-26 05:17
Hi @v-sijeff , as I can't reproduce your problem in my environment, could you please help provide more information. What's the exact IP address of your login url in the VM ? Could you please try to check the `/etc/hosts` file or run `tracepath <host>` command to check why the url is direct to a wrong IP ? 
And I'm not sure why you need to override AZURE_DEVOPS_EXT_PAT ? It seems that in cli login process, we will not use the env variable ?

**Comment by arrownj** [comment] 2020-11-02 05:57
Hi @v-sijeff , I will close this issue first as it seems to be an environment issue. If you still meet this or have other problems, you can reopen or submit a new one. Thanks

**Closed by arrownj** 2020-11-02 05:57 UTC
Labels: Account, OKR3.2 Candidate, customer-reported, customer-response-expected

**Comment by Zeka13** [comment] 2021-08-10 11:36
same shit, good job Microsoft

**Comment by jiasli** [comment] 2021-08-11 03:09
@Zeka13, `az login --identity` is for [managed identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) login. According to [How to use managed identities for Azure resources on an Azure VM to acquire an access token](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token), `169.254.169.254` is a special IP address where the managed identity endpoint is hosted.

`azcopy` is another command line tool, different from Azure CLI `az`. If you have any question regarding `azcopy`, please feel free to create an issue at https://github.com/Azure/azure-storage-azcopy. Our developers will gladly assist you with it.
