### ISSUE TITLE
Not able to create Metric Alert using Azure CLI

### ISSUE THREAD

**Issue by satheeshpayoda** [Azure/azure-cli#16513] opened 2021-01-13 06:51 UTC
## Describe the bug
I'm trying to create CPU alert for VM using Azure CLI command but failing with weird error. Even i set region using --region explicitly but same error.

**Command Name**
`az monitor metrics alert create`

**Errors:**
```
BadRequestError: The following resources were not found under the region global: /subscriptions/<SUB_ID>/resourceGroups/<RG_NAME>/providers/Microsoft.Compute/virtualMachines/<VM Name>. Activity ID: xxxxxx.
```

## To Reproduce:
Steps to reproduce the behavior.

- `az monitor metrics alert create -n {} -g {} --scopes {} --condition {} --window-size {} --evaluation-frequency {} --description {}`

## Expected Behavior
CPU Alert should be created for VM but it is failing with above error. I think some issue with target region. 

## Environment Summary
```
Linux-4.4.0-148-generic-x86_64-with-debian-jessie-sid
Python 3.6.10
Installer: DEB

azure-cli 2.17.1

Extensions:
aks-preview 0.4.71
application-insights 0.1.13
storage-preview 0.7.0

```

**Comment by yonzhan** [comment] 2021-01-13 07:02
monitor

**Comment by 951p** [comment] 2021-01-26 16:42
We just had the same issue.
For info, running the following command used to work before the az upgrade to 2.18.0 :
az monitor metrics alert create -n <Name> -g <ResourceGroup> --window-size <Value> --evaluation-frequency <Value> --condition <SomeValidCondition> --description "AnAlert!" --region <SomeRegion> --scope "/subscriptions/<SubId>/resourceGroups/<ResourceGroup>/providers/microsoft.insights/components/<AppInsightComponentId>"

Error code: 
BadRequestError: The following resources were not found under the region global: /subscriptions/<SubId>/resourceGroups/<ResourceGroup>/providers/microsoft.insights/components/<AppInsightComponentId>

If I retry the command shortly after I will get the following error:
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<SubId>/resourceGroups/<ResourceGroup>/providers/Microsoft.Insights/metricAlerts/<AlertName>?api-version=2018-03-01 (Caused by ResponseError('too many 500 error responses',))

Version prior the upgrade:
az version
{
  "azure-cli": "2.15.1",
  "azure-cli-core": "2.15.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
  "application-insights": "0.1.11"
  }
}

Version after upgrade
az version
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "application-insights": "0.1.13"
  }
}

**Comment by mortenlerudjordet** [comment] 2021-01-27 11:42
Having the same issue.

```
❯ az version
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.72",
    "azure-devops": "0.18.0",
    "azure-firewall": "0.8.0",
    "db-up": "0.2.0"
  }
}
```

**Comment by TanishGuleria** [comment] 2021-02-02 09:13
Having same issue with azure cli 

script -:
`az monitor metrics alert create -n <alertname> --region <region> -g <rg> --scopes "/subscriptions/<sbid>/resourceGroups/<Rgname>/providers/Microsoft.Insights/components/<application insight name>"  --condition "count <metric name> alert >= 1"  --window-size 1m --evaluation-frequency 1m --action {action id}  --description "test alert" --severity 2` 

Error :-
`BadRequestError: The following resources were not found under the region global:`

**Comment by DannyArr** [comment] 2021-02-02 14:16
Same here. I get the same error when trying on an App Service, but works ok on, for example, Front Door.

**Comment by kairu-ms** [comment] 2021-02-03 02:50
It will be fixed in next CLI version, which will be released at 02/09/2021.

**Closed** 2021-02-03 05:42 UTC
Labels: Monitor
