### ISSUE TITLE
az login fails 

### ISSUE THREAD

**Issue by kishoresayee** [Azure/azure-cli#15986] opened 2020-11-19 20:25 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
local variable 'token_entry' referenced before assignment
Traceback (most recent call last):
lib\site-packages\knack\cli.py, ln 216, in invoke
    cmd_result = self.invocation.execute(args)
cli\core\commands\__init__.py, ln 654, in execute
    raise ex
cli\core\commands\__init__.py, ln 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli\core\commands\__init__.py, ln 710, in _run_job
    six.reraise(*sys.exc_info())
env\lib\site-packages\six.py, ln 703, in reraise
    raise value
...
azure\cli\core\__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cli\command_modules\profile\custom.py, ln 158, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
azure\cli\core\_profile.py, ln 195, in find_subscriptions_on_login
    tenant, self._ad_resource_uri, authority_url)
azure\cli\core\_profile.py, ln 875, in find_through_authorization_code_flow
    self.user_id = token_entry[_TOKEN_ENTRY_USER_ID]
UnboundLocalError: local variable 'token_entry' referenced before assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.4
Installer: PIP

azure-cli 2.15.0

```

**Comment by evelyn-ys** [comment] 2020-11-20 01:57
This is a known issue #15961  and we are working on a fix. To get over it, please use a valid user account.

**Comment by jiasli** [comment] 2020-11-20 03:19
Duplicate of #15961

**Closed** 2020-12-31 02:32 UTC
Labels: Account, OKR3.2 Candidate, feature-request
