### ISSUE TITLE
AZL

### ISSUE THREAD

**Issue by tallywizu** [Azure/azure-cli#22637] opened 2022-05-26 15:33 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az portal dashboard update  

https://docs.microsoft.com/en-us/cli/azure/portal/dashboard?view=azure-cli-latest

**Describe the bug**
The AZ portal dashboard update command only accepts files with specific encoding which is not mentioned in the Microsoft documentation and throwing up errors when running other encoding types , the encoding type that is accepted is UTF-8 

**To Reproduce**

I converted the file the customer sent to UTF-8 and ran the command but I didn't get any error
 
![image](https://user-images.githubusercontent.com/80165865/170525770-b3a33dc3-78f5-4514-9b55-3ca8e2f2ecd8.png)

 
I converted the file the customer sent to ucs-2 le bom and I was getting the  below error
 
 
![image](https://user-images.githubusercontent.com/80165865/170526190-68dc8059-6c41-4de3-aa11-82e77ce28497.png)

 
I took a json file from my lab and converted to ucs-2 le bom but I got the below  
 
![Uploading image.png…]()

 
**Expected behavior**

The AZ dashboard update command is suppose to accept any file format and if there any specifics, it should be stated in the Microsoft documentation

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment] 2022-05-26 23:38
portal

**Comment by temidayo0301** [comment] 2022-07-25 14:29
Hello @jsntcy

Please find attached as requested. Thank you.
[test.txt](https://github.com/Azure/azure-cli/files/9182030/test.txt)

**Comment by jsntcy** [comment] 2022-07-26 04:18
@tallywizu, @temidayo0301, I used the file you provided above, but cannot reproduce the issue (I can run the command `az portal dashboard update` with your json file correctly.), could you please provide more details?

![image](https://user-images.githubusercontent.com/16348853/180921574-25ce8b40-0e8d-4b9f-852a-5a431c735b01.png)

**Comment by RomanDvorsky** [comment] 2022-07-29 04:39
Hi, what operation system machine do you use to reproduce the error?

**Comment by jsntcy** [comment] 2022-07-29 05:14
I use Windows and ran the command with the file @temidayo0301 provided above. What do you mean for "try file with windows encoding to get a failure"?

**Comment by RomanDvorsky** [comment] 2022-07-29 05:39
well the cli command works only with utf-8 encoding with CR line end other encoding like with cr lf line end did produce an error.

**Comment by jsntcy** [comment] 2022-07-29 09:06
@RomanDvorsky, could you please provide a file with other encoding which produces an error to help us troubleshoot?

**Comment by RomanDvorsky** [comment] 2022-07-29 09:14
Hi, can you review support case 2203290050000472 - there is a lot of details there.

Simply run: “Az portal dashboard show” command to any dashboard and try to upload the result back.

I have found 'test.json' file in my communication history but I would preferer to not provide it public way - how can I provide this file in private manner?

**Comment by jsntcy** [comment] 2022-07-29 09:38
I didn't receive any information about support case 2203290050000472, where can I find it?
You can send file to AzPyCLI@microsoft.com.

**Comment by RomanDvorsky** [comment] 2022-07-29 09:56
Hi, 
now I'm bit confused I did create a premium support ticket on Microsoft - this ticket is still opened and seems really difficult to solve - now there is another place where should I solve the same?

I will forward this link to the support case and hopefully someone will solve and explain this.
Did you try to export import any dashboard your self?

File was posted to given email.

Regards,
R.

**Comment by jsntcy** [comment] 2022-07-29 10:34
We are developer team and only support engineer team can access the system for the support ticket. They need forward information about the support ticket to us, so that we can know there is a support ticket. In this case, support engineer team didn't tell us there is a such ticket.

Anyway, customers can report issue here (GitHub issue) which we can see it directly.

With the file you provided, we can reproduce the issue now. We'll troubleshoot the issue and update you the status.

**Comment by jsntcy** [comment] 2022-08-03 10:08
@RomanDvorsky, the issue has been fixed in latest portal extension (0.1.3), please [upgrade to the latest version](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview#how-to-update-extensions) to check if the issue is resolved or not.

**Closed** 2022-08-15 14:05 UTC
Labels: customer-reported, needs-author-feedback, no-recent-activity, Portal, Auto-Assign
