### ISSUE TITLE
'az sql server create' mishandling password string

### ISSUE THREAD

**Issue by hKaspy** [Azure/azure-cli#10370] opened 2019-08-29 12:36 UTC
## Describe the bug

`az sql server create --admin-password` argument tries to interpret the password and fails on less-than sign.

I've tried single quotes, double quotes, putting in equal sign, variable... No Luck so far.

**Errors:**
```
PS C:\> az sql server create --admin-user "admin" --admin-password a<b
The system cannot find the file specified.
PS C:\> az sql server create --admin-user "admin" --admin-password 'a<b'
The system cannot find the file specified.
PS C:\> az sql server create --admin-user "admin" --admin-password "a<b"
The system cannot find the file specified.
PS C:\> az sql server create --admin-user "admin" --admin-password='a<b'
The system cannot find the file specified.
PS C:\> az sql server create --admin-user "admin" --admin-password="a<b"
The system cannot find the file specified.
PS C:\> $sqlPassword="a<b"
PS C:\> az sql server create --admin-user "admin" --admin-password $sqlPassword
The system cannot find the file specified.
PS C:\> az sql server create --admin-user "admin" --admin-password=$sqlPassword
The system cannot find the file specified.
```

## To Reproduce:

`az sql server create --admin-user "admin" --admin-password "a<b"`

## Expected Behavior

Fails with `az sql server create: error: the following arguments are required: --resource-group/-g, --name/-n`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.71 *
```
## Additional Context

Right-sided parenthesis also breaks this in different way:

```
PS C:\> az sql server create --admin-user "admin" --admin-password="a)b"
b was unexpected at this time.
C:\>  "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\\..\python.exe" -IBm azure.cli sql server create --admin-user admin --admin-password=a)b
```

**Comment by jaredmoo** [comment] 2019-09-05 15:33
Thank you for reporting this issue. It looks like this issue affects more than just SQL commands.

```
> az group create -n "a<b" -g "westus"
The system cannot find the file specified.
```

I'll include the CLI core team to help investigate deeper.

**Comment by Juliehzl** [comment] 2019-09-06 03:09
@jaredmoo  are you want to run `az group create -n "a<b" -l "westus"` not `-g "westus"`? If yes, `az group create` will tell you ` Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'`. `az group` have validation for parameters. So I think this may be just related to SQL not core.

**Comment by jaredmoo** [comment] 2019-09-06 03:49
In that case it might just be PowerShell interpreting as I/O redirection.

**Comment by Juliehzl** [comment] 2019-09-23 05:33
@hKaspy When I want to reproduce your issue, it looks "<" works but ")" cannot be parsed correctly in PS. Can you verify it? 
I really agree with what @jaredmoo said, it is more related to PS and there is a little we can do. But I will add these specific letters scenario in CLI document [here](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md) to make users know these cases and use cli more effectively.

**Comment by hKaspy** [comment] 2019-09-23 07:13
@Juliehzl Tested again with following config, issue still completely valid. However it does not happen in cmd.exe.
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe
azure-cli 2.0.71 *
```

I disagree with you and @jaredmoo, as this hints at bad string handling inside your script, since this happens no mather what string quotation technique I use. Per [powershell documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-5.1) (5.1 in my case):

> When you enclose a string in single-quotation marks (a single-quoted string), the string is passed to the command exactly as you type it. No substitution is performed.

Moreover, `mkdir "a)b"` is completely valid and creates a folder named `a)b` and `mkdir "a>b"` fails with `mkdir : Illegal characters in path.`.

This wouldn't be such a problem for me if it was not a password argument failing. It should accept any printable character. Invalidating `<`, `)` and possibly other characters weakens password security. 

The issue is also in that Web GUI version accepts those characters, so (as happened to me) someone could create the DB password in GUI and then I am unable to replicate this in automated CI/CD script.

**Comment by hKaspy** [comment] 2019-09-23 07:37
Tested now with Azure Key Vault, so we can rule out the SQL:

```
az keyvault secret set --vault-name test-kv --name "test" --value "a)b"
b was unexpected at this time.
```

**Comment by Juliehzl** [comment] 2019-09-27 07:25
@hKaspy For me, `)` still works now with azure-cli 2.0.74 as follows:
![image](https://user-images.githubusercontent.com/49508232/65750386-d803ef00-e13a-11e9-8dfe-0a112741881c.png)

Can you try again? If you still have such problem, please let me know.

**Comment by hKaspy** [comment] 2019-09-27 12:01
@Juliehzl Still an issue for me, `<` works and `)` fails for both (keyvault, sql) commands.

```
PS C:\> az --version
azure-cli                         2.0.74

command-modules-nspkg              2.0.3
core                              2.0.74
nspkg                              3.0.4
telemetry                          1.0.3

...

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

**Comment by yonzhan** [comment] 2019-11-02 02:42
@Juliehzl  please create a PS ticket and put it here, then we can close this issue.

**Comment by ArgTang** [comment] 2019-11-26 15:38
Same issue for `az postgres server create` `<` and `)` in pasword arg crashed prosess 
powershell 5, az cli 2.0.76

**Comment by Juliehzl** [comment] 2019-12-01 13:33
> Same issue for `az postgres server create` `<` and `)` in pasword arg crashed prosess
> powershell 5, az cli 2.0.76

Hi @ArgTang, it is a powershell issue. Could you use cmd to unblock yourself? Out of curiosity, `)` doesn't work for you, right? Could you share more info about `)`  scenario with me? It works for me as follows again.
![image](https://user-images.githubusercontent.com/49508232/69914708-04f9b880-1482-11ea-8268-e9b6e1a4b546.png)

**Comment by jiasli** [comment] 2019-12-04 07:18
As @Juliehzl stated, this is a Windows PowerShell issue. We have updated CLI doc for explanation and workaround: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#argument-parsing-issue-in-powershell

**Comment by jeroenterheerdt** [comment] 2019-12-06 01:58
@ArgTang please let us know if you need more help - otherwise we will proceed to close this issue.

**Comment by ArgTang** [comment] 2019-12-06 07:49
@jeroenterheerdt no, i think we have a workaround. thanks

**Comment by jeroenterheerdt** [comment] 2019-12-06 16:53
@jiasli please go ahead and close this.

**Closed** 2019-12-07 01:45 UTC
Labels: SQL, Service Attention
