### ISSUE TITLE
"az cosmosdb create" fails with authorization error while Portal works

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#6894] opened 2018-07-26 16:37 UTC
**Describe the bug**
`az cosmosdb create --resource-group ... --name ...` fails with

> The client '...@microsoft.com' with object id '...' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/.../resourcegroups/...'.

**Expected behavior**
It works on the Azure Portal with the same user, so it should work with the cli as well. I did `az login` just to be sure, but no difference.

**Environment summary**
Version: 2.0.41
Install Method: MSI
OS version: Windows 10
Shell Type: cmd.exe

**Comment by shurd** [comment] 2019-06-05 23:23
Hi @letmaik if you are still experiencing this problem, could you open a support ticket via the Azure portal with details about your account, subscription and RBAC rule assigned to the user? The provider giving you the error is the Resource team, so there is likely a mismatch between the active subscription in the CLI and where your resource is located.

**Comment by shurd** [comment] 2019-06-12 06:32
This issue is related to RBAC permissions and likely was caused by insufficient permissions or a mismatch between the active account on the CLI and the subscription the resource group resides in. I am going to close this issue for now. If you are still facing this problem, you can re-open the issue and provide more details.

**Closed by shurd** 2019-06-12 06:32 UTC
Labels: Cosmos, Service Attention
