### ISSUE TITLE
I can't connect to SQL Server on Azure

### ISSUE THREAD

**Issue by LaurentiuAugustin** [Azure/azure-cli#22933] opened 2022-06-20 07:59 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0
```

**Comment by yonzhan** [comment] 2022-06-20 08:42
@jiasli for awareness

**Comment by yonzhan** [comment] 2022-06-20 08:43
Duplicate of https://github.com/Azure/azure-cli/issues/20231

**Closed by yonzhan** 2022-06-20 08:43 UTC
Labels: Account, customer-reported, Auto-Assign
