### ISSUE TITLE
"Please run 'az login' to setup account" while I already logged in

### ISSUE THREAD

**Issue by sanghoonkim0918** [Azure/azure-cli#12750] opened 2020-03-26 01:43 UTC
## Describe the bug

**Command Name**
`az vm create`

**Errors:**
```
Please run 'az login' to setup account.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create --subscription {my_own_subscription} --location eastus2 --resource-group {my_own_resource_group} --name myVM --image UbuntuLTS --generate-ssh-keys --output none`

## Expected Behavior
Since I already logged in to Azure, the VM should have been made successfully. 
## Environment Summary
```
Linux-5.0.0-1032-azure-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9

azure-cli 2.2.0

```
## Additional Context
I already logged in using the command 'az login'. What I am doing is I made a python script that uses Azure CLI commands, instead of Azure Python SDK, to create several VMs concurrently using a thread pool. 

Most VMs (ex: 30 out of 31) are made successfully, but some VMs (ex: 1 out of 31) give me the error above "Please run 'az login' to setup account".

**Comment by yonzhan** [comment] 2020-03-26 01:49
@qwordy please take a look.

**Comment by pascencio** [comment] 2020-03-26 16:30
Hi, I have the same issue. The weird thing happens when sign out of the azure portal, then I execute `az login`, write my credentials and proceed with the login and it's fail again.

This happens even if I already logged or not.

![azure_error](https://user-images.githubusercontent.com/9783678/77670604-346a8e80-6f65-11ea-8b1a-90d3e2c1ee0b.png)

This is the output from my terminal:
```shell
Authentication Error: "['server_error']". Description: "['AADSTS40008: There was an unexpected error from the external identity provider.\r\nTrace ID: ab0d9d60-6a9c-41a1-9c73-cf52e79a3200\r\nCorrelation ID: 2e5f5d5a-52a1-45f8-9ca0-5b93cf09819c\r\nTimestamp: 2020-03-26 16:24:32Z']" 
Login failed
```

Thanks in the advance!

**Comment by qwordy** [comment] 2020-03-30 06:04
It's a strange problem. 
1. What if you create VMs sequentially?
2. What if you create other number of VMs?
3. Can you share the Python script?

**Comment by yonzhan** [comment] 2020-04-11 11:47
@sanghoonkim0918 any update/feedback for above questions ?

**Comment by qwordy** [comment] 2020-05-27 02:41
@sanghoonkim0918

**Comment by qwordy** [comment] 2020-06-03 06:30
It's a tricky problem and I have not reproduced it. Close the issue for now. Open a new issue if there is any problem. Or you can still comment here.

**Closed by qwordy** 2020-06-03 06:30 UTC
Labels: Compute

**Comment by nehalilani** [comment] 2020-10-27 13:15
Hi, I'm facing the same issue while creating resources in the Azure portal using a powershell script

**Comment by tpanum** [comment] 2021-10-13 07:58
I guess it would be time for a reopening...

**Comment by ioanvapi** [comment] 2021-11-06 16:06
The same issue on Ubuntu 20 on WSL2. I have installed az cli then successful login with "az login --allow-no-subscriptions". I tried 'az ad app list' and got the message: "Please run 'az login' to setup account." 

![image](https://user-images.githubusercontent.com/7744363/140616077-8f8082cd-0299-40e9-a3b8-b91cc2a67707.png)

Ran again with --debug and got:

❯ az ad app list --debug                                                                                                                                 ⏎
cli.knack.cli: Command arguments: ['ad', 'app', 'list', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f81b2202a60>, <function OutputProducer.on_global_arguments at 0x7f81b2133598>, <function CLIQuery.on_global_arguments at 0x7f81b214d6a8>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'ad': ['azure.cli.command_modules.role']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: role                      0.003        17        61
cli.azure.cli.core: Total (1)                 0.003        17        61
cli.azure.cli.core: Loaded 17 groups, 61 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : ad app list
cli.azure.cli.core: Command table: ad app list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f81b1bcfea0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/vapi/.azure/commands/2021-11-06.18-00-33.ad_app_list.26332.log'.
az_command_data_logger: command args: ad app list --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f81b1bf7e18>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f81b1b5f598>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f81b1b5f620>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f81b1b5f730>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f81b2133620>, <function CLIQuery.handle_query_parameter at 0x7f81b214d730>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f81b1b5f510>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f81b1b5f6a8>]
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 77, in get_graph_client_applications
    return _graph_client_factory(cli_ctx).applications
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/_client_factory.py", line 25, in _graph_client_factory
    resource=cli_ctx.cloud.endpoints.active_directory_graph_resource_id)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 315, in get_login_credentials
    account = self.get_subscription(subscription_id)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 542, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

cli.azure.cli.core.azclierror: Please run 'az login' to setup account.
az_command_data_logger: Please run 'az login' to setup account.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f81b1bd3158>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.217 seconds (init: 0.086, invoke: 0.131)

**Comment by jiasli** [comment] 2021-11-08 02:37
The size of your `azureProfile.json` is suspicious. Its size should be around 300 bytes:

```
$ ls -l ~/.azure
total 60
-rw-r--r-- 1 user1 user1     5 Nov  8 10:31 az.json
-rw-r--r-- 1 user1 user1     5 Nov  8 10:31 az.sess
-rw-r--r-- 1 user1 user1   361 Nov  8 10:31 azureProfile.json
...

$ cat ~/.azure/azureProfile.json
﻿{"subscriptions": [{"id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a", "name": "N/A(tenant level account)", "state": "Enabled", "user": {"name": "user1@azuresdkteam.onmicrosoft.com", "type": "user"}, "isDefault": true, "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a", "environmentName": "AzureCloud"}], "installationId": "f9029028-403b-11ec-825e-00155d4a130a"}
```

Could you use `cat` to echo its content and run `az account list`?

**Comment by ioanvapi** [comment] 2021-11-08 07:07
Right now, the size is different because I have created a subscription then did login again. All these updated the file with a new content and it's about 400 bytes now. But still I remember (from my memory) the previous content was something like {"id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a"}. 

My curent configuration cannot help that much. I had to delete the subscription, the .azure local folder and az login again.
Just let me know.

**Comment by jiasli** [comment] 2021-11-08 07:16
`az login --allow-no-subscriptions` only works if you have access to an AAD tenant, as it will create a tenant account like:

```
[
  {
    "cloudName": "AzureCloud",
    "id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "isDefault": true,
    "name": "N/A(tenant level account)",
    "state": "Enabled",
    "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "user": {
      "name": "user1@azuresdkteam.onmicrosoft.com",
      "type": "user"
    }
  }
]
```

Please make sure the account you used to log in has tenant access.

**Comment by ioanvapi** [comment] 2021-11-08 08:20
I have logged in with the same user that I have used to create the Azure account. Right now, the 'az account list' echos:
`
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "cd44df35-cde2-4917-8cab-03139fa4bc85",
    "id": "2c0d2676-9a7b-4d8c-874f-89b9d69993e8",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Azure subscription 1",
    "state": "Enabled",
    "tenantId": "cd44df35-cde2-4917-8cab-03139fa4bc85",
    "user": {
      "name": "je@gmail.com",
      "type": "user"
    }
  }
]
`

**Comment by jiasli** [comment] 2021-11-08 08:29
This should work now. Are you still seeing the error?

**Comment by k-guy-dev** [comment] 2022-02-13 05:23
Hi, I'm facing the same error! I am using a subscription of "Azure for Students". I tried doing the login with and without 
--allow-no-subscriptions but nothing seems to work.

**Comment by MurugeswariMuthurajan** [comment] 2022-06-14 02:26
Hi @jiasli ,

I am getting the same error, while training the ML Model

![image](https://user-images.githubusercontent.com/107349920/173479849-6c288027-ba61-4d7b-81e8-93fccb6ef3e3.png)

I have authenticated my service principal also

![image](https://user-images.githubusercontent.com/107349920/173480292-f58fdb3f-597d-438f-a777-d6aa3c121e50.png)

Could you please help me
