### ISSUE TITLE
Unable to login through "az login"

### ISSUE THREAD

**Issue by RachnaKP** [Azure/azure-cli#26190] opened 2023-04-19 06:20 UTC
Getting below error while using az login command :

The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /****/***/***** (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object) - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by yonzhan** [comment] 2023-04-19 06:21
Thank you for opening this issue, we will look into it.

**Comment by RachnaKP** [comment] 2023-04-19 06:58
Please update me on this

**Comment by bebound** [comment] 2023-04-19 09:34
Duplicate of #21514

**Closed by bebound** 2023-04-19 09:34 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
