### ISSUE TITLE
Why are we using 32bit python?

### ISSUE THREAD

**Issue by uBadRequest** [Azure/azure-cli#22103] opened 2022-04-19 02:10 UTC
https://github.com/Azure/azure-cli/blob/822a2141215acea607ca9446dc113ebed792fc37/build_scripts/windows/scripts/build.cmd#L19

Why we using 32bit python?! Can we please give the option to use 64 bit? https://www.python.org/ftp/python/3.10.4/python-3.10.4-embed-amd64.zip

I had the 64 bit version of OpenSSH installed and wasted a good amount of time wondering why the heck it wouldn't find it, only to realize that it would only look in C:\Windows\SysWOW64\OpenSSH.

**Comment by yonzhan** [comment] 2022-04-19 02:35
@jiasli for awareness

**Comment by jiasli** [comment] 2022-04-19 02:57
Duplicate of #18766

**Closed by jiasli** 2022-04-19 02:57 UTC
Labels: Packaging, customer-reported, feature-request
