### ISSUE TITLE
az storage blob upload fials on Windows Server 2019

### ISSUE THREAD

**Issue by a3nick** [Azure/azure-cli#10188] opened 2019-08-08 09:18 UTC
## Describe the bug

**Command Name**
`az storage blob upload` using AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variable for authentication

**Errors:**
```
('Connection aborted.', timeout())
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 320, in _send_until_done
pip-install-rtk110ve\pyOpenSSL\OpenSSL\SSL.py, ln 1737, in send
pip-install-rtk110ve\pyOpenSSL\OpenSSL\SSL.py, ln 1624, in _raise_ssl_error
OpenSSL.SSL.WantWriteError

...

storage\v2018_11_09\common\storageclient.py, ln 430, in _perform_request
storage\v2018_11_09\common\storageclient.py, ln 361, in _perform_request
azure.common.AzureException: ('Connection aborted.', timeout())
```

## To Reproduce:
Any call to 

- `az storage blob upload -c {} -f {} -n {}`

fails in Windows Server 2016 and 2019. It works well on a Windows 10 machine.

## Expected Behavior
The operation must complete succesfully

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.70

```

**Comment by Juliehzl** [comment] 2019-08-09 16:10
It looks an timeout connection error, which may caused by poor network or something else. Can you try again with good network connection? If there is still such error, can you show me the message for ```az storage blob upload -f cc -n ss -a ccc --debug```?

**Comment by Juliehzl** [comment] 2019-08-25 16:14
@a3nick what about your problem now?

**Comment by a3nick** [comment] 2019-09-04 13:42
> 
> 
> It looks an timeout connection error, which may caused by poor network or something else. Can you try again with good network connection? If there is still such error, can you show me the message for `az storage blob upload -f cc -n ss -a ccc --debug`?

I'm sorry for the late response but i was out-of-office. I don't think that the problem is due by a poor connection as i used the same connection with my Windows 10 machine which works well, the only difference is that the Windows Server is running as a virtual machine on an ESXi instance.
Tomorrow i'll try to upload the files with the command you suggest and i'll give you a feedback with the details.

**Comment by a3nick** [comment] 2019-09-05 08:55
Dear @Juliehzl, this is the output of the command with the `--debug` switch (i replaced the sensitive info with `file-name`, `storage-name` and `container-name`).

```
Command arguments: ['storage', 'blob', 'upload', '-c', 'container-name', '-f', '.\\file-name', '-n', 'file-name', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0397F978>, <function OutputProducer.on_global_arguments at 0x03A4C660>, <function CLIQuery.on_global_arguments at 0x03A69738>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.012 seconds.
Loaded module 'acs' in 0.025 seconds.
Loaded module 'advisor' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.017 seconds.
Loaded module 'appconfig' in 0.010 seconds.
Loaded module 'appservice' in 0.022 seconds.
Loaded module 'backup' in 0.009 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.026 seconds.
Loaded module 'batchai' in 0.009 seconds.
Loaded module 'billing' in 0.008 seconds.
Loaded module 'botservice' in 0.010 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.009 seconds.
Loaded module 'cloud' in 0.007 seconds.
Loaded module 'cognitiveservices' in 0.007 seconds.
Loaded module 'configure' in 0.005 seconds.
Loaded module 'consumption' in 0.009 seconds.
Loaded module 'container' in 0.009 seconds.
Loaded module 'cosmosdb' in 0.012 seconds.
Loaded module 'deploymentmanager' in 0.009 seconds.
Loaded module 'dla' in 0.014 seconds.
Loaded module 'dls' in 0.010 seconds.
Loaded module 'dms' in 0.007 seconds.
Loaded module 'eventgrid' in 0.010 seconds.
Loaded module 'eventhubs' in 0.010 seconds.
Loaded module 'extension' in 0.004 seconds.
Loaded module 'feedback' in 0.003 seconds.
Loaded module 'find' in 0.007 seconds.
Loaded module 'hdinsight' in 0.008 seconds.
Loaded module 'interactive' in 0.002 seconds.
Loaded module 'iot' in 0.017 seconds.
Loaded module 'iotcentral' in 0.006 seconds.
Loaded module 'keyvault' in 0.015 seconds.
Loaded module 'kusto' in 0.010 seconds.
Loaded module 'lab' in 0.011 seconds.
Loaded module 'managedservices' in 0.006 seconds.
Loaded module 'maps' in 0.005 seconds.
Loaded module 'monitor' in 0.015 seconds.
Loaded module 'natgateway' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.014 seconds.
Loaded module 'network' in 0.060 seconds.
Loaded module 'policyinsights' in 0.008 seconds.
Loaded module 'privatedns' in 0.012 seconds.
Loaded module 'profile' in 0.007 seconds.
Loaded module 'rdbms' in 0.015 seconds.
Loaded module 'redis' in 0.008 seconds.
Loaded module 'relay' in 0.012 seconds.
Loaded module 'reservations' in 0.007 seconds.
Loaded module 'resource' in 0.019 seconds.
Loaded module 'role' in 0.012 seconds.
Loaded module 'search' in 0.006 seconds.
Loaded module 'security' in 0.010 seconds.
Loaded module 'servicebus' in 0.014 seconds.
Loaded module 'servicefabric' in 0.007 seconds.
Loaded module 'signalr' in 0.008 seconds.
Loaded module 'sql' in 0.019 seconds.
Loaded module 'sqlvm' in 0.010 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.063 seconds.
Loaded module 'vm' in 0.035 seconds.
Loaded all modules in 0.731 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\n.luraghi\.azure\cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03B02CD8>]
az_command_data_logger : command args: storage blob upload -c {} -f {} -n {} --debug
metadata file logging enabled - writing logs to 'C:\Users\n.luraghi\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03BC91E0>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03BC9198>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03BC9858>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04845078>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03A4C6A8>, <function CLIQuery.handle_query_parameter at 0x03A69780>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03BC9810>, <function handler at 0x048F7F60>]
Getting data service client service_type=BlockBlobService
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:44:52 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQSUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQSUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:44:52 GMT', 'Authorization': 'REDACTED'}.
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:44:52 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:44:52 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (1): storage-name.blob.core.windows.net:443
urllib3.connectionpool : Starting new HTTPS connection (2): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=0, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Retry policy is allowing a retry: Retry count=1, Interval=12.33655637181906.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=0, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Retry policy is allowing a retry: Retry count=1, Interval=15.42145094201749.
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:45:26 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:45:26 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (3): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:45:29 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQSUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQSUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:45:29 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (4): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=1, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Retry policy is allowing a retry: Retry count=2, Interval=16.961046732936428.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=1, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Retry policy is allowing a retry: Retry count=2, Interval=19.923627068594637.
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:46:03 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:46:03 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (5): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:46:09 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQSUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQSUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:46:09 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (6): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=2, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Retry policy is allowing a retry: Retry count=3, Interval=22.29062178379366.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=2, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Retry policy is allowing a retry: Retry count=3, Interval=23.468251317473317.
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:46:46 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:46:46 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (7): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:46:53 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQSUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQSUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:46:53 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (8): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=3, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d9b3f4c-cfb9-11e9-870f-000c2989a70e Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:47:06 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRGd6T0RnMk1EZyUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRGd6T0RnMk1EZyUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:47:06 GMT', 'Authorization': 'REDACTED'}.
az_command_data_logger : exit code: 1
urllib3.connectionpool : Starting new HTTPS connection (9): storage-name.blob.core.windows.net:443
Suppress exception There are no active accounts.
Suppress exception Please run 'az login' to setup account.
telemetry.save : Save telemetry record of length 2304 in cache
telemetry.check : Negative: The C:\Users\n.luraghi\.azure\telemetry.txt was modified at 2019-09-05 10:42:01.195960, which in less than 600.000000 s
command ran in 136.848 seconds.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=3, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=6d98dc28-cfb9-11e9-9bbd-000c2989a70e Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=0, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Retry policy is allowing a retry: Retry count=1, Interval=17.93968053092481.
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:47:45 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRGd6T0RnMk1EZyUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRGd6T0RnMk1EZyUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:47:45 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (10): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=1, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Retry policy is allowing a retry: Retry count=2, Interval=17.756374180118975.
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:48:23 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRGd6T0RnMk1EZyUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRGd6T0RnMk1EZyUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:48:23 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (11): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=2, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Retry policy is allowing a retry: Retry count=3, Interval=21.37259989187974.
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT


4194304








x-ms-client-request-id:6bf861d2-cfb9-11e9-9fad-000c2989a70e
x-ms-date:Thu, 05 Sep 2019 08:49:05 GMT
x-ms-version:2018-11-09
/storage-name/container-name/file-name
blockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRGd6T0RnMk1EZyUzRA==
comp:block
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Outgoing request: Method=PUT, Path=/container-name/file-name, Query={'comp': 'block', 'blockid': 'TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRGd6T0RnMk1EZyUzRA==', 'timeout': None}, Headers={'x-ms-lease-id': None, 'Content-Length': '4194304', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70 AZURECLI/2.0.70', 'x-ms-client-request-id': '6bf861d2-cfb9-11e9-9fad-000c2989a70e', 'x-ms-date': 'Thu, 05 Sep 2019 08:49:05 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (12): storage-name.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Operation failed: checking if the operation should be retried. Current retry count=3, , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=bd79928c-cfb9-11e9-a6d2-000c2989a70e Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=('Connection aborted.', timeout()).
```

**Comment by Juliehzl** [comment] 2019-09-11 05:03
@a3nick Thanks for your feedback and sorry for my late response. I have tried to reproduce your issue but  it works for me in Windows 2019 Server. For the azure.common.AzureException, which is from python SDK, not cli command, @zezha-msft do you have any idea for such error?

**Comment by a3nick** [comment] 2019-09-11 10:00
Dear @Juliehzl, as you suggested i checked if the problem was related to a network connection issue and finally i found a solution.
As i wrote, the server runs on a esxi instance.
Changing the network adapter type from `E1000` to `VMXNET 3` solved the connection issue and now everything works well

**Comment by a3nick** [comment] 2019-09-11 10:29
@Juliehzl, i need more time as i had the same problem randomly, even with the network adapter type change, uploading about 20 files.
The problem don't seems related to the file size.

**Comment by Juliehzl** [comment] 2019-09-12 01:47
@zezha-msft Thanks a lot for you looking at it!! @a3nick Sound good that it works now. I will close it now and you can reopen it or open a new one if you still have the issue in the future.

**Closed by Juliehzl** 2019-09-12 01:47 UTC
Labels: Storage
