### ISSUE TITLE
Console colors do not always revert back to default

### ISSUE THREAD

**Issue by jcleavel** [Azure/azure-cli#6080] opened 2018-04-10 20:31 UTC
The `az keyvault certificate show` changes the foreground and background console text colors when the requested certificate is not found, but does not revert the colors when the command is complete.
The color change remains in place until `$Host.UI.RawUI.ForegroundColor/$Host.UI.RawUI.BackgroundColor` is manually reset, or until a new session/host process is created.

---

### Environment summary

Install Method:
MSI

CLI version:
```
azure-cli (2.0.30)

acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.1.0)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.20)
core (2.0.30)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.20)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.20)
monitor (0.1.4)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.21)
rdbms (0.2.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.30)
vm (2.0.29)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\USER_NAME\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```
OS version:
Windows 10 v1709, Build 16299.309

Shell Type:
```
powershell.exe


Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  251     
```

**Comment by tjprescott** [comment] 2018-04-11 16:24
I have seen something like this happen inconsistently in CMD as well.

**Comment by jurgyy** [comment] 2019-09-26 12:35
Any updates? This issue is from a year ago and is currently still a problem in the latest version of az cli in combination with Powershell

**Comment by yonzhan** [comment] 2019-09-28 03:56
@jiasli please take a look and comment.

**Comment by yonzhan** [comment] 2019-10-13 00:40
This is a PowerShell issue. Issue created: https://github.com/PowerShell/PowerShell/issues/10729

**Comment by jiasli** [comment] 2019-10-15 08:44
This also happens in cmd. Looks like a colorama issue https://github.com/tartley/colorama/issues/200. Root cause provided by https://github.com/tartley/colorama/issues/200#issuecomment-476104215.

**Comment by abarger-bss** [comment] 2019-11-24 15:56
Can this issue be left open until the colorama issue is resolved, or until the az cli provides a mitigation? My team encounters this issue almost daily, and it makes the product seem unprofessional. Even if the root cause belongs to another product, the az cli owns some responsibility by selecting the dependency. I would accept an option to disable colors altogether. As it stands I am considering wrapping my PowerShell functions which use the az cli try/finally blocks to ensure the terminal colors revert to their original values.

**Comment by jiasli** [comment] 2019-12-02 02:41
Hi @abarger-bss, sure we can reopen this issue. I have created an issue in Knack to allow disabling color. I will work on this to disable colored output.

**Comment by jiasli** [comment] 2019-12-03 10:38
Hi @abarger-bss, actually even pip is affected by this issue https://github.com/pypa/pip/issues/6354. Given the condition that there is no better python lib for coloring, I have created PR https://github.com/microsoft/knack/pull/171 to allow disabling color.

**Comment by mgeorgebrown89** [comment] 2020-03-04 16:29
Just adding that for me, this happens regardless of the command, but any time there is a failure or a warning, all the output from then on turns either red or yellow, including the prompt.

**Comment by jiasli** [comment] 2020-03-17 09:55
This issue can be solved after PR https://github.com/Azure/azure-cli/pull/12604 is merged. We are planing to include the change in this release.

**Closed** 2020-03-17 09:55 UTC
Labels: Core, Infrastructure, Needs Triage, Output

**Comment by jiasli** [comment] 2021-01-20 02:58
This issue has been fixed by https://github.com/microsoft/knack/pull/209 in Azure CLI 2.18.0. Azure CLI can now disable color automatically if `stdout` is not a TTY. Please update to the latest version and let us know if the issue is solved. Thank you.
