### ISSUE TITLE
az bot create errors

### ISSUE THREAD

**Issue by bandmask** [Azure/azure-cli#9363] opened 2019-05-10 10:00 UTC
Azure CLI version: 2.0.64

When using az bot create --version v4 I'm getting errors when providing --insights-location 'North Euroupe':
'--insights-location' is not recognized as an internal or external command, operable program or batch file.
Seeing the Warning for v4 and insights location I tried to remove that command and verify that the insights location is derived from the provided --location ('northeurope').
This resulted in an error:
'--verbose' is not recognized as an internal or external command, operable program or batch file.

My command looks like the following, (with and without --insights-location):
az bot create --kind webapp --name &lt;BotName&gt; --location &lt;Location&gt; --version v4 --resource-group &lt;ResourceGroup&gt; --appid "&lt;AppId&gt;" --password "&lt;AppPassword&gt;" --insights-location "&lt;LocationLongName&gt;" --verbose

Can you provide me with some info about what I am doing wrong and why it does not work anymore?
Why I say anymore is because I've used the exact same command earlier without problems. Maybe with a previous version of Azure CLI, I don't know, all I know is that it currently is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55111b1f-ca0d-0eb9-7457-3cdee47a6804
* Version Independent ID: 9442f477-20be-a67b-a38a-1846dc3cfbc4
* Content: [az bot](https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py)
* Service: **bot-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment] 2019-05-10 16:02
//CC: @stevengum

**Comment by KevinBrooke** [comment] 2019-05-15 22:54
See here: https://github.com/MicrosoftDocs/azure-docs-cli/issues/1423

**Comment by johansandblom** [comment] 2019-05-16 12:06
I'm a bit confused here. Task MicrosoftDocs/azure-docs-cli#1423 is about breaking changes. Does this mean that support for --insights-location is dropped forever or will it be fixed in a future release?

**Comment by stevengum** [comment] 2019-05-16 17:29
@johansandblom and @bandmask, we removed support for creating an Application Insights resource when creating a v4 SDK bot because it's not required to have App Insights to deploy your bot. By always creating or using an Application Insights resource when creating a Web App bot it created the illusion that the two are tightly coupled together when this isn't actually the case.

We've also pivoted to ARM deployments and have provided [sample ARM templates][ARM-samples] and [instructions][ARM-instructions] on how to use the ARM templates. ARM templates are the standard mechanism for creating resources and the sample ARM templates provided are easily extendable to make it so that users can provision any amount or type of resources they need at once.

[App Insights ARM template reference][AI-ref]

  [ARM-Samples]: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot/DeploymentTemplates
  [ARM-instructions]: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg
  [AI-ref]: https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2015-05-01/components

**Comment by stevengum** [comment] 2019-05-16 17:30
That said it does look like there is a separate bug here, so I'll investigate and see why it says `"'--insights-location' is not recognized as an internal or external command, operable program or batch file"`

**Comment by dawwa** [comment] 2019-05-16 18:51
that is the breaking change impacts msbot, you need downgrade to earlier version.
https://github.com/Azure/azure-cli/issues/9414

**Comment by stevengum** [comment] 2019-07-03 20:11
@bandmask I'm unable to reproduce this issue in the command prompt; are you still running into this error message? Are you using single quotes or double quotes when passing in the `"North Europe"` location for `--insights-location`?

```bash
az bot create -n azcli-9363 -k webapp -v v4 --appid ########-####-####-####-############ 
-p "################################" --echo --insights-location "North Europe" 
--lang javascript --verbose -g azcli-9363
```

**Comment by stevengum** [comment] 2019-07-08 23:28
Closing issue due to inactivity, @bandmask if you are still running into this issue please **@mention** me.

**Closed by stevengum** 2019-07-08 23:28 UTC
Labels: BotService, Service Attention

**Comment by archmangler** [comment] 2020-02-25 02:41
> 
> 
> @johansandblom and @bandmask, we removed support for creating an Application Insights resource when creating a v4 SDK bot because it's not required to have App Insights to deploy your bot. By always creating or using an Application Insights resource when creating a Web App bot it created the illusion that the two are tightly coupled together when this isn't actually the case.
> 
> We've also pivoted to ARM deployments and have provided [sample ARM templates](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot/DeploymentTemplates) and [instructions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg) on how to use the ARM templates. ARM templates are the standard mechanism for creating resources and the sample ARM templates provided are easily extendable to make it so that users can provision any amount or type of resources they need at once.
> 
> [App Insights ARM template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2015-05-01/components)

@stevengum  - Just clarifying your earlier comment: is it still the case that the az bot create cli tools are broken and ARM is the way to do this?
