### ISSUE TITLE
"az network nsg create" should display warning message or be blocked when updating existing NSG

### ISSUE THREAD

**Issue by tatazoe** [Azure/azure-cli#8754] opened 2019-03-11 07:04 UTC
**Is your feature request related to a problem? Please describe.**
"az network nsg create" command change existing NSG setting without warnings.
This will impose very high risk of unexpected mis-configuration.

    [Version]
    azure-cli 2.0.59 *
    
    [How to reproduce]
    # Create NSG 
    az network nsg create -g "Dev_test01" -n "test_nsg" --tags "hogehoge" "01"
    az network nsg show -g "Dev_test01" -n "test_nsg" --query tags
    -->
    {
      "01": "",
      "hogehoge": ""
    }
    
    # Update NSG with create command
    az network nsg create -g "Dev_test01" -n "test_nsg" --tags "hogehoge" "02"
    az network nsg show -g "Dev_test01" -n "test_nsg" --query tags
    -->
    {
      "02": "",
      "hogehoge": ""
    } ** Tag information is updated with create command.

**Describe the solution you'd like**
1. Display warning message and pause the process.
2. Change specification to prohibit "az network nsg create" command for NSG updating. Use az network nsg update.

**Comment by tjprescott** [comment] 2019-03-11 17:09
This is by design and is true for nearly all create commands in the CLI. There is an open issue already to offer an opt-in safety net for all create commands (#7613). Since this ask is covered by that, I will close this issue.

**Closed by tjprescott** 2019-03-11 17:09 UTC
