### ISSUE TITLE
Unsupported API version '2020-04-01' for Network Resource. MS is fixing it.

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#13827] opened 2020-06-04 09:29 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

CLI 2.7.0 fails to run command az network vnet show

**To Reproduce**

```sh
sudo apt-get install -y apt-transport-https
# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null

##### git bash for windows based on Ubuntu
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
sudo apt-get update
sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | 
    sudo tee /etc/apt/sources.list.d/azure-cli.list

sudo apt-get update
apt search azure-cli 
apt-cache search azure-cli 
apt list azure-cli -a
sudo apt-get install azure-cli # azure-cli=2.5.0-1~bionic
sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli
sudo apt-get upgrade azure-cli
az login

az vm create --name $bastion_name \
    --image UbuntuLTS \
    --admin-username $bastion_admin_username \
    --resource-group $rg_bastion_name \
    --vnet-name $vnet_bastion_name \
    --subnet ManagementSubnet \
    --nsg $b_nsg \
    --size Standard_B1s \
    --zone 1 \
    --location $location \
    --ssh-key-values ~/.ssh/$ssh_key.pub

vnet_id=$(az network vnet show --resource-group $rg_name --name $vnet_name --query id -o tsv)
echo "VNet Id :" $vnet_id	

master_subnet_id=$(az network vnet subnet show --name $master_subnet_name --vnet-name $vnet_name  -g $rg_name --query id -o tsv)
echo "Master Subnet Id :" $master_subnet_id	

worker_subnet_id=$(az network vnet subnet show --name $worker_subnet_name --vnet-name $vnet_name -g $rg_name --query id -o tsv)
echo "Worker Subnet Id :" $worker_subnet_id	

ilb_subnet_id=$(az network vnet subnet show --resource-group $rg_name --vnet-name  $vnet_name --name $ilb_subnet_name --query id -o tsv)
echo "Internal Load BalancerLB Subnet Id :" $ilb_subnet_id	

bastion_vnet_id=$(az network vnet show --name $vnet_bastion_name -g $rg_bastion_name --query id -o tsv)
echo "Bastion VNet Id :" $bastion_vnet_id	

bastion_subnet_id=$(az network vnet subnet show --name $subnet_bastion_name --vnet-name $vnet_bastion_name -g $rg_bastion_name --query id -o tsv)
echo "Bastion Subnet Id :" $bastion_subnet_id	

acr_registry_id=$(az acr show --name $acr_registry_name --resource-group $rg_name --query "id" --output tsv)
echo "ACR registry ID :" $acr_registry_id

```

**Expected behavior**

az network vnet show command should run successfully 

**Environment summary**

 az version
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}

**Additional context**

**Comment by ezYakaEagle442** [comment] 2020-06-04 09:37
sudo apt remove azure-cli
sudo apt-get install azure-cli=2.5.1-1~bionic

This fixed the issue, looks like a regression in CLI v2.7.0 ...

**Comment by Smoovsky** [comment] 2020-06-04 09:48
Not just CLI, the portal also fails a lot of types of requests with the same error reason.

**Comment by usrme** [comment] 2020-06-04 10:05
I am also having issues with deploying network type resources in _any_ region at the moment. This is not just an issue with the CLI. Posting this here is because I can't find any official page where this issue is discussed or mentioned.

**Comment by chencivalue** [comment] 2020-06-04 10:34
Same issue here:

Failed to add peering 'xxx'. Error: No registered resource provider found for location 'westeurope' and API version '2020-04-01' for type 'virtualNetworks'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01, 2018-10-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth'..

**Comment by usrme** [comment] 2020-06-04 10:35
Is anybody able to find any official mention of this underlying issue?

**Comment by mortenlerudjordet** [comment] 2020-06-04 10:35
Have this issue. If you look at the supported api version the new one is not in the list.
`((Get-AzResourceProvider -ProviderNamespace  Microsoft.Network).ResourceTypes | Where-Object ResourceTypeName -eq networkProfiles).ApiVersions`

2020-03-01
2020-01-01
2019-12-01
2019-11-01
2019-09-01
2019-08-01
2019-07-01
2019-06-01
2019-04-01
2019-02-01
2018-12-01
2018-11-01
2018-10-01
2018-08-01
2018-07-01
2018-06-01
2018-05-01

No 2020-04-01

**Comment by usrme** [comment] 2020-06-04 10:41
@mortenlerudjordet, but if you try to just deploy a simple virtual machine in the Azure Portal, then that fails as well :smile:

**Comment by Smoovsky** [comment] 2020-06-04 10:45
> @mortenlerudjordet, but if you try to just deploy a simple virtual machine in the Azure Portal, then that fails as well 😄

You can either use an older version of az-cli or fix the api version manually in the rest request. Let's hope MS fix this soon

**Comment by JorTurFer** [comment] 2020-06-04 11:37
+1 when I try to recover an `publicIPAddresses`

**Comment by usrme** [comment] 2020-06-04 11:50
Here are some potentially useful links about this:

- https://docs.microsoft.com/en-us/answers/questions/31974/cant-create-azure-virtual-machines-network-deploym.html
- https://status.azure.com/en-us/status

>  Starting at 08:45 UTC on 04 Jun 2020, some customers may experience issues with resource creation for services that depend on the Azure Resource Manager (ARM) platform. We are aware of this issue and are actively investigating. The next update will be provided in 60 minutes, or as events warrant. This message was last updated at 11:37 UTC on 04 June 2020

**Comment by yonzhan** [comment] 2020-06-04 12:00
add to S171

**Comment by MyronFanQiu** [comment] 2020-06-04 12:58
@ezYakaEagle442 Thanks for bring this issue to us. I believe service team and ARM team are actively fixing it. I'm sorry I changed your issue's title so that I can pin this issue.

**Comment by timvanderweijde** [comment] 2020-06-04 13:01
I have the same issue with publicIPAddresses. 

When can we expected a fix and is there a workaround?

**Comment by gstolz** [comment] 2020-06-04 13:04
same here with PIP! Hope there will be a solution soon...

**Comment by MyronFanQiu** [comment] 2020-06-04 13:05
> I have the same issue with publicIPAddresses.
> 
> When can we expect a fix and is there a workaround?

I believe this issue should be fixed soon.

A workaround is to use old version of Azure CLI. Please uninstall the 2.7.0 and install any older version. It uses 2020-03-01 api-version or before which are not effected.

**Comment by timvanderweijde** [comment] 2020-06-04 13:32
> A workaround is to use old version of Azure CLI. Please uninstall the 2.7.0 and install any older version. It uses 2020-03-01 api-version or before which are not effected.

Where can I find a MSI file for version 2.6.0? How do I install an older version? It's not described in the documentation.

**Comment by MyronFanQiu** [comment] 2020-06-04 13:41
> > A workaround is to use old version of Azure CLI. Please uninstall the 2.7.0 and install any older version. It uses 2020-03-01 api-version or before which are not effected.
> 
> Where can I find a MSI file for version 2.6.0? How do I install an older version? It's not described in the documentation.

For Windows, please use this script in powershell to install previous version such as 2.6.0.
```
Invoke-WebRequest -Uri https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.6.0.msi -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
```

You can also download other older versions through 
```
https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.6.0.msi
```
Sorry for the convenience.

**Comment by pdev1989** [comment] 2020-06-04 13:51
I get the same error: 
Tried with the az-cli versions: 2.4.0 and 2.0.75.

Should I use 2.6.0 specifically ?

**Comment by MyronFanQiu** [comment] 2020-06-04 14:03
> I get the same error:
> Tried with the az-cli versions: 2.4.0 and 2.0.75.
> 
> Should I use 2.6.0 specifically ?
> 
> Error I get:
> 
> msrestazure.azure_exceptions.CloudError: Azure Error: NoRegisteredProviderFound
> Message: No registered resource provider found for location 'westeurope' and API version '2020-04-01' for type 'virtualNetworks'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01, 2018-10-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth'.

2.4.0 should not have this issue. 2020-04-01 appears in 2.7.0 first time. Did you install multiple azure-cli in your machine? Could you confirm whether you removed 2.7.0 or not?

**Comment by MyronFanQiu** [comment] 2020-06-04 14:05
The latest update for this issue is on this page. https://status.azure.com/en-us/status

**Comment by RuthNjeri** [comment] 2020-06-04 14:09
Thanks for the help @MyronFanQiu , I am trying to figure out if there is a way I can specify an older version with this command for Ubuntu and Debian
`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

**Comment by MyronFanQiu** [comment] 2020-06-04 14:26
> Thanks for the help @MyronFanQiu , I am trying to figure out if there is a way I can specify an older version with this command for Ubuntu and Debian
> `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

Hi. Installation method for old version in any platform can be found from [here](https://github.com/Azure/azure-cli/issues/13331#issuecomment-635446175)

**Comment by gstolz** [comment] 2020-06-04 18:02
Microsoft has fixed the problem on Azure backend side. For me az cli 2.7.0 (on Ubuntu 20.04) seems to work again!

> 
PRELIMINARY ROOT CAUSE: Engineers determined that a recent deployment contained a configuration bug, which caused requests through the ARM deployment and management service to fail.
MITIGATION: Engineers rolled back the faulty configuration safely, which mitigated the issue.

**Closed** 2020-06-04 23:29 UTC
Labels: Network, Service Attention
