### ISSUE TITLE
Unable to pass environment variables containing `=` to `az container create`

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-cli#4142] opened 2017-08-04 07:52 UTC
### Description
**Outline the issue here:**

An example scenario is passing a connection string to a container as environment variable.

To further illustrate, the command below:

```
az container create -g SomeGroup --name something --image some/image -e 'EVENT_HUBS_CONNECTION_STRING=Endpoint=sb://foo.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=bar='
```

Will result into the following error:

```
Incorrectly formatted enviroment settings. Argmuent values should be in the format a=b c=d
```

**Comment by tjprescott** [comment] 2017-08-04 15:35
This is a dupe of #4084.

**Closed** 2017-08-04 17:15 UTC
Labels: bug, container
