### ISSUE TITLE
'NoneType' object has no attribute 'id' for az backup protection enable-for-azurefileshare if fileshare already protected

### ISSUE THREAD

**Issue by sebastianrogers** [Azure/azure-cli#14177] opened 2020-07-02 06:18 UTC
**Describe the bug**
'NoneType' object has no attribute 'id' for az backup protection enable-for-azurefileshare if fileshare already protected

**To Reproduce**
```sh
az backup protection enable-for-azurefileshare --azure-file-share $filesharename --policy-name $policyname --storage-account $storageaccount --resource-group $resourcegroup --vault-name $vaultname --subscription $subscription
az backup protection enable-for-azurefileshare --azure-file-share $filesharename --policy-name $policyname --storage-account $storageaccount --resource-group $resourcegroup --vault-name $vaultname --subscription $subscription```
```

**Expected behavior**
Running command twice with same parameters works so that it is idempotent

**Environment summary**
azure-cli                          2.8.0

command-modules-nspkg              2.0.3
core                               2.8.0
nspkg                              3.0.4
telemetry                          1.0.4

**Additional context**

**Comment by yungezz** [comment] 2020-07-02 07:30
routing to appropriate team

**Comment by pvrk** [comment] 2020-07-06 13:14
Looking at this. Sorry for the delay in response.

**Comment by pvrk** [comment] 2020-07-06 13:15
@hiaga: Can you please look into this?

**Comment by hiaga** [comment] 2020-07-07 06:59
Able to reproduce this issue. further debugging.

**Comment by hiaga** [comment] 2020-07-07 11:42
@sebastianrogers - this error is expected because the given command is used to enable protection for the first time. If you want to re-enable/ resume the backup for your file share please use "az backup protection resume" command. Please refer to a sample below -

**az backup protection resume  -c StorageContainer;Storage;sample-rg;samplefileshare -i AzureFileShare;b119aujkkjg3j535jkjkj4h3h535jkh6j45k6hj4hkjhkjh5664a4 -p DailyPolicy --backup-management-type AzureStorage --workload-type AzureFileShare -g sample-rg -v sample-vault**

**Comment by sebastianrogers** [comment] 2020-07-07 12:21
That doesn't make it idempotent which is a big drawback meaning conditional logic has to be introduced into pipelines.

Can it be made idempotent please?

**Comment by pvrk** [comment] 2020-07-08 07:36
@sebastianrogers : Sorry, but I still do not understand the final requirement. This is a command to enable backup for a 'yet-unprotected-item'. So, not able to understand what does idempotent mean. Can you please help me out here?

**Comment by sebastianrogers** [comment] 2020-07-08 07:50
If the command was idempotent it would be an 'ensure that this item is protected regardless of its current state, i.e. protected or unprotected'

```
in imperative programming, a subroutine with side effects is idempotent if the system state remains the same after one or several calls, in other words if the function from the system state space to itself associated to the subroutine is idempotent in the mathematical sense given in the definition;
```

As I'm sure you can see this means that the pipeline that does the backup deployment can then be run multiple times without making changes.  Otherwise it has to detect the state and change its behaviour accordingly.

The ARM templates and Az CLI are nearly idempotent which makes them much better for deployment automation than the REST or PowerShell APIs.  It is a shock therefore when one of the Az CLI calls is not idempotent.

**Comment by pvrk** [comment] 2020-07-08 08:05
@sebastianrogers : From an ARM template/deployment perspective, we got a feedback that they customers want different behaviors for protected and unprotected behaviors and hence they don't usually combine both. Because when it is unprotected, there are inputs like vault and policy and when it is protected, there are other parameters like adhoc backup and retention time. So, it will help if you can explain what is the behavior you intend to have for protected and unprotected. Is it different for you or same?

**Comment by sebastianrogers** [comment] 2020-07-08 16:14
Its always the same in that I don't know or care what state the system is currently in, I want it to be in the described state when  the command has run.

In the case of an adhoc backup I would expect that to be an imperative command not a declarative one.  In the case of retention time I would expect that to be available when specifying how the fileshare should be protected, if I specify again and choose a different value then it should change.

In the case of the az backup protection enable-for-azurefileshare if it is run twice and the parameters are still valid then I would not expect an error.

Maybe to avoid a breaking change an idempotent option is needed which creates or modifies if needed?

```sh
az backup protection azurefileshare
```

**Comment by yungezz** [comment] 2020-07-09 01:45
#14287

**Comment by pvrk** [comment] 2020-07-09 05:39
Since the underlying REST API doesn't behave this way, we need to discuss internally on this and come back. Please give us some time. Current ETA: July 23rd.

**Comment by sebastianrogers** [comment] 2020-07-09 08:22
Certainly, thank you

**Comment by pvrk** [comment] 2020-07-24 09:54
@sebastianrogers : Sorry for the delay. We discussed this internally and one of the option is as you suggested "Maybe to avoid a breaking change an idempotent option is needed which creates or modifies if needed". We can think of a parameter that indicate an idempotent response is required. If that parameter is not given, then current behavior continues i.e., error if the given resource is already protected. While we have this option, we have to plan and implement. Will update once more when the plan is finalized and I have a release date in mind.

**Comment by pvrk** [comment] 2020-07-24 12:37
@sebastianrogers : Also want to clarify that this command will not replace the resume backup behavior. If protection is stopped, you still have to az backup protection resume (which takes in different set of parameters i.e., item-name, container-name etc). This can be the final behavior.

An Azure File share sampleFileShare is not protected.
```az backup protection enable-for-fileshare``` is ran with the relevant parameters - it is successful
The Azure File share sampleFileShare is now protected. If we just again run the query
```az backup protection enable-for-fileshare``` is ran with the relevant parameters - it is successful
The Azure File share sampleFileShare protection is disabled. The backup data is retained but protection is inactive. If we just again run the query
```az backup protection enable-for-fileshare``` is ran with the relevant parameters - it will lead to error
You need to run the ```az backup protection resume``` command with a different set of parameters.

Hope this is clear.

**Comment by sebastianrogers** [comment] 2020-07-24 15:39
That sounds ideal.

**Comment by andresgomezfrr** [comment] 2020-09-01 06:47
I have the same problem but the first time that I execute the command `az backup protection enable-for-azurefileshare` within an unprotected fileshare. Any idea?

```    
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 782, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom_base.py", line 304, in enable_for_azurefileshare
    return custom_afs.enable_for_AzureFileShare(cmd, client, resource_group_name, vault_name, azure_file_share,
  File "/usr/local/Cellar/azure-cli/2.11.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom_afs.py", line 72, in enable_for_AzureFileShare
    container_uri = helper.get_protection_container_uri_from_id(protectable_item.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by pvrk** [comment] 2020-09-24 11:17
@andboyer : The error usually comes when the item to be protected is not found/identified. Can you please re-run the command with "--debug" parameter to know more about the service response?

**Comment by mepand** [comment] 2020-10-14 07:45
@andboyer : Can you please share the trace after executing the command with --debug parameter so that we can analyze further?

**Comment by mepand** [comment] 2021-03-21 16:36
We are working on making the API response idempotent and tracking it internally. Once the changes are live, we will update the thread. Since there is no immediate action pending on the PG team, closing this thread. Incase you have any further questions or concerns, please feel free to reopen this case or open a new one with reference to this issue.

**Closed by mepand** 2021-03-21 16:36 UTC
Labels: Recovery Services Backup, Service Attention, customer-reported, feature-request
