### ISSUE TITLE
az synapse notebook create

### ISSUE THREAD

**Issue by chitrankv27** [Azure/azure-cli#21686] opened 2022-03-18 03:27 UTC
## Describe the bug

**Command Name**
`az synapse notebook create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'metadata'
Traceback (most recent call last):
  File "/Users/vermach/brew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/vermach/brew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/Users/vermach/brew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/vermach/brew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/Users/vermach/brew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/vermach/brew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/vermach/brew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 228, in create_or_update_notebook
    metadata = definition_file['metadata']
KeyError: 'metadata'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse notebook create --workspace-name {} --name {} --file {} --spark-pool-name {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
datafactory 0.5.0
storage-preview 0.8.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-03-18 06:46
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2022-03-18 18:32
@chitrankv27 I do not see this issue in my environment.  I believe the problem is with the .ipynpb file which you are trying to upload.  Did you try uploading any other file.

**Comment by chitrankv27** [comment] 2022-03-21 02:41
Hi @SaurabhSharma-MSFT  - I have developed notebook from the synapse studio and its a json file and not .ipynb file
I am trying to deploy it in synapse live env with az cmds.

**Comment by chitrankv27** [comment] 2022-03-21 02:43
![Screen Shot 2022-03-20 at 10 42 50 PM](https://user-images.githubusercontent.com/62769794/159198781-4956ff5b-ed0b-482b-85ac-a3824d73cca3.png)

**Comment by SaurabhSharma-MSFT** [comment] 2022-03-24 21:39
@chitrankv27 Have you tried importing the by changing the extension to `.ipynb` as I believe only .ipynb file is supported for importing.

**Comment by SaurabhSharma-MSFT** [comment] 2022-03-29 22:52
@chitrankv27 Please let me know if you have any questions.

**Comment by chitrankv27** [comment] 2022-03-30 23:21
Hi @SaurabhSharma-MSFT  - I am able to deploy file with `.pynb` extension. My ask is that to deploy notebook which is getting created as JSON files in synapse github repo. I have github integration enabled in Synapse. Now I want to promote my notebook from dev to master branch and then use `az cmds` to deploy those JSON notebooks in Synapse Production Live env. Currently as my master branch has only JSON files, I am curious to know how can we deploy those. 

Screenshot of my github repo. 

![Screen Shot 2022-03-30 at 7 17 55 PM](https://user-images.githubusercontent.com/62769794/160946441-bb158361-12a0-4d93-bbe5-8091ee582ef2.png)

**Comment by SaurabhSharma-MSFT** [comment] 2022-04-14 18:06
@chitrankv27 Sorry for the delay on this one.  I am working internally with the products team on this issue and get back to you as early as possible.

**Comment by SaurabhSharma-MSFT** [comment] 2022-04-21 16:22
@chitrankv27 You can try to use git CI/CD tools to copy artifacts from one synapse workspace to another synapse workspace.
There is a doc about CI/CD for azure synapse: [Continuous integration & delivery in Azure Synapse Analytics - Azure Synapse Analytics](https://docs.microsoft.com/en-us/azure/synapse-analytics/cicd/continuous-integration-delivery) which will help you achieve the same.  Please let me know if you have any other questions.

**Comment by SaurabhSharma-MSFT** [comment] 2022-04-26 21:35
@chitrankv27 Please let me know if you have any questions else, we will proceed with the closure of this issue.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment] 2022-05-02 17:50
@chitrankv27 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-05-02 17:50 UTC
Labels: customer-reported, Synapse, needs-team-attention, needs-author-feedback, CXP Attention, Auto-Assign
