### ISSUE TITLE
az functionapp raises CryptographyDeprecationWarning due to outdated version of paramiko

### ISSUE THREAD

**Issue by olsgaard** [Azure/azure-cli#30299] opened 2024-11-11 07:53 UTC
### Describe the bug

az uses outdated paramiko 3.4.0. Should use 3.4.1 or newer to avoid "CryptographyDeprecationWarning"

### Related command

$ az functionapp list > /dev/null

### Errors

/opt/az/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/opt/az/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,

### Issue script & Debug output

There is too much private data in the debug statement to post here.

### Expected behavior

No "CryptographyDeprecationWarning"

### Environment Summary

azure-cli                         2.66.0

core                              2.66.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/supermads/.azure/cliextensions'

Python (Linux) 3.12.7 (main, Oct 30 2024, 03:55:58) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

You can fix the issue locally by running `sudo /opt/az/bin/python3 -m pip install --upgrade paramiko` which is probably not a good idea.

**Comment by yonzhan** [comment] 2024-11-11 07:53
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2024-11-12 03:22
Duplicate of https://github.com/Azure/azure-cli/issues/30147

**Closed by bebound** 2024-11-12 03:22 UTC
Labels: bug, Service Attention, Functions, customer-reported, Auto-Assign, Similar-Issue
