### ISSUE TITLE
 Az login error [WinError -2146893813] Key not valid for use in specified state.. 

### ISSUE THREAD

**Issue by CharbelHanna** [Azure/azure-cli#22707] opened 2022-06-02 09:31 UTC
I got a strange error today when I am trying to login or logout to azure via Az cli

Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

I am running the below environment

azure-cli                           2.37.0

core                                  2.37.0
telemetry                          1.0.6

Extensions:
aks-preview                           0.5.76
azure-devops                         0.25.0
resource-graph                       2.1.0

Dependencies:
msal                                         1.18.0b1
azure-mgmt-resource             21.1.0b1

**Comment by yonzhan** [comment] 2022-06-02 10:30
Duplicate of https://github.com/Azure/azure-cli/issues/20231

**Closed by yonzhan** 2022-06-02 10:30 UTC
Labels: Graph, customer-reported, Auto-Assign
