### ISSUE TITLE
Compatibility with SRV record sets of BIND-generated DNS zone files

### ISSUE THREAD

**Issue by angalyuz** [Azure/azure-cli#7405] opened 2018-09-24 21:56 UTC
**Problem**
Azure CLI does not support `.@` at the end of SRV record set name. 

**Solution**
Azure CLI should strip `.@` from SRV record set name before passing to Azure DNS.

**Additional context**
Example of zone file:
```
; Exported zone file from Azure DNS
;      Zone name: azurecli.test
;      Resource Group Name: angalyuz
;      Date and time (UTC): Thu, 13 Sep 2018 12:09:12 -0700

$TTL 300
$ORIGIN azurecli.test.
    
_sipfederationtls._tcp.@ 3600 IN SRV 100 1 5061 sipfed.online.lync.com.

_sip._tls 3600 IN SRV 100 1 443 sipdir.online.lync.com.

autodiscover 3600 IN CNAME autodiscover.outlook.com.

sip 3600 IN CNAME sipdir.online.lync.com.

www 3600 IN CNAME www.azurewebsites.net.

@ 3600 IN TXT "v=spf1 include:spf.protection.outlook.com -all"
```

Example of Azure CLI output:
```
>az network dns zone import -g angalyuz -n azurecli.test -f zone.txt

== BEGINNING ZONE IMPORT: azurecli.test ==

(1/6) Imported 1 records of type 'txt' and name '@'
400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/a984ce58-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/angalyuz/providers/Microsoft.Network/dnsZones/azurecli.test/SRV/_sipfederationtls._tcp.@?api-version=2018-03-01-preview
(3/6) Imported 1 records of type 'srv' and name '_sip._tls'
(4/6) Imported 1 records of type 'cname' and name 'autodiscover'
(5/6) Imported 1 records of type 'cname' and name 'sip'
(6/6) Imported 1 records of type 'cname' and name 'www'

== 5/6 RECORDS IMPORTED SUCCESSFULLY: 'azurecli.test' ==
```

**Comment by tjprescott** [comment] 2018-10-01 16:53
This is a duplicate of #2917.

**Closed by tjprescott** 2018-10-01 16:53 UTC
Labels: Network-cli
