### ISSUE TITLE
az aks upgrade still prompts for confirmation even when -y or --yes specified

### ISSUE THREAD

**Issue by david618** [Azure/azure-cli#12142] opened 2020-02-11 21:04 UTC
**Describe the bug**
When we run 

```
az aks upgrade ...
Kubernetes may be unavailable during cluster upgrades.
Are you sure you want to perform this operation? (y/n):
```

 When we add the -y or --yes
 
```
az aks upgrade --yes ...
```
It gets up past this first yes; then wait at another prompt. 
 
Then either

```
Since control-plane-only argument is specified, this will upgrade only the control plane to 1.15.5. Node pool will not change. Continue? (y/N):
```
or
 
```
Since control-plane-only argument is not specified, this will upgrade the control plane AND all nodepools to version 1.15.5. Continue? (y/N):
```

**To Reproduce**
Run az aks upgrade on a cluster with the -y or --yes option. 

**Expected behavior**
If -y or --yes is provided; the upgrade should proceed without prompts. 

**Environment summary**
Install Method
- Ubuntu: apt-get
- Mac:  brew install 

Azure CLI Version: 2.0.81 

**Additional context**
None

**Comment by arrownj** [comment] 2020-02-12 01:28
@david618 , thanks for reporting, we are looking at this.

**Comment by tdihp** [comment] 2020-02-29 02:49
Duplicate of https://github.com/Azure/azure-cli/issues/11099

**Comment by Jen7714** [comment] 2020-05-29 16:47
Please check this fix for the latest status: https://github.com/Azure/azure-cli/pull/13741

**Closed by Jen7714** 2020-05-29 16:47 UTC
Labels: AKS, Service Attention
