### ISSUE TITLE
Azure AKS

### ISSUE THREAD

**Issue by luke-garcia** [Azure/azure-cli#16846] opened 2021-02-08 09:13 UTC
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
<urlopen error [Errno -3] Try again>
Traceback (most recent call last):
lib/python3.6/urllib/request.py, ln 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
lib/python3.6/http/client.py, ln 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
lib/python3.6/http/client.py, ln 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
lib/python3.6/http/client.py, ln 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
lib/python3.6/http/client.py, ln 1036, in _send_output
    self.send(msg)
...
local/lib/python3.6/socket.py, ln 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again


lib/python3.6/urllib/request.py, ln 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Try again>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Linux-4.19.121-linuxkit-x86_64-with
Python 3.6.10
Installer: DOCKER

azure-cli 2.18.0

```

**Comment by yonzhan** [comment] 2021-02-08 09:40
aks

**Comment by RakeshMohanMSFT** [comment] 2022-08-09 08:55
Duplicate of https://github.com/Azure/azure-cli/issues/15860

**Closed by RakeshMohanMSFT** 2022-08-09 08:55 UTC
Labels: Service Attention, AKS
