### ISSUE TITLE
`az ad sp credential list --id ` throws error Parameter 'application_object_id' can not be None.

### ISSUE THREAD

**Issue by hvnsweeting** [Azure/azure-cli#8900] opened 2019-03-28 09:30 UTC
**Describe the bug**

```
 $ az ad sp credential list --id yyy-zzz-zzzz-zzzz-xxx
The command failed with an unexpected error. Here is the traceback:

Parameter 'application_object_id' can not be None.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 400, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 1080, in list_service_principal_credentials
    return _get_service_principal_credentials(graph_client, app_object_id, cert)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 1087, in _get_service_principal_credentials
    app_creds = list(graph_client.applications.list_password_credentials(app_object_id))
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/graphrbac/operations/applications_operations.py", line 669, in internal_paging
    'applicationObjectId': self._serialize.url("application_object_id", application_object_id, 'str'),
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 592, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 662, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'application_object_id' can not be None.
```

**To Reproduce**
Run 
```
 $ az ad sp credential list --id yyy-zzz-zzzz-zzzz-xxx
```

**Expected behavior**

Error message or list of credentials, not stacktrace.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
 $ brew info azure-cli
azure-cli: stable 2.0.61 (bottled), HEAD
Microsoft Azure CLI 2.0
https://docs.microsoft.com/cli/azure/overview
/usr/local/Cellar/azure-cli/2.0.61 (26,234 files, 121.1MB) *
  Poured from bottle on 2019-03-28 at 16:25:23
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/azure-cli.rb
==> Dependencies
Required: openssl ✔, python ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 15,924 (30 days), 43,213 (90 days), 138,953 (365 days)
install_on_request: 15,724 (30 days), 42,611 (90 days), 135,991 (365 days)
build_error: 0 (30 days)

$ az --version
azure-cli                         2.0.61

acr                                2.2.3
acs                               2.3.20
advisor                            2.0.0
ams                                0.4.3
appservice                        0.2.16
backup                             1.2.2
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                         0.1.9
cdn                                0.2.1
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.61
cosmosdb                           0.2.9
dla                                0.2.5
dls                                0.1.8
dms                                0.1.3
eventgrid                          0.2.2
eventhubs                          0.3.4
extension                          0.2.4
feedback                           2.1.4
find                               0.3.1
hdinsight                          0.3.2
interactive                        0.4.2
iot                                0.3.7
iotcentral                         0.1.6
keyvault                          2.2.13
kusto                              0.2.1
lab                                0.1.6
maps                               0.3.4
monitor                           0.2.11
network                            2.3.5
nspkg                              3.0.3
policyinsights                     0.1.2
profile                            2.1.4
rdbms                              0.3.9
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.12
role                               2.4.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.15
signalr                            1.0.0
sql                                2.2.0
sqlvm                              0.1.1
storage                            2.3.2
telemetry                          1.0.2
vm                                2.2.17

Extensions:
subscription                       0.1.1
interactive                        0.4.1

Python location '/usr/local/Cellar/azure-cli/2.0.61/libexec/bin/python'
Extensions directory '/Users/xxx/.azure/cliextensions'

Python (Darwin) 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by tjprescott** [comment] 2019-04-03 15:54
@marstr @yugangw-msft for comment.

**Comment by yugangw-msft** [comment] 2019-04-04 03:52
@hvnsweeting, if you run `az ad sp show --spn yyy-zzz-zzzz-zzzz-xxx`, do you get anything? If nothing, then it is multi-tenant app which was created in an external tenant. The error needs polish, but the behavior is by-design

**Comment by MattMencel** [comment] 2019-04-04 19:17
@yugangw-msft I'm seeing the same error and ran that command you posted.

``` bash
> az ad sp show --id 8ac6f6f2-...  -o json                                                                                        1251ms < Thu Apr  4 14:11:05 2019
{
  "accountEnabled": "True",
  "addIns": [],
  "alternativeNames": [],
  "appDisplayName": "MATT-TEST",
  "appId": "37d49879-b9.....",
...
```

Running the credential list command gives me an error...

``` bash
az ad sp credential list --id 8ac6f6f2-...
The command failed with an unexpected error. Here is the traceback:

Parameter 'application_object_id' can not be None.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 400, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 1080, in list_service_principal_credentials
    return _get_service_principal_credentials(graph_client, app_object_id, cert)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 1087, in _get_service_principal_credentials
    app_creds = list(graph_client.applications.list_password_credentials(app_object_id))
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/graphrbac/operations/applications_operations.py", line 669, in internal_paging
    'applicationObjectId': self._serialize.url("application_object_id", application_object_id, 'str'),
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 592, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 662, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'application_object_id' can not be None.
```

This Application, SPN, and credential was created using Terraform...

``` terraform
resource "random_uuid" "spn_password" {}

resource "azuread_application" "spn" {
  name     = "${var.spn_name}"
  homepage = "${local.spn_url}"
}

resource "azuread_service_principal" "spn" {
  application_id = "${azuread_application.spn.application_id}"
}

resource "azuread_service_principal_password" "spn" {
  service_principal_id = "${azuread_service_principal.spn.id}"
  value                = "${random_uuid.spn_password.result}"
  end_date_relative    = "${var.spn_password_expiry}"
}
```

The SPN and credential work fine for my purposes, I just can't list the credentials from `az cli`.

**Comment by yugangw-msft** [comment] 2019-04-05 03:56
@MattMencel, what you get if you use `app credential list` with appId
```
    az ad app credential list --id 37d49879-b9.....
```

**Comment by MattMencel** [comment] 2019-04-05 13:07
`az ad app credential list --id 37d49879-b9....`

The command returns an empty line.  No errors.

**Comment by yugangw-msft** [comment] 2019-04-18 03:44
I still can't reproduce it.
```bash
(env) C:\sdk\azure-cli-extensions>az ad sp create-for-rbac -n yugangw-creds --skip-assignment
Changing "yugangw-creds" to a valid URI of "http://yugangw-creds", which is the required format used for service principal names
{
  "appId": "6b5bbcaa-6bcb-4f55-803d-179485cf12345",
  "displayName": "yugangw-creds",
  "name": "http://yugangw-creds",
  "password": "ed901407-c669-415f-9c79-078bc0512345",
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a312345"
}

(env) C:\sdk\azure-cli-extensions>az ad sp credential list --id 6b5bbcaa-6bcb-4f55-803d-179485cf12345
[
  {
    "additionalProperties": null,
    "customKeyIdentifier": "rbac",
    "endDate": "2020-04-18T03:37:35.876609+00:00",
    "keyId": "2657913d-4267-4b49-bbb4-3dd3308b1b7a",
    "startDate": "2019-04-18T03:37:35.876609+00:00",
    "value": null
  }
]

(env) C:\sdk\azure-cli-extensions>az ad app credential list --id 6b5bbcaa-6bcb-4f55-803d-79485cf12345
[
  {
    "additionalProperties": null,
    "customKeyIdentifier": "rbac",
    "endDate": "2020-04-18T03:37:35.876609+00:00",
    "keyId": "2657913d-4267-4b49-bbb4-3dd3308b1b7a",
    "startDate": "2019-04-18T03:37:35.876609+00:00",
    "value": null
  }
]
```

**Comment by neiltingley3** [comment] 2019-04-24 13:41
I get the exact same error for a  SP created with terraform .

**Comment by MattMencel** [comment] 2019-05-07 13:43
[This comment](https://github.com/terraform-providers/terraform-provider-azuread/issues/77#issuecomment-489641152) in the Azure Provider for Terraform seems to indicate it may be an issue in Azure CLI?

**Comment by yugangw-msft** [comment] 2019-05-07 16:16
Let me try from terraform. Hope I can find a repro

**Comment by yugangw-msft** [comment] 2019-05-08 06:25
@MattMencel, I figured out. The fix will be released in 2 weeks.

**Closed** 2019-06-26 20:02 UTC
Labels: Authorization-cli, Bug

**Comment by cbtham** [comment] 2019-10-10 11:23
I am still facing the same issue when using terraform to create a SP. After SP creation, azure portal does not show a secret being saved. When i do "az sp list" output is []
