### ISSUE TITLE
No details on what a condition is or what it can be set to

### ISSUE THREAD

**Issue by etaham** [Azure/azure-cli#17935] opened 2021-04-30 19:30 UTC
There is no description of what a condition is and what its potential values are. Please update the docs and/or add a link to the documentation for role assignment conditions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dacfad8-cb2f-2534-3b29-89b0930a2252
* Version Independent ID: 17325cd4-44c5-4069-d9f6-940a55f0f7c9
* Content: [az role assignment](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/role/assignment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/role/assignment.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2021-04-30 23:22
@jiasli for awareness

**Comment by jiasli** [comment] 2023-08-24 12:00
Duplicate of #15628

**Closed** 2023-08-24 12:01 UTC
Labels: RBAC, feature-request
