### ISSUE TITLE
az functionapp config ssl import - breaks with latest CLI version (Microsoft Graph api updates)

### ISSUE THREAD

**Issue by asos-vinodpatil** [Azure/azure-cli#22761] opened 2022-06-07 10:23 UTC
## Describe the bug

**Command Name**
`az functionapp config ssl import`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'GraphClient' object has no attribute 'service_principals'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 39, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2700, in import_ssl_cert
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2779, in _check_service_principal_permissions
AttributeError: 'GraphClient' object has no attribute 'service_principals'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp config ssl import --resource-group {} --name {} --key-vault {} --key-vault-certificate-name {}`

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
cosmosdb-preview 0.11.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-06-07 10:42
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-06-07 16:14
@asos-vinodpatil it looks like a regression in Az CLI 2.37.0 can you downgrade to 2.36.0 and check if it works? I verified and it works for me.

**Comment by asos-vinodpatil** [comment] 2022-06-07 16:16
Hi Rakesh,

Yes it works for 2.36.0. Opened this ticket for 2.37.0 

Thanks,
Vinod

**Comment by RakeshMohanMSFT** [comment] 2022-06-08 08:26
Closing this issue, it is being tracked in https://github.com/Azure/azure-cli/issues/22722

**Closed by RakeshMohanMSFT** 2022-06-08 08:26 UTC
Labels: bug, Service Attention, Functions, customer-reported, needs-team-attention, Auto-Assign
