### ISSUE TITLE
Unable to use `table` output when querying az command results

### ISSUE THREAD

**Issue by Christophosaurus** [Azure/azure-cli#20469] opened 2021-11-22 16:05 UTC
## Describe the bug
I am unable to return table output when querying az commands. `az group list -o table` returns the error `Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.`.

I am using the `azure-cli` in normal mode (not interactive mode). I found a closed issue #14634 relating to the same problem in the interactive shell.

![image](https://user-images.githubusercontent.com/16116204/142889595-fb89019a-a07f-4936-98a9-3d41b46c35c2.png)

I am also experiencing another issue running commands which are returning an error #20444. I am not sure if these are related or not.

I have run `brew doctor` yielding no results specific to the azure-cli (or anything seemingly related) 

I have also uninstalled and reinstalled azure-cli via homebrew. And uninstalled, ran `brew cleanup -s` and even `rm -rf $(brew --cache)` before re-install and am getting the same error.

**Command Name**
`az group list -o table`  or just any command querying to the table output

**Errors:**
```
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Run any valid command with the postfix` -o table` flag
## Expected Behavior
the command should output to the table format (which it does in the cloud shell)

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.30.0

Extensions:
aks-preview 0.5.42
interactive 0.4.5

```
## Additional Context

Table output runs as expected in the cloud shell for the same commands I am trying from my local terminal.

**Comment by yonzhan** [comment] 2021-11-22 23:27
@jiasli for awareness

**Comment by jiasli** [comment] 2021-11-23 03:12
Duplicate of #20348

**Closed** 2021-11-24 02:13 UTC
Labels: Core, ARM, customer-reported
