### ISSUE TITLE
ML Extension 2.30.0 responds with: `'ml' is misspelled or not recognized by the system` when triggered.

### ISSUE THREAD

**Issue by yogeshg** [Azure/azure-cli#29940] opened 2024-09-19 21:02 UTC
### Describe the bug

ML Extension 2.30.0 responds with: `'ml' is misspelled or not recognized by the system` when triggered.

### Related command

```
$ az ml --help
```

### Errors

```
'ml' is misspelled or not recognized by the system.
```

### Issue script & Debug output

```bash
$ az extension add --name ml
Default enabled including preview versions for extension installation now. Disabled in May 2024. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
 - Searching ..
Extension 'ml' 2.29.0 is already installed.
$ az extension update --name ml
Default enabled including preview versions for extension installation now. Disabled in May 2024. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
 - Installing ..

$ az version
cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/homebrew/Cellar/azure-cli/2.60.0/libexec/lib/python3.11/site-packages/azure/core/credentials.py)
{
  "azure-cli": "2.60.0",
  "azure-cli-core": "2.60.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ml": "2.30.0",
    "storage-preview": "1.0.0b1"
  }
}
$ az ml --help
cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/homebrew/Cellar/azure-cli/2.60.0/libexec/lib/python3.11/site-packages/azure/core/credentials.py)
'ml' is misspelled or not recognized by the system.
```

### Expected behavior

It should return the error message.

### Environment Summary

```
{
  "azure-cli": "2.60.0",
  "azure-cli-core": "2.60.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ml": "2.30.0",
    "storage-preview": "1.0.0b1"
  }
}
```
I am using this in mac os. M3 machine

**Comment by yonzhan** [comment] 2024-09-19 21:02
Thank you for opening this issue, we will look into it.

**Comment by levu74** [comment] 2024-09-20 06:00
I'm facing the same issue after upgrade `ml` extension to latest version

```
 {
    "experimental": false,
    "extensionType": "whl",
    "name": "ml",
    "path": "<removed>",
    "preview": false,
    "version": "2.30.0"
  }
```

**Comment by miladh** [comment] 2024-09-20 07:08
Started to see same error since yesterday, even with older versions (`2.23.0`). 

Created this ticket in `azure-sdk-for-python` (although it should probably have been created in this repo). Cross sharing for awareness: https://github.com/Azure/azure-sdk-for-python/issues/37491

**Comment by MetelStairs** [comment] 2024-09-20 08:21
Similar issue on our end, it was all working fine yesterday but not running into this issue.

**Comment by rikwatson** [comment] 2024-09-20 08:23
Also seeing since today (2024-09-20)

**Comment by AndreasJ91** [comment] 2024-09-20 08:43
Also seeing it since today (2024-09-20)

**Comment by mrcrelex** [comment] 2024-09-20 08:52
Same problem on 2.21.1

**Comment by alehpa** [comment] 2024-09-20 09:14
Same here. My Azure devops pipelines are broken. Even if I specify previous version of ml 2.29.0.  Found that pipeline was working with OS: Ubuntu 22.04.4 LTS. Now pool returns Ubuntu 22.04.5 LTS. Code of pipeline the same. The only thing environment changed. I have tried  
pool:
    vmImage: ubuntu-20.04
Nothing changed  - the same error.

**Comment by pvaneck** [comment] 2024-09-20 09:41
It appears that there is some intermingling of dependencies. Do extension Python package dependencies consider the base azure-cli dependencies when installed?

Looking at where CLI extension dependencies are installed for me, (`~/.azure/cliextensions/ml`), I do see that there are compatible versions of `azure-core` and `azure-identity` installed. However, the versions of these packages installed in the `azure-cli` Python virtual environment (e.g. `/opt/az/lib/python3.11/site-packages/`) seem to take precedence at runtime causing incompatibilities. 

I think something may need updating in the dependency resolution logic when installing an extension. Ideally, azure-cli extension Python requirements should remain compatible with the base azure-cli requirements when the extension is installed (i.e. azure-identity 1.17.1 should automatically have been installed with the ML extension).

The **workaround** is to install an older version of azure-identity in whatever virtual environment azure-cli is using. 

Example workarounds:

**Linux**:
```bash
sudo /opt/az/bin/python3 -m pip install azure-identity==1.17.1
```

**Windows** (in elevated/administrator terminal):
```bash
C:\"Program Files (x86)"\"Microsoft SDKs"\Azure\CLI2\python.exe -m pip install azure-identity==1.17.1
```

Not sure about Mac, but probably just need to run the python executable somewhere in `/opt/homebrew/Cellar/azure-cli/2.60.0/libexec/` ?

I think you can glean the location of the environment your azure-cli is using based on the error message:

`cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)` -> Need to use python executable somewhere in `/opt/az`

**Comment by yogeshg** [comment] 2024-09-20 15:20
Thanks @pvaneck  I am trying out the workaround, and seems promising. I tried pinning the cli and the extension versions y'day, but was seeing the issue with older versions too, just like [this report](https://github.com/Azure/azure-cli/issues/29940#issuecomment-2362986021). Thanks for debugging and explaining the issue, now it makes sense why even the older versions would be broken.  I hope you can address the root cause by updating the packaging strategy, perhaps syncing the release cadence of the Azure CLI and its extensions. Python dependency hell is well-named for a reason!

**Comment by kairu-ms** [comment] 2024-09-23 02:50
It's resolved by https://github.com/Azure/azure-cli-extensions/pull/8006

**Closed by kairu-ms** 2024-09-23 02:50 UTC
Labels: bug, Service Attention, Machine Learning, customer-reported, Auto-Assign, Auto-Resolve, Similar-Issue

**Comment by jiasli** [comment] 2024-09-23 04:31
> However, the versions of these packages installed in the `azure-cli` Python virtual environment (e.g. `/opt/az/lib/python3.11/site-packages/`) seem to take precedence at runtime causing incompatibilities.

It is by design that packages installed by base Azure CLI take precedence. Previously, there was a PR https://github.com/Azure/azure-cli/pull/12778 to prioritize packages installed by extensions, but it was rejected as explained in https://github.com/Azure/azure-cli/pull/12778#issuecomment-605759789.

The base Azure CLI has no dependency on `azure-identity` (https://github.com/Azure/azure-cli/pull/19853#issuecomment-1011763038), but it depends on 

https://github.com/Azure/azure-cli/blob/9f506a39ebdf963001ab64b5db102f2e2c26a38d/src/azure-cli/requirements.py3.Linux.txt#L11

We have to bump to `azure-core>=1.31.0` (https://github.com/Azure/azure-cli/pull/29944) so that Azure CLI can be compatible with `azure-identity>=1.18.0` (https://github.com/Azure/azure-sdk-for-python/pull/36882).

**Comment by emibcn** [comment] 2024-10-30 08:19
> We have to bump to `azure-core>=1.31.0` ([#29944](https://github.com/Azure/azure-cli/pull/29944)) so that Azure CLI can be compatible with `azure-identity>=1.18.0` ([Azure/azure-sdk-for-python#36882](https://github.com/Azure/azure-sdk-for-python/pull/36882)).

In Ubuntu, for doing this manually (until updated APT packages are publicly available), you can execute the commands published in https://github.com/Azure/azure-cli/issues/30209#issuecomment-2446061758 :
```shell
sudo /opt/az/bin/python3 -m pip install \
    azure-core==1.31.0 \
    azure-identity==1.18.0
```

**Comment by yogeshg** [comment] 2025-01-06 23:14
looks like similar issues happen on new release of ml extension: https://github.com/Azure/azure-cli/issues/30615

**Comment by yogeshg** [comment] 2025-04-09 18:55
Another one: https://github.com/Azure/azure-cli-extensions/issues/8646

**Comment by yogeshg** [comment] 2025-04-17 21:21
There have been many issues of this sort:
https://github.com/Azure/azure-cli/issues/29940
https://github.com/Azure/azure-cli/issues/30615
https://github.com/Azure/azure-cli-extensions/issues/8646
https://github.com/Azure/azure-cli-extensions/issues/8667
