### ISSUE TITLE
Client font color will be broken after pipeline and `findstr` command are used in Windows CMD

### ISSUE THREAD

**Issue by bim-msft** [Azure/azure-cli#11671] opened 2019-12-26 08:16 UTC
**Describe the bug**
![微信截图_20191226160908](https://user-images.githubusercontent.com/3250203/71466287-15d7e880-27fa-11ea-9b30-f77296aef057.png)

**To Reproduce**
1. Run `az network private-endpoint list-types -l eastus2euap`
2. Then run `az network private-endpoint list-types -l eastus2euap | findstr vault`

**Environment summary**
azure-cli dev branch 93a50bb
knack 0.6.3

**Comment by bim-msft** [comment] 2019-12-26 08:17
@jiasli Please take a look.

**Comment by jiasli** [comment] 2020-03-17 06:23
Will be fixed by https://github.com/microsoft/knack/pull/181, https://github.com/Azure/azure-cli/pull/12604

**Closed by jiasli** 2020-03-17 06:23 UTC
Labels: Core, Feature Request, OKR3.2 Candidate

**Comment by jiasli** [comment] 2021-01-20 02:59
Duplicate of #6080

**Comment by jiasli** [comment] 2021-01-20 03:07
This issue has been fixed. Please see https://github.com/Azure/azure-cli/issues/6080#issuecomment-763294594 for the solution.
