### ISSUE TITLE
"az login" failed

### ISSUE THREAD

**Issue by takamatsujun** [Azure/azure-cli#23774] opened 2022-09-02 16:59 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1662134292.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1662137629,
  "nbf": 1662137629,
  "exp": 1662141529,
  "aio": "AWQAm/8TAAAA/ZqemJqTJwBJ6OT7gN2E0g+8JiCLer5nnOOXjI+RBz2NOImZWwUkPYBqxMLR/vCYeHURAvJVyIC9zd4vbcemvLJeYhRlLmhYmPPz41bvSn6d/dXBM7RNsQYwPLAyu/iw",
  "name": "Jun Takamatsu",
  "oid": "f4985163-d092-4cef-b9f2-9cd89ed9f29a",
  "preferred_username": "takamatsujun@microsoft.com",
  "puid": "100320013E3719F2",
  "rh": "0.AQEAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAKM.",
  "sub": "ZKH5uGQB8tu8jVPpGrLaQix4jB-48vhRZeq_bp0UlB8",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "K5nPygRrTkeLBbPvhF80AA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 152, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1670, in acquire_token_by_device_flow
    response = _clean_up(self.client.obtain_token_by_device_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 384, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 346, in _obtain_token_by_device_flow
    result = self._obtain_token(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 789, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 599, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 310, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 153, in __add
    decode_id_token(id_token, client_id=event["client_id"])
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    raise RuntimeError("%s Current epoch = %s.  The id_token was: %s" % (
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1662134292.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1662137629,
  "nbf": 1662137629,
  "exp": 1662141529,
  "aio": "AWQAm/8TAAAA/ZqemJqTJwBJ6OT7gN2E0g+8JiCLer5nnOOXjI+RBz2NOImZWwUkPYBqxMLR/vCYeHURAvJVyIC9zd4vbcemvLJeYhRlLmhYmPPz41bvSn6d/dXBM7RNsQYwPLAyu/iw",
  "name": "Jun Takamatsu",
  "oid": "f4985163-d092-4cef-b9f2-9cd89ed9f29a",
  "preferred_username": "takamatsujun@microsoft.com",
  "puid": "100320013E3719F2",
  "rh": "0.AQEAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAKM.",
  "sub": "ZKH5uGQB8tu8jVPpGrLaQix4jB-48vhRZeq_bp0UlB8",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "K5nPygRrTkeLBbPvhF80AA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-5.15.57.1-microsoft-standard-WSL2-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.39.0
```

**Comment by yonzhan** [comment] 2022-09-02 23:41
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2022-09-02 23:41 UTC
Labels: Account, customer-reported, Auto-Assign
