### ISSUE TITLE
Deployment validate wrong exit code

### ISSUE THREAD

**Issue by Satak** [Azure/azure-cli#10279] opened 2019-08-20 13:59 UTC
**CLI version**
2.0.62 / latest

**Describe the bug**
When you run `az group deployment validate` command against your ARM templates in for example CircleCI the CLI tool returns exit code 0 though you encountered an error and your json error response is not null. Same behavior is for Windows.

**To Reproduce**
Validate any invalid arm template with the AZ CLI tool with command `az group deployment validate --resource-group myRSGroup --template-file myTemplate.json --parameters @myTemplate.parameters.json` and check the exit code. It's always 0 no matter if the template passed or not.

**Expected behavior**
Expected to have other than 0 exit code for non-valid templates so those can be captured in CI/CD pipelines.

**Environment summary**
Docker, Windows workstation

**Comment by Juliehzl** [comment] 2019-09-02 09:20
@Satak Thanks for your feedback. We will improve this soon.

**Comment by Juliehzl** [comment] 2019-09-24 09:08
dupe of issue #5590

**Comment by Juliehzl** [comment] 2019-10-11 03:16
Blocked by service API. Have to move to next sprint.

**Comment by yonzhan** [comment] 2019-11-02 02:48
@Juliehzl  any feedback from service API ?

**Comment by Juliehzl** [comment] 2019-11-08 02:38
From API side, we need API version at lease v2019-08-01, which handle such 400 status code correctly. @hjhhh3000vitae @Tiano2017 Do you have any plan for upgrade api version?

**Comment by Tiano2017** [comment] 2019-11-08 18:42
@Juliehzl I'm a bit confused. what's the issue with service here and how does 2019-08-01 fix that?

**Comment by yonzhan** [comment] 2019-12-15 10:57
What is the status of this issue?

**Comment by zhoxing-ms** [comment] 2020-01-14 06:34
@Tiano2017 Because the SDK did not throw an exception when the status code of the Service returned is 400, so the exit code is 0 when the verification fails.
You can see here file:_deployments_operations.py function: validate_at_subscription_scope()
We solved the problem in azure-cli this time. Could you help to upgrade the exception handling of SDK later?

**Comment by Tiano2017** [comment] 2020-01-14 18:12
@zhoxing-ms The SDK is generated. Can you let me know what needs to change in swagger?

**Comment by zhoxing-ms** [comment] 2020-01-15 03:12
Please see here: [code link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_10_01/operations/_deployments_operations.py#L2898)
I think it might be better to change this to `if response.status_code not in [200]:`

**Closed** 2020-01-19 09:34 UTC
Labels: ARM
