### ISSUE TITLE
Issue: az upgrade bug

### ISSUE THREAD

**Issue by Mleng89** [Azure/azure-cli#24066] opened 2022-09-30 00:40 UTC
## Describe the bug

**Command Name**
`az extension update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 413, in update_extension
    _add_whl_ext(cli_ctx=cmd_cli_ctx, source=download_url, ext_sha256=ext_sha256,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 113, in _add_whl_ext
    raise CLIError('The extension {} already exists.'.format(extension_name))
knack.util.CLIError: The extension ml already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/extension/custom.py", line 34, in update_extension_cmd
    return update_extension(cli_ctx=cmd.cli_ctx, extension_name=extension_name, index_url=index_url,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 421, in update_extension
    shutil.copytree(backup_dir, extension_path)
  File "/usr/lib/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.9/shutil.py", line 467, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Running sandbox via `learn.microsoft.com` 
- Whilst in bash running command of `az upgrade` prompts the error listed above

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.40.0

Extensions:
ai-examples 0.2.5
ml 2.7.1
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-09-30 00:43
route to CXP team

**Comment by navba-MSFT** [comment] 2022-09-30 02:56
@Mleng89 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-09-30 07:28
@Mleng89 I tried running both the commands` az extension update -n ml` and `az upgrade`. It worked fine. I am unable to reproduce this issue.

Could you please confirm if you tried running this command ` az extension update -n ml` ?

As a workaround, Could you please delete the `ml `dir from this path _/usr/lib/python3.9/site-packages/azure-cli-extensions/ml_ in your box and install ml again using the command `az extension add -n ml` ? Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-10-03 04:40
@Mleng89 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-10-04 05:55
@Mleng89 Thanks for your reply. Did you try running the command with `sudo` ? 

>sudo rmdir "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml"

Please let me know if this helps. 

In the meantime, I am also checking with the AzCLI team, if there are any command switch / parameter available to _force upgrade_ and override the system level extension ? I will keep you posted.

**Comment by navba-MSFT** [comment] 2022-10-07 03:47
@Mleng89 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-10-10 04:37
@Mleng89 Did you get a chance to run the below command and then reinstall the extension and check if that helps ?

>sudo rmdir "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml"

> az extension add -n ml

Awaiting your reply.

**Comment by jiasli** [comment] 2022-10-12 06:00
Duplicate of #24023

**Comment by jiasli** [comment] 2022-10-12 06:00
This is Azure Cloud Shell, so the user should have no permission to run `rmdir "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml"` or `sudo`.

**Closed** 2022-10-12 06:03 UTC
Labels: bug, Machine Learning, customer-reported, needs-author-feedback, Upgrade, CXP Attention, Auto-Assign, Azure CLI Team
