### ISSUE TITLE
Mount path for windows - invalid characters?

### ISSUE THREAD

**Issue by dazinator** [Azure/azure-cli#11932] opened 2020-01-23 10:56 UTC
I am trying to add a path mapping - my container is a windows container not linux.
If I run the command I get back "Bad Request". If I add the --debug argument I can see that it doesn't like the --mount-path argument. I have tried various combinations like "C:/webstorage" and "/webstorage" and can't get anything to work. What is the correct syntax for this argument for windows and mounting to the C:/ drive somewhere?
&gt;
msrest.http_logger : Response content:
msrest.http_logger : {"Code":"BadRequest","Message":"The parameter 'AzureStoragePropertyDictionary' has an invalid value. Details: Mount path contains invalid characters. Please review documentation for a list of valid mount path characters..","Target":null,"Details":[{"Message":"The parameter 'AzureStoragePropertyDictionary' has an invalid value. Details: Mount path contains invalid characters. Please review documentation for a list of valid mount path characters.."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01033","MessageTemplate":"The parameter '{0}' has an invalid value. Details: {1}.","Parameters":["AzureStoragePropertyDictionary","Mount path contains invalid characters. Please review documentation for a list of valid mount path characters."],"Code":"BadRequest","Message":"The parameter 'AzureStoragePropertyDictionary' has an invalid value. Details: Mount path contains invalid characters. Please review documentation for a list of valid mount path characters.."}}],"Innererror":null}
msrest.exceptions : Operation returned an invalid status code 'Bad Request'
cli.azure.cli.core.util : Operation returned an invalid status code 'Bad Request'
Operation returned an invalid status code 'Bad Request'
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2580 in cache
telemetry.check : Negative: The C:\Users\DarrellTunnell\.azure\telemetry.txt was modified at 2020-01-23 10:43:00.920906, which in less than 600.000000 s
command ran in 6.148 seconds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4892bb1c-5cb4-91fa-325b-f5180cd05c3a
* Version Independent ID: 8c9a9a0e-5b36-4039-72c5-b28fd0bb9fd4
* Content: [az webapp config storage-account](https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/config/storage-account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/storage-account.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MaximeRastello** [comment] 2020-01-24 16:36
Same issue here using Az PowerShell module, please advise

**Comment by Rodske** [comment] 2020-01-25 11:43
--mount-path "\data" 
worked for me with Windows Containers in App Service

**Comment by MaximeRastello** [comment] 2020-01-27 09:46
> --mount-path "\data"
> worked for me with Windows Containers in App Service

Is "data" a subfolder of /site/home ?

**Comment by dazinator** [comment] 2020-01-27 12:59
> --mount-path "\data"
worked for me with Windows Containers in App Service

Assuming that maps to c:/data then that wouldnt work for mapping to other drives on windows such as D:/. 

I have an existing app service with c:/webstorage mapped - so this worked at some point previously, I'm concerned to know why it now does not, I.e it seems to be a regression

**Comment by Rodske** [comment] 2020-02-09 08:55
@dazinator & @MaximeRastello - Yes it would mount the share into c: as the folder name data. It's not creating a new drive for the mount.

**Comment by panchagnula** [comment] 2020-05-11 19:13
@vinisoto can you comment on this?

**Comment by vinisoto** [comment] 2020-05-11 19:44
Thanks for using Windows Containers.

Just tried and **--mountpath /webstorage** works for me (both in the Portal and CLI). There was a regression a few sprints back but it is working now.

cc @jvano

**Comment by dazinator** [comment] 2020-05-11 21:39
@vinisoto as per the original issue, the error I was seeing was when specifying a drive etc `--mountpath C:/webstorage`. This used to work as a mapping through the UI. Several weeks ago this stopped working in the UI for a while, and also fails through the CLI. It does work if I don't specify a drive e.g `--mountpath /webstorage` but that means you can't map to custom drives, only to subfolders of the default C drive. Is this a new intentional change or has this now been fixed?

**Comment by vinisoto** [comment] 2020-05-14 05:41
@dazinator behind the scenes we have only supported mounting in subfolders of C: all along (in fact, I believe that in the past if you specified something different than C: we showed an error message indicating that you had to specify C: as the root of your mount path). Because of that (and also to be consistent with how specify mount paths in Linux containers) we chose to remove the drive letter.

Is there a scenario in which you would need your mount path to be in a custom drive?

**Comment by dazinator** [comment] 2020-05-14 07:03
@vinisoto thank you, that finally explains the behaviour I was seeing.

The only scenarios for not wanting to mount under C drive that I can think of are:-

1. You are not sure whether a subfolder already exists under C for the mount path. I think if you mount into an existing non empty folder on windows it used to cause `docker run` to error with a not helpful message.

2. The applications running within the container use other drive paths by convention. For example they might expect E:\Backups. To stick to this convention you want to mount to E:\Backups rather than attempt to reconfigure the application.

**Comment by panchagnula** [comment] 2020-08-04 06:18
@vinisoto can we close this issue?

**Comment by vinisoto** [comment] 2020-08-04 14:11
I think we should close it. By design we won't be supporting custom drives for now.

**Comment by panchagnula** [comment] 2020-08-04 16:19
Thank @vinisoto closing the issue.

**Closed by panchagnula** 2020-08-04 16:19 UTC
Labels: Service Attention, Web Apps

**Comment by jvano** [comment] 2020-08-04 21:06
@dazinator  thanks for the feedback about the "E:\Backups" example.

I will add this into our backlog but as @vinisoto mentioned custom drives are not supported at this point.

**Comment by jvano** [comment] 2021-04-28 04:33
Just to let you all know that we recently made a fix to support custom drives. It will take few months for the change to be released and available worldwide.
