### ISSUE TITLE
az aks update-credentials failed

### ISSUE THREAD

**Issue by zsolt-bognar** [Azure/azure-cli#14393] opened 2020-07-16 08:48 UTC
## Describe the bug

**Command Name**
`az aks update-credentials`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update-credentials --resource-group {} --name {} --reset-service-principal --service-principal {} --client-secret {}`

## Environment Summary
```
Linux-4.15.0-1091-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.0

```

**Comment by yonzhan** [comment] 2020-07-16 10:57
aks

**Comment by yungezz** [comment] 2020-07-16 23:54
hi @zsolt-bognar did you meet the issue in Cloudshell? Could you pls try workaround with `az login`? This is a known Cloudshell issue #11749 .

**Comment by BellaLi** [comment] 2020-07-21 16:17
@zsolt-bognar 
When you see this error "400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token",  can you try "az login --identity" and paste the response here? Please also share the time that this error shows, so we can dig into our logs. Thank you.

**Comment by maertendMSFT** [comment] 2020-09-30 23:17
Ping on @zsolt-bognar  for @BellaLi 's request

**Comment by maertendMSFT** [comment] 2020-11-20 22:53
Can we close this as a dupe of: https://github.com/Azure/azure-cli/issues/11749

**Closed** 2020-11-21 02:24 UTC
Labels: Cloud Shell, Service Attention, customer-reported
