### ISSUE TITLE
Application gateway: http settings: --path option does not work

### ISSUE THREAD

**Issue by nagpal** [Azure/azure-cli#6679] opened 2018-06-28 10:29 UTC
**Describe the bug**
The --path option of app gateway http-settings does not work.

In the help, it says the value in --path option is prefixed to all HTTP requests. Currently this value seems to have no effect on the http request.

**To Reproduce**
1. Setup an app gateway
1. Create a listener to listen to a domain (listener1)
1. Create two http settings (httpsetting1 and httpsetting2) 
1. Create two backend pools (backend1 and backend2)
1. Create a path based rule with the following options:
    * Default listener: listener1
    * Default backend pool: backend1
    * Default http settings: httpsetting1
    * New configuration with name as 'assets-path', path as /asset/* , backend pool has backend2 and http setting as httpsetting2
1. Using azure cli, update the path option for httpsetting2 using this command:
`az network application-gateway http-settings update --resource-group <resource-group> --gateway-name <gateway-name> --name httpsetting2 --path "/baz/qux/"`

**Expected behavior**
When:  you request the resource (using the browser) through https://<domain-name>/asset/foo/bar (https or http, depending on what protocol is configured in listener1)
Expected: Then request should be forwarded to backend2 on path: /baz/qux/asset/foo/bar
Actual: The requested is routed to backend2 on path: /asset/foo/bar

The same actual behaviour is seen when the http-settings path is set to null (through resources.azure.com), "", "/" or "any-string-here"

**Environment summary**
Installed using brew:
OS: MacOS 10.13.5 (17F77)
az version: 
azure-cli (2.0.38)

acr (2.0.27)
acs (2.1.1)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.35)
backup (1.1.1)
batch (3.2.4)
batchai (0.3.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.14)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.16)
consumption (0.3.1)
container (0.1.24)
core (2.0.38)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.15)
feedback (2.1.2)
find (0.2.10)
interactive (0.3.23)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.7)
network (2.1.4)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.26)
rdbms (0.2.4)
redis (0.2.13)
reservations (0.2.0)
resource (2.0.31)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.34)

Python location '/usr/local/opt/python/bin/python3.6'
Extensions directory '/Users/vijay/.azure/cliextensions'

Python (Darwin) 3.6.5 (default, Jun 17 2018, 12:13:06)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by nagpal** [comment] 2018-07-12 10:46
Any update on this? It has been 2 weeks. Is it not a bug at all or is it low on the priority list?

**Comment by tjprescott** [comment] 2018-07-12 15:58
Based on your original post, it looked like a service issue. If you set the path through the portal, does the request forward as you expect it? If so, then the issue is with the CLI specifically.

**Comment by nagpal** [comment] 2018-07-17 07:03
Nope, even through the portal it does not give me an error but seems like the path option is not used at all in routing. Should I open the bug some place else?

**Comment by tjprescott** [comment] 2018-07-17 16:11
If it doesn't work when set through the portal then it is a service bug, not a CLI issue. You can open a support request through the portal to get the issue routed to the service team. That would be the quickest way to get resolution.

I will keep this issue open as it will eventually be assigned to the service team based on its labels, but my recommendation would be to open the support request in the portal.

**Comment by MyronFanQiu** [comment] 2019-08-19 09:45
@akshaysngupta Any update on this issue?

**Closed** 2019-12-22 04:58 UTC
Labels: Network - Application Gateway, Network-cli, ServiceAttn
