### ISSUE TITLE
`az resource show`: CLI 2.0 command provided in "Resource Explorer" does not work

### ISSUE THREAD

**Issue by maaren** [Azure/azure-cli#6475] opened 2018-06-01 11:05 UTC
**Describe the bug**
When I cut'n paste the Azure CLI v2.0 command from https://resources.azure.com/subscriptions I get:
$ az resource show --id /subscriptions/deadbeaf-1111-2222-3333-666666666666/resources --api-version 2017-05-10
az resource: error: argument --ids: invalid ResourceId value: '/subscriptions/deadbeef-1111-2222-3333-666666666666/resources'

**To Reproduce**
Login to https://resources.azure.com/ 
Under subscriptions click on resources
Cut'n paste the command from the Azure CLI v2.0 tab

**Expected behavior**
I expect to receive the same json as in data tab of https://resources.azure.com

**Environment summary**
rpm fedora 28 install:
```
# rpm -qf /bin/az
azure-cli-2.0.33-1.el7.x86_64
```

**Comment by tjprescott** [comment] 2018-06-01 15:38
The ID in that example is fictitious. There is no value that can be put there that is "cut and paste"-able. You would need to supply your own ID for some Azure resource.

**Comment by maaren** [comment] 2018-06-01 16:07
It did not seem like a good idea to me to post the real ID to a public forum. Did you actually try to reproduce it?

**Comment by tjprescott** [comment] 2018-06-01 17:07
Sorry, I misunderstood the issue. I thought you cut and paste an example by running `az resource show -h` which most often can't be simply pasted in.

**Comment by tjprescott** [comment] 2018-06-01 17:14
The question would be whether that ID (which is rejected by msrestazure as invalid) is accepted by the REST API or whether resource explorer is interpreting it and doing some "extra stuff".  If it's the former, then we should definitely fix the ID parsing in msrestazure to support the scenario.  If the latter, then we would have to decide whether to copy the feature or not.

**Comment by maaren** [comment] 2018-06-01 17:22
No worries, I guess I could have been clearer. Are you able to reproduce this?

**Comment by tjprescott** [comment] 2018-06-01 17:29
Yes, I can reproduce the behavior and have confirmed that the REST API supports this ID.  We'll have to fix the issue in msrestazure that is blocking this.  There may be an additional fix in the CLI. Thanks for the report!

**Comment by tjprescott** [comment] 2018-06-01 17:40
@yugangw-msft another alternative would be to simply detect this special-case ID type and not put it through the parser.  What do you think?  The format is:

/subscriptions/{subscription-id}[/resourceGroups/{rg}]/resources

**Comment by yugangw-msft** [comment] 2018-06-01 22:14
@tjprescott , agreed we can detect this case. After that, shall we error out, or redirect to `ResourcesOperations.list_by_resource_group`?

**Comment by maaren** [comment] 2018-06-04 07:39
Not sure if it helps, but powershell has the same issue in the latest AzureRM (6.1.1). This was working in 5.5.0.

**Comment by williexu** [comment] 2018-06-04 18:59
The same would happen if one tried to do a `resource show` on `/subscriptions/00977cdb-163f-435f-9c32-00000000000/providers/Microsoft.Storage/storageAccounts`

While this and `/subscriptions/deadbeaf-1111-2222-3333-666666666666/resources` are valid ARM IDs, they do not refer to specific ARM resources.

**Comment by tjprescott** [comment] 2018-06-04 19:07
I would argue we not error out, but simply detect these special-case IDs and pass them along. I think it would be too much work to try and "redirect" the user to different commands. It seems that there is (potentially) some additional metadata that the resource show command might expose that the corresponding list command does not.

**Comment by tjprescott** [comment] 2018-06-04 19:12
We would need to fix this in msrest, imo, if this form of ID was accepted anywhere an ARM ID could be supplied. I doubt that this is the case. If it is only interpreted by the ARM resource endpoints, then I believe we should just adjust the custom command in the CLI.

**Comment by williexu** [comment] 2018-06-04 20:01
Even the resource sdk docs expect a id to be given for a specific ARM resource:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/operations/resources_operations.py#L1222

Anything other than a ARM resource id should be unknown territory.

**Comment by adewaleo** [comment] 2019-04-09 18:45
@tjprescott @yugangw-msft, what is our consensus on this? Do we want to permit this type of ID or not?

**Comment by tjprescott** [comment] 2019-04-09 19:12
I would say no. The Azure CLI script tab was removed because the scripts in it were not actually verified to work. The resource explorer cannot make statements about what the CLI command should do, but should instead rely on what the CLI does. Since the type of ID does not work in the CLI, it should never have appeared in the Resource Explorer. I would recommend closing this.

**Comment by adewaleo** [comment] 2019-04-09 19:48
Thanks @tjprescott. This all makes sense.

I will close this issue

**Closed by adewaleo** 2019-04-09 19:48 UTC
Labels: Discussion, Resource Manager-cli
