### ISSUE TITLE
az webapp up - from inside Visual Studio Code dev container

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#22256] opened 2022-05-03 14:29 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 1] Operation not permitted: '/workspace/.azure/config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/appservice/commands.py", line 39, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 4400, in webapp_up
    _set_webapp_up_default_args(cmd, rg_name, sku, plan, loc, name)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 4410, in _set_webapp_up_default_args
    cmd.cli_ctx.config.set_value('defaults', 'group', rg_name)
  File "/opt/az/lib/python3.8/site-packages/knack/config.py", line 155, in set_value
    self._config_file_chain[0].set_value(section, option, value)
  File "/opt/az/lib/python3.8/site-packages/knack/config.py", line 240, in set_value
    self.set(config)
  File "/opt/az/lib/python3.8/site-packages/knack/config.py", line 229, in set
    os.chmod(self.config_path, stat.S_IRUSR | stat.S_IWUSR)
PermissionError: [Errno 1] Operation not permitted: '/workspace/.azure/config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --location {} --name {} --sku {} --resource-group {} --verbose`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Debian GNU/Linux 11 (bullseye)
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
application-insights 0.1.16
account 0.2.3

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```
## Additional Context

Full console.log

```
node ➜ /workspace $ az webapp up --location westus3 --name diberry-02 --sku F1 --resource-group learn-c0aaef7e-604f-4a00-9f38-0b49d907d501 --verbose
Configured default 'js-rentals-284134351' for arg name
Configured default 'js-rentals-284134351' for arg resource_group_name
Configured default 'diberry_asp_Linux_westus3_0' for arg plan
Configured default 'westus' for arg location
The webapp 'diberry-02' doesn't exist
Found sku argument, skipping use default sku
Creating AppServicePlan 'diberry_asp_Linux_westus3_0' ...
Creating webapp 'diberry-02' ...
will set appsetting for enabling build
Configuring default logging for the app, if not already enabled
Creating zip with contents of dir /workspace ...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
Fetching changes.
Fetching changes.
Fetching changes.
Fetching changes.
Fetching changes.
Running oryx build...
Running oryx build...
Running oryx build...
Running oryx build...
Running oryx build...
Running oryx build...
Running oryx build...
Running oryx build...
Running oryx build...
Running oryx build...
Fetching changes.
You can launch the app at http://diberry-02.azurewebsites.net
Setting 'az webapp up' default arguments for current directory. Manage defaults with 'az configure --scope local'
The command failed with an unexpected error. Here is the traceback:
[Errno 1] Operation not permitted: '/workspace/.azure/config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/appservice/commands.py", line 39, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 4400, in webapp_up
    _set_webapp_up_default_args(cmd, rg_name, sku, plan, loc, name)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 4410, in _set_webapp_up_default_args
    cmd.cli_ctx.config.set_value('defaults', 'group', rg_name)
  File "/opt/az/lib/python3.8/site-packages/knack/config.py", line 155, in set_value
    self._config_file_chain[0].set_value(section, option, value)
  File "/opt/az/lib/python3.8/site-packages/knack/config.py", line 240, in set_value
    self.set(config)
  File "/opt/az/lib/python3.8/site-packages/knack/config.py", line 229, in set
    os.chmod(self.config_path, stat.S_IRUSR | stat.S_IWUSR)
PermissionError: [Errno 1] Operation not permitted: '/workspace/.azure/config'
To open an issue, please run: 'az feedback'
Command ran in 95.517 seconds (init: 0.125, invoke: 95.392)
```

**Comment by SaurabhSharma-MSFT** [comment] 2022-05-03 17:07
@diberry We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment] 2022-05-03 23:11
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2022-05-05 21:28
@diberry I not able to reproduce this and the command works as expected - 
![image](https://user-images.githubusercontent.com/38112130/167028176-7279aeea-daca-434d-991a-b74e90126ebf.png)
Can you please try running only `az` command and check if are getting any errors.
 If you get any errors then run `sudo rm ~/.azure/commandIndex.json` and then try `az` command.  Please let me know if you still any problems. Thanks.
Saurabh

**Comment by SaurabhSharma-MSFT** [comment] 2022-05-12 13:27
@diberry We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-05-12 13:27 UTC
Labels: Web Apps, needs-author-feedback, CXP Attention, Auto-Assign
