### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.mgmt.botservice' on `az bot` commands

### ISSUE THREAD

**Issue by jbeard4** [Azure/azure-cli#7448] opened 2018-10-01 03:48 UTC
**Describe the bug**

I get an error `ModuleNotFoundError: No module named 'azure.mgmt.botservice'` on `az bot publish` and `az bot download` commands.

**To Reproduce**

Download and install azure-cli with homebrew according to instructions [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest).

Login with `az login`, succeeds.

Add botbuilder extension with `az extension add -n botservice` according to instructions [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-download-source-code?view=azure-bot-service-4.0).

Try to download existing botbuilder application according to instructions [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-download-source-code?view=azure-bot-service-4.0#download-code-usubg-azure-cli):

`az bot download --name "my-bot-name" --resource-group "my-bot-resource-group"`

I get an error and stack trace:

```
No module named 'azure.mgmt.botservice'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 262, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 253, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 141, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jbeard4/.azure/cliextensions/botservice/azext_bot/custom.py", line 11, in <module>
    from azure.mgmt.botservice.models import Bot, BotProperties, Sku
ModuleNotFoundError: No module named 'azure.mgmt.botservice'
```

I also tried publishing my bot with the following according to instructions [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-download-source-code?view=azure-bot-service-4.0#publish-code-using-azure-cli), and got the same error:

`az bot publish --name "my-bot-name" --resource-group "my-bot-resource-group" --code-dir .`

**Expected behavior**
The `az bot download` command should download the bot application source code from azure.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Install method: homebrew
Shell type: bash
OS version: OS X 10.12 Sierra
CLI version:

```
azure-cli (2.0.46)

acr (2.1.5)
acs (2.3.4)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.4)
backup (1.2.1)
batch (3.4.0)
batchai (0.4.3)
billing (0.2.0)
botservice (0.1.1)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.4)
core (2.0.46)
cosmosdb (0.2.1)
dla (0.2.3)
dls (0.1.3)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.2.4)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.30)
iot (0.3.2)
iotcentral (0.1.2)
keyvault (2.2.3)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.5)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.4)
role (2.1.5)
search (0.1.1)
servicebus (0.2.3)
servicefabric (0.1.3)
signalr (1.0.0)
sql (2.1.4)
storage (2.2.2)
telemetry (1.0.0)
vm (2.2.3)

Extensions:
botservice (0.4.1)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/jbeard4/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Sep 18 2018, 18:47:29) 
[Clang 9.0.0 (clang-900.0.39.2)]

```

**Additional context**
I tried relinking python according to the instructions [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest#unable-to-find-python-or-installed-packages). Relinking succeeded, but the above error persists.

**Comment by troydai** [comment] 2018-10-01 16:27
Acknowledge. Looking at it.

**Comment by jbeard4** [comment] 2018-10-01 16:27
Thank you.

**Comment by troydai** [comment] 2018-10-01 17:20
Found the cause of it. It was a homebrew specific issue. I will create a PR soon to address this issue. IT will be fixed in the next release (https://github.com/Azure/azure-cli/milestone/48) due 10/9.

**Comment by jbeard4** [comment] 2018-10-01 17:42
Great. Thank you, Troy.

**Comment by troydai** [comment] 2018-10-01 18:11
You're welcome. Thank you for taking time to open this issue.

**Closed** 2018-10-01 20:30 UTC
Labels: BotService, Question
