### ISSUE TITLE
Line number is always 1

### ISSUE THREAD

**Issue by Peter-Optiway** [Azure/azure-cli#9142] opened 2019-04-18 09:34 UTC
## Describe the bug
When i try to validate my templates i always get 1 as line number,  "at line '1' and column '16535'" it not helpful i have tried with both windows and linux line endings.

**Command Name**
`az group deployment validate`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Run: az group deployment validate -g {} --template-file {} --parameters {} --output {} --subscription {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62

```

**Comment by tjprescott** [comment] 2019-04-19 17:57
Can you provide the actual error returned and/or upload a sample of your template (with any sensitive info removed).

**Comment by tjprescott** [comment] 2019-04-19 17:59
When I intentionally mess up a template file, I will get correct line numbers for JSON format errors, but ARM template errors do always say line 1. I think that is because the template is serialized when sent to the service and thus does not retain any concept of "line numbers". In that case, the service team would need to address this.

**Comment by ifeoluwaokunoren** [comment] 2019-09-20 22:31
@fidorz & @alex-frankel can you please address this issue - thank you.

**Comment by alex-frankel** [comment] 2019-09-24 23:34
As of CLI version 2.0.74 this has been fixed. It is not the default behavior, but you can use the `--handle-extended-json-format` flag to send the ARM template unmodified which will preserve the line numbers and positions and you will get more helpful information back.

Once we verify this is working as intended, this will become the default behavior.

Closing this since users are now unblocked

**Closed by alex-frankel** 2019-09-24 23:34 UTC
Labels: ARM, ARM - Templates, Question, Service Attention
