### ISSUE TITLE
A few fellow SEs informed me az vm repair restore took 20-30 minutes to complete on a few occasions

### ISSUE THREAD

**Issue by rjmccallumbigl** [Azure/azure-cli#19153] opened 2021-08-06 22:01 UTC
### Extension name (the extension in question)
az vm repair

### Description of issue (in as much detail as possible)

- Received 2 recent reports from other Support Engineers that running `az vm repair restore` took 20-30 minutes to complete for them.
- The hold us was after running the command and before asking if they wanted to do the cleanup on the repair VM.
- Tried to repro 3 times using 0.3.5 and 0.3.6 but the restore command took less than 100 seconds each time I tried.
- Thought I should post here just in case this can be investigated and if anything, for further guidance. 
- I believe this operation is using the OS disk swap API so could the hold up be in calling `az vm disk detach` or  `az vm update -g $rg -n $name --os-disk $osDiskName`?
- Are there any recommendations we can make to speed this operation up? Should the Rescue VM generally be shut down/deallocated prior to running the restore operation? Anything we should check for prior to running the restore operation? Thanks!

- Case 1:
  - OS disk size (GB): 32
  - OS disk type (HDD? SDD?): Premium SSD
  - OS version: Rhel 8 
  - Region: Westus
  - Size: Standard_DS1_v2
  - Commands:
    - `az vm repair create --verbose -g Perfab -n ALAR1 --repair-username rescue --repair-password <REDACTED>`
    - `az vm repair run --verbose -g Perfab -n ALAR1 --run-id linux-alar-fki --parameters fstab --run-on-repair`
    - `az vm repair restore -n ALAR1 -g Perfab --verbose  `
- Case 2:
  - OS disk size (GB): 30 GiB
  - OS disk type (HDD? SDD?): Standard HDD
  - OS version: Canonical Ubuntu 18.04-LTS
  - Region: North Central US

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355a594a-22ef-fd15-0b58-07701dd1815c
* Version Independent ID: d8356a0a-9aaf-900b-ce7a-021c9a0af509
* Content: [az vm repair](https://docs.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest#ext-vm-repair-az-vm-repair-create)
* Content Source: [latest/docs-ref-autogen/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vm/repair.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2021-08-07 00:26
route to service team

**Comment by zhoxing-ms** [comment] 2021-08-07 11:04
@malachma Could you please help to have a look at this issue?

**Comment by malachma** [comment] 2021-08-10 10:37
The restore operation is part of the normal 'vm repair' extension. The ALAR scripts don't have any side effects.
What I can imagine is that, due to the os-disk-swpa operation. Any running VM needs to be shutdown first. This shutdown operation may take sometime sometimes. As described in the report the issue was not be able to be reproduced. It could be therefore that there was a temporary issue in one specific location that may have prevented to get the VMs shutdown and started again. Another point to investigate is whether the VM to be recovered used managed disks or unmanaged disks. The restore logic is different for both types. Maybe there was also a resource constrain , which allowed the right VM size not to be allocated immediately.

**Comment by Vaibhav-Agar** [comment] 2021-08-12 17:20
Hi @rjmccallumbigl , as this seems to be a transient issue which we are not able to reproduce, I am going to close it for now. If you do encounter this again, please feel free to reopen.

**Closed by Vaibhav-Agar** 2021-08-12 17:20 UTC
Labels: Compute, Service Attention, customer-reported
