### ISSUE TITLE
webapp: Multi- container quickstart is broken from CLI

### ISSUE THREAD

**Issue by SnehaAgrawal-MSFT** [Azure/azure-cli#14208] opened 2020-07-03 07:30 UTC
Bug Description:
 
Multi-container [quickstart](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-multi-container) is broken from CLI 

![image](https://user-images.githubusercontent.com/46553948/86443490-f7b0ef00-bd2c-11ea-9ecd-76511edc9650.png)

 Reproduced:
    This has been reproduced by trying two different compose YML files and got the same result. 
   Portal -> container settings shows strange characters (see screenshots).
  
   
![image](https://user-images.githubusercontent.com/46553948/86440327-e4e7eb80-bd27-11ea-97c6-13fcfa0fbe3c.png)

Expected behavior:
 As this is working fine from portal but CLI should work correctly.

**Comment by yonzhan** [comment] 2020-07-03 13:17
Was this a portal bug or CLI issue?

**Comment by yungezz** [comment] 2020-07-04 07:37
this looks like a portal bug instead of Azure CLI bug. hi @SnehaAgrawal-MSFT the screencut resolution is low, I cannot see the scirpt on it. while the flow hasn't been in Azure CLI yet. It's portal logic to show the script. This should not be a Azure CLI bug.

**Comment by willson556** [comment] 2020-07-06 01:13
@yungezz, @yonzhan I've run into the same problem and I also believe this is a CLI issue.

I ran:
```bash
az webapp config container set --resource-group <rg> --name <webapp> --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml
```
and had a YAML parse exception like @SnehaAgrawal-MSFT. The configuration appeared to be improperly encoded in the portal. I then pasted the configuration into the portal and saved. The configuration was then correctly parsed and the app deployed.

**Comment by yungezz** [comment] 2020-07-06 01:41
thanks @willson556 for the detail! could you pls paste the error messages? thanks.

**Comment by willson556** [comment] 2020-07-06 05:28
Yeah, the error in the container logs was:
```
2020-07-06T01:01:37.141Z INFO  - Starting multi-container app..
2020-07-06T01:01:37.142Z ERROR - Exception in multi-container config parsing: YamlException: (Line: 6, Col: 1, Idx: 255) - (Line: 6, Col: 1, Idx: 255): While scanning a simple key, could not find expected ':'.
2020-07-06T01:01:37.142Z ERROR - Start multi-container app failed
```

Also, my cloud shell session history seems to have cleared but the output of the command contained something like:
```
"COMPOSE|<some encoded string approximately the length of the YAML file>"
```

**Comment by panchagnula** [comment] 2020-07-06 18:20
@Kotasudhakarreddy could you please check if you can repro this using CLI. Seems like CLI is incorrectly parsing some values. We can chat more on this during our meeting.

**Comment by IntoTheNature** [comment] 2020-07-07 17:36
I can reproduce this issue. Seems like a CLI issue: base64-encoded file gets lowercased. 
I have az cli 2.7 and 2.8 next to each other:
2.8 lowercases the file content while 2.7 doesn't.

**Comment by panchagnula** [comment] 2020-07-07 18:26
@IntoTheNature thanks for comment are you saying that if you use version 2.7 - you don't see this problem on portal?

**Comment by IntoTheNature** [comment] 2020-07-07 19:15
> @IntoTheNature thanks for comment are you saying that if you use version 2.7 - you don't see this problem on portal?

That is correct, the base64 isn't lowercased in the command output:
This is a screenshot of 2.0.75:
![image](https://user-images.githubusercontent.com/2073524/86829848-e9334200-c062-11ea-873d-e5e41470185b.png)
Same file on 2.8.0:
![image](https://user-images.githubusercontent.com/2073524/86831176-93f83000-c064-11ea-85c7-3f46d6878504.png)

(pay attention to lowercased DOCKER_CUSTOM_IMAGE_NAME value)

**Comment by panchagnula** [comment] 2020-07-07 20:43
This seems like it regressed with this change https://github.com/Azure/azure-cli/commit/728301a9ebda73ce57ad6440254323af260fa5c5#diff-75a1767a60b87df72982d626136921db

@vinisoto can you please take care of fixing the regression in Linux - i want to make sure we don't regress your windows container fix while trying to fix the regression. Thanks!

**Comment by vinisoto** [comment] 2020-07-07 20:45
Looking at it

**Comment by panchagnula** [comment] 2020-07-10 16:33
Closing since this is now merged & will release with the upcoming release

**Closed** 2020-07-10 16:33 UTC
Labels: Service Attention, Web Apps
