### ISSUE TITLE
az interactive failed to load

### ISSUE THREAD

**Issue by jishnudantu** [Azure/azure-cli#12836] opened 2020-04-01 21:25 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
cannot import name 'ENV_ADDITIONAL_USER_AGENT'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 625, in execute
    raise ex
cli/core/commands/__init__.py, ln 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 682, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 31, in <module>
    from azure.cli.core.commands.client_factory import ENV_ADDITIONAL_USER_AGENT
ImportError: cannot import name 'ENV_ADDITIONAL_USER_AGENT'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-5.3.0-42-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment] 2020-04-01 23:18
interactive

**Comment by jiasli** [comment] 2020-04-02 03:59
Duplicate of #12837

**Closed by jiasli** 2020-04-02 03:59 UTC
Labels: Feature Request, Interactive, Service Attention

**Comment by jiasli** [comment] 2020-04-02 04:08
Duplicate of https://github.com/Azure/azure-cli-extensions/issues/1480
