### ISSUE TITLE
Issue with az autoscale command

### ISSUE THREAD

**Issue by hmundeepi** [Azure/azure-cli#11307] opened 2019-11-19 04:42 UTC
## Describe the bug

**Command Name**
`az monitor autoscale rule list`

**Errors:**
```
Traceback (most recent call last):
Temp\pip-install-umfcm_n2\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 652, in _run_job
azure\cli\command_modules\monitor\_exception_handler.py, ln 27, in monitor_exception_handler
Local\Temp\pip-install-umfcm_n2\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
cli\command_modules\monitor\operations\autoscale_settings.py, ln 341, in autoscale_rule_list
StopIteration
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor autoscale rule list --autoscale-name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment] 2019-11-19 08:17
@MyronFanQiu please take a look.

**Comment by MyronFanQiu** [comment] 2019-11-21 03:07
@hmundeepi Hello. I cannot reproduce the error. Could you run the command with `--debug` and paste the error information?

**Comment by MyronFanQiu** [comment] 2019-12-30 05:32
@hmundeepi I closed this issue since it's out of date. If you still meet this error, don't hesitate and feel free to open a new one.

**Closed by MyronFanQiu** 2019-12-30 05:32 UTC
Labels: Monitor, Monitor - Autoscale
