### ISSUE TITLE
--custom-domain-https-parameters

### ISSUE THREAD

**Issue by jeffreydahan** [Azure/azure-cli#10995] opened 2019-10-27 09:13 UTC
Is there an example for how this parameter should be structured?  We are using a mix of customer provided and CDN managed (depending on the endpoint), so an example of each would be greatly appreciated.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8c61db-b294-77fb-0e92-eae01d07b776
* Version Independent ID: 958b6e8d-609b-2a58-dbe1-240d3fd894bb
* Content: [az cdn custom-domain](https://docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2019-10-27 11:14
@jiasli add to S162.

**Comment by jiasli** [comment] 2019-12-11 05:59
+CDN module owner @hytao. 

[`az cdn custom-domain enable-https`
](https://docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest#az-cdn-custom-domain-enable-https) directly [maps to](https://github.com/Azure/azure-cli/blob/a3ed6f76283c040bc38d24458f9bf79ecfb046da/src/azure-cli/azure/cli/command_modules/cdn/commands.py#L108) Python SDK's [`enable_custom_https`](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cdn/azure-mgmt-cdn/azure/mgmt/cdn/operations/_custom_domains_operations.py#L482) which takes arg `custom_domain_https_parameters` of type `azure.mgmt.cdn.models.CustomDomainHttpsParameters`. However, neither Azure CLI, Python SDK or msrest supports JSON string. The functionality is currently broken. We will fix it asap.

**Comment by timja** [comment] 2020-01-22 14:36
@hytao any news on this?

**Comment by lsmith130** [comment] 2020-01-28 19:06
Closing as a duplicate of #9894

**Closed by lsmith130** 2020-01-28 19:06 UTC
Labels: Bug, CDN, Service Attention
