### ISSUE TITLE
az login --use-device-code error

### ISSUE THREAD

**Issue by Cemlyn** [Azure/azure-cli#16007] opened 2020-11-21 14:27 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
local variable 'code' referenced before assignment
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-s90ugolk\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 717, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 710, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-7f66x3i5\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-_1bqfhco\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\profile\custom.py, ln 158, in login
pip-unpacked-wheel-_1bqfhco\azure\cli\core\_profile.py, ln 202, in find_subscriptions_on_login
pip-unpacked-wheel-_1bqfhco\azure\cli\core\_profile.py, ln 889, in find_through_interactive_flow
UnboundLocalError: local variable 'code' referenced before assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.15.0

```

**Comment by yonzhan** [comment] 2020-11-21 14:40
az login

**Comment by jiasli** [comment] 2020-11-23 02:14
Duplicate of #15961

**Closed by jiasli** 2020-11-23 02:14 UTC
Labels: Account
