### ISSUE TITLE
Offline error text is not user-friendly

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#980] opened 2016-09-26 14:00 UTC
call az vm list -g myvms while offline

Expected: one-line error message
Actual:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token?api-version=1.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106728350>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
Traceback (most recent call last):
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/azure/cli/main.py", line 35, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/azure/cli/core/application.py", line 120, in execute
    result = expanded_arg.func(params)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 229, in _execute_command
    result = operation(client, **kwargs) if client else operation(**kwargs)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/azure/cli/command_modules/vm/custom.py", line 136, in list_vm
    return list(vm_list)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/msrest/paging.py", line 60, in __iter__
    for i in self.next():
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/msrest/paging.py", line 92, in next
    self._response = self._get_next(self.next_link)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/azure/mgmt/compute/operations/virtual_machines_operations.py", line 546, in internal_paging
    request, header_parameters, **operation_config)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/msrest/service_client.py", line 167, in send
    session = self.creds.signed_session()
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/azure/cli/core/adal_authentication.py", line 21, in signed_session
    scheme, token = self._token_retriever()
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 230, in <lambda>
    username_or_sp_id, account[_TENANT_ID], resource)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 349, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, CLIENT_ID)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/authentication_context.py", line 106, in acquire_token
    return self._acquire_token(token_func)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/authentication_context.py", line 89, in _acquire_token
    return token_func(self)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/authentication_context.py", line 104, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/token_request.py", line 350, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/cache_driver.py", line 182, in find
    is_resource_tenant_specific)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/cache_driver.py", line 168, in _refresh_entry_if_necessary
    return self._refresh_expired_entry(entry)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/cache_driver.py", line 146, in _refresh_expired_entry
    token_response = self._refresh_function(entry, None)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/token_request.py", line 138, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/token_request.py", line 342, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/adal/oauth2_client.py", line 260, in get_token
    verify=self._call_context.get('verify_ssl', None))
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/burtb/repos/envs/pypi/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token?api-version=1.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106728350>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by derekbekoe** [comment] 2016-09-26 14:35
Duplicate of https://github.com/Azure/azure-cli/issues/949?

**Comment by derekbekoe** [comment] 2016-09-26 17:45
Closing this. Reopen if you don't think it's a duplicate.

**Closed by derekbekoe** 2016-09-26 17:45 UTC
