### ISSUE TITLE
Progress bar fails to show 100% for az storage blob upload with az_cli 2.34.1

### ISSUE THREAD

**Issue by jaianshu12** [Azure/azure-cli#21781] opened 2022-03-24 05:55 UTC
**Description**
Command: az storage blob upload --file filename -c container_name --account-name stg_acc_name

The progress bar does not show 100% completion when a file of large size is being uploaded (~1GB) even though it is seen file is uploaded to storage account. It reaches to aroung 99.6% and the just ends. Also noted that progess bar completion to 100% is seen with lower version of az_cli i.e. 2.32.0. 

Please note that we have tried upload with az_copy but we saw performact of  az storage blob upload is much faster than az_copy.  So we plan to use  "az storage blob upload".

**To Reproduce**
1. Get a file of size 1GB or more.
2. Check az cli version (az --version).
3. Set the env variable "AZURE_STORAGE_KEY" (Get it from access key of storage account).
4. az storage blob upload --file <filename> -c <container_name> --account-name <stg_acc_name>
5. Check Progess Bar while the data is being uploaded.

**Expected behavior**
Progress Bar should show 100%  upon completion.

**Environment summary**
az_cli 2.34.1

**Comment by yonzhan** [comment] 2022-03-24 06:59
storage

**Comment by jaianshu12** [comment] 2022-03-28 11:14
Is there any way we can get to know that file is uploaded completely via az-cli instead of relying on progess bar? What would be the best mechanism to do that?

**Comment by evelyn-ys** [comment] 2022-03-29 01:32
You can use `az storage blob show` to check if it exists and even its size

**Comment by calvinhzy** [comment] 2022-03-29 04:16
This seems to be an SDK issue. You would also see the progress bar jumping around occasionally. The upload_stream_current returned is not thread safe. 
Potential area of issue
https://github.com/Azure/azure-sdk-for-python/blob/c0d46894e17111d4bbf2c5efab11eb261e46444c/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py#L255-L262
https://github.com/Azure/azure-sdk-for-python/blob/c0d46894e17111d4bbf2c5efab11eb261e46444c/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py#L195-L200

**Comment by navba-MSFT** [comment] 2022-03-29 07:22
Adding Service team to take a look into this.

**Comment by jaianshu12** [comment] 2022-03-30 04:52
> https://github.com/Azure/azure-sdk-for-python/blob/c0d46894e17111d4bbf2c5efab11eb261e46444c/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py#L255-L262

Thanks [navba-MSFT] for adding service team. 
Just heads up, issue occurs when you try to upload a file of large size(~1GB or more) only. Small uploads works fine. And on 2.32.0 issue is not seen.

> You can use `az storage blob show` to check if it exists and even its size
Thanks [evelyn-ys]

**Comment by jaianshu12** [comment] 2022-04-05 09:08
Hello MSFT Service team, 
Do you have any update on this?

**Comment by jalauzon-msft** [comment] 2022-04-11 17:42
Hi @jaianshu12 Anshul, sorry for the delay. This has been identified as an SDK issue and is being tracked here: https://github.com/Azure/azure-sdk-for-python/issues/23934.

Once it's fixed in the SDK, CLI will also have to make some changes to support the fix.

**Comment by jaianshu12** [comment] 2022-04-13 04:13
Thanks for the heads up. @jalauzon-msft

**Closed** 2022-05-18 08:38 UTC
Labels: Storage, Service Attention, customer-reported, Auto-Assign

**Comment by igorpupkinable** [comment] 2023-03-25 11:27
I faced this issue while downloading disk snapshot. Progress was stuck at 99.9870% on every download attempt.

Steps to reproduce:
1. Create a snapshot of Linux VM disk (30GB standard HDD).
2. Allow public network access  in Networking settings
3. Restrict access to Azure AD accounts in Export settings
4. Generate download URL
5. `az login --use-device-code` in terminal
6. `az storage blob download --file vms/test.vhd --blob-url "https://md-mxxqhzfhr54w.z7.blob.storage.azure.net/<generated URL>" --auth-mode login --verbose`

**Expected:**
- VHD is downloaded at 100% progress
- Azure CLI finishes execution successfully

**Actual:**
- VHD seems to be downloaded
- progress stuck at 99.9870%
- Azure CLI hangs until generated URL expires

**Azure CLI version:**
```
azure-cli                         2.46.0
core                              2.46.0
telemetry                          1.0.8

Extensions:
account                            0.2.4

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/xxx/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Mar  6 2023, 09:39:14) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.
```

**Terminal output:**
```
Alive[############################################################### ]  99.9870%
Request URL: 'https://md-mxxqhzfhr54w.z7.blob.storage.azure.net/4mvxxrzzxwmx/abcd?snapshot=REDACTED&sv=REDACTED&sr=REDACTED&si=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'If-Match': '"0x8DB2BB5BD48EEFD"'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.12.0 Python/3.10.10 (Linux-5.19.0-35-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': REDACTED'
    'Authorization': 'REDACTED'
No body was attached to the request
Response status: 403
Response headers:
    'Content-Length': '544'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-error-code': 'REDACTED'
    'x-ms-request-id': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Date': 'Fri, 24 Mar 2023 18:33:58 GMT'

Unable to stream download: HTTPSConnectionPool(host='md-mxzqhzfhr54w.z7.blob.storage.azure.net', port=443): Read timed out.
Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.
                    
Command ran in 80431.771 seconds (init: 0.414, invoke: 80431.358)
```
