### ISSUE TITLE
az group exists does not return false

### ISSUE THREAD

**Issue by dalehhirt** [Azure/azure-cli#8594] opened 2019-02-20 23:22 UTC
**Describe the bug**
When calling az group exists, if the group does not exist, it does not return false, it lists the error.

e.g. 

Operation failed with status: 'Forbidden'. Details: 403 Client Error: Forbidden for url: https://management.azure.com/subscriptions/cd29b01d-2308-4a33-b27f-45629ebac41a/resourcegroups/msvce-production-v1?api-version=2018-05-01

**To Reproduce**
az group exists -g <non-existent group>

**Expected behavior**
It should swallow any error and return false.

**Environment summary**
interactive on powershell
version 2.0.58

**Additional context**

**Comment by tjprescott** [comment] 2019-02-21 00:03
I just ran `az interactive` on PowerShell and it worked as expected. 

![image](https://user-images.githubusercontent.com/5723682/53133716-f6609700-3528-11e9-8261-de986750da66.png)

**Comment by tjprescott** [comment] 2019-02-21 00:03
The error you are seeing looks like it may affect more than just that one command. Can you create or list resource groups?

**Comment by richl10x** [comment] 2019-04-02 10:14
I'm also experiencing this problem, running azure CLI commands in Devops Deployment tasks:

if (az group exists -g $(resourceGroupName) )
{
    az group delete -n $(resourceGroupName) -y
}

returns: 
Resource group '<myresourcegroupname>' could not be found.

should return:
false

environment info:
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 3.1.23

**Comment by tjprescott** [comment] 2019-04-26 20:51
@dalehhirt I cannot repro your issue, though it seems like you hit a transient server issue. @richl10x you get "Resource group '' could not be found" because the delete command is called. The reason is that the exists call does in fact return "false" but your script is looking at exit code, not the output. The command returns exit code 0 (successful) and thus the delete is executed.

For this, you should use `az group show ...` which will return exit code 3 if the group is not found.

@kristapratico, for this we should ensure that `group exists` also uses exit code 3 when the result is "false".

**Comment by jsntcy** [comment] 2019-11-07 10:14
@tjprescott , why should `group exists` use exit code 3 but not other non-zero code when the result is "false"? what's the meaning of exit code 3?

**Comment by tjprescott** [comment] 2019-11-19 18:31
@Juliehzl for comment

**Comment by Juliehzl** [comment] 2020-01-02 02:28
@dalehhirt @richl10x I have tried with the latest azure cli in Azure Powershell, it can return false or true as expected. Can you try again? If you still have the problem, can you provide us debug information for finding root cause? 
I think there is nothing for CLI to do with this now. In this way, I will close this issue now and feel free to reopen it or create a new one.

**Closed by Juliehzl** 2020-01-02 02:28 UTC
Labels: ARM
