### ISSUE TITLE
How to list policy assignments?

### ISSUE THREAD

**Issue by mgwelch** [Azure/azure-cli#10038] opened 2019-07-24 20:43 UTC
The command

```
az policy assignment list
```

Shows only optional parameters:

> <img width="795" alt="image" src="https://user-images.githubusercontent.com/824136/61827758-ec6df780-ae2a-11e9-9e3d-cea574202aa1.png">

However I get this error when I run it:

```
$ az policy assignment list
usage error: --scope ARM_ID | --resource-group NAME | --subscription ID
```

> **Note:** The `--subscription` parameter shows up in the usage error message but it isn't listed in the documentation. 

I then added `--resource-group` parameter to my query but I still get the same error.

```
$ az policy assignment list --resource-group msftlearn-core-infrastructure-rg
usage error: --scope ARM_ID | --resource-group NAME | --subscription ID
```

I then added `--subscription` parameter along with the guid of the subscription I'm using, but I then get

```
$ az policy assignment list --resource-group msftlearn-core-infrastructure-rg --subscription b4966312-15d0-4f96-92eb-18d4aa323245
az: error: unrecognized arguments: --subscription b4966312-15d0-4f96-92eb-18d4aa323245
```

I would try to specify the third and final parameter "scope" but I'm not sure how to do that. I copy/pasted the scope from the GUI and enclosed it in quotes because of the spaces and got this error:

```
usage error `--scope`: must be a fully qualified ARM ID
```

But I'm brand new to Azure (I'm going through the Azure Fundamentals course at docs.microsoft.com and I'm just trying to do some of the GUI examples via the command line) and don't know what a fully qualified ARM ID is yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6760bb-c278-da56-a95c-4e82e221f1e8
* Version Independent ID: e25cbd2a-b415-214f-7d50-c403992c9361
* Content: [az policy assignment](https://docs.microsoft.com/en-us/cli/azure/policy/assignment?view=azure-cli-latest#az-policy-assignment-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment] 2019-09-23 05:57
Hi @mgwelch can you try your command with the latest azure-cli version? I cannot reproduce your issue now.

**Comment by zhoxing-ms** [comment] 2020-01-08 06:05
Because it hasn't been replied for a long time, I'll close the issue first. If you have any other questions, please feel free to reopen it or create a new one.

**Closed by zhoxing-ms** 2020-01-08 06:05 UTC
Labels: ARM, Needs Triage, Policy, Resource Manager-cli
