### ISSUE TITLE
az network public-ip show

### ISSUE THREAD

**Issue by gravfu** [Azure/azure-cli#26496] opened 2023-05-19 14:26 UTC
## Describe the bug

**Command Name**
`az network public-ip show`

**Errors:**
```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: option values must be strings
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 680, in execute
    self.cli_ctx.save_local_context(parsed_args, self.commands_loader.command_table[command].arguments,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 154, in save_local_context
    self.local_context.set(lca.scopes, lca.name, value)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/local_context.py", line 116, in set
    self._local_context_file.set_value(scope.lower(), argument, value)
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 239, in set_value
    config.set(section, option, value)
  File "/opt/az/lib/python3.10/configparser.py", line 1205, in set
    self._validate_value_types(option=option, value=value)
  File "/opt/az/lib/python3.10/configparser.py", line 1190, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a VM with a public IP Address
- `az network public-ip show -g {} -n {} --query "ipAddress" -o tsv`

## Expected Behavior

It should show the public IP of the instance

## Environment Summary
```
Linux-5.19.0-41-generic-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.48.1

Extensions:
ssh 1.1.6

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by necusjz** [comment] 2023-06-07 04:50
Duplicate of https://github.com/Azure/azure-cli/issues/26432.

**Closed by necusjz** 2023-06-07 04:50 UTC
Labels: Network, question, customer-reported, Auto-Assign, Azure CLI Team, Auto-Resolve, Similar-Issue
