### ISSUE TITLE
WebApp:azure-cli 2.24.0 az webapp config appsettings set Settings file with KeyVault references sets 'False' as value

### ISSUE THREAD

**Issue by jspiva** [Azure/azure-cli#18265] opened 2021-05-28 02:07 UTC
Calling 'az webapp config appsettings set' at cli version 2.24.0, with a json setting file, containing key vault references sets 'False' instead of the reference value.

For the this file example...
```
[
  {
    "slotSetting": false,
    "value": "@Microsoft.KeyVault(SecretUri=https://KeyVaultName.vault.azure.net/secrets/SecretName)",
    "name": "TestSetting1"
  },
  {
    "slotSetting": false,
    "value": "TestValue2",
    "name": "TestSetting2"
  }
]
```

az webapp config appsettings set --name <WebAppName> --resource-group <ResourceGroupName> --settings @JsonFileName.json

The call using 2.24.0 returns the following result:
```
[ 
 {
    "name": "TestSetting1",
    "slotSetting": false,
    "value": "False"
  },
  {
    "name": "TestSetting2",
    "slotSetting": false,
    "value": "TestValue2"
  }
]
```
Note the KeyVault reference is set to "False" as a string value, and not the expected reference string.
These same values are reflected within the app service configuration ui.

The call using 2.23.0 returns the following result:
```
[ 
 {
    "name": "TestSetting1",
    "slotSetting": false,
    "value": "@Microsoft.KeyVault(SecretUri=https://KeyVaultName.vault.azure.net/secrets/SecretName)"
  },
  {
    "name": "TestSetting2",
    "slotSetting": false,
    "value": "TestValue2"
  }
]
```

Works as expected in 2.23.0, which at the time of this writing was still available in Azure Cloud Shell, but using the cli in Azure Dev Ops pipelines has already been updated to 2.24.0 breaking for all pipelines requiring it.

Use of an actual key vault is not required for testing.

**Comment by yonzhan** [comment] 2021-05-28 02:31
route to service team

**Comment by Kotasudhakarreddy** [comment] 2021-05-28 07:00
Duplicate of #18266

**Closed by Kotasudhakarreddy** 2021-05-28 07:00 UTC
Labels: Service Attention, Web Apps
