### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by Candelit** [Azure/azure-cli#23917] opened 2022-09-16 12:40 UTC
[Skriv din feedback här]

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 92115d19-d7a0-93a8-bf2b-5126d1cddcd0
* Version Independent ID: a657f09b-e1ac-12a2-4b9c-7aaa1f0e3f5c
* Content: [az storage account](https://docs.microsoft.com/sv-se/cli/azure/storage/account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/account.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2022-09-16 14:31
Please provide detailed command and error message for us to troubleshoot.

**Comment by Candelit** [comment] 2022-09-16 14:43
I use VS code, gitbash and the az module
This has always been an issue in VS code, but we are now moving to all ARM + cli in deployment and this is getting to be a bigger issue.

**Comment by evelyn-ys** [comment] 2022-09-19 01:39
Duplicate of #23918

**Closed by evelyn-ys** 2022-09-19 01:39 UTC
Labels: Storage, question, customer-reported, CXP Attention, Auto-Assign, Azure CLI Team
