### ISSUE TITLE
`az aks command invoke` not waiting for command to complete

### ISSUE THREAD

**Issue by toastedonion** [Azure/azure-cli#22373] opened 2022-05-12 11:28 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az aks command invoke --command "sleep 6000" --resource-group <my-rg> --name <my-aks-cluster>`

**Describe the bug**

The above command does not wait for command completion, but instead permaturely exits after approximately 5 minutes of polling for the current pod's status.

**To Reproduce**

1. Create a new AKS cluster
2. Run the above command (sleep for 10 minutes)
3. After approximately 5 minutes the `az aks command invoke` command will prematurely exit

**Expected behavior**

I would expect the `az aks command invoke` command to wait for the command that is run inside the pod to finish or rather until the pod transitioned to either of the `Succeeded` or `Failed` states.

**Environment summary**

```bash
➜ az --version
azure-cli                         2.36.0

core                              2.36.0
telemetry                          1.0.6

Extensions:
ssh                                1.0.0
azure-devops                      0.22.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location '/opt/azure-cli/bin/python'
Extensions directory '/home/username/.azure/cliextensions'

Python (Linux) 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

```bash
➜ az aks command invoke --no-wait --command "kubectl version" --resource-group <my-rg> --name <my-aks-cluster>
command started at 2022-05-12 11:22:12+00:00, finished at 2022-05-12 11:22:12+00:00 with exitcode=0
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:05:33Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

It also seems like the `--no-wait` flag is ignored, as polling for the status still takes place and it displays the exact same behaviour as when not providing the flag.

**Comment by yonzhan** [comment] 2022-05-12 11:29
route to CXP team

**Comment by toastedonion** [comment] 2022-05-12 11:48
After some digging, I guess this is related to the following line:

https://github.com/Azure/azure-cli/blob/d9775946cda2dcdde2190ed1e45107652eae2fa6/src/azure-cli/azure/cli/command_modules/acs/custom.py#L2602

**Comment by bobalong79** [comment] 2022-05-12 14:46
Could be related to https://github.com/Azure/azure-cli/issues/22375

**Comment by navba-MSFT** [comment] 2022-07-27 02:53
@toastedonion Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-07-28 03:23
@toastedonion` az aks command invoke `(the run command feature) is not designed for long running operations. There's a hard limit in the resource provider side that the operation would expire in 30 mins. In CLI side, the timeout for polling results is 5 minutes (300 seconds). So the issue is by design.
 

The `--no-wait` option used to not work, but should have been fixed in latest cli version (2.38.0) in this PR [[AKS] `az aks command invoke`: Add support for `--no-wait` by FumingZhang · Pull Request #22813 · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/pull/22813). Hope this answers.

**Comment by navba-MSFT** [comment] 2022-08-01 03:04
@toastedonion I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-08-02 03:54
@toastedonion I hope you had a chance to look at my above comment. As a workaround you could use `--no-wait `option using the most recent Az CLI version. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Closed by navba-MSFT** 2022-08-02 03:54 UTC
Labels: question, AKS, customer-reported, needs-author-feedback, CXP Attention, Auto-Assign
