### ISSUE TITLE
The api-version query parameter (?api-version=) is required for all requests.

### ISSUE THREAD

**Issue by a-vishar** [Azure/azure-cli#12463] opened 2020-03-05 17:11 UTC
**Describe the bug**
Calling `az resource tag` results in this error: "The api-version query parameter (?api-version=) is required for all requests."

**To Reproduce**
az resource tag --tags ServiceName='TAGVALUE' --ids '/subscriptions/SUBSCRIPTIONID/resourceGroups/GROUPNAME/providers/Microsoft.Web/certificates/72B7597AD09DB99A2DFDCAB3D50F8C4935475231#CERTIFICATENAME-WestEuropewebspace'

**Expected behavior**
The resource should be tagged or a more sensible error should be displayed.

**Environment summary**
Windows via PowerShell

**Comment by yonzhan** [comment] 2020-03-06 00:02
add to S167.

**Comment by a-vishar** [comment] 2020-03-10 13:42
Hi, any update on this?

**Comment by zhoxing-ms** [comment] 2020-03-16 03:12
@a-vishar I cannot reproduce your problem. What version of azure-cli and python do you use?
And could you please try the latest version of azure-cli(2.2.0) to see if this problem still exists?

**Comment by zhoxing-ms** [comment] 2020-03-27 01:46
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-03-27 01:46 UTC
Labels: ARM, customer-response-expected

**Comment by a-vishar** [comment] 2020-04-13 01:52
Yes, I am using the latest version.  It turns out that the issue is related to orphaned resources.

Easy repro steps:
1. Create a SQL DB
2. Create an alert
3. Move the DB to another resource group / subscription (orphaning the alert)
4. Try to tag the orphaned alert
