### ISSUE TITLE
webapp:Azure App Service settings changed after deploying updated container image

### ISSUE THREAD

**Issue by SnehaAgrawal-MSFT** [Azure/azure-cli#9283] opened 2019-05-02 06:04 UTC
Bug Description:
App service settings changes from true to false when deploying an updated  container image.

Customers Verbatim
“As the topic say I have a problem with my web app settings when deploying an updated container image. The setting that get changed from "TRUE" to "FALSE" is: "HTTP_ENABLE_APP_SERVICE_STORAGE=TRUE" When updating the container and after the restart of the web app this setting is "FALSE". Dockerimage is stored in ACR. Any solutions?
I have been trying to google around and find solutions but have not yet found anything or even where I should start looking. Thanks for help,
Update 1:
The problem occurs when I run the following commands in az cli:
az webapp config container set \
--docker-custom-image-name "DOCKER|xx.azurecr.io/imagename:tag" \
--docker-registry-server-password topsecret \
--docker-registry-server-url https://index.docker.io \
--docker-registry-server-user username \
--name MyWebApp \
--resource-group MyResourceGroup
The return of this command shows the following:
  {
    "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
    "slotSetting": false,
    "value": "false"
  },
Even though that the setting was TRUE before updating. Im not using slots but I have tried with setting the value on both "slotSetting": true, and "value": "true" but still no success.”

Expected behavior
After deploying updated container Image App setting should not changed from True to False.

Additional context
The conversation with PG team on email confirmed that this is bug.

**Comment by panchagnula** [comment] 2019-05-03 03:08
@Nking92 can you take a look at this?

**Comment by panchagnula** [comment] 2019-05-13 19:47
@SnehaAgrawal-MSFT can you try to repro this again but this time before you run the config update command can you check the original value of this setting by running az webapp config show? thank you.

**Comment by panchagnula** [comment] 2019-05-31 22:46
@patricklee2 can you look at this, its related to bring your own storage feature. Thank you

**Comment by patricklee2** [comment] 2019-06-08 01:07
ill take a look

**Comment by panchagnula** [comment] 2019-06-14 20:15
@patricklee2 can we get this in for the next sprint please?

**Comment by patricklee2** [comment] 2019-06-14 20:17
26th? Yes, I'll aim for that.

**Comment by patricklee2** [comment] 2019-06-17 23:50
`HTTP_ENABLE_APP_SERVICE_STORAGE` does not get overwritten with `az webapp config container set`
Does the customer mean `WEBSITES_ENABLE_APP_SERVICE_STORAGE` is overwritten?

**Comment by patricklee2** [comment] 2019-06-19 19:10
@SnehaAgrawal-MSFT I'm not able to reproduce the bug the customer reported.
When I update the image the app setting `HTTP_ENABLE_APP_SERVICE_STORAGE ` does not get overwritten.  Can you ask the customer if they meant that `WEBSITES_ENABLE_APP_SERVICE_STORAGE` should to be preserved?

**Comment by panchagnula** [comment] 2019-06-28 01:12
@SnehaAgrawal-MSFT please provide the information that Patrick requested - or provide the repro steps. Since we cannot repro this - closing this.

**Closed by panchagnula** 2019-06-28 01:12 UTC
Labels: Service Attention, Web Apps-cli
