### ISSUE TITLE
[webapp] - az webapp config storage-account add without -slot-setting but with -slot creates sticky mount

### ISSUE THREAD

**Issue by carlwoodhouse** [Azure/azure-cli#9707] opened 2019-06-18 10:22 UTC
when running the following

```
az webapp config storage-account add -g some-rg -n some-app -s staging -i "mountName" -t AzureFiles -a some-storageaccountname --sn "mountShareName" -k some-storageaccount-key -m "/some/mount/path"
```

A mount is created on the staging slot as expected, but this seems to be sticky (doesn't move to production with a slot swap) I thought this should only happen if you specify `--slot-setting`.

Works as expected when creating via portal

**Comment by panchagnula** [comment] 2019-06-18 22:55
@patricklee2 can you look at this issue - not sure if CLI is doing something here to make this sticky by default or what the expected behavior should be?

**Comment by patricklee2** [comment] 2019-06-18 22:57
ill take a look

**Comment by panchagnula** [comment] 2019-07-02 18:45
@patricklee2 any update on this? Is this something we can have a fix for this up-coming release?

**Comment by patricklee2** [comment] 2019-07-02 20:00
I didnt get a chance to look at it yet.  I'll target Sprint 66

**Comment by panchagnula** [comment] 2019-07-15 22:22
@patricklee2 do you have an update on this  still targeting Sprint 66?

**Comment by patricklee2** [comment] 2019-07-16 17:42
I didnt get a chance to look at it yet. I'll work on it this week.

**Comment by patricklee2** [comment] 2019-07-17 05:29
@carlwoodhouse 
I was not able to reproduce the problem, do you have more details steps for a reproduction?

My steps
```
az appservice plan create -n test -g test --is-linux -l "West US" --number-of-workers 1 --sku S1
az webapp create --name test --plan test --resource-group test --runtime "php|7.3"
az webapp deployment slot create --name test --resource-group test --slot staging

az webapp config storage-account add -n test -g test -s staging -i pic -t AzureFiles -a test --sn pic -m /home/site/wwwroot/pic -k test 


az webapp deployment slot swap --name test --resource-group test --slot staging
```

**Comment by btardif** [comment] 2019-07-17 19:46
@carlwoodhouse we need to decide if this is still an issue, if we don't get confirmation from you we will close this item as no repro by end of sprint (July 24th)

**Comment by carlwoodhouse** [comment] 2019-07-17 19:52
I will test again tomorrow and let you know

**Comment by panchagnula** [comment] 2019-07-24 20:36
@carlwoodhouse do have an update to share here please? Thank you.

**Comment by btardif** [comment] 2019-07-25 16:40
I'm closing this as no-repro

**Closed by btardif** 2019-07-25 16:40 UTC
Labels: App Services, Service Attention, Web Apps
