### ISSUE TITLE
how to use Azure Backup via azure-cli?

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#4459] opened 2017-09-18 07:02 UTC
### Description
**Outline the issue here:**
I cannot use Azure Backup via azure-cli
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
MSI
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
2.0.17
**OS Version:** What OS and version are you using?  
Answer here:
10.0.16288.1
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Windows

**Comment by tjprescott** [comment] 2017-09-19 17:45
Is this a duplicate of #2384?

**Comment by tjprescott** [comment] 2017-09-19 17:46
If you are asking for support for Azure Backup, it has already been added and will be in the next release.

**Comment by alexeyshishkin01** [comment] 2017-09-19 20:18
what's next release GA date?

**Comment by tjprescott** [comment] 2017-09-19 22:33
The Backup module will be released next week in Preview status.

**Comment by alexeyshishkin01** [comment] 2017-09-20 07:55
how to grab Preview? how far Release is going to be from Preview?

**Comment by tjprescott** [comment] 2017-09-20 16:36
It is a public preview.  You can get it right now with a developer setup or https://github.com/Azure/azure-cli#edge-builds. 

Next week you'll be able to get it via the usual install channels.

**Closed by tjprescott** 2017-09-20 16:36 UTC
Labels: Question, RecoveryServices

**Comment by alexeyshishkin01** [comment] 2017-09-20 21:18
ok, many thanks!

**Comment by alexeyshishkin01** [comment] 2017-09-24 20:50
got it in 2.0.18 - when are you going to update doc file - https://docs.microsoft.com/pdfstore/en-us/Azure.azure-documents/live/backup.pdf ?

**Comment by tjprescott** [comment] 2017-09-25 15:41
I just looked at it and it looks up to date. I see references to the CLI 2.0 commands.

**Comment by alexeyshishkin01** [comment] 2017-09-25 20:47
studying ...
