### ISSUE TITLE
Request to have azure cli of latest version in Homebrew formula

### ISSUE THREAD

**Issue by helenlivsc** [Azure/azure-cli#4278] opened 2017-08-21 08:40 UTC
### Description
**Outline the issue here:**
On webpage https://docs.microsoft.com/en-us/cli/azure/install-azure-cli, the azure-cli version on Homebrew formula is outdated. Can you update it on Homebrew?
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: we would like to install CLI of latest version through homebrew.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0

**OS Version:** What OS and version are you using?  
Answer here: macOS sierra 10.12.6

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by derekbekoe** [comment] 2017-08-24 16:29
Closing as dupe of https://github.com/Azure/azure-cli/issues/643

**Closed by derekbekoe** 2017-08-24 16:29 UTC
Labels: Packaging
