### ISSUE TITLE
WebApp:Issues after changing php version via "az webapp config set" command.

### ISSUE THREAD

**Issue by PrakashLakhara** [Azure/azure-cli#15596] opened 2020-10-21 11:47 UTC
After changing the php version in my webapp, I am not able to edit or create anyfile via ssh and also from the ftp in the webapp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e50d77a-f2fa-6d6e-0c57-2f434c12766f
* Version Independent ID: f9a98805-6e16-487a-03ce-237cb964f83c
* Content: [az webapp config](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-10-21 23:47
webapp

**Comment by btardif** [comment] 2020-10-28 21:07
can you share the command you used for this? @PrakashLakhara would like to try and repro

**Comment by PrakashLakhara** [comment] 2020-10-30 11:49
> can you share the command you used for this? @PrakashLakhara would like to try and repro
The command was the following:
az webapp config set --name mywebapp   --resource-group MYRESOURCEGROUP --linux-fx-version "PHP|7.3"

**Comment by PrakashLakhara** [comment] 2020-10-30 11:50
> can you share the command you used for this? @PrakashLakhara would like to try and repro

The command was the following:
az webapp config set --name mywebapp --resource-group MYRESOURCEGROUP --linux-fx-version "PHP|7.3"

**Comment by btardif** [comment] 2021-06-25 17:11
@seligj95 see if you can repro this

**Comment by seligj95** [comment] 2021-07-09 17:59
closing, was unable to reproduce. az webapp config set works successfully. was able to create/add files after updating php version.

**Closed by seligj95** 2021-07-09 17:59 UTC
Labels: Service Attention, Web Apps
