### ISSUE TITLE
Application Gateway frontend ip update is not working

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2175] opened 2017-02-20 07:32 UTC
Update on frontend ip returns immediately and does not set values. See debug output below. Also please note that when a static internal ip is assigned the private ip allocation method should be dynamic. In output below, it is being sent as Dynamic. So even if the update was working, it would send incorrect params to the backend.

azureuser@amitubuntu15:~$ appgw frontend-ip update -n appgwinternal --private-ip-address 10.5.0.10 --subnet default --vnet-name azurewebsitetest  --gateway-name azurewebsitetest -g azurewebsitetest --debug

msrest.http_logger : Request body:
msrest.http_logger : {"location": "eastus", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"sku": {"tier": "Standard", "capacity": 1, "name": "Standard_Small"}, "frontendPorts": [{"etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"port": 80, "provisioningState": "Succeeded"}, "name": "appGatewayFrontendPort", "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendPorts/appGatewayFrontendPort"}, {"etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"port": 443, "provisioningState": "Succeeded"}, "name": "sslport", "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendPorts/sslport"}], "requestRoutingRules": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/requestRoutingRules/rule1", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"backendAddressPool": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendAddressPools/appGatewayBackendPool"}, "httpListener": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/httpListeners/appGatewayHttpListener"}, "ruleType": "Basic", "backendHttpSettings": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendHttpSettingsCollection/appGatewayBackendHttpSettings"}, "provisioningState": "Succeeded"}, "name": "rule1"}], "backendHttpSettingsCollection": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendHttpSettingsCollection/appGatewayBackendHttpSettings", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"cookieBasedAffinity": "Disabled", "requestTimeout": 30, "protocol": "Http", "port": 80, "provisioningState": "Succeeded"}, "name": "appGatewayBackendHttpSettings"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendHttpSettingsCollection/settin2", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"protocol": "Http", "cookieBasedAffinity": "Enabled", "requestTimeout": 30, "probe": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/probes/probe5"}, "port": 80, "provisioningState": "Succeeded"}, "name": "settin2"}], "probes": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/probes/probe2", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"host": "127.0.0.1", "protocol": "Http", "timeout": 120, "path": "/", "unhealthyThreshold": 8, "interval": 30, "provisioningState": "Succeeded"}, "name": "probe2"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/probes/probe5", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"host": "127.0.0.1", "protocol": "Http", "timeout": 120, "path": "/", "unhealthyThreshold": 8, "interval": 30, "provisioningState": "Succeeded"}, "name": "probe5"}], "backendAddressPools": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendAddressPools/appGatewayBackendPool", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"backendAddresses": [], "provisioningState": "Succeeded"}, "name": "appGatewayBackendPool"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendAddressPools/temp1", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"backendAddresses": [{"ipAddress": "10.0.0.5"}], "provisioningState": "Succeeded"}, "name": "temp1"}], "gatewayIPConfigurations": [{"etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"subnet": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/virtualNetworks/azurewebsitetest/subnets/default"}, "provisioningState": "Succeeded"}, "name": "appGatewayIpConfig", "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/gatewayIPConfigurations/appGatewayIpConfig"}], "frontendIPConfigurations": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendIPConfigurations/appGatewayFrontendIP", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"privateIPAllocationMethod": "Dynamic", "provisioningState": "Succeeded", "publicIPAddress": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/publicIPAddresses/azurewebsitetest"}}, "name": "appGatewayFrontendIP"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendIPConfigurations/appgwinternal", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"subnet": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/virtualNetworks/azurewebsitetest/subnets/default"}, "privateIPAllocationMethod": "Dynamic", "privateIPAddress": "10.5.0.10", "provisioningState": "Succeeded"}, "name": "appgwinternal"}], "sslCertificates": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/sslCertificates/newcert", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "name": "newcert", "properties": {"publicCertData": "MIIClAYJKoZIhvcNAQcCoIIChTCCAoECAQExADALBgkqhkiG9w0BBwGgggJpMIICZTCCAc4CCQC6bHNqqn4VSDANBgkqhkiG9w0BAQsFADB3MQswCQYDVQQGEwJVUzELMAkGA1UECAwCV0ExEDAOBgNVBAcMB1JlZG1vbmQxDTALBgNVBAoMBGFtaXQxDTALBgNVBAsMBGFtaXQxDTALBgNVBAMMBGFtaXQxHDAaBgkqhkiG9w0BCQEWDWFtaXRAYW1pdC5jb20wHhcNMTYwOTEzMDYxODU5WhcNMTcwOTEzMDYxODU5WjB3MQswCQYDVQQGEwJVUzELMAkGA1UECAwCV0ExEDAOBgNVBAcMB1JlZG1vbmQxDTALBgNVBAoMBGFtaXQxDTALBgNVBAsMBGFtaXQxDTALBgNVBAMMBGFtaXQxHDAaBgkqhkiG9w0BCQEWDWFtaXRAYW1pdC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMmrOwqp2511v6pg5e+c7RmS3aoI4zfUcbqMZqF8TcJPGqH6V+xxtUd79lGnngnlrplc761Btyx5AaFVo+W1lQrQMDA8hGWZXkD9iGO1zfcFWb6ntNVuUE29QS+CqVXF9dnNak1AmOMsO+XcYEyOAq2I0zqq1cShqPt5RkgkTM2hAgMBAAEwDQYJKoZIhvcNAQELBQADgYEAwhYpFtFdB3yrA8ofqLBaeA0u6TjHMag6iGye+CbGZbXUgOPUz0ne62Jg8ceW6p6OckQ3S5b1o1vGgRHZostHoMRj6PzWZuac+q5XERlpnlh/n+dPiS/jTQQJJdlp3ihZV/NwHrgxGNLOuWtJt76sGQxwau2hbSm6ldXwie9DUTAxAA==", "provisioningState": "Succeeded"}}], "authenticationCertificates": [], "httpListeners": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/httpListeners/appGatewayHttpListener", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"provisioningState": "Succeeded", "protocol": "Http", "frontendIPConfiguration": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendIPConfigurations/appGatewayFrontendIP"}, "requireServerNameIndication": false, "frontendPort": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendPorts/appGatewayFrontendPort"}}, "name": "appGatewayHttpListener"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/httpListeners/sslListener", "etag": "W/\"42feeaa6-d923-4479-83f5-cf3ca973760e\"", "properties": {"requireServerNameIndication": false, "protocol": "Https", "sslCertificate": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/sslCertificates/newcert"}, "frontendPort": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendPorts/sslport"}, "frontendIPConfiguration": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendIPConfigurations/appGatewayFrontendIP"}, "provisioningState": "Succeeded"}, "name": "sslListener"}], "resourceGuid": "c46e09cd-503e-47b2-98c7-c753dffcf60b", "urlPathMaps": [], "provisioningState": "Succeeded"}, "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest"}

**Comment by tjprescott** [comment] 2017-02-20 19:00
When I try and send updates, the contents of the post are correct, but I get error messages from the server such as:

- "appGatewayFrontendIP private IP cannot be changed" when trying to change the static IP of an internal configuration
- "appGatewayFrontendIP private IP allocation type cannot be changed" when trying to convert an internal configuration from dynamic to static (by specifying a static IP address).

The CLI seems to be sending the correct parameters, but it seems the service rejects them.

I have confirmed that if you specify a --private-ip-address value, it sets the allocation-method to static.

**Comment by tjprescott** [comment] 2017-03-07 16:24
This is a service issue--so I am moving this to the backlog.

**Comment by MyronFanQiu** [comment] 2019-08-19 09:47
@akshaysngupta Any update or conclusion about this issue?

**Closed** 2019-12-26 07:07 UTC

**Comment by dNetGuru** [comment] 2020-01-13 04:48
Any updates on this?

**Comment by fiftin** [comment] 2020-06-05 17:46
Any updates? 3 years without response. WTF microsoft? Remove from documentation if you can't fix this!
