### ISSUE TITLE
Confusing error message for az deployment sub create

### ISSUE THREAD

**Issue by JonathanFingold** [Azure/azure-cli#16130] opened 2020-12-02 23:00 UTC
## Describe the bug

**Command Name**
`az deployment sub create`

**Errors:**
```
Parameter 'deployment_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
```

**Issue**: `deployment_name` is not a parameter I provided, nor is it listed as a parameter when I run `az deployment sub create --help`.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Follow the steps as outlined in [Tutorial: Deploy a basic bot](https://docs.microsoft.com/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=csharp).
- In step 4, follow the **Deploy via ARM template with new Resource Group** path.
- `az deployment sub create --template-file {} --location {} --parameters {} {} {} {} {} {} {} {} {} --name {}`
- Get error message, which is a dead end.

## Expected Behavior
The error message should name the correct parameter, and the parameter should be described in the help text for the command.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.15.1

```

**Comment by yonzhan** [comment] 2020-12-03 03:31
ARM

**Comment by pmsousa** [comment] 2021-02-08 14:34
@yonzhan, same issue occurs with

`az deployment group show`

### To Reproduce

From: [https://github.com/mspnp/microservices-reference-implementation](https://github.com/mspnp/microservices-reference-implementation)

`export DEV_PREREQ_DEPLOYMENT_NAME=azuredeploy-prereqs-${DEPLOYMENT_SUFFIX}-dev
az deployment sub create \
   --name $DEV_PREREQ_DEPLOYMENT_NAME \
   --location $LOCATION \
   --template-file ${PROJECT_ROOT}/azuredeploy-prereqs.json \
   --parameters resourceGroupName=$RESOURCE_GROUP \
                resourceGroupLocation=$LOCATION \
                demoFor=$DEMOFOR

export IDENTITIES_DEV_DEPLOYMENT_NAME=$(az deployment sub  show -n $DEV_PREREQ_DEPLOYMENT_NAME --query properties.outputs.identitiesDeploymentName.value -o tsv) && \
export DELIVERY_ID_NAME=$(az group deployment show -g $RESOURCE_GROUP -n $IDENTITIES_DEV_DEPLOYMENT_NAME --query properties.outputs.deliveryIdName.value -o tsv)`

**Comment by zhoxing-ms** [comment] 2021-02-09 02:41
@JonathanFingold Hi, the logic of `deployment_name` is that if `--name/-n` parameter is passed in, it is the value of this parameter, otherwise it is the file name of `--template-file`.
Please check its value to see if it meets the specification `^[-\\w\\._\\(\\)]+$`.

**Comment by zhoxing-ms** [comment] 2021-02-09 02:58
@pmsousa Yes, it's not a demand, it's a bug or usage issue.
We have another meaning in this label (only for internal triage), please don't care about it

Could you please describe the parameters and error information of command `az deployment group show`?
If it is convenient, please add parameter `--debug` to the original command, and then send the printed information to me by email
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment] 2021-03-01 02:04
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2021-03-01 02:04 UTC
Labels: ARM, OKR3.2 Candidate, feature-request

**Comment by cgtheflash** [comment] 2021-05-22 21:26
I get this same error on a resource group deployment:
cli.azure.cli.core.azclierror: Parameter 'deployment_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
az_command_data_logger: Parameter 'deployment_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.

Parameter file: `   {
      "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
      "contentVersion": "1.0.0.0",
      "parameters": {
         "activityLogAlertNameSuffix": {
            "value": "test"
         },
          "deployAlertSecuritySolutionWrite": {
            "value": "Yes"
         },
          "enableActivityLogSecuritySolutionWrite": {
            "value": "True"
         },
          "deployAlertSecuritySolutionDelete": {
            "value": "Yes"
         },
          "enableActivityLogSecuritySolutionDelete": {
            "value": "True"
         },
          "deployAlertNetworkSecurityGroupWrite": {
            "value": "Yes"
         },
          "enableActivityLogNetworkSecurityGroupWrite": {
            "value": "True"
         },
          "deployAlertNetworkSecurityGroupDelete": {
            "value": "Yes"
         },
          "enableActivityLogNetworkSecurityGroupDelete": {
            "value": "True"
         },
          "deployAlertNetworkSecurityGroupRuleWrite": {
            "value": "Yes"
         },
          "enableActivityLogNetworkSecurityGroupRuleWrite": {
            "value": "True"
         },
          "deployAlertNetworkSecurityGroupRuleDelete": {
            "value": "Yes"
         },
          "enableActivityLogNetworkSecurityGroupRuleDelete": {
            "value": "True"
         },
          "deployAlertSQLFirewallRuleWrite": {
            "value": "Yes"
         },
          "enableActivityLogSQLFirewallRuleWrite": {
            "value": "True"
         },
          "deployAlertSQLFirewallRuleDelete": {
            "value": "Yes"
         },
          "enableActivityLogSQLFirewallRuleDelete": {
            "value": "True"
         },
          "deployAlertPolicyAssignmentWrite": {
            "value": "Yes"
         },
          "enableActivityLogPolicyAssignmentWrite": {
            "value": "True"
         },
          "deployAlertPolicyAssignmentDelete": {
            "value": "Yes"
         },
          "enableActivityLogPolicyAssignmentDelete": {
            "value": "True"
         },
          "deployAlertPolicyWrite": {
            "value": "Yes"
         },
          "enableActivityLogPolicyWrite": {
            "value": "True"
         },
          "actionGroup": {
            "value": "/subscriptions/xxxxxxx/resourceGroups/test/providers/microsoft.insights/actionGroups/andanothertest"
         }
      }
   }
`

`PS C:\Code\> az deployment group create --resource-group test --name "ActivityLogAlertsDeploy - Copy" --template-file "C:\Code\ARM\ActivityLogAlertsDeploy - Copy.json" --parameters "C:\Code\ARM\ActivityLogAlertsDeploy - Copy\2021-05-22(6)\Parameters.json" --debug

cli.knack.cli: Command arguments: ['deployment', 'group', 'create', '--resource-group', 'test', '--name', 'ActivityLogAlertsDeploy - Copy', '--template-file', 'C:\\Code\\ARM\\ActivityLogAlertsDeploy - Copy.json', '--parameters', 'C:\\Code\\ARM\\ActivityLogAlertsDeploy - Copy\\2021-05-22(6)\\Parameters.json', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x03AB4F18>, <function OutputProducer.on_global_arguments at 0x03B50468>, <function CLIQuery.on_global_arguments at 0x03B6B390>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'deployment': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.027        37       176
cli.azure.cli.core: Total (1)                 0.027        37       176
cli.azure.cli.core: Loaded 37 groups, 176 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : deployment group create
cli.azure.cli.core: Command table: deployment group create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03E27E88>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\xxxxxxx\.azure\commands\2021-05-22.17-20-06.deployment_group_create.15684.log'.
az_command_data_logger: command args: deployment group create --resource-group {} --name {} --template-file {} --parameters {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03E71810>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x03E71F18>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03E71F60>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03E89030>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03B504B0>, <function CLIQuery.handle_query_parameter at 0x03B6B3D8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x03E71930>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03E71FA8>]
cli.azure.cli.core.util: attempting to read file C:\Code\ARM\ActivityLogAlertsDeploy - Copy.json as utf-8-sig
cli.azure.cli.core.util: attempting to read file C:\Code\ARM\ActivityLogAlertsDeploy - Copy\2021-05-22(6)\Parameters.json as utf-8-sig
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': '7aa51a5a-bb43-11eb-8725-0433c2a535d8'
cli.azure.cli.core.commands.client_factory:     'CommandName': 'deployment group create'
cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '--resource-group --name --template-file --parameters --debug'
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.exceptions: Parameter 'deployment_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 807, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 544, in deploy_arm_template_at_resource_group
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 581, in _deploy_arm_template_at_resource_group
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/resources/v2020_10_01/operations/_deployments_operations.py", line 3243, in validate
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/resources/v2020_10_01/operations/_deployments_operations.py", line 3165, in _validate_initial
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 648, in url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 636, in _http_component_validation
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 740, in validate
msrest.exceptions.ValidationError: Parameter 'deployment_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 102, in handle_template_based_exception
AttributeError: 'NoneType' object has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 104, in handle_template_based_exception
knack.util.CLIError: Parameter 'deployment_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.

cli.azure.cli.core.azclierror: Parameter 'deployment_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
az_command_data_logger: Parameter 'deployment_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03E27FA8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.779 seconds (init: 0.195, invoke: 0.584)
telemetry.save: Save telemetry record of length 3147 in cache`

**Comment by zhoxing-ms** [comment] 2021-05-24 02:17
@cgtheflash Hi
> 1. --name parameter is set to something with characters considered unacceptable such as a hyphen
ex. az deployment group create --resource-group test --name "test - Copy" --template-file test.json --parameters test.parameters.json

On this issue, the reason for the problem is that the deployment name contains invalid characters `' '`. At present, CLI can provide specific error information:
```
{"error":{"code":"InvalidDeployment","message":"The provided deployment name 'test - Copy' has these invalid characters: '  '. The name can only be a letter, digit, '-', '.' or '_'. Please see https://aka.ms/arm-deploy for usage details."}}
```

> 2. --name parameter is not set at all
ex. az deployment group create --resource-group test --template-file test.json --parameters test.parameters.json

For this one, I can't reproduce it. If it is convenient, please add parameter `--debug` to the original command, and then send the printed information to me by email
My email address is Zhou.Xing@microsoft.com, thanks~
