### ISSUE TITLE
Provide option to disable showing progress

### ISSUE THREAD

**Issue by stepro** [Azure/azure-cli#7149] opened 2018-08-27 17:26 UTC
Certain long-running commands, such as `az group delete`, try to show a progress message like " - Running .." First of all, it doesn't appear to do what I think was expected (the spinner never spins). Secondly, when I'm scripting with az, and outputting my own progress messages, I'd prefer to not have this message show up. I know it doesn't appear if you pipe to a file, but if I'm just running my script from a console session, I can't find any way to disable it.

**Comment by yugangw-msft** [comment] 2019-03-13 20:20
We will need more user votes to consider any actions on this

**Comment by yonzhan** [comment] 2019-12-21 14:25
add to S165.

**Comment by qianwens** [comment] 2020-02-21 04:53
Close this issue since this is by design and there is no vote.

**Closed by qianwens** 2020-02-21 04:53 UTC
Labels: Feature Request, Infrastructure
