### ISSUE TITLE
Not working: `az webapp`

### ISSUE THREAD

**Issue by tsubakimoto** [Azure/azure-cli#22296] opened 2022-05-07 02:32 UTC
## Describe the bug

**Command Name**
`az webapp`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'vsts_cd_manager'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 583, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.8/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/opt/az/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.8/argparse.py", line 1988, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.8/argparse.py", line 1965, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.8/argparse.py", line 1159, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/az/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/opt/az/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.8/argparse.py", line 1044, in __call__
    parser.print_help()
  File "/opt/az/lib/python3.8/argparse.py", line 2494, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/parser.py", line 195, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/opt/az/lib/python3.8/site-packages/knack/parser.py", line 248, in format_help
    self.cli_help.show_help(self.prog.split()[0],
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/_help.py", line 165, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/opt/az/lib/python3.8/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/_help.py", line 303, in load
    loader.versioned_load(self, options)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/opt/az/lib/python3.8/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/opt/az/lib/python3.8/site-packages/knack/parser.py", line 241, in __getattribute__
    self.description = self._description() \
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkmbmbr/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 90, in <module>
    from .vsts_cd_provider import VstsContinuousDeliveryProvider
  File "/home/tkmbmbr/.azure/cliextensions/appservice-kube/azext_appservice_kube/vsts_cd_provider.py", line 8, in <module>
    from vsts_cd_manager.continuous_delivery_manager import ContinuousDeliveryManager
ModuleNotFoundError: No module named 'vsts_cd_manager'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Open Cloud Shell on https://docs.microsoft.com/ja-jp/azure/app-service/tutorial-connect-msi-sql-database?tabs=windowsclient%2Cefcore%2Cdotnet#code-try-9 .
- Type and Run `az webapp -h` .

## Expected Behavior
Show `az webapp` help.

## Environment Summary
```
Linux-5.4.0-1077-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
aks-preview 0.5.31
spring-cloud 2.8.0
customlocation 0.1.2
connectedk8s 1.1.10
appservice-kube 0.1.20
k8s-extension 0.7.0
ai-examples 0.2.5
ssh 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-05-07 02:53
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-05-09 03:50
@tsubakimoto Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment] 2022-05-09 11:03
@tsubakimoto I am able to get it work without any issue, can you please try again and share the debug log?

**Comment by tsubakimoto** [comment] 2022-05-10 00:00
@RakeshMohanMSFT Thank you for confirmation. However, the error is occuring now.
I tried same page and steps. The result is below.

```
$ date
Mon 09 May 2022 11:54:38 PM UTC
$ az webapp
The command failed with an unexpected error. Here is the traceback:
No module named 'vsts_cd_manager'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 583, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.8/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/opt/az/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.8/argparse.py", line 2009, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.8/argparse.py", line 1965, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.8/argparse.py", line 1159, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.8/argparse.py", line 2034, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/parser.py", line 160, in error
    recommender.set_help_examples(self.get_examples(self.prog))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/parser.py", line 201, in get_examples
    return self.cli_help.get_examples(command,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/_help.py", line 192, in get_examples
    else self.group_help_cls(self, delimiters, parser)
  File "/opt/az/lib/python3.8/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/_help.py", line 303, in load
    loader.versioned_load(self, options)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/opt/az/lib/python3.8/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/opt/az/lib/python3.8/site-packages/knack/parser.py", line 241, in __getattribute__
    self.description = self._description() \
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkmbmbr/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 90, in <module>
    from .vsts_cd_provider import VstsContinuousDeliveryProvider
  File "/home/tkmbmbr/.azure/cliextensions/appservice-kube/azext_appservice_kube/vsts_cd_provider.py", line 8, in <module>
    from vsts_cd_manager.continuous_delivery_manager import ContinuousDeliveryManager
ModuleNotFoundError: No module named 'vsts_cd_manager'
To open an issue, please run: 'az feedback'
```

Azure CLI's version is below.

```
$ az -v
azure-cli                         2.36.0

core                              2.36.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.31
spring-cloud                       2.8.0
customlocation                     0.1.2
connectedk8s                      1.1.10
appservice-kube                   0.1.20
k8s-extension                      0.7.0
ai-examples                        0.2.5
ssh                                1.1.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/tkmbmbr/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.8/site-packages/azure-cli-extensions'

Python (Linux) 3.8.13 (default, Apr 22 2022, 04:53:00) 
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Comment by RakeshMohanMSFT** [comment] 2022-05-10 14:28
@tsubakimoto I am really not sure what is causing the issue, I have seen similar issue in the past due to appservice-kube extension   can you please upgrade it once and check if that helps?

**Comment by tsubakimoto** [comment] 2022-05-11 10:31
# Before upgrade
```
$ az -v
azure-cli                         2.36.0

core                              2.36.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.31
spring-cloud                       2.8.0
customlocation                     0.1.2
connectedk8s                      1.1.10
appservice-kube                   0.1.20
k8s-extension                      0.7.0
ai-examples                        0.2.5
ssh                                1.1.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/tkmbmbr/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.8/site-packages/azure-cli-extensions'

Python (Linux) 3.8.13 (default, Apr 22 2022, 04:53:00) 
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

# Upgrade
```
$ az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.36.0
Upgrading extensions
Checking update for aks-preview
Checking update for spring-cloud
Checking update for customlocation
Checking update for connectedk8s
Checking update for appservice-kube
No updates available for 'appservice-kube'. Use --debug for more information.
Checking update for k8s-extension
Checking update for ai-examples
No updates available for 'ai-examples'. Use --debug for more information.
Checking update for ssh
Failed to delete '/opt/az/lib/python3.8/site-packages/azure-cli-extensions/ssh': [Errno 13] Permission denied: '__init__.py'. Retrying ...
Failed to delete '/opt/az/lib/python3.8/site-packages/azure-cli-extensions/ssh': [Errno 13] Permission denied: '__init__.py'. Retrying ...
Failed to delete '/opt/az/lib/python3.8/site-packages/azure-cli-extensions/ssh': [Errno 13] Permission denied: '__init__.py'. Retrying ...
Failed to delete '/opt/az/lib/python3.8/site-packages/azure-cli-extensions/ssh': [Errno 13] Permission denied: '__init__.py'. You may try to delete it manually.
An error occurred whilst updating.
The extension ssh already exists.
The command failed with an unexpected error. Here is the traceback:
[Errno 17] File exists: '/opt/az/lib/python3.8/site-packages/azure-cli-extensions/ssh'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 412, in update_extension
    _add_whl_ext(cli_ctx=cmd_cli_ctx, source=download_url, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 113, in _add_whl_ext
    raise CLIError('The extension {} already exists.'.format(extension_name))
knack.util.CLIError: The extension ssh already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/extension/custom.py", line 34, in update_extension_cmd
    return update_extension(cli_ctx=cmd.cli_ctx, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 420, in update_extension
    shutil.copytree(backup_dir, extension_path)
  File "/opt/az/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/opt/az/lib/python3.8/shutil.py", line 458, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/bin/../../opt/az/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/opt/az/lib/python3.8/site-packages/azure-cli-extensions/ssh'
To open an issue, please run: 'az feedback'
Upgrade finished.You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update
```

---

@RakeshMohanMSFT I could not upgrade Azure CLI. Shoud I help to Azure Support?

**Comment by RakeshMohanMSFT** [comment] 2022-05-11 10:46
@tsubakimoto Apologies for not being clear earlier, I meant appservice-kube extension upgrade.

You can use these commands
```
az extension remove -n appservice-kube
az extension add -n appservice-kube
```

**Comment by tsubakimoto** [comment] 2022-05-14 04:27
@RakeshMohanMSFT Thank you so much. I upgraded `appservice-kube` and this error is fixed!

```
$ az extension remove -n appservice-kube
$ az extension add -n appservice-kube
The installed extension 'appservice-kube' is in preview.
```

```
$ az webapp
the following arguments are required: _subcommand

Examples from AI knowledge base:
az webapp list --query "[].{hostName: defaultHostName, state: state}"
List default host name and state for all web apps.

https://docs.microsoft.com/en-US/cli/azure/webapp#az_webapp_list
Read more about the command in reference docs
```

---

Azure CLI version is below.

```
$ az -v
azure-cli                         2.36.0

core                              2.36.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.66
spring-cloud                       3.1.4
customlocation                     0.1.3
connectedk8s                       1.2.8
appservice-kube                    0.1.6
k8s-extension                      1.2.1
ai-examples                        0.2.5
ssh                                1.1.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/tkmbmbr/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.8/site-packages/azure-cli-extensions'

Python (Linux) 3.8.13 (default, Apr 22 2022, 04:53:00) 
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Comment by RakeshMohanMSFT** [comment] 2022-05-15 08:52
@tsubakimoto Glad to hear that the issue is resolved. Closing the issue.

**Closed by RakeshMohanMSFT** 2022-05-15 08:52 UTC
Labels: Web Apps, customer-reported, needs-team-attention, CXP Attention, Auto-Assign
