### ISSUE TITLE
az storage container create 

### ISSUE THREAD

**Issue by rebecca-makar** [Azure/azure-cli#13401] opened 2020-05-08 14:16 UTC
> ### `az storage container create`

**Describe the bug**
Have this automated in azure devops pipelines, have been using same az command for months and this broke from last night to this morning. Microsoft Internal user.
`2020-05-05T15:40:55.3539676Z The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue 2020-05-05T15:40:55.3542457Z <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format. 2020-05-05T15:40:55.3544065Z RequestId<requstidNum> 2020-05-05T15:40:55.3545698Z Time:2020-05-05T15:40:55.3535810Z</Message><HeaderName>x-ms-blob-public-access</HeaderName><HeaderValue>off</HeaderValue></Error> 2020-05-05T15:40:55.4536092Z ##[error]Blob container (<NAME>) creation failed. See log for details`

**To Reproduce**
create storage account
try to create storagecontainer 
**Expected behavior**
Storage container created

**Environment summary**
I am using azure devops Ubuntu 16.04: here is what is on image: [Ubuntu1604-github-readme](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1604-README.md
)
It is installing: az cli version 2.3.1

If during my setup, I install az cli 2.2.0 the az storage container create command will work fine. 
Also able to use UI/postman, so I am unsure where there is a misconnect happening.

**Comment by yungezz** [comment] 2020-05-08 23:38
hi @Juliehzl could you pls have a look?

**Comment by yonzhan** [comment] 2020-05-09 03:28
add to S170

**Comment by RickLatrine** [comment] 2020-05-14 15:31
identical issue for me.

az cli versions used in DevOps:
azure-cli: 2.5.1
command-modules-nspkg: 2.0.3
core: 2.5.1
nspkg: 3.0.4
telemetry: 1.0.4

**Comment by MKruger777** [comment] 2020-05-14 17:29
I think I am seeing the same result. Until now I was creating the storage container via the az command line from within the azure-cli container : 
`docker run -it mcr.microsoft.com/azure-cli:latest `

command:
`az storage container create -n $BLOB_CONTAINER --public-access off --account-name $AZURE_STORAGE_ACCOUNT_ID`

Running this command in the container works perfectly every time.

I just installed the az cli on my ubuntu 18.04 by running:
`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`
(As instructed [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest))

Running the same command (that works fine from within the container) now fails on the newly installed az cli on my ubuntu command line.

err message:
```
The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:8c3999ec-f01e-0026-630e-2a8a3b000000
Time:2020-05-14T16:37:56.2754781Z</Message><HeaderName>x-ms-blob-public-access</HeaderName><HeaderValue>off</HeaderValue></Error>
```

Any ideas?

**Comment by ttalal** [comment] 2020-05-15 07:34
I have the same issue

**Comment by Juliehzl** [comment] 2020-05-20 08:08
dupe of #13373

**Comment by Juliehzl** [comment] 2020-05-20 08:10
It is fixed in latest azure cli. please try with https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest.

**Comment by MKruger777** [comment] 2020-05-25 15:54
I just tested it on my Ubuntu 18.04 with version:
  "azure-cli": "2.6.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.6.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}

Works like a charm - thanks so much, much appreciated! :-)

**Closed** 2020-05-25 23:06 UTC
Labels: Storage
