### ISSUE TITLE
`apt-get update` for https://packages.microsoft.com/ randomly fails with "server certificate verification failed"

### ISSUE THREAD

**Issue by usternik** [Azure/azure-cli#19405] opened 2021-08-31 16:32 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Installing azure cli via the installation script or by running the manual installation fails at random.
As part of our CI/CD process, we need to install the azure cli. With no apparent reason, sometimes it works and sometimes it does't. When it fails, it fails with an error about the certificate of packages.microsoft.com
```
The following NEW packages will be installed:
  azure-cli
0 upgraded, 1 newly installed, 0 to remove and 249 not upgraded.
Need to get 63.1 MB of archives.
After this operation, 924 MB of additional disk space will be used.
Err https://packages.microsoft.com/repos/azure-cli/ trusty/main azure-cli all 2.27.2-1~trusty
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.27.2-1~trusty_all.deb  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
I tried adding apt-get update --fix-missing.
I tried adding `trusted=yes` in the configuration of the repo in the /etc/apt/sources.list.d/azure-cli.list file.
And I tried running it with this script:
```
sudo apt-get update
sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
echo -n | openssl s_client -showcerts -connect packages.microsoft.com:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /usr/local/share/ca-certificates/packages.microsoft.com.crt
update-ca-certificates --fresh
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
sudo apt-get update
sudo apt-get install azure-cli
```
But still no luck. It works most of the times, but when it doesn't, it breaks the build, and I don't know why it doesn't work.

**To Reproduce**
install az cli via script or manually 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Expected behavior**
Install the az cli with no problems.

**Environment summary**
Interactive script. Tried to reproduce it by connecting to the container with ssh and still most of the time it worked, but sometime it would still fail.

**Additional context**
It appears to be a problem with the apt-get update command / A problem with packages.microsoft.com

**Comment by yonzhan** [comment] 2021-08-31 22:26
@jiasli for awareness

**Comment by nakazonot** [comment] 2021-09-02 10:52
The certificate for the packages.microsoft.com domain seems to randomly return one for August 13, 2022, and one for September 20, 2021.
Could this be the problem?

Maybe the error occurs when the certificate retrieved for installation does not match the certificate returned during installation?

**Comment by usternik** [comment] 2021-09-02 11:19
> I am having the same problem.
> 
> The certificate for the packages.microsoft.com domain seems to randomly return one for August 13, 2022, and one for September 20, 2021.
> Could this be the problem?
> 
> Maybe the error occurs when the certificate retrieved for installation does not match the certificate returned during installation?

hey, 
what command did you use to check the certificate return? how did you see it?

a workaround i used is to run the apt-get update and apt-get install azure-cli with the `-o Acquire::https::packages.microsoft.com::Verify-Peer="false"` flag
like so: `sudo apt-get -o Acquire::https::packages.microsoft.com::Verify-Peer="false" update`

**Comment by nakazonot** [comment] 2021-09-02 11:32
confirmed that there are two certificates by accessing the site from a browser.

I'll use the Verify-Peer option until it's resolved. Thank you.

**Comment by jiasli** [comment] 2021-09-03 03:17
I tried to get the cert from https://packages.microsoft.com/ but couldn’t repro:

```
$ openssl s_client -showcerts -servername packages.microsoft.com -connect packages.microsoft.com:443 </dev/null | openssl x509 -text
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 06
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = packages.microsoft.com
verify return:1
DONE
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            33:00:18:e5:3a:6d:46:a1:ba:59:0e:5f:dc:00:00:00:18:e5:3a
        Signature Algorithm: sha384WithRSAEncryption
        Issuer: C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 06
        Validity
            Not Before: Aug 17 18:30:20 2021 GMT
            Not After : Aug 12 18:30:20 2022 GMT
        Subject: C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = packages.microsoft.com
```

It looks like the invalid certificate is only returned by some CDN nodes. I will reach out to https://packages.microsoft.com/ team to take a look.

**Comment by nakazonot** [comment] 2021-09-03 04:27
I tried to run the command from Japan, but the contents seem to be different.
```
openssl s_client -showcerts -servername packages.microsoft.com -connect packages.microsoft.com:443 </dev/null | openssl x509 -text

depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 02
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = packages.microsoft.com
verify return:1
poll errorCertificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            33:00:01:80:ae:ae:d5:76:c6:5a:49:8e:e5:00:00:00:01:80:ae
    Signature Algorithm: sha384WithRSAEncryption
        Issuer: C=US, O=Microsoft Corporation, CN=Microsoft Azure TLS Issuing CA 02
        Validity
            Not Before: Sep 24 18:22:10 2020 GMT
            Not After : Sep 19 18:22:10 2021 GMT
        Subject: C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=packages.microsoft.com

```

**Comment by nakazonot** [comment] 2021-09-03 04:58
I tried the command again and this time it was something else.

```
openssl s_client -showcerts -servername packages.microsoft.com -connect packages.microsoft.com:443 </dev/null | openssl x509 -text

depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 06
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = packages.microsoft.com
verify return:1
poll errorCertificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            33:00:18:e5:3a:6d:46:a1:ba:59:0e:5f:dc:00:00:00:18:e5:3a
    Signature Algorithm: sha384WithRSAEncryption
        Issuer: C=US, O=Microsoft Corporation, CN=Microsoft Azure TLS Issuing CA 06
        Validity
            Not Before: Aug 17 18:30:20 2021 GMT
            Not After : Aug 12 18:30:20 2022 GMT
        Subject: C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=packages.microsoft.com
```

**Comment by jiasli** [comment] 2021-09-03 05:08
@nakazonot, this is because the Microsoft Linux repo is rotating the certificate as the old one expires at **Sep 19 18:22:10 2021 GMT**. Are you seeing any failure? Also, could you share the result if you run both commands?

```
nslookup packages.microsoft.com
openssl s_client -showcerts -servername packages.microsoft.com -connect packages.microsoft.com:443 </dev/null | openssl x509 -text
```

**Comment by nakazonot** [comment] 2021-09-03 05:26
@jiasli
Probably because there are two certificates, the installation from packages.microsoft.com causes a certificate error.

In fact, there is about a 1/2 chance of getting a certificate error.

```
$ nslookup packages.microsoft.com
Server:		192.168.11.1
Address:	192.168.11.1#53

Non-authoritative answer:
packages.microsoft.com	canonical name = apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net	canonical name = csd-apt-eas-d-4.eastasia.cloudapp.azure.com.
Name:	csd-apt-eas-d-4.eastasia.cloudapp.azure.com
Address: 40.83.79.38

$ openssl s_client -showcerts -servername packages.microsoft.com -connect packages.microsoft.com:443 </dev/null | openssl x509 -text
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 02
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = packages.microsoft.com
verify return:1
poll errorCertificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            33:00:01:80:ae:ae:d5:76:c6:5a:49:8e:e5:00:00:00:01:80:ae
    Signature Algorithm: sha384WithRSAEncryption
        Issuer: C=US, O=Microsoft Corporation, CN=Microsoft Azure TLS Issuing CA 02
        Validity
            Not Before: Sep 24 18:22:10 2020 GMT
            Not After : Sep 19 18:22:10 2021 GMT
        Subject: C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=packages.microsoft.com
```

**Comment by jiasli** [comment] 2021-09-03 05:31
This certificate is still valid:

```
Not After : Sep 19 18:22:10 2021 GMT
```

Actually both certificates are valid. Do you have some other settings that block a valid certificate? Could you check if the time of your machine is correct?

```
$ date
Fri Sep  3 13:30:55 CST 2021
```

**Comment by nakazonot** [comment] 2021-09-03 05:45
Yes, I think it's valid.

The following command is executed when installing azure-cli.
Is it possible that different certificates are used by curl and apt-get?
```
sudo apt-get update
sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg

curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    sudo tee /etc/apt/sources.list.d/azure-cli.list

sudo apt-get update
sudo apt-get install azure-cli
```

```
$ date --iso-8601=seconds
2021-09-03T05:39:41+0000
```

**Comment by jiasli** [comment] 2021-09-03 06:01
> Is it possible that different certificates are used by curl and apt-get?

It is possible if requests from `curl` and `apt` are load-balanced to different servers.

I tried both the nodes returning old cert and new cert, and both work fine:

```sh
# Old cert

$ nslookup packages.microsoft.com
Name:   csd-apt-sea-d-4.southeastasia.cloudapp.azure.com
Address: 40.65.182.21

$ openssl s_client -showcerts -servername packages.microsoft.com -connect 40.65.182.21:443 </dev/null | openssl x509 -text
Not After : Sep 19 18:22:10 2021 GMT

$ curl https://packages.microsoft.com --resolve packages.microsoft.com:443:40.65.182.21
<html>
<head><title>Index of /</title></head>


# New cert

$ nslookup csd-apt-sea-d-1.southeastasia.cloudapp.azure.com
Name:   csd-apt-sea-d-1.southeastasia.cloudapp.azure.com
Address: 52.230.121.169

$ openssl s_client -showcerts -servername packages.microsoft.com -connect 52.230.121.169:443 </dev/null | openssl x509 -text
Not After : Aug 12 18:30:20 2022 GMT

$ curl https://packages.microsoft.com --resolve packages.microsoft.com:443:40.65.182.21
<html>
<head><title>Index of /</title></head>
```

**Comment by nakazonot** [comment] 2021-09-03 06:15
The command worked fine for both old cert and new cert.

So, what I wanted to say was...

For example, the following command is executed with old cert.
```
curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
```

Then, run the following command with new cert.

```
sudo apt-get update
sudo apt-get install azure-cli
```

If I do that, won't the certificates mismatch?

**Comment by jiasli** [comment] 2021-09-03 06:47
I don't think it is relevant. https://packages.microsoft.com/keys/microsoft.asc is the certificate used by Microsoft to sign the package, but the failed certificate is for TLS/HTTPS.

**Comment by nakazonot** [comment] 2021-09-03 06:55
I see. Then what is it?

When I run the azure-cli install command from an empty VM in CircleCI, I get "server certificate verification failed" about 1/2 of the time.

**Comment by jshimazu** [comment] 2021-09-03 09:38
I'm having the same problem since several days ago, I'm also using CircleCI.
Is it CircleCI's problem?

**Comment by jiasli** [comment] 2021-09-03 09:55
As we haven't received any report from users of Azure DevOps and other platforms, could you report this problem to CircleCI to take a look? It is possible that the CA of one of the certificates is not trusted. 

```
openssl s_client -showcerts -servername packages.microsoft.com -connect 40.65.182.21:443 </dev/null | openssl x509 -text
openssl s_client -showcerts -servername packages.microsoft.com -connect 52.230.121.169:443 </dev/null | openssl x509 -text
```

**Comment by nakazonot** [comment] 2021-09-03 09:57
The cause was a certificate mismatch.

When I tried, ca-certificates.crt contained an old cert.

When I modified the hosts file to specify that apt-get should use the new cert, I got the following error.

```
server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

I modified the hosts file to specify that apt-get should use the old cert, and the following error disappeared.

**Comment by jiasli** [comment] 2021-09-03 10:48
I checked the certificate chain and both use the same root CA:

```
 1 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
-----BEGIN CERTIFICATE-----
MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI
2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx
1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQ
q2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5Wz
tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
vIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAP
BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV
5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY
1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4
NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NG
Fdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ91
8rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTe
pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
MrY=
-----END CERTIFICATE-----
```

which appears in `/etc/ssl/certs/ca-certificates.crt`. Could you share your `/etc/ssl/certs/ca-certificates.crt`?

**Comment by nakazonot** [comment] 2021-09-03 11:13
attach the [ca-certificates.crt.txt](https://github.com/Azure/azure-cli/files/7105359/ca-certificates.crt.txt) file.
In my case, the following command caused an error.

```
sudo apt-get remove azure-cli
sudo rm /var/cache/apt/archives/azure-cli_2.27.2-1~trusty_all.de
echo "52.230.121.169 packages.microsoft.com" | sudo tee -a /etc/hosts
sudo apt-get install azure-cli
```

**Comment by jiasli** [comment] 2021-09-03 13:15
I can repro, but this problem only happens to Ubuntu Trusty 14.04.

```
docker run -it --rm ubuntu:trusty
```

```sh
# Force packages.microsoft.com to resolve to csd-apt-sea-d-1.southeastasia.cloudapp.azure.com 52.230.121.169,
# which returns the new cert
echo "52.230.121.169 packages.microsoft.com" | tee -a /etc/hosts

apt-get update
apt-get install ca-certificates curl apt-transport-https lsb-release gnupg

curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    tee /etc/apt/sources.list.d/azure-cli.list

# This fails!
apt-get update
>> W: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

# But this works!
curl https://packages.microsoft.com --resolve packages.microsoft.com:443:52.230.121.169
```

Ubuntu Focal 20.04 on the other hand works correctly:

```
docker run -it --rm ubuntu:focal
```

**Comment by jiasli** [comment] 2021-09-03 13:31
One Trust, `openssl` fails with `verify error:num=19:self signed certificate in certificate chain`.

Also, the certificate order is not correct. Not sure if this is related.

```
# openssl s_client -showcerts -servername packages.microsoft.com -connect 52.230.121.169:443 </dev/null
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/CN=packages.microsoft.com
   i:/C=US/O=Microsoft Corporation/CN=Microsoft Azure TLS Issuing CA 06
-----BEGIN CERTIFICATE-----
MIIIbzCCBlegAwIBAgITMwAY5TptRqG6WQ5f3AAAABjlOjANBgkqhkiG9w0BAQwF
...
GEXnqRuAR8lC1I2UJIo7Ewbzya0ZDoqdrrREKHs8rvRdaW4bZJS4H1kFgxzd8Kf1
Bgzz
-----END CERTIFICATE-----
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
-----BEGIN CERTIFICATE-----
MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
...
pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
MrY=
-----END CERTIFICATE-----
 2 s:/C=US/O=Microsoft Corporation/CN=Microsoft Azure TLS Issuing CA 06
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
-----BEGIN CERTIFICATE-----
MIIF8zCCBNugAwIBAgIQAueRcfuAIek/4tmDg0xQwDANBgkqhkiG9w0BAQwFADBh
...
8y4m/HyTQeI2IMvMrQnwqPpY+rLIXyviI2vLoI+4xKE4Rn38ZZ8m
-----END CERTIFICATE-----
```

The cert `s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2` does exist in `/etc/ssl/certs/ca-certificates.crt`:

```
# cat /etc/ssl/certs/ca-certificates.crt | grep tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
```

Ubuntu focal works correctly.

**Comment by jiasli** [comment] 2021-09-03 13:50
A summary of different systems and `openssl version`:

- Trusty 14.04 / OpenSSL 1.0.1f 6 Jan 2014 ❌
- Xenial 16.04 / OpenSSL 1.0.2g  1 Mar 2016 ✔
- Bionic 18.04 / OpenSSL 1.1.1  11 Sep 2018 ✔
- Focal 20.04 / OpenSSL 1.1.1f  31 Mar 2020 ✔

**Comment by jiasli** [comment] 2021-09-04 02:44
# Summary

## Root Cause

We recently updated the TLS/SSL certificate on half of the mirrors of `packages.microsoft.com` gradually in a rolling fashion. 14 mirrors with the new certificate have this issue, and the remaining 14 mirrors are good as of now as they still use the old valid certificate. 

The issue with the new certificate seems to be caused by **reversed order of the intermediate CA and root CA**. This is causing problem in an older version of Linux (Ubuntu Trusty 14.04) and seems to be fine on newer version of Linux (Ubuntu Xenial 16.04, Bionic 18.04 and Focal 20.04). So the problem is isolated as of now to Ubuntu Trusty.

## Solution

We were able to reproduce this issue in our Pre-Production Environment with a Trusty machine. We changed the order of certificate in our Pre-Production Environment and the issue seems to be resolved in Ubuntu Trusty.

We will roll out the fixed new certificate for impacted machines (14 mirrors out of 28) next week after the long weekend (Monday, September 6th is US Labor Day holiday). 

## Mitigation

In the meantime, the mitigation is to ask `apt`/`apt-get` to trust the `packages.microsoft.com` SSL certificate:

```
sudo apt-get -o Acquire::https::packages.microsoft.com::Verify-Peer="false" update
sudo apt-get -o Acquire::https::packages.microsoft.com::Verify-Peer="false" install azure-cli
```

@usternik, @nakazonot, @jshimazu, thank you so much for reporting this issue and all the valuable information provided!

**Comment by jiasli** [comment] 2021-09-09 03:16
We have deployed the fixed new certificate to these regions:

| Node                                             | IP Address     |
| ------------------------------------------------ | -------------- |
| csd-apt-sea-d-1.southeastasia.cloudapp.azure.com | 52.230.121.169 |
| csd-apt-sea-d-2.southeastasia.cloudapp.azure.com | 20.188.102.6   |
| csd-apt-eas-d-1.eastasia.cloudapp.azure.com      | 13.75.64.135   |
| csd-apt-eas-d-2.eastasia.cloudapp.azure.com      | 65.52.183.205  |

I have tested these nodes with the script in https://github.com/Azure/azure-cli/issues/19405#issuecomment-912531180, and everything is working as expected.

**Comment by nakazonot** [comment] 2021-09-14 11:31
Thank you @jiasli, it worked fine.

**Comment by uncycler** [comment] 2023-04-18 18:34
I guess I can bump this issue!

![image](https://user-images.githubusercontent.com/1673467/232871113-d0348d63-ddf5-4269-b425-e8dbfdccf438.png)

I guess the process wasn't improved since...

**Comment by jiasli** [comment] 2023-04-19 00:58
@uncycler, we are tracking the expired certificate issue in https://github.com/Azure/azure-cli/issues/26182.

**Comment by jiasli** [comment] 2023-05-31 00:53
@trailstrider, please create a new issue with error message you got and the following commands' output:

```
$ nslookup packages.microsoft.com
$ openssl s_client -showcerts -servername packages.microsoft.com -connect packages.microsoft.com:443 </dev/null | openssl x509 -text
```

**Closed by jiasli** 2023-05-31 00:53 UTC
Labels: feature-request, Linux Repo
