### ISSUE TITLE
az interactive command on ubuntu 20 powershell

### ISSUE THREAD

**Issue by arthurgichuhi** [Azure/azure-cli#24165] opened 2022-10-12 07:44 UTC
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/home/gichuhi/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/home/gichuhi/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 33, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-5.15.0-48-generic-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0

Extensions:
interactive 0.4.5

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-10-12 08:35
interactive

**Comment by navba-MSFT** [comment] 2022-10-13 03:20
@arthurgichuhi Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-10-13 06:16
@arthurgichuhi Tagging the similar issue here : https://github.com/Azure/azure-cli/issues/10088. Please follow the below action plan for now:

1. If you installed through pip, run `pip uninstall prompt-toolkit`
2. If you installed through Windows installer, delete `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\prompt_toolkit`
3. If you installed through Linux bundle, find the installation location and delete the package folder. Say for Ubuntu, the folder would be `/opt/az/lib/python3.6/site-packages/prompt_toolkit`

Please let me know if you still face any issues.  Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-10-17 05:49
@arthurgichuhi I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by jiasli** [comment] 2022-10-19 06:47
Duplicate of #24213

**Closed by jiasli** 2022-10-19 06:47 UTC
Labels: Interactive, customer-reported, needs-author-feedback, feature-request, CXP Attention, Auto-Assign, Azure CLI Team
