### ISSUE TITLE
az vm extension image list doesn't show all versions

### ISSUE THREAD

**Issue by darrinthomascecil** [Azure/azure-cli#19296] opened 2021-08-20 19:59 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

The package aadsshlogin-selinux-1.0.016890001-1.x86_64.rpm was recently pushed after a GPG  key bug fix, but does not show up when listing images

**To Reproduce**

az vm extension image list -l westus2 --publisher Microsoft.Azure.ActiveDirectory --output table
Name                 Publisher                                 Version
-------------------  ----------------------------------------  ----------
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1553.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1560.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1588.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1595.1                                                                                             

**Expected behavior**

Should include 1.0.016890001

**Environment summary**

azure-cli    2.0.81
bash

**Additional context**

**Comment by yonzhan** [comment] 2021-08-20 23:47
Compute

**Comment by zhoxing-ms** [comment] 2021-08-24 06:28
In fact, CLI only requests REST [virtual-machine-extension-images/list-versions](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-extension-images/list-versions) and displays the returned results from REST directly. Therefore, this may be the service related issue.

@darrinthomascecil Could you provide us with the specific debug logs to investigate this issue? Please add `--debug` after the original executed command, then send us the printed information by email

**Comment by amjads1** [comment] 2021-08-24 18:05
Looking into the issue.

**Comment by zhoxing-ms** [comment] 2021-08-25 06:39
> AADSSHLoginForLinux Microsoft.Azure.ActiveDirectory 1.0.1553.1
AADSSHLoginForLinux Microsoft.Azure.ActiveDirectory 1.0.1560.1
AADSSHLoginForLinux Microsoft.Azure.ActiveDirectory 1.0.1588.1
AADSSHLoginForLinux Microsoft.Azure.ActiveDirectory 1.0.1595.1

According to the debug log provided by @darrinthomascecil, service only returns the above images

Request URL: /subscriptions/{subscription}/providers/Microsoft.Compute/locations/westus2/publishers/Microsoft.Azure.ActiveDirectory/artifacttypes/vmextension/types/AADSSHLoginForLinux/versions?api-version=2019-07-01

**'x-ms-correlation-request-id': '336a90c3-4aff-4f51-8bb5-1e8c79e1dffd'**

**Comment by amjads1** [comment] 2021-09-09 06:57
@darrinthomascecil Received the debug log details from @zhoxing-ms and currently going through the log details. I will update here as soon as I find anything on this issue.

**Comment by zhoxing-ms** [comment] 2021-09-09 07:38
@grizzlytheodore Could you please help to look at this issue?

**Comment by amjads1** [comment] 2021-09-23 06:58
Issue is still under investigation and will update back as soon as I have more information.

**Comment by amjads1** [comment] 2021-10-07 08:04
Issues seems to be related to API as the CLI returns the result of the REST API call but all the versions are not returned in the debug.  Need to work with extensions team and will update back soon.

**Comment by axelgMS** [comment] 2021-10-12 07:52
@darrinthomascecil I'm getting the following output when running the command

```
az vm extension image list -l westus2 --publisher Microsoft.Azure.ActiveDirectory --output table
Name                 Publisher                                 Version
-------------------  ----------------------------------------  ----------
...
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1553.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1560.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1588.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1595.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1713.1
...
```

So not seeing 1.0.016890001 or 1.0.1689.1 either.
Looking at the backend logs, and the Platform Image Repository only returns the 5 versions above - which makes me think it wasn't published correctly - and that it's not an issue with Azure CLI.

When was the package pushed? Did you get in touch with the MS team in charge of publishing ?

**Comment by amjads1** [comment] 2021-11-04 17:44
@darrinthomascecil - Based on the above comments, can you confirm when the package was pushed and if you are still experiencing the issue?

**Comment by amjads1** [comment] 2021-12-09 07:59
@darrinthomascecil - Can you please confirm if the issue is still there? Otherwise, we can close this item.

**Comment by amjads1** [comment] 2022-01-13 20:05
Closing this issue and feel free to re-open if you need any further help. Thanks!

**Closed by amjads1** 2022-01-13 20:05 UTC
Labels: Compute, Service Attention, customer-reported
