### ISSUE TITLE
error loading command module 'aro' while login

### ISSUE THREAD

**Issue by artnim** [Azure/azure-cli#24330] opened 2022-10-21 13:37 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/lib/python3/dist-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/usr/lib/python3/dist-packages/azure/cli/core/auth/identity.py", line 112, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/usr/lib/python3/dist-packages/msal/application.py", line 1525, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- kept kali up to date (sudo apt upgrade && sudo apt upgrade -y) as of 2022-10-20
- `az login`

## Expected Behavior

az login without complaining about missing modules 

## Environment Summary
```
Linux-5.19.0-kali2-amd64-x86_64-with-glibc2.35, Kali GNU/Linux Rolling
Python 3.10.7
Installer: DEB

azure-cli 2.41.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment] 2022-10-21 23:30
@jiasli for awareness

**Comment by bebound** [comment] 2022-10-24 02:45
Duplicate of #19640

**Closed by bebound** 2022-10-24 02:45 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
