### ISSUE TITLE
Found multiple accounts with the same username

### ISSUE THREAD

**Issue by yzhangCrestron** [Azure/azure-cli#29289] opened 2024-07-01 16:41 UTC
### Describe the bug

I need to download some frameworks, so in the terminal app (from MacOS) , enter the command "az login --allow-no-subscriptions", I got the following response with error from the terminal:

A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.

Retrieving tenants and subscriptions for the selection...
Found multiple accounts with the same username 

### Related command

az login --allow-no-subscriptions

### Errors

Found multiple accounts with the same username 

### Issue script & Debug output

Found multiple accounts with the same username 

### Expected behavior

I hope the download the frameworks, which I need.

### Environment Summary

azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/bin/python'
Extensions directory '/Users/yzhang/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment] 2024-07-01 16:42
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-07-02 07:28
Duplicate of https://github.com/Azure/azure-cli/issues/20168

**Closed by jiasli** 2024-07-02 07:28 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team, Auto-Resolve, Similar-Issue, Possible-Solution

**Comment by asouzajunior** [comment] 2024-09-24 14:22
Same issue here. Nothing works.
