### ISSUE TITLE
microsoft/azure-cli:2.0.53 docker image az cli dont work

### ISSUE THREAD

**Issue by rscoz** [Azure/azure-cli#8087] opened 2018-12-18 17:42 UTC
**Describe the bug**
microsoft/azure-cli:2.0.53 docker image dont work

**To Reproduce**
docker run -it microsoft/azure-cli:2.0.53 az --version
standard_init_linux.go:207: exec user process caused "exec format error"

**Expected behavior**
az cli works.

**Environment summary**
Official docker image.

**Comment by marstr** [comment] 2018-12-18 21:50
I can confirm that this repro's, thanks for bringing this to our attention.

**Comment by yugangw-msft** [comment] 2018-12-18 22:45
//CC @tjprescott

**Comment by marstr** [comment] 2018-12-18 23:45
> @marstr says:
> We would have caught this error had our test been as follows:
> 
> docker run $IMAGE_NAME time az self-test &&
> docker run $IMAGE_NAME time az --version

I have modified our Prerelease build pipeline to test the image in the way mentioned here. Sure enough, it now catches this issue.

**Comment by marstr** [comment] 2018-12-18 23:48
I have kicked a new build to generate a fixed Docker image.

**Comment by marstr** [comment] 2018-12-19 00:41
I have now pushed updated images to Docker Hub images `microsoft/azure-cli:latest` and `microsoft/azure-cli:2.0.53`. @williexu tested this from his machine to validate that this no longer repros.

**Comment by marstr** [comment] 2018-12-19 00:42
@rscoz, mind validating that this is now fixed?

**Comment by marstr** [comment] 2018-12-19 01:40
I'm going to close this until I hear back, because I am not able to repro this from @JMstrobel's machine, who had never pulled an Azure CLI image before.

**Closed by marstr** 2018-12-19 01:40 UTC
Labels: Packaging/Docker, bug

**Comment by rscoz** [comment] 2018-12-19 11:09
It's working perfectly now, thank you.
