### ISSUE TITLE
[WebToolsE2E][ARM64] When running the "az login" command, an error message displayed saying 'User cancelled the accounts control operation'.

### ISSUE THREAD

**Issue by ymmendoza** [Azure/azure-cli#29293] opened 2024-07-02 06:25 UTC
**INSTALL STEPS**
1. Clean machine: Win11 Arm64
2. Install VS VS 17.11 Preview 3: main-35030.12 
   • Web workload + Maui workload + Nodejs workload 
   • Check 6.0 runtime under IC 

**REPRO STEPS**
1. Install Azure CLI (Latest MSI of the Azure CLI (64-bit)).
2. Open Command Prompt and run command "az login"

**ACTUAL**
The "az login" command isn't working in CMD after you select your account in the web browser.

Run 'az login'
![image](https://github.com/Azure/azure-cli/assets/157694450/3177b8d6-32e1-411f-a97d-8e3b86aaebe4)

**EXPECTED**
After Successfully install Azure CLI Latest MSI of the Azure (64-bit).
and Run the 'az login' command the account login should be successful

**Note:** 
This issue does not repro in arm machines from DTL
This issue can repro in VSJADE Arm machine

**Comment by yonzhan** [comment] 2024-07-02 06:25
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-07-02 07:29
Duplicate of #28997

**Closed by jiasli** 2024-07-02 07:29 UTC
Labels: Account, question, Auto-Assign, Azure CLI Team

**Comment by ymmendoza** [comment] 2024-07-02 08:37
This workaround works for me:

az account clear
az config set core.enable_broker_on_windows=false
az login

This issue will be fixed in Azure CLI 2.62.0. The target release date is 07-09-2024.
