### ISSUE TITLE
“Az Snapshot Create” fails with 404 when the Managed Disk and Resource Group locations are different.

### ISSUE THREAD

**Issue by RishiMaini** [Azure/azure-cli#11909] opened 2020-01-20 13:55 UTC
“Az Snapshot Create” fails with 404 when the Managed Disk and Resource Group locations are different.

Steps to repro 
===============
Create a Resource Group in location 1

Create a managed disk under the same Resource Group but the Managed disk location should be different from Resource Group location.

Now if you try to create a Snapshot of the Disk using “Az Snapshot Create”, it will fail with 404 error.

Same operation works either through PowerShell or directly from portal.

abc@Azure:~$ az snapshot create -g "DiskRG" -n "Snap99" --source "testdisk2"
**Resource testdisk2 is not found.**

Looks like Az Snapshot is checking for Disk existence under the Resource Group location rather than actual disk location.

Expectation is that CLI command should also work fine independent of Resource Group and Disk location, just like PowerShell and Portal.

This is same issue as https://github.com/Azure/azure-cli/issues/9233 which was closed earlier without further research.

**Comment by yonzhan** [comment] 2020-01-21 13:43
issue labelled.

**Comment by qwordy** [comment] 2020-03-17 08:28
I reproduce the problem using the following code.
```
az group create -g fyrg1 -l westus
az disk create -g fyrg1 -n d1 --size-gb 10 -l eastus
az snapshot create -g fyrg1 -n s1 --source d1
```
Some logs of `snapshot create` command
```
Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/fyrg1/providers/Microsoft.Compute/snapshots/s1?api-version=2019-07-01'
Request body:
{"location": "westus", "tags": {}, "sku": {"name": "Standard_LRS"}, "properties": {"hyperVGeneration": "V1", "creationData": {"createOption": "Copy", "sourceResourceId": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/fyrg1/providers/Microsoft.Compute/disks/d1"}}}
Response content:
{
  "error": {
    "code": "NotFound",
    "message": "Resource d1 is not found."
  }
}
```
Azure CLI doesn't have location limitation in this command. In this example, it sends request to service and gets an error from service. I am not very familiar with PowerShell. Can you share PowerShell commands? Or can you paste HTTP request of PowerShell snapshot create command from log if the log has this info? Thank you!

**Comment by RishiMaini** [comment] 2020-03-18 08:15
Hi Feiyue, In your example CLI definitely has issues with location since its expecting to see the disk in RG location(WestUS) and not the actual disk location (EastUS). Thus the error.

Below is the PowerShell example that you were looking for which just works fine.

New-AzResourceGroup -ResourceGroupName "fyrg3" -Location "westus"

$diskConfig = New-AzDiskConfig -Location "EastUS" -CreateOption Empty -DiskSizeGB 1

$managedDisk = New-AzDisk -ResourceGroupName "fyrg3" -DiskName "myDisk" -Disk $diskConfig

$snapshotConfig = New-AzSnapshotConfig -SourceResourceId $managedDisk.Id -Location $managedDisk.Location 

New-AzSnapshot -ResourceGroupName 'fyrg3' -SnapshotName 'Snapshot01' -Snapshot $snapshotconfig

**Comment by qwordy** [comment] 2020-03-27 03:07
In your commands, the disk and snapshot are in same location.
The equivalent CLI commands of powershell commands you provided are
```
az group create -g fyrg1 -l westus
az disk create -g fyrg1 -n d1 --size-gb 10 -l eastus
az snapshot create -g fyrg1 -n s1 --source d1 -l eastus
```
It succeeds.
And if I change
```
$snapshotConfig = New-AzSnapshotConfig -SourceResourceId $managedDisk.Id -Location $managedDisk.Location -CreateOption "Copy"
```
into
```
$snapshotConfig = New-AzSnapshotConfig -SourceResourceId $managedDisk.Id -Location "westus" -CreateOption "Copy"
```
I get the same error `Resource myDisk is not found`.
Add a service attention to confirm with service team if it is possible to create a snapshot from a disk in different location.

**Comment by RishiMaini** [comment] 2020-03-30 08:07
Creating snapshot in different locations might not be possible which is understood and might require another approach as mentioned in Export/Copy a snapshot to a storage account in different region with CLI
 
Concern is creating snapshot in the same location but under a destination RG where RG location is different from the source snapshot location.
 
Here is the problem :- CLI should be smart enough to detect the location of the resources that is getting copied. It should not depend on location of Resource Group when, for the Copy/Create process we have already mentioned the ResourceID of the copy source. Example as below :- 
 
 
A.	Create RG named  “fyrg1" , disk and snapshot all in same location “eastUS”
B.	Create RG named “fyrg2" In different location , let’s say “WestUS”
C.	Try to create/copy the snapshot in “fyrg2” specifying the source of copy as snapshot under “fyrg1” (which is in “eastUS”) This will fail with error ResourceNotFound since CLI is assuming that source snapshot location is “WestUS” (same as that of destination RG “fyrg2" , rather than the actual location of the source snapshot which is “eastUS”)
D.	If “fyrg2” was in same location i.e. “EastUS” , everything works fine.
 
 
 
az group create -g fyrg1 -l eastus
az disk create -g fyrg1 -n d1 --size-gb 1 -l eastus
az snapshot create -g fyrg1 -n s1 --source d1 -l eastus
 
az group create -g fyrg2 -l westus
az group create -g fyrg3 -l eastus
 
snapshotId=$(az snapshot show --name s1 --resource-group fyrg1 --query [id] -o tsv)
echo 'source snapshot Id is: ' $snapshotId
 
az snapshot create --resource-group fyrg2 --name s2 --source $snapshotId --sku Standard_LRS  ==> This fails since “fyrg2” location is “WestUS” which is different from Source snapshot location , which is “eastUS”
 
az snapshot create --resource-group fyrg3 --name s2 --source $snapshotId --sku Standard_LRS ==> This works fine since “fyrg3” location and Source snapshot location are same i.e. “EastUS”.
 
 
 
 
Possible workaround is to specify the "--location" parameter. 
 
 
az snapshot create --resource-group fyrg2 --name s2 --source $snapshotId --sku Standard_LRS --location eastus ==>This works fine irrespective of RG location.
 
 
Now as per DOCS for “az snapshot create", it does not call out what the “location” means here . Is it source snapshot location, destination snapshot location ?
 
--location -l
Location. Values from: az account list-locations. You can configure the default location using az configure --defaults location=<location>.

**Comment by qwordy** [comment] 2020-03-31 03:43
```
az snapshot create -g fyrg2 -n s2 –source s1 -l eastus
```
In this command, “-l” means the snapshot you are going to create is located in eastus.
If “-l” is omitted, location will be same as fyrg2.
You can always use “-l” to specify location explicitly to make the command more clear.
If s1 is a name, Azure CLI will automatically transform it to an ID with assumption of s1 is in fyrg2 in default subscription.
If s1 is an ID, Azure CLI will use it without modification.
Source snapshot contains location information itself. It’s a property of the snapshot. In the request body, location represents the location of snapshot you want to create.
The limitation is different location of source snapshot and target snapshot, not location of resource group.
Hope my explanation can help you.

**Comment by qwordy** [comment] 2020-03-31 08:25
--location -l

Location. Values from: az account list-locations. You can configure the default location using az configure --defaults location=<location>.

This is help of snapshot create. It is not clear enough. I will update it to let user know exact behavior.

**Comment by qwordy** [comment] 2020-04-02 03:36
The PR that updating help is merged. It will be released on 4/21/2020.
According to the internal email threads, the question and confusion is solved. Close this issue now.
The more general problem of location is tracked here:
https://github.com/Azure/azure-cli/issues/12841

**Closed by qwordy** 2020-04-02 03:36 UTC
Labels: Compute, OKR3.2 Candidate, Service Attention

**Comment by vnextcoder** [comment] 2020-12-29 10:25
https://docs.microsoft.com/en-us/cli/azure/snapshot?view=azure-cli-latest  still has old references and the documents "Create commands" without Location flag still . 

The **AZ CLI** itself needs to update itself to enforce requiring Location Property when it caann't work without **Location** for creating Snapshots

**Comment by qwordy** [comment] 2020-12-30 02:29
This is current help message of `--location`
```
--location -l

Location. Values from: az account list-locations. You can configure the default location using az configure --defaults location=<location>. If location is not specified and no default location specified, location will be automatically set as same as the resource group.
```
`--location` is not a required field.
Do you mean we should tell users the correct usage in error message when there is an error caused by location?
