### ISSUE TITLE
az login fails

### ISSUE THREAD

**Issue by msjaosborn** [Azure/azure-cli#1708] opened 2017-01-11 04:02 UTC
I am on a Wind River 7 NUC-based box running Python 2.7.  I obtained the CLI via:

`pip install --upgrade azure-cli`

I then did "az login" successfully.

The next day I attempted to do "az login" again and got the following error:
```
root@WR-IDP-EA09:~# az login
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code <removed> to authenticate.
'unicode' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/azure/cli/main.py", line 33, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/lib64/python2.7/site-packages/azure/cli/core/application.py", line 122, in execute
    result = expanded_arg.func(params)
  File "/usr/lib64/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 234, in _execute_command
    result = operation(client, **kwargs) if client else operation(**kwargs)
  File "/usr/lib64/python2.7/site-packages/azure/cli/command_modules/profile/custom.py", line 60, in login
    tenant)
  File "/usr/lib64/python2.7/site-packages/azure/cli/core/_profile.py", line 122, in find_subscriptions_on_login
    is_service_principal)
  File "/usr/lib64/python2.7/site-packages/azure/cli/core/_profile.py", line 133, in _normalize_properties
    _STATE: s.state.value,
AttributeError: 'unicode' object has no attribute 'value'
root@WR-IDP-EA09:~# az account list
Please run "az login" to access your accounts.
root@WR-IDP-EA09:~# az login
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code <removed> to authenticate.
'unicode' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/azure/cli/main.py", line 33, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/lib64/python2.7/site-packages/azure/cli/core/application.py", line 122, in execute
    result = expanded_arg.func(params)
  File "/usr/lib64/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 234, in _execute_command
    result = operation(client, **kwargs) if client else operation(**kwargs)
  File "/usr/lib64/python2.7/site-packages/azure/cli/command_modules/profile/custom.py", line 60, in login
    tenant)
  File "/usr/lib64/python2.7/site-packages/azure/cli/core/_profile.py", line 122, in find_subscriptions_on_login
    is_service_principal)
  File "/usr/lib64/python2.7/site-packages/azure/cli/core/_profile.py", line 133, in _normalize_properties
    _STATE: s.state.value,
AttributeError: 'unicode' object has no attribute 'value'
root@WR-IDP-EA09:~#

```
I rebooted the machine and tried again with the same results.

**Comment by yugangw-msft** [comment] 2017-01-12 19:03
@msjaosborn, I tried several installation options, include `pip`, but i could not reproduce it. I am using Ubuntu 16.04 LTS by the way.
Could you check out what is version of `azure-mgmt-resource` installed in your environment?

**Comment by yugangw-msft** [comment] 2017-07-28 18:57
closing for no further repro details.

**Closed by yugangw-msft** 2017-07-28 18:57 UTC
Labels: Auth, bug

**Comment by dennis-benzinger-hybris** [comment] 2017-08-22 07:43
FWIW the same happened to me with version 0.30.0rc5 of `azure-mgmt-resource`. With 1.1.0 the problem is gone. I didn't try the versions in between.
