### ISSUE TITLE
Within WSL, `az artifacts universal download` downloads an artifact to wrong destination when supplied with absolute path on Windows fs.

### ISSUE THREAD

**Issue by Arech** [Azure/azure-cli#27945] opened 2023-11-29 09:33 UTC
### Describe the bug

When inside WSL2 Ubuntu 20.04 terminal, invocation of `az artifacts universal download` with `--path` argument specifying and absolute (linux) path located on a Windows filesystem mountpoint, - for example `--path /mnt/c/some/dir`, - will download the artifact into a totally different `C:\mnt\c\some\dir` instead of `/mnt/c/some/dir`.

When --path is supplied with relative path, the downloader works correctly for Windows mountpoints.

To replicate locally:

1. launch WSL2 Ubuntu20.04 image (probably any other image would do also)
2. in bash terminal type `az artifacts universal download` command for some Azure Artifact and set `--path /mnt/c/some/dir` as a destination to download artifact. This is an absolute path to a native Windows filesystem directory `C:\some\dir`
3. run the command and observe that `C:\some\dir` was not created (if it did’t exist before) or updated. Instead, `C:\mnt\c\some\dir` directory was created and the artifact was downloaded there.

Environment: reproducible on current latest Windows 10 22H2 build 19045.3693 with the latest WSL2 image of Ubuntu 20.04 with the latest az script, however, this problem persists for more that year and a half already.

### Related command

az artifacts universal download

### Errors

no errors, command behavior is incorrect

### Issue script & Debug output

There's too much of sensitive info in the log and I'm not sure I can clean it up completely (my company has strict infosec policy to which I must comply).
The command works nicely, it just assumes it works in Windows filesystem and therefore it assumes that (Linux abs) path `/mnt/c/some/dir`  is actually just a path relative to `C:\`.

### Expected behavior

When command is invoked in Linux with absolute path such as `/mnt/c/some/dir` it must download artifact to that path. On a native Windows filesystem this abs path corresponds to `C:\some\dir`, not `C:\mnt\c\some\dir`

### Environment Summary

Note, this is the result of `az --version` invoked from WSL Linux shell and it still assumes it works under Windows, which explains the filesystem issue.

```
$ az --version
azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\arechins\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment] 2023-11-29 09:33
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2023-11-30 02:15
Duplicate of https://github.com/Azure/azure-cli/issues/19517

**Closed by bebound** 2023-11-30 02:15 UTC
Labels: bug, Service Attention, customer-reported, Artifacts, Auto-Assign
