### ISSUE TITLE
It' Scenario current in my notebook wich WSL ubuntu

### ISSUE THREAD

**Issue by ricardo2009** [Azure/azure-cli#25307] opened 2023-01-31 16:44 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1675179187.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1675183130,
  "nbf": 1675183130,
  "exp": 1675187030,
  "aio": "AWQAm/8TAAAALP0uLl9unI6jtQPzCuds5Qn9C9UIxE32sMFjB4h+BYdCxPIXCo7kNzg3q1J7tthtj2CyfX1aSpDweCkmDclMQIpwaAazSw2b4WjnUQvqUUookVsb1MHPzgWOmcmKakkp",
  "name": "Ricardo Lima",
  "oid": "94343d9f-1fdf-4b11-a677-ae600b36c148",
  "preferred_username": "ricardolima@microsoft.com",
  "puid": "100320012097479B",
  "rh": "0.ARoAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAFE.",
  "sub": "mkAgKPNN0HwT0AyQja7_41DCuNDTkVwXWiK9eU-f9sg",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "SWiY5BoKxE-Hn8CtlkKlAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 168, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1978, in acquire_token_by_device_flow
    response = _clean_up(self.client.obtain_token_by_device_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 383, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 345, in _obtain_token_by_device_flow
    result = self._obtain_token(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 788, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 700, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 314, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 117, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 158, in __add
    decode_id_token(id_token, client_id=event["client_id"]) if id_token else {})
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    raise RuntimeError("%s Current epoch = %s.  The id_token was: %s" % (
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1675179187.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1675183130,
  "nbf": 1675183130,
  "exp": 1675187030,
  "aio": "AWQAm/8TAAAALP0uLl9unI6jtQPzCuds5Qn9C9UIxE32sMFjB4h+BYdCxPIXCo7kNzg3q1J7tthtj2CyfX1aSpDweCkmDclMQIpwaAazSw2b4WjnUQvqUUookVsb1MHPzgWOmcmKakkp",
  "name": "Ricardo Lima",
  "oid": "94343d9f-1fdf-4b11-a677-ae600b36c148",
  "preferred_username": "ricardolima@microsoft.com",
  "puid": "100320012097479B",
  "rh": "0.ARoAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAFE.",
  "sub": "mkAgKPNN0HwT0AyQja7_41DCuNDTkVwXWiK9eU-f9sg",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "SWiY5BoKxE-Hn8CtlkKlAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-5.15.83.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.44.1

Extensions:
aks-preview 0.5.128
alertsmanagement 0.2.2
interactive 0.4.6
resource-graph 2.1.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2023-02-01 00:47
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2023-02-01 00:47 UTC
Labels: Account, Graph, customer-reported, Auto-Assign
