### ISSUE TITLE
azlogin got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by hevel** [Azure/azure-cli#18918] opened 2021-07-19 03:10 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 152, in login
    subscriptions = profile.find_subscriptions_on_login(
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 215, in find_subscriptions_on_login
    subscriptions = subscription_finder.find_from_service_principal_id(
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 939, in find_from_service_principal_id
    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 1033, in _find_using_specific_tenant
    client = self._arm_client_factory(token_credential)
  File "/home/ehexshi/venv3.8/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 880, in create_arm_client_factory
    client = client_type(credentials, api_version=api_version,
TypeError: __init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal --username {} --password {} --tenant {}`

## Environment Summary
```
Linux-5.4.0-77-generic-x86_64-with-glibc2.27
Python 3.8.2
Installer: PIP

azure-cli 2.26.1

```

**Comment by yonzhan** [comment] 2021-07-19 03:44
@jiasli for awareness

**Comment by jiasli** [comment] 2021-08-10 06:03
Duplicate of #18626. Please see the analysis at https://github.com/Azure/azure-cli/issues/18626#issuecomment-879609185 and workaround at https://github.com/Azure/azure-cli/issues/18626#issuecomment-887411446.

**Closed by jiasli** 2021-08-10 06:03 UTC
Labels: Account
