### ISSUE TITLE
--subscription does not seem to work anymore for "az monitor metrics alert create" at least

### ISSUE THREAD

**Issue by tmontalbano** [Azure/azure-cli#8437] opened 2019-02-05 22:07 UTC
**Describe the bug**

I get an odd error when trying to create an alert. This happens since I have updated azure-cli:
Arm resource /subscriptions/subId2/resourceGroups/infraName-group/providers/microsoft.insights/actionGroups/send-email-ops is invalid.. [Code: "BadRequest"]

With subId2 being a subscription id set at some point in the environment with "az set --subscription".

**To Reproduce**

az account set --subscription "subName2"
az monitor metrics alert create --name infraName-APIM-TotalRequests-4 --resource-group infraName-group --scopes /subscriptions/subId1/resourceGroups/infraName-group/providers/Microsoft.ApiManagement/service/apim-infraName-cluster-default --description 'alert if TotalRequests > 99' --severity 4 --window-size 5m --evaluation-frequency 1m --condition 'max TotalRequests < 99' --action send-email-ops --subscription "subName1"
Arm resource /subscriptions/subName2/resourceGroups/infraName-group/providers/microsoft.insights/actionGroups/send-email-ops is invalid.. [Code: "BadRequest »]

az account set --subscription "subName1"
az monitor metrics alert create --name infraName-APIM-TotalRequests-4 --resource-group infraName-group --scopes /subscriptions/subId1/resourceGroups/infraName-group/providers/Microsoft.ApiManagement/service/apim-infraName-cluster-default --description 'alert if TotalRequests > 99' --severity 4 --window-size 5m --evaluation-frequency 1m --condition 'max TotalRequests < 99' --action send-email-ops --subscription "subName1"
{
  "actions": [
    {
      "actionGroupId": "/subscriptions/subId1/resourceGroups/infraName-group/providers/microsoft.insights/actionGroups/send-email-ops",
      "webhookProperties": null
    }
  ],
  "autoMitigate": null,
  "criteria": {
    "additionalProperties": null,
    "allOf": [
      {
        "dimensions": [],
        "metricName": "TotalRequests",
        "metricNamespace": "microsoft.apimanagement/service",
        "name": "cond0",
        "operator": "LessThan",
        "threshold": 99.0,
        "timeAggregation": "Maximum"
      }
    ],
    "odatatype": "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria"
  },
  "description": "alert if TotalRequests > 99",
  "enabled": true,
  "evaluationFrequency": "0:01:00",
  "id": "/subscriptions/subId1/resourceGroups/infraName-group/providers/Microsoft.Insights/metricAlerts/infraName-APIM-TotalRequests-4",
  "lastUpdatedTime": null,
  "location": "global",
  "name": "infraName-APIM-TotalRequests-4",
  "resourceGroup": "infraName-group",
  "scopes": [
    "/subscriptions/subId1/resourceGroups/infraName-group/providers/Microsoft.ApiManagement/service/apim-infraName-cluster-default"
  ],
  "severity": 4,
  "tags": null,
  "type": "Microsoft.Insights/metricAlerts",
  "windowSize": "0:05:00"
}

**Expected behavior**

We should not need to set the subscription before using the command, as long as we put --subscription parameter in the command.

**Environment summary**

azure-cli (2.0.55) or azure-cli (2.0.57)
It worked fine with azure-cli (2.0.50)

**Comment by tmontalbano** [comment] 2019-02-07 01:53
I have done some more testing and the problem occurs after version 2.0.52. This is the highest version at which the problem does not show from what I have been testing.

**Comment by tmontalbano** [comment] 2019-02-07 02:05
Another detail is that the right command should use the subscription ID and not the subscription name, otherwise, I get another strange error:

 az monitor metrics alert create --name "infraName-APIM-TotalRequests-4" --resource-group "infraName-group" --scopes "/subscriptions/subId/resourceGroups/ddo-2392-thierry-group/providers/Microsoft.ApiManagement/service/apim-infraName-cluster-default" --description "alert if TotalRequests > 99" --severity 4 --window-size 5m --evaluation-frequency 1m --condition "max TotalRequests < 99" --action "send-email-ops" --subscription "subName"            
The client has permission to perform action 'microsoft.insights/actionGroups/read' on scope '/subscriptions/subId/resourceGroups/infraName-group/providers/Microsoft.Insights/metricAlerts/infraName-APIM-TotalRequests-4', however the linked subscription 'subName' was not found. . [Code: "LinkedAuthorizationFailed"]

I'm not sure if this is also a bug to fix, but it's easy enough to work around this one by providing the subscription ID instead of the subscription name:

 az monitor metrics alert create --name "infraName-APIM-TotalRequests-4" --resource-group "infraName-group" --scopes "/subscriptions/subId/resourceGroups/ddo-2392-thierry-group/providers/Microsoft.ApiManagement/service/apim-infraName-cluster-default" --description "alert if TotalRequests > 99" --severity 4 --window-size 5m --evaluation-frequency 1m --condition "max TotalRequests < 99" --action "send-email-ops" --subscription "subId"      

Thought, the main bug remains. Even this command won't work if the version of azure-cli is superior to 2.0.52 and az set --subscription has been used prior to this command and set to different subscription than the one we are trying to operate in this command.

**Comment by tjprescott** [comment] 2019-02-09 21:24
In regards to using the subscription ID, I cannot reproduce this issue.

Assuming you are set to subscription 2, breaking down the parameters that are subscription sensitive:
- `--scopes /subscriptions/{subID1}/resourceGroups/infraName-group/providers/Microsoft.ApiManagement/service/apim-infraName-cluster-default` Here you have directly embedded sub ID 1.
- `--subscription {subID1}` Since you specify this, any name properties will use this subscription ID.
- `--action send-email-ops` Since you are specifiying action group by NAME, then it will use the values from `--subscription` and `--resource-group` when resolving this. If it is in subscription 2 or a different resource group, you must specify the full resource ID.

By virute of supplying `--subscription` the alert itself would be targeted for creation inside subscription 1 and `infraName-group` resource group.

The error you mention is:
```
Arm resource /subscriptions/subName2/resourceGroups/infraName-group/providers/microsoft.insights/actionGroups/send-email-ops is invalid.. [Code: "BadRequest »]
```
You say it should "subName2" but when I try this, supplying `--action {ag-name} --subscription {subID1}` it does not use subscription 2 but subscription 1 (which is what it is supposed to do).

Can you verify that the action group is in the same subscription and resource group that you specified with `-g/--resource-group` and `--subscription`?  If not, then this error would be expected.

**Comment by tjprescott** [comment] 2019-02-09 21:26
In regards to the second part, I am able to reproduce the issue with supplying the subscription name (rather than the ID) failing. I will look into this.

**Comment by tmontalbano** [comment] 2019-02-10 16:06
Can you tell me which version of azure-cli you are using? Because, my issue can only be reproduced in versions of azure-cli that are beyond 2.0.52, given that I have not been able to test with any version beyond 2.0.57. So, if you try this command with azure versions outside of the bracket between 2.0.53 and 2.0.57, it may be normal that you cannot reproduce it.

In versions equal or earlier than 2.0.52, the exact same command works regardless of what subscription we have set before.

Just to clarify, subId2 and subName2 are the same subscription (one being the subscription ID and the other the subscription name).

In my example, the action group is in the subscription 1. Otherwise, it would not work at all, would it?

Thank you.
Thierry.

**Comment by tjprescott** [comment] 2019-02-11 05:03
Hi @tmontalbano thanks for the reply.  I wanted to clarify where the action group was located because in your initial post, you said the error was:

Arm resource /subscriptions/**subName2**/resourceGroups/infraName-group/providers/microsoft.insights/actionGroups/send-email-ops is invalid.. [Code: "BadRequest »]

When I run this scenario (with account set to sub2) it correctly looks for and finds the action-group in sub1. I have a PR out that will fix the issue when you provide a subscription name instead of ID. The other issue might be fixed in the upcoming release (2.0.58) as I'm not able to reproduce it on the latest dev build.

**Comment by tmontalbano** [comment] 2019-02-11 05:22
Thanks @tjprescott.

Indeed, The reason I showed the error mentioning subName2 is that it did not make any sense to have subName2 in my error message when I clearly put subName1 as a --subscription parameter and also subId1 in the --scope parameter. The only reason why it was appearing in the error message was because of the previous command: az account set --subscription "subName2". If this bug is fixed by version 2.0.58, that's nice. I'd be looking forward to try it out when it will be out then. For now, I will keep using 2.0.52.

Is it possible for you to test it out with version 2.0.57 by chance? Just so we are sure it is an actual bug...

Also, thanks for addressing the other bug, it's appreciated.

**Comment by tjprescott** [comment] 2019-02-11 15:51
Hi @tmontalbano I was able to repro with 2.0.57. Fortunately, PR #8404 was merged recently which will fix this issue for you in tomorrow's release. However, you will need to use the subscription ID.  The subscription name bug will not be until the 2.0.59 release (roughly end of February).

**Closed** 2019-02-13 01:17 UTC
Labels: Infrastructure, bug

**Comment by tmontalbano** [comment] 2019-02-13 16:05
Thank you,
I confirm that it works with 2.0.58.
No problems for the other bug.
