### ISSUE TITLE
az restore flexible-server does not work

### ISSUE THREAD

**Issue by yadavama-intel** [Azure/azure-cli#29683] opened 2024-08-08 07:18 UTC
### Describe the bug

Following command mention in [this](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-restore-server-cli) document does not work when a --source-server is from another resource-group.

```
az postgres flexible-server restore --restore-time
                                 --source-server
                                 [--ids]
                                 [--location]
                                 [--name]
                                 [--no-wait]
                                 [--resource-group]
                                 [--subscription]
```

For example - 
`az postgres flexible-server restore --resource-group rg-myrg --name pgsql-myserver-05 \
          --source-server /subscriptions/{mysubid}/resourceGroups/source-rg-name/providers/Microsoft.DBforPostgreSQL/flexibleServers/source-pgsql-server`

gives following -

`(ResourceNotFound) The Resource 'Microsoft.DBforPostgreSQL/flexibleServers/source-pgsql-server' under resource group 'rg-myrg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.DBforPostgreSQL/flexibleServers/source-pgsql-server' under resource group 'rg-myrg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix`

az cli version - 2.62.0 and beyond

### Related command

`az postgres flexible-server restore --resource-group rg-myrg --name pgsql-myserver-05 \
          --source-server /subscriptions/{mysubid}/resourceGroups/source-rg-name/providers/Microsoft.DBforPostgreSQL/flexibleServers/source-pgsql-server`

### Errors

`(ResourceNotFound) The Resource 'Microsoft.DBforPostgreSQL/flexibleServers/source-pgsql-server' under resource group 'rg-myrg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.DBforPostgreSQL/flexibleServers/source-pgsql-server' under resource group 'rg-myrg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix`

### Issue script & Debug output

`(ResourceNotFound) The Resource 'Microsoft.DBforPostgreSQL/flexibleServers/source-pgsql-server' under resource group 'rg-myrg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.DBforPostgreSQL/flexibleServers/source-pgsql-server' under resource group 'rg-myrg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix`

### Expected behavior

should start creating new pgsql server in target resource-group

### Environment Summary

azure-cli: 2.62.0, 2.63.0

**Comment by yonzhan** [comment] 2024-08-08 07:18
Thank you for opening this issue, we will look into it.

**Comment by nachoalonsoportillo** [comment] 2024-08-09 15:53
Thanks @yadavama-intel for taking the time to report this issue. I'm closing it as a duplicate of https://github.com/Azure/azure-cli/issues/29353.

**Closed by nachoalonsoportillo** 2024-08-09 15:53 UTC
Labels: bug, Service Attention, PostgreSQL, customer-reported, Auto-Assign, Auto-Resolve, Similar-Issue

**Comment by yadavama-intel** [comment] 2024-08-12 15:56
I feel following is not working, please verify - 

az postgres flexible-server restore --resource-group rg-dev-2 --name pgsql-dev-2-restore \
          --source-server /subscriptions/{my-sub-id}/resourceGroups/rg-dev-1/providers/Microsoft.DBforPostgreSQL/flexibleServers/pgsql-rg-dev-1
          
          here i am trying to restore from another resource group.

**Comment by nachoalonsoportillo** [comment] 2024-08-19 12:04
> I feel following is not working, please verify -
> 
> here i am trying to restore from another resource group. - az postgres flexible-server restore --resource-group rg-dev-2 --name pgsql-dev-2-restore --source-server /subscriptions/{my-sub-id}/resourceGroups/rg-dev-1/providers/Microsoft.DBforPostgreSQL/flexibleServers/pgsql-rg-dev-1

Reopened #29353 to track this down.
