### ISSUE TITLE
fail to login in when the password is starts with '-'

### ISSUE THREAD

**Issue by MayXuQQ** [Azure/azure-cli#23580] opened 2022-08-18 14:28 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az login --service-principal
**Describe the bug**

fail to login when the password stars with '-'
$az login --service-principal -u 542ef77d-**** -p "**-**G9-8pR0E***" --tenant 259714ad-***
argument --password/-p: expected one argument

**To Reproduce**

$az ad sp create-for-rbac --role Owner --name maxu-installer –year 100 --scopes //subscriptions/8fe0c1b4-8b05-4ef7-8129-7cf5680f27e7
created the sp password starts with '-'
fail to login with the password.  
**Expected behavior**
login in succeed. 
**Environment summary**

$ az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Additional context**

**Comment by yonzhan** [comment] 2022-08-18 14:45
@jiasli for awareness

**Comment by jiasli** [comment] 2022-08-23 15:17
Duplicate of #7054

This is well documented at https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#use-hyphen-characters-in-parameters

**Closed by jiasli** 2022-08-23 15:17 UTC
Labels: bug, Account, Graph, customer-reported, Auto-Assign, Azure CLI Team
