### ISSUE TITLE
SSL error when trying to execute azure container command

### ISSUE THREAD

**Issue by Shr3ps** [Azure/azure-cli#14822] opened 2020-08-18 07:44 UTC
## Describe the bug

azure-cli crashes when tring to execute a command in one of my Azure containers (ACI group).

**Command Name**
`az container exec`

**Errors:**
```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
usr/lib/python3.8/ssl.py, ln 1040, in _create
    self.do_handshake()
usr/lib/python3.8/ssl.py, ln 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container exec --resource-group {} --name {} --container-name {} --exec-command {}`

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.2
Installer: PIP

azure-cli 2.6.0

in WSL 2/Ubuntu 20.04 LTS
```

**Comment by yonzhan** [comment] 2020-08-18 08:14
container

**Comment by Shr3ps** [comment] 2020-08-18 08:16
For the record, I have the same error in Azure cloud shell on the Azure portal.

**Comment by jiasli** [comment] 2021-08-06 06:41
Duplicate of #15121

**Closed** 2021-08-06 06:42 UTC
Labels: Service Attention, Container Instances, customer-reported
