### ISSUE TITLE
az role assignment creating fails on role definitions which are valid on 1+ subscription

### ISSUE THREAD

**Issue by alanold** [Azure/azure-cli#9868] opened 2019-07-05 16:13 UTC
Previous issue with this title has been closed but I'm still seeing the behaviour.

In this case executing again Azure China.

## Describe the bug

**Command Name**
`az role assignment create`

**Errors:**
```
list index out of range
Traceback (most recent call last):
cli/command_modules/role/custom.py, ln 134, in create_role_assignment
    resolve_assignee=(not assignee_object_id))
cli/command_modules/role/custom.py, ln 152, in _create_role_assignment
    return worker.create_role_assignment(assignments_client, _gen_guid(), role_id, object_id, scope)
cli/command_modules/role/_multi_api_adaptor.py, ln 52, in create_role_assignment
    return client.create(scope, assignment_name, parameters)
authorization/v2018_01_01_preview/operations/role_assignments_operations.py, ln 329, in create
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: RoleAssignmentExists
Message: The role assignment already exists.

...

cli/command_modules/role/custom.py, ln 137, in create_role_assignment
    return list_role_assignments(cmd, assignee, role, resource_group_name, scope)[0]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- run following command with appid role id and sub id once.  then repeat and get the error
- `az role assignment create --assignee {} --role {} --scope {}`

## Expected Behavior
code executes without error on subsequent deployments

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67 *

Extensions:
resource-graph 0.1.11
subscription 0.1.3

```

**Comment by tjprescott** [comment] 2019-07-05 17:41
I believe this is true of many AD/Graph-related commands. @marstr and @yugangw-msft for comment.

**Comment by yugangw-msft** [comment] 2019-07-05 22:34
this command was made to be idempotent with client end workaround. I can't reproduce this in PublicCloud. @alanold, do you mind  run with `--debug` flag and send the trace to me at yugangw at microsoft dot com?

**Comment by alanold** [comment] 2019-07-08 14:21
Hi

Thanks for the quick response.  I've sent the debugs over.

It does appear to be OK on some subscriptions but not others.  I've sent output for both.  I'm using the same service principle in both cases and I believe they have the same access on each subscription.

Kind regards,


Alan Old
Platform Services – Cloud Infrastructure Engineering
DDI: +44 207 076 7091|Mob: +44 7967 002268

[cid:image001.png@01D10DA8.04D304A0]

**Comment by alanold** [comment] 2019-07-18 08:21
Hi Yugang

Testing advice 
'I guess I figured out, looks like the role definition of “a614ca30-22f5-5606-b5bf-9ea5669640e2” is applicable in both subscriptions of “73044326-e1af-45d8-a88e-a56ae30e11bd” and “712330b2-aada-46a5-870a-070ed09927f3”
I have not sorted out the right fix, but if you use “—role '/subscriptions/712330b2-aada-46a5-870a-070ed09927f3/providers/Microsoft.Authorization/roleDefinitions/a614ca30-22f5-5606-b5bf-9ea5669640e2'”, the command would work.'

This has enabled deployment of role assignments across subscriptions

**Comment by alanold** [comment] 2019-07-18 08:23
Probably requires a separate ticket but there is also an issue with invalid principle when attempting to deploy role assignments via ARM templates (which would be my preferred mechinism)

**Comment by yugangw-msft** [comment] 2019-08-09 02:43
Let us close it and let @alanold open a separate issue tracking the `invalid principal` issue.

**Closed by yugangw-msft** 2019-08-09 02:43 UTC
Labels: Bug, Graph

**Comment by jasric89** [comment] 2024-04-25 14:39
Hi I am getting this error and I am on the latest Azure CLI: 

```
az role assignment create --assignee "/subscriptions/$subscriptionID/resourcegroups/jc-testing-dns/providers/Microsoft.ContainerService/managedClusters/cert-manager-demo" --role "DNS Zone Contributor" --scope "/subscriptions/$subscriptionID/resourceGroups/jc-testing-dns/providers/Microsoft.Network/privateDnsZones/private.jcdnstesting.azure.com"

Failed to query 4ef163e9-0a17-4ee5-bba0-ec60bab6f992/resourcegroups/jc-testing-dns/providers/Microsoft.ContainerService/managedClusters/cert-manager-demo by invoking Graph API. If you don't have permission to query Graph API, please specify --assignee-object-id and --assignee-principal-type.
The command failed with an unexpected error. Here is the traceback:
Unsupported or invalid query filter clause specified for property 'servicePrincipalNames' of resource 'ServicePrincipal'.
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1007, in send_raw_request
azure.cli.core.azclierror.HTTPError: Bad Request({"error":{"code":"Request_UnsupportedQuery","message":"Unsupported or invalid query filter clause specified for property 'servicePrincipalNames' of resource 'ServicePrincipal'.","innerError":{"date":"2024-04-25T14:37:01","request-id":"d40b7774-db07-490c-880f-54811f11708b","client-request-id":"d40b7774-db07-490c-880f-54811f11708b"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 167, in create_role_assignment
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 1539, in _resolve_object_id_and_type
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 179, in service_principal_list
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 55, in _send
azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Unsupported or invalid query filter clause specified for property 'servicePrincipalNames' of resource 'ServicePrincipal'.
```
