### ISSUE TITLE
az login --identity

### ISSUE THREAD

**Issue by zylxjtu** [Azure/azure-cli#29174] opened 2024-06-15 20:51 UTC
### Describe the bug

Not sure if this is a bug, but for Azure Arc machines, the IMDS endpoint for MSI token access is different than the "169.254.169.254". as pointed out here: https://learn.microsoft.com/en-us/azure/azure-arc/servers/managed-identity-authentication#security-overview, while powershell can use the env variables to login in through Azure Arc MSI, but not sure if Azure CLI support this or not? that is define the IMDS related endpoint with a setting/environment variable? thanks

### Related command

az login --identity

### Errors

ERROR: Failed to connect to MSI. Please make sure MSI is configured correctly and check the network connection.
Error detail: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BBC677E90>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))

### Issue script & Debug output

az login --identity --debug

### Expected behavior

Successful login with Azure Arc MSI

### Environment Summary

{
  "azure-cli": "2.61.0",
  "azure-cli-core": "2.61.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "acrquery": "1.0.1",
    "aks-preview": "2.0.0b8",
    "azure-devops": "0.26.0",
    "bastion": "0.3.0",
    "capi": "0.1.5",
    "connectedmachine": "0.7.0",
    "init": "0.1.0",
    "storage-preview": "1.0.0b1"
  }
}

**Comment by yonzhan** [comment] 2024-06-15 20:51
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-06-17 04:08
Duplicate of #25959

**Closed by jiasli** 2024-06-17 04:08 UTC
Labels: Account, customer-reported, feature-request, Auto-Assign, Azure CLI Team, Auto-Resolve, Similar-Issue, Possible-Solution
