### ISSUE TITLE
listing 100k+ users run out of memory

### ISSUE THREAD

**Issue by b-dasass** [Azure/azure-cli#16776] opened 2021-02-02 17:53 UTC
## Describe the bug

**Command Name**
`az ad user list`

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:


Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py", line 239, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-pwfpui04\knack\output.py", line 148, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-pwfpui04\knack\output.py", line 40, in format_json
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 202, in encode
MemoryError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- have more than 100k users
- In Windows PowerShell
- `$users = az ad user list`

## Expected Behavior

Not throw an error, but return the users

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0

```

**Comment by yonzhan** [comment] 2021-02-02 23:22
Graph

**Comment by jiasli** [comment] 2021-02-02 23:53
Duplicate of https://github.com/Azure/azure-cli/issues/15268.

**Closed by jiasli** 2021-02-02 23:53 UTC
Labels: Graph
