### ISSUE TITLE
AZ batch upload

### ISSUE THREAD

**Issue by mayamr90** [Azure/azure-cli#11175] opened 2019-11-10 09:06 UTC
## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload-batch --account-name {} --account-key {} -s {} -d {} --auth-mode {}`

## Environment Summary
```
Linux-5.0.0-1018-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment] 2019-11-11 02:20
@Juliehzl please take a look.

**Comment by Juliehzl** [comment] 2019-11-11 03:25
Hi @mayamr90, can you share me more information for your issue? e.g can you share me debug info with `--debug` in your command?

**Comment by Juliehzl** [comment] 2019-11-24 13:53
Hi @mayamr90 , we are waiting for your more information. Without your information, we cannot find root cause for you issue, but for this kind of issue, it should be firewall or authentication failed and we can throw accurate message in azure cli 2.0.77 with PR #11345. In this way, please try with new azure cli and I will close this issue. If you still have problem, feel free to create a new one.

**Closed by Juliehzl** 2019-11-24 13:53 UTC
Labels: Storage
