### ISSUE TITLE
Make --subscription a global parameter for all commands

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-cli#5618] opened 2018-02-20 22:25 UTC
The current CLI currently requires this workflow:

```
# set subscription
az account set --subscription <sub_name>

# do az stuff in that sub
az acs login --name ...
```

This makes it very unfriendly and dangerous for scripts and interactive use.

Consider:

1. Long running script sets curernt sub to SubProduction, then does some azure commands.
2. In the meantime user from the terminal, is thinking the commands execute against SubDev issues "delete resource group MyApp". **OOPS**.

If we had `--subscription` as a globa flag, we could have all scripts use that and not interfere with each other.

**Comment by tjprescott** [comment] 2018-02-20 23:51
Duplicate of #807, but great point.  Please +1 and add your comments to that issue.

**Closed by tjprescott** 2018-02-20 23:51 UTC
