### ISSUE TITLE
az aks install-cli results in Error 13

### ISSUE THREAD

**Issue by Monte-Christo** [Azure/azure-cli#16984] opened 2021-02-18 19:58 UTC
### **This is autogenerated. Please review and update as needed.**

Created an AKS with 

`az aks create -g ek-k8s -n ekclust --node-count 1 --enable-addons monitoring --generate-ssh-keys`

then tried to install kubectl with

`az aks install-cli --install-location=./kubectl`

and got below error.

**Command Name**
`az aks install-cli`

**Errors:**
```
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
az/lib/python3.6/shutil.py, ln 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmp10oj9jlu/bin/linux_amd64/kubelogin' -> '/usr/local/bin/kubelogin'

...

az/lib/python3.6/shutil.py, ln 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az aks create -g ek-k8s -n ekclust --node-count 1 --enable-addons monitoring --generate-ssh-keys
- az aks install-cli --install-location=./kubectl

Command bombs out.

## Expected Behavior

Kubectl is installed

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.19.0 *

Extensions:
ai-examples 0.2.5

```

**Comment by yonzhan** [comment] 2021-02-19 00:42
AKS

**Comment by RakeshMohanMSFT** [comment] 2022-08-09 08:56
Duplicate of https://github.com/Azure/azure-cli/issues/15860

**Closed by RakeshMohanMSFT** 2022-08-09 08:56 UTC
Labels: Service Attention, question, AKS
