### ISSUE TITLE
Get full error when VM provisioning fails. 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-cli#3741] opened 2017-06-15 18:57 UTC
### Description

Cannot view full error when VM provisioning fails in Azure ARM. Currently, we have to go to the portal and click on "failed->" to view the full error. 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
0.10.12

**OS Version:** What OS and version are you using?  
6      1      7601   65536
Windows 7 

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
cmd.exe

**Comment by tjprescott** [comment] 2017-06-15 19:25
This is a dupe of #2792 and will be fixed by PR #3726.

**Closed by tjprescott** 2017-06-15 19:25 UTC
