### ISSUE TITLE
Azure devops. AzureCLI extension. az login command fails

### ISSUE THREAD

**Issue by marcosfriasraet** [Azure/azure-cli#15930] opened 2020-11-16 10:04 UTC
HI All.

We have a self-managed pool that PD teams use for different build processes. These servers make use
 of the azure devops azure cli extension. We've had this random error for ane week back.
 I have tried updating the agents but we keep getting this error. Could you guide us to the cause of it?
 
 Unable to check if your CLI is up-to-date. Check your internet connection.
azure-cli                         2.11.1
core                              2.11.1
telemetry                          1.0.5

Extensions:
application-insights               0.1.1
azure-devops                      0.17.0
eventgrid                          0.4.9

**************************** 

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /***/oauth2/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x021ECF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))
##[error]Error Code: [1]
##[error]Error: Azure login failed
##[error]Script failed with error: Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /***/oauth2/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x021ECF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))).

**Comment by yonzhan** [comment] 2020-11-16 11:36
devops

**Comment by marcosfriasraet** [comment] 2020-11-17 08:44
Hi.. Any info can help us..

**Comment by yonzhan** [comment] 2020-11-17 11:23
devops service team should look into this.

**Comment by jiasli** [comment] 2022-10-19 08:12
Duplicate of #11829

**Closed by jiasli** 2022-10-19 08:12 UTC
Labels: Service Attention, DevOps
