### ISSUE TITLE
[Help] Extract command descriptions from method docstring

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#365] opened 2016-06-06 21:13 UTC
This is a known gap we should fill in. Lost of methods have pretty good summary in its docstring which can be used for help. And cli is already loading the param section in docstring for help, and we should make it complete 
The effort involved would be to parse the doc-string in finer grain to extract out the summary

**Comment by tjprescott** [comment] 2016-08-22 19:26
Is this essentially a duplicate of #270?

**Comment by tjprescott** [comment] 2016-08-23 16:23
This is more important now that we are on the hook for help documentation.

**Closed** 2016-08-25 21:51 UTC
Labels: Documentation
