### ISSUE TITLE
FunctionaApp:Unable to update min instances with az functionapp plan update

### ISSUE THREAD

**Issue by rachelxj-ms** [Azure/azure-cli#21319] opened 2022-02-16 01:42 UTC
## Describe the bug

**Command Name**
`az functionapp plan update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'sku'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 713, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 38, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 200, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1867, in update_functionapp_app_service_plan
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1843, in update_app_service_plan
AttributeError: 'NoneType' object has no attribute 'sku'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp plan update -g {} -n {} --min-instances {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0 *

Extensions:
authV2 0.1.1
containerapp 0.2.0
log-analytics 0.2.2
resource-graph 2.1.0
spring-cloud 2.12.3

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-02-16 01:52
route to CXP team

**Comment by PramodValavala-MSFT** [comment] 2022-02-16 05:32
@rachelxj-ms I believe you are using the name of the functionapp instead of the plan when running this command. Could you confirm?

You can check [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#plan-and-sku-settings) for more info.

**Comment by rachelxj-ms** [comment] 2022-02-17 01:23
> @rachelxj-ms I believe you are using the name of the functionapp instead of the plan when running this command. Could you confirm?
> 
> You can check [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#plan-and-sku-settings) for more info.

No, I'm using the plan name, not function app name.

**Comment by rachelxj-ms** [comment] 2022-02-17 01:29
I tried it again today, there is no error now, but the result is not expected. 
az functionapp plan update -g hybrid-rg -n ASP-hybridrg-af34 --min-instances 2
![image](https://user-images.githubusercontent.com/66855967/154386433-88f0b196-a232-4ce0-a7cd-3274e59ef8c2.png)
I removed my sub id from the result. 
C:\Users\xuejl>az functionapp plan update -g hybrid-rg -n ASP-hybridrg-af34 --min-instances 2
{
  "freeOfferExpirationTime": null,
  "geoRegion": "Central US",
  "hostingEnvironmentProfile": null,
  "hyperV": false,
  "id": "/subscriptions/XXXXXX/resourceGroups/hybrid-rg/providers/Microsoft.Web/serverfarms/ASP-hybridrg-af34",
  "isSpot": false,
  "isXenon": false,
  "kind": "elastic",
  "location": "Central US",
  "maximumElasticWorkerCount": 20,
  "maximumNumberOfWorkers": 20,
  "name": "ASP-hybridrg-af34",
  "numberOfSites": 1,
  "perSiteScaling": false,
  "provisioningState": "Succeeded",
  "reserved": false,
  "resourceGroup": "hybrid-rg",
  "sku": {
    "capabilities": null,
    "capacity": 1,
    "family": "EP",
    "locations": null,
    "name": "EP1",
    "size": "EP1",
    "skuCapacity": null,
    "tier": "ElasticPremium"
  },
  "spotExpirationTime": null,
  "status": "Ready",
  "subscription": "XXXXXX",
  "systemData": null,
  "tags": null,
  "targetWorkerCount": 0,
  "targetWorkerSizeId": 0,
  "type": "Microsoft.Web/serverfarms",
  "workerTierName": null
}

**Comment by PramodValavala-MSFT** [comment] 2022-02-17 05:41
@rachelxj-ms According to [this section of the doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#plan-and-sku-settings), looks like the minimum is set to the max always ready instance count of the apps deployed in that play.

But I too couldn't increase it using Azure CLI like the doc mentions. I will confirm with the team concerned and get back to you.

**Comment by panchagnula** [comment] 2022-02-22 19:25
@rachelxj-ms is this behavior similar (minInstances not getting updated) in portal as well? because if so this is not CLI specific issue - & need to be looked at by the right owner.

**Comment by rachelxj-ms** [comment] 2022-03-31 07:30
@panchagnula  I think we need update the document as it's disabled to change minimum instance from ASP level

**Comment by panchagnula** [comment] 2022-03-31 23:55
@rachelxj-ms I am not the owner of this area to update the documentation please work with CXP or doc team directly for this. The answer from the feature team on how mininstance support works is as below:
"Hi, some actions are restricted by design. The minimum instances for the ASP is inferred based on the minimum settings of all the apps in the plan. 
 
For example, if you have 4 apps with a minimum of 2, but one app with a minimum of 5, then the minimum for the whole ASP should be 5. And then if you decrease the minimum of that one app from 5 down to 2, then the minimum for the ASP should drop down to 2."

**Comment by panchagnula** [comment] 2022-05-20 19:34
Closing this since this is not a CLI issue, CXP team should work with functions & doc team to update the changes appropriately

**Closed by panchagnula** 2022-05-20 19:34 UTC
Labels: Service Attention, Functions, customer-reported, feature-request
