### ISSUE TITLE
.msi install doesn't work with git-for-windows bash

### ISSUE THREAD

**Issue by v-iam** [Azure/azure-cli#3445] opened 2017-05-24 21:25 UTC
### Description

Installing the .msi (0.2.9) and issuing the `az` command in the bash shell that comes with https://git-for-windows.github.io gives the following error:

```
C:\Program Files\Python36\python.exe: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Installed using the .msi.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 
```
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)
```

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise (1607)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Git Bash from https://git-for-windows.github.io

**Comment by derekbekoe** [comment] 2017-05-24 22:04
Does it work in cmd.exe?

**Comment by v-iam** [comment] 2017-05-24 22:05
Yes, it does. Sorry, should have mentioned.

**Comment by derekbekoe** [comment] 2017-05-26 05:50
We don't officially support Git Bash.
I would recommend using cmd.exe or if you'd like a *nix experience, [Bash on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) is available and the CLI can be installed with apt-get [see this](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows).

**Comment by tjprescott** [comment] 2017-05-26 16:03
Closing this issue as git-bash is not a supported shell for the CLI.

**Closed by tjprescott** 2017-05-26 16:03 UTC
Labels: Packaging

**Comment by AshleyGrant** [comment] 2017-10-25 14:54
I really wish this issue would be reopened. There are tons of people who use Git Bash in favor of WSL. There are still various issues with WSL, while Git Bash works natively and works well.

**Comment by whindes** [comment] 2017-11-02 22:01
I tried in windows 7 :  git bash az.cmd --version

**Comment by rondemena** [comment] 2018-06-07 13:49
The issue is fundamentally not recognizing the .cmd execution extension in windows.  Just alias it out in the git bash shell wiht "alias az='az.cmd'"

**Comment by benktesh** [comment] 2019-07-17 12:40
@rondemena. Thanks much.

**Comment by ichandan16** [comment] 2019-08-14 16:00
A good workaround that helped me: https://stackoverflow.com/a/47085659/1651761
