### ISSUE TITLE
az vm list-usages needs table/tsv work

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3165] opened 2017-05-04 20:59 UTC
Currently outputs like:

```
$ az vm list-usage --location westus
  Limit    CurrentValue
-------  --------------
   2000
    100               4
  10000               4
   2000
    100               4
    100
    100
    100
    100
    100
    100
    100
    100
    100
    100
     24
     48
      8
    100
    100
    100
    100

   2000               1
   2000               4
```

But should have a formatter written to provide output like
```
Name                       CurrentValue Limit
------------------- ------------- --------
standardMSFamily                      1    2000   
StandardDiskCount                    0      100
PremiumDiskCount                     1      100
[...]
```

In addition, when the `CurrentValue`values are 0, we should still show the 0 in `table` output, where it seems we suppress the 0 value now (it is in the JSON doc).

**Comment by yugangw-msft** [comment] 2017-05-04 22:23
this is a dupe of #2333, but we can leave that as the general item and use this for individual command

**Comment by tjprescott** [comment] 2017-05-24 16:47
As a caveat, the table-formatter only works for table output. The official policy on TSV is: use `--query`.

**Closed** 2017-05-24 19:12 UTC
Labels: Compute, Output
