### ISSUE TITLE
az login has a bug! local variable 'token_entry' referenced before assignment

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15981] opened 2020-11-19 08:07 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

```
> az login -u azureclitest@azuresdkteam.onmicrosoft.com -p ***
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
local variable 'token_entry' referenced before assignment
Traceback (most recent call last):
  File "C:\yfy\env\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in execute
    raise ex
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 710, in _run_job
    six.reraise(*sys.exc_info())
  File "C:\yfy\env\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "c:\yfy\azure-cli\src\azure-cli\azure\cli\command_modules\profile\custom.py", line 158, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\_profile.py", line 213, in find_subscriptions_on_login
    username, password, tenant, self._ad_resource_uri)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\_profile.py", line 851, in find_from_user_account
    if not token_entry:
UnboundLocalError: local variable 'token_entry' referenced before assignment
```

When I input a wrong password, it tells me local variable 'token_entry' referenced before assignment. I don't know what it means.

**To Reproduce**

**Expected behavior**

**Environment summary**

Azure CLI 2.14.2
Window 10
PowerShell

**Additional context**

**Comment by jiasli** [comment] 2020-11-19 08:17
Duplicate of #15961

**Closed** 2020-12-31 02:32 UTC
Labels: Account, OKR3.2 Candidate, feature-request
