### ISSUE TITLE
az containerapp create hangs with invalid parameter --revision-suffix

### ISSUE THREAD

**Issue by jscheeres** [Azure/azure-cli#23934] opened 2022-09-19 14:02 UTC
The command _az containerapp create_ hangs infinite with invalid _--revision-suffix_.

Revision suffix must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character and cannot have '--'. And a length of max 64 characters.

**Comment by yonzhan** [comment] 2022-09-19 14:34
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-09-20 03:15
@jscheeres Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment] 2022-09-20 11:54
@jscheeres I tried creating with "--" value for suffix and it worked without any issue. Can you please share the value you were using which cause the process to hang?
`az containerapp update -n issue23934capp -g Issue23934 --image issue23934acr.azurecr.io/helloworld-mvc:1.0 --environment Issue23934env --ingress external --target-port 80 --registry-server issue23934acr.azurecr.io --revision-suffix "test--01" --registry-username issue23934acr --registry-password *****`

**Comment by jscheeres** [comment] 2022-09-20 12:13
The command below hangs infinite because the revision-suffix does not conforms the naming convention for revision-suffix.

az containerapp **create** \
                      --name xxxxx-handls-jupj \
                      --resource-group xxxx-tst-rg \
                      --environment xxxx-tst-cae \
                      --image xxxx.azurecr.io/xxxx.handlers:0.3.0-40495-container-a640 \
                      --min-replicas 0 \
                      --max-replicas 1 \
                      --registry-server xxxx.azurecr.io \
                      --registry-username xxxx \
                      --registry-password  \
                      --cpu 0.25 \
                      --memory 0.5 \
--revision-suffix 0.3.0-40495-container-a640

You executed an update, which doesn't give an error, but also doesn't set the right suffix.

**Comment by RakeshMohanMSFT** [comment] 2022-09-20 14:44
@jscheeres We are unable to reproduce this issue, please see the screenshot below. Are you using latest version of azure cli 2.40.0 and extension containerapp 0.3.11?
![image](https://user-images.githubusercontent.com/49954584/191288845-30e913a1-b25f-4807-90f1-dac5eabbaba9.png)

**Comment by jscheeres** [comment] 2022-09-20 17:57
Ok, i upgraded de az cli to 2.40.0. And executed the following command.

![image](https://user-images.githubusercontent.com/10026982/191328358-188d3819-0317-4362-9bc9-aba6ad3cdd55.png)

Creating the container app is "succeeded". It took at least 15/20 minutes. The output contains the revision-suffix.

![image](https://user-images.githubusercontent.com/10026982/191328885-81a3cc46-3b8f-411a-8f1e-7849abc11a57.png)

However when you look at the azure portal the container app does not show the revision name (yellow).

![image](https://user-images.githubusercontent.com/10026982/191329221-834f0ed4-121d-4429-997b-d41cdfe2bd23.png)

And the container app no revisions.

![image](https://user-images.githubusercontent.com/10026982/191329388-8884f9c9-b951-4ea6-bad5-41decec75138.png)

The parameter _--revision-suffix_ of the  _az containerapp create_ command is accepting invallid input. Because it is not allowed to start a revision-suffix with a numeric character. Like i said in the opening post: "_Revision suffix must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character and cannot have '--'. And a length of max 64 characters._"

The CLI should not accept invallid input for this parameter.

**Comment by panchagnula** [comment] 2022-09-27 23:26
@haroonf given the API is accepting this, very sure there is no validation on platform end. If this validation is something we haven't fixed on CLI, can you take care of it. Looks like CreateOrUpdate is allowing this revision name, but GET is not, hence the behavior.

**Comment by RakeshMohanMSFT** [comment] 2022-10-12 02:45
@jscheeres This is fixed in Containerapp-0.3.12.

**Closed by RakeshMohanMSFT** 2022-10-12 02:45 UTC
Labels: Container Instances, customer-reported, Client, needs-team-attention, CXP Attention, Auto-Assign, ContainerApp
