### ISSUE TITLE
[BUG] Azure CLI: Linux VM Run command can hang

### ISSUE THREAD

**Issue by ShreyasRmsft** [Azure/azure-cli#14642] opened 2020-08-04 08:29 UTC
### Describe the bug
There are times when a azure vm linux run command execution gets hung and remains in this state indefinitely and we are unable to queue new run commands on that VM. The 90 minute timeout mentioned in the docs does not kick in. Stopping and starting the VM also does not allow queueing a new run command.

One simple way to repro this is to restart the walinuxagent process while a run command script is executing. This is not the only reason why it's gotten hung though, it has happened a few times arbitrarily but restarting the walinuxagent is one definitive way to repro this issues.

### Expected behavior
There should be a server side timeout for the run command if the walinuxagent never reports back the status of the runcommand due to various reasons such as systems restarts etc.

### Actual behavior (include Exception or Stack Trace)
The previous command remains in progress indefinitely and we are unable to queue new commands even after the 90 min timeout described in the docs

### To Reproduce
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

One simple way to repro this is to restart the walinuxagent process while a run command script is executing.
Environment:

Name and version of the Library package used: https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest
Hosting platform or OS: Azure Linux VM, Debian.

**Comment by yonzhan** [comment] 2020-08-04 11:08
Linux VM

**Comment by nadesu** [comment] 2020-08-07 11:03
Can we have an update on this? We are using Azure 'Run command API' extensively for [GHPI control plan](https://github.com/github/ghpi-controlplane/) development, which is planned for Sep release. Appreciate your quick clarification, so that we revisit design choices.

**Comment by qwordy** [comment] 2020-08-10 12:22
Could you share you command and output? `az vm run-command invoke` with `--debug`
You can try Azure Powershell or REST API to see if this issue still exists. If so, it may be a service problem.

**Comment by qwordy** [comment] 2020-08-24 04:55
I tested systemctl restart walinuxagent. It executes successfully. I think the problem is https://docs.microsoft.com/en-us/rest/api/compute/virtual%20machines%20run%20commands/runcommand. This API does not allow run multiple commands at the same time. I run az vm run-command invoke -g fy3 -n vm --command-id RunShellScript --scripts "sleep 60s" twice. The 2nd one returns Run command extension execution is in progress. Please wait for completion before invoking a run command. If a command hangs, then you cannot run any command any more.

**Comment by qwordy** [comment] 2020-09-29 05:58
Hi guys, does RemoveRunCommandLinuxExtension or RemoveRunCommandWindowsExtension solve your problem?

**Comment by nadesu** [comment] 2020-09-29 06:31
It works with the provided work-around. When the issue is present, we run 'az vm run-command invoke -g MyResourceGroup -n MyVM --command-id RemoveRunCommandLinuxExtension' that will remove the extension. When the RunCommand is re-run, the extn is automatically installed and the flow goes through. 
However, I will suggest that the time-out is honoured and make the above steps transparent to the client in the longer run.

**Comment by qwordy** [comment] 2020-09-29 07:13
Hi service team, can you confirm that service doesn't honor the 90 min timeout defined in doc?
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command#restrictions
And if it is a bug, please fix it. Thanks!

**Comment by axayjo** [comment] 2020-10-01 17:48
Looking into this issue.

**Comment by axayjo** [comment] 2020-10-15 06:47
If there's no communication between the Agent and Extension for 25 minutes, the fail fast mechanism is triggered. This is by design with all VM Extensions, not just Run Command. I'll run this bug by the team update this thread.

**Comment by ManuelMinkAtBOSCH** [comment] 2020-11-25 11:08
That issue is so worse!

We update our VMs via run-command, before we install some tools on it.
But for two weeks now our deployments fail on CentOS7 VMs with infinite wait when executing:
            az vm run-command invoke -g $(resourceGroup) -n $(vmName) --command-id RunShellScript --scripts "yum makecache; yum upgrade -y "

I figured out, that there is an update for the WALinuxAgent from Version 2.2.45 to 2.2.46.

What happens is, that yum tries to upgrade all packages, including walinuxAgent and the operation breaks in the middle, as the connection got lost, when the agent is killed due to the update.
This results in an inconsistent package state, and "Run command extension execution is in progress." which makes it impossible to get the vm under control again.

The only way to get it back, is to manually uninstall both installed versions and install the new one.

**To workaround this issue, my solution at the moment is to update the WALinuxAgent package at first. Using a systemd unit file which we can execute completely also when losing connection.**

cat WALinuxAgentUpdate.service

> [Unit]
> Description=Update waagent
> 
> [Service]
> Type=oneshot
> ExecStart=/bin/yum update -y WALinuxAgent
> StandardOutput=journal
> 

```
encoded=`base64 -w0 WALinuxAgentUpdate.service`
az vm run-command invoke -g $(resourceGroup) -n $(vmName) --command-id RunShellScript --scripts "echo $encoded | base64 -d > /usr/lib/systemd/system/WALinuxAgentUpdate.service; systemctl daemon-reload; yum makecache; bash -c 'systemctl start WALinuxAgentUpdate' &"
```


### Problem Details:
tail yum_upgrade_err.log
**Non-fatal POSTUN scriptlet failure in rpm package WALinuxAgent-2.2.45-1.el7.noarch**

rpm -qa | grep WALinuxAgent

> WALinuxAgent-2.2.45-1.el7.noarch
> WALinuxAgent-2.2.46-2.el7_9.noarch

yum info WALinuxAgent

> Loaded plugins: fastestmirror, langpacks
> Loading mirror speeds from cached hostfile
>  * base: nyc.mirrors.clouvider.net
>  * extras: mirror.keystealth.org
>  * updates: mirror.vtti.vt.edu
> Installed Packages
> Name        : WALinuxAgent
> Arch        : noarch
> Version     : 2.2.45
> Release     : 1.el7
> Size        : 1.0 M
> Repo        : installed
> From repo   : openlogic
> Summary     : The Microsoft Azure Linux Agent
> URL         : https://github.com/Azure/WALinuxAgent
> License     : Apache License Version 2.0
> Description : The Azure Linux Agent supports the provisioning and running of Linux
>             : VMs in the Azure cloud. This package should be installed on Linux disk
>             : images that are built to run in the Azure environment.
> 
> Name        : WALinuxAgent
> Arch        : noarch
> Version     : 2.2.46
> Release     : 2.el7_9
> Size        : 1.8 M
> Repo        : installed
> Summary     : Microsoft Azure Linux Agent
> URL         : https://github.com/Azure/WALinuxAgent
> License     : ASL 2.0
> Description : The Azure Linux Agent supports the provisioning and running of Linux
>             : VMs in the Azure cloud. This package should be installed on Linux disk
>             : images that are built to run in the Azure environment.
> 

yum-complete-transaction --cleanup-only

> Loaded plugins: fastestmirror, langpacks
> Loading mirror speeds from cached hostfile
>  * base: ftp.nluug.nl
>  * epel: epel.mirror.wearetriple.com
>  * extras: ams.edge.kernel.org
>  * updates: mirror.amsiohosting.net
> Cleaning up unfinished transaction journals
> Cleaning up 2020-11-24.14:07.06
> [root@qa-teamserver tmp]# yum update -y WALinuxAgent
> Loaded plugins: fastestmirror, langpacks
> Loading mirror speeds from cached hostfile
>  * base: ftp.nluug.nl
>  * epel: epel.mirror.wearetriple.com
>  * extras: ams.edge.kernel.org
>  * updates: mirror.amsiohosting.net
> Resolving Dependencies
> --> Running transaction check
> ---> Package WALinuxAgent.noarch 0:2.2.45-1.el7 will be updated
> ---> Package WALinuxAgent.noarch 0:2.2.46-2.el7_9 will be an update
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
>  Package                                      Arch                                   Version                                           Repository                                        Size
> Updating:
>  WALinuxAgent                                 noarch                                 2.2.46-2.el7_9                                    extras-openlogic                                 420 k
> 
> Transaction Summary
> 
> Upgrade  1 Package
> 
> Total size: 420 k
> Downloading packages:
> Running transaction check
> Running transaction test
> 
> 
> Transaction check error:
>   package WALinuxAgent-2.2.46-2.el7_9.noarch is already installed
>

**Comment by dctucker** [comment] 2021-01-21 18:25
We're still seeing this problem and it's consuming a lot of our time in the process of trying to extract data from a production instance. Has there been any follow up on this since the most recent comment?

**Comment by axayjo** [comment] 2021-01-22 21:19
@koralski, can you please take a look at this issue?

**Comment by joshspicer** [comment] 2021-02-09 11:32
+1 this issue is really annoying!  Thank to @nadesu for his workaround above - this is working wonderfully for me so far:

`az vm run-command invoke -g MyResourceGroup -n MyVM --command-id RemoveRunCommandLinuxExtension`

**Comment by axayjo** [comment] 2021-07-01 07:28
@koralski any update on this issue? Is this an issue with the VM Agent or the Run Command extension?

**Comment by avirishuv** [comment] 2021-11-09 23:56
Assigning to @amjads1 and removing @axayjo

**Comment by amjads1** [comment] 2021-12-08 08:14
Apologies for the delay, looking into the issue.

**Comment by koralski** [comment] 2021-12-08 21:22
This issue was fixed in October 2021.

**Comment by amjads1** [comment] 2021-12-09 07:57
Closing this item as the issue is fixed. Please feel free to re-open if you are still experiencing the issue or need any further help.

**Closed by amjads1** 2021-12-09 07:57 UTC
Labels: Compute, Service Attention, Compute - Extensions, feature-request
