### ISSUE TITLE
storage file share download-batch with snapshot is missing files

### ISSUE THREAD

**Issue by jimmythedog** [Azure/azure-cli#9961] opened 2019-07-17 11:15 UTC
## Describe the bug

If a file is subsequently deleted **after** creating the snapshot, it will **not** be downloaded when using the `--snapshot` argument in the `az storage file download-batch` command

**Command Name**
`az storage file download-batch ... --source [SHARE_NAME] --destination [DEST_DIR] --snapshot [SNAPSHOT]`

**Errors:**

## To Reproduce:

- Create a file in the file share
- Create a snapshot
- Delete the file
- `az storage file download-batch --account-name {} --account-key {} --source {} --destination {} --no-progress --snapshot {}`
- The file that was in the snapshot does not get downloaded

## Expected Behavior
The file that existed in the snapshot should be downloaded

## Environment Summary
```
Linux-4.19.0-5-amd64-x86_64-with-debian-10.0
Python 3.6.5
Shell: bash

azure-cli 2.0.69

```

**Comment by limingu** [comment] 2019-07-22 02:35
The root cause is that download-batch command only list and check the current files matching the pattern. If the file is deleted and only exists in the snapshot, download-batch command won't download it. The fix should let download-batch check the snapshot when the snapshot parameter is provided.

**Comment by yonzhan** [comment] 2020-06-01 03:18
add to S172

**Comment by zhoxing-ms** [comment] 2020-06-23 03:53
Yes, this problem is caused by that the [list-directories-and-files](https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files) dose not return the file data which is deleted and only exists in the snapshot.
Fixing this problem requires that the Service's REST API support returns all files in the snapshot, including files that have been deleted but exist in the snapshot.

**Comment by xiafu-msft** [comment] 2020-12-10 08:08
This is a duplicate of https://github.com/Azure/azure-cli/issues/9959
@Juliehzl can you help take a look and confirm if it's a CLI bug?

**Comment by zhoxing-ms** [comment] 2020-12-11 08:30
@xiafu-msft Thanks for your reminder, we have submitted a PR #16244 to fix this problem~

**Comment by zhoxing-ms** [comment] 2020-12-24 06:58
> @xiafu-msft Thanks for your reminder, we have submitted a PR #16244 to fix this problem~

I's repeated with #16275

**Closed by zhoxing-ms** 2020-12-24 06:58 UTC
Labels: Storage, customer-reported, feature-request, needs-team-triage
