### ISSUE TITLE
--help should use `less`

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#120] opened 2016-04-19 17:06 UTC
The standard behavior for explicit help is to use the less utility or equivalent paginator rather than simply dumping the help text to stdout.  The reason for this is that it allows you to page through the help in a consistent fashion, then exit the help and return the terminal: your command history isn't scrolled off.

**Comment by JasonRShaver** [comment] 2017-11-03 01:08
Clean

**Comment by adewaleo** [comment] 2019-03-05 21:34
closing this as it is a duplicate of #7587

cc @tjprescott @JasonRShaver @binderjoe @johanste

**Comment by adewaleo** [comment] 2019-06-25 05:41
reopening this as #7587 will be closed

**Comment by adewaleo** [comment] 2019-07-26 21:39
I will be closing this for now as CLI team does not have the bandwidth to implement this in the near feature and there isn't a high demand for this feature.

**Closed by adewaleo** 2019-07-26 21:39 UTC
Labels: Documentation, Output
