### ISSUE TITLE
az aks browse doesn't work when one of the pod is in pending state

### ISSUE THREAD

**Issue by techiearun** [Azure/azure-cli#6305] opened 2018-05-08 15:55 UTC
**Describe the bug**
I had deployed an application with 5 replicas all pods were running, and tried to access the 'az aks browse -g group -n name' the browser opened with kubernetes dashboard. But when i scaled the replicas to 100, due to a node capacity few pods were in pending state and this has caused connection error and the kubernestes dashboard crashed. Again tried to execute 'az aks browse.....' but got the below error

Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: unable to forward port because pod is not running. Current status=Pending

**To Reproduce**
1. Deploy app with 5 replicas and 2 nodes
2. Execute 'az aks browser -g <<resource_group>> -n <<clustername>> 
3. Ecale the app to 100 replicas
4. Few pods goes to pending state
5. Kubernetes cluster dashboard closes / crashes
6. Execute 'az aks browser -g <<resource_group>> -n <<clustername>> 
7. Dashboard doesnt open, instead the error message shown
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: unable to forward port because pod is not running. Current status=Pending

**Expected behavior**
I expect the dashboard to open regardless of pod state, this is how gks behaves.  This needs to work in same fashion as gks. Otherwise,  its disturbing developer experience 

**Environment summary**
AZ cli on mac, connected to AKS cluster

**Comment by mboersma** [comment] 2018-05-22 22:26
> I expect the dashboard to open regardless of pod state

That error message is referring to the dashboard pod itself, which apparently after crashing is in `Pending` state. It's not possible to see the dashboard until that pod is `Running` again.

If this is a reliable way to crash the dashboard pod, that's where we should attempt to fix things. I'll take this information to the AKS team and see if we can reproduce it and make the dashboard more robust in this situation.

**Comment by umaxfun** [comment] 2018-05-28 22:09
Me too, cluster is shown to be running, but cannot access the dashboard =(

**Comment by umaxfun** [comment] 2018-05-29 00:08
I see this:
```
➜  ~ az aks browse --resource-group qqq --name www
Merged "www" as current context in /var/folders/by/ybjhgc315xq06bjtvcv9jhw80000gn/T/tmplxqd97l3
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: unable to forward port because pod is not running. Current status=Pending
➜  ~ kubectl get pods
No resources found.
➜  ~ kubectl get deployments
No resources found.
➜  ~ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   2d
```
And no clue how to see the console =(

**Comment by umaxfun** [comment] 2018-05-30 13:47
This was my solution: https://github.com/Azure/AKS/issues/394
Just to drop the cluster and recreate ;)

**Comment by dreamPathsProjekt** [comment] 2018-05-30 18:03
Also Heapster pod in kube-system ns is restarting, describe shows no available nodes. I can run pods on nodes without problem.

**Comment by troydai** [comment] 2018-06-01 16:56
I'm going to close this issue since it is not directly related to the CLI.

**Closed by troydai** 2018-06-01 16:56 UTC
Labels: ACS, Question
