### ISSUE TITLE
az ad group create is not idempotent

### ISSUE THREAD

**Issue by bmukes** [Azure/azure-cli#8624] opened 2019-02-22 22:58 UTC
if you execute az ad group create with options --display-name, --mail-nickname, --subscription then multiple groups within Azure Active Directory are created.  I was under the impression that all Azure CLI commands were to be idempotent.  If you create more than one of these groups and then attempt az ad group member add you will get an error message.

**Comment by bmukes** [comment] 2019-02-22 23:00
After reading the post I must clarify. that you must run the command more than once in order to get a duplicate.

**Comment by marstr** [comment] 2019-02-28 00:18
Howdy, I've confirmed that running this operation twice creates two groups with the same display name and mail nickname.

If this is blocking you, do know that you can work around it by specifying the objectID rather than the display name when adding resources to it. I need to look-up the constraints on groups. If there is no restriction on having two groups with the same display name then I'll have to close this as by-design. It does feel conspicuous though.

**Comment by marstr** [comment] 2019-02-28 00:25
Alright, I've checked around and can't find any documentation that says you can't have two active directory groups with the the same display name. For that reason I think our hands are tied and this is by design.

**Closed** 2019-02-28 00:26 UTC
Labels: Authorization-cli, Won't Fix
