### ISSUE TITLE
Add `--redirect-port` to `az login` command

### ISSUE THREAD

**Issue by cecheta** [Azure/azure-cli#28425] opened 2024-02-21 19:18 UTC
**Related command**

`az login`

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Similar to the `azd auth login` command, it would be good to have the ability to specify the redirect port used in the browser login for `az login`. At the moment, it uses a random ephemeral port.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by yonzhan** [comment] 2024-02-21 19:19
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-04-08 06:03
Duplicate of #24626

**Closed by jiasli** 2024-04-08 06:03 UTC
Labels: Account, feature-request, Azure CLI Team
