### ISSUE TITLE
Can't create a service principle and getting cryptic error.

### ISSUE THREAD

**Issue by yoavweber** [Azure/azure-cli#23382] opened 2022-07-29 12:23 UTC
## Describe the bug
Can't create a sp and getting cryptic error.

**Command Name**
`az ad sp create-for-rbac -n "test" --role Contributor --scopes /subscriptions/<subscription_id>`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'RoleAssignmentsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/commands.py", line 54, in graph_err_handler
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 1255, in create_service_principal_for_rbac
    _create_role_assignment(cmd.cli_ctx, role, sp_oid, None, scope, resolve_assignee=False,
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 196, in _create_role_assignment
    assignments_client.config.subscription_id)
AttributeError: 'RoleAssignmentsOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Run the following command:
`az ad sp create-for-rbac -n "test" --role Contributor --scopes /subscriptions/<subscription_id>`

## Expected Behavior
Create a new sp, or provide an error message to why the operation has failed

## Environment Summary
```
Linux-5.18.0
Python 3.9.13
Installer: DEB

azure-cli 2.38.0

Extensions:
account 0.2.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment] 2022-07-29 14:04
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment] 2022-08-03 03:31
@yoavweber Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment] 2022-08-03 04:11
@yoavweber We are unable to reproduce this issue. Upgrade to the latest version of CLI [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and check again, though i am also using the same 2.38.0 from a windows machine.

`az ad sp create-for-rbac -n "issue23382new" --scopes /subscriptions/<subscriptoin_id> --role Contributor`
Creating 'Contributor' role assignment under scope '/subscriptions/<subscription_id>'
The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
{
  "appId": "2fc8745d-7d8e-4d73-****-****",
  "displayName": "issue23382new",
  "password": "<pwd>",
  "tenant": "<tenant_id>"
}

Similar environment too.
az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.3"
  }
}

**Comment by jiasli** [comment] 2022-08-03 05:39
Duplicate of #19640

**Closed by jiasli** 2022-08-03 05:39 UTC
Labels: Graph, customer-reported, needs-author-feedback, CXP Attention, Auto-Assign
