### ISSUE TITLE
__init__() got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by whitelancer** [Azure/azure-cli#23641] opened 2022-08-23 14:57 UTC
## Describe the bug

Running a simple `az login` has started to kick back with the following error.  I am running the same version as I have been for weeks now without updates.
```
tcgetpgrp failed: Not a tty
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
```
```
{
  "azure-cli": "2.34.0",
  "azure-cli-core": "2.34.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.3",
    "alias": "0.5.2",
    "interactive": "0.4.5"
  }
}
```

**Command Name**
`az login`

**Errors:**
```

The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/home/computer/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 177, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 727, in find_using_common_tenant
    client = self._create_subscription_client(credential)
  File "/home/computer/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 818, in _create_subscription_client
    client = client_type(credential, api_version=api_version,
TypeError: __init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.3 LTS
Python 3.8.10
Installer: PIP

azure-cli 2.34.0 *

Extensions:
alias 0.5.2
interactive 0.4.5
account 0.2.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 10.2.0
```

**Comment by yonzhan** [comment] 2022-08-24 00:43
@jiasli for awareness

**Comment by bebound** [comment] 2022-08-24 01:48
Duplicate of https://github.com/Azure/azure-cli/issues/21189

**Closed by bebound** 2022-08-24 01:48 UTC
Labels: bug, Account, customer-reported, Auto-Assign, Azure CLI Team
