### ISSUE TITLE
azure-cli 2.0.70 az interactive  No module named 'prompt_toolkit.interface'

### ISSUE THREAD

**Issue by pameruoso** [Azure/azure-cli#10129] opened 2019-08-02 11:13 UTC
## Describe the bug
After upgrading azure-cli to version 2.0.70 the az interactive command is broken.
**Command Name**
`az interactive`

**Errors:**
```
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
Temp\pip-install-rtk110ve\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-rtk110ve\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 305, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\interactive\custom.py, ln 41, in start_shell
.azure\cliextensions\interactive\azext_interactive\__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
cliextensions\interactive\azext_interactive\azclishell\app.py, ln 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- upgrade az-cli to version 2.0.70
- `az interactive`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.70

Extensions:
interactive 0.4.3

```

**Comment by yugangw-msft** [comment] 2019-08-02 17:29
dupe of #10088

**Closed by yugangw-msft** 2019-08-02 17:29 UTC

**Comment by pameruoso** [comment] 2019-08-05 09:19
Hi the proposed fix is not working in powershell, neither in WSL - Debian. No pip command available.
