### ISSUE TITLE
az storage account keys list throwing errors after updating from azure-cli-2.0.45 to azure-cli-2.13??

### ISSUE THREAD

**Issue by tuttipazzo** [Azure/azure-cli#15709] opened 2020-10-28 23:00 UTC
So I updated from 2.0.45 to 2.13 in hopes of getting the same options listed in 

https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-cli

But I was wrong.  Seems 2.13 is not new enough.  So I just decided to not use 
'--enabled-protocols SMB' option and continued on my merry way.

I just ran this command:

az storage account keys list -n <storage account name>

and it spit out the strack trace below.  BTW that cmd worked fine 2.0.45.

## Describe the bug

**Command Name**
`az storage account keys list`

**Errors:**
```
'StorageManagementClient' object has no attribute 'config'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 775, in default_command_handler
    client = client_factory(cmd.cli_ctx, command_args) if client_factory else None
cli/command_modules/storage/_client_factory.py, ln 150, in cf_sa_for_keys
    client.config.enable_http_logger = False
AttributeError: 'StorageManagementClient' object has no attribute 'config'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account keys list -n {}`

## Environment Summary
```
Linux-5.3.18-lp152.47-default-x86_64-with-glibc2.3.4
Python 3.6.10
Installer: PIP

azure-cli 2.13.0 *

```

**Comment by yonzhan** [comment] 2020-10-29 02:20
storage

**Comment by Juliehzl** [comment] 2020-10-30 04:34
Hi @tuttipazzo, may I know your installed version for azure-mgmt-storage?

**Comment by tuttipazzo** [comment] 2020-11-03 23:36
python3-azure-mgmt-storage-16.0.0-26.1.  So I had to deinstall everything related to azure-cli by hand (OUCH).  The problem was that I didn't remove the old azure-cli like so:

sudo zypper -n rm -y --clean-deps azure-cli

That got rid of all the older pkg azure-cli dependencies.  In the end I wind up re-installing the older version as other things were breaking using the newer azure-cli.  But that was my laptop which has been upgraded twice.  I spun up an Azure Leap15.2 VM, deinstalled (using --clean-deps) the azure-cli that came with leap, added ms gpg, azure-cli repo, and installed the upstream azure-cli and I have to errors.  Basically followed this:

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum

but added priority=50 to the repo definition.
Haven't tried that option.  You can close this.

**Comment by Juliehzl** [comment] 2020-11-04 03:07
Hi @tuttipazzo, thanks a lot for your information. 
The root cause for your issue should be caused by azure-mgmt-storage 16.0.0, which has breaking changes compared with 11.2.0. When you install azure cli with pip, your azure-mgmt-storage 16.0.0 will take effect and azure cli is not compatible with the new version. A workaround is that you could downgrade azure-mgmt-storage to 11.2.0 with `pip install azure-mgmt-storage==11.2.0`.

And you could also uninstall pip installed azure cli and install with the guide https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt, which will not be influenced by your local azure-mgmt-storage version.

**Comment by Juliehzl** [comment] 2020-11-04 03:08
@jsntcy please also take a look for this track 2 issue in storage module.

**Comment by jsntcy** [comment] 2020-11-04 03:34
Will fix this issue when CLI migrate to track2 storage SDK in this sprint, currently CLI still only support track1 storage SDK.

**Comment by Juliehzl** [comment] 2020-11-26 06:58
Hi @tuttipazzo, the issue should be already fixed in latest cli version. Please update cli with `az upgrade` and try again.

**Closed by Juliehzl** 2020-11-26 06:58 UTC
Labels: OKR3.2 Candidate, Storage, customer-response-expected, feature-request
