### ISSUE TITLE
az login (redirects to localhost and hits ERR_CONNECTION_REFUSED)

### ISSUE THREAD

**Issue by dsteeley** [Azure/azure-cli#26199] opened 2023-04-19 13:24 UTC
## Describe the bug
Similar to other recent issues but slightly different symptoms. I run az login, follow through the interactive login process and the oauth flow redirects me to localhost:<port> where I hit an ERR_CONNECTION_REFUSED. 
Using edge browser. 
`--use-device-code` does work. 

From the debug logs there is also a link to localhost:<port>?error=abort which I've tested and still hit an ERR_CONNECTION_REFUSED. 
It looks to me like `az` is unable to open a connection on localhost:<port> which is leading to this issue. I'm concerned about this as I later tried to run `az ad group list --debug` and hit issues relating to my device not being managed which I've previously never hit so suspect it's a symptom of the same issue. 

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
- `az login --debug`

## Environment Summary
```
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.6 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.47.0

Extensions:
azure-devops 0.26.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment] 2023-04-19 13:24
Thank you for opening this issue, we will look into it.

**Comment by cclark-work** [comment] 2023-04-19 18:18
Getting the same thing running in Ubuntu 22.04 in WSL2
`azure-cli is already the newest version (2.47.0-1~jammy)`

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

It opens the browser window and prompts me for my username, I click on it and then it redirects to something like this:
`http://localhost:37703/?code=0.AQEAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaAF0.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wUA9P_IhyZAukuBZmlJVGg0kli_hAxwezGF_DsRLr-30hbfOy18b3X6ZngrWNu0lJ5-
...
&state=RSWHYicFyuqstkNI&session_state=5d78015d-af92-4042-b278-73ae72a88f13`

**Comment by bebound** [comment] 2023-04-20 06:33
I guess this is the same as #26180

**Comment by jiasli** [comment] 2023-04-20 06:44
Duplicate of #26180

**Closed** 2023-04-20 06:43 UTC
Labels: Account, question, Graph, customer-reported, Auto-Assign, Azure CLI Team

**Comment by cclark-work** [comment] 2023-04-20 13:27
Yes, as mentioned in #26180  executing `wsl --update --pre-release` to get the patch has worked for me
