### ISSUE TITLE
WebApp:az webapp deployment slot create DOESN'T duplicate all settings from source slot

### ISSUE THREAD

**Issue by panmail** [Azure/azure-cli#17531] opened 2021-03-31 14:27 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The following powershell command doesn't duplicate all settings from the source slot.
`az webapp deployment slot create --name 'newSlotName' --resource-group 'rscGroup' --slot 'test' --configuration-source 'srcSlotName' --subscription 'subID' --debug`

**To Reproduce**
run command above and found that the source slot setting of "ASPNETCORE_ENVIRONMENT" was not duplicated over to the new slot.

**Expected behavior**

**Environment summary**

I ran this in Win10 PS ISE, Azure portal powershell with same result.

**Additional context**

**Comment by panchagnula** [comment] 2021-03-31 16:45
@panmail thanks for reporting - out of curiosity is this specific setting - "set as slot Setting or not"? I believe only settings marked slot settings should be copied over & not others - portal doesn't follow this rule. Can you please share this info.

@Kotasudhakarreddy  can you or Parveen test this behavior & share your notes as well? Thank you.

**Comment by panmail** [comment] 2021-03-31 17:16
@panchagnula, I can confirm that if using PS, then 'yes' ONLY non-slot settings are cloned over; however, when using the Azure portal UI, then ALL (slot and non-slot) settings are cloned over.  I would like to see PS to have same behavior as portal.
![image](https://user-images.githubusercontent.com/7851873/113184443-0835bd80-920a-11eb-89d0-94b863925b7e.png)

**Comment by panchagnula** [comment] 2021-08-18 16:31
Making this duplicate of original issue #6638

**Closed by panchagnula** 2021-08-18 16:31 UTC
Labels: bug, Web Apps, Service Attention
