### ISSUE TITLE
Unable to upload Blob with --auth-mode=key

### ISSUE THREAD

**Issue by tomasszabo** [Azure/azure-cli#10861] opened 2019-10-16 13:07 UTC
## Describe the bug

**Bug**
Seems that Signature parameter in HTTP request is wrongly calculated (see XML error description from server bellow). 

**Command Name**
`az storage blob upload`

**Errors:**

Response from Blob Storage (using `--debug` parameter):
```
<?xml version="1.0" encoding="utf-8"?>
<Error>
	<Code>AuthenticationFailed</Code>
	<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:77402b9f-e01e-002f-2520-8494db000000Time:2019-10-16T12:55:06.3428350Z</Message>
	<AuthenticationErrorDetail>The MAC signature found in the HTTP request '***REDACTED***' is not the same as any computed signature. Server used following string to sign: 'PUT758x-ms-blob-content-type:application/xmlx-ms-blob-type:BlockBlobx-ms-client-request-id:2cf4f0bc-f014-11e9-b44c-***REDACTED***x-ms-date:Wed, 16 Oct 2019 12:55:06 GMTx-ms-version:2018-11-09/devmcom***REDACTED***'.</AuthenticationErrorDetail>
</Error>
```

Azure CLI interpretation of Blob Storage response:
```
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- prepare Container with Public Access Level "Blob" 
- parameter --type is "blob"
- parameter --auth-mode is "key"
- parameter --content-type is "application/xml"
- `az storage blob upload -f {} -c {} -n {} --content-type {} --type {} --auth-mode {} --account-key {} --account-name {} --debug`

## Expected Behavior
File should be uploaded to Blob Storage Container

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.74 *

```

**Comment by Juliehzl** [comment] 2019-10-17 02:11
Hi @tomasszabo, I can reproduce your error when I typo account-key on purpose. So can you check your storage account key is correct or not? 
In addition, if you don't provide account-key and with access permission to the storage account, you also can do the upload. So you can also remove account-key value if you don't know what is the correct account-key.

**Comment by Juliehzl** [comment] 2019-10-17 02:13
dupe of #9995 for inaccurate error message

**Comment by tomasszabo** [comment] 2019-11-08 12:04
@Juliehzl 

1. All values are correct, there's no typo.
2. This is used by our Build Server, it doesn't have any Azure Identity (and we don't want to create one), therefore account-key option must be used.
3. Just checked on v2.0.75, no difference, problem is still there
4. Just FYI - using sasToken option upload works, but it's really slow in comparison with Az Module in PowerShell. However, we don't want to use sasToken, but account-key.

**Comment by Juliehzl** [comment] 2019-11-18 07:26
Hi @tomasszabo when you provide `account-key` value in your command, you don't need to use `--auth-mode key`.
But here I think you get such kind of error due to firewall. Can you check your storage account network rules using `az storage account show -n {accountname} --query networkRuleSet`? 
Please make sure your ip address is allowed in `ipRules` or vnet is allowed in `virtualNetworkRules` or `defaultAction` is "Allow".

**Comment by tomasszabo** [comment] 2019-11-18 12:39
@Juliehzl 

1. As I wrote in my previous post, using sasToken option or using Az Module in Powershell works, therefore there cannot be any "firewall issues", because then the other methods will also not work. However, if you want to know it exactly, there are no network restrictions defined on Blob Storage end.
2. As mentioned in Error Description in response from Blob Storage, Signature field, that Azure CLI is sending, is wrongly calculated. Take a look at this Signature field, how it's calculated in Azure CLI. It can be so simple that time difference between client/server is too big and it can invalidate the signature.

**Comment by yonzhan** [comment] 2019-12-15 10:50
any update for this issue?

**Comment by qianwens** [comment] 2020-02-13 14:34
Hi @tomasszabo, an error like "The MAC signature found in the HTTP request***" is a generic error message indicating that the access key is incorrect or does not have permission when sending a request to Azure storage. I tried exactly the same command in my environment, but I cannot repro. Could you please help provide more information like OS and file size? 
Could you please try this command for some other storage account and check if it can repro? 
Could you please try to add quotes "" for the storage key and

**Comment by qianwens** [comment] 2020-02-13 14:36
Hi @tomasszabo, an error like "The MAC signature found in the HTTP request***" is a generic error message indicating that the access key is incorrect or does not have permission when sending a request to Azure storage. I tried exactly the same command in my environment, but I cannot repro. Could you please help provide more information like OS and file size? To verify if it is due to some specific storage account, please help try this command for some other storage account and check if it can repro. Besides, could you please also try to add quotes "" for the storage key and check if it can work?

**Comment by qianwens** [comment] 2020-02-28 08:35
Close this issue since there is no response. Please help create a new issue if you still have questions.

**Closed by qianwens** 2020-02-28 08:35 UTC
Labels: Storage, customer-response-expected
