### ISSUE TITLE
Azure login issue: RuntimeError: 0. The ID token is not yet valid. 

### ISSUE THREAD

**Issue by KavaliAbhilash** [Azure/azure-cli#20822] opened 2021-12-23 13:04 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1640257966.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1640264082,
  "nbf": 1640264082,
  "exp": 1640267982,
  "aio": "AWQAm/8TAAAAD5XQ4zFzM/6ir5nG4Mni3g+nwHTrhoYaZQoy2BCjlTOYhOkNdYezGOf9D0M64kj42krpaT6qJSGcrVpVxiWmE0QNOHaO9hINNKgW1SRLiBPgeqOKfGF9tHR6DrtX8i3w",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "7746977328e538c0a1540e516e579513722f2751129fff7c4ec640157fcc73db",
  "preferred_username": "aravindk543578@gmail.com",
  "rh": "0.AXEAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAMI.",
  "sub": "y_nSuFCSri2THgGkY2F6F1Dsy_s016h9h61xk2w-6ZI",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "jRivUV-o6EKotK6nhJuIAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 147, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1640257966.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1640264082,
  "nbf": 1640264082,
  "exp": 1640267982,
  "aio": "AWQAm/8TAAAAD5XQ4zFzM/6ir5nG4Mni3g+nwHTrhoYaZQoy2BCjlTOYhOkNdYezGOf9D0M64kj42krpaT6qJSGcrVpVxiWmE0QNOHaO9hINNKgW1SRLiBPgeqOKfGF9tHR6DrtX8i3w",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "7746977328e538c0a1540e516e579513722f2751129fff7c4ec640157fcc73db",
  "preferred_username": "aravindk543578@gmail.com",
  "rh": "0.AXEAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAMI.",
  "sub": "y_nSuFCSri2THgGkY2F6F1Dsy_s016h9h61xk2w-6ZI",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "jRivUV-o6EKotK6nhJuIAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

```

**Comment by yonzhan** [comment] 2021-12-23 14:19
@jiasli for awareness

**Comment by jiasli** [comment] 2021-12-24 02:31
Duplicate of #20388

**Closed by jiasli** 2021-12-24 02:31 UTC
Labels: Account, customer-reported
