### ISSUE TITLE
Question about VM Create

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#3574] opened 2017-06-01 13:48 UTC
### Description
**Outline the issue here:**
Suppose I'd created VM using 'az vm create ... --public-ip-address-dns-name myvm-dnsname-xx' in the past.
Its FQDN is myvm-dnsname-xx.<location>.cloudapp.azure.com
I use this FQDN instead of IP-address to connect to VM.

1)
Now suppose I by mistake run the same command to create new VM as in the past.
My tests show:
- no error message is thrown
- no new VM is created, instead of it I get the same command output as it is after new VM is successfully created
- it is really confusing and not correct behavior from my point of view

2)
Suppose I run the command to create new VM which has with the same '--public-ip-address-dns-name' value (suppose everything else I was able to change).
In this case I get an error message (which is good from my point of view):
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "DnsRecordInUse",
    "message": "DNS record myvm-dnsname-xx.northeurope.cloudapp.azure.com is already used by another public IP.",
    "details": []
  }
}  Correlation ID: a87eef2b-477c-42f7-b6d6-cf1ee012d0fe

My question is why I don't get the error message in case 1)?
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
According to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
root@Alexey-HP:~# az --version | head -1
azure-cli (2.0.7)
**OS Version:** What OS and version are you using?  
Answer here:
D:\>ver
Microsoft Windows [Version 10.0.15063]
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Windows

**Comment by tjprescott** [comment] 2017-06-01 14:02
You shouldn't get an error in case 1, if I understand your scenario correctly. You are re-running the same command with the same parameters, yes?  In that case, you should get no error and the create should succeed.  This is because creates in Azure should be idempotent, or goal-seeking. However, due to issue #3563, I would actually expect your scenario to fail (though it shouldn't).

**Comment by alexeyshishkin01** [comment] 2017-06-01 14:26
in case 1 I run exactly the same command to create VM as in the past.
in my case I'm creating another VM with the same:
--name myvm-xx
--public-ip-address-dns-name myvm-dnsname-xx
--os-disk-name myosdisk-xx
in the same resource group and in the same location

And I don't get a warning message that another VM has at least one duplicate either in: --name, --public-ip-address-dns-name or --os-disk-name.

In case 2) duplicate is found correctly and warned me about it.

So, is it possible to fix the behavior in case 1) to get warning? because new VM is not created and no warning is thrown.

**Comment by alexeyshishkin01** [comment] 2017-06-01 14:42
a list of my tests below, from my point of view tests 1) and 5) should have given error messages, but it doesn't happen:

0)VM is created
az vm create \
--name myvm-xx \
--resource-group myresourcegroup \
--image postgres-pro:postgres-pro-standard:hrly:9.6.2 \
--location northeurope \
--size Standard_DS1 \
--admin-password <azureuserpassword> \
--admin-username azureuser \
--authentication-type password \
--public-ip-address-dns-name myvm-dnsname-xx \
--os-disk-name myosdisk-xx

1)no error, no new VM is created
az vm create \
--name myvm-xx \
--resource-group myresourcegroup \
--image postgres-pro:postgres-pro-standard:hrly:9.6.2 \
--location northeurope \
--size Standard_DS1 \
--admin-password <azureuserpassword> \
--admin-username azureuser \
--authentication-type password \
--public-ip-address-dns-name myvm-dnsname-xx \
--os-disk-name myosdisk-xx

2)DNS error
az vm create \
--name myvm-02 \
--resource-group myresourcegroup \
--image postgres-pro:postgres-pro-standard:hrly:9.6.2 \
--location northeurope \
--size Standard_DS1 \
--admin-password <azureuserpassword> \
--admin-username azureuser \
--authentication-type password \
--public-ip-address-dns-name myvm-dnsname-xx \
--os-disk-name myosdisk-02

3)DNS error
az vm create \
--name myvm-03 \
--resource-group myresourcegroup \
--image postgres-pro:postgres-pro-standard:hrly:9.6.2 \
--location northeurope \
--size Standard_DS1 \
--admin-password <azureuserpassword> \
--admin-username azureuser \
--authentication-type password \
--public-ip-address-dns-name myvm-dnsname-xx \
--os-disk-name myosdisk-xx

4)osDisk.name error
az vm create \
--name myvm-xx \
--resource-group myresourcegroup \
--image postgres-pro:postgres-pro-standard:hrly:9.6.2 \
--location northeurope \
--size Standard_DS1 \
--admin-password <azureuserpassword> \
--admin-username azureuser \
--authentication-type password \
--public-ip-address-dns-name myvm-dnsname-xx \
--os-disk-name myosdisk-04

5)no error, no new VM is created
az vm create \
--name myvm-xx \
--resource-group myresourcegroup \
--image postgres-pro:postgres-pro-standard:hrly:9.6.2 \
--location northeurope \
--size Standard_DS1 \
--admin-password <azureuserpassword> \
--admin-username azureuser \
--authentication-type password \
--public-ip-address-dns-name myvm-dnsname-05 \
--os-disk-name myosdisk-xx

**Comment by alexeyshishkin01** [comment] 2017-06-01 14:44
one more details for test 3) and object 'myvm-03NSG' is created

**Comment by tjprescott** [comment] 2017-06-01 16:37
For test 0 and 1, the behavior you observe is exactly what is intended by the service. You don't get the failure described in #3563 because you are attaching an OS disk.

For test 5, again, a new VM would *not* be created.  As a user, I'd expect it to update the DNS name, but knowing the implementation of VM create, I suspect it doesn't. Is this correct?

**Comment by tjprescott** [comment] 2017-06-01 18:45
For test 3, this is an unfortunate side effect of ARM templates--an NSG gets created as it is a prerequisite for creating the VM--but then the VM creation fails, leaving behind the orphan resources.

**Comment by tjprescott** [comment] 2017-06-01 18:54
I ran a simple test for issue 5, running the same VM create command but just changing the public IP DNS name. It did change the FQDNS for the VM.

**Comment by alexeyshishkin01** [comment] 2017-06-02 07:24
thanks for the replies!
0) is not actually a test - it's a starting point
1) let me not agree with you - I get command output about VM - it's the same as I get in 0), but not having info about 0) I get the impression I have new VM created which is not true - I'd like to have a warning message like 'VM with the same name or with the same os-disk name or with the same FQDN already exists'
3) NSG creation is definitely a bug, is it possible to fix it?
5) FQDN for VM is not changed, but its output is the same as for successful VM creation - this is wrong, I'd suggest to change it somehow
many thanks!

**Comment by tjprescott** [comment] 2017-06-02 16:15
Hi @alexeyshishkin01, in the case of 1, this is by design across Azure. One of the main reasons for this is because if you ran a script to set up your infrastructure, and that script failed for some reason (intermittent service issue or something), you want to be able to re-run that script and not have it fail because your VM already exists, nor would you want it to create another VM (which it couldn't anyways because the ID would be the same). 

As far as issuing a warning, there is no way for us to do this without making additional REST calls against the user's quota to see if the VM already exists. As a CLI design principle, we purposely avoid this. However, I've opened an issue for this specifically (#3593) so we can gather more feedback on this. Like anything, if enough people want it... :smile:

That the NSG is left over after a failed template deployment is actually by-design. However, expecting transactional behavior is not unreasonable (and not impossible) so I've created issue #3595 to gather additional feedback and track this potential feature work.

Regarding the FQDN--I ran it twice with different values for --public-ip-address-dns-name and it did in fact update the FQDN. However, your issue did alert me that some of the template based creates make not be fully goal-seeking.  I created a separate issue to track that  (#3592).

I'm going to close this issue since the potentially actionable feature work items have been moved to new issues, but feel free to continue the discussion here (or in the other threads) as you feel appropriate. :grin:

**Closed by tjprescott** 2017-06-02 16:15 UTC
Labels: Compute, Question

**Comment by alexeyshishkin01** [comment] 2017-06-06 09:51
ok, thanks

**Comment by HughDevlin** [comment] 2020-01-31 20:33
An ARM template for a virtual machine with a public ip address with the domainNameLabel parameter, is not idempotent.

To duplicate, 

1. create a simple template to create a simple virtual machine with a public IP with a domainNameLabel parameter as a prefix to the fully qualified domain name.
2. Deploy the template.
3. Deploy the template again. 2nd & successive deployments fail with the DnsRecordInUse error code.

A virtual machine with a public IP is a very common pattern.

The ["Azure Resource Manager templates overview"](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/overview) page under the subheading "Why choose Resource Manager templates?" states that among the advantages of ARM templates are the "Declarative syntax" and:

> "Repeatable results: Repeatedly deploy your infrastructure throughout the development lifecycle and have confidence your resources are deployed in a consistent manner. Templates are **idempotent**, which means you can deploy the same template many times and get the same resource types in the same state."

This bug defeats these advantages. The template is not idempotent. Recreating the resources requires scripting a procedural step to destroy an earlier resource first.

The above response from Microsoft, an internal "design principle" that any solution may not include additional underlying CLI or API calls, does not overrule Microsoft's commitment to customer-facing key features: the declarative nature and idempotency of ARM templates.

Please re-open this issue.
