### ISSUE TITLE
Inconsistency between the portal and the command

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-cli#6731] opened 2018-07-06 09:45 UTC
Here is the command, which appears to be working. At least it creates tables in the storage

```bash
az vm extension set --publisher Microsoft.Azure.Diagnostics --name LinuxDiagnostic --version 3.0 --resource-group tst --vm-name tst-dev-master-0 --protected-settings '{"storageAccountName": "stsstr", "storageAccountSasToken": "some SAS"}' --settings monitoring-config.json
```

However, "basic metrics" checkbox on the portal is not set. Which creates a lot of confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebbeb5f-6ab6-3fb3-c969-5d935e60f251
* Version Independent ID: 9d4169c9-f5b5-512a-8061-2234d6dec1eb
* Content: [az vm extension](https://docs.microsoft.com/en-us/cli/azure/vm/extension?view=azure-cli-latest#az-vm-extension-set)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment] 2018-10-19 01:35
Hello @eosfor.

I tested the command and it seems the CLI properly sets the extension resource on the VM. The portal shows that the extension was properly set / provisioned.  The CLI itself ultimately makes calls to the appropriate services to provision or update resources.

If the issue is that the extension was not properly set, let us know. If the issue is a portal UI issue, you can raise this with the [azure portal team](https://feedback.azure.com/forums/34192--general-feedback).

Also in the future you can consider using [`az vm diagnostics`](https://docs.microsoft.com/en-us/cli/azure/vm/diagnostics?view=azure-cli-latest) to configure diagnostics for your VM. it is a wrapper around the extension set command. 

Closing this issue. Please let me know if you have any other questions.

**Closed by adewaleo** 2018-10-19 01:35 UTC
Labels: Compute-cli, Question
