### ISSUE TITLE
Random docker container failures

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli#10026] opened 2019-07-24 05:19 UTC
Just creating this issue to track the problem.
The docker test failed in following PR:

https://github.com/Azure/azure-cli/pull/10023

========================== Starting Command Output ===========================
in/bash --noprofile --norc /home/vsts/work/_temp/907e6f1b-8e7c-44c7-8806-43d2d4f1983f.sh
== Test docker image ==

CLI_VERSION=`cat $SYSTEM_ARTIFACTSDIRECTORY/metadata/version`
cat $SYSTEM_ARTIFACTSDIRECTORY/metadata/version
++ cat /home/vsts/work/1/a/metadata/version
+ CLI_VERSION=2.0.69
IMAGE_NAME=clibuild$BUILD_BUILDNUMBER:latest
+ IMAGE_NAME=clibuild20190723.34:latest
TAR_FILE=$SYSTEM_ARTIFACTSDIRECTORY/docker/docker-azure-cli-$CLI_VERSION.tar
+ TAR_FILE=/home/vsts/work/1/a/docker/docker-azure-cli-2.0.69.tar

echo "== Test docker image =="
+ echo '== Test docker image =='

docker load < $TAR_FILE
+ docker load
Loaded image: clibuild20190723.34:latest
docker run $IMAGE_NAME /bin/bash -c "time az self-test && time az --version && sleep 5"
+ docker run clibuild20190723.34:latest /bin/bash -c 'time az self-test && time az --version && sleep 5'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/__main__.py", line 10, in <module>
    from knack.completion import ARGCOMPLETE_ENV_NAME
ModuleNotFoundError: No module named 'knack'

https://dev.azure.com/azure-sdk/public/_build/results?buildId=73039&view=logs&j=ae655c34-2740-5ddc-d560-639cf64e2aae&t=248e5207-5b8c-5f2d-d635-058f6cf8ac65&l=43

**Comment by zikalino** [comment] 2019-07-24 05:32
compared docker image build log with correct build log. In case of this build, we run into connection timeouts:

 [0m[91m  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f27e7806668>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/isodate/
 [0m  Downloading https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl (45kB)
 Collecting Jinja2==2.10.1 (from -r ./src/azure-cli/requirements.py3.Linux.txt (line 94))
 [91m  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f27e78d2f28>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/jinja2/
 [0m[91m  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f27e77c0860>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/jinja2/
 [0m[91m  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f27e75b2d30>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/jinja2/
 [0m[91m  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f27e78307f0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/jinja2/
 [0m[91m  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f27e7830f98>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/jinja2/
 [0m[91m  Could not find a version that satisfies the requirement Jinja2==2.10.1 (from -r ./src/azure-cli/requirements.py3.Linux.txt (line 94)) (from versions: )
 [0m[91mNo matching distribution found for Jinja2==2.10.1 (from -r ./src/azure-cli/requirements.py3.Linux.txt (line 94))
 [0m[91mYou are using pip version 9.0.3, however version 19.2.1 is available.
 You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by zikalino** [comment] 2019-07-24 05:57
we should investigate why **pip** doesn't fail properly.
when I run **pip install something** I simply get an error:

```
Collecting something
  ERROR: Could not find a version that satisfies the requirement something (from versions: none)
ERROR: No matching distribution found for something
```

**Comment by yonzhan** [comment] 2020-06-16 07:06
@fengzhou-msft please take a look

**Comment by yungezz** [comment] 2020-12-07 06:54
Test against latest docker build, the issue is not there any more, CI is stable for months. close the issue

**Closed by yungezz** 2020-12-07 06:54 UTC
Labels: Installation, OKR3.4 Candidate
