### ISSUE TITLE
"az aks enable-addons" breaks Azure-cli's idempotency = 1 assertion

### ISSUE THREAD

**Issue by Penberthy** [Azure/azure-cli#8248] opened 2019-01-15 18:46 UTC
**Describe the bug**
When you run  "az aks enable-addons" multiple times it works fine the first time but fails every time after that.

**To Reproduce**
Run  "az aks enable-addons" multiple times with the same arguments.
After the first success you get the following error on each successive execution.

> The monitoring addon is already enabled for this managed cluster.
> To change monitoring configuration, run "az aks disable-addons -a monitoring"before enabling it again.

**Expected behavior**
Like all other Azure CLI commands it should return the same results if you run the same command multiple times

**Environment summary**
azure-cli (2.0.50)
windows 10 
CMD.exe

**Comment by palma21** [comment] 2019-12-17 00:06
ARM is idempotent but CLI is not, so it will display a error to the user for information.

**Comment by jluk** [comment] 2019-12-17 00:06
Closing as by design

**Closed by jluk** 2019-12-17 00:06 UTC
Labels: AKS, Question, Service Attention
