### ISSUE TITLE
az login not working

### ISSUE THREAD

**Issue by kendrickchibueze** [Azure/azure-cli#21260] opened 2022-02-11 19:29 UTC
PS C:\Windows\system32> # Login to Azure using Powershell and az
$adminUPN="MyEmailAddress@domain.com"

$userCredential = Get-Credential -UserName $adminUPN -Message "Type the password."

connect-msolservice -Credential $userCredential

connect-azaccount

az login 

connect-msolservice : The term 'connect-msolservice' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:6 char:1
+ connect-msolservice -Credential $userCredential
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (connect-msolservice:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
connect-azaccount : The term 'connect-azaccount' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:8 char:1
+ connect-azaccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (connect-azaccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
az : WARNING: The default web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. 
Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code 
flow with `az login --use-device-code`.
At line:10 char:1
+ az login
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: The de...e-device-code`.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 9. The current time MUST be before the time represented by the exp Claim. Current epoch = 1644639970.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1644607297,
  "nbf": 1644607297,
  "exp": 1644611197,
  "aio": "AYQAe/8TAAAABySGq6kMIXQVXT2aV+eZYXsUGc7kIRIGAXM7hAPSuRJF2438OnSG9lxP/jZC1gwaKtUWp0fAzSMqEfSIEqXyaSXArtbNv1JQ7UdaWpZotc5yNTS
Y8Ek/MyULNNXXwjjeKZikXngfbWkB5LUw19EZFQcwDEMnF8RuNFqOisG+lYs=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "6a2f1a24f0a6e39cf9c6e29fae4e2c3ef0e63e9903404a9e5624f62aae3edde7",
  "preferred_username": "chibuezeken@outlook.com",
  "rh": "0.AU8AMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAEI.",
  "sub": "RzNysx6kswE2T1S2HXVCvD2k3KZQpeHIrcaoQSxCCeU",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "CALgIDwhjESs5xpmNuQuAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in 
_run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in 
handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in 
login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 171, in 
login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in 
obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in 
_obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in 
obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in 
obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in 
obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in 
_obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 9. The current time MUST be before the time represented by the exp Claim. Current epoch = 1644639970.  The id_token 
was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1644607297,
  "nbf": 1644607297,
  "exp": 1644611197,
  "aio": "AYQAe/8TAAAABySGq6kMIXQVXT2aV+eZYXsUGc7kIRIGAXM7hAPSuRJF2438OnSG9lxP/jZC1gwaKtUWp0fAzSMqEfSIEqXyaSXArtbNv1JQ7UdaWpZotc5yNTS
Y8Ek/MyULNNXXwjjeKZikXngfbWkB5LUw19EZFQcwDEMnF8RuNFqOisG+lYs=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "6a2f1a24f0a6e39cf9c6e29fae4e2c3ef0e63e9903404a9e5624f62aae3edde7",
  "preferred_username": "chibuezeken@outlook.com",
  "rh": "0.AU8AMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAEI.",
  "sub": "RzNysx6kswE2T1S2HXVCvD2k3KZQpeHIrcaoQSxCCeU",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "CALgIDwhjESs5xpmNuQuAA",
  "ver": "2.0"
}
To open an issue, please run: 'az feedback'

PS C:\Windows\system32> # Login to Azure using Powershell and az
$adminUPN="chibuezeken@outlook.com"

$userCredential = Get-Credential -UserName $adminUPN -Message "chibueze2245"

connect-msolservice -Credential $userCredential

connect-azaccount

az login 

connect-msolservice : The term 'connect-msolservice' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:6 char:1
+ connect-msolservice -Credential $userCredential
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (connect-msolservice:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
connect-azaccount : The term 'connect-azaccount' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:8 char:1
+ connect-azaccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (connect-azaccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
az : WARNING: The default web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. 
Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code 
flow with `az login --use-device-code`.
At line:10 char:1
+ az login
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: The de...e-device-code`.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 9. The current time MUST be before the time represented by the exp Claim. Current epoch = 1644640012.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1644607339,
  "nbf": 1644607339,
  "exp": 1644611239,
  "aio": "AYQAe/8TAAAAXxxvn6DrU9RWHJigp8yG/mVmrXis7UJipR4w3s3QHohp9qFyQYu3Mto3TBT0++P1K3qtkHQJmnmn8rjMH9hCvlfbqL7eqX6qxwEfENL3wXMUcls
y5GCa6VqFGIglBvWrVz7Wjx2a87JvVzIOg1k9Np3rK8zZeXMJ9b8KxPphDIs=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "34bcacc25a6bdf78e2e90bd0a729122120699da32d629cae312cb8095d3597d9",
  "preferred_username": "chibuezeken@outlook.com",
  "rh": "0.AU8AMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAEI.",
  "sub": "RzNysx6kswE2T1S2HXVCvD2k3KZQpeHIrcaoQSxCCeU",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "eF9SVdhBQUOUV9tZYTctAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in 
_run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in 
handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in 
login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 171, in 
login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in 
obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in 
_obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in 
obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in 
obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in 
obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in 
_obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 9. The current time MUST be before the time represented by the exp Claim. Current epoch = 1644640012.  The id_token 
was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1644607339,
  "nbf": 1644607339,
  "exp": 1644611239,
  "aio": "AYQAe/8TAAAAXxxvn6DrU9RWHJigp8yG/mVmrXis7UJipR4w3s3QHohp9qFyQYu3Mto3TBT0++P1K3qtkHQJmnmn8rjMH9hCvlfbqL7eqX6qxwEfENL3wXMUcls
y5GCa6VqFGIglBvWrVz7Wjx2a87JvVzIOg1k9Np3rK8zZeXMJ9b8KxPphDIs=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "34bcacc25a6bdf78e2e90bd0a729122120699da32d629cae312cb8095d3597d9",
  "preferred_username": "chibuezeken@outlook.com",
  "rh": "0.AU8AMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAEI.",
  "sub": "RzNysx6kswE2T1S2HXVCvD2k3KZQpeHIrcaoQSxCCeU",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "eF9SVdhBQUOUV9tZYTctAA",
  "ver": "2.0"
}
To open an issue, please run: 'az feedback'

PS C:\Windows\system32>

**Comment by kendrickchibueze** [comment] 2022-02-12 02:19
az login is not working. I am receiving an error although l have installed Azure Cli in windows

**Comment by jiasli** [comment] 2022-02-14 03:38
Duplicate of #20158

**Closed by jiasli** 2022-02-14 03:38 UTC
Labels: Account, customer-reported
