### ISSUE TITLE
Permission Denied on PKG-INFO file of azure_cosmos package

### ISSUE THREAD

**Issue by ericstephens** [Azure/azure-cli#13691] opened 2020-05-26 22:00 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Get a permission denied error on /usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/PKG-INFO

I manually resolved it and then when I invoke a command I get a series of warning messages having to do with conditional statements in Python 3.8.x (installed with azure-cli)

**To Reproduce**

Occurs on macOS 10.15.4

su admin 
brew install azure-cli
az login

**Expected behavior**

No Permission Denied error
No Python 3.8 warnings

**Environment summary**

azure-cli 2.6.0
macOS 10.15.4
zsh

**Additional context**

**Comment by yonzhan** [comment] 2020-05-26 23:15
@fengzhou-msft please take a look

**Comment by nrobert** [comment] 2020-05-29 20:17
Same problem on my side since updated Python to 3.8 and az-cli, with brew

**Comment by ericstephens** [comment] 2020-05-29 20:46
When I installed the cli using the native Linux method (no package management) it works just fine. No errors or warnings

**Comment by fengzhou-msft** [comment] 2020-06-29 03:47
@ericstephens is there some reason that you need to run `su admin` before `brew install azure-cli`?

**Comment by nrobert** [comment] 2020-06-29 06:27
@fengzhou-msft if it is like for me, it is due to non-admin rights on the account initially running the terminal. So brew will not execute correctly

**Comment by PeterUpfold** [comment] 2020-07-21 09:16
This also occurred for me on azure-cli 2.9.1 on macOS 10.15.6 installed with Homebrew 2.4.8.

The installation was performed using a different user account (with administrator privileges) than the user who is running the `az` command. (Although it's not technically about administrator rights _per se_, it's about the files below being owned by the installation user and unreadable by anyone else.)

Other files in `/usr/local/Cellar/azure-cli/2.9.1/libexec/lib/python3.8/site-packages/` have the permissions set to `-rw-r--r--` (0644), but the following files are set to `-rw-------` (600):

    % cd /usr/local/Cellar/azure-cli/2.9.1/libexec/lib/python3.8/site-packages    
    % find -perm 600
    ./azure_cosmos-3.1.0-py3.8.egg-info/PKG-INFO
    ./azure_cosmos-3.1.0-py3.8.egg-info/SOURCES.txt
    ./azure_cosmos-3.1.0-py3.8.egg-info/requires.txt
    ./azure_cosmos-3.1.0-py3.8.egg-info/top_level.txt
    ./azure_cosmos-3.1.0-py3.8.egg-info/dependency_links.txt

One or more of these files are attempted to be read upon running `az`, so therefore no user other than the installation user can execute `az` unless these permissions are manually changed.

**Comment by nrobert** [comment] 2020-07-21 09:36
@PeterUpfold  thanks for the clarification, that's exactly what I am facing.
On my side, the error starts on the 1st file you mentioned:

> PermissionError: [Errno 13] Permission denied: '/usr/local/Cellar/azure-cli/2.9.1/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/PKG-INFO'

Doing the following fixed my `az` commands which were failing:

```
cd /usr/local/Cellar/azure-cli/2.9.1/libexec/lib/python3.8/site-packages
find . -type f -perm 600 -exec chmod 644 {} \;
```

**Comment by ericstephens** [comment] 2020-07-21 09:43
Yes - my default login does not have admin rights.

**Comment by fengzhou-msft** [comment] 2020-08-10 02:47
@arrownj, I checked the file permission of `azure_cosmos` 3.2.0 tarball, these files now have the read permission for all users. Please help verify when you're testing the new homebrew package.

**Comment by nrobert** [comment] 2020-08-12 09:07
@fengzhou-msft , can you confirm once the package is released?

I just upgraded my azure-cli package from 2.10.0 to 2.10.1 and still got the issue:

![image](https://user-images.githubusercontent.com/6305666/89997080-f2c84f00-dc8b-11ea-9d8d-65b4a0551c9b.png)

**Comment by fengzhou-msft** [comment] 2020-08-16 10:52
@nrobert The `azure-cosmos` package is upgraded in this [PR](https://github.com/Azure/azure-cli/pull/14372/files#diff-a2ee9569f39205b90420fb434778cf6c) and is targeted to be released on August 25 with `2.11.0`.

**Comment by nrobert** [comment] 2020-08-25 12:39
\o/ 
I can confirm that the error seems to be fixed in `2.11.0` on my machine. Thanks!

**Comment by PeterUpfold** [comment] 2020-08-28 14:23
This looks like it is fixed for me too.

    % az --version                                                                           
    azure-cli                         2.11.0

**Comment by rnagpal** [comment] 2020-09-07 03:37
@ericstephens : Please feel free to reactivate this if you still repro this. Closing this issues based on couple of confirmations.

**Closed by rnagpal** 2020-09-07 03:37 UTC
Labels: Cosmos, OKR3.2 Candidate, Packaging, Service Attention, question
