### ISSUE TITLE
functions:Cannot deploy zip package using CLI az functionapp deployment source config-zip

### ISSUE THREAD

**Issue by martinjanitor** [Azure/azure-cli#17533] opened 2021-03-31 22:36 UTC
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
HTTPSConnectionPool(host='func-d-customerconnectivitysync.scm.azurewebsites.net', port=443): Read timed out. (read timeout=3)
Traceback (most recent call last):
Lib\site-packages\urllib3\connectionpool.py, ln 426, in _make_request
<string>, ln 3, in raise_from
Lib\site-packages\urllib3\connectionpool.py, ln 421, in _make_request
http\client.py, ln 1331, in getresponse
http\client.py, ln 297, in begin
http\client.py, ln 258, in _read_status
socket.py, ln 586, in readinto
site-packages\urllib3\contrib\pyopenssl.py, ln 326, in recv_into
socket.timeout: The read operation timed out

...

Lib\site-packages\requests\sessions.py, ln 646, in send
Lib\site-packages\requests\adapters.py, ln 529, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='func-d-customerconnectivitysync.scm.azurewebsites.net', port=443): Read timed out. (read timeout=3)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip --subscription {} --resource-group {} --src {} --name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0

Extensions:
application-insights 0.1.3
interactive 0.4.4

```

**Comment by yonzhan** [comment] 2021-04-01 00:13
route to service team

**Comment by Kotasudhakarreddy** [comment] 2021-04-05 03:12
Will take a look in to in to this.

**Comment by panchagnula** [comment] 2021-04-05 21:18
@Kotasudhakarreddy is this happening for function app only or for webapp as well? if this is functions specific please  route to the functions team. Thanks!

**Comment by Kotasudhakarreddy** [comment] 2021-04-06 07:18
@panchagnula yes the issue is with functions alone.

**Comment by Kotasudhakarreddy** [comment] 2021-04-06 07:20
@v-anvari - assigning this to you as it is related to the functions.

**Comment by fabiocav** [comment] 2021-04-12 17:21
@apawast can we look at this issue in triage? Thanks!

**Comment by apawast** [comment] 2021-04-22 17:41
@martinjanitor has this issue persisted for you?

**Comment by panchagnula** [comment] 2022-04-01 01:19
Please open a new issue if this still happens, with latest CLI version.

**Closed by panchagnula** 2022-04-01 01:19 UTC
Labels: Service Attention, Functions
