### ISSUE TITLE
`az vm secret format` returns nothing

### ISSUE THREAD

**Issue by akx** [Azure/azure-cli#7260] opened 2018-09-10 13:28 UTC
**Describe the bug**

`az vm secret format` returns nothing. With `-o json`, it doesn't seem to return anything that's usable by VMs.

**To Reproduce**

Create a secret in a vault:

```shell
$ az keyvault secret set --vault-name examplevault --name testfoo --value this-is-a-value
Value
---------------
this-is-a-value
$ az keyvault secret list-versions --vault-name examplevault -n testfoo -o json
[
  {
    "attributes": {
      "created": "2018-09-10T13:21:15+00:00",
      "enabled": true,
      "expires": null,
      "notBefore": null,
      "recoveryLevel": "Purgeable",
      "updated": "2018-09-10T13:21:15+00:00"
    },
    "contentType": null,
    "id": "https://examplevault.vault.azure.net/secrets/testfoo/deadbeefcafedeadbeefcafedeadbeef",
    "managed": null,
    "tags": {
      "file-encoding": "utf-8"
    }
  }
]
```

Attempt to format it for VM use:

```shell
$ az vm secret format --secret https://examplevault.vault.azure.net/secrets/testfoo/deadbeefcafedeadbeefcafedeadbeef

$ az vm secret format --secret https://examplevault.vault.azure.net/secrets/testfoo/deadbeefcafedeadbeefcafedeadbeef -o json
[
  {
    "sourceVault": {
      "id": "/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/resourcegroupfoo/providers/Microsoft.KeyVault/vaults/examplevault"
    },
    "vaultCertificates": [
      {
        "certificateUrl": "https://examplevault.vault.azure.net/secrets/testfoo/deadbeefcafedeadbeefcafedeadbeef"
      }
    ]
  }
]
$
```

**Expected behavior**

`az vm secret format`, as the usage is described in e.g. https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/linux/tutorial-automate-vm-deployment.md , should return some value that can be added to `az vm create --secrets`.

**Environment summary**

macOS 10.13.6, azure-cli (2.0.45) installed via Brew, on Python 3.7.

**Comment by akx** [comment] 2018-09-14 11:07
Apparently the output generated by `-o json` can be piped into a file, then used with `--secrets @...`, i.e.

```
$ az vm secret format --secret https://examplevault.vault.azure.net/secrets/testfoo/deadbeefcafedeadbeefcafedeadbeef -o json > secret-payload.json
$ az vm create --other-parameters-here --secrets @secret-payload.json
```

However it's important to note (as I found out the hard way) that *secrets other than certificates are __not__ supported at present by the VM creation process*.
That is, you can't use this method to inject an arbitrary secret value into your VM.

The bug still stands though; `az vm secret format` should output something usable without `-o json`.

**Comment by adewaleo** [comment] 2018-10-19 02:28
Hello @akx 

What is your default output format? The default CLI output format is json. I imagine your default output format is `table`.

Unfortunately, output formats other than json/jsonc can lose information because there isn't always a clear way to format certain types of data. One easy problem is how to clearly output nested json information in a tsv or table format.

Here is my output when I run the same command.

```
$ az vm secret format --secret $my_secret --keyvault tosinkeyvault
[
  {
    "sourceVault": {
      "id": "/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/ovaTestGroup/providers/Microsoft.KeyVault/vaults/tosinkeyvault"
    },
    "vaultCertificates": [
      {
        "certificateUrl": "https://tosinkeyvault.vault.azure.net/secrets/password/e5724bf40e7b432b8a793e3f6ead89f3"
      }
    ]
  }
]

$ az vm secret format --secret $my_secret --keyvault tosinkeyvault -o table

$ az vm secret format --secret $my_secret --keyvault tosinkeyvault -o tsv
	1
```
As you can see, no information is outputted with `-o table`. If your default output isn't -o table or -o tsv, let me know, otherwise this is the expected behavior.

Concerning using arbitrary secrets during VM creation, this is a service side issue.

I will be closing this issue, but please let me know if you have any more questions.

**Closed by adewaleo** 2018-10-19 02:28 UTC
Labels: Compute-cli, Output

**Comment by akx** [comment] 2018-10-23 11:06
It would probably be user friendly to document that this command always requires JSON output, or maybe even force it to always output as JSON, if all other formats are utterly useless? :)

**Comment by adewaleo** [comment] 2018-10-23 21:17
Hello @akx. Thanks for the feedback. However, this issue of certain output formats omitting nested data applies to other commands. You might find our [docs](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest) on output formats helpful, they mention how certain output formats omit nested data. 

The query option can be very helpful for extracting desired fields from / transforming data in the result.
Here is a helpful [doc](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest) that explains how `--query` works.

For example, so to get at the sourceVault id in the command above:
``` 
ID=$(az vm secret format --secret $my_secret --keyvault tosinkeyvault --query "[].sourceVault.id" -o tsv)
```
This will give you the sourceVaultID without the quotes.

**Comment by akx** [comment] 2018-10-24 07:41
I'm aware of various output formats being available, thank you :)

However, I would say `az vm secret format` is a special case, as it is a command primarily (or rather, solely) meant for retrieving the "blob" of data that is to be used with `az vm create`, as I discussed in [this comment](https://github.com/Azure/azure-cli/issues/7260#issuecomment-421324762) a month ago, and the data is absolutely not usable for that command in any other format than `json`.

**Comment by adewaleo** [comment] 2018-10-24 18:42
@akx, no worries. I was just referring you to the doc because in the description of the tsv and output formats, it is mentioned that these formats omit nested data.

I created an issue to warn users when -o table and -o tsv formats are used.
