### ISSUE TITLE
aks-preview changes az get-credentials

### ISSUE THREAD

**Issue by paulgmiller** [Azure/azure-cli#9736] opened 2019-06-19 20:41 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version azure-cli                       2.0.63
acs                               2.3.22 *
**Describe the bug**
adding the aks-preview extension changes the output file argument for get-credentials

**To Reproduce**
az extension remove --name aks-preview
az aks get-credentials --help
...
 --file -f                      : Kubernetes configuration file to update. Use "-" to print YAML
                                     to stdout instead.  Default: C:\Users\pmiller\.kube\config.
...
az extension add --name aks-preview
az aks get-credentials --help
--path                         : Default: C:\Users\pmiller\.kube\config.

**Expected behavior**
I think this isn't intended and it should just stay -f/--file

**Environment summary**
Windows 10 and ubuntu 16. 

**Additional context**

**Comment by bergerx** [comment] 2019-07-05 10:30
We are also hit by this, we first thought the change was introduced in new azure-cli versions, then realised that half of the team has `--file -f` and other half has `--path` instead for the `az aks get-credentials` method on the same azure-cli version. Turned out that if the `aks-preview` extension is added, the flags are changing in an incompatible way. This is kind of breaking our automations as well since some clusters we have VMSS, but old ones doesn't have it.

We can solve the problem by adding a condition like `az aks get-credentials --help | grep "--path"` before calling it in our automation but this seems more like a bug in azure-cli, instead of putting workaround i prefer the issue to be addressed in upstream.

**Comment by brendandburns** [comment] 2019-08-03 02:09
I can't reproduce this any more. I think this can be closed.

**Comment by paulgmiller** [comment] 2019-08-03 23:07
Agree thought I saw it just this week but now gone on three different machines

**Closed** 2019-08-03 23:07 UTC
Labels: AKS, Needs Triage, Service Attention
