### ISSUE TITLE
unable to login az cli

### ISSUE THREAD

**Issue by muralikrishnarokkam** [Azure/azure-cli#23547] opened 2022-08-16 13:48 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0
```

**Comment by ramfattah** [comment] 2022-08-16 14:46
Possibly related to https://github.com/Azure/azure-cli/issues/23497 ?

**Comment by ramfattah** [comment] 2022-08-16 14:49
@muralikrishnarokkam 

I was able to log in using the `@microsoft` email.
Are you facing this issue if using a specific email account or in general `az login` does not work? 

Also, are you using proxy by any chance?

**Comment by muralikrishnarokkam** [comment] 2022-08-16 15:17
I am using my work email address to login

**Comment by yonzhan** [comment] 2022-08-16 22:39
Duplicate of https://github.com/Azure/azure-cli/issues/20231

**Closed by yonzhan** 2022-08-16 22:39 UTC
Labels: Account, customer-reported, Auto-Assign
