### ISSUE TITLE
az hana database restoration failed

### ISSUE THREAD

**Issue by sakibmas** [Azure/azure-cli#26084] opened 2023-04-08 14:26 UTC
## Describe the bug

**Command Name**
`az backup restore restore-azurewl`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup restore restore-azurewl -g {} -v {} --recovery-config {} --verbose`

## Environment Summary
```
Windows-10-10.0.20348-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.47.0

Extensions:
alertsmanagement 0.2.2
billing-benefits 0.1.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment] 2023-04-08 14:26
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment] 2023-04-09 01:42
@sakibmas Closing this issue as a duplicate of [26083](https://github.com/Azure/azure-cli/issues/26083).

**Closed by SaurabhSharma-MSFT** 2023-04-09 01:42 UTC
Labels: question, Recovery Services Backup, customer-reported, Backup, CXP Attention, Auto-Assign, Azure CLI Team
