### ISSUE TITLE
Unable to create a VM with PremiumV2_LRS disks 

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#23202] opened 2022-07-14 03:32 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az vm create 

**Describe the bug**
I am getting the following error while creating a VM with Premium v2 with the latest CLI SDK. Can you please look into the issue? 

raman@ramanlaptop:/mnt/c/Users/ramankum$ az vm create -n $vmName -g $resourceGroupName \
> --image $vmImage \
> --zone $zone \
> --authentication-type password --admin-password $adminPassword --admin-username $adminUserName \
> --size $vmSize \
> --location $region \
> --attach-data-disks $diskName
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see [https://aka.ms/DeployOperations](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FDeployOperations&data=05%7C01%7CRaman.Kumar%40microsoft.com%7C6456a9c0990b4556214608da65483150%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637933657987829348%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mrI35Bs7CV%2BGRMOc33Qcv6mq9ED1wxBty5WlPkUy6Wo%3D&reserved=0) for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"Minimum api-version required for using PremiumV2 SKU is 2021-12-01.\",\r\n    \"target\": \"/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/PremiumV2Testing/providers/Microsoft.Compute/disks/myPremiumV2Disk1\"\r\n  }\r\n}"}]}}

**To Reproduce**
diskName="myPremiumV2Disk1"
resourceGroupName="PremiumV2Testing"
region="swedencentral"
vmName="myVMWithPVD1"
vmImage="Win2016Datacenter"
adminPassword=""
adminUserName=""
vmSize="Standard_D4s_v3"
zone="1"

az disk create -n $diskName -g $resourceGroupName \
--size-gb 100 \
--disk-iops-read-write 5000 \
--disk-mbps-read-write 150 \
--location $region \
--zone $zone \
--sku PremiumV2_LRS
az vm create -n $vmName -g $resourceGroupName \
--image $vmImage \
--zone $zone \
--authentication-type password --admin-password $adminPassword --admin-username $adminUserName \
--size $vmSize \
--location $region \
--attach-data-disks $diskName

**Expected behavior**
Should be able to create a VM with PremiumV2_LRS disks with the latest version of CLI

**Environment summary**
raman@ramanlaptop:/mnt/c/Users/ramankum$ az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Additional context**

**Comment by yonzhan** [comment] 2022-07-14 03:42
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment] 2022-07-14 06:50
@ramankumarlive CLI uses the api-version `2022-03-01`, which is higher than the minimum required api-version `2021-12-01`. Therefore, this may be the problem of ARM service or Compute RP service. 
Please contact the service team to investigate the root cause of this error message, thanks!

**Comment by jaylabell** [comment] 2022-07-21 19:42
@TravisCragg-MSFT  can you please look into this disk issue?

**Comment by TravisCragg-MSFT** [comment] 2022-08-04 22:05
Spoke with issue owner offline, closing as resolved. This is currently not possible and being worked on.

**Closed by TravisCragg-MSFT** 2022-08-04 22:05 UTC
Labels: Service Attention, Compute - Managed Disks, Auto-Assign
