### ISSUE TITLE
[docs] az vm extension set: misdocumented required args

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#752] opened 2016-08-25 18:47 UTC
Help message for `az vm extension set` is misleading about the required arguments.

```
➜  ~ az vm extension set -h

Command
    az vm extension set

Arguments
    --name -n         [Required]: The name of the extension.
    --publisher       [Required]: The name of extension publisher.
    --auto-upgrade-minor-version: Auto upgrade to the newer version if available.
    --ids                       : ID of resource.
    --protected-settings        : Protected settings or a file path with such contents.
    --resource-group -g         : Name of resource group.
    --settings                  : Public settings or a file path with such contents.
    --version                   : The version of extension.
    --vm-name                   : The name of the virtual machine.

Global Arguments
    --debug                     : Increase logging verbosity to show all debug logs.
    --help -h                   : Show this help message and exit.
    --output -o                 : Output format.  Allowed values: json, tsv, list, table, jsonc.
                                  Default: json.
    --query                     : JMESPath query string. See http://jmespath.org/ for more
                                  information and examples.
    --verbose                   : Increase logging verbosity. Use --debug for full debug logs.

Examples
    Add a new linux user
        az vm extension set -n VMAccessForLinux --publisher Microsoft.OSTCExtensions --version 1.4
        --vm-name myvm --resource-group yugangw --private-config '{"username":"user1",
        "ssh_key":"ssh_rsa ..."}'



➜  ~ az vm extension set -n CustomScript --publisher Microsoft.Azure.Extensions --auto-upgrade-minor-version
usage: az vm extension set [-h] [--output {json,tsv,list,table,jsonc}]
                           [--verbose] [--debug] [--query JMESPATH]
                           --publisher PUBLISHER
                           [--protected-settings PROTECTED_SETTINGS]
                           [--vm-name NAME] [--auto-upgrade-minor-version]
                           --name NAME [--settings SETTINGS]
                           [--version VERSION]
                           [--resource-group RESOURCE_GROUP_NAME]
                           [--ids RESOURCE_ID [RESOURCE_ID ...]]
az vm extension set: error: (--vm-name --resource-group | --ids) are required
```

**Comment by yugangw-msft** [comment] 2016-08-26 01:57
dupe of #656

**Closed by yugangw-msft** 2016-08-26 01:57 UTC
