### ISSUE TITLE
[Monitor] cannot create diagnostics-settings

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#6162] opened 2018-04-19 21:04 UTC
Installed via apt.

In my command below, `$group_name`, `$diagnostics_name` and `$eventhub_name` are all short (single-segment) names. `$eh_authzrule_id` and `$storage_account_id` are full resource paths (aka ids). I tried alternate combinations of short and long names too and still get the same error, I think it's something intrinsic to building the request payload.

Here's the command and trimmed debug output:

```bash
az monitor diagnostic-settings create \
    --name $diagnostics_name \
    --event-hub $eventhub_name \
    --event-hub-rule $eh_authzrule_id \
    --resource $storage_account_id

Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x7fad87aa5620>]                 
Event: CommandInvoker.OnCommandTableLoaded []                                                                   
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fad878e90d0>]                       
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fad88a929d8>, <function CLIQuery.handle_query_parameter at 0x7fad88ab1510>, <function handler at 0x7fad87820598>]                    
usage: az monitor diagnostic-settings create [-h] [--verbose] [--debug]                                         
                                             [--output {json,jsonc,table,tsv}]                                  
                                             [--query JMESPATH] --name NAME                                     
                                             <snip>                     
az monitor diagnostic-settings create: error: 'Namespace' object has no attribute 'event_hub_name'  
```

related: https://github.com/Azure/azure-cli/issues/5698

**Comment by troydai** [comment] 2018-04-19 22:39
@tjprescott looks like a bug. Is it a regression?

**Comment by anoff** [comment] 2018-04-23 13:12
Same issue here trying to activate redis diagnostics -> eventhub

```text
azure-cli (2.0.31)
monitor (0.1.5)
```

Are there any known workarounds like switching to older CLI versions? (except powershell 😬)

**Comment by tjprescott** [comment] 2018-04-23 16:35
@troydai it's not technically a regression. A review of PR #5424 makes it clear that it never worked. The custom command signature and validator don't match, and this scenario was not covered by a test.

**Comment by troydai** [comment] 2018-04-25 16:12
I'll take a look today.

**Comment by anoff** [comment] 2018-04-25 17:52
Roll out as in release a new version or just bring it in the codebase? 👀

**Comment by troydai** [comment] 2018-04-25 18:26
In codebase. It will show up in the next release (check: https://github.com/Azure/azure-cli/milestone/38). If you want to use it right now, you can use the edge build (https://github.com/azure/azure-cli/#edge-builds).

**Comment by troydai** [comment] 2018-04-25 22:06
Fixed in https://github.com/Azure/azure-cli/pull/6216#event-1594817368.

**Closed by troydai** 2018-04-25 22:06 UTC
Labels: Monitor, bug
