### ISSUE TITLE
Parameters not accepted from command-line

### ISSUE THREAD

**Issue by deltadan** [Azure/azure-cli#3341] opened 2017-05-12 11:50 UTC
### Description
**Outline the issue here:**
When trying to use az group deployment create command if there are parameters that the user needs to provide text the cli errors.  When the deployment command is running the - user will be prompted for:  WebVMName, WebVMAdminUserName, WEbVMAdminPassword, WebPublicDNSName.  The parameters are accepted as they are being typed, but the following error occurs immediately:
 
C:\Users\DanPatrick>az group deployment create -g ARMLabsRG --template-file C:\OpsgilityTraining\azurelabdeploy-after-ex2.json
Please provide a value for 'WebVMName' (? for help): webvm
Please provide a value for 'WebVMAdminUserName' (? for help): demouser
Please provide a value for 'WebVMAdminPassword' (? for help):
Please provide a value for 'WebPublicIPDnsName' (? for help): webvm987234987
Deployment template validation failed: 'The value for the template parameter 'WebVMName' at line '1' and column '334' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.

Command used:
Create the RG (works fine)
az group create -n ARMLabsRG -l eastus

Submit deployment command (errors)
az group deployment create -g ARMLabsRG --template-file C:\path\azuredeploy.json

Here is the json file:
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "vmstorageType": {
            "type": "string",
            "defaultValue": "Standard_LRS",
            "allowedValues": [
                "Standard_LRS",
                "Standard_GRS",
                "Standard_RAGRS",
                "Premium_LRS"
            ]
        },
        "WebVMName": {
            "type": "string",
            "minLength": 1
        },
        "WebVMAdminUserName": {
            "type": "string",
            "minLength": 1
        },
        "WebVMAdminPassword": {
            "type": "securestring"
        },
        "WebVMUbuntuOSVersion": {
            "type": "string",
            "defaultValue": "14.04.2-LTS",
            "allowedValues": [
                "12.04.5-LTS",
                "14.04.2-LTS"
            ]
        },
        "WebPublicIPDnsName": {
            "type": "string",
            "minLength": 1
        }
    },
    "variables": {
        "OPSTrainingVNETPrefix": "10.0.0.0/16",
        "OPSTrainingVNETSubnet1Name": "FrontendNetwork",
        "OPSTrainingVNETSubnet1Prefix": "10.0.1.0/24",
        "OPSTrainingVNETSubnet2Name": "BackendNetwork",
        "OPSTrainingVNETSubnet2Prefix": "10.0.2.0/24",
        "vmstorageName": "[concat('vmstorage', uniqueString(resourceGroup().id))]",
        "WebVMImagePublisher": "Canonical",
        "WebVMImageOffer": "UbuntuServer",
        "WebVMOSDiskName": "WebVMOSDisk",
        "WebVMVmSize": "Standard_D1",
        "WebVMVnetID": "[resourceId('Microsoft.Network/virtualNetworks', 'OPSTrainingVNET')]",
        "WebVMSubnetRef": "[concat(variables('WebVMVnetID'), '/subnets/', variables('OPSTrainingVNETSubnet1Name'))]",
        "WebVMStorageAccountContainerName": "vhds",
        "WebVMNicName": "[concat(parameters('WebVMName'), 'NetworkInterface')]",
        "WebPublicIPName": "WebPublicIP"
    },
    "resources": [
        {
            "name": "OPSTrainingVNET",
            "type": "Microsoft.Network/virtualNetworks",
            "location": "[resourceGroup().location]",
            "apiVersion": "2015-06-15",
            "dependsOn": [ ],
            "tags": {
                "displayName": "OPSTrainingVNET"
            },
            "properties": {
                "addressSpace": {
                    "addressPrefixes": [
                        "[variables('OPSTrainingVNETPrefix')]"
                    ]
                },
                "subnets": [
                    {
                        "name": "[variables('OPSTrainingVNETSubnet1Name')]",
                        "properties": {
                            "addressPrefix": "[variables('OPSTrainingVNETSubnet1Prefix')]"
                        }
                    },
                    {
                        "name": "[variables('OPSTrainingVNETSubnet2Name')]",
                        "properties": {
                            "addressPrefix": "[variables('OPSTrainingVNETSubnet2Prefix')]"
                        }
                    }
                ]
            }
        },
        {
            "name": "[variables('vmstorageName')]",
            "type": "Microsoft.Storage/storageAccounts",
            "location": "[resourceGroup().location]",
            "apiVersion": "2015-06-15",
            "dependsOn": [ ],
            "tags": {
                "displayName": "vmstorage"
            },
            "properties": {
                "accountType": "[parameters('vmstorageType')]"
            }
        },
        {
            "name": "[variables('WebVMNicName')]",
            "type": "Microsoft.Network/networkInterfaces",
            "location": "[resourceGroup().location]",
            "apiVersion": "2015-06-15",
            "dependsOn": [
                "[concat('Microsoft.Network/virtualNetworks/', 'OPSTrainingVNET')]"
            ],
            "tags": {
                "displayName": "WebVMNic"
            },
            "properties": {
                "ipConfigurations": [
                    {
                        "name": "ipconfig1",
                        "properties": {
                            "privateIPAllocationMethod": "Dynamic",
                            "subnet": {
                                "id": "[variables('WebVMSubnetRef')]"
                            },
                            "publicIPAddress": {
                                "id": "[resourceId('Microsoft.Network/publicIPAddresses', variables('WebPublicIPName'))]"
                            }
                        }
                    }
                ]
            }
        },
        {
            "name": "[parameters('WebVMName')]",
            "type": "Microsoft.Compute/virtualMachines",
            "location": "[resourceGroup().location]",
            "apiVersion": "2015-06-15",
            "dependsOn": [
                "[concat('Microsoft.Storage/storageAccounts/', variables('vmstorageName'))]",
                "[concat('Microsoft.Network/networkInterfaces/', variables('WebVMNicName'))]"
            ],
            "tags": {
                "displayName": "WebVM"
            },
            "properties": {
                "hardwareProfile": {
                    "vmSize": "[variables('WebVMVmSize')]"
                },
                "osProfile": {
                    "computerName": "[parameters('WebVMName')]",
                    "adminUsername": "[parameters('WebVMAdminUsername')]",
                    "adminPassword": "[parameters('WebVMAdminPassword')]"
                },
                "storageProfile": {
                    "imageReference": {
                        "publisher": "[variables('WebVMImagePublisher')]",
                        "offer": "[variables('WebVMImageOffer')]",
                        "sku": "[parameters('WebVMUbuntuOSVersion')]",
                        "version": "latest"
                    },
                    "osDisk": {
                        "name": "WebVMOSDisk",
                        "vhd": {
                            "uri": "[concat('http://', variables('vmstorageName'), '.blob.core.windows.net/', variables('WebVMStorageAccountContainerName'), '/', variables('WebVMOSDiskName'), '.vhd')]"
                        },
                        "caching": "ReadWrite",
                        "createOption": "FromImage"
                    }
                },
                "networkProfile": {
                    "networkInterfaces": [
                        {
                            "id": "[resourceId('Microsoft.Network/networkInterfaces', variables('WebVMNicName'))]"
                        }
                    ]
                }
            }
        },
        {
            "name": "[variables('WebPublicIPName')]",
            "type": "Microsoft.Network/publicIPAddresses",
            "location": "[resourceGroup().location]",
            "apiVersion": "2015-06-15",
            "dependsOn": [ ],
            "tags": {
                "displayName": "WebPublicIP"
            },
            "properties": {
                "publicIPAllocationMethod": "Dynamic",
                "dnsSettings": {
                    "domainNameLabel": "[parameters('WebPublicIPDnsName')]"
                }
            }
        }
    ],
    "outputs": {
    }
}
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
This was atteptmeted on both Installed via MSI on windows and running latest docker container on a linuxbox.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
2.0.6
**OS Version:** What OS and version are you using?  
Answer here:
window
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Microsoft Windows [Version 10.0.15063]

**Comment by tjprescott** [comment] 2017-05-12 15:25
Sounds like this may be related to or a dupe of #3001.  @brendandburns does PR #3173 address this?

**Comment by brendandburns** [comment] 2017-05-16 23:29
Yes, sounds like this is a dupe of #3001, I'll get that PR to a mergeable state.

**Comment by deltadan** [comment] 2017-05-18 00:56
Thanks guys...

**Comment by brendandburns** [comment] 2017-05-25 22:08
Closing since #3173 is merged.

**Closed by brendandburns** 2017-05-25 22:08 UTC
Labels: bug, Resource Manager
