### ISSUE TITLE
Using the --ids flag in 'az vm run-command invoke' always runs a dummy script

### ISSUE THREAD

**Issue by apar-singhal** [Azure/azure-cli#23625] opened 2022-08-22 19:41 UTC
I need to start the docker desktop application through the command line. I am running the command:
`az vm run-command invoke --name <vm-name> --resource-group <resource-group-name> --subscription <subscription-id> --command-id RunPowerShellScript --scripts "Start-Process 'C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe'"`
but gives does not work due to "Access Denied".

I am able to run the exact command from the PowerShell from inside the VM and that works.

So I tried to run "az vm run-command" command as the same user I logged into the VM as follows:

`az vm run-command create --vm-name <vm-name> --resource-group <resource-group-name> --subscription <subscription-id> --script "Start-Process -FilePath 'C:\Program Files\Docker\Docker\Docker Desktop.exe'" --run-as-user <username> --run-as-password <password-in-plain-text>`

It gives me a resource ID which I use in the next command:
`az vm run-command invoke --name <vm-name> --resource-group <resource-group-name> --subscription <subscription-id> --command-id RunPowerShellScript --ids <resource-id-given-above>`
But this returns:
```
{
  "value": [
    {
      "code": "ComponentStatus/StdOut/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "This is a sample script with parameters  ",
      "time": null
    },
    {
      "code": "ComponentStatus/StdErr/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "",
      "time": null
    }
  ]
}
```

Using the --ids flag in az vm run-command invoke does not runs the actual script but a dummy script which is as below:
```
param(
  [string]$arg1,
  [string]$arg2
)
Write-Host This is a sample script with parameters $arg1 $arg2
```

I know this is what it runs as this gets stored inside the VM at the location:
`C:\Packages\Plugins\Microsoft.CPlat.Core.RunCommandWindows\1.1.11\Downloads`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04b196d-7d11-7213-f037-f12b85b19c52
* Version Independent ID: adc05d8e-b13b-134b-5f61-42aaf23666df
* Content: [az vm run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/run-command.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/run-command.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2022-08-22 23:08
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment] 2022-08-23 03:00
@apar-singhal Could you please send me the debug log (Add --debug parameter) by email? My email address is [Zhou.Xing@microsoft.com](mailto:Zhou.Xing@microsoft.com), thanks~

**Comment by zhoxing-ms** [comment] 2022-08-23 09:49
@apar-singhal In fact, I guess you should first get the `name`  from the return result of command `az vm run-command create`, and then pass it to the `--command-id` parameter of command `az vm run-command invoke`
Because the `--ids` parameter of the `az vm run-command invoke` command is used to pass in the VM resource ID, and if the `--command-id` parameter is passed in another new name without specifying the `--scripts` parameter, it will execute the default sample script.

**Comment by zhoxing-ms** [comment] 2022-08-24 06:35
Currently, there may be some problems with the service:

I can find a runCommand named `zhoxing-test` under VM `zhoxing-test`
```
Request URL: GET /subscriptions/{subscription}/resourceGroups/zhoxing-test/providers/Microsoft.Compute/virtualMachines/zhoxing-test/runCommands/zhoxing-test?api-version=2022-03-01 HTTP/1.1
{
  "name": "zhoxing-test",
  "id": "/subscriptions/{subscription}/resourceGroups/zhoxing-test/providers/Microsoft.Compute/virtualMachines/zhoxing-test/runCommands/zhoxing-test",
  "type": "Microsoft.Compute/virtualMachines/runCommands",
  "location": "eastus",
  "properties": {
    "source": {
      "script": "Write-Host Hello World!"
    },
    "timeoutInSeconds": 0,
    "provisioningState": "Succeeded",
    "asyncExecution": false
  }
}
```

However, when I execute it, an error `The entity was not found in this Azure location.` occurred
```
Request URL: POST https://management.azure.com/subscriptions/{subscription}/resourceGroups/zhoxing-test/providers/Microsoft.Compute/virtualMachines/zhoxing-test/runCommand?api-version=2022-03-01
Request Body:
{
	"commandId": "zhoxing-test",
	"parameters": []
}
Response:
{
  "error": {
    "code": "NotFound",
    "message": "The entity was not found in this Azure location."
  }
}
```
This requires the service team to investigate the root cause of this error.
**'x-ms-request-id': 'a4a958fa-e0a8-4a91-afa9-1c9b925fb3cc'**

**Comment by vivlingaiah** [comment] 2022-08-24 18:11
Are you using RunAs ? The extension has an issue with RunAs at this time. A fix has been merged for Windows machines, it has not been deployed and made available yet, though.

**Comment by apar-singhal** [comment] 2022-08-24 18:43
Yes, I am using the run-as-user flag.

I need this as without it the command is not working. I have a docker-desktop pre-installed and want to start it automatically with this command. But default user (NT AUTHORITY\SYSTEM) get Access Denied error.

**Comment by apar-singhal** [comment] 2022-08-24 20:55
When is the fix planned to be deployed?

**Comment by vivlingaiah** [comment] 2022-09-06 18:03
Fix is planned to be deployed in few weeks. Tentative date is 10/01

**Comment by mattwalkenhorst** [comment] 2022-10-19 03:57
I ran into this issue today, exact same scenario. @vivlingaiah is there any update on when a fix might be deployed?

**Comment by jadcosta** [comment] 2022-11-21 12:54
@vivlingaiah I'm still facing this issue, is there any estimative when this is going to be fixed?

**Comment by vivlingaiah** [comment] 2022-11-22 03:08
@jadcosta , please also check whether runAsUser has access to run the executable. Managed Run Command would not provide any additional access to runAs user.

**Comment by jadcosta** [comment] 2022-11-25 15:16
@vivlingaiah I'm experiencing exactly the same issue as was reported in this thread.

I'm getting the following output:
      "message": "This is a sample script with parameters  ",

I'm assuming it's running the default script as described above.

**Comment by jadcosta** [comment] 2023-01-05 15:41
@zhoxing-ms Are you able to share if this issue has been fixed?

**Comment by zhoxing-ms** [comment] 2023-01-06 02:11
@jadcosta Sorry, this is a service issue, we can only get the feedback from the service team.

@vivlingaiah May I ask what's the new progress?

**Comment by miblafi** [comment] 2023-03-14 23:13
Is there an ETA on when this will be fixed

**Comment by tlaukkanen** [comment] 2024-01-04 13:17
Any updates for 2024 to fix this and maybe improve documentation on how the `create` + `invoke` should be used together to run commands as specific user on VM? I'm still having similar error `The entity was not found in this Azure location.` with latest Azure CLI 2.55.0.

Tried it for example like this:
```bash
az vm run-command create \
  --name MyCustomCommand \
  --vm-name myvm \
  --resource-group rg-mygroup \
  --run-as-user customuser@localhost \
  --run-as-password <pwd> \
  --script "PowerShell -ExecutionPolicy Unrestricted -NonInteractive -File C:\temp\my-script.ps1 -foo:bar
```
...and then take the "name" and "id" from that output and trying to invoke it:
```bash
az vm run-command invoke \
  --command-id MyCustomCommand \
  --ids "/subscription/...<really_long_resource_id_of_previous_output>/runCommands/MyCustomCommand"
```
...and this causes error:
```
(NotFound) The entity was not found in this Azure location.
```

**Comment by tlaukkanen** [comment] 2024-01-08 06:30
So it turns out that `az vm run-command create ...` actually creates **and executes** the script right away ([spotted from this doc](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/virtual-machines/windows/run-command-managed.md#execute-a-script-with-the-vm)). Based on [Az CLI run-command docs](https://learn.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest#az-vm-run-command-create) I was assuming that you'll need to `invoke` it separately. The output of `create` just doesn't indicate the execution in any way. You can check the output using `show` command (see below).

So if someone else finds this thread when trying to run commands on Azure VM with specific user, I found the following to work.

This will create (and execute) the specified script on the VM:
```bash
az vm run-command create \
  --name MyCustomCommand \
  --vm-name myvm \
  --resource-group rg-mygroup \
  --run-as-user customuser \ # this was my local user on VM, "customuser@localhost" format didn't work
  --run-as-password <pwd> \
  --script "PowerShell -ExecutionPolicy Unrestricted -NonInteractive -File C:\temp\my-script.ps1 -foo:bar
```

You can check the output of execution using `show` command with `--expand instanceView` parameter
```bash
az vm run-command show \
  --name MyCustomCommand \
  --vm-name myvm \
  --resource-group rg-mygroup \
  --expand instanceView
```

**Comment by vivlingaiah** [comment] 2024-08-08 20:29
"az vm run-command Invoke" (Action Run Command / v1) or  "az vm run-command create"  (Managed Run Command / v2) are two separate APIs. You don't need to use both.
az vm run-command create would be enough to run a script. It also supports running as a different user using "RunAsUser" parameter and you'd be able to see output using "az vm run-command show" once you issue Run Command.
Is anyone having issues currently ?

**Comment by GabstaMSFT** [comment] 2024-08-20 14:59
@apar-singhal @miblafi @tlaukkanen checking if anyone is still experiencing this issue as this issue should be fixed in more recent versions.

**Comment by GabstaMSFT** [comment] 2024-08-20 16:08
@apar-singhal @miblafi @tlaukkanen checking if anyone is still experiencing this issue

**Comment by GabstaMSFT** [comment] 2024-09-24 14:26
#issue-addressed

**Closed** 2024-10-01 17:56 UTC
Labels: Compute, Service Attention, customer-reported, feature-request, Auto-Assign, issue-addressed
