### ISSUE TITLE
az aks browse - Failed to establish a new connection: [Errno 61] Connection refused'))

### ISSUE THREAD

**Issue by andrewfsmith** [Azure/azure-cli#9465] opened 2019-05-23 16:39 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106e05a90>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
python3.7/site-packages/urllib3/connection.py, ln 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
site-packages/urllib3/util/connection.py, ln 80, in create_connection
    raise err
...

python3.7/site-packages/requests/adapters.py, ln 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106e05a90>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse -n {} -g {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64 *

```

**Comment by yugangw-msft** [comment] 2019-05-23 21:53
dupe of #9452

**Closed by yugangw-msft** 2019-05-23 21:53 UTC
Labels: AKS
