### ISSUE TITLE
az consumption budget create fails with error - TypeError: 'Budget' object is not iterable

### ISSUE THREAD

**Issue by pebarrer** [Azure/azure-cli#7775] opened 2018-11-07 04:01 UTC
Following line in AZ cli throws error
azure-cli (2.0.49)
consumption (0.4.0)
--
$ az consumption budget create --amount 100 --time-grain annually --start-date 2018-11-01 --end-date 2019-11-01 --resource-group-filter demo --resource-group demo --budget-name mybudget --category cost

'Budget' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/consumption/_exception_handler.py", line 17, in consumption_exception_handler
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 346, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/consumption/custom.py", line 111, in cli_consumption_create_budget
    return client.create_or_update(resource_group_name, budget_name, parameters)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/consumption/operations/budgets_operations.py", line 265, in create_or_update
    header_parameters.update(custom_headers)
TypeError: 'Budget' object is not iterable

**Comment by yonzhan** [comment] 2021-07-08 01:33
route to service team

**Comment by sashahdo** [comment] 2021-07-13 19:03
Closing this incident since it over 2.5 years old. Feel free to reopen this ticket or create a new one if the issue can still be reproduced.

**Closed by sashahdo** 2021-07-13 19:03 UTC
Labels: Consumption-Budget, Service Attention, bug
