### ISSUE TITLE
Documentation: wildcard character * interpreted by markdown

### ISSUE THREAD

**Issue by nbering** [Azure/azure-cli#4869] opened 2017-11-12 00:51 UTC
I noticed this on the `azure storage blob upload` command for the `--if-none-match` option. `*` is a special character in markdown and should be escaped, or matched pairs will become a marker for an italicized block.

I'd have updated the markdown file, but I suspect this page was generated, and I would need the escape character added upstream to prevent it from being clobbered.

**Comment by tjprescott** [comment] 2018-11-30 16:05
@adewaleo this likely needs to be done as part of the sphinx generation process.

**Comment by nbering** [comment] 2018-11-30 16:36
It's been a while since I originally posted this. When the issue finally received a comment, I went back to check if it's still and issue. It is, and can be seen here:

https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-upload

![image](https://user-images.githubusercontent.com/4421371/49302101-1df91380-f494-11e8-97b4-421153250df5.png)

**Comment by adewaleo** [comment] 2019-05-03 20:09
Being tracked by Docs team [here](https://ceapex.visualstudio.com/Engineering/_workitems/edit/89650).

**Comment by adewaleo** [comment] 2019-07-26 21:31
closing as this is being address by the docs team cc: @daxianji007

**Comment by nbering** [comment] 2019-07-28 19:24
Is this closed because it was supposed to be fixed, or just no longer tracked here? I can't see the linked issue, and the public documentation page still has this issue.

**Comment by adewaleo** [comment] 2019-07-29 04:13
@nbering I closed this because it is being tracked internally by our docs team.

cc: @daxianji007 @dend

**Comment by nbering** [comment] 2019-07-29 13:59
Just curious, really. But also that little feedback that when I volunteer my time to report issues, it's nice to be able to see when it gets closed.

**Comment by adewaleo** [comment] 2019-07-29 18:09
@nbering no p. Thanks for following up about this and opening the issue in the first place.

I assumed that given this issue would be handled by the docs team it would be okay to close it. But given your interest in the issue and that the link I posted above is not publicly viewable. I will reopen this issue.

Hopefully @daxianji007 or @dend will be able to close this duplicate of their internally tracked issue when it is resolved.

**Comment by daxianji007** [comment] 2019-07-30 09:38
Actually this can be 2 kinds of issues:
1. It is the [reStructuredText](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) syntax that turns `*` to `<emphasis>`, which is the built-in syntax of sphinx and there is no way to turn it off.
I have created same [issue here](https://github.com/Azure/azure-cli/issues/9117)
This is not easy to fix. Currently I just add a post step in Docs CI to turn `<emphasis>` back to `*` as work-around.
2. The docs template markup the `*` to `<em>`. I am working on it.

**Comment by adewaleo** [comment] 2019-07-31 22:57
> Actually this can be 2 kinds of issues:
> 
> 1. It is the [reStructuredText](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) syntax that turns `*` to `<emphasis>`, which is the built-in syntax of sphinx and there is no way to turn it off.
>    I have created same [issue here](https://github.com/Azure/azure-cli/issues/9117)
>    This is not easy to fix. Currently I just add a post step in Docs CI to turn `<emphasis>` back to `*` as work-around.
> 2. The docs template markup the `*` to `<em>`. I am working on it.

@daxianji007, I hear you. Is there a way we can escape the asterisk to to make this easier for you? We might be able to add some logic in our doc generation scripts / command to escape asterisks or force users to denote asterisks a certain way when authoring help text.

**Comment by daxianji007** [comment] 2019-08-27 07:17
@adewaleo @Juliehzl Escaping is easy. Just use `\*` instead of `*`. If that can be in the doc generation scripts / command, that would be a perfect solution.

**Comment by Juliehzl** [comment] 2019-08-28 03:04
@nbering  We are still following up this issue with docs team. @daxianji007 will help us do some change from docs system. @daxianji007 If there is any update, please let me know.

**Comment by daxianji007** [comment] 2019-08-30 06:22
fixed. @Juliehzl you can verify it in internal site before next go-live

**Comment by adewaleo** [comment] 2019-08-30 19:36
> @adewaleo @Juliehzl Escaping is easy. Just use `\*` instead of `*`. If that can be in the doc generation scripts / command, that would be a perfect solution.

@daxianji007 @Juliehzl this makes sense from a markdown perspective. However, CLI help (az --help) interprets help content literally, it doesn't interpret it as markdown as CLI's typically emit output in plain text.

This means if `*` is replaced with `\*` then the actual help output when `--help` is run then the user sees `\*`, unless we add special CLI logic to strip the backslash when the emitting help output.

**Comment by daxianji007** [comment] 2019-09-02 08:39
@adewaleo Yes, that is the key point. Now I have added a step in Docs CI to escape the `*` after sphinx generates xml. This issue should have been resolved. But we need next Docs release to show the fix in Docs page.

**Comment by adewaleo** [comment] 2019-09-03 18:28
@daxianji007 I see, thanks for this. What PR was this?

**Comment by Juliehzl** [comment] 2019-09-04 02:31
@nbering It is fixed now. Thanks for your feedback. And @daxianji007 thanks a lot for quick action. Also thanks @adewaleo for keeping track of this issue.

**Closed by Juliehzl** 2019-09-04 02:31 UTC
Labels: Bug, Documentation

**Comment by nbering** [comment] 2019-09-04 13:56
Confirmed fixed. Good word!

![image](https://user-images.githubusercontent.com/4421371/64261214-2b976a00-cefa-11e9-8e2d-b606fa65fb8a.png)
