### ISSUE TITLE
apt-get support for Ubuntu 18.10 (Cosmic Cuttlefish).

### ISSUE THREAD

**Issue by pjdv2** [Azure/azure-cli#7918] opened 2018-11-26 20:34 UTC
**Describe the bug**
`apt-get` not yet working for this release of Ubuntu.

**To Reproduce**
Try installing via `apt-get` using [this](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#install-step-1) documentation. Fails at the last step using `sudo apt-get install azure-cli`.

**Expected behavior**
_Azure Cli_ to be installed on this Ubuntu release.

**Environment summary**
bash.

**Comment by tjprescott** [comment] 2018-11-26 21:00
Duplicate of #7776.

**Closed by tjprescott** 2018-11-26 21:00 UTC
