### ISSUE TITLE
Error when logging into Azure Government

### ISSUE THREAD

**Issue by duanecr** [Azure/azure-cli#12808] opened 2020-03-31 16:21 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
'displayName'
Traceback (most recent call last):
Temp\pip-install-i2ys5wad\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 625, in execute
azure\cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 682, in _run_job
Local\Temp\pip-install-i2ys5wad\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 659, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 531, in default_command_handler
azure\cli\command_modules\profile\custom.py, ln 150, in login
azure-cli-core\azure\cli\core\_profile.py, ln 196, in find_subscriptions_on_login
azure-cli-core\azure\cli\core\_profile.py, ln 832, in find_through_authorization_code_flow
azure-cli-core\azure\cli\core\_profile.py, ln 883, in _find_using_common_tenant
KeyError: 'displayName'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
Run `az cloud set --name AzureUSGovernment`

Run `az login`

## Expected Behavior
I should be able to log in.  I get a message that I logged in, but I also get a lot of errors after that message.  It looks like some commands work, such az account list, but az group list gives an error about login.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.0

```
## Additional Context

The command failed with an unexpected error. Here is the traceback:

'displayName'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\commands\__init__.py", line 625, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\commands\__init__.py", line 689, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\commands\__init__.py", line 682, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\__init__.py", line 531, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli\azure\cli\command_modules\profile\custom.py", line 150, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\_profile.py", line 196, in find_subscriptions_on_login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\_profile.py", line 832, in find_through_authorization_code_flow
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-i2ys5wad\azure-cli-core\azure\cli\core\_profile.py", line 883, in _find_using_common_tenant
KeyError: 'displayName'

**Comment by yonzhan** [comment] 2020-03-31 22:10
add to S169

**Comment by jiasli** [comment] 2020-04-01 07:55
Duplicate of https://github.com/Azure/azure-cli/issues/12818. Please see the comment at https://github.com/Azure/azure-cli/issues/12818#issuecomment-607031075.

**Closed** 2020-04-01 11:07 UTC
Labels: Authentication

**Comment by jiasli** [comment] 2020-04-01 11:29
We have release 2.3.1 and fixed this issue. Please update the installed Azure CLI and give it a try!
