### ISSUE TITLE
Error on az login: RuntimeError: 0. The ID token is not yet valid.

### ISSUE THREAD

**Issue by umbeb** [Azure/azure-cli#21357] opened 2022-02-18 12:46 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1645184470.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1645187945,
  "nbf": 1645187945,
  "exp": 1645191845,
  "aio": "AWQAm/8TAAAA3yMlxzEyj9fC9FTLoSEPD0d7/eNkd9DGP4keXfKpMS0HRrXE2Iq6wOpZ9V78nAfxAvofBCSCV4OhwDli+mI3mPknmqcs2IitEykougX7J9aRHq943b6bh3K8dnJPWxH4",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "preferred_username": "umbeb@yahoo.com",
  "prov_data": [
    {
      "at": true,
      "prov": "github.com",
      "altsecid": "10133667"
    }
  ],
  "rh": "0.AXoAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAM8.",
  "sub": "5SUrtqXUZAoQ4LyCkmjvm9IwZZZumYSnX4kKunin5XE",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "7qujjiliiUGDafS3BIYqAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 158, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 153, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 182, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 1619, in acquire_token_by_device_flow
    **kwargs))
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 384, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 347, in _obtain_token_by_device_flow
    self.DEVICE_FLOW["GRANT_TYPE"], data=data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 115, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 795, in _obtain_token
    "response": _resp, "params": params, "data": _data,
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 582, in <lambda>
    event, environment=authority.instance)),
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 307, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 153, in __add
    if id_token else {})
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    err, _now, json.dumps(decoded, indent=2)))
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1645184470.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1645187945,
  "nbf": 1645187945,
  "exp": 1645191845,
  "aio": "AWQAm/8TAAAA3yMlxzEyj9fC9FTLoSEPD0d7/eNkd9DGP4keXfKpMS0HRrXE2Iq6wOpZ9V78nAfxAvofBCSCV4OhwDli+mI3mPknmqcs2IitEykougX7J9aRHq943b6bh3K8dnJPWxH4",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "preferred_username": "umbeb@yahoo.com",
  "prov_data": [
    {
      "at": true,
      "prov": "github.com",
      "altsecid": "10133667"
    }
  ],
  "rh": "0.AXoAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAM8.",
  "sub": "5SUrtqXUZAoQ4LyCkmjvm9IwZZZumYSnX4kKunin5XE",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "7qujjiliiUGDafS3BIYqAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.13.0-28-generic-x86_64-with-debian-11.0, Ubuntu 21.10
Python 3.6.10
Installer: DEB

azure-cli 2.33.1
```

**Comment by yonzhan** [comment] 2022-02-18 13:36
@jiasli for awareness

**Comment by jiasli** [comment] 2022-03-04 10:19
Duplicate of #20388

**Closed** 2022-03-04 10:20 UTC
Labels: Account, customer-reported, Auto-Assign
