### ISSUE TITLE
az login error

### ISSUE THREAD

**Issue by shabeeraslam1** [Azure/azure-cli#23295] opened 2022-07-21 15:27 UTC
PS C:\Users\sa9478> az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231
PS C:\Users\sa9478> az login --use-device-code
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code E3YW4825W to authenticate.
Terminate batch job (Y/N)? y
PS C:\Users\sa9478> az login --use-device-code
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AC7L2EHWX to authenticate.
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231

**Comment by yonzhan** [comment] 2022-07-21 21:36
Duplicate of https://github.com/Azure/azure-cli/issues/20231

**Closed by yonzhan** 2022-07-21 21:36 UTC
Labels: Account, customer-reported, Auto-Assign
