### ISSUE TITLE
az appservice plan create does not allow P

### ISSUE THREAD

**Issue by doodlemania2** [Azure/azure-cli#6753] opened 2018-07-09 16:15 UTC
**Describe the bug**
az appservice plan create does not allow P SKUs

**To Reproduce**
az appservice plan create --name wplab --resource-group wplab --sku p2v2 --is-linux (can't create Linux P2V2 in CLI)
Error:
usage error: P2 is not a valid sku for linux plan, please use one of the following: B1, B2, B3, S1, S2, S3

**Expected behavior**
Ability to create P series like I can in the portal.

**Environment summary**
CLI in Azure Shell (shell.azure.com)

**Additional context**

**Comment by ahmedelnably** [comment] 2018-07-09 16:45
Thanks for reporting the issue, closing this is as it is a dupe of https://github.com/Azure/azure-cli/issues/6663
This is a known issue, we are working on a fix for it.

**Closed by ahmedelnably** 2018-07-09 16:45 UTC
Labels: Feature, Web Apps, Web Apps-cli
