### ISSUE TITLE
AZ Webapp up command throwing exception

### ISSUE THREAD

**Issue by TheEngineeringAlgorist** [Azure/azure-cli#11089] opened 2019-11-04 04:18 UTC
## Describe the bug
Azure throws an exception while trying to deploy .net core 2.2 application to sandbox app service
**Command Name**
az webapp up

**Errors:**

~/BestBikeApp$ az webapp up --name $APPNAME --resource-group $APPRG --plan $APPPLAN --sku $APPSKU --location "$APPLOCATION"
Webapp TestAzureDeployAlgorist already exists. The command will deploy contents to the existing app.
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, ininvoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'

To open an issue, please run: 'az feedback'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

I am following azure hosting tutorial at the following URL:

https://docs.microsoft.com/en-us/learn/modules/host-a-web-app-with-azure-app-service 

When I run the following command:

az webapp up --name $APPNAME --resource-group $APPRG --plan $APPPLAN --sku $APPSKU --location "$APPLOCATION"

Azure throws an exception

## Expected Behavior

I expect my sandbox application to deploy

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by jamesallen74** [comment] 2019-11-04 04:40
I receive the same issue on that tutorial link when I attempt "az webapp up" command with parameters.

CLI version is 2.0.76.

**Comment by Juliehzl** [comment] 2019-11-05 06:56
dupe of #11100

**Comment by kairaazure** [comment] 2019-11-09 08:41
Getting the same error with latest version of azure cli 

c

cloudkapil@Azure:~/kirti/html-docs-hello-world$ az webapp up --location centralus --name myapp12 --resource-group kirti

Webapp myapp12 already exists. The command will deploy contents to the existing app.
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'resource_group'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)

loudkapil@Azure:~/kirti/html-docs-hello-world$ az --version
azure-cli                         2.0.76

command-modules-nspkg              2.0.3
core                              2.0.76
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/cloudkapil/.azure/cliextensions'
FYI----->
Python (Linux) 3.6.5 (default, Oct 30 2019, 06:32:16)
[GCC 5.4.0 20160609]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

**Comment by baddevotions** [comment] 2019-11-12 14:23
i get the same issue running through the sandbox learning here at step 2 https://docs.microsoft.com/en-gb/learn/modules/develop-app-that-queries-azure-sql/5-exercise-connect-aspnet-to-azure-sql

**Comment by mcurko** [comment] 2019-11-19 13:25
Same here: https://azuredevopslabs.com/labs/vstsextend/docker/

**Comment by LeoPAllen** [comment] 2019-11-25 16:50
I'm running into the same issue using this Quickstart: https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python?tabs=bash

| => az --version
azure-cli                         2.0.76

command-modules-nspkg              2.0.3
core                              2.0.76
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.0.76/libexec/bin/python'
Extensions directory '/Users/leoallen/.azure/cliextensions'

Python (Darwin) 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by panchagnula** [comment] 2019-11-25 18:24
Sorry for the trouble but this is a known issue and until the fix is rolled out in 2.0.77 which is scheduled for Nov 26th you can rollback to 2.0.75 or use the Edge builds

**Comment by jsntcy** [comment] 2019-11-28 06:23
@jamesallen74, @kairaazure, @baddevotions, @mcurko, @LeoPAllen, Could you try the Azure CLI latest version (2.0.77) to see if this issue is fixed?

**Closed** 2019-12-27 00:41 UTC
Labels: Service Attention, Web Apps

**Comment by saipraveen-a** [comment] 2020-09-17 04:16
I am using CLI version 2.11.1 and still facing the same issue
