### ISSUE TITLE
az cognitiveservices account create --kind options are difficult to find

### ISSUE THREAD

**Issue by bowdenk7** [Azure/azure-cli#6190] opened 2018-04-23 22:00 UTC
---

### Environment summary

Install Method: homebrew
CLI version: 2.0.31
OS version: macOS High Sierra - 10.13.1
Shell Type: bash

---

I am trying to write a tutorial for using the Node.js cognitive services spell check sdk, and part of that requires the user to setup a congitive services account. 
```
az cognitiveservices account create --kind 'spellcheck' -n cogstest -g cogstestrg --sku S0 --location 'westus' --yes
```
With the above command I get the following error:`(InvalidApiSetId) The account type 'spellcheck' is either invalid or unavailable in given region.`

This error message is great in that I know what the problem is, but I'm not sure what string to pass in to create a spell check account. Checking [the docs](https://docs.microsoft.com/en-us/cli/azure/cognitiveservices/account?view=azure-cli-latest#required-parameters) doesn't help (which I'm also working to change), but would it be possible to list valid options in the error text or help text (or both)?

The current help text is: 
```
$ az cognitiveservices account create  --help

Command
    az cognitiveservices account create: Create an Azure Cognitive Services account.

Arguments
    --kind              [Required]: The API name of cognitive services account.
    --location -l       [Required]: Location. You can configure the default location using `az
                                    configure --defaults location=<location>`.
    --name -n           [Required]: Cognitive service account name.
    --resource-group -g [Required]: Name of resource group. You can configure the default group
                                    using `az configure --defaults group=<name>`.
    --sku               [Required]: The Sku of cognitive services account.
    --tags                        : Space-separated tags in 'key[=value]' format. Use '' to clear
                                    existing tags.
    --yes                         : Do not prompt for terms confirmation.
```

After a lot of snooping I ended up finding the valid options [here](https://github.com/Azure/azure-sdk-for-python/blob/d34b99738a391431947d84ba6987f02dc7946208/azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_create_parameters.py#L20).

```
:param kind: Required. Gets or sets the Kind of the resource. Possible
     values include: 'Academic', 'Bing.Autosuggest', 'Bing.Search',
     'Bing.Speech', 'Bing.SpellCheck', 'ComputerVision', 'ContentModerator',
     'CustomSpeech', 'Emotion', 'Face', 'LUIS', 'Recommendations',
     'SpeakerRecognition', 'Speech', 'SpeechTranslation', 'TextAnalytics',
     'TextTranslation', 'WebLM'
```

**Comment by tjprescott** [comment] 2018-04-23 22:03
Duplicate of #5246.

**Comment by bowdenk7** [comment] 2018-04-23 22:04
Ahh sorry - I looked really hard for a dupe before posting this ><

**Closed by tjprescott** 2018-04-23 22:03 UTC
Labels: CognitiveServices, Documentation

**Comment by tjprescott** [comment] 2018-04-23 22:08
No worries.  You are correct though--the command should definitely provide information on where to get those values. cc/ @kostenray
