### ISSUE TITLE
 az group creation and az keyvault create failed

### ISSUE THREAD

**Issue by allschu** [Azure/azure-cli#14470] opened 2020-07-22 16:56 UTC
## Describe the bug

**Command Name**
`az keyvault create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Enter the following values

 $myResourceGroup="<<VAULTNAME>>"
 $myKeyVault="<<VAULTNAME>>" + $(get-random -minimum 10000 -maximum 100000)
 $myLocation="westus"

 az group create --name $myResourceGroup --location $myLocation

## Expected Behavior

KeyVault created in Azure

## Environment Summary
```
Linux-4.15.0-1091-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.0 *

```

**Comment by allschu** [comment] 2020-07-22 17:35
if I do this directly like so: 
` az keyvault create --resource-group "testvault" --name "testVault" --location "westus"`

it works fine!

**Comment by yonzhan** [comment] 2020-07-22 22:48
@zhoxing-ms  please help check az group part.

**Comment by zhoxing-ms** [comment] 2020-07-23 00:38
@allschu Hi, does this problem occur in CloudShell? If so, it's a known issue #11749 of Cloudshell. You can try to run `az login` as a workaround.

**Comment by allschu** [comment] 2020-07-23 05:57
@zhoxing-ms tried to login again, but resulted in exactly the same error

**Comment by maertendMSFT** [comment] 2020-10-06 18:24
Can we close this as a dupe of https://github.com/Azure/azure-cli/issues/11749?

**Closed** 2020-10-07 01:34 UTC
Labels: Cloud Shell, Service Attention, customer-reported
