### ISSUE TITLE
unable to create azure vm -following documentation -https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-manage-vm#code-try-0

### ISSUE THREAD

**Issue by PritiM0912** [Azure/azure-cli#16397] opened 2020-12-30 15:08 UTC
## Describe the bug
OSError: [Errno 30] Read-only file system: '/home/dev/.azure/commands/2020-12-30.15-02-31.group_create.225.log'

**Command Name**
az vm create \
    --resource-group myResourceGroupVM \
    --name myVM \
    --image UbuntuLTS \
    --admin-username azureuser \
    --generate-ssh-keys

**Errors:**
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/dev/.azure/commands/2020-12-30.15-02-31.group_create.225.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 511, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 86, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 108, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/dev/.azure/commands/2020-12-30.15-02-31.group_create.225.log'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
-->https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-manage-vm#code-try-0

- _Put any pre-requisite steps here..._
- ``create resource group using following command.
- az group create --name myResourceGroupVM --location eastus

## Expected Behavior
Create virtual machine

## Environment Summary
```
Linux-4.15.0-1102-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.16.0 *

Extensions:
ai-examples 0.2.5

```

**Comment by fengzhou-msft** [comment] 2020-12-30 15:41
The issues seems to be caused by a known directory permission [issue](https://github.com/Azure/azure-cli/issues/13855) of Cloud Shell. Please follow this [workaround](https://github.com/Azure/azure-cli/issues/13855#issuecomment-722412068).

**Comment by fengzhou-msft** [comment] 2020-12-30 15:41
Duplicate of #13855

**Comment by yungezz** [comment] 2021-03-16 09:23
> The issues seems to be caused by a known directory permission [issue](https://github.com/Azure/azure-cli/issues/13855) of Cloud Shell. Please follow this [workaround](https://github.com/Azure/azure-cli/issues/13855#issuecomment-722412068).

hi @PritiM0912 does the workaround work for you? thanks.

**Comment by yungezz** [comment] 2021-03-29 02:22
close since no response. feel free to create new issue if any other error met.

**Closed by yungezz** 2021-03-29 02:22 UTC
Labels: Cloud Shell, Compute - VM, Core, OKR3.2 Candidate, customer-response-expected, question
