### ISSUE TITLE
Container SAS: Missing permissions a (add) + c (create)

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/azure-cli#8809] opened 2019-03-18 15:27 UTC
**Is your feature request related to a problem? Please describe.**
According to https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas#specifying-permissions there should be an `add` as well as a `create` permission for Container SAS tokens.

Currently the lastest `az cli`(2.0.60) doesn't support it.

Output:
`az storage container policy create: error: valid values are (d)elete (l)ist (r)ead (w)rite or a combination thereof.`

**Describe the solution you'd like**
The [--permissions PERMISSION] flag should accept `a` and `c` permission attributes.

Hint: The same applies for access policies (see https://docs.microsoft.com/en-us/cli/azure/storage/container/policy?view=azure-cli-latest#az-storage-container-policy-create)

**Comment by williexu** [comment] 2019-03-19 17:37
@zezha-msft currently the storage data-plane sdk does not support add or create permissions: https://github.com/Azure/azure-storage-python/blob/216f883533b9324c1a38eae4515261d2f630682f/azure-storage-blob/azure/storage/blob/models.py#L650-L672

Does it need to be updated?

**Comment by zezha-msft** [comment] 2019-03-19 21:49
@williexu thanks for tagging me. 

@mirobers do you know if there's any historical reason why `add` and `create` are absent?

**Comment by jrauschenbusch** [comment] 2019-03-25 08:32
is there any update? is it just the extension of the model class?

**Comment by zezha-msft** [comment] 2019-03-26 20:50
@jrauschenbusch sorry for the wait. I confirmed that `add` and `create` should be added. I've created an item on our side to track this work.

**Comment by jrauschenbusch** [comment] 2019-06-19 10:23
As meanwhile the storage data-plane sdk supports the missing permissions, is there also an update planned for the azure-cli?

See: https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/models.py#L650

**Comment by zezha-msft** [comment] 2019-07-03 20:50
@zhusijia26 @limingu this has been fixed in the SDK already: https://github.com/Azure/azure-storage-python/releases/tag/v2.0.0-blob

**Comment by zhusijia26** [comment] 2019-07-03 20:56
Thanks @zezha-msft! Will wait for @limingu 's comment.

**Comment by limingu** [comment] 2019-07-03 21:55
Need to update the SDK version in the CLI. I will update once that is done.

**Comment by jrauschenbusch** [comment] 2019-08-12 10:52
Hi. Are there any updates? Still waiting for the feature.

**Comment by zhusijia26** [comment] 2019-08-12 15:26
Looks like @Juliehzl is handling this issue now. I just removed Storage label. Please add Storage if there is anything we can do. @Juliehzl please help with the issue. Thanks!

**Comment by Juliehzl** [comment] 2019-08-14 15:56
@jrauschenbusch  I think it is already supported. See https://docs.microsoft.com/en-us/cli/azure/storage/container/policy?view=azure-cli-latest#az-storage-container-policy-create.

**Comment by jrauschenbusch** [comment] 2019-09-10 08:46
@Juliehzl No, it isn't supported.

I think there is an update needed for azure-storage-blob to at least v2.0.0 in the following files:
- https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py2.Linux.txt#L81
- https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py2.Darwin.txt#L81
- https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py2.windows.txt#L81
- https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.Linux.txt#L81
- https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.Darwin.txt#L81
- https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.windows.txt#L81

See releases: https://github.com/Azure/azure-storage-python/releases

But honestly i don't understand the repository split of the different sdks as there is also a ` azure-sdk-for-python` repository which also contains storage related code:
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage

**Comment by jrauschenbusch** [comment] 2019-09-10 13:02
I've to withdraw my last comment. It seems that it's supported now. But i don't have any clue which change was responsible for it. Unfortunately there is also no single release note which notes the added functionality.

**Comment by zezha-msft** [comment] 2019-09-10 18:16
Hi @jrauschenbusch, for context, the storage package in azure-sdk-for-python is the redesigned version that is in preview right now.

**Closed** 2019-10-16 08:32 UTC
Labels: Feature Request
