### ISSUE TITLE
[webapp] - hostname parameter is missing in the SSL Bind command

### ISSUE THREAD

**Issue by pratapprashant** [Azure/azure-cli#9677] opened 2019-06-13 23:16 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Hostname parameter is missing in the below CLI cmd.

                   az webapp config ssl bind  

https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest 

Hostname parameter is available in the PowerShell cmdlet as “Name” and also available in the REST API.

New-AzureRmWebAppSSLBinding -Name 
https://docs.microsoft.com/en-us/powershell/module/azurerm.websites/new-azurermwebappsslbinding?view=azurermps-6.13.0  

REST API has hostname parameter, 
https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdatehostnamebinding 

**To Reproduce**
Run this below cmd 
az webapp config ssl bind  

**Expected behavior**
Command should have parameter to specify the hostname

**Environment summary**

**Additional context**
PowerShell cmdlet and REST API has hostname parameter.

**Comment by SQLLord** [comment] 2019-06-21 14:29
There is a need for this because the normal binding should grab all the SAN names in the cert and bind it but it will miss the SCM of the web app and not everyone has a wild card cert for their ASEs.  So we have to bind SCM manually.  The parameter will allow for us to do the manual binding of the scm with this parameter.

**Comment by btardif** [comment] 2019-07-15 19:37
This is a dupe of #9804

**Closed** 2019-07-15 19:37 UTC
Labels: App Services, Needs Triage, Service Attention, Web Apps-cli
