### ISSUE TITLE
Issues with Azure Container Registry Login and timing out 

### ISSUE THREAD

**Issue by beaudryj** [Azure/azure-cli#6478] opened 2018-06-02 00:04 UTC
**Describe the bug**
I am currently using Azure CLI to login to Azure Container registry and we are finding ourselves having non reproducable timeouts, we are not sure if its a docker problem, an ACR problem, or an AZ CLI problem

**To Reproduce**
I wish I had some :/

**Expected behavior**
Container pushes and session stays logged in 

**Environment summary**
Install Method - Chocolatey 
Version: 2.0.32

**Additional context**
Container will be mid push and then it ends saying unauthorized access to container registry. 

Our Build Server passes through a Palo Alto Firewall that Decrypts and checks encrypted traffic, I had them set an exception to oursite.azurecr.io and stop decrypting to see if that helps resolve our problem, but I noticed we started getting this error as well today. (I did notice Azure CLI is still able to log in and do its thing, but it seemed to have broken the Azure CLI login process to the container registry which may be related to my existing problem)

```
3:36:11][Step 11/18] ERROR: HTTPSConnectionPool(host='REDACTED.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
[13:36:11][Step 11/18] Traceback (most recent call last):
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 441, in wrap_socket
[13:36:11][Step 11/18]     cnx.do_handshake()
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\SSL.py", line 1806, in do_handshake
[13:36:11][Step 11/18]     self._raise_ssl_error(self._ssl, result)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\SSL.py", line 1546, in _raise_ssl_error
[13:36:11][Step 11/18]     _raise_current_error()
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
[13:36:11][Step 11/18]     raise exception_type(errors)
[13:36:11][Step 11/18] OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
[13:36:11][Step 11/18] 
[13:36:11][Step 11/18] During handling of the above exception, another exception occurred:
[13:36:11][Step 11/18] 
[13:36:11][Step 11/18] Traceback (most recent call last):
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
[13:36:11][Step 11/18]     chunked=chunked)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
[13:36:11][Step 11/18]     self._validate_conn(conn)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
[13:36:11][Step 11/18]     conn.connect()
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connection.py", line 326, in connect
[13:36:11][Step 11/18]     ssl_context=context)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
[13:36:11][Step 11/18]     return context.wrap_socket(sock, server_hostname=server_hostname)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 448, in wrap_socket
[13:36:11][Step 11/18]     raise ssl.SSLError('bad handshake: %r' % e)
[13:36:11][Step 11/18] ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
[13:36:11][Step 11/18] 
[13:36:11][Step 11/18] During handling of the above exception, another exception occurred:
[13:36:11][Step 11/18] 
[13:36:11][Step 11/18] Traceback (most recent call last):
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 440, in send
[13:36:11][Step 11/18]     timeout=timeout
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
[13:36:11][Step 11/18]     _stacktrace=sys.exc_info()[2])
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\retry.py", line 388, in increment
[13:36:11][Step 11/18]     raise MaxRetryError(_pool, url, error or ResponseError(cause))
[13:36:11][Step 11/18] urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='REDACTED.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
[13:36:11][Step 11/18] 
[13:36:11][Step 11/18] During handling of the above exception, another exception occurred:
[13:36:11][Step 11/18] 
[13:36:11][Step 11/18] Traceback (most recent call last):
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
[13:36:11][Step 11/18]     cmd_result = self.invocation.execute(args)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 332, in execute
[13:36:11][Step 11/18]     six.reraise(*sys.exc_info())
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
[13:36:11][Step 11/18]     raise value
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 306, in execute
[13:36:11][Step 11/18]     result = cmd(params)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 167, in __call__
[13:36:11][Step 11/18]     return super(AzCliCommand, self).__call__(*args, **kwargs)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
[13:36:11][Step 11/18]     return self.handler(*args, **kwargs)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
[13:36:11][Step 11/18]     result = op(**command_args)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\custom.py", line 169, in acr_login
[13:36:11][Step 11/18]     password=password)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 179, in get_login_credentials
[13:36:11][Step 11/18]     only_refresh_token=True)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 136, in _get_credentials
[13:36:11][Step 11/18]     password = _get_aad_token(cli_ctx, login_server, only_refresh_token, repository, permission)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 39, in _get_aad_token
[13:36:11][Step 11/18]     challenge = requests.get('https://' + login_server + '/v2/', verify=(not should_disable_connection_verify()))
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\api.py", line 72, in get
[13:36:11][Step 11/18]     return request('get', url, params=params, **kwargs)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\api.py", line 58, in request
[13:36:11][Step 11/18]     return session.request(method=method, url=url, **kwargs)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 508, in request
[13:36:11][Step 11/18]     resp = self.send(prep, **send_kwargs)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 618, in send
[13:36:11][Step 11/18]     r = adapter.send(request, **kwargs)
[13:36:11][Step 11/18]   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 506, in send
[13:36:11][Step 11/18]     raise SSLError(e, request=request)
[13:36:11][Step 11/18] requests.exceptions.SSLError: HTTPSConnectionPool(host='REDACTED.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
[13:36:11][Step 11/18] Process exited with code 0
```

**Comment by djyou** [comment] 2018-06-13 18:58
@beaudryj This looks like a client with unsigned cert issue. Could you try setting the env variable
```
AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1
```
to bypass cert check?
/cc @sajayantony

**Comment by Dost2010** [comment] 2018-10-09 23:41
Hello,
My client is using expressroute and we are facing exactly the same issue. We are running a loop to go through container registry and cleaning up one by one. Occasionally we get the following error. AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1 solve the problem. However we want the verification to happen. Here is the error.

az : ERROR: HTTPSConnectionPool(host='acr7316.azurecr.io', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 
'tls_process_server_certificate', 'certificate verify failed')],)",),))
At line:21 char:10
+ $repo = (az acr repository list -n $regi | ConvertFrom-Json)
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: HTTPSCon...iled')],)",),)):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\contrib\pyopenssl.py", line 444, in wrap_socket
    cnx.do_handshake()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\OpenSSL\SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\OpenSSL\SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connection.py", line 356, in connect
    ssl_context=context)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\util\ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\contrib\pyopenssl.py", line 450, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acr7316.azurecr.io', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(SSLError("bad handshake: 
Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-acr\azure\cli\command_modules\acr\repository.py", line 227, in acr_repository_list
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-acr\azure\cli\command_modules\acr\_
docker_utils.py", line 225, in get_access_credentials
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-acr\azure\cli\command_modules\acr\_docker_utils.py", line 151, in _get_credentials
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-acr\azure\cli\command_modules\acr\_docker_utils.py", line 101, in _get_aad_token
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='acr7316.azurecr.io', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL 
routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by djyou** [comment] 2018-10-10 00:04
@Dost2010 Could you please confirm is it just ACR commands that are not working or all CLI commands are not working for you?

@troydai @tjprescott Is there a more secured workaround other than disabling verification for this issue?

**Comment by sajayantony** [comment] 2019-07-11 09:04
Consider closing this since there is no action planned on this item.

**Comment by tjprescott** [comment] 2019-07-11 15:34
How can you have no action planned on an issue that clearly raises a stack trace?

**Comment by sajayantony** [comment] 2019-07-11 15:48
Ok let’s see if this still an issue. 
@Dost2010 does this condition still occur? 
Also can you share your output from `az acr check-health —ignore-errors`

**Comment by yugangw-msft** [comment] 2019-10-09 08:09
Likely there was a proxy server involved. If yes, then this is not a ACR command specific; rather common to all CLI commands. For secure ways to only accept unsigned certificates of proxy server, we wrote a [doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy) with detail instructions

**Closed** 2019-10-09 08:10 UTC
Labels: Container Registry, Question, Service Attention

**Comment by saad-hassanDS** [comment] 2020-04-16 09:31
Hi, Output of azr health check is this:
![image](https://user-images.githubusercontent.com/58459816/79439969-e5a59700-7fee-11ea-8e64-6d58cba2a2f4.png),

Still getting that timeout error
