### ISSUE TITLE
az role definition

### ISSUE THREAD

**Issue by devhl-labs** [Azure/azure-cli#30061] opened 2024-10-09 19:44 UTC
### Describe the bug

Updating a role is giving an error, apparently looking for property roleName

The command is similar to this
"az" "role" "definition" "update" "--role-definition" "{\"Id\":\"/subscriptions/guid/providers/Microsoft.Authorization/roleDefinitions/guid\"\"IsCustom\":true\"Description\":\"Some test role\"\"Actions\":[\"*\"]\"NotActions\":[]\"DataActions\":[]\"NotDataActions\":[]\"AssignableScopes\":[\"/subscriptions/guid\"]}"

The docs don't mention including role name. Also the casing of the properties is different.
https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles-cli#update-a-custom-role

Including the role name seems to cause this warning
WARNING: Readonly attribute type will be ignored in class <class 'azure.mgmt.authorization.v2022_05_01_preview.models._models_py3.RoleDefinition'>

### Related command

az role definition

### Errors

ERROR: 'roleName'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 75, in update_role_definition
    return _create_update_role_definition(cmd, role_definition, for_update=True)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 105, in _create_update_role_definition
    role_name = role_definition['roleName']
KeyError: 'roleName'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Issue script & Debug output

n/a

### Expected behavior

Update the role

### Environment Summary

azure-cli                         2.53.0 *

core                              2.53.0 *
telemetry                          1.1.0

Extensions:
application-insights              0.1.16
kusto                              0.5.0
log-analytics-solution               0.1.1
ml                                2.21.1
storage-blob-preview               0.7.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/shawn/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.10/site-packages/azure-cli-extensions'

Python (Linux) 3.10.10 (main, Sep 20 2023, 06:08:04) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'

**Comment by yonzhan** [comment] 2024-10-09 19:44
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-10-10 02:47
Duplicate of https://github.com/Azure/azure-cli/issues/12027. Please see the comment at https://github.com/Azure/azure-cli/issues/12027#issuecomment-618901218.

**Closed by jiasli** 2024-10-10 02:47 UTC
Labels: question, RBAC, customer-reported, Upgrade, Auto-Assign, Azure CLI Team, Auto-Resolve, Similar-Issue
