### ISSUE TITLE
kubectl command throws error of multiple login attempts with adm account

### ISSUE THREAD

**Issue by smb168** [Azure/azure-cli#26908] opened 2023-07-17 08:37 UTC
### Describe the bug

 kubectl get nodes
Error: failed to get token: expected an empty error but received: AzureCLICredential: ERROR: Found multiple accounts with the same username 'ADMSMB168@crb.apmoller.net': [{'home_account_id': '2928daae-8596-412a-8643-69b41bb91af4.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': '2928daae-8596-412a-8643-69b41bb91af4', 'realm': 'organizations'}, {'home_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b', 'realm': 'organizations'}]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

E0717 14:02:39.125035   76076 memcache.go:238] couldn't get current server API group list: Get "https://mcom-np-west-1-3e48d23c.hcp.westeurope.azmk8s.io:443/api?timeout=32s": getting credentials: exec: executable kubelogin failed with exit code 1
Error: failed to get token: expected an empty error but received: AzureCLICredential: ERROR: Found multiple accounts with the same username 'ADMSMB168@crb.apmoller.net': [{'home_account_id': '2928daae-8596-412a-8643-69b41bb91af4.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': '2928daae-8596-412a-8643-69b41bb91af4', 'realm': 'organizations'}, {'home_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b', 'realm': 'organizations'}]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

E0717 14:02:39.869936   76076 memcache.go:238] couldn't get current server API group list: Get "https://mcom-np-west-1-3e48d23c.hcp.westeurope.azmk8s.io:443/api?timeout=32s": getting credentials: exec: executable kubelogin failed with exit code 1
Error: failed to get token: expected an empty error but received: AzureCLICredential: ERROR: Found multiple accounts with the same username 'ADMSMB168@crb.apmoller.net': [{'home_account_id': '2928daae-8596-412a-8643-69b41bb91af4.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': '2928daae-8596-412a-8643-69b41bb91af4', 'realm': 'organizations'}, {'home_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b', 'realm': 'organizations'}]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

E0717 14:02:40.633533   76076 memcache.go:238] couldn't get current server API group list: Get "https://mcom-np-west-1-3e48d23c.hcp.westeurope.azmk8s.io:443/api?timeout=32s": getting credentials: exec: executable kubelogin failed with exit code 1
Error: failed to get token: expected an empty error but received: AzureCLICredential: ERROR: Found multiple accounts with the same username 'ADMSMB168@crb.apmoller.net': [{'home_account_id': '2928daae-8596-412a-8643-69b41bb91af4.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': '2928daae-8596-412a-8643-69b41bb91af4', 'realm': 'organizations'}, {'home_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b', 'realm': 'organizations'}]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

Unable to connect to the server: getting credentials: exec: executable kubelogin failed with exit code 1

### Related command

kubectl get nodes

### Errors

Error: failed to get token: expected an empty error but received: AzureCLICredential: ERROR: Found multiple accounts with the same username 'ADMSMB168@crb.apmoller.net': [{'home_account_id': '2928daae-8596-412a-8643-69b41bb91af4.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': '2928daae-8596-412a-8643-69b41bb91af4', 'realm': 'organizations'}, {'home_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b', 'realm': 'organizations'}]

### Issue script & Debug output

NA

### Expected behavior

Kubectl commands should work without error

### Environment Summary

kubectl version --client                
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7

**Comment by yonzhan** [comment] 2023-07-17 08:37
Thank you for opening this issue, we will look into it.

**Comment by smb168** [comment] 2023-07-17 08:48
FYI.. same issue is happening even with az login command ..

az login                                                                                                                                                    
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Found multiple accounts with the same username 'ADMSMB168@crb.apmoller.net': [{'home_account_id': '2928daae-8596-412a-8643-69b41bb91af4.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': '2928daae-8596-412a-8643-69b41bb91af4', 'realm': 'organizations'}, {'home_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b.05d75c05-fa1a-42e7-9cf1-eb416c396f2d', 'environment': 'login.microsoftonline.com', 'username': 'ADMSMB168@crb.apmoller.net', 'authority_type': 'MSSTS', 'local_account_id': 'b3828a34-c649-49c8-bfd4-59ca38a9302b', 'realm': 'organizations'}]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

**Comment by jiasli** [comment] 2023-07-18 03:25
Duplicate of #20168

**Closed by jiasli** 2023-07-18 03:25 UTC
Labels: bug, customer-reported, Azure CLI Team
