### ISSUE TITLE
Error while subscribing to a custom topic

### ISSUE THREAD

**Issue by frahugo** [Azure/azure-cli#16231] opened 2020-12-10 15:51 UTC
I'm following the quickstart guide (https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart) and ended up with this error when subscribing to the custom topic.

## Describe the bug

**Command Name**
`az eventgrid event-subscription create`

**Errors:**
```
'subscription-id'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 710, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrest/service_client.py, ln 108, in _request
    request = ClientRequest(method, self.format_url(url))
python3.6/site-packages/msrest/service_client.py, ln 151, in format_url
    url = url.format(**kwargs)
KeyError: 'subscription-id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az eventgrid event-subscription create --source-resource-id {} --name {} --endpoint {}`

## Environment Summary
```
Linux-4.15.0-1100-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.16.0

Extensions:
ai-examples 0.2.5

```

**Comment by yungezz** [comment] 2020-12-11 02:28
route to appropriate team

**Comment by jfggdl** [comment] 2020-12-11 04:34
@frahugo, Thank you for reporting this issue. We will be investigating what is the root cause.

**Comment by ahamad-MS** [comment] 2020-12-11 05:36
Hello @frahugo .. Thanks for reaching out and reporting this issue.

I Am not able to repro the issue described here. Can you please provide us with the following info:

1. Is this failure is encountered while running locally or when using shell.azure.com?
2. Can you please provide us with the az version. For example, here is the az version in my shell.azure.com account:

ashraf@Azure:~$ az version
{
  "azure-cli": "2.16.0",
  "azure-cli-core": "2.16.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5"
  }
}
ashraf@Azure:~$

3. Is you are running any eventgrid cli extension, can you please remove them and either use shell.azure.com or install latest cli module on your local machine?

4. here is an example of how the command look like and expected output from my shell.azure.com:

ashraf@Azure:~$ az eventgrid event-subscription create --source-resource-id /subscriptions/XYZ/resourceGroups/ABC/providers/microsoft.eventgrid/topics/HIJ --name OPQRST --endpoint https://ww.example.com

If the provided endpoint does not support subscription validation handshake, navigate to the validation URL that you receive in the subscription validation event, in order to complete the event subscription creation or update. For more details, please visit http://aka.ms/esvalidation

Thanks

**Comment by ahamad-MS** [comment] 2020-12-21 22:26
Hello @frahugo frahugo  .. Please let us know if you are still having any issue. We are closing this issue as not repro and we think we addressed your concern. If you feel otherwise, or still have a repro even with our instructions, please reactivate. thanks

**Closed by ahamad-MS** 2020-12-21 22:26 UTC
Labels: Event Grid, Service Attention, customer-response-expected, question
