### ISSUE TITLE
az aks list returns bad json

### ISSUE THREAD

**Issue by woodsaj** [Azure/azure-cli#7314] opened 2018-09-13 16:57 UTC
**Describe the bug**
The json returned by `az aks list` cant be parsed due to bad json (unescaped "\n" in strings)

**To Reproduce**
When creating an aks cluster, add a newline to the end of an SSH publickey.
Then run `az aks list` and try and parse the json response.eg
```
az aks list | jq -r '.[] | .name'
```
you will get an error like
```
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 27, column 1
```
The bad data in the json response from the az aks list command looks like
```
        "publicKeys": [
          {
            "keyData": "<REDACTED>\n"
          }
````

**Expected behavior**
Json response to be valid

**Environment summary**
installed via apt-get from official repo.
azure-cli (2.0.45)

**Comment by brendandburns** [comment] 2018-09-14 04:16
Hrm, this works as expected for me for my cluster. Do your cluster names have unicode in them?

**Comment by woodsaj** [comment] 2018-09-14 09:44
No, Unicode is not used.

As explained in the post above.  The issue is due to a newline "\n" in a public key not being correctly escaped.

The json response returned included
```
"publicKeys": [
          {
            "keyData": "<REDACTED>\n"
          }
```
the "\n" at the end is not correctly escaped and so the json document cant be parsed.
Somewhere in the azure platform between the user inputing the key and azure cli creating the json document response, there is an encoding problem.

**Comment by weinong** [comment] 2018-09-19 16:55
@woodsaj mine has `\n` at the end and `az aks show` returned just fine.
can you send your cluster info like subID, rg, cluster name and reference to this issue to aks-help @ service.microsoft.com for us to take a look?

**Comment by mboersma** [comment] 2019-01-05 01:39
I tried this as described and can't reproduce any error with `az` CLI 2.0.52. @tjprescott let's close this issue.

**Closed** 2019-01-07 17:35 UTC
Labels: AKS, Question, Service Attention

**Comment by kshillingstad** [comment] 2023-01-03 19:27
I am also getting invalid JSON from the azure-cli when running the following. 

```
az extension add --upgrade --name aks-preview
az feature register --name AKS-KedaPreview --namespace Microsoft.ContainerService
az provider register -n Microsoft.ContainerService
az provider register -n Microsoft.OperationalInsights

# create cluster
CLUSTER_CREATE_RESULTS=$(az aks create -g ${RESOURCE_GROUP_NAME} -n ${CLUSTER_NAME} \
    --attach-acr $CONTAINER_REGISTRY_NAME \
    --network-plugin azure \
    --node-count 3 \
    --enable-cluster-autoscaler \
        --min-count 3 \
        --max-count 6 \
    --enable-oidc-issuer \
    --enable-managed-identity \
    --enable-msi-auth-for-monitoring \
    --enable-keda \
    --enable-addons monitoring,azure-policy,azure-keyvault-secrets-provider,ingress-appgw \
    --appgw-name "$APPLICATION_GATEWAY_NAME" \
    --appgw-subnet-cidr "$APPLICATION_GATEWAY_CIDR" \
    --generate-ssh-keys)
echo $CLUSTER_CREATE_RESULTS | bin/$(bin/helpers/get_os.sh)/jq .
```
error message
`parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 1`
My environment is as follows. 
```
az --version
azure-cli                         2.43.0

core                              2.43.0
telemetry                          1.0.8

Extensions:
aks-preview                      0.5.121
application-insights              0.1.16
account                            0.2.5

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1
```
Would it be best for me to create a new issue or can this issue be reopened?
