### ISSUE TITLE
NOT idempotent

### ISSUE THREAD

**Issue by toddplu** [Azure/azure-cli#11729] opened 2019-12-31 16:33 UTC
Reference: https://github.com/Azure/azure-cli/issues/10673
az storage account network-rule add is not idempotent; subsequent invocations result in:

Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id(unique). For more information, see - https://aka.ms/storagenetworkruleset

In the spirit of https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac52f120-deaa-0a12-3663-8bf51cbbd234
* Version Independent ID: b7e2694c-c7be-8d1f-da00-fdd8b60f327e
* Content: [az storage account network-rule](https://docs.microsoft.com/en-us/cli/azure/storage/account/network-rule?view=azure-cli-latest#az-storage-account-network-rule-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bim-msft** [comment] 2020-01-01 13:14
@Juliehzl Please take a look.

**Comment by Juliehzl** [comment] 2020-01-01 14:30
dupe of #10673

**Comment by Juliehzl** [comment] 2020-01-01 14:33
Hi @toddplu , can you provide more debug information with `--debug` in your command?

**Comment by yonzhan** [comment] 2020-02-02 01:30
@toddplu any update?

**Comment by michaelsync** [comment] 2020-02-25 05:15
Same issue. It said, "This is a bug in Azure CLI and we will fix it."
https://github.com/Azure/azure-cli/issues/10673

**Comment by yonzhan** [comment] 2020-02-25 10:24
@toddplu any update?

**Comment by Juliehzl** [comment] 2020-03-12 03:26
It is already fixed in PR https://github.com/Azure/azure-cli/pull/12327.
Please try with new azure cli version.

**Closed by Juliehzl** 2020-03-12 03:26 UTC
Labels: OKR3.2 Candidate, Storage
