### ISSUE TITLE
500 Server Error when creating Encryption scope for Storage account with UserAssigned identity

### ISSUE THREAD

**Issue by jango-free** [Azure/azure-cli#22157] opened 2022-04-22 13:02 UTC
**Describe the bug**
While trying to create encryption scope with UserAssigned identity enabled Storage account, we are facing 500 server error.

**To Reproduce**
```
keyvault_name=<some_exisiting keyvault>

# URL to key uploaded to Keyvault in advance
keyvault_key_url=https://${keyvault_name}.vault.azure.net/keys/888

storacc=<any_valid_storacc_name>

rg=<resource_group_name> # existing resource group
region=germanywestcentral # region of resource group

identity_name=testidentity

# Creating access policy
az identity create --name $identity_name --resource-group $rg
identity_resource_id=`az identity show --name $identity_name --resource-group $rg | jq -r .id`
identity_client_id=`az identity show --name $identity_name --resource-group $rg | jq -r .clientId`

# Setting access policy for Managed Identity
az keyvault set-policy --key-permissions get unwrapKey wrapKey --object-id $identity_client_id \
    --name $keyvault_name

# Creating Managed identity enabled storage account
az storage account create -n $storacc -g $rg -l $region --sku Standard_LRS \
    --identity-type UserAssigned \
    --user-identity-id $identity_resource_id

# Trying to create Encryption scope
az storage account encryption-scope create --name testencrscope \
                                           --account-name $storacc  \
                                           --key-source Microsoft.KeyVault \
                                           --key-uri $keyvault_key_url \
                                           --require-infrastructure-encryption false \
                                           --resource-group $rg

(UnexpectedException) The server was unable to complete your request.
Code: UnexpectedException
Message: The server was unable to complete your request.
```

If use Azure CLI cli with `--debug` argument for the last command, output shows "500 Server Error", so we assume that there are issues on Azure side with creation of encryption scope.

**Expected behavior**
Successfully created encryption scope

**Environment summary**
Commands are running in Azure Cloud Shell
```
az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "ssh": "1.0.1"
  }
}
```

**Comment by yonzhan** [comment] 2022-04-22 14:08
keyvault

**Comment by evelyn-ys** [comment] 2022-04-24 01:57
Need storage server side to investigate

**Comment by navba-MSFT** [comment] 2022-04-25 05:11
@jango-free Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. Could you please refer **[**this**](https://docs.microsoft.com/en-us/azure/storage/common/customer-managed-keys-configure-key-vault?tabs=powershell#configure-a-key-vault)** article and then run the PS commands mentioned there in order and check if you still see the same issue ?

If you encounter the same issue, please run **$DebugPreference="Continue"** before your PS commands and then share the complete output with failing error along with the failing Server Request ID and the time of the issue in UTC. Awaiting your reply.

**Comment by jango-free** [comment] 2022-04-25 09:54
Sure. Here commands I run

```
$keyVaultName = "CustomerKeyKV"
$rg = <resource_group_name> # existing resource group
$region = "germanywestcentral" # region of resource group

# Creating Keyvault
$keyVault = New-AzKeyVault -Name $keyVaultName `
    -ResourceGroupName $rg `
    -Location $region `
    -EnablePurgeProtection

$keyName = "rsa-key"

# Adding key
$key = Add-AzKeyVaultKey -VaultName $keyVault.VaultName `
    -Name $keyName `
    -Destination 'Software'

$existingIdentity = "testidentity"

Import-Module Az.ManagedServiceIdentity
$userIdentityId = Get-AzUserAssignedIdentity -Name $existingIdentity -ResourceGroupName $rg
$principalId = $userIdentityId.PrincipalId

Set-AzKeyVaultAccessPolicy `
    -VaultName $keyVault.VaultName `
    -ObjectId $principalId `
    -PermissionsToKeys wrapkey,unwrapkey,get

$storaccName = "checkencrccopes"
New-AzStorageAccount -ResourceGroupName $rg `
    -Name $storaccName `
    -Kind StorageV2 `
    -SkuName Standard_LRS `
    -Location $region `
    -IdentityType SystemAssignedUserAssigned `
    -UserAssignedIdentityId $userIdentityId.Id

New-AzStorageEncryptionScope -ResourceGroupName $rg -AccountName $storaccName `
    -EncryptionScopeName testscope -KeyvaultEncryption -KeyUri $key.Id
```

Error after execution of the last command
`New-AzStorageEncryptionScope: Operation returned an invalid status code 'BadRequest'`

Gist to debug output of the same command
https://gist.github.com/jango-free/d455a4a3aedab926d66eb1f02f0e5239

Just to verify I also granted all keys permissions to Managed identity in Keyvault access policy. Same result

**Comment by navba-MSFT** [comment] 2022-04-26 07:30
@jango-free Thanks for getting back. I am able to reproduce this issue. I am working with the Product Owners for the fix to be released. In the meantime, If you would like a quick workaround, you can use the [System Managed Identity](https://docs.microsoft.com/en-us/azure/storage/common/customer-managed-keys-configure-key-vault?tabs=portal#use-a-system-assigned-managed-identity-to-authorize-access) instead. I will provide you an update once I hear back from the Product owners. Please let me know if you have any queries.

**Comment by jango-free** [comment] 2022-04-26 07:46
Unfortunately System Managed Identity doesn't work for us. We have large amount of storage accounts, which should have encryption scopes secured by personal Key Vault key. System Managed Identity creates Azure AD app per storage account after creating encryption scope, while with UserAssigned we have Managed Identity created in advance and could easily programmatically control this.

**Comment by navba-MSFT** [comment] 2022-04-26 07:49
@jango-free Thanks for getting back. I will keep you posted about the fix for the User Managed Identity then. I don't have any ETA as of now on when the fix will be released for your Storage tenant. I will update this github thread once I hear from the Product Group team. Sorry for the inconvenience.

**Comment by navba-MSFT** [comment] 2022-04-27 03:58
@jango-free I have heard back from the Product Group team and This issue would require an in-depth troubleshooting. Could you please open up a support ticket and we would be happy to take this forward and work closely with you ? Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-04-28 06:13
@jango-free Thanks for getting back. Please paste the Support Ticket # here. So that I can give the context and share my findings with the Support professional to speed up the resolution.

**Comment by jango-free** [comment] 2022-04-28 07:34
Support request number 2204270050002231

**Comment by navba-MSFT** [comment] 2022-04-29 04:05
@jango-free I have given the background of this issue to the Support Professional who is working on that issue. Also we have reached out to the product Group team to look into this issue on priority. Our support engineer will work closely with you further on this and share the update.

**Comment by navba-MSFT** [comment] 2022-05-02 03:21
@jango-free Since this issue is now troubleshooted over support ticket, I am proceeding with the archival of this github thread. Please follow-up with the support professional for the next set of action plan. If you don't get any traction on the support ticket, Please feel free to let me know. I will get the support ticket prioritized.

**Closed by navba-MSFT** 2022-05-02 03:21 UTC
Labels: bug, Storage, KeyVault, customer-reported, needs-team-attention, CXP Attention, Auto-Assign
