### ISSUE TITLE
az group list and az group list --subscription does not work

### ISSUE THREAD

**Issue by ranjitk99** [Azure/azure-cli#10631] opened 2019-09-25 05:10 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az group list and az group list --subscription does not work with latest cli
Error-
AADSTS9002313: Invalid request. Request is malformed or invalid.
Trace ID: 5da7935b-d53a-4924-a6c7-b751628c1000
Correlation ID: c9be7f6d-ee6e-46f7-83bf-68a53a3b0403
Timestamp: 2019-09-25 05:09:54Z

**To Reproduce**
1. Install latest cli
2. az login
3. az group list
**Expected behavior**
List all resource groups in the subscription
**Environment summary**
Installation of CLI method used: Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
**Additional context**

**Comment by Juliehzl** [comment] 2019-09-26 02:04
Hi @ranjitk99, I cannot reproduce your issue with azure cli 2.0.74 in my computer. Can you show me more information with `--debug` appended your original command and give me a more detailed description for your error scenario?

**Comment by ranjitk99** [comment] 2019-09-26 02:24
Well, I cannot reproduce now as well. Please find the screenshot from yesterdays which shows the error below.
1. I think if you have 0 resource groups in all of your subscriptions it will show. I was having 4 resource groups in one of subscription and I deleted 2 days back and when I run command yesterday it has given that error which i shown. Now it is giving different message showing "[]" which I think it is correct. 
2. Also I assume you may check the logs with the corresponding correlation id, trace id and timstamp from the error.

![image](https://user-images.githubusercontent.com/45135508/65653319-a61f4b00-dfc9-11e9-9ea5-9425aa5d48f3.png)

![image](https://user-images.githubusercontent.com/45135508/65653345-bcc5a200-dfc9-11e9-80e2-77336d544d15.png)

**Comment by yonzhan** [comment] 2020-05-03 03:50
add to S170

**Comment by zhoxing-ms** [comment] 2020-05-15 09:14
@ranjitk99 Sorry, because this problem occurred so early, so there is no clue for investigation any more. I can't reproduce this problem on my side, can you reproduce the problem?

**Comment by zhoxing-ms** [comment] 2020-05-25 01:48
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-05-25 01:48 UTC
Labels: ARM, OKR3.4 Candidate
