### ISSUE TITLE
MSI Installer doesn't download - Network error

### ISSUE THREAD

**Issue by vinnytheviking** [Azure/azure-cli#5674] opened 2018-02-27 06:26 UTC
I'm trying to download and install CLI using the msi file. 

When I try and download the msi it fails with a network error.

I've tried edge and chrome and both failed. also tried 'save as' option and that didn't work

**Comment by polys** [comment] 2018-02-28 14:39
Same here; tried with Chrome, Firefox, Edge and IE.

**Comment by derekbekoe** [comment] 2018-02-28 17:05
Same as https://github.com/Azure/azure-docs-cli-python/issues/607

Are you behind a proxy? Also, what version of windows are you running? Is some security scanner blocking the download?

**Comment by polys** [comment] 2018-02-28 17:27
I'm running Windows 10 Enterprise (10.0.16299.125) behind a proxy. I tried bypassing the proxy though and didn't seem to make a difference.

I was able to download it through a debian-based docker container though:
```powershell
docker run -it --rm -v ${PWD}:/tmp -w /tmp buildpack-deps:curl wget https://azurecliprod.blob.core.windows.net/msi/azure-cli-latest.msi
```
Interestingly, when I tried the same with an alpine-based container (replace `buildpack-deps:curl` with `alpine`), it did download but gave these errors as well:
```
wget: got bad TLS record (len:0) while expecting handshake record
wget: error getting response: Connection reset by peer
```

**Comment by derekbekoe** [comment] 2018-02-28 22:01
As a workaround, for the 2.0.28 release, I've added the MSI to our GitHub release page.
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.28
Download link: https://github.com/Azure/azure-cli/releases/download/azure-cli-2.0.28/azure-cli-2.0.28.msi

Let me know if you still have issues with that download. I would be interested to know either way.
note: right now, there's no guarantee that we'll publish future releases to GitHub also.

**Comment by polys** [comment] 2018-03-01 09:29
Yeah, this link works perfectly. It's significantly faster as well.

**Comment by vinnytheviking** [comment] 2018-03-07 19:54
That link works for me too

**Comment by polys** [comment] 2018-03-15 13:34
Just downloaded v2.0.29 from the website successfully.
Looks like the https://aka.ms/installazurecliwindows link works.

**Comment by derekbekoe** [comment] 2018-03-15 16:43
Yes we made some changes that should resolve this.
Closing.

**Closed by derekbekoe** 2018-03-15 16:43 UTC
Labels: Packaging/WindowsMSI

**Comment by JJ** [comment] 2018-06-06 16:06
The problem is that Alpine has a `wget` clone which is actually an alias for their all-purpose shell, `busybox`. It works almost the same, but not quite. You can, however, add the real one with apk add wget.
