### ISSUE TITLE
Can't install Azure CLI ML extension - Failed to delete 'C:\Users\xxx\.azure\cliextensions\ml': [WinError 3] The system cannot find the path specified: 'C:\\Users\\xxx\\.azure\\cliextensions\\ml'.

### ISSUE THREAD

**Issue by dr-dolittle** [Azure/azure-cli#22089] opened 2022-04-18 07:42 UTC
**Describe the bug**
I can successfully install the Azure CLI ML extension v1 via `az extension add --name azure-cli-ml`.

If I try the same (and `azure-cli-ml` is not installed) for `az extension add --name ml` I get `Failed to delete 'C:\Users\xxx\.azure\cliextensions\ml': [WinError 3] The system cannot find the path specified: 'C:\\Users\\xxx\\.azure\\cliextensions\\ml'`

**To Reproduce**
Install ML extension via `az extension add --name ml`

**Expected behavior**
The extension is being installed.

**Environment summary**
Windows 11
Python: 3.10.4
Azure CLI: 2.35.0

**Comment by yonzhan** [comment] 2022-04-18 08:33
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-04-18 10:35
@dr-dolittle Thank you for reaching out to us, we are looking into it.

**Comment by harrysummer** [comment] 2022-04-18 20:30
I am having the same issue here. Here is the error log after adding `--debug` flag:
```
ERROR: Cannot install ml because these package versions have conflicting dependencies.

The conflict is caused by:
    docker 5.0.3 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.2 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.1 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.0 depends on pywin32==227; sys_platform == "win32"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Exception information:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 385, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('pywin32==227; sys_platform == "win32"'), parent=LinkCandidate('https://files.pythonhosted.org/packages/54/f3/7af47ead249fbb798d64a0438bad5c26f17ef6ac5cd324d802038eb10d90/docker-5.0.3-py2.py3-none-any.whl#sha256=7a79bb439e3df59d0a72621775d600bc8bc8b422d285824cb37103eab91d1ce0 (from https://pypi.org/simple/docker/) (requires-python:>=3.6)')), RequirementInformation(requirement=SpecifierRequirement('pywin32==227; sys_platform == "win32"'), parent=LinkCandidate('https://files.pythonhosted.org/packages/59/86/b2430d652d082a2132bbd6023b3f298d0582977c27f125c7e3875c65e178/docker-5.0.2-py2.py3-none-any.whl#sha256=9b17f0723d83c1f3418d2aa17bf90b24dbe97deda06208dd4262fa30a6ee87eb (from https://pypi.org/simple/docker/) (requires-python:>=3.6)')), RequirementInformation(requirement=SpecifierRequirement('pywin32==227; sys_platform == "win32"'), parent=LinkCandidate('https://files.pythonhosted.org/packages/0f/f6/7bffaae55542f5317d292f95171a65d535ac26eaf4de65f2c539d680a93d/docker-5.0.1-py2.py3-none-any.whl#sha256=b88eef725b33c0ed59c67506631bbb09b480b7ca5a739bbbb948b446443fe914 (from https://pypi.org/simple/docker/) (requires-python:>=3.6)')), RequirementInformation(requirement=SpecifierRequirement('pywin32==227; sys_platform == "win32"'), parent=LinkCandidate('https://files.pythonhosted.org/packages/b2/5a/f988909dfed18c1ac42ad8d9e611e6c5657e270aa6eb68559985dbb69c13/docker-5.0.0-py2.py3-none-any.whl#sha256=fc961d622160e8021c10d1bcabc388c57d55fb1f917175afbe24af442e6879bd (from https://pypi.org/simple/docker/) (requires-python:>=3.6)'))]
```

**Comment by diondrapeck** [comment] 2022-04-18 22:31
Note that Python 3.9+ is not supported for this release. However, we have also reproduced this with 3.8 which should be supported. We're still working to find the root cause, but in the meantime you can workaround this by creating a Python 3.7 environment and installing inside there.

1. conda create -n cli_v2 python=3.7
2. conda activate cli_v2
3. pip install azure-cli
4. az extension add -n ml

**Comment by diondrapeck** [comment] 2022-04-19 00:12
Supporting Python 3.10 (and therefore aligning with Azure CLI) is in the works for upcoming releases.

**Comment by harrysummer** [comment] 2022-04-19 20:16
> Note that Python 3.9+ is not supported for any of the existing v2 CLI releases, so this installation failure is expected behavior.
> 
> You can get a working installation by creating a Python 3.6, 3.7 or 3.8 environment and installing inside there.
> 
> 1. conda create -n cli_v2 python=3.7 # or 3.8 or 3.6
> 2. conda activate cli_v2
> 3. pip install azure-cli
> 4. az extension add -n ml

Thanks for the workaround, @diondrapeck ! It would be great if the Azure CLI could run functional test for the official extensions before updating the Python version.

**Comment by RakeshMohanMSFT** [comment] 2022-04-20 03:40
@dr-dolittle Let us know if the work around provided helped you fix your problem.

**Comment by dr-dolittle** [comment] 2022-04-21 05:34
> 4\. az extension add -n ml

I uninstalled Python 3.10. und installed 3.8 and can now successfully install the ml extension.

**Comment by RakeshMohanMSFT** [comment] 2022-04-21 05:46
@dr-dolittle Glad to hear that the issue is resolved. I will close the issue.

**Closed by RakeshMohanMSFT** 2022-04-21 05:46 UTC
Labels: Machine Learning, Installation, needs-team-attention, CXP Attention, Auto-Assign
