### ISSUE TITLE
Can't login with az cli. Tested from Windows 11 and Ubuntu, and two different Azure tenants

### ISSUE THREAD

**Issue by heintonny** [Azure/azure-cli#21164] opened 2022-02-01 14:00 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1643720364.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/2d3a1c6d-3a10-4c61-87f6-8eba54f91a3e/v2.0",
  "iat": 1643723664,
  "nbf": 1643723664,
  "exp": 1643727564,
  "aio": "AWQAm/8TAAAA2sO1FZ81/mIgOv/fhuBBuY2xgCGW5rff626uu0UX5twrPZHjxUP66A2IPpzfnjZCej8pO0K6T0yQjLkUl+cah3SUu8Er8NhjJM0R9ua+Dn6Z61t4M+pPp1RT8f3ogVK7",
  "name": "Global Admin",
  "nonce": "a7527f12911b7d60f518ed1a22acd4066f6b307bd82038afd8f35ad953e50e15",
  "oid": "db4f5808-4b85-4a81-9d0f-1bf03403e620",
  "preferred_username": "admin@blinqservicesdev.onmicrosoft.com",
  "puid": "10032001289D8924",
  "rh": "0.AYIAbRw6LRA6YUyH9o66VPkaPpV3sATbjRpGu-4C-eG_e0aCAAY.",
  "sub": "kKaOsycuQLovxiSndWqoKKJkRQJvvZAAoOF1V7x_3N8",
  "tid": "2d3a1c6d-3a10-4c61-87f6-8eba54f91a3e",
  "uti": "n-h0j-_nAk-3n8YpMKGUAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 171, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1643720364.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/2d3a1c6d-3a10-4c61-87f6-8eba54f91a3e/v2.0",
  "iat": 1643723664,
  "nbf": 1643723664,
  "exp": 1643727564,
  "aio": "AWQAm/8TAAAA2sO1FZ81/mIgOv/fhuBBuY2xgCGW5rff626uu0UX5twrPZHjxUP66A2IPpzfnjZCej8pO0K6T0yQjLkUl+cah3SUu8Er8NhjJM0R9ua+Dn6Z61t4M+pPp1RT8f3ogVK7",
  "name": "Global Admin",
  "nonce": "a7527f12911b7d60f518ed1a22acd4066f6b307bd82038afd8f35ad953e50e15",
  "oid": "db4f5808-4b85-4a81-9d0f-1bf03403e620",
  "preferred_username": "admin@blinqservicesdev.onmicrosoft.com",
  "puid": "10032001289D8924",
  "rh": "0.AYIAbRw6LRA6YUyH9o66VPkaPpV3sATbjRpGu-4C-eG_e0aCAAY.",
  "sub": "kKaOsycuQLovxiSndWqoKKJkRQJvvZAAoOF1V7x_3N8",
  "tid": "2d3a1c6d-3a10-4c61-87f6-8eba54f91a3e",
  "uti": "n-h0j-_nAk-3n8YpMKGUAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: 

azure-cli 2.32.0

Extensions:
account 0.2.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-02-02 01:22
@Jiasli for awareness

**Comment by jiasli** [comment] 2022-02-07 06:21
Duplicate of #20388

**Closed by jiasli** 2022-02-07 06:21 UTC
Labels: Account, customer-reported
