### ISSUE TITLE
login is not working as expected.

### ISSUE THREAD

**Issue by hem1999** [Azure/azure-cli#21268] opened 2022-02-12 11:33 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1644645762.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/00f9cda3-075e-44e5-aa0b-aba3add6539f/v2.0",
  "iat": 1644665262,
  "nbf": 1644665262,
  "exp": 1644669162,
  "aio": "AUQAu/8TAAAAhsx87kLbdquSpnPYaYSym8QBacXPdg43b6S9BF9mhOZM13h3f38lvypPUQ+9Ci/IYNtQFq4VNc+4dnIy8oqsYA==",

  "nonce": "b06c5e2cb7f774fe3a988e6d0bea712e52f865beab33d6fcd0752be5ddb4e85a",
  "oid": "902250dc-f942-47c5-b622-40bcd9646f5d",

  "puid": "100320008DC6418A",
  "rh": "0.AXIAo835AF4H5USqC6ujrdZTn5V3sATbjRpGu-4C-eG_e0ZyABY.",
  "sub": "x32-tG5l8BXYDbu0ldyIJYEOZbnN9yZwj6Spu4Y68Yo",
  "tid": "00f9cda3-075e-44e5-aa0b-aba3add6539f",
  "uti": "h0bxiUkaa0WolHCtp4QlAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 171, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1644645762.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/00f9cda3-075e-44e5-aa0b-aba3add6539f/v2.0",
  "iat": 1644665262,
  "nbf": 1644665262,
  "exp": 1644669162,
  "aio": "AUQAu/8TAAAAhsx87kLbdquSpnPYaYSym8QBacXPdg43b6S9BF9mhOZM13h3f38lvypPUQ+9Ci/IYNtQFq4VNc+4dnIy8oqsYA==",

  "nonce": "b06c5e2cb7f774fe3a988e6d0bea712e52f865beab33d6fcd0752be5ddb4e85a",
  "oid": "902250dc-f942-47c5-b622-40bcd9646f5d",
  "preferred_username": "cb.en.u4cse17624@cb.students.amrita.edu",
  "puid": "100320008DC6418A",
  "rh": "0.AXIAo835AF4H5USqC6ujrdZTn5V3sATbjRpGu-4C-eG_e0ZyABY.",
  "sub": "x32-tG5l8BXYDbu0ldyIJYEOZbnN9yZwj6Spu4Y68Yo",
  "tid": "00f9cda3-075e-44e5-aa0b-aba3add6539f",
  "uti": "h0bxiUkaa0WolHCtp4QlAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.0
```

**Comment by yonzhan** [comment] 2022-02-13 01:02
@jiasli for awareness

**Comment by jiasli** [comment] 2022-02-14 03:36
Duplicate of #20388

**Closed by jiasli** 2022-02-14 03:36 UTC
Labels: Account, customer-reported
