### ISSUE TITLE
fail to login in AzureUSGovernment

### ISSUE THREAD

**Issue by MayXuQQ** [Azure/azure-cli#23575] opened 2022-08-18 08:08 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1660809177.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.us/259714ad-a323-4da0-bb68-d38a0dba0eea/v2.0",
  "iat": 1660809511,
  "nbf": 1660809511,
  "exp": 1660813411,
  "aio": "ATQAy/8JAAAAqkFMhaZDZPgpf5miXCIzESmgIhpwbxCZoEY0N91+u2dGTtTsWWnelZ5v+pTdxUss",
  "name": "May Xu",
  "oid": "e3ee4119-4381-469f-8c2e-4a8ac6d65917",
  "preferred_username": "maxu@pntcloudops.onmicrosoft.us",
  "puid": "10032918BE65B3CE",
  "rh": "0.AAAArRSXJSOjoE27aNOKDboO6pV3sATbjRpGu-4C-eG_e0YCACs.",
  "sub": "34xgcTROyVfcKiHQQECFSeWDXe9WDoTgbHXjNotKS7w",
  "tid": "259714ad-a323-4da0-bb68-d38a0dba0eea",
  "uti": "u45QgTgvFU68H67zk6moAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 148, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 152, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 1681, in acquire_token_by_device_flow
    **kwargs))
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 384, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 347, in _obtain_token_by_device_flow
    self.DEVICE_FLOW["GRANT_TYPE"], data=data, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 795, in _obtain_token
    "response": _resp, "params": params, "data": _data,
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 600, in <lambda>
    event, environment=authority.instance)),
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/token_cache.py", line 310, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/token_cache.py", line 154, in __add
    if id_token
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 78, in decode_id_token
    err, _now, json.dumps(decoded, indent=2)))
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1660809177.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.us/259714ad-a323-4da0-bb68-d38a0dba0eea/v2.0",
  "iat": 1660809511,
  "nbf": 1660809511,
  "exp": 1660813411,
  "aio": "ATQAy/8JAAAAqkFMhaZDZPgpf5miXCIzESmgIhpwbxCZoEY0N91+u2dGTtTsWWnelZ5v+pTdxUss",
  "name": "May Xu",
  "oid": "e3ee4119-4381-469f-8c2e-4a8ac6d65917",
  "preferred_username": "maxu@pntcloudops.onmicrosoft.us",
  "puid": "10032918BE65B3CE",
  "rh": "0.AAAArRSXJSOjoE27aNOKDboO6pV3sATbjRpGu-4C-eG_e0YCACs.",
  "sub": "34xgcTROyVfcKiHQQECFSeWDXe9WDoTgbHXjNotKS7w",
  "tid": "259714ad-a323-4da0-bb68-d38a0dba0eea",
  "uti": "u45QgTgvFU68H67zk6moAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.15.16-200.fc35.x86_64-x86_64-with-fedora-35-Thirty_Five, Fedora Linux 35 (Cloud Edition)
Python 3.6.15
Installer: RPM

azure-cli 2.37.0 *
```

**Comment by yonzhan** [comment] 2022-08-18 11:17
Duplicate of https://github.com/Azure/azure-cli/issues/20388

**Closed by yonzhan** 2022-08-18 11:17 UTC
Labels: Account, customer-reported, Auto-Assign
