### ISSUE TITLE
azure-cli command to launch kubernetes service web UI mgmt dashboard

### ISSUE THREAD

**Issue by myusrn** [Azure/azure-cli#8746] opened 2019-03-09 02:34 UTC
**Describe the bug**
I was following https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough which ends with a Next Steps section that takes you to details on how to Access the Kubernetes web dashboard [ in Azure Kubernetes Service (AKS) ].

Those instructions simply say to execute the following command: <br>
```az aks browse --resource-group KubernetesWork --name myks``` 

The output window produces the message ```unknown flag: --address``` followed by a bunch of red colored text, e.g. ```HTTPConnectionPool(host='localhost', port=8888)``` suggesting attempts to communicate with localhost:8888 port is failing. It also launches a browser window pointed at the url ```http://127.0.0.1:8001/``` that produces a can't reach this page result.
**&lt;<span style="color:red">03/14/19 status update</span>&gt; I upgraded from aka.ms/installazurecliwindows | azure-cli-2.0.59.msi to the current azure-cli-2.0.60.msi bits, digitally signed on 07mar19, and confirmed update with ```az --version``` check.  now when I run above noted command I know longer get the output window message error and ```http://127.0.0.1:8001/``` local browser instance launched url displays a web UI dashboard.  I also found that my single test environment setup vm cluster node had to be running for this to work otherwise 127.0.0.1:8001 would return page not found. ** 

**To Reproduce**
Follow steps in https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough and then the "Next Steps" | "Access the Kubernetes web dashboard [ in Azure Kubernetes Service (AKS) ]" instructions.

**Expected behavior**
console doesn't produce any errors and browser http://127.0.0.1:8001 page brings up azure kubernetes service web UI dashboard.

**Environment summary**
windows 10 april 2019 update version 18351.1 and https://aka.ms/installazurecliwindows | azure-cli.msi  version 2.0.59

**Additional context**

**Comment by icewhite** [comment] 2019-03-14 11:11
I'm seeing the same thing. I'm behind a corporate internet proxy. Wondering if that's the cause. @myusrn are you the same?

**Comment by myusrn** [comment] 2019-03-14 15:23
@icewhite I am not behind corporate internet http proxy or nat, i'm on home broadband network with typical broadbrand router nat in place.

**Comment by seanmck** [comment] 2019-12-14 01:15
Duplicate of #8642.

**Closed by seanmck** 2019-12-14 01:15 UTC
Labels: AKS, Needs Triage, Service Attention
