### ISSUE TITLE
az aks browse fails repeatedly

### ISSUE THREAD

**Issue by julianrubisch** [Azure/azure-cli#9842] opened 2019-07-02 13:22 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109d64470>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
python3.7/site-packages/urllib3/connection.py, ln 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
site-packages/urllib3/util/connection.py, ln 80, in create_connection
    raise err
...

python3.7/site-packages/requests/adapters.py, ln 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109d64470>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67

```

**Comment by yashghia** [comment] 2019-07-05 18:45
Facing similar error while trying `az aks browse` , here is the error stack trace. 

The command failed with an unexpected error. Here is the traceback:

HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnection
Error('<urllib3.connection.HTTPConnection object at 0x07438C50>: Failed to establish a new connection: [WinError 10061]
No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\urllib3\urllib3\connection.py", line 159, in _new_conn

  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\urllib3\urllib3\util\connection.py", line 80, in creat
e_connection
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\urllib3\urllib3\util\connection.py", line 70, in creat
e_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by ondrejhlavacek** [comment] 2019-07-12 10:18
+1 here, happens every few minutes, very annoying :-(

**Comment by seanmck** [comment] 2019-07-14 07:09
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:09 UTC
Labels: AKS, Bug
