### ISSUE TITLE
DNS import

### ISSUE THREAD

**Issue by hindocha85** [Azure/azure-cli#10423] opened 2019-09-04 14:44 UTC
## Describe the bug

**Command Name**
`az network dns zone import`

**Errors:**
```
[Errno 2] No such file or directory: 'inforblock_dns.csv'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/network/custom.py, ln 1406, in import_zone
    file_text = read_file_content(file_name)
azure/cli/core/util.py, ln 222, in read_file_content
    with codecs_open(file_path, encoding=encoding) as f:
az/lib/python3.6/codecs.py, ln 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'inforblock_dns.csv'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network dns zone import -g {} -n {} -f {}`

## Environment Summary
```
Linux-4.15.0-1055-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72

```

**Comment by MyronFanQiu** [comment] 2019-09-05 12:24
@hindocha85 Hello. Could you please run command with `--debug` to check the real path of the file? This `inforblock_dns.csv` should your personal file. This issue may be caused by relative path or wrong path.

**Comment by MyronFanQiu** [comment] 2020-02-18 07:34
@hindocha85 Hello. Do you still have such issue? If not, I will close this one.

**Comment by hindocha85** [comment] 2020-02-18 14:13
Yes still having issues

**Comment by yonzhan** [comment] 2020-02-18 23:17
add to S167.

**Comment by MyronFanQiu** [comment] 2020-02-19 02:12
@hindocha85 Hi. Can you run it with `--debug` and paste the error log?

**Comment by MyronFanQiu** [comment] 2020-04-13 07:11
@hindocha85 I exam the logic of this part, it's just a file loading process. I cannot reproduce this scenario. The most potential reason is that it's a wrong file path. I closed this issue since it's out of date and you use latest Azure CLI. If you still encounter this issue, feel free to open a new one.

**Closed by MyronFanQiu** 2020-04-13 07:11 UTC
Labels: Network, Network - DNS
