### ISSUE TITLE
[azcli 2.48.1] Warning messages are considered as errors

### ISSUE THREAD

**Issue by bcouavoux** [Azure/azure-cli#26330] opened 2023-05-04 09:24 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

All azcli commands that generate warnings

**Describe the bug**

Warning messages are considered as errors and fail all our pipelines with the failOnStandardError parameter set to true. In workaround, we are forced to go back over all our pipelines and set the parameter to false to resolve the problem. Already stated in this issue on version 2.45.0: https://github.com/Azure/azure-cli/issues/25406

**To Reproduce**

**Expected behavior**

**Environment summary**

Pipeline azure devops
Agent pool : ubuntu-latest
azcli version : 2.48.1

**Additional context**

Ex logs : 

WARNING: Readonly attribute name will be ignored in class <class 'azure.mgmt.resource.locks.v2016_09_01.models._models_py3.ManagementLockObject'>
##[error]WARNING: Readonly attribute name will be ignored in class <class 'azure.mgmt.resource.locks.v2016_09_01.models._models_py3.ManagementLockObject'>
WARNING: Readonly attribute name will be ignored in class <class 'azure.mgmt.resource.locks.v2016_09_01.models._models_py3.ManagementLockObject'>
**##[error]Script has output to stderr. Failing as failOnStdErr is set to true.**

**Comment by yonzhan** [comment] 2023-05-04 09:25
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2023-05-05 02:49
This issue is not related to https://github.com/Azure/azure-cli/issues/25406.

Duplicate of #26155.

**Closed by bebound** 2023-05-05 02:49 UTC
Labels: question, customer-reported, Installation, Auto-Assign, Azure CLI Team

**Comment by jiasli** [comment] 2023-06-14 09:54
The topic of using `failOnStderr` is tracked by https://github.com/Azure/azure-cli/issues/18372.
