### ISSUE TITLE
Credential helper error with Azure cli

### ISSUE THREAD

**Issue by Lucki9999** [Azure/azure-cli#12320] opened 2020-02-22 06:21 UTC
**Resource Provider**
mcr.microsoft.com/azure-cli

**Description of Feature or Work Requested**
This image was working fine for docker build till 3 days ago... now all of sudden it is throwing an error
ERROR: docker: WARNING! Your password will be stored unencrypted in /root/.docker/config.json.

Below error seen:
We use this image with bitbucket and 

          image: mcr.microsoft.com/azure-cli
          caches:
            - docker
          services:
            - docker
          script:
            - az acr login --name ${azure_container_name} --u ${AZURE_APP_ID} -p ${AZURE_PASSWORD}
 

Login Succeeded
ERROR: docker: WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Kindly suggest as we have to use it bitbucket pipeline...

**Comment by yonzhan** [comment] 2020-02-22 08:15
@fengzhou-msft please take a look.

**Comment by fengzhou-msft** [comment] 2020-02-22 14:32
Thanks for reporting the issue. The warning is caused by underlying docker login when running az acr login. Adding acr team to investigate.

**Comment by yugangw-msft** [comment] 2020-02-22 18:25
Please use previous version or temporary ignore this error. The rightful fix was merged to be release in the upcoming release #12282 . Sorry for the trouble.  
I am closing the issue since there are nothing else to track, and thank you @Lucki9999 for reporting this

**Closed by yugangw-msft** 2020-02-22 18:25 UTC
Labels: Container Registry, Packaging, Service Attention

**Comment by zffocussss** [comment] 2020-05-15 02:47
what is the solution? should I update az-cli?

**Comment by yugangw-msft** [comment] 2020-05-26 17:56
Please install the latest Azure CLI
