### ISSUE TITLE
az postgres up sdk docs don't mention that the extension is in preview

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#11629] opened 2019-12-20 18:11 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
_"Meaning when you run the command after looking at the SDK docs, it doesn't work.

A note about the command being in preview, and instructions for installing the needed CLI plugin need to be added.

Page: https://docs.microsoft.com/en-us/cli/azure/ext/db-up/postgres?view=azure-cli-latest#ext-db-up-az-postgres-up
"_

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

![image](https://user-images.githubusercontent.com/30876406/71280780-101d6700-2311-11ea-812b-e66a155fca20.png)

**Comment by yonzhan** [comment] 2019-12-21 12:49
add to S164.

**Comment by yonzhan** [comment] 2019-12-21 12:50
add to S164.

**Comment by Juliehzl** [comment] 2020-03-12 07:24
There are several things to be improved:
1. Preview information for commands when is_preview=True is specified in commands or commands group.
Currently it only shows up ***blue information*** when inputting `-h`.

2. Show up commands belonging to extension and need additional step to install it.
Current generated doc structure is as follows:
![image](https://user-images.githubusercontent.com/49508232/76495874-b9887a80-6472-11ea-8db5-9f2c8fa1b42e.png)

Although we already group all commands in extension with left directory structure, it is a little hard for customers to know these commands belong to parent extensions not main cli.

In addition, even in main page for db-up, there is no install instruction.
![image](https://user-images.githubusercontent.com/49508232/76496071-2c91f100-6473-11ea-8cc9-60870f416b85.png)

3. No extension Preview information shown up. 
We have preview metadata for the extension in https://github.com/Azure/azure-cli-extensions/blob/master/src/index.json#L1128 and when inputting the commands in such extension with `-h`,  the following **_yellow information_** will show up：
![image](https://user-images.githubusercontent.com/49508232/76496291-ac1fc000-6473-11ea-809f-9dd158ad98ef.png)

But there is no such information in doc page.

Finally, it should be noted that all these docs information is automatically generated according to _help.py without  manual intervention. 

Potential solution:
1. Get Preview information and extension warning information in azure-cli-core, and transform to special tags which can be resolved by docs team.
    - Commands from cli and extension will show up mixed. Should we combine  preview kwargs and extension metadata preview information to one Preview format in docs?
    - extension generator and cli generator are two ways for docs team. For extension commands, they may have both extension preview metadata and Preview kwargs. Should we make extension metadata override Preview kwargs?
    - When command group is Preview, we should make sure all commands inside the group have the Preview flag in docs. Considering how? 
2. Add related extension information in command page and find a way to add install instruction.

**Comment by Juliehzl** [comment] 2020-03-12 07:26
For Preview kwargs part, it is dupe of #11923.

**Comment by nachoalonsoportillo** [comment] 2024-07-04 21:52
@chenlomis Thanks for having created this issue. All the problems listed in this issue are resolved now.

**Comment by nachoalonsoportillo** [comment] 2024-07-04 21:52
@yonzhan Please, proceed to close this issue. Thanks!

**Closed** 2024-07-04 23:45 UTC
Labels: Documentation, PostgreSQL, feature-request
