### ISSUE TITLE
Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

### ISSUE THREAD

**Issue by NeilCondon** [Azure/azure-cli#24703] opened 2022-11-21 18:58 UTC
This issue has arisen after my company was migrated from one Azure tenant to another.   When using the Azure CLI to log in to the new tenant, this error is produced.

**Comment by yonzhan** [comment] 2022-11-22 01:02
@jiasli for awareness

**Comment by bebound** [comment] 2022-12-19 06:08
Duplicate of #20168

**Closed by bebound** 2022-12-19 06:08 UTC
Labels: Account, customer-reported, feature-request, Azure CLI Team
