### ISSUE TITLE
Verifying the role assignments of a system-managed policy identity requires case changes

### ISSUE THREAD

**Issue by cgordoncarroll** [Azure/azure-cli#14037] opened 2020-06-19 21:52 UTC
## Describe the bug
There is an outstanding bug in the Azure Policy Assignment API Here: https://github.com/Azure/azure-powershell/issues/10196

This requires a user to manually assign permissions to a system-generated identity via a workaround (either Powershell or AZ Cli). When I retrieve the `roleDefinitionIds` from a policy definition to ensure that the workaround was successful, I have to change `microsoft.authorization` in the role identifier in order for the `az role assignment list` command to work.

**Command Name**
`az policy definition show` and `az role assignment list`

**Errors:**
Returns an empty list of role assignments erroneously.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- ```az policy definition show --name <name> --scope <scope>```
Take the `roleDefinitionIDs` from `policyRule.then.details.roleDefinitionId`.

- ```az role assignment list --assignee <uuid> --scope /subscriptions/<sub_id> --role /subscriptions/<sub_id>/providers/microsoft.authorization/roleDefinitions/<role_id>```
- Returns : ```[]```
- Change `microsoft.authorization` to `Microsoft.Authorization`
- ```az role assignment list --assignee <uuid> --scope /subscriptions/<sub_id> --role /subscriptions/<sub_id>/providers/Microsoft.Authorization/roleDefinitions/<role_id>```
- Returns: ```[{<role_assignment_object>}```

## Expected Behavior
That the role definition returned by an azure CLI call can be used in a subsequent azure CLI call without the need for transformation.

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.6.0 *

```

**Comment by yonzhan** [comment] 2020-06-19 23:06
add to S172

**Comment by zhoxing-ms** [comment] 2020-07-30 10:03
@cgordoncarroll  Hi, this is due to the inconsistency case of the ResourceType name, which is case-sensitive by design, so `microsoft.authorization` is not a valid ResourceType.
May I ask why do you use the all-lowercase name of ResourceType?

**Comment by yonzhan** [comment] 2020-08-01 03:25
@cgordoncarroll  any update?

**Comment by zhoxing-ms** [comment] 2020-08-11 02:04
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Closed by zhoxing-ms** 2020-08-11 02:04 UTC
Labels: ARM, Feature Request, OKR3.2 Candidate, Policy, RBAC
