### ISSUE TITLE
Error while following the "Host a web application with Azure App service" tutorial

### ISSUE THREAD

**Issue by niklasstich** [Azure/azure-cli#11208] opened 2019-11-13 19:42 UTC
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/custom.py, ln 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
cli/command_modules/appservice/custom.py, ln 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
cli/command_modules/appservice/utils.py, ln 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Following the tutorial at https://docs.microsoft.com/en-gb/learn/modules/host-a-web-app-with-azure-app-service/6-exercise-deploy-your-code-to-app-service?pivots=csharp the error occurs after entering these commands:

-APPNAME=$(az webapp list --query [0].name --output tsv)
-APPRG=$(az webapp list --query [0].resourceGroup --output tsv)
-APPPLAN=$(az appservice plan list --query [0].name --output tsv)
-APPSKU=$(az appservice plan list --query [0].sku.name --output tsv)
-APPLOCATION=$(az appservice plan list --query [0].location --output tsv)
- az webapp up --name $APPNAME --resource-group $APPRG --plan $APPPLAN --sku $APPSKU --location "$APPLOCATION"

## Expected Behavior
The Test App deploys as outlined in the tutorial under the step "Exercise - Deploy your code to App Service"

## Actual Behavior
The error shown above occurs after entering the final command
## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```
## Additional Context
Sandbox is activated and an App Service is deployed

**Comment by niklasstich** [comment] 2019-11-13 19:44
Might be a duplicate of #11100

**Comment by fengzhou-msft** [comment] 2019-11-14 02:23
Duplicate of #11100

**Comment by panchagnula** [comment] 2019-12-27 00:32
Please upgrade to 2.0.77

**Closed by panchagnula** 2019-12-27 00:32 UTC
Labels: Service Attention, Web Apps
