### ISSUE TITLE
Bicep : Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id

### ISSUE THREAD

**Issue by sf-declanomalley** [Azure/azure-cli#23318] opened 2022-07-25 14:20 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
```
az deployment group create --resource-group %RESOURCE_GROUP% --template-file main.bicep --parameters parameters\main.parameters.json --debug
```
**Describe the bug**
receive the following message on deployment
```
{'code': 'InvalidValuesForRequestParameters', 'target': 'sf1devopsportalsa', 'message': 'Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset'}
az_command_data_logger: {'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'main' is not valid according to the validation procedure. The tracking id is 'd9a06ae0-4e9d-493b-9ee1-f77a834ca55a'. See inner errors for details."}
```

**To Reproduce**
```
 resource stateStorageAccount 'Microsoft.Storage/storageAccounts@2021-09-01' = {
  name: StorageAccountName
  location: rgLocation
  sku: {
    name: storageAccountSku
  }
  kind: 'StorageV2'
  properties:{
    networkAcls: {
      defaultAction: 'Deny'
      bypass: 'AzureServices'
      virtualNetworkRules: [
        {
          id:virtualNetwork.properties.subnets[0].id
        }
        {
          id:virtualNetwork.properties.subnets[1].id
        }        
      ]
    }
  }
}
```
**Expected behavior**
table storage account to be created with network access disabled by default with access through the 2 subnets defined earlier within the virtualnetwork resource definition

**Environment summary**
```
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\domalley\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**
the same configuration works for keyvault
```
 resource keyVault 'Microsoft.KeyVault/vaults@2019-09-01' = {
  name: keyVaultName
  location: rgLocation
  tags: tags
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: subscription().tenantId
    enableSoftDelete: true
    enabledForTemplateDeployment: true
    createMode: keyVaultCreateMode
    accessPolicies:[
      
    ]
    networkAcls:{
      defaultAction:'Deny'
      bypass:'AzureServices'
      virtualNetworkRules: [
        {
          id:virtualNetwork.properties.subnets[0].id
        }
        {
          id:virtualNetwork.properties.subnets[1].id
        }        
      ]
    }

  }
}
```

**Comment by yonzhan** [comment] 2022-07-25 22:27
route to CXP team

**Comment by navba-MSFT** [comment] 2022-07-26 03:27
@sf-declanomalley Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-07-26 05:38
@sf-declanomalley Could you please provide the action in your template as shown below ?

>"virtualNetworkRules": [
                               {
                                 "id": "[parameters('subnetId')]",
                                 **"action": "Allow"**
                               }
                               
Refer the sample bicep template for the Storage Account [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?tabs=bicep#template-format). Please let me know if this helps. Awaiting your reply.

**Comment by sf-declanomalley** [comment] 2022-07-26 10:28
virtual network resource below 
```
resource virtualNetwork 'Microsoft.Network/virtualNetworks@2021-08-01' = {
  name: virtualNetworkName
  location: rgLocation
  properties: {
    addressSpace: {
      addressPrefixes: [
        '10.1.0.0/16'
      ]
    }
    subnets: [
      {
        name: appPortalSubnetName
        properties: {
          addressPrefix: '10.1.0.0/21'
          delegations:[
            {
              name:'Microsoft.Web.serverFarms'
              properties:{
                serviceName:'Microsoft.Web/serverFarms'
              }
            }
          ]
          serviceEndpoints:[
            {
              service: 'Microsoft.KeyVault'
              locations: [
                '*'
              ]
            }
            {
              service: 'Microsoft.Storage'
              locations: [
                '*'
              ]
            }            
          ]
        }
      }
      {
        name: internalSubnetName
        properties:{
          addressPrefix: '10.1.8.0/21'
          serviceEndpoints:[
            {
              service: 'Microsoft.KeyVault'
              locations: [
                '*'
              ]
            }
            {
              service: 'Microsoft.Storage'
              locations: [
                '*'
              ]
            }
          ]          
        }
      }
    ]

  }
}
```

**Comment by navba-MSFT** [comment] 2022-07-26 10:33
@sf-declanomalley Could you confirm if you have tested using the [above](https://github.com/Azure/azure-cli/issues/23318#issuecomment-1195027293) plan? Did that help?

**Comment by sf-declanomalley** [comment] 2022-07-26 10:34
just to add to this , I've found a workaround. I have moved the creation of the storageAccount into a module passing in the virtual network as a parameter , that works. it doesn't if the same definition exists in main.bicep
```

```

> @sf-declanomalley Could you please provide the action in your template as shown below ?
> 
> > "virtualNetworkRules": [
> > {
> > "id": "[parameters('subnetId')]",
> > **"action": "Allow"**
> > }
> 
> Refer the sample bicep template for the Storage Account [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?tabs=bicep#template-format). Please let me know if this helps. Awaiting your reply.

I tried adding "action" previously. the same error is returned
```
Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset
```

**Comment by navba-MSFT** [comment] 2022-07-26 12:22
@sf-declanomalley Thanks for getting back and sharing the update. I had used the sample bicep available here:
[vnet.bicep](https://gist.githubusercontent.com/Jeroen-VdB/1cdf6995022b5391969d67f9e906a620/raw/cdbd7f5927c6c6352ac789a8e72cd61a040257da/vnet.bicep), [Main.bicep](https://gist.githubusercontent.com/Jeroen-VdB/1cdf6995022b5391969d67f9e906a620/raw/cdbd7f5927c6c6352ac789a8e72cd61a040257da/main.bicep),[storage-account.bicep](https://gist.githubusercontent.com/Jeroen-VdB/1cdf6995022b5391969d67f9e906a620/raw/cdbd7f5927c6c6352ac789a8e72cd61a040257da/storage-account.bicep) and that worked. Could you refer this sample and check if that helps ?

**Comment by sf-declanomalley** [comment] 2022-07-26 14:04
hi @navba-MSFT , thanks for the above approach. That is how I managed to workaround the issue in the end. 
> just to add to this , I've found a workaround. I have moved the creation of the storageAccount into a module passing in the virtual network as a parameter , that works. it doesn't if the same definition exists in main.bicep

Is this however the expected behaviour? if so is there any documentation that explains why the same approach doesn't work when deploying difference resources ?

please see the 2 attached main.bicep files. one deploying keyvault, one deploying tablestorage. both have the configuration. keyvault deploys but tablestorage doesn't.
[main.bicep](https://github.com/Azure/azure-cli/files/9190468/main.txt) (storage)

[main.bicep](https://github.com/Azure/azure-cli/files/9190478/main.txt) (keyvault)

**Comment by navba-MSFT** [comment] 2022-08-03 04:39
@sf-declanomalley Thanks for getting back. I can repro the below error by running `az deployment group validate -f main.bicep --resource-group My-test `with main.bicep shared by you.

>{"code": "InvalidValuesForRequestParameters", "target": "XXXXprefixdev", "message": "Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - [https://aka.ms/storagenetworkruleset]

I am working with the Bicep Product Owners to identify the cause. I will keep you posted on this.

**Comment by navba-MSFT** [comment] 2022-08-10 03:19
@sf-declanomalley Apologies for the delay in getting back. The Bicep team is now checking with the Storage RP team and awaiting their reply.

**Comment by navba-MSFT** [comment] 2022-08-24 03:39
@sf-declanomalley We appreciate your patience on this. We have created a workitem to internally track this bug and fix it. We have no ETA on when this will be fixed. We will update you once the fix is released. Since the [above](https://github.com/Azure/azure-cli/issues/23318#issuecomment-1195413427) workaround is in place we will proceed with the archival of this thread. Feel free to get back to us if you have any follow-up queries.

**Closed by navba-MSFT** 2022-08-24 03:39 UTC
Labels: bug, Storage, ARM, customer-reported, CXP Attention, Auto-Assign
