### ISSUE TITLE
Load Balancer Inbound NAT Rule CLI

### ISSUE THREAD

**Issue by mahipdeora** [Azure/azure-cli#24722] opened 2022-11-23 18:19 UTC
### Related command

az network lb inbound-nat-rule update

### Resource Provider

Microsoft.Network/loadBalancers

### Description of Feature or Work Requested

1. Currently, portal allows users to update the backend pool used by the inbound NAT rule v2. However, CLI currently lacks this feature. The feature request is to add a parameter (e.g. --backend-pool) that allows a user to update/change the backend pool used by their NAT rules

2. The current documentation for az network lb inbound-nat-rule update has a few bugs. The doc lists all the parameters as optional, but this is false. The resource group, LB name, and rule name are all required. 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/110857524/203617449-ffb3a19c-2d88-4c8e-85fe-4ef3a36264ee.png">

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A

### Target Date

2023-01-02

**Comment by yonzhan** [comment] 2022-11-23 22:55
@necusjz for awareness

**Comment by necusjz** [comment] 2022-11-30 03:06
As bandwidth limited, we have to plan this feature to **the sprint after the next sprint** (will be released around Feb 2023).

For your second question, `--resource-group`, `--lb-name` and `--name` are optional when `--ids` is provided.

**Comment by mahipdeora** [comment] 2022-11-30 18:20
Hi @necusjz, Feb 2023 sounds good to me. On the second point, I would like to have parity with our other CLI docs where we state that --rg, --lb-name, and -name are required. Maybe we can state either the ID or the other 3 items is required?

**Comment by necusjz** [comment] 2022-12-01 04:00
@mahipdeora Unfortunately, it's by design, we can see similar case in `az network lb outbound-rule update`.

https://learn.microsoft.com/en-us/cli/azure/network/lb/outbound-rule?view=azure-cli-latest#az-network-lb-outbound-rule-update

**Comment by mahipdeora** [comment] 2023-01-17 18:27
hi @necusjz, happy new year. Just wanted to ping you on this CLI. Are we still on track for a feb 2023 release?

**Comment by necusjz** [comment] 2023-01-18 01:43
> hi @necusjz, happy new year. Just wanted to ping you on this CLI. Are we still on track for a feb 2023 release?

@mahipdeora Yes, it is.

**Closed** 2023-01-29 07:18 UTC
Labels: Network, feature-request, Auto-Assign, Azure CLI Team

**Comment by mahipdeora** [comment] 2023-01-30 18:25
Thank you for your help on this. Do you know when this will roll out and will the docs be updated by your team?

**Comment by necusjz** [comment] 2023-01-31 02:09
> Thank you for your help on this. Do you know when this will roll out and will the docs be updated by your team?

Around 02/07/2023.
