### ISSUE TITLE
az storage blob now (2.19) requires login even if connection-string is provided

### ISSUE THREAD

**Issue by lbesson** [Azure/azure-cli#16872] opened 2021-02-09 12:07 UTC
**Describe the bug**
Since version 2.19, the cli requires a login when using az storage blob, even if a connection string is provided.
This was ok in 2.18

**To Reproduce**
For example the following command
```
az storage blob sync \
  --container $CONTAINER \
  --source $SOURCE \
  --destination $DEST \
  --connection-string $CONNECTION_STRING
```
will output:
`This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Please run 'az login' to setup account.`

**Expected behavior**
Login shouldn't be required.

**Environment summary**
Installed via apt-get on a debian

**Comment by yonzhan** [comment] 2021-02-09 14:29
storage

**Comment by EyuelDK** [comment] 2021-02-09 17:13
I can confirm - same issue broke my ci/cd pipeline. 
"Fixed" it by downgrading back to 2.18.
The CLI must have just broke today probably when they pushed an update 
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#february-09-2021

**Comment by jdedwards3** [comment] 2021-02-09 22:30
With login provided using az login the az storage blob sync is showing an error regarding MSI authentication. I am using it within Github actions, and it was working as of last week. Please let me know if this should be a separate issue, although it seems to be related.

**Comment by MitchReidNZ** [comment] 2021-02-10 01:29
I have the same issue as @jdedwards3 - also 'fixed' by rolling back to 2.18

**Comment by Juliehzl** [comment] 2021-02-10 01:31
Hi all, I could reproduce your scenario.
As mentioned above, it could be fixed with rolling back to 2.18.0. And we will do a fix in new version, too.

**Comment by Juliehzl** [comment] 2021-02-10 06:34
Another workaround is that you could just run `az login`, and then we will still use your input account key or connection string for the following credential. You could skip the exception then.

**Comment by Juliehzl** [comment] 2021-02-10 06:43
> With login provided using az login the 'az storage blob sync' is showing an error regarding MSI authentication. I am using it within Github actions, and it was working as of last week. Please let me know if this should be a separate issue, although it seems to be related.

Hi @jdedwards3, if you are not login in, you will get the same issue. You could login first to skip it and then use account key or connection string in your command.

**Comment by jdedwards3** [comment] 2021-02-12 18:05
@Juliehzl I am using az login as and the msi error is occurring

**Closed** 2021-02-19 07:54 UTC
Labels: OKR3.2 Candidate, Storage, feature-request

**Comment by Juliehzl** [comment] 2021-02-19 07:58
There are edge builds with fix available now. Could you try to install edge builds according to https://github.com/Azure/azure-cli#edge-builds and try again?

**Comment by CasperJ** [comment] 2021-02-28 21:20
FYI: As a temp fix, I have put this at the top of my Azure DevOps Pipelines:

```bash
# Downgrade AZ CLI because of this bug: https://github.com/Azure/azure-cli/issues/16872
sudo apt install -y --allow-downgrades azure-cli=2.18.0-1~bionic
```

Thanks to: https://stackoverflow.com/a/61215035/1684235
