### ISSUE TITLE
az login gives error sayign tis readonly file system

### ISSUE THREAD

**Issue by goldentigerindia** [Azure/azure-cli#15369] opened 2020-09-30 15:13 UTC
## Describe the bug

**Command Name**
``

**Errors:**
geeth@Azure:~$ az login
UnexpectedError: The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/geeth/.azure/commands/2020-09-30.15-10-21.login.331.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 511, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 86, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 108, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/geeth/.azure/commands/2020-09-30.15-10-21.login.331.log'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1095-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.12.0 *

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment] 2020-09-30 16:32
add to S177

**Comment by jiasli** [comment] 2022-07-26 06:04
Duplicate of #13855

**Closed** 2022-07-26 06:55 UTC
Labels: Account, feature-request
