### ISSUE TITLE
az aks browse is failed when using VPN

### ISSUE THREAD

**Issue by heavenwing** [Azure/azure-cli#9691] opened 2019-06-16 03:51 UTC
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05EB7E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
pip-install-oxpg5sa3\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
urllib3\urllib3\util\connection.py, ln 70, in create_connection
...
pip-install-ygnynjtx\requests\requests\adapters.py, ln 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05EB7E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66

```

**Comment by ts46235** [comment] 2019-07-02 15:22
Getting same error using 2.0.59
win 10 version 1709
```
PS C:\app> az aks browse -g ****** -n **********
Merged "FngVstsKubernetesService" as current context in C:\Users\*******\AppData\Local\Temp\tmp5i2qy3em
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
Error: unknown flag: --address


Examples:
  # Listen on ports 5000 and 6000 locally, forwarding data to/from ports 5000 and 6000 in the pod
  kubectl port-forward pod/mypod 5000 6000

  # Listen on ports 5000 and 6000 locally, forwarding data to/from ports 5000 and 6000 in a pod selected by the deployment
  kubectl port-forward deployment/mydeployment 5000 6000

  # Listen on port 8888 locally, forwarding to 5000 in the pod
  kubectl port-forward pod/mypod 8888:5000

  # Listen on a random port locally, forwarding to 5000 in the pod
  kubectl port-forward pod/mypod :5000

Options:
      --pod-running-timeout=1m0s: The length of time (like 5s, 2m, or 3h, higher than zero) to wait until at least one pod is running

Usage:
  kubectl port-forward TYPE/NAME [LOCAL_PORT:]REMOTE_PORT [...[LOCAL_PORT_N:]REMOTE_PORT_N] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

unknown flag: --address
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07773A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\util\connection.py", line 80, in create_connection
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\util\connection.py", line 70, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 354, in _make_request
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connection.py", line 181, in connect
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x07773A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\util\retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07773A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 386, in _run_jobs_serially
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\six\six.py", line 693, in reraise
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 356, in _run_job
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\__init__.py", line 452, in default_command_handler
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-acs\azure\cli\command_modules\acs\custom.py", line 1409, in aks_browse
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\api.py", line 116, in post
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\api.py", line 60, in request
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07773A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))```

**Comment by ts46235** [comment] 2019-07-02 16:53
Mine turned out to be related to an older version of kubectl. I upgraded it (and placed its path above docker's kubectl location in my sys path) and that fixed it. 

It was related to `unknown flag: --address`

**Comment by seanmck** [comment] 2019-07-14 07:10
Duplicate of #7686

**Closed by seanmck** 2019-07-14 07:10 UTC
Labels: AKS, Needs Triage
