### ISSUE TITLE
`az` does not complete, it would seem as if it does not return properly

### ISSUE THREAD

**Issue by leidegre** [Azure/azure-cli#6436] opened 2018-05-25 10:06 UTC
**Describe the bug**
This is a theory, not something I can confirm completely but I was running some Azure CLI commands from home and they would take forever, to complete, like 10-30 minutes (or not at all). We use Azure CLI as part of our VSTS deployment process as well, and right now they don't complete at all, they get stuck on the Azure CLI commands.

**To Reproduce**
N/A looking for more information or help on the subject matter

**Expected behavior**
Azure CLI should return within a few seconds the expected response

**Environment summary**
MSI Windows 10 and Hosted 2017, build agents in VSTS/Azure

**Additional context**
This started when I upgraded to the most recent version. I don't know exactly what version of Azure CLI tooling is running in VSTS but everything broke down starting yesterday.

**Comment by sseveringhaus-newclassrooms** [comment] 2018-05-25 19:51
This started happening for us on our CI platform a couple of weeks ago, though we have _not_ updated our Azure CLI recently (currently 2.0.27 on a Windows server of some kind). Hangs seem to happen randomly with low probability (less than 1% of calls, I'd estimate) for az login, az account set, az webapp stop, and az webapp start. Hangs are apparently indefinite--at least dozens of hours. I'm considering trying to run some of these in a loop with `--debug` to see if I can catch in the act, but it hasn't been a priority so far.

**Comment by leidegre** [comment] 2018-05-26 06:05
As the only cross platform tooling for Azure that is easy enough to integrate into other tools, the reliability and performance of Azure CLI tooling is paramount. I have attempted to recreate the issue by running all of the commands involved in our deployment process in isolation, in separate VSTS tasks (since this is where the issue was most noticeable) but I haven't had any issues as of last night.

I would very much appreciate if we could root cause this, or keep tracking this issue as it may portray to some Azure issue. There was an event with respect to VSTS that may have coincided with our issues but I [fail](https://blogs.msdn.microsoft.com/vsoservice/?p=16875) to see how these are related, the dates don't line up. Anyway, putting it here for now.

**Comment by leidegre** [comment] 2018-05-28 12:30
I think I've found the issue

~~~
2018-05-25T11:51:29.1136719Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription Pay-As-You-Go"
2018-05-25T17:50:34.5144881Z ##[error]The operation was canceled.
2018-05-25T17:50:34.5166559Z ##[section]Finishing: Azure CLI 
~~~

The time differential here is 6 hours. It's somehow waiting over 6 hours to complete `account set`...

**Comment by troydai** [comment] 2018-05-29 23:01
This is likely the telemetry issue. https://github.com/Azure/azure-cli/issues/6265

The release 2.0.33 should have a mitigation which will timeout the telemetry after 10 seconds. The root cause is the Application Insight misbehave recently. @leidegre can you update your Azure CLI?

And if the issue still persists, you can disable the telemetry.

**Comment by leidegre** [comment] 2018-05-31 08:06
@troydai @tjprescott 

I managed to get the following information from logs that where not obvious at first

~~~
2018-05-31T07:52:58.0103591Z Tessin Azure Deployment Utility [Version 3/22/2018 1:27:25 PM +00:00]
2018-05-31T07:53:00.5087882Z Info: getting web apps for 'TessinDev'...
2018-05-31T07:53:10.7559378Z Info: getting deployment slots for 'tessin-dev-web-node-ukb3ep7yw254y'...
2018-05-31T07:58:37.3509454Z ERROR: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/1c4992c2-c303-4972-8122-8d3a28201cd9/resourceGroups/TessinDev/providers/Microsoft.Web/sites/tessin-dev-web-node-ukb3ep7yw254y/slots?api-version=2016-08-01 (Caused by ResponseError('too many 504 error responses',))
2018-05-31T07:58:37.3510497Z Traceback (most recent call last):
2018-05-31T07:58:37.3510902Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 440, in send
2018-05-31T07:58:37.3511195Z     timeout=timeout
2018-05-31T07:58:37.3511531Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
2018-05-31T07:58:37.3512012Z     body_pos=body_pos, **response_kw)
2018-05-31T07:58:37.3512310Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
2018-05-31T07:58:37.3512624Z     body_pos=body_pos, **response_kw)
2018-05-31T07:58:37.3512919Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
2018-05-31T07:58:37.3513750Z     body_pos=body_pos, **response_kw)
2018-05-31T07:58:37.3514179Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 712, in urlopen
2018-05-31T07:58:37.3533936Z     retries = retries.increment(method, url, response=response, _pool=self)
2018-05-31T07:58:37.3534320Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\retry.py", line 388, in increment
2018-05-31T07:58:37.3534841Z     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2018-05-31T07:58:37.3535482Z urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/1c4992c2-c303-4972-8122-8d3a28201cd9/resourceGroups/TessinDev/providers/Microsoft.Web/sites/tessin-dev-web-node-ukb3ep7yw254y/slots?api-version=2016-08-01 (Caused by ResponseError('too many 504 error responses',))
2018-05-31T07:58:37.3535943Z 
2018-05-31T07:58:37.3536203Z During handling of the above exception, another exception occurred:
2018-05-31T07:58:37.3536531Z 
2018-05-31T07:58:37.3536724Z Traceback (most recent call last):
2018-05-31T07:58:37.3537008Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\service_client.py", line 257, in send
2018-05-31T07:58:37.3537457Z     **kwargs)
2018-05-31T07:58:37.3538123Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 508, in request
2018-05-31T07:58:37.3538427Z     resp = self.send(prep, **send_kwargs)
2018-05-31T07:58:37.3538887Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 618, in send
2018-05-31T07:58:37.3539153Z     r = adapter.send(request, **kwargs)
2018-05-31T07:58:37.3539443Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 499, in send
2018-05-31T07:58:37.3539709Z     raise RetryError(e, request=request)
2018-05-31T07:58:37.3540182Z requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/1c4992c2-c303-4972-8122-8d3a28201cd9/resourceGroups/TessinDev/providers/Microsoft.Web/sites/tessin-dev-web-node-ukb3ep7yw254y/slots?api-version=2016-08-01 (Caused by ResponseError('too many 504 error responses',))
2018-05-31T07:58:37.3540716Z 
2018-05-31T07:58:37.3540939Z During handling of the above exception, another exception occurred:
2018-05-31T07:58:37.3541081Z 
2018-05-31T07:58:37.3541244Z Traceback (most recent call last):
2018-05-31T07:58:37.3541701Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
2018-05-31T07:58:37.3542691Z     cmd_result = self.invocation.execute(args)
2018-05-31T07:58:37.3543438Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 332, in execute
2018-05-31T07:58:37.3543784Z     six.reraise(*sys.exc_info())
2018-05-31T07:58:37.3544102Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
2018-05-31T07:58:37.3544373Z     raise value
2018-05-31T07:58:37.3544711Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 306, in execute
2018-05-31T07:58:37.3545071Z     result = cmd(params)
2018-05-31T07:58:37.3545423Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 167, in __call__
2018-05-31T07:58:37.3545792Z     return super(AzCliCommand, self).__call__(*args, **kwargs)
2018-05-31T07:58:37.3546123Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
2018-05-31T07:58:37.3546810Z     return self.handler(*args, **kwargs)
2018-05-31T07:58:37.3547093Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
2018-05-31T07:58:37.3547563Z     result = op(**command_args)
2018-05-31T07:58:37.3548163Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\appservice\custom.py", line 1263, in list_slots
2018-05-31T07:58:37.3548924Z     slots = list(client.web_apps.list_slots(resource_group_name, webapp))
2018-05-31T07:58:37.3549419Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\paging.py", line 121, in __next__
2018-05-31T07:58:37.3550055Z     self.advance_page()
2018-05-31T07:58:37.3550541Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\paging.py", line 107, in advance_page
2018-05-31T07:58:37.3550852Z     self._response = self._get_next(self.next_link)
2018-05-31T07:58:37.3551551Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\web\operations\web_apps_operations.py", line 9796, in internal_paging
2018-05-31T07:58:37.3552138Z     request, header_parameters, stream=False, **operation_config)
2018-05-31T07:58:37.3552634Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\service_client.py", line 290, in send
2018-05-31T07:58:37.3553517Z     raise_with_traceback(ClientRequestError, msg, err)
2018-05-31T07:58:37.3553856Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\exceptions.py", line 45, in raise_with_traceback
2018-05-31T07:58:37.3554214Z     raise error.with_traceback(exc_traceback)
2018-05-31T07:58:37.3554532Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\service_client.py", line 257, in send
2018-05-31T07:58:37.3555225Z     **kwargs)
2018-05-31T07:58:37.3555701Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 508, in request
2018-05-31T07:58:37.3556657Z     resp = self.send(prep, **send_kwargs)
2018-05-31T07:58:37.3557737Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 618, in send
2018-05-31T07:58:37.3558619Z     r = adapter.send(request, **kwargs)
2018-05-31T07:58:37.3559116Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 499, in send
2018-05-31T07:58:37.3559983Z     raise RetryError(e, request=request)
2018-05-31T07:58:37.3560838Z msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/1c4992c2-c303-4972-8122-8d3a28201cd9/resourceGroups/TessinDev/providers/Microsoft.Web/sites/tessin-dev-web-node-ukb3ep7yw254y/slots?api-version=2016-08-01 (Caused by ResponseError('too many 504 error responses',))
~~~

**Comment by leidegre** [comment] 2018-05-31 08:11
> The release 2.0.33 should have a mitigation which will timeout the telemetry after 10 seconds. The root cause is the Application Insight misbehave recently. @leidegre can you update your Azure CLI?

The issue is happening in the VSTS Azure CLI 2.0 task, I don't think I have any control over which version of the Azure CLI 2.0 tooling is running. I attempting to set `AZURE_CORE_COLLECT_TELEMETRY=False` as a workaround.

**Comment by leidegre** [comment] 2018-05-31 10:42
Right now, this might be related to a Azure service outage related to App Service infrastructure

https://twitter.com/AzureSupport/status/1002110193138847745

**Comment by troydai** [comment] 2018-05-31 16:19
@leidegre 

Thank you for the logs. you're right this is a management service endpoint misbehave and it is not related to the telemetry upload process. if that's the case, disable telemetry will not help. This may be an issue irrelevant to the initial problem you registered.

I still believe the first issue you observed (6 hours hang for account set command) was caused by the telemetry upload process. And the hanging as far as I can tell impact Windows box specifically because of the processes fork mechanism difference. This PR (https://github.com/Azure/azure-cli/pull/6345) fixed the mechanism.

Overall you should be able to disable telemetry to bypass the issue, though we do hope you keep it on as telemetry data helps us to improve products.

I'm also in contact with Application Insight team regarding their progress of fixing the service. I'll keep this issue open till we can conclude from our side that the service issue is resolved.

**Comment by leidegre** [comment] 2018-06-01 10:55
@troydai looks OK now. I'm confident the issue has been resolved. 

I'll keep the `AZURE_CORE_COLLECT_TELEMETRY=False` flag for now.

Feel free to close this issue if you want and I'll reopen if I anything related pops up.

**Comment by troydai** [comment] 2018-06-01 15:39
Thank you. I will close this issue for now.

**Closed by troydai** 2018-06-01 15:39 UTC
Labels: Performance, telemetry
