### ISSUE TITLE
Edge Build not working with updated versioning process

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8139] opened 2019-01-02 18:42 UTC
**Describe the bug**
Without bumping core versions, the edge build seems to not publish the correct artifacts, leading to errors when trying to run off of it.

**To Reproduce**
After a release, obtain the edge build before the core versions have been bumped. Then run `vm create`. It will fail with a stack trace.

**Expected behavior**
All commands run correctly.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

install via edge build directions (essentially pip)

**Comment by tjprescott** [comment] 2019-01-02 19:48
Transferred to @marstr since it is related to other work he is doing. This should just be a matter of updating the edge build instructions once you have attached the build pipelines to PRs.

**Comment by yugangw-msft** [comment] 2019-02-13 05:46
I took a look today. A few comments here:
1. First, the PR of pinning the command module version in `azure-cli` might have already broken the edge builds. E.g. the `azure-cli-botservice==0.1.6` will not match the edge build of `azure-cli-botservice-0.1.6.dev12345` because pip won't match a release build with a dev build. I tried out the edge build instructions, pip now just pulls modules from official pypi.org, which is not right. 
2. I don't believe we should keep old edge builds, which are absolutely useless; rather, I suggest we only keep the current one. If it is broken, we fix it right way.
3. Because of the first reason, for repeatable install, I suggest the edge build should be installed from a pip file with command modules' versions pinned to the edge build, so the instruction would become
   `pip install https://azurecliprod.blob.core.windows.net/edge/pip.txt`?

@marstr @tjprescott, thoughts?

**Comment by marstr** [comment] 2019-02-13 22:14
Sorry, I thought I'd updated this thread with incremental progress earlier. Better late than never!

I do think that the problem we're having is fundamentally one about the timing of bits becoming available in PyPI vs our [PEP503 repository](https://azurecliprod.blob.core.windows.net/edge/azure-cli/) where we host our edge builds.

> 2\. I don't believe we should keep old edge builds, which are absolutely useless; rather, I suggest we only keep the current one. If it is broken, we fix it right way.

I definitely think that a retention policy would be valuable. Though, I don't have strong opinions about if this is literally only keeping the latest one, or if each build is only kept for a set number of days.

> 1\. First, the PR of pinning the command module version in `azure-cli` might have already broken the edge builds. E.g. the `azure-cli-botservice==0.1.6` will not match the edge build of `azure-cli-botservice-0.1.6.dev12345` because pip won't match a release build with a dev build. I tried out the edge build instructions, pip now just pulls modules from official pypi.org, which is not right.
> ...
> 3\. Because of the first reason, for repeatable install, I suggest the edge build should be installed from a pip file with command modules' versions pinned to the edge build, so the instruction would become
`pip install https://azurecliprod.blob.core.windows.net/edge/pip.txt`?

I really like the idea of being aggressive about pinning our dependencies, and I think that using the edge build as a way to test our strategy makes a lot of sense. I suspect that doing this pinning would fix our edge build issues, though I'm still surprised that we would be seeing a stack trace, and not just getting the most recently created build. It must mean that we're treating the core and command_modules differently for the sake of edge builds.

**Comment by yugangw-msft** [comment] 2019-02-14 01:44
> I'm still surprised that we would be seeing a stack trace, and not just getting the most recently created build

If you meant the internal report which mentioned the broken, that was because the edge installation command ended up getting the released azure-cli-core instead the on in the latest dev. Upper'ing the azure-cli & azure-cli-core versions doesn't really resolve the problem though, sure those 2 packages are getting the dev build, while the rest are still the released ones, so the new commands added by appservice teams are all missing

```bash
Successfully ... azure-cli-appservice-0.2.13 ... azure-cli-core-2.0.59.dev17766 
```
The edges builds have been probably flaky for a long long while.

**Comment by marstr** [comment] 2019-02-20 21:21
I chatted with @yugangw-msft offline a little bit about this, and I think it was productive. Basically, I think the problem that we're running into with our edge build is actually demonstrative of a general weakness surrounding reproducible builds. There have been several threads about how we'd like to tackle that problem. However, at the root of a lot of it is that `pip` is really optimized for installing libraries which naturally have looser dependency requirements*. For that reason, I'd propose that we continue to push command module definition libraries to our pip repository, but that we start utilizing our CI builds to publish edge builds for our more traditional application release channels.

For instance, the easiest one is having an edge-MSI installer. We're already building the MSI after each PR is merged. It would be simple to add a step that makes it available in our storage account alongside the latest stable build. From there we could have another aka.ms link that redirects to the edge build.

[Another example is how Docker publishes their RPMs into three different repositories](https://docs.docker.com/install/linux/docker-ce/centos/), each with a different cadence: nightly, test, and stable. Today, we only have a [stable repository](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest), but at least conceptually it wouldn't be too difficult to add a couple of more. :)

---

\* I'm not giving up on reproducible builds using `pip`, there's still lots of room for a conversation about how to pin builds, and it will need to be adopted by whatever solution we come-up with for edge builds. But I think it would be more productive to get some of this easiest stuff out of the way first.

**Closed** 2019-05-07 20:03 UTC
Labels: Packaging
