### ISSUE TITLE
az dls fs commads throwing 400 bad request error

### ISSUE THREAD

**Issue by BharathNimmala-MSFT** [Azure/azure-cli#9729] opened 2019-06-19 16:42 UTC
**Describe the bug**
When trying to run the below commands with in the cloud shell focus mode or try mode it throws 400 bad request and follow trace. 

az dls fs test --account myaccountname --path /source/test.txt
 az dls fs move --account myaccountname --destination-path /destination --source-path /source/text.txt

Following the steps in the document - https://docs.microsoft.com/en-us/cli/azure/dls/fs?view=azure-cli-latest#code-try-11

The command failed with an unexpected error. Here is the traceback:

400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 566, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 624, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 617, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 594, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 303, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 470, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/dls/custom.py", line 213,in test_adls_item
    return cf_dls_filesystem(cmd.cli_ctx, account_name).exists(path)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/dls/_client_factory.py", line 43, in cf_dls_filesystem
    url_suffix=cli_ctx.cloud.suffixes.azure_datalake_store_file_system_endpoint)
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/core.py", line 70, in __init__
    self.connect()
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/core.py", line 88, in connect
    self.azure = DatalakeRESTInterface(token=self.token, **self.kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/lib.py", line 270, in __init__
    self._check_token()  # Retryable method. Will ensure that signed_session token is current when we set it on next line
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/lib.py", line 303, in _check_token
    check_token_internal()
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/retry.py", line 108, in f_retry
    raise last_exception
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/retry.py", line 93, in f_retry
    out = func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/lib.py", line 299, in check_token_internal
    cur_session = self.token.signed_session()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 26, insigned_session
    scheme, token, _ = self._token_retriever()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 540, in _retrieve_token
    return self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 373, in _get_token_from_cloud_shell
    auth = MSIAuthentication(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

**To Reproduce**
Go to this link https://docs.microsoft.com/en-us/cli/azure/dls/fs?view=azure-cli-latest
Try out any of the move or test commands and it throws with the bad request error

az dls fs test --account myaccountname --path /source/test.txt
az dls fs move --account myaccountname --destination-path /destination --source-path /source/text.txt
 

**Expected behavior**
It should test the file exists or not and the next command should move the file from source path to destination

**Environment summary**
Trying it in the cloud shell only , with in this link - https://docs.microsoft.com/en-us/cli/azure/dls/fs?view=azure-cli-latest#code-try-11

**Additional context**
Other customers on Stack seems to experience the same thing

https://stackoverflow.com/questions/56657939/correct-syntax-on-az-dls-fs-move

**Comment by akharit** [comment] 2019-09-04 19:00
Similar to issue https://github.com/Azure/azure-cli/issues/6406. 
This seems to be by design.

**Comment by sumantmehtams** [comment] 2019-09-16 20:04
@akharit to check with @yugangw-msft and close this out.

**Closed** 2019-09-17 01:19 UTC
Labels: Data Lake Store, Service Attention
