### ISSUE TITLE
Error running az apim command

### ISSUE THREAD

**Issue by Spyntek** [Azure/azure-cli#10496] opened 2019-09-10 18:29 UTC
## Describe the bug

**Command Name**
`az apim show`

**Errors:**
```
No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
pip-install-qxmmnr17\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 523, in execute
azure\cli\core\__init__.py, ln 291, in load_arguments
cli\core\commands\__init__.py, ln 290, in load_arguments
pip-install-qxmmnr17\knack\knack\commands.py, ln 97, in load_arguments
cli\core\commands\arm.py, ln 709, in generic_show_arguments_loader
...
<frozen importlib._bootstrap_external>, ln 678, in exec_module
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
cli\command_modules\apim\custom.py, ln 9, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim show`

## Environment Summary
```
Windows-10-10.0.18975-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.72
azure-cli-iot-ext 0.7.1

Extensions:
alias 0.5.2
azure-cli-iot-ext 0.7.1
azure-devops 0.12.0
interactive 0.4.3
storage-preview 0.2.7
vm-repair 0.1.1
webapp 0.2.19

```

**Comment by jurgyy** [comment] 2019-09-16 14:57
The `custom.py` file seems to reference a file called `azure\mgmt\apimanagement\models\api_management_client_enums.py` however if we look in the `azure\mgmt\apimanagement\models` directory we see that the file is actually called `_api_management_client_enums.py`.

Removing the underscore in the filename seems to work. But in order to not break anything else I advice you to copy the file and remove the underscore from the copy, so that programs that reference the file with the underscore don't break.

Disclaimer: I'm not familiar with the source, but this is a work around until it is officially fixed. I wouldn't use this in any production environment.

@the azure team,  
In the `custom.py` file, shouldn't the line  
```python
from azure.mgmt.apimanagement.models.api_management_client_enums import VirtualNetworkType, SkuType
```
just be  
```python
from azure.mgmt.apimanagement.models import VirtualNetworkType, SkuType
```
?  
Those two classes are already exposed by the init file.

**Comment by wshamroukh** [comment] 2019-09-25 13:40
@jurgyy ,

I can't find a file called custom.py in my machine. Where do you find it?

Mine is referring to a path where it is not there at all. This user doesn't exist **C:\Users\VSSADM~1**

 `az apim show
The command failed with an unexpected error. Here is the traceback:

No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", line 523, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\__init__.py", line 291, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", line 291, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\commands.py", line 97, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\arm.py", line 709, in generic_show_arguments_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\arm.py", line 390, in get_arguments_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\__init__.py", line 528, in get_op_handler
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli\azure\cli\command_modules\apim\custom.py", line 9, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'`

**Comment by jurgyy** [comment] 2019-09-26 07:18
@wshamroukh For me it's in `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\mgmt\apimanagement\models`

**Comment by wshamroukh** [comment] 2019-09-26 07:56
> @wshamroukh I don't think you should edit the `custom.pyc` file, since it's a compiled python file, but it's file location for me is is `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\apim\`.
> 
> For the work-around you can find the `api_management_client_enums` file in `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\mgmt\apimanagement\models\`

For me not to get it working i had to have two files with the following names under `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\mgmt\apimanagement\models\`:
```
api_management_client_enums.py
_api_management_client_enums.py
```

Because when I renamed the file from **_api_management_client_enums.py** to **api_management_client_enums.py** the **__init__.py** was still looking for **_api_management_client_enums.py**

**Comment by jurgyy** [comment] 2019-09-26 09:07
Great that it works, but that's exactly what I said in my earlier comment ;)

> But in order to not break anything else I advice you to copy the file and remove the underscore from the copy, so that programs that reference the file with the underscore don't break.

**Comment by Spyntek** [comment] 2019-10-01 12:00
When should we expect a fix for this issue?

**Comment by jurgyy** [comment] 2019-11-27 13:43
@MyronFanQiu has accepted my PR and has since been moved to the release branch, right? So this issue could be marked as solved.

**Comment by MyronFanQiu** [comment] 2019-11-28 01:48
@jurgyy Yes. It's has been released. Feel free to re-open this one if you still meet problems.

**Comment by Shufflette** [comment] 2020-01-22 10:51
Same issue:
azure-cli                         2.0.80

command-modules-nspkg              2.0.3
core                              2.0.80
nspkg                              3.0.4
telemetry                          1.0.4

Used workaround above:
api_management_client_enums.py
_api_management_client_enums.py

**Comment by Ugenx** [comment] 2020-02-20 20:52
This should be re-opened, it is still an issue with the latest release. The cloud powershell shell does not seem to be affected.

**Comment by MyronFanQiu** [comment] 2020-02-21 01:56
@Ugenx I have open a PR to fix it. @jurgyy Hi. Looks like last time we didn't fix them all. I have created a PR, could you please review it and sign off?

**Closed** 2020-02-21 10:47 UTC
Labels: API Management, Service Attention

**Comment by lprichar** [comment] 2020-02-22 15:16
Yea, same as @Ugenx I'm still seeing this error in 2.1.0.  You can reproduce it with any of the following commands:

* `az apim apply-network-updates --help`
* `az apim backup --help`
* `az apim check-name --help`
* `az apim create --help`
* `az apim delete --help`
* `az apim list --help`
* `az apim show --help`
* `az apim update --help`

**Comment by MyronFanQiu** [comment] 2020-02-24 02:31
@lprichar Sure. We have fixed this one and merged a PR. The new version will be available in the next week. Currently, you can use our edge build version. https://github.com/Azure/azure-cli#edge-builds
