### ISSUE TITLE
Use pip_system_certs in place of certifi

### ISSUE THREAD

**Issue by willwh** [Azure/azure-cli#26456] opened 2023-05-16 22:43 UTC
**Related command**
This is related to any TLS verification by az cli. 

**Is your feature request related to a problem? Please describe.**
Managing certificates is very challenging in a corporate environment, the advice in https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy works, but is rather cumbersome.

**Describe the solution you'd like**
Using `pip_system_certs` would likely greatly improve the user experience by using the system certificate store, and likely reduce support requests etc related to problem like this.... just searching the issue queue with `is:issue is:open certificate` it looks like there are 105 at the time of writing.

See: [pip_system_certs](https://pypi.org/project/pip-system-certs/)

**Comment by yonzhan** [comment] 2023-05-16 22:43
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2023-05-17 05:15
This issue has been tracked by the underlying `requests` library: https://github.com/psf/requests/issues/2966

**Comment by bebound** [comment] 2023-05-17 06:59
It seems that it does not support MacOS: https://gitlab.com/alelec/pip-system-certs/-/issues/19

**Comment by jiasli** [comment] 2024-12-19 05:42
Duplicate of https://github.com/Azure/azure-cli/issues/19305

**Closed by jiasli** 2024-12-19 05:42 UTC
Labels: customer-reported, feature-request, Azure CLI Team
