### ISSUE TITLE
az keyvault create failed on cloudshell 

### ISSUE THREAD

**Issue by astapell** [Azure/azure-cli#13393] opened 2020-05-08 07:44 UTC
## Describe the bug

**Command Name**
`az keyvault create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault create --location {} --name {} --resource-group {} --sku {} --enable-soft-delete --debug`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```
## Additional Context

The same command works when executed from local desktop. Using local desktop is not an option as the command must be provided to external parties.

**Comment by yungezz** [comment] 2020-05-08 08:57
hi @astapell did you meet the error on CloudShell? If yes this is a known issue at CloudShell. You can run azure CLI locally to workaround the issue. We're following up on the issue.

**Comment by astapell** [comment] 2020-05-08 09:19
hi @yungezz  thanks for your input. I did it already but as we could not always get the credentials on behalf of the end user I'd like a solution to run from the portal. Do you think additional az login there (in cloudshell) as a workaround (which seems to work), is reliable and won't have sort of side effects?

**Comment by astapell** [comment] 2020-06-19 07:56
Hi @yungezz , the issue was gone on cloudshell for a time , I am not sure this was a result of the az (re)login command. It does now re-occurs for us since yesterday. As you were following up on the issue, can you tell me a bit more on it and if this can be a periodic issue?

**Comment by astapell** [comment] 2020-06-19 08:43
Hi @yungezz, my impression is that a certain time after first user login to cloudshell , oauth2 token expires and causes issues to some objects creation as the keyvault. Using az login again renews this token and fixes the issues for another period. Can you confirm I am correct?

**Comment by maertendMSFT** [comment] 2020-07-13 17:41
@astapell this should be fixed in Cloud Shell.  Can you see if it is fixed your your scenario?
If so, please close the issue.
If not, please provide an update here.

**Comment by richeney** [comment] 2020-08-13 15:14
I'm still seeing the error. 

Commands run in the Cloud Shell.  (Within Windows Terminal on Windows 10.)

```bash
export AZURE_DEFAULTS_LOCATION=westeurope
export AZURE_DEFAULTS_GROUP=managedIdentityLab
keyvault=msiLab$(head -c256 /dev/urandom | tr -dc "a-z0-9" | head -c 16)
az keyvault create --name $keyvault --resource-group managedIdentityLan --location westeurope
```

Looks like a token issue in Cloud Shell for this command. Extracted from the full [az.log](https://gist.github.com/richeney/fde673a3f20a386874ec9070996f579a)

```text
183 : 2020-08-13 15:02:20,699 : DEBUG : urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
183 : 2020-08-13 15:03:00,723 : DEBUG : urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 400 124
183 : 2020-08-13 15:03:00,724 : DEBUG : msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://graph.windows.net/'}
183 : 2020-08-13 15:03:00,724 : WARNING : msrestazure.azure_active_directory : MSI: Failed to retrieve a token from 'http://localhost:50342/oauth2/token' with an error of '400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token'. This could be caused by the MSI extension not yet fully provisioned.
183 : 2020-08-13 15:03:00,728 : ERROR : cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:
183 : 2020-08-13 15:03:00,728 : ERROR : cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:
183 : 2020-08-13 15:03:00,729 : ERROR : cli.azure.cli.core.util : 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

az version:

```json
{
  "azure-cli": "2.9.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.9.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```

**Comment by maertendMSFT** [comment] 2020-10-06 18:23
Can we close this as a dupe of https://github.com/Azure/azure-cli/issues/11749?

**Comment by maertendMSFT** [comment] 2020-11-20 22:51
Please close as a dupe :)

**Closed** 2020-11-21 02:24 UTC
Labels: Cloud Shell, Service Attention, customer-reported, question
