### ISSUE TITLE
HTTPSConnectionPool(host='azcliprod.blob.core.windows.net', port=443): Max retries exceeded with url: /msi/azure-cli-2.47.0.msi (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04428B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

### ISSUE THREAD

**Issue by varmav1** [Azure/azure-cli#26045] opened 2023-04-04 11:58 UTC
HTTPSConnectionPool(host='azcliprod.blob.core.windows.net', port=443): Max retries exceeded with url: /msi/azure-cli-2.47.0.msi (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04428B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -u {} -p {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0 *
```
## Additional Context

HTTPSConnectionPool(host='azcliprod.blob.core.windows.net', port=443): Max retries exceeded with url: /msi/azure-cli-2.47.0.msi (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04428B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by yonzhan** [comment] 2023-04-04 11:58
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment] 2023-04-10 03:21
The error indicates that you can't open `https://azcliprod.blob.core.windows.net/msi/azure-cli-2.47.0.msi`.
Please check your DNS/network setting. This is not a CLI error.
Duplicate of #21514

**Closed by bebound** 2023-04-10 03:21 UTC
Labels: Account, question, customer-reported, Auto-Assign, Azure CLI Team
