### ISSUE TITLE
az extension add --name azure-devops

### ISSUE THREAD

**Issue by HeydarHoseinian** [Azure/azure-cli#19140] opened 2021-08-05 19:45 UTC
## Describe the bug

**Command Name**
`az extension add`

**Errors:**
```
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /Azure/azure-devops-cli-extension/releases/download/20200401.4/azure_devops-0.18.0-py2.py3-none-any.whl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.25.0

```

**Comment by yonzhan** [comment] 2021-08-05 23:15
extension

**Comment by jiasli** [comment] 2021-08-06 06:16
Duplicate of #1572

**Closed** 2021-08-06 06:25 UTC
Labels: Extensions, customer-reported
