### ISSUE TITLE
'az webapp config appsettings set' is not configuring webapp correctly with multiple settings

### ISSUE THREAD

**Issue by rick-hayek** [Azure/azure-cli#23896] opened 2022-09-15 05:00 UTC
**Env:**

> azure-cli                         2.40.0
> 
> core                              2.40.0
> telemetry                          1.0.8
> 
> Dependencies:
> msal                            1.18.0b1
> azure-mgmt-resource             21.1.0b1
> 
> Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

**Steps:**
run powershell:
```
$settings = [System.Collections.ArrayList]@()
$settings.Add("a=b")
$settings.Add("c=d")
az webapp config appsettings set --resource-group $group --name $app --settings $settings
```

**Expected Result:**
  {
    "name": "a",
    "slotSetting": false,
    "value": "b"
  },
  {
    "name": "c",
    "slotSetting": false,
    "value": "d"
  }

**Actual Result:**
  {
    "name": "a",
    "slotSetting": false,
    **"value": "b c=d"**
  }

**Note:**
This issue is not happening on azure-cli 2.39.*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2022-09-15 08:18
route to CXP team

**Comment by berhir** [comment] 2022-09-16 08:45
We are facing the same issue. Version 2.40 is breaking our deployment pipeline. It worked fine with previous versions.

**Comment by RakeshMohanMSFT** [comment] 2022-09-17 15:27
@rick-hayek Thank you for reaching out, we are looking into it

**Comment by RakeshMohanMSFT** [comment] 2022-09-17 16:54
@rick-hayek Check if this work around helps? https://github.com/Azure/azure-cli/issues/23920#issuecomment-1249520225

**Comment by vstkamath** [comment] 2022-09-17 19:21
This issue is not just limited to resource tags. Wherever array parameters are passed, cli version 2.40.0 has regressed. Whether it is specifying the service bus access, aks zone configuration all apis are broken. Is there any solution under work? Since the DevOps pipelines are already getting the images with 2.40.0, it is a major impact for us.

**Comment by rick-hayek** [comment] 2022-09-18 14:22
> @rick-hayek Check if this work around helps? [#23920 (comment)](https://github.com/Azure/azure-cli/issues/23920#issuecomment-1249520225)

Thanks. I did not try that.

I can get things worked **_for now_** using Invoke-Expression:

```

$settings = [System.Collections.ArrayList]@()
$settings.Add("a=b")
$settings.Add("c=d")
$settingsString = [System.Collections.ArrayList]@()
$settings | Foreach {
    $value = $_.Replace("""", "") # required if your key-value is something like this: myKey="MyValue"
    $settingsString.Add("""$value""") | Out-Null;
}

$command = "az webapp config appsettings set --resource-group $group --name $app --settings $settingsString"

Invoke-Expression -Command $command

```

This solution is ugly and potentially  problematic. 
I think storing settings into a list variable could be a common scenario. appreciated if this issue can get fixed.

**Comment by jiasli** [comment] 2022-09-19 02:23
Duplicate of https://github.com/Azure/azure-cli/issues/23797

**Closed by jiasli** 2022-09-19 02:23 UTC
Labels: Web Apps, customer-reported, needs-team-attention, CXP Attention, Auto-Assign
