### ISSUE TITLE
Login error using az login for mooncake

### ISSUE THREAD

**Issue by harchawla** [Azure/azure-cli#29277] opened 2024-06-28 18:18 UTC
### Describe the bug

Used az login with device code after setting cloud to AzureChinaCloud
account used: harchawla@cme.gbl

![image](https://github.com/Azure/azure-cli/assets/95934390/6a3d2b75-0564-462d-a47e-d5254c6e3fa5)

### Related command

 az login --use-device-code

### Errors

Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

### Issue script & Debug output

Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

### Expected behavior

az logged in successfully

### Environment Summary

azure-cli                         2.30.0 *

core                              2.30.0 *
telemetry                          1.0.6 *

Extensions:
connectedk8s                       1.2.8
providerhub                        0.2.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\harchawla\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Comment by yonzhan** [comment] 2024-06-28 18:18
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment] 2024-07-01 06:48
Duplicate of #20168

**Closed by jiasli** 2024-07-01 06:48 UTC
Labels: Account, question, Upgrade, Auto-Assign, Azure CLI Team, Auto-Resolve, Similar-Issue, Possible-Solution
