### ISSUE TITLE
azure login issue.

### ISSUE THREAD

**Issue by Ashishpatel2321** [Azure/azure-cli#23316] opened 2022-07-25 07:21 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1658329330.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/d70cb4db-69c4-4a49-aaf3-f1e7ac277686/v2.0",
  "iat": 1658733287,
  "nbf": 1658733287,
  "exp": 1658737187,
  "aio": "AVQAq/8TAAAAuTLyNmFY9TECM0Pvzz3tXR9aKjH6z1aIt7BoRvLNFk3cFMqLyhjKG9zUW8GiZZv3wsE1BUWmNUdXm8Q0pAYNeCE6U4GsaZDoEwWdIaVQE9I=",
  "name": "Ashish Patel",
  "nonce": "0647a6ab8896f4edc1c01ff7d13b2992d3e34f1764895f24ccd2fb5d675f907b",
  "oid": "1e645c69-fd82-4d24-9c74-b5eab3a48cb8",
  "preferred_username": "ashishp@unifycloud.com",
  "puid": "100320012E46215D",
  "rh": "0.ARsA27QM18RpSUqq8_HnrCd2hpV3sATbjRpGu-4C-eG_e0YbAI0.",
  "sub": "7L1VweqSLmaUcGRm92lkqyZIW6sEQh5DI2g8INEZkPk",
  "tid": "d70cb4db-69c4-4a49-aaf3-f1e7ac277686",
  "uti": "H8Pub0PTpUS9k8fB04LnAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 154, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 141, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1608, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 281, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 138, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 116, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 599, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 310, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 153, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 77, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1658329330.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/d70cb4db-69c4-4a49-aaf3-f1e7ac277686/v2.0",
  "iat": 1658733287,
  "nbf": 1658733287,
  "exp": 1658737187,
  "aio": "AVQAq/8TAAAAuTLyNmFY9TECM0Pvzz3tXR9aKjH6z1aIt7BoRvLNFk3cFMqLyhjKG9zUW8GiZZv3wsE1BUWmNUdXm8Q0pAYNeCE6U4GsaZDoEwWdIaVQE9I=",
  "name": "Ashish Patel",
  "nonce": "0647a6ab8896f4edc1c01ff7d13b2992d3e34f1764895f24ccd2fb5d675f907b",
  "oid": "1e645c69-fd82-4d24-9c74-b5eab3a48cb8",
  "preferred_username": "ashishp@unifycloud.com",
  "puid": "100320012E46215D",
  "rh": "0.ARsA27QM18RpSUqq8_HnrCd2hpV3sATbjRpGu-4C-eG_e0YbAI0.",
  "sub": "7L1VweqSLmaUcGRm92lkqyZIW6sEQh5DI2g8INEZkPk",
  "tid": "d70cb4db-69c4-4a49-aaf3-f1e7ac277686",
  "uti": "H8Pub0PTpUS9k8fB04LnAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0
```

**Comment by jiasli** [comment] 2022-07-25 07:46
Duplicate of #20388

**Closed by jiasli** 2022-07-25 07:46 UTC
Labels: Account, customer-reported, Auto-Assign
