### ISSUE TITLE
Azure login

### ISSUE THREAD

**Issue by SindiswaMafilika** [Azure/azure-cli#20973] opened 2022-01-13 09:33 UTC
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1641979982.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1642066048,
  "nbf": 1642066048,
  "exp": 1642069948,
  "aio": "AYQAe/8TAAAAgyDbumaXcXuHKea2Fd1asea/INL1jbpwvYI2mUpdcLyzg7JamW3prthynBVYgrTTHu19SHEMk/ZozV3/ADEAk9ARiLaSml28IrN3B0TezVUqRCWMo1NvvXffzteR/BpwTNj/o8SKJCnT/ZziswW9PCvjPHytDB9ZAlcz04q//Iw=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "30d909366ab64136b073c167cff0a40dd33dfaa7eec2e47a9bcfdd51d71178e9",
  "preferred_username": "sindi301.sm@gmail.com",
  "prov_data": [
    {
      "at": true,
      "prov": "github.com",
      "altsecid": "94858102"
    }
  ],
  "rh": "0.AU4AMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBALo.",
  "sub": "ZrPSXMG0esr2UyUJNTgnHdxb93lEToa8GecfynV4zY8",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "Ac4pDBHKgE6EmWANAntXAg",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 171, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1641979982.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1642066048,
  "nbf": 1642066048,
  "exp": 1642069948,
  "aio": "AYQAe/8TAAAAgyDbumaXcXuHKea2Fd1asea/INL1jbpwvYI2mUpdcLyzg7JamW3prthynBVYgrTTHu19SHEMk/ZozV3/ADEAk9ARiLaSml28IrN3B0TezVUqRCWMo1NvvXffzteR/BpwTNj/o8SKJCnT/ZziswW9PCvjPHytDB9ZAlcz04q//Iw=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "30d909366ab64136b073c167cff0a40dd33dfaa7eec2e47a9bcfdd51d71178e9",
  "preferred_username": "sindi301.sm@gmail.com",
  "prov_data": [
    {
      "at": true,
      "prov": "github.com",
      "altsecid": "94858102"
    }
  ],
  "rh": "0.AU4AMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBALo.",
  "sub": "ZrPSXMG0esr2UyUJNTgnHdxb93lEToa8GecfynV4zY8",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "Ac4pDBHKgE6EmWANAntXAg",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0

Extensions:
azure-iot 0.12.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment] 2022-01-13 09:37
@jiasli for awareness

**Comment by jiasli** [comment] 2022-01-14 06:16
Duplicate of #20388

**Closed by jiasli** 2022-01-14 06:16 UTC
Labels: Account, customer-reported
