### ISSUE TITLE
Issue on sandbox while creating function 

### ISSUE THREAD

**Issue by kulomkar93** [Azure/azure-cli#17653] opened 2021-04-12 13:09 UTC
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 660, in execute
    raise ex
cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
...
python3.6/site-packages/requests/models.py, ln 897, in json
    return complexjson.loads(self.text, **kwargs)
lib/python3.6/json/__init__.py, ln 354, in loads
    return _default_decoder.decode(s)
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Linux-4.15.0-1111-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.21.0

Extensions:
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by yonzhan** [comment] 2021-04-12 14:22
route to service team

**Comment by apawast** [comment] 2021-04-22 17:50
@kulomkar93 are you able to reproduce this or was it just the one time? Could you also share your app name with us? If the issue is persisting, can you rerun the command with the --debug flag and share the output with us?

cc @gzuber

**Comment by kulomkar93** [comment] 2021-04-23 05:25
Since it was a learning  sandbox, I can neither able to reproduce it nor
give you the function name .I remember it was kulomkarfunction  It was just
happened one time.

**Comment by apawast** [comment] 2021-05-19 21:07
@kulomkar93 since we are unable to reproduce the issue, we will be closing the issue at this time.

**Closed** 2022-04-01 01:17 UTC
Labels: Service Attention, Functions
