### ISSUE TITLE
Command does not work for VM workload-type  | az backup container register --resource-group MyResourceGroup --vault-name MyVault --resource-id MyResourceId --workload-type VM--backup-management-type AzureWorkload --resource-id MyResourceID

### ISSUE THREAD

**Issue by shubhammicrosoft1** [Azure/azure-cli#11700] opened 2019-12-28 18:23 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09210de3-5f1e-a72e-286b-998275969c13
* Version Independent ID: c5f2c022-f67d-b53f-9e63-ebb9acbb22de
* Content: [az backup container](https://docs.microsoft.com/en-us/cli/azure/backup/container?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/backup/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/backup/_help.py)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by shubhammicrosoft1** [comment] 2019-12-28 18:26
Below is the log
Getting management service client client_type=RecoveryServicesBackupClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : 'VM'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 490, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_base.py", line 234, in register_wl_container
    resource_id, backup_management_type)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_wl.py", line 94, in register_wl_container
    workload_type = workload_type_map[workload_type]
KeyError: 'VM'
'VM'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 490, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_base.py", line 234, in register_wl_container
    resource_id, backup_management_type)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_wl.py", line 94, in register_wl_container
    workload_type = workload_type_map[workload_type]
KeyError: 'VM'
cli.azure.cli.core.util :

**Comment by pvrk** [comment] 2020-02-25 06:15
Apologies. Will change the help text. WorkloadType "VM" is not supported. You don't require registration for Azure VM backups.

**Comment by pvrk** [comment] 2020-02-27 13:35
Closing this issue since this is by design. Updating the help text in next release.

**Closed by pvrk** 2020-02-27 13:35 UTC
Labels: Recovery Services Backup, Service Attention
