### ISSUE TITLE
webapp:WebApp/Functionapp cannot update SlotSettings through CLI

### ISSUE THREAD

**Issue by recao** [Azure/azure-cli#9290] opened 2019-05-02 18:54 UTC
> ### Update SlotSettings through CLI 

**Describe the bug**
Cannot set SlotSettings to true/false through `az webapp config appsettings set`  or `az functionapp config appsettings set` command. 

**To Reproduce**
If a WebApp already has a non-slotsetting k1=v1 and a slotSetting k2=v2, as below: 
![image](https://user-images.githubusercontent.com/20957260/57098648-7d6f7f80-6ccf-11e9-842b-7f2ed26f73c3.png)
If an user wants to change k1 to be a slotsetting, and k2 to non-slotsetting through CLI bu running command `az webapp config appsettings set -n appname -g apprg --settings k2=v2 --slot-settings k1=v1`, it does not guarantee to set correctly. 

**Expected behavior**
With the command above, k1 should become a slotsetting, and k2 should become a non-slotsetting. 

**Environment summary**
Official Azure CLI. Same issue happens for `az functionapp config appsettings set command`.

**Additional context**
Same issue happens for `az functionapp config appsettings set command`.

**Comment by panchagnula** [comment] 2019-05-03 03:07
Currently there is no support for FunctionApp slots using CLI - this is a feature we will support with CLI @ankitkumarr , please feel free to resolve this as a duplicate of the workitem you have.

**Comment by recao** [comment] 2019-05-03 23:28
Hi @panchagnula , thanks for reply. I believe this is an open bug.  
`az webapp/function app config appsettings set` is a public CLI command, people like our team would assume it should work as --h info indicated. Currently if we modified slotSettings through this command, it would end up with an **uncertain** result without any warning/error messages, and even affects other settings without notification. This is dangerous and worse than "operation not supported" or "update failure".

**Comment by panchagnula** [comment] 2019-05-03 23:41
@recao - got it the ask is to make an existing appSetting as  slotSetting using CLI - will take a look at this.

**Comment by panchagnula** [comment] 2019-09-26 04:49
Marking this as Feature request

**Comment by panchagnula** [comment] 2019-10-17 14:03
@reaco finally got around to looking at this & noticed that this already works as expected if you run the command as follows

` az webapp config appsettings set -g myRG -n myApp --slot-settings mySetting=value`
OR
`az webapp config appsettings set -g sisirap_rg_Linux_centralus -n sisirap-reactApp --slot-settings @appsettings.json`

where my appsetings.json is as follows:
{
  "endpoints": {
       "api":"https://example.com"
    }
}

NOTE: the settings should be of format key:value looking at your original issue description looks like the JSON object is incorrect.

I am closing this with this info, please let us know if this doesn't solve your issue.

**Closed by panchagnula** 2019-10-17 14:03 UTC
Labels: App Services, Feature Request, Functions, Service Attention, Web Apps
