### ISSUE TITLE
Unable to get kube/.config with multiple masters

### ISSUE THREAD

**Issue by nerdondon** [Azure/azure-cli#2353] opened 2017-03-02 10:16 UTC
Hi,

when I run the following:
```
az group create --name=$RESOURCE_GROUP --location=$LOCATION

az acs create --orchestrator-type=kubernetes --resource-group $RESOURCE_GROUP --name=$CLUSTER_NAME --dns-prefix=$DNS_PREFIX --agent-count=$NUM_AGENTS --ssh-key-value=$SSH_PUB_KEY

az acs kubernetes get-credentials --resource-group=$RESOURCE_GROUP --name=$CLUSTER_NAME --ssh-key-file=$SSH_PRIV_KEY
```

`get-credentials` fails with: `scp: .kube/config: No such file or directory`

I tried to ssh into one of the master nodes and ~/.kube/config didn't exist. Everything was working for me when I tried a couple weeks ago and I think I tracked the issue down to PR #2210. Indeed when I create a single master cluster:
```
az acs create --orchestrator-type=kubernetes --resource-group $RESOURCE_GROUP --name=$CLUSTER_NAME --dns-prefix=$DNS_PREFIX --agent-count=$NUM_AGENTS --ssh-key-value=$SSH_PUB_KEY --master-count 1
```
A subsequent `az acs kubernetes get-credentials` call succeeds.

Briefly, I am on macOS and `az --version` shows that I am on azure-cli 2.0.0.

**Comment by brendandburns** [comment] 2017-03-10 21:53
I think that this was due to the recent outage here:

https://github.com/azure/acs/issues/9

If this re-occurs, please re-open.

**Comment by selvasingh** [comment] 2017-04-25 17:08
I am seeing the same issue today

```
bash-3.2$ az acs kubernetes get-credentials --resource-group=kubernetes-6-asir --name=containerservice-kubernetes-6-asir
scp: .kube/config: No such file or directory
Traceback (most recent call last):
  File "/Users/selvasingh/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/selvasingh/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
    result = expanded_arg.func(params)
  File "/Users/selvasingh/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 403, in _execute_command
    raise ex
SCPException: scp: .kube/config: No such file or directory
bash-3.2$ az --version
azure-cli (2.0.3)

acr (2.0.1)
acs (2.0.3)
appservice (0.1.3)
batch (2.0.1)
cloud (2.0.1)
component (2.0.1)
configure (2.0.3)
container (0.1.3)
core (2.0.3)
documentdb (0.1.3)
feedback (2.0.1)
find (0.0.2)
iot (0.1.3)
keyvault (2.0.1)
lab (0.0.2)
monitor (0.0.2)
network (2.0.3)
nspkg (2.0.0)
profile (2.0.3)
redis (0.2.0)
resource (2.0.3)
role (2.0.2)
sql (2.0.1)
storage (2.0.3)
vm (2.0.3)

Python (Darwin) 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
bash-3.2$ 
```

**Comment by selvasingh** [comment] 2017-04-25 17:13
@brendandburns this is with nightly:

```
scp: .kube/config: No such file or directory
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
    result = expanded_arg.func(params)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 404, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 399, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 692, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 713, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 43, in SecureCopy
    scp.get(src, dest)
  File "/usr/local/lib/python2.7/site-packages/scp.py", line 198, in get
    self._recv_all()
  File "/usr/local/lib/python2.7/site-packages/scp.py", line 348, in _recv_all
    raise SCPException(asunicode(msg[1:]))
SCPException: scp: .kube/config: No such file or directory
```

**Comment by brendandburns** [comment] 2017-04-25 19:05
Your cluster isn't turning up correctly, can you check and validate that the service principal is correct?

Thanks

**Comment by selvasingh** [comment] 2017-04-25 22:38
Here is how I created the cluster

```
// Create a resource group
az group create --name=kubernetes-6-asir --location=southcentralus
	
// Create a Kubernetes cluster
az acs create --orchestrator-type=kubernetes --resource-group=kubernetes-6-asir \
        --name=containerservice-kubernetes-6-asir \
        --dns-prefix=kubernetes-6-asir
```

**Comment by selvasingh** [comment] 2017-04-25 22:42
Cluster was created successfully. From CLI, logged in using that SP, I am able to list or show the cluster

**Comment by brendandburns** [comment] 2017-04-26 00:01
Can you create VMs or virtual networks?


Thanks

--brendan



________________________________

**Comment by selvasingh** [comment] 2017-04-26 00:09
Yes

**Comment by mboersma** [comment] 2018-07-25 01:10
I created a multi-master ACS cluster and was not able to reproduce this issue as described here. `az acs kubernetes get-credentials` seems to be working as advertised.

@tjprescott given this issue is 15 months old, I think we should close it.

**Closed** 2018-08-06 16:11 UTC
Labels: ACS
