### ISSUE TITLE
Permission denied: 'C:\\agent-01\\_work\\_temp\\.azclitask\\msal_token_cache.bin.lockfile'

### ISSUE THREAD

**Issue by ericgoudriaan** [Azure/azure-cli#20931] opened 2022-01-07 20:31 UTC
From Azure DevOps we use an Azure CLI task to execute a powershell script in which an access token is fetched using az account get-access-token. The access token is then used to make a call to our own API. 

This works ok most of the times, but every now and then we get the following exception: Permission denied: 'C:\\agent-01\\_work\\_temp\\.azclitask\\msal_token_cache.bin.lockfile'**. 

The following powershell script is used inside the Azure CLI task:

------------------
$audience = 'xxx'
$url = 'xxx'

$accessToken = & az account get-access-token --resource=$audience --query accessToken
$accessToken = $accessToken.Trim('"')

$headers = @{
    "Content-Type"="application/json"
    Authorization="Bearer $accessToken"
}

Invoke-WebRequest -Uri $url -Method Post -Headers $headers -UseBasicParsing
----------------

See the following entire log (removed some sensitive lines):

2021-12-19T19:07:38.6202884Z ==============================================================================
2021-12-19T19:07:38.6203151Z Task         : Azure CLI
2021-12-19T19:07:38.6203551Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
2021-12-19T19:07:38.6203938Z Version      : 2.1.2
2021-12-19T19:07:38.6204170Z Author       : Microsoft Corporation
2021-12-19T19:07:38.6204451Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2021-12-19T19:07:38.6204769Z ==============================================================================
2021-12-19T19:07:39.5811018Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2021-12-19T19:07:43.7227332Z WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
2021-12-19T19:07:43.7227729Z 
2021-12-19T19:07:43.7228002Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-12-19T19:07:43.7229107Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-12-19T19:07:43.7229662Z azure-cli                         2.30.0 *
2021-12-19T19:07:43.7229816Z 
2021-12-19T19:07:43.7230093Z core                              2.30.0 *
2021-12-19T19:07:43.7230343Z telemetry                          1.0.6
2021-12-19T19:07:43.7230483Z 
2021-12-19T19:07:43.7230733Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2021-12-19T19:07:43.7231215Z Extensions directory 'C:\Users\WEB_DEP_LSV\.azure\cliextensions'
2021-12-19T19:07:43.7231403Z 
2021-12-19T19:07:43.7231718Z Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
2021-12-19T19:07:43.7231927Z 
2021-12-19T19:07:43.7232163Z Legal docs and information: aka.ms/AzureCliLegal
2021-12-19T19:07:43.7232320Z 
2021-12-19T19:07:43.7232392Z 
2021-12-19T19:07:43.7388607Z Setting AZURE_CONFIG_DIR env variable to: C:\agent-01\_work\_temp\.azclitask
2021-12-19T19:07:43.7393705Z Setting active cloud to: AzureCloud
2021-12-19T19:07:43.7401670Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2021-12-19T19:07:53.1060535Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** "--password=***" --tenant *** --allow-no-subscriptions"
2021-12-19T19:07:55.9559946Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription 62d3d9f9-d154-4e4e-abdc-975b9394edfb"
2021-12-19T19:07:56.3152597Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\agent-01\_work\_temp\azureclitaskscript1639940859512.ps1'"
**2021-12-19T19:07:57.5298709Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-12-19T19:07:57.5300700Z ERROR: [Errno 13] Permission denied: 'C:\\agent-01\\_work\\_temp\\.azclitask\\msal_token_cache.bin.lockfile'**
2021-12-19T19:07:57.5301111Z Traceback (most recent call last):
2021-12-19T19:07:57.5301490Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
2021-12-19T19:07:57.5301963Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
2021-12-19T19:07:57.5302496Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-12-19T19:07:57.5303003Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-12-19T19:07:57.5303495Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
2021-12-19T19:07:57.5303985Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2021-12-19T19:07:57.5304546Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 74, in get_access_token
2021-12-19T19:07:57.5305045Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 382, in get_raw_token
2021-12-19T19:07:57.5305589Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line 128, in get_token
2021-12-19T19:07:57.5306082Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1589, in acquire_token_for_client
2021-12-19T19:07:57.5306777Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 735, in obtain_token_for_client
2021-12-19T19:07:57.5307256Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
2021-12-19T19:07:57.5307724Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 771, in _obtain_token
2021-12-19T19:07:57.5308166Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 523, in <lambda>
2021-12-19T19:07:57.5309052Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
2021-12-19T19:07:57.5309483Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
2021-12-19T19:07:57.5309921Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 237, in __add
2021-12-19T19:07:57.5310366Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 43, in modify
2021-12-19T19:07:57.5310834Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/cache_lock.py", line 29, in __enter__
2021-12-19T19:07:57.5311296Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/utils.py", line 199, in __enter__
2021-12-19T19:07:57.5311748Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/utils.py", line 128, in acquire
2021-12-19T19:07:57.5312206Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/utils.py", line 175, in _get_fh
2021-12-19T19:07:57.5312685Z PermissionError: [Errno 13] Permission denied: 'C:\\agent-01\\_work\\_temp\\.azclitask\\msal_token_cache.bin.lockfile'
2021-12-19T19:07:57.5531954Z To open an issue, please run: 'az feedback'
2021-12-19T19:07:57.7120197Z You cannot call a method on a null-valued expression.
2021-12-19T19:07:57.7120881Z At C:\agent-01\_work\_temp\azureclitaskscript1639940859503_inlinescript.ps1:8 
2021-12-19T19:07:57.7121199Z char:1
2021-12-19T19:07:57.7121408Z + $accessToken = $accessToken.Trim('"')
2021-12-19T19:07:57.7121671Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-12-19T19:07:57.7121996Z     + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRec 
2021-12-19T19:07:57.7122274Z    ordException
2021-12-19T19:07:57.7122523Z     + FullyQualifiedErrorId : InvokeMethodOnNull
2021-12-19T19:07:57.7122756Z  
2021-12-19T19:07:57.7366960Z ##[error]Script failed with exit code: 1
2021-12-19T19:07:57.7377966Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2021-12-19T19:07:58.2877316Z ##[section]Finishing: trigger deployment endpoint

**Comment by yonzhan** [comment] 2022-01-08 00:00
@jiasli for awareness

**Comment by jiasli** [comment] 2022-01-10 02:05
Duplicate of #20273

**Closed by jiasli** 2022-01-10 02:05 UTC
Labels: MSAL
