### ISSUE TITLE
Issue with "az aks get-credentials" command

### ISSUE THREAD

**Issue by akoval-jsp** [Azure/azure-cli#7257] opened 2018-09-08 15:20 UTC
When I try to use "az aks get-credentials" command I get the following error:
$ az aks get-credentials --resource-group "$RESOURCE_GROUP" --name "$AKS_CLUSTER_NAME" --admin
The HTTP method 'POST' is not supported.

It worked OK few days ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by brendandburns** [comment] 2018-09-19 04:31
I can not reproduce this on az cli `2.0.44`, acs `2.3.0`

What version are you running?

**Comment by sanudatta11** [comment] 2019-02-05 13:45
azure-cli (2.0.55)

acr (2.1.12)
acs (2.3.14)
advisor (2.0.0)
ams (0.3.2)
appservice (0.2.11)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.6)
billing (0.2.0)
botservice (0.1.4)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.11)
core (2.0.55)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.2.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.8)
network (2.3.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.8)
role (2.3.0)
search (0.1.1)
security (0.1.0)
servicebus (0.3.2)
servicefabric (0.1.11)
signalr (1.0.0)
sql (2.1.7)
storage (2.3.0)
telemetry (1.0.0)
vm (2.2.12)

Same issue

**Comment by jluk** [comment] 2019-12-16 23:13
I am also unable to reproduce this on latest build 2.0.77. I am going to close this given the age of the issue, but @akoval-jsp please give it a retry and if it still occurs comment and I can re-open.

**Closed by jluk** 2019-12-16 23:13 UTC
Labels: AKS, Question, Service Attention
