### ISSUE TITLE
2.30 Unable to use Table Output (mac/brew)

### ISSUE THREAD

**Issue by theharrisonchow** [Azure/azure-cli#20400] opened 2021-11-17 20:49 UTC
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Upon upgrading to 2.30 AZ CLI table outputs are unavailable.

```
az account list -o table
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```

Debug Logs
```
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.output: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 237, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 146, in out
    output = formatter(obj)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 79, in format_table
    raise CLIError("Table output unavailable. "
knack.util.CLIError: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

cli.azure.cli.core.azclierror: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
az_command_data_logger: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```

**To Reproduce**

```
brew install azure-cli
az account list -o table
```

**Expected behavior**

Human readable table output

**Environment summary**

Homebrew 3.3.4
```
az --version                                                                                                                                                                INT ✘  py39   01:47:08 pm
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.42
account                            0.2.1

Python location '/usr/local/Cellar/azure-cli/2.30.0_1/libexec/bin/python'
Extensions directory '/Users/aa/.azure/cliextensions'

Python (Darwin) 3.10.0 (default, Oct 13 2021, 06:44:31) [Clang 12.0.0 (clang-1200.0.32.29)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**

**Comment by yonzhan** [comment] 2021-11-17 23:01
@jiasli for awareness

**Comment by jiasli** [comment] 2021-11-18 02:34
Duplicate of #20348

**Closed by jiasli** 2021-11-18 02:34 UTC
Labels: Account, customer-reported
